import type { PhraseScene } from './types'

/**
 * よく使う英会話フレーズ。場面ごとに、英文・和訳・使いどころの3点セット。
 * ホームのイングバードが1つずつ紹介する。短くて丸ごと覚えられるものを優先する。
 */
export const PHRASE_SCENES: readonly PhraseScene[] = [
  {
    label: '朝のあいさつ',
    phrases: [
      ['Good morning! Did you sleep well?', 'おはよう!よく眠れた?', '朝いちばんの定番。sleep well よりやわらかい聞き方。'],
      ['Morning! How are you feeling today?', 'おはよう!今日の調子はどう?', '短い Morning! だけでも十分自然。'],
      ['It’s a beautiful morning, isn’t it?', 'いい朝だね。', '天気の話を添えると会話が始めやすい。'],
      ['I’m not a morning person.', '朝は弱いんだ。', '自分を説明するときの定番表現。'],
      ['Did you stay up late last night?', '昨夜は夜更かしした?', 'stay up late で「夜更かしする」。'],
      ['Let’s make it a good day.', 'いい1日にしよう。', '気合いを入れるときのひと言。'],
      ['I’m still half asleep.', 'まだ眠いよ。', 'half asleep で「半分眠っている」。'],
      ['Have a great day!', 'いい1日を!', '見送るときの定番。'],
      ['I woke up early today.', '今日は早起きした。', 'woke は wake の過去形。'],
      ['It’s chilly this morning.', '今朝は冷えるね。', 'chilly は「肌寒い」。'],
      ['I need my coffee first.', 'まずコーヒーが必要。', '朝の定番ネタ。'],
      ['Time to get going.', 'そろそろ動き出すか。', '重い腰を上げるときの表現。'],
      ['Rise and shine!', '起きて!', '人を起こすときの明るいひと言。'],
      ['I’m off now.', '行ってきます。', '家を出るときの定番。'],
    ],
  },
  {
    label: '別れぎわ',
    phrases: [
      ['See you later!', 'またあとで!', 'いちばん軽い別れのあいさつ。'],
      ['Take care!', '気をつけてね。', '相手を気づかう定番。'],
      ['Have a nice weekend!', 'いい週末を!', '金曜日の別れぎわに。'],
      ['It was nice talking to you.', '話せてよかった。', '初対面の会話を締めるとき。'],
      ['Catch you later.', 'またね。', 'カジュアルな See you later。'],
      ['I’d better get going.', 'そろそろ行かないと。', '席を立つときの一言。'],
      ['Let’s keep in touch.', '連絡を取り合おう。', '連絡先を交換したあとに。'],
      ['Say hi to your family for me.', 'ご家族によろしく。', '家族の話が出たときの締め。'],
      ['Thanks for your time.', '時間をもらってありがとう。', '打ち合わせの終わりに。'],
      ['See you tomorrow.', 'また明日。', '毎日会う人に。'],
      ['Have a safe trip home.', '気をつけて帰ってね。', '帰宅する人に。'],
      ['I’ll text you.', 'メッセージするね。', 'text は動詞でも使える。'],
      ['Good luck!', 'がんばって!', '相手を送り出すとき。'],
      ['It’s been fun.', '楽しかったよ。', '集まりの締めくくり。'],
    ],
  },
  {
    label: 'お礼',
    phrases: [
      ['Thanks a lot!', '本当にありがとう!', 'Thanks を強めたカジュアルな言い方。'],
      ['I really appreciate it.', '本当に感謝してます。', '大人っぽく丁寧なお礼。'],
      ['That’s very kind of you.', 'ご親切にありがとう。', '贈り物や助けを受けたとき。'],
      ['You shouldn’t have.', 'そんな気を使わなくていいのに。', 'プレゼントをもらったとき。'],
      ['Thanks for helping me out.', '助けてくれてありがとう。', 'help out で「手を貸す」。'],
      ['I could not have done it without you.', 'あなたなしではできなかった。', '大きな助けへのお礼。'],
      ['Thanks for the heads-up.', '教えてくれてありがとう。', '事前に知らせてもらったときに。'],
      ['That means a lot to me.', 'それはすごくうれしい。', '気持ちのこもった返し。'],
      ['I owe you one.', '借りができたね。', '軽いお礼の決まり文句。'],
      ['Thanks for waiting.', '待ってくれてありがとう。', '遅れて合流したとき。'],
      ['I’m grateful for your help.', '助けに感謝しています。', 'appreciate より少し固い言い方。'],
      ['No, thank you.', 'こちらこそありがとう。', 'お礼を返すとき。'],
      ['Thanks anyway.', 'でもありがとう。', '断ったあとにも添えられる。'],
      ['You made my day.', '最高の気分になったよ。', 'make one’s day で「その日をよくする」。'],
    ],
  },
  {
    label: 'お詫び',
    phrases: [
      ['I’m sorry I’m late.', '遅れてごめん。', '遅刻したときの第一声。'],
      ['My apologies.', '申し訳ありません。', '少し改まった謝罪。'],
      ['That was my fault.', '私のミスです。', '責任をはっきり認める。'],
      ['I didn’t mean to.', 'わざとじゃなかった。', '誤解を解くとき。'],
      ['Sorry to keep you waiting.', '待たせてごめん。', '会議や待ち合わせで。'],
      ['I’m terribly sorry.', '本当に申し訳ない。', 'terribly で強く謝る。'],
      ['Please forgive me.', '許してください。', '深くお詫びするとき。'],
      ['It won’t happen again.', 'もう起きません。', '再発防止を伝える。'],
      ['No worries.', '気にしないで。', '謝られた側の返し。'],
      ['It’s not a big deal.', '大したことじゃないよ。', '相手を安心させる。'],
      ['I feel bad about it.', '申し訳なく思ってる。', '気持ちを伝える謝罪。'],
      ['I’ll make it up to you.', '埋め合わせするね。', '埋め合わせの約束。'],
    ],
  },
  {
    label: 'お願い・依頼',
    phrases: [
      ['Could you do me a favor?', 'ちょっとお願いがあるんだけど。', '依頼の切り出し。'],
      ['Would you mind helping me?', '手を貸してもらえますか?', 'mind のあとは動名詞。'],
      ['Can I ask you something?', 'ちょっと聞いてもいい?', '質問の前置き。'],
      ['Could you say that again?', 'もう一度言ってもらえますか?', '聞き取れなかったとき。'],
      ['Please let me know.', '教えてください。', '連絡を頼む定番。'],
      ['I’d appreciate it if you could check.', '確認してもらえると助かります。', '丁寧な依頼。'],
      ['Can you give me a hand?', '手を貸してくれる?', 'give a hand で「手伝う」。'],
      ['Take your time.', 'ゆっくりでいいよ。', '急かさないひと言。'],
      ['Would it be okay if I joined?', '混ざってもいい?', '参加のお願い。'],
      ['Could you hold this for a second?', 'これを持っていてもらえる?', 'for a second で「少しの間」。'],
      ['Feel free to ask me anything.', '何でも聞いてね。', '相手を歓迎する。'],
      ['Would you like me to help?', '手伝おうか?', '自分から申し出るとき。'],
      ['Let me know if that works.', 'それで大丈夫か教えて。', '予定の確認。'],
      ['Could we make it a bit later?', '少し遅らせてもらえる?', '時間変更のお願い。'],
      ['I was wondering if you could help.', '手伝ってもらえたらと思って。', 'やわらかい依頼の切り出し。'],
      ['Do you have a minute?', 'ちょっといい?', '時間をもらう前置き。'],
    ],
  },
  {
    label: '同意・あいづち',
    phrases: [
      ['I see.', 'なるほど。', 'いちばん基本のあいづち。'],
      ['That makes sense.', 'それなら納得。', '理由を聞いて腑に落ちたとき。'],
      ['Tell me more.', 'もっと聞かせて。', '話を広げる相づち。'],
      ['That’s a good point.', 'いい指摘だね。', '話し合いで使える。'],
      ['I couldn’t agree more.', 'まったく同感。', '強い同意を表す決まり文句。'],
      ['Absolutely.', 'そのとおり。', '力強いうなずき。'],
      ['You’re right.', 'そのとおりだね。', '素直な同意。'],
      ['I know what you mean.', '言いたいことはわかる。', '共感を示す。'],
      ['Same here.', '私も同じ。', '相手に合わせるとき。'],
      ['Fair enough.', 'まあ、そうだね。', '完全同意ではない同意。'],
      ['Right?', 'だよね?', '同意を求める相づち。'],
      ['Exactly!', 'まさにそれ!', 'ぴたりと合ったとき。'],
      ['That sounds great.', 'いいね。', '提案への返事。'],
      ['No kidding.', '本当に?', '驚きのあいづち。'],
      ['I guess so.', 'そうかもね。', 'やや控えめな同意。'],
      ['Good point, actually.', '実はいいところを突いてる。', 'actually で強調する。'],
    ],
  },
  {
    label: 'やわらかい否定',
    phrases: [
      ['I’m not so sure about that.', 'そこはちょっと自信ないな。', '角を立てずに反対する。'],
      ['I see it a little differently.', 'ちょっと見方が違うかな。', '対案を出したいとき。'],
      ['That’s not exactly what I meant.', 'そういう意味じゃないんだ。', '誤解を正す。'],
      ['I’m afraid I can’t agree.', 'すみません、賛成できません。', 'afraid でやわらげる。'],
      ['I don’t think that’s right.', 'それは違うと思う。', 'はっきり否定する。'],
      ['Maybe not.', 'たぶん違うかな。', 'やわらかい軽い否定。'],
      ['It depends.', '場合によるね。', '即答を避ける。'],
      ['I’d rather not.', '遠慮しておきます。', '丁寧な断り。'],
      ['That’s one way to look at it.', 'そういう見方もあるね。', '認めつつ距離を置く。'],
      ['I’m on the fence.', 'どちらとも言えない。', 'on the fence で「迷っている」。'],
      ['Not necessarily.', '必ずしもそうとは限らない。', '論理的に反論する。'],
      ['I have to disagree.', '申し訳ないけど反対です。', 'はっきり伝える反対。'],
    ],
  },
  {
    label: '意見を言う',
    phrases: [
      ['In my opinion, it’s worth trying.', '私の意見では試す価値がある。', '意見の前置き。'],
      ['I think we should wait.', '待つべきだと思う。', 'should で提案する。'],
      ['If you ask me, it’s too early.', '私に言わせれば早すぎる。', '強調の前置き。'],
      ['As far as I know, that’s correct.', '私の知る限り正しい。', '知識の範囲を明示する。'],
      ['To be honest, I’m not sure.', '正直言うと自信がない。', 'honestly より会話的。'],
      ['My guess is that it will work.', 'うまくいくと思うよ。', '推測を伝える。'],
      ['I’d say it’s about fifty fifty.', '五分五分かな。', '確率の言い方。'],
      ['It seems to me that we are close.', 'あと少しだと思う。', 'seems to me でやわらかく。'],
      ['I’m pretty sure about this.', 'これはけっこう自信ある。', 'pretty で強調する。'],
      ['Let’s agree to disagree.', '意見が違うのは認めよう。', '議論をやめる合図。'],
      ['I’m leaning toward the first one.', '最初の案に傾いてる。', 'lean toward で「傾く」。'],
      ['That’s how I see it.', '私はそう見てる。', '意見表明の締め。'],
      ['Correct me if I’m wrong.', '違ってたら教えて。', '前置きに使える。'],
      ['I have mixed feelings.', '複雑な気持ちだ。', '単純に決められないとき。'],
    ],
  },
  {
    label: '感想・気持ち',
    phrases: [
      ['That sounds amazing!', 'すごくよさそう!', '誘いへの前向きな返し。'],
      ['I’m looking forward to it.', '楽しみにしてる。', 'to のあとは名詞か動名詞。'],
      ['I’m a bit nervous.', 'ちょっと緊張してる。', '本番前の気持ち。'],
      ['I’m so relieved.', 'ほっとした。', '心配が消えたとき。'],
      ['That made me happy.', 'うれしかった。', 'シンプルな感想。'],
      ['I can’t wait!', '待ちきれない!', '楽しみを強調する。'],
      ['I’m not in the mood today.', '今日はその気分じゃない。', 'mood の使い方。'],
      ['It was better than I expected.', '期待以上だった。', '感想の定番。'],
      ['I’m proud of you.', '誇らしいよ。', '相手を称える。'],
      ['That’s a relief.', '安心した。', 'relief は「安堵」。'],
      ['I really enjoyed it.', 'すごく楽しかった。', 'enjoy は it を取る。'],
      ['It was worth the effort.', '苦労した甲斐があった。', 'worth の使い方。'],
      ['I’m touched.', '感動した。', '心を動かされたとき。'],
      ['That bugs me a little.', 'ちょっと気になる。', 'bug は「もやもやさせる」。'],
    ],
  },
  {
    label: '質問する',
    phrases: [
      ['What do you think?', 'どう思う?', '意見を求める定番。'],
      ['How was your day?', '今日はどうだった?', '会話の入り口。'],
      ['What are you up to this weekend?', '週末は何するの?', 'up to は予定を聞くカジュアル表現。'],
      ['How long does it take?', 'どのくらい時間がかかる?', '所要時間を聞く。'],
      ['Where are you from?', '出身はどこ?', '初対面の定番。'],
      ['What do you do?', '仕事は何を?', '職業を聞く言い方。'],
      ['How did it go?', 'どうだった?', '結果を聞く。'],
      ['Why not?', 'いいね、なぜダメなの?', '誘いに乗るときと理由を聞くときの両方で使う。'],
      ['What’s going on?', '何が起きてるの?', '状況を聞く。'],
      ['Do you know what I mean?', 'わかる?', '説明のあとに添える。'],
      ['How come?', 'どうして?', 'why より会話的。'],
      ['Which one do you like?', 'どっちが好き?', '選択を聞く。'],
      ['Have you ever been there?', 'そこに行ったことある?', '経験を聞く現在完了。'],
      ['What’s it like?', 'どんな感じ?', '印象を聞く。'],
      ['How’s it going?', '調子どう?', '軽いあいさつにもなる。'],
      ['Any plans for tonight?', '今夜は予定ある?', '誘う前の前置き。'],
    ],
  },
  {
    label: '聞き返す・確認',
    phrases: [
      ['Sorry, what did you say?', 'ごめん、何て言った?', '聞き取れなかったとき。'],
      ['Could you speak a little slower?', 'もう少しゆっくり話してもらえますか?', '学習者にうれしいお願い。'],
      ['What does that mean?', 'どういう意味?', '語句の意味を聞く。'],
      ['Did you say fifteen or fifty?', '15と50のどちら?', '聞き間違えやすい数字の確認。'],
      ['Just to be sure, you mean tomorrow?', '念のため、明日で合ってる?', 'be sure で確認する。'],
      ['Let me repeat that back to you.', '復唱しますね。', '正確に伝わったか確かめる。'],
      ['Do you mean this one or that one?', 'これとそれ、どっち?', '指して確認する。'],
      ['How do you spell that?', 'つづりは?', '名前や単語の確認。'],
      ['Am I saying it right?', '発音合ってる?', '発音の確認。'],
      ['Could you write it down?', '書いてもらえますか?', '聞き取れないときの最終手段。'],
      ['Wait, what?', 'え、何て?', 'カジュアルな聞き返し。'],
      ['I didn’t catch that.', '聞き取れなかった。', 'catch は「聞き取る」。'],
    ],
  },
  {
    label: '誘う・約束',
    phrases: [
      ['Do you want to grab a coffee?', 'コーヒーでも行かない?', 'grab は気軽に誘う動詞。'],
      ['Are you free on Friday?', '金曜は空いてる?', '予定を確かめる。'],
      ['Let’s hang out sometime.', '今度遊ぼうよ。', 'sometime で具体性をぼかす。'],
      ['How about going for a walk?', '散歩はどう?', 'How about のあとは動名詞。'],
      ['Would you like to join us?', '一緒にどう?', '丁寧な誘い。'],
      ['I’ll pick you up at seven.', '7時に迎えに行くね。', 'pick up は「車で迎える」。'],
      ['Let’s meet halfway.', '中間地点で会おう。', 'halfway は「途中」。'],
      ['Count me in.', '参加するよ。', '誘いに乗るとき。'],
      ['I’ll take a rain check.', 'また今度誘って。', '断るときの決まり文句。'],
      ['Maybe next time.', 'また今度ね。', 'やわらかい軽い断り。'],
      ['Sounds like a plan.', 'それで決まりだね。', '予定がまとまったとき。'],
      ['What time works for you?', '何時がいい?', '時間を調整する。'],
      ['I’m in.', '参加!', '短くて元気な同意。'],
      ['Let’s make it official.', '正式に決めよう。', '冗談めかして決めるとき。'],
    ],
  },
  {
    label: '買い物',
    phrases: [
      ['I’m just looking, thanks.', '見てるだけです。', '店員に声をかけられたとき。'],
      ['How much is this?', 'これはいくら?', '値段を聞く基本。'],
      ['Do you have this in a smaller size?', 'これのもっと小さいサイズはありますか?', 'サイズの相談。'],
      ['Can I try it on?', '試着してもいい?', 'try on は「試着する」。'],
      ['I’ll take it.', 'これください。', '購入を決めたとき。'],
      ['Do you accept credit cards?', 'カードは使えますか?', '支払い方法の確認。'],
      ['It’s a little too expensive.', 'ちょっと高すぎるかな。', '値段の感想。'],
      ['Where’s the fitting room?', '試着室はどこ?', '店内で聞く。'],
      ['I’m looking for a gift.', 'プレゼントを探してる。', '目的を伝える。'],
      ['Can I get a receipt?', 'レシートをもらえますか?', '会計のあとに。'],
      ['Is this on sale?', 'これはセール中?', 'on sale は「特売で」。'],
      ['I’d like to return this.', 'これを返品したい。', '返品の申し出。'],
      ['Keep the change.', 'おつりは取っておいて。', 'チップを渡すとき。'],
      ['Just browsing, thanks.', '見て回ってるだけです。', 'looking より店らしい言い方。'],
    ],
  },
  {
    label: 'レストラン・カフェ',
    phrases: [
      ['A table for two, please.', '2人です。', '入店時の定番。'],
      ['Could I see the menu?', 'メニューをください。', '席についたら。'],
      ['What do you recommend?', 'おすすめは?', '店員に聞く。'],
      ['I’ll have the same.', '同じものを。', '連れと同じ注文。'],
      ['Can I get this to go?', 'これを持ち帰りで。', 'to go は「持ち帰り」。'],
      ['Could we get the check?', 'お会計お願いします。', 'check は米英語。'],
      ['It’s on me.', '私が払うよ。', '奢るときの決まり文句。'],
      ['Let’s split the bill.', '割り勘にしよう。', 'split は「分ける」。'],
      ['This is delicious.', 'これおいしい。', '食事中の感想。'],
      ['I’m allergic to nuts.', 'ナッツアレルギーです。', 'allergy の言い方。'],
      ['No onions, please.', '玉ねぎ抜きで。', '注文のカスタマイズ。'],
      ['Do you have a reservation?', '予約はありますか?', '店側の定番の質問。'],
      ['I’d like a refill.', 'おかわりをください。', '飲み物の追加。'],
      ['Could I get the bill, please?', 'お会計をお願いできますか?', 'check のイギリス風の言い方。'],
    ],
  },
  {
    label: '道をたずねる・移動',
    phrases: [
      ['Excuse me, how do I get to the station?', 'すみません、駅へはどう行けば?', '道を聞く基本形。'],
      ['Is it far from here?', 'ここから遠い?', '距離を確認する。'],
      ['Go straight for two blocks.', '2ブロックまっすぐ。', 'まっすぐ進む道案内。'],
      ['Turn left at the corner.', '角を左に曲がって。', '曲がる指示。'],
      ['It’s within walking distance.', '歩いて行ける距離。', 'within の使い方。'],
      ['I think we are lost.', '道に迷ったみたい。', 'lost の使い方。'],
      ['Which line should I take?', 'どの路線に乗れば?', '電車の乗り換え。'],
      ['Does this bus go downtown?', 'このバスは中心街に行く?', '行き先の確認。'],
      ['How long is the ride?', '乗車時間はどのくらい?', 'ride は「乗車」。'],
      ['I missed my stop.', '降りる駅を逃した。', 'miss a stop の使い方。'],
      ['Could you tell me when to get off?', '降りる場所を教えてもらえますか?', '不安なときの頼み。'],
      ['It’s just around the corner.', 'すぐそこだよ。', 'corner を使った定番。'],
      ['Take the second exit.', '2つ目の出口を出て。', '出口の案内。'],
      ['Let’s grab a taxi.', 'タクシーに乗ろう。', 'grab a taxi の使い方。'],
    ],
  },
  {
    label: '電話・オンライン',
    phrases: [
      ['Can you hear me?', '聞こえますか?', 'オンライン会議の最初。'],
      ['You’re breaking up.', '声が途切れてる。', '通話トラブルの定番。'],
      ['Let me share my screen.', '画面を共有します。', '会議で使う。'],
      ['Sorry, I was on mute.', 'すみません、ミュートでした。', 'よくある失敗のひと言。'],
      ['Can everyone see my screen?', '画面見えてますか?', '共有後の確認。'],
      ['I’ll call you back.', 'かけ直すね。', '電話を切るとき。'],
      ['Who’s speaking?', 'どちら様ですか?', '電話の応対。'],
      ['Hold on a second.', 'ちょっと待って。', '保留のカジュアル版。'],
      ['Let’s take this offline.', 'これは別で話そう。', '会議を止めるとき。'],
      ['Could you unmute yourself?', 'ミュート解除してもらえますか?', '会議あるあるの依頼。'],
      ['The connection is bad.', '回線が悪いね。', 'connection の使い方。'],
      ['I’ll send you the link.', 'リンクを送るね。', 'オンラインの誘い。'],
      ['Sorry, go ahead.', 'すみません、どうぞ。', '話を譲るとき。'],
      ['You froze for a second.', '一瞬固まってたよ。', '映像トラブルの表現。'],
    ],
  },
  {
    label: 'メール・チャット',
    phrases: [
      ['Just a quick note.', 'ちょっとした連絡です。', 'メールの前置き。'],
      ['Thanks for your quick reply.', 'すぐに返信ありがとう。', 'ビジネスメールの定番。'],
      ['I’m writing to ask about the schedule.', '日程について伺っています。', '用件を最初に書く。'],
      ['Please find the file attached.', 'ファイルを添付しました。', '添付の案内。'],
      ['Sorry for the late reply.', '返信が遅れてすみません。', '遅れたときの第一声。'],
      ['Let me know what you think.', '意見を聞かせて。', '確認のお願い。'],
      ['I’ll get back to you soon.', 'すぐ返事します。', 'get back to は「返答する」。'],
      ['Could you send it again?', 'もう一度送ってもらえる?', '届かないとき。'],
      ['Looking forward to your reply.', '返信お待ちしています。', 'メールの結び。'],
      ['Talk soon.', 'また連絡するね。', 'カジュアルな結び。'],
      ['Sorry to bother you.', 'お手数かけます。', '依頼の前置き。'],
      ['Cc me on that.', '私もCCに入れて。', 'ビジネスで便利なひと言。'],
      ['Sounds good, will do.', '了解、そうするね。', 'チャットの返し。'],
      ['Let me double-check.', '確認してみる。', 'double-check の使い方。'],
    ],
  },
  {
    label: '困ったとき',
    phrases: [
      ['I need some help.', '助けが必要です。', '助けを求める第一声。'],
      ['Could you help me with this?', 'これを手伝ってもらえますか?', 'help with の使い方。'],
      ['Something went wrong.', '何か問題が起きた。', 'went wrong の使い方。'],
      ['I lost my wallet.', '財布をなくした。', '紛失の言い方。'],
      ['My phone died.', 'スマホの充電が切れた。', 'die は電池にも使える。'],
      ['I’m locked out.', '締め出された。', 'locked out の使い方。'],
      ['It’s an emergency.', '緊急です。', '緊急時のひと言。'],
      ['Can I use your phone?', '電話を借りてもいい?', '困ったときの頼み。'],
      ['I don’t feel well.', '気分が悪い。', '体調不良を伝える。'],
      ['Could you call a doctor?', '医者を呼んでもらえますか?', '緊急時の依頼。'],
      ['I think I left it on the train.', '電車に置き忘れたみたい。', 'left は「置き忘れた」。'],
      ['Is there a lost and found?', '遺失物係はありますか?', '落とし物を探す。'],
      ['Don’t worry about it.', '心配しないで。', '相手を落ち着かせる。'],
      ['We’ll figure it out.', 'なんとかしよう。', 'figure out は「解決する」。'],
    ],
  },
  {
    label: '褒める・励ます',
    phrases: [
      ['You did a great job!', 'よくやったね!', '結果への褒め言葉。'],
      ['I’m impressed.', '感心したよ。', '素直な称賛。'],
      ['You have improved a lot.', 'すごく上達したね。', '上達を伝える。'],
      ['Keep up the good work.', 'その調子で。', '継続を励ます。'],
      ['You can do it.', 'きみならできる。', '短くて強い応援。'],
      ['Don’t give up.', 'あきらめないで。', '励ましの定番。'],
      ['Take it one step at a time.', '一歩ずつでいい。', '焦る人へのひと言。'],
      ['That’s the spirit!', 'その意気だよ!', '前向きな姿勢を褒める。'],
      ['You should be proud of yourself.', '自分を誇っていいよ。', 'proud of の使い方。'],
      ['It’s okay to make mistakes.', '間違えても大丈夫。', '学習者への温かい一言。'],
      ['You’re getting better every day.', '毎日よくなってるよ。', '成長を実感させる。'],
      ['I believe in you.', '信じてるよ。', '背中を押す。'],
      ['Hang in there.', 'もう少しがんばって。', 'つらいときの励まし。'],
      ['Nice try!', 'よくやった!', '結果が出なくても褒める。'],
    ],
  },
  {
    label: '自己紹介・初対面',
    phrases: [
      ['Nice to meet you.', 'はじめまして。', '初対面の定番。'],
      ['Please call me Ken.', 'ケンと呼んでください。', '呼び名を指定する。'],
      ['I’m from Japan.', '日本から来ました。', '出身を伝える。'],
      ['I work as an engineer.', 'エンジニアをしています。', 'work as の使い方。'],
      ['I’ve been learning English for two years.', '英語を2年勉強しています。', '現在完了で期間を言う。'],
      ['What brings you here?', 'ここへはどうして?', '初対面の会話を広げる。'],
      ['I’m here on business.', '仕事で来ています。', 'on business の使い方。'],
      ['How do you know each other?', 'お2人はどういうご関係?', '紹介された場で。'],
      ['Let me introduce myself.', '自己紹介させてください。', '改まった場で。'],
      ['I’m a big fan of your work.', '作品のファンです。', '初対面の称賛。'],
      ['It’s a small world.', '世間は狭いね。', '偶然の再会で。'],
      ['I’ve heard a lot about you.', 'お話は伺っています。', '紹介されたとき。'],
    ],
  },
  {
    label: '天気・雑談',
    phrases: [
      ['It’s a lovely day, isn’t it?', 'いい天気だね。', '天気の定番。'],
      ['It looks like it’s going to rain.', '雨が降りそうだね。', 'look like の使い方。'],
      ['It’s freezing today.', '今日は凍えるほど寒い。', 'freezing は強い寒さ。'],
      ['What’s the weather like there?', 'そっちの天気は?', '遠くの人に聞く。'],
      ['I hope it clears up.', '晴れるといいね。', 'clear up は「晴れる」。'],
      ['It’s hotter than usual.', 'いつもより暑いね。', 'than usual の使い方。'],
      ['Did you see the game last night?', '昨夜の試合見た?', '雑談の入り口。'],
      ['How was your weekend?', '週末はどうだった?', '月曜日の定番。'],
      ['Long time no see!', '久しぶり!', '日本語由来の英語。'],
      ['What have you been up to?', '最近何してた?', '久しぶりに会ったとき。'],
      ['Crazy weather, huh?', 'すごい天気だね。', 'huh で同意を求める。'],
      ['I can’t believe it’s already December.', 'もう12月なんて信じられない。', '時の速さを話題にする。'],
    ],
  },
  {
    label: '仕事・学校',
    phrases: [
      ['I have a meeting at ten.', '10時に会議があります。', '予定を伝える。'],
      ['Let’s get started.', '始めましょう。', '会議の開始。'],
      ['Could you send me the details?', '詳細を送ってもらえますか?', '仕事の依頼。'],
      ['I’m working on it.', '今取りかかっています。', '進捗の返事。'],
      ['The deadline is next Monday.', '締め切りは来週の月曜です。', 'deadline の使い方。'],
      ['Let’s go over it once more.', 'もう一度確認しよう。', 'go over は「見直す」。'],
      ['I’ll take care of it.', '私が対応します。', '引き受けるとき。'],
      ['Can we discuss this later?', 'あとで相談できますか?', '会議中に使う。'],
      ['I’m running late.', '遅れています。', 'running late の使い方。'],
      ['Let’s wrap up.', 'まとめよう。', '会議の終わり。'],
      ['I have a lot on my plate.', '仕事が山積みです。', 'on one’s plate の使い方。'],
      ['Good work, everyone.', 'みんなお疲れさま。', '締めの一言。'],
      ['Could you cover for me?', '代わってもらえますか?', 'cover for の使い方。'],
      ['I’ll follow up by email.', 'メールで追います。', 'follow up の使い方。'],
    ],
  },
  {
    label: '旅行',
    phrases: [
      ['I’d like to check in.', 'チェックインしたいです。', 'ホテルで使う。'],
      ['Is breakfast included?', '朝食は付いてますか?', 'included の使い方。'],
      ['Could I have a wake-up call?', 'モーニングコールをお願いできますか?', 'ホテルのサービス。'],
      ['Where can I exchange money?', 'どこで両替できますか?', 'exchange の使い方。'],
      ['I’m here for sightseeing.', '観光で来ました。', '入国の定番。'],
      ['How much is the admission?', '入場料はいくら?', 'admission は「入場料」。'],
      ['Could you take a picture of us?', '写真を撮ってもらえますか?', '撮影のお願い。'],
      ['Is there Wi-Fi here?', 'ここにWi-Fiはありますか?', '接続の確認。'],
      ['I’d like a window seat.', '窓側の席をお願いします。', '窓側を頼むとき。'],
      ['What time is check-out?', 'チェックアウトは何時?', 'ホテルで確認する。'],
      ['Can I leave my luggage here?', '荷物を預かってもらえますか?', '観光の前に。'],
      ['Do I need a reservation?', '予約は必要ですか?', '店などで確認する。'],
      ['It’s my first time here.', 'ここは初めてです。', '初訪問を伝える。'],
      ['What’s worth seeing here?', 'ここは何が見どころ?', 'worth seeing の使い方。'],
    ],
  },
  {
    label: '体調・健康',
    phrases: [
      ['I have a headache.', '頭が痛い。', 'have a で症状を言う。'],
      ['I think I caught a cold.', '風邪をひいたみたい。', 'catch a cold の使い方。'],
      ['I feel much better.', 'だいぶよくなった。', 'much better で回復を伝える。'],
      ['I didn’t sleep well last night.', '昨夜はよく眠れなかった。', '眠りについての話。'],
      ['You look tired.', '疲れてるみたいだね。', 'look と形容詞。'],
      ['Take a break.', '休憩しよう。', '相手を休ませるとき。'],
      ['I need to rest.', '休む必要がある。', 'need to の使い方。'],
      ['Drink plenty of water.', '水をたくさん飲んで。', 'plenty of の使い方。'],
      ['Get well soon.', 'お大事に。', '病気の人へ。'],
      ['I’m feeling under the weather.', '少し体調がすぐれない。', 'under the weather の使い方。'],
      ['Are you feeling okay?', '大丈夫?', '体調を気づかう。'],
      ['I have a sore throat.', 'のどが痛い。', 'sore の使い方。'],
      ['Let’s call it a day.', '今日はここまでにしよう。', '切り上げるとき。'],
      ['Sleep is the best medicine.', '睡眠が一番の薬。', 'ことわざ風のひと言。'],
    ],
  },
]
