import type { GrammarUnit } from '../../types'

// U23 仮定法の発展

export const u23: GrammarUnit = {
  id: 'u23',
  level: 'B2',
  title: '仮定法の発展',
  lessons: [
    {
      id: 'u23-l1',
      unitId: 'u23',
      level: 'B2',
      title: '混合条件文',
      objective: '「過去にこうしていれば、今こうなのに」という時間のずれた仮定を、混合条件文で正しく表現できるようになります。',
      minutes: 12,
      prereqs: ['u22-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '「あのとき〜だったら、今…なのに」',
          body:
            '第2条件文は「現在の仮定 → 現在の結果」、第3条件文は「過去の仮定 → 過去の結果」と、時間がそろっていました。でも実際の会話では、**過去の選択が今の状況に影響している**話をよくします。\n\n「あの仕事を受けていたら(過去)、今ごろニューヨークに住んでいるのに(現在)」\n\nこのように if節と主節で時間がずれる文を**混合条件文**と呼びます。作り方はシンプルで、if節は第3条件文の形、主節は第2条件文の形を、そのまま組み合わせるだけです。',
        },
        {
          type: 'timeline',
          title: '時間のずれを図で確認',
          timelines: [
            {
              title: 'If I had taken that job,(過去の仮定)',
              point: 30,
              pointLabel: 'あの仕事を受けていたら',
              caption: 'if節は過去の一点への仮定。第3条件文と同じ had + 過去分詞。',
            },
            {
              title: 'I would be living in New York now.(現在の結果)',
              point: 100,
              pointLabel: '今ごろニューヨークに住んでいる',
              caption: '結果は「今」の話。第2条件文と同じ would + 動詞。',
            },
          ],
        },
        {
          type: 'explanation',
          title: '形と見分け方',
          body:
            "**If + 主語 + had + 過去分詞(過去の条件), 主語 + would + 動詞の原形(現在の結果)**\n\n- If I had taken that job, I would be living in New York now.\n\n見分けるヒントは主節の **now / today / still** などの「現在」を示す語です。語句だけで決めず、結果が「今の状態」なのか「すでに完了したこと」なのかを確かめます。by now なら「今までに」という完了を表すこともあります。\n\n逆のパターン(現在の状態 → 過去の結果)もあります。\n\n- If I weren't so shy, I would have introduced myself.(内気な性格は今も続く状態 → 自己紹介しなかったのは過去)",
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'If I had taken that job, I would be living in New York now.', ja: 'あの仕事を受けていたら、今ごろニューヨークに住んでいるでしょう。', highlight: 'would be living' },
            { en: 'If she had studied medicine, she would be a doctor today.', ja: '彼女が医学を学んでいたら、今日は医師になっているでしょう。', highlight: 'would be' },
            { en: "If we hadn't missed our flight, we would be on the beach right now.", ja: '飛行機に乗り遅れていなければ、今ごろビーチにいるのに。', highlight: "hadn't missed" },
            { en: "If he had saved more money, he wouldn't be so worried now.", ja: 'もっとお金を貯めていれば、彼は今こんなに心配していないでしょう。', highlight: "wouldn't be" },
            { en: "If I weren't so shy, I would have introduced myself at the party.", ja: 'こんなに内気でなければ、パーティーで自己紹介したのですが。', highlight: 'would have introduced', note: '逆パターン。現在も続く性格 → 過去の結果。' },
          ],
        },
        {
          type: 'table',
          title: '条件文の4つの型',
          headers: ['型', 'if節', '主節', '時間の流れ'],
          rows: [
            ['第2条件文', '過去形', 'would + 原形', '現在の仮定 → 現在の結果'],
            ['第3条件文', 'had + 過去分詞', 'would have + 過去分詞', '過去の仮定 → 過去の結果'],
            ['混合(基本)', 'had + 過去分詞', 'would + 原形', '過去の仮定 → 現在の結果'],
            ['混合(逆)', '過去形', 'would have + 過去分詞', '現在の仮定 → 過去の結果'],
          ],
        },
      ],
      quiz: [
        {
          id: 'u23-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'If I had gone to bed earlier, I ___ so tired now.',
          sentenceJa: 'もっと早く寝ていれば、今こんなに疲れていないのに。',
          choices: ["wouldn't be", "wouldn't have been", "won't be", "hadn't been"],
          correctIndex: 0,
          explanation: '条件は過去(had gone)ですが、結果は now が示すとおり現在の状態です。現在の結果には would + 原形を使います。',
          choiceNotes: [null, "wouldn't have been は過去の結果に使う形です。now と合いません。", '仮定の話の主節に will は使えません。would を使います。', 'had + 過去分詞は if節で過去の条件を表す形で、主節には使いません。'],
          audioEn: "If I had gone to bed earlier, I wouldn't be so tired now.",
        },
        {
          id: 'u23-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「あのとき彼のアドバイスを聞いていれば、今こんな問題は抱えていないのに」と言いたいとき。',
          choices: [
            'If I listened to his advice, I would not have this problem now.',
            'If I had listened to his advice, I would not have this problem now.',
            'If I had listened to his advice, I would not have had this problem now.',
            'If I have listened to his advice, I will not have this problem now.',
          ],
          correctIndex: 1,
          explanation: '「あのとき聞いていれば」は過去の非現実なので if節は had listened、「今抱えていない」は現在の結果なので would not have です。',
          choiceNotes: ['過去形 listened は「現在の非現実」(第2条件文)を表す形で、過去の「あのとき」を表せません。', null, 'would not have had は過去の結果の形です。「今」の問題の話には合いません。', 'if節に現在完了、主節に will は使えません。仮定法では時制を過去にずらします。'],
          audioEn: 'If I had listened to his advice, I would not have this problem now.',
        },
        {
          id: 'u23-l1-q3',
          prompt: '次の文から分かることを選んでください。',
          sentence: "If she hadn't moved to Canada, we would still work together.",
          choices: [
            '彼女はカナダに引っ越さず、今も一緒に働いている。',
            '彼女はカナダに引っ越したので、今は一緒に働いていない。',
            '彼女はこれからカナダに引っ越すつもりだ。',
            '二人は過去に一緒に働いたことがない。',
          ],
          correctIndex: 1,
          explanation: '仮定法は現実の裏返しです。「引っ越していなければ今も一緒に働いているのに」= 実際は引っ越した・今は一緒に働いていない、ということです。',
          choiceNotes: ['if節は「実際に起きたこと」の裏返しです。引っ越したのが現実です。', null, '未来の予定の話ではありません。had moved は過去の出来事への仮定です。', 'would still work together は「今も続いていたはず」で、以前一緒に働いていたことが前提です。'],
          audioEn: "If she hadn't moved to Canada, we would still work together.",
        },
        {
          id: 'u23-l1-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'If we had bought that house, we would be neighbors now.',
            'If he had taken the medicine, he would feel better today.',
            'If I had learned to drive, I will not need to take the bus now.',
            "If they hadn't lost the map, they wouldn't be lost now.",
          ],
          correctIndex: 2,
          explanation: '仮定の結果には will ではなく would を使います。正しくは I would not need to take the bus now です。',
          choiceNotes: ['正しい混合条件文です(過去の購入 → 現在の隣人関係)。', '正しい混合条件文です(過去の服薬 → 今日の体調)。', null, '正しい混合条件文です(過去の紛失 → 現在の状況)。'],
          audioEn: 'If I had learned to drive, I would not need to take the bus now.',
        },
        {
          id: 'u23-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'If we had booked the tickets last month, we ___ about the price now.',
          sentenceJa: '先月チケットを予約していれば、今ごろ値段の心配などしていないのに。',
          choices: [
            "wouldn't have worried",
            "won't be worrying",
            "wouldn't be worrying",
            "hadn't been worrying",
          ],
          correctIndex: 2,
          explanation: '条件は過去(had booked)ですが、結果は now が示すとおり現在の状態です。現在の結果は would + 原形で表し、進行中の心配なので be worrying にします。',
          choiceNotes: ['これは過去の結果を表す形です。now とかみ合いません。', '仮定の話の主節に will は使いません。', null, 'had + 過去分詞は if節で過去の条件を表す形です。主節には置けません。'],
          audioEn: "If we had booked the tickets last month, we wouldn't be worrying about the price now.",
        },
        {
          id: 'u23-l1-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「もっと社交的な性格だったら、あのとき彼に話しかけていたのに」と言いたいとき(性格は今も変わらない)。',
          choices: [
            'If I had been more outgoing, I would have talked to him then.',
            'If I were more outgoing, I would have talked to him then.',
            'If I were more outgoing, I would talk to him then.',
            'If I had been more outgoing, I would talk to him then.',
          ],
          correctIndex: 1,
          explanation: '「今も続く性格」は現在の非現実なので if節は were、「あのとき話しかけた」は過去の結果なので would have talked です。混合条件文の逆パターンです。',
          choiceNotes: ['had been だと「あのときだけ社交的だったら」となり、今も続く性格を表せません。', null, 'would talk は現在の結果の形です。then とかみ合いません。', 'if節・主節ともに時間の向きが逆になっています。'],
          audioEn: 'If I were more outgoing, I would have talked to him then.',
        },
        {
          id: 'u23-l1-q7',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'If my parents had not sold the house, I would be living in the countryside today.',
          choices: [
            '両親は家を売らなかったので、私は今も田舎に住んでいる。',
            '両親は家を売ったので、私は今は田舎に住んでいない。',
            '両親はこれから家を売るつもりでいる。',
            '私は田舎に住んだことが一度もない。',
          ],
          correctIndex: 1,
          explanation: '仮定法は現実の裏返しです。「売らなかったら今住んでいるのに」ということは、実際には売ったので今は住んでいないという意味になります。',
          choiceNotes: ['仮定法で述べているので、現実は逆です。実際には売っています。', null, 'had not sold は過去の出来事についての仮定で、これからの予定の話ではありません。', '過去に住んでいたかどうかは、この文だけでは断定できません。'],
          audioEn: 'If my parents had not sold the house, I would be living in the countryside today.',
        },
        {
          id: 'u23-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'If she had accepted the offer, she would be working in Osaka now.',
            "If I didn't have a meeting tomorrow, I would have joined you tonight.",
            "If they had left earlier, they wouldn't be stuck in traffic at the moment.",
            'If he had studied harder, he would passed the exam last year.',
          ],
          correctIndex: 3,
          explanation: '過去の条件に対する過去の結果は would have + 過去分詞です。正しくは he would have passed the exam last year. です。',
          choiceNotes: ['正しい混合条件文です。過去の条件から現在の結果を導いています。', '正しい混合条件文です。明日の予定という現在の事情から、今夜という過去寄りの結果を導いています。', '正しい混合条件文です。at the moment が現在の結果であることを示しています。', null],
          audioEn: 'If he had studied harder, he would have passed the exam last year.',
        },
        {
          id: 'u23-l1-q9',
          prompt: '空所に入る形を選んでください。',
          sentence: 'If Kenta ___ the train schedule, he would not be waiting at the station now.',
          sentenceJa: 'ケンタが電車の時刻表を確認していたら、今ごろ駅で待っていないでしょう。',
          choices: [
            'checked',
            'has checked',
            'would check',
            'had checked',
          ],
          correctIndex: 3,
          explanation: '主節が would not be waiting now と現在の結果を表しているので、if節は過去の非現実を表す had + 過去分詞にします。',
          choiceNotes: ['過去形 checked は現在の非現実を表す形で、「あのとき確認していれば」という過去の仮定にはなりません。', '現在完了は仮定法の条件節には使いません。', 'if節の中に would は置きません。', null],
          audioEn: 'If Kenta had checked the train schedule, he would not be waiting at the station now.',
        },
        {
          id: 'u23-l1-q10',
          prompt: '次の2文が表す時間関係の組み合わせとして正しいものを選んでください。',
          sentence: 'If I had learned to drive, I would take you to the airport tomorrow.',
          choices: [
            '過去の条件 → 過去の結果',
            '現在の条件 → 現在の結果',
            '過去の条件 → これからの結果',
            'これからの条件 → 過去の結果',
          ],
          correctIndex: 2,
          explanation: 'if節の had learned は過去の非現実、主節の would take と tomorrow はこれからの話です。混合条件文は主節が現在に限らず、未来を指すこともあります。',
          choiceNotes: ['過去の結果なら would have taken になります。', '現在の条件なら if節は過去形 learned です。', null, '条件節は had learned で、これからの話ではありません。'],
          audioEn: 'If I had learned to drive, I would take you to the airport tomorrow.',
        },
      ],
      summary: [
        '混合条件文は「過去の条件 → 現在の結果」。If + had 過去分詞, would + 原形。',
        '主節に now / today / still があれば結果は現在。would have done ではなく would do。',
        '逆パターン「現在の状態 → 過去の結果」は If + 過去形, would have + 過去分詞。',
        '仮定の結果に will は使わない。仮定法の主節は常に would(could / might)。',
      ],
    },
    {
      id: 'u23-l2',
      unitId: 'u23',
      level: 'B2',
      title: 'provided / suppose / on condition that',
      objective: 'provided / on condition that / suppose などを使って、if 以外の形で条件を表現できるようになります。',
      minutes: 10,
      prereqs: ['u23-l1'],
      blocks: [
        {
          type: 'explanation',
          title: 'if だけが条件ではない',
          body:
            '「〜という条件なら」「もし〜だとしたら」を表す言い方は、if 以外にもいくつかあります。B2レベルの読み書きでは、これらを使い分けられると表現の幅がぐっと広がります。\n\n- **provided (that) / providing (that)**: 「〜という条件であれば」。条件を満たすことをはっきり求める、やや硬めの表現\n- **on condition that**: 「〜という条件で」。契約や交渉で使うフォーマルな表現\n- **suppose / supposing**: 「もし〜だとしたら(どうする?)」。仮の話を持ちかける表現で、疑問文と相性抜群です',
        },
        {
          type: 'table',
          title: '条件表現の使い分け',
          headers: ['表現', '意味', 'よく使う場面'],
          rows: [
            ['provided (that)', '〜という条件であれば', '許可・約束に条件を付けるとき'],
            ['on condition that', '〜という条件で', '契約・交渉などフォーマルな場面'],
            ['suppose / supposing', 'もし〜だとしたら', '仮の話を持ちかける。後ろに疑問文が続くことが多い'],
            ['what if ...?', 'もし〜だったらどうする?', '心配や提案を切り出す会話表現'],
          ],
        },
        {
          type: 'explanation',
          title: '中の動詞は if と同じルール',
          body:
            "これらの表現の後ろの動詞は、**if節とまったく同じルール**で動きます。\n\n- 現実的な条件 → 現在形(未来のことでも will は使わない)\n- 現実離れした仮定 → 過去形(主節・続く文は would)\n\n比べてみましょう。\n\n- Suppose he **doesn't** come. What **will** we do?(実際にあり得る話)\n- Suppose you **won** the lottery. What **would** you do?(まずあり得ない仮定)",
        },
        {
          type: 'contrast',
          title: '条件を課すのか、仮の話を持ちかけるのか',
          left: {
            label: 'provided / on condition that — 条件を課す',
            items: [
              { en: 'You may leave early provided that you finish the report first.', ja: '先に報告書を仕上げるという条件であれば、早く帰って構いません。', highlight: 'provided that' },
              { en: 'They agreed to the deal on condition that the price stayed the same.', ja: '価格が変わらないという条件で、彼らはその取引に同意しました。', highlight: 'on condition that' },
            ],
            pointJa: '許可や合意に必要条件を付けます。on condition that は契約に近いフォーマルさです。',
          },
          right: {
            label: 'suppose / supposing — 仮の話を持ちかける',
            items: [
              { en: 'Suppose the train was cancelled. How would you get to the airport?', ja: '電車が運休になったとしましょう。どうやって空港へ行きますか。', highlight: 'Suppose' },
              { en: 'Supposing nobody replies, should we send the message again?', ja: '仮に誰も返信しなかったら、もう一度メッセージを送るべきでしょうか。', highlight: 'Supposing' },
            ],
            pointJa: '条件を課すのではなく、仮の状況を相手に考えさせます。疑問文が続くのが典型です。',
          },
          note: 'どの表現でも節の中に will は入れません。非現実の仮定なら過去形にします。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'You can borrow my car this weekend provided you fill up the tank before you return it.', ja: '今週末は車を貸してもいいですよ。ただし返す前にガソリンを満タンにしてください。', highlight: 'provided' },
            { en: "We'll sign the contract on condition that the price stays the same.", ja: '価格が変わらないという条件で、契約にサインします。', highlight: 'on condition that' },
            { en: 'Suppose you lost your phone while travelling abroad. What would you do first?', ja: '海外を旅行中に携帯をなくしたとしましょう。あなたはまず何をしますか。', highlight: 'Suppose', note: 'あり得なくはないが仮の話なので過去形 lost + would。' },
            { en: 'Supposing he refuses to sign the contract, who will explain the situation to the client?', ja: '仮に彼が契約書に署名を拒んだら、誰が顧客に事情を説明するのですか。', highlight: 'Supposing', note: '現実的にあり得る話なら現在形 + will でも使えます。' },
            { en: 'Providing that everyone agrees, we will start the project next week.', ja: '全員が賛成すれば、来週プロジェクトを始めます。', highlight: 'Providing that' },
            { en: 'What if we miss the last train and there are no taxis outside the station?', ja: '終電を逃して、駅の外にタクシーが一台もなかったらどうしますか。', highlight: 'What if' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u23-l2-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'You can stay at my place ___ you keep the room clean.',
          sentenceJa: '部屋をきれいにしておくなら、うちに泊まってもいいですよ。',
          choices: ['provided', 'unless', 'in case', 'even if'],
          correctIndex: 0,
          explanation: '「〜という条件であれば」と条件を付けて許可しているので provided が合います。',
          choiceNotes: [null, 'unless は「〜しない限り」で、意味が逆になります。', 'in case は「〜の場合に備えて」で、許可の条件には合いません。', 'even if は「たとえ〜でも」で、条件ではなく譲歩を表します。'],
          audioEn: 'You can stay at my place provided you keep the room clean.',
        },
        {
          id: 'u23-l2-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Suppose you ___ the lottery. What would you do first?',
          sentenceJa: '宝くじが当たったとしたら、まず何をしますか。',
          choices: ['win', 'won', 'will win', 'had won'],
          correctIndex: 1,
          explanation: '続く文が would なので、現実には起きていない仮定の話です。suppose の後ろも第2条件文の if節と同じ過去形にします。',
          choiceNotes: ['現在形は現実的な条件のときに使います。would と組み合わせるなら過去形です。', null, 'suppose の後ろに will は使えません(if節と同じルール)。', 'had won は過去への仮定で、would have done とセットで使う形です。'],
          audioEn: 'Suppose you won the lottery. What would you do first?',
        },
        {
          id: 'u23-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「価格を上げないという条件で、契約を更新します」と言いたいとき。',
          choices: [
            'We will renew the contract on condition that you will not raise the price.',
            "We will renew the contract on condition that you don't raise the price.",
            'We will renew the contract on condition to not raise the price.',
            'We renewed the contract on condition that you did not raise the price.',
          ],
          correctIndex: 1,
          explanation: 'on condition that の後ろは if節と同じで、未来のことでも現在形を使います。',
          choiceNotes: ['条件を表す節の中では will を使いません。', null, 'on condition の後ろは to不定詞ではなく that + 文を続けます。', 'これから更新する話なので、過去形では場面に合いません。'],
          audioEn: "We will renew the contract on condition that you don't raise the price.",
        },
        {
          id: 'u23-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Provided that the weather is good, the ceremony will be held outside.',
            'Suppose she said no. What would you do then?',
            'You can join the trip on condition that you pay for yourself.',
            'Providing you will finish the report by Friday, you can leave early today.',
          ],
          correctIndex: 3,
          explanation: 'providing(= provided)の後ろは条件節なので will は使えません。正しくは Providing you finish the report by Friday です。',
          choiceNotes: ['正しい文です。provided that + 現在形で未来の条件を表しています。', '正しい文です。suppose + 過去形で仮定を持ちかけています。', '正しい文です。on condition that + 現在形です。', null],
          audioEn: 'Providing you finish the report by Friday, you can leave early today.',
        },
        {
          id: 'u23-l2-q5',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'You may use the meeting room ___ you clean it up afterwards.',
          sentenceJa: 'あとで片付けてくれるという条件であれば、会議室を使ってかまいません。',
          choices: [
            'in case',
            'as though',
            'provided that',
            'even if',
          ],
          correctIndex: 2,
          explanation: 'provided that は「〜という条件であれば」と条件を強く打ち出す表現で、if より許可の条件を明確にします。',
          choiceNotes: ['in case は「〜する場合に備えて」で、許可の条件を示しません。', 'as though は「まるで〜のように」で、条件表現ではありません。', null, 'even if は「たとえ〜でも」という譲歩で、条件を付ける文にはなりません。'],
          audioEn: 'You may use the meeting room provided that you clean it up afterwards.',
        },
        {
          id: 'u23-l2-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「仮に宝くじが当たったとしたら、あなたは何をしますか」と相手に仮の話を持ちかけるとき。',
          choices: [
            'Supposing you won the lottery, what would you do with the money?',
            'Supposing you win the lottery, what will you have done with the money?',
            'Supposing you had won the lottery, what would you do with the money?',
            'Supposing you would win the lottery, what did you do with the money?',
          ],
          correctIndex: 0,
          explanation: 'supposing は「もし〜だとしたら」と仮の話を持ちかける表現です。現在の非現実の仮定なので過去形 won、主節は would do にします。',
          choiceNotes: [null, '現在形と未来完了の組み合わせでは、仮の話を持ちかけるニュアンスになりません。', 'had won は過去の非現実なので、主節も would have done にそろえる必要があります。', '条件節に would は置かず、主節も過去形では意味が通りません。'],
          audioEn: 'Supposing you won the lottery, what would you do with the money?',
        },
        {
          id: 'u23-l2-q7',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The bank approved the loan ___ that the company submit a detailed business plan.',
          sentenceJa: 'その会社が詳細な事業計画を提出することを条件に、銀行は融資を承認しました。',
          choices: [
            'in case',
            'on condition',
            'as long',
            'supposing',
          ],
          correctIndex: 1,
          explanation: 'on condition that は契約や交渉で使うフォーマルな条件表現です。that節の中では動詞の原形を使うこともあります。',
          choiceNotes: ['in case that という形は使いません。in case のあとは節をそのまま続けます。', null, 'as long のあとには as が必要で、as long as that という形にはなりません。', 'supposing that は仮の話を持ちかける表現で、契約条件の提示には合いません。'],
          audioEn: 'The bank approved the loan on condition that the company submit a detailed business plan.',
        },
        {
          id: 'u23-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Provided that the weather stays fine, we will hold the ceremony outdoors.',
            'Suppose your flight was cancelled tomorrow, what would you do?',
            'You can borrow my car providing you fill up the tank before returning it.',
            'I will lend you the money on condition that you will pay me back by June.',
          ],
          correctIndex: 3,
          explanation: 'on condition that の節は if節と同じルールで、未来のことでも will を使わず現在形にします。正しくは you pay me back by June です。',
          choiceNotes: ['正しい文です。provided that のあとは未来のことでも現在形にします。', '正しい文です。suppose のあとに過去形を置いて仮の話を持ちかけています。', '正しい文です。providing は provided と同じように使えます。', null],
          audioEn: 'I will lend you the money on condition that you pay me back by June.',
        },
        {
          id: 'u23-l2-q9',
          prompt: '次の文の意味として最も近いものを選んでください。',
          sentence: 'You are welcome to stay with us as long as you do not smoke inside the house.',
          choices: [
            '家の中でたばこを吸わない限り、うちに泊まってかまいません。',
            '家の中でたばこを吸っている間だけ、うちに泊まれます。',
            '家の中でたばこを吸うことになるので、泊まらないでください。',
            'たばこを吸う人だけが、うちに泊まれます。',
          ],
          correctIndex: 0,
          explanation: 'as long as は「〜する限りは」という条件を表します。ここでは滞在を認める条件を述べています。',
          choiceNotes: [null, 'as long as は時間の長さではなく条件を表しています。', '歓迎する文なので、断っているわけではありません。', '条件は「吸わないこと」であって、喫煙者に限定する文ではありません。'],
          audioEn: 'You are welcome to stay with us as long as you do not smoke inside the house.',
        },
        {
          id: 'u23-l2-q10',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'Take an umbrella with you ___ it rains on the way home.',
          sentenceJa: '帰り道で雨が降る場合に備えて、傘を持って行きなさい。',
          choices: [
            'provided that',
            'in case',
            'on condition that',
            'unless',
          ],
          correctIndex: 1,
          explanation: 'in case は「〜する場合に備えて」と、あらかじめ備える理由を示します。条件を付けて許可する provided that とは役割が違います。',
          choiceNotes: ['provided that は「〜という条件であれば」で、備えの理由にはなりません。', null, 'on condition that は契約の条件を示す表現で、この文には合いません。', 'unless は「〜でない限り」で、意味が逆になります。'],
          audioEn: 'Take an umbrella with you in case it rains on the way home.',
        },
      ],
      summary: [
        'provided / providing (that) は「〜という条件であれば」。if より条件を強く打ち出す、やや硬めの表現。',
        'on condition that は契約・交渉向きのフォーマルな条件表現。',
        'suppose / supposing は「もし〜だとしたら」と仮の話を持ちかける。疑問文とよく組み合わせる。',
        'どの表現も中身は if節と同じルール。条件節に will は入れず、非現実の仮定なら過去形。',
      ],
    },
    {
      id: 'u23-l3',
      unitId: 'u23',
      level: 'B2',
      title: "would rather / it's time",
      objective: "would rather と It's time の後ろの動詞の形を正しく選び、希望や催促を控えめに伝えられるようになります。",
      minutes: 10,
      prereqs: ['u23-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'would rather は「どちらかと言えばこっち」',
          body:
            "**would rather + 動詞の原形**で「(どちらかと言えば)〜したい」という自分の好みを表します。会話では I'd rather と短縮するのが普通です。\n\n- I'd rather stay home tonight.(今夜はむしろ家にいたい)\n- 比較の相手は than: I'd rather walk than take a taxi.\n- 否定は would rather **not**: I'd rather not talk about it.\n\nwant to よりも「選べるならこっち」という比較のニュアンスが出る、控えめで大人な言い方です。",
        },
        {
          type: 'contrast',
          title: '自分がするのか、人にしてほしいのか',
          left: {
            label: 'would rather + 原形(自分がする)',
            items: [
              { en: "I'd rather stay home tonight.", ja: '今夜はむしろ家にいたいです。', highlight: 'stay' },
              { en: "I'd rather not go out in this rain.", ja: 'この雨の中は出かけたくないです。', highlight: 'not go' },
            ],
            pointJa: '自分の行動には動詞の原形',
          },
          right: {
            label: 'would rather + 人 + 過去形(人にしてほしい)',
            items: [
              { en: "I'd rather you stayed home tonight.", ja: '今夜はあなたに家にいてほしいです。', highlight: 'stayed' },
              { en: "I'd rather you didn't go out in this rain.", ja: 'この雨の中は出かけないでほしいです。', highlight: "didn't go" },
            ],
            pointJa: '別の人の行動には過去形(仮定法)',
          },
          note: '後ろに「別の主語」が入った瞬間、動詞は過去形になります。形は過去でも意味は現在・未来です。',
        },
        {
          type: 'explanation',
          title: "It's time + 過去形",
          body:
            "**It's time + 主語 + 過去形**は「もう〜していい時間だ(なのにまだしていない)」という軽い催促を表します。\n\n- It's time you went to bed.(もう寝る時間だよ)\n\n過去形を使いますが、過去の話ではありません。「まだ寝ていない」現実とのずれを過去形で表す、仮定法の仲間です。\n\n- 強調するなら It's **high** time / It's **about** time\n- 単に「〜する時間だ」と言うだけなら to不定詞も使えます: It's time to go.(相手への催促のニュアンスは弱まります)",
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: "I'd rather walk to the office than squeeze onto a crowded morning train.", ja: '混み合った朝の電車に押し込まれるより、会社まで歩きたいです。', highlight: 'rather walk to the office than' },
            { en: "I'd rather not talk about the results until everyone has had time to read them.", ja: '全員が目を通す時間を持つまでは、結果について話したくないのですが。', highlight: 'rather not talk' },
            { en: "I'd rather you told me the truth now, even if it is bad news.", ja: 'たとえ悪い知らせでも、今は本当のことを話してほしいのですが。', highlight: 'told', note: '主語 you が入ったので動詞は過去形。' },
            { en: 'Would you rather work from home or come to the office?', ja: '在宅勤務と出社、どちらがいいですか。', highlight: 'Would you rather' },
            { en: "It's time we left. The last train leaves at eleven.", ja: 'もう出る時間です。終電は11時なので。', highlight: 'time we left' },
            { en: "It's high time you cleaned your room, because your guests arrive tomorrow morning.", ja: '明日の朝にお客さんが来るのだから、いいかげん部屋を片付ける時間ですよ。', highlight: 'high time you cleaned' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u23-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: "I'd rather ___ at home than go to the party.",
          sentenceJa: 'パーティーに行くより、家にいたいです。',
          choices: ['to stay', 'stay', 'staying', 'stayed'],
          correctIndex: 1,
          explanation: '自分の行動を表す would rather の後ろは動詞の原形です。',
          choiceNotes: ['would rather の後ろに to不定詞は使えません。', null, '-ing 形は使えません。原形を続けます。', '過去形になるのは would rather の後ろに別の主語が入るときだけです。'],
          audioEn: "I'd rather stay at home than go to the party.",
        },
        {
          id: 'u23-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: "I'd rather you ___ anyone about this yet.",
          sentenceJa: 'このことはまだ誰にも言わないでほしいのですが。',
          choices: ["don't tell", "didn't tell", "won't tell", 'not tell'],
          correctIndex: 1,
          explanation: 'would rather の後ろに別の主語(you)が来ると、動詞は過去形になります。形は過去でも「これから」の話です。',
          choiceNotes: ['別の主語が入るときは現在形ではなく過去形を使います。', null, 'would rather の節の中で will は使いません。', "原形が使えるのは主語が入らないとき(I'd rather not tell)だけです。"],
          audioEn: "I'd rather you didn't tell anyone about this yet.",
        },
        {
          id: 'u23-l3-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: "It's already midnight. It's time the children ___ to bed.",
          sentenceJa: 'もう夜中の12時です。子どもたちはもう寝る時間です。',
          choices: ['go', 'went', 'will go', 'have gone'],
          correctIndex: 1,
          explanation: "It's time + 主語の後ろは過去形を使います。「もうすべき時間なのに、まだしていない」というニュアンスです。",
          choiceNotes: ["It's time の後ろに主語が入る場合、現在形ではなく過去形にします。", null, '未来の話に見えますが、この構文では will を使いません。', '完了形は使いません。単純な過去形にします。'],
          audioEn: "It's already midnight. It's time the children went to bed.",
        },
        {
          id: 'u23-l3-q4',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: "I'd rather you paid by card.",
          choices: [
            '私はカードで払いたい。',
            'あなたにカードで払ってほしい。',
            'あなたは以前カードで払った。',
            'カードで払うべきだった(後悔)。',
          ],
          correctIndex: 1,
          explanation: 'would rather + 人 + 過去形は「その人に〜してほしい」という現在・未来への希望です。paid は過去形ですが過去の話ではありません。',
          choiceNotes: ["「自分が払いたい」なら you を入れずに I'd rather pay by card. と言います。", null, '過去形ですが過去の出来事を述べているのではありません。', '後悔を表すのは should have paid のような形です。'],
          audioEn: "I'd rather you paid by card.",
        },
        {
          id: 'u23-l3-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: "It's getting late. I'd rather we ___ this discussion tomorrow morning.",
          sentenceJa: 'もう遅い時間です。この話し合いは明日の朝に続けたいのですが。',
          choices: [
            'continue',
            'continued',
            'to continue',
            'will continue',
          ],
          correctIndex: 1,
          explanation: 'would rather のあとに別の主語(we)が入ると、動詞は過去形になります。形は過去でも、指しているのは明日の話です。',
          choiceNotes: ['原形が使えるのは主語を挟まないとき(I would rather continue)だけです。', null, 'would rather のあとに to不定詞は続けられません。', 'この構文の節の中では will を使いません。'],
          audioEn: "It's getting late. I'd rather we continued this discussion tomorrow morning.",
        },
        {
          id: 'u23-l3-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「もういいかげん、この問題について真剣に話し合う時期だ」と強めに言いたいとき。',
          choices: [
            'It is high time we discuss this problem seriously.',
            'It is high time we discussed this problem seriously.',
            'It is high time we will discuss this problem seriously.',
            'It is high time we have discussed this problem seriously.',
          ],
          correctIndex: 1,
          explanation: "It's high time + 主語のあとは過去形にします。「もうその時期なのに、まだしていない」という現実とのずれを過去形で表します。",
          choiceNotes: ['主語が入る場合は現在形ではなく過去形にします。', null, 'この構文では will を使いません。', '完了形ではなく単純な過去形を使います。'],
          audioEn: 'It is high time we discussed this problem seriously.',
        },
        {
          id: 'u23-l3-q7',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: "I'd rather not comment on the results until the official report comes out.",
          choices: [
            '公式な報告が出るまでは結果について意見を述べたくない。',
            '公式な報告が出たあとで、必ず結果について意見を述べる。',
            '公式な報告について、すでに意見を述べてしまった。',
            '公式な報告が出るまで結果を知らないままでいたい。',
          ],
          correctIndex: 0,
          explanation: 'would rather not は「どちらかと言えば〜したくない」という控えめな拒否を表します。ここでは意見を述べることを避けています。',
          choiceNotes: [null, 'あとで必ず述べるとは言っていません。控えめに今は避けているだけです。', 'これから述べるかどうかの話で、すでに述べたわけではありません。', '避けているのは意見を述べることで、結果を知ることではありません。'],
          audioEn: "I'd rather not comment on the results until the official report comes out.",
        },
        {
          id: 'u23-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            "I'd rather you didn't post those photos on social media.",
            "It's about time this company took environmental issues seriously.",
            'Would you rather meet in person or discuss everything by email?',
            "I'd rather to work from home than commute for two hours every day.",
          ],
          correctIndex: 3,
          explanation: 'would rather のあとは動詞の原形です。to は付けません。正しくは I would rather work from home than commute です。',
          choiceNotes: ['正しい文です。別の主語 you が入ったので過去形になっています。', "正しい文です。It's about time のあとは過去形にします。", '正しい文です。選択を尋ねる Would you rather A or B の形です。', null],
          audioEn: "I'd rather work from home than commute for two hours every day.",
        },
        {
          id: 'u23-l3-q9',
          prompt: '空所に入る形を選んでください。',
          sentence: "I'd rather you ___ me before making such an important decision.",
          sentenceJa: 'そんな重要な決定をする前に、私に相談してほしかったのですが。',
          choices: [
            'consult',
            'consulted',
            'will consult',
            'to consult',
          ],
          correctIndex: 1,
          explanation: 'would rather のあとに別の主語 you が入るので過去形 consulted にします。相手の行動への希望を控えめに伝える形です。',
          choiceNotes: ['原形になるのは主語を挟まないときだけです。', null, 'この構文の節の中では will を使いません。', 'would rather のあとに to不定詞は続けられません。'],
          audioEn: "I'd rather you consulted me before making such an important decision.",
        },
        {
          id: 'u23-l3-q10',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: "A: It's time to leave.   B: It's time we left.",
          choices: [
            'Aは単に出発の時刻を告げ、Bは「まだ出ていない」という催促を含む。',
            'Aは催促で、Bは単に時刻を告げている。',
            'AもBも過去に出発したことを表す。',
            'Aは未来、Bは過去の出来事を表す。',
          ],
          correctIndex: 0,
          explanation: "It's time to do は時刻を述べるだけですが、It's time + 主語 + 過去形は「もうすべき時間なのにまだしていない」という軽い催促のニュアンスを持ちます。",
          choiceNotes: [null, '催促のニュアンスを持つのは過去形を使う B のほうです。', 'どちらも過去の出来事を述べてはいません。', 'B の left は過去形ですが、指しているのは今の状況です。'],
          audioEn: "It's time to leave. It's time we left.",
        },
      ],
      summary: [
        'would rather + 動詞の原形 = 「(自分が)むしろ〜したい」。比較は than、否定は would rather not。',
        'would rather + 人 + 過去形 = 「(人に)〜してほしい」。過去形でも現在・未来の話。',
        "It's time + 主語 + 過去形 = 「もう〜していい時間だ(のにまだしていない)」。",
        'これらの過去形は時間ではなく「現実とのずれ」を表す仮定法の仲間。',
      ],
    },
  ],
}
