import type { GrammarUnit } from '../../types'

// U24 使役と知覚

export const u24: GrammarUnit = {
  id: 'u24',
  level: 'B2',
  title: '使役と知覚',
  lessons: [
    {
      id: 'u24-l1',
      unitId: 'u24',
      level: 'B2',
      title: 'have / get something done',
      objective: '「(お金を払って)〜してもらう」「〜される」を have / get + 物 + 過去分詞で表現できるようになります。',
      minutes: 10,
      prereqs: ['u23-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '「した」のか「してもらった」のか',
          body:
            '日本語の「髪を切った」は、自分で切ったのか美容院で切ってもらったのか、区別せずに使えます。英語はここをはっきり分けます。\n\n- I cut my hair.(自分でハサミを持って切った)\n- I **had my hair cut**.(切ってもらった)\n\n「してもらった」を表すのが **have + 物 + 過去分詞** の形です。美容院・修理・クリーニングなど、**プロやサービスに作業を頼む**場面で毎日のように使われます。',
        },
        {
          type: 'structure',
          title: '「してもらう」の語順',
          parts: [
            { label: '主語', text: 'I' },
            { label: 'have / had', text: 'had' },
            { label: '物', text: 'my hair' },
            { label: '過去分詞', text: 'cut' },
          ],
          caption: '「物」は「される」側なので過去分詞。had cut my hair と語順を変えると過去完了(自分で切った)になってしまうので、順番が命です。',
        },
        {
          type: 'explanation',
          title: 'get でも言える・「される」も表せる',
          body:
            '**get + 物 + 過去分詞** も同じ意味で使えます。have より少しくだけた、会話的な響きです。\n\n- I **got my watch repaired**.(腕時計を修理してもらった)\n\nもうひとつ大事な使い方があります。have + 物 + 過去分詞は、頼んでいないのに「**〜される**」という被害も表します。\n\n- I **had my wallet stolen** on the train.(電車で財布を盗まれた)\n\n盗んでもらったわけではありません。「してもらった」のか「された」のかは文脈で判断します。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I had my hair cut yesterday because I have a job interview on Friday.', ja: '金曜日に就職面接があるので、昨日、髪を切ってもらいました。', highlight: 'had my hair cut' },
            { en: 'We got the kitchen repainted last month and it looks much brighter now.', ja: '先月キッチンを塗り直してもらったら、今はずっと明るく見えます。', highlight: 'got the kitchen repainted' },
            { en: 'I need to have this suit cleaned before the wedding.', ja: '結婚式の前にこのスーツをクリーニングに出す必要があります。', highlight: 'have this suit cleaned' },
            { en: 'Where do you get your car serviced when the warranty has already expired?', ja: '保証期間が切れてしまったあと、車の点検はどこでしてもらっていますか。', highlight: 'get your car serviced' },
            { en: 'He had his bag stolen at the airport while he was checking the departure board.', ja: '彼は出発案内板を見ている間に、空港でかばんを盗まれました。', highlight: 'had his bag stolen', note: '依頼ではなく被害を表す使い方です。' },
          ],
        },
        {
          type: 'contrast',
          title: '自分でする vs してもらう',
          left: {
            label: '自分でする(ふつうの文)',
            items: [
              { en: 'I fixed my bike.', ja: '自分で自転車を直しました。', highlight: 'fixed my bike' },
              { en: 'She painted the fence.', ja: '彼女は自分でフェンスを塗りました。', highlight: 'painted the fence' },
            ],
            pointJa: '主語が自分で作業する',
          },
          right: {
            label: 'してもらう(have / get + 物 + 過去分詞)',
            items: [
              { en: 'I had my bike fixed.', ja: '自転車を直してもらいました。', highlight: 'had my bike fixed' },
              { en: 'She got the fence painted.', ja: '彼女はフェンスを塗ってもらいました。', highlight: 'got the fence painted' },
            ],
            pointJa: '作業をするのは他の人',
          },
          note: '日本語ではどちらも「直した」「塗った」と言えてしまうので、英語にするときは「実際に手を動かしたのは誰か」を意識しましょう。',
        },
      ],
      quiz: [
        {
          id: 'u24-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'She has her nails ___ once a month.',
          sentenceJa: '彼女は月に一度ネイルをしてもらいます。',
          choices: ['do', 'done', 'doing', 'to do'],
          correctIndex: 1,
          explanation: 'ネイルは「される」側なので過去分詞 done を使います。have + 物 + 過去分詞の形です。',
          choiceNotes: ['原形を使うのは have + 人 + 原形(人に〜させる)のときです。nails は動作をする側ではありません。', null, '-ing 形は「物がされる」関係を表せません。', 'have のあとに to不定詞は使えません。'],
          audioEn: 'She has her nails done once a month.',
        },
        {
          id: 'u24-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「先週、歯医者で歯を抜いてもらいました」と言いたいとき。',
          choices: [
            'I had pulled out my tooth last week.',
            'I had my tooth pulled out last week.',
            'I had my tooth pull out last week.',
            'I pulled my tooth out at the dentist last week.',
          ],
          correctIndex: 1,
          explanation: '「してもらう」は have + 物 + 過去分詞。had my tooth pulled out の語順にします。',
          choiceNotes: ['had pulled out は過去完了で、「自分で抜いてしまっていた」という別の意味になります。', null, '歯は「抜かれる」側なので、原形 pull ではなく過去分詞 pulled にします。', 'これは「自分で歯を抜いた」という意味になってしまいます。'],
          audioEn: 'I had my tooth pulled out last week.',
        },
        {
          id: 'u24-l1-q3',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'Emi had her bike stolen in front of the supermarket.',
          choices: [
            'エミは誰かに頼んで自転車を運んでもらった。',
            'エミはスーパーの前で自転車を盗まれた。',
            'エミはスーパーの前で自転車を盗んだ。',
            'エミの自転車は盗まれずにすんだ。',
          ],
          correctIndex: 1,
          explanation: 'have + 物 + 過去分詞は「してもらう」だけでなく「〜される」という被害も表します。盗難の話なので被害の意味です。',
          choiceNotes: ['stolen は「盗まれる」で、運んでもらう話ではありません。', null, '盗んだのはエミではありません。her bike が stolen(盗まれる)側です。', '肯定文なので、実際に盗まれています。'],
          audioEn: 'Emi had her bike stolen in front of the supermarket.',
        },
        {
          id: 'u24-l1-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I got my eyes tested last month.',
            'We had the contract checked by a lawyer.',
            'He got his hair cutting at a new salon.',
            'They had their house painted before selling it.',
          ],
          correctIndex: 2,
          explanation: '髪は「切られる」側なので、get + 物 + 過去分詞で got his hair cut にします。',
          choiceNotes: ['正しい文です。get + 物 + 過去分詞の形です。', '正しい文です。by 〜 で作業した人も示せます。', null, '正しい文です。売る前に家を塗ってもらった、という意味です。'],
          audioEn: 'He got his hair cut at a new salon.',
        },
        {
          id: 'u24-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I need to ___ before the interview on Monday.',
          sentenceJa: '月曜日の面接の前に、このスーツをクリーニングに出す必要があります。',
          choices: [
            'have cleaned this suit',
            'have this suit cleaned',
            'have this suit clean',
            'have cleaning this suit',
          ],
          correctIndex: 1,
          explanation: '「〜してもらう」は have + 物 + 過去分詞の語順です。物が先、過去分詞があとになります。',
          choiceNotes: ['過去分詞と目的語の順序が逆です。物を先に置きます。', null, 'スーツは「洗われる」側なので原形ではなく過去分詞にします。', 'have のあとに -ing は続けられません。'],
          audioEn: 'I need to have this suit cleaned before the interview on Monday.',
        },
        {
          id: 'u24-l1-q6',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'She had her wallet stolen while she was shopping downtown.',
          choices: [
            '彼女は誰かに財布を盗ませた。',
            '彼女は買い物中に財布を盗まれた。',
            '彼女は盗まれた財布を取り戻した。',
            '彼女は自分で財布を隠した。',
          ],
          correctIndex: 1,
          explanation: 'have + 物 + 過去分詞は「してもらう」だけでなく、望まない出来事を受けたことも表します。文脈から被害だと判断します。',
          choiceNotes: ['盗ませたのではありません。被害を受けたという意味です。', null, '取り戻したという情報はこの文にはありません。', '隠したのではなく、盗まれています。'],
          audioEn: 'She had her wallet stolen while she was shopping downtown.',
        },
        {
          id: 'u24-l1-q7',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「来月、家の窓を全部交換してもらう予定です」と言いたいとき。',
          choices: [
            'We are getting all the windows replace next month.',
            'We are getting replaced all the windows next month.',
            'We are getting all the windows replaced next month.',
            'We are getting all the windows to replace next month.',
          ],
          correctIndex: 2,
          explanation: 'get + 物 + 過去分詞の語順です。窓は「交換される」側なので replaced にします。',
          choiceNotes: ['窓は交換される側なので原形ではなく過去分詞にします。', '物より先に過去分詞を置くことはできません。', null, 'この構文では to不定詞は使いません。'],
          audioEn: 'We are getting all the windows replaced next month.',
        },
        {
          id: 'u24-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I had my passport renewed at the city office last week.',
            'They are having their garden redesigned by a professional.',
            'You should get your eyes checked at least once a year.',
            'He got his tooth pull at the dentist yesterday morning.',
          ],
          correctIndex: 3,
          explanation: '歯は「抜かれる」側なので過去分詞にします。正しくは He got his tooth pulled です。',
          choiceNotes: ['正しい文です。パスポートは更新してもらうものです。', '正しい文です。by で作業者を示しています。', '正しい文です。目は検査してもらうものです。', null],
          audioEn: 'He got his tooth pulled at the dentist yesterday morning.',
        },
        {
          id: 'u24-l1-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: I painted the fence.   B: I had the fence painted.',
          choices: [
            'Aは自分で塗り、Bは誰かに塗ってもらった。',
            'Aは誰かに塗ってもらい、Bは自分で塗った。',
            'どちらも自分で塗ったことを表す。',
            'どちらも塗る予定があることを表す。',
          ],
          correctIndex: 0,
          explanation: 'have + 物 + 過去分詞は、主語自身ではなく誰かに作業してもらったことを表します。単純な過去形は自分でしたという意味です。',
          choiceNotes: [null, '手配を表すのは have を使う B のほうです。', 'B は自分で塗ったことを表しません。', 'どちらもすでに終わったことを述べています。'],
          audioEn: 'I painted the fence. I had the fence painted.',
        },
        {
          id: 'u24-l1-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Where do you usually ___ when it breaks down?',
          sentenceJa: '車が故障したとき、いつもどこで修理してもらっていますか。',
          choices: [
            'get repaired your car',
            'get your car repair',
            'repair getting your car',
            'get your car repaired',
          ],
          correctIndex: 3,
          explanation: 'get + 物 + 過去分詞の語順です。your car を先に置き、そのあとに repaired を続けます。',
          choiceNotes: ['過去分詞と目的語の順序が逆です。', '車は修理される側なので過去分詞にします。', '語順が崩れており、文として成り立ちません。', null],
          audioEn: 'Where do you usually get your car repaired when it breaks down?',
        },
      ],
      summary: [
        'have + 物 + 過去分詞 = 「(お金を払って)〜してもらう」。物は「される」側なので過去分詞。',
        'get + 物 + 過去分詞も同じ意味で、より会話的。',
        '語順が重要。had my hair cut は「切ってもらった」、had cut my hair は過去完了で「自分で切っていた」。',
        'have + 物 + 過去分詞は「〜される」という被害(had my wallet stolen)も表す。',
      ],
    },
    {
      id: 'u24-l2',
      unitId: 'u24',
      level: 'B2',
      title: 'make / let / have / get + 人 + 動詞',
      objective: 'make(強制)・let(許可)・have(依頼)・get(説得)をニュアンスで使い分け、それぞれ正しい動詞の形で使役文を作れるようになります。',
      minutes: 12,
      prereqs: ['u24-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '「させる」にも強さのレベルがある',
          body:
            '日本語の「〜させる」「〜してもらう」を英語にするときは、**相手にどれくらい選択の自由があるか**で動詞を選びます。\n\n- **make**: 強制。相手に選択肢はない\n- **have**: 依頼。仕事や役割として当然のことをしてもらう(部下・店員・業者など)\n- **get**: 説得・働きかけ。頼み込んだり工夫したりして、なんとかしてもらう\n- **let**: 許可。相手がしたがっていることを許す\n\n同じ「宿題をやらせた」でも、make なら「無理やり」、get なら「うまく仕向けて」というまったく違う場面が伝わります。',
        },
        {
          type: 'structure',
          title: '使役の語順',
          parts: [
            { label: '主語', text: 'My boss' },
            { label: '使役動詞', text: 'made' },
            { label: '人', text: 'me' },
            { label: '動詞の原形', text: 'stay late' },
          ],
          caption: 'make / let / have は人のあとに動詞の原形。to を入れないのが最大のポイントです。get だけは to不定詞(got me to stay late)を使います。',
        },
        {
          type: 'table',
          title: '4つの使役動詞の使い分け',
          headers: ['動詞', '人のあとの形', 'ニュアンス', '例'],
          rows: [
            ['make', '動詞の原形', '強制(選択肢なし)', 'made me wait'],
            ['have', '動詞の原形', '依頼(役割として当然)', 'had the clerk check it'],
            ['get', 'to + 動詞の原形', '説得・働きかけ', 'got him to help me'],
            ['let', '動詞の原形', '許可', 'let me leave early'],
          ],
        },
        {
          type: 'explanation',
          title: 'get だけ to、受け身では make にも to',
          body:
            '形の例外は2つだけ覚えれば十分です。\n\n1. **get は to不定詞**: I got him **to help** me.(× got him help)。「説得して〜してもらう」という一手間が、to の分の距離感に表れていると考えると覚えやすいです。\n\n2. **make の受動態では to が現れる**: He **was made to apologize**.(彼は謝らされた)。能動態では made him apologize と to なしなのに、受け身になると to が復活します。\n\nなお、let はふつう受動態にせず、be allowed to(〜することを許される)で言い換えます。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The teacher made us clean the classroom before we were allowed to go home.', ja: '先生は、帰宅を許す前に私たちに教室を掃除させました。', highlight: 'made us clean' },
            { en: 'My parents let me stay out late on weekends.', ja: '両親は週末は遅くまで外にいさせてくれます。', highlight: 'let me stay' },
            { en: "I'll have my assistant send you the file as soon as the meeting is over.", ja: '会議が終わり次第、アシスタントにファイルを送らせます。', highlight: 'have my assistant send' },
            { en: 'How did you get your kids to eat vegetables?', ja: 'どうやって子どもたちに野菜を食べさせたのですか。', highlight: 'get your kids to eat' },
            { en: 'He was made to wait outside for an hour before anyone came to explain the delay.', ja: '誰かが遅れの理由を説明しに来るまで、彼は1時間外で待たされました。', highlight: 'was made to wait', note: '受動態では to が現れます。' },
          ],
        },
        {
          type: 'contrast',
          title: 'make(強制)vs let(許可)',
          left: {
            label: 'make(相手の意思に関係なく)',
            items: [
              { en: 'My mother makes me practice the piano every day.', ja: '母は毎日私にピアノを練習させます。', highlight: 'makes me practice' },
              { en: 'The movie made me cry.', ja: 'その映画で泣いてしまいました。', highlight: 'made me cry', note: '人以外が主語でも使えます。' },
            ],
            pointJa: '相手に選択肢を与えずにさせる',
          },
          right: {
            label: 'let(相手が望むことを)',
            items: [
              { en: 'My mother lets me play games after dinner.', ja: '母は夕食後にゲームをさせてくれます。', highlight: 'lets me play' },
              { en: 'Let me carry that for you.', ja: 'それ、私が持ちますよ。', highlight: 'Let me carry', note: 'Let me 〜 は「私に〜させて」という申し出の定番表現です。' },
            ],
            pointJa: '相手がしたいことを許す',
          },
          note: '日本語ではどちらも「〜させる」と訳せるので要注意。強制なのか許可なのかを考えてから動詞を選びます。どちらも後ろは動詞の原形です。',
        },
      ],
      quiz: [
        {
          id: 'u24-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The security guard made everyone ___ their bags.',
          sentenceJa: '警備員は全員にかばんを開けさせました。',
          choices: ['open', 'to open', 'opening', 'opened'],
          correctIndex: 0,
          explanation: 'make + 人 のあとは動詞の原形です。to は入れません。',
          choiceNotes: [null, 'to が現れるのは受動態(was made to open)のときだけです。', 'make のあとに -ing 形は使えません。', '過去分詞は「物がされる」関係のときの形で、ここでは everyone が開ける側です。'],
          audioEn: 'The security guard made everyone open their bags.',
        },
        {
          id: 'u24-l2-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I finally got my landlord ___ the heater.',
          sentenceJa: 'ようやく大家さんに暖房を直してもらいました。',
          choices: ['fix', 'to fix', 'fixed', 'fixing'],
          correctIndex: 1,
          explanation: '使役の get だけは 人 + to不定詞 を取ります。got my landlord to fix が正しい形です。',
          choiceNotes: ['原形でよいのは make / let / have のときです。get は to不定詞です。', null, '過去分詞は get + 物 + 過去分詞(got the heater fixed)の形で使います。ここでは大家さんという「人」が直す側です。', 'get + 人 のあとに -ing 形は使えません。'],
          audioEn: 'I finally got my landlord to fix the heater.',
        },
        {
          id: 'u24-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「父は私に自分の車を使わせてくれませんでした(許可しなかった)」と言いたいとき。',
          choices: [
            "My father didn't let me to use his car.",
            "My father didn't make me use his car.",
            "My father didn't let me use his car.",
            "My father didn't let me using his car.",
          ],
          correctIndex: 2,
          explanation: '「許可しなかった」は let の否定で表します。let + 人 + 動詞の原形です。',
          choiceNotes: ['let のあとの動詞に to は付けません。', 'make は強制なので「使うことを強制しなかった」という別の意味になります。', null, 'let のあとは原形です。-ing 形は使えません。'],
          audioEn: "My father didn't let me use his car.",
        },
        {
          id: 'u24-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'She had the students hand in their essays by noon.',
            'The doctor made him to give up smoking.',
            'I got my sister to drive me to the airport.',
            'Just let me know when you arrive.',
          ],
          correctIndex: 1,
          explanation: 'make + 人 のあとは動詞の原形です。to が現れるのは受動態(He was made to give up smoking)のときだけです。',
          choiceNotes: ['正しい文です。have + 人 + 原形で「提出させた」を表しています。', null, '正しい文です。get + 人 + to不定詞の形です。', '正しい文です。let me know は「知らせてください」の定番表現です。'],
          audioEn: 'The doctor made him give up smoking.',
        },
        {
          id: 'u24-l2-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It took a long time, but we finally got the landlord ___ the broken heater.',
          sentenceJa: '時間はかかりましたが、ようやく家主を説得して壊れた暖房を直してもらいました。',
          choices: [
            'fix',
            'to fix',
            'fixing',
            'fixed',
          ],
          correctIndex: 1,
          explanation: 'get + 人 + to不定詞の形です。make / let / have が原形を取るのに対し、get だけが to を必要とします。',
          choiceNotes: ['原形を取るのは make / let / have です。get には to が必要です。', null, '-ing 形はこの構文では使いません。', '過去分詞は物が動作を受けるときの形です。'],
          audioEn: 'It took a long time, but we finally got the landlord to fix the broken heater.',
        },
        {
          id: 'u24-l2-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼は上司に1時間外で待たされた」と受動態で言いたいとき。',
          choices: [
            'He was made wait outside for an hour by his boss.',
            'He was made to wait outside for an hour by his boss.',
            'He was let wait outside for an hour by his boss.',
            'He was had to wait outside for an hour by his boss.',
          ],
          correctIndex: 1,
          explanation: 'make の受動態では、能動態にはなかった to が現れて be made to do の形になります。',
          choiceNotes: ['受動態では原形ではなく to不定詞にします。', null, 'let は受動態にできません。be allowed to で言い換えます。', 'have も受動態のこの形では使いません。'],
          audioEn: 'He was made to wait outside for an hour by his boss.',
        },
        {
          id: 'u24-l2-q7',
          prompt: '空所に入る動詞を選んでください。',
          sentence: 'My parents never ___ me stay out after ten when I was in high school.',
          sentenceJa: '高校生のとき、両親は10時以降に外にいることを決して許してくれませんでした。',
          choices: [
            'let',
            'made',
            'got',
            'had',
          ],
          correctIndex: 0,
          explanation: '許可を表すのは let です。never と組み合わせて「許してくれなかった」という意味になります。',
          choiceNotes: [null, 'made だと「外にいることを強制した」となり、意味が通りません。', 'got なら to stay が必要で、説得のニュアンスも文脈に合いません。', 'had だと立場を使った依頼になり、許可の意味になりません。'],
          audioEn: 'My parents never let me stay out after ten when I was in high school.',
        },
        {
          id: 'u24-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The manager had the new employee attend a safety training session.',
            'That documentary made me think about how much food we waste.',
            'She let her students choose their own presentation topics.',
            'I got my brother carry the boxes up to the third floor.',
          ],
          correctIndex: 3,
          explanation: 'get + 人のあとは to不定詞にします。正しくは I got my brother to carry the boxes です。',
          choiceNotes: ['正しい文です。have + 人 + 原形で立場を使った依頼を表しています。', '正しい文です。人以外が主語でも make は使えます。', '正しい文です。let + 人 + 原形で許可を表しています。', null],
          audioEn: 'I got my brother to carry the boxes up to the third floor.',
        },
        {
          id: 'u24-l2-q9',
          prompt: '次の2文のニュアンスの違いとして正しいものを選んでください。',
          sentence: 'A: I had my assistant book the flights.   B: I got my assistant to book the flights.',
          choices: [
            'Aは立場を使った当然の依頼、Bは説得や工夫を経た依頼という響きがある。',
            'Aは説得を経た依頼、Bは強制的な命令である。',
            'Aは自分で予約し、Bは他人が予約した。',
            'どちらも許可を求めている。',
          ],
          correctIndex: 0,
          explanation: 'have は立場上あたりまえの依頼、get は相手を動かすために働きかけたという含みを持ちます。',
          choiceNotes: [null, '説得の含みを持つのは get のほうです。', 'どちらもアシスタントが予約しています。', '許可を表すのは let です。'],
          audioEn: 'I had my assistant book the flights. I got my assistant to book the flights.',
        },
        {
          id: 'u24-l2-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The coach made the whole team ___ an extra hour after the match.',
          sentenceJa: 'コーチは試合のあと、チーム全員にもう1時間練習させました。',
          choices: [
            'to practice',
            'practicing',
            'practice',
            'practiced',
          ],
          correctIndex: 2,
          explanation: 'make + 人 + 原形の形です。能動態では to を付けません。',
          choiceNotes: ['能動態の make に to は付けません。受動態のときだけ to が現れます。', '-ing 形はこの構文では使いません。', null, '過去分詞は物が動作を受けるときの形です。'],
          audioEn: 'The coach made the whole team practice an extra hour after the match.',
        },
      ],
      summary: [
        'make(強制)・have(依頼)・let(許可)は 人 + 動詞の原形。to を入れない。',
        'get(説得・働きかけ)だけは 人 + to不定詞。',
        '日本語の「させる」が強制なのか許可なのかを考えて make / let を選ぶ。',
        '受動態では to が現れる: He was made to wait. let の受け身は be allowed to で言い換える。',
      ],
    },
    {
      id: 'u24-l3',
      unitId: 'u24',
      level: 'B2',
      title: '知覚動詞 + 原形 / -ing',
      objective: 'see / hear / feel などの知覚動詞のあとの動詞を原形と -ing で使い分け、「一部始終」か「途中の一場面」かを区別して表現できるようになります。',
      minutes: 10,
      prereqs: ['u24-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '「見た・聞いた」の中身まで1文で',
          body:
            'I saw him. で終わらせず、「彼が通りを渡るのを見た」のように**見聞きした出来事の中身**まで1文で伝えられるのが知覚動詞の構文です。\n\n**知覚動詞(see / watch / hear / feel / notice)+ 人・物 + 動詞**\n\nこのときの動詞は**原形か -ing** の2択で、どちらを選ぶかで伝わる意味が変わります。使役の make / let と同じく、**to不定詞は使えません**(× I saw him to cross)。',
        },
        {
          type: 'structure',
          title: '知覚動詞の語順',
          parts: [
            { label: '主語', text: 'I' },
            { label: '知覚動詞', text: 'saw' },
            { label: '人・物', text: 'him' },
            { label: '原形 / -ing', text: 'cross / crossing the street' },
          ],
          caption: '原形なら「渡り終えるまで全部見た」、-ing なら「渡っている途中の一場面を見た」ことになります。',
        },
        {
          type: 'explanation',
          title: '原形は「全部」、-ing は「途中」',
          body:
            '- **原形**: 動作を最初から最後まで見聞きした。**完結**した出来事として伝える\n- **-ing**: 動作の**途中の様子**を見聞きした。始まりや終わりを見たかまでは、この形だけでは分からない\n\nたとえば I saw him cross the street. なら渡り終えるところまで見届けた感じ、I saw him crossing the street. なら「渡っている最中の姿を見かけた」だけです。\n\nもうひとつ、見聞きした対象が「**される**」側のときは過去分詞を使います。\n\n- I heard my name **called**.(名前が呼ばれるのを聞いた)',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I felt the floor shake twice during the night and could not get back to sleep.', ja: '夜中に床が2回揺れるのを感じて、その後は眠れませんでした。', highlight: 'shake' },
            { en: 'Did you hear the phone ring while I was taking a shower this morning?', ja: '今朝、私がシャワーを浴びている間に電話が鳴ったのが聞こえましたか。', highlight: 'ring' },
            { en: 'She noticed a man standing by the gate and quietly asked him what he wanted.', ja: '彼女は門のそばに男の人が立っているのに気づき、静かに用件を尋ねました。', highlight: 'standing' },
            { en: 'We watched the children playing in the pool for a while.', ja: '子どもたちがプールで遊んでいるのをしばらく眺めていました。', highlight: 'playing' },
            { en: 'I heard my name called from behind just as I was leaving the building.', ja: '建物を出ようとしたちょうどそのとき、後ろから名前を呼ばれるのが聞こえました。', highlight: 'called', note: '名前は「呼ばれる」側なので過去分詞です。' },
          ],
        },
        {
          type: 'contrast',
          title: '原形 vs -ing',
          left: {
            label: '原形(一部始終)',
            items: [
              { en: 'I saw him cross the street.', ja: '彼が通りを渡るのを(渡り終えるまで)見ました。', highlight: 'cross' },
              { en: 'We watched the plane take off.', ja: '飛行機が離陸するのを見届けました。', highlight: 'take off' },
            ],
            pointJa: '動作の始まりから終わりまで',
          },
          right: {
            label: '-ing(途中の一場面)',
            items: [
              { en: 'I saw him crossing the street.', ja: '彼が通りを渡っているところを見かけました。', highlight: 'crossing' },
              { en: 'I heard the baby crying in the next room.', ja: '隣の部屋で赤ちゃんが泣いているのが聞こえました。', highlight: 'crying' },
            ],
            pointJa: '進行中の動作の一部だけ',
          },
          note: '泣き声のように「いつ始まっていつ終わったか分からない」ものは -ing が自然です。逆に、離陸のように区切りのはっきりした短い動作は原形とよく合います。',
        },
      ],
      quiz: [
        {
          id: 'u24-l3-q1',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'I saw Ken crossing the street.',
          choices: [
            'ケンが通りを渡り終えるまで見ていた。',
            'ケンが通りを渡っている途中の姿を見かけた。',
            'ケンはこれから通りを渡るところだった。',
            'ケンが通りを渡るのを見損ねた。',
          ],
          correctIndex: 1,
          explanation: '-ing は進行中の動作の一場面を見たことを表します。渡り終えたかどうかまでは分かりません。',
          choiceNotes: ['一部始終を見たと言いたいなら原形 cross を使います。', null, '「これから渡る」はまだ始まっていない動作なので、進行中を表す -ing と合いません。', 'saw とあるので実際に見ています。'],
          audioEn: 'I saw Ken crossing the street.',
        },
        {
          id: 'u24-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'As I walked past the music room, I heard someone ___ the violin.',
          sentenceJa: '音楽室の前を通りかかったとき、誰かがバイオリンを弾いているのが聞こえました。',
          choices: ['play', 'playing', 'to play', 'played'],
          correctIndex: 1,
          explanation: '通り過ぎる間に耳にしたのは演奏の途中の一場面なので、-ing の playing が合います。',
          choiceNotes: ['原形は演奏を最初から最後まで聞いた場合の形です。通りかかっただけの場面には合いません。', null, '知覚動詞のあとに to不定詞は使えません。', '過去分詞は対象が「される」側のときに使います。someone は弾く側です。'],
          audioEn: 'As I walked past the music room, I heard someone playing the violin.',
        },
        {
          id: 'u24-l3-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「昨夜、隣人が車で出かけるのを(出発するまで)見ました」と言いたいとき。',
          choices: [
            'I saw my neighbor to drive away last night.',
            'I saw my neighbor drove away last night.',
            'I saw my neighbor drive away last night.',
            'I saw my neighbor driven away last night.',
          ],
          correctIndex: 2,
          explanation: '出発という動作を最後まで見たので、知覚動詞 + 人 + 動詞の原形を使います。',
          choiceNotes: ['知覚動詞のあとに to不定詞は使えません。', '知覚動詞のあとに過去形は続けられません。原形にします。', null, '過去分詞は対象が「される」側のときの形です。隣人は運転する側です。'],
          audioEn: 'I saw my neighbor drive away last night.',
        },
        {
          id: 'u24-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I felt someone tap me on the shoulder.',
            'We heard the rain falling on the roof all night.',
            'She watched her son played soccer.',
            'I heard my name called at the reception desk.',
          ],
          correctIndex: 2,
          explanation: '知覚動詞のあとの動詞は原形か -ing で、過去形は使えません。watched her son play(または playing)soccer が正しい形です。',
          choiceNotes: ['正しい文です。肩を叩く短い動作を原形で表しています。', '正しい文です。一晩中続く雨音を -ing で表しています。', null, '正しい文です。名前は「呼ばれる」側なので過去分詞 called です。'],
          audioEn: 'She watched her son play soccer.',
        },
        {
          id: 'u24-l3-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'From the window I saw the postman ___ a package on the doorstep and drive away.',
          sentenceJa: '窓から、郵便配達員が玄関先に荷物を置いて走り去るのが見えました。',
          choices: [
            'leaving',
            'to leave',
            'left',
            'leave',
          ],
          correctIndex: 3,
          explanation: '置いてから走り去るまでの一連の動作を最後まで見ているので、原形 leave を使います。',
          choiceNotes: ['-ing は進行中の一場面を切り取る形で、走り去るまでの一連には合いません。', '知覚動詞のあとに to不定詞は使いません。', '知覚が過去でも、後ろの動詞は過去形にしません。', null],
          audioEn: 'From the window I saw the postman leave a package on the doorstep and drive away.',
        },
        {
          id: 'u24-l3-q6',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: I saw her cross the bridge.   B: I saw her crossing the bridge.',
          choices: [
            'Aは渡り切るまで見た、Bは渡っている途中を見かけた。',
            'Aは渡っている途中を見かけた、Bは渡り切るまで見た。',
            'Aは見えなかった、Bは見えた。',
            'どちらも彼女が橋を渡らなかったことを表す。',
          ],
          correctIndex: 0,
          explanation: '原形は動作の始まりから終わりまでをひとまとまりで捉え、-ing は進行中の一場面を捉えます。',
          choiceNotes: [null, '進行中の一場面を表すのは -ing のほうです。', 'どちらも見たことを述べています。', 'どちらも実際に渡ったことを前提にしています。'],
          audioEn: 'I saw her cross the bridge. I saw her crossing the bridge.',
        },
        {
          id: 'u24-l3-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'When I walked into the kitchen, I found the tap ___ and the floor completely wet.',
          sentenceJa: '台所に入ると、蛇口が出しっぱなしで床がすっかり濡れていました。',
          choices: [
            'run',
            'running',
            'to run',
            'ran',
          ],
          correctIndex: 1,
          explanation: 'find + 目的語 + -ing で「〜が…している状態を見つける」を表します。進行中の状況なので running にします。',
          choiceNotes: ['原形は一連の動作を最後まで捉える形で、見つけた瞬間の状態には合いません。', null, 'この構文では to不定詞は使いません。', '目的語のあとに過去形は置けません。'],
          audioEn: 'When I walked into the kitchen, I found the tap running and the floor completely wet.',
        },
        {
          id: 'u24-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'We could feel the whole building shake during the earthquake.',
            'I heard the neighbours arguing again late last night.',
            'The children were seen to leave the playground before sunset.',
            'Nobody noticed him to take the documents from the desk.',
          ],
          correctIndex: 3,
          explanation: 'notice も知覚動詞と同じ形を取り、to不定詞は使いません。正しくは noticed him take または noticed him taking です。',
          choiceNotes: ['正しい文です。feel + 目的語 + 原形で揺れ全体を捉えています。', '正しい文です。-ing で進行中の場面を表しています。', '正しい文です。受動態では原形の前に to が現れます。', null],
          audioEn: 'Nobody noticed him take the documents from the desk.',
        },
        {
          id: 'u24-l3-q9',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「その少年が店を出て行くところが防犯カメラに写っていた」と受動態で言いたいとき。',
          choices: [
            'The boy was seen leave the shop on the security camera.',
            'The boy was seen to leave the shop on the security camera.',
            'The boy was seen leave to the shop on the security camera.',
            'The boy saw to leave the shop on the security camera.',
          ],
          correctIndex: 1,
          explanation: '知覚動詞の受動態では、能動態では現れなかった to が原形の前に付いて be seen to do になります。',
          choiceNotes: ['受動態では原形の前に to が必要です。', null, 'to の位置が違い、文として成り立ちません。', '主語が「見た」ことになり、意味が逆になります。'],
          audioEn: 'The boy was seen to leave the shop on the security camera.',
        },
        {
          id: 'u24-l3-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I heard my name ___ from the other side of the crowded platform.',
          sentenceJa: '混雑したホームの反対側から、自分の名前が呼ばれるのが聞こえました。',
          choices: [
            'call',
            'calling',
            'called',
            'to call',
          ],
          correctIndex: 2,
          explanation: '名前は「呼ばれる」側なので過去分詞 called を使います。目的語が動作を受ける場合は過去分詞にします。',
          choiceNotes: ['原形だと名前が自分で呼ぶことになってしまいます。', '-ing でも名前が呼ぶ側になってしまいます。', null, '知覚動詞のあとに to不定詞は使いません。'],
          audioEn: 'I heard my name called from the other side of the crowded platform.',
        },
      ],
      summary: [
        '知覚動詞(see / watch / hear / feel / notice)+ 人・物 + 原形 / -ing。to不定詞は使わない。',
        '原形 = 動作を最初から最後まで見聞きした(一部始終)。',
        '-ing = 進行中の動作の一場面だけを見聞きした。',
        '対象が「される」側なら過去分詞(I heard my name called.)。',
      ],
    },
  ],
}
