import type { GrammarUnit } from '../../types'

// U25 分詞

export const u25: GrammarUnit = {
  id: 'u25',
  level: 'B2',
  title: '分詞',
  lessons: [
    {
      id: 'u25-l1',
      unitId: 'u25',
      level: 'B2',
      title: '分詞形容詞 -ing / -ed',
      objective: 'boring / bored のような感情を表す形容詞を、「感情を引き起こす側」か「感じる側」かで正しく使い分けられるようになります。',
      minutes: 10,
      prereqs: ['u24-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '-ing は「させる側」、-ed は「させられる側」',
          body:
            'bore(退屈させる)、excite(わくわくさせる)、surprise(驚かせる)など、感情を表す英語の動詞は「**人をその気持ちにさせる**」という意味を持ちます。ここから2種類の形容詞が生まれます。\n\n- **-ing** = その気持ちを**引き起こす側**の性質\n- **-ed** = その気持ちを**受け取った人**の状態\n\n映画がつまらなくて眠くなった場面なら、こうなります。\n\n- The movie is **boring**.(映画が退屈させる側)\n- I am **bored**.(私が退屈させられた側)\n\n「誰が引き起こし、誰が感じているのか」を考えるのがすべての出発点です。',
        },
        {
          type: 'table',
          title: 'よく使う感情動詞のペア',
          headers: ['動詞', '-ing(引き起こす側)', '-ed(感じる側)'],
          rows: [
            ['bore(退屈させる)', 'boring(退屈な)', 'bored(退屈している)'],
            ['excite(わくわくさせる)', 'exciting(わくわくさせる)', 'excited(わくわくしている)'],
            ['surprise(驚かせる)', 'surprising(驚くような)', 'surprised(驚いている)'],
            ['tire(疲れさせる)', 'tiring(骨の折れる)', 'tired(疲れている)'],
            ['confuse(混乱させる)', 'confusing(紛らわしい)', 'confused(混乱している)'],
            ['disappoint(がっかりさせる)', 'disappointing(期待外れの)', 'disappointed(がっかりしている)'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'This puzzle game is really interesting once you understand the basic rules.', ja: 'このパズルゲームは、基本ルールが分かればとても面白いです。', highlight: 'interesting' },
            { en: "I'm interested in Japanese history, especially the period before the Meiji Restoration.", ja: '私は日本史、とくに明治維新より前の時代に興味があります。', highlight: 'interested', note: '興味を「持たされている」側なので -ed です。' },
            { en: 'The long flight was tiring, and everyone was tired.', ja: '長時間のフライトは疲れるもので、みんな疲れていました。', highlight: 'tiring', note: '同じ文の中でも、フライトは -ing、人は -ed です。' },
            { en: 'His explanation was so confusing that nobody dared to ask a follow up question.', ja: '彼の説明はあまりに分かりにくく、追加の質問をする勇気のある人はいませんでした。', highlight: 'confusing' },
            { en: 'The test results were disappointing, but the teacher encouraged us to try again next month.', ja: 'テストの結果は期待外れでしたが、先生は来月もう一度挑戦するよう励ましてくれました。', highlight: 'disappointing' },
          ],
        },
        {
          type: 'contrast',
          title: '-ing と -ed の視点のちがい',
          left: {
            label: '-ing(感情を引き起こす側)',
            items: [
              { en: 'The lecture was boring.', ja: '講義は退屈でした。', highlight: 'boring' },
              { en: 'The news was surprising.', ja: 'その知らせは驚くべきものでした。', highlight: 'surprising' },
            ],
            pointJa: '主語が感情の「原因」になっている',
          },
          right: {
            label: '-ed(感情を感じる側)',
            items: [
              { en: 'The students were bored.', ja: '学生たちは退屈していました。', highlight: 'bored' },
              { en: 'We were surprised at the news.', ja: '私たちはその知らせに驚きました。', highlight: 'surprised' },
            ],
            pointJa: '主語が感情を「受け取って」いる',
          },
          note: '同じ場面でも、原因を主語にすれば -ing、感じた人を主語にすれば -ed になります。',
        },
        {
          type: 'explanation',
          title: '「人 = -ed」と丸暗記しない',
          body:
            'よくある誤解が「人には -ed、物には -ing」という覚え方です。実際には**人にも -ing を使えます**。\n\n- He is bored.(彼は退屈している)\n- He is boring.(彼はつまらない人だ = 周りを退屈させる)\n\n判断基準はあくまで「**その感情を引き起こしているのか、感じているのか**」です。人について -ing を使うと性格・性質の評価になるので、うっかり I am boring. と言うと「私はつまらない人間です」という自己紹介になってしまいます。',
        },
      ],
      quiz: [
        {
          id: 'u25-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The instructions were so ___ that nobody could follow them.',
          sentenceJa: '説明書がとても分かりにくかったので、誰も手順どおりにできませんでした。',
          choices: ['confusing', 'confused', 'confuse', 'confusion'],
          correctIndex: 0,
          explanation: '説明書は読む人を混乱「させる側」なので -ing の confusing を使います。',
          choiceNotes: [null, 'confused だと「説明書自体が混乱している(混乱させられている)」という意味になってしまいます。', '動詞の原形は形容詞の位置には置けません。', 'confusion は名詞なので、so ... that の形容詞の位置には合いません。'],
          audioEn: 'The instructions were so confusing that nobody could follow them.',
        },
        {
          id: 'u25-l1-q2',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'Kenji is boring.',
          choices: ['ケンジは退屈している。', 'ケンジはつまらない人だ。', 'ケンジは退屈な場所にいる。', 'ケンジは疲れている。'],
          correctIndex: 1,
          explanation: '-ing は「周りを退屈させる側」の性質を表します。「本人が退屈している」なら Kenji is bored. です。',
          choiceNotes: ['「退屈している」は感情を受けた状態なので bored を使います。', null, '場所の情報はこの文には含まれていません。', '「疲れている」は tired です。boring とは別の単語です。'],
          audioEn: 'Kenji is boring.',
        },
        {
          id: 'u25-l1-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「その知らせに私は驚きました」と言いたいとき。',
          choices: ['I was surprising at the news.', 'I was surprised at the news.', 'The news was surprised to me.', 'I surprised at the news.'],
          correctIndex: 1,
          explanation: '私は驚きを「感じた側」なので surprised を使います。be surprised at で「〜に驚く」です。',
          choiceNotes: ['surprising だと「私が周りを驚かせる人だ」という性質の話になってしまいます。', null, '知らせは驚きを「引き起こす側」なので、使うなら surprising です。', 'surprise は「〜を驚かせる」という他動詞なので、この形では文になりません。'],
          audioEn: 'I was surprised at the news.',
        },
        {
          id: 'u25-l1-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The movie was so boring that I fell asleep.',
            'She looked bored during the meeting.',
            'It was a tiring day, so I went to bed early.',
            'I was disappointing with my test score.',
          ],
          correctIndex: 3,
          explanation: '私は失望を「感じた側」なので disappointed が正しい形です。I was disappointed with my test score. とします。',
          choiceNotes: ['正しい文です。映画は退屈させる側なので boring。', '正しい文です。彼女は退屈を感じている側なので bored。', '正しい文です。一日は人を疲れさせる側なので tiring。', null],
          audioEn: 'I was disappointed with my test score.',
        },
        {
          id: 'u25-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Everyone was ___ when the CEO announced her resignation without any warning.',
          sentenceJa: 'CEOが何の前触れもなく辞任を発表したとき、全員が驚きました。',
          choices: [
            'shocking',
            'shocked',
            'shock',
            'shockingly',
          ],
          correctIndex: 1,
          explanation: '驚きを受け取った側が主語なので -ed の shocked を使います。発表のほうを主語にするなら shocking です。',
          choiceNotes: ['shocking だと「全員が周りを驚かせる存在だ」という意味になってしまいます。', null, '原形は be動詞のあとの形容詞の位置には置けません。', '副詞は be動詞のあとの補語にはなりません。'],
          audioEn: 'Everyone was shocked when the CEO announced her resignation without any warning.',
        },
        {
          id: 'u25-l1-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「あの講演はとても刺激的だったので、参加者はみな意欲的になった」と言いたいとき。',
          choices: [
            'The talk was so inspired that all the participants felt motivating.',
            'The talk was so inspiring that all the participants felt motivated.',
            'The talk was so inspiring that all the participants felt motivating.',
            'The talk was so inspired that all the participants felt motivated.',
          ],
          correctIndex: 1,
          explanation: '講演は刺激を与える側なので inspiring、参加者は意欲を受け取った側なので motivated です。',
          choiceNotes: ['講演は刺激を与える側なので inspiring にします。', null, '参加者は意欲を受け取った側なので motivated にします。', '講演は inspiring、参加者は motivated という組み合わせになります。'],
          audioEn: 'The talk was so inspiring that all the participants felt motivated.',
        },
        {
          id: 'u25-l1-q7',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'To be honest, I found the second half of the film rather depressing.',
          choices: [
            '正直なところ、映画の後半はかなり気が滅入る内容だった。',
            '正直なところ、私は映画の後半で落ち込んでいた。',
            '正直なところ、映画の後半は元気が出る内容だった。',
            '正直なところ、私は映画の後半を見ていなかった。',
          ],
          correctIndex: 0,
          explanation: 'depressing は気を滅入らせる側の性質です。ここでは映画の後半そのものの評価を述べています。',
          choiceNotes: [null, '自分が落ち込んでいたなら I felt depressed になります。', 'depressing は元気が出るという意味ではありません。', '見ていなかったという情報は含まれていません。'],
          audioEn: 'To be honest, I found the second half of the film rather depressing.',
        },
        {
          id: 'u25-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The instructions on the website were extremely confusing for first time users.',
            'I was really embarrassed when I forgot my colleague name in front of everyone.',
            'The results of the survey were quite surprising to the research team.',
            'Many customers were annoying by the long wait at the service counter.',
          ],
          correctIndex: 3,
          explanation: '客は不快にさせられた側なので annoyed が正しい形です。annoying は不快にさせる側の性質を表します。',
          choiceNotes: ['正しい文です。説明は混乱させる側なので confusing。', '正しい文です。恥ずかしい思いをした側なので embarrassed。', '正しい文です。結果は驚かせる側なので surprising。', null],
          audioEn: 'Many customers were annoyed by the long wait at the service counter.',
        },
        {
          id: 'u25-l1-q9',
          prompt: '空所に入る形の組み合わせを選んでください。',
          sentence: 'The training session was ___ , and by the end all of us were completely ___ .',
          sentenceJa: 'その研修はくたびれるもので、終わるころには全員がすっかり疲れ切っていました。',
          choices: [
            'exhausted / exhausting',
            'exhausting / exhausted',
            'exhausting / exhausting',
            'exhausted / exhausted',
          ],
          correctIndex: 1,
          explanation: '研修は疲れさせる側なので exhausting、私たちは疲れを感じた側なので exhausted です。',
          choiceNotes: ['前後が入れ替わっています。研修が exhausting です。', null, '人が exhausting だと「周りを疲れさせる人」という意味になります。', '研修が exhausted だと「研修が疲れている」ことになります。'],
          audioEn: 'The training session was exhausting, and by the end all of us were completely exhausted.',
        },
        {
          id: 'u25-l1-q10',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: My uncle is very amusing.   B: My uncle is very amused.',
          choices: [
            'Aは「面白い人だ」、Bは「面白がっている」という意味になる。',
            'Aは「面白がっている」、Bは「面白い人だ」という意味になる。',
            'どちらも「面白い人だ」という意味になる。',
            'どちらも「面白がっている」という意味になる。',
          ],
          correctIndex: 0,
          explanation: '人に -ing を使うと「周りをその気持ちにさせる性質」の評価になり、-ed は本人がその気持ちを感じている状態を表します。',
          choiceNotes: [null, '面白がっているのは -ed を使う B のほうです。', 'B は本人の感情を表しています。', 'A は本人の性質についての評価です。'],
          audioEn: 'My uncle is very amusing. My uncle is very amused.',
        },
      ],
      summary: [
        '-ing は感情を「引き起こす側」、-ed は感情を「感じる側」を表す。',
        'boring / bored、exciting / excited、confusing / confused などのペアで覚える。',
        '人にも -ing は使えるが、「周りをそうさせる性格だ」という評価になる。',
        '「人 = -ed、物 = -ing」ではなく「原因か、感じた側か」で判断する。',
      ],
    },
    {
      id: 'u25-l2',
      unitId: 'u25',
      level: 'B2',
      title: '分詞による後置修飾',
      objective: 'the man standing there のように分詞を名詞の後ろに置き、関係詞節よりも引き締まった形で名詞に説明を加えられるようになります。',
      minutes: 10,
      prereqs: ['u25-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '名詞のうしろから説明を足す',
          body:
            '分詞に場所・対象などの説明を添えて名詞を詳しくするときは、**名詞の後ろにひとかたまりで置く**のが基本です。\n\n- the man **standing there** → そこに立っている男性\n- the documents **sent yesterday** → 昨日送られた書類\n\nthe man who is standing there から who is をまとめて省いた形、と考えると理解しやすくなります。standing there は「男性が立っている」、sent yesterday は「書類が送られた」という関係です。\n\na **broken** window のように短い分詞を名詞の前に置く形もあります。ただし、位置が単純に語数だけで決まるわけではありません。**説明全体をどの名詞に結び付けるか**を確認しましょう。',
        },
        {
          type: 'structure',
          title: '関係詞節を分詞に縮約する',
          parts: [
            { label: '名詞', text: 'the man' },
            { label: '関係詞 + be動詞を省略', text: '(who is)' },
            { label: '分詞のまとまり', text: 'standing at the door' },
          ],
          caption: 'The man who is standing at the door is my boss. → The man standing at the door is my boss.',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The woman wearing a red coat near the ticket gate is my aunt from Sapporo.', ja: '改札の近くで赤いコートを着ている女性は、札幌に住む私のおばです。', highlight: 'wearing a red coat' },
            { en: 'Do you know the boy talking to the teacher outside the staff room right now?', ja: '今ちょうど職員室の外で先生と話している男の子を知っていますか。', highlight: 'talking to the teacher' },
            { en: 'They live in a house built over a hundred years ago.', ja: '彼らは建てられてから100年以上たつ家に住んでいます。', highlight: 'built over a hundred years ago' },
            { en: 'Most of the emails sent to this address during the night turn out to be spam.', ja: 'このアドレスに夜間に送られてくるメールの大半は、結局は迷惑メールです。', highlight: 'sent to this address' },
            { en: 'There were many people waiting in line outside the store.', ja: '店の外には列に並んで待っている人がたくさんいました。', highlight: 'waiting in line' },
          ],
        },
        {
          type: 'contrast',
          title: '-ing で修飾するか、-ed で修飾するか',
          left: {
            label: '現在分詞 -ing(名詞がする側)',
            items: [
              { en: 'The dog barking next door kept me awake.', ja: '隣で吠えている犬のせいで眠れませんでした。', highlight: 'barking' },
              { en: 'The girl singing on stage is my cousin.', ja: 'ステージで歌っている女の子は私のいとこです。', highlight: 'singing' },
            ],
            pointJa: '名詞がその動作を「している」',
          },
          right: {
            label: '過去分詞 -ed(名詞がされる側)',
            items: [
              { en: 'The windows broken in the storm were replaced.', ja: '嵐で割れた窓は交換されました。', highlight: 'broken' },
              { en: 'I love the pictures taken by my grandfather.', ja: '祖父が撮った写真が大好きです。', highlight: 'taken' },
            ],
            pointJa: '名詞がその動作を「される」',
          },
          note: '分詞の形を決めるのは時制ではなく「する側か、される側か」です。taken は「過去」ではなく「撮られる」という受け身を表しています。',
        },
        {
          type: 'explanation',
          title: '名詞の説明と、独立した文を区別する',
          body:
            '**過去分詞は、過去の出来事を何でも名詞の説明に変えられる形ではありません**。次の3つを比べてください。\n\n- the man **who robbed the bank** → 銀行を襲った男。who 以下が the man を説明する名詞のかたまりです。\n- **The man robbed the bank.** → その男は銀行を襲いました。robbed が文の動詞になった、独立した文です。\n- the man **robbed by the gang** → その集団に金品を奪われた男。男が行為を受ける側です。\n\n「銀行を襲った男」というかたまりを作りたいなら、who robbed the bank を残します。**過去の話かどうかと、する側・される側の区別は別**に考えましょう。',
        },
      ],
      quiz: [
        {
          id: 'u25-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The people ___ for the bus looked very cold.',
          sentenceJa: 'バスを待っている人たちはとても寒そうでした。',
          choices: ['waiting', 'waited', 'who waiting', 'are waiting'],
          correctIndex: 0,
          explanation: '人々はバスを「待っている側」なので現在分詞 waiting で後ろから修飾します。',
          choiceNotes: [null, '人は「待たれる側」ではないので過去分詞は使えません。', '関係詞を使うなら who are waiting と be動詞が必要です。', '名詞の直後に are waiting を続けるには関係詞 who が必要です。'],
          audioEn: 'The people waiting for the bus looked very cold.',
        },
        {
          id: 'u25-l2-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Most of the cheese ___ in this region is exported to Europe.',
          sentenceJa: 'この地域で作られるチーズの大半はヨーロッパに輸出されます。',
          choices: ['making', 'made', 'makes', 'is made'],
          correctIndex: 1,
          explanation: 'チーズは「作られる側」なので過去分詞 made を使います。',
          choiceNotes: ['making だと「チーズが何かを作っている」という意味になってしまいます。', null, '動詞の現在形をそのまま名詞の修飾には使えません。', 'is made を続けるなら関係詞 that が必要です。この文の動詞は後ろの is exported です。'],
          audioEn: 'Most of the cheese made in this region is exported to Europe.',
        },
        {
          id: 'u25-l2-q3',
          prompt: '次の文を分詞を使って書き換えたものとして正しいものを選んでください。',
          sentence: 'Do you know the woman who is talking to Ken?',
          sentenceJa: 'ケンと話している女性を知っていますか。',
          choices: [
            'Do you know the woman talked to Ken?',
            'Do you know the talking woman to Ken?',
            'Do you know the woman talking to Ken?',
            'Do you know the woman is talking to Ken?',
          ],
          correctIndex: 2,
          explanation: 'who is を省略し、talking to Ken を名詞 the woman の後ろに置きます。',
          choiceNotes: ['女性は「話す側」なので過去分詞 talked では受け身の意味になってしまいます。', 'talking to Ken は2語以上のまとまりなので、名詞の前ではなく後ろに置きます。', null, '関係詞 who を消すなら is も一緒に消します。'],
          audioEn: 'Do you know the woman talking to Ken?',
        },
        {
          id: 'u25-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The man arrested by the police was innocent.',
            'The bridge connecting the two islands is very long.',
            'The man robbed the bank was caught yesterday.',
            'The cookies baked this morning smell wonderful.',
          ],
          correctIndex: 2,
          explanation: '男は銀行を「襲った側」なので、過去分詞では表せません。The man who robbed the bank was caught yesterday. と関係詞を使います。',
          choiceNotes: ['正しい文です。男は「逮捕された側」なので過去分詞 arrested。', '正しい文です。橋は2つの島を「つないでいる側」なので現在分詞 connecting。', null, '正しい文です。クッキーは「焼かれた側」なので過去分詞 baked。'],
          audioEn: 'The man who robbed the bank was caught yesterday.',
        },
        {
          id: 'u25-l2-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The report ___ by the committee last week contains several serious errors.',
          sentenceJa: '先週その委員会が提出した報告書には、深刻な誤りがいくつか含まれています。',
          choices: [
            'submitting',
            'submitted',
            'submits',
            'to submit',
          ],
          correctIndex: 1,
          explanation: '報告書は「提出される」側なので過去分詞 submitted で後ろから修飾します。関係詞なら which was submitted です。',
          choiceNotes: ['-ing だと報告書が提出する側になってしまいます。', null, '名詞のあとに現在形の動詞は置けません。', 'to不定詞ではこれから提出する予定という別の意味になります。'],
          audioEn: 'The report submitted by the committee last week contains several serious errors.',
        },
        {
          id: 'u25-l2-q6',
          prompt: '次の文を分詞で言い換えたものとして正しいものを選んでください。',
          sentence: 'The man who is standing near the entrance is our new security guard.',
          choices: [
            'The man stood near the entrance is our new security guard.',
            'The man to stand near the entrance is our new security guard.',
            'The man standing near the entrance is our new security guard.',
            'The man being stand near the entrance is our new security guard.',
          ],
          correctIndex: 2,
          explanation: 'who is standing の関係代名詞と be動詞を省くと、-ing の分詞だけが名詞の後ろに残ります。',
          choiceNotes: ['stood では過去分詞となり、男性が立たされている意味になってしまいます。', 'to不定詞ではこれから立つ予定という意味になります。', null, 'being stand という形は英語にありません。'],
          audioEn: 'The man standing near the entrance is our new security guard.',
        },
        {
          id: 'u25-l2-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Anyone ___ in joining the volunteer program should contact the office by Friday.',
          sentenceJa: 'ボランティア計画への参加に関心のある方は、金曜日までに事務局に連絡してください。',
          choices: [
            'interesting',
            'interested',
            'interest',
            'to interest',
          ],
          correctIndex: 1,
          explanation: '関心を持たされている側なので過去分詞 interested を使い、anyone を後ろから修飾します。',
          choiceNotes: ['interesting だと「参加することが面白い人」という別の意味になります。', null, '名詞のあとに動詞の原形は置けません。', 'この位置では to不定詞は自然ではありません。'],
          audioEn: 'Anyone interested in joining the volunteer program should contact the office by Friday.',
        },
        {
          id: 'u25-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The candidates selected for the final round will be notified by email.',
            'Students living more than ten kilometers away can apply for a travel allowance.',
            'We finally found the file containing all the sales figures for last year.',
            'The message leaving on my desk did not have a signature or a date.',
          ],
          correctIndex: 3,
          explanation: 'メモは「置かれた」側なので過去分詞にします。正しくは The message left on my desk です。',
          choiceNotes: ['正しい文です。候補者は選ばれる側なので過去分詞。', '正しい文です。学生は住んでいる側なので -ing。', '正しい文です。ファイルは含んでいる側なので -ing。', null],
          audioEn: 'The message left on my desk did not have a signature or a date.',
        },
        {
          id: 'u25-l2-q9',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'The passengers waiting at gate twelve were told that their flight had been cancelled.',
          choices: [
            '12番ゲートで待っていた乗客は、便が欠航になったと知らされた。',
            '12番ゲートで待つよう言われた乗客が、便を欠航にした。',
            '乗客は12番ゲートで待つように指示された。',
            '12番ゲートで待っていた乗客だけが搭乗できた。',
          ],
          correctIndex: 0,
          explanation: 'waiting at gate twelve は The passengers を後ろから修飾しています。文の動詞は were told です。',
          choiceNotes: [null, '欠航にしたのは乗客ではありません。', '待つよう指示されたという内容ではありません。', '搭乗できたという情報は含まれていません。'],
          audioEn: 'The passengers waiting at gate twelve were told that their flight had been cancelled.',
        },
        {
          id: 'u25-l2-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The photographs ___ in this exhibition were all taken during the 1960s.',
          sentenceJa: 'この展覧会で展示されている写真は、すべて1960年代に撮影されたものです。',
          choices: [
            'displaying',
            'display',
            'displayed',
            'to display',
          ],
          correctIndex: 2,
          explanation: '写真は「展示される」側なので過去分詞 displayed で後ろから修飾します。',
          choiceNotes: ['-ing だと写真が何かを展示していることになります。', '名詞のあとに原形は置けません。', null, 'to不定詞ではこれから展示する予定という意味になります。'],
          audioEn: 'The photographs displayed in this exhibition were all taken during the 1960s.',
        },
      ],
      summary: [
        '2語以上のまとまりで名詞を説明するときは、分詞を名詞の後ろに置く。',
        '名詞が「する側」なら現在分詞 -ing、「される側」なら過去分詞。',
        '関係詞 + be動詞(who is など)を省略した形と考えると分かりやすい。',
        '過去に「した側」は過去分詞で表せない。the man who robbed the bank のように関係詞を使う。',
      ],
    },
    {
      id: 'u25-l3',
      unitId: 'u25',
      level: 'B2',
      title: '分詞構文',
      objective: 'Walking home, I saw... のように接続詞を使った文を分詞構文に書き換え、「〜しながら」「〜なので」を引き締まった形で表現できるようになります。',
      minutes: 12,
      prereqs: ['u25-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '「接続詞 + 主語 + 動詞」をひとつの分詞に圧縮',
          body:
            '次の2つの文は同じ意味です。\n\n- **While I was walking** home, I saw an old friend.\n- **Walking** home, I saw an old friend.(家に歩いて帰る途中、旧友に会いました)\n\n下の形が**分詞構文**です。接続詞と主語を消して動詞を -ing にすることで、「〜するとき」「〜なので」「〜しながら」といった意味を文脈に任せて、短く引き締めて伝えます。書き言葉で特によく使われる表現です。',
        },
        {
          type: 'structure',
          title: '書き換えの3ステップ',
          parts: [
            { label: '1 接続詞を消す', text: 'While' },
            { label: '2 同じ主語を消す', text: 'I' },
            { label: '3 動詞を -ing に', text: 'was walking → walking' },
          ],
          caption: 'While I was walking home, I saw an old friend. → Walking home, I saw an old friend.',
        },
        {
          type: 'table',
          title: '分詞構文が表す主な意味',
          headers: ['意味', '分詞構文', 'ふつうの文にすると'],
          rows: [
            ['時(〜するとき)', 'Walking home, I saw an old friend.', 'While I was walking home, I saw an old friend.'],
            ['理由(〜なので)', 'Feeling tired, she went to bed early.', 'Because she felt tired, she went to bed early.'],
            ['付帯状況(〜しながら)', 'She sat by the window, listening to the rain.', 'She sat by the window while she listened to the rain.'],
          ],
        },
        {
          type: 'explanation',
          title: '否定・受け身・主語のルール',
          body:
            '基本形に加えて、3つのルールを押さえましょう。\n\n- **否定**は Not を分詞の前に置く: **Not knowing** what to say, I stayed silent.\n- **受け身**は過去分詞で始める: **Seen** from the plane, the island looks like a heart.(Being seen の Being が省略された形です)\n- **最重要**: 分詞の意味上の主語は**主節の主語と一致**させる。× Walking home, my phone rang. だと「電話が歩いて帰っていた」ことになってしまいます。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Walking home along the riverside path, I saw an old friend from high school.', ja: '川沿いの道を歩いて家に帰る途中、高校時代の旧友に会いました。', highlight: 'Walking home' },
            { en: 'Feeling tired after a long day of meetings, she went to bed much earlier than usual.', ja: '会議続きの長い一日で疲れていたので、彼女はいつもよりずっと早く寝ました。', highlight: 'Feeling tired' },
            { en: 'Not knowing what to say to the grieving family, I just stayed silent for a while.', ja: '悲しみに暮れる家族に何と言えばいいか分からず、私はしばらく黙っていました。', highlight: 'Not knowing' },
            { en: 'Seen from the plane, the island looks like a heart.', ja: '飛行機から見ると、その島はハートの形に見えます。', highlight: 'Seen from the plane', note: '島は「見られる側」なので過去分詞で始めます。' },
            { en: 'She sat by the window, listening to the rain.', ja: '彼女は雨の音を聞きながら、窓辺に座っていました。', highlight: 'listening to the rain', note: '文の後ろに置いて「〜しながら」と付け足す形もよく使われます。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u25-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ the news, she burst into tears.',
          sentenceJa: 'その知らせを聞いて、彼女は泣き出しました。',
          choices: ['Heard', 'Hearing', 'To hear', 'She hearing'],
          correctIndex: 1,
          explanation: '彼女は知らせを「聞く側」なので現在分詞 Hearing で始めます。',
          choiceNotes: ['過去分詞で始めると「彼女が聞かれる側」という受け身の意味になってしまいます。', null, 'to不定詞だと「聞くために」という目的の意味になり、文脈に合いません。', '主節と同じ主語は、分詞構文では残さず消します。'],
          audioEn: 'Hearing the news, she burst into tears.',
        },
        {
          id: 'u25-l3-q2',
          prompt: '次の文を分詞構文で書き換えたものとして正しいものを選んでください。',
          sentence: 'Because he did not have a car, he took the bus to work.',
          sentenceJa: '車を持っていなかったので、彼はバスで通勤しました。',
          choices: [
            'Not having a car, he took the bus to work.',
            'Having not a car, he took the bus to work.',
            'Not had a car, he took the bus to work.',
            'He not having a car, took the bus to work.',
          ],
          correctIndex: 0,
          explanation: '接続詞 because と主語 he を消し、動詞を having にします。否定の not は分詞の前に置きます。',
          choiceNotes: [null, '否定の not は分詞の後ろではなく前に置きます。', '彼は車を「持つ側」なので過去分詞 had は使えません。', '主節と同じ主語 he は分詞構文では残しません。'],
          audioEn: 'Not having a car, he took the bus to work.',
        },
        {
          id: 'u25-l3-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ in simple English, this book is popular with beginners.',
          sentenceJa: 'やさしい英語で書かれているので、この本は初心者に人気があります。',
          choices: ['Writing', 'Written', 'Wrote', 'To write'],
          correctIndex: 1,
          explanation: '本は「書かれる側」なので、受け身の分詞構文として過去分詞 Written で始めます。',
          choiceNotes: ['Writing だと「本が何かを書いている」ことになってしまいます。', null, '過去形をそのまま文頭の分詞の位置に置くことはできません。', 'to不定詞だと「書くために」という目的の意味になってしまいます。'],
          audioEn: 'Written in simple English, this book is popular with beginners.',
        },
        {
          id: 'u25-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Waiting for the train, I read the news on my phone.',
            'Opening the window, she let some fresh air in.',
            'Walking down the street, the old clock tower came into view.',
            'Having no time for breakfast, he grabbed a banana and left.',
          ],
          correctIndex: 2,
          explanation: '分詞の意味上の主語は主節の主語と一致させます。この文では「時計台が通りを歩いていた」ことになってしまいます。Walking down the street, I saw the old clock tower. のように主語をそろえます。',
          choiceNotes: ['正しい文です。待っていたのもニュースを読んでいたのも I です。', '正しい文です。窓を開けたのも空気を入れたのも she です。', null, '正しい文です。時間がなかったのもバナナをつかんだのも he です。'],
          audioEn: 'Walking down the street, I saw the old clock tower.',
        },
        {
          id: 'u25-l3-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ the report twice, she finally noticed the mistake in the final paragraph.',
          sentenceJa: '報告書を2回読み終えて、彼女はようやく最終段落の誤りに気づきました。',
          choices: [
            'Having read',
            'Being read',
            'To read',
            'Read',
          ],
          correctIndex: 0,
          explanation: '読み終えたあとで気づいたという前後関係を示すには、完了形の分詞構文 Having + 過去分詞を使います。',
          choiceNotes: [null, 'Being read だと彼女が読まれる側になってしまいます。', 'To read では目的を表す形になり、前後関係を示せません。', '過去分詞だけでは彼女が読まれる側という意味になります。'],
          audioEn: 'Having read the report twice, she finally noticed the mistake in the final paragraph.',
        },
        {
          id: 'u25-l3-q6',
          prompt: '次の文を分詞構文で言い換えたものとして正しいものを選んでください。',
          sentence: 'Because it was written in simple English, the manual was easy for everyone to follow.',
          choices: [
            'Writing in simple English, the manual was easy for everyone to follow.',
            'Written in simple English, the manual was easy for everyone to follow.',
            'To write in simple English, the manual was easy for everyone to follow.',
            'Being write in simple English, the manual was easy for everyone to follow.',
          ],
          correctIndex: 1,
          explanation: 'マニュアルは「書かれる」側なので過去分詞で始めます。Being written の Being は普通省略します。',
          choiceNotes: ['-ing だとマニュアルが何かを書いていることになります。', null, 'to不定詞では理由を表せません。', 'Being のあとは過去分詞にします。原形は続けられません。'],
          audioEn: 'Written in simple English, the manual was easy for everyone to follow.',
        },
        {
          id: 'u25-l3-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ what to do next, the team decided to ask their supervisor for advice.',
          sentenceJa: '次に何をすべきか分からなかったので、チームは上司に助言を求めることにしました。',
          choices: [
            'Not knowing',
            'Knowing not',
            'Not known',
            'Do not know',
          ],
          correctIndex: 0,
          explanation: '分詞構文の否定は not を分詞の前に置きます。Not knowing の語順になります。',
          choiceNotes: [null, 'not は分詞のあとではなく前に置きます。', 'known ではチームが知られる側になってしまいます。', '分詞構文に定形動詞は使いません。'],
          audioEn: 'Not knowing what to do next, the team decided to ask their supervisor for advice.',
        },
        {
          id: 'u25-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Arriving at the station early, we had time for a proper breakfast.',
            'Built in the twelfth century, the castle attracts thousands of visitors each year.',
            'Having lived abroad for ten years, he speaks three languages fluently.',
            'Walking along the river, the old bridge suddenly came into view before us.',
          ],
          correctIndex: 3,
          explanation: '分詞の主語は主節の主語と同じでなければなりません。この文では橋が歩いていることになってしまいます。',
          choiceNotes: ['正しい文です。到着したのも朝食の時間があったのも we です。', '正しい文です。城は建てられる側なので過去分詞。', '正しい文です。海外に住んでいたのも話すのも he です。', null],
          audioEn: 'Walking along the river, we suddenly saw the old bridge come into view.',
        },
        {
          id: 'u25-l3-q9',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'Seen from the top of the tower, the whole city looks surprisingly small and quiet.',
          choices: [
            '塔の上から見ると、街全体が驚くほど小さく静かに見える。',
            '塔の上から街を見た人は、驚くほど小さく静かだった。',
            '街全体が塔の上を見ている。',
            '塔の上から見られた街は、実際には大きくにぎやかだ。',
          ],
          correctIndex: 0,
          explanation: 'Seen from ... は「〜から見られると」という意味で、主節の主語 the whole city を説明しています。',
          choiceNotes: [null, '小さく静かに見えるのは街であって人ではありません。', '街が見ているのではなく、見られる側です。', '実際にどうであるかは、この文からは分かりません。'],
          audioEn: 'Seen from the top of the tower, the whole city looks surprisingly small and quiet.',
        },
        {
          id: 'u25-l3-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'He spent the whole afternoon in the garden, ___ to the radio and pulling out weeds.',
          sentenceJa: '彼は午後じゅう庭で、ラジオを聴きながら草むしりをして過ごしました。',
          choices: [
            'listened',
            'to listen',
            'listening',
            'listen',
          ],
          correctIndex: 2,
          explanation: '文の後ろに置いて「〜しながら」と付け足すときも -ing の分詞を使います。',
          choiceNotes: ['過去形はこの位置では使えません。', 'to不定詞では「聴くために」という目的の意味になります。', null, '原形はこの位置では使えません。'],
          audioEn: 'He spent the whole afternoon in the garden, listening to the radio and pulling out weeds.',
        },
      ],
      summary: [
        '分詞構文は「接続詞 + 主語 + 動詞」を分詞に圧縮した形。接続詞と主語を消し、動詞を -ing にする。',
        '意味(時・理由・付帯状況)は文脈が決める。書き言葉で特によく使われる。',
        '否定は Not を分詞の前に、受け身は過去分詞で文を始める。',
        '分詞の意味上の主語は主節の主語と必ず一致させる。ずれると意味の通らない文になる。',
      ],
    },
  ],
}
