import type { GrammarUnit } from '../../types'

// U26 受動態の発展 — 伝聞の受動態・受動の不定詞/動名詞・get受動態と慣用表現

export const u26: GrammarUnit = {
  id: 'u26',
  level: 'B2',
  title: '受動態の発展',
  lessons: [
    {
      id: 'u26-l1',
      unitId: 'u26',
      level: 'B2',
      title: 'It is said that / He is said to',
      objective: '「〜と言われている」「〜と報じられている」という伝聞・報道を、2つの受動態パターンで表せるようになります。',
      minutes: 12,
      prereqs: ['u13-l4'],
      blocks: [
        {
          type: 'explanation',
          title: '「誰が言ったか」を出さずに伝える',
          body:
            'ニュースやうわさを伝えるとき、日本語では「〜と言われている」「〜らしい」と言いますね。英語では **say / believe / report などの受動態** を使って、「誰が言ったのか」をぼかしたまま情報の内容だけを伝えます。\n\n- People say that he is very rich.(人々は彼がとても金持ちだと言う)\n- → **It is said that** he is very rich.(彼はとても金持ちだと言われている)\n\n言い手の people を消して say を受動態にした形です。ニュース・報告書・アカデミックな文章で非常によく使われます。パターンは2つあります。',
        },
        {
          type: 'structure',
          title: 'パターン1: It is said that + 文',
          parts: [
            { label: '仮の主語', text: 'It' },
            { label: '受動態', text: 'is said' },
            { label: 'that節(内容)', text: 'that he is very rich' },
          ],
          caption: 'It は仮の主語で、実際の内容は that 以下です。that節の中は普通の文をそのまま置けます。',
        },
        {
          type: 'structure',
          title: 'パターン2: 主語 + be said + to不定詞',
          parts: [
            { label: 'うわさの主役', text: 'He' },
            { label: '受動態', text: 'is said' },
            { label: 'to不定詞(内容)', text: 'to be very rich' },
          ],
          caption: 'うわさの主役を文の主語に立てた形。意味はパターン1とまったく同じです。that節の代わりに to不定詞を使います。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'It is said that this temple is over a thousand years old.', ja: 'この寺は千年以上の歴史があると言われています。', highlight: 'It is said that' },
            { en: 'He is said to be one of the best chefs in the city, though he never gives interviews.', ja: '彼は取材を一切受けませんが、市内で最高のシェフの一人だと言われています。', highlight: 'is said to be' },
            { en: 'It is believed that the painting was stolen in the 1970s.', ja: 'その絵は1970年代に盗まれたと考えられています。', highlight: 'It is believed that', note: 'say 以外に believe / report / expect / know なども同じ形で使えます。' },
            { en: 'The company is expected to announce a new product next week.', ja: 'その会社は来週新製品を発表すると見られています。', highlight: 'is expected to announce' },
            { en: 'She is said to have lived in Paris when she was young.', ja: '彼女は若い頃パリに住んでいたと言われています。', highlight: 'to have lived', note: '「言われている今」より前のことは to have + 過去分詞で表します。' },
          ],
        },
        {
          type: 'explanation',
          title: '「それより前のこと」は to have + 過去分詞',
          body:
            'パターン2で注意したいのが時間のズレです。\n\n- He is said **to be** rich.(今、金持ちだと言われている)\n- He is said **to have been** rich.(昔、金持ちだったと言われている)\n\n「言われている」のは今でも、内容が過去のことなら **to have + 過去分詞** を使います。\n\nパターン1なら that節の中の時制を変えるだけなのでシンプルです: It is said that he **was** rich.',
        },
      ],
      quiz: [
        {
          id: 'u26-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It ___ that the castle is haunted.',
          sentenceJa: 'その城には幽霊が出ると言われています。',
          choices: ['said', 'is said', 'says', 'is saying'],
          correctIndex: 1,
          explanation: '伝聞の「〜と言われている」は It is said that + 文 の形です。say を受動態にすることで言い手を出さずに済みます。',
          choiceNotes: ['be動詞のない said だけでは受動態になりません。', null, 'says だと「それが言う」という能動になり、誰が言うのかも不明のままです。', '進行形では「今まさに言っている最中」となり、一般的な伝聞を表せません。'],
          audioEn: 'It is said that the castle is haunted.',
        },
        {
          id: 'u26-l1-q2',
          prompt: 'People believe that the actor lives in this neighborhood. とほぼ同じ意味の文を選んでください。',
          sentenceJa: 'その俳優はこの近所に住んでいると信じられています。',
          choices: [
            'The actor is believed to live in this neighborhood.',
            'The actor is believed to living in this neighborhood.',
            'The actor believes to live in this neighborhood.',
            'It is believed the actor to live in this neighborhood.',
          ],
          correctIndex: 0,
          explanation: 'うわさの主役 the actor を主語に立て、be believed + to不定詞 でつなぎます。',
          choiceNotes: [null, 'to の後ろは動詞の原形です。to living という形は作れません。', '「俳優が信じている」という能動の意味に変わってしまいます。', 'It を主語にするなら It is believed that the actor lives ... と that節を使います。'],
          audioEn: 'The actor is believed to live in this neighborhood.',
        },
        {
          id: 'u26-l1-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The writer is said ___ his first novel at the age of nineteen.',
          sentenceJa: 'その作家は19歳で最初の小説を書いたと言われています。',
          choices: ['to write', 'to have written', 'to be written', 'to have been written'],
          correctIndex: 1,
          explanation: '「言われている」のは今、「書いた」のは過去です。主節より前のことは to have + 過去分詞で表します。',
          choiceNotes: ['to write では「今書く・普段書く」となり、19歳のときという過去と合いません。', null, '受動の to be written では「作家が書かれる」ことになってしまいます。', '受動の完了形なので、やはり主語の作家が「書かれた」ことになります。'],
          audioEn: 'The writer is said to have written his first novel at the age of nineteen.',
        },
        {
          id: 'u26-l1-q4',
          prompt: '「その2社は合併すると報じられています」— 正しい文を選んでください。',
          choices: [
            'It is reported that the two companies will merge.',
            'It is reported the two companies to merge.',
            'The two companies are reported that they will merge.',
            'It reports that the two companies will merge.',
          ],
          correctIndex: 0,
          explanation: 'It is reported that + 文 が正しい形です。that節の中は will merge のように普通の文をそのまま置けます。',
          choiceNotes: [null, 'It is reported の後ろは that節です。to不定詞を使うなら主語を companies に変えます。', '主語を companies にした場合は are reported to be merging のように to不定詞でつなぎ、that節は続けられません。', '「それが報じる」という能動になり、報じ手が不明のままで文が成り立ちません。'],
          audioEn: 'It is reported that the two companies will merge.',
        },
        {
          id: 'u26-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The former mayor ___ to have donated a large sum to the local hospital.',
          sentenceJa: '前市長は地元の病院に多額の寄付をしたと言われています。',
          choices: [
            'is saying',
            'says',
            'is said',
            'said',
          ],
          correctIndex: 2,
          explanation: '情報源をぼかして「〜と言われている」と述べるので受動態にします。寄付は言われている時点より前なので to have donated です。',
          choiceNotes: ['能動態では市長自身が言っていることになってしまいます。', '同じく能動態では意味が逆になります。', null, '過去形の能動態でも、市長が言ったという意味になります。'],
          audioEn: 'The former mayor is said to have donated a large sum to the local hospital.',
        },
        {
          id: 'u26-l1-q6',
          prompt: '次の文を It で始める形に書き換えたものとして正しいものを選んでください。',
          sentence: 'This bridge is believed to be the oldest one in the region.',
          choices: [
            'It is believed that this bridge is the oldest one in the region.',
            'It believes that this bridge is the oldest one in the region.',
            'It is believed this bridge to be the oldest one in the region.',
            'That is believed this bridge is the oldest one in the region.',
          ],
          correctIndex: 0,
          explanation: 'A is said to do は It is said that A does と書き換えられます。believe も同じ形を取ります。',
          choiceNotes: [null, 'It believes では能動態になり、It が信じていることになります。', 'It is believed のあとに目的語と to不定詞を続ける形は使いません。', 'この位置に That は置けません。'],
          audioEn: 'It is believed that this bridge is the oldest one in the region.',
        },
        {
          id: 'u26-l1-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The suspect is reported ___ the country before the police arrived at his house.',
          sentenceJa: '容疑者は警察が自宅に着く前に出国したと報じられています。',
          choices: [
            'to leave',
            'to have left',
            'leaving',
            'to be left',
          ],
          correctIndex: 1,
          explanation: '出国は報道されている時点より前の出来事なので、完了不定詞 to have left を使います。',
          choiceNotes: ['to leave では報道と同時か、これからの話になってしまいます。', null, 'is reported のあとに -ing は続けられません。', 'to be left では容疑者が置き去りにされたという意味になります。'],
          audioEn: 'The suspect is reported to have left the country before the police arrived at his house.',
        },
        {
          id: 'u26-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'It is known that this species survives only on two small islands.',
            'The new policy is expected to reduce waiting times at the clinic.',
            'She is thought to have written the novel while living in Lisbon.',
            'It is said this restaurant to serve the best ramen in the prefecture.',
          ],
          correctIndex: 3,
          explanation: 'It is said のあとは that節を続けます。正しくは It is said that this restaurant serves ... です。',
          choiceNotes: ['正しい文です。It is known that + 節の形です。', '正しい文です。be expected to + 原形の形です。', '正しい文です。執筆は思われている時点より前なので完了不定詞です。', null],
          audioEn: 'It is said that this restaurant serves the best ramen in the prefecture.',
        },
        {
          id: 'u26-l1-q9',
          prompt: 'この形が新聞記事などで好まれる理由として最も適切なものを選んでください。',
          sentence: 'It is reported that more than fifty families have already left the area.',
          choices: [
            '誰が言っているかを明示せずに、情報を客観的に提示できるから。',
            '文が短くなり、読みやすくなるから。',
            '過去の出来事だけを表せるから。',
            '話し手の強い意見を示せるから。',
          ],
          correctIndex: 0,
          explanation: 'It is said that / It is reported that は情報源を前面に出さず、内容を客観的な情報として提示するための形です。',
          choiceNotes: [null, '能動態より長くなることが多く、簡潔さが理由ではありません。', '現在・過去のどちらの内容にも使えます。', 'むしろ話し手の意見を前面に出さないための形です。'],
          audioEn: 'It is reported that more than fifty families have already left the area.',
        },
        {
          id: 'u26-l1-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Several passengers ___ to have been injured when the bus skidded off the road.',
          sentenceJa: 'バスが道路を滑り落ちた際、数人の乗客が負傷したと見られています。',
          choices: [
            'are believed',
            'believe',
            'are believing',
            'believed',
          ],
          correctIndex: 0,
          explanation: '乗客は「そう考えられている」側なので受動態にします。負傷は過去の出来事なので to have been injured です。',
          choiceNotes: [null, '能動態では乗客が何かを信じていることになります。', 'believe は進行形にしにくい動詞で、ここでも使いません。', '過去形の能動態でも意味が通りません。'],
          audioEn: 'Several passengers are believed to have been injured when the bus skidded off the road.',
        },
      ],
      summary: [
        '伝聞・報道は It is said that + 文、または 主語 + be said + to不定詞 の2パターン。意味は同じ。',
        'say のほか believe / report / expect / know なども同じ形で使える。',
        '主節より前の内容は to have + 過去分詞(He is said to have been ...)。',
        '「誰が言ったか」を出さずに情報を伝えられるので、ニュースや報告書で頻出。',
      ],
    },
    {
      id: 'u26-l2',
      unitId: 'u26',
      level: 'B2',
      title: '受動の不定詞・動名詞',
      objective: 'to be done / being done の形を使って、不定詞や動名詞の位置でも「〜される」という意味を表せるようになります。',
      minutes: 10,
      prereqs: ['u26-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '不定詞・動名詞の中にも「される」が入る',
          body:
            'これまで受動態は The window was broken. のように文全体の動詞で学びました。実は **to不定詞や動名詞の位置でも「〜される」と言いたい場面** があります。\n\n- I want **to invite** them.(私が招待する = する側)\n- I want **to be invited**.(私が招待される = される側)\n\n日本語ではどちらも「〜したい」の形に見えることがあるので、**主語がする側なのか、される側なのか** を意識して形を選ぶのがポイントです。',
        },
        {
          type: 'explanation',
          title: '形の作り方と使いどころ',
          body:
            '作り方はシンプルで、be を不定詞・動名詞の形にするだけです。\n\n- 不定詞の受動: **to be + 過去分詞**(to be told / to be chosen)\n- 動名詞の受動: **being + 過去分詞**(being told / being chosen)\n\nよく出る型:\n\n- want / hope / expect / need **to be done**: The form needs to be signed.\n- enjoy / avoid / mind / hate / remember **being done**: He hates being treated like a child.\n- 前置詞のあと(without / after / of など)は必ず動名詞: without **being noticed**',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Everyone wants to be respected at work, regardless of age or job title.', ja: '年齢や役職に関係なく、誰でも職場では尊重されたいと思っています。', highlight: 'to be respected' },
            { en: 'This form needs to be signed by a parent before the school trip next month.', ja: 'この用紙は来月の遠足の前に、保護者の署名を受ける必要があります。', highlight: 'to be signed' },
            { en: 'He hates being treated like a child, even though he is only nineteen.', ja: '彼はまだ19歳ですが、子ども扱いされるのを嫌がります。', highlight: 'being treated' },
            { en: 'She left the office early without being noticed.', ja: '彼女は誰にも気づかれずに早めに退社しました。', highlight: 'being noticed', note: '前置詞 without の後ろなので動名詞の受動形です。' },
            { en: 'I remember being taken to this park by my father almost every Sunday when I was little.', ja: '小さい頃、ほぼ毎週日曜日に父にこの公園へ連れてきてもらったのを覚えています。', highlight: 'being taken' },
          ],
        },
        {
          type: 'contrast',
          title: 'する側? される側?',
          left: {
            label: '能動(主語がする側)',
            items: [
              { en: 'I want to invite them to the party.', ja: '私は彼らをパーティーに招待したい。', highlight: 'to invite' },
              { en: 'She avoided answering the question.', ja: '彼女はその質問に答えるのを避けました。', highlight: 'answering' },
            ],
            pointJa: '主語が動作をする側なら to do / doing',
          },
          right: {
            label: '受動(主語がされる側)',
            items: [
              { en: 'I want to be invited to the party.', ja: '私はパーティーに招待されたい。', highlight: 'to be invited' },
              { en: 'She avoided being asked about it.', ja: '彼女はそのことについて尋ねられるのを避けました。', highlight: 'being asked' },
            ],
            pointJa: '主語が動作をされる側なら to be done / being done',
          },
          note: '形だけ暗記するのではなく、「この主語はする側か、される側か」を毎回確認するのが確実です。',
        },
      ],
      quiz: [
        {
          id: 'u26-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Nobody likes ___ what to do all the time.',
          sentenceJa: '四六時中あれこれ指図されるのが好きな人はいません。',
          choices: ['telling', 'being told', 'to told', 'being telling'],
          correctIndex: 1,
          explanation: '主語の「人」は指図されるside、つまりされる側なので、動名詞の受動形 being told を使います。',
          choiceNotes: ['telling だと「自分が指図する」side になり、意味が逆です。', null, 'to の後ろに過去分詞を直接置くことはできません。to be told なら可能です。', 'being の後ろは過去分詞です。-ing形は続けられません。'],
          audioEn: 'Nobody likes being told what to do all the time.',
        },
        {
          id: 'u26-l2-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'These documents need ___ before Friday.',
          sentenceJa: 'これらの書類は金曜日までに提出される必要があります。',
          choices: ['to submit', 'to be submitted', 'to submitting', 'be submitted'],
          correctIndex: 1,
          explanation: '主語の documents は「提出される」側なので、不定詞の受動形 to be submitted を使います。',
          choiceNotes: ['to submit だと「書類が(何かを)提出する」という不自然な意味になります。', null, 'need + to のあとは動詞の原形です。to submitting という形はありません。', 'need の後ろに be動詞の原形を直接は置けません。to が必要です。'],
          audioEn: 'These documents need to be submitted before Friday.',
        },
        {
          id: 'u26-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼女は結婚式に招待されて喜んでいました」と言いたいとき。',
          choices: [
            'She was happy to be invited to the wedding.',
            'She was happy to invite to the wedding.',
            'She was happy to inviting to the wedding.',
            'She was happy being invite to the wedding.',
          ],
          correctIndex: 0,
          explanation: '彼女は招待「される」側なので、不定詞の受動形 to be invited が正解です。',
          choiceNotes: [null, 'to invite だと彼女が招待する側になり、しかも目的語(誰を)が抜けています。', 'to の後ろに -ing形は置けません。', 'being の後ろは過去分詞 invited が必要です。'],
          audioEn: 'She was happy to be invited to the wedding.',
        },
        {
          id: 'u26-l2-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The thief entered the building without ___.',
          sentenceJa: '泥棒は誰にも見られることなく建物に入りました。',
          choices: ['seeing', 'being seen', 'to be seen', 'seen'],
          correctIndex: 1,
          explanation: '前置詞 without の後ろは動名詞で、泥棒は「見られる」側なので being seen です。',
          choiceNotes: ['seeing だと「泥棒が(何も)見ずに」という別の意味になります。', null, '前置詞の後ろに to不定詞は置けません。', '過去分詞単独では動名詞になりません。being が必要です。'],
          audioEn: 'The thief entered the building without being seen.',
        },
        {
          id: 'u26-l2-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'These documents need ___ by two different managers before Friday afternoon.',
          sentenceJa: 'これらの書類は金曜の午後までに、2人の異なる管理職の承認を受ける必要があります。',
          choices: [
            'to approve',
            'approving',
            'to be approved',
            'being approved',
          ],
          correctIndex: 2,
          explanation: '書類は「承認される」側なので、受動の不定詞 to be approved を使います。',
          choiceNotes: ['to approve だと書類が承認する側になってしまいます。', 'need -ing でも受動の意味を表せますが、to approving という形は成り立ちません。', null, 'need のあとに being + 過去分詞は続けられません。'],
          audioEn: 'These documents need to be approved by two different managers before Friday afternoon.',
        },
        {
          id: 'u26-l2-q6',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼は同僚の前で批判されるのを我慢できなかった」と言いたいとき。',
          choices: [
            'He could not stand criticizing in front of his colleagues.',
            'He could not stand to criticize in front of his colleagues.',
            'He could not stand been criticized in front of his colleagues.',
            'He could not stand being criticized in front of his colleagues.',
          ],
          correctIndex: 3,
          explanation: 'stand のあとは動名詞で、彼は批判される側なので受動の動名詞 being criticized にします。',
          choiceNotes: ['criticizing では彼が批判する側になってしまいます。', 'to criticize でも彼が批判する側になります。', 'been ではなく being を使います。', null],
          audioEn: 'He could not stand being criticized in front of his colleagues.',
        },
        {
          id: 'u26-l2-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'She managed to slip out of the reception hall without ___ by any of the reporters.',
          sentenceJa: '彼女は記者の誰にも気づかれずに、レセプション会場から抜け出すことができました。',
          choices: [
            'noticing',
            'being noticed',
            'to be noticed',
            'been noticed',
          ],
          correctIndex: 1,
          explanation: '前置詞 without のあとは動名詞で、彼女は気づかれる側なので受動の being noticed にします。',
          choiceNotes: ['noticing では彼女が気づく側になってしまいます。', null, '前置詞のあとに to不定詞は続けられません。', 'been ではなく being を使います。'],
          audioEn: 'She managed to slip out of the reception hall without being noticed by any of the reporters.',
        },
        {
          id: 'u26-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Nobody enjoys being told what to do in front of an audience.',
            'The building is old enough to be listed as a cultural property.',
            'She was delighted to have been chosen as the keynote speaker.',
            'I do not like to be ask personal questions during job interviews.',
          ],
          correctIndex: 3,
          explanation: 'to のあとは原形なので、受動にするなら to be asked です。ask のままでは受動になりません。',
          choiceNotes: ['正しい文です。enjoy のあとは動名詞で、受動なので being told。', '正しい文です。建物は登録される側なので to be listed。', '正しい文です。選ばれたのは喜んだ時点より前なので完了受動の不定詞。', null],
          audioEn: 'I do not like to be asked personal questions during job interviews.',
        },
        {
          id: 'u26-l2-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: I want to invite them.   B: I want to be invited.',
          choices: [
            'Aは自分が招待する側、Bは自分が招待される側である。',
            'Aは自分が招待される側、Bは自分が招待する側である。',
            'どちらも自分が招待する側である。',
            'どちらもすでに招待が終わっている。',
          ],
          correctIndex: 0,
          explanation: 'to不定詞を受動 to be + 過去分詞にすると、主語が動作を受ける側になります。',
          choiceNotes: [null, '受動になっているのは B のほうです。', 'B は招待される側です。', 'どちらもこれから望むことを述べています。'],
          audioEn: 'I want to invite them. I want to be invited.',
        },
        {
          id: 'u26-l2-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I still remember ___ to this beach by my grandparents almost every summer.',
          sentenceJa: 'ほとんど毎年の夏、祖父母にこの浜辺へ連れてきてもらったことを今でも覚えています。',
          choices: [
            'taking',
            'to be taken',
            'being taken',
            'to take',
          ],
          correctIndex: 2,
          explanation: 'remember + 動名詞は過去の記憶を表し、自分は連れて行かれる側なので受動の being taken にします。',
          choiceNotes: ['taking では自分が誰かを連れて行ったことになります。', 'remember to do はこれからする予定を思い出す形です。', null, 'to take でも自分が連れて行く側になってしまいます。'],
          audioEn: 'I still remember being taken to this beach by my grandparents almost every summer.',
        },
      ],
      summary: [
        '不定詞の受動は to be + 過去分詞、動名詞の受動は being + 過去分詞。',
        '主語が「する側」なら能動(to do / doing)、「される側」なら受動(to be done / being done)。',
        '前置詞(without / after など)の後ろは必ず動名詞。「されずに」は without being done。',
        'need to be done、hate being told など、よく使う型はフレーズごと覚えると速い。',
      ],
    },
    {
      id: 'u26-l3',
      unitId: 'u26',
      level: 'B2',
      title: 'get受動態と受動の慣用表現',
      objective: 'get + 過去分詞で「〜される」という出来事を会話らしく表し、be supposed to などの受動の決まり文句を使えるようになります。',
      minutes: 10,
      prereqs: ['u26-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'be の代わりに get',
          body:
            '会話では、be + 過去分詞の代わりに **get + 過去分詞** で受動を表すことがとてもよくあります。\n\n- My bike **got stolen** last night.(昨夜、自転車を盗まれた)\n- Be careful not to **get hurt**.(けがをしないように気をつけて)\n\nget を使うと「〜という出来事が起こった・状態が変わった」という**アクシデント感・変化のニュアンス**が出ます。くだけた場面で使うのが基本で、フォーマルな書き言葉では be を使います。',
        },
        {
          type: 'contrast',
          title: 'be + 過去分詞 vs get + 過去分詞',
          left: {
            label: 'be + 過去分詞',
            items: [
              { en: 'The road is closed for repairs.', ja: 'その道路は工事のため閉鎖されています。', highlight: 'is closed' },
              { en: 'This cheese is made in France.', ja: 'このチーズはフランスで作られています。', highlight: 'is made' },
            ],
            pointJa: '状態や一般的な事実。フォーマルな場面でも使える',
          },
          right: {
            label: 'get + 過去分詞',
            items: [
              { en: 'My bike got stolen last night.', ja: '昨夜、自転車を盗まれました。', highlight: 'got stolen' },
              { en: 'He got caught cheating on the test.', ja: '彼は試験でカンニングをして見つかりました。', highlight: 'got caught' },
            ],
            pointJa: '「出来事が起きた」感じが強い。主に会話で',
          },
          note: 'get受動態は悪い出来事(hurt / stolen / fired)と特に相性がよいですが、get paid / get promoted のような良いことにも使えます。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Be careful not to get hurt when you are carrying those heavy boxes downstairs.', ja: 'あの重い箱を階下へ運ぶときは、けがをしないよう気をつけてね。', highlight: 'get hurt' },
            { en: 'We get paid on the twenty-fifth of every month, or on the previous Friday if it falls on a weekend.', ja: '給料は毎月25日、週末に当たる場合はその前の金曜日に支払われます。', highlight: 'get paid' },
            { en: 'They got married in a small wooden church in Nagano with only twelve guests.', ja: '彼らは招待客12人だけで、長野の小さな木造の教会で結婚しました。', highlight: 'got married', note: 'get married / get dressed / get lost は変化を表す日常表現です。' },
            { en: 'The meeting is supposed to start at ten, but the projector still is not working.', ja: '会議は10時に始まることになっていますが、プロジェクターがまだ動きません。', highlight: 'is supposed to' },
            { en: 'My grandfather was born in a small fishing town.', ja: '祖父は小さな漁師町で生まれました。', highlight: 'was born', note: 'be born は必ず受動の形で使う決まり文句です。' },
            { en: 'The hotel is located within walking distance of the station.', ja: 'そのホテルは駅から歩ける距離にあります。', highlight: 'is located' },
          ],
        },
        {
          type: 'explanation',
          title: '受動の形が決まり文句になった表現',
          body:
            '受動態の形のまま「決まり文句」として使われる表現があります。フレーズごと覚えてしまうのが早道です。\n\n- **be supposed to do**: 〜することになっている(規則・予定・期待)。過去形 was supposed to は「〜するはずだったのに、しなかった」という含みを持ちます。\n- **be born**: 生まれる。過去の事実は was born。「生む側」の能動では使いません。\n- **be located**: 〜に位置している。施設の場所紹介の定番。\n- **be involved in**: 〜に関わっている。\n- **get married / get dressed / get lost**: 「結婚する・服を着る・道に迷う」。get で状態の変化を表します。',
        },
      ],
      quiz: [
        {
          id: 'u26-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Three people ___ in the accident last night.',
          sentenceJa: '昨夜の事故で3人がけがをしました。',
          choices: ['got hurt', 'got hurting', 'hurt', 'got to hurt'],
          correctIndex: 0,
          explanation: '「けがをさせられた = けがをした」という出来事なので、会話でよく使う get + 過去分詞の形 got hurt が自然です。',
          choiceNotes: [null, 'get受動態は get + 過去分詞です。-ing形は使いません。', 'hurt を能動で使うと「3人が(誰かを)傷つけた」となり、目的語も必要です。', 'got to hurt は「傷つける機会を得た」のような別の意味になってしまいます。'],
          audioEn: 'Three people got hurt in the accident last night.',
        },
        {
          id: 'u26-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'You ___ to wear a helmet on this construction site.',
          sentenceJa: 'この工事現場ではヘルメットを着用することになっています。',
          choices: ['are supposed', 'suppose', 'are supposing', 'supposed'],
          correctIndex: 0,
          explanation: '「〜することになっている」という規則は be supposed to do で表します。受動の形の決まり文句です。',
          choiceNotes: [null, '能動の suppose は「思う・仮定する」で、規則の意味になりません。', '進行形にはできません。be supposed to という固定の形です。', 'be動詞のない supposed だけでは文になりません。'],
          audioEn: 'You are supposed to wear a helmet on this construction site.',
        },
        {
          id: 'u26-l3-q3',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'You were supposed to call me last night.',
          choices: [
            '昨夜、電話するはずだったのにしなかった。',
            '昨夜、電話してくれてありがとう。',
            '昨夜、電話する必要はなかった。',
            '昨夜、電話したと言われている。',
          ],
          correctIndex: 0,
          explanation: 'was / were supposed to は「〜するはずだった(のに実際はしなかった)」という含みを持つ、軽い非難や残念さの表現です。',
          choiceNotes: [null, '実際には電話が来ていない、というのがこの文の含みです。', '「必要がなかった」は didn\'t have to で表します。', '「〜したと言われている」は be said to have done の形です。'],
          audioEn: 'You were supposed to call me last night.',
        },
        {
          id: 'u26-l3-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My mother ___ born in a small village in Kyushu.',
          sentenceJa: '母は九州の小さな村で生まれました。',
          choices: ['was', 'got', 'is', 'has been'],
          correctIndex: 0,
          explanation: 'be born は be を使う決まり文句で、特定の過去の事実なので過去形 was born にします。',
          choiceNotes: [null, 'born には get を使わず、be born という固定の形で言います。', 'is born は「一般に生まれるものだ」という一般論で使う形で、特定の過去の出来事には合いません。', '生まれた時点がはっきりした過去の事実なので、現在完了ではなく過去形を使います。'],
          audioEn: 'My mother was born in a small village in Kyushu.',
        },
        {
          id: 'u26-l3-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Two of our suitcases ___ damaged somewhere between Narita and Helsinki.',
          sentenceJa: 'スーツケースのうち2つが、成田とヘルシンキの間のどこかで破損しました。',
          choices: [
            'got',
            'were getting',
            'have got',
            'get',
          ],
          correctIndex: 0,
          explanation: 'get受動態は予期しない出来事や変化を表します。過去の出来事なので got を使います。',
          choiceNotes: [null, 'get受動態を進行形にすることはほとんどありません。', '現在完了では過去の一時点を示す文脈と合いません。', '現在形では過去の出来事を表せません。'],
          audioEn: 'Two of our suitcases got damaged somewhere between Narita and Helsinki.',
        },
        {
          id: 'u26-l3-q6',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'The delivery was supposed to arrive before noon, but it finally came at eight in the evening.',
          choices: [
            '配達は正午前に届くはずだったが、実際は夜8時になった。',
            '配達は夜8時に届く予定で、そのとおりになった。',
            '配達は正午前に届き、そのあと夜8時にもう一度届いた。',
            '配達は正午前に届く予定はなかった。',
          ],
          correctIndex: 0,
          explanation: 'be supposed to は「〜することになっている」という予定や約束を表し、but 以下でそれが守られなかったことを示しています。',
          choiceNotes: [null, '予定は正午前で、実際とはずれています。', '届いたのは夜8時の1回だけです。', '正午前に届く予定でした。'],
          audioEn: 'The delivery was supposed to arrive before noon, but it finally came at eight in the evening.',
        },
        {
          id: 'u26-l3-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Please hold the handrail on the escalator so that you do not ___ .',
          sentenceJa: 'エスカレーターではけがをしないよう、手すりにつかまってください。',
          choices: [
            'get hurt',
            'get hurting',
            'be hurting',
            'hurt to be',
          ],
          correctIndex: 0,
          explanation: 'get hurt は「けがをする」という変化を表す定番の表現です。be hurt が状態を表すのに対し、get hurt は出来事を表します。',
          choiceNotes: [null, 'get のあとは過去分詞にします。-ing は続けられません。', 'be hurting では痛みが続いている状態の表現になります。', '語順が崩れており、文として成り立ちません。'],
          audioEn: 'Please hold the handrail on the escalator so that you do not get hurt.',
        },
        {
          id: 'u26-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'My phone got stolen while I was watching the fireworks by the river.',
            'We are supposed to submit the application form by the end of this month.',
            'He got promoted to section manager after working here for only two years.',
            'The museum is get located just behind the old city hall.',
          ],
          correctIndex: 3,
          explanation: 'be located は状態を表す決まり文句で、get とは組み合わせません。正しくは The museum is located です。',
          choiceNotes: ['正しい文です。予期しない被害を get受動態で表しています。', '正しい文です。be supposed to で決まりや予定を表しています。', '正しい文です。昇進という変化を get で表しています。', null],
          audioEn: 'The museum is located just behind the old city hall.',
        },
        {
          id: 'u26-l3-q9',
          prompt: '次の2文のニュアンスの違いとして正しいものを選んでください。',
          sentence: 'A: The window was broken.   B: The window got broken.',
          choices: [
            'Aは割れている状態にも読め、Bは割れるという出来事が起きたことを強く示す。',
            'Aは出来事を、Bは状態だけを表す。',
            'AもBもこれから割れる予定を表す。',
            'Aは誰が割ったかを必ず示す。',
          ],
          correctIndex: 0,
          explanation: 'be受動態は状態と出来事の両方に読めますが、get受動態は変化が起きたことをはっきり示します。',
          choiceNotes: [null, '出来事をはっきり示すのは get のほうです。', 'どちらもすでに起きたことを述べています。', 'by句がなければ誰が割ったかは示されません。'],
          audioEn: 'The window was broken. The window got broken.',
        },
        {
          id: 'u26-l3-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'We ___ on the twenty-fifth, so most people do their shopping that weekend.',
          sentenceJa: '私たちは25日に給料が支払われるので、たいていの人はその週末に買い物をします。',
          choices: [
            'get paying',
            'get paid',
            'are paying',
            'get pay',
          ],
          correctIndex: 1,
          explanation: 'get paid は「給料が支払われる」という日常表現です。get のあとは過去分詞にします。',
          choiceNotes: ['get のあとに -ing は続けられません。', null, 'are paying では自分たちが支払う側になってしまいます。', 'get のあとに原形は続けられません。'],
          audioEn: 'We get paid on the twenty-fifth, so most people do their shopping that weekend.',
        },
      ],
      summary: [
        '会話では be の代わりに get + 過去分詞で「〜される」を表せる(get hurt / get paid / got stolen)。',
        'get受動態は「出来事が起きた・状態が変わった」感じが強く、アクシデントや変化と相性がよい。',
        'be supposed to は「〜することになっている」。過去形は「するはずだったのにしなかった」の含み。',
        'be born / be located / get married などの決まり文句はフレーズごと覚える。',
      ],
    },
  ],
}
