import type { GrammarUnit } from '../../types'

// U28 談話標識と文章構成

export const u28: GrammarUnit = {
  id: 'u28',
  level: 'B2',
  title: '談話標識と文章構成',
  lessons: [
    {
      id: 'u28-l1',
      unitId: 'u28',
      level: 'B2',
      title: '逆接・譲歩 however / despite / although',
      objective: 'however / although / despite などの逆接・譲歩の表現を、後ろに続く形に合わせて正しく使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u16-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '同じ「しかし」でも、つなぎ方が違う',
          body:
            '日本語の「しかし」「〜だけれど」「〜にもかかわらず」は、英語では**何をつなぐか**で使う語が決まっています。\n\n- **文と文**をつなぐ → however(前の文をピリオドで閉じ、新しい文の頭に置く)\n- **1つの文の中の節と節**をつなぐ → but / although\n- **名詞(句)**につなぐ → despite / in spite of\n\n意味はどれも近いので、「後ろに何が続くか」を見るのが使い分けの最短ルートです。B2の読み書きでは、この形の違いが正確さを大きく左右します。',
        },
        {
          type: 'table',
          title: '逆接・譲歩の標識(機能別)',
          headers: ['標識', '働き', '後ろに続く形・位置'],
          rows: [
            ['however', '前の文全体と対比する(フォーマル)', '新しい文の頭に置き、コンマを打つ'],
            ['but', '1つの文の中で節と節をつなぐ(カジュアル)', 'コンマ + but + 主語 + 動詞'],
            ['although / even though', '「〜だけれども」という譲歩の節を作る', '主語 + 動詞'],
            ['despite / in spite of', '「〜にもかかわらず」', '名詞・動名詞'],
            ['on the other hand', '2つの側面・選択肢を対比する', '新しい文の頭に置き、コンマを打つ'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The restaurant is expensive. However, the food is worth every yen.', ja: 'そのレストランは高いです。しかし、料理はその値段の価値があります。', highlight: 'However,' },
            { en: 'Although it was raining steadily all afternoon, the outdoor concert went ahead as planned.', ja: '午後じゅう雨が降り続いていましたが、野外コンサートは予定どおり行われました。', highlight: 'Although' },
            { en: 'Despite the heavy traffic on the expressway, we still arrived at the airport on time.', ja: '高速道路のひどい渋滞にもかかわらず、私たちは時間どおり空港に着きました。', highlight: 'Despite', note: 'despite の後ろは名詞です。節は続けられません。' },
            { en: 'In spite of feeling sick all morning, she finished the presentation without a single mistake.', ja: '午前中ずっと体調が悪かったにもかかわらず、彼女は一つのミスもなくプレゼンをやり遂げました。', highlight: 'In spite of', note: '動名詞(feeling)を続けることもできます。' },
            { en: 'Working from home saves time. On the other hand, it can feel lonely.', ja: '在宅勤務は時間の節約になります。その一方で、孤独に感じることもあります。', highlight: 'On the other hand,' },
          ],
        },
        {
          type: 'contrast',
          title: 'however と but の使い分け',
          left: {
            label: 'however(文と文・フォーマル)',
            items: [
              { en: 'The plan sounded great. However, it had one serious problem.', ja: 'その計画はすばらしく思えました。しかし、1つ重大な問題がありました。', highlight: 'However,' },
            ],
            pointJa: '前の文をピリオドで閉じ、新しい文の頭でコンマとともに使う。書き言葉・フォーマルな場面向き',
          },
          right: {
            label: 'but(文中・カジュアル)',
            items: [
              { en: 'The plan sounded great, but it had one serious problem.', ja: 'その計画はすばらしく思えたけれど、1つ重大な問題があった。', highlight: 'but' },
            ],
            pointJa: 'コンマ + but で1つの文の中に収める。会話で最もよく使う',
          },
          note: 'however は接続詞ではなく副詞なので、コンマだけで2つの文をつなぐことはできません。ピリオド(またはセミコロン)で文を区切ってから使います。',
        },
        {
          type: 'explanation',
          title: 'despite と although の境界線',
          body:
            '意味はほぼ同じ「〜にもかかわらず」でも、続けられる形がはっきり分かれます。\n\n- **although + 主語 + 動詞**: Although the tickets were expensive, we went.\n- **despite + 名詞・動名詞**: Despite the high prices, we went. / Despite paying a lot, we enjoyed it.\n\n注意点は2つあります。\n\n- × despite of — この形は存在しません(in spite **of** との混同に注意)\n- despite の後ろに節を続けたいときは **despite the fact that + 主語 + 動詞** が使えます',
        },
      ],
      quiz: [
        {
          id: 'u28-l1-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ the heavy rain, the soccer match was not canceled.',
          sentenceJa: '大雨にもかかわらず、サッカーの試合は中止になりませんでした。',
          choices: ['Although', 'Despite', 'However', 'Even though'],
          correctIndex: 1,
          explanation: '空所の後ろは the heavy rain という名詞です。名詞を続けられるのは前置詞の despite だけです。',
          choiceNotes: ['although の後ろには主語 + 動詞の節が必要です。名詞だけは続けられません。', null, 'however は副詞なので、後ろに名詞を目的語として取れません。', 'even though も although と同じく、後ろに節が必要です。'],
          audioEn: 'Despite the heavy rain, the soccer match was not canceled.',
        },
        {
          id: 'u28-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「この街の家賃は高いです。しかし、多くの若者が住みたがります」と言いたいとき。',
          choices: [
            'Rents in this city are high. However, many young people want to live there.',
            'Rents in this city are high, however many young people want to live there.',
            'Despite rents in this city are high, many young people want to live there.',
            'Although rents in this city are high. Many young people want to live there.',
          ],
          correctIndex: 0,
          explanation: 'however は前の文をピリオドで閉じてから、新しい文の頭でコンマとともに使います。',
          choiceNotes: [null, 'however はコンマだけで2つの文をつなげません。前の文をピリオドで区切る必要があります。', 'despite の後ろに主語 + 動詞の節は続けられません。節をつなぐなら although を使います。', 'although の節は単独では文になれません。主節とコンマでつないで1つの文にします。'],
          audioEn: 'Rents in this city are high. However, many young people want to live there.',
        },
        {
          id: 'u28-l1-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'In spite of the delay, we made our connecting flight.',
            'Despite of his injury, he played the entire game.',
            'Even though the store was crowded, the staff stayed calm.',
            'The hotel was old. However, the rooms were spotless.',
          ],
          correctIndex: 1,
          explanation: 'despite は単独で前置詞なので of は不要です。of を使うのは in spite of の形のときだけです。',
          choiceNotes: ['正しい文です。in spite of + 名詞の形です。', null, '正しい文です。even though + 主語 + 動詞の節です。', '正しい文です。前の文をピリオドで閉じ、However をコンマとともに使っています。'],
          audioEn: 'Despite his injury, he played the entire game.',
        },
        {
          id: 'u28-l1-q4',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'This apartment is close to the station. ___, the rent is quite high.',
          sentenceJa: 'このアパートは駅に近いです。その一方で、家賃はかなり高いです。',
          choices: ['On the other hand', 'Despite', 'Although', 'In spite of'],
          correctIndex: 0,
          explanation: '良い面と悪い面という2つの側面を対比しているので、新しい文の頭にコンマとともに置ける on the other hand が合います。',
          choiceNotes: [null, 'despite は前置詞なので、後ろに名詞が必要です。コンマで区切って文頭に単独では置けません。', 'although は節と節をつなぐ接続詞で、コンマで区切って文頭に単独では置けません。', 'in spite of も後ろに名詞が必要で、この位置には置けません。'],
          audioEn: 'This apartment is close to the station. On the other hand, the rent is quite high.',
        },
        {
          id: 'u28-l1-q5',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ the enormous cost, the city council approved the new stadium project.',
          sentenceJa: '莫大な費用にもかかわらず、市議会は新スタジアム計画を承認しました。',
          choices: [
            'Although',
            'Despite',
            'However',
            'Even though',
          ],
          correctIndex: 1,
          explanation: '空所のあとは the enormous cost という名詞句です。名詞を続けられる譲歩表現は despite です。',
          choiceNotes: ['although のあとには主語と動詞のある節が必要です。', null, 'however は接続副詞で、名詞句を直接続けられません。', 'even though も節を必要とします。'],
          audioEn: 'Despite the enormous cost, the city council approved the new stadium project.',
        },
        {
          id: 'u28-l1-q6',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Sales in Europe fell sharply last year, ___ sales in Asia grew by nearly twenty percent.',
          sentenceJa: '昨年ヨーロッパの売上は急落しましたが、一方でアジアの売上は20パーセント近く伸びました。',
          choices: [
            'despite',
            'whereas',
            'therefore',
            'moreover',
          ],
          correctIndex: 1,
          explanation: 'whereas は2つの事実を並べて対比する接続詞です。硬めの書き言葉でよく使われます。',
          choiceNotes: ['despite のあとには名詞句が必要です。', null, 'therefore は結果を示し、対比にはなりません。', 'moreover は情報を追加する語です。'],
          audioEn: 'Sales in Europe fell sharply last year, whereas sales in Asia grew by nearly twenty percent.',
        },
        {
          id: 'u28-l1-q7',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The evidence against him was weak. ___ , the committee decided to suspend him.',
          sentenceJa: '彼に不利な証拠は弱いものでした。それにもかかわらず、委員会は彼の停職を決めました。',
          choices: [
            'Therefore',
            'Nevertheless',
            'For example',
            'In addition',
          ],
          correctIndex: 1,
          explanation: 'nevertheless は「それにもかかわらず」と、前の文から予想されるのとは逆の内容を導く接続副詞です。',
          choiceNotes: ['therefore なら証拠が弱いから停職しない、という流れになるはずです。', null, 'for example は例示で、逆接にはなりません。', 'in addition は情報の追加です。'],
          audioEn: 'The evidence against him was weak. Nevertheless, the committee decided to suspend him.',
        },
        {
          id: 'u28-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Although the deadline was extended, several teams still failed to submit on time.',
            'In spite of the warning signs, a few hikers continued towards the summit.',
            'The hotel was fully booked. However, the staff found us a room nearby.',
            'Despite we booked early, we could not get seats together on the flight.',
          ],
          correctIndex: 3,
          explanation: 'despite のあとには名詞や動名詞を置きます。節を続けるなら although を使い、Although we booked early とします。',
          choiceNotes: ['正しい文です。although のあとに節が続いています。', '正しい文です。in spite of のあとに名詞句が続いています。', '正しい文です。However が2文をつないでいます。', null],
          audioEn: 'Although we booked early, we could not get seats together on the flight.',
        },
        {
          id: 'u28-l1-q9',
          prompt: '次の文を despite を使って書き換えたものとして正しいものを選んでください。',
          sentence: 'Although she had very little experience, she was offered the position.',
          choices: [
            'Despite she had very little experience, she was offered the position.',
            'Despite of her very little experience, she was offered the position.',
            'Despite having very little experience, she was offered the position.',
            'Despite that she had very little experience, she was offered the position.',
          ],
          correctIndex: 2,
          explanation: 'despite のあとには名詞か動名詞を置きます。節を動名詞に変えて having very little experience とします。',
          choiceNotes: ['despite のあとに節は置けません。', 'despite of という形はありません。in spite of なら正しい形です。', null, 'despite that という形は一般的ではありません。'],
          audioEn: 'Despite having very little experience, she was offered the position.',
        },
        {
          id: 'u28-l1-q10',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: The plan sounded great, but it had one serious problem.   B: The plan sounded great. However, it had one serious problem.',
          choices: [
            'but は1文の中で節をつなぎ、however は文と文をつなぐ接続副詞である。',
            'but は文と文をつなぎ、however は節をつなぐ接続詞である。',
            'however はカンマなしで使うのが普通である。',
            '意味も使い方もまったく同じで、置き換えても構わない。',
          ],
          correctIndex: 0,
          explanation: 'but は等位接続詞で1文の中の節をつなぎ、however は接続副詞なので独立した文の先頭でカンマとともに使います。',
          choiceNotes: [null, '役割が逆です。', '文頭の however の後ろにはカンマを置くのが普通です。', '品詞が異なるため、そのままでは置き換えられません。'],
          audioEn: 'The plan sounded great. However, it had one serious problem.',
        },
      ],
      summary: [
        '逆接・譲歩は「後ろに何が続くか」で語を選ぶ。文と文 = however、節 = but / although、名詞 = despite / in spite of。',
        'however は副詞。前の文をピリオドで閉じ、新しい文の頭でコンマとともに使う。コンマだけで文をつなげない。',
        'despite of という形はない。節を続けたいときは despite the fact that を使う。',
        'on the other hand は2つの側面・選択肢の対比に使い、文頭でコンマとともに置く。',
      ],
    },
    {
      id: 'u28-l2',
      unitId: 'u28',
      level: 'B2',
      title: '因果・追加・例示 therefore / moreover / such as',
      objective: 'therefore / in addition / such as などを使って、因果・追加・例示の論理関係をはっきり示せるようになります。',
      minutes: 10,
      prereqs: ['u28-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '論理の方向を教える道路標識',
          body:
            '談話標識は、読み手・聞き手に「話がこれからどちらへ進むか」を予告する**道路標識**のような言葉です。\n\n- **因果**: だから結果はこうなる → therefore / as a result\n- **追加**: 同じ方向にもう1つ積み上げる → in addition / moreover\n- **例示**: 具体例で説明する → for example / such as\n\n標識が正しければ、多少難しい内容でも読み手は迷子になりません。逆に標識を間違えると、1文1文は正しくても文章全体が伝わらなくなります。',
        },
        {
          type: 'table',
          title: '因果・追加・例示の標識(機能別)',
          headers: ['機能', '標識', '使い方のポイント'],
          rows: [
            ['因果(だから)', 'therefore / as a result / consequently', '新しい文の頭に置き、コンマを打つ。フォーマルな響き'],
            ['追加(さらに)', 'in addition / moreover / furthermore', '新しい文の頭に置き、コンマを打つ'],
            ['追加(〜に加えて)', 'in addition to', '前置詞。後ろに名詞・動名詞を続ける'],
            ['例示(たとえば)', 'for example / for instance', '文頭に置き、コンマのあとに完全な文を続ける'],
            ['例示(〜のような)', 'such as', '名詞の直後に付けて、その例を並べる'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The demand for the product doubled within three months. Therefore, we increased production at both factories.', ja: '製品の需要が3か月で2倍になりました。そのため、私たちは両方の工場で生産を増やしました。', highlight: 'Therefore,' },
            { en: 'The new model is noticeably lighter. Moreover, the battery lasts almost twice as long.', ja: '新モデルは目に見えて軽量です。さらに、バッテリーはほぼ2倍長持ちします。', highlight: 'Moreover,' },
            { en: 'In addition to English, she speaks Portuguese and Korean well enough to work in both.', ja: '英語に加えて、彼女はどちらの言語でも仕事ができる程度にポルトガル語と韓国語を話します。', highlight: 'In addition to', note: 'in addition to は前置詞なので、後ろは名詞です。' },
            { en: 'I like winter sports such as skiing and snowboarding, but I have never tried skating.', ja: 'スキーやスノーボードのようなウィンタースポーツが好きですが、スケートはやったことがありません。', highlight: 'such as' },
            { en: 'Some habits are hard to change. For example, I still check my phone before bed.', ja: '変えるのが難しい習慣もあります。たとえば、私は今でも寝る前にスマホを見てしまいます。', highlight: 'For example,' },
            { en: 'It snowed heavily all night in the north. As a result, most of the morning trains were delayed.', ja: '北部では一晩中激しく雪が降りました。その結果、朝の電車のほとんどが遅れました。', highlight: 'As a result,' },
          ],
        },
        {
          type: 'contrast',
          title: 'such as と for example の使い分け',
          left: {
            label: 'such as(名詞にくっつける)',
            items: [
              { en: 'She enjoys quiet hobbies such as reading and knitting.', ja: '彼女は読書や編み物のような静かな趣味を楽しんでいます。', highlight: 'such as' },
            ],
            pointJa: '名詞の直後に置き、その名詞の具体例をそのまま並べる。文の途中で使う',
          },
          right: {
            label: 'for example(文に例を足す)',
            items: [
              { en: 'She enjoys quiet hobbies. For example, she reads and knits every evening.', ja: '彼女は静かな趣味を楽しんでいます。たとえば、毎晩読書と編み物をします。', highlight: 'For example,' },
            ],
            pointJa: '新しい文の頭に置き、コンマのあとに完全な文を続ける',
          },
          note: 'such as の後ろは名詞(句)だけ、for example の後ろは完全な文、と覚えると迷いません。',
        },
        {
          type: 'explanation',
          title: 'therefore と so の温度差',
          body:
            'therefore と so はどちらも「だから」ですが、使う場面が違います。\n\n- **so**: 会話・カジュアルな文章向き。コンマ + so で文中に置く(It was late, so we went home.)\n- **therefore**: レポート・ビジネスメールなどの書き言葉向き。新しい文の頭でコンマとともに使う\n\n同じことは追加の標識にも言えます。会話で「さらに」は and や also が自然で、moreover / furthermore はフォーマルな書き言葉です。話し言葉で連発すると堅苦しく響くので、場面に合わせて選びましょう。',
        },
      ],
      quiz: [
        {
          id: 'u28-l2-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The main road was closed for repairs. ___, we took a different route.',
          sentenceJa: '幹線道路が工事で通行止めでした。そのため、私たちは別のルートを通りました。',
          choices: ['Therefore', 'Moreover', 'For example', 'On the other hand'],
          correctIndex: 0,
          explanation: '前の文が原因、後ろの文がその結果という因果関係なので、therefore が合います。',
          choiceNotes: [null, 'moreover は「さらに」と同じ方向の情報を追加する標識で、原因から結果への流れには合いません。', 'for example は例を挙げる標識です。別ルートは通行止めの例ではなく結果です。', 'on the other hand は対比の標識です。前後の文は対立していません。'],
          audioEn: 'The main road was closed for repairs. Therefore, we took a different route.',
        },
        {
          id: 'u28-l2-q2',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The museum has works by famous artists ___ Monet and Picasso.',
          sentenceJa: 'その美術館にはモネやピカソのような有名な画家の作品があります。',
          choices: ['such as', 'for example', 'therefore', 'in addition'],
          correctIndex: 0,
          explanation: '名詞 famous artists の直後にその具体例を並べているので、名詞にくっつけて使う such as が合います。',
          choiceNotes: [null, 'for example は文頭でコンマとともに完全な文を続ける使い方が基本で、名詞に直接つなげる位置には合いません。', 'therefore は因果を表す標識で、例を挙げる働きはありません。', 'in addition は「さらに」と情報を追加する副詞で、名詞に例をつなげる働きはありません。'],
          audioEn: 'The museum has works by famous artists such as Monet and Picasso.',
        },
        {
          id: 'u28-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「この仕事は給料が良いです。その上、在宅勤務もできます」と言いたいとき。',
          choices: [
            'This job pays well. Moreover, you can work from home.',
            'This job pays well. Therefore, you can work from home.',
            'This job pays well. In addition to, you can work from home.',
            'This job pays well, such as working from home.',
          ],
          correctIndex: 0,
          explanation: '給料の良さに「在宅勤務ができる」という別の利点を積み上げているので、追加の標識 moreover を使います。',
          choiceNotes: [null, 'therefore は因果の標識です。給料が良いことは在宅勤務の原因ではありません。', 'in addition to は前置詞なので後ろに名詞が必要です。文を続けるなら to のない In addition, を使います。', '在宅勤務は「給料が良いこと」の例ではないので、such as は使えません。'],
          audioEn: 'This job pays well. Moreover, you can work from home.',
        },
        {
          id: 'u28-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The store was out of stock. Therefore, we ordered the parts online.',
            'Moreover the high cost, the plan had several technical problems.',
            'Big cities such as Tokyo and Osaka attract many tourists.',
            'The team practiced every day. As a result, they won the tournament.',
          ],
          correctIndex: 1,
          explanation: 'moreover は副詞なので、後ろに名詞を直接つなげられません。「〜に加えて」と名詞を続けるなら前置詞の in addition to を使います。',
          choiceNotes: ['正しい文です。前の文の結果を Therefore が導いています。', null, '正しい文です。名詞の直後に such as で例を並べています。', '正しい文です。As a result が因果関係を示しています。'],
          audioEn: 'In addition to the high cost, the plan had several technical problems.',
        },
        {
          id: 'u28-l2-q5',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The factory had been losing money for years. ___ , the head office decided to close it.',
          sentenceJa: 'その工場は何年も赤字が続いていました。そのため、本社は閉鎖を決めました。',
          choices: [
            'Nevertheless',
            'For instance',
            'Therefore',
            'On the other hand',
          ],
          correctIndex: 2,
          explanation: '赤字が続いた結果として閉鎖を決めているので、結果を導く therefore が適切です。',
          choiceNotes: ['nevertheless は逆接で、この流れには合いません。', 'for instance は例示です。', null, 'on the other hand は対比を示します。'],
          audioEn: 'The factory had been losing money for years. Therefore, the head office decided to close it.',
        },
        {
          id: 'u28-l2-q6',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The apartment is close to the station. ___ , the rent is surprisingly reasonable.',
          sentenceJa: 'そのアパートは駅に近いです。さらに、家賃も驚くほど手ごろです。',
          choices: [
            'Moreover',
            'However',
            'In short',
            'As a result',
          ],
          correctIndex: 0,
          explanation: 'よい点を積み重ねているので、情報を追加する moreover が適切です。',
          choiceNotes: [null, 'however は逆接で、よい点の追加には合いません。', 'in short は要約を導きます。', 'as a result は結果を導きます。'],
          audioEn: 'The apartment is close to the station. Moreover, the rent is surprisingly reasonable.',
        },
        {
          id: 'u28-l2-q7',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The museum houses works by major impressionists ___ Monet, Renoir and Degas.',
          sentenceJa: 'その美術館はモネ、ルノワール、ドガといった主要な印象派の作品を所蔵しています。',
          choices: [
            'for example,',
            'such as',
            'that is to say',
            'as a result of',
          ],
          correctIndex: 1,
          explanation: '名詞をそのまま並べて例を挙げるときは such as を使います。文を続ける for example とは形が違います。',
          choiceNotes: ['for example のあとには通常カンマを置いて文を続けます。名詞を直接続ける形には向きません。', null, 'that is to say は言い換えを導きます。', 'as a result of は原因を示します。'],
          audioEn: 'The museum houses works by major impressionists such as Monet, Renoir and Degas.',
        },
        {
          id: 'u28-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'In addition to the entrance fee, visitors must pay for the audio guide separately.',
            'The bridge was damaged in the typhoon. As a result, the ferry service was doubled.',
            'Many nutrients, for instance vitamin C, are lost when vegetables are boiled too long.',
            'The road was icy, therefore we should have left much earlier that morning.',
          ],
          correctIndex: 3,
          explanation: 'therefore は接続詞ではないので、カンマだけで2つの文をつなげません。ピリオドかセミコロンで区切ります。',
          choiceNotes: ['正しい文です。in addition to のあとに名詞句が続いています。', '正しい文です。As a result で結果を導いています。', '正しい文です。for instance で例を挿入しています。', null],
          audioEn: 'The road was icy. Therefore, we should have left much earlier that morning.',
        },
        {
          id: 'u28-l2-q9',
          prompt: '次の文の論理関係として正しいものを選んでください。',
          sentence: 'The new software reduces errors by half. In addition, it cuts processing time by thirty percent.',
          choices: [
            '前の内容に情報を積み重ねている。',
            '前の内容と逆のことを述べている。',
            '前の内容を要約している。',
            '前の内容の例を挙げている。',
          ],
          correctIndex: 0,
          explanation: 'in addition は前の文に情報を追加する接続副詞です。同じ方向の利点を積み重ねています。',
          choiceNotes: [null, '逆接なら however や nevertheless を使います。', '要約なら in short などを使います。', '例示なら for example を使います。'],
          audioEn: 'The new software reduces errors by half. In addition, it cuts processing time by thirty percent.',
        },
        {
          id: 'u28-l2-q10',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'Sea levels are rising, ___ many coastal cities will need expensive flood defences.',
          sentenceJa: '海面が上昇しており、その結果として多くの沿岸都市が高価な洪水対策を必要とするでしょう。',
          choices: [
            'such as',
            'in short',
            'so',
            'for example',
          ],
          correctIndex: 2,
          explanation: 'カンマ1つで2つの節をつなぐには等位接続詞が必要です。結果を導く so が適切です。',
          choiceNotes: ['such as のあとには名詞を置きます。', 'in short は接続副詞なので、カンマだけで節はつなげません。', null, 'for example も接続副詞で、カンマだけでは節をつなげません。'],
          audioEn: 'Sea levels are rising, so many coastal cities will need expensive flood defences.',
        },
      ],
      summary: [
        '因果は therefore / as a result、追加は in addition / moreover、例示は for example / such as。標識で論理の方向を予告する。',
        'such as は名詞の直後に例を並べ、for example は文頭でコンマのあとに完全な文を続ける。',
        'in addition は副詞(文頭 + コンマ)、in addition to は前置詞(+ 名詞)。形を混ぜない。',
        'therefore / moreover はフォーマルな書き言葉向き。会話では so / and / also が自然。',
      ],
    },
    {
      id: 'u28-l3',
      unitId: 'u28',
      level: 'B2',
      title: '順序・要約・言い換え',
      objective: 'first of all / in short / in other words などで話の順序を示し、要約や言い換えで内容を整理して伝えられるようになります。',
      minutes: 10,
      prereqs: ['u28-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '話の「設計図」を先に見せる',
          body:
            'プレゼンや長めの説明では、聞き手は「今どこの話をしているのか」を見失いがちです。順序・要約・言い換えの標識は、話の**設計図**を示して聞き手を案内する道具です。\n\n- **順序**: 話を段階に分ける → first of all / then / finally\n- **要約**: 長い話を一言にまとめる → in short / to sum up\n- **言い換え**: 同じ内容を別の言葉で分かりやすく → in other words\n\nどれも文の頭に置いてコンマで区切るのが基本の形です。',
        },
        {
          type: 'table',
          title: '順序・要約・言い換えの標識(機能別)',
          headers: ['機能', '標識', '使う場面'],
          rows: [
            ['順序(最初に)', 'first of all / to begin with', '話や手順の出発点を示す'],
            ['順序(次に・最後に)', 'then / next / finally', '段階を追って話を進める'],
            ['要約', 'in short / to sum up / in conclusion', '長い内容を短くまとめる。in conclusion はスピーチや文章の締めに'],
            ['言い換え', 'in other words / that is to say', '直前の内容を別の言葉で分かりやすく言い直す'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'First of all, let me thank everyone for coming here on such a cold morning.', ja: 'まず初めに、こんなに寒い朝にお越しいただいた皆さまに感謝いたします。', highlight: 'First of all,' },
            { en: 'Chop the onions finely. Then add them to the hot pan with a little olive oil.', ja: '玉ねぎを細かく刻みます。それから少量のオリーブオイルと一緒に熱したフライパンに入れます。', highlight: 'Then' },
            { en: 'Finally, let the soup simmer gently for twenty minutes without putting the lid on.', ja: '最後に、ふたをせずにスープを20分ほど弱火で煮込みます。', highlight: 'Finally,' },
            { en: 'The flight was delayed, the hotel lost our booking, and it rained all week. In short, the trip was a disaster.', ja: '飛行機は遅れ、ホテルは予約を紛失し、一週間ずっと雨でした。要するに、その旅行は散々でした。', highlight: 'In short,' },
            { en: 'The offer expires on Friday. In other words, you need to decide this week.', ja: 'そのオファーの期限は金曜日です。つまり、今週中に決める必要があるということです。', highlight: 'In other words,' },
            { en: 'To sum up, the new system is faster, cheaper, and considerably easier for beginners to use.', ja: 'まとめると、新システムはより速く、安く、初心者にとってかなり使いやすいということです。', highlight: 'To sum up,' },
          ],
        },
        {
          type: 'contrast',
          title: 'first(of all)と at first の使い分け',
          left: {
            label: 'first / first of all(順序の最初)',
            items: [
              { en: 'First, preheat the oven to 200 degrees.', ja: 'まず、オーブンを200度に予熱します。', highlight: 'First,' },
              { en: 'First of all, I want to explain the schedule.', ja: 'まず初めに、スケジュールを説明したいと思います。', highlight: 'First of all,' },
            ],
            pointJa: '手順や話の「1番目」を示す。あとに then / next / finally が続く',
          },
          right: {
            label: 'at first(最初は〜だった)',
            items: [
              { en: 'At first, the job seemed boring, but now I love it.', ja: '最初その仕事は退屈に思えましたが、今では大好きです。', highlight: 'At first,' },
            ],
            pointJa: '「最初は〜だったが、あとで変わった」という変化を予告する。but や later とセットになることが多い',
          },
          note: '手順の説明に at first を使うのは日本人学習者に多い誤りです。「1番目のステップ」は first で表します。',
        },
        {
          type: 'explanation',
          title: 'in short と in other words は似て非なるもの',
          body:
            'どちらも「つまり」と訳されがちですが、働きが違います。\n\n- **in short**: 長い内容を**短く要約**する。情報を圧縮するのが目的\n- **in other words**: 直前の内容を**別の言葉で言い直す**。長さは変わらなくてよく、分かりやすくするのが目的\n\n- The report is 90 pages of data and charts. **In short**, sales are falling.(90ページ → 一言に圧縮)\n- He is not in a position to say yes. **In other words**, the decision is not his to make.(同じ内容を別の角度から言い直す)\n\n迷ったら「まとめているのか、言い直しているのか」を考えると選べます。',
        },
      ],
      quiz: [
        {
          id: 'u28-l3-q1',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___, I would like to introduce our new team members.',
          sentenceJa: 'まず初めに、新しいチームメンバーを紹介したいと思います。',
          choices: ['First of all', 'In short', 'In other words', 'At first'],
          correctIndex: 0,
          explanation: '話の出発点を示す場面なので、順序の最初を表す first of all が合います。',
          choiceNotes: [null, 'in short は要約の標識です。話を始める場面には合いません。', 'in other words は言い換えの標識で、直前に言い直す内容が必要です。', 'at first は「最初は〜だった(が後で変わった)」という変化を表し、話の順序には使えません。'],
          audioEn: 'First of all, I would like to introduce our new team members.',
        },
        {
          id: 'u28-l3-q2',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The test results were inconclusive. ___, we cannot say for sure that the new drug works.',
          sentenceJa: '試験結果は決定的ではありませんでした。つまり、新薬が効くとは断言できないということです。',
          choices: ['In other words', 'For example', 'On the other hand', 'First of all'],
          correctIndex: 0,
          explanation: '後半は前の文と同じ内容を分かりやすく言い直しているので、言い換えの in other words が合います。',
          choiceNotes: [null, 'for example は例を挙げる標識です。後半は前の文の例ではなく言い換えです。', 'on the other hand は対比の標識ですが、前後の文は対立していません。', 'first of all は順序の最初を示す標識で、言い換えの働きはありません。'],
          audioEn: 'The test results were inconclusive. In other words, we cannot say for sure that the new drug works.',
        },
        {
          id: 'u28-l3-q3',
          prompt: '次の文から読み取れることを選んでください。',
          sentence: 'At first, living alone felt scary.',
          choices: [
            '一人暮らしの怖さは今も変わっていない。',
            '最初は怖かったが、あとで気持ちが変わったことを示唆している。',
            '一人暮らしの手順の最初のステップを説明している。',
            '直前の長い話を短く要約している。',
          ],
          correctIndex: 1,
          explanation: 'at first は「最初は〜だった(が、あとで変わった)」という変化を予告する表現です。このあとには but now や later などの展開が自然に続きます。',
          choiceNotes: ['at first はむしろ「あとで変わった」ことを示唆する表現です。', null, '手順の1番目を示すのは first や first of all です。', '要約を導くのは in short や to sum up です。'],
          audioEn: 'At first, living alone felt scary.',
        },
        {
          id: 'u28-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'First of all, check that the cable is connected properly.',
            'At first, I will explain the budget. Then we will discuss the schedule.',
            'The hotel was cheap, clean, and quiet. In short, it was perfect.',
            'The meeting starts at nine. In other words, you should leave home by eight.',
          ],
          correctIndex: 1,
          explanation: '手順や話の順序の「1番目」を示すのは first や first of all です。at first は「最初は〜だった(が後で変わった)」という変化を表すので、この場面には合いません。',
          choiceNotes: ['正しい文です。手順の最初を first of all が示しています。', null, '正しい文です。3つの特徴を in short で一言にまとめています。', '正しい文です。前の文の意味を in other words で言い換えています。'],
          audioEn: 'First of all, I will explain the budget. Then we will discuss the schedule.',
        },
        {
          id: 'u28-l3-q5',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___ , the report was too long, too vague, and delivered three weeks late.',
          sentenceJa: '要するに、その報告書は長すぎ、曖昧で、しかも3週間遅れて提出されました。',
          choices: [
            'In short',
            'First of all',
            'At first',
            'In addition',
          ],
          correctIndex: 0,
          explanation: '複数の欠点を1文にまとめて締めくくっているので、要約を導く in short が適切です。',
          choiceNotes: [null, 'first of all は最初の項目を示す語で、まとめには使いません。', 'at first は「最初は〜だった」と後の変化を含意します。', 'in addition は情報の追加です。'],
          audioEn: 'In short, the report was too long, too vague, and delivered three weeks late.',
        },
        {
          id: 'u28-l3-q6',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___ the course looked impossible, but after two months I began to enjoy it.',
          sentenceJa: '最初その講座は無理そうに見えましたが、2か月後には楽しめるようになりました。',
          choices: [
            'First of all',
            'At first',
            'Firstly',
            'In the first place',
          ],
          correctIndex: 1,
          explanation: 'at first は「最初は〜だった、しかし後で変わった」という変化を前提にした表現です。but 以下と対になっています。',
          choiceNotes: ['first of all は手順や項目の1番目を示す語です。', null, 'firstly も項目の列挙に使う語です。', 'in the first place は理由を並べるときや「そもそも」の意味で使います。'],
          audioEn: 'At first the course looked impossible, but after two months I began to enjoy it.',
        },
        {
          id: 'u28-l3-q7',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The contract renews automatically. ___ , you must cancel before the end of March.',
          sentenceJa: 'その契約は自動更新されます。つまり、3月末までに解約しなければなりません。',
          choices: [
            'On the other hand',
            'In other words',
            'For example',
            'Nevertheless',
          ],
          correctIndex: 1,
          explanation: '前の文の内容をかみ砕いて言い換えているので、in other words が適切です。',
          choiceNotes: ['on the other hand は対比を示します。', null, 'for example は例を挙げる表現です。', 'nevertheless は逆接です。'],
          audioEn: 'The contract renews automatically. In other words, you must cancel before the end of March.',
        },
        {
          id: 'u28-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'To sum up, the new timetable is faster but slightly more expensive for commuters.',
            'First of all, I would like to thank the volunteers who prepared this venue.',
            'Finally, please make sure that all the windows are closed before you leave.',
            'At first of all, we should decide who is going to chair the meeting.',
          ],
          correctIndex: 3,
          explanation: 'at first of all という形はありません。1番目の項目を示すなら first of all です。',
          choiceNotes: ['正しい文です。to sum up で要約しています。', '正しい文です。first of all で最初の項目を示しています。', '正しい文です。finally で最後の項目を示しています。', null],
          audioEn: 'First of all, we should decide who is going to chair the meeting.',
        },
        {
          id: 'u28-l3-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: At first, the job seemed boring.   B: First, the job seemed boring.',
          choices: [
            'Aは「最初は〜だったが後に変わった」、Bは項目や手順の1番目を示す。',
            'Aは項目の1番目、Bは「最初は〜だった」を表す。',
            'どちらも手順の1番目を示す。',
            'Bは文法的に誤りである。',
          ],
          correctIndex: 0,
          explanation: 'at first は後の変化を前提にした時間表現、first は列挙の順序を示す語です。',
          choiceNotes: [null, '役割が逆です。', 'A は変化を前提にした表現です。', 'B は正しい文です。'],
          audioEn: 'At first, the job seemed boring. First, the job seemed boring.',
        },
        {
          id: 'u28-l3-q10',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___ , the committee recommends postponing the launch until the safety tests are complete.',
          sentenceJa: 'まとめると、委員会は安全試験が完了するまで発売を延期することを勧めています。',
          choices: [
            'For instance',
            'To sum up',
            'On the contrary',
            'By the way',
          ],
          correctIndex: 1,
          explanation: '議論全体をまとめて結論を述べているので、to sum up が適切です。',
          choiceNotes: ['for instance は例示です。', null, 'on the contrary は前の内容を否定して反対を述べる表現です。', 'by the way は話題を変える表現です。'],
          audioEn: 'To sum up, the committee recommends postponing the launch until the safety tests are complete.',
        },
      ],
      summary: [
        '順序は first of all → then / next → finally。話の設計図を先に見せると聞き手が迷わない。',
        'first(of all)は順序の1番目、at first は「最初は〜だった(が後で変わった)」。手順に at first は使わない。',
        'in short / to sum up は要約(圧縮)、in other words は言い換え(別の言葉で明確化)。',
        'これらの標識は文の頭に置き、コンマで区切るのが基本の形。',
      ],
    },
  ],
}
