import type { GrammarUnit } from '../../types'

// U29 名詞節 — B2

export const u29: GrammarUnit = {
  id: 'u29',
  level: 'B2',
  title: '名詞節',
  lessons: [
    {
      id: 'u29-l1',
      unitId: 'u29',
      level: 'B2',
      title: 'that節の使い方',
      objective: 'that節を「〜ということ」という名詞のかたまりとして使い、that を省略できる場面とできない場面を判断できるようになります。',
      minutes: 10,
      prereqs: ['u19-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '文をまるごと名詞に変える that',
          body:
            'that + 主語 + 動詞 のかたまりは、**文をまるごと1つの名詞に変える**働きをします。\n\n「計画がうまくいく」→ that the plan will work(計画がうまくいく**ということ**)。\n\nこうして名詞になった文は、ふつうの名詞と同じ場所——動詞の目的語、形容詞のあと、名詞のあと、文の主語——に置けます。B2レベルの読み書きでは、この「文の入れ子」を自在に扱えることが土台になります。',
        },
        {
          type: 'table',
          title: 'that節が置ける場所',
          headers: ['場所', 'よく使う形', '例'],
          rows: [
            ['動詞の目的語', 'think / know / believe / hope + that節', 'I think that the plan will work.'],
            ['形容詞のあと', 'be sure / afraid / glad / aware + that節', "I'm sure that she will come."],
            ['名詞のあと(同格)', 'the fact / the news / the idea + that節', 'the fact that he apologized'],
            ['文の主語', 'That + 文 + is ...', 'That he lied is obvious.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I believe that this approach will save us time and reduce the number of errors.', ja: 'このやり方は時間の節約になり、ミスの数も減らせると思います。', highlight: 'that this approach will save us time' },
            { en: "I'm afraid we missed the last train, so we will have to find a hotel tonight.", ja: '残念ですが終電を逃したようなので、今夜はホテルを探さなければなりません。', highlight: 'we missed the last train', note: '話し言葉では that はよく省略されます。' },
            { en: 'The news that the factory would close shocked the whole town.', ja: '工場が閉鎖されるという知らせは、町全体に衝撃を与えました。', highlight: 'that the factory would close', note: 'the news の中身を説明する同格の that節です。' },
            { en: 'That nobody in the audience complained about the delay genuinely surprised me.', ja: '観客の誰一人として遅れに文句を言わなかったことが、私には本当に驚きでした。', highlight: 'That nobody in the audience complained' },
            { en: 'We should accept the fact that plans change once the real work begins.', ja: '実際の作業が始まれば計画は変わるものだという事実を、受け入れるべきです。', highlight: 'the fact that plans change' },
          ],
        },
        {
          type: 'explanation',
          title: 'that はいつ省略できる?',
          body:
            'think / know / say など**よく使う動詞のあと**では、話し言葉で that をよく省略します。\n\n- I think (that) you are right.\n- She said (that) she would be late.\n\n一方、**省略しない**のが基本の場面もあります。\n\n- 文の主語になる that節: That he lied is obvious.\n- 名詞のあとの同格: the fact that ...\n- フォーマルな書き言葉や、どこからが that節か分かりにくい長い文',
        },
        {
          type: 'contrast',
          title: '同格の that と関係代名詞の that',
          left: {
            label: '同格の that(中身の説明)',
            items: [
              { en: 'the fact that he lied', ja: '彼が嘘をついたという事実', highlight: 'that he lied' },
              { en: 'the idea that money buys happiness', ja: 'お金で幸せが買えるという考え', highlight: 'that money buys happiness' },
            ],
            pointJa: 'that の後ろは完全な文。「名詞 = that節の中身」の関係',
          },
          right: {
            label: '関係代名詞の that(絞り込み)',
            items: [
              { en: 'the fact that he tried to hide', ja: '彼が隠そうとした事実', highlight: 'that he tried to hide' },
              { en: 'the idea that she proposed', ja: '彼女が提案したアイデア', highlight: 'that she proposed' },
            ],
            pointJa: 'that の後ろは欠けのある文(hide や proposed の目的語がない)',
          },
          note: '後ろの文が完全なら同格(〜という)、どこかが欠けていれば関係代名詞(〜する)です。',
        },
      ],
      quiz: [
        {
          id: 'u29-l1-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The fact ___ he apologized in person changed how everyone felt.',
          sentenceJa: '彼が直接謝ったという事実が、みんなの気持ちを変えました。',
          choices: ['that', 'which', 'what', 'whether'],
          correctIndex: 0,
          explanation: '空所のあとは he apologized in person という完全な文なので、the fact の中身を説明する同格の that を使います。',
          choiceNotes: [null, '関係代名詞 which の後ろは、名詞が1つ欠けた文でなければなりません。ここでは完全な文が続いています。', 'what は先行詞を含む語なので、the fact のような名詞のあとには置けません。', '「謝ったかどうか」では文の意味が通りません。'],
          audioEn: 'The fact that he apologized in person changed how everyone felt.',
        },
        {
          id: 'u29-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼女が試験に受かったことは、みんなを驚かせた」と言いたいとき。',
          choices: [
            'She passed the exam surprised everyone.',
            'That she passed the exam surprised everyone.',
            'She passed the exam that surprised everyone.',
            'That she passed the exam it surprised everyone.',
          ],
          correctIndex: 1,
          explanation: '文を主語にするには that でまとめて名詞のかたまりにします。That she passed the exam が主語、surprised が動詞です。',
          choiceNotes: ['2つの文が接続なしでぶつかっていて、主語がどれか分かりません。', null, 'これでは「みんなを驚かせた試験に受かった」という別の意味になります。', 'that節がすでに主語なので、it は余分です。'],
          audioEn: 'That she passed the exam surprised everyone.',
        },
        {
          id: 'u29-l1-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I think that this restaurant is overpriced.',
            'I know you are busy, so I will keep this short.',
            "I'm sure of that he will accept the offer.",
            'That he changed his mind is not surprising.',
          ],
          correctIndex: 2,
          explanation: "前置詞(of)の直後に that節は置けません。I'm sure that ... と of を取るか、I'm sure of the fact that ... のように名詞を挟みます。",
          choiceNotes: ['動詞 think のあとの that節。正しい文です。', 'know のあとの that は省略できます。正しい文です。', null, '主語の that節はフォーマルですが正しい形です。'],
          audioEn: "I'm sure that he will accept the offer.",
        },
        {
          id: 'u29-l1-q4',
          prompt: 'that を省略できない文を選んでください。',
          choices: [
            'I think (that) the movie starts at seven.',
            'He told me (that) he was moving to Nagoya.',
            'The news (that) the factory would close shocked the town.',
            "I'm glad (that) you could make it.",
          ],
          correctIndex: 2,
          explanation: '名詞(the news)の中身を説明する同格の that は省略しません。省略すると the news と the factory の関係が読み取れなくなります。',
          choiceNotes: ['think のあとの that は会話では頻繁に省略されます。', 'told me のあとの that も省略できます。', null, '形容詞 glad のあとの that も話し言葉では省略できます。'],
          audioEn: 'The news that the factory would close shocked the town.',
        },
        {
          id: 'u29-l1-q5',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'We cannot ignore ___ the number of applicants has fallen for three years in a row.',
          sentenceJa: '応募者数が3年連続で減っているという事実を無視することはできません。',
          choices: [
            'the fact which',
            'the fact that',
            'the fact what',
            'that fact of',
          ],
          correctIndex: 1,
          explanation: 'the fact の中身を説明する同格の that節です。that のあとには欠けのない完全な文が続きます。',
          choiceNotes: ['which は関係代名詞で、後ろに主語か目的語の欠けた文が必要です。', null, 'what は先行詞を含む関係詞なので the fact のあとには置けません。', '語順が崩れており、文として成り立ちません。'],
          audioEn: 'We cannot ignore the fact that the number of applicants has fallen for three years in a row.',
        },
        {
          id: 'u29-l1-q6',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: the idea that money buys happiness   B: the idea that she proposed',
          choices: [
            'Aは the idea の中身を説明する同格節、Bは the idea を修飾する関係詞節である。',
            'Aは関係詞節、Bは同格節である。',
            'どちらも同格節である。',
            'Bは文法的に誤りである。',
          ],
          correctIndex: 0,
          explanation: 'that のあとが完全な文なら同格節、目的語などが欠けていれば関係詞節です。B は proposed の目的語が欠けています。',
          choiceNotes: [null, 'A のほうが同格節です。', 'B は proposed の目的語が欠けた関係詞節です。', 'B は正しい形です。'],
          audioEn: 'The idea that money buys happiness is not new. This is the idea that she proposed.',
        },
        {
          id: 'u29-l1-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ so many people volunteered on a rainy Sunday really encouraged the organizers.',
          sentenceJa: '雨の日曜日にこれほど多くの人が参加してくれたことは、主催者を大いに勇気づけました。',
          choices: [
            'That',
            'What',
            'Which',
            'It',
          ],
          correctIndex: 0,
          explanation: '文全体を主語にするときは That + 完全な文の形にします。that は「〜ということ」というまとまりを作ります。',
          choiceNotes: [null, 'what のあとには主語か目的語の欠けた文が必要です。', 'which を文頭の主語として使うことはできません。', 'It で始めるなら It really encouraged the organizers that ... の語順にします。'],
          audioEn: 'That so many people volunteered on a rainy Sunday really encouraged the organizers.',
        },
        {
          id: 'u29-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I am convinced that this is the best solution available to us right now.',
            'The rumour that the branch would close turned out to be completely false.',
            'She admitted she had forgotten to send the invitation to two of the guests.',
            'The problem that the machine needs repair is which nobody wants to discuss.',
          ],
          correctIndex: 3,
          explanation: 'which は先行詞を含めない関係代名詞なので、is のあとの補語として単独では使えません。正しくは the one that nobody wants to discuss です。',
          choiceNotes: ['正しい文です。be convinced that + 節の形です。', '正しい文です。the rumour の中身を同格の that節が説明しています。', '正しい文です。目的語の that が省略されています。', null],
          audioEn: 'The problem that the machine needs repair is the one that nobody wants to discuss.',
        },
        {
          id: 'u29-l1-q9',
          prompt: 'that を省略できない文を選んでください。',
          choices: [
            'I think that we should postpone the meeting until next week.',
            'She said that the report would be ready by Thursday afternoon.',
            'That the results were leaked to the press angered the whole committee.',
            'He knows that the office closes early on the last Friday of the month.',
          ],
          correctIndex: 2,
          explanation: '文の主語として使う that節の that は省略できません。動詞の目的語になる that節では省略できます。',
          choiceNotes: ['think のあとの that は省略できます。', 'said のあとの that は省略できます。', null, 'knows のあとの that は省略できます。'],
          audioEn: 'That the results were leaked to the press angered the whole committee.',
        },
        {
          id: 'u29-l1-q10',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'There is a real possibility ___ the ferry service will be suspended during the typhoon.',
          sentenceJa: '台風の間、フェリーの運航が停止される可能性が本当にあります。',
          choices: [
            'what',
            'that',
            'which',
            'of that',
          ],
          correctIndex: 1,
          explanation: 'possibility の中身を説明する同格の that節です。後ろには完全な文が続きます。',
          choiceNotes: ['what は先行詞を含む関係詞なので、名詞のあとには置けません。', null, 'which を使うなら後ろの文に欠けが必要です。', 'of that という形はここでは使いません。'],
          audioEn: 'There is a real possibility that the ferry service will be suspended during the typhoon.',
        },
      ],
      summary: [
        'that節は文を「〜ということ」という名詞のかたまりに変える。',
        '動詞の目的語・形容詞のあと・名詞のあと(同格)・文の主語の位置で使える。',
        '話し言葉では動詞のあとの that を省略できるが、主語の that節や同格の that は省略しない。',
        '同格の that の後ろは完全な文、関係代名詞の that の後ろは欠けのある文。',
      ],
    },
    {
      id: 'u29-l2',
      unitId: 'u29',
      level: 'B2',
      title: 'wh節・whether節',
      objective: '「何を言ったか」「〜かどうか」という内容を文の中に入れ、正しい語順と whether / if の使い分けができるようになります。',
      minutes: 10,
      prereqs: ['u29-l1', 'u19-l4'],
      blocks: [
        {
          type: 'explanation',
          title: '疑問の内容を文の中に入れる',
          body:
            '「彼女がどこに住んでいるか」のような疑問の内容を、文の一部として入れられます。その中は**ふつうの文の語順**にします。\n\n- Where does she live? → I have no idea **where she lives**.\n\ndoes を使った疑問文から戻すときは、動詞に三単現の -s を戻します。\n\nただし、疑問詞自身が主語なら、そのあとに別の主語を足しません。**Who called? → I wonder who called.** では who が「誰が」という主語です。「疑問詞 + 主語 + 動詞」と機械的に並べず、**誰が主語なのか**を確かめましょう。',
        },
        {
          type: 'structure',
          title: 'wh節の語順',
          parts: [
            { label: '主節', text: 'I wonder' },
            { label: 'wh語', text: 'why' },
            { label: '主語', text: 'the flight' },
            { label: '動詞', text: 'was delayed' },
          ],
          caption: '疑問文 Why was the flight delayed? を文の中に入れると、the flight was のように「主語 + 動詞」の順に戻ります。',
        },
        {
          type: 'explanation',
          title: 'whether / if 「〜かどうか」',
          body:
            'yes / no で答える疑問文を別の文の中に入れるときは **whether** か **if** を使います。\n\n- Is the store open? → I wonder **whether the store is open**.\n\n動詞の目的語の位置ではどちらも使えますが、それ以外の場所(主語・前置詞のあと・to不定詞の前)では whether だけが使えます。また、直後に or not を続けられるのも whether だけです。',
        },
        {
          type: 'contrast',
          title: 'whether しか使えない場所・if も使える場所',
          left: {
            label: 'whether のみ',
            items: [
              { en: 'Whether we expand overseas is still under discussion.', ja: '海外展開するかどうかは、まだ議論中です。', highlight: 'Whether', note: '文の主語の位置。' },
              { en: 'Success depends on whether customers trust the brand.', ja: '成功は、顧客がそのブランドを信頼するかどうかにかかっています。', highlight: 'whether', note: '前置詞 on のあと。' },
              { en: "We can't decide whether to rent or buy.", ja: '借りるか買うかを決められません。', highlight: 'whether to rent', note: 'to不定詞の前。' },
            ],
            pointJa: '主語・前置詞のあと・to不定詞の前は whether だけ',
          },
          right: {
            label: 'if も使える',
            items: [
              { en: "I don't know if the store is open today.", ja: '今日その店が開いているかどうか分かりません。', highlight: 'if' },
              { en: 'She asked if I needed a ride.', ja: '彼女は、車で送ろうかと尋ねてくれました。', highlight: 'if' },
            ],
            pointJa: 'know / ask / wonder などの目的語の位置では if も whether も使える',
          },
          note: 'or not を直後に置けるのは whether だけです(I asked whether or not it was true.)。if or not とは言えません。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'What she said at the budget meeting completely changed my mind about the proposal.', ja: '予算会議で彼女が言ったことが、その提案についての私の考えをすっかり変えました。', highlight: 'What she said at the budget meeting', note: 'what節は「〜したこと・もの」を表し、主語にもなれます。' },
            { en: 'I have no idea where he parked the car in this enormous underground garage.', ja: 'この巨大な地下駐車場のどこに彼が車を停めたのか、まったく分かりません。', highlight: 'where he parked the car' },
            { en: 'How the fire started in a building with no gas supply is still unknown.', ja: 'ガスの供給がない建物でどのように火事が始まったのかは、まだ分かっていません。', highlight: 'How the fire started' },
            { en: 'The report explains in detail why sales dropped so sharply in March.', ja: 'その報告書は、3月に売上がこれほど急落した理由を詳しく説明しています。', highlight: 'why sales dropped so sharply in March' },
            { en: 'Let me know whether the revised schedule works for you and your colleagues.', ja: '修正した日程であなたと同僚の都合がつくかどうか教えてください。', highlight: 'whether the revised schedule works' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u29-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Could you tell me ___?',
          sentenceJa: 'いちばん近い薬局がどこにあるか教えていただけますか。',
          choices: ['where is the nearest pharmacy', 'where the nearest pharmacy is', 'where does the nearest pharmacy is', 'is where the nearest pharmacy'],
          correctIndex: 1,
          explanation: '文の中に入れた疑問は「主語 + 動詞」の順に戻ります。where + 主語(the nearest pharmacy)+ 動詞(is)の順です。',
          choiceNotes: ['疑問文の語順のままです。別の文の中に入れると「主語 + 動詞」の順に戻ります。', null, 'be動詞の文に does は使えず、語順も誤りです。', 'wh語が名詞節の先頭に来る必要があります。'],
          audioEn: 'Could you tell me where the nearest pharmacy is?',
        },
        {
          id: 'u29-l2-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ we move forward with the project depends on the test results.',
          sentenceJa: 'プロジェクトを進めるかどうかは、テストの結果しだいです。',
          choices: ['If', 'Whether', 'That', 'What'],
          correctIndex: 1,
          explanation: '「〜かどうか」という名詞節が文の主語になっています。主語の位置で使えるのは whether だけです。',
          choiceNotes: ['if の名詞節は動詞の目的語の位置でしか使えません。主語にはなれません。', null, 'that節は「〜ということ」。まだ決まっていない「〜かどうか」の意味は表せません。', 'move forward は目的語を取らないので、what の入る欠けがありません。'],
          audioEn: 'Whether we move forward with the project depends on the test results.',
        },
        {
          id: 'u29-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼が何と言ったかは重要ではありません」と言いたいとき。',
          choices: [
            "What did he say doesn't matter.",
            "What he said doesn't matter.",
            "That he said doesn't matter.",
            "He said what doesn't matter.",
          ],
          correctIndex: 1,
          explanation: 'what節は「what + 主語 + 動詞」の順で作ります。What he said(彼が言ったこと)が主語です。',
          choiceNotes: ['did he say は疑問文の語順です。名詞節では he said に戻します。', null, 'that節は完全な文を導きますが、said の目的語が欠けているので what が必要です。', 'これでは「彼は重要でないことを言った」という別の文になります。'],
          audioEn: "What he said doesn't matter.",
        },
        {
          id: 'u29-l2-q4',
          prompt: '空所に入る語を選んでください。',
          sentence: "We haven't decided ___ or not to renew the contract.",
          sentenceJa: '契約を更新するかどうか、まだ決めていません。',
          choices: ['if', 'whether', 'that', 'what'],
          correctIndex: 1,
          explanation: '直後に or not を続けられるのは whether だけです。さらに、このあとの to不定詞(to renew)の前でも whether しか使えません。',
          choiceNotes: ['if or not という並びは使えません。また if は to不定詞の前にも置けません。', null, 'that は「〜かどうか」の意味を表せません。', '「何を」という欠けがないので what は使えません。'],
          audioEn: "We haven't decided whether or not to renew the contract.",
        },
        {
          id: 'u29-l2-q5',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The board has not yet decided ___ to build the new plant in Vietnam or in Thailand.',
          sentenceJa: '取締役会は、新工場をベトナムに建てるかタイに建てるかをまだ決めていません。',
          choices: [
            'if',
            'that',
            'whether',
            'what',
          ],
          correctIndex: 2,
          explanation: 'to不定詞の前に置けるのは whether だけで、if は使えません。また or と組み合わせるときも whether が自然です。',
          choiceNotes: ['if は to不定詞の前には置けません。', 'that では選択の意味を表せません。', null, 'what のあとには主語か目的語の欠けた文が必要です。'],
          audioEn: 'The board has not yet decided whether to build the new plant in Vietnam or in Thailand.',
        },
        {
          id: 'u29-l2-q6',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Everything now depends on ___ the supplier can deliver the parts before the deadline.',
          sentenceJa: 'すべては、仕入れ先が期限前に部品を納入できるかどうかにかかっています。',
          choices: [
            'if',
            'whether',
            'that',
            'what',
          ],
          correctIndex: 1,
          explanation: '前置詞のあとに置けるのは whether で、if は使えません。',
          choiceNotes: ['前置詞 on のあとに if は置けません。', null, 'that では「〜かどうか」という選択の意味になりません。', 'what のあとには欠けのある文が必要です。'],
          audioEn: 'Everything now depends on whether the supplier can deliver the parts before the deadline.',
        },
        {
          id: 'u29-l2-q7',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ the earlier version of the software actually caused the crash is still unclear.',
          sentenceJa: '旧バージョンのソフトが実際にクラッシュを引き起こしたのかどうかは、まだはっきりしません。',
          choices: [
            'If',
            'Whether',
            'What',
            'That',
          ],
          correctIndex: 1,
          explanation: '文の主語になる位置では if は使えず、whether を使います。',
          choiceNotes: ['主語の位置に if節は置けません。', null, 'what のあとには主語か目的語の欠けた文が必要です。', 'that では「〜かどうか」という選択の意味になりません。'],
          audioEn: 'Whether the earlier version of the software actually caused the crash is still unclear.',
        },
        {
          id: 'u29-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I have no idea where she keeps the spare keys to the storage room.',
            'Nobody could explain why the alarm went off in the middle of the night.',
            'The question of whether the treatment is safe has not been settled.',
            'Please tell me that time the last bus leaves from this stop.',
          ],
          correctIndex: 3,
          explanation: '時刻を尋ねる名詞節は what time で始めます。that time では節になりません。',
          choiceNotes: ['正しい文です。where節が目的語になっています。', '正しい文です。why節が目的語になっています。', '正しい文です。前置詞 of のあとに whether節が続いています。', null],
          audioEn: 'Please tell me what time the last bus leaves from this stop.',
        },
        {
          id: 'u29-l2-q9',
          prompt: '空所に入る語順を選んでください。',
          sentence: 'Could you tell me ___ from this platform?',
          sentenceJa: 'この番線からどの電車が空港へ行くのか教えていただけますか。',
          choices: [
            'which train does go to the airport',
            'which train goes to the airport',
            'does which train go to the airport',
            'which train go to the airport',
          ],
          correctIndex: 1,
          explanation: '文の中に入った疑問は、疑問文の語順ではなく主語 + 動詞の平叙文の語順にします。',
          choiceNotes: ['名詞節の中で do を使った疑問文の語順にはしません。', null, '名詞節の中で疑問文の語順にはしません。', '三人称単数の主語なので goes にします。'],
          audioEn: 'Could you tell me which train goes to the airport from this platform?',
        },
        {
          id: 'u29-l2-q10',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'What worries the residents most is whether the new road will increase noise at night.',
          choices: [
            '住民が最も心配しているのは、新しい道路が夜間の騒音を増やすかどうかだ。',
            '住民は新しい道路が夜間の騒音を増やすと確信している。',
            '住民は夜間の騒音についてまったく心配していない。',
            '新しい道路は夜間の騒音を必ず増やす。',
          ],
          correctIndex: 0,
          explanation: 'What worries the residents most が主語、whether節が補語です。whether は「〜かどうか」という未確定の内容を表します。',
          choiceNotes: [null, 'whether は確信ではなく未確定であることを示します。', '最も心配していることとして述べられています。', '増えるかどうかはまだ分かりません。'],
          audioEn: 'What worries the residents most is whether the new road will increase noise at night.',
        },
      ],
      summary: [
        '疑問文を名詞節にすると、「wh語 + 主語 + 動詞」の順に戻る。',
        'what節は「〜したこと・もの」を表し、文の主語にもなれる。',
        'yes / no で答える疑問文を別の文の中に入れるときは whether / if。主語・前置詞のあと・to不定詞の前は whether のみ。',
        'or not を直後に続けられるのは whether だけ。',
      ],
    },
    {
      id: 'u29-l3',
      unitId: 'u29',
      level: 'B2',
      title: 'It構文',
      objective: '仮主語の it を使って It is important that ... / It seems that ... のような文を作り、seem を使った書き換えもできるようになります。',
      minutes: 10,
      prereqs: ['u29-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '頭でっかちを避ける仮主語 it',
          body:
            'That he passed the exam is surprising. は文法的には正しいものの、主語が長くて頭でっかちです。英語はこれを嫌い、**とりあえず it を置いて、本当の主語(that節)を後ろに回します**。\n\n- **It** is surprising **that he passed the exam**.\n\nこの it は「それ」とは訳しません。主語の置き場所を確保するためだけの**仮主語**です。',
        },
        {
          type: 'structure',
          title: '長い主語を後ろへ回す',
          parts: [
            { label: '仮主語', text: 'It' },
            { label: '判断・評価', text: 'is surprising' },
            { label: '本当の主語(that節)', text: 'that he passed the exam' },
          ],
          caption: 'That he passed the exam is surprising. の長い主語を後ろへ回した形です。会話でも書き言葉でも、こちらが圧倒的に自然です。',
        },
        {
          type: 'table',
          title: 'It + that節の定番パターン',
          headers: ['パターン', 'よく使う語', '例'],
          rows: [
            ['It is + 形容詞 + that', 'important / clear / likely / surprising', 'It is clear that he lied.'],
            ['It + 動詞 + that', 'seems / appears / turns out / happens', 'It turns out that we were wrong.'],
            ['It is + 過去分詞 + that', 'said / believed / reported / known', 'It is said that the water here is very clean.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'It is obvious from the notes in the margin that she worked hard on this.', ja: '余白の書き込みを見れば、彼女がこれに一生懸命取り組んだのは明らかです。', highlight: 'It is obvious' },
            { en: 'It seems that the schedule has changed again since the email was sent yesterday.', ja: '昨日メールが送られてから、また予定が変わったようです。', highlight: 'It seems that' },
            { en: 'It turned out that the rumor about the merger was completely false after all.', ja: '合併のうわさは結局まったくの誤りだと判明しました。', highlight: 'It turned out that' },
            { en: 'It is essential that every application be reviewed twice.', ja: 'すべての応募書類は2回チェックされることが不可欠です。', highlight: 'be reviewed', note: '「重要・必要」の that節では動詞が原形になります(下の解説参照)。' },
            { en: "It's a shame that you can't stay longer, because the festival starts tomorrow.", ja: '明日から祭りが始まるので、もっと長くいられないのは残念です。', highlight: "It's a shame that" },
          ],
        },
        {
          type: 'explanation',
          title: 'seem の書き換えと「重要・必要」の that節',
          body:
            'It seems that ... は、that節の主語を文の主語にして seem to ... と言い換えられます。\n\n- It seems that she is tired. = She seems **to be** tired.\n- It seems that she has forgotten. = She seems **to have forgotten**.(seem より前の時点のことは to have + 過去分詞)\n\nもう1つ、It is important / essential / necessary that ... のような「重要・必要」を表す文では、that節の動詞を**原形**にします(仮定法現在)。\n\n- It is essential that every visitor **wear** a badge.',
        },
      ],
      quiz: [
        {
          id: 'u29-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ that the tickets sold out in ten minutes.',
          sentenceJa: 'チケットは10分で売り切れたと判明しました。',
          choices: ['It turned out', 'That turned out', 'There turned out', 'It was turned out'],
          correctIndex: 0,
          explanation: 'that節を後ろに回す文の先頭には仮主語の it を置きます。It turned out that ... で「〜だと判明した」です。',
          choiceNotes: [null, 'that は仮主語として使えません。', 'there は「存在」を導く語で、that節の仮主語にはなれません。', 'turn out は自動詞なので受動態にできません。'],
          audioEn: 'It turned out that the tickets sold out in ten minutes.',
        },
        {
          id: 'u29-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It is essential that every visitor ___ a badge at all times.',
          sentenceJa: 'すべての来訪者が常に名札を着用することが不可欠です。',
          choices: ['wear', 'wears', 'is wearing', 'to wear'],
          correctIndex: 0,
          explanation: 'essential / important / necessary などの後の that節では、動詞を原形にします(仮定法現在)。主語が単数でも -s は付けません。',
          choiceNotes: [null, 'イギリス英語では見られますが、アメリカ英語では原形が標準です。', '進行形にする理由がなく、この構文では原形を使います。', 'that節の中に to不定詞は置けません。'],
          audioEn: 'It is essential that every visitor wear a badge at all times.',
        },
        {
          id: 'u29-l3-q3',
          prompt: 'ほぼ同じ意味の文を選んでください。',
          sentence: 'It seems that Meg has forgotten our appointment.',
          sentenceJa: 'メグは約束を忘れてしまったようです。',
          choices: [
            'Meg seems to forget our appointment.',
            'Meg seems to have forgotten our appointment.',
            'Meg is seemed to forget our appointment.',
            'It seems Meg to have forgotten our appointment.',
          ],
          correctIndex: 1,
          explanation: 'that節の中が has forgotten(seem より前に起きたこと)なので、書き換えでは to have + 過去分詞を使います。',
          choiceNotes: ['to forget では「いつも忘れるようだ」という習慣の意味になり、元の文とずれます。', null, 'seem は受動態にできません。', 'seem は「It seems + 人 + to do」という形を取れません。'],
          audioEn: 'Meg seems to have forgotten our appointment.',
        },
        {
          id: 'u29-l3-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ no use arguing with him once he has made up his mind.',
          sentenceJa: '彼が一度決心したら、言い争ってもむだです。',
          choices: ["It's", "That's", "There's", 'What is'],
          correctIndex: 0,
          explanation: 'It is no use -ing で「〜してもむだだ」。この it は仮主語で、本当の主語は arguing 以下です。',
          choiceNotes: [null, 'that は仮主語になれません。', "There's no use は There's no point (in) -ing と混ざった不自然な形です。定番の形は It's no use -ing です。", '疑問文ではないので what is は使えません。'],
          audioEn: "It's no use arguing with him once he has made up his mind.",
        },
        {
          id: 'u29-l3-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It is essential that every visitor ___ a badge while inside the research building.',
          sentenceJa: '研究棟の中では、すべての来訪者がバッジを着用することが不可欠です。',
          choices: [
            'wears',
            'wear',
            'wore',
            'is wearing',
          ],
          correctIndex: 1,
          explanation: 'essential / important / necessary などのあとの that節では、主語が三人称単数でも動詞を原形にします。',
          choiceNotes: ['この構文では三単現の s を付けません。', null, '過去形は使いません。', '進行形はこの構文では使いません。'],
          audioEn: 'It is essential that every visitor wear a badge while inside the research building.',
        },
        {
          id: 'u29-l3-q6',
          prompt: '次の文を It で始める形に書き換えたものとして正しいものを選んでください。',
          sentence: 'That the museum closes on Mondays is not widely known.',
          choices: [
            'It is not widely known that the museum closes on Mondays.',
            'It is not widely known the museum closes on Mondays that.',
            'That it is not widely known the museum closes on Mondays.',
            'It that the museum closes on Mondays is not widely known.',
          ],
          correctIndex: 0,
          explanation: '長い that節を主語にすると頭でっかちになるので、It を仮の主語に立てて that節を後ろへ回します。',
          choiceNotes: [null, 'that の位置が違い、文として成り立ちません。', 'That で始めると主語が二重になります。', 'It と that節を並べる語順にはしません。'],
          audioEn: 'It is not widely known that the museum closes on Mondays.',
        },
        {
          id: 'u29-l3-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It ___ that the two companies had been negotiating in secret for over a year.',
          sentenceJa: 'その2社が1年以上も秘密裏に交渉していたことが判明しました。',
          choices: [
            'turned out',
            'was turned out',
            'turned',
            'has turned to',
          ],
          correctIndex: 0,
          explanation: 'It turns out that ... で「〜だと判明する」を表します。受動態にはしません。',
          choiceNotes: [null, 'turn out は受動態にしません。', 'turn だけでは「判明する」の意味になりません。', 'turn to では別の意味になります。'],
          audioEn: 'It turned out that the two companies had been negotiating in secret for over a year.',
        },
        {
          id: 'u29-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'It seems that the delivery has been delayed by the heavy snow again.',
            'It is important that the report be submitted before the committee meets.',
            'It is a shame that you cannot join us for the closing dinner tonight.',
            'It appears the machine to have been running without oil for weeks.',
          ],
          correctIndex: 3,
          explanation: 'It appears のあとは that節にします。to不定詞を使うなら The machine appears to have been running ... の形です。',
          choiceNotes: ['正しい文です。It seems that + 節の形です。', '正しい文です。important のあとの that節では動詞が原形になります。', '正しい文です。It is a shame that + 節の形です。', null],
          audioEn: 'It appears that the machine has been running without oil for weeks.',
        },
        {
          id: 'u29-l3-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: It seems that she has changed her mind.   B: She seems to have changed her mind.',
          choices: [
            '意味はほぼ同じで、Bは主語を前に出した形である。',
            'Aは推測、Bは事実の断定である。',
            'Bは文法的に誤りである。',
            'Aは過去、Bは現在のことを表す。',
          ],
          correctIndex: 0,
          explanation: 'It seems that A does は A seems to do に書き換えられます。内容が seem より前のことなら to have + 過去分詞にします。',
          choiceNotes: [null, 'どちらも推測を表します。', 'B は正しい形です。', 'どちらも心変わりが現在より前に起きたことを示しています。'],
          audioEn: 'It seems that she has changed her mind. She seems to have changed her mind.',
        },
        {
          id: 'u29-l3-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The committee recommended that the deadline ___ by two weeks to allow more testing.',
          sentenceJa: '委員会は、より多くの試験を行えるよう期限を2週間延ばすことを勧告しました。',
          choices: [
            'is extended',
            'be extended',
            'extends',
            'will be extended',
          ],
          correctIndex: 1,
          explanation: 'recommend / suggest / insist / demand のあとの that節でも動詞は原形にします。受動なら be + 過去分詞です。',
          choiceNotes: ['この構文では is ではなく原形の be を使います。', null, '期限は延ばされる側なので受動にします。', 'この構文では will を使いません。'],
          audioEn: 'The committee recommended that the deadline be extended by two weeks to allow more testing.',
        },
      ],
      summary: [
        'It is ... that 〜 の it は仮主語。長い主語(that節)を後ろに回した形。',
        'It seems / It turns out / It is said that など、that節を導く定番パターンをまとめて覚える。',
        'It seems that S V は S seems to do に書き換えられる。前の時点のことは to have + 過去分詞。',
        'important / essential / necessary などの後の that節では動詞は原形(仮定法現在)。',
      ],
    },
  ],
}
