import type { GrammarUnit } from '../../types'

// U30 強調・倒置・省略

export const u30: GrammarUnit = {
  id: 'u30',
  level: 'B2',
  title: '強調・倒置・省略',
  lessons: [
    {
      id: 'u30-l1',
      unitId: 'u30',
      level: 'B2',
      title: '強調構文(cleft)',
      objective: 'It is ... that の強調構文と What ... is の文を使って、文の中で一番伝えたい部分にスポットライトを当てられるようになります。',
      minutes: 12,
      prereqs: ['u29-l3'],
      blocks: [
        {
          type: 'explanation',
          title: 'スポットライトを当てる It is ... that',
          body:
            '言いたいことの中で**一番伝えたい部分にスポットライトを当てる**のが強調構文です。\n\n普通の文 Kenta broke the copy machine. は事実を伝えるだけですが、「壊したのは(他の誰でもなく)ケンタだ」と言いたいときはこうします。\n\n- **It was Kenta that** broke the copy machine.\n\n作り方は「**It is / It was + 強調したい部分 + that + 残りの文**」。強調できるのは主語・目的語・時間・場所などの表現で、時制は元の文に合わせて is / was を選びます。人を強調するときは that の代わりに **who** も使えます。',
        },
        {
          type: 'structure',
          title: '通常語順',
          parts: [
            { label: '主語', text: 'Kenta' },
            { label: '動詞', text: 'broke' },
            { label: '目的語', text: 'the copy machine' },
          ],
          caption: 'まずは普通の文。このままでは「誰が」を特に強調できません。',
        },
        {
          type: 'structure',
          title: '変形後: It was ... that の強調構文',
          parts: [
            { label: 'It was', text: 'It was' },
            { label: '強調したい部分', text: 'Kenta' },
            { label: 'that', text: 'that' },
            { label: '残りの文', text: 'broke the copy machine' },
          ],
          caption: '強調したい部分を It was と that で挟み、残りの文をそのまま that の後ろに続けます。',
        },
        {
          type: 'explanation',
          title: 'What で始めるもう一つの強調',
          body:
            'もう一つの強調が **What ... is ~**(〜なのは…だ)です。\n\n- **What I need right now is** a cup of coffee.(今必要なのはコーヒーだ)\n\nWhat節(〜なのは)で聞き手の注意を引きつけておいて、be動詞のあとに一番伝えたい情報を出します。\n\n- What matters is your health.(大事なのは健康です)\n- What surprised me was the price.(驚いたのは値段でした)\n\nIt is ... that が文の一部を取り出して強調するのに対し、What ... is は「これから大事なことを言いますよ」と**前置きしてためを作る**強調です。会話でもビジネスでも非常によく使います。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'It was Kenta that broke the copy machine, though nobody wanted to say so.', ja: '誰も口に出したがりませんでしたが、コピー機を壊したのはケンタです。', highlight: 'It was Kenta that' },
            { en: 'It was last summer that we visited Okinawa for the first time as a family.', ja: '私たちが家族で初めて沖縄を訪れたのは去年の夏です。', highlight: 'last summer', note: '時間の表現も強調できます。' },
            { en: 'It was at a small cafe that I first heard this song.', ja: 'この曲を初めて聞いたのは小さなカフェでした。', highlight: 'at a small cafe' },
            { en: 'It was my grandmother who taught me this recipe when I was about ten years old.', ja: '私が10歳くらいのときにこのレシピを教えてくれたのは祖母です。', highlight: 'who', note: '人を強調するときは who も使えます。' },
            { en: 'What I need right now is a cup of strong coffee and half an hour of quiet.', ja: '今の私に必要なのは濃いコーヒー一杯と、30分の静けさです。', highlight: 'What I need right now is' },
            { en: 'What surprised me most was the view from the top of the old lighthouse.', ja: '一番驚いたのは、古い灯台の頂上からの眺めでした。', highlight: 'What surprised me most was' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u30-l1-q1',
          prompt: 'Naomi を強調した文として正しいものを選んでください。',
          sentenceJa: '「このケーキを作ったのはナオミです」と言いたいとき(元の文: Naomi made this cake.)。',
          choices: [
            'It was Naomi that made this cake.',
            'It was Naomi made this cake.',
            'It was that Naomi made this cake.',
            'Naomi was it that made this cake.',
          ],
          correctIndex: 0,
          explanation: '強調構文は It was + 強調したい部分 + that + 残りの文、という形です。Naomi を It was と that で挟みます。',
          choiceNotes: [null, '強調した部分のあとに that が必要です。', 'that の位置が違います。It was that ... では「〜ということだった」という別の文になってしまいます。', 'It を文頭に置くのが強調構文の形です。この語順では文が成り立ちません。'],
          audioEn: 'It was Naomi that made this cake.',
        },
        {
          id: 'u30-l1-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ I want for my birthday is a new bicycle.',
          sentenceJa: '誕生日に欲しいのは新しい自転車です。',
          choices: ['What', 'That', 'It', 'Which'],
          correctIndex: 0,
          explanation: '「〜なのは…だ」の強調は What節を主語にします。What I want for my birthday(私が誕生日に欲しいもの)+ is + 強調部分です。',
          choiceNotes: [null, 'That I want ... だと「私が欲しいということ」となり、意味が通りません。', 'It を使う強調構文は It is ... that の形です。It I want とは続けられません。', 'Which はこの位置で「〜なもの」を表せません。'],
          audioEn: 'What I want for my birthday is a new bicycle.',
        },
        {
          id: 'u30-l1-q3',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'It was the location that convinced us to buy the house, not the price.',
          choices: [
            '家の購入の決め手は立地であって、価格ではなかった。',
            '家の購入の決め手は価格であって、立地ではなかった。',
            '立地は良かったが、結局その家は買わなかった。',
            '立地も価格も購入の決め手にはならなかった。',
          ],
          correctIndex: 0,
          explanation: 'It was X that ... は X にスポットライトを当てる形です。強調されているのは the location で、not the price が「価格ではなく」と対比しています。',
          choiceNotes: [null, '強調されているのは It was の直後にある the location です。', 'convinced us to buy the house は「購入を決心させた」なので、実際に買う方向の話です。', 'the location は決め手として強調されています。'],
          audioEn: 'It was the location that convinced us to buy the house, not the price.',
        },
        {
          id: 'u30-l1-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'It was in Kyoto that they held the wedding.',
            'What we need now is more time.',
            'It was my coach who encouraged me to keep going.',
            'What made her famous it was this novel.',
          ],
          correctIndex: 3,
          explanation: 'What節がすでに主語なので、it は不要です。正しくは What made her famous was this novel. です。',
          choiceNotes: ['正しい強調構文です。場所の表現 in Kyoto を強調しています。', '正しい What ... is の強調です。', '正しい文です。人を強調するときは who も使えます。', null],
          audioEn: 'What made her famous was this novel.',
        },
        {
          id: 'u30-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ the quality of the service that keeps customers coming back, not the low prices.',
          sentenceJa: '客が繰り返し来るのはサービスの質のおかげであって、安さのせいではありません。',
          choices: [
            'That is',
            'It is',
            'What is',
            'There is',
          ],
          correctIndex: 1,
          explanation: 'It is + 強調したい部分 + that の形です。ここでは the quality of the service にスポットライトを当てています。',
          choiceNotes: ['That is では強調構文になりません。', null, 'What is で始めるなら What keeps customers coming back is ... の語順にします。', 'There is は存在を表す構文で、強調はできません。'],
          audioEn: 'It is the quality of the service that keeps customers coming back, not the low prices.',
        },
        {
          id: 'u30-l1-q6',
          prompt: '次の文を What で始める強調文に書き換えたものとして正しいものを選んでください。',
          sentence: 'This team needs a clear leader more than anything else.',
          choices: [
            'What this team needs most is a clear leader.',
            'What this team needs most it is a clear leader.',
            'That this team needs most is a clear leader.',
            'What does this team need most is a clear leader.',
          ],
          correctIndex: 0,
          explanation: 'What節を主語にして、be動詞のあとに一番伝えたい情報を置きます。What節がすでに主語なので it は不要です。',
          choiceNotes: [null, 'What節が主語なので、あとから it を重ねません。', 'That では「〜ということ」となり、強調になりません。', '名詞節の中では疑問文の語順にしません。'],
          audioEn: 'What this team needs most is a clear leader.',
        },
        {
          id: 'u30-l1-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It was not until she read the second letter ___ she understood what had really happened.',
          sentenceJa: '2通目の手紙を読んで初めて、彼女は実際に何が起きたのかを理解しました。',
          choices: [
            'when',
            'that',
            'which',
            'what',
          ],
          correctIndex: 1,
          explanation: 'It was not until ... that ... で「〜して初めて…した」を表します。強調構文の一種で、that を使います。',
          choiceNotes: ['この構文では when ではなく that を使います。', null, '強調構文の後半に which は使いません。', 'what は先行詞を含む関係詞で、この位置には合いません。'],
          audioEn: 'It was not until she read the second letter that she understood what had really happened.',
        },
        {
          id: 'u30-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'It was in 1964 that the first bullet train started running between Tokyo and Osaka.',
            'What impressed the judges most was the confidence of the youngest competitor.',
            'It is my younger brother who takes care of our parents every weekend.',
            'What we should do first it is to check whether everyone is safe.',
          ],
          correctIndex: 3,
          explanation: 'What節がすでに主語なので、そのあとに it is を重ねることはできません。正しくは What we should do first is to check ... です。',
          choiceNotes: ['正しい強調構文です。年号を強調しています。', '正しい What ... is の強調です。', '正しい強調構文です。人には who を使えます。', null],
          audioEn: 'What we should do first is to check whether everyone is safe.',
        },
        {
          id: 'u30-l1-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: It was Yuki who called the ambulance.   B: Yuki called the ambulance.',
          choices: [
            'Aは「呼んだのは他の誰でもなくユキだ」と焦点を当て、Bは事実を述べているだけである。',
            'Aは事実を述べ、Bが焦点を当てている。',
            'Aはユキが呼ばなかったことを表す。',
            '意味も焦点もまったく同じである。',
          ],
          correctIndex: 0,
          explanation: '強調構文は文の一部を取り出して「他ではなくこれだ」と焦点を当てます。普通の文は事実を伝えるだけです。',
          choiceNotes: [null, '焦点を当てているのは強調構文の A のほうです。', 'A もユキが呼んだことを述べています。', 'A には焦点を当てる働きがあります。'],
          audioEn: 'It was Yuki who called the ambulance. Yuki called the ambulance.',
        },
        {
          id: 'u30-l1-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: '___ worries me is not the cost of the project but the very tight schedule.',
          sentenceJa: '私が心配しているのは計画の費用ではなく、非常にきつい日程のほうです。',
          choices: [
            'That',
            'It',
            'Which',
            'What',
          ],
          correctIndex: 3,
          explanation: 'What節を主語にして「〜なのは…だ」を表します。What worries me = 私を心配させること、です。',
          choiceNotes: ['That worries me では「そのことが私を心配させる」という別の文になります。', 'It で始めるなら It is not the cost that worries me の形にします。', 'Which を文頭の主語として使うことはできません。', null],
          audioEn: 'What worries me is not the cost of the project but the very tight schedule.',
        },
      ],
      summary: [
        'It is / It was + 強調したい部分 + that + 残りの文。主語・目的語・時間・場所にスポットライトを当てられる。',
        '時制は元の文に合わせて is / was を選ぶ。人を強調するときは that の代わりに who も使える。',
        'What ... is ~ は「〜なのは…だ」。What節で前置きして、be動詞のあとに一番伝えたい情報を置く。',
        'What節が主語になるので、あとから it などの主語を重ねない。',
      ],
    },
    {
      id: 'u30-l2',
      unitId: 'u30',
      level: 'B2',
      title: '倒置の基本',
      objective: 'Never have I ... のような倒置文を正しい語順で作り、So do I / Neither do I で「私も」と自然に応じられるようになります。',
      minutes: 12,
      prereqs: ['u30-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '否定の言葉を文頭に出すと語順が変わる',
          body:
            'Never や Rarely のような**否定的な意味の語句を文頭に出す**と、「一度も〜ない」という気持ちを強く打ち出せます。ただし語順に代償があります。\n\n**文頭に否定語句 → 後ろは疑問文と同じ語順**(助動詞 + 主語)になります。これを**倒置**と呼びます。\n\n- I have never seen such a mess. → **Never have I seen** such a mess.\n\n倒置を起こす代表的な表現:\n\n- Never(一度も〜ない)\n- Rarely / Seldom(めったに〜ない)\n- Little(まったく〜ない。Little did I know ...)\n- Not only(〜だけでなく)\n- Under no circumstances(どんな状況でも〜ない)\n\n助動詞がない一般動詞の文では、疑問文と同じように **do / does / did を借ります**。',
        },
        {
          type: 'structure',
          title: '通常語順',
          parts: [
            { label: '主語', text: 'I' },
            { label: '助動詞', text: 'have' },
            { label: 'never', text: 'never' },
            { label: '動詞', text: 'seen' },
            { label: '目的語', text: 'such a mess' },
          ],
          caption: '普通の文では never は have と seen の間に置きます。',
        },
        {
          type: 'structure',
          title: '変形後: Never を文頭に出した倒置',
          parts: [
            { label: 'Never', text: 'Never' },
            { label: '助動詞', text: 'have' },
            { label: '主語', text: 'I' },
            { label: '動詞', text: 'seen' },
            { label: '目的語', text: 'such a mess' },
          ],
          caption: 'Never を文頭に出すと、have と I の順番が入れ替わります(疑問文と同じ語順)。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Never have I seen such a beautiful sunset as the one we watched from that hill.', ja: 'あの丘から見た夕日ほど美しいものは、これまで見たことがありません。', highlight: 'Never have I seen' },
            { en: 'Little did I know that this was only the beginning.', ja: 'これがほんの始まりに過ぎないとは、まったく知りませんでした。', highlight: 'Little did I know', note: '一般動詞の文は do / does / did を借りて倒置します。' },
            { en: 'Not only does she speak French, but she also teaches it at a local university.', ja: '彼女はフランス語を話すだけでなく、地元の大学で教えてもいます。', highlight: 'Not only does she speak', note: 'Not only の文は but ... also で受けるのが基本の形です。' },
            { en: 'Rarely do we get such a clear view of Mount Fuji from this side of the lake.', ja: '湖のこちら側から富士山がこんなにはっきり見えることは、めったにありません。', highlight: 'Rarely do we get' },
            { en: 'Under no circumstances should you share this password with anyone outside the team.', ja: 'どんな状況でも、このパスワードをチーム外の人に教えてはいけません。', highlight: 'should you share' },
          ],
        },
        {
          type: 'explanation',
          title: '会話の定番: So do I / Neither do I',
          body:
            '倒置は日常会話にも定番の形があります。相手の発言に「私も」と返す **So + 助動詞 + 主語** です。\n\n- I love this song. — **So do I.**(私も好きです)\n- I was exhausted. — **So was I.**(私もでした)\n\n相手の文が否定文なら、So の代わりに **Neither(または Nor)** を使います。\n\n- I can\'t swim. — **Neither can I.**(私も泳げません)\n\nポイントは助動詞選びです。相手の文が be動詞なら be動詞、can なら can、一般動詞なら do / does / did。相手の文とセットで反射的に出るまで練習しましょう。',
        },
        {
          type: 'contrast',
          title: '「私も」の使い分け',
          left: {
            label: '肯定文に同意: So + 助動詞 + 主語',
            items: [
              { en: 'So do I.', ja: '私も好きです。', note: '相手: I like coffee.(一般動詞 → do)' },
              { en: 'So am I.', ja: '私も疲れています。', note: '相手: I am tired.(be動詞 → am)' },
            ],
            pointJa: '助動詞は相手の文に合わせる',
          },
          right: {
            label: '否定文に同意: Neither + 助動詞 + 主語',
            items: [
              { en: 'Neither do I.', ja: '私も好きではありません。', note: '相手: I do not like natto.' },
              { en: 'Neither can I.', ja: '私も泳げません。', note: '相手: I cannot swim.' },
            ],
            pointJa: 'Neither 自体が否定なので not は付けない',
          },
          note: 'くだけた会話なら肯定文には Me too、否定文には Me neither も使えます。',
        },
      ],
      quiz: [
        {
          id: 'u30-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Never ___ such heavy snow in this town.',
          sentenceJa: 'この町でこんな大雪は見たことがありません。',
          choices: ['I have seen', 'have I seen', 'I saw', 'did I saw'],
          correctIndex: 1,
          explanation: 'Never を文頭に出したら、後ろは疑問文と同じ語順(have + 主語 + 過去分詞)にします。',
          choiceNotes: ['Never が文頭にあるのに通常の語順のままでは使えません。倒置が必要です。', null, '倒置になっていないうえ、never は saw の前に置く必要があります。', 'did のあとの動詞は原形です。saw は続けられません。'],
          audioEn: 'Never have I seen such heavy snow in this town.',
        },
        {
          id: 'u30-l2-q2',
          prompt: '「私もです」と返す言葉として正しいものを選んでください。',
          sentence: "I can't eat raw fish. — ___",
          sentenceJa: '生魚が食べられないんです。— 私もです。',
          choices: ['So can I.', 'So do I.', 'Neither can I.', 'Neither do I.'],
          correctIndex: 2,
          explanation: "相手の文は can't の否定文なので Neither を使い、助動詞も相手に合わせて can にします。",
          choiceNotes: ['So は肯定文への同意に使います。相手の文は否定文です。', 'So は肯定文向きで、助動詞も can の文には do ではなく can で応じます。', null, '助動詞は相手の文に合わせます。can の文には do ではなく can です。'],
          audioEn: 'Neither can I.',
        },
        {
          id: 'u30-l2-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Not only ___ late, but he also forgot the documents.',
          sentenceJa: '彼は遅刻しただけでなく、書類も忘れました。',
          choices: ['he was', 'was he', 'did he', 'he is'],
          correctIndex: 1,
          explanation: 'Not only を文頭に出したら倒置が必要です。late は形容詞なので be動詞を主語の前に出して was he とします。',
          choiceNotes: ['Not only が文頭にあるので、通常の語順のままでは使えません。', null, 'late は形容詞なので do ではなく be動詞で倒置します。', '倒置になっておらず、時制も過去の文脈に合いません。'],
          audioEn: 'Not only was he late, but he also forgot the documents.',
        },
        {
          id: 'u30-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Little did we know that the store would close that day.',
            'Rarely does he show his true feelings.',
            'Not only did they win the final, but they also broke the national record.',
            'Never I had been to such a formal dinner before.',
          ],
          correctIndex: 3,
          explanation: 'Never を文頭に出したら助動詞と主語を入れ替えます。正しくは Never had I been to such a formal dinner before. です。',
          choiceNotes: ['正しい倒置です。一般動詞の過去の文なので did を借りています。', '正しい倒置です。三人称単数・現在なので does を借りています。', '正しい倒置です。過去の一般動詞の文なので did を借りています。', null],
          audioEn: 'Never had I been to such a formal dinner before.',
        },
        {
          id: 'u30-l2-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Seldom ___ a candidate with such a wide range of practical experience.',
          sentenceJa: 'これほど幅広い実務経験を持つ候補者に出会うことはめったにありません。',
          choices: [
            'we meet',
            'do we meet',
            'we do meet',
            'meet we',
          ],
          correctIndex: 1,
          explanation: 'Seldom を文頭に出すと倒置が必要です。一般動詞の文なので do を借りて do we meet とします。',
          choiceNotes: ['否定的な語句が文頭にあるので、通常の語順のままでは使えません。', null, 'do の位置が違います。助動詞を主語の前に出します。', '助動詞を借りずに動詞と主語を入れ替えることはできません。'],
          audioEn: 'Seldom do we meet a candidate with such a wide range of practical experience.',
        },
        {
          id: 'u30-l2-q6',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Not until the results were published ___ how serious the problem had become.',
          sentenceJa: '結果が公表されて初めて、その問題がどれほど深刻になっていたかを私たちは知りました。',
          choices: [
            'we realized',
            'realized we',
            'did we realize',
            'we did realize',
          ],
          correctIndex: 2,
          explanation: 'Not until ... を文頭に出すと、主節が倒置します。一般動詞の過去の文なので did we realize になります。',
          choiceNotes: ['Not until が文頭にあるので倒置が必要です。', '助動詞を借りずに動詞と主語を入れ替えることはできません。', null, 'did の位置が違います。助動詞を主語の前に出します。'],
          audioEn: 'Not until the results were published did we realize how serious the problem had become.',
        },
        {
          id: 'u30-l2-q7',
          prompt: '「私もです」と返す言葉として正しいものを選んでください。',
          sentence: 'I have never been to Hokkaido in winter. — ___',
          sentenceJa: '冬に北海道へ行ったことがありません。— 私もです。',
          choices: [
            'So have I.',
            'Neither have I.',
            'Neither do I.',
            'So do I.',
          ],
          correctIndex: 1,
          explanation: '相手の文は never を含む否定文なので Neither を使い、助動詞も相手に合わせて have にします。',
          choiceNotes: ['So は肯定文への同意に使います。', null, '助動詞は相手の文に合わせます。have の文には do ではなく have です。', '否定文への同意には Neither を使います。'],
          audioEn: 'Neither have I.',
        },
        {
          id: 'u30-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Under no circumstances should staff leave the reception desk unattended.',
            'Rarely have I read a report so clearly written and so well organized.',
            'Little did the organizers know that over two thousand people would attend.',
            'Never I will forget the kindness of the people in that small village.',
          ],
          correctIndex: 3,
          explanation: 'Never を文頭に出したら助動詞と主語を入れ替えます。正しくは Never will I forget です。',
          choiceNotes: ['正しい倒置です。should が主語の前に出ています。', '正しい倒置です。have が主語の前に出ています。', '正しい倒置です。did を借りています。', null],
          audioEn: 'Never will I forget the kindness of the people in that small village.',
        },
        {
          id: 'u30-l2-q9',
          prompt: '倒置を使う効果として最も適切なものを選んでください。',
          sentence: 'Never have I seen the harbour so quiet at this time of year.',
          choices: [
            '書き言葉やフォーマルな場面で、否定の気持ちを強く打ち出す効果がある。',
            '過去の出来事であることをはっきり示す効果がある。',
            '疑問文であることを示す効果がある。',
            '文を短くして会話らしくする効果がある。',
          ],
          correctIndex: 0,
          explanation: '倒置は通常の語順でも文法的には正しく、強調のために使う形です。書き言葉やフォーマルな場面で好まれます。',
          choiceNotes: [null, '時制を示すのは動詞の形であって、倒置ではありません。', '語順は疑問文と同じですが、疑問文ではありません。', 'むしろ改まった響きになり、会話らしさは減ります。'],
          audioEn: 'Never have I seen the harbour so quiet at this time of year.',
        },
        {
          id: 'u30-l2-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: "I wasn't able to finish the report on time. — ___",
          sentenceJa: '報告書を期限内に仕上げられませんでした。— 私もです。',
          choices: [
            'So was I.',
            'Neither did I.',
            'Neither was I.',
            'So did I.',
          ],
          correctIndex: 2,
          explanation: '相手の文は was not able という be動詞の否定文なので、Neither was I. と応じます。',
          choiceNotes: ['So は肯定文への同意です。', '助動詞は相手の文に合わせます。be動詞の文には do ではなく be動詞です。', null, '否定文への同意には Neither を使います。'],
          audioEn: 'Neither was I.',
        },
      ],
      summary: [
        'Never / Rarely / Little / Not only などの否定的な語句を文頭に出すと、後ろは疑問文と同じ語順(倒置)になる。',
        '助動詞がない一般動詞の文は do / does / did を借りて倒置する。',
        '「私も」は肯定文に So + 助動詞 + 主語、否定文に Neither + 助動詞 + 主語。助動詞は相手の文に合わせる。',
        '倒置は書き言葉やフォーマルな場面で強調を生む形。通常の語順でも文法的には正しい。',
      ],
    },
    {
      id: 'u30-l3',
      unitId: 'u30',
      level: 'B2',
      title: '省略と代用',
      objective: 'so / not や助動詞、if possible などの省略表現を使って、同じ言葉を繰り返さない簡潔で自然な英語を話せるようになります。',
      minutes: 10,
      prereqs: ['u30-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '繰り返さないのが英語流: so と not',
          body:
            '英語は同じ言葉の繰り返しをとても嫌う言語です。一度出てきた内容は、できるだけ短い形で受け直します。\n\nその代表が **so と not** です。Do you think it will rain? と聞かれて、that節をまるごと繰り返す代わりにこう答えます。\n\n- I think **so**.(降ると思います = I think it will rain.)\n- I hope **not**.(降らないといいのですが = I hope it will not rain.)\n\nso は「前の内容をそのまま」、not は「前の内容の否定」を一語で受けます。',
        },
        {
          type: 'table',
          title: 'so / not の組み合わせ',
          headers: ['動詞', '「そうだと思う」', '「そうではないと思う」'],
          rows: [
            ['think', 'I think so.', "I don't think so."],
            ['hope', 'I hope so.', 'I hope not.'],
            ['be afraid', "I'm afraid so.", "I'm afraid not."],
            ['guess', 'I guess so.', 'I guess not.'],
          ],
        },
        {
          type: 'explanation',
          title: '動詞のかたまりは助動詞・to で止める',
          body:
            '動詞のかたまり(動詞 + そのあと全部)が繰り返しになるときは、**助動詞だけ残してあとを省略**します。\n\n- She has finished her report, but I **haven\'t**.(haven\'t のあとの finished my report を省略)\n- My wife gets up earlier than I **do**.(一般動詞の繰り返しは do / does / did で代用)\n\nto不定詞の繰り返しは **to で止める**のが自然です。\n\n- You can leave early if you want **to**.(want to のあとの leave early を省略)',
        },
        {
          type: 'explanation',
          title: 'if possible: 副詞節の中の省略',
          body:
            'if / when / while などの後ろでは、**「主語 + be動詞」をまとめて省略**できます。主語が it の決まり文句や、主節と主語が同じときに使える書き方です。\n\n- **if possible**(= if it is possible)可能であれば\n- **when necessary**(= when it is necessary)必要なときに\n- **while waiting for the bus**(= while I was waiting for the bus)バスを待っている間に\n\n掲示や説明書、ビジネスメールで非常によく見かける形です。',
        },
        {
          type: 'structure',
          title: '残すのは主語と助動詞、落とすのはその後ろ',
          parts: [
            { label: '残す: 主語', text: 'I' },
            { label: '残す: 助動詞', text: "haven't" },
            { label: '落とす: 繰り返し部分', text: 'finished my report' },
          ],
          caption: "She has finished her report, but I haven't. のように、繰り返しになる部分だけを落とします。日本語は主語ごと落とせますが、英語で落とせるのは助動詞より後ろだけです。",
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Will the meeting finish by five so that I can catch the express train? I think so.', ja: '特急に間に合うよう、会議は5時までに終わりますか。そう思います。', highlight: 'I think so' },
            { en: 'Do we have to work this weekend as well as next one? I really hope not.', ja: '来週末に加えて今週末も働かないといけないのですか。本当にそうでないといいのですが。', highlight: 'I really hope not' },
            { en: "My husband can't drive on the expressway at night, but I can.", ja: '夫は夜に高速道路を運転できませんが、私はできます。', highlight: 'but I can', note: 'can のあとの drive を繰り返しません。' },
            { en: 'She practices the violin much more seriously than I do these days.', ja: '彼女は最近、私よりずっと真剣にバイオリンを練習しています。', highlight: 'than I do', note: 'practice の繰り返しを do で代用します。' },
            { en: 'You can stay longer after the workshop finishes if you want to.', ja: '研修が終わったあと、望むならもっと長くいてもいいですよ。', highlight: 'want to', note: 'to のあとの stay longer を省略しています。' },
            { en: 'Please reply to this message by Friday afternoon if possible.', ja: '可能であれば金曜日の午後までにこのメッセージへ返信してください。', highlight: 'if possible', note: 'if it is possible の it is を省略した形です。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u30-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Will it rain during the festival? — I hope ___.',
          sentenceJa: 'お祭りの間に雨は降るでしょうか。— 降らないといいのですが。',
          choices: ['not', 'so', "don't", 'it'],
          correctIndex: 0,
          explanation: '「降らないでほしい」という否定の内容を受けるので not を使います。I hope not. = I hope it will not rain. です。',
          choiceNotes: [null, 'I hope so. だと「降ってほしい」という逆の意味になります。', "hope の否定は I don't hope とは言わず、I hope not. の形にします。", 'it では前の文の内容を受けられません。so か not を使います。'],
          audioEn: 'I hope not.',
        },
        {
          id: 'u30-l3-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: 'My brother speaks English much better than I ___.',
          sentenceJa: '兄は私よりずっと上手に英語を話します。',
          choices: ['do', 'am', 'it', 'so'],
          correctIndex: 0,
          explanation: '一般動詞 speak の繰り返しを避けるため、代動詞の do で受けます。than I do = than I speak English です。',
          choiceNotes: [null, 'speaks は一般動詞なので be動詞では受けられません。', 'it は動詞の代わりにはなりません。', 'so は think so のように節を受ける言葉で、動詞の代わりには使えません。'],
          audioEn: 'My brother speaks English much better than I do.',
        },
        {
          id: 'u30-l3-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「必要なら私の傘を使ってください」と言いたいとき。',
          choices: [
            'Use my umbrella if necessary.',
            'Use my umbrella if it necessary.',
            'Use my umbrella if is necessary.',
            'Use my umbrella if necessary it is.',
          ],
          correctIndex: 0,
          explanation: 'if necessary は if it is necessary の「主語 + be動詞」を省略した決まり文句です。',
          choiceNotes: [null, '省略するなら it is を丸ごと省きます。it だけ残すことはできません。', '主語だけを省いて is を残す形はありません。', '語順が崩れています。省略しない形は if it is necessary です。'],
          audioEn: 'Use my umbrella if necessary.',
        },
        {
          id: 'u30-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            "She has read the book, but I haven't.",
            "Do you think he will accept the offer? I'm afraid not.",
            "You don't have to apologize, but I know you want to.",
            'Is the museum open on Mondays? I believe it.',
          ],
          correctIndex: 3,
          explanation: '前の文の内容(美術館が月曜日に開いていること)を受けるときは it ではなく so を使います。正しくは I believe so. です。',
          choiceNotes: ["正しい省略です。haven't のあとの read the book を繰り返していません。", "正しい形です。be afraid の否定の代用は not です。", '正しい省略です。to のあとの apologize を省いています。', null],
          audioEn: 'I believe so.',
        },
        {
          id: 'u30-l3-q5',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Is the ferry running today despite the wind? — I am afraid ___ .',
          sentenceJa: 'この風でも今日フェリーは動いていますか。— 残念ながら動いていないようです。',
          choices: [
            'not',
            'so',
            'it',
            'no',
          ],
          correctIndex: 0,
          explanation: 'be afraid の否定の代用は not です。I am afraid not. = I am afraid it is not running. という意味になります。',
          choiceNotes: [null, 'I am afraid so. だと「残念ながら動いています」という逆の意味になります。', 'it では前の文の内容を受けられません。', 'この位置に no は置けません。'],
          audioEn: 'I am afraid not.',
        },
        {
          id: 'u30-l3-q6',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My colleagues have already submitted their forms, but I ___ .',
          sentenceJa: '同僚たちはもう用紙を提出しましたが、私はまだです。',
          choices: [
            "don't",
            "haven't",
            "didn't",
            'am not',
          ],
          correctIndex: 1,
          explanation: "前の節が現在完了なので、繰り返しを避けるときも同じ助動詞 have を残して haven't とします。",
          choiceNotes: ['前の節は現在完了なので do では受けられません。', null, '前の節は現在完了なので did では受けられません。', 'be動詞では現在完了の文を受けられません。'],
          audioEn: "My colleagues have already submitted their forms, but I haven't.",
        },
        {
          id: 'u30-l3-q7',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'We will send a printed copy of the contract ___ .',
          sentenceJa: 'ご要望があれば、契約書の紙のコピーをお送りします。',
          choices: [
            'if requesting',
            'if it request',
            'if requested',
            'if to request',
          ],
          correctIndex: 2,
          explanation: 'if requested は if it is requested の「主語 + be動詞」を省略した形です。掲示や書類でよく使われます。',
          choiceNotes: ['-ing だとコピーが要求する側になってしまいます。', 'it だけを残す形にはできません。', null, 'if のあとに to不定詞は続けられません。'],
          audioEn: 'We will send a printed copy of the contract if requested.',
        },
        {
          id: 'u30-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Please contact the office by phone rather than email when possible.',
            'I would like to join the trip, but my manager says I cannot.',
            'She reads far more novels in a year than I do.',
            'Do you think the train will be on time? I believe it.',
          ],
          correctIndex: 3,
          explanation: '前の文の内容を受けるときは it ではなく so を使います。正しくは I believe so. です。',
          choiceNotes: ['正しい省略です。when it is possible の it is を省いています。', '正しい省略です。cannot のあとの join the trip を省いています。', '正しい代用です。reads の繰り返しを do で受けています。', null],
          audioEn: 'I believe so.',
        },
        {
          id: 'u30-l3-q9',
          prompt: '空所に入る形を選んでください。',
          sentence: 'You do not have to attend the whole workshop, but you may stay ___ .',
          sentenceJa: '研修全体に出席する必要はありませんが、望むなら残っていてかまいません。',
          choices: [
            'if you want to',
            'if you want',
            'if you want it',
            'if you want that',
          ],
          correctIndex: 0,
          explanation: 'to不定詞の繰り返しは to で止めます。if you want to = if you want to stay という意味です。',
          choiceNotes: [null, 'want のあとに to を残すほうが自然で、省略の形として定着しています。', 'it では動詞句の繰り返しを受けられません。', 'that では動詞句の繰り返しを受けられません。'],
          audioEn: 'You do not have to attend the whole workshop, but you may stay if you want to.',
        },
        {
          id: 'u30-l3-q10',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: "A: I don't think so.   B: I think not.",
          choices: [
            'どちらも否定を表すが、Aが日常的で、Bはかなり硬い言い方である。',
            'Aは肯定、Bは否定を表す。',
            'Bのほうが日常会話でよく使われる。',
            'Aは疑問文である。',
          ],
          correctIndex: 0,
          explanation: "think の否定は I don't think so が普通で、I think not はかなり改まった響きになります。hope や be afraid では逆に not を使うのが普通です。",
          choiceNotes: [null, 'どちらも否定を表します。', '日常的なのは A のほうです。', 'A は平叙文です。'],
          audioEn: "I don't think so.",
        },
      ],
      summary: [
        '前の文の内容は so(肯定)/ not(否定)で受ける。I think so. / I hope not.',
        "think の否定は I don't think so、hope / be afraid は I hope not / I'm afraid not と作り方が違う。",
        '繰り返しになる動詞のかたまりは助動詞や to で止める。than I do / if you want to.',
        'if possible / when necessary などは「主語 + be動詞」を省略した決まり文句。',
      ],
    },
  ],
}
