import type { GrammarUnit } from '../../types'

// U31 紛らわしい構造の整理 — B2の総仕上げ。時制の総合選択と、混同しやすい単語ペアの整理。

export const u31: GrammarUnit = {
  id: 'u31',
  level: 'B2',
  title: '紛らわしい構造の整理',
  lessons: [
    {
      id: 'u31-l1',
      unitId: 'u31',
      level: 'B2',
      title: '時制の総合選択',
      objective: '時を表す語句と文脈を手がかりに、過去形・現在完了・過去完了などの時制を正しく選び分けられるようになります。',
      minutes: 12,
      prereqs: ['u30-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '時制は基準となる時点から考える',
          body:
            '時制を選ぶときは、**基準となる時点 → 出来事との関係 → 文脈**の順に確認します。\n\n- **いつの場面か**: 今、過去、未来のどこを基準に話していますか。\n- **どんな様子か**: 習慣・状態、進行中の動作、その時点までの経験・継続・完了のどれですか。\n- **何を伝えたいか**: 出来事の発生、途中の様子、結果のどれに注目していますか。\n\nfor / since / yesterday などは手がかりです。ただし、for があっても過去形・現在完了・過去完了のどれも使えます。単語を拾うだけでなく、**話の基準となる時点と出来事の関係**を読んで選びましょう。',
        },
        {
          type: 'timeline',
          title: '3つの時制の「時間の位置」',
          timelines: [
            {
              title: '過去形: We moved here in 2015.',
              point: 40,
              pointLabel: '2015年に引っ越した',
              caption: '終わった時間(in 2015)の中の一点。今の状況には触れません。',
            },
            {
              title: '現在完了: We have lived here since 2015.',
              range: [40, 100],
              rangeLabel: '2015年から今まで',
              arrowToNow: true,
              caption: '過去に始まり、今も続く。since / for とセットで使います。',
            },
            {
              title: '過去完了: The train had already left when we arrived.',
              point: 25,
              pointLabel: '電車が出発',
              caption: '過去の基準点(駅に着いた)よりさらに前を表します。基準になる過去が必要です。',
            },
          ],
        },
        {
          type: 'table',
          title: '時間のシグナルと時制の対応',
          headers: ['時を示す語句', '選ぶ時制', '例'],
          rows: [
            ['yesterday / ago / last week / in 2010', '過去形', 'I saw him two days ago.'],
            ['since / for / just / yet / so far', '現在完了', 'I have known her since college.'],
            ['for + 期間(動作が今も進行中)', '現在完了進行形', 'She has been waiting for an hour.'],
            ['by the time + 過去の文', '過去完了', 'The movie had started by the time we arrived.'],
            ['when / if / as soon as の節(未来の内容)', '現在形', 'I will text you when I arrive.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have just finished the report, so I can help you now.', ja: 'ちょうどレポートを終えたところなので、今なら手伝えます。', highlight: 'have just finished' },
            { en: 'We moved to this city ten years ago and have never seriously thought about leaving.', ja: '10年前にこの街に引っ越してきて、離れようと本気で考えたことは一度もありません。', highlight: 'moved', note: 'ago があるので過去形。現在完了は使えません。' },
            { en: 'By the time we got to the theater, the movie had started.', ja: '映画館に着いたときには、映画は始まっていました。', highlight: 'had started' },
            { en: 'She has been practicing the violin for two hours, and she is still playing.', ja: '彼女は2時間バイオリンを練習していて、今もまだ弾いています。', highlight: 'has been practicing' },
            { en: 'I will send you a message as soon as I arrive at the hotel tomorrow evening.', ja: '明日の夕方ホテルに着いたら、すぐメッセージを送ります。', highlight: 'arrive', note: '時の副詞節の中は、未来の内容でも現在形です。' },
          ],
        },
        {
          type: 'contrast',
          title: '過去形 vs 現在完了',
          left: {
            label: '過去形',
            items: [
              { en: 'I lived in Osaka for three years.', ja: '私は3年間大阪に住んでいました。', highlight: 'lived', note: '今は住んでいません。' },
              { en: 'She worked here until last March.', ja: '彼女は去年の3月までここで働いていました。', highlight: 'worked' },
            ],
            pointJa: '今とは切り離された、終わった話',
          },
          right: {
            label: '現在完了',
            items: [
              { en: 'I have lived in Osaka for three years.', ja: '私は大阪に住んで3年になります。', highlight: 'have lived', note: '今も住んでいます。' },
              { en: 'She has worked here since last March.', ja: '彼女は去年の3月からここで働いています。', highlight: 'has worked' },
            ],
            pointJa: '過去から今につながる話',
          },
          note: '同じ for three years でも、過去形なら「終わった3年間」、現在完了なら「今も続く3年間」です。',
        },
        {
          type: 'explanation',
          title: '間違えやすい3つの落とし穴',
          body:
            '- **終わった時間の語句と現在完了は同居できない**: yesterday / last week / ago / in 2010 などで出来事を終わった過去に位置付けるなら、過去形などの過去を表す形で述べます。× I have seen him yesterday.\n\n- **時・条件の副詞節では未来でも現在形**: when / if / as soon as / until の節の中では will を使いません。I will call you when I **get** home.\n\n- **過去完了は単独で使わない**: had done は「過去の基準点よりさらに前」を表す形なので、基準になる過去の出来事が文脈に必要です。',
        },
      ],
      quiz: [
        {
          id: 'u31-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My parents ___ in this house since 1998.',
          sentenceJa: '両親は1998年からこの家に住んでいます。',
          choices: ['live', 'lived', 'have lived', 'had lived'],
          correctIndex: 2,
          explanation: 'since 1998(1998年から今まで)という継続を表すのは現在完了です。',
          choiceNotes: [
            '現在形は「今の習慣・事実」を表す形で、since からの継続は表せません。',
            '過去形は今と切り離された話に使う形で、「今まで」を含む since とは組み合わせられません。',
            null,
            '過去完了は過去の基準点よりさらに前を表す形で、「今までの継続」には使えません。',
          ],
          audioEn: 'My parents have lived in this house since 1998.',
        },
        {
          id: 'u31-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「先週その映画を見ました」と言いたいとき。',
          choices: [
            'I have seen the movie last week.',
            'I saw the movie last week.',
            'I had seen the movie last week.',
            'I have been seeing the movie last week.',
          ],
          correctIndex: 1,
          explanation: 'last week は「終わった時間」を示す語句なので、過去形を使います。',
          choiceNotes: [
            'last week のような終わった時間の語句は、現在完了と同じ文では使えません。',
            null,
            '過去完了は基準になる別の過去の出来事が必要です。ここでは単独の過去の話なので使えません。',
            '現在完了進行形も last week とは組み合わせられません。1回見た経験に進行形も不自然です。',
          ],
          audioEn: 'I saw the movie last week.',
        },
        {
          id: 'u31-l1-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I will let you know when the package arrives.',
            'By the time we reached the top, the sun had risen.',
            'I have known him for over twenty years.',
            'She will call you as soon as she will finish the meeting.',
          ],
          correctIndex: 3,
          explanation: '時の副詞節(as soon as など)の中では、未来の内容でも will を使わず現在形にします。正しくは as soon as she finishes the meeting です。',
          choiceNotes: [
            '正しい文です。時の副詞節 when の中は、未来の内容でも現在形 arrives を使います。',
            '正しい文です。頂上に着いた(過去の基準点)より前に日が昇っていたことを過去完了で表しています。',
            '正しい文です。know のような状態動詞は for + 期間と現在完了で「今までの継続」を表せます。',
            null,
          ],
          audioEn: 'She will call you as soon as she finishes the meeting.',
        },
        {
          id: 'u31-l1-q4',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'Emi has been writing her novel for six months.',
          choices: [
            'エミは6か月前に小説を書き終えた。',
            'エミは6か月かけて小説を書き、今は書いていない。',
            'エミは6か月前から小説を書いていて、今も書いている途中だ。',
            'エミは6か月後に小説を書き始める予定だ。',
          ],
          correctIndex: 2,
          explanation: '現在完了進行形は「過去に始まった動作が今も続いている」ことを表します。6か月前に始めた執筆が今も続いている、という意味です。',
          choiceNotes: [
            '「6か月前に書き終えた」なら finished her novel six months ago のように過去形で表します。',
            '完成を表すなら has written her novel のような完了の形になります。進行形は動作の継続を表します。',
            null,
            '未来の予定の話ではありません。has been writing は過去から今への継続を表します。',
          ],
          audioEn: 'Emi has been writing her novel for six months.',
        },
        {
          id: 'u31-l1-q5',
          prompt: '空所に入る形を選んでください。',
          sentence: 'By the time the fire brigade arrived, the neighbours ___ most of the furniture outside.',
          sentenceJa: '消防隊が到着したときには、近所の人たちが家具の大半を外へ運び出していました。',
          choices: [
            'carried',
            'have carried',
            'had carried',
            'were carrying',
          ],
          correctIndex: 2,
          explanation: '到着より前に完了していた動作なので、過去完了 had carried を使います。By the time は前後関係を示す目印です。',
          choiceNotes: ['過去形では、到着より前だという前後関係を示せません。', '現在完了は過去の一時点を示す文脈と一緒に使えません。', null, '進行形では運び終えていたことを表せません。'],
          audioEn: 'By the time the fire brigade arrived, the neighbours had carried most of the furniture outside.',
        },
        {
          id: 'u31-l1-q6',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I ___ this dictionary for over fifteen years, and I still use it almost every day.',
          sentenceJa: 'この辞書を15年以上持っていて、今でもほぼ毎日使っています。',
          choices: [
            'have had',
            'had',
            'am having',
            'have been having',
          ],
          correctIndex: 0,
          explanation: '過去から今まで続いている状態なので現在完了にします。have は状態動詞なので進行形にはしません。',
          choiceNotes: [null, '過去形では今も持っていることを表せません。', 'have を所有の意味で使うときは進行形にしません。', '状態動詞 have は完了進行形にもしません。'],
          audioEn: 'I have had this dictionary for over fifteen years, and I still use it almost every day.',
        },
        {
          id: 'u31-l1-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'We will start the presentation as soon as everyone ___ in the main hall.',
          sentenceJa: '全員が大ホールに着き次第、プレゼンテーションを始めます。',
          choices: [
            'will arrive',
            'arrives',
            'will have arrived',
            'arrived',
          ],
          correctIndex: 1,
          explanation: '時を表す副詞節の中では、未来の内容でも現在形を使います。主語が everyone なので arrives にします。',
          choiceNotes: ['時の副詞節の中に will は置きません。', null, 'この節の中では未来完了も使いません。', '過去形では未来の話になりません。'],
          audioEn: 'We will start the presentation as soon as everyone arrives in the main hall.',
        },
        {
          id: 'u31-l1-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'She has been reading that novel since the beginning of the holidays.',
            'I met my current business partner in Osaka about twelve years ago.',
            'When I got back to my desk, someone had moved all my papers.',
            'We have visited the shrine last weekend with my parents from Nagano.',
          ],
          correctIndex: 3,
          explanation: 'last weekend のように過去の一時点を示す語句とは、現在完了を使えません。過去形 visited にします。',
          choiceNotes: ['正しい文です。since と現在完了進行形が対応しています。', '正しい文です。ago があるので過去形です。', '正しい文です。戻る前の出来事を過去完了で示しています。', null],
          audioEn: 'We visited the shrine last weekend with my parents from Nagano.',
        },
        {
          id: 'u31-l1-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: I lived in Osaka for three years.   B: I have lived in Osaka for three years.',
          choices: [
            'Aは今は住んでいない、Bは今も住んでいることを表す。',
            'Aは今も住んでいる、Bは今は住んでいないことを表す。',
            'どちらも今も住んでいることを表す。',
            'Bは文法的に誤りである。',
          ],
          correctIndex: 0,
          explanation: '過去形は終わったこととして切り離し、現在完了は現在までつながっていることを表します。',
          choiceNotes: [null, '今とつながっているのは現在完了の B のほうです。', 'A は現在とのつながりを示しません。', 'B は正しい文です。'],
          audioEn: 'I lived in Osaka for three years. I have lived in Osaka for three years.',
        },
        {
          id: 'u31-l1-q10',
          prompt: '空所に入る形を選んでください。',
          sentence: 'While I ___ dinner, the smoke alarm suddenly went off and startled everyone.',
          sentenceJa: '夕食を作っている最中に火災報知器が突然鳴り、全員が驚きました。',
          choices: [
            'cooked',
            'was cooking',
            'had cooked',
            'have cooked',
          ],
          correctIndex: 1,
          explanation: '進行中の背景の動作には過去進行形を使い、その途中で起きた出来事を過去形で表します。',
          choiceNotes: ['過去形では進行中の背景であることを示せません。', null, '過去完了では、報知器が鳴る前に作り終えたことになります。', '現在完了は過去の場面の描写には使えません。'],
          audioEn: 'While I was cooking dinner, the smoke alarm suddenly went off and startled everyone.',
        },
      ],
      summary: [
        '時制は「時を示す語句」と「今とのつながり」の2つを手がかりに選ぶ。',
        'yesterday / ago など終わった時間の語句 → 過去形。since / for / yet など → 現在完了。',
        '過去完了は過去の基準点よりさらに前を表す。基準になる過去がなければ使わない。',
        '時・条件の副詞節(when / if / as soon as)の中は、未来の内容でも現在形。',
      ],
    },
    {
      id: 'u31-l2',
      unitId: 'u31',
      level: 'B2',
      title: '紛らわしいペア(1)',
      objective: 'by と until、during と while、despite と although のペアを、意味と後ろに置ける形の違いから正しく使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u31-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '見分けの軸は2つだけ',
          body:
            '意味はほとんど同じなのに、テストや実際の英文でよく混同されるペアを整理します。ポイントは2つだけです。\n\n- **後ろに何を置けるか**: 前置詞(during / despite)の後ろは名詞、接続詞(while / although)の後ろは主語+動詞の文\n- **時間の形**: by は「その時までのどこかで(締め切り)」、until は「その時までずっと(継続)」\n\nこの2つの視点でペアを見ていくと、迷いがほぼなくなります。',
        },
        {
          type: 'contrast',
          title: 'by vs until',
          left: {
            label: 'by(締め切り)',
            items: [
              { en: 'Please send me the file by noon.', ja: '正午までにファイルを送ってください。', highlight: 'by noon' },
              { en: 'I will be home by seven.', ja: '7時までには家に着きます。', highlight: 'by seven' },
            ],
            pointJa: 'その時までのどこかで1回起きる',
          },
          right: {
            label: 'until(継続)',
            items: [
              { en: 'The shop is open until nine.', ja: 'その店は9時まで開いています。', highlight: 'until nine' },
              { en: 'I waited for her until midnight.', ja: '夜中の12時まで彼女を待ちました。', highlight: 'until midnight' },
            ],
            pointJa: 'その時までずっと続く',
          },
          note: '動詞が finish / send / arrive のような1回きりの動作なら by、stay / wait / be open のような続く動作・状態なら until です。',
        },
        {
          type: 'contrast',
          title: 'during vs while',
          left: {
            label: 'during(前置詞)',
            items: [
              { en: 'He fell asleep during the movie.', ja: '彼は映画の間に眠ってしまいました。', highlight: 'during the movie' },
              { en: 'We met a lot of people during our trip.', ja: '旅行の間にたくさんの人と出会いました。', highlight: 'during our trip' },
            ],
            pointJa: '後ろは名詞(the movie / our trip)',
          },
          right: {
            label: 'while(接続詞)',
            items: [
              { en: 'He fell asleep while we were watching the movie.', ja: '私たちが映画を見ている間に、彼は眠ってしまいました。', highlight: 'while we were watching' },
              { en: 'Someone called while you were out.', ja: 'あなたの外出中に誰かから電話がありました。', highlight: 'while you were out' },
            ],
            pointJa: '後ろは主語+動詞の文',
          },
          note: '意味はほぼ同じ「〜の間に」。違いは後ろに置ける形だけです。',
        },
        {
          type: 'explanation',
          title: '「〜だけれど」の despite と although',
          body:
            'despite と although はどちらも「〜にもかかわらず・〜だけれど」という譲歩を表します。意味の違いはほぼなく、違うのは**後ろに置ける形**だけです。\n\n- **despite + 名詞・動名詞**: Despite the rain / Despite being tired\n- **although + 文**: Although it was raining\n\n注意点が2つあります。\n\n- × despite of ... という形は存在しません\n- in spite of は despite と同じ意味・同じ使い方で、こちらは of が付きます(3語でひとつの前置詞の働き)',
        },
        {
          type: 'contrast',
          title: 'despite vs although',
          left: {
            label: 'despite(前置詞)',
            items: [
              { en: 'Despite the heavy rain, the game continued.', ja: '激しい雨にもかかわらず、試合は続きました。', highlight: 'Despite the heavy rain' },
              { en: 'She went to work despite feeling sick.', ja: '体調が悪いのに、彼女は仕事に行きました。', highlight: 'despite feeling sick', note: '動名詞も置けます。' },
            ],
            pointJa: '後ろは名詞・動名詞。in spite of も同じ働き',
          },
          right: {
            label: 'although(接続詞)',
            items: [
              { en: 'Although it was raining heavily, the game continued.', ja: '激しく雨が降っていたけれど、試合は続きました。', highlight: 'Although it was raining' },
              { en: 'Although she felt sick, she went to work.', ja: '体調が悪かったけれど、彼女は仕事に行きました。', highlight: 'Although she felt sick' },
            ],
            pointJa: '後ろは主語+動詞の文',
          },
          note: '× despite of は存在しない形です。of を付けるのは in spite of だけです。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Please reply to this email by Wednesday so that we can confirm the numbers.', ja: '人数を確定できるよう、水曜日までにこのメールに返信してください。', highlight: 'by Wednesday' },
            { en: 'The library stays open until ten on weekdays.', ja: '図書館は平日は10時まで開いています。', highlight: 'until ten' },
            { en: 'My phone rang three times during the lecture even though I had switched it to silent.', ja: 'マナーモードにしていたのに、講義の間に電話が3回鳴りました。', highlight: 'during the lecture' },
            { en: 'I did the laundry while the kids were sleeping.', ja: '子どもたちが寝ている間に洗濯をしました。', highlight: 'while the kids were sleeping' },
            { en: 'Despite a painful injury to her left knee, she finished the race in under four hours.', ja: '左ひざの痛むけがにもかかわらず、彼女は4時間を切ってレースを走りきりました。', highlight: 'Despite' },
            { en: 'Although he apologized several times that evening, she was still angry the next morning.', ja: '彼はその晩に何度も謝りましたが、彼女は翌朝もまだ怒っていました。', highlight: 'Although he apologized' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u31-l2-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'You can keep the laptop ___ Friday, but I need it back on Saturday.',
          sentenceJa: '金曜日までそのノートパソコンを使っていていいですが、土曜日には返してください。',
          choices: ['by', 'until', 'during', 'while'],
          correctIndex: 1,
          explanation: '「金曜日までずっと持っている」という継続なので until を使います。',
          choiceNotes: [
            'by は「その時までのどこかで1回する」締め切りを表します。「持ったままでいる」継続には合いません。',
            null,
            'during は「〜の間に」を表す前置詞で、the meeting のような出来事の名詞と使います。期限には使えません。',
            'while は接続詞なので、後ろには Friday のような名詞ではなく文を続けます。',
          ],
          audioEn: 'You can keep the laptop until Friday, but I need it back on Saturday.',
        },
        {
          id: 'u31-l2-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「カナダ滞在中にたくさんの面白い人に出会いました」と言いたいとき。',
          choices: [
            'I met a lot of interesting people while my stay in Canada.',
            'I met a lot of interesting people during my stay in Canada.',
            'I met a lot of interesting people during I stayed in Canada.',
            'I met a lot of interesting people while I stay in Canada.',
          ],
          correctIndex: 1,
          explanation: 'my stay in Canada は名詞のかたまりなので、前置詞 during を使います。',
          choiceNotes: [
            'while は接続詞なので、後ろには my stay という名詞ではなく文を続けます。',
            null,
            'during は前置詞なので、後ろに主語+動詞の文は続けられません。',
            'while + 文の形は合っていますが、過去の話なので I stayed / I was staying と過去の時制が必要です。',
          ],
          audioEn: 'I met a lot of interesting people during my stay in Canada.',
        },
        {
          id: 'u31-l2-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Although the tickets were expensive, the concert was worth it.',
            'Despite the heavy traffic, we arrived on time.',
            'Despite of being tired, she finished the marathon.',
            'In spite of the cold weather, the children played outside.',
          ],
          correctIndex: 2,
          explanation: 'despite に of は付けません。正しくは Despite being tired、または In spite of being tired です。',
          choiceNotes: [
            '正しい文です。although の後ろに主語+動詞の文が続いています。',
            '正しい文です。despite の後ろに名詞 the heavy traffic が続いています。',
            null,
            '正しい文です。of が付くのは in spite of のときだけです。',
          ],
          audioEn: 'Despite being tired, she finished the marathon.',
        },
        {
          id: 'u31-l2-q4',
          prompt: '次の指示の意味として正しいものを選んでください。',
          sentence: 'Please finish the report by three.',
          choices: [
            '3時までずっと休まずレポートを書き続けてほしい。',
            '3時までのどこかの時点でレポートを終わらせてほしい。',
            '3時ちょうどにレポートを書き始めてほしい。',
            '3時以降にレポートを終わらせてほしい。',
          ],
          correctIndex: 1,
          explanation: 'by は締め切りを表します。「3時までのどこかの時点で終わらせる」という意味で、3時より前ならいつ終わらせてもかまいません。',
          choiceNotes: [
            '「その時までずっと〜し続ける」という継続を表すのは until です。',
            null,
            '開始時刻の指定ではありません。by three は「3時までに」という期限です。',
            'by three は「3時までに」なので、3時以降では遅すぎます。',
          ],
          audioEn: 'Please finish the report by three.',
        },
        {
          id: 'u31-l2-q5',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The application form must reach the office ___ the last working day of the month.',
          sentenceJa: '申込書は月の最終営業日までに事務局へ届かなければなりません。',
          choices: [
            'until',
            'by',
            'during',
            'while',
          ],
          correctIndex: 1,
          explanation: '期限までに1回の動作を完了させるので by を使います。until は状態や動作が続く終点を示します。',
          choiceNotes: ['until は「そのときまでずっと」続く場合に使います。届くのは1回の出来事です。', null, 'during のあとには期間を表す名詞が必要です。', 'while のあとには節が必要です。'],
          audioEn: 'The application form must reach the office by the last working day of the month.',
        },
        {
          id: 'u31-l2-q6',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The security guard stays at the north entrance ___ the last visitor has left the building.',
          sentenceJa: '警備員は最後の来訪者が建物を出るまで、北口に留まっています。',
          choices: [
            'by',
            'until',
            'during',
            'despite',
          ],
          correctIndex: 1,
          explanation: '留まるという状態が続く終点なので until を使います。by は1回の動作の期限に使います。',
          choiceNotes: ['by では「そのときまでずっと留まる」という継続を表せません。', null, 'during のあとには期間を表す名詞が必要です。', 'despite は譲歩を表します。'],
          audioEn: 'The security guard stays at the north entrance until the last visitor has left the building.',
        },
        {
          id: 'u31-l2-q7',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Several people left the hall ___ the second half of the concert.',
          sentenceJa: 'コンサートの後半の間に、数人が会場を出ていきました。',
          choices: [
            'while',
            'during',
            'until',
            'although',
          ],
          correctIndex: 1,
          explanation: 'during のあとには期間を表す名詞が続きます。節を続けるなら while を使います。',
          choiceNotes: ['while のあとには主語と動詞のある節が必要です。', null, 'until では出ていく時点ではなく終点を示すことになります。', 'although は譲歩を表す接続詞です。'],
          audioEn: 'Several people left the hall during the second half of the concert.',
        },
        {
          id: 'u31-l2-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Please stay in your seats until the aircraft has come to a complete stop.',
            'I read three chapters during the long train ride to Kanazawa.',
            'Although the software is free, it works better than most paid alternatives.',
            'Despite we had a reservation, we waited almost forty minutes for a table.',
          ],
          correctIndex: 3,
          explanation: 'despite のあとには名詞か動名詞を置きます。節を続けるなら Although we had a reservation とします。',
          choiceNotes: ['正しい文です。until のあとに節が続いています。', '正しい文です。during のあとに名詞句が続いています。', '正しい文です。although のあとに節が続いています。', null],
          audioEn: 'Although we had a reservation, we waited almost forty minutes for a table.',
        },
        {
          id: 'u31-l2-q9',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: I will finish it by Friday.   B: I will work on it until Friday.',
          choices: [
            'Aは金曜までに終える、Bは金曜まで作業を続けるという意味である。',
            'Aは金曜まで作業を続ける、Bは金曜までに終えるという意味である。',
            'どちらも金曜に始めることを表す。',
            'どちらも金曜に終わることを保証している。',
          ],
          correctIndex: 0,
          explanation: 'by は期限までの完了、until は継続の終点を示します。日本語ではどちらも「まで」なので注意が必要です。',
          choiceNotes: [null, '意味が逆になっています。', 'どちらも開始時点の話ではありません。', 'B は金曜まで続けるだけで、終わるとは言っていません。'],
          audioEn: 'I will finish it by Friday. I will work on it until Friday.',
        },
        {
          id: 'u31-l2-q10',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The delivery arrived ___ I was upstairs looking for the missing receipt.',
          sentenceJa: '私が2階でなくした領収書を探している間に、荷物が届きました。',
          choices: [
            'during',
            'while',
            'by',
            'until',
          ],
          correctIndex: 1,
          explanation: '空所のあとに主語と動詞のある節が続いているので while を使います。during のあとには名詞が必要です。',
          choiceNotes: ['during のあとに節は置けません。', null, 'by は期限を表し、この文には合いません。', 'until では届いた時点ではなく終点を示すことになります。'],
          audioEn: 'The delivery arrived while I was upstairs looking for the missing receipt.',
        },
      ],
      summary: [
        'by は「その時までのどこかで(締め切り)」、until は「その時までずっと(継続)」。',
        'during と while は同じ「〜の間に」。during + 名詞、while + 文。',
        'despite(= in spite of)+ 名詞・動名詞、although + 文。意味はほぼ同じ。',
        '× despite of は存在しない形。of が付くのは in spite of だけ。',
      ],
    },
    {
      id: 'u31-l3',
      unitId: 'u31',
      level: 'B2',
      title: '紛らわしいペア(2)',
      objective: 'so と such、another と other、rise と raise を、後ろに来る形や目的語の有無を手がかりに正しく使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u31-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '最後の仕上げは「形の使い分け」',
          body:
            'このレッスンでは、意味が近いのに形の使い方が違うために間違えやすい単語ペアを整理します。\n\n見分けの軸はシンプルです。\n\n- **後ろに何が来るか**: so の後ろは形容詞・副詞、such の後ろは名詞のかたまり\n- **単数か複数か**: another は単数、other は複数・不可算\n- **目的語があるか**: rise は自動詞、raise は他動詞\n\nどれも「意味」ではなく「形のルール」で決まるので、軸さえ覚えれば確実に得点源にできます。',
        },
        {
          type: 'contrast',
          title: 'so vs such',
          left: {
            label: 'so + 形容詞・副詞',
            items: [
              { en: "The soup was so hot that I couldn't eat it.", ja: 'スープがとても熱かったので、飲めませんでした。', highlight: 'so hot' },
              { en: 'He speaks so fast that I often miss the details.', ja: '彼はとても速く話すので、細かい部分をよく聞き逃します。', highlight: 'so fast' },
            ],
            pointJa: '後ろは形容詞・副詞だけ。名詞は置けない',
          },
          right: {
            label: 'such +(a)+ 形容詞 + 名詞',
            items: [
              { en: 'It was such a hot day that we stayed inside.', ja: 'とても暑い日だったので、私たちは家の中にいました。', highlight: 'such a hot day' },
              { en: 'They are such kind neighbors that everyone loves them.', ja: 'とても親切な隣人なので、みんな彼らが大好きです。', highlight: 'such kind neighbors' },
            ],
            pointJa: '名詞のかたまりが入るなら such',
          },
          note: 'どちらも that節を続けて「とても〜なので…」を表せます。可算名詞の単数なら such a ... の a を忘れずに。',
        },
        {
          type: 'table',
          title: 'another / other の仲間の使い分け',
          headers: ['形', '意味', '例'],
          rows: [
            ['another + 単数名詞', 'もう1つの・別の', 'another cup of coffee'],
            ['other + 複数名詞・不可算名詞', 'ほかの〜', 'other questions'],
            ['others(単独で使う)', 'ほかの人・もの', 'Some walk, and others take the bus.'],
            ['the other + 単数名詞', '(2つのうち)残りの1つの', 'the other side of the street'],
            ['the others', '残りの全部', 'Two students passed, and the others failed.'],
          ],
        },
        {
          type: 'explanation',
          title: 'rise と raise は「自分で上がるか、上げるか」',
          body:
            '**rise** は「(主語が自分で)上がる」自動詞、**raise** は「(何かを)上げる」他動詞です。\n\n- The sun **rises**.(太陽が昇る — 自分で上がる)\n- She **raised** her hand.(手を上げた — her hand という目的語がある)\n\n活用にも注意が必要です。\n\n- rise – **rose** – **risen**(不規則)\n- raise – raised – raised(規則変化)\n\nrise の過去形 rose と原形 raise の形が似ているのが混乱のもとです。迷ったら「動詞のすぐ後ろに目的語があるか」を確認しましょう。同じ関係のペアに lie(横になる・自動詞)と lay(〜を置く・他動詞)があります。',
        },
        {
          type: 'contrast',
          title: 'rise vs raise',
          left: {
            label: 'rise(自動詞)',
            items: [
              { en: 'The sun rises at five in summer.', ja: '夏は5時に日が昇ります。', highlight: 'rises' },
              { en: 'Prices rose sharply last year.', ja: '去年、物価が急に上がりました。', highlight: 'rose', note: '過去形は rose です。' },
            ],
            pointJa: '主語が自分で上がる。目的語なし',
          },
          right: {
            label: 'raise(他動詞)',
            items: [
              { en: 'She raised her hand to ask a question.', ja: '彼女は質問するために手を上げました。', highlight: 'raised her hand' },
              { en: 'The city raised bus fares in April.', ja: '市は4月にバス運賃を値上げしました。', highlight: 'raised bus fares' },
            ],
            pointJa: '何かを上げる。必ず目的語がある',
          },
          note: '「物価が上がった」は Prices rose(自動詞)、「会社が価格を上げた」は The company raised prices(他動詞)です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The final scene of the movie was so moving that half the audience was in tears.', ja: 'その映画の最後の場面はとても感動的で、観客の半分が涙を流していました。', highlight: 'so moving' },
            { en: 'This coffee has gotten cold. Could I have another cup?', ja: 'コーヒーが冷めてしまいました。もう一杯いただけますか。', highlight: 'another cup' },
            { en: 'Some students walk to school, and others take the bus.', ja: '歩いて通学する生徒もいれば、バスで通う生徒もいます。', highlight: 'others' },
            { en: 'I have two keys. One is for the house, and the other is for my bike.', ja: '鍵を2つ持っています。1つは家の鍵で、もう1つは自転車の鍵です。', highlight: 'the other' },
            { en: 'Food prices have risen again this year, mainly because of the poor summer harvest.', ja: '主に夏の不作が原因で、今年また食品の価格が上がりました。', highlight: 'risen' },
            { en: 'The airline raised its ticket prices last month without giving passengers any warning.', ja: 'その航空会社は乗客に何の予告もなく、先月航空券の値段を上げました。', highlight: 'raised' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u31-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'It was ___ a boring lecture that half the students fell asleep.',
          sentenceJa: 'とても退屈な講義だったので、学生の半分は眠ってしまいました。',
          choices: ['so', 'such', 'too', 'very'],
          correctIndex: 1,
          explanation: 'a boring lecture という名詞のかたまりが続くので such を使います。such a ... that の形です。',
          choiceNotes: [
            'so の後ろは形容詞・副詞だけです。a boring lecture という名詞のかたまりには such を使います。',
            null,
            'too は「〜すぎる」を表し、that節と組み合わせるこの形には使えません。',
            'very は that節と組み合わせて「とても〜なので…」の形を作れません。',
          ],
          audioEn: 'It was such a boring lecture that half the students fell asleep.',
        },
        {
          id: 'u31-l3-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「別の日に会議を設定してもらえますか」と言いたいとき。',
          choices: [
            'Could you schedule the meeting for other day?',
            'Could you schedule the meeting for another day?',
            'Could you schedule the meeting for the another day?',
            'Could you schedule the meeting for others day?',
          ],
          correctIndex: 1,
          explanation: '「もう1つの・別の」+ 単数名詞は another を使います。',
          choiceNotes: [
            'other は単独では単数名詞に付けられません。単数には another を使います。',
            null,
            'another に the は付けません。「残りの1つ」と特定するなら the other day ですが、意味が変わります。',
            'others は単独で使う代名詞で、後ろに名詞は続けられません。',
          ],
          audioEn: 'Could you schedule the meeting for another day?',
        },
        {
          id: 'u31-l3-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'The sun rises earlier in summer.',
            'She raised her hand to ask a question.',
            'Gas prices have raised sharply this year.',
            'The company raised salaries last month.',
          ],
          correctIndex: 2,
          explanation: '「価格が上がる」は主語が自分で上がる自動詞 rise を使い、現在完了は have risen です。raise は目的語が必要な他動詞です。',
          choiceNotes: [
            '正しい文です。太陽は自分で昇るので自動詞 rise を使います。',
            '正しい文です。her hand という目的語があるので他動詞 raise を使います。',
            null,
            '正しい文です。salaries という目的語があるので他動詞 raise を使います。',
          ],
          audioEn: 'Gas prices have risen sharply this year.',
        },
        {
          id: 'u31-l3-q4',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'One of my sisters lives in Kyoto, and the other works in Nagoya.',
          choices: [
            '姉妹は2人いる。',
            '姉妹は3人以上いる。',
            '姉妹は1人しかいない。',
            '京都にいる姉妹は名古屋でも働いている。',
          ],
          correctIndex: 0,
          explanation: 'the other は「残りの1人」を指すので、姉妹は全部で2人だと分かります。3人以上いて「別の1人」なら another、「残り全員」なら the others を使います。',
          choiceNotes: [
            null,
            '3人以上いる場合、「別の1人」は another、「残り全員」は the others で表します。the other は残りが1人のときの形です。',
            'one of my sisters という言い方は、姉妹が複数いることが前提です。',
            'one(京都に住む人)と the other(名古屋で働く人)は別の人を指しています。',
          ],
          audioEn: 'One of my sisters lives in Kyoto, and the other works in Nagoya.',
        },
        {
          id: 'u31-l3-q5',
          prompt: '空所に入る語を選んでください。',
          sentence: 'It was ___ a convincing argument that even the strongest opponents changed their minds.',
          sentenceJa: 'あまりに説得力のある主張だったので、最も強硬な反対派さえ考えを変えました。',
          choices: [
            'so',
            'such',
            'very',
            'too',
          ],
          correctIndex: 1,
          explanation: 'a convincing argument という名詞句が続くので such を使います。so は形容詞・副詞に直接付きます。',
          choiceNotes: ['so のあとに冠詞付きの名詞句は続けられません。', null, 'very では that節につながる構文になりません。', 'too では「〜すぎて…できない」という別の意味になります。'],
          audioEn: 'It was such a convincing argument that even the strongest opponents changed their minds.',
        },
        {
          id: 'u31-l3-q6',
          prompt: '空所に入る語を選んでください。',
          sentence: 'I did not like the first hotel, so we moved to ___ one closer to the station.',
          sentenceJa: '最初のホテルが気に入らなかったので、駅に近い別のホテルへ移りました。',
          choices: [
            'the other',
            'another',
            'other',
            'others',
          ],
          correctIndex: 1,
          explanation: '不特定の「もう一つ別の」は another です。数を限定していないので the other にはしません。',
          choiceNotes: ['the other は2つのうちの残り1つを指すときに使います。', null, 'other のあとには複数名詞が必要です。', 'others は代名詞で、名詞 one の前には置けません。'],
          audioEn: 'I did not like the first hotel, so we moved to another one closer to the station.',
        },
        {
          id: 'u31-l3-q7',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Electricity prices ___ sharply last winter, and the government ___ the subsidy in response.',
          sentenceJa: '昨冬は電気料金が急騰し、政府はそれに応じて補助金を引き上げました。',
          choices: [
            'raised / rose',
            'rose / raised',
            'rose / rose',
            'raised / raised',
          ],
          correctIndex: 1,
          explanation: 'rise は自動詞で「上がる」、raise は他動詞で「上げる」です。価格は自ら上がり、政府は補助金を上げます。',
          choiceNotes: ['raise には目的語が必要です。価格が自ら上がる場合は rose です。', null, '2つ目は the subsidy という目的語を取るので raised にします。', '1つ目には目的語がないので rose にします。'],
          audioEn: 'Electricity prices rose sharply last winter, and the government raised the subsidy in response.',
        },
        {
          id: 'u31-l3-q8',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'Some passengers took the shuttle bus, and others walked to the terminal.',
            'The presentation was so well prepared that the client signed on the spot.',
            'I have two brothers. One lives in Fukuoka, and the other works in Sendai.',
            'The temperature has raised by almost three degrees since this morning.',
          ],
          correctIndex: 3,
          explanation: '温度が自ら上がるので自動詞の rise を使います。正しくは The temperature has risen です。',
          choiceNotes: ['正しい文です。some と others が対になっています。', '正しい文です。so + 副詞 + that の形です。', '正しい文です。2人のうちの残り1人なので the other です。', null],
          audioEn: 'The temperature has risen by almost three degrees since this morning.',
        },
        {
          id: 'u31-l3-q9',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Three of the five machines are working normally. ___ two are still being repaired.',
          sentenceJa: '5台のうち3台は正常に動いています。残りの2台はまだ修理中です。',
          choices: [
            'Another',
            'Other',
            'The other',
            'Others',
          ],
          correctIndex: 2,
          explanation: '5台のうち3台を除いた残り全部を指すので、限定を示す the other を使います。',
          choiceNotes: ['another のあとは単数名詞で、不特定の1つを指します。', 'other だけでは残り全部という限定を示せません。', null, 'others は代名詞なので、名詞 two の前には置けません。'],
          audioEn: 'Three of the five machines are working normally. The other two are still being repaired.',
        },
        {
          id: 'u31-l3-q10',
          prompt: '次の2文の違いとして正しいものを選んでください。',
          sentence: 'A: so expensive that we gave up   B: such an expensive plan that we gave up',
          choices: [
            'soは形容詞・副詞に直接付き、suchは名詞句を伴う。',
            'soは名詞句を伴い、suchは形容詞に直接付く。',
            'どちらも名詞句を伴う。',
            'Bは文法的に誤りである。',
          ],
          correctIndex: 0,
          explanation: 'so + 形容詞・副詞、such + a + 形容詞 + 名詞、という形の違いがあります。意味は近くても形が異なります。',
          choiceNotes: [null, '役割が逆です。', 'A は形容詞に直接付いています。', 'B は正しい形です。'],
          audioEn: 'It was so expensive that we gave up. It was such an expensive plan that we gave up.',
        },
      ],
      summary: [
        'so + 形容詞・副詞、such +(a)+ 形容詞 + 名詞。どちらも that節と組み合わせて「とても〜なので…」。',
        'another は「もう1つ(単数)」、other は複数・不可算名詞に、the other は「(2つのうち)残りの1つ」。',
        'rise は自動詞「上がる」(rise – rose – risen)、raise は他動詞「〜を上げる」(raise – raised – raised)。',
        '迷ったら「動詞のすぐ後ろに目的語があるか」「後ろに名詞が来るか」という形のルールで判断する。',
      ],
    },
  ],
}
