import type { ReadingPassage } from '../types'

// 多読の本文。本プロジェクト用に書き下ろした自作テキスト(外部からの転載なし)。
// 数字は表記ゆれと音声化のぶれを避けるため、綴りで書く。

export const passages: ReadingPassage[] = [
  {
    id: 'r-a2-01',
    level: 'A2',
    title: 'The Library on Maple Street',
    titleJa: 'メープル通りの図書館',
    minutes: 12,
    canDo: ['R-A2-1', 'R-A2-2'],
    paragraphs: [
      'The small library on Maple Street opens at nine in the morning and closes at six in the evening. It is closed on Mondays. Many people in the neighborhood visit it every week.',
      'On the first floor, there are newspapers, magazines, and a quiet room for reading. Children go to the second floor, where the staff read stories aloud every Saturday afternoon. Parents often stay and listen too.',
      'You can borrow up to six books at a time. You keep them for three weeks, and you can renew them once by phone or on the website. If you return a book late, you do not pay money, but you cannot borrow anything new for a week.',
      'The library also lends tools. You can borrow a drill, a ladder, or a sewing machine for two days. This service started three years ago, and it has become very popular with people who live in small apartments.',
    ],
    paragraphsJa: [
      'メープル通りの小さな図書館は、朝9時に開き、夕方6時に閉まります。月曜日は休館です。近所の多くの人が毎週訪れます。',
      '1階には新聞と雑誌、それに静かな読書室があります。子どもたちは2階へ行き、そこでは毎週土曜の午後にスタッフが物語を読み聞かせます。保護者もよく残って一緒に聞いています。',
      '一度に6冊まで借りられます。3週間手元に置くことができ、電話かウェブサイトで1回だけ延長できます。返却が遅れてもお金はかかりませんが、1週間は新しく借りられません。',
      '図書館では道具の貸し出しもしています。ドリル、はしご、ミシンを2日間借りられます。このサービスは3年前に始まり、狭いアパートに住む人たちにとても人気があります。',
    ],
    glossary: [
      { word: 'borrow', ja: '借りる' },
      { word: 'renew', ja: '(貸出期間を)延長する' },
      { word: 'return', ja: '返却する' },
      { word: 'lend', ja: '貸す' },
      { word: 'popular', ja: '人気がある' },
      { word: 'neighborhood', ja: '近所、地域' },
    ],
    questions: [
      {
        id: 'r-a2-01-q1',
        prompt: '図書館が閉まっているのはいつですか。',
        choices: ['On Saturdays', 'On Mondays', 'In the morning', 'For three weeks'],
        correctIndex: 1,
        explanation: '第1段落に It is closed on Mondays. とあります。',
        choiceNotes: ['土曜の午後には読み聞かせがあるので、開いています。', null, '朝9時に開きます。', '3週間は本を借りられる期間です。'],
      },
      {
        id: 'r-a2-01-q2',
        prompt: '2階では何が行われますか。',
        choices: ['Tools are repaired.', 'Newspapers are sold.', 'Stories are read to children.', 'Books are printed.'],
        correctIndex: 2,
        explanation: '第2段落に、2階でスタッフが毎週土曜の午後に物語を読み聞かせるとあります。',
        choiceNotes: ['道具は貸し出されますが、修理の記述はありません。', '新聞は1階にありますが、売っているとは書かれていません。', null, '印刷についての記述はありません。'],
      },
      {
        id: 'r-a2-01-q3',
        prompt: '本を返すのが遅れると何が起きますか。',
        choices: ['You pay money.', 'You cannot borrow for a week.', 'You lose your card.', 'Nothing happens.'],
        correctIndex: 1,
        explanation: '第3段落に、お金はかからないが1週間は新しく借りられないとあります。',
        choiceNotes: ['you do not pay money と明確に否定されています。', null, 'カードについての記述はありません。', '1週間借りられないという結果があります。'],
      },
      {
        id: 'r-a2-01-q4',
        prompt: '道具の貸し出しについて正しいものはどれですか。',
        choices: ['It started this year.', 'It is only for staff.', 'The tools are free to keep.', 'You can keep a tool for two days.'],
        correctIndex: 3,
        explanation: '第4段落に for two days とあります。',
        choiceNotes: ['3年前に始まりました。', '利用者向けのサービスです。', '貸し出しであって譲渡ではありません。', null],
      },
      {
        id: 'r-a2-01-q5',
        prompt: 'この文章の目的として最も適切なものはどれですか。',
        choices: ['図書館の利用方法を伝えること', '読書の効果を主張すること', '図書館の歴史を語ること', '本の書評を述べること'],
        correctIndex: 0,
        explanation: '開館時間・貸出冊数・延長・道具貸出など、利用に必要な情報が並んでいます。',
        choiceNotes: [null, '効果についての主張はありません。', '道具貸出の開始年に触れるだけで、歴史の記述ではありません。', '特定の本を評価してはいません。'],
      },
    ],
  },
  {
    id: 'r-a2-02',
    level: 'A2',
    title: 'Riding to Work',
    titleJa: '自転車で通勤する',
    minutes: 12,
    canDo: ['R-A2-1', 'R-B1-2'],
    paragraphs: [
      'Kenji works at a hospital in the center of the city. For six years, he took the train to work. The train was fast, but it was always crowded, and he often had to stand for forty minutes.',
      'Last spring, he bought a used bicycle from a neighbor. At first, he only rode it on Sundays. Then one morning the trains stopped because of heavy rain, and he rode to the hospital instead. It took fifty minutes, but he arrived on time.',
      'Now he rides almost every day. He leaves home earlier than before, and he arrives feeling awake. He says the ride costs nothing, and he no longer goes to the gym in the evening.',
      'There are problems, of course. In winter the road is dark, and in summer he needs a shower before work. His hospital has a locker room, so this is not difficult. When the weather is very bad, he still takes the train.',
    ],
    paragraphsJa: [
      'ケンジは市の中心にある病院で働いています。6年間、電車で通勤していました。電車は速いのですが、いつも混んでいて、40分間立っていなければならないこともよくありました。',
      '昨年の春、彼は近所の人から中古の自転車を買いました。最初は日曜日に乗るだけでした。ところがある朝、大雨で電車が止まり、代わりに自転車で病院へ向かいました。50分かかりましたが、遅刻せずに着きました。',
      '今ではほぼ毎日自転車で通っています。以前より早く家を出ますが、頭がすっきりした状態で到着します。費用はかからず、夜にジムへ行くこともなくなったと言います。',
      'もちろん問題もあります。冬は道が暗く、夏は仕事前にシャワーが必要です。病院には更衣室があるので、これは困りません。天気がとても悪いときは、今でも電車を使います。',
    ],
    glossary: [
      { word: 'crowded', ja: '混雑した' },
      { word: 'used', ja: '中古の' },
      { word: 'instead', ja: '代わりに' },
      { word: 'on time', ja: '時間どおりに' },
      { word: 'awake', ja: '目が覚めた、意識がはっきりした' },
      { word: 'locker room', ja: '更衣室' },
    ],
    questions: [
      {
        id: 'r-a2-02-q1',
        prompt: 'ケンジが自転車で通勤し始めたきっかけは何ですか。',
        choices: ['彼は自転車が好きだったから', '大雨で電車が止まったから', 'ジムをやめたかったから', '病院が引っ越したから'],
        correctIndex: 1,
        explanation: '第2段落に、大雨で電車が止まったので代わりに自転車で行ったとあります。',
        choiceNotes: ['最初は日曜に乗るだけでした。', null, 'ジムに行かなくなったのは結果です。', '引っ越しの記述はありません。'],
      },
      {
        id: 'r-a2-02-q2',
        prompt: '自転車と電車の所要時間を比べると、どうですか。',
        choices: ['自転車のほうが10分長い', '同じくらい', '自転車のほうが速い', '本文に記述がない'],
        correctIndex: 0,
        explanation: '電車では40分立っていた、自転車では50分かかったとあるので、10分長くなります。',
        choiceNotes: [null, '10分の差があります。', '電車のほうが速いと書かれています。', '両方の時間が示されています。'],
      },
      {
        id: 'r-a2-02-q3',
        prompt: '本文によると、彼が夜にジムへ行かなくなったのはなぜですか。',
        choices: ['ジムが閉まったから', '料金が高いから', '自転車で運動しているから', '時間が足りないから'],
        correctIndex: 2,
        explanation: '通勤そのものが運動になったため、ジムに行かなくなったという流れです。',
        choiceNotes: ['閉店の記述はありません。', '費用は自転車のほうの話です。', null, '時間についての言及はありません。'],
      },
      {
        id: 'r-a2-02-q4',
        prompt: '天気がとても悪い日、彼はどうしますか。',
        choices: ['歩いて行く', '仕事を休む', '自転車で行く', '電車に乗る'],
        correctIndex: 3,
        explanation: '最終文に he still takes the train とあります。',
        choiceNotes: ['徒歩の記述はありません。', '休むとは書かれていません。', '悪天候のときは自転車を使いません。', null],
      },
      {
        id: 'r-a2-02-q5',
        prompt: '筆者はケンジの自転車通勤をどのように描いていますか。',
        choices: ['問題も認めたうえで、利点が多いものとして', '危険で勧められないものとして', '一時的な流行として', '費用がかさむものとして'],
        correctIndex: 0,
        explanation: '第4段落で問題点を挙げつつ、解決できることを示し、全体としては肯定的です。',
        choiceNotes: [null, '危険だという記述はありません。', '今ではほぼ毎日続けています。', '費用はかからないと述べています。'],
      },
    ],
  },
  {
    id: 'r-b1-01',
    level: 'B1',
    title: 'Why Cities Are Planting Trees Again',
    titleJa: '都市が再び木を植える理由',
    minutes: 12,
    canDo: ['R-B1-1', 'R-B2-1'],
    paragraphs: [
      'For most of the last century, city planners treated trees as decoration. Roads were widened, parking spaces were added, and the trees that stood in the way were removed. Today, many of the same cities are spending large sums to put them back.',
      'The main reason is heat. Dark surfaces such as asphalt and concrete absorb sunlight during the day and release it slowly at night, so a city can stay several degrees warmer than the countryside around it. A street lined with mature trees can be noticeably cooler at midday, and the shade reduces the need for air conditioning in nearby buildings.',
      'Water is another reason. When heavy rain falls on hard surfaces, it runs straight into drains, which can overflow within minutes. Soil and roots hold part of that water and release it slowly, so the pressure on the drainage system is lower.',
      'Trees are not a complete solution, and planting them is easier than keeping them alive. A young tree needs water for several summers, and city soil is often compacted and poor. Studies suggest that a large share of newly planted street trees die within a few years, usually because nobody was responsible for them after the planting event ended.',
      'For this reason, some cities now sign maintenance contracts before the first tree goes into the ground. It is less photogenic than a planting ceremony, but it is what decides whether the shade will still be there in twenty years.',
    ],
    paragraphsJa: [
      '前世紀の大半、都市計画者は樹木を装飾として扱っていました。道路は拡幅され、駐車場が増設され、邪魔になる木は撤去されました。今日、同じ都市の多くが、それを元に戻すために多額の費用を投じています。',
      '主な理由は熱です。アスファルトやコンクリートのような暗い色の表面は日中に日光を吸収し、夜にゆっくり放出するため、都市は周囲の郊外より数度高い状態が続きます。成木が並ぶ通りは正午でも明らかに涼しく、その日陰は近隣の建物の冷房需要を減らします。',
      '水も理由の一つです。硬い舗装面に大雨が降ると、水はそのまま排水溝へ流れ込み、数分で溢れることがあります。土壌と根はその一部を保持してゆっくり放出するため、排水システムへの負荷が下がります。',
      '樹木は完全な解決策ではありませんし、植えることは生かし続けることより簡単です。若木は数年の夏のあいだ水を必要としますが、都市の土壌はしばしば締め固められて痩せています。新しく植えられた街路樹のかなりの割合が数年以内に枯れるという研究があり、その原因はたいてい、植樹イベントが終わったあと誰も責任を負わなかったことです。',
      'そのため、最初の一本を植える前に維持管理の契約を結ぶ都市も出てきました。植樹式より見栄えはしませんが、20年後にその日陰が残っているかを決めるのはそちらです。',
    ],
    glossary: [
      { word: 'decoration', ja: '装飾' },
      { word: 'absorb', ja: '吸収する' },
      { word: 'mature', ja: '成熟した' },
      { word: 'drainage', ja: '排水' },
      { word: 'compacted', ja: '締め固められた' },
      { word: 'maintenance', ja: '維持管理' },
      { word: 'photogenic', ja: '写真映えする' },
    ],
    questions: [
      {
        id: 'r-b1-01-q1',
        prompt: 'この文章の主旨として最も適切なものはどれですか。',
        choices: [
          '都市の樹木には実用的な効果があるが、維持こそが課題である',
          '都市計画者は過去の判断を謝罪すべきである',
          '樹木は冷房よりも効果的である',
          '植樹式は無意味である',
        ],
        correctIndex: 0,
        explanation: '前半で効果(熱・水)を挙げ、後半で維持管理の難しさと契約の必要性に議論が移ります。',
        choiceNotes: [null, '謝罪については述べていません。', '冷房需要を減らすとは述べていますが、比較はしていません。', '見栄えはしないと述べただけで、無意味とは言っていません。'],
      },
      {
        id: 'r-b1-01-q2',
        prompt: '都市が周囲より暖かくなる理由として本文が挙げているのは何ですか。',
        choices: ['車の排気熱', '暗い色の舗装面が熱を吸収し夜に放出すること', '建物が高いこと', '人口が多いこと'],
        correctIndex: 1,
        explanation: '第2段落に、暗い表面が日中に吸収し夜間に放出すると説明されています。',
        choiceNotes: ['排気については触れていません。', null, '建物の高さは述べられていません。', '人口には言及がありません。'],
      },
      {
        id: 'r-b1-01-q3',
        prompt: '樹木が排水に役立つのはなぜですか。',
        choices: ['雨を蒸発させるから', '排水溝を広げるから', '土と根が水を保持して徐々に放出するから', '雨量そのものを減らすから'],
        correctIndex: 2,
        explanation: '第3段落の Soil and roots hold part of that water and release it slowly が該当します。',
        choiceNotes: ['蒸発の記述はありません。', '排水溝を広げるとは書かれていません。', null, '降水量は変わりません。'],
      },
      {
        id: 'r-b1-01-q4',
        prompt: '新しく植えられた街路樹が枯れる主な原因として述べられているのは何ですか。',
        choices: ['病気', '植樹後に責任者がいないこと', '寒さ', '樹種の選択の誤り'],
        correctIndex: 1,
        explanation: 'usually because nobody was responsible for them after the planting event ended とあります。',
        choiceNotes: ['病気の記述はありません。', null, '寒さではなく夏の水やりが問題です。', '樹種には触れていません。'],
      },
      {
        id: 'r-b1-01-q5',
        prompt: '最終段落の It is less photogenic than a planting ceremony が指しているのは何ですか。',
        choices: ['樹木の成長', '維持管理契約を結ぶこと', '道路の拡幅', '研究の発表'],
        correctIndex: 1,
        explanation: '直前の sign maintenance contracts を指しています。写真映えしないが決定的だ、という対比です。',
        choiceNotes: ['成長そのものの話ではありません。', null, '拡幅は第1段落の話題です。', '研究発表は指示対象ではありません。'],
      },
    ],
  },
  {
    id: 'r-b1-02',
    level: 'B1',
    title: 'The Night Shift',
    titleJa: '夜勤',
    minutes: 12,
    canDo: ['R-B1-2', 'R-B2-2'],
    paragraphs: [
      'When I took the night shift at the bakery, I thought the hardest part would be waking up. It was not. The hardest part was that the rest of the world kept its own schedule, and mine no longer matched it.',
      'My work began at eleven at night and finished at seven in the morning. For the first month I slept badly. I would come home, close the curtains, and lie awake listening to children walking to school. By the third week I had learned to sleep with earplugs, but I still woke up whenever the post arrived.',
      'What surprised me was how the work itself changed my sense of time. In the bakery, the night is divided by what is in the oven, not by the clock. Once the first bread goes in, everything else follows, and five hours can pass without my noticing.',
      'I also began to notice the people who share those hours. Nurses coming off duty, drivers waiting for the first delivery, a man who walked his dog at four every morning because he could not sleep either. We rarely spoke, but there was a kind of agreement between us.',
      'I left the bakery after two years, and I sleep at night again now. I do not miss the exhaustion. What I miss, and this still surprises me, is the quiet certainty of that world, where nothing was expected of me except that the bread should be ready by six.',
    ],
    paragraphsJa: [
      'パン屋の夜勤に就いたとき、いちばん大変なのは起きることだろうと思っていました。違いました。いちばん大変だったのは、世界のほうは自分の時間割で動いていて、私のそれがもう噛み合わなくなったことでした。',
      '仕事は夜11時に始まり、朝7時に終わりました。最初の1か月はよく眠れませんでした。帰宅してカーテンを閉め、登校する子どもたちの足音を聞きながら横になっていました。3週目には耳栓をして眠れるようになりましたが、郵便が届くとやはり目が覚めました。',
      '驚いたのは、仕事そのものが時間の感覚を変えたことです。パン屋では、夜は時計ではなくオーブンの中身で区切られます。最初のパンを入れてしまえば、あとは次々に続き、気づかないうちに5時間が過ぎていきます。',
      'その時間を共有している人たちにも気づくようになりました。勤務明けの看護師、最初の配達を待つ運転手、眠れないからと毎朝4時に犬を散歩させる男性。ほとんど言葉は交わしませんでしたが、私たちの間には一種の了解がありました。',
      '2年後にパン屋を辞め、今はまた夜に眠っています。あの疲労が恋しいわけではありません。恋しいのは——自分でも意外なのですが——6時までにパンができていればそれ以外は何も求められない、あの世界の静かな確かさです。',
    ],
    glossary: [
      { word: 'shift', ja: '勤務時間帯、シフト' },
      { word: 'match', ja: '合致する' },
      { word: 'earplugs', ja: '耳栓' },
      { word: 'come off duty', ja: '勤務を終える' },
      { word: 'exhaustion', ja: '極度の疲労' },
      { word: 'certainty', ja: '確かさ' },
    ],
    questions: [
      {
        id: 'r-b1-02-q1',
        prompt: '筆者にとって夜勤の最も難しかった点は何でしたか。',
        choices: ['早起きすること', '仕事量が多いこと', '世界と生活時間がずれること', 'パンを焼く技術'],
        correctIndex: 2,
        explanation: '第1段落で「起きることではなく、世界の時間割と噛み合わなくなったこと」と明示されています。',
        choiceNotes: ['It was not. と否定されています。', '仕事量への言及はありません。', null, '技術の難しさは述べていません。'],
      },
      {
        id: 'r-b1-02-q2',
        prompt: '第2段落から分かることはどれですか。',
        choices: ['筆者はすぐに睡眠に慣れた', '耳栓の後も完全には眠れなかった', '子どもの声が好きだった', '昼に働くほうが疲れた'],
        correctIndex: 1,
        explanation: '耳栓で眠れるようになっても、郵便で目が覚めたとあります。',
        choiceNotes: ['最初の1か月はよく眠れませんでした。', null, '好き嫌いの記述はありません。', '比較はしていません。'],
      },
      {
        id: 'r-b1-02-q3',
        prompt: '「夜は時計ではなくオーブンの中身で区切られる」とはどういう意味ですか。',
        choices: [
          '作業の進行が時間の感覚を決めていた',
          '時計が壊れていた',
          '休憩が取れなかった',
          '夜勤には決まった手順がなかった',
        ],
        correctIndex: 0,
        explanation: '直後に「5時間が気づかぬうちに過ぎる」とあり、作業の流れが時間感覚を支配していたことを表します。',
        choiceNotes: [null, '時計の故障の話ではありません。', '休憩には触れていません。', '手順はむしろ決まっています。'],
      },
      {
        id: 'r-b1-02-q4',
        prompt: '第4段落の a kind of agreement between us が表しているのは何ですか。',
        choices: ['正式な契約', '同じ時間帯を生きる者どうしの暗黙の了解', '労働組合の取り決め', '静かにするという規則'],
        correctIndex: 1,
        explanation: 'We rarely spoke, but ... と対比されており、言葉を介さない共感を指します。',
        choiceNotes: ['契約書の話ではありません。', null, '組合には触れていません。', '規則ではありません。'],
      },
      {
        id: 'r-b1-02-q5',
        prompt: '筆者の現在の気持ちとして最も近いものはどれですか。',
        choices: ['夜勤に戻りたい', '夜勤を後悔している', '疲労は懐かしくないが、あの単純さは懐かしい', '夜勤は誰にでも勧められる'],
        correctIndex: 2,
        explanation: '最終段落で「疲労は恋しくないが、静かな確かさが恋しい」と述べています。',
        choiceNotes: ['戻りたいとは書いていません。', '後悔の表現はありません。', null, '他人への推奨はしていません。'],
      },
    ],
  },
  {
    id: 'r-b2-01',
    level: 'B2',
    title: 'Remote Work and the Cost of Distance',
    titleJa: 'リモートワークと距離のコスト',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'When large numbers of employees began working from home, the early predictions were confident and, in most cases, wrong. Offices were said to be finished. City centers were said to be emptying for good. Several years on, the picture is more complicated, and the interesting question is no longer whether remote work survives, but what it quietly costs.',
      'The benefits are easy to measure, which is part of the problem. A commute that disappears can be counted in hours and in fares. Companies that give up floor space can report the saving in the next set of accounts. Employees who move further from the office can point to lower rent. Numbers of this kind travel well in meetings.',
      'The costs are harder to see because they arrive late and are spread thinly. Junior staff learn a great deal by accident: from half-heard conversations, from watching how a difficult client is handled, from the correction that would never have been written down. Remove the room, and that learning has to be arranged deliberately, which means somebody must notice it is missing in the first place.',
      'There is a second cost, which falls on the people who are not in the room. Where some employees are present and others are not, decisions tend to drift towards those who happen to be nearby. Firms that take this seriously usually respond by making the meeting itself remote for everyone, even when half the participants are in the same building. This feels absurd, and it works.',
      'None of this argues for a return to the old arrangement. It argues instead for honesty about what an office was actually doing. Much of it was never in anyone job description, and that is exactly why it disappeared without being noticed.',
    ],
    paragraphsJa: [
      '多くの従業員が在宅で働き始めたとき、初期の予測は自信に満ちていて、たいていは外れました。オフィスは終わったと言われました。都心は永久に空になると言われました。数年を経て、状況はもっと複雑で、興味深い問いは「リモートワークが生き残るか」ではなく「それが静かに何を犠牲にしているか」に移っています。',
      '利点は測りやすく、それ自体が問題の一部です。なくなった通勤は時間と運賃で数えられます。床面積を手放した企業は、次の決算で節約額を報告できます。オフィスから遠くへ引っ越した従業員は、家賃の低下を示せます。この種の数字は会議でよく通ります。',
      'コストのほうは見えにくい。遅れてやってきて、薄く広がるからです。若手は偶然から多くを学びます。断片的に聞こえてくる会話から、難しい顧客への対応の仕方を見ることから、決して文書には残らなかったであろう訂正から。部屋をなくせば、その学習は意図的に設計しなければならず、それにはまず誰かが「欠けている」と気づく必要があります。',
      'もう一つのコストは、その場にいない人たちに降りかかります。一部が出社し一部がそうでない状況では、意思決定は近くにいる人のほうへ流れがちです。これを真剣に受け止める企業はたいてい、参加者の半分が同じ建物にいても会議自体を全員リモートにするという対応を取ります。ばかげて感じられますが、機能します。',
      'これらは以前の体制へ戻れという議論ではありません。オフィスが実際に何をしていたのかについて正直であれ、という議論です。その多くは誰の職務記述書にも書かれていませんでした。だからこそ、気づかれないまま消えたのです。',
    ],
    glossary: [
      { word: 'prediction', ja: '予測' },
      { word: 'for good', ja: '永久に' },
      { word: 'floor space', ja: '床面積、オフィス面積' },
      { word: 'spread thinly', ja: '薄く広がる' },
      { word: 'deliberately', ja: '意図的に' },
      { word: 'drift towards', ja: '〜のほうへ流れる' },
      { word: 'job description', ja: '職務記述書' },
    ],
    questions: [
      {
        id: 'r-b2-01-q1',
        prompt: '筆者の主張として最も適切なものはどれですか。',
        choices: [
          'リモートワークは失敗であり、出社に戻すべきだ',
          'リモートワークの見えにくい代償を認識し、意図的に補うべきだ',
          'オフィスのコスト削減効果は誇張されている',
          '若手の育成は企業の責任ではない',
        ],
        correctIndex: 1,
        explanation: '最終段落で「以前の体制に戻れという議論ではない」と明示し、オフィスの機能への正直さを求めています。',
        choiceNotes: ['None of this argues for a return と否定されています。', null, '削減効果自体は否定していません。', '逆に、意図的な設計が必要だと述べています。'],
      },
      {
        id: 'r-b2-01-q2',
        prompt: '第2段落の Numbers of this kind travel well in meetings. が含意しているのは何ですか。',
        choices: [
          '測りやすい利点ほど組織の判断で重視されやすい',
          '会議では数字を使うべきではない',
          '通勤時間は正確に測れない',
          '会計報告は信頼できない',
        ],
        correctIndex: 0,
        explanation: '「利点は測りやすく、それが問題の一部」という流れを受け、可視的な数字が議論を支配することを示しています。',
        choiceNotes: [null, '使うなとは述べていません。', '時間と運賃で数えられると述べています。', '会計の信頼性は論点ではありません。'],
      },
      {
        id: 'r-b2-01-q3',
        prompt: '第3段落で述べられている若手の学習の特徴はどれですか。',
        choices: ['研修によって計画的に得られる', '文書化された手順から得られる', '偶発的で、記録に残らない', '顧客からの評価で測られる'],
        correctIndex: 2,
        explanation: 'by accident、would never have been written down という表現が該当します。',
        choiceNotes: ['むしろ計画外です。', '文書には残らないと述べています。', null, '評価の話は出てきません。'],
      },
      {
        id: 'r-b2-01-q4',
        prompt: '全員をリモート参加にする対応について、筆者はどう評価していますか。',
        choices: ['無駄である', '違和感はあるが有効である', '法的に必要である', '一時的な流行である'],
        correctIndex: 1,
        explanation: 'This feels absurd, and it works. と、違和感と有効性を並置しています。',
        choiceNotes: ['it works と述べています。', null, '法的な議論はありません。', '流行としては扱っていません。'],
      },
      {
        id: 'r-b2-01-q5',
        prompt: '筆者の論の進め方として最も適切な説明はどれですか。',
        choices: [
          '一般的な予測を否定したうえで、可視的な利点と不可視のコストを対比している',
          '統計を列挙して結論を導いている',
          '個人の体験を中心に据えている',
          '二つの企業の事例を比較している',
        ],
        correctIndex: 0,
        explanation: '第1段落で初期予測を退け、第2段落(利点)と第3・4段落(コスト)を対比する構成です。',
        choiceNotes: [null, '具体的な統計は示されていません。', '個人の体験談ではありません。', '特定企業の比較はありません。'],
      },
    ],
  },
  {
    id: 'r-b2-02',
    level: 'B2',
    title: 'The Repair Cafe',
    titleJa: 'リペアカフェ',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'On the first Saturday of each month, a community hall near the station fills with broken objects. Toasters, lamps, bicycles, a sewing machine that has not run since the owner inherited it. Volunteers with tools sit at long tables, and anyone may bring one item and stay while it is examined. Nothing is left behind to be collected later, and this rule matters more than it appears to.',
      'The organizers are careful about how they describe what they do. They are not, they insist, a free repair service. Visitors are expected to sit beside the volunteer, hold the torch, and be told what is being done and why. A quarter of the items are not repaired at all, and the volunteer is expected to explain that outcome as clearly as a successful one.',
      'Critics argue that projects of this kind are sentimental. The volume of waste diverted from landfill is small, they say, and the hours involved would be better spent campaigning for laws that require manufacturers to make products repairable in the first place. The argument is not unreasonable, and the organizers do not dispute the numbers.',
      'What the numbers miss, however, is what happens to a person who watches a device being opened. Objects that were sealed and mysterious become things with screws, and a certain resignation loses its grip. Several volunteers first came as visitors with a broken kettle and no relevant skill whatsoever.',
      'Whether that shift can be scaled into policy is genuinely unclear. It would be dishonest to claim that a monthly gathering in a community hall will change manufacturing. It would be equally dishonest to measure it only in kilograms.',
    ],
    paragraphsJa: [
      '毎月第1土曜日、駅の近くの公民館が壊れた物でいっぱいになります。トースター、ランプ、自転車、持ち主が相続してから一度も動いていないミシン。工具を持ったボランティアが長机に座り、誰でも1点持ち込んで、それが調べられる間その場にいられます。あとで引き取る形で置いていくことはできません。この規則は、見た目以上に重要です。',
      '主催者は自分たちの活動の説明の仕方に慎重です。私たちは無料の修理サービスではない、と彼らは強調します。来訪者はボランティアの隣に座り、ライトを持ち、何をなぜしているのかの説明を受けることが求められます。持ち込まれた物の4分の1はまったく直りませんが、ボランティアはその結果も成功と同じくらい明確に説明することを求められます。',
      '批判もあります。この種の取り組みは感傷的だ、埋め立てから逸らされる廃棄物の量はわずかで、その時間はむしろ、製品を修理可能に作ることをメーカーに義務づける法律を求める運動に使うべきだ、というのです。この主張は不合理ではなく、主催者も数字そのものは否定しません。',
      'しかし数字が捉えそこねているのは、機器が開けられるのを見た人に起きることです。密閉されて不可解だった物が、ねじのある物になり、ある種のあきらめが力を失います。何人かのボランティアは、壊れたやかんを持ち、関連する技能を何ひとつ持たない来訪者として最初にやってきた人たちです。',
      'その変化を政策の規模にまで拡大できるかは、正直なところ分かりません。公民館の月一回の集まりが製造業を変えると主張するのは不誠実でしょう。しかし、それをキログラムでだけ測るのも、同じくらい不誠実です。',
    ],
    glossary: [
      { word: 'inherit', ja: '相続する' },
      { word: 'insist', ja: '強く主張する' },
      { word: 'outcome', ja: '結果' },
      { word: 'divert', ja: '(別の方向へ)逸らす' },
      { word: 'landfill', ja: '埋め立て地' },
      { word: 'resignation', ja: 'あきらめ' },
      { word: 'scale', ja: '規模を拡大する' },
    ],
    questions: [
      {
        id: 'r-b2-02-q1',
        prompt: '「置いていくことはできない」という規則が重要なのはなぜですか。',
        choices: [
          '保管場所がないから',
          '来訪者が修理の過程を見て学ぶことが目的だから',
          '盗難を防ぐため',
          '責任の所在を明確にするため',
        ],
        correctIndex: 1,
        explanation: '第2段落で、隣に座り説明を受けることが求められると述べられており、規則はその目的に沿っています。',
        choiceNotes: ['保管の都合には触れていません。', null, '盗難の記述はありません。', '責任問題は論じられていません。'],
      },
      {
        id: 'r-b2-02-q2',
        prompt: '批判者の主張として本文に挙げられているのはどれですか。',
        choices: [
          'ボランティアの技術が不足している',
          '参加費が高すぎる',
          '削減される廃棄物量が小さく、法制度を求める運動のほうが有効だ',
          '修理が失敗することが多すぎる',
        ],
        correctIndex: 2,
        explanation: '第3段落にそのまま述べられています。',
        choiceNotes: ['技術批判は出てきません。', '費用の話はありません。', null, '4分の1が直らないのは主催者側の説明です。'],
      },
      {
        id: 'r-b2-02-q3',
        prompt: '筆者は批判者の主張をどのように扱っていますか。',
        choices: ['一方的に退けている', '無視している', '一定の妥当性を認めたうえで、別の観点を示している', '全面的に同意している'],
        correctIndex: 2,
        explanation: 'The argument is not unreasonable と認めたうえで、What the numbers miss と続けています。',
        choiceNotes: ['退けてはいません。', '正面から扱っています。', null, '全面同意なら第4段落は不要です。'],
      },
      {
        id: 'r-b2-02-q4',
        prompt: '第4段落の a certain resignation loses its grip が意味しているのは何ですか。',
        choices: [
          '「どうせ直らない」という思い込みが弱まる',
          'ボランティアが辞めていく',
          '道具の握りが緩む',
          '批判が説得力を失う',
        ],
        correctIndex: 0,
        explanation: '密閉された不可解な物が「ねじのある物」になる、という文脈からの比喩表現です。',
        choiceNotes: [null, 'resignation は辞職ではなくあきらめの意味で使われています。', '物理的な握りの話ではありません。', '批判については第3段落で扱われています。'],
      },
      {
        id: 'r-b2-02-q5',
        prompt: '最終段落から読み取れる筆者の立場はどれですか。',
        choices: [
          '効果は限定的だが、評価の物差しを一つに絞るべきではない',
          '政策への拡大は確実である',
          '数値評価こそが唯一の基準である',
          '製造業の変革は不要である',
        ],
        correctIndex: 0,
        explanation: '「製造業を変えると主張するのは不誠実」「キログラムでだけ測るのも同じく不誠実」という二重の留保が要点です。',
        choiceNotes: [null, 'genuinely unclear と述べています。', 'それを不誠実だとしています。', '法制度の必要性は否定していません。'],
      },
    ],
  },
]
