import type { ReadingPassage } from '../types.ts'

// B2 追加分(r-b2-07 〜 r-b2-18)。本プロジェクト用に書き下ろした自作テキスト(外部からの転載なし)。
// 数字は表記ゆれと音声化のぶれを避けるため綴りで書き、所有格のアポストロフィは避ける。
// B2 の設問は事実の検索だけでなく、論の運び・筆者の立場・含意を問う。

export const b2PassagesB: ReadingPassage[] = [
  {
    id: 'r-b2-07',
    level: 'B2',
    title: 'The Cost of a Street Tree',
    titleJa: '街路樹の値段',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'When a city plants a tree beside a road, the cost lands in the accounts within a single year. The benefits, if they are counted at all, arrive slowly across the following three decades. That mismatch explains a great deal about why our streets look the way they do.',
      'The benefits are not imaginary. A mature tree lowers the temperature of the ground beneath it by several degrees on a hot afternoon. Its roots hold back rain that would otherwise reach the drains all at once. Houses on streets with trees sell for more, which suggests that buyers value something they are rarely asked to describe.',
      'The costs are not imaginary either. Roots lift the stones of the path and injure people who trip on them. Branches come down in storms. Leaves block the drains in autumn, and the crew that clears them is paid from the same budget that planted the tree. Every one of these costs has a date, a bill and a department that must answer for it.',
      'Set the two lists side by side and the imbalance is obvious. The costs are precise, immediate and attached to someone. The benefits are spread thin, delayed and attached to nobody in particular. A finance officer who cannot measure the second list is not being unreasonable in ignoring it, but the decision that follows is still the wrong one.',
      'Cities already know how to solve this problem elsewhere. A bridge is not judged by what it costs in its first year, because everyone accepts that it will stand for a century. Trees receive no such treatment, and the reason is not that they last a shorter time. It is that nobody has yet decided that a tree counts as public equipment.',
    ],
    paragraphsJa: [
      '市が道路脇に木を1本植えると、その費用は同じ年の会計に計上されます。便益のほうは、そもそも数えられるとしても、その後30年かけてゆっくり現れます。このずれが、私たちの街路が今のような姿である理由の多くを説明します。',
      '便益は空想ではありません。育った木は、暑い午後に足元の地面の温度を数度下げます。その根は、放っておけば一度に排水口へ流れ込む雨水を受け止めます。木のある通りの家はより高く売れます。これは、買い手が、言葉にするよう求められることのめったにない何かを評価していることを示しています。',
      '費用のほうも空想ではありません。根は歩道の敷石を持ち上げ、つまずいた人にけがをさせます。枝は嵐で落ちます。秋には落ち葉が排水口を塞ぎ、それを片付ける作業班の人件費は、その木を植えたのと同じ予算から出ます。これらの費用にはどれも、日付と請求書と、責任を負う部署があります。',
      '二つのリストを並べれば、不均衡は明らかです。費用は正確で、即時で、誰かに紐づいています。便益は薄く広がり、遅れてやってきて、特定の誰にも紐づきません。二つ目のリストを測れない財務担当者が、それを無視するのは不合理ではありません。しかしそれに続く判断は、やはり誤りです。',
      '都市はこの問題を、ほかの場面ではすでに解決できています。橋は初年度の費用で評価されません。100年もつと誰もが受け入れているからです。木にはそうした扱いが与えられません。その理由は、木のほうが寿命が短いからではありません。木を公共設備として数える、と誰もまだ決めていないからです。',
    ],
    glossary: [
      { word: 'mismatch', ja: 'ずれ、食い違い' },
      { word: 'mature', ja: '十分に育った' },
      { word: 'drain', ja: '排水口' },
      { word: 'crew', ja: '作業班' },
      { word: 'imbalance', ja: '不均衡' },
      { word: 'immediate', ja: '即時の' },
      { word: 'unreasonable', ja: '不合理な' },
    ],
    questions: [
      {
        id: 'r-b2-07-q1',
        prompt: '第1段落で筆者が指摘している「ずれ」とは何ですか。',
        choices: [
          '費用は1年で計上され、便益は数十年かけて現れること',
          '木の種類によって成長速度が違うこと',
          '市と住民で意見が違うこと',
          '街路樹の数が都市ごとに違うこと',
        ],
        correctIndex: 0,
        explanation: 'the cost lands in the accounts within a single year に対し、便益は across the following three decades と述べられています。',
        choiceNotes: [null, '樹種の話は出てきません。', '住民と市の対立は論点ではありません。', '本数の比較はしていません。'],
      },
      {
        id: 'r-b2-07-q2',
        prompt: '家の価格について筆者が述べていることはどれですか。',
        choices: [
          '木のある通りの家は高く売れ、買い手は評価の理由を説明する機会がない',
          '木のある通りの家は安く売れる',
          '価格と木の有無に関係はない',
          '木のある家は買い手が見つかりにくい',
        ],
        correctIndex: 0,
        explanation: 'value something they are rarely asked to describe が、評価されているが言語化されない便益を示しています。',
        choiceNotes: [null, 'sell for more と逆です。', '関係があると述べられています。', '売れにくいとは書かれていません。'],
      },
      {
        id: 'r-b2-07-q3',
        prompt: '第3段落を置いたことで、筆者の議論はどうなっていますか。',
        choices: [
          '反対側の事実を認めることで、後の主張の説得力を上げている',
          '主張を撤回している',
          '話題を別の問題へ移している',
          '第2段落の内容を否定している',
        ],
        correctIndex: 0,
        explanation: 'The costs are not imaginary either と費用の実在を認めた上で、第4段落で会計の非対称へ論を進めています。',
        choiceNotes: [null, '主張は撤回されていません。', '同じ問題を扱い続けています。', '便益の存在は否定されていません。'],
      },
      {
        id: 'r-b2-07-q4',
        prompt: '財務担当者について筆者はどのような態度をとっていますか。',
        choices: [
          '判断の動機は理解できるが、結果としての判断は誤りだとしている',
          '完全に正しいとしている',
          '不誠実だと非難している',
          '専門知識が足りないとしている',
        ],
        correctIndex: 0,
        explanation: 'is not being unreasonable in ignoring it, but the decision that follows is still the wrong one が該当します。',
        choiceNotes: [null, 'the wrong one と明言されています。', '不誠実だとは述べていません。', '知識ではなく測定可能性の問題としています。'],
      },
      {
        id: 'r-b2-07-q5',
        prompt: '橋を持ち出した意図として最も適切なものはどれですか。',
        choices: [
          '長期の資産として扱う会計をすでに人は使えていると示すため',
          '橋のほうが木より重要だと示すため',
          '建設費の高さを強調するため',
          '木の寿命が短いことを認めるため',
        ],
        correctIndex: 0,
        explanation: '最終段落は、橋には長期評価が適用されるのに木には適用されないという扱いの差を突いています。',
        choiceNotes: [null, '重要性の比較はしていません。', '費用の大小は論点ではありません。', 'the reason is not that they last a shorter time と否定しています。'],
      },
    ],
  },
  {
    id: 'r-b2-08',
    level: 'B2',
    title: 'The Argument About Light',
    titleJa: '光をめぐる議論',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'For most of human history the dark was a problem to be solved. Street lighting was one of the great public health achievements of the nineteenth century, and the case for it seemed so obvious that almost nobody troubled to write it down.',
      'That case is being rewritten. Insects that find their way by the moon circle a lamp until they fall. Birds that travel at night are pulled off course by lit towers. Sleep in the brightest neighbourhoods is worse than sleep elsewhere, even behind closed curtains, and the effect is largest for the people least able to move house.',
      'Against this stands an argument that is hard to answer honestly. The people who ask for less light are usually not the people who walk home alone at midnight. Whatever the studies say, a dark street feels dangerous, and a public authority that ignores how a street feels will not stay in office long.',
      'The useful move is to notice that the two sides are arguing about the wrong quantity. The research linking the amount of light to the amount of crime is far weaker than either side likes to admit. What does show up clearly is that direction and timing matter. A covered lamp aimed at the ground lights the path without lighting the sky, and a street can be bright at eleven and much darker at three.',
      'Framed as brightness against darkness, the question has no answer that anyone will accept. Framed as control, it turns into an ordinary engineering problem with ordinary engineering answers. It is worth asking why the first framing survived for so long, and who was served by it.',
    ],
    paragraphsJa: [
      '人類史の大半において、暗さは解決すべき問題でした。街路照明は19世紀の公衆衛生上の大きな成果のひとつであり、その正当性はあまりに明白に思われたため、書き留めようとする人はほとんどいませんでした。',
      'その正当性は今、書き直されつつあります。月を頼りに進む昆虫は、ランプの周りを回り続けて落ちます。夜に移動する鳥は、光を放つ塔に進路を狂わされます。最も明るい地域の睡眠は、カーテンを閉めていても他所より質が悪く、その影響は引っ越す余裕の最も少ない人々に最も大きく出ます。',
      'これに対して、正直に答えるのが難しい反論があります。光を減らせと求める人は、たいてい真夜中に一人で歩いて帰る人ではありません。研究が何を言おうと、暗い通りは危険に感じられます。そして通りがどう感じられるかを無視する行政は、長くその職にとどまれません。',
      '有効な一手は、両者が誤った量について争っていると気づくことです。光の量と犯罪の量を結びつける研究は、どちらの側が認めたがるよりもはるかに弱いものです。はっきり示されているのは、向きと時間帯が効くということです。地面に向けた覆い付きのランプは、空を照らさずに道を照らします。通りは11時には明るく、3時にはずっと暗くできます。',
      '明るさ対暗さという枠組みでは、この問いに誰もが受け入れる答えはありません。制御の問題という枠組みにすれば、ありふれた工学の問題になり、ありふれた工学の答えが出てきます。なぜ最初の枠組みがこれほど長く生き延びたのか、そしてそれで誰が得をしたのかは、問う価値があります。',
    ],
    glossary: [
      { word: 'achievement', ja: '成果' },
      { word: 'off course', ja: '進路を外れて' },
      { word: 'curtain', ja: 'カーテン' },
      { word: 'authority', ja: '当局、行政' },
      { word: 'quantity', ja: '量' },
      { word: 'frame', ja: '枠組みで捉える' },
      { word: 'engineering', ja: '工学' },
    ],
    questions: [
      {
        id: 'r-b2-08-q1',
        prompt: '睡眠への影響について筆者が付け加えている点はどれですか。',
        choices: [
          '影響は引っ越す余裕の少ない人ほど大きい',
          'カーテンを閉めれば影響は消える',
          '若い人にだけ影響がある',
          '影響は測定されていない',
        ],
        correctIndex: 0,
        explanation: 'the effect is largest for the people least able to move house が該当します。',
        choiceNotes: [null, 'even behind closed curtains と否定されています。', '年齢による差には触れていません。', '測定結果として述べられています。'],
      },
      {
        id: 'r-b2-08-q2',
        prompt: '第3段落の反論を筆者はどのように扱っていますか。',
        choices: [
          '答えにくい正当な反論として受け止めている',
          '感情的で無視してよいとしている',
          '事実誤認だと退けている',
          '第2段落の内容を撤回する根拠としている',
        ],
        correctIndex: 0,
        explanation: 'an argument that is hard to answer honestly と述べ、体感の重みを認めています。',
        choiceNotes: [null, '無視してよいとはしていません。', '誤りだとは述べていません。', '第2段落は撤回されていません。'],
      },
      {
        id: 'r-b2-08-q3',
        prompt: '光の量と犯罪の関係について、筆者はどう述べていますか。',
        choices: [
          '研究は双方が認めたがるよりも弱い',
          '明るいほど犯罪が減ることが証明されている',
          '明るいほど犯罪が増えることが証明されている',
          '研究はまったく行われていない',
        ],
        correctIndex: 0,
        explanation: 'far weaker than either side likes to admit が根拠です。どちらの立場にも有利な結論を出していません。',
        choiceNotes: [null, '証明されているとは述べていません。', '逆の証明も述べていません。', '研究の存在自体は前提とされています。'],
      },
      {
        id: 'r-b2-08-q4',
        prompt: '筆者が提案する解決の方向はどれですか。',
        choices: [
          '光の向きと時間帯を制御する',
          '街路照明をすべて撤去する',
          '照明をさらに明るくする',
          '住民投票で決める',
        ],
        correctIndex: 0,
        explanation: 'direction and timing matter と、覆い付きランプと深夜の減光の例が挙げられています。',
        choiceNotes: [null, '撤去は提案されていません。', '増光も提案されていません。', '決め方の手続きは論じられていません。'],
      },
      {
        id: 'r-b2-08-q5',
        prompt: '最終段落の最後の一文には、どのような含みがありますか。',
        choices: [
          '明るさ対暗さという対立の構図が、誰かの利益になっていた可能性',
          '工学者の責任が重いということ',
          '歴史研究が不足しているということ',
          '議論はもう終わったということ',
        ],
        correctIndex: 0,
        explanation: 'who was served by it は、その枠組みで利益を得た者がいたという含みを持たせた問いかけです。',
        choiceNotes: [null, '工学者の責任は問われていません。', '歴史研究の量は話題ではありません。', '問う価値があると述べ、議論を開いています。'],
      },
    ],
  },
  {
    id: 'r-b2-09',
    level: 'B2',
    title: 'What the Date on the Package Means',
    titleJa: '包装の日付が意味するもの',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'The date printed on a package of food reads like an instruction. Most shoppers treat it as one. In fact the majority of these dates are not instructions at all, and the difference between the two kinds is almost never explained on the package itself.',
      'One kind marks safety. After that day the maker will not promise that the food is safe, and with fresh meat or ready meals this is a real deadline. The other kind marks quality. It says that the biscuit will still taste as the maker intended, and nothing more. Dried pasta, tinned beans and sugar carry such a date, and they are safe long after it.',
      'The result is easy to observe in any kitchen. Households throw away food that is perfectly good, because the only signal they have been given is a number, and a number that has passed looks like a rule that has been broken. Shops move stock forward, and what does not sell in time leaves through the back door.',
      'Makers did not invent these dates in order to waste food. A firm that prints a cautious date protects itself against a small number of very expensive complaints, and no manager has ever been blamed for a date that was too early. The behaviour is rational at the level of the single firm and wasteful at the level of the whole system.',
      'This is what makes the problem interesting rather than merely annoying. Nobody in the chain is acting badly, and the outcome is bad anyway. When a system produces that pattern, telling shoppers to try harder is not a solution. Changing what the package is allowed to say is.',
    ],
    paragraphsJa: [
      '食品の包装に印字された日付は、指示のように読めます。買い物客の多くはそれを指示として扱います。しかし実際には、これらの日付の大半はそもそも指示ではありません。そして二種類の違いは、包装そのものにはほとんど説明されていません。',
      '一方は安全を示します。その日を過ぎると、製造者はその食品が安全だと約束しません。生肉や調理済み食品では、これは実際の期限です。もう一方は品質を示します。それは、そのビスケットが製造者の意図した味のままであると言っているだけで、それ以上ではありません。乾麺、豆の缶詰、砂糖はこの種の日付を持ち、それを過ぎてもずっと安全です。',
      'その結果はどの家庭の台所でも観察できます。家庭はまったく問題のない食品を捨てます。与えられた唯一の合図が数字であり、過ぎた数字は破られた規則のように見えるからです。店は在庫を前に送り出し、期限内に売れなかったものは裏口から出ていきます。',
      '製造者は食品を捨てさせるためにこの日付を考案したのではありません。慎重な日付を印字する企業は、数は少ないが非常に高くつく苦情から自社を守ります。そして、日付が早すぎたことで責められた管理職はいまだかつていません。この振る舞いは一企業の水準では合理的で、システム全体の水準では無駄です。',
      'だからこそこの問題は、単に腹立たしいだけでなく興味深いのです。この連鎖の中で誰も悪意をもって動いていないのに、結果はやはり悪い。システムがこの型を生むとき、買い物客にもっと努力せよと言うことは解決になりません。包装に何を書いてよいかを変えることが解決です。',
    ],
    glossary: [
      { word: 'instruction', ja: '指示' },
      { word: 'deadline', ja: '期限' },
      { word: 'tinned', ja: '缶詰の' },
      { word: 'stock', ja: '在庫' },
      { word: 'cautious', ja: '慎重な' },
      { word: 'complaint', ja: '苦情' },
      { word: 'rational', ja: '合理的な' },
    ],
    questions: [
      {
        id: 'r-b2-09-q1',
        prompt: '二種類の日付の違いとして正しいものはどれですか。',
        choices: [
          '一方は安全の期限、もう一方は味の目安',
          '一方は国が決め、もう一方は店が決める',
          '一方は加工食品用、もう一方は生鮮食品用',
          '一方は輸入品用、もう一方は国産品用',
        ],
        correctIndex: 0,
        explanation: 'One kind marks safety と The other kind marks quality が対比されています。',
        choiceNotes: [null, '決定主体の話は出てきません。', '加工と生鮮の区分ではありません。', '輸入か国産かは論じられていません。'],
      },
      {
        id: 'r-b2-09-q2',
        prompt: '家庭が食べられる食品を捨てる理由として、筆者が挙げているのはどれですか。',
        choices: [
          '与えられた合図が数字だけで、過ぎた数字が破られた規則に見えるから',
          '食品の味が実際に落ちているから',
          '冷蔵庫が小さいから',
          '店が返品を受け付けないから',
        ],
        correctIndex: 0,
        explanation: 'a number that has passed looks like a rule that has been broken が理由として示されています。',
        choiceNotes: [null, '味の劣化は理由として挙げられていません。', '保管容量の話は出てきません。', '返品には触れていません。'],
      },
      {
        id: 'r-b2-09-q3',
        prompt: '製造者が慎重な日付を印字する理由として述べられているのはどれですか。',
        choices: [
          '高くつく苦情から自社を守るためで、早すぎる日付は責められないから',
          '法律で最短の日付が決められているから',
          '消費者からそう要望されたから',
          '印字の技術的な制約があるから',
        ],
        correctIndex: 0,
        explanation: 'protects itself against a small number of very expensive complaints と no manager has ever been blamed for a date that was too early が根拠です。',
        choiceNotes: [null, '法規制の内容には触れていません。', '消費者の要望は述べられていません。', '技術的制約の話は出てきません。'],
      },
      {
        id: 'r-b2-09-q4',
        prompt: '「一企業の水準では合理的で、システム全体の水準では無駄」という指摘の要点はどれですか。',
        choices: [
          '個々の判断が正しくても全体として悪い結果が出うる',
          '企業は常に非合理に行動する',
          '無駄は消費者の責任である',
          '大企業ほど無駄が多い',
        ],
        correctIndex: 0,
        explanation: 'rational at the level of the single firm and wasteful at the level of the whole system が、個別最適と全体最適のずれを示しています。',
        choiceNotes: [null, '合理的だと述べています。', '消費者の責任には帰していません。', '企業規模の比較はしていません。'],
      },
      {
        id: 'r-b2-09-q5',
        prompt: '筆者が結論として支持している対応はどれですか。',
        choices: [
          '包装に書ける内容の規則を変えること',
          '買い物客の意識を高めること',
          '日付の印字をやめること',
          '製造者に罰金を科すこと',
        ],
        correctIndex: 0,
        explanation: 'Changing what the package is allowed to say is. が最終文の結論です。',
        choiceNotes: [null, 'telling shoppers to try harder is not a solution と否定しています。', '印字の廃止は提案されていません。', '罰金には触れていません。'],
      },
    ],
  },
  {
    id: 'r-b2-10',
    level: 'B2',
    title: 'The Witness Who Was Certain',
    titleJa: '確信していた目撃者',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'To almost everyone sitting in a court, confidence and accuracy feel like the same thing. A witness who says that she is completely sure is believed more than one who hesitates. The connection is intuitive, and it is much weaker than it feels.',
      'Memory is not a recording that can be played again. It is built each time it is used, out of what was seen, what has been heard since, and what the person now expects to have happened. Every retelling edits the account a little, and the edits are invisible to the person doing the telling.',
      'The procedures used to identify a suspect can make this far worse. If the officer showing the photographs knows which face is the one under suspicion, small unconscious signals pass to the witness. If the faces are shown side by side, the witness compares them and picks the closest match rather than deciding whether any of them is the person seen. Once the choice is made and confirmed, confidence rises sharply, and it keeps rising for months.',
      'None of this means that witnesses are useless. It means that a statement taken carefully on the first day is worth far more than the same statement repeated in court a year later, and that the second version will sound better while being worse.',
      'What is striking is how cheap the improvements are. Show the faces one at a time. Make sure the officer running the process does not know the answer. Write down how sure the witness is before anyone says anything else. These cost almost nothing, they have been recommended for decades, and adoption has been slow. That tells us something about which kinds of evidence institutions find it comfortable to doubt.',
    ],
    paragraphsJa: [
      '法廷に座るほとんどの人にとって、確信と正確さは同じもののように感じられます。まったく確信していると言う目撃者は、ためらう目撃者よりも信じられます。この結びつきは直観的であり、そして感じられるよりもずっと弱いものです。',
      '記憶は、再生できる録音ではありません。記憶は使われるたびに、見たもの、その後に聞いたこと、そして本人が今こうだったはずだと考えていることから組み立て直されます。語り直すたびに説明は少しずつ書き換えられ、その書き換えは語っている本人には見えません。',
      '容疑者を特定するための手続きは、これをはるかに悪化させることがあります。写真を見せる係官がどの顔が容疑対象かを知っていれば、小さな無意識の合図が目撃者へ伝わります。顔を横に並べて見せれば、目撃者はそれらを比べて最も似たものを選ぶことになり、その中に見た人物がいるかどうかを判断しなくなります。いったん選択がなされて追認されると、確信は急に高まり、そのまま何か月も高まり続けます。',
      'これは目撃者が役に立たないという意味ではありません。初日に注意深く取られた証言は、1年後に法廷で繰り返される同じ証言よりもはるかに価値がある、そして後者のほうが、より劣っていながらより立派に聞こえる、という意味です。',
      '印象的なのは、改善策がどれほど安上がりかという点です。顔は一枚ずつ見せる。手続きを進める係官に正解を知らせない。誰かが何か言う前に、目撃者がどれほど確信しているかを書き留める。これらはほとんど費用がかからず、何十年も前から勧告されており、それでも導入は進んでいません。そのことは、どの種類の証拠なら疑っても居心地が悪くないと制度が感じているかを教えてくれます。',
    ],
    glossary: [
      { word: 'accuracy', ja: '正確さ' },
      { word: 'hesitate', ja: 'ためらう' },
      { word: 'intuitive', ja: '直観的な' },
      { word: 'retelling', ja: '語り直し' },
      { word: 'suspect', ja: '容疑者' },
      { word: 'unconscious', ja: '無意識の' },
      { word: 'adoption', ja: '導入、採用' },
    ],
    questions: [
      {
        id: 'r-b2-10-q1',
        prompt: '記憶について筆者が述べていることはどれですか。',
        choices: [
          '使われるたびに組み立て直され、書き換えは本人に見えない',
          '一度作られると変化しない',
          '時間が経つほど正確になる',
          '訓練を受けた人だけが正確に保てる',
        ],
        correctIndex: 0,
        explanation: 'It is built each time it is used と the edits are invisible to the person doing the telling が根拠です。',
        choiceNotes: [null, '毎回作り直されると述べています。', '正確さが増すとは述べていません。', '訓練の話は出てきません。'],
      },
      {
        id: 'r-b2-10-q2',
        prompt: '顔写真を横に並べて見せることの問題点はどれですか。',
        choices: [
          '見た人物がいるかを判断せず、最も似た顔を選んでしまう',
          '写真の枚数が多すぎて疲れる',
          '写真が古いものになりやすい',
          '目撃者が緊張してしまう',
        ],
        correctIndex: 0,
        explanation: 'picks the closest match rather than deciding whether any of them is the person seen が該当します。',
        choiceNotes: [null, '枚数や疲労は論点ではありません。', '写真の新旧には触れていません。', '緊張は挙げられていません。'],
      },
      {
        id: 'r-b2-10-q3',
        prompt: '第4段落の「より劣っていながらより立派に聞こえる」が指しているものはどれですか。',
        choices: [
          '1年後に法廷で繰り返される証言',
          '初日に取られた証言',
          '係官が書いた報告書',
          '専門家の意見',
        ],
        correctIndex: 0,
        explanation: 'the second version は the same statement repeated in court a year later を指しています。',
        choiceNotes: [null, 'こちらが worth far more とされています。', '報告書の話ではありません。', '専門家は登場しません。'],
      },
      {
        id: 'r-b2-10-q4',
        prompt: '筆者が挙げている改善策に共通する特徴はどれですか。',
        choices: [
          '費用がほとんどかからないのに導入が進んでいない',
          '高度な技術を必要とする',
          '法律の改正が前提になる',
          '目撃者の訓練を必要とする',
        ],
        correctIndex: 0,
        explanation: 'These cost almost nothing ... and adoption has been slow が要点です。',
        choiceNotes: [null, '技術的な要求は述べられていません。', '立法の必要には触れていません。', '訓練対象は目撃者ではありません。'],
      },
      {
        id: 'r-b2-10-q5',
        prompt: '最終文で筆者が示唆していることはどれですか。',
        choices: [
          '制度には、疑うことを避けたい種類の証拠がある',
          '目撃証言は法廷から排除すべきだ',
          '係官の能力が不足している',
          '研究者の発信が足りない',
        ],
        correctIndex: 0,
        explanation: 'which kinds of evidence institutions find it comfortable to doubt は、疑いにくい証拠があることを含意しています。',
        choiceNotes: [null, '排除は主張していません。', '個人の能力の問題とはしていません。', 'recommended for decades と、勧告自体はあったとしています。'],
      },
    ],
  },
  {
    id: 'r-b2-11',
    level: 'B2',
    title: 'Who the Road Belongs To',
    titleJa: '道路は誰のものか',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Arguments about bicycle lanes are rarely arguments about bicycles. They are arguments about who has a claim on a strip of public ground that has been treated as belonging to cars for about seventy years.',
      'This is why the debate has a temper that the subject does not seem to deserve. A city that removes a line of parking spaces is not taking property away from anyone, because nobody owned those spaces. It is withdrawing a habit, and a habit that has lasted a lifetime is felt as a right.',
      'The evidence on what actually happens is less dramatic than either side predicts. Shops on streets that lose parking usually report a fall in takings in the first year and a recovery afterwards, partly because shopkeepers consistently overestimate how many of their customers arrive by car. Traffic does not simply move to the next street in the quantities that were feared, because some of the journeys stop being made by car at all.',
      'The honest difficulty is elsewhere. A lane that runs for two streets and then stops is worse than useless, because it puts people who ride bicycles into the middle of the road at the point where they are least expected. Half a network is not half as good as a network. It is a different thing, and often a dangerous one.',
      'That is the argument that deserves attention, and it is almost never the one that is had. A city can reasonably decide not to build. What it cannot reasonably do is build a third of the plan, watch it fail, and treat the failure as evidence about bicycles.',
    ],
    paragraphsJa: [
      '自転車レーンをめぐる議論が、自転車についての議論であることはめったにありません。それは、およそ70年にわたって自動車のものとして扱われてきた公共の地面の一帯に、誰が権利を主張できるのかという議論です。',
      'だからこそこの論争は、主題からは不釣り合いに思えるほど熱を帯びます。駐車枠を一列撤去する都市は、誰からも財産を奪ってはいません。その枠を所有していた人はいないからです。撤回されているのは習慣です。そして一生続いた習慣は、権利として感じられます。',
      '実際に何が起きるかについての証拠は、どちらの側の予測よりも地味です。駐車枠を失った通りの店は、たいてい初年度に売上の減少を、その後に回復を報告します。理由の一つは、店主が自分の客のうち車で来る人の割合を一貫して過大に見積もっていることです。交通は、恐れられたほどの量では隣の通りへ単純に移動しません。移動の一部が、そもそも車で行われなくなるからです。',
      '本当の難しさは別のところにあります。2区画だけ続いて途切れるレーンは、無いより悪いのです。自転車に乗る人を、最も予期されていない地点で車道の真ん中へ放り出すからです。ネットワークの半分は、ネットワークの半分の価値ではありません。それは別のものであり、しばしば危険なものです。',
      'それこそ注意を払うに値する論点であり、そしてほとんど交わされることのない論点です。都市が造らないと決めるのは、それなりに筋が通ります。筋が通らないのは、計画の3分の1だけを造り、それが失敗するのを眺め、その失敗を自転車についての証拠として扱うことです。',
    ],
    glossary: [
      { word: 'strip', ja: '細長い一帯' },
      { word: 'temper', ja: '荒れた調子、気色ばみ' },
      { word: 'withdraw', ja: '撤回する' },
      { word: 'takings', ja: '売上' },
      { word: 'overestimate', ja: '過大に見積もる' },
      { word: 'network', ja: '網、ネットワーク' },
      { word: 'reasonably', ja: '筋の通った形で' },
    ],
    questions: [
      {
        id: 'r-b2-11-q1',
        prompt: '第2段落で筆者が説明している、論争が熱を帯びる理由はどれですか。',
        choices: [
          '長く続いた習慣が権利として感じられるから',
          '駐車枠が個人の財産だから',
          '自転車が危険だと考えられているから',
          '費用が大きいから',
        ],
        correctIndex: 0,
        explanation: 'a habit that has lasted a lifetime is felt as a right が理由として示されています。',
        choiceNotes: [null, 'nobody owned those spaces と否定されています。', '危険性は第4段落の別の論点です。', '費用は論じられていません。'],
      },
      {
        id: 'r-b2-11-q2',
        prompt: '店の売上について述べられていることはどれですか。',
        choices: [
          '初年度は減り、その後回復することが多い',
          '一貫して減り続ける',
          '最初から変化がない',
          '初年度から増える',
        ],
        correctIndex: 0,
        explanation: 'a fall in takings in the first year and a recovery afterwards が該当します。',
        choiceNotes: [null, '回復すると述べられています。', '初年度は減少します。', '初年度は減少します。'],
      },
      {
        id: 'r-b2-11-q3',
        prompt: '「ネットワークの半分は、ネットワークの半分の価値ではない」が意味しているのはどれですか。',
        choices: [
          '途切れたレーンは効果が薄いだけでなく危険を生む',
          '建設費が二倍かかる',
          '利用者が半分しか集まらない',
          '半分でも十分に機能する',
        ],
        correctIndex: 0,
        explanation: 'It is a different thing, and often a dangerous one が、量の問題ではないことを示しています。',
        choiceNotes: [null, '費用の話ではありません。', '利用者数の比例の話ではありません。', 'worse than useless と述べています。'],
      },
      {
        id: 'r-b2-11-q4',
        prompt: '筆者が「筋が通らない」としているのはどれですか。',
        choices: [
          '計画の一部だけ造って失敗させ、それを自転車の評価に使うこと',
          '自転車レーンを造らないと決めること',
          '駐車枠を撤去すること',
          '交通量を調査すること',
        ],
        correctIndex: 0,
        explanation: 'build a third of the plan, watch it fail, and treat the failure as evidence about bicycles が該当します。',
        choiceNotes: [null, 'can reasonably decide not to build と認めています。', '撤去自体は否定されていません。', '調査は論じられていません。'],
      },
      {
        id: 'r-b2-11-q5',
        prompt: 'この文章における筆者の立場として最も適切なものはどれですか。',
        choices: [
          'どちらの側の予測にも距離を置きつつ、設計の中途半端さを批判する',
          '自転車レーンに全面的に反対する',
          '自転車レーンを無条件に推進する',
          '判断は住民に委ねるべきだとする',
        ],
        correctIndex: 0,
        explanation: 'less dramatic than either side predicts と両論を退けたうえで、半端な整備を問題としています。',
        choiceNotes: [null, '造らない選択も認めており全面反対ではありません。', '無条件の推進もしていません。', '決定手続きには触れていません。'],
      },
    ],
  },
  {
    id: 'r-b2-12',
    level: 'B2',
    title: 'The Objects That Went Home',
    titleJa: '帰っていった品々',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'When a national collection agrees to send an object back to the country it came from, the news is usually reported as an ending. It is closer to a beginning, because the hard questions start once the principle has been accepted.',
      'The easy cases are the ones taken openly by force, where the record is clear and the request comes from a state that plainly stands in the place of the people who lost them. These cases are rarer than the argument suggests. Far more objects arrived through a long chain of sales, gifts and excavations carried out under rules written by the side that was in charge.',
      'Defenders of keeping them make two arguments that should be kept apart. The first is about care, and it is weakening every year as new buildings open and staff are trained. The second is about access, and it is more serious. An object in a city that millions pass through is seen by more people than the same object in a small town, whatever else is true.',
      'Against that stands something the access argument cannot reach. An object is not only a thing to be looked at. It carries a claim about who is entitled to explain it, and that claim is not settled by counting how many people walk past.',
      'The most useful returns so far have not been simple transfers. They have been long loans in both directions, shared control over how the object is described, and copies good enough to teach with. None of that satisfies anyone completely, which is a reasonable sign that it is close to right.',
    ],
    paragraphsJa: [
      '国立の収蔵機関が、ある品をそれが生まれた国へ返すと合意すると、その報せはたいてい結末として報じられます。実際にはむしろ始まりに近いのです。原則が受け入れられた時点から、難しい問いが始まるからです。',
      '簡単な事例は、公然と力ずくで持ち去られたもの、つまり記録が明確で、失った人々の立場に明らかに立つ国家から要求が来る場合です。こうした事例は、議論から受ける印象よりもまれです。はるかに多くの品は、売買、贈与、そして支配していた側が書いた規則のもとで行われた発掘という、長い連鎖を経て到着しました。',
      '保有を擁護する側は、区別しておくべき二つの主張をします。第一は保存管理についてのもので、これは新しい施設が開き人材が育つにつれて、年々弱まっています。第二は接近可能性についてのもので、こちらはより重大です。何百万人もが通り過ぎる都市にある品は、同じ品が小さな町にある場合よりも多くの人に見られます。他に何が言えるとしても、これは事実です。',
      'これに対して、接近可能性の議論では届かないものがあります。品は、眺められるための物であるだけではありません。それは、誰にそれを説明する資格があるのかという主張を帯びており、その主張は、前を通った人数を数えることでは決着しません。',
      'これまでで最も有効だった返還は、単純な移管ではありませんでした。双方向の長期貸与、その品をどう説明するかについての共同管理、そして教材として使える水準の複製です。そのどれも誰をも完全には満足させません。それは、答えとしてほぼ正しいことの、それなりに信頼できるしるしです。',
    ],
    glossary: [
      { word: 'collection', ja: '収蔵品、収蔵機関' },
      { word: 'by force', ja: '力ずくで' },
      { word: 'excavation', ja: '発掘' },
      { word: 'access', ja: '接近可能性' },
      { word: 'entitled', ja: '資格がある' },
      { word: 'transfer', ja: '移管' },
      { word: 'loan', ja: '貸与' },
    ],
    questions: [
      {
        id: 'r-b2-12-q1',
        prompt: '返還の合意を「始まりに近い」と述べるのはなぜですか。',
        choices: [
          '原則が認められた後に難しい問いが始まるから',
          '返還には長い時間がかかるから',
          '合意が破られることが多いから',
          '別の品の要求が続くから',
        ],
        correctIndex: 0,
        explanation: 'the hard questions start once the principle has been accepted が理由です。',
        choiceNotes: [null, '所要時間の話ではありません。', '合意の破棄には触れていません。', '連鎖的な要求は述べられていません。'],
      },
      {
        id: 'r-b2-12-q2',
        prompt: '「簡単な事例」について筆者はどう述べていますか。',
        choices: [
          '議論から受ける印象よりもまれである',
          '大半の事例がこれにあたる',
          '記録が残っていないことが多い',
          '要求する国家が存在しない',
        ],
        correctIndex: 0,
        explanation: 'These cases are rarer than the argument suggests が該当します。',
        choiceNotes: [null, 'Far more objects は別経路で到着したとされています。', 'the record is clear と述べられています。', '要求する国家は存在する前提です。'],
      },
      {
        id: 'r-b2-12-q3',
        prompt: '保有を擁護する二つの主張について、筆者はどう評価していますか。',
        choices: [
          '保存管理の主張は弱まっており、接近可能性の主張のほうが重大である',
          '両方とも同じくらい強い',
          '両方とも既に無効である',
          '保存管理の主張のほうが重大である',
        ],
        correctIndex: 0,
        explanation: 'it is weakening every year と it is more serious の対比が根拠です。',
        choiceNotes: [null, '重みに差をつけています。', '接近可能性は more serious とされています。', '逆の評価です。'],
      },
      {
        id: 'r-b2-12-q4',
        prompt: '第4段落で筆者が持ち出す反論の核心はどれですか。',
        choices: [
          '品は説明する資格をめぐる主張を帯びており、人数では決着しない',
          '品は破損の危険があるから移動すべきでない',
          '来場者数の統計が信用できない',
          '品の価値は金額では測れない',
        ],
        correctIndex: 0,
        explanation: 'a claim about who is entitled to explain it, and that claim is not settled by counting が該当します。',
        choiceNotes: [null, '破損の危険は論じられていません。', '統計の信頼性の話ではありません。', '金銭的価値は論点ではありません。'],
      },
      {
        id: 'r-b2-12-q5',
        prompt: '「誰をも完全には満足させない」ことを、筆者はどう捉えていますか。',
        choices: [
          '答えとしてほぼ正しいことのしるしだと捉えている',
          '解決が失敗した証拠だと捉えている',
          '交渉が不十分だった結果だと捉えている',
          '当事者の努力不足だと捉えている',
        ],
        correctIndex: 0,
        explanation: 'a reasonable sign that it is close to right が筆者の評価です。',
        choiceNotes: [null, '失敗とは捉えていません。', '交渉不足とは述べていません。', '努力不足には触れていません。'],
      },
    ],
  },
  {
    id: 'r-b2-13',
    level: 'B2',
    title: 'Reading a Person from a Form',
    titleJa: '書類から人を読む',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A large firm may receive two thousand applications for thirty positions. Reading them properly would take a team several weeks, and the team does not exist. Software that sorts them in an afternoon is not a luxury. It is the only way the process happens at all.',
      'The usual objection is that such software is unfair. That is true but imprecise, because the comparison is never with a fair process. It is with a tired manager at four in the afternoon, who has already decided that the pile is too big and who will not remember by evening why he moved one form to the left.',
      'The real difficulty is different, and it is structural. Software learns what a good employee looks like from the record of who was hired before and who did well. If the firm hired a narrow kind of person for twenty years, that pattern is what the system will find and reproduce, with a confidence that no tired manager could ever project.',
      'This is why the fix that firms reach for first does not work. Removing names and addresses from the form does not remove the pattern, because the pattern survives in the choice of school, in the gaps in a working life, in the sports listed at the bottom of the page. What has been removed is the evidence that would let anyone prove what happened.',
      'There is a version of this technology that would help. It would explain each decision in terms a person can check, keep the rejected applications for study, and be tested every year against results rather than intentions. Almost nobody buys that version, because it is slower and it produces uncomfortable reports. The problem was never the machine.',
    ],
    paragraphsJa: [
      '大きな企業が30の職に2,000通の応募を受け取ることがあります。それらをきちんと読むには、あるチームが数週間を要するでしょう。そしてそのチームは存在しません。午後のうちに仕分けるソフトウェアは贅沢品ではありません。そもそも選考が成り立つ唯一の方法なのです。',
      'よくある反論は、そうしたソフトウェアは不公平だ、というものです。それは正しいけれども不正確です。比較の相手が公平な手続きであったことは一度もないからです。相手は午後4時の疲れた管理職であり、彼はすでに山が大きすぎると判断しており、夕方までにはなぜある一通を左へ寄せたのかを覚えていません。',
      '本当の難しさは別のところにあり、それは構造的なものです。ソフトウェアは、これまで誰が採用され誰が成果を出したかという記録から、良い従業員がどう見えるかを学びます。その企業が20年にわたって狭い種類の人材を採ってきたなら、システムが見つけて再生産するのはその型です。しかも、疲れた管理職には到底出せない確信を伴って。',
      'だからこそ、企業が最初に手を伸ばす修正は効きません。書類から氏名と住所を消しても、型は消えません。型は、出身校の選択に、職歴の空白に、ページの末尾に並ぶスポーツの種目に生き残るからです。消えたのは、何が起きたのかを誰かが証明できたはずの証拠のほうです。',
      'この技術には、役に立つ形もあります。それは各判断を人が検証できる言葉で説明し、不採用の応募を研究用に保存し、意図ではなく結果に照らして毎年検査されるものです。その形はほとんど誰も買いません。遅く、しかも居心地の悪い報告を出すからです。問題は初めから機械ではありませんでした。',
    ],
    glossary: [
      { word: 'application', ja: '応募書類' },
      { word: 'luxury', ja: '贅沢品' },
      { word: 'imprecise', ja: '不正確な' },
      { word: 'structural', ja: '構造的な' },
      { word: 'reproduce', ja: '再生産する' },
      { word: 'reject', ja: '不採用にする' },
      { word: 'intention', ja: '意図' },
    ],
    questions: [
      {
        id: 'r-b2-13-q1',
        prompt: '「不公平だという反論は正しいが不正確だ」と筆者が述べる理由はどれですか。',
        choices: [
          '比較の相手が公平な手続きだったことはないから',
          'ソフトウェアは実際には公平だから',
          '不公平の定義が定まっていないから',
          '応募者が制度を理解していないから',
        ],
        correctIndex: 0,
        explanation: 'the comparison is never with a fair process が理由として明示されています。',
        choiceNotes: [null, 'That is true と不公平さ自体は認めています。', '定義の議論はしていません。', '応募者の理解には触れていません。'],
      },
      {
        id: 'r-b2-13-q2',
        prompt: '筆者が「本当の難しさ」と呼んでいるものはどれですか。',
        choices: [
          '過去の採用の型を学習し、確信をもって再生産すること',
          '処理速度が遅いこと',
          '導入費用が高いこと',
          '応募者が書き方を工夫すること',
        ],
        correctIndex: 0,
        explanation: 'that pattern is what the system will find and reproduce が該当します。',
        choiceNotes: [null, '速さはむしろ利点として挙げられています。', '費用は論じられていません。', '応募者側の対策は述べられていません。'],
      },
      {
        id: 'r-b2-13-q3',
        prompt: '氏名と住所を消す対策について、筆者はどう評価していますか。',
        choices: [
          '型は他の情報に残り、消えるのは証明のための証拠のほうである',
          '有効だが不十分である',
          '法的に問題がある',
          '応募者に不便を強いる',
        ],
        correctIndex: 0,
        explanation: 'the pattern survives ... What has been removed is the evidence が根拠です。',
        choiceNotes: [null, '有効だとはしていません。', '法的な議論はしていません。', '応募者の負担には触れていません。'],
      },
      {
        id: 'r-b2-13-q4',
        prompt: '役に立つ形の技術の条件として挙げられていないものはどれですか。',
        choices: [
          '処理を可能な限り高速にすること',
          '判断を人が検証できる言葉で説明すること',
          '不採用の応募を保存すること',
          '結果に照らして毎年検査されること',
        ],
        correctIndex: 0,
        explanation: 'it is slower と、むしろ遅くなることが前提とされています。',
        choiceNotes: [null, 'explain each decision in terms a person can check が挙げられています。', 'keep the rejected applications for study が挙げられています。', 'tested every year against results が挙げられています。'],
      },
      {
        id: 'r-b2-13-q5',
        prompt: '最終文「問題は初めから機械ではありませんでした」の意味として最も適切なものはどれですか。',
        choices: [
          '検証可能な仕組みを選ばない組織の側に問題がある',
          '機械の性能はまだ不十分である',
          '人間が判断するほうが常に良い',
          '技術は中立なので評価できない',
        ],
        correctIndex: 0,
        explanation: '直前の Almost nobody buys that version が、選ばない側の問題であることを示しています。',
        choiceNotes: [null, '性能不足の話ではありません。', '疲れた管理職の例で人間の優位を否定しています。', '中立だから評価不能とは述べていません。'],
      },
    ],
  },
  {
    id: 'r-b2-14',
    level: 'B2',
    title: 'The Rules That Changed the Game',
    titleJa: '競技を変えた規則',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'For a long time a blow to the head was treated as part of the game. A player who could stand up and answer a question went back on, and the crowd approved. What has changed is not the force of the blows. It is what we now believe happens afterwards.',
      'The evidence that made the change unavoidable did not come from the field. It came from the brains of former players examined after death, and from the families who insisted that the confusion and anger of the last years were not simply age. Once that connection was made public, no league could go on saying that the matter was unclear.',
      'The rules that followed have been unpopular in a revealing way. Players complain that the sport has been softened, and some of them are the same people who will need care in thirty years. Supporters complain that the flow of the match is broken. Neither group is lying, and neither objection touches the reason the rules exist.',
      'It is worth being precise about what the rules can and cannot do. Removing the worst kinds of contact reduces the number of severe injuries. It does not remove the ordinary repeated knocks, which may matter more in total, and which are much harder to legislate against without changing the sport into something else.',
      'That is the question the governing bodies have avoided in public. If the risk lies partly in the ordinary business of the game, then the choice is not between a safe sport and a dangerous one. It is about how much risk adults may accept, how young a person may be when the accepting starts, and who explains it to them.',
    ],
    paragraphsJa: [
      '長いあいだ、頭部への衝撃は競技の一部として扱われてきました。立ち上がって問いに答えられる選手はプレーに戻り、観客はそれをよしとしました。変わったのは衝撃の強さではありません。その後に何が起きると私たちが今考えているか、です。',
      'この変化を避けられないものにした証拠は、競技場から出てきたのではありません。死後に検査された元選手の脳から、そして、晩年の混乱と怒りは単なる加齢ではないと言い張った家族から出てきました。その結びつきがいったん公になると、どのリーグももはや、この件は不明確だと言い続けることはできませんでした。',
      'それに続いた規則は、示唆に富む形で不人気でした。選手たちは競技が甘くなったと不平を言います。その一部は、30年後に介護を必要とすることになる当人です。ファンは試合の流れが切れると不平を言います。どちらの集団も嘘をついてはいません。そしてどちらの異議も、その規則が存在する理由には触れていません。',
      '規則にできることとできないことは、正確に述べておく価値があります。最悪の種類の接触を取り除けば、重い負傷の件数は減ります。しかしそれは、日常的に繰り返される軽い衝撃を取り除きはしません。総量では後者のほうが重要かもしれず、しかもそれを規則で禁じることは、競技を別の何かに変えずには、はるかに困難です。',
      'それこそ、統括団体が公の場で避けてきた問いです。危険の一部が競技の日常的な営みそのものにあるのなら、選択肢は安全な競技と危険な競技のあいだにあるのではありません。大人がどれだけの危険を引き受けてよいか、その引き受けが始まるのは何歳からでよいか、そして誰がそれを本人に説明するのか、という問題なのです。',
    ],
    glossary: [
      { word: 'blow', ja: '打撃、衝撃' },
      { word: 'unavoidable', ja: '避けられない' },
      { word: 'league', ja: 'リーグ、連盟' },
      { word: 'revealing', ja: '示唆に富む' },
      { word: 'contact', ja: '接触プレー' },
      { word: 'legislate', ja: '規則で定める' },
      { word: 'governing body', ja: '統括団体' },
    ],
    questions: [
      {
        id: 'r-b2-14-q1',
        prompt: '第1段落で筆者が「変わった」としているものはどれですか。',
        choices: [
          '衝撃の後に何が起きると考えられているか',
          '衝撃そのものの強さ',
          '観客の人数',
          '競技の規則の総数',
        ],
        correctIndex: 0,
        explanation: 'It is what we now believe happens afterwards. が該当します。',
        choiceNotes: [null, 'not the force of the blows と否定されています。', '観客数の話は出てきません。', '規則の数は論じられていません。'],
      },
      {
        id: 'r-b2-14-q2',
        prompt: '変化を決定づけた証拠の出所として述べられているのはどれですか。',
        choices: [
          '死後に検査された元選手の脳と、その家族の主張',
          '試合中の測定機器の記録',
          '現役選手への聞き取り調査',
          '海外リーグとの比較研究',
        ],
        correctIndex: 0,
        explanation: 'the brains of former players examined after death, and from the families が根拠です。',
        choiceNotes: [null, '測定機器には触れていません。', '現役選手の調査は述べられていません。', '国際比較は出てきません。'],
      },
      {
        id: 'r-b2-14-q3',
        prompt: '「示唆に富む形で不人気」という表現が指しているのはどれですか。',
        choices: [
          '不平を言う選手自身が将来その保護を必要としうること',
          '規則が誰にも支持されていないこと',
          '不人気の理由が調査されていないこと',
          '不平がすべて事実に反すること',
        ],
        correctIndex: 0,
        explanation: 'some of them are the same people who will need care in thirty years が、その示唆の内容です。',
        choiceNotes: [null, '不人気だが理由が存在すると述べています。', '理由は本文で示されています。', 'Neither group is lying と述べています。'],
      },
      {
        id: 'r-b2-14-q4',
        prompt: '規則の限界として筆者が挙げているのはどれですか。',
        choices: [
          '日常的に繰り返される軽い衝撃には手が届かないこと',
          '重い負傷を減らせないこと',
          '審判が判定できないこと',
          '選手が規則を知らないこと',
        ],
        correctIndex: 0,
        explanation: 'It does not remove the ordinary repeated knocks, which may matter more in total が該当します。',
        choiceNotes: [null, 'reduces the number of severe injuries と効果は認めています。', '判定の実務は論じられていません。', '周知の問題は出てきません。'],
      },
      {
        id: 'r-b2-14-q5',
        prompt: '最終段落で筆者が本当の論点だとしているのはどれですか。',
        choices: [
          '誰がどの年齢からどれだけの危険を引き受け、誰が説明するのか',
          '競技を廃止すべきか否か',
          '統括団体の財政をどうするか',
          '観客の安全をどう守るか',
        ],
        correctIndex: 0,
        explanation: 'how much risk adults may accept, how young a person may be ... and who explains it to them が結論の問いです。',
        choiceNotes: [null, '廃止は選択肢として提示されていません。', '財政には触れていません。', '観客の安全は論点ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-15',
    level: 'B2',
    title: 'The Seeds Nobody Plants',
    titleJa: '誰も蒔かない種',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A field of wheat that yields more than any field yielded a century ago is an achievement, and it is also a narrowing. The gain came from planting the best variety everywhere, and the best variety is, by definition, one thing rather than many.',
      'The risk in this is not hard to see. A disease that a widely planted variety cannot resist has an open road in front of it. The older pattern, in which each valley grew something slightly different, was less productive in a good year and much safer in a bad one.',
      'Collections of stored seed exist to hold the difference open. They are often described as a backup, which is only half of what they are for. Most of what is taken out of them goes not to farmers after a disaster but to plant breeders, who need the old varieties as material to build the new ones. A collection that is never opened has failed.',
      'The awkward part is that keeping seed alive is not like keeping a book. Seed loses the ability to grow, so every sample must be planted out and harvested again on a schedule, in a place where it will grow properly. This is skilled, unglamorous work, funded in short cycles by bodies that prefer to announce new things.',
      'It is a familiar shape. The cost falls now, on a named budget, and the benefit falls later, on people who will not know what they were protected from. We have seen how badly that arrangement tends to go. There is no reason to think it will go better here.',
    ],
    paragraphsJa: [
      '1世紀前のどの畑よりも多く穫れる小麦畑は、ひとつの成果であり、同時にひとつの狭まりでもあります。その増収は、最良の品種をどこにでも植えることから得られました。そして最良の品種とは、定義上、多くのものではなくひとつのものです。',
      'ここにある危険は見て取るのが難しくありません。広く植えられた品種が抵抗できない病気には、目の前に開けた道があります。それぞれの谷が少しずつ違うものを育てていた古い型は、豊作の年には生産性が低く、凶作の年にははるかに安全でした。',
      '保存された種子の集積は、その差異を開いたままにしておくために存在します。それらはしばしば予備の控えとして説明されますが、それは用途の半分にすぎません。そこから取り出されるものの大半は、災害後の農家へではなく、育種家のもとへ行きます。彼らは新しい品種を作る材料として古い品種を必要とします。一度も開かれない集積は、失敗した集積です。',
      '厄介なのは、種子を生かしておくことが本を保管することとは違う点です。種子は発芽する力を失うため、どの試料も一定の周期で、それがきちんと育つ場所で、植えて収穫し直さなければなりません。これは熟練を要する、見栄えのしない仕事であり、新しいことを発表したがる組織によって短い周期で資金が付けられます。',
      'これは見慣れた形です。費用は今、名前のついた予算に落ち、便益は後で、自分が何から守られたのかを知ることのない人々に落ちます。その配置がどれほどうまくいかないかを、私たちは見てきました。ここだけはうまくいくと考える理由はありません。',
    ],
    glossary: [
      { word: 'yield', ja: '収穫を上げる、収量' },
      { word: 'narrowing', ja: '狭まり' },
      { word: 'variety', ja: '品種' },
      { word: 'productive', ja: '生産性の高い' },
      { word: 'breeder', ja: '育種家' },
      { word: 'sample', ja: '試料' },
      { word: 'unglamorous', ja: '見栄えのしない' },
    ],
    questions: [
      {
        id: 'r-b2-15-q1',
        prompt: '収量の増加を筆者が「狭まり」とも呼ぶのはなぜですか。',
        choices: [
          '最良の品種を一律に植えたことで多様性が減ったから',
          '農地の面積が減ったから',
          '農家の数が減ったから',
          '収穫期間が短くなったから',
        ],
        correctIndex: 0,
        explanation: 'the best variety is, by definition, one thing rather than many が理由です。',
        choiceNotes: [null, '面積の話は出てきません。', '農家数には触れていません。', '期間の話ではありません。'],
      },
      {
        id: 'r-b2-15-q2',
        prompt: '古い作付けの型について述べられていることはどれですか。',
        choices: [
          '豊作の年には生産性が低く、凶作の年には安全だった',
          '常に生産性が高かった',
          '病気に弱かった',
          '記録が残っていない',
        ],
        correctIndex: 0,
        explanation: 'less productive in a good year and much safer in a bad one が該当します。',
        choiceNotes: [null, '生産性は低かったとされています。', 'much safer と逆です。', '記録の有無は論じられていません。'],
      },
      {
        id: 'r-b2-15-q3',
        prompt: '種子の集積の主な用途として、筆者が強調しているのはどれですか。',
        choices: [
          '育種家が新品種を作る材料として使うこと',
          '災害後に農家へ配ること',
          '博物館で展示すること',
          '価格の変動に備えること',
        ],
        correctIndex: 0,
        explanation: 'Most of what is taken out of them goes not to farmers after a disaster but to plant breeders が根拠です。',
        choiceNotes: [null, 'not to farmers after a disaster と明示的に退けられています。', '展示には触れていません。', '価格の話は出てきません。'],
      },
      {
        id: 'r-b2-15-q4',
        prompt: '種子の保存が本の保管と違う点はどれですか。',
        choices: [
          '発芽力を失うため、周期的に植え直す必要がある',
          '温度管理が不要である',
          '数量を数える必要がない',
          '所有権が定まらない',
        ],
        correctIndex: 0,
        explanation: 'every sample must be planted out and harvested again on a schedule が該当します。',
        choiceNotes: [null, '温度管理の要否は述べられていません。', '数量管理の話ではありません。', '所有権は論点ではありません。'],
      },
      {
        id: 'r-b2-15-q5',
        prompt: '最終段落の「見慣れた形」とは何を指していますか。',
        choices: [
          '費用が今の予算に、便益が後の人々に落ちる配置',
          '研究資金が毎年増える配置',
          '農家と行政が対立する配置',
          '技術が古い方法を完全に置き換える配置',
        ],
        correctIndex: 0,
        explanation: 'The cost falls now ... and the benefit falls later が、その形の内容です。',
        choiceNotes: [null, 'funded in short cycles と、むしろ不安定だと述べています。', '対立構図は描かれていません。', '置き換えの話ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-16',
    level: 'B2',
    title: 'What a Play Is Worth',
    titleJa: '1回の再生の値段',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Musicians who complain about streaming are often answered with a calculation. The service pays out most of what it takes in, the answer goes, so the money must be going somewhere reasonable. The calculation is correct and the conclusion does not follow.',
      'What matters is not how much is paid out but how it is divided. Under the usual method, all the money from all the subscriptions in a country is put in one pot, and each recording takes a share equal to its share of total listening. A person who pays a monthly fee and listens only to one quiet singer is, in effect, paying the most popular acts in the country.',
      'There is another method, in which the fee paid by each listener is divided among the recordings that listener actually played. It sounds like a small technical change. It moves a noticeable amount of money away from the top of the chart and towards the people whose audiences are small and loyal.',
      'The services have been slow to adopt it, and the reason given is that it is complicated to calculate. That is true. It is also true that the current method is convenient for the parties who negotiate the contracts, who are not usually the people whose names appear on the recordings.',
      'The wider point is that there is no natural price for a single play. The figure that everyone quotes is not discovered but produced, by a rule that somebody chose and that could be chosen differently. Arguments that treat it as a fact of the market are describing a decision as though it were weather.',
    ],
    paragraphsJa: [
      '配信について不平を言う音楽家は、しばしば計算で返されます。サービスは受け取った額の大半を支払っている、だから金はどこかまっとうな場所へ行っているはずだ、と。その計算は正しく、そして結論はそこから導かれません。',
      '重要なのは、いくら支払われるかではなく、どう分けられるかです。通常の方式では、その国のすべての加入料が一つの器に入れられ、各録音は総再生時間に占める自分の割合に等しい分け前を受け取ります。月額を払って静かな歌い手一人だけを聴く人は、事実上、その国で最も人気のある演者に支払っているのです。',
      'もう一つの方式があります。各聴き手が払った額を、その聴き手が実際に再生した録音のあいだで分けるやり方です。小さな技術的変更のように聞こえます。実際にはそれは、相当の額を上位から引きはがし、聴衆が少なく忠実な人々のほうへ動かします。',
      'サービス各社の採用は遅れており、示される理由は計算が複雑だというものです。それは事実です。同時に、現行の方式が契約を交渉する当事者にとって都合がよいことも事実です。そしてその当事者は、たいてい録音に名前が載る人々ではありません。',
      'より広く言えるのは、1回の再生に自然な値段など存在しないということです。誰もが引用するあの数字は、発見されたものではなく、誰かが選び、別様にも選べたはずの規則によって生み出されたものです。それを市場の事実として扱う議論は、決定を天気であるかのように語っているのです。',
    ],
    glossary: [
      { word: 'calculation', ja: '計算' },
      { word: 'subscription', ja: '加入、月額契約' },
      { word: 'pot', ja: '(集められた)資金の器' },
      { word: 'in effect', ja: '事実上' },
      { word: 'loyal', ja: '忠実な' },
      { word: 'adopt', ja: '採用する' },
      { word: 'negotiate', ja: '交渉する' },
    ],
    questions: [
      {
        id: 'r-b2-16-q1',
        prompt: '第1段落で筆者が指摘している論理の問題はどれですか。',
        choices: [
          '計算は正しいが、そこから結論は導かれない',
          '計算そのものが誤っている',
          '数字が公開されていない',
          '音楽家が計算を理解していない',
        ],
        correctIndex: 0,
        explanation: 'The calculation is correct and the conclusion does not follow. が該当します。',
        choiceNotes: [null, 'correct と認めています。', '非公開の話は出てきません。', '音楽家の理解力は論じられていません。'],
      },
      {
        id: 'r-b2-16-q2',
        prompt: '通常の分配方式の下で起きることとして述べられているのはどれですか。',
        choices: [
          '一人の歌い手だけを聴く人が、事実上は人気演者に払うことになる',
          '聴かない録音には一切支払われない',
          '加入料が国ごとに変動する',
          '音楽家が直接契約を結ぶ',
        ],
        correctIndex: 0,
        explanation: 'is, in effect, paying the most popular acts in the country が該当します。',
        choiceNotes: [null, '総再生に応じて分配されるため逆です。', '料金の変動は論じられていません。', '直接契約の話は出てきません。'],
      },
      {
        id: 'r-b2-16-q3',
        prompt: 'もう一つの分配方式の効果として述べられているのはどれですか。',
        choices: [
          '上位から、聴衆が少なく忠実な人々へ金が移る',
          '全体の支払総額が増える',
          '加入料が下がる',
          '再生回数の集計が不要になる',
        ],
        correctIndex: 0,
        explanation: 'away from the top of the chart and towards the people whose audiences are small and loyal が該当します。',
        choiceNotes: [null, '総額の増加は述べられていません。', '料金の変化には触れていません。', '集計は依然として必要です。'],
      },
      {
        id: 'r-b2-16-q4',
        prompt: '採用が進まない理由について、筆者はどう述べていますか。',
        choices: [
          '計算の複雑さは事実だが、現行方式が交渉当事者に都合よいことも事実だ',
          '複雑さだけが唯一の理由である',
          '法律で禁じられている',
          '聴き手が反対している',
        ],
        correctIndex: 0,
        explanation: 'That is true. It is also true that ... convenient for the parties who negotiate the contracts と二重の理由を示しています。',
        choiceNotes: [null, 'It is also true と別の理由を加えています。', '法的禁止には触れていません。', '聴き手の反対は述べられていません。'],
      },
      {
        id: 'r-b2-16-q5',
        prompt: '「決定を天気であるかのように語っている」という比喩の意味はどれですか。',
        choices: [
          '人が選んだ規則の結果を、変えられない自然現象のように扱っている',
          '予測が難しいと言っている',
          '季節によって金額が変わると言っている',
          '専門家でも分からないと言っている',
        ],
        correctIndex: 0,
        explanation: 'not discovered but produced, by a rule that somebody chose と対応しています。',
        choiceNotes: [null, '予測可能性の話ではありません。', '季節変動の話ではありません。', '専門性の限界の話ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-17',
    level: 'B2',
    title: 'The Line to the Coast',
    titleJa: '海岸へ向かう線路',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'The case for closing a rural railway line writes itself. Four trains a day, most of them nearly empty, running on track that will need replacing within the decade. Set the cost of the repair against the money taken at the stations, and the answer looks obvious.',
      'It looks obvious because of what the calculation leaves out. The station is why the doctor agreed to hold a clinic in the village twice a week. It is why the secondary school can accept pupils from three valleys, and why the two hotels near the coast can fill rooms in a season that is only four months long.',
      'Supporters of closure reply that a bus can do the same work for a fraction of the cost, and in narrow terms they are right. What buses have not managed anywhere is to hold their passengers. A line on a map that has been there for a century is trusted in a way that a service which may be rerouted next year is not, and people make decisions about where to live on the strength of that difference.',
      'This is not an argument that every line should stay open. Some carry almost nobody and serve places that have already emptied. It is an argument that the numbers used in these decisions measure the easiest thing rather than the important thing, and that the gap between the two is widest exactly where the population is smallest.',
      'A village that loses its line does not close the following year. It loses the doctor, then the school, then the young families, over about fifteen years, and by the time the pattern is visible the decision is far too old to be reversed. The cost was real. It was simply not paid by the people who counted it.',
    ],
    paragraphsJa: [
      '地方の鉄道路線を廃止する理由は、自ずと書き上がります。1日4本、その大半はほぼ空、しかも10年以内に取り替えを要する線路の上を走る。修繕費を駅の収入と突き合わせれば、答えは明白に見えます。',
      '明白に見えるのは、その計算が何を落としているかのせいです。その駅があるから、医師は週2回この村で診療を持つことに同意しました。その駅があるから、中等学校は三つの谷から生徒を受け入れられ、海岸近くの二軒の宿は、わずか4か月しかない季節に部屋を埋められます。',
      '廃止に賛成する側は、バスなら同じ仕事をはるかに安くこなせると答えます。狭い意味では、その通りです。ただしバスがどこでも達成できていないのは、乗客をつなぎ止めることです。1世紀そこにある地図上の線は、来年には経路が変わるかもしれない便とは違う仕方で信頼されます。そして人々は、その違いを頼りにどこに住むかを決めます。',
      'これは、すべての路線を残すべきだという主張ではありません。ほとんど誰も乗せず、すでに人が去った場所に通じる路線もあります。これは、こうした判断に使われる数字が、重要なものではなく最も測りやすいものを測っているという主張であり、両者の隔たりは、人口が最も少ない場所でこそ最大になるという主張です。',
      '路線を失った村は、翌年に消えるわけではありません。医師を失い、次に学校を失い、次に若い家族を失う。それが約15年かけて進み、その型が見えるようになった頃には、決定はもう覆すにはあまりに古くなっています。費用は実在しました。ただ、それを計算した人々が払わなかっただけです。',
    ],
    glossary: [
      { word: 'rural', ja: '地方の、田舎の' },
      { word: 'closure', ja: '廃止、閉鎖' },
      { word: 'fraction', ja: 'わずかな割合' },
      { word: 'reroute', ja: '経路を変える' },
      { word: 'on the strength of', ja: '〜を頼りに' },
      { word: 'reverse', ja: '覆す' },
      { word: 'visible', ja: '目に見える' },
    ],
    questions: [
      {
        id: 'r-b2-17-q1',
        prompt: '第2段落で挙げられている、計算から抜け落ちているものはどれですか。',
        choices: [
          '医師の診療、学校の通学範囲、宿の稼働',
          '線路の修繕費',
          '駅の収入',
          '列車の本数',
        ],
        correctIndex: 0,
        explanation: '医師の clinic、secondary school、two hotels の三つが、計算に入らない便益として挙げられています。',
        choiceNotes: [null, '修繕費は計算に入っています。', '駅の収入も計算に入っています。', '本数は第1段落の計算側の情報です。'],
      },
      {
        id: 'r-b2-17-q2',
        prompt: 'バスによる代替について、筆者はどう評価していますか。',
        choices: [
          '費用面では正しいが、乗客をつなぎ止められていない',
          'あらゆる面で鉄道に劣る',
          '鉄道より優れている',
          '実例がないので判断できない',
        ],
        correctIndex: 0,
        explanation: 'in narrow terms they are right に続けて What buses have not managed anywhere is to hold their passengers と限界を示しています。',
        choiceNotes: [null, '費用面の正しさは認めています。', '優れているとはしていません。', 'anywhere と実例を踏まえた記述です。'],
      },
      {
        id: 'r-b2-17-q3',
        prompt: '鉄道が信頼される理由として述べられているのはどれですか。',
        choices: [
          '経路が変わりにくく、1世紀にわたり地図上に存在してきたから',
          '運賃が安いから',
          '速度が速いから',
          '本数が多いから',
        ],
        correctIndex: 0,
        explanation: 'A line on a map that has been there for a century is trusted が根拠です。',
        choiceNotes: [null, '運賃はむしろバスが安いとされています。', '速度には触れていません。', '1日4本と少ないと述べられています。'],
      },
      {
        id: 'r-b2-17-q4',
        prompt: '第4段落で筆者が明確にしている自らの立場はどれですか。',
        choices: [
          'すべての路線を残せという主張ではなく、測り方の問題を指摘している',
          'すべての路線を残すべきだと主張している',
          '廃止は常に正しいと主張している',
          '判断は国が行うべきだと主張している',
        ],
        correctIndex: 0,
        explanation: 'This is not an argument that every line should stay open. と明示的に立場を限定しています。',
        choiceNotes: [null, '明示的に否定されています。', '廃止の是非を一律には論じていません。', '決定主体の話は出てきません。'],
      },
      {
        id: 'r-b2-17-q5',
        prompt: '最終文「それを計算した人々が払わなかっただけです」が示しているのはどれですか。',
        choices: [
          '費用の負担者と、判断を下した者が別であること',
          '計算に誤りがあったこと',
          '費用が過大に見積もられたこと',
          '住民が支払いを拒んだこと',
        ],
        correctIndex: 0,
        explanation: 'The cost was real. It was simply not paid by the people who counted it. が、負担と判断の分離を指しています。',
        choiceNotes: [null, '計算の誤りではなく範囲の問題です。', '過大ではなく計上漏れの話です。', '支払い拒否の話ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-18',
    level: 'B2',
    title: 'The Medicine That Stops Working',
    titleJa: '効かなくなる薬',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'An antibiotic is unusual among medicines in that using it makes it worse. Every course given anywhere in the world moves the bacteria that survive a little further towards resistance, and the loss is shared by everyone who will need that drug later.',
      'This puts a doctor in a genuinely hard position. The patient in front of her is a person with a name, and the people who will be harmed by resistance are a statistic in the future. A doctor who prescribes when in doubt is being kind to the person she can see. Multiply that kindness by several hundred million and the drug stops working.',
      'It is tempting to end there, with individual restraint as the answer. That would be a mistake, because a large share of the world supply is not given to sick people at all. It is fed to healthy farm animals to make them grow, and no amount of care in a clinic offsets that.',
      'The other half of the problem is that almost no new antibiotics are being developed. A firm that spends a decade producing one is told, correctly, that it must be used as little as possible and kept in reserve. That is excellent policy and a terrible business, and the market has responded exactly as anyone would predict.',
      'What follows is uncomfortable for people who like clean answers. A drug that must be sold sparingly cannot be funded by selling it. Either the public pays for the development of medicines it hopes never to need, or the medicines do not exist. There is no third option, although a great deal of effort has gone into looking for one.',
    ],
    paragraphsJa: [
      '抗生物質は、使うほど悪くなるという点で薬の中でも異例です。世界のどこであれ1回の投与が行われるたびに、生き残った細菌は耐性へ向けて少しずつ進みます。そしてその損失は、後にその薬を必要とするすべての人が分け合います。',
      'これは医師を、本当に難しい立場に置きます。目の前の患者は名前を持つ一人の人間であり、耐性によって害を受ける人々は未来の統計です。迷ったときに処方する医師は、自分に見える相手に親切にしています。その親切を数億回かければ、薬は効かなくなります。',
      'そこで話を終え、個人の自制を答えとしたくなります。それは誤りでしょう。世界の供給量の大きな部分は、そもそも病人に与えられていないからです。それは健康な家畜に成長を促すために与えられており、診療所でどれほど注意を払ってもそれを相殺できません。',
      '問題のもう半分は、新しい抗生物質がほとんど開発されていないことです。10年をかけて一つを生み出した企業は、それをできるだけ使わず、切り札として温存せよと言われます。しかもその指示は正しい。それは優れた政策であり、ひどい商売です。そして市場は、誰もが予測する通りに反応しました。',
      'ここから導かれることは、きれいな答えを好む人には居心地の悪いものです。控えめにしか売れない薬は、それを売ることでは開発費を賄えません。公衆が、決して必要にならないことを願う薬の開発に支払うか、さもなければその薬は存在しないかです。第三の選択肢はありません。それを探すことに多大な努力が注がれてきたにもかかわらず。',
    ],
    glossary: [
      { word: 'antibiotic', ja: '抗生物質' },
      { word: 'course', ja: '一連の投薬' },
      { word: 'resistance', ja: '耐性' },
      { word: 'prescribe', ja: '処方する' },
      { word: 'restraint', ja: '自制' },
      { word: 'offset', ja: '相殺する' },
      { word: 'sparingly', ja: '控えめに' },
    ],
    questions: [
      {
        id: 'r-b2-18-q1',
        prompt: '抗生物質が薬の中で異例だとされる理由はどれですか。',
        choices: [
          '使うことによって効果が失われていくから',
          '価格が高いから',
          '副作用が強いから',
          '保存が難しいから',
        ],
        correctIndex: 0,
        explanation: 'using it makes it worse と、投与のたびに耐性が進む仕組みが説明されています。',
        choiceNotes: [null, '価格は論点ではありません。', '副作用には触れていません。', '保存の話は出てきません。'],
      },
      {
        id: 'r-b2-18-q2',
        prompt: '医師の立場について筆者はどう述べていますか。',
        choices: [
          '目の前の相手への親切が、積み重なると害になる',
          '医師の判断は常に誤っている',
          '医師には裁量がない',
          '医師は統計を理解していない',
        ],
        correctIndex: 0,
        explanation: 'Multiply that kindness by several hundred million and the drug stops working. が該当します。',
        choiceNotes: [null, 'being kind と動機を認めています。', '処方の裁量は前提とされています。', '理解不足とは述べていません。'],
      },
      {
        id: 'r-b2-18-q3',
        prompt: '「個人の自制を答えとするのは誤り」だとする根拠はどれですか。',
        choices: [
          '供給量の大きな部分が健康な家畜に使われているから',
          '医師が指針を守らないから',
          '患者が薬を要求するから',
          '自制の効果が測定できないから',
        ],
        correctIndex: 0,
        explanation: 'It is fed to healthy farm animals ... and no amount of care in a clinic offsets that が根拠です。',
        choiceNotes: [null, '医師の不遵守は挙げられていません。', '患者の要求には触れていません。', '測定可能性の話ではありません。'],
      },
      {
        id: 'r-b2-18-q4',
        prompt: '「優れた政策であり、ひどい商売」とはどういう意味ですか。',
        choices: [
          '温存すべきという指針は正しいが、その薬では開発費を回収できない',
          '政策が企業に有利すぎる',
          '企業が政策を無視している',
          '政策の内容が誤っている',
        ],
        correctIndex: 0,
        explanation: 'used as little as possible and kept in reserve が正しい方針である一方、収益にならないことを指しています。',
        choiceNotes: [null, '企業に不利な構図です。', '無視ではなく撤退が示唆されています。', 'excellent policy と正しさは認めています。'],
      },
      {
        id: 'r-b2-18-q5',
        prompt: '筆者が示す結論はどれですか。',
        choices: [
          '公的資金で開発を賄うか、薬が存在しないかのどちらかしかない',
          '価格を上げれば市場が解決する',
          '家畜への使用を止めれば十分である',
          '新薬の開発はもう必要ない',
        ],
        correctIndex: 0,
        explanation: 'Either the public pays ... or the medicines do not exist. There is no third option. が結論です。',
        choiceNotes: [null, '控えめにしか売れない以上、価格では解決しないと述べています。', '家畜使用は問題の一部にすぎません。', '開発の不足を問題としています。'],
      },
    ],
  },
]
