import type { ReadingPassage } from '../types.ts'

// B2 追加分(r-b2-19 〜 r-b2-36)。本プロジェクト用に書き下ろした自作テキスト(外部からの転載なし)。
// 数字は表記ゆれと音声化のぶれを避けるため綴りで書き、所有格のアポストロフィは避ける。
// 設問は事実の検索に留めず、論の運び・筆者の立場・含意・事実と意見の区別を問う。

export const b2PassagesC: ReadingPassage[] = [
  {
    id: 'r-b2-19',
    level: 'B2',
    title: 'The Price of a Quiet Carriage',
    titleJa: '静かな車両の値段',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Several railway companies now run one carriage on which conversation and phone calls are discouraged. It costs nothing extra, and it is usually the first carriage to fill.',
      'The obvious next step would be to charge for it. If a seat there is worth more to passengers, a price would tell the company how much more, and the money could pay for another quiet carriage.',
      'The argument is clean and it has not been followed, which is interesting. Companies that have tested a paid quiet carriage report that it stops being quiet. Once people have paid, they feel entitled to make a short call, and a short call is all it takes.',
      'What holds the free carriage together is not enforcement but shared understanding. Nobody has bought a right, so nobody has a right to defend, and a passenger who forgets is corrected by a look rather than an argument.',
      'This is worth remembering wherever a good thing is provided informally. Putting a price on it does not simply add money to the arrangement. It replaces one set of reasons for behaving with another, and the new set is often weaker.',
    ],
    paragraphsJa: [
      'いくつかの鉄道会社は今、会話や通話を控えるよう求める車両を1両運行しています。追加料金はかからず、たいてい最初に埋まる車両です。',
      '次に来る当然の一手は、有料化でしょう。その座席が乗客にとってより価値があるなら、価格はどれだけ価値があるかを会社に伝え、その収入で静かな車両をもう1両用意できます。',
      'この議論はすっきりしていて、それでも実行されていません。そこが興味深いところです。有料の静かな車両を試した会社は、それが静かでなくなると報告しています。いったん支払えば、人は短い通話くらいしてよいと感じます。そして短い通話一本で十分に壊れるのです。',
      '無料の車両を保っているのは取り締まりではなく、共有された了解です。誰も権利を買っていないので、誰にも守るべき権利がありません。うっかりした乗客は、議論ではなく視線によって正されます。',
      'これは、良いものが非公式に提供されている場面すべてで覚えておく価値があります。値段を付けることは、その仕組みに単にお金を足すことではありません。ふるまう理由の一式を別の一式に置き換えることであり、新しい一式のほうが弱いことがしばしばあるのです。',
    ],
    glossary: [
      { word: 'carriage', ja: '車両' },
      { word: 'discourage', ja: '控えるよう求める' },
      { word: 'entitled', ja: '権利があると感じる' },
      { word: 'enforcement', ja: '取り締まり' },
      { word: 'shared understanding', ja: '共有された了解' },
      { word: 'informally', ja: '非公式に' },
      { word: 'arrangement', ja: '仕組み、取り決め' },
    ],
    questions: [
      {
        id: 'r-b2-19-q1',
        prompt: '有料化が「当然の一手」に見える理由はどれですか。',
        choices: [
          '価格が価値を測り、その収入で車両を増やせるから',
          '乗客が支払いを望んでいるから',
          '無料では利用者が少ないから',
          '法律で求められているから',
        ],
        correctIndex: 0,
        explanation: 'a price would tell the company how much more, and the money could pay for another quiet carriage が理由です。',
        choiceNotes: [null, '乗客の要望は述べられていません。', '最初に埋まると述べられています。', '法的要請の話は出てきません。'],
      },
      {
        id: 'r-b2-19-q2',
        prompt: '有料の静かな車両を試した会社の報告はどれですか。',
        choices: [
          '静かでなくなる',
          '収入が増えない',
          '乗客が減る',
          '苦情が減る',
        ],
        correctIndex: 0,
        explanation: 'it stops being quiet と報告されています。',
        choiceNotes: [null, '収入の話は出てきません。', '乗客数の話は出てきません。', '苦情の話は出てきません。'],
      },
      {
        id: 'r-b2-19-q3',
        prompt: '無料の車両が静けさを保てている理由はどれですか。',
        choices: [
          '誰も権利を買っておらず、守るべき権利がないから',
          '車掌が巡回しているから',
          '座席数が少ないから',
          '罰則があるから',
        ],
        correctIndex: 0,
        explanation: 'Nobody has bought a right, so nobody has a right to defend が理由です。',
        choiceNotes: [null, 'not enforcement と否定されています。', '座席数の話は出てきません。', '罰則の話は出てきません。'],
      },
      {
        id: 'r-b2-19-q4',
        prompt: '「議論ではなく視線によって正される」が示しているのはどれですか。',
        choices: [
          '規則ではなく暗黙の了解が秩序を保っていること',
          '乗客が互いに無関心であること',
          '車内が暗いこと',
          '会話が禁止されていること',
        ],
        correctIndex: 0,
        explanation: '前文の shared understanding を具体化した表現です。',
        choiceNotes: [null, '互いに反応しています。', '照明の話ではありません。', 'discouraged であって禁止ではありません。'],
      },
      {
        id: 'r-b2-19-q5',
        prompt: '最終段落で筆者が一般化している主張はどれですか。',
        choices: [
          '値付けは動機を置き換え、新しい動機は弱いことがある',
          '無料のサービスは常に優れている',
          '価格は正確に価値を反映する',
          '鉄道会社は利益を追うべきでない',
        ],
        correctIndex: 0,
        explanation: 'It replaces one set of reasons for behaving with another, and the new set is often weaker. が該当します。',
        choiceNotes: [null, '常にとは述べていません。', '反映しない例を挙げています。', '経営方針の主張ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-20',
    level: 'B2',
    title: 'What Counts as Waste',
    titleJa: '何を廃棄と数えるか',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A city that announces a recycling rate of sixty per cent is making a claim that sounds simple. It is in fact the result of a long series of choices about what to count.',
      'The figure is normally the weight of material collected for recycling divided by the weight of all household waste. Both halves of that fraction can be moved. Garden waste is heavy and easy to compost, so a city that collects a lot of it will look successful without changing anything about packaging.',
      'More importantly, the number describes collection rather than outcome. Material that is collected, shipped abroad and then buried still counts on the day the lorry leaves. Several countries reported excellent rates for years while the physical fate of the material was unknown to them.',
      'None of this means the figure is worthless. Cities that improved their collection genuinely did improve it, and the comparison between one year and the next within the same city is meaningful.',
      'The danger is in the league table. A number built for internal management becomes a public score, and the cheapest way to raise a score is rarely the same as the cheapest way to reduce harm. Anyone reading such a table should ask what was counted before asking who came first.',
    ],
    paragraphsJa: [
      'リサイクル率60パーセントと発表する都市は、単純に聞こえる主張をしています。実際にはそれは、何を数えるかについての長い選択の連なりの結果です。',
      'この数字はふつう、リサイクルのために回収された資源の重量を、家庭廃棄物全体の重量で割ったものです。この分数は、分子も分母も動かせます。庭のごみは重く、堆肥にしやすいので、それを多く回収する都市は、包装について何も変えずに成功して見えます。',
      'さらに重要なのは、この数字が結果ではなく回収を記述している点です。回収され、海外へ送られ、そのあと埋められた資源も、収集車が出発した日に計上されます。いくつかの国は何年も優秀な率を報告していましたが、その資源が物理的にどうなったかを自分たちで把握していませんでした。',
      'これは、この数字が無価値だという意味ではありません。回収を改善した都市は本当に改善したのですし、同じ都市の前年との比較には意味があります。',
      '危ういのは順位表です。内部管理のために作られた数字が公開の点数になると、点数を上げる最も安い方法は、害を減らす最も安い方法とはめったに一致しません。そうした表を読む人は、誰が1位かを尋ねる前に、何が数えられたのかを尋ねるべきです。',
    ],
    glossary: [
      { word: 'rate', ja: '率' },
      { word: 'fraction', ja: '分数' },
      { word: 'compost', ja: '堆肥にする' },
      { word: 'packaging', ja: '包装' },
      { word: 'outcome', ja: '結果' },
      { word: 'fate', ja: '行き着く先' },
      { word: 'league table', ja: '順位表' },
    ],
    questions: [
      {
        id: 'r-b2-20-q1',
        prompt: '庭のごみを多く回収する都市について述べられていることはどれですか。',
        choices: [
          '包装を変えずに成功して見える',
          '費用が下がる',
          '住民の満足度が上がる',
          '率が下がる',
        ],
        correctIndex: 0,
        explanation: 'will look successful without changing anything about packaging が該当します。',
        choiceNotes: [null, '費用の話は出てきません。', '満足度の話は出てきません。', '率は上がります。'],
      },
      {
        id: 'r-b2-20-q2',
        prompt: '筆者が「さらに重要」とする問題はどれですか。',
        choices: [
          '数字が結果ではなく回収を記述していること',
          '計測機器の精度',
          '発表の頻度',
          '住民の分別意識',
        ],
        correctIndex: 0,
        explanation: 'the number describes collection rather than outcome が該当します。',
        choiceNotes: [null, '機器の話は出てきません。', '頻度の話は出てきません。', '住民の意識は論点ではありません。'],
      },
      {
        id: 'r-b2-20-q3',
        prompt: '第4段落を置いた筆者の意図として最も適切なものはどれですか。',
        choices: [
          '批判を限定し、数字に意味がある範囲を認めるため',
          '主張を撤回するため',
          '別の話題へ移るため',
          '第3段落を否定するため',
        ],
        correctIndex: 0,
        explanation: 'None of this means the figure is worthless. と、有効な用途を認めています。',
        choiceNotes: [null, '撤回していません。', '同じ話題です。', '第3段落は否定されていません。'],
      },
      {
        id: 'r-b2-20-q4',
        prompt: '筆者が有意味だとしている比較はどれですか。',
        choices: [
          '同じ都市の前年との比較',
          '都市どうしの比較',
          '国どうしの比較',
          '企業との比較',
        ],
        correctIndex: 0,
        explanation: 'the comparison between one year and the next within the same city is meaningful とあります。',
        choiceNotes: [null, '順位表の危うさを指摘しています。', '国際比較も同じ問題を抱えます。', '企業比較は出てきません。'],
      },
      {
        id: 'r-b2-20-q5',
        prompt: '最終文が読者に求めていることはどれですか。',
        choices: [
          '順位を見る前に、何が数えられたかを確認すること',
          '順位表を無視すること',
          '自分の都市の順位を上げること',
          '統計の専門家に任せること',
        ],
        correctIndex: 0,
        explanation: 'should ask what was counted before asking who came first が該当します。',
        choiceNotes: [null, '無視せよとは述べていません。', '順位を上げることは批判の対象です。', '専門家任せは述べていません。'],
      },
    ],
  },
  {
    id: 'r-b2-21',
    level: 'B2',
    title: 'The Committee That Cannot Say No',
    titleJa: 'ノーと言えない委員会',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Every organisation of a certain size has a body that approves things. Its members are usually careful people, chosen because they are careful, and the results are rarely what anyone intended.',
      'Consider what happens to a member who approves a proposal that later fails. The failure has a date, a cost and a list of names attached to it. Consider what happens to a member who blocks a proposal that would have succeeded. Nothing happens, because the success never occurs and therefore cannot be counted.',
      'From this asymmetry everything else follows. The committee does not become cautious in the way it imagines. It becomes cautious about visible risk and indifferent to invisible cost, which is a different and much worse thing.',
      'The usual response is to demand more evidence before approval. This appears rigorous and it makes the problem larger, because the proposals that can supply the most evidence are the ones most similar to what has already been done.',
      'A better response is to record the refusals. If a committee had to publish what it declined and revisit those decisions after three years, the invisible column of the ledger would begin to have entries in it. Very few organisations do this, and the reason is not that it would be difficult.',
    ],
    paragraphsJa: [
      '一定の規模を超えた組織には、必ず物事を承認する機関があります。その委員は、慎重であるという理由で選ばれた慎重な人々であるのがふつうです。そして結果は、誰の意図とも異なるものになりがちです。',
      'のちに失敗した案を承認した委員に何が起きるか考えてみてください。その失敗には日付と費用と、名前の一覧が付いてきます。次に、成功したはずの案を止めた委員に何が起きるか考えてみてください。何も起きません。その成功は決して起きないので、数えることができないからです。',
      'この非対称から、あとはすべて導かれます。委員会は、自分が思っているような形では慎重になりません。目に見える危険には慎重になり、目に見えない損失には無関心になるのです。それは別のこと、しかもはるかに悪いことです。',
      'よくある対応は、承認の前にもっと証拠を求めることです。これは厳格に見え、そして問題を大きくします。最も多くの証拠を出せる案とは、すでに行われたことに最も似ている案だからです。',
      'より良い対応は、却下を記録することです。委員会が、退けた案を公表し、3年後にその判断を見直さなければならないとしたら、台帳の見えない側の欄にも記入が始まるでしょう。これを行う組織はごくわずかです。そしてその理由は、難しいからではありません。',
    ],
    glossary: [
      { word: 'approve', ja: '承認する' },
      { word: 'proposal', ja: '提案、案件' },
      { word: 'asymmetry', ja: '非対称' },
      { word: 'indifferent', ja: '無関心な' },
      { word: 'rigorous', ja: '厳格な' },
      { word: 'decline', ja: '却下する' },
      { word: 'ledger', ja: '台帳' },
    ],
    questions: [
      {
        id: 'r-b2-21-q1',
        prompt: '筆者が指摘する非対称の内容はどれですか。',
        choices: [
          '承認した失敗は記録されるが、止めた成功は存在しないため数えられない',
          '承認より却下のほうが手続きが重い',
          '委員によって権限の重さが違う',
          '失敗の費用が過小に見積もられる',
        ],
        correctIndex: 0,
        explanation: '第2段落の二つの場合の対比がそのまま非対称の内容です。',
        choiceNotes: [null, '手続きの重さは論じられていません。', '権限差の話は出てきません。', '見積もりの精度の話ではありません。'],
      },
      {
        id: 'r-b2-21-q2',
        prompt: '委員会が実際に慎重になる対象はどれですか。',
        choices: [
          '目に見える危険',
          'あらゆる危険',
          '長期の損失',
          '組織の評判',
        ],
        correctIndex: 0,
        explanation: 'cautious about visible risk and indifferent to invisible cost が該当します。',
        choiceNotes: [null, '見えない損失には無関心です。', '見えない損失に含まれます。', '評判は論点ではありません。'],
      },
      {
        id: 'r-b2-21-q3',
        prompt: '証拠を追加で求めることが問題を悪化させる理由はどれですか。',
        choices: [
          '証拠を多く出せる案は既存のものに似た案だから',
          '審査に時間がかかるから',
          '証拠の作成費が高いから',
          '委員が読まないから',
        ],
        correctIndex: 0,
        explanation: 'the proposals that can supply the most evidence are the ones most similar to what has already been done が理由です。',
        choiceNotes: [null, '所要時間は挙げられていません。', '費用は挙げられていません。', '読解の話は出てきません。'],
      },
      {
        id: 'r-b2-21-q4',
        prompt: '筆者が提案している対応はどれですか。',
        choices: [
          '却下した案を公表し、数年後に見直すこと',
          '委員の数を増やすこと',
          '承認基準を緩めること',
          '外部の専門家を入れること',
        ],
        correctIndex: 0,
        explanation: 'publish what it declined and revisit those decisions after three years が提案です。',
        choiceNotes: [null, '人数の話は出てきません。', '基準の緩和は述べていません。', '外部専門家の話は出てきません。'],
      },
      {
        id: 'r-b2-21-q5',
        prompt: '最終文「難しいからではありません」の含みはどれですか。',
        choices: [
          '実行されないのは技術的困難ではなく、都合の悪さのためである',
          '実行には高度な技術が要る',
          'すでに多くの組織が実行している',
          '規則で禁じられている',
        ],
        correctIndex: 0,
        explanation: '困難さを否定することで、実行されない別の理由を読者に推論させています。',
        choiceNotes: [null, '難しさを否定しています。', 'Very few organisations do this とあります。', '規制の話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-22',
    level: 'B2',
    title: 'When the Map Became the Territory',
    titleJa: '地図が土地になるとき',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A navigation app used to describe the roads. Now, in any city where most drivers follow one, it decides how the roads are used.',
      'The change happened without announcement. When a main road slows, the app sends a share of the traffic through the smaller streets beside it. Each individual instruction is reasonable, and the total effect is that a residential street built for twenty cars an hour receives two hundred.',
      'The residents of such a street have no one to complain to. The traffic is not the result of a plan that a council approved, and it can move again next week if a different route becomes faster. There is no document to object to and no meeting at which the decision was taken.',
      'Some cities have responded by making the small streets physically slower, with narrow entrances and raised surfaces. This works, and it is an odd sort of victory. A public authority is now writing rules in concrete because it cannot write them in software.',
      'The wider issue is not about traffic. Any system that gives individually sensible advice to a large number of people is making collective decisions, whether or not it accepts that description. Our procedures for arguing with such decisions were designed for bodies that meet, publish and can be voted out.',
    ],
    paragraphsJa: [
      'ナビゲーションのアプリは、かつて道路を記述するものでした。今では、運転者の多数がそれに従う都市において、道路がどう使われるかを決めています。',
      'この変化は告知なしに起きました。幹線道路の流れが悪くなると、アプリは交通の一部を、その脇の細い通りへ回します。個々の指示はどれも妥当です。そして総体としての効果は、1時間に20台を想定して造られた住宅街の通りが200台を受け取る、というものです。',
      'そうした通りの住民には、苦情を言う相手がいません。その交通は、議会が承認した計画の結果ではありませんし、別の経路が速くなれば来週にはまた移動します。異議を申し立てる文書もなければ、その決定が下された会議も存在しません。',
      '対応として、細い通りを物理的に遅くした都市もあります。入口を狭くし、路面を盛り上げるのです。これは効きます。そして奇妙な勝利でもあります。公的機関が今や、ソフトウェアに規則を書けないので、コンクリートに規則を書いているのです。',
      'より広い論点は交通の話ではありません。多数の人に個別には妥当な助言を与える仕組みは、それが自らをそう記述するかどうかにかかわらず、集団的な決定を下しています。私たちがそうした決定に異議を唱えるための手続きは、会議を開き、公表し、投票で退けられる機関のために設計されたものです。',
    ],
    glossary: [
      { word: 'navigation', ja: '経路案内' },
      { word: 'instruction', ja: '指示' },
      { word: 'residential', ja: '住宅の' },
      { word: 'object to', ja: '異議を申し立てる' },
      { word: 'raised surface', ja: '盛り上げた路面' },
      { word: 'collective', ja: '集団的な' },
      { word: 'procedure', ja: '手続き' },
    ],
    questions: [
      {
        id: 'r-b2-22-q1',
        prompt: '第1段落で述べられている変化はどれですか。',
        choices: [
          '道路を記述する道具から、道路の使われ方を決める仕組みへ',
          '有料から無料へ',
          '地図の精度が上がったこと',
          '運転者の数が増えたこと',
        ],
        correctIndex: 0,
        explanation: 'used to describe the roads. Now ... it decides how the roads are used. が該当します。',
        choiceNotes: [null, '料金の話は出てきません。', '精度の話ではありません。', '台数の話ではありません。'],
      },
      {
        id: 'r-b2-22-q2',
        prompt: '住宅街の通りについて述べられている数値の対比はどれですか。',
        choices: [
          '想定20台に対し実際200台',
          '想定200台に対し実際20台',
          '想定100台に対し実際200台',
          '想定20台に対し実際100台',
        ],
        correctIndex: 0,
        explanation: 'built for twenty cars an hour receives two hundred とあります。',
        choiceNotes: [null, '逆です。', '本文の数と違います。', '本文の数と違います。'],
      },
      {
        id: 'r-b2-22-q3',
        prompt: '住民が苦情を言えない理由はどれですか。',
        choices: [
          '異議を申し立てる文書も決定の会議も存在しないから',
          '議会が受け付けないから',
          '証拠が集まらないから',
          '住民の数が少ないから',
        ],
        correctIndex: 0,
        explanation: 'There is no document to object to and no meeting at which the decision was taken. が理由です。',
        choiceNotes: [null, '議会の対応は述べられていません。', '証拠の話は出てきません。', '人数の話は出てきません。'],
      },
      {
        id: 'r-b2-22-q4',
        prompt: '「コンクリートに規則を書いている」という表現の含意はどれですか。',
        choices: [
          '本来はソフトウェア側で扱うべき問題を物理設計で処理していること',
          '道路工事の費用が高いこと',
          'コンクリートが最良の素材であること',
          '規則が永続的であること',
        ],
        correctIndex: 0,
        explanation: 'because it cannot write them in software が、対応の不自然さを示しています。',
        choiceNotes: [null, '費用の話は出てきません。', '素材の評価ではありません。', '永続性の話ではありません。'],
      },
      {
        id: 'r-b2-22-q5',
        prompt: '最終段落で筆者が示す一般的な論点はどれですか。',
        choices: [
          '個別に妥当な助言を大量に与える仕組みは集団的決定を下している',
          '交通量の予測は不可能である',
          'アプリの利用を制限すべきである',
          '住民参加を増やすべきである',
        ],
        correctIndex: 0,
        explanation: 'is making collective decisions, whether or not it accepts that description が該当します。',
        choiceNotes: [null, '予測可能性の話ではありません。', '利用制限は主張していません。', '参加手続きの拡充は述べていません。'],
      },
    ],
  },
  {
    id: 'r-b2-23',
    level: 'B2',
    title: 'The Skill That Left with the Machine',
    titleJa: '機械とともに去った技能',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'When a task is automated, the usual question is how many jobs are lost. A more useful question is what happens to the people who remain.',
      'They are not doing the old job with a machine attached. They are doing a new job, which consists of watching the machine and taking over at the moments when it fails. Those moments are rare, unpredictable and by definition the hardest cases.',
      'This is where the difficulty sits. The routine work that has been removed was also the practice. A person who handled ordinary cases every day built the judgement needed for the strange ones. Take away the ordinary cases and the judgement has nowhere to come from.',
      'The problem is well documented in aviation, where crews spend most of a flight monitoring rather than flying, and it appears wherever the pattern repeats. Hospitals, power stations and financial systems all now employ people whose value lies in a form of expertise that their daily work no longer produces.',
      'The fix is not to slow down automation. It is to accept that practice must now be arranged deliberately rather than acquired as a by-product of the job. That costs money and produces nothing visible, which is why it is usually the first item removed from a budget.',
    ],
    paragraphsJa: [
      '仕事が自動化されるとき、ふつう問われるのは何人分の職が失われるかです。より有用な問いは、残った人に何が起きるか、です。',
      '彼らは、機械を付けただけの昔の仕事をしているのではありません。新しい仕事をしているのです。それは機械を見張り、機械が失敗する瞬間に引き継ぐという仕事です。その瞬間はまれで、予測できず、そして定義上、最も難しい事例です。',
      '困難はここにあります。取り除かれた定型的な仕事は、同時に訓練でもあったのです。日々ふつうの事例を扱っていた人は、そこから異常な事例に必要な判断力を作り上げていました。ふつうの事例を取り去れば、判断力の出どころがなくなります。',
      'この問題は航空の分野でよく記録されています。乗員は飛行時間の大半を、操縦ではなく監視に費やします。そして同じ型が繰り返されるところには、どこでも現れます。病院も、発電所も、金融の仕組みも、今や、日々の業務がもはや生み出さない種類の熟練にこそ価値がある人々を雇っています。',
      '解決策は自動化を遅らせることではありません。訓練は、仕事の副産物として得られるものではなく、意図的に設計しなければならないものになった、と受け入れることです。それには費用がかかり、目に見える成果を何も生みません。だからこそ、予算から真っ先に削られるのがふつうなのです。',
    ],
    glossary: [
      { word: 'automate', ja: '自動化する' },
      { word: 'take over', ja: '引き継ぐ' },
      { word: 'unpredictable', ja: '予測できない' },
      { word: 'routine', ja: '定型的な' },
      { word: 'judgement', ja: '判断力' },
      { word: 'aviation', ja: '航空' },
      { word: 'by-product', ja: '副産物' },
    ],
    questions: [
      {
        id: 'r-b2-23-q1',
        prompt: '筆者がより有用だとする問いはどれですか。',
        choices: [
          '残った人に何が起きるか',
          '何人分の職が失われるか',
          '費用がどれだけ下がるか',
          '導入にどれだけ時間がかかるか',
        ],
        correctIndex: 0,
        explanation: 'A more useful question is what happens to the people who remain. とあります。',
        choiceNotes: [null, 'usual question として退けられています。', '費用の話は出てきません。', '所要時間の話は出てきません。'],
      },
      {
        id: 'r-b2-23-q2',
        prompt: '残った人が担う仕事の性質はどれですか。',
        choices: [
          'まれで予測できない最難関の事例を引き継ぐこと',
          '定型的な処理を高速に行うこと',
          '機械を製造すること',
          '新人を教育すること',
        ],
        correctIndex: 0,
        explanation: 'rare, unpredictable and by definition the hardest cases が該当します。',
        choiceNotes: [null, '定型は取り除かれています。', '製造の話は出てきません。', '教育は結論部の別論点です。'],
      },
      {
        id: 'r-b2-23-q3',
        prompt: '筆者が指摘する核心的な困難はどれですか。',
        choices: [
          '取り除かれた定型業務が判断力の訓練でもあったこと',
          '機械の故障が増えたこと',
          '人員が足りないこと',
          '賃金が下がったこと',
        ],
        correctIndex: 0,
        explanation: 'The routine work that has been removed was also the practice. が核心です。',
        choiceNotes: [null, '故障の頻度は論点ではありません。', '人員数の話ではありません。', '賃金の話は出てきません。'],
      },
      {
        id: 'r-b2-23-q4',
        prompt: '航空の例を持ち出した意図はどれですか。',
        choices: [
          '同じ型がよく記録された分野として示すため',
          '航空が最も危険だと示すため',
          '自動化を止めるべきだと示すため',
          '乗員の技量が低いと示すため',
        ],
        correctIndex: 0,
        explanation: 'The problem is well documented in aviation ... and it appears wherever the pattern repeats が意図です。',
        choiceNotes: [null, '危険度の比較はしていません。', 'not to slow down automation と述べています。', '技量の批判ではありません。'],
      },
      {
        id: 'r-b2-23-q5',
        prompt: '訓練の予算が削られやすい理由として述べられているのはどれですか。',
        choices: [
          '費用がかかるのに目に見える成果を生まないから',
          '効果が否定されているから',
          '法律で任意とされているから',
          '現場が反対するから',
        ],
        correctIndex: 0,
        explanation: 'That costs money and produces nothing visible が理由です。',
        choiceNotes: [null, '効果は前提とされています。', '法の話は出てきません。', '現場の反対は述べられていません。'],
      },
    ],
  },
  {
    id: 'r-b2-24',
    level: 'B2',
    title: 'Nobody Reads the Terms',
    titleJa: '誰も規約を読まない',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Studies that measure how long people spend on a terms of service page find a figure of a few seconds. The documents themselves would take most readers well over an hour.',
      'The standard reaction is to blame the reader. This is comfortable and it does not survive contact with the arithmetic. A person who genuinely read every agreement they accepted in a year would spend several working weeks doing so, and would still be unable to negotiate a single line of any of them.',
      'That last point is the one that matters. Reading is only useful where refusal is possible. If the alternative to accepting is losing access to the service that your employer, your bank and your children all use, then the choice being described is not really a choice.',
      'Defenders of the current arrangement say that nobody is forced to use these services. In a narrow legal sense this is true. It is also true that nobody is forced to have a bank account, and we do not treat banking terms as freely chosen for that reason.',
      'What follows is not that agreements should be shorter, although they should. It is that consent obtained this way should carry less weight than consent normally does. A signature means something because it could have been withheld, and we have built a system in which, for practical purposes, it could not.',
    ],
    paragraphsJa: [
      '利用規約のページに人がどれだけ時間をかけるかを測った研究は、数秒という数字を出します。文書そのものは、大半の読み手にとって1時間をゆうに超える分量です。',
      '定番の反応は読み手を責めることです。それは気楽で、そして算数と突き合わせると生き残りません。1年間に同意したすべての契約を本当に読んだ人は、そのために数週間の労働時間を費やし、しかもそのどれ一行も交渉できないままなのです。',
      'その最後の点が重要です。読むことが役に立つのは、拒否が可能な場合だけです。受け入れないことの代わりが、勤務先も銀行も子どもたちも使っているサービスへの接続を失うことなのであれば、そこで語られている選択は、本当は選択ではありません。',
      '現状を擁護する側は、誰もこれらのサービスの利用を強制されていないと言います。狭い法的な意味では、それは正しい。同時に、誰も銀行口座を持つことを強制されていないというのも正しいことです。それでも私たちは、その理由で銀行の約款を自由に選ばれたものとは扱いません。',
      'ここから導かれるのは、契約を短くすべきだということではありません。もちろん短くすべきですが。導かれるのは、この方法で得られた同意は、ふつうの同意より軽く扱われるべきだ、ということです。署名に意味があるのは、それを拒めたはずだからです。そして私たちは、実務上それが拒めない仕組みを作ってしまいました。',
    ],
    glossary: [
      { word: 'terms of service', ja: '利用規約' },
      { word: 'arithmetic', ja: '算数、計算' },
      { word: 'agreement', ja: '契約、同意' },
      { word: 'negotiate', ja: '交渉する' },
      { word: 'refusal', ja: '拒否' },
      { word: 'consent', ja: '同意' },
      { word: 'withhold', ja: '与えないでおく' },
    ],
    questions: [
      {
        id: 'r-b2-24-q1',
        prompt: '筆者が「読み手を責める」反応を退ける根拠はどれですか。',
        choices: [
          '実際に読めば数週間かかり、しかも一行も交渉できないから',
          '規約は法的に無効だから',
          '読み手に読解力がないから',
          '規約は頻繁に変わるから',
        ],
        correctIndex: 0,
        explanation: 'would spend several working weeks ... and would still be unable to negotiate a single line が根拠です。',
        choiceNotes: [null, '無効だとは述べていません。', '読解力の問題にしていません。', '改訂頻度の話は出てきません。'],
      },
      {
        id: 'r-b2-24-q2',
        prompt: '筆者が「最も重要」だとする点はどれですか。',
        choices: [
          '読むことが有用なのは拒否が可能な場合だけであること',
          '文書が長すぎること',
          '表示が小さいこと',
          '専門用語が多いこと',
        ],
        correctIndex: 0,
        explanation: 'Reading is only useful where refusal is possible. が該当します。',
        choiceNotes: [null, '長さは副次的だとしています。', '表示の話は出てきません。', '用語の話は出てきません。'],
      },
      {
        id: 'r-b2-24-q3',
        prompt: '銀行口座の例はどのような役割を果たしていますか。',
        choices: [
          '「強制されていない」という反論が実質を伴わないと示すため',
          '銀行の規約が最も厳しいと示すため',
          '金融規制を強化すべきだと示すため',
          '口座開設が難しいと示すため',
        ],
        correctIndex: 0,
        explanation: 'we do not treat banking terms as freely chosen for that reason が、反論への切り返しです。',
        choiceNotes: [null, '厳しさの比較はしていません。', '規制強化は述べていません。', '手続きの難易は論点ではありません。'],
      },
      {
        id: 'r-b2-24-q4',
        prompt: '筆者が結論として導いていることはどれですか。',
        choices: [
          'この方法で得た同意は通常より軽く扱われるべきだ',
          '規約を短くすれば解決する',
          '利用者は規約を読むべきだ',
          'サービスを使うべきでない',
        ],
        correctIndex: 0,
        explanation: 'consent obtained this way should carry less weight than consent normally does が結論です。',
        choiceNotes: [null, 'although they should と副次扱いです。', '読むことの限界を論じています。', '利用の是非は論じていません。'],
      },
      {
        id: 'r-b2-24-q5',
        prompt: '最終文の署名の比喩が示しているのはどれですか。',
        choices: [
          '拒めない同意は、同意としての意味を失うということ',
          '署名は手書きであるべきだということ',
          '契約書は不要だということ',
          '署名の偽造が問題だということ',
        ],
        correctIndex: 0,
        explanation: 'A signature means something because it could have been withheld が該当します。',
        choiceNotes: [null, '形式の話ではありません。', '契約の廃止は述べていません。', '偽造の話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-25',
    level: 'B2',
    title: 'The Case Against the Pilot Project',
    titleJa: '試行事業への疑い',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A pilot project is meant to be a cautious first step. Try the idea in one place, measure what happens, and expand it if the results are good. Very few pilots are ever expanded, and the reason is not usually that they failed.',
      'A pilot is run by people who chose to run it. They are enthusiastic, they are watched, and they receive attention from senior managers that no ordinary service ever receives. The thing being tested is therefore never the thing that would later be rolled out.',
      'This is why results so often shrink on expansion. The second site has staff who were told to do it, a manager with four other priorities and no visiting researchers. Nothing has gone wrong. The conditions that produced the first result have simply been removed.',
      'A more honest design exists. Choose the site rather than letting it volunteer, give it no extra staff, and measure it after the person who introduced it has left. Almost nobody does this, because it is a test that a promising idea can fail.',
      'None of which argues against trying things in small ways first. It argues that a pilot answers a narrower question than it appears to. It tells you whether an idea can work somewhere, under favourable conditions, with people who want it. Whether it will work everywhere, under ordinary conditions, with people who did not ask for it, remains untested.',
    ],
    paragraphsJa: [
      '試行事業は慎重な第一歩のはずです。一か所で試し、何が起きるかを測り、結果が良ければ広げる。ところが広げられる試行はごくわずかであり、その理由はたいてい、失敗したからではありません。',
      '試行は、自らそれをやろうと選んだ人々によって運営されます。彼らは熱意があり、注目されており、通常の業務では決して受けられない上層部の関心を受けます。したがって、そこで試されているものは、後に全面展開されるものとは決して同じではありません。',
      'だからこそ、成果は展開時にしばしば縮みます。2番目の拠点には、やれと言われた職員と、ほかに4つの優先課題を抱えた管理職がいて、視察に来る研究者はいません。何も間違ってはいません。最初の結果を生んだ条件が、単に取り除かれただけなのです。',
      'より正直な設計もあります。拠点を立候補させずに指定すること、追加の人員を与えないこと、そしてそれを導入した本人が去ったあとに測定すること。これを行う人はほとんどいません。有望な着想が落第しうる試験だからです。',
      'これは、まず小さく試すこと自体への反論ではありません。試行は、見かけよりも狭い問いにしか答えていない、という指摘です。それは、ある着想が、好条件のもとで、それを望む人々とともに、どこかで機能しうるかを教えます。それが、ふつうの条件のもとで、それを求めなかった人々とともに、どこでも機能するかどうかは、試されないままです。',
    ],
    glossary: [
      { word: 'pilot project', ja: '試行事業' },
      { word: 'expand', ja: '拡大する' },
      { word: 'enthusiastic', ja: '熱意のある' },
      { word: 'roll out', ja: '全面展開する' },
      { word: 'shrink', ja: '縮む' },
      { word: 'favourable', ja: '好都合な' },
      { word: 'untested', ja: '試されていない' },
    ],
    questions: [
      {
        id: 'r-b2-25-q1',
        prompt: '試行が拡大されない理由について、筆者はどう述べていますか。',
        choices: [
          '失敗したからではないことが多い',
          'ほとんどが失敗するから',
          '予算が足りないから',
          '法的な制約があるから',
        ],
        correctIndex: 0,
        explanation: 'the reason is not usually that they failed とあります。',
        choiceNotes: [null, '失敗が主因ではないとしています。', '予算は主因として挙げられていません。', '法的制約の話は出てきません。'],
      },
      {
        id: 'r-b2-25-q2',
        prompt: '試行の条件として挙げられていないものはどれですか。',
        choices: [
          '外部から予算が別枠で付くこと',
          '運営者が自ら手を挙げていること',
          '注目されていること',
          '上層部の関心を受けること',
        ],
        correctIndex: 0,
        explanation: '第2段落に挙げられているのは自発性・注目・上層部の関心の3点です。',
        choiceNotes: [null, '挙げられています。', '挙げられています。', '挙げられています。'],
      },
      {
        id: 'r-b2-25-q3',
        prompt: '2番目の拠点で成果が縮む理由はどれですか。',
        choices: [
          '最初の結果を生んだ条件が取り除かれているから',
          '職員の能力が低いから',
          '着想そのものが誤りだから',
          '測定方法が変わるから',
        ],
        correctIndex: 0,
        explanation: 'The conditions that produced the first result have simply been removed. が理由です。',
        choiceNotes: [null, '能力の問題とはしていません。', 'Nothing has gone wrong. とあります。', '測定方法の変更は述べられていません。'],
      },
      {
        id: 'r-b2-25-q4',
        prompt: '「より正直な設計」が採用されない理由はどれですか。',
        choices: [
          '有望な着想が落第しうる試験だから',
          '費用が高いから',
          '時間がかかりすぎるから',
          '倫理的な問題があるから',
        ],
        correctIndex: 0,
        explanation: 'it is a test that a promising idea can fail が理由です。',
        choiceNotes: [null, '費用は挙げられていません。', '期間は挙げられていません。', '倫理の話は出てきません。'],
      },
      {
        id: 'r-b2-25-q5',
        prompt: '筆者の最終的な立場はどれですか。',
        choices: [
          '小さく試すこと自体は否定せず、試行が答える問いの狭さを指摘する',
          '試行事業は廃止すべきだ',
          '試行の結果は信用できない',
          '最初から全面展開すべきだ',
        ],
        correctIndex: 0,
        explanation: 'None of which argues against trying things in small ways first. と限定したうえでの主張です。',
        choiceNotes: [null, '廃止は主張していません。', '条件付きで有効だとしています。', '全面展開は勧めていません。'],
      },
    ],
  },
  {
    id: 'r-b2-26',
    level: 'B2',
    title: 'Who Pays for the Flood',
    titleJa: '水害の費用は誰が払うのか',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'After a serious flood, the same houses are usually rebuilt in the same places. This is described as resilience, and it is often something closer to the opposite.',
      'The reason is not that people are stubborn, although some are. It is that the incentives point that way. Insurance pays to restore what was there, not to move it somewhere safer. A household that wanted to relocate would receive less help than one that wanted to rebuild in the same spot.',
      'Where private insurance withdraws from an area, governments frequently step in with a public scheme. This is politically unavoidable and it has a consequence that is rarely stated. A price signal that would have discouraged building in the worst places is removed, and building continues.',
      'The counter-argument deserves a proper hearing. Communities are not simply collections of buildings, and telling a village of four hundred people that it is uneconomic is a serious thing to do. Many of the households with the least capacity to move are in exactly the places most at risk.',
      'But the choice is not between compassion and arithmetic. It is between paying to move people once, with notice and a say in where they go, and paying to rebuild repeatedly until an event arrives that is too large to rebuild after. The second option is more expensive and it is the one we keep choosing, because its costs arrive in instalments and never carry anyone name.',
    ],
    paragraphsJa: [
      '深刻な水害のあと、たいてい同じ家が同じ場所に建て直されます。これは強靭さと表現されますが、しばしばその反対に近いものです。',
      '理由は人々が頑固だからではありません。もっとも、頑固な人もいますが。理由は、誘因がそちらを向いているからです。保険は、そこにあったものを元に戻すために払われるのであって、より安全な場所へ移すために払われるのではありません。転居したい世帯は、同じ場所に建て直したい世帯より少ない支援しか受け取れません。',
      '民間保険がある地域から撤退すると、政府はしばしば公的な制度で肩代わりします。これは政治的に避けられず、そしてめったに口にされない帰結を伴います。最悪の場所への建築を思いとどまらせたはずの価格の合図が消え、建築は続くのです。',
      '反論はきちんと聞かれるべきものです。共同体は建物の集まりではありませんし、400人の村に対して採算が合わないと告げることは重大な行為です。移る余力が最も少ない世帯こそ、最も危険な場所にいることが多いのです。',
      'しかし選択肢は、思いやりと算数のあいだにあるのではありません。予告と行き先への発言権を伴って人々を一度移す費用を払うか、それとも、その後には建て直せないほど大きな出来事が来るまで、繰り返し建て直す費用を払うか、のあいだにあります。二つ目のほうが高くつきます。そして私たちが選び続けているのはそちらです。その費用は分割で到着し、決して誰の名前も背負わないからです。',
    ],
    glossary: [
      { word: 'resilience', ja: '強靭さ、回復力' },
      { word: 'stubborn', ja: '頑固な' },
      { word: 'incentive', ja: '誘因' },
      { word: 'relocate', ja: '転居する' },
      { word: 'withdraw', ja: '撤退する' },
      { word: 'uneconomic', ja: '採算が合わない' },
      { word: 'in instalments', ja: '分割で' },
    ],
    questions: [
      {
        id: 'r-b2-26-q1',
        prompt: '同じ場所に建て直される主な理由として述べられているのはどれですか。',
        choices: [
          '保険が現状復旧に払われ、転居には少ない支援しか出ないから',
          '住民が頑固だから',
          '安全な土地がないから',
          '建て直しのほうが工期が短いから',
        ],
        correctIndex: 0,
        explanation: 'Insurance pays to restore what was there, not to move it somewhere safer. が理由です。',
        choiceNotes: [null, 'although some are と副次扱いです。', '土地の有無は述べられていません。', '工期の話は出てきません。'],
      },
      {
        id: 'r-b2-26-q2',
        prompt: '公的制度が肩代わりすることの「めったに口にされない帰結」はどれですか。',
        choices: [
          '危険地への建築を抑える価格の合図が消えること',
          '保険料が上がること',
          '民間保険が戻ってくること',
          '住民の負担が増えること',
        ],
        correctIndex: 0,
        explanation: 'A price signal that would have discouraged building ... is removed が該当します。',
        choiceNotes: [null, '保険料の変化は述べられていません。', '撤退したままです。', '負担増は述べられていません。'],
      },
      {
        id: 'r-b2-26-q3',
        prompt: '第4段落で筆者が認めている点はどれですか。',
        choices: [
          '移る余力の少ない世帯ほど危険地にいることが多い',
          '共同体の移転は容易である',
          '採算だけで判断すべきである',
          '反論には根拠がない',
        ],
        correctIndex: 0,
        explanation: 'the least capacity to move are in exactly the places most at risk が該当します。',
        choiceNotes: [null, '重大な行為だとしています。', '算数だけの問題ではないとしています。', 'deserves a proper hearing と述べています。'],
      },
      {
        id: 'r-b2-26-q4',
        prompt: '筆者が示す本当の選択肢はどれですか。',
        choices: [
          '予告付きで一度移す費用か、繰り返し建て直す費用か',
          '思いやりか算数か',
          '民間保険か公的制度か',
          '転居か放置か',
        ],
        correctIndex: 0,
        explanation: 'It is between paying to move people once ... and paying to rebuild repeatedly が該当します。',
        choiceNotes: [null, 'not between compassion and arithmetic と否定されています。', '保険の主体は前段の論点です。', '放置は選択肢として挙げられていません。'],
      },
      {
        id: 'r-b2-26-q5',
        prompt: '高くつく選択肢が選ばれ続ける理由として述べられているのはどれですか。',
        choices: [
          '費用が分割で到着し、誰の名前も背負わないから',
          '住民が投票で選ぶから',
          '費用が実際には安いから',
          '技術的に容易だから',
        ],
        correctIndex: 0,
        explanation: 'its costs arrive in instalments and never carry anyone name が理由です。',
        choiceNotes: [null, '投票の話は出てきません。', 'more expensive とされています。', '技術の話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-27',
    level: 'B2',
    title: 'The Slow Death of the Local Paper',
    titleJa: '地方紙が消えていく',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'When a local newspaper closes, the usual reaction is a mild regret about tradition. The measurable effects are stranger and larger than that.',
      'Researchers who compared towns that lost a paper with similar towns that kept one found that borrowing costs for the local council rose afterwards. Lenders, it turns out, had been relying on the paper to notice mistakes, and priced the new uncertainty accordingly.',
      'Other findings point the same way. Fewer people stand for local election. Those who do are more likely to be from the same party as the last person, and turnout falls. None of this is caused by a shortage of information in general, since the same towns have more media available than ever.',
      'What disappeared was not information but attention of a specific kind. National outlets will cover a scandal in a small town once it is large. Nobody covers the planning committee every Tuesday, and it is the coverage of the ordinary Tuesday that changes how the committee behaves.',
      'It is tempting to look for a business model that brings the papers back. The harder possibility is that the function was always paid for accidentally, by advertisements for cars and houses that now appear elsewhere, and that anything which replaces it will have to be paid for on purpose.',
    ],
    paragraphsJa: [
      '地方紙が廃刊になると、よくある反応は伝統への軽い惜しみです。測定できる影響は、それより奇妙で、大きいものです。',
      '新聞を失った町と、新聞が残った類似の町を比べた研究者たちは、その後に地方自治体の借入費用が上昇することを見いだしました。貸し手は、誤りに気づく役目を新聞に頼っており、新たに生じた不確かさをそのぶん価格に織り込んでいたのです。',
      'ほかの知見も同じ方向を指します。地方選挙に立候補する人が減ります。立候補する人は前任者と同じ政党である可能性が高くなり、投票率は下がります。これらは情報一般の不足によるものではありません。同じ町で利用できるメディアは、かつてないほど多いのですから。',
      '消えたのは情報ではなく、特定の種類の注意でした。全国の媒体は、小さな町の不祥事が大きくなれば取り上げます。しかし毎週火曜の都市計画委員会を取材する人はいません。そして委員会のふるまいを変えるのは、ふつうの火曜の報道なのです。',
      '新聞を復活させる事業モデルを探したくなります。より厄介な可能性は、その機能がもともと偶然に賄われていたということです。今は別の場所に載るようになった、車や住宅の広告によって。そしてそれに代わるものは何であれ、意図的に費用を払われなければならないということです。',
    ],
    glossary: [
      { word: 'regret', ja: '惜しむ気持ち' },
      { word: 'borrowing cost', ja: '借入費用' },
      { word: 'lender', ja: '貸し手' },
      { word: 'uncertainty', ja: '不確かさ' },
      { word: 'stand for election', ja: '立候補する' },
      { word: 'turnout', ja: '投票率' },
      { word: 'coverage', ja: '報道' },
    ],
    questions: [
      {
        id: 'r-b2-27-q1',
        prompt: '研究が示した最初の効果はどれですか。',
        choices: [
          '自治体の借入費用が上昇した',
          '人口が減少した',
          '税収が減った',
          '犯罪が増えた',
        ],
        correctIndex: 0,
        explanation: 'borrowing costs for the local council rose afterwards とあります。',
        choiceNotes: [null, '人口の話は出てきません。', '税収の話は出てきません。', '犯罪の話は出てきません。'],
      },
      {
        id: 'r-b2-27-q2',
        prompt: '貸し手が価格を変えた理由はどれですか。',
        choices: [
          '誤りに気づく役目を新聞に頼っていたから',
          '自治体が資料を出さなくなったから',
          '金利が上がったから',
          '住民が減ったから',
        ],
        correctIndex: 0,
        explanation: 'had been relying on the paper to notice mistakes が理由です。',
        choiceNotes: [null, '資料提供の話は出てきません。', '一般金利の話ではありません。', '人口の話は出てきません。'],
      },
      {
        id: 'r-b2-27-q3',
        prompt: '筆者が「情報一般の不足ではない」と断る理由はどれですか。',
        choices: [
          '同じ町で使えるメディアはかつてなく多いから',
          '住民が情報を求めていないから',
          '新聞は元々読まれていなかったから',
          '全国紙が代わりを務めているから',
        ],
        correctIndex: 0,
        explanation: 'the same towns have more media available than ever が理由です。',
        choiceNotes: [null, '需要の話は出てきません。', '購読状況の話は出てきません。', '全国紙は大きな事件しか扱いません。'],
      },
      {
        id: 'r-b2-27-q4',
        prompt: '「ふつうの火曜の報道」が意味しているのはどれですか。',
        choices: [
          '事件でない日常的な会議の継続的な取材',
          '週1回の特集記事',
          '選挙期間中の報道',
          '不祥事の追跡報道',
        ],
        correctIndex: 0,
        explanation: 'Nobody covers the planning committee every Tuesday が指す内容です。',
        choiceNotes: [null, '特集の話ではありません。', '選挙報道ではありません。', '不祥事は全国媒体が扱うとされています。'],
      },
      {
        id: 'r-b2-27-q5',
        prompt: '最終段落で筆者が示す「より厄介な可能性」はどれですか。',
        choices: [
          'その機能は広告収入で偶然に賄われており、今後は意図的な負担が要る',
          '新聞は今後も自然に復活する',
          '読者が費用を払うべきだ',
          '広告主が責任を負うべきだ',
        ],
        correctIndex: 0,
        explanation: 'was always paid for accidentally ... will have to be paid for on purpose が該当します。',
        choiceNotes: [null, '自然な復活は述べていません。', '負担者は特定していません。', '広告主の責任は述べていません。'],
      },
    ],
  },
  {
    id: 'r-b2-28',
    level: 'B2',
    title: 'A Degree and What It Signals',
    titleJa: '学位が伝えているもの',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Graduates earn more than non-graduates, and the gap has been stable for decades. The usual explanation is that they learned things that employers need.',
      'A competing explanation is less comfortable. On this account, much of the value of a degree lies in what completing it proves about a person, rather than in what the person now knows. Finishing three years of assessed work demonstrates persistence, a tolerance for boredom and the ability to hand things in.',
      'Distinguishing the two is genuinely hard, because both predict the same wage gap. The most useful evidence comes from students who completed almost all of a degree and then left. If knowledge were the whole story, they should earn nearly as much as those who finished. They do not, and the gap appears sharply at the point where the certificate is issued.',
      'This does not mean that nothing is learned, which would be an absurd conclusion. It means that a system built to teach is also functioning as an expensive filter, and that the two purposes are difficult to separate once they are combined.',
      'The practical question is who pays for the filter. At present it is largely the student, who takes on debt for a process that partly exists to save employers the cost of assessing people themselves. Whatever one thinks of that arrangement, it should at least be described accurately before it is defended.',
    ],
    paragraphsJa: [
      '大卒者は非大卒者より多く稼ぎ、その差は何十年も安定しています。通常の説明は、雇用主が必要とすることを彼らが学んだから、というものです。',
      'これと競合する説明は、もう少し居心地の悪いものです。この見方では、学位の価値の多くは、その人が今何を知っているかではなく、それを修了したことがその人について何を証明するかにあります。評価を伴う3年間の課程を終えることは、粘り強さ、退屈への耐性、そして期限内に提出する能力を示します。',
      '二つを区別するのは本当に難しいことです。どちらも同じ賃金差を予測するからです。最も有用な証拠は、学位のほぼ全課程を修了してから去った学生から得られます。知識がすべてなら、彼らは修了者とほぼ同額を稼ぐはずです。実際にはそうならず、その差は証書が発行される地点で鋭く現れます。',
      'これは何も学ばれていないという意味ではありません。それは馬鹿げた結論です。意味するのは、教えるために作られた仕組みが、同時に高価なふるいとしても機能しており、いったん結合したこの二つの目的は切り離しにくいということです。',
      '実務的な問いは、そのふるいの費用を誰が払うのか、です。現状では主に学生であり、彼らは、雇用主が自ら人を評価する費用を節約するために一部存在している過程のために、借金を背負います。この配置をどう考えるにせよ、擁護する前に、まずは正確に記述されるべきです。',
    ],
    glossary: [
      { word: 'graduate', ja: '大卒者' },
      { word: 'assessed', ja: '評価を伴う' },
      { word: 'persistence', ja: '粘り強さ' },
      { word: 'tolerance', ja: '耐性' },
      { word: 'certificate', ja: '証書' },
      { word: 'absurd', ja: '馬鹿げた' },
      { word: 'filter', ja: 'ふるい' },
    ],
    questions: [
      {
        id: 'r-b2-28-q1',
        prompt: '「競合する説明」の内容はどれですか。',
        choices: [
          '学位の価値の多くは、修了が人について証明する内容にある',
          '学位の価値は知識の量で決まる',
          '学位に価値はない',
          '学位の価値は大学の名前で決まる',
        ],
        correctIndex: 0,
        explanation: 'what completing it proves about a person が該当します。',
        choiceNotes: [null, 'それが通常の説明です。', '価値は認めています。', '大学名の話は出てきません。'],
      },
      {
        id: 'r-b2-28-q2',
        prompt: '二つの説明を区別する証拠として挙げられているのはどれですか。',
        choices: [
          'ほぼ全課程を終えてから去った学生の賃金',
          '卒業生の満足度調査',
          '雇用主への聞き取り',
          '学生の成績分布',
        ],
        correctIndex: 0,
        explanation: 'students who completed almost all of a degree and then left が該当します。',
        choiceNotes: [null, '満足度は出てきません。', '聞き取りは出てきません。', '成績分布は出てきません。'],
      },
      {
        id: 'r-b2-28-q3',
        prompt: 'その証拠から導かれることはどれですか。',
        choices: [
          '賃金差は証書の発行地点で鋭く現れる',
          '賃金差は学年ごとに滑らかに増える',
          '中退者も同程度に稼ぐ',
          '賃金差は存在しない',
        ],
        correctIndex: 0,
        explanation: 'the gap appears sharply at the point where the certificate is issued が該当します。',
        choiceNotes: [null, '滑らかではなく鋭い差です。', 'They do not と否定されています。', '差は安定して存在します。'],
      },
      {
        id: 'r-b2-28-q4',
        prompt: '筆者が明確に退けている結論はどれですか。',
        choices: [
          '大学では何も学ばれていない',
          '学位はふるいとしても機能している',
          '二つの目的は切り離しにくい',
          '費用の負担者を問うべきだ',
        ],
        correctIndex: 0,
        explanation: 'which would be an absurd conclusion と明示的に退けています。',
        choiceNotes: [null, '筆者の主張です。', '筆者の主張です。', '筆者の問いです。'],
      },
      {
        id: 'r-b2-28-q5',
        prompt: '最終文で筆者が求めていることはどれですか。',
        choices: [
          '擁護する前に、まず仕組みを正確に記述すること',
          '学費を無償化すること',
          '雇用主に費用を負担させること',
          '学位制度を廃止すること',
        ],
        correctIndex: 0,
        explanation: 'it should at least be described accurately before it is defended が該当します。',
        choiceNotes: [null, '無償化は主張していません。', '負担者の変更までは主張していません。', '廃止は主張していません。'],
      },
    ],
  },
  {
    id: 'r-b2-29',
    level: 'B2',
    title: 'The Ward with No Windows',
    titleJa: '窓のない病棟',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Hospital buildings are designed around the movement of staff and equipment. This is not a failure of imagination. A nurse who walks an extra thirty metres for every task walks several kilometres in a shift, and that distance comes out of patient care.',
      'The trouble is that this logic has no natural stopping point. Every metre saved is a metre justified, and the result is a deep building in which the rooms that people occupy for weeks sit far from any outside wall.',
      'The evidence on what that costs has been available since the nineteen eighties. Patients in rooms with a view of anything outside use fewer painkillers and leave earlier. The effect is small for a single patient and substantial across a building.',
      'It is worth being careful here. The early studies were small, and the effect has sometimes been overstated by people who wanted architecture to matter more than it does. Later work has confirmed a real effect while reducing its size.',
      'What has not changed is the asymmetry in how the two considerations enter the design. Walking distances are calculated by an engineer and appear in the plan. Recovery time appears nowhere in the plan, and it is paid for by a different budget in a later year. A building will always favour whichever of its effects can be counted at the moment it is drawn.',
    ],
    paragraphsJa: [
      '病院の建物は、職員と機材の動線を中心に設計されます。これは想像力の欠如ではありません。1つの作業ごとに30メートル余分に歩く看護師は、1回の勤務で数キロを歩くことになり、その距離は患者のケアから差し引かれます。',
      '問題は、この論理に自然な停止点がないことです。節約された1メートルはどれも正当化された1メートルであり、その結果は奥行きの深い建物です。そこでは、人が何週間も過ごす部屋が、外壁からはるかに離れた場所に置かれます。',
      'その代償についての証拠は1980年代から存在します。外の何かが見える部屋の患者は、鎮痛剤の使用が少なく、退院が早くなります。この効果は患者一人では小さく、建物全体では相当な大きさになります。',
      'ここは慎重であるべきところです。初期の研究は規模が小さく、その効果は、建築が実際以上に重要であってほしいと願う人々によって誇張されることもありました。その後の研究は、効果の実在を確かめつつ、その大きさを下方修正しています。',
      '変わっていないのは、二つの考慮事項が設計に入ってくる仕方の非対称です。歩行距離は技術者が計算し、図面に現れます。回復期間は図面のどこにも現れず、後の年度に別の予算から支払われます。建物は常に、それが描かれる時点で数えられるほうの効果を優遇します。',
    ],
    glossary: [
      { word: 'ward', ja: '病棟' },
      { word: 'equipment', ja: '機材' },
      { word: 'shift', ja: '勤務' },
      { word: 'justify', ja: '正当化する' },
      { word: 'painkiller', ja: '鎮痛剤' },
      { word: 'overstate', ja: '誇張する' },
      { word: 'consideration', ja: '考慮事項' },
    ],
    questions: [
      {
        id: 'r-b2-29-q1',
        prompt: '職員の動線を優先する設計を、筆者はどう評価していますか。',
        choices: [
          '想像力の欠如ではなく、根拠のある判断だとしている',
          '完全な誤りだとしている',
          '費用削減だけが目的だとしている',
          '古い慣習にすぎないとしている',
        ],
        correctIndex: 0,
        explanation: 'This is not a failure of imagination. と、看護師の歩行距離の説明が続きます。',
        choiceNotes: [null, '誤りとは述べていません。', '費用の話ではありません。', '慣習だとは述べていません。'],
      },
      {
        id: 'r-b2-29-q2',
        prompt: '「自然な停止点がない」とはどういう意味ですか。',
        choices: [
          '距離短縮の正当化がどこまでも続き、奥行きの深い建物になること',
          '工事が終わらないこと',
          '設計者が交代し続けること',
          '予算に上限がないこと',
        ],
        correctIndex: 0,
        explanation: 'Every metre saved is a metre justified に続く結果が述べられています。',
        choiceNotes: [null, '工期の話ではありません。', '人事の話ではありません。', '予算の話ではありません。'],
      },
      {
        id: 'r-b2-29-q3',
        prompt: '外が見える部屋の効果として述べられているのはどれですか。',
        choices: [
          '鎮痛剤の使用が減り、退院が早まる',
          '感染症が減る',
          '看護師の負担が減る',
          '入院費が下がる',
        ],
        correctIndex: 0,
        explanation: 'use fewer painkillers and leave earlier とあります。',
        choiceNotes: [null, '感染の話は出てきません。', '職員の負担は別の論点です。', '費用の話は出てきません。'],
      },
      {
        id: 'r-b2-29-q4',
        prompt: '第4段落を置いた筆者の意図はどれですか。',
        choices: [
          '証拠の扱いに慎重さを示し、誇張と実在を切り分けるため',
          '第3段落を撤回するため',
          '建築家を批判するため',
          '研究を無効とするため',
        ],
        correctIndex: 0,
        explanation: 'confirmed a real effect while reducing its size が、その慎重な位置づけです。',
        choiceNotes: [null, '効果の実在は認めています。', '建築家批判ではありません。', '無効とはしていません。'],
      },
      {
        id: 'r-b2-29-q5',
        prompt: '最終段落の非対称の内容はどれですか。',
        choices: [
          '歩行距離は図面に現れ、回復期間は現れず別年度の別予算になること',
          '職員と患者の人数差',
          '建設費と維持費の差',
          '新病院と旧病院の差',
        ],
        correctIndex: 0,
        explanation: 'Walking distances ... appear in the plan. Recovery time appears nowhere in the plan が該当します。',
        choiceNotes: [null, '人数の話ではありません。', '費目の対比ではありません。', '新旧の比較ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-30',
    level: 'B2',
    title: 'What an Old Building Is For',
    titleJa: '古い建物は何のためにあるのか',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Arguments about protecting old buildings are usually conducted as though beauty were the only value at stake. That framing loses the argument more often than it wins it.',
      'The stronger case is economic and it is rarely made. A street of old buildings contains small units with different owners, cheap upper floors and awkward spaces that no developer would build today. Those awkward spaces are where a business with no money can start.',
      'Replace the street with a single new block and the arithmetic changes. New floor space must earn a return on recent construction costs, which sets a rent that only established firms can pay. The building may be better in every measurable way and still support a narrower range of activity.',
      'The counter-argument is serious. Cities need housing, old buildings are often expensive to heat, and protecting everything is a way of protecting whoever already owns property. A rule that freezes a district in place will produce a museum with a housing shortage attached to it.',
      'The reasonable position lies between these, and it depends on being clear about which value is doing the work. If a building is protected because it is beautiful, say so and accept the cost. If it is protected because cheap awkward space is scarce and hard to rebuild, then say that instead, because it points to a different rule and a different set of buildings.',
    ],
    paragraphsJa: [
      '古い建物を守ることをめぐる議論は、たいてい美しさだけが争点であるかのように行われます。その枠組みは、議論に勝つよりも負けることのほうが多いのです。',
      'より強い論拠は経済的なもので、そしてめったに持ち出されません。古い建物の並ぶ通りには、所有者の異なる小さな区画、安い上階、そして今日どの開発業者も造らないような使い勝手の悪い空間があります。その使い勝手の悪い空間こそ、資金のない事業が始められる場所です。',
      'その通りを新しい建物1棟に置き換えると、算数が変わります。新しい床面積は、最近の建設費に見合う利回りを稼がなければならず、それは既存の企業にしか払えない賃料を設定します。その建物は測定できるあらゆる面で優れていながら、支えられる活動の幅は狭くなりうるのです。',
      '反論は真剣に受け止めるべきものです。都市には住宅が必要ですし、古い建物は暖房費が高くつくことが多く、すべてを守ることは、すでに不動産を持っている人を守ることでもあります。ある地区をその場に凍結する規則は、住宅不足を付属させた博物館を生むでしょう。',
      '妥当な立場はその中間にあり、それは、どの価値が実際に働いているのかを明確にできるかにかかっています。美しいから守るのなら、そう言って、その費用を引き受けること。安くて使い勝手の悪い空間が希少で作り直しにくいから守るのなら、そう言うこと。そちらは別の規則と、別の建物群を指し示すからです。',
    ],
    glossary: [
      { word: 'at stake', ja: '争点となっている' },
      { word: 'framing', ja: '枠組みの立て方' },
      { word: 'unit', ja: '区画' },
      { word: 'awkward', ja: '使い勝手の悪い' },
      { word: 'return', ja: '利回り' },
      { word: 'established', ja: '既存の、地位のある' },
      { word: 'scarce', ja: '希少な' },
    ],
    questions: [
      {
        id: 'r-b2-30-q1',
        prompt: '筆者が「より強い論拠」と呼ぶものはどれですか。',
        choices: [
          '経済的な論拠',
          '美しさの論拠',
          '歴史的な論拠',
          '環境上の論拠',
        ],
        correctIndex: 0,
        explanation: 'The stronger case is economic and it is rarely made. とあります。',
        choiceNotes: [null, '負けやすい枠組みとされています。', '歴史は挙げられていません。', '暖房費は反論側にあります。'],
      },
      {
        id: 'r-b2-30-q2',
        prompt: '「使い勝手の悪い空間」の価値はどこにあると述べられていますか。',
        choices: [
          '資金のない事業が始められる場所であること',
          '観光客を集めること',
          '建設費が安いこと',
          '歴史的価値があること',
        ],
        correctIndex: 0,
        explanation: 'where a business with no money can start が該当します。',
        choiceNotes: [null, '観光の話は出てきません。', '建設費ではなく賃料の話です。', '歴史的価値は論じられていません。'],
      },
      {
        id: 'r-b2-30-q3',
        prompt: '新しい建物1棟に置き換えたときに起きることはどれですか。',
        choices: [
          '賃料が上がり、支えられる活動の幅が狭くなる',
          '賃料が下がり、活動が多様になる',
          '所有者が増える',
          '床面積が減る',
        ],
        correctIndex: 0,
        explanation: 'sets a rent that only established firms can pay ... support a narrower range of activity が該当します。',
        choiceNotes: [null, '逆です。', '単一の建物になります。', '床面積の減少は述べられていません。'],
      },
      {
        id: 'r-b2-30-q4',
        prompt: '第4段落で認められている反論に含まれないものはどれですか。',
        choices: [
          '古い建物は耐震性に問題がある',
          '都市には住宅が必要である',
          '古い建物は暖房費が高い',
          '保護は既存の所有者を守ることになる',
        ],
        correctIndex: 0,
        explanation: '第4段落に挙げられているのは住宅・暖房費・所有者保護の3点です。',
        choiceNotes: [null, '挙げられています。', '挙げられています。', '挙げられています。'],
      },
      {
        id: 'r-b2-30-q5',
        prompt: '筆者が最終段落で求めていることはどれですか。',
        choices: [
          'どの価値を理由に守るのかを明示すること',
          'すべての古い建物を守ること',
          '古い建物をすべて建て替えること',
          '住民投票で決めること',
        ],
        correctIndex: 0,
        explanation: 'it depends on being clear about which value is doing the work が該当します。',
        choiceNotes: [null, '全面保護は退けています。', '全面建て替えも支持していません。', '決定手続きの話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-31',
    level: 'B2',
    title: 'The Trouble with Volunteers',
    titleJa: 'ボランティアという難題',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A service run by volunteers is often described as a community coming together. Sometimes it is. It is also, quite often, a paid service that stopped being paid for while nobody was looking.',
      'The distinction matters because the two behave differently under strain. A library staffed by employees that loses a member of staff advertises the post. A library staffed by volunteers that loses its most reliable person may simply reduce its opening hours, and nothing in the accounts records what happened.',
      'There is a second difference that is easy to miss. Volunteers are not distributed evenly. The neighbourhoods with the most people who have time, confidence and transport are usually the neighbourhoods that need the service least. A model that works in one district can fail entirely three kilometres away, and the failure will look like a lack of community spirit rather than a design fault.',
      'None of this is an argument against volunteering, which produces things that paid work does not. A person who chooses to be there changes the character of a place, and no wage buys that.',
      'The argument is against using volunteers as a budget line. When a service is genuinely optional, unpaid help is a gift. When it is something a town cannot do without, calling it voluntary does not make it optional. It only moves the risk onto whoever turns up.',
    ],
    paragraphsJa: [
      'ボランティアが運営するサービスは、しばしば地域が力を合わせたものとして語られます。実際にそうであることもあります。しかしそれは、かなりの頻度で、誰も見ていないうちに有償ではなくなった有償サービスでもあります。',
      'この区別が重要なのは、負荷がかかったときの挙動が違うからです。職員で運営される図書館は、職員が1人抜ければ求人を出します。ボランティアで運営される図書館は、最も頼りになる人が抜ければ、単に開館時間を減らすかもしれません。そして会計上、何が起きたのかを記録するものは何もありません。',
      '見落としやすい第二の違いがあります。ボランティアは均等に分布していません。時間と自信と移動手段を持つ人が最も多い地域は、たいていそのサービスを最も必要としない地域です。ある地区で機能する方式が、3キロ先ではまったく機能しないことがあります。そしてその失敗は、設計の欠陥ではなく地域の連帯の欠如のように見えるのです。',
      'これはボランティア活動への反論ではありません。それは有償労働が生み出さないものを生みます。そこにいることを自分で選んだ人は、その場所の性格を変えます。そしてそれを買える賃金はありません。',
      '反論の対象は、ボランティアを予算項目として使うことです。サービスが本当に任意のものであるなら、無償の手助けは贈り物です。それが町にとって欠かせないものであるなら、それを任意と呼んでも任意にはなりません。ただ、危険を、たまたま現れた人に移し替えるだけです。',
    ],
    glossary: [
      { word: 'strain', ja: '負荷' },
      { word: 'advertise a post', ja: '求人を出す' },
      { word: 'reliable', ja: '頼りになる' },
      { word: 'evenly', ja: '均等に' },
      { word: 'district', ja: '地区' },
      { word: 'optional', ja: '任意の' },
      { word: 'turn up', ja: '現れる' },
    ],
    questions: [
      {
        id: 'r-b2-31-q1',
        prompt: '第1段落で筆者が付け加えている見方はどれですか。',
        choices: [
          '誰も見ていないうちに有償でなくなった有償サービスであることが多い',
          '地域の連帯の証である',
          '費用が安く済む優れた方式である',
          '歴史的に定着した仕組みである',
        ],
        correctIndex: 0,
        explanation: 'a paid service that stopped being paid for while nobody was looking が該当します。',
        choiceNotes: [null, 'Sometimes it is. と限定した上で別の見方を出しています。', '費用対効果の評価ではありません。', '歴史の話は出てきません。'],
      },
      {
        id: 'r-b2-31-q2',
        prompt: '人が抜けたときの違いとして述べられているのはどれですか。',
        choices: [
          '有償なら求人を出すが、無償なら開館時間が減り記録も残らない',
          '有償のほうが早く人が抜ける',
          '無償のほうが代わりが見つかりやすい',
          'どちらも同じ対応になる',
        ],
        correctIndex: 0,
        explanation: '第2段落の図書館の対比がそのまま該当します。',
        choiceNotes: [null, '離脱の速さは論じられていません。', '逆の含みです。', '違うと述べられています。'],
      },
      {
        id: 'r-b2-31-q3',
        prompt: 'ボランティアの分布について述べられていることはどれですか。',
        choices: [
          '担い手が多い地域ほど、そのサービスを必要としない傾向がある',
          '必要な地域ほど担い手が多い',
          '分布は地域によらず一定である',
          '都市部にのみ集中している',
        ],
        correctIndex: 0,
        explanation: 'the neighbourhoods that need the service least が該当します。',
        choiceNotes: [null, '逆です。', 'not distributed evenly とあります。', '都市と地方の対比ではありません。'],
      },
      {
        id: 'r-b2-31-q4',
        prompt: '第4段落で筆者が認めているボランティアの価値はどれですか。',
        choices: [
          '自ら選んで来た人が場所の性格を変えること',
          '費用が安いこと',
          '柔軟に人数を増やせること',
          '専門性が高いこと',
        ],
        correctIndex: 0,
        explanation: 'A person who chooses to be there changes the character of a place が該当します。',
        choiceNotes: [null, '費用の安さは批判の対象です。', '人数の話は出てきません。', '専門性は述べられていません。'],
      },
      {
        id: 'r-b2-31-q5',
        prompt: '最終文が指摘している問題はどれですか。',
        choices: [
          '不可欠なサービスを任意と呼ぶことで、危険が担い手に移されること',
          'ボランティアの数が不足していること',
          '行政の説明が不足していること',
          '賃金の水準が低いこと',
        ],
        correctIndex: 0,
        explanation: 'It only moves the risk onto whoever turns up. が該当します。',
        choiceNotes: [null, '人数の話ではありません。', '説明責任の話ではありません。', '賃金水準の話ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-32',
    level: 'B2',
    title: 'The Forecast That Was Right',
    titleJa: '当たっていた予報',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A forecast of a thirty per cent chance of rain is not wrong when it rains. It is not right when it stays dry either. A single day cannot test a statement of that kind, and yet a single day is how almost everyone judges it.',
      'This creates a strange incentive for the people who issue such statements. A forecaster who says seventy per cent when the honest figure is fifty will be praised more often than blamed, because rain is remembered and dry days are not. Over time, published probabilities drift away from the numbers the models actually produced.',
      'The same pressure appears far outside weather. A doctor estimating the risk of a procedure, an engineer estimating the life of a structure and an official estimating the cost of a project all face an audience that will grade them on one outcome.',
      'The technical solution has existed for decades. Score the forecaster across hundreds of statements, rewarding calibration rather than individual hits, and the incentive reverses. Weather services do this and their published probabilities are, as a result, unusually honest.',
      'Almost no other field has adopted it, and the obstacle is not mathematics. Keeping score over hundreds of predictions requires writing the prediction down beforehand, in public, in a form that cannot be reinterpreted afterwards. That is an uncomfortable thing to ask of anyone whose authority rests on appearing certain.',
    ],
    paragraphsJa: [
      '降水確率30パーセントという予報は、雨が降ったからといって外れではありません。降らなかったからといって当たりでもありません。1日ではその種の言明を検証できません。それなのに、ほとんど誰もが1日で判断します。',
      'これは、そうした言明を出す人々に奇妙な誘因を生みます。正直な数字が50のときに70と言う予報者は、責められるより褒められることのほうが多くなります。雨は記憶され、降らなかった日は記憶されないからです。時間が経つにつれ、公表される確率は、モデルが実際に出した数字から離れていきます。',
      '同じ圧力は、天気のはるか外側にも現れます。手術の危険を見積もる医師、構造物の寿命を見積もる技術者、事業費を見積もる担当者。いずれも、たった一つの結果で自分を採点する相手を前にしています。',
      '技術的な解決策は何十年も前から存在します。予報者を数百件の言明にわたって採点し、個々の的中ではなく確率の較正を評価すれば、誘因は反転します。気象機関はこれを行っており、その結果、公表される確率は際立って正直です。',
      'ほかの分野はほとんど採用しておらず、障害は数学ではありません。数百件の予測にわたって記録を付けるには、あらかじめ、公開の場で、後から解釈し直せない形で予測を書き留める必要があります。それは、確信ありげに見えることの上に権威が成り立っている人にとって、居心地の悪い要求なのです。',
    ],
    glossary: [
      { word: 'forecast', ja: '予報' },
      { word: 'issue', ja: '発表する' },
      { word: 'probability', ja: '確率' },
      { word: 'drift', ja: '徐々にずれる' },
      { word: 'procedure', ja: '手術、処置' },
      { word: 'calibration', ja: '較正、確率の正しさ' },
      { word: 'reinterpret', ja: '解釈し直す' },
    ],
    questions: [
      {
        id: 'r-b2-32-q1',
        prompt: '筆者が第1段落で指摘している問題はどれですか。',
        choices: [
          '確率の言明は1日では検証できないのに1日で判断されること',
          '確率の計算が難しいこと',
          '予報が発表されないこと',
          '確率の表記が分かりにくいこと',
        ],
        correctIndex: 0,
        explanation: 'A single day cannot test a statement of that kind, and yet a single day is how almost everyone judges it. が該当します。',
        choiceNotes: [null, '計算の難しさは論点ではありません。', '発表はされています。', '表記の話は出てきません。'],
      },
      {
        id: 'r-b2-32-q2',
        prompt: '予報者が高めの数字を出す動機はどれですか。',
        choices: [
          '雨は記憶され、降らなかった日は記憶されないから',
          '高い確率のほうが計算が簡単だから',
          '上司の指示があるから',
          '視聴率が上がるから',
        ],
        correctIndex: 0,
        explanation: 'because rain is remembered and dry days are not が理由です。',
        choiceNotes: [null, '計算の難易ではありません。', '指示の話は出てきません。', '視聴率の話は出てきません。'],
      },
      {
        id: 'r-b2-32-q3',
        prompt: '同じ圧力を受ける例として挙げられていないものはどれですか。',
        choices: [
          '選挙の結果を予想する記者',
          '手術の危険を見積もる医師',
          '構造物の寿命を見積もる技術者',
          '事業費を見積もる担当者',
        ],
        correctIndex: 0,
        explanation: '第3段落に挙げられているのは医師・技術者・担当者の3者です。',
        choiceNotes: [null, '挙げられています。', '挙げられています。', '挙げられています。'],
      },
      {
        id: 'r-b2-32-q4',
        prompt: '技術的な解決策の内容はどれですか。',
        choices: [
          '数百件にわたって採点し、個々の的中でなく較正を評価する',
          '確率の表示をやめる',
          '予報の頻度を減らす',
          '複数の予報を平均する',
        ],
        correctIndex: 0,
        explanation: 'rewarding calibration rather than individual hits が該当します。',
        choiceNotes: [null, '表示の廃止ではありません。', '頻度の話ではありません。', '平均の話は出てきません。'],
      },
      {
        id: 'r-b2-32-q5',
        prompt: '他分野で採用されない理由として示されているのはどれですか。',
        choices: [
          '事前に公開の形で予測を残すことが、権威にとって居心地が悪いから',
          '数学的に困難だから',
          '記録の保管費用が高いから',
          '法律で禁じられているから',
        ],
        correctIndex: 0,
        explanation: 'the obstacle is not mathematics. と、最終文の理由が対応しています。',
        choiceNotes: [null, '明示的に否定されています。', '費用の話は出てきません。', '法の話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-33',
    level: 'B2',
    title: 'Why the Queue Moves',
    titleJa: '行列が進む理由',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'A bank with one line feeding six counters serves people at the same average speed as a bank with six separate lines. The mathematics of this is not in dispute. What differs is how the waiting feels, and that difference is not a trivial matter.',
      'In separate lines, the person who chose badly watches later arrivals leave first. The average wait is unchanged and the sense of unfairness is intense. In a single line nobody overtakes anybody, and complaints fall sharply even though the clock says the same thing.',
      'Airports learned to use this. Some deliberately place the baggage hall a long walk from the gate. Passengers who walk for six minutes and then wait for two complain far less than passengers who walk for one and wait for seven, although the second group has been in the building for less time.',
      'It would be easy to file this under manipulation, and sometimes that is what it is. A wait that is disguised rather than shortened has not been fixed.',
      'But the framing cuts both ways. If a person judges a wait by its fairness and its emptiness rather than its length, then a manager who reduces the average by two minutes while creating visible queue-jumping has made things worse by every measure that the customer actually uses. The subjective experience is not a distortion of the real service. For the person waiting, it is the service.',
    ],
    paragraphsJa: [
      '6つの窓口に1本の列が流れ込む銀行は、6本の別々の列を持つ銀行と、平均では同じ速さで人をさばきます。その数学に異論はありません。異なるのは待ち時間がどう感じられるかであり、その差は些細な問題ではありません。',
      '別々の列では、選択を誤った人が、後から来た人の先に帰っていくのを見ることになります。平均待ち時間は変わらないのに、不公平の感覚は激烈です。1本の列では誰も誰かを追い越しません。そして時計が同じことを示していても、苦情は急激に減ります。',
      '空港はこれを使うことを学びました。手荷物受取所を、搭乗口からわざと長く歩く位置に置く空港もあります。6分歩いてから2分待つ乗客は、1分歩いて7分待つ乗客よりもはるかに不平を言いません。建物の中にいた時間は後者のほうが短いにもかかわらず、です。',
      'これを操作の一語で片づけたくなりますし、実際にそうである場合もあります。短縮ではなく偽装された待ち時間は、解決されたことになりません。',
      'しかしこの枠組みは両方向に切れます。人が待ち時間を、長さではなく公平さと手持ち無沙汰さで判断するのなら、平均を2分縮める代わりに目に見える割り込みを生んだ管理者は、客が実際に使うあらゆる尺度において事態を悪化させたことになります。主観的な経験は、本当のサービスを歪めたものではありません。待っている人にとっては、それがサービスなのです。',
    ],
    glossary: [
      { word: 'counter', ja: '窓口' },
      { word: 'in dispute', ja: '争いがある' },
      { word: 'trivial', ja: '些細な' },
      { word: 'overtake', ja: '追い越す' },
      { word: 'baggage hall', ja: '手荷物受取所' },
      { word: 'disguise', ja: '偽装する' },
      { word: 'subjective', ja: '主観的な' },
    ],
    questions: [
      {
        id: 'r-b2-33-q1',
        prompt: '1本の列と6本の列を比べたとき、変わらないものはどれですか。',
        choices: ['平均の処理速度', '不公平の感覚', '苦情の件数', '客の満足度'],
        correctIndex: 0,
        explanation: 'serves people at the same average speed とあります。',
        choiceNotes: [null, '激烈に異なると述べられています。', '急激に減ると述べられています。', '感じ方は変わります。'],
      },
      {
        id: 'r-b2-33-q2',
        prompt: '別々の列で不公平感が強まる理由はどれですか。',
        choices: [
          '後から来た人が先に帰るのを見ることになるから',
          '列が長く見えるから',
          '窓口が見えないから',
          '待ち時間が実際に長いから',
        ],
        correctIndex: 0,
        explanation: 'watches later arrivals leave first が理由です。',
        choiceNotes: [null, '見た目の長さの話ではありません。', '窓口の可視性の話ではありません。', '平均は変わりません。'],
      },
      {
        id: 'r-b2-33-q3',
        prompt: '空港の例が示していることはどれですか。',
        choices: [
          '滞在時間が長くても、歩く時間が多いほうが不平が少ない',
          '滞在時間が短いほど不平が少ない',
          '手荷物の受取が早いほど満足度が高い',
          '搭乗口の位置は影響しない',
        ],
        correctIndex: 0,
        explanation: '6分歩いて2分待つ側のほうが、建物内滞在は長いのに不平が少ないと述べられています。',
        choiceNotes: [null, '逆の結果が示されています。', '受取速度の話ではありません。', '配置が影響しています。'],
      },
      {
        id: 'r-b2-33-q4',
        prompt: '第4段落で筆者が留保している点はどれですか。',
        choices: [
          '偽装された待ち時間は解決されたことにならない',
          '待ち時間の操作は常に正当である',
          '空港の設計は誤りである',
          '数学的な分析は無意味である',
        ],
        correctIndex: 0,
        explanation: 'A wait that is disguised rather than shortened has not been fixed. が該当します。',
        choiceNotes: [null, '常に正当だとはしていません。', '誤りとは述べていません。', 'not in dispute と認めています。'],
      },
      {
        id: 'r-b2-33-q5',
        prompt: '最終文が主張していることはどれですか。',
        choices: [
          '待つ人にとっては主観的経験こそがサービスそのものである',
          '主観は測定できないので無視すべきだ',
          '平均待ち時間を最優先すべきだ',
          '客の判断は誤っている',
        ],
        correctIndex: 0,
        explanation: 'For the person waiting, it is the service. が該当します。',
        choiceNotes: [null, '無視すべきとは逆です。', '平均優先を批判しています。', '客の判断を尊重しています。'],
      },
    ],
  },
  {
    id: 'r-b2-34',
    level: 'B2',
    title: 'The Case for Doing Nothing',
    titleJa: '何もしないという選択',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Medicine has become much better at finding things. Scans reveal small growths, blood tests show values slightly outside the normal range, and screening detects conditions that would never have caused a symptom.',
      'Finding more is not the same as helping more. Some of what is found would have sat quietly for forty years. Treating it converts a person who felt well into a patient who has had an operation, with all the risk that carries and none of the benefit.',
      'The obvious reply is that we cannot tell in advance which growths are the dangerous ones. That is true for many of them, and it is the strongest argument for acting. It is also an argument for saying so plainly, rather than presenting treatment as the safe default and waiting as the reckless choice.',
      'The pressures all run one way. A doctor who treats and is wrong has followed the standard path. A doctor who waits and is wrong has a conversation that no training prepares anyone for. Patients, meanwhile, hear waiting as neglect, because doing something feels like being cared for.',
      'Several health services now use the phrase active monitoring instead of watching and waiting. Renaming a thing is usually a poor substitute for changing it. In this case the new name describes the work accurately, and the old one described only the absence of an operation. That is a small improvement and it is not nothing.',
    ],
    paragraphsJa: [
      '医療は、ものを見つけることがはるかに上手になりました。画像検査は小さな増殖を映し出し、血液検査は正常範囲をわずかに外れた値を示し、集団検診は、生涯なんの症状も起こさなかったはずの状態を検出します。',
      'より多く見つけることは、より多く助けることと同じではありません。見つかったもののうちには、40年間おとなしくしていたはずのものもあります。それを治療することは、健康だと感じていた人を、手術を受けた患者に変えることです。手術に伴う危険はすべて引き受け、利益は一つも得られないままに。',
      '当然の反論は、どの増殖が危険なものかを事前には言えない、というものです。多くのものについてそれは事実であり、それが治療を行う最も強い論拠です。同時にそれは、そのことを率直に述べる論拠でもあります。治療を安全な既定路線として、待つことを無謀な選択として提示するのではなく。',
      '圧力はすべて同じ方向に働きます。治療して誤った医師は、標準的な道筋をたどったことになります。待って誤った医師は、どんな訓練も備えさせてくれない会話をすることになります。一方で患者は、待つことを放置として受け取ります。何かをしてもらうことが、大切に扱われている感覚だからです。',
      'いくつかの医療機関は今、「経過観察」という言い方の代わりに「能動的監視」という語を使います。名前を変えることは、たいてい中身を変えることの粗末な代用品です。しかしこの場合、新しい名前は仕事の中身を正確に記述しており、古い名前は手術がないことだけを記述していました。それは小さな改善であり、そして無ではありません。',
    ],
    glossary: [
      { word: 'scan', ja: '画像検査' },
      { word: 'screening', ja: '集団検診' },
      { word: 'symptom', ja: '症状' },
      { word: 'default', ja: '既定の選択' },
      { word: 'reckless', ja: '無謀な' },
      { word: 'neglect', ja: '放置' },
      { word: 'substitute', ja: '代用品' },
    ],
    questions: [
      {
        id: 'r-b2-34-q1',
        prompt: '「より多く見つけることは、より多く助けることと同じではない」の理由はどれですか。',
        choices: [
          '一部は生涯問題を起こさず、治療は危険だけをもたらすから',
          '検査の精度が低いから',
          '検査費用が高いから',
          '医師の数が足りないから',
        ],
        correctIndex: 0,
        explanation: 'with all the risk that carries and none of the benefit が理由です。',
        choiceNotes: [null, '精度の話ではありません。', '費用の話は出てきません。', '人員の話は出てきません。'],
      },
      {
        id: 'r-b2-34-q2',
        prompt: '「事前には見分けられない」という反論を、筆者はどう扱っていますか。',
        choices: [
          '事実と認めつつ、率直に伝える根拠でもあるとしている',
          '誤りとして退けている',
          '無関係だとしている',
          '治療をやめる根拠としている',
        ],
        correctIndex: 0,
        explanation: 'That is true ... It is also an argument for saying so plainly が該当します。',
        choiceNotes: [null, '事実と認めています。', '強い論拠だと認めています。', '治療の否定ではありません。'],
      },
      {
        id: 'r-b2-34-q3',
        prompt: '医師にかかる圧力について正しいものはどれですか。',
        choices: [
          '治療して誤るほうが、待って誤るより責められにくい',
          '待って誤るほうが責められにくい',
          'どちらも同じ扱いになる',
          '医師は責任を問われない',
        ],
        correctIndex: 0,
        explanation: '標準的な道筋をたどった場合と、訓練が備えさせない会話になる場合の対比が示されています。',
        choiceNotes: [null, '逆です。', '違うと述べられています。', '責任は問われます。'],
      },
      {
        id: 'r-b2-34-q4',
        prompt: '患者が待つことを放置と受け取る理由はどれですか。',
        choices: [
          '何かをしてもらうことが大切に扱われている感覚だから',
          '説明が不足しているから',
          '待機時間が長いから',
          '費用が変わらないから',
        ],
        correctIndex: 0,
        explanation: 'because doing something feels like being cared for が理由です。',
        choiceNotes: [null, '説明不足は挙げられていません。', '待機時間の長さの話ではありません。', '費用の話は出てきません。'],
      },
      {
        id: 'r-b2-34-q5',
        prompt: '呼称の変更について筆者はどう評価していますか。',
        choices: [
          '一般には粗末な代用だが、この場合は中身を正確に表す小さな改善だ',
          '常に有効な手段である',
          'まったく無意味である',
          '混乱を招くだけである',
        ],
        correctIndex: 0,
        explanation: 'That is a small improvement and it is not nothing. が評価です。',
        choiceNotes: [null, 'usually a poor substitute と一般化を否定しています。', '無意味とはしていません。', '混乱の話は出てきません。'],
      },
    ],
  },
  {
    id: 'r-b2-35',
    level: 'B2',
    title: 'What Open Data Does Not Show',
    titleJa: '公開データが映さないもの',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'Governments now publish enormous quantities of data. Spending, contracts, waiting times and inspection results are all available to anyone with a connection and an afternoon.',
      'This is a genuine gain, and the way it is described is misleading. Publishing is treated as though it were the same act as being open, when the two can move in opposite directions.',
      'A dataset answers the questions it was built to answer. Spending files list what was paid to whom, which is useful, and they do not record what was decided in the meeting before the contract was drawn up. An organisation can therefore publish everything it holds and still disclose nothing about how it chose.',
      'There is a second effect that is easier to miss. Once data is published, the burden shifts. A journalist who cannot find evidence of a problem in the files is treated as having failed to prove it, even where the files were never capable of containing that evidence. Publication converts an absence of records into an appearance of innocence.',
      'The remedy is not less publication. It is to be specific about what a release can support. A spending file is evidence about payments. It is not evidence about judgement, and a body that answers questions about judgement by pointing at a spreadsheet has not answered them.',
    ],
    paragraphsJa: [
      '各国政府は今や膨大な量のデータを公開しています。支出、契約、待ち時間、検査結果は、接続環境と午後の時間さえあれば誰でも入手できます。',
      'これは本当の前進であり、そしてその語られ方は誤解を招きます。公開することが、開かれていることと同じ行為であるかのように扱われているのです。実際には、この二つは逆方向に動きうるものです。',
      'データの集合は、それが答えるために作られた問いにだけ答えます。支出のファイルは、誰にいくら支払われたかを列挙します。それは有用ですが、契約書が作られる前の会議で何が決められたかは記録していません。ですから組織は、保有するすべてを公開しながら、どう選んだかについては何も明かさないでいられます。',
      'もう一つ、見落としやすい効果があります。データが公開されると、立証の負担が移ります。ファイルの中に問題の証拠を見つけられない記者は、それを証明できなかった者として扱われます。そのファイルがもともとその証拠を含みうるものでなかった場合でさえ、そうなります。公開は、記録の不在を、潔白の外観へと変換するのです。',
      '処方箋は、公開を減らすことではありません。ある公開が何を裏づけうるのかを具体的に述べることです。支出ファイルは支払いについての証拠です。それは判断についての証拠ではありません。そして、判断についての問いに表計算ファイルを指さして答える組織は、答えていないのです。',
    ],
    glossary: [
      { word: 'inspection', ja: '検査' },
      { word: 'misleading', ja: '誤解を招く' },
      { word: 'dataset', ja: 'データの集合' },
      { word: 'draw up', ja: '作成する' },
      { word: 'disclose', ja: '明かす' },
      { word: 'burden', ja: '負担' },
      { word: 'remedy', ja: '処方箋、対策' },
    ],
    questions: [
      {
        id: 'r-b2-35-q1',
        prompt: '筆者が誤解を招くとしている点はどれですか。',
        choices: [
          '公開することと開かれていることが同一視されていること',
          'データ量が多すぎること',
          'データが有料であること',
          'データの形式が古いこと',
        ],
        correctIndex: 0,
        explanation: 'Publishing is treated as though it were the same act as being open が該当します。',
        choiceNotes: [null, '量の多さは前進として述べられています。', '無料で入手できます。', '形式の話は出てきません。'],
      },
      {
        id: 'r-b2-35-q2',
        prompt: '支出ファイルが記録していないものはどれですか。',
        choices: [
          '契約書が作られる前の会議での決定',
          '支払先の名前',
          '支払額',
          '契約の日付',
        ],
        correctIndex: 0,
        explanation: 'they do not record what was decided in the meeting before the contract was drawn up が該当します。',
        choiceNotes: [null, '記録されています。', '記録されています。', '支出情報に含まれます。'],
      },
      {
        id: 'r-b2-35-q3',
        prompt: '「立証の負担が移る」とはどういうことですか。',
        choices: [
          '記録に証拠がないと、証明できなかった側の失敗とされること',
          '記者が費用を負担すること',
          '行政が説明義務を負うこと',
          '裁判で立証責任が変わること',
        ],
        correctIndex: 0,
        explanation: 'is treated as having failed to prove it が該当します。',
        choiceNotes: [null, '費用の話ではありません。', '逆方向の効果です。', '法廷の手続きの話ではありません。'],
      },
      {
        id: 'r-b2-35-q4',
        prompt: '「記録の不在を潔白の外観へ変換する」が意味しているのはどれですか。',
        choices: [
          '記録に載らない事柄が、問題がなかった証拠のように見えてしまうこと',
          '記録が改ざんされること',
          '記録が失われること',
          '記録が非公開になること',
        ],
        correctIndex: 0,
        explanation: 'even where the files were never capable of containing that evidence が前提にあります。',
        choiceNotes: [null, '改ざんの話は出てきません。', '紛失の話ではありません。', '公開されています。'],
      },
      {
        id: 'r-b2-35-q5',
        prompt: '筆者が示す対策はどれですか。',
        choices: [
          '公開が何を裏づけうるのかを具体的に述べること',
          '公開の量を減らすこと',
          '記者の権限を強化すること',
          '表計算での公開をやめること',
        ],
        correctIndex: 0,
        explanation: 'It is to be specific about what a release can support. が該当します。',
        choiceNotes: [null, 'not less publication と否定されています。', '権限の話は出てきません。', '形式の否定ではありません。'],
      },
    ],
  },
  {
    id: 'r-b2-36',
    level: 'B2',
    title: 'The Border That Runs Through a Town',
    titleJa: '町を貫く国境',
    minutes: 12,
    canDo: ['R-B2-1', 'R-B2-2'],
    paragraphs: [
      'There are towns in Europe where the line between two countries runs along a street, and in a few cases through a building. The people who live there tend to be studied as a curiosity. They are more useful than that.',
      'A border of this kind makes visible what is normally hidden. Two sets of rules apply to houses that share a wall, and the differences that result are unusually easy to attribute. When electricity costs half as much on one side, nobody can argue that the reason is climate or culture.',
      'Residents respond in ways that look irrational from a distance and are obviously sensible up close. They register a business on one side and a car on the other. They send children to whichever school starts later. Officials describe this as an abuse of the system, which is a strange description of people following two sets of rules that were each designed to be followed.',
      'The interesting finding is what happens to the differences over time. Where the border is open, the two sides converge on many things, but not on the ones that governments control most tightly. Shop hours become similar. Tax rates do not.',
      'This is a reminder that a border is not one thing. It is a bundle of separate lines that happen to lie on top of each other, and when the bundle is loosened, they come apart at very different speeds.',
    ],
    paragraphsJa: [
      'ヨーロッパには、二国間の境界線が通りに沿って走り、ごく一部では建物の中を貫いている町があります。そこに住む人々は、たいてい珍しい事例として研究されます。実際には、それ以上に有用な存在です。',
      'この種の国境は、ふだん隠れているものを目に見えるようにします。壁を共有する家々に二組の規則が適用され、そこから生じる差は、原因を突き止めるのが異常に容易です。片側で電気代が半額なら、その理由が気候や文化だと主張できる人はいません。',
      '住民の対応は、遠くから見れば不合理に見え、近くで見れば明らかに理にかなっています。事業は片側で登録し、車はもう片側で登録します。子どもは、始業時刻の遅いほうの学校へ通わせます。当局はこれを制度の濫用と表現します。それぞれ守られるために設計された二組の規則を守っている人々に対して、奇妙な表現です。',
      '興味深い知見は、その差が時間とともにどうなるかです。国境が開かれている場合、両側は多くのことで収斂します。ただし、政府が最も強く統制しているものについては収斂しません。店の営業時間は似てきます。税率は似てきません。',
      'これは、国境が一つのものではないことを思い出させます。国境とは、たまたま重なり合っている複数の別々の線の束です。そしてその束が緩められると、それらはまったく異なる速さで離れていくのです。',
    ],
    glossary: [
      { word: 'curiosity', ja: '珍しい事例' },
      { word: 'attribute', ja: '原因を帰する' },
      { word: 'register', ja: '登録する' },
      { word: 'abuse', ja: '濫用' },
      { word: 'converge', ja: '収斂する、近づく' },
      { word: 'tightly', ja: '強く、厳しく' },
      { word: 'bundle', ja: '束' },
    ],
    questions: [
      {
        id: 'r-b2-36-q1',
        prompt: 'この種の国境が研究に有用な理由はどれですか。',
        choices: [
          '差の原因を気候や文化に帰せないため、規則の効果が見えるから',
          '人口が少なく調査しやすいから',
          '歴史資料が豊富だから',
          '住民が協力的だから',
        ],
        correctIndex: 0,
        explanation: 'nobody can argue that the reason is climate or culture が理由です。',
        choiceNotes: [null, '人口規模の話は出てきません。', '資料の話は出てきません。', '協力度の話は出てきません。'],
      },
      {
        id: 'r-b2-36-q2',
        prompt: '住民の行動として挙げられていないものはどれですか。',
        choices: [
          '両側で二重に納税する',
          '事業を片側で登録する',
          '車をもう片側で登録する',
          '始業の遅い学校を選ぶ',
        ],
        correctIndex: 0,
        explanation: '第3段落に挙げられているのは事業登録・車の登録・学校選びの3点です。',
        choiceNotes: [null, '挙げられています。', '挙げられています。', '挙げられています。'],
      },
      {
        id: 'r-b2-36-q3',
        prompt: '当局の「制度の濫用」という表現を、筆者はどう評価していますか。',
        choices: [
          '守られるために作られた規則を守る行為への奇妙な呼び方だとしている',
          '正確な表現だとしている',
          '住民の弁明だとしている',
          '法的に誤りだとしている',
        ],
        correctIndex: 0,
        explanation: 'which is a strange description of people following two sets of rules が該当します。',
        choiceNotes: [null, 'strange と評しています。', '当局の表現です。', '違法性の判断はしていません。'],
      },
      {
        id: 'r-b2-36-q4',
        prompt: '国境が開かれている場合の収斂について正しいものはどれですか。',
        choices: [
          '営業時間は似てくるが、税率は似てこない',
          'すべてが均一になる',
          '何も変わらない',
          '税率から先に似てくる',
        ],
        correctIndex: 0,
        explanation: 'Shop hours become similar. Tax rates do not. が該当します。',
        choiceNotes: [null, '政府が統制するものは収斂しません。', '多くのことで収斂します。', '逆です。'],
      },
      {
        id: 'r-b2-36-q5',
        prompt: '最終段落の比喩が示していることはどれですか。',
        choices: [
          '国境は複数の線の束であり、緩むと異なる速さで分離する',
          '国境は撤廃すべきである',
          '国境は物理的な壁にすぎない',
          '国境の位置は歴史的偶然である',
        ],
        correctIndex: 0,
        explanation: 'they come apart at very different speeds が該当します。',
        choiceNotes: [null, '撤廃は主張していません。', '規則の束だと述べています。', '位置の由来は論じていません。'],
      },
    ],
  },
]
