import type { VocabularyEntry } from '../types'

export const batch07: VocabularyEntry[] = [
  {
    id: 'refuse',
    word: 'refuse',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['断る、拒否する'],
    pronunciation: '/rɪˈfjuːz/',
    exampleSentence: 'She refused to sign the contract without reading it first.',
    exampleTranslationJa: '彼女はまず読まずに契約書に署名することを拒否した。',
    collocations: ['refuse to do something', 'refuse an offer', 'flatly refuse'],
    relatedWords: ['reject', 'decline', 'refusal'],
  },
  {
    id: 'regard',
    word: 'regard',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['〜とみなす、考える', '(名詞)配慮、敬意'],
    pronunciation: '/rɪˈɡɑːrd/',
    exampleSentence: 'Many people regard her as the best writer of her generation.',
    exampleTranslationJa: '多くの人が彼女を同世代で最高の作家とみなしている。',
    collocations: ['regard A as B', 'with regard to', 'highly regarded'],
    etymology: '古フランス語 regarder(見る)から。「〜を見る→〜とみなす」と意味が広がった。',
    relatedWords: ['consider', 'respect', 'regarding'],
  },
  {
    id: 'region',
    word: 'region',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['地域、地方'],
    pronunciation: '/ˈriːdʒən/',
    exampleSentence: 'This region is famous for its wine and beautiful mountains.',
    exampleTranslationJa: 'この地域はワインと美しい山々で有名だ。',
    collocations: ['mountainous region', 'coastal region', 'in the region of'],
    etymology: 'ラテン語 regio(方向、支配する範囲)から。regere(支配する)が語根。',
    relatedWords: ['regional', 'area', 'district'],
  },
  {
    id: 'regional',
    word: 'regional',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['地域の、地方の'],
    pronunciation: '/ˈriːdʒənl/',
    exampleSentence: 'The company opened a new regional office in Osaka.',
    exampleTranslationJa: 'その会社は大阪に新しい地域事務所を開設した。',
    collocations: ['regional differences', 'regional office', 'regional dialect'],
    wordFormation: 'region(地域)+ -al(形容詞化の接尾辞)',
    relatedWords: ['region', 'local', 'national'],
  },
  {
    id: 'register',
    word: 'register',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['登録する、記名する', '(名詞)登録簿、名簿'],
    pronunciation: '/ˈredʒɪstər/',
    exampleSentence: 'You need to register for the course before the end of March.',
    exampleTranslationJa: '3月末までにその講座に登録する必要がある。',
    collocations: ['register for a course', 'register a company', 'registered mail'],
    relatedWords: ['registration', 'enroll', 'sign up'],
  },
  {
    id: 'regret',
    word: 'regret',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['後悔する、残念に思う', '(名詞)後悔、遺憾'],
    pronunciation: '/rɪˈɡret/',
    exampleSentence: 'I regret not studying harder when I was in college.',
    exampleTranslationJa: '大学時代にもっと熱心に勉強しなかったことを後悔している。',
    collocations: ['regret doing something', 'deeply regret', 'express regret'],
    relatedWords: ['regretful', 'apologize', 'remorse'],
  },
  {
    id: 'regular',
    word: 'regular',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['定期的な、規則正しい', '通常の、普通の'],
    pronunciation: '/ˈreɡjələr/',
    exampleSentence: 'Regular exercise helps you stay healthy and sleep better.',
    exampleTranslationJa: '定期的な運動は健康を保ち、よく眠るのに役立つ。',
    collocations: ['regular exercise', 'on a regular basis', 'regular customer'],
    etymology: 'ラテン語 regula(定規、規則)から。rule や regulate と同じ語根。',
    relatedWords: ['regularly', 'irregular', 'routine'],
  },
  {
    id: 'regulation',
    word: 'regulation',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['規制、規則', '取り締まり'],
    pronunciation: '/ˌreɡjuˈleɪʃn/',
    exampleSentence: 'The new safety regulations apply to all factories in the country.',
    exampleTranslationJa: '新しい安全規制は国内のすべての工場に適用される。',
    collocations: ['safety regulations', 'strict regulations', 'comply with regulations'],
    wordFormation: 'regul(規則 ← ラテン語 regula)+ -ation(名詞化の接尾辞)',
    relatedWords: ['regulate', 'rule', 'law', 'restriction'],
  },
  {
    id: 'reject',
    word: 'reject',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['拒絶する、却下する'],
    pronunciation: '/rɪˈdʒekt/',
    exampleSentence: 'The committee rejected his proposal because it was too expensive.',
    exampleTranslationJa: '委員会は費用がかかりすぎるという理由で彼の提案を却下した。',
    collocations: ['reject a proposal', 'reject an application', 'firmly reject'],
    wordFormation: 're-(後ろへ)+ ject(投げる ← ラテン語 jacere)。「投げ返す」イメージ。',
    relatedWords: ['rejection', 'refuse', 'accept', 'decline'],
  },
  {
    id: 'relate',
    word: 'relate',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['関連づける、関係がある', '共感する(relate to)'],
    pronunciation: '/rɪˈleɪt/',
    exampleSentence: 'The study relates stress at work to poor sleep quality.',
    exampleTranslationJa: 'その研究は職場のストレスを睡眠の質の低下と関連づけている。',
    collocations: ['relate A to B', 'relate to someone', 'closely related'],
    relatedWords: ['relation', 'relationship', 'related', 'relative'],
  },
  {
    id: 'relation',
    word: 'relation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['関係、関連', '(複数形で)国家間や団体間の関係'],
    pronunciation: '/rɪˈleɪʃn/',
    exampleSentence: 'The two countries are working to improve their trade relations.',
    exampleTranslationJa: '両国は貿易関係の改善に取り組んでいる。',
    collocations: ['in relation to', 'international relations', 'public relations'],
    wordFormation: 'relate(関連づける)+ -ion(名詞化の接尾辞)',
    relatedWords: ['relationship', 'connection', 'relative'],
  },
  {
    id: 'relationship',
    word: 'relationship',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['関係、間柄', '恋愛関係'],
    pronunciation: '/rɪˈleɪʃnʃɪp/',
    exampleSentence: 'She has a very good relationship with her coworkers.',
    exampleTranslationJa: '彼女は同僚たちととても良い関係を築いている。',
    collocations: ['close relationship', 'build a relationship', 'relationship between A and B'],
    wordFormation: 'relation(関係)+ -ship(状態・性質を表す接尾辞)',
    relatedWords: ['relation', 'connection', 'bond'],
  },
  {
    id: 'relative',
    word: 'relative',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['親戚、身内', '(形容詞)相対的な、比較上の'],
    pronunciation: '/ˈrelətɪv/',
    exampleSentence: 'We visited our relatives in the countryside during the holidays.',
    exampleTranslationJa: '休暇中に田舎の親戚を訪ねた。',
    collocations: ['close relative', 'distant relative', 'relative to'],
    relatedWords: ['relation', 'relatively', 'family'],
  },
  {
    id: 'relatively',
    word: 'relatively',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['比較的、相対的に'],
    pronunciation: '/ˈrelətɪvli/',
    exampleSentence: 'The test was relatively easy compared to last year.',
    exampleTranslationJa: 'その試験は昨年に比べて比較的簡単だった。',
    collocations: ['relatively easy', 'relatively small', 'relatively new'],
    wordFormation: 'relative(相対的な)+ -ly(副詞化の接尾辞)',
    relatedWords: ['comparatively', 'fairly', 'quite'],
  },
  {
    id: 'release',
    word: 'release',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['解放する、放出する', '発売する、公開する', '(名詞)公開、発売、解放'],
    pronunciation: '/rɪˈliːs/',
    exampleSentence: 'The band will release a new album next month.',
    exampleTranslationJa: 'そのバンドは来月新しいアルバムを発売する。',
    collocations: ['release a film', 'press release', 'release a prisoner'],
    etymology: 'ラテン語 relaxare(緩める)が古フランス語を経て変化した語。relax と同じ語源。',
    relatedWords: ['publish', 'launch', 'free'],
  },
  {
    id: 'relevant',
    word: 'relevant',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['関連のある、適切な'],
    pronunciation: '/ˈreləvənt/',
    exampleSentence: 'Please include only information that is relevant to the topic.',
    exampleTranslationJa: 'トピックに関連する情報だけを含めてください。',
    collocations: ['relevant to', 'relevant information', 'highly relevant'],
    relatedWords: ['irrelevant', 'related', 'appropriate', 'relevance'],
  },
  {
    id: 'reliable',
    word: 'reliable',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['信頼できる、頼りになる'],
    pronunciation: '/rɪˈlaɪəbl/',
    exampleSentence: 'We need a reliable source of information before we make a decision.',
    exampleTranslationJa: '決定を下す前に信頼できる情報源が必要だ。',
    collocations: ['reliable source', 'reliable information', 'highly reliable'],
    wordFormation: 'rely(頼る)+ -able(〜できる)。「頼ることができる」。',
    relatedWords: ['rely', 'dependable', 'trustworthy', 'unreliable'],
  },
  {
    id: 'relief',
    word: 'relief',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['安堵、ほっとすること', '(苦痛などの)緩和、救済'],
    pronunciation: '/rɪˈliːf/',
    exampleSentence: 'It was a great relief to hear that everyone was safe.',
    exampleTranslationJa: '全員が無事だと聞いて大いにほっとした。',
    collocations: ['a sense of relief', 'sigh of relief', 'pain relief', 'disaster relief'],
    etymology: 'ラテン語 levare(軽くする)+ re- が語源。「重荷を軽くすること」。elevate と同根。',
    relatedWords: ['relieve', 'relaxation', 'comfort'],
  },
  {
    id: 'relieve',
    word: 'relieve',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(苦痛・不安などを)和らげる、軽減する'],
    pronunciation: '/rɪˈliːv/',
    exampleSentence: 'This medicine will help relieve your headache quickly.',
    exampleTranslationJa: 'この薬は頭痛をすばやく和らげるのに役立つ。',
    collocations: ['relieve pain', 'relieve stress', 'relieve pressure'],
    wordFormation: 're-(強調)+ liev(軽くする ← ラテン語 levare)。relief の動詞形。',
    relatedWords: ['relief', 'ease', 'reduce', 'relieved'],
  },
  {
    id: 'religion',
    word: 'religion',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['宗教'],
    pronunciation: '/rɪˈlɪdʒən/',
    exampleSentence: 'People of many different religions live together in this city.',
    exampleTranslationJa: 'この都市では多くの異なる宗教の人々が共に暮らしている。',
    collocations: ['practice a religion', 'freedom of religion', 'organized religion'],
    relatedWords: ['religious', 'faith', 'belief'],
  },
  {
    id: 'religious',
    word: 'religious',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['宗教の、宗教的な', '信心深い'],
    pronunciation: '/rɪˈlɪdʒəs/',
    exampleSentence: 'The festival has both religious and cultural meanings.',
    exampleTranslationJa: 'その祭りには宗教的な意味と文化的な意味の両方がある。',
    collocations: ['religious beliefs', 'religious ceremony', 'deeply religious'],
    wordFormation: 'religion(宗教)+ -ous(形容詞化の接尾辞)',
    relatedWords: ['religion', 'spiritual', 'sacred'],
  },
  {
    id: 'rely',
    word: 'rely',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['頼る、当てにする(rely on)'],
    pronunciation: '/rɪˈlaɪ/',
    exampleSentence: 'Many small businesses rely on local customers to survive.',
    exampleTranslationJa: '多くの小さな企業は生き残るために地元の客に頼っている。',
    collocations: ['rely on someone', 'rely heavily on', 'rely on someone to do'],
    etymology: 'ラテン語 religare(しっかり縛る)が語源。re-(強調)+ ligare(結ぶ)。',
    relatedWords: ['reliable', 'depend', 'reliance', 'count on'],
  },
  {
    id: 'remain',
    word: 'remain',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['〜のままである', '残る、とどまる'],
    pronunciation: '/rɪˈmeɪn/',
    exampleSentence: 'Despite the changes, the price will remain the same this year.',
    exampleTranslationJa: '変更にもかかわらず、価格は今年も同じままだろう。',
    collocations: ['remain silent', 'remain calm', 'remain unchanged'],
    wordFormation: 're-(後ろに)+ main(とどまる ← ラテン語 manere)',
    relatedWords: ['remaining', 'stay', 'remainder'],
  },
  {
    id: 'remarkable',
    word: 'remarkable',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['注目に値する、驚くべき'],
    pronunciation: '/rɪˈmɑːrkəbl/',
    exampleSentence: 'She has made remarkable progress in English in just six months.',
    exampleTranslationJa: '彼女はわずか6か月で英語に目覚ましい進歩を遂げた。',
    collocations: ['remarkable progress', 'remarkable achievement', 'truly remarkable'],
    wordFormation: 'remark(注目する)+ -able(〜に値する)。「注目するに値する」。',
    relatedWords: ['remarkably', 'outstanding', 'impressive', 'notable'],
  },
  {
    id: 'remind',
    word: 'remind',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['思い出させる、気づかせる'],
    pronunciation: '/rɪˈmaɪnd/',
    exampleSentence: 'Please remind me to call the dentist tomorrow morning.',
    exampleTranslationJa: '明日の朝、歯医者に電話するよう私に思い出させてください。',
    collocations: ['remind someone to do', 'remind someone of something', 'remind someone about'],
    wordFormation: 're-(再び)+ mind(心)。「再び心に呼び戻す」。',
    relatedWords: ['reminder', 'remember', 'recall'],
  },
  {
    id: 'remote',
    word: 'remote',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['遠く離れた、へんぴな', '遠隔の(リモートの)'],
    pronunciation: '/rɪˈmoʊt/',
    exampleSentence: 'They live in a remote village that has no train station.',
    exampleTranslationJa: '彼らは駅のないへんぴな村に住んでいる。',
    collocations: ['remote area', 'remote work', 'remote control'],
    wordFormation: 're-(後ろへ)+ mote(動かされた ← ラテン語 movere)。remove と同じ語根。',
    relatedWords: ['distant', 'isolated', 'remotely'],
  },
  {
    id: 'remove',
    word: 'remove',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['取り除く、除去する', '(衣服などを)脱ぐ'],
    pronunciation: '/rɪˈmuːv/',
    exampleSentence: 'Please remove your shoes before entering the house.',
    exampleTranslationJa: '家に入る前に靴を脱いでください。',
    collocations: ['remove a stain', 'remove an obstacle', 'completely remove'],
    wordFormation: 're-(後ろへ)+ move(動かす)。「別の場所へ動かす→取り除く」。',
    relatedWords: ['removal', 'delete', 'eliminate'],
  },
  {
    id: 'rent',
    word: 'rent',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['賃借りする、賃貸しする', '(名詞)家賃、賃貸料'],
    pronunciation: '/rent/',
    exampleSentence: 'We rented a car for the weekend and drove along the coast.',
    exampleTranslationJa: '週末に車を借りて海岸沿いをドライブした。',
    collocations: ['rent an apartment', 'pay the rent', 'for rent'],
    relatedWords: ['rental', 'lease', 'landlord', 'tenant'],
  },
  {
    id: 'repair',
    word: 'repair',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['修理する、直す', '(名詞)修理'],
    pronunciation: '/rɪˈper/',
    exampleSentence: 'It cost two hundred dollars to repair my laptop.',
    exampleTranslationJa: 'ノートパソコンの修理に200ドルかかった。',
    collocations: ['repair a car', 'under repair', 'repair the damage'],
    wordFormation: 're-(再び)+ pair(整える ← ラテン語 parare)。prepare と同じ語根。',
    relatedWords: ['fix', 'mend', 'restore', 'maintenance'],
  },
  {
    id: 'repeat',
    word: 'repeat',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['繰り返す、繰り返して言う'],
    pronunciation: '/rɪˈpiːt/',
    exampleSentence: 'Could you repeat the question more slowly, please?',
    exampleTranslationJa: 'その質問をもう少しゆっくり繰り返していただけますか。',
    collocations: ['repeat a question', 'repeat a mistake', 'repeat after me'],
    wordFormation: 're-(再び)+ peat(求める ← ラテン語 petere)。compete と同じ語根。',
    relatedWords: ['repetition', 'repeatedly', 'again'],
  },
  {
    id: 'replace',
    word: 'replace',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['取り替える、交換する', '取って代わる'],
    pronunciation: '/rɪˈpleɪs/',
    exampleSentence: 'We need to replace the batteries in the smoke alarm.',
    exampleTranslationJa: '火災報知器の電池を交換する必要がある。',
    collocations: ['replace A with B', 'replace a part', 'be replaced by'],
    wordFormation: 're-(再び)+ place(置く)。「置き直す→取り替える」。',
    relatedWords: ['replacement', 'substitute', 'exchange'],
  },
  {
    id: 'represent',
    word: 'represent',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['代表する', '表す、象徴する'],
    pronunciation: '/ˌreprɪˈzent/',
    exampleSentence: 'She was chosen to represent her school at the national contest.',
    exampleTranslationJa: '彼女は全国大会で学校を代表するために選ばれた。',
    collocations: ['represent a country', 'represent an idea', 'be represented by'],
    wordFormation: 're-(再び)+ present(示す、提示する)。「再び示す→表す・代表する」。',
    relatedWords: ['representative', 'representation', 'stand for'],
  },
  {
    id: 'representative',
    word: 'representative',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['代表者、担当者', '(形容詞)代表的な、典型的な'],
    pronunciation: '/ˌreprɪˈzentətɪv/',
    exampleSentence: 'A sales representative will contact you within two business days.',
    exampleTranslationJa: '営業担当者が2営業日以内にご連絡します。',
    collocations: ['sales representative', 'elected representative', 'representative of'],
    wordFormation: 'represent(代表する)+ -ative(〜の性質を持つ人・もの)',
    relatedWords: ['represent', 'delegate', 'agent'],
  },
  {
    id: 'reputation',
    word: 'reputation',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['評判、名声'],
    pronunciation: '/ˌrepjuˈteɪʃn/',
    exampleSentence: 'The restaurant has a reputation for excellent service.',
    exampleTranslationJa: 'そのレストランは素晴らしいサービスで評判だ。',
    collocations: ['have a reputation for', 'good reputation', 'damage a reputation'],
    etymology: 'ラテン語 reputare(考え直す、見積もる)から。putare(考える)が語根で compute と同根。',
    relatedWords: ['fame', 'image', 'reputable'],
  },
  {
    id: 'request',
    word: 'request',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['依頼、要請', '(動詞)依頼する、要請する'],
    pronunciation: '/rɪˈkwest/',
    exampleSentence: 'We received a request for more information about the event.',
    exampleTranslationJa: 'そのイベントに関する詳しい情報の依頼を受け取った。',
    collocations: ['make a request', 'on request', 'request for'],
    wordFormation: 're-(再び)+ quest(求める ← ラテン語 quaerere)。question と同じ語根。',
    relatedWords: ['require', 'demand', 'ask'],
  },
  {
    id: 'require',
    word: 'require',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['必要とする', '要求する、義務づける'],
    pronunciation: '/rɪˈkwaɪər/',
    exampleSentence: 'This job requires good communication skills and patience.',
    exampleTranslationJa: 'この仕事には優れたコミュニケーション能力と忍耐力が必要だ。',
    collocations: ['require skills', 'be required to do', 'require attention'],
    wordFormation: 're-(再び)+ quire(求める ← ラテン語 quaerere)。request と同じ語根。',
    relatedWords: ['requirement', 'need', 'demand'],
  },
  {
    id: 'requirement',
    word: 'requirement',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['必要条件、要件'],
    pronunciation: '/rɪˈkwaɪərmənt/',
    exampleSentence: 'A university degree is a basic requirement for this position.',
    exampleTranslationJa: 'この職には大学の学位が基本的な必要条件だ。',
    collocations: ['meet the requirements', 'entry requirements', 'legal requirement'],
    wordFormation: 'require(必要とする)+ -ment(名詞化の接尾辞)',
    relatedWords: ['require', 'condition', 'qualification'],
  },
  {
    id: 'rescue',
    word: 'rescue',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['救助する、救い出す', '(名詞)救助'],
    pronunciation: '/ˈreskjuː/',
    exampleSentence: 'Firefighters rescued three people from the burning building.',
    exampleTranslationJa: '消防士たちは燃えている建物から3人を救助した。',
    collocations: ['rescue someone from', 'rescue operation', 'come to the rescue'],
    relatedWords: ['save', 'recover', 'survivor'],
  },
  {
    id: 'research',
    word: 'research',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['研究、調査', '(動詞)研究する、調査する'],
    pronunciation: '/ˈriːsɜːrtʃ/',
    exampleSentence: 'Recent research shows that sleep is important for memory.',
    exampleTranslationJa: '最近の研究は睡眠が記憶にとって重要であることを示している。',
    collocations: ['do research', 'research shows', 'scientific research', 'research into'],
    wordFormation: 're-(繰り返し)+ search(探す)。「繰り返し探し求める」。',
    relatedWords: ['researcher', 'study', 'investigation'],
  },
  {
    id: 'reserve',
    word: 'reserve',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['予約する', '取っておく、確保する', '(名詞)蓄え、保護区'],
    pronunciation: '/rɪˈzɜːrv/',
    exampleSentence: 'I reserved a table for four at the Italian restaurant.',
    exampleTranslationJa: 'イタリアンレストランに4人分のテーブルを予約した。',
    collocations: ['reserve a table', 'reserve a room', 'nature reserve'],
    wordFormation: 're-(後ろに)+ serve(保つ ← ラテン語 servare)。preserve や conserve と同じ語根。',
    relatedWords: ['reservation', 'book', 'preserve'],
  },
  {
    id: 'resident',
    word: 'resident',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['居住者、住民'],
    pronunciation: '/ˈrezɪdənt/',
    exampleSentence: 'Local residents are worried about the increase in traffic.',
    exampleTranslationJa: '地元住民は交通量の増加を心配している。',
    collocations: ['local residents', 'permanent resident', 'residents of the area'],
    etymology: 'ラテン語 residere(座って留まる)から。re-(後ろに)+ sedere(座る)。',
    relatedWords: ['residence', 'residential', 'inhabitant', 'citizen'],
  },
  {
    id: 'resist',
    word: 'resist',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['抵抗する、反抗する', '(誘惑などを)我慢する'],
    pronunciation: '/rɪˈzɪst/',
    exampleSentence: 'I could not resist buying another piece of chocolate cake.',
    exampleTranslationJa: 'チョコレートケーキをもう一切れ買うのを我慢できなかった。',
    collocations: ["can't resist doing", 'resist change', 'resist temptation'],
    wordFormation: 're-(〜に対抗して)+ sist(立つ ← ラテン語 sistere)。「立ち向かう」。',
    relatedWords: ['resistance', 'oppose', 'withstand'],
  },
  {
    id: 'resolve',
    word: 'resolve',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(問題などを)解決する', '決心する'],
    pronunciation: '/rɪˈzɑːlv/',
    exampleSentence: 'The two companies met to resolve the dispute over the contract.',
    exampleTranslationJa: '両社は契約をめぐる争いを解決するために会合した。',
    collocations: ['resolve a problem', 'resolve a conflict', 'resolve to do'],
    wordFormation: 're-(強調)+ solve(解く ← ラテン語 solvere)。「完全に解きほぐす」。',
    relatedWords: ['resolution', 'solve', 'settle'],
  },
  {
    id: 'resource',
    word: 'resource',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['資源', '(学習・仕事などの)資料、リソース'],
    pronunciation: '/ˈriːsɔːrs/',
    exampleSentence: 'The country is rich in natural resources such as oil and gas.',
    exampleTranslationJa: 'その国は石油やガスなどの天然資源が豊富だ。',
    collocations: ['natural resources', 'human resources', 'limited resources'],
    relatedWords: ['source', 'supply', 'asset'],
  },
  {
    id: 'respect',
    word: 'respect',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['尊敬、敬意', '(動詞)尊敬する、尊重する', '点、側面(in this respect)'],
    pronunciation: '/rɪˈspekt/',
    exampleSentence: 'Students show great respect for their teacher.',
    exampleTranslationJa: '生徒たちは先生に大きな敬意を示している。',
    collocations: ['show respect for', 'with respect to', 'earn respect'],
    wordFormation: 're-(再び)+ spect(見る ← ラテン語 specere)。「何度も見る→敬意を払う」。inspect と同じ語根。',
    relatedWords: ['respectful', 'admire', 'honor'],
  },
  {
    id: 'respond',
    word: 'respond',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['返答する、応じる', '反応する'],
    pronunciation: '/rɪˈspɑːnd/',
    exampleSentence: 'The company responded quickly to the customer complaints.',
    exampleTranslationJa: 'その会社は顧客の苦情に迅速に対応した。',
    collocations: ['respond to', 'respond quickly', 'respond positively'],
    wordFormation: 're-(返して)+ spond(誓う、約束する ← ラテン語 spondere)。sponsor と同じ語根。',
    relatedWords: ['response', 'reply', 'react', 'answer'],
  },
  {
    id: 'response',
    word: 'response',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['返答、応答', '反応'],
    pronunciation: '/rɪˈspɑːns/',
    exampleSentence: 'I sent an email last week but have not received a response yet.',
    exampleTranslationJa: '先週メールを送ったが、まだ返答を受け取っていない。',
    collocations: ['in response to', 'positive response', 'immediate response'],
    wordFormation: 'respond(返答する)の名詞形',
    relatedWords: ['respond', 'reply', 'reaction'],
  },
  {
    id: 'responsibility',
    word: 'responsibility',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['責任', '職務、責務'],
    pronunciation: '/rɪˌspɑːnsəˈbɪləti/',
    exampleSentence: 'Taking care of the customers is my main responsibility at work.',
    exampleTranslationJa: '顧客対応が私の職場での主な責務だ。',
    collocations: ['take responsibility for', 'sense of responsibility', 'accept responsibility'],
    wordFormation: 'responsible(責任がある)+ -ity(名詞化の接尾辞)',
    relatedWords: ['responsible', 'duty', 'obligation'],
  },
  {
    id: 'responsible',
    word: 'responsible',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['責任がある(responsible for)', '信頼できる、責任感のある'],
    pronunciation: '/rɪˈspɑːnsəbl/',
    exampleSentence: 'She is responsible for training all the new employees.',
    exampleTranslationJa: '彼女はすべての新入社員の研修を担当している。',
    collocations: ['be responsible for', 'hold someone responsible', 'a responsible person'],
    wordFormation: 'respond(応じる)+ -ible(〜できる)。「応じることができる→責任を負える」。',
    relatedWords: ['responsibility', 'accountable', 'irresponsible'],
  },
  {
    id: 'restore',
    word: 'restore',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['回復させる、修復する', '復元する'],
    pronunciation: '/rɪˈstɔːr/',
    exampleSentence: 'The city plans to restore the old theater to its original condition.',
    exampleTranslationJa: '市はその古い劇場を元の状態に修復する計画だ。',
    collocations: ['restore order', 'restore confidence', 'restore a building'],
    etymology: 'ラテン語 restaurare(再建する)から。restaurant(元気を回復させる場所)と同じ語源。',
    relatedWords: ['restoration', 'repair', 'recover'],
  },
  {
    id: 'restrict',
    word: 'restrict',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['制限する、限定する'],
    pronunciation: '/rɪˈstrɪkt/',
    exampleSentence: 'The new law restricts smoking in all public places.',
    exampleTranslationJa: '新しい法律はすべての公共の場所での喫煙を制限している。',
    collocations: ['restrict access', 'restrict A to B', 'strictly restricted'],
    wordFormation: 're-(強調)+ strict(縛る ← ラテン語 stringere)。「きつく縛る→制限する」。',
    relatedWords: ['restriction', 'limit', 'strict'],
  },
  {
    id: 'result',
    word: 'result',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['結果、成果', '(動詞)結果として生じる(result in / result from)'],
    pronunciation: '/rɪˈzʌlt/',
    exampleSentence: 'The results of the test will be announced next Friday.',
    exampleTranslationJa: '試験の結果は来週の金曜日に発表される。',
    collocations: ['as a result of', 'result in', 'exam results'],
    etymology: 'ラテン語 resultare(跳ね返る)から。re-(戻って)+ saltare(跳ぶ)。',
    relatedWords: ['outcome', 'consequence', 'effect'],
  },
  {
    id: 'retain',
    word: 'retain',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['保持する、維持する'],
    pronunciation: '/rɪˈteɪn/',
    exampleSentence: 'It is hard to retain new vocabulary without regular review.',
    exampleTranslationJa: '定期的な復習なしに新しい語彙を記憶に保持するのは難しい。',
    collocations: ['retain information', 'retain control', 'retain customers'],
    wordFormation: 're-(後ろに)+ tain(保つ ← ラテン語 tenere)。maintain や contain と同じ語根。',
    relatedWords: ['keep', 'maintain', 'retention'],
  },
  {
    id: 'retire',
    word: 'retire',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['退職する、引退する'],
    pronunciation: '/rɪˈtaɪər/',
    exampleSentence: 'My father plans to retire from his job next year.',
    exampleTranslationJa: '父は来年仕事を退職する予定だ。',
    collocations: ['retire from', 'retire early', 'retire at the age of'],
    etymology: 'フランス語 retirer(引き下がる)から。re-(後ろへ)+ tirer(引く)。',
    relatedWords: ['retirement', 'retired', 'resign'],
  },
  {
    id: 'retirement',
    word: 'retirement',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['退職、引退', '退職後の生活'],
    pronunciation: '/rɪˈtaɪərmənt/',
    exampleSentence: 'He is saving money for a comfortable retirement.',
    exampleTranslationJa: '彼は快適な退職後の生活のために貯金をしている。',
    collocations: ['early retirement', 'retirement age', 'save for retirement'],
    wordFormation: 'retire(退職する)+ -ment(名詞化の接尾辞)',
    relatedWords: ['retire', 'pension', 'resignation'],
  },
  {
    id: 'reveal',
    word: 'reveal',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['明らかにする、暴露する', '見せる、現す'],
    pronunciation: '/rɪˈviːl/',
    exampleSentence: 'The report revealed serious problems in the safety system.',
    exampleTranslationJa: 'その報告書は安全システムの深刻な問題を明らかにした。',
    collocations: ['reveal a secret', 'reveal the truth', 'reveal that'],
    etymology: 'ラテン語 revelare が語源。re-(除いて)+ velum(覆い、ベール)。「ベールを取り除く」。',
    relatedWords: ['disclose', 'expose', 'hide', 'revelation'],
  },
  {
    id: 'revenue',
    word: 'revenue',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['収益、歳入'],
    pronunciation: '/ˈrevənuː/',
    exampleSentence: 'The company expects its revenue to grow by ten percent this year.',
    exampleTranslationJa: 'その会社は今年、収益が10パーセント伸びると見込んでいる。',
    collocations: ['tax revenue', 'annual revenue', 'generate revenue'],
    etymology: 'フランス語で「戻ってくるもの」の意。re-(戻って)+ venir(来る ← ラテン語 venire)。',
    relatedWords: ['income', 'profit', 'earnings'],
  },
  {
    id: 'review',
    word: 'review',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['批評、レビュー', '見直し、再検討', '(動詞)見直す、批評する'],
    pronunciation: '/rɪˈvjuː/',
    exampleSentence: 'The movie received excellent reviews from critics.',
    exampleTranslationJa: 'その映画は批評家たちから素晴らしい評価を受けた。',
    collocations: ['write a review', 'under review', 'review the plan'],
    wordFormation: 're-(再び)+ view(見る)。「もう一度見る→見直す・批評する」。',
    relatedWords: ['reviewer', 'evaluate', 'assessment'],
  },
  {
    id: 'revise',
    word: 'revise',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['修正する、改訂する', '(英)復習する'],
    pronunciation: '/rɪˈvaɪz/',
    exampleSentence: 'We had to revise our plans because of the weather.',
    exampleTranslationJa: '天候のせいで計画を修正しなければならなかった。',
    collocations: ['revise a plan', 'revised edition', 'revise upward'],
    wordFormation: 're-(再び)+ vise(見る ← ラテン語 videre)。vision と同じ語根。',
    relatedWords: ['revision', 'modify', 'update'],
  },
  {
    id: 'revolution',
    word: 'revolution',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['革命', '大変革'],
    pronunciation: '/ˌrevəˈluːʃn/',
    exampleSentence: 'The internet caused a revolution in the way people communicate.',
    exampleTranslationJa: 'インターネットは人々のコミュニケーションの方法に大変革をもたらした。',
    collocations: ['industrial revolution', 'digital revolution', 'lead a revolution'],
    wordFormation: 're-(再び)+ volut(回る ← ラテン語 volvere)+ -ion。「ぐるりと回る→体制がひっくり返る」。',
    relatedWords: ['revolutionary', 'reform', 'evolution'],
  },
  {
    id: 'reward',
    word: 'reward',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['報酬、ほうび', '(動詞)報いる、報酬を与える'],
    pronunciation: '/rɪˈwɔːrd/',
    exampleSentence: 'She got a small reward for returning the lost wallet.',
    exampleTranslationJa: '彼女は落とし物の財布を届けたことで小さな謝礼をもらった。',
    collocations: ['as a reward for', 'offer a reward', 'rewarding experience'],
    relatedWords: ['prize', 'bonus', 'rewarding'],
  },
  {
    id: 'rhythm',
    word: 'rhythm',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['リズム、律動'],
    pronunciation: '/ˈrɪðəm/',
    exampleSentence: 'The dancers moved perfectly to the rhythm of the drums.',
    exampleTranslationJa: 'ダンサーたちは太鼓のリズムに合わせて完璧に動いた。',
    collocations: ['the rhythm of', 'a sense of rhythm', 'natural rhythm'],
    etymology: 'ギリシャ語 rhythmos(流れ、拍子)から。',
    mnemonic: 'つづりは Rhythm Helps Your Two Hips Move の頭文字と覚える。',
    relatedWords: ['beat', 'tempo', 'rhythmic'],
  },
  {
    id: 'rid',
    word: 'rid',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['取り除く(get rid of で「〜を処分する、追い払う」)'],
    pronunciation: '/rɪd/',
    exampleSentence: 'I want to get rid of all these old clothes.',
    exampleTranslationJa: 'この古い服を全部処分したい。',
    collocations: ['get rid of', 'rid A of B', 'be rid of'],
    relatedWords: ['remove', 'eliminate', 'throw away'],
  },
  {
    id: 'risk',
    word: 'risk',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['危険、リスク', '(動詞)危険にさらす、あえて〜する'],
    pronunciation: '/rɪsk/',
    exampleSentence: 'Smoking increases the risk of heart disease.',
    exampleTranslationJa: '喫煙は心臓病のリスクを高める。',
    collocations: ['take a risk', 'at risk', 'reduce the risk of', 'risk factor'],
    relatedWords: ['risky', 'danger', 'hazard'],
  },
  {
    id: 'role',
    word: 'role',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['役割', '(俳優の)役'],
    pronunciation: '/roʊl/',
    exampleSentence: 'Parents play an important role in their children’s education.',
    exampleTranslationJa: '親は子どもの教育において重要な役割を果たす。',
    collocations: ['play a role in', 'leading role', 'role model'],
    etymology: 'フランス語 rôle から。もとは俳優のせりふが書かれた「巻紙」を指した。roll と同じ語源。',
    relatedWords: ['part', 'function', 'position'],
  },
  {
    id: 'roll',
    word: 'roll',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['転がる、転がす', '巻く', '(名詞)巻いたもの、ロールパン'],
    pronunciation: '/roʊl/',
    exampleSentence: 'The ball rolled down the hill and into the river.',
    exampleTranslationJa: 'ボールは坂を転がり落ちて川に入った。',
    collocations: ['roll down', 'roll up', 'roll over'],
    etymology: 'ラテン語 rotula(小さな車輪)から。rota(車輪)が語根で rotate と同根。',
    relatedWords: ['rotate', 'spin', 'turn'],
  },
  {
    id: 'rough',
    word: 'rough',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['(表面が)粗い、ざらざらした', '大まかな、おおよその', '荒っぽい、つらい'],
    pronunciation: '/rʌf/',
    exampleSentence: 'The road was so rough that we had to drive slowly.',
    exampleTranslationJa: '道がとてもでこぼこだったので、ゆっくり運転しなければならなかった。',
    collocations: ['rough surface', 'rough idea', 'a rough day'],
    relatedWords: ['roughly', 'smooth', 'uneven'],
  },
  {
    id: 'roughly',
    word: 'roughly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['おおよそ、ざっと', '乱暴に'],
    pronunciation: '/ˈrʌfli/',
    exampleSentence: 'The trip takes roughly three hours by train.',
    exampleTranslationJa: 'その旅は電車でおよそ3時間かかる。',
    collocations: ['roughly speaking', 'roughly half', 'roughly the same'],
    wordFormation: 'rough(大まかな)+ -ly(副詞化の接尾辞)',
    relatedWords: ['approximately', 'about', 'around'],
  },
  {
    id: 'route',
    word: 'route',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['道筋、ルート、経路'],
    pronunciation: '/ruːt/',
    exampleSentence: 'We took a different route to avoid the traffic jam.',
    exampleTranslationJa: '渋滞を避けるために別のルートを通った。',
    collocations: ['take a route', 'the shortest route', 'bus route', 'escape route'],
    etymology: 'ラテン語 via rupta(切り開かれた道)から。rumpere(破る)が語根。',
    relatedWords: ['path', 'way', 'course', 'direction'],
  },
  {
    id: 'routine',
    word: 'routine',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['日課、決まった手順', '(形容詞)日常的な、決まりきった'],
    pronunciation: '/ruːˈtiːn/',
    exampleSentence: 'Reading before bed is part of my daily routine.',
    exampleTranslationJa: '寝る前の読書は私の毎日の日課の一部だ。',
    collocations: ['daily routine', 'morning routine', 'routine check'],
    wordFormation: 'route(道筋)+ -ine。「決まった道筋→日課」。',
    relatedWords: ['habit', 'schedule', 'pattern'],
  },
  {
    id: 'row',
    word: 'row',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['列、並び', '連続(in a row で「連続して」)'],
    pronunciation: '/roʊ/',
    exampleSentence: 'We sat in the front row of the theater.',
    exampleTranslationJa: '私たちは劇場の最前列に座った。',
    collocations: ['in a row', 'front row', 'a row of houses'],
    relatedWords: ['line', 'column', 'queue'],
  },
  {
    id: 'royal',
    word: 'royal',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['王の、王室の'],
    pronunciation: '/ˈrɔɪəl/',
    exampleSentence: 'Thousands of people gathered to see the royal family.',
    exampleTranslationJa: '何千人もの人々が王室一家を見るために集まった。',
    collocations: ['royal family', 'royal palace', 'royal wedding'],
    etymology: 'ラテン語 regalis(王の)がフランス語を経て変化した語。rex(王)が語根で regal と同根。',
    relatedWords: ['royalty', 'king', 'queen', 'noble'],
  },
  {
    id: 'rub',
    word: 'rub',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['こする、さする'],
    pronunciation: '/rʌb/',
    exampleSentence: 'She rubbed her eyes because she was tired.',
    exampleTranslationJa: '彼女は疲れていたので目をこすった。',
    collocations: ['rub your eyes', 'rub your hands together', 'rub out'],
    relatedWords: ['scratch', 'stroke', 'polish'],
  },
  {
    id: 'rubbish',
    word: 'rubbish',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ごみ、くず(主にイギリス英語)', 'くだらないこと、ばかげた話'],
    pronunciation: '/ˈrʌbɪʃ/',
    exampleSentence: 'Please put the rubbish in the bin outside.',
    exampleTranslationJa: 'ごみは外のごみ箱に入れてください。',
    collocations: ['throw away rubbish', 'rubbish bin', 'talk rubbish'],
    relatedWords: ['trash', 'garbage', 'waste', 'litter'],
  },
  {
    id: 'rude',
    word: 'rude',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['無礼な、失礼な'],
    pronunciation: '/ruːd/',
    exampleSentence: 'It is rude to talk loudly on the phone on the train.',
    exampleTranslationJa: '電車の中で大声で電話するのは失礼だ。',
    collocations: ['rude to someone', 'rude behavior', "it's rude to do"],
    etymology: 'ラテン語 rudis(未加工の、粗野な)から。',
    relatedWords: ['polite', 'impolite', 'rudeness', 'offensive'],
  },
  {
    id: 'ruin',
    word: 'ruin',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['台無しにする、破滅させる', '(名詞、複数形で)遺跡、廃墟'],
    pronunciation: '/ˈruːɪn/',
    exampleSentence: 'The heavy rain ruined our plans for a picnic.',
    exampleTranslationJa: '大雨がピクニックの計画を台無しにした。',
    collocations: ['ruin your chances', 'completely ruin', 'ancient ruins', 'in ruins'],
    etymology: 'ラテン語 ruina(崩壊)から。ruere(崩れ落ちる)が語根。',
    relatedWords: ['destroy', 'spoil', 'damage'],
  },
  {
    id: 'rule',
    word: 'rule',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['規則、ルール', '支配', '(動詞)支配する、統治する'],
    pronunciation: '/ruːl/',
    exampleSentence: 'You must follow the rules of the game.',
    exampleTranslationJa: 'ゲームのルールに従わなければならない。',
    collocations: ['follow the rules', 'break a rule', 'as a rule', 'rule out'],
    etymology: 'ラテン語 regula(定規、規則)から。regular や regulate と同じ語根。',
    relatedWords: ['ruler', 'regulation', 'law', 'govern'],
  },
  {
    id: 'run-out-of',
    word: 'run out of',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['〜を使い果たす、〜を切らす'],
    pronunciation: '/rʌn aʊt əv/',
    exampleSentence: 'We may run out of milk before the weekend.',
    exampleTranslationJa: '週末になる前に牛乳を切らすかもしれない。',
    collocations: ['run out of time', 'run out of money', 'run out of patience'],
    relatedWords: ['use up', 'run low on', 'exhaust'],
  },
  {
    id: 'rural',
    word: 'rural',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['田舎の、農村の'],
    pronunciation: '/ˈrʊrəl/',
    exampleSentence: 'Many young people are leaving rural areas to find work in cities.',
    exampleTranslationJa: '多くの若者が都市で仕事を見つけるために農村部を離れている。',
    collocations: ['rural areas', 'rural communities', 'rural life'],
    etymology: 'ラテン語 rus(田舎)から。',
    relatedWords: ['urban', 'countryside', 'agricultural'],
  },
  {
    id: 'rush',
    word: 'rush',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['急いで行く、急ぐ', '(名詞)急ぐこと、混雑'],
    pronunciation: '/rʌʃ/',
    exampleSentence: 'She rushed to the station but still missed the train.',
    exampleTranslationJa: '彼女は駅へ急いだが、それでも電車に乗り遅れた。',
    collocations: ['rush hour', 'in a rush', 'rush to do'],
    relatedWords: ['hurry', 'dash', 'haste'],
  },
  {
    id: 'sacrifice',
    word: 'sacrifice',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['犠牲にする', '(名詞)犠牲'],
    pronunciation: '/ˈsækrɪfaɪs/',
    exampleSentence: 'She sacrificed her free time to care for her sick mother.',
    exampleTranslationJa: '彼女は病気の母親の世話をするために自由な時間を犠牲にした。',
    collocations: ['make a sacrifice', 'sacrifice A for B', 'great sacrifice'],
    wordFormation: 'sacri(神聖な ← ラテン語 sacer)+ fice(する ← facere)。「神聖なものにする→神に捧げる」。',
    relatedWords: ['sacred', 'devote', 'give up'],
  },
  {
    id: 'sample',
    word: 'sample',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['見本、サンプル、標本', '(動詞)試す、試食する'],
    pronunciation: '/ˈsæmpl/',
    exampleSentence: 'The store gave us free samples of the new cheese.',
    exampleTranslationJa: 'その店は新しいチーズの無料サンプルをくれた。',
    collocations: ['free sample', 'blood sample', 'a sample of'],
    etymology: '古フランス語 essample の短縮形で、example と同じ語源。',
    relatedWords: ['example', 'specimen', 'trial'],
  },
  {
    id: 'satellite',
    word: 'satellite',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['人工衛星、衛星'],
    pronunciation: '/ˈsætəlaɪt/',
    exampleSentence: 'The weather satellite sends images of the storm every hour.',
    exampleTranslationJa: 'その気象衛星は1時間ごとに嵐の画像を送信する。',
    collocations: ['satellite image', 'communications satellite', 'launch a satellite'],
    etymology: 'ラテン語 satelles(従者、護衛)から。「惑星に付き従うもの」の意味で使われるようになった。',
    relatedWords: ['orbit', 'spacecraft', 'GPS'],
  },
  {
    id: 'satisfaction',
    word: 'satisfaction',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['満足、満足感'],
    pronunciation: '/ˌsætɪsˈfækʃn/',
    exampleSentence: 'She looked at her finished painting with great satisfaction.',
    exampleTranslationJa: '彼女は完成した絵を大きな満足感とともに眺めた。',
    collocations: ['customer satisfaction', 'job satisfaction', 'a sense of satisfaction'],
    wordFormation: 'satis(十分 ← ラテン語)+ fact(する ← facere)+ -ion。「十分にすること」。',
    relatedWords: ['satisfy', 'satisfied', 'contentment'],
  },
  {
    id: 'satisfied',
    word: 'satisfied',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['満足した(satisfied with)'],
    pronunciation: '/ˈsætɪsfaɪd/',
    exampleSentence: 'Most customers were satisfied with the new service.',
    exampleTranslationJa: 'ほとんどの顧客が新しいサービスに満足していた。',
    collocations: ['be satisfied with', 'fully satisfied', 'satisfied customers'],
    wordFormation: 'satisfy(満足させる)の過去分詞が形容詞化したもの',
    relatedWords: ['satisfy', 'satisfying', 'content', 'dissatisfied'],
  },
  {
    id: 'satisfy',
    word: 'satisfy',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['満足させる', '(条件などを)満たす'],
    pronunciation: '/ˈsætɪsfaɪ/',
    exampleSentence: 'The explanation did not satisfy everyone in the room.',
    exampleTranslationJa: 'その説明は部屋にいた全員を満足させたわけではなかった。',
    collocations: ['satisfy a need', 'satisfy the requirements', 'satisfy curiosity'],
    wordFormation: 'satis(十分 ← ラテン語)+ -fy(〜にする)。「十分な状態にする」。',
    relatedWords: ['satisfaction', 'satisfied', 'fulfill', 'please'],
  },
  {
    id: 'saving',
    word: 'saving',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['節約', '(複数形 savings で)貯金、蓄え'],
    pronunciation: '/ˈseɪvɪŋ/',
    exampleSentence: 'They used their savings to buy a small house near the beach.',
    exampleTranslationJa: '彼らは貯金を使って海辺の近くに小さな家を買った。',
    collocations: ['savings account', 'life savings', 'a saving of ten percent'],
    wordFormation: 'save(蓄える、節約する)+ -ing(名詞化)',
    relatedWords: ['save', 'deposit', 'budget'],
  },
  {
    id: 'scale',
    word: 'scale',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['規模', '目盛り、尺度', '(複数形で)体重計、はかり'],
    pronunciation: '/skeɪl/',
    exampleSentence: 'The earthquake caused damage on a massive scale.',
    exampleTranslationJa: 'その地震は大規模な被害をもたらした。',
    collocations: ['on a large scale', 'a scale of one to ten', 'full-scale'],
    etymology: '「規模、目盛り」の意味はラテン語 scala(はしご)から。',
    relatedWords: ['size', 'range', 'measure'],
  },
  {
    id: 'scan',
    word: 'scan',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['ざっと見る、走り読みする', 'スキャンする、読み取る', '(名詞)精密検査、スキャン'],
    pronunciation: '/skæn/',
    exampleSentence: 'Scan the QR code to see the full menu.',
    exampleTranslationJa: 'QRコードをスキャンして全メニューをご覧ください。',
    collocations: ['scan a document', 'scan the headlines', 'brain scan'],
    relatedWords: ['scanner', 'skim', 'examine'],
  },
  {
    id: 'scare',
    word: 'scare',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['怖がらせる、おびえさせる', '(名詞)恐怖、不安'],
    pronunciation: '/sker/',
    exampleSentence: 'The loud thunder scared the children last night.',
    exampleTranslationJa: '昨夜、大きな雷鳴が子どもたちを怖がらせた。',
    collocations: ['scare someone away', 'scare someone to death', 'health scare'],
    relatedWords: ['scared', 'scary', 'frighten', 'terrify'],
  },
  {
    id: 'scared',
    word: 'scared',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['怖がって、おびえて(scared of)'],
    pronunciation: '/skerd/',
    exampleSentence: 'My little brother is scared of the dark.',
    exampleTranslationJa: '弟は暗闇を怖がっている。',
    collocations: ['be scared of', 'scared to death', 'feel scared'],
    wordFormation: 'scare(怖がらせる)の過去分詞が形容詞化したもの',
    relatedWords: ['scare', 'afraid', 'frightened', 'terrified'],
  },
  {
    id: 'scene',
    word: 'scene',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(映画・劇の)場面、シーン', '現場', '光景'],
    pronunciation: '/siːn/',
    exampleSentence: 'The opening scene of the movie takes place in Tokyo.',
    exampleTranslationJa: 'その映画の冒頭のシーンは東京が舞台だ。',
    collocations: ['the scene of the accident', 'behind the scenes', 'opening scene'],
    etymology: 'ギリシャ語 skene(舞台、テント)から。',
    relatedWords: ['scenery', 'setting', 'sight'],
  },
  {
    id: 'schedule',
    word: 'schedule',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['予定、スケジュール', '(動詞)予定する'],
    pronunciation: '/ˈskedʒuːl/',
    exampleSentence: 'The project is running behind schedule because of the delays.',
    exampleTranslationJa: '遅延のせいでプロジェクトは予定より遅れている。',
    collocations: ['on schedule', 'behind schedule', 'a busy schedule', 'be scheduled for'],
    etymology: 'ラテン語 schedula(小さな紙片)から。「紙に書かれた予定表」の意味に発展した。',
    relatedWords: ['timetable', 'plan', 'agenda'],
  },
  {
    id: 'scheme',
    word: 'scheme',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['計画、制度(主にイギリス英語)', 'たくらみ、悪だくみ'],
    pronunciation: '/skiːm/',
    exampleSentence: 'The city introduced a new scheme to encourage recycling.',
    exampleTranslationJa: '市はリサイクルを促進する新しい制度を導入した。',
    collocations: ['pension scheme', 'color scheme', 'a scheme to do'],
    etymology: 'ギリシャ語 schema(形、図)から。',
    relatedWords: ['plan', 'program', 'project'],
  },
  {
    id: 'scholar',
    word: 'scholar',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['学者', '奨学生'],
    pronunciation: '/ˈskɑːlər/',
    exampleSentence: 'She is a respected scholar of Japanese history.',
    exampleTranslationJa: '彼女は日本史の尊敬される学者だ。',
    collocations: ['a leading scholar', 'legal scholar', 'visiting scholar'],
    etymology: 'ギリシャ語 schole(暇、そこから学問の意)が語源。school と同根。',
    relatedWords: ['scholarship', 'academic', 'researcher', 'expert'],
  },
  {
    id: 'scientific',
    word: 'scientific',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['科学の、科学的な'],
    pronunciation: '/ˌsaɪənˈtɪfɪk/',
    exampleSentence: 'There is no scientific evidence to support that claim.',
    exampleTranslationJa: 'その主張を裏づける科学的な証拠はない。',
    collocations: ['scientific evidence', 'scientific research', 'scientific method'],
    wordFormation: 'scien(知る ← ラテン語 scire)+ -ific(〜を作る)。science の形容詞形。',
    relatedWords: ['science', 'scientist', 'academic'],
  },
  {
    id: 'score',
    word: 'score',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['得点、点数', '(動詞)得点する'],
    pronunciation: '/skɔːr/',
    exampleSentence: 'She got a high score on the English test.',
    exampleTranslationJa: '彼女は英語のテストで高得点を取った。',
    collocations: ['high score', 'final score', 'score a goal'],
    etymology: '古ノルド語 skor(刻み目)から。昔は木に刻み目を付けて数を数えた。',
    relatedWords: ['point', 'grade', 'result'],
  },
  {
    id: 'scratch',
    word: 'scratch',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['引っかく、かく', '(名詞)引っかき傷', 'from scratch で「最初から、ゼロから」'],
    pronunciation: '/skrætʃ/',
    exampleSentence: 'The cat scratched the sofa again this morning.',
    exampleTranslationJa: '猫が今朝またソファを引っかいた。',
    collocations: ['scratch your head', 'from scratch', 'scratch the surface'],
    relatedWords: ['scrape', 'rub', 'mark'],
  },
  {
    id: 'scream',
    word: 'scream',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['悲鳴を上げる、叫ぶ', '(名詞)悲鳴'],
    pronunciation: '/skriːm/',
    exampleSentence: 'She screamed when she saw a spider in the bathroom.',
    exampleTranslationJa: '彼女は浴室でクモを見て悲鳴を上げた。',
    collocations: ['scream in pain', 'scream at someone', 'scream for help'],
    relatedWords: ['shout', 'yell', 'cry'],
  },
  {
    id: 'screen',
    word: 'screen',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['画面、スクリーン', '(動詞)検査する、ふるいにかける'],
    pronunciation: '/skriːn/',
    exampleSentence: 'I spend too much time looking at my phone screen every day.',
    exampleTranslationJa: '毎日スマートフォンの画面を見るのに時間を使いすぎている。',
    collocations: ['on screen', 'touch screen', 'screen time'],
    relatedWords: ['display', 'monitor', 'screening'],
  },
  {
    id: 'seal',
    word: 'seal',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['密封する、封をする', '(名詞)印、封印', '(名詞)アザラシ'],
    pronunciation: '/siːl/',
    exampleSentence: 'Seal the envelope before you mail the letter.',
    exampleTranslationJa: '手紙を出す前に封筒に封をしてください。',
    collocations: ['seal an envelope', 'seal a deal', 'tightly sealed'],
    etymology: '「印、封印」の意味はラテン語 sigillum(小さな印)から。動物のアザラシは別語源。',
    relatedWords: ['close', 'stamp', 'signature'],
  },
  {
    id: 'search',
    word: 'search',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['探す、捜索する(search for)', '(名詞)捜索、検索'],
    pronunciation: '/sɜːrtʃ/',
    exampleSentence: 'The police searched the area for the missing child.',
    exampleTranslationJa: '警察は行方不明の子どもを求めてその地域を捜索した。',
    collocations: ['search for', 'in search of', 'search engine', 'search results'],
    etymology: 'ラテン語 circare(歩き回る)から。circus(円)が語根で circle と同根。',
    relatedWords: ['seek', 'look for', 'explore'],
  },
  {
    id: 'section',
    word: 'section',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['部分、区画', '(本・書類の)節、セクション'],
    pronunciation: '/ˈsekʃn/',
    exampleSentence: 'You can find cooking books in the food section of the store.',
    exampleTranslationJa: '料理の本は店の食品コーナーで見つかります。',
    collocations: ['sports section', 'non-smoking section', 'the first section of'],
    wordFormation: 'sect(切る ← ラテン語 secare)+ -ion。「切り分けられた部分」。',
    relatedWords: ['part', 'division', 'segment', 'sector'],
  },
  {
    id: 'sector',
    word: 'sector',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['(経済・産業の)部門、分野'],
    pronunciation: '/ˈsektər/',
    exampleSentence: 'More young people are finding jobs in the technology sector.',
    exampleTranslationJa: 'より多くの若者がテクノロジー部門で仕事を見つけている。',
    collocations: ['private sector', 'public sector', 'financial sector'],
    wordFormation: 'sect(切る ← ラテン語 secare)+ -or。section と同じ語根。',
    relatedWords: ['section', 'industry', 'field'],
  },
  {
    id: 'secure',
    word: 'secure',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['安全な、安心な', 'しっかり固定された', '(動詞)確保する、守る'],
    pronunciation: '/sɪˈkjʊr/',
    exampleSentence: 'Make sure the door is secure before you leave the house.',
    exampleTranslationJa: '家を出る前にドアがしっかり閉まっているか確認しなさい。',
    collocations: ['feel secure', 'a secure job', 'secure a place'],
    wordFormation: 'se-(〜なしに)+ cure(心配 ← ラテン語 cura)。「心配のない状態」。sure と同根。',
    relatedWords: ['security', 'safe', 'insecure', 'protect'],
  },
  {
    id: 'security',
    word: 'security',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['安全、防犯、セキュリティ', '安心感'],
    pronunciation: '/sɪˈkjʊrəti/',
    exampleSentence: 'Airport security checks all bags before the flight.',
    exampleTranslationJa: '空港の保安検査では搭乗前にすべての荷物を調べる。',
    collocations: ['security camera', 'security guard', 'national security', 'a sense of security'],
    wordFormation: 'secure(安全な)+ -ity(名詞化の接尾辞)',
    relatedWords: ['secure', 'safety', 'protection'],
  },
  {
    id: 'seek',
    word: 'seek',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['探し求める', '(助言・助けなどを)求める'],
    pronunciation: '/siːk/',
    exampleSentence: 'You should seek advice from a doctor before taking this medicine.',
    exampleTranslationJa: 'この薬を飲む前に医師の助言を求めるべきだ。',
    collocations: ['seek advice', 'seek help', 'seek employment'],
    relatedWords: ['search', 'pursue', 'look for'],
  },
  {
    id: 'select',
    word: 'select',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['選ぶ、選択する'],
    pronunciation: '/sɪˈlekt/',
    exampleSentence: 'Select the file you want to delete and press this button.',
    exampleTranslationJa: '削除したいファイルを選択して、このボタンを押してください。',
    collocations: ['select from', 'carefully selected', 'select an option'],
    wordFormation: 'se-(分けて)+ lect(選ぶ、集める ← ラテン語 legere)。collect や elect と同じ語根。',
    relatedWords: ['selection', 'choose', 'pick'],
  },
  {
    id: 'selection',
    word: 'selection',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['選択、選抜', '選ばれたもの、品ぞろえ'],
    pronunciation: '/sɪˈlekʃn/',
    exampleSentence: 'The store offers a wide selection of cheeses from around the world.',
    exampleTranslationJa: 'その店は世界中のチーズの幅広い品ぞろえを提供している。',
    collocations: ['a wide selection of', 'natural selection', 'selection process'],
    wordFormation: 'select(選ぶ)+ -ion(名詞化の接尾辞)',
    relatedWords: ['select', 'choice', 'variety'],
  },
  {
    id: 'senior',
    word: 'senior',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['上位の、上級の', '年上の', '(名詞)年長者、最上級生'],
    pronunciation: '/ˈsiːniər/',
    exampleSentence: 'She was promoted to a senior position in the marketing department.',
    exampleTranslationJa: '彼女はマーケティング部の上級職に昇進した。',
    collocations: ['senior manager', 'senior citizen', 'senior to someone'],
    etymology: 'ラテン語 senex(老いた)の比較級で「より年上の」の意。senator と同根。',
    relatedWords: ['junior', 'superior', 'elderly'],
  },
  {
    id: 'sense',
    word: 'sense',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['感覚', '意味', '分別(make sense で「意味をなす、理にかなう」)'],
    pronunciation: '/sens/',
    exampleSentence: 'Dogs have a much better sense of smell than humans.',
    exampleTranslationJa: '犬は人間よりもはるかに優れた嗅覚を持っている。',
    collocations: ['make sense', 'a sense of humor', 'common sense', 'in a sense'],
    etymology: 'ラテン語 sensus(感覚)から。sentire(感じる)が語根。',
    relatedWords: ['sensible', 'sensitive', 'feeling', 'sensation'],
  },
  {
    id: 'sensible',
    word: 'sensible',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['分別のある、賢明な'],
    pronunciation: '/ˈsensəbl/',
    exampleSentence: 'It was sensible of you to save money before quitting your job.',
    exampleTranslationJa: '仕事を辞める前に貯金するとは賢明だった。',
    collocations: ['a sensible decision', 'sensible advice', 'sensible shoes'],
    wordFormation: 'sens(感じる ← ラテン語 sentire)+ -ible。sensitive(敏感な)との意味の違いに注意。',
    mnemonic: 'sensible は「センスのある判断ができる=賢明な」と覚える。',
    relatedWords: ['sensitive', 'reasonable', 'wise', 'practical'],
  },
  {
    id: 'sensitive',
    word: 'sensitive',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['敏感な、傷つきやすい', '(問題などが)デリケートな、取り扱いに注意を要する'],
    pronunciation: '/ˈsensətɪv/',
    exampleSentence: 'Her skin is very sensitive to strong sunlight.',
    exampleTranslationJa: '彼女の肌は強い日差しにとても敏感だ。',
    collocations: ['sensitive to', 'sensitive skin', 'a sensitive issue', 'sensitive information'],
    wordFormation: 'sens(感じる ← ラテン語 sentire)+ -itive。sensible(賢明な)との意味の違いに注意。',
    relatedWords: ['sensible', 'sensitivity', 'delicate'],
  },
  {
    id: 'sentence',
    word: 'sentence',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['文', '判決、刑', '(動詞)判決を下す'],
    pronunciation: '/ˈsentəns/',
    exampleSentence: 'Write a sentence using each new word you learned today.',
    exampleTranslationJa: '今日学んだ新しい単語をそれぞれ使って文を書きなさい。',
    collocations: ['write a sentence', 'complete sentence', 'a prison sentence'],
    etymology: 'ラテン語 sententia(意見、判断)から。sentire(感じる)が語根で sense と同根。',
    relatedWords: ['phrase', 'paragraph', 'grammar'],
  },
  {
    id: 'separate',
    word: 'separate',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['分ける、引き離す', '(形容詞)別々の、分かれた(形容詞の発音は /ˈsepərət/)'],
    pronunciation: '/ˈsepəreɪt/',
    exampleSentence: 'Please separate the plastic bottles from the other trash.',
    exampleTranslationJa: 'ペットボトルは他のごみと分別してください。',
    collocations: ['separate A from B', 'a separate room', 'go their separate ways'],
    wordFormation: 'se-(離して)+ parate(整える ← ラテン語 parare)。prepare と同じ語根。',
    relatedWords: ['separation', 'divide', 'split', 'separately'],
  },
  {
    id: 'sequence',
    word: 'sequence',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['連続、順序、一連'],
    pronunciation: '/ˈsiːkwəns/',
    exampleSentence: 'The book describes the sequence of events that led to the war.',
    exampleTranslationJa: 'その本は戦争に至った一連の出来事を描いている。',
    collocations: ['a sequence of events', 'in sequence', 'follow a sequence'],
    wordFormation: 'sequ(続く、従う ← ラテン語 sequi)+ -ence。consequence と同じ語根。',
    relatedWords: ['order', 'series', 'consequence'],
  },
  {
    id: 'series',
    word: 'series',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['一連、連続(a series of)', '(テレビなどの)シリーズ'],
    pronunciation: '/ˈsɪriːz/',
    exampleSentence: 'The city held a series of concerts in the park this summer.',
    exampleTranslationJa: '市はこの夏、公園で一連のコンサートを開催した。',
    collocations: ['a series of', 'TV series', 'a new series'],
    etymology: 'ラテン語 serere(つなぐ)から。「つながったもの」。',
    relatedWords: ['sequence', 'season', 'succession'],
  },
  {
    id: 'serious',
    word: 'serious',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['深刻な、重大な', '真剣な、まじめな'],
    pronunciation: '/ˈsɪriəs/',
    exampleSentence: 'Air pollution is a serious problem in many big cities.',
    exampleTranslationJa: '大気汚染は多くの大都市で深刻な問題だ。',
    collocations: ['serious problem', 'serious injury', 'be serious about'],
    relatedWords: ['seriously', 'severe', 'grave'],
  },
  {
    id: 'seriously',
    word: 'seriously',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['深刻に、ひどく', '真剣に、まじめに'],
    pronunciation: '/ˈsɪriəsli/',
    exampleSentence: 'Two people were seriously injured in the accident.',
    exampleTranslationJa: 'その事故で2人が重傷を負った。',
    collocations: ['seriously injured', 'take something seriously', 'seriously ill'],
    wordFormation: 'serious(深刻な)+ -ly(副詞化の接尾辞)',
    relatedWords: ['serious', 'severely', 'badly'],
  },
  {
    id: 'serve',
    word: 'serve',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(食事を)出す、給仕する', '仕える、勤める', '役立つ(serve as)'],
    pronunciation: '/sɜːrv/',
    exampleSentence: 'The restaurant serves breakfast from seven to ten in the morning.',
    exampleTranslationJa: 'そのレストランは朝7時から10時まで朝食を提供している。',
    collocations: ['serve food', 'serve customers', 'serve as'],
    etymology: 'ラテン語 servire(仕える)から。servus(召使い)が語根。',
    relatedWords: ['service', 'server', 'provide'],
  },
  {
    id: 'service',
    word: 'service',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['サービス、接客', '公共事業、業務', '点検、修理'],
    pronunciation: '/ˈsɜːrvɪs/',
    exampleSentence: 'The hotel is famous for its excellent customer service.',
    exampleTranslationJa: 'そのホテルは素晴らしい顧客サービスで有名だ。',
    collocations: ['customer service', 'public services', 'service charge'],
    wordFormation: 'serve(仕える)+ -ice(名詞化の接尾辞)',
    relatedWords: ['serve', 'assistance', 'support'],
  },
  {
    id: 'session',
    word: 'session',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['(活動の)時間、セッション', '会議、会期'],
    pronunciation: '/ˈseʃn/',
    exampleSentence: 'We have a training session every Monday morning.',
    exampleTranslationJa: '毎週月曜の朝にトレーニングセッションがある。',
    collocations: ['training session', 'question and answer session', 'hold a session'],
    etymology: 'ラテン語 sedere(座る)から。「座って行う集まり」の意。',
    relatedWords: ['meeting', 'class', 'period'],
  },
  {
    id: 'set-up',
    word: 'set up',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['設立する、立ち上げる', '設置する、準備する'],
    pronunciation: '/set ʌp/',
    exampleSentence: 'They set up a small company to sell handmade furniture.',
    exampleTranslationJa: '彼らは手作り家具を販売する小さな会社を設立した。',
    collocations: ['set up a business', 'set up a meeting', 'set up equipment'],
    relatedWords: ['establish', 'found', 'organize', 'setup'],
  },
  {
    id: 'settle',
    word: 'settle',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['解決する', '定住する、落ち着く(settle down)', '(勘定を)清算する'],
    pronunciation: '/ˈsetl/',
    exampleSentence: 'After years of traveling, they finally settled in a small town.',
    exampleTranslationJa: '何年も旅をした後、彼らはついに小さな町に定住した。',
    collocations: ['settle a dispute', 'settle down', 'settle in', 'settle the bill'],
    etymology: '古英語 setl(座席)から。sit や set と同根で「腰を落ち着ける」が原義。',
    relatedWords: ['settlement', 'resolve', 'settle down'],
  },
  {
    id: 'severe',
    word: 'severe',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['深刻な、ひどい', '厳しい、厳格な'],
    pronunciation: '/sɪˈvɪr/',
    exampleSentence: 'The region suffered severe damage from the typhoon.',
    exampleTranslationJa: 'その地域は台風で深刻な被害を受けた。',
    collocations: ['severe weather', 'severe pain', 'severe punishment'],
    relatedWords: ['severely', 'serious', 'harsh', 'strict'],
  },
  {
    id: 'shade',
    word: 'shade',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['日陰、陰', '色合い、色調'],
    pronunciation: '/ʃeɪd/',
    exampleSentence: 'We sat in the shade of a large tree to escape the heat.',
    exampleTranslationJa: '暑さを逃れるために大きな木の陰に座った。',
    collocations: ['in the shade', 'a shade of blue', 'provide shade'],
    etymology: '古英語 sceadu(影)から。shadow と同じ語源。',
    relatedWords: ['shadow', 'shady', 'sunshine'],
  },
  {
    id: 'shadow',
    word: 'shadow',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['影'],
    pronunciation: '/ˈʃædoʊ/',
    exampleSentence: 'The tree cast a long shadow across the garden in the evening.',
    exampleTranslationJa: '夕方、その木は庭に長い影を落とした。',
    collocations: ['cast a shadow', 'in the shadow of', 'long shadows'],
    etymology: '古英語 sceadu(影)から。shade と同じ語源。shade は「日陰」、shadow は「輪郭のある影」。',
    relatedWords: ['shade', 'silhouette', 'darkness'],
  },
  {
    id: 'shallow',
    word: 'shallow',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['浅い', '浅はかな、うわべだけの'],
    pronunciation: '/ˈʃæloʊ/',
    exampleSentence: 'The water is shallow here, so it is safe for children to swim.',
    exampleTranslationJa: 'ここは水が浅いので、子どもが泳いでも安全だ。',
    collocations: ['shallow water', 'shallow breathing', 'a shallow argument'],
    relatedWords: ['deep', 'depth', 'superficial'],
  },
  {
    id: 'shame',
    word: 'shame',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['恥、恥ずかしさ', '残念なこと(What a shame! で「なんて残念な」)'],
    pronunciation: '/ʃeɪm/',
    exampleSentence: "It's a shame that you can't come to the party tonight.",
    exampleTranslationJa: '今夜パーティーに来られないとは残念だ。',
    collocations: ["it's a shame that", 'what a shame', 'feel shame', 'a sense of shame'],
    relatedWords: ['ashamed', 'embarrassment', 'pity'],
  },
  {
    id: 'shape',
    word: 'shape',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['形、形状', '調子、状態(in good shape)', '(動詞)形作る'],
    pronunciation: '/ʃeɪp/',
    exampleSentence: 'The cookies were made in the shape of stars and hearts.',
    exampleTranslationJa: 'そのクッキーは星やハートの形に作られていた。',
    collocations: ['in the shape of', 'in good shape', 'take shape'],
    relatedWords: ['form', 'figure', 'design'],
  },
  {
    id: 'share',
    word: 'share',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['共有する、分け合う', '(名詞)分け前、株'],
    pronunciation: '/ʃer/',
    exampleSentence: 'I share an apartment with two friends from college.',
    exampleTranslationJa: '大学時代の友人2人とアパートを共有している。',
    collocations: ['share A with B', 'share information', 'share an opinion', 'market share'],
    etymology: '古英語 scearu(切り分けること)から。shear(刈る)と同根で「切り分けて配る」が原義。',
    relatedWords: ['divide', 'split', 'shared', 'shareholder'],
  },
]
