import type { VocabularyEntry } from '../types'

export const batch03: VocabularyEntry[] = [
  {
    id: 'eventually',
    word: 'eventually',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['(時間や困難を経て)最終的に、結局'],
    pronunciation: '/ɪˈventʃuəli/',
    exampleSentence: 'After months of practice, she eventually passed her driving test.',
    exampleTranslationJa: '何か月も練習した末に、彼女は最終的に運転免許試験に合格した。',
    collocations: ['eventually become', 'eventually find', 'eventually lead to'],
    wordFormation: 'event(出来事)+ -ual + -ly。「出来事の成り行きの果てに」というイメージ。',
    relatedWords: ['finally', 'in the end', 'ultimately'],
  },
  {
    id: 'evidence',
    word: 'evidence',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['証拠', '根拠'],
    pronunciation: '/ˈevɪdəns/',
    exampleSentence: 'The police found no evidence that he was involved in the crime.',
    exampleTranslationJa: '警察は彼が犯罪に関与したという証拠を見つけられなかった。',
    collocations: ['strong evidence', 'provide evidence', 'scientific evidence'],
    wordFormation: 'e(ex-)=外に + vid=見る(ラテン語 videre)+ -ence →外からはっきり見えるもの→証拠。',
    relatedWords: ['evident', 'proof', 'clue'],
  },
  {
    id: 'evident',
    word: 'evident',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['明らかな、明白な'],
    pronunciation: '/ˈevɪdənt/',
    exampleSentence: 'It was evident from her smile that she was pleased with the results.',
    exampleTranslationJa: '彼女の笑顔から、結果に満足していることは明らかだった。',
    collocations: ['it is evident that', 'become evident', 'clearly evident'],
    wordFormation: 'e(ex-)=外に + vid=見る + -ent →外からはっきり見える→明らかな。evidence の形容詞形。',
    relatedWords: ['obvious', 'apparent', 'evidence'],
  },
  {
    id: 'evil',
    word: 'evil',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['邪悪な、悪意のある', '(名詞)悪'],
    pronunciation: '/ˈiːvl/',
    exampleSentence: 'The story is about the battle between good and evil.',
    exampleTranslationJa: 'その物語は善と悪の戦いを描いている。',
    collocations: ['an evil spirit', 'good and evil', 'an evil plan'],
    relatedWords: ['wicked', 'cruel', 'good'],
  },
  {
    id: 'evolve',
    word: 'evolve',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['進化する', '徐々に発展する'],
    pronunciation: '/ɪˈvɑːlv/',
    exampleSentence: 'Smartphones have evolved rapidly over the past twenty years.',
    exampleTranslationJa: 'スマートフォンはこの20年で急速に進化してきた。',
    collocations: ['evolve into', 'evolve from', 'gradually evolve'],
    wordFormation: 'e(ex-)=外へ + volve=巻く(ラテン語 volvere)→巻物を広げていく→徐々に展開・発展する。',
    relatedWords: ['evolution', 'develop', 'revolve'],
  },
  {
    id: 'exact',
    word: 'exact',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['正確な、ちょうどの'],
    pronunciation: '/ɪɡˈzækt/',
    exampleSentence: "I can't remember the exact date, but it was sometime in June.",
    exampleTranslationJa: '正確な日付は思い出せないが、6月のいつかだった。',
    collocations: ['the exact time', 'the exact location', 'to be exact'],
    relatedWords: ['exactly', 'precise', 'accurate'],
  },
  {
    id: 'examine',
    word: 'examine',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['詳しく調べる、検査する', '(医者が)診察する'],
    pronunciation: '/ɪɡˈzæmɪn/',
    exampleSentence: 'The doctor examined her carefully but found nothing wrong.',
    exampleTranslationJa: '医者は彼女を注意深く診察したが、異常は見つからなかった。',
    collocations: ['examine the evidence', 'examine carefully', 'examine a patient'],
    wordFormation: '名詞は examination。試験を表す exam はその短縮形。',
    relatedWords: ['exam', 'examination', 'inspect'],
  },
  {
    id: 'exceed',
    word: 'exceed',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['超える、上回る'],
    pronunciation: '/ɪkˈsiːd/',
    exampleSentence: 'Sales this year exceeded our expectations by twenty percent.',
    exampleTranslationJa: '今年の売上は私たちの予想を20パーセント上回った。',
    collocations: ['exceed expectations', 'exceed the limit', 'exceed the budget'],
    wordFormation: 'ex-=外へ + ceed=行く(ラテン語 cedere)→限度の外へ出て行く→超える。',
    relatedWords: ['excess', 'excessive', 'surpass'],
  },
  {
    id: 'excellent',
    word: 'excellent',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['非常に優れた、素晴らしい'],
    pronunciation: '/ˈeksələnt/',
    exampleSentence: 'The hotel staff gave us excellent service during our stay.',
    exampleTranslationJa: '滞在中、ホテルのスタッフは素晴らしいサービスを提供してくれた。',
    collocations: ['an excellent opportunity', 'excellent service', 'an excellent example'],
    wordFormation: 'excel(秀でる)+ -ent。名詞形は excellence(卓越)。',
    relatedWords: ['excel', 'excellence', 'outstanding'],
  },
  {
    id: 'exception',
    word: 'exception',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['例外'],
    pronunciation: '/ɪkˈsepʃn/',
    exampleSentence: 'Everyone must attend the meeting, and no exceptions will be made.',
    exampleTranslationJa: '全員が会議に出席しなければならず、例外は認められない。',
    collocations: ['with the exception of', 'make an exception', 'without exception'],
    wordFormation: 'ex-=外に + cept=取る(ラテン語 capere)+ -ion →外に取り出されたもの→例外。accept や concept と同じ語根。',
    relatedWords: ['except', 'exceptional', 'exclude'],
  },
  {
    id: 'exchange',
    word: 'exchange',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['交換する', '(名詞)交換、両替'],
    pronunciation: '/ɪksˈtʃeɪndʒ/',
    exampleSentence: 'We exchanged phone numbers before the end of the conference.',
    exampleTranslationJa: '会議が終わる前に、私たちは電話番号を交換した。',
    collocations: ['exchange information', 'an exchange rate', 'in exchange for'],
    wordFormation: 'ex-=互いに外へ + change=変える →互いに取り替える。',
    relatedWords: ['change', 'trade', 'swap'],
  },
  {
    id: 'exhibit',
    word: 'exhibit',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['展示する', '(感情・特徴を)示す', '(名詞)展示品'],
    pronunciation: '/ɪɡˈzɪbɪt/',
    exampleSentence: 'The museum will exhibit works by local artists next month.',
    exampleTranslationJa: 'その美術館は来月、地元アーティストの作品を展示する。',
    collocations: ['exhibit paintings', 'exhibit signs of'],
    wordFormation: 'ex-=外に + hibit=持つ(ラテン語 habere)→外に持ち出して見せる→展示する。',
    relatedWords: ['exhibition', 'display', 'show'],
  },
  {
    id: 'exhibition',
    word: 'exhibition',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['展覧会、展示会'],
    pronunciation: '/ˌeksɪˈbɪʃn/',
    exampleSentence: 'We went to a photography exhibition at the city museum.',
    exampleTranslationJa: '私たちは市立美術館の写真展に行った。',
    collocations: ['hold an exhibition', 'an art exhibition', 'a special exhibition'],
    wordFormation: 'exhibit(展示する)+ -ion。',
    relatedWords: ['exhibit', 'display', 'gallery'],
  },
  {
    id: 'exist',
    word: 'exist',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['存在する'],
    pronunciation: '/ɪɡˈzɪst/',
    exampleSentence: 'Scientists believe that water may exist on other planets.',
    exampleTranslationJa: '科学者たちは、他の惑星に水が存在するかもしれないと考えている。',
    collocations: ['continue to exist', 'still exist'],
    wordFormation: 'ex-=外に + (s)ist=立つ(ラテン語 sistere)→姿を現して立つ→存在する。',
    relatedWords: ['existence', 'existing', 'survive'],
  },
  {
    id: 'existence',
    word: 'existence',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['存在', '生存、生活'],
    pronunciation: '/ɪɡˈzɪstəns/',
    exampleSentence: 'The company has faced many challenges during its fifty years of existence.',
    exampleTranslationJa: 'その会社は50年の歴史の中で多くの困難に直面してきた。',
    collocations: ['come into existence', 'the existence of', 'daily existence'],
    wordFormation: 'exist(存在する)+ -ence(名詞化)。',
    relatedWords: ['exist', 'presence', 'survival'],
  },
  {
    id: 'expand',
    word: 'expand',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['拡大する、広げる', '(事業を)拡張する'],
    pronunciation: '/ɪkˈspænd/',
    exampleSentence: 'The company plans to expand its business into Asian markets.',
    exampleTranslationJa: 'その会社はアジア市場へ事業を拡大する計画だ。',
    collocations: ['expand the business', 'expand rapidly', 'expand into'],
    wordFormation: 'ex-=外へ + pand=広げる(ラテン語 pandere)。名詞形は expansion。',
    relatedWords: ['expansion', 'extend', 'grow'],
  },
  {
    id: 'expectation',
    word: 'expectation',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['期待', '予想'],
    pronunciation: '/ˌekspekˈteɪʃn/',
    exampleSentence: 'The new movie failed to meet the expectations of its fans.',
    exampleTranslationJa: 'その新作映画はファンの期待に応えられなかった。',
    collocations: ['meet expectations', 'exceed expectations', 'high expectations'],
    wordFormation: 'expect + -ation。expect は ex-=外を + spect=見る(ラテン語 spectare)→外を見て待ち構える→期待する。',
    relatedWords: ['expect', 'anticipate', 'hope'],
  },
  {
    id: 'expense',
    word: 'expense',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['費用、出費'],
    pronunciation: '/ɪkˈspens/',
    exampleSentence: 'Moving to a new city involves a lot of unexpected expenses.',
    exampleTranslationJa: '新しい街への引っ越しには、多くの予想外の出費がともなう。',
    collocations: ['living expenses', 'at your own expense', 'cut expenses'],
    wordFormation: 'ex-=外へ + pense=支払う・量る(ラテン語 pendere)→支払われるお金→費用。expensive の名詞形にあたる。',
    relatedWords: ['expensive', 'cost', 'spending'],
  },
  {
    id: 'experiment',
    word: 'experiment',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['実験', '(動詞)実験する、試す'],
    pronunciation: '/ɪkˈsperɪmənt/',
    exampleSentence: 'The students conducted an experiment to test their theory.',
    exampleTranslationJa: '生徒たちは自分たちの仮説を確かめるために実験を行った。',
    collocations: ['conduct an experiment', 'a scientific experiment', 'experiment with'],
    wordFormation: 'experi=試す(ラテン語 experiri)+ -ment。experience(経験)や expert(専門家)と同じ語根。',
    relatedWords: ['experience', 'expert', 'test'],
  },
  {
    id: 'expert',
    word: 'expert',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['専門家、熟練者', '(形容詞)熟練した'],
    pronunciation: '/ˈekspɜːrt/',
    exampleSentence: 'She is an expert on climate change and often appears on TV.',
    exampleTranslationJa: '彼女は気候変動の専門家で、テレビによく出演している。',
    collocations: ['an expert on', 'expert advice', 'a leading expert'],
    wordFormation: 'ラテン語 expertus(経験を積んだ)から。experiri=試す が語根で、experience や experiment と同族。',
    relatedWords: ['expertise', 'specialist', 'professional'],
  },
  {
    id: 'explanation',
    word: 'explanation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['説明', '理由、釈明'],
    pronunciation: '/ˌekspləˈneɪʃn/',
    exampleSentence: 'The teacher gave a clear explanation of the grammar rule.',
    exampleTranslationJa: '先生はその文法規則をわかりやすく説明してくれた。',
    collocations: ['give an explanation', 'a clear explanation', 'an explanation for'],
    wordFormation: 'explain + -ation。explain は ex-=完全に + plain=平らな(ラテン語 planus)→平らにならす→わかりやすくする。',
    relatedWords: ['explain', 'reason', 'description'],
  },
  {
    id: 'explode',
    word: 'explode',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['爆発する', '(怒りなどが)爆発する'],
    pronunciation: '/ɪkˈsploʊd/',
    exampleSentence: 'A gas pipe exploded, but fortunately no one was hurt.',
    exampleTranslationJa: 'ガス管が爆発したが、幸いけが人はいなかった。',
    collocations: ['a bomb explodes', 'explode with anger'],
    etymology: 'ラテン語 explodere(拍手やヤジで役者を舞台から追い出す)から。ex-=外へ + plaudere=拍手する。「大きな音とともに外へ出す」イメージが爆発の意味につながった。',
    relatedWords: ['explosion', 'explosive', 'burst'],
  },
  {
    id: 'explore',
    word: 'explore',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['探検する', '(可能性などを)探る、検討する'],
    pronunciation: '/ɪkˈsplɔːr/',
    exampleSentence: 'We spent the whole day exploring the old town on foot.',
    exampleTranslationJa: '私たちは一日中、旧市街を歩いて探索した。',
    collocations: ['explore the city', 'explore possibilities', 'explore options'],
    relatedWords: ['exploration', 'explorer', 'investigate'],
  },
  {
    id: 'explosion',
    word: 'explosion',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['爆発', '急増'],
    pronunciation: '/ɪkˈsploʊʒn/',
    exampleSentence: 'The explosion could be heard from miles away.',
    exampleTranslationJa: 'その爆発音は何マイルも離れた場所から聞こえた。',
    collocations: ['a huge explosion', 'a population explosion', 'cause an explosion'],
    wordFormation: 'explode(爆発する)の名詞形。',
    relatedWords: ['explode', 'explosive', 'blast'],
  },
  {
    id: 'export',
    word: 'export',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['輸出する', '(名詞)輸出、輸出品'],
    pronunciation: '/ɪkˈspɔːrt/',
    exampleSentence: 'Japan exports cars and electronic products to countries around the world.',
    exampleTranslationJa: '日本は自動車や電子製品を世界中の国々に輸出している。',
    collocations: ['export goods', 'a major export', 'export to'],
    wordFormation: 'ex-=外へ + port=運ぶ(ラテン語 portare)→国の外へ運ぶ→輸出する。反対語は import(中へ運ぶ)。名詞は語頭にアクセント。',
    relatedWords: ['import', 'transport', 'trade'],
  },
  {
    id: 'expose',
    word: 'expose',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['さらす、触れさせる', '(秘密などを)暴く'],
    pronunciation: '/ɪkˈspoʊz/',
    exampleSentence: 'Children should not be exposed to violent movies.',
    exampleTranslationJa: '子どもたちを暴力的な映画にさらすべきではない。',
    collocations: ['be exposed to', 'expose the truth', 'expose a scandal'],
    wordFormation: 'ex-=外に + pose=置く →外に置いて人目にさらす。名詞形は exposure。',
    relatedWords: ['exposure', 'reveal', 'uncover'],
  },
  {
    id: 'express',
    word: 'express',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(考え・感情を)表現する', '(形容詞)急行の'],
    pronunciation: '/ɪkˈspres/',
    exampleSentence: 'It is sometimes difficult to express my feelings in English.',
    exampleTranslationJa: '英語で自分の気持ちを表現するのは難しいときがある。',
    collocations: ['express an opinion', 'express concern', 'express gratitude'],
    wordFormation: 'ex-=外へ + press=押す →心の中のものを外へ押し出す→表現する。',
    relatedWords: ['expression', 'impress', 'pressure'],
  },
  {
    id: 'expression',
    word: 'expression',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['表現、言い回し', '表情'],
    pronunciation: '/ɪkˈspreʃn/',
    exampleSentence: 'I could tell from her expression that something was wrong.',
    exampleTranslationJa: '彼女の表情から何かがおかしいとわかった。',
    collocations: ['a facial expression', 'a common expression', 'freedom of expression'],
    wordFormation: 'express(表現する)+ -ion。',
    relatedWords: ['express', 'phrase', 'look'],
  },
  {
    id: 'extend',
    word: 'extend',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['延長する', '広げる、及ぶ'],
    pronunciation: '/ɪkˈstend/',
    exampleSentence: 'The professor agreed to extend the deadline by one week.',
    exampleTranslationJa: '教授は締め切りを1週間延長することに同意した。',
    collocations: ['extend a deadline', 'extend a visa', 'extend an invitation'],
    wordFormation: 'ex-=外へ + tend=伸ばす(ラテン語 tendere)→外へ伸ばす→延長する。名詞形は extension。',
    relatedWords: ['extension', 'extent', 'expand'],
  },
  {
    id: 'extent',
    word: 'extent',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['程度', '範囲、規模'],
    pronunciation: '/ɪkˈstent/',
    exampleSentence: 'I agree with you to some extent, but I have a few concerns.',
    exampleTranslationJa: 'ある程度あなたに賛成だが、いくつか懸念もある。',
    collocations: ['to some extent', 'to a large extent', 'the full extent of'],
    wordFormation: 'extend(広げる)と同じ語根。「広げられた範囲」→程度。',
    relatedWords: ['extend', 'degree', 'scale'],
  },
  {
    id: 'external',
    word: 'external',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['外部の、外側の'],
    pronunciation: '/ɪkˈstɜːrnl/',
    exampleSentence: "The building's external walls were damaged in the storm.",
    exampleTranslationJa: 'その建物の外壁は嵐で損傷した。',
    collocations: ['external factors', 'external pressure', 'for external use'],
    wordFormation: 'exter=外の(exterior と同根)+ -al。反対語は internal(内部の)。',
    relatedWords: ['internal', 'exterior', 'outside'],
  },
  {
    id: 'extraordinary',
    word: 'extraordinary',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['並外れた、驚くべき'],
    pronunciation: '/ɪkˈstrɔːrdəneri/',
    exampleSentence: 'She has an extraordinary talent for learning languages.',
    exampleTranslationJa: '彼女には語学習得の並外れた才能がある。',
    collocations: ['an extraordinary achievement', 'an extraordinary talent', 'quite extraordinary'],
    wordFormation: 'extra-=〜の外・〜を越えた + ordinary=普通の →普通を越えた→並外れた。',
    relatedWords: ['ordinary', 'remarkable', 'exceptional'],
  },
  {
    id: 'extreme',
    word: 'extreme',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['極端な、極度の', '(名詞)極端'],
    pronunciation: '/ɪkˈstriːm/',
    exampleSentence: 'Extreme weather events are becoming more common around the world.',
    exampleTranslationJa: '極端な気象現象が世界中でますます一般的になっている。',
    collocations: ['extreme weather', 'extreme sports', 'in extreme cases'],
    etymology: 'ラテン語 extremus(「外の」を意味する exter の最上級)から。「一番外側の」→極端な。',
    relatedWords: ['extremely', 'excessive', 'moderate'],
  },
  {
    id: 'extremely',
    word: 'extremely',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['極めて、非常に'],
    pronunciation: '/ɪkˈstriːmli/',
    exampleSentence: 'The final exam was extremely difficult for most students.',
    exampleTranslationJa: '期末試験はほとんどの学生にとって非常に難しかった。',
    collocations: ['extremely difficult', 'extremely important', 'extremely rare'],
    wordFormation: 'extreme(極端な)+ -ly。very より強い強調を表す。',
    relatedWords: ['extreme', 'incredibly', 'highly'],
  },
  {
    id: 'facility',
    word: 'facility',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['施設、設備(通例 facilities)'],
    pronunciation: '/fəˈsɪləti/',
    exampleSentence: 'The new sports facility has a pool and two gyms.',
    exampleTranslationJa: 'その新しいスポーツ施設にはプールと2つのジムがある。',
    collocations: ['sports facilities', 'medical facilities', 'public facilities'],
    wordFormation: 'ラテン語 facilis(容易な)から。fac=作る・行う(facere)が語根で、fact や factory と同族。',
    relatedWords: ['equipment', 'factory', 'service'],
  },
  {
    id: 'factor',
    word: 'factor',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['要因、要素'],
    pronunciation: '/ˈfæktər/',
    exampleSentence: 'Price is an important factor when people choose a smartphone.',
    exampleTranslationJa: 'スマートフォンを選ぶとき、価格は重要な要因だ。',
    collocations: ['a key factor', 'an important factor in', 'a major factor'],
    wordFormation: 'fact=作る・行う(ラテン語 facere)+ -or →結果を作り出すもの→要因。',
    relatedWords: ['fact', 'element', 'cause'],
  },
  {
    id: 'fail',
    word: 'fail',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['失敗する', '(試験に)落ちる', '(fail to do で)〜しない、〜できない'],
    pronunciation: '/feɪl/',
    exampleSentence: 'If you fail the test, you can take it again next month.',
    exampleTranslationJa: '試験に落ちても、来月もう一度受けられます。',
    collocations: ['fail an exam', 'fail to do', 'never fail to'],
    relatedWords: ['failure', 'succeed', 'mistake'],
  },
  {
    id: 'failure',
    word: 'failure',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['失敗', '(機械などの)故障'],
    pronunciation: '/ˈfeɪljər/',
    exampleSentence: 'The project ended in failure because of poor planning.',
    exampleTranslationJa: 'そのプロジェクトは計画のまずさが原因で失敗に終わった。',
    collocations: ['end in failure', 'engine failure', 'fear of failure'],
    wordFormation: 'fail + -ure(名詞化。press → pressure と同じ接尾辞)。',
    relatedWords: ['fail', 'success', 'breakdown'],
  },
  {
    id: 'faith',
    word: 'faith',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['信頼', '信仰'],
    pronunciation: '/feɪθ/',
    exampleSentence: "She never lost faith in her son's ability to succeed.",
    exampleTranslationJa: '彼女は息子が成功する力を信じ続けた。',
    collocations: ['have faith in', 'lose faith', 'religious faith'],
    etymology: 'ラテン語 fides(信頼)に由来する。faithful や confident に含まれる fid- と同じ語根。',
    relatedWords: ['faithful', 'belief', 'trust'],
  },
  {
    id: 'fake',
    word: 'fake',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['偽の、偽造の', '(名詞)偽物', '(動詞)偽る、でっちあげる'],
    pronunciation: '/feɪk/',
    exampleSentence: 'The police discovered that the painting was a fake.',
    exampleTranslationJa: '警察はその絵が偽物であることを突き止めた。',
    collocations: ['fake news', 'a fake smile', 'a fake ID'],
    relatedWords: ['false', 'genuine', 'artificial'],
  },
  {
    id: 'familiar',
    word: 'familiar',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['よく知っている、なじみのある'],
    pronunciation: '/fəˈmɪliər/',
    exampleSentence: 'Are you familiar with the rules of baseball?',
    exampleTranslationJa: '野球のルールをよくご存じですか。',
    collocations: ['be familiar with', 'look familiar', 'a familiar face'],
    etymology: 'ラテン語 familia(家族)から。「家族のようによく知っている」が原義。',
    relatedWords: ['family', 'unfamiliar', 'well-known'],
  },
  {
    id: 'fancy',
    word: 'fancy',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['高級な、しゃれた', '手の込んだ', '(動詞・主に英)欲しいと思う'],
    pronunciation: '/ˈfænsi/',
    exampleSentence: 'They celebrated their anniversary at a fancy restaurant downtown.',
    exampleTranslationJa: '彼らは繁華街の高級レストランで記念日を祝った。',
    collocations: ['a fancy restaurant', 'a fancy hotel', 'fancy clothes'],
    etymology: 'fantasy(空想)が短縮してできた語。「空想的な・凝った」→「しゃれた・高級な」。',
    relatedWords: ['fantasy', 'luxurious', 'plain'],
  },
  {
    id: 'fascinating',
    word: 'fascinating',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['非常に興味深い、魅力的な'],
    pronunciation: '/ˈfæsɪneɪtɪŋ/',
    exampleSentence: 'The documentary about deep sea creatures was absolutely fascinating.',
    exampleTranslationJa: '深海生物についてのドキュメンタリーは実に興味深かった。',
    collocations: ['a fascinating story', 'absolutely fascinating', 'find it fascinating'],
    etymology: 'ラテン語 fascinare(魔法をかける)から。魔法にかけられたように心を奪う、というイメージ。',
    relatedWords: ['fascinate', 'fascinated', 'intriguing'],
  },
  {
    id: 'fashionable',
    word: 'fashionable',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['流行の、おしゃれな'],
    pronunciation: '/ˈfæʃnəbl/',
    exampleSentence: 'This area is full of fashionable cafes and clothing stores.',
    exampleTranslationJa: 'この地域にはおしゃれなカフェや洋服店がたくさんある。',
    collocations: ['fashionable clothes', 'a fashionable area', 'become fashionable'],
    wordFormation: 'fashion(流行)+ -able。反対語は unfashionable や old-fashioned。',
    relatedWords: ['fashion', 'trendy', 'stylish'],
  },
  {
    id: 'fasten',
    word: 'fasten',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['しっかり留める、締める、固定する'],
    pronunciation: '/ˈfæsn/',
    exampleSentence: 'Please fasten your seatbelt before the plane takes off.',
    exampleTranslationJa: '飛行機が離陸する前にシートベルトをお締めください。',
    collocations: ['fasten your seatbelt', 'fasten a button', 'fasten securely'],
    wordFormation: 'fast には「速い」のほかに「しっかり固定した」という古い意味があり、それ + -en(動詞化)→固定する。t は発音しない。',
    relatedWords: ['unfasten', 'tie', 'attach'],
  },
  {
    id: 'fault',
    word: 'fault',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(過失の)責任', '欠点、欠陥'],
    pronunciation: '/fɔːlt/',
    exampleSentence: 'It was my fault that we missed the train.',
    exampleTranslationJa: '私たちが電車に乗り遅れたのは私のせいだった。',
    collocations: ["it's my fault", 'find fault with', 'through no fault of your own'],
    etymology: 'fail と同じくラテン語 fallere(しくじる・欺く)に由来する。',
    relatedWords: ['fail', 'failure', 'mistake'],
  },
  {
    id: 'favor',
    word: 'favor',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['親切な行為、頼み事', '好意、支持(in favor of で「〜に賛成して」)'],
    pronunciation: '/ˈfeɪvər/',
    exampleSentence: 'Could you do me a favor and water my plants this weekend?',
    exampleTranslationJa: 'お願いがあるんだけど、今週末うちの植物に水をやってくれない?',
    collocations: ['do me a favor', 'ask a favor', 'in favor of'],
    etymology: 'ラテン語 favere(好意を示す)に由来する。favorite(お気に入り)と同族。',
    relatedWords: ['favorite', 'favorable', 'kindness'],
  },
  {
    id: 'feature',
    word: 'feature',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['特徴、機能', '(顔の)造作', '(動詞)特集する、目玉として登場させる'],
    pronunciation: '/ˈfiːtʃər/',
    exampleSentence: 'The new phone has several features that older models lack.',
    exampleTranslationJa: 'その新しい電話には、旧モデルにはない機能がいくつかある。',
    collocations: ['a key feature', 'safety features', 'a special feature'],
    relatedWords: ['characteristic', 'function', 'aspect'],
  },
  {
    id: 'fee',
    word: 'fee',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['料金、手数料', '(専門職への)報酬'],
    pronunciation: '/fiː/',
    exampleSentence: 'The museum charges a small entrance fee for adults.',
    exampleTranslationJa: 'その博物館は大人から少額の入場料を取っている。',
    collocations: ['an entrance fee', 'school fees', 'pay a fee'],
    relatedWords: ['charge', 'fare', 'cost'],
  },
  {
    id: 'feed',
    word: 'feed',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['食べ物を与える、餌をやる', '(家族を)養う'],
    pronunciation: '/fiːd/',
    exampleSentence: "Don't forget to feed the cat before you leave.",
    exampleTranslationJa: '出かける前に猫に餌をやるのを忘れないでね。',
    collocations: ['feed the baby', 'feed the dog', 'feed a family'],
    wordFormation: 'food(食べ物)と同じゲルマン語の語根から。過去形・過去分詞は fed。',
    relatedWords: ['food', 'feedback', 'nutrition'],
  },
  {
    id: 'feedback',
    word: 'feedback',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['フィードバック、意見・感想'],
    pronunciation: '/ˈfiːdbæk/',
    exampleSentence: 'My manager gave me useful feedback on my presentation.',
    exampleTranslationJa: '上司は私のプレゼンについて有益なフィードバックをくれた。',
    collocations: ['give feedback', 'positive feedback', 'receive feedback on'],
    wordFormation: 'feed=与える + back=返す →結果を相手に返して次に生かすもの。',
    relatedWords: ['response', 'comment', 'evaluation'],
  },
  {
    id: 'fence',
    word: 'fence',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['フェンス、柵、塀'],
    pronunciation: '/fens/',
    exampleSentence: 'We built a wooden fence around the garden to keep dogs out.',
    exampleTranslationJa: '犬が入らないように、私たちは庭の周りに木の柵を作った。',
    collocations: ['build a fence', 'a wooden fence', 'climb over a fence'],
    etymology: 'defense(防御)の語頭が取れてできた語。「囲って守るもの」が原義。',
    relatedWords: ['defense', 'wall', 'gate'],
  },
  {
    id: 'fever',
    word: 'fever',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['熱、発熱', '熱狂'],
    pronunciation: '/ˈfiːvər/',
    exampleSentence: 'He stayed home from school because he had a high fever.',
    exampleTranslationJa: '彼は高熱があったので学校を休んで家にいた。',
    collocations: ['have a fever', 'a high fever', 'run a fever'],
    relatedWords: ['temperature', 'flu', 'illness'],
  },
  {
    id: 'figure',
    word: 'figure',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['数字、数値', '人物', '姿、体型'],
    pronunciation: '/ˈfɪɡjər/',
    exampleSentence: 'The latest sales figures show that business is improving.',
    exampleTranslationJa: '最新の売上数値は業績が上向いていることを示している。',
    collocations: ['sales figures', 'a public figure', 'official figures'],
    etymology: 'ラテン語 figura(形)に由来する。「形」→「姿・人物」→「数字の字形」と意味が広がった。',
    relatedWords: ['number', 'statistic', 'shape'],
  },
  {
    id: 'figure-out',
    word: 'figure out',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['理解する、解き明かす', '(方法・答えを)考え出す'],
    pronunciation: '/ˌfɪɡjər ˈaʊt/',
    exampleSentence: "I can't figure out how to set up this new printer.",
    exampleTranslationJa: 'この新しいプリンターの設定方法がどうしてもわからない。',
    collocations: ['figure out how to', 'figure out why', 'figure it out'],
    mnemonic: '答えの「figure(形・数字)」を out(外へ)引っ張り出す、と覚える。',
    relatedWords: ['work out', 'solve', 'understand'],
  },
  {
    id: 'finance',
    word: 'finance',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['財政、金融', '(finances で)資金、財源', '(動詞)資金を提供する'],
    pronunciation: '/ˈfaɪnæns/',
    exampleSentence: 'She studied finance in college and now works at a bank.',
    exampleTranslationJa: '彼女は大学で金融を学び、今は銀行で働いている。',
    collocations: ['personal finance', 'public finances', 'finance a project'],
    etymology: '古フランス語 finer(支払いを終える)から。fin-=終わり(finish と同根)。「支払いを済ませること」→財政。',
    relatedWords: ['financial', 'fund', 'budget'],
  },
  {
    id: 'financial',
    word: 'financial',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['財政の、金銭的な'],
    pronunciation: '/faɪˈnænʃl/',
    exampleSentence: 'The company is facing serious financial problems this year.',
    exampleTranslationJa: 'その会社は今年、深刻な財政問題に直面している。',
    collocations: ['financial problems', 'financial support', 'a financial crisis'],
    wordFormation: 'finance(財政)+ -ial(形容詞化)。',
    relatedWords: ['finance', 'economic', 'monetary'],
  },
  {
    id: 'find-out',
    word: 'find out',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['(調べたり聞いたりして)知る、突き止める'],
    pronunciation: '/ˌfaɪnd ˈaʊt/',
    exampleSentence: 'I need to find out what time the last train leaves.',
    exampleTranslationJa: '終電が何時に出るのか調べなければならない。',
    collocations: ['find out about', 'find out the truth', 'find out what happened'],
    relatedWords: ['discover', 'learn', 'figure out'],
  },
  {
    id: 'firm',
    word: 'firm',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['会社、事務所', '(形容詞)固い、しっかりした、断固とした'],
    pronunciation: '/fɜːrm/',
    exampleSentence: 'He works as a lawyer at a large law firm in Chicago.',
    exampleTranslationJa: '彼はシカゴの大手法律事務所で弁護士として働いている。',
    collocations: ['a law firm', 'a firm mattress', 'a firm decision'],
    etymology: 'ラテン語 firmus(堅固な)から。confirm(確認して固める)と同根。会社の意味はイタリア語 firma(署名)を経由して生まれた。',
    relatedWords: ['company', 'confirm', 'solid'],
  },
  {
    id: 'fix',
    word: 'fix',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['修理する', '固定する', '(日時などを)決める'],
    pronunciation: '/fɪks/',
    exampleSentence: 'My dad fixed the washing machine without calling a repair service.',
    exampleTranslationJa: '父は修理業者を呼ばずに洗濯機を直した。',
    collocations: ['fix a car', 'fix a problem', 'fix a date'],
    etymology: 'ラテン語 figere(固定する)の過去分詞 fixus から。「固定する」が原義で、「直して正常な状態に留める」→修理する。',
    relatedWords: ['repair', 'mend', 'solve'],
  },
  {
    id: 'flavor',
    word: 'flavor',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['風味、味'],
    pronunciation: '/ˈfleɪvər/',
    exampleSentence: 'This ice cream shop offers more than thirty flavors.',
    exampleTranslationJa: 'このアイスクリーム店は30種類以上のフレーバーを提供している。',
    collocations: ['a strong flavor', 'vanilla flavor', 'add flavor to'],
    relatedWords: ['taste', 'spice', 'ingredient'],
  },
  {
    id: 'flexible',
    word: 'flexible',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['柔軟な、融通のきく', '曲げやすい'],
    pronunciation: '/ˈfleksəbl/',
    exampleSentence: 'My working hours are flexible, so I can start early or late.',
    exampleTranslationJa: '私の勤務時間は柔軟なので、早く始めることも遅く始めることもできる。',
    collocations: ['flexible working hours', 'a flexible schedule', 'stay flexible'],
    wordFormation: 'flex=曲げる(ラテン語 flectere)+ -ible=〜できる →曲げられる→柔軟な。名詞形は flexibility。',
    relatedWords: ['flexibility', 'rigid', 'adaptable'],
  },
  {
    id: 'float',
    word: 'float',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['浮く、浮かぶ', '漂う'],
    pronunciation: '/floʊt/',
    exampleSentence: 'The children watched their paper boats float down the stream.',
    exampleTranslationJa: '子どもたちは紙の船が小川を流れていくのを見ていた。',
    collocations: ['float on water', 'float in the air'],
    wordFormation: 'flow(流れる)と同じゲルマン語の語根から。反対語は sink(沈む)。',
    relatedWords: ['flow', 'sink', 'drift'],
  },
  {
    id: 'flood',
    word: 'flood',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['洪水', '(動詞)氾濫する、(be flooded with で)殺到する'],
    pronunciation: '/flʌd/',
    exampleSentence: 'The heavy rain caused a flood that damaged hundreds of homes.',
    exampleTranslationJa: '大雨で洪水が起き、何百もの家屋が被害を受けた。',
    collocations: ['a flash flood', 'flood damage', 'be flooded with'],
    wordFormation: 'flow(流れる)と同じ語根。「あふれるほどの流れ」→洪水。発音は /flʌd/ で「フラッド」。',
    relatedWords: ['flow', 'overflow', 'disaster'],
  },
  {
    id: 'flow',
    word: 'flow',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['流れる', '(名詞)流れ'],
    pronunciation: '/floʊ/',
    exampleSentence: 'The river flows through the center of the city.',
    exampleTranslationJa: 'その川は市の中心部を流れている。',
    collocations: ['flow into', 'the flow of traffic', 'cash flow'],
    relatedWords: ['flood', 'float', 'stream'],
  },
  {
    id: 'focus',
    word: 'focus',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(focus on で)集中する、重点を置く', '(名詞)焦点、中心'],
    pronunciation: '/ˈfoʊkəs/',
    exampleSentence: 'I turned off my phone so I could focus on my homework.',
    exampleTranslationJa: '宿題に集中できるように携帯の電源を切った。',
    collocations: ['focus on', 'the main focus of', 'stay focused'],
    etymology: 'ラテン語 focus(炉・かまど)から。家の中心である炉→光や注意が集まる点→焦点。',
    relatedWords: ['concentrate', 'attention', 'focused'],
  },
  {
    id: 'fold',
    word: 'fold',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['折りたたむ', '(腕を)組む'],
    pronunciation: '/foʊld/',
    exampleSentence: 'She folded the letter carefully and put it in an envelope.',
    exampleTranslationJa: '彼女は手紙を丁寧に折りたたんで封筒に入れた。',
    collocations: ['fold the laundry', 'fold a piece of paper', 'fold your arms'],
    wordFormation: '反対語は unfold(広げる)。folder(フォルダー)は「書類を折り込んで挟むもの」。',
    relatedWords: ['unfold', 'folder', 'bend'],
  },
  {
    id: 'folk',
    word: 'folk',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['人々(folks で「みなさん」「家族」)', '(形容詞)民間の、民俗の'],
    pronunciation: '/foʊk/',
    exampleSentence: 'The band mixes traditional folk music with modern sounds.',
    exampleTranslationJa: 'そのバンドは伝統的なフォーク音楽と現代的なサウンドを融合させている。',
    collocations: ['folk music', 'folk tales', 'old folks'],
    wordFormation: '古英語 folc(人々)から。l は発音せず /foʊk/。folklore(民間伝承)にも含まれる。',
    relatedWords: ['people', 'folklore', 'traditional'],
  },
  {
    id: 'force',
    word: 'force',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['力、暴力', '(the police force などで)部隊、軍', '(動詞)強制する'],
    pronunciation: '/fɔːrs/',
    exampleSentence: 'The police had to use force to open the door.',
    exampleTranslationJa: '警察はドアを開けるために力ずくでやらざるを得なかった。',
    collocations: ['use force', 'the police force', 'force someone to do'],
    etymology: 'ラテン語 fortis(強い)から。effort や comfort にも同じ語根が含まれる。',
    relatedWords: ['strength', 'power', 'effort'],
  },
  {
    id: 'forecast',
    word: 'forecast',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['予報、予測', '(動詞)予測する'],
    pronunciation: '/ˈfɔːrkæst/',
    exampleSentence: 'The weather forecast says it will rain all weekend.',
    exampleTranslationJa: '天気予報によると週末はずっと雨らしい。',
    collocations: ['the weather forecast', 'an economic forecast', 'forecast growth'],
    wordFormation: 'fore-=前もって(before の fore)+ cast=投げる →先へ投げかける→予測する。',
    relatedWords: ['predict', 'prediction', 'outlook'],
  },
  {
    id: 'forgive',
    word: 'forgive',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['許す'],
    pronunciation: '/fərˈɡɪv/',
    exampleSentence: 'She finally forgave her brother for breaking her camera.',
    exampleTranslationJa: '彼女はカメラを壊した弟をついに許した。',
    collocations: ['forgive someone for', 'forgive and forget'],
    wordFormation: 'for-=完全に + give=与える。過去形は forgave、過去分詞は forgiven。名詞形は forgiveness。',
    relatedWords: ['forgiveness', 'excuse', 'apologize'],
  },
  {
    id: 'formal',
    word: 'formal',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['正式の、公式の', '(服装・言葉遣いが)フォーマルな、堅い'],
    pronunciation: '/ˈfɔːrml/',
    exampleSentence: 'You should wear formal clothes to the wedding ceremony.',
    exampleTranslationJa: '結婚式にはフォーマルな服を着ていくべきだ。',
    collocations: ['formal clothes', 'formal education', 'formal language'],
    wordFormation: 'form=形 + -al →型どおりの→正式の。反対語は informal(in-=否定)。',
    relatedWords: ['informal', 'official', 'casual'],
  },
  {
    id: 'former',
    word: 'former',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['以前の、元の', '(the former で)前者'],
    pronunciation: '/ˈfɔːrmər/',
    exampleSentence: 'The former president still gives speeches around the country.',
    exampleTranslationJa: '前大統領は今でも国中で講演を行っている。',
    collocations: ['the former president', 'a former colleague', 'the former and the latter'],
    relatedWords: ['latter', 'previous', 'current'],
  },
  {
    id: 'fortune',
    word: 'fortune',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['財産、大金', '運、幸運'],
    pronunciation: '/ˈfɔːrtʃən/',
    exampleSentence: 'He made a fortune by investing in technology companies.',
    exampleTranslationJa: '彼はテクノロジー企業への投資でひと財産を築いた。',
    collocations: ['make a fortune', 'cost a fortune', 'good fortune'],
    etymology: 'ラテン語 fortuna(運命・運命の女神)から。「運」→「運がもたらす富」と意味が広がった。',
    relatedWords: ['fortunate', 'unfortunately', 'wealth'],
  },
  {
    id: 'found',
    word: 'found',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['設立する、創設する(活用は found - founded - founded)'],
    pronunciation: '/faʊnd/',
    exampleSentence: 'The university was founded more than one hundred years ago.',
    exampleTranslationJa: 'その大学は100年以上前に創設された。',
    collocations: ['found a company', 'be founded in', 'newly founded'],
    wordFormation: 'ラテン語 fundus(底・基礎)から。foundation(土台)と同族。find の過去形 found とは別の単語なので注意。',
    relatedWords: ['foundation', 'founder', 'establish'],
  },
  {
    id: 'foundation',
    word: 'foundation',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['土台、基礎', '財団', '設立'],
    pronunciation: '/faʊnˈdeɪʃn/',
    exampleSentence: 'Trust is the foundation of any good relationship.',
    exampleTranslationJa: '信頼はあらゆる良い人間関係の土台である。',
    collocations: ['lay the foundation for', 'a solid foundation', 'a charitable foundation'],
    wordFormation: 'found(設立する)+ -ation。fund=底・基礎(ラテン語 fundus)が語根で、fundamental と同族。',
    relatedWords: ['found', 'founder', 'basis'],
  },
  {
    id: 'frame',
    word: 'frame',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['枠、フレーム、額縁', '骨組み'],
    pronunciation: '/freɪm/',
    exampleSentence: 'I bought a wooden frame for our family photo.',
    exampleTranslationJa: '家族写真のために木製の額縁を買った。',
    collocations: ['a picture frame', 'a window frame', 'a time frame'],
    relatedWords: ['framework', 'border', 'structure'],
  },
  {
    id: 'freeze',
    word: 'freeze',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['凍る、凍らせる', '(動きが)固まる、止まる'],
    pronunciation: '/friːz/',
    exampleSentence: 'The lake freezes completely during the coldest winter months.',
    exampleTranslationJa: 'その湖は冬の最も寒い時期には完全に凍る。',
    collocations: ['freezing cold', 'frozen food', 'freeze to death'],
    wordFormation: '過去形は froze、過去分詞は frozen。frozen food(冷凍食品)、freezer(冷凍庫)。',
    relatedWords: ['frozen', 'freezer', 'melt'],
  },
  {
    id: 'frequent',
    word: 'frequent',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['頻繁な、たびたびの'],
    pronunciation: '/ˈfriːkwənt/',
    exampleSentence: 'She is a frequent visitor to the art museum.',
    exampleTranslationJa: '彼女はその美術館の常連客だ。',
    collocations: ['a frequent visitor', 'frequent flights', 'less frequent'],
    wordFormation: '副詞は frequently、名詞は frequency(頻度・周波数)。',
    relatedWords: ['frequently', 'frequency', 'regular'],
  },
  {
    id: 'frequently',
    word: 'frequently',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['頻繁に、よく'],
    pronunciation: '/ˈfriːkwəntli/',
    exampleSentence: 'This website is frequently updated with new information.',
    exampleTranslationJa: 'このウェブサイトは新しい情報で頻繁に更新されている。',
    collocations: ['frequently asked questions', 'occur frequently', 'frequently used'],
    wordFormation: 'frequent(頻繁な)+ -ly。often よりやや硬い語。',
    relatedWords: ['frequent', 'often', 'rarely'],
  },
  {
    id: 'frighten',
    word: 'frighten',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['怖がらせる、おびえさせる'],
    pronunciation: '/ˈfraɪtn/',
    exampleSentence: 'The sudden noise frightened the birds away.',
    exampleTranslationJa: '突然の物音に驚いて鳥たちは飛び去った。',
    collocations: ['frighten someone away', 'be easily frightened'],
    wordFormation: 'fright(恐怖)+ -en(〜させる。strengthen や shorten と同じ動詞化の接尾辞)。',
    relatedWords: ['frightened', 'frightening', 'scare'],
  },
  {
    id: 'frightened',
    word: 'frightened',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['おびえた、怖がっている'],
    pronunciation: '/ˈfraɪtnd/',
    exampleSentence: 'The little boy was frightened of the dark.',
    exampleTranslationJa: 'その小さな男の子は暗闇を怖がっていた。',
    collocations: ['be frightened of', 'a frightened child', 'too frightened to move'],
    wordFormation: '-ed 形は「(人が)恐怖を感じている」側を表す。感じさせる側は frightening。',
    relatedWords: ['scared', 'afraid', 'frightening'],
  },
  {
    id: 'frightening',
    word: 'frightening',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['恐ろしい、ぞっとさせる'],
    pronunciation: '/ˈfraɪtnɪŋ/',
    exampleSentence: 'Getting lost in a foreign city was a frightening experience.',
    exampleTranslationJa: '外国の街で道に迷ったのは恐ろしい経験だった。',
    collocations: ['a frightening experience', 'a frightening thought'],
    wordFormation: '-ing 形は「(物事が)恐怖を感じさせる」側を表す。感じる側は frightened。',
    relatedWords: ['scary', 'terrifying', 'frightened'],
  },
  {
    id: 'fuel',
    word: 'fuel',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['燃料', '(動詞)あおる、助長する'],
    pronunciation: '/ˈfjuːəl/',
    exampleSentence: 'The price of fuel has risen sharply this year.',
    exampleTranslationJa: '今年は燃料の価格が急激に上昇した。',
    collocations: ['fossil fuels', 'fuel prices', 'add fuel to the fire'],
    relatedWords: ['gasoline', 'energy', 'coal'],
  },
  {
    id: 'fulfill',
    word: 'fulfill',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(夢・約束を)果たす、実現する', '(条件を)満たす'],
    pronunciation: '/fʊlˈfɪl/',
    exampleSentence: 'She finally fulfilled her dream of opening her own bakery.',
    exampleTranslationJa: '彼女はついに自分のパン屋を開くという夢を実現した。',
    collocations: ['fulfill a dream', 'fulfill a promise', 'fulfill the requirements'],
    wordFormation: 'full=いっぱいの + fill=満たす →完全に満たす→果たす。名詞形は fulfillment。',
    relatedWords: ['fulfillment', 'achieve', 'satisfy'],
  },
  {
    id: 'function',
    word: 'function',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['機能、働き', '(動詞)機能する'],
    pronunciation: '/ˈfʌŋkʃn/',
    exampleSentence: 'The main function of the heart is to pump blood around the body.',
    exampleTranslationJa: '心臓の主な機能は血液を全身に送り出すことだ。',
    collocations: ['perform a function', 'the function of', 'function properly'],
    relatedWords: ['functional', 'purpose', 'role'],
  },
  {
    id: 'fund',
    word: 'fund',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['資金、基金', '(動詞)資金を出す'],
    pronunciation: '/fʌnd/',
    exampleSentence: 'The school raised funds to build a new library.',
    exampleTranslationJa: 'その学校は新しい図書館を建てるための資金を集めた。',
    collocations: ['raise funds', 'a pension fund', 'lack of funds'],
    wordFormation: 'ラテン語 fundus(底・基礎・土地)から。foundation や fundamental と同族。「財産の基盤」→資金。',
    relatedWords: ['funding', 'finance', 'budget'],
  },
  {
    id: 'fundamental',
    word: 'fundamental',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['基本的な、根本的な'],
    pronunciation: '/ˌfʌndəˈmentl/',
    exampleSentence: 'Freedom of speech is a fundamental right in a democracy.',
    exampleTranslationJa: '言論の自由は民主主義における基本的な権利だ。',
    collocations: ['a fundamental change', 'fundamental rights', 'fundamental to'],
    wordFormation: 'fundament(基礎)+ -al。fund=底・基礎(ラテン語 fundus)が語根で、foundation と同族。',
    relatedWords: ['basic', 'essential', 'foundation'],
  },
  {
    id: 'funeral',
    word: 'funeral',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['葬式'],
    pronunciation: '/ˈfjuːnərəl/',
    exampleSentence: 'Hundreds of people attended the funeral of the famous writer.',
    exampleTranslationJa: '何百人もの人々がその有名な作家の葬儀に参列した。',
    collocations: ['attend a funeral', 'a funeral service'],
    relatedWords: ['ceremony', 'grave', 'grief'],
  },
  {
    id: 'furthermore',
    word: 'furthermore',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['さらに、その上(書き言葉で情報を追加する)'],
    pronunciation: '/ˌfɜːrðərˈmɔːr/',
    exampleSentence: 'The apartment is close to the station. Furthermore, the rent is quite reasonable.',
    exampleTranslationJa: 'そのアパートは駅に近い。さらに、家賃もかなり手頃だ。',
    wordFormation: 'further(さらに)+ more。文頭で使い、コンマを続けることが多い。',
    relatedWords: ['moreover', 'in addition', 'besides'],
  },
  {
    id: 'gain',
    word: 'gain',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(努力して)得る、獲得する', '増す', '(名詞)増加、利益'],
    pronunciation: '/ɡeɪn/',
    exampleSentence: 'You will gain valuable experience by working abroad.',
    exampleTranslationJa: '海外で働くことで貴重な経験を得られるだろう。',
    collocations: ['gain experience', 'gain weight', 'gain confidence'],
    relatedWords: ['obtain', 'earn', 'loss'],
  },
  {
    id: 'gap',
    word: 'gap',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['隙間', '格差、隔たり', '空白(期間)'],
    pronunciation: '/ɡæp/',
    exampleSentence: 'There is a growing gap between the rich and the poor.',
    exampleTranslationJa: '富裕層と貧困層の格差が拡大している。',
    collocations: ['the gap between', 'fill a gap', 'a generation gap'],
    relatedWords: ['space', 'difference', 'distance'],
  },
  {
    id: 'gather',
    word: 'gather',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['集める、集まる', '(情報を)収集する'],
    pronunciation: '/ˈɡæðər/',
    exampleSentence: 'A large crowd gathered in front of the station to watch the parade.',
    exampleTranslationJa: 'パレードを見ようと大勢の人が駅前に集まった。',
    collocations: ['gather information', 'a crowd gathers', 'gather around'],
    etymology: 'together(一緒に)と同じゲルマン語の語根から。「一つに集める」が原義。',
    relatedWords: ['collect', 'assemble', 'together'],
  },
  {
    id: 'gene',
    word: 'gene',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['遺伝子'],
    pronunciation: '/dʒiːn/',
    exampleSentence: 'Scientists have identified a gene that is linked to the disease.',
    exampleTranslationJa: '科学者たちはその病気に関連する遺伝子を特定した。',
    collocations: ['carry a gene', 'a gene for'],
    wordFormation: 'ギリシャ語 genos(生まれ・種族)から。gen=生む は generate や generation と共通の語根。',
    relatedWords: ['genetic', 'DNA', 'generation'],
  },
  {
    id: 'generate',
    word: 'generate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['生み出す、発生させる', '(電気を)起こす'],
    pronunciation: '/ˈdʒenəreɪt/',
    exampleSentence: 'This wind farm generates enough electricity for fifty thousand homes.',
    exampleTranslationJa: 'この風力発電所は5万世帯分の電力を生み出している。',
    collocations: ['generate electricity', 'generate income', 'generate interest'],
    wordFormation: 'gen=生む(ラテン語 generare)+ -ate。gene、generation、generous と同じ語根。',
    relatedWords: ['generation', 'generator', 'produce'],
  },
  {
    id: 'generation',
    word: 'generation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['世代', '(電気などの)発生'],
    pronunciation: '/ˌdʒenəˈreɪʃn/',
    exampleSentence: "My grandmother's generation grew up without the internet.",
    exampleTranslationJa: '祖母の世代はインターネットなしで育った。',
    collocations: ['the younger generation', 'from generation to generation', 'a generation gap'],
    wordFormation: 'generate(生み出す)+ -ion。「同じ時期に生まれた人々」→世代。',
    relatedWords: ['generate', 'gene', 'ancestor'],
  },
  {
    id: 'generous',
    word: 'generous',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['気前のよい、寛大な', '(量が)たっぷりの'],
    pronunciation: '/ˈdʒenərəs/',
    exampleSentence: "It was generous of him to pay for everyone's dinner.",
    exampleTranslationJa: '全員の夕食代を払うとは彼は気前がよかった。',
    collocations: ['generous with', 'a generous offer', 'generous support'],
    etymology: 'ラテン語 generosus(高貴な生まれの)から。gen=生まれ。「良家の生まれ」→「気前がよい」と意味が変化した。',
    relatedWords: ['generosity', 'kind', 'selfish'],
  },
  {
    id: 'gentle',
    word: 'gentle',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['優しい、穏やかな'],
    pronunciation: '/ˈdʒentl/',
    exampleSentence: 'The nurse was very gentle with the frightened child.',
    exampleTranslationJa: 'その看護師はおびえた子どもにとても優しく接した。',
    collocations: ['a gentle voice', 'a gentle breeze', 'be gentle with'],
    etymology: 'ラテン語 gentilis(同じ一族の→良家の)から。gentleman の gentle も同じで、「上品な→優しい」と意味が変化した。',
    relatedWords: ['gentleman', 'gently', 'mild'],
  },
  {
    id: 'genuine',
    word: 'genuine',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['本物の', '(感情が)偽りのない、心からの'],
    pronunciation: '/ˈdʒenjuɪn/',
    exampleSentence: 'She showed a genuine interest in learning about Japanese culture.',
    exampleTranslationJa: '彼女は日本文化を学ぶことに心からの関心を示した。',
    collocations: ['a genuine interest', 'genuine leather', 'a genuine smile'],
    relatedWords: ['real', 'authentic', 'fake'],
  },
  {
    id: 'gesture',
    word: 'gesture',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['身ぶり、ジェスチャー', '(気持ちを示す)行為、意思表示'],
    pronunciation: '/ˈdʒestʃər/',
    exampleSentence: 'He made a gesture with his hand to show us where to sit.',
    exampleTranslationJa: '彼は手ぶりでどこに座ればよいかを示した。',
    collocations: ['make a gesture', 'a friendly gesture', 'a gesture of goodwill'],
    relatedWords: ['body language', 'signal', 'sign'],
  },
  {
    id: 'get-over',
    word: 'get over',
    level: 'B2',
    partOfSpeech: '句動詞',
    meaningsJa: ['(病気・ショックから)立ち直る、乗り越える'],
    pronunciation: '/ˌɡet ˈoʊvər/',
    exampleSentence: 'It took her months to get over the shock of losing her job.',
    exampleTranslationJa: '彼女が失業のショックから立ち直るには何か月もかかった。',
    collocations: ['get over an illness', 'get over the shock', 'get over a breakup'],
    mnemonic: '障害物を over(越えて)向こう側へ行くイメージ、と覚える。',
    relatedWords: ['recover', 'overcome', 'deal with'],
  },
  {
    id: 'get-rid-of',
    word: 'get rid of',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['取り除く、処分する、追い払う'],
    pronunciation: '/ˌɡet ˈrɪd əv/',
    exampleSentence: 'We should get rid of these old magazines to make more space.',
    exampleTranslationJa: 'スペースを空けるために、この古い雑誌を処分したほうがいい。',
    collocations: ['get rid of old clothes', 'get rid of a bad habit'],
    relatedWords: ['remove', 'throw away', 'eliminate'],
  },
  {
    id: 'give-up',
    word: 'give up',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['あきらめる', '(習慣を)やめる'],
    pronunciation: '/ˌɡɪv ˈʌp/',
    exampleSentence: 'He decided to give up smoking when his first child was born.',
    exampleTranslationJa: '彼は最初の子どもが生まれたときに喫煙をやめることにした。',
    collocations: ['give up smoking', 'give up hope', 'never give up'],
    relatedWords: ['quit', 'stop', 'abandon'],
  },
  {
    id: 'global',
    word: 'global',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['世界的な、地球規模の'],
    pronunciation: '/ˈɡloʊbl/',
    exampleSentence: 'Global warming is one of the biggest problems facing our planet.',
    exampleTranslationJa: '地球温暖化は私たちの惑星が直面する最大の問題の一つだ。',
    collocations: ['global warming', 'the global economy', 'on a global scale'],
    wordFormation: 'globe=地球・球 + -al。',
    relatedWords: ['globe', 'worldwide', 'international'],
  },
  {
    id: 'govern',
    word: 'govern',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['統治する', '(規則が)左右する、支配する'],
    pronunciation: '/ˈɡʌvərn/',
    exampleSentence: 'The country was governed by the same party for thirty years.',
    exampleTranslationJa: 'その国は30年間同じ政党によって統治された。',
    collocations: ['govern a country', 'the rules governing'],
    etymology: 'ギリシャ語 kybernan(船の舵を取る)がラテン語 gubernare を経て英語に入った。「国という船の舵を取る」イメージ。',
    relatedWords: ['government', 'governor', 'rule'],
  },
  {
    id: 'government',
    word: 'government',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['政府', '政治、統治'],
    pronunciation: '/ˈɡʌvərnmənt/',
    exampleSentence: 'The government announced a new plan to reduce taxes.',
    exampleTranslationJa: '政府は減税のための新しい計画を発表した。',
    collocations: ['the federal government', 'local government', 'form a government'],
    wordFormation: 'govern(統治する)+ -ment(名詞化)。',
    relatedWords: ['govern', 'governor', 'politics'],
  },
  {
    id: 'gradually',
    word: 'gradually',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['徐々に、だんだんと'],
    pronunciation: '/ˈɡrædʒuəli/',
    exampleSentence: 'Her English gradually improved after she moved to Seattle.',
    exampleTranslationJa: 'シアトルに引っ越してから、彼女の英語は徐々に上達した。',
    collocations: ['gradually increase', 'gradually improve', 'change gradually'],
    wordFormation: 'gradual + -ly。ラテン語 gradus(歩み・段階)が語根で、grade(段階)や graduate(卒業する=段階を進む)と同族。',
    relatedWords: ['gradual', 'slowly', 'suddenly'],
  },
  {
    id: 'grant',
    word: 'grant',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(正式に)与える、認める', '(名詞)助成金、補助金', '(take ~ for granted で)当然のことと思う'],
    pronunciation: '/ɡrænt/',
    exampleSentence: 'The city granted the company permission to build a new factory.',
    exampleTranslationJa: '市はその会社に新工場建設の許可を与えた。',
    collocations: ['grant permission', 'a research grant', 'take it for granted'],
    relatedWords: ['permit', 'scholarship', 'funding'],
  },
  {
    id: 'grateful',
    word: 'grateful',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['感謝している'],
    pronunciation: '/ˈɡreɪtfl/',
    exampleSentence: 'I am deeply grateful for all the support you have given me.',
    exampleTranslationJa: 'いただいたすべてのご支援に深く感謝しています。',
    collocations: ['be grateful for', 'be grateful to someone', 'deeply grateful'],
    wordFormation: 'ラテン語 gratus(感謝している・喜ばしい)+ -ful。gratitude(感謝)や congratulate(祝う)と同族。',
    relatedWords: ['gratitude', 'thankful', 'appreciate'],
  },
  {
    id: 'growth',
    word: 'growth',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['成長', '増加、発展'],
    pronunciation: '/ɡroʊθ/',
    exampleSentence: 'The country has enjoyed rapid economic growth over the last decade.',
    exampleTranslationJa: 'その国はこの10年間、急速な経済成長を遂げてきた。',
    collocations: ['economic growth', 'population growth', 'a growth rate'],
    wordFormation: 'grow + -th(名詞化。warm → warmth、true → truth と同じ接尾辞)。',
    relatedWords: ['grow', 'increase', 'development'],
  },
  {
    id: 'guarantee',
    word: 'guarantee',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['保証する', '(名詞)保証'],
    pronunciation: '/ˌɡærənˈtiː/',
    exampleSentence: 'We guarantee that your order will arrive within three days.',
    exampleTranslationJa: 'ご注文の品は3日以内に届くことを保証します。',
    collocations: ['guarantee quality', 'a money-back guarantee', 'there is no guarantee that'],
    relatedWords: ['promise', 'warranty', 'assure'],
  },
  {
    id: 'guilty',
    word: 'guilty',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['罪悪感のある、うしろめたい', '有罪の'],
    pronunciation: '/ˈɡɪlti/',
    exampleSentence: "I felt guilty about forgetting my friend's birthday.",
    exampleTranslationJa: '友人の誕生日を忘れてしまい、申し訳ない気持ちになった。',
    collocations: ['feel guilty about', 'be found guilty of', 'a guilty conscience'],
    wordFormation: 'guilt(罪・罪悪感)+ -y。反対語は innocent(無罪の)。',
    relatedWords: ['guilt', 'innocent', 'ashamed'],
  },
  {
    id: 'handle',
    word: 'handle',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['対処する、処理する', '扱う', '(名詞)取っ手'],
    pronunciation: '/ˈhændl/',
    exampleSentence: 'She handled the difficult customer calmly and politely.',
    exampleTranslationJa: '彼女は気難しい客に冷静かつ丁寧に対応した。',
    collocations: ['handle a problem', 'handle pressure', 'a door handle'],
    wordFormation: 'hand(手)+ -le →手で扱う。',
    relatedWords: ['deal with', 'manage', 'treat'],
  },
  {
    id: 'harm',
    word: 'harm',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['害、危害', '(動詞)害を与える'],
    pronunciation: '/hɑːrm/',
    exampleSentence: "A little rain won't do any harm to the garden.",
    exampleTranslationJa: '少しの雨なら庭に害はないだろう。',
    collocations: ['do harm to', 'do more harm than good', 'no harm done'],
    relatedWords: ['harmful', 'damage', 'hurt'],
  },
  {
    id: 'harmful',
    word: 'harmful',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['有害な'],
    pronunciation: '/ˈhɑːrmfl/',
    exampleSentence: 'Smoking is harmful to your health in many ways.',
    exampleTranslationJa: '喫煙はさまざまな面で健康に有害だ。',
    collocations: ['harmful effects', 'harmful to your health', 'harmful chemicals'],
    wordFormation: 'harm(害)+ -ful(〜に満ちた)。反対語は harmless(-less=〜がない)。',
    relatedWords: ['harm', 'harmless', 'damaging'],
  },
  {
    id: 'harvest',
    word: 'harvest',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['収穫、収穫期', '(動詞)収穫する'],
    pronunciation: '/ˈhɑːrvɪst/',
    exampleSentence: 'Farmers were busy with the rice harvest all through October.',
    exampleTranslationJa: '農家の人々は10月の間ずっと稲の収穫で忙しかった。',
    collocations: ['a good harvest', 'the harvest season', 'harvest crops'],
    etymology: '古英語で「秋」を意味した hærfest が、秋に行う収穫そのものを指すようになった。',
    relatedWords: ['crop', 'agriculture', 'farming'],
  },
  {
    id: 'hesitate',
    word: 'hesitate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['ためらう、躊躇する'],
    pronunciation: '/ˈhezɪteɪt/',
    exampleSentence: 'If you have any questions, please do not hesitate to contact us.',
    exampleTranslationJa: 'ご質問がありましたら、遠慮なくお問い合わせください。',
    collocations: ['hesitate to do', 'hesitate for a moment', "don't hesitate to ask"],
    wordFormation: '名詞形は hesitation(ためらい)。without hesitation(ためらわずに)。',
    relatedWords: ['hesitation', 'pause', 'doubt'],
  },
  {
    id: 'hide',
    word: 'hide',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['隠す、隠れる'],
    pronunciation: '/haɪd/',
    exampleSentence: 'The children hid behind the sofa during the game.',
    exampleTranslationJa: '子どもたちはゲームの間ソファの後ろに隠れた。',
    collocations: ['hide the truth', 'hide behind', 'hide your feelings'],
    wordFormation: '過去形は hid、過去分詞は hidden。hidden は「隠れた・秘密の」という形容詞としてもよく使う。',
    relatedWords: ['hidden', 'conceal', 'reveal'],
  },
  {
    id: 'highlight',
    word: 'highlight',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['強調する、浮き彫りにする', '(名詞)最も重要な部分、見どころ'],
    pronunciation: '/ˈhaɪlaɪt/',
    exampleSentence: 'The report highlights the need for better public transportation.',
    exampleTranslationJa: 'その報告書は公共交通機関の改善の必要性を浮き彫りにしている。',
    collocations: ['highlight the importance of', 'the highlight of the trip'],
    wordFormation: 'high=強い + light=光 →強い光を当てて目立たせる。',
    relatedWords: ['emphasize', 'stress', 'feature'],
  },
  {
    id: 'highly',
    word: 'highly',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['非常に、大いに', '(think highly of で)高く評価する'],
    pronunciation: '/ˈhaɪli/',
    exampleSentence: 'This restaurant is highly recommended by local food critics.',
    exampleTranslationJa: 'このレストランは地元の食評論家たちに強く勧められている。',
    collocations: ['highly recommended', 'highly successful', 'think highly of'],
    wordFormation: 'high + -ly。「高い程度で」→非常に。highly skilled(高度な技術を持つ)のように形容詞を強める。',
    relatedWords: ['extremely', 'greatly', 'high'],
  },
  {
    id: 'hire',
    word: 'hire',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['雇う', '(主に英)賃借りする'],
    pronunciation: '/ˈhaɪər/',
    exampleSentence: 'The company plans to hire twenty new engineers this year.',
    exampleTranslationJa: 'その会社は今年、20人の新しいエンジニアを雇う予定だ。',
    collocations: ['hire new staff', 'hire a lawyer'],
    relatedWords: ['employ', 'recruit', 'fire'],
  },
  {
    id: 'honor',
    word: 'honor',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['名誉、光栄', '敬意', '(動詞)称える'],
    pronunciation: '/ˈɑːnər/',
    exampleSentence: 'It is a great honor to receive this award tonight.',
    exampleTranslationJa: '今夜この賞をいただけることは大変光栄です。',
    collocations: ['in honor of', 'a great honor', 'it is an honor to'],
    wordFormation: '語頭の h は発音しない /ˈɑːnər/。イギリス英語のつづりは honour。形容詞は honorable(立派な)。',
    relatedWords: ['honorable', 'respect', 'pride'],
  },
  {
    id: 'horror',
    word: 'horror',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['恐怖', 'ホラー(作品)'],
    pronunciation: '/ˈhɔːrər/',
    exampleSentence: 'She watched in horror as the car slid off the road.',
    exampleTranslationJa: '彼女は車が道路から滑り落ちるのを恐怖の中で見つめた。',
    collocations: ['a horror movie', 'in horror', 'to my horror'],
    etymology: 'ラテン語 horrere(毛が逆立つ)から。「身の毛もよだつ」恐怖を表す。',
    relatedWords: ['horrible', 'terror', 'fear'],
  },
  {
    id: 'household',
    word: 'household',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['世帯、家庭', '(形容詞)家庭の'],
    pronunciation: '/ˈhaʊshoʊld/',
    exampleSentence: 'Most households in this neighborhood own at least one car.',
    exampleTranslationJa: 'この地域のほとんどの世帯は少なくとも1台の車を所有している。',
    collocations: ['a single-person household', 'household chores', 'a household name'],
    wordFormation: 'house=家 + hold=保つ →一つの家を維持する人々の集まり→世帯。',
    relatedWords: ['family', 'home', 'domestic'],
  },
  {
    id: 'however',
    word: 'however',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['しかしながら', '(however + 形容詞/副詞で)どんなに〜でも'],
    pronunciation: '/haʊˈevər/',
    exampleSentence: 'The hotel was quite expensive. However, the service was worth every dollar.',
    exampleTranslationJa: 'そのホテルはかなり高かった。しかし、サービスは払った金額に見合う価値があった。',
    wordFormation: 'how + ever。文と文をつなぐときは However, のようにコンマを添える。but より硬い語。',
    relatedWords: ['but', 'although', 'nevertheless'],
  },
  {
    id: 'huge',
    word: 'huge',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['巨大な、莫大な'],
    pronunciation: '/hjuːdʒ/',
    exampleSentence: 'The concert was a huge success, and every ticket was sold.',
    exampleTranslationJa: 'コンサートは大成功で、チケットは完売した。',
    collocations: ['a huge amount of', 'a huge success', 'a huge difference'],
    relatedWords: ['enormous', 'massive', 'tiny'],
  },
  {
    id: 'humor',
    word: 'humor',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ユーモア、おかしさ'],
    pronunciation: '/ˈhjuːmər/',
    exampleSentence: 'A good sense of humor helps in stressful situations.',
    exampleTranslationJa: '優れたユーモアのセンスはストレスの多い状況で役に立つ。',
    collocations: ['a sense of humor', 'dark humor'],
    etymology: 'ラテン語 humor(体液)から。かつては体液のバランスが気質や気分を決めると考えられ、「気分」→「おかしさ」へと意味が変化した。',
    relatedWords: ['humorous', 'funny', 'joke'],
  },
  {
    id: 'hunt',
    word: 'hunt',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['狩る、狩りをする', '(hunt for で)探し回る'],
    pronunciation: '/hʌnt/',
    exampleSentence: 'After graduation, she spent three months hunting for a job.',
    exampleTranslationJa: '卒業後、彼女は3か月かけて仕事を探した。',
    collocations: ['hunt for', 'job hunting', 'hunt deer'],
    relatedWords: ['hunter', 'search', 'chase'],
  },
  {
    id: 'hurricane',
    word: 'hurricane',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ハリケーン'],
    pronunciation: '/ˈhɜːrɪkeɪn/',
    exampleSentence: 'The hurricane destroyed hundreds of homes along the coast.',
    exampleTranslationJa: 'そのハリケーンは沿岸の何百もの家屋を破壊した。',
    collocations: ['a powerful hurricane', 'hurricane season'],
    etymology: 'カリブ海の先住民タイノ族の嵐の神フラカン(Huracán)に由来し、スペイン語 huracán を経て英語に入った。',
    relatedWords: ['storm', 'typhoon', 'tornado'],
  },
  {
    id: 'identify',
    word: 'identify',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['特定する、識別する', '(identify with で)共感する'],
    pronunciation: '/aɪˈdentɪfaɪ/',
    exampleSentence: 'The police were able to identify the thief from the security video.',
    exampleTranslationJa: '警察は防犯カメラの映像から泥棒を特定することができた。',
    collocations: ['identify the cause', 'identify a problem', 'identify with a character'],
    wordFormation: 'ident=同じ(ラテン語 idem)+ -ify=〜にする →同一人物・同一物だと確認する。',
    relatedWords: ['identity', 'identification', 'recognize'],
  },
  {
    id: 'identity',
    word: 'identity',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['身元、正体', 'アイデンティティ、独自性'],
    pronunciation: '/aɪˈdentəti/',
    exampleSentence: 'Living abroad made him think deeply about his own identity.',
    exampleTranslationJa: '海外での生活は、彼に自分自身のアイデンティティについて深く考えさせた。',
    collocations: ['a sense of identity', 'identity theft', 'national identity'],
    wordFormation: 'ident=同じ(ラテン語 idem)+ -ity。「他と区別され、一貫して同じであること」が原義。',
    relatedWords: ['identify', 'identification', 'personality'],
  },
]
