import type { VocabularyEntry } from '../types'

export const batch04: VocabularyEntry[] = [
  {
    id: 'ignore',
    word: 'ignore',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['無視する', '気に留めない'],
    pronunciation: '/ɪɡˈnɔːr/',
    exampleSentence: 'She decided to ignore the rude comment and keep walking.',
    exampleTranslationJa: '彼女は失礼なコメントを無視して歩き続けることにした。',
    collocations: ['ignore advice', 'ignore a warning', 'completely ignore'],
    etymology: 'ラテン語 ignorare「知らない」(in-=否定 + 「知る」を表す語根)に由来。',
    relatedWords: ['ignorance', 'ignorant', 'overlook'],
  },
  {
    id: 'illegal',
    word: 'illegal',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['違法の', '不法の'],
    pronunciation: '/ɪˈliːɡəl/',
    exampleSentence: 'It is illegal to park your car on this street at night.',
    exampleTranslationJa: '夜間にこの通りに駐車するのは違法だ。',
    collocations: ['illegal parking', 'illegal drugs', 'strictly illegal'],
    wordFormation: 'il-(in-の変形)=否定 + legal=合法の。lの前で in- は il- になる。',
    relatedWords: ['legal', 'illegally', 'law'],
  },
  {
    id: 'illustrate',
    word: 'illustrate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(例で)説明する、示す', '挿絵を入れる'],
    pronunciation: '/ˈɪləstreɪt/',
    exampleSentence: 'The teacher used a simple diagram to illustrate her point.',
    exampleTranslationJa: '先生は簡単な図を使って自分の言いたいことを説明した。',
    collocations: ['illustrate a point', 'clearly illustrate', 'illustrate with examples'],
    etymology: 'ラテン語 illustrare「照らす、明らかにする」(in-=上に + lustrare=照らす)に由来。',
    relatedWords: ['illustration', 'demonstrate', 'example'],
  },
  {
    id: 'image',
    word: 'image',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['画像、映像', '印象、イメージ', '(心に浮かぶ)像'],
    pronunciation: '/ˈɪmɪdʒ/',
    exampleSentence: 'The company wants to improve its public image.',
    exampleTranslationJa: 'その会社は世間でのイメージを良くしたいと考えている。',
    collocations: ['public image', 'brand image', 'create an image'],
    etymology: 'ラテン語 imago「像、似姿」に由来。imagine と同語源。',
    relatedWords: ['imagine', 'imagination', 'picture'],
  },
  {
    id: 'imagination',
    word: 'imagination',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['想像力', '想像'],
    pronunciation: '/ɪˌmædʒəˈneɪʃən/',
    exampleSentence: 'Children often have a rich imagination and invent their own stories.',
    exampleTranslationJa: '子どもは豊かな想像力を持ち、自分だけの物語を作り出すことが多い。',
    collocations: ['use your imagination', 'rich imagination', 'capture the imagination'],
    wordFormation: 'imagine=想像する + -ation(名詞語尾)。',
    relatedWords: ['imagine', 'imaginative', 'creative'],
  },
  {
    id: 'immediate',
    word: 'immediate',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['即座の', 'すぐ近くの、直接の'],
    pronunciation: '/ɪˈmiːdiət/',
    exampleSentence: 'The medicine had an immediate effect on my headache.',
    exampleTranslationJa: 'その薬は私の頭痛にすぐに効果があった。',
    collocations: ['immediate effect', 'immediate response', 'immediate family'],
    wordFormation: 'im-(in-)=否定 + mediate(medius=中間)→「間に何も挟まない」→即座の。',
    relatedWords: ['immediately', 'instant', 'urgent'],
  },
  {
    id: 'immediately',
    word: 'immediately',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['ただちに、すぐに'],
    pronunciation: '/ɪˈmiːdiətli/',
    exampleSentence: 'Please call me immediately if anything changes.',
    exampleTranslationJa: '何か変化があったら、すぐに私に電話してください。',
    collocations: ['immediately after', 'immediately before', 'respond immediately'],
    wordFormation: 'immediate=即座の + -ly(副詞語尾)。',
    relatedWords: ['immediate', 'instantly', 'at once'],
  },
  {
    id: 'immigrant',
    word: 'immigrant',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['移民、(外国からの)移住者'],
    pronunciation: '/ˈɪmɪɡrənt/',
    exampleSentence: 'Many immigrants came to the city in search of better jobs.',
    exampleTranslationJa: '多くの移民がより良い仕事を求めてその都市にやって来た。',
    collocations: ['immigrant workers', 'immigrant community', 'first-generation immigrant'],
    wordFormation: 'im-(in-)=中へ + migr=移動する(ラテン語 migrare)+ -ant=人。「中へ移り住む人」。',
    relatedWords: ['immigration', 'immigrate', 'emigrant', 'migrate'],
  },
  {
    id: 'impact',
    word: 'impact',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['影響、効果', '衝撃、衝突'],
    pronunciation: '/ˈɪmpækt/',
    exampleSentence: 'Social media has had a huge impact on the way we communicate.',
    exampleTranslationJa: 'ソーシャルメディアは私たちのコミュニケーションの仕方に大きな影響を与えてきた。',
    collocations: ['have an impact on', 'environmental impact', 'major impact'],
    wordFormation: '動詞(〜に影響を与える)としても使われ、その場合は /ɪmˈpækt/ と後ろに強勢が移る。',
    relatedWords: ['influence', 'effect', 'affect'],
  },
  {
    id: 'imply',
    word: 'imply',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['ほのめかす、暗に意味する'],
    pronunciation: '/ɪmˈplaɪ/',
    exampleSentence: 'His tone seemed to imply that he was not satisfied with the results.',
    exampleTranslationJa: '彼の口調は、結果に満足していないことをほのめかしているようだった。',
    collocations: ['seem to imply', 'strongly imply'],
    wordFormation: 'im-(in-)=中に + ply(ラテン語 plicare=折る)→「中に折り込む」→言葉の中に隠して伝える。',
    relatedWords: ['implication', 'suggest', 'hint'],
  },
  {
    id: 'import',
    word: 'import',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['輸入する', '(名詞)輸入、輸入品'],
    pronunciation: '/ɪmˈpɔːrt/',
    exampleSentence: 'The country imports most of its oil from abroad.',
    exampleTranslationJa: 'その国は石油の大部分を海外から輸入している。',
    collocations: ['import goods', 'import from', 'imports and exports'],
    wordFormation: 'im-(in-)=中へ + port=運ぶ(ラテン語 portare)。名詞は /ˈɪmpɔːrt/ と前に強勢。',
    relatedWords: ['export', 'transport', 'importer'],
  },
  {
    id: 'impress',
    word: 'impress',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['感銘を与える、印象づける'],
    pronunciation: '/ɪmˈpres/',
    exampleSentence: 'He worked hard to impress his new boss during the first week.',
    exampleTranslationJa: '彼は最初の1週間、新しい上司に良い印象を与えようと懸命に働いた。',
    collocations: ['be impressed by', 'deeply impress', 'try to impress'],
    wordFormation: 'im-(in-)=上に + press=押す →「心に押しつける」→印象づける。',
    relatedWords: ['impression', 'impressive', 'impressed'],
  },
  {
    id: 'impression',
    word: 'impression',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['印象', '感銘'],
    pronunciation: '/ɪmˈpreʃən/',
    exampleSentence: 'The young player made a strong impression at his first game.',
    exampleTranslationJa: 'その若い選手は初めての試合で強い印象を残した。',
    collocations: ['first impression', 'make an impression', 'give the impression'],
    wordFormation: 'impress=印象づける + -ion(名詞語尾)。',
    relatedWords: ['impress', 'impressive'],
  },
  {
    id: 'impressive',
    word: 'impressive',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['印象的な、見事な'],
    pronunciation: '/ɪmˈpresɪv/',
    exampleSentence: 'The view from the top of the mountain was truly impressive.',
    exampleTranslationJa: '山頂からの眺めは実に見事だった。',
    collocations: ['impressive performance', 'impressive record', 'highly impressive'],
    wordFormation: 'impress=印象づける + -ive(形容詞語尾)。',
    relatedWords: ['impress', 'impression', 'remarkable'],
  },
  {
    id: 'improve',
    word: 'improve',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['改善する、良くする', '上達する'],
    pronunciation: '/ɪmˈpruːv/',
    exampleSentence: 'Reading every day is a great way to improve your English.',
    exampleTranslationJa: '毎日読書をすることは英語を上達させる素晴らしい方法だ。',
    collocations: ['improve skills', 'improve quality', 'significantly improve'],
    relatedWords: ['improvement', 'improved', 'enhance'],
  },
  {
    id: 'improvement',
    word: 'improvement',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['改善、向上'],
    pronunciation: '/ɪmˈpruːvmənt/',
    exampleSentence: 'There has been a big improvement in her grades this year.',
    exampleTranslationJa: '今年、彼女の成績は大きく向上した。',
    collocations: ['significant improvement', 'room for improvement', 'improvement in'],
    wordFormation: 'improve=改善する + -ment(名詞語尾)。',
    relatedWords: ['improve', 'progress', 'development'],
  },
  {
    id: 'incident',
    word: 'incident',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['出来事、事件'],
    pronunciation: '/ˈɪnsɪdənt/',
    exampleSentence: 'The police are investigating a serious incident at the station.',
    exampleTranslationJa: '警察は駅で起きた重大な事件を捜査している。',
    collocations: ['serious incident', 'report an incident', 'without incident'],
    wordFormation: 'in-=上に + cid(ラテン語 cadere=落ちる)+ -ent →「身に降りかかること」。accident と同じ語根。',
    relatedWords: ['accident', 'event', 'incidentally'],
  },
  {
    id: 'include',
    word: 'include',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['含む、含める'],
    pronunciation: '/ɪnˈkluːd/',
    exampleSentence: 'The price of the tour includes lunch and museum tickets.',
    exampleTranslationJa: 'ツアーの料金には昼食と美術館のチケットが含まれている。',
    collocations: ['include in', 'prices include'],
    etymology: 'ラテン語 includere「閉じ込める」(in-=中に + claudere=閉じる)に由来。',
    relatedWords: ['including', 'inclusive', 'exclude', 'contain'],
  },
  {
    id: 'income',
    word: 'income',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['収入、所得'],
    pronunciation: '/ˈɪnkʌm/',
    exampleSentence: 'Families with a low income can apply for extra support.',
    exampleTranslationJa: '低所得の家庭は追加の支援を申請できる。',
    collocations: ['annual income', 'low income', 'source of income'],
    wordFormation: 'in=中に + come=来る →「入ってくるお金」。',
    relatedWords: ['salary', 'earnings', 'revenue'],
  },
  {
    id: 'increase',
    word: 'increase',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['増える、増やす', '(名詞)増加'],
    pronunciation: '/ɪnˈkriːs/',
    exampleSentence: 'The number of students learning online has increased rapidly.',
    exampleTranslationJa: 'オンラインで学ぶ学生の数は急速に増えている。',
    collocations: ['increase by', 'increase in', 'sharp increase'],
    wordFormation: 'in-=中へ + crease(ラテン語 crescere=成長する)。名詞は /ˈɪnkriːs/ と前に強勢。',
    relatedWords: ['decrease', 'increasingly', 'growth'],
  },
  {
    id: 'increasingly',
    word: 'increasingly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['ますます、だんだん'],
    pronunciation: '/ɪnˈkriːsɪŋli/',
    exampleSentence: 'It is becoming increasingly difficult to find affordable housing in the city.',
    exampleTranslationJa: '都市部で手頃な住宅を見つけるのはますます難しくなっている。',
    collocations: ['increasingly important', 'increasingly popular', 'increasingly common'],
    wordFormation: 'increase=増える + -ing + -ly(副詞語尾)。',
    relatedWords: ['increase', 'growing', 'more and more'],
  },
  {
    id: 'incredible',
    word: 'incredible',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['信じられないほどすばらしい', '信じがたい、驚くべき'],
    pronunciation: '/ɪnˈkredəbəl/',
    exampleSentence: 'The team made an incredible comeback in the final minutes.',
    exampleTranslationJa: 'チームは残り数分で信じられないような逆転をした。',
    collocations: ['incredible story', 'absolutely incredible', 'incredible experience'],
    wordFormation: 'in-=否定 + cred=信じる(ラテン語 credere)+ -ible=できる →「信じられない」。',
    relatedWords: ['incredibly', 'unbelievable', 'amazing'],
  },
  {
    id: 'incredibly',
    word: 'incredibly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['信じられないほど、非常に'],
    pronunciation: '/ɪnˈkredəbli/',
    exampleSentence: 'She is incredibly talented for someone so young.',
    exampleTranslationJa: '彼女はあれほど若いのに信じられないほど才能がある。',
    collocations: ['incredibly difficult', 'incredibly fast'],
    wordFormation: 'incredible=信じられない + -ly(副詞語尾)。',
    relatedWords: ['incredible', 'extremely', 'amazingly'],
  },
  {
    id: 'indeed',
    word: 'indeed',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['実に、確かに', '(強調して)本当に'],
    pronunciation: '/ɪnˈdiːd/',
    exampleSentence: 'The results were very surprising indeed.',
    exampleTranslationJa: 'その結果は実に驚くべきものだった。',
    collocations: ['very much indeed', 'thank you very much indeed'],
    wordFormation: 'in + deed=行い →「実際の行いにおいて」→実際に、確かに。',
    relatedWords: ['certainly', 'truly', 'really'],
  },
  {
    id: 'independence',
    word: 'independence',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['独立', '自立'],
    pronunciation: '/ˌɪndɪˈpendəns/',
    exampleSentence: 'The country celebrated fifty years of independence last month.',
    exampleTranslationJa: 'その国は先月、独立50周年を祝った。',
    collocations: ['gain independence', 'financial independence', 'Independence Day'],
    wordFormation: 'in-=否定 + depend=依存する + -ence(名詞語尾)→「依存しないこと」。',
    relatedWords: ['independent', 'dependence', 'freedom'],
  },
  {
    id: 'independent',
    word: 'independent',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['独立した', '自立した'],
    pronunciation: '/ˌɪndɪˈpendənt/',
    exampleSentence: 'She has been independent since she moved out at eighteen.',
    exampleTranslationJa: '彼女は18歳で家を出て以来、自立している。',
    collocations: ['independent country', 'financially independent', 'independent of'],
    wordFormation: 'in-=否定 + dependent=依存した。',
    relatedWords: ['independence', 'independently', 'dependent'],
  },
  {
    id: 'indicate',
    word: 'indicate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['示す、指し示す', '(データなどが)〜を示唆する'],
    pronunciation: '/ˈɪndɪkeɪt/',
    exampleSentence: 'Recent studies indicate that regular exercise improves sleep.',
    exampleTranslationJa: '最近の研究は、定期的な運動が睡眠を改善することを示している。',
    collocations: ['research indicates', 'clearly indicate', 'indicate that'],
    etymology: 'ラテン語 indicare「指し示す」に由来。dict(言う・示す)系の語根を含む。',
    relatedWords: ['indication', 'indicator', 'suggest'],
  },
  {
    id: 'individual',
    word: 'individual',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['個々の、個人の', '(名詞)個人'],
    pronunciation: '/ˌɪndɪˈvɪdʒuəl/',
    exampleSentence: 'Each individual student receives feedback from the teacher.',
    exampleTranslationJa: '一人ひとりの生徒が先生からフィードバックを受け取る。',
    collocations: ['individual needs', 'individual choice', 'private individual'],
    wordFormation: 'in-=否定 + divid=分ける + -ual →「それ以上分けられないもの」→個人。',
    relatedWords: ['individually', 'personal', 'person'],
  },
  {
    id: 'industrial',
    word: 'industrial',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['産業の、工業の'],
    pronunciation: '/ɪnˈdʌstriəl/',
    exampleSentence: 'The city grew quickly during the industrial age.',
    exampleTranslationJa: 'その都市は工業化の時代に急速に発展した。',
    collocations: ['industrial area', 'industrial revolution', 'industrial production'],
    wordFormation: 'industry=産業 + -al(形容詞語尾)。',
    relatedWords: ['industry', 'manufacturing', 'industrialize'],
  },
  {
    id: 'industry',
    word: 'industry',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['産業、工業', '〜業界'],
    pronunciation: '/ˈɪndəstri/',
    exampleSentence: 'She works in the fashion industry in New York.',
    exampleTranslationJa: '彼女はニューヨークのファッション業界で働いている。',
    collocations: ['tourist industry', 'film industry', 'heavy industry'],
    relatedWords: ['industrial', 'business', 'sector'],
  },
  {
    id: 'inevitable',
    word: 'inevitable',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['避けられない、必然的な'],
    pronunciation: '/ɪnˈevɪtəbəl/',
    exampleSentence: 'After so many mistakes, his defeat was inevitable.',
    exampleTranslationJa: 'あれほど多くのミスをした後では、彼の敗北は避けられなかった。',
    collocations: ['inevitable result', 'seem inevitable', 'almost inevitable'],
    wordFormation: 'in-=否定 + evitable(ラテン語 evitare=避ける + -able)→「避けることができない」。',
    relatedWords: ['inevitably', 'unavoidable', 'certain'],
  },
  {
    id: 'infection',
    word: 'infection',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['感染', '感染症'],
    pronunciation: '/ɪnˈfekʃən/',
    exampleSentence: 'Wash your hands often to prevent the spread of infection.',
    exampleTranslationJa: '感染の拡大を防ぐために、こまめに手を洗いましょう。',
    collocations: ['ear infection', 'risk of infection', 'spread of infection'],
    wordFormation: 'infect=感染させる + -ion(名詞語尾)。',
    relatedWords: ['infect', 'infectious', 'disease', 'virus'],
  },
  {
    id: 'influence',
    word: 'influence',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['影響、影響力', '(動詞)影響を与える'],
    pronunciation: '/ˈɪnfluəns/',
    exampleSentence: "Parents have a strong influence on their children's habits.",
    exampleTranslationJa: '親は子どもの習慣に強い影響を与える。',
    collocations: ['have an influence on', 'under the influence of', 'strong influence'],
    etymology: 'ラテン語 influere「流れ込む」(in-=中へ + fluere=流れる)に由来。星から流れ込む力が人を左右するという占星術の考えから。',
    relatedWords: ['influential', 'impact', 'affect'],
  },
  {
    id: 'inform',
    word: 'inform',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['知らせる、通知する'],
    pronunciation: '/ɪnˈfɔːrm/',
    exampleSentence: 'Please inform the office if you change your address.',
    exampleTranslationJa: '住所を変更した場合は事務所に知らせてください。',
    collocations: ['inform somebody of', 'keep somebody informed'],
    etymology: 'ラテン語 informare「形づくる」(in- + forma=形)に由来。「心に形を与える」→教える、知らせる。',
    relatedWords: ['information', 'informative', 'notify'],
  },
  {
    id: 'ingredient',
    word: 'ingredient',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(料理の)材料、成分', '(成功などの)要素'],
    pronunciation: '/ɪnˈɡriːdiənt/',
    exampleSentence: 'Mix all the ingredients together in a large bowl.',
    exampleTranslationJa: 'すべての材料を大きなボウルで混ぜ合わせてください。',
    collocations: ['main ingredient', 'fresh ingredients', 'key ingredient'],
    relatedWords: ['recipe', 'element', 'component'],
  },
  {
    id: 'initial',
    word: 'initial',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['最初の、初めの', '(名詞)頭文字、イニシャル'],
    pronunciation: '/ɪˈnɪʃəl/',
    exampleSentence: 'My initial reaction was to say no, but then I changed my mind.',
    exampleTranslationJa: '最初の反応は断ることだったが、その後考えを変えた。',
    collocations: ['initial stage', 'initial reaction', 'initial cost'],
    wordFormation: 'ラテン語 initium「始まり」+ -al(形容詞語尾)。',
    relatedWords: ['initially', 'initiative', 'original'],
  },
  {
    id: 'initially',
    word: 'initially',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['初めは、当初は'],
    pronunciation: '/ɪˈnɪʃəli/',
    exampleSentence: 'Initially the plan seemed impossible, but it worked in the end.',
    exampleTranslationJa: '当初その計画は不可能に思えたが、最終的にはうまくいった。',
    wordFormation: 'initial=最初の + -ly(副詞語尾)。',
    relatedWords: ['initial', 'originally', 'at first'],
  },
  {
    id: 'initiative',
    word: 'initiative',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['自発性、率先', '主導権', '(新しい)取り組み'],
    pronunciation: '/ɪˈnɪʃətɪv/',
    exampleSentence: 'She showed great initiative by solving the problem on her own.',
    exampleTranslationJa: '彼女は自力で問題を解決し、優れた自発性を示した。',
    collocations: ['take the initiative', 'on your own initiative', 'new initiative'],
    wordFormation: 'ラテン語 initium「始まり」から。initial・initiate と同じ語根。',
    relatedWords: ['initiate', 'initial', 'leadership'],
  },
  {
    id: 'injure',
    word: 'injure',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['傷つける、けがをさせる'],
    pronunciation: '/ˈɪndʒər/',
    exampleSentence: 'Two players were injured during the soccer match.',
    exampleTranslationJa: 'サッカーの試合中に2人の選手が負傷した。',
    collocations: ['be seriously injured', 'be injured in an accident'],
    etymology: 'ラテン語 injuria「不正、侵害」(in-=否定 + jus=法・正義)に由来。',
    relatedWords: ['injury', 'injured', 'hurt', 'wound'],
  },
  {
    id: 'injury',
    word: 'injury',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['けが、負傷'],
    pronunciation: '/ˈɪndʒəri/',
    exampleSentence: 'He missed the rest of the season because of a knee injury.',
    exampleTranslationJa: '彼はひざのけがのためにシーズンの残りを欠場した。',
    collocations: ['serious injury', 'suffer an injury', 'head injury'],
    wordFormation: 'injure=傷つける の名詞形。',
    relatedWords: ['injure', 'injured', 'wound'],
  },
  {
    id: 'inner',
    word: 'inner',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['内側の、内部の', '内面の、心の中の'],
    pronunciation: '/ˈɪnər/',
    exampleSentence: 'The hotel is located in the inner part of the old city.',
    exampleTranslationJa: 'そのホテルは旧市街の内側の部分にある。',
    collocations: ['inner city', 'inner peace', 'inner circle'],
    wordFormation: 'in=中 + -er(比較級語尾)→「より内側の」。反対語は outer。',
    relatedWords: ['outer', 'internal', 'inside'],
  },
  {
    id: 'innocent',
    word: 'innocent',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['無罪の、無実の', '無邪気な、罪のない'],
    pronunciation: '/ˈɪnəsənt/',
    exampleSentence: 'The court decided that the man was innocent of the crime.',
    exampleTranslationJa: '裁判所はその男性がその犯罪について無実だと判断した。',
    collocations: ['innocent of', 'innocent victim', 'completely innocent'],
    wordFormation: 'in-=否定 + noc(ラテン語 nocere=害する)+ -ent →「害をなさない」。',
    relatedWords: ['innocence', 'guilty'],
  },
  {
    id: 'innovation',
    word: 'innovation',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['革新、イノベーション', '新しい工夫・発明'],
    pronunciation: '/ˌɪnəˈveɪʃən/',
    exampleSentence: 'The company is famous for innovation in electric cars.',
    exampleTranslationJa: 'その会社は電気自動車におけるイノベーションで有名だ。',
    collocations: ['technological innovation', 'encourage innovation', 'product innovation'],
    wordFormation: 'in-=中へ + nov=新しい(ラテン語 novus)+ -ation →「新しくすること」。',
    relatedWords: ['innovate', 'innovative', 'invention'],
  },
  {
    id: 'insight',
    word: 'insight',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['洞察(力)', '深い理解'],
    pronunciation: '/ˈɪnsaɪt/',
    exampleSentence: 'Her book gives real insight into life in a small village.',
    exampleTranslationJa: '彼女の本は小さな村での暮らしについて本当の意味での深い理解を与えてくれる。',
    collocations: ['insight into', 'gain insight', 'valuable insight'],
    wordFormation: 'in=中を + sight=見ること →「物事の内側を見抜く力」。',
    relatedWords: ['insightful', 'understanding', 'perception'],
  },
  {
    id: 'insist',
    word: 'insist',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(強く)主張する、言い張る', '強く要求する'],
    pronunciation: '/ɪnˈsɪst/',
    exampleSentence: 'He insisted that he had paid the bill already.',
    exampleTranslationJa: '彼はすでに勘定を払ったと言い張った。',
    collocations: ['insist on', 'insist that'],
    wordFormation: 'in-=上に + sist(ラテン語 sistere=立つ)→「自分の立場に立ち続ける」→主張する。',
    relatedWords: ['insistence', 'demand', 'claim'],
  },
  {
    id: 'inspire',
    word: 'inspire',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['奮い立たせる、やる気にさせる', '着想を与える'],
    pronunciation: '/ɪnˈspaɪər/',
    exampleSentence: 'Her speech inspired many young people to start their own businesses.',
    exampleTranslationJa: '彼女のスピーチは多くの若者を起業へと奮い立たせた。',
    collocations: ['inspire somebody to do', 'be inspired by'],
    etymology: 'ラテン語 inspirare「息を吹き込む」(in-=中へ + spirare=息をする)に由来。',
    relatedWords: ['inspiration', 'inspiring', 'motivate'],
  },
  {
    id: 'install',
    word: 'install',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['取り付ける、設置する', '(ソフトを)インストールする'],
    pronunciation: '/ɪnˈstɔːl/',
    exampleSentence: 'You need to install the latest version of the app first.',
    exampleTranslationJa: 'まずアプリの最新バージョンをインストールする必要があります。',
    collocations: ['install software', 'install a security camera', 'newly installed'],
    relatedWords: ['installation', 'set up', 'uninstall'],
  },
  {
    id: 'instance',
    word: 'instance',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['例、事例', '(for instance で)例えば'],
    pronunciation: '/ˈɪnstəns/',
    exampleSentence: 'There have been several instances of students cheating on tests.',
    exampleTranslationJa: '生徒がテストで不正行為をした事例がいくつかあった。',
    collocations: ['for instance', 'in this instance'],
    relatedWords: ['example', 'case', 'occasion'],
  },
  {
    id: 'instant',
    word: 'instant',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['即座の', '即席の、インスタントの', '(名詞)瞬間'],
    pronunciation: '/ˈɪnstənt/',
    exampleSentence: 'The movie was an instant success all over the world.',
    exampleTranslationJa: 'その映画は世界中でたちまち成功を収めた。',
    collocations: ['instant success', 'instant coffee', 'in an instant'],
    wordFormation: 'in-=そばに + stant(ラテン語 stare=立つ)→「すぐそばに迫っている」→即座の。',
    relatedWords: ['instantly', 'immediate', 'moment'],
  },
  {
    id: 'institute',
    word: 'institute',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['研究所、協会', '(動詞)(制度などを)設ける'],
    pronunciation: '/ˈɪnstɪtuːt/',
    exampleSentence: 'She works at a research institute that studies climate change.',
    exampleTranslationJa: '彼女は気候変動を研究する研究所で働いている。',
    collocations: ['research institute', 'national institute'],
    wordFormation: 'in-=上に + stitute(ラテン語 statuere=立てる)→「設立されたもの」。',
    relatedWords: ['institution', 'academy', 'establish'],
  },
  {
    id: 'institution',
    word: 'institution',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['機関、団体', '制度、慣習'],
    pronunciation: '/ˌɪnstɪˈtuːʃən/',
    exampleSentence: 'Universities are among the oldest institutions in Europe.',
    exampleTranslationJa: '大学はヨーロッパで最も古い機関の一つだ。',
    collocations: ['financial institution', 'educational institution', 'public institution'],
    wordFormation: 'institute=設立する + -ion(名詞語尾)。',
    relatedWords: ['institute', 'institutional', 'organization'],
  },
  {
    id: 'instruction',
    word: 'instruction',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['指示', '(instructions で)説明書、使用法'],
    pronunciation: '/ɪnˈstrʌkʃən/',
    exampleSentence: 'Read the instructions carefully before you use the machine.',
    exampleTranslationJa: '機械を使う前に説明書をよく読んでください。',
    collocations: ['follow instructions', 'give instructions', 'detailed instructions'],
    wordFormation: 'in-=上に + struct(ラテン語 struere=築く)+ -ion。structure と同じ語根。',
    relatedWords: ['instruct', 'instructor', 'direction'],
  },
  {
    id: 'instrument',
    word: 'instrument',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['楽器', '器具、計器'],
    pronunciation: '/ˈɪnstrəmənt/',
    exampleSentence: 'The piano is one of the most popular instruments to learn.',
    exampleTranslationJa: 'ピアノは習い事として最も人気のある楽器の一つだ。',
    collocations: ['musical instrument', 'play an instrument', 'precision instrument'],
    etymology: 'ラテン語 instruere「備え付ける」に由来。instruct と同じ語根。',
    relatedWords: ['instrumental', 'tool', 'device'],
  },
  {
    id: 'insurance',
    word: 'insurance',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['保険'],
    pronunciation: '/ɪnˈʃʊrəns/',
    exampleSentence: 'You should buy travel insurance before your trip abroad.',
    exampleTranslationJa: '海外旅行の前に旅行保険に入っておくべきだ。',
    collocations: ['health insurance', 'car insurance', 'insurance company'],
    wordFormation: 'insure=保険をかける(sure=確実な が語根)+ -ance(名詞語尾)。',
    relatedWords: ['insure', 'assure', 'policy'],
  },
  {
    id: 'intelligence',
    word: 'intelligence',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['知能、知性', '諜報、情報(機関)'],
    pronunciation: '/ɪnˈtelɪdʒəns/',
    exampleSentence: 'Scientists are still studying how human intelligence develops.',
    exampleTranslationJa: '科学者たちは人間の知能がどのように発達するかを今も研究している。',
    collocations: ['artificial intelligence', 'human intelligence', 'intelligence test'],
    wordFormation: 'inter-=間 + leg=選ぶ・読む(ラテン語 legere)+ -ence →「物事の間から選び取る力」。',
    relatedWords: ['intelligent', 'intellectual', 'smart'],
  },
  {
    id: 'intelligent',
    word: 'intelligent',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['頭のよい、知能の高い'],
    pronunciation: '/ɪnˈtelɪdʒənt/',
    exampleSentence: 'Dolphins are extremely intelligent animals.',
    exampleTranslationJa: 'イルカは非常に知能の高い動物だ。',
    collocations: ['highly intelligent', 'intelligent question'],
    wordFormation: 'intelligence の形容詞形。-ent は形容詞語尾。',
    relatedWords: ['intelligence', 'clever', 'smart'],
  },
  {
    id: 'intend',
    word: 'intend',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['〜するつもりである', '意図する'],
    pronunciation: '/ɪnˈtend/',
    exampleSentence: 'We intend to open a second store next year.',
    exampleTranslationJa: '私たちは来年2号店を開く つもりだ。',
    collocations: ['intend to do', 'be intended for'],
    etymology: 'ラテン語 intendere「〜へ(心を)向ける、伸ばす」(in-=〜へ + tendere=伸ばす)に由来。',
    relatedWords: ['intention', 'intended', 'plan'],
  },
  {
    id: 'intense',
    word: 'intense',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['強烈な、激しい', '(感情が)強い'],
    pronunciation: '/ɪnˈtens/',
    exampleSentence: 'The heat was so intense that we stayed inside all day.',
    exampleTranslationJa: '暑さがあまりに激しかったので、私たちは一日中屋内にいた。',
    collocations: ['intense heat', 'intense pressure', 'intense competition'],
    etymology: 'ラテン語 intensus「張りつめた」(intendere「伸ばす」の過去分詞)に由来。',
    relatedWords: ['intensity', 'intensive', 'extreme'],
  },
  {
    id: 'intention',
    word: 'intention',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['意図、つもり'],
    pronunciation: '/ɪnˈtenʃən/',
    exampleSentence: 'I have no intention of selling the house.',
    exampleTranslationJa: '私はその家を売るつもりはまったくない。',
    collocations: ['have no intention of', 'good intentions', 'original intention'],
    wordFormation: 'intend=意図する の名詞形。',
    relatedWords: ['intend', 'intentional', 'purpose', 'aim'],
  },
  {
    id: 'interact',
    word: 'interact',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['交流する、ふれ合う', '相互に作用する'],
    pronunciation: '/ˌɪntərˈækt/',
    exampleSentence: 'The teacher encourages students to interact with each other in English.',
    exampleTranslationJa: 'その先生は生徒たちに英語で互いに交流するよう促している。',
    collocations: ['interact with', 'interact directly'],
    wordFormation: 'inter-=相互に + act=作用する・行動する。',
    relatedWords: ['interaction', 'interactive', 'communicate'],
  },
  {
    id: 'internal',
    word: 'internal',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['内部の', '国内の', '体内の'],
    pronunciation: '/ɪnˈtɜːrnəl/',
    exampleSentence: 'The report is for internal use only and should not be shared.',
    exampleTranslationJa: 'その報告書は社内利用に限られており、外部と共有してはならない。',
    collocations: ['internal use', 'internal affairs', 'internal organs'],
    wordFormation: 'ラテン語 internus「内部の」+ -al。反対語は external。',
    relatedWords: ['external', 'inner', 'internally'],
  },
  {
    id: 'international',
    word: 'international',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['国際的な、国家間の'],
    pronunciation: '/ˌɪntərˈnæʃənəl/',
    exampleSentence: 'The city hosts an international film festival every spring.',
    exampleTranslationJa: 'その都市では毎年春に国際映画祭が開かれる。',
    collocations: ['international trade', 'international community', 'international flight'],
    wordFormation: 'inter-=〜の間 + nation=国家 + -al →「国家間の」。',
    relatedWords: ['internationally', 'national', 'global'],
  },
  {
    id: 'interpret',
    word: 'interpret',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['解釈する', '通訳する'],
    pronunciation: '/ɪnˈtɜːrprət/',
    exampleSentence: 'People can interpret the same painting in very different ways.',
    exampleTranslationJa: '人は同じ絵をまったく異なる仕方で解釈することがある。',
    collocations: ['interpret as', 'interpret data', 'widely interpreted'],
    etymology: 'ラテン語 interpres「仲介者、通訳者」に由来。inter-=間 →「両者の間に立って意味を伝える」。',
    relatedWords: ['interpretation', 'interpreter', 'translate'],
  },
  {
    id: 'interrupt',
    word: 'interrupt',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(話などを)さえぎる', '中断する'],
    pronunciation: '/ˌɪntəˈrʌpt/',
    exampleSentence: "Please don't interrupt me while I'm talking.",
    exampleTranslationJa: '私が話している間は口を挟まないでください。',
    collocations: ['sorry to interrupt', 'interrupt a conversation'],
    wordFormation: 'inter-=間に + rupt(ラテン語 rumpere=破る)→「間に割って入る」。',
    relatedWords: ['interruption', 'disturb', 'break in'],
  },
  {
    id: 'introduce',
    word: 'introduce',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['紹介する', '導入する、取り入れる'],
    pronunciation: '/ˌɪntrəˈduːs/',
    exampleSentence: 'Let me introduce you to my colleague from the Tokyo office.',
    exampleTranslationJa: '東京オフィスの同僚をあなたに紹介させてください。',
    collocations: ['introduce somebody to', 'introduce a new system'],
    wordFormation: 'intro-=中へ + duce(ラテン語 ducere=導く)→「中へ導き入れる」。',
    relatedWords: ['introduction', 'introductory'],
  },
  {
    id: 'invest',
    word: 'invest',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['投資する', '(時間・労力を)注ぐ'],
    pronunciation: '/ɪnˈvest/',
    exampleSentence: 'They decided to invest their savings in a small restaurant.',
    exampleTranslationJa: '彼らは貯金を小さなレストランに投資することにした。',
    collocations: ['invest in', 'invest money', 'invest time'],
    etymology: 'ラテン語 investire「衣を着せる」(in- + vestis=衣服)に由来。のちにイタリア語で「資金を投じる」の意味が生まれた。',
    relatedWords: ['investment', 'investor', 'fund'],
  },
  {
    id: 'investigate',
    word: 'investigate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['調査する、捜査する'],
    pronunciation: '/ɪnˈvestɪɡeɪt/',
    exampleSentence: 'The police are investigating the cause of the fire.',
    exampleTranslationJa: '警察は火事の原因を調査している。',
    collocations: ['investigate a crime', 'thoroughly investigate', 'investigate a complaint'],
    etymology: 'ラテン語 investigare「跡をたどる」(vestigium=足跡)に由来。',
    relatedWords: ['investigation', 'investigator', 'examine'],
  },
  {
    id: 'investment',
    word: 'investment',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['投資', '投資した金・もの'],
    pronunciation: '/ɪnˈvestmənt/',
    exampleSentence: 'Buying a good dictionary is a smart investment for any learner.',
    exampleTranslationJa: '良い辞書を買うことは、どんな学習者にとっても賢い投資だ。',
    collocations: ['make an investment', 'foreign investment', 'return on investment'],
    wordFormation: 'invest=投資する + -ment(名詞語尾)。',
    relatedWords: ['invest', 'investor', 'fund'],
  },
  {
    id: 'invitation',
    word: 'invitation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['招待', '招待状'],
    pronunciation: '/ˌɪnvɪˈteɪʃən/',
    exampleSentence: 'Thank you for the invitation to your wedding.',
    exampleTranslationJa: '結婚式へのご招待をありがとうございます。',
    collocations: ['accept an invitation', 'send an invitation', 'invitation to'],
    wordFormation: 'invite=招待する + -ation(名詞語尾)。',
    relatedWords: ['invite', 'guest'],
  },
  {
    id: 'involve',
    word: 'involve',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['含む、伴う', '関与させる、巻き込む'],
    pronunciation: '/ɪnˈvɑːlv/',
    exampleSentence: 'The job involves traveling to other countries several times a year.',
    exampleTranslationJa: 'その仕事には年に数回の海外出張が含まれる。',
    collocations: ['involve doing', 'be involved in', 'get involved'],
    etymology: 'ラテン語 involvere「巻き込む」(in-=中へ + volvere=回す・巻く)に由来。',
    relatedWords: ['involved', 'involvement', 'include'],
  },
  {
    id: 'involved',
    word: 'involved',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['関わっている、関与した', '(話などが)込み入った'],
    pronunciation: '/ɪnˈvɑːlvd/',
    exampleSentence: 'More than fifty volunteers were involved in the cleanup project.',
    exampleTranslationJa: '50人を超えるボランティアがその清掃プロジェクトに関わった。',
    collocations: ['be involved in', 'get involved with', 'deeply involved'],
    wordFormation: 'involve の過去分詞が形容詞化したもの。be involved in の形で使うことが多い。',
    relatedWords: ['involve', 'involvement', 'engaged'],
  },
  {
    id: 'issue',
    word: 'issue',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['問題(点)、論点', '(雑誌の)号、発行', '(動詞)発行する'],
    pronunciation: '/ˈɪʃuː/',
    exampleSentence: 'Climate change is one of the most important issues of our time.',
    exampleTranslationJa: '気候変動は現代の最も重要な問題の一つだ。',
    collocations: ['raise an issue', 'social issues', 'deal with an issue'],
    etymology: '古フランス語 issir「外へ出る」(ラテン語 exire)に由来。「出てくるもの」→発行物、論点。',
    relatedWords: ['problem', 'matter', 'topic'],
  },
  {
    id: 'item',
    word: 'item',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['品物、品目', '(リストの)項目'],
    pronunciation: '/ˈaɪtəm/',
    exampleSentence: 'Please check that every item on the list is packed.',
    exampleTranslationJa: 'リストのすべての品物が荷造りされているか確認してください。',
    collocations: ['item on the list', 'luxury item', 'news item'],
    etymology: 'ラテン語 item「同様に」に由来。リストで各項目の前に置かれた語がそのまま名詞になった。',
    relatedWords: ['list', 'article', 'goods'],
  },
  {
    id: 'journal',
    word: 'journal',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['専門誌、学術誌', '日誌、日記'],
    pronunciation: '/ˈdʒɜːrnəl/',
    exampleSentence: 'Her research was published in a famous medical journal.',
    exampleTranslationJa: '彼女の研究は有名な医学雑誌に掲載された。',
    collocations: ['academic journal', 'scientific journal', 'keep a journal'],
    etymology: 'ラテン語 diurnalis「毎日の」に由来。もとは「日々の記録」の意味。journey と同語源。',
    relatedWords: ['journalist', 'journalism', 'magazine', 'diary'],
  },
  {
    id: 'journey',
    word: 'journey',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(長い)旅、道のり', '(比喩的に)過程、歩み'],
    pronunciation: '/ˈdʒɜːrni/',
    exampleSentence: 'The journey from the airport to the hotel takes about an hour.',
    exampleTranslationJa: '空港からホテルまでの道のりは約1時間かかる。',
    collocations: ['long journey', 'safe journey', 'journey to'],
    etymology: '古フランス語 journee「一日(の旅)」に由来。ラテン語 diurnus「日の」から。',
    relatedWords: ['trip', 'travel', 'voyage'],
  },
  {
    id: 'judge',
    word: 'judge',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['裁判官', '審査員', '(動詞)判断する、審査する'],
    pronunciation: '/dʒʌdʒ/',
    exampleSentence: "You shouldn't judge people by their appearance.",
    exampleTranslationJa: '人を見た目で判断すべきではない。',
    collocations: ['judge by', 'judge a competition', 'federal judge'],
    etymology: 'ラテン語 judex「裁判官」(jus=法 + dicere=言う)に由来。「法を告げる人」。',
    relatedWords: ['judgment', 'justice', 'court'],
  },
  {
    id: 'judgment',
    word: 'judgment',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['判断、判断力', '判決'],
    pronunciation: '/ˈdʒʌdʒmənt/',
    exampleSentence: 'In my judgment, this is the best option we have.',
    exampleTranslationJa: '私の判断では、これが私たちにとって最良の選択肢だ。',
    collocations: ['make a judgment', 'good judgment', 'pass judgment'],
    wordFormation: 'judge=判断する + -ment(名詞語尾)。イギリス英語では judgement ともつづる。',
    relatedWords: ['judge', 'justice', 'decision'],
  },
  {
    id: 'junior',
    word: 'junior',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['下級の、若手の', '(名詞)年少者、(米国で)大学3年生'],
    pronunciation: '/ˈdʒuːniər/',
    exampleSentence: 'She started as a junior member of the design team.',
    exampleTranslationJa: '彼女はデザインチームの若手メンバーとしてスタートした。',
    collocations: ['junior staff', 'junior high school'],
    etymology: 'ラテン語 junior「より若い」(juvenis「若い」の比較級)に由来。',
    relatedWords: ['senior', 'youth'],
  },
  {
    id: 'justice',
    word: 'justice',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['正義、公正', '司法、裁判'],
    pronunciation: '/ˈdʒʌstɪs/',
    exampleSentence: 'The families of the victims are still waiting for justice.',
    exampleTranslationJa: '被害者の家族たちは今も正義がなされるのを待っている。',
    collocations: ['social justice', 'bring somebody to justice', 'sense of justice'],
    wordFormation: 'just=正しい + -ice(名詞語尾)。ラテン語 justitia から。',
    relatedWords: ['just', 'justify', 'injustice', 'fair'],
  },
  {
    id: 'justify',
    word: 'justify',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['正当化する', '正当な理由を示す'],
    pronunciation: '/ˈdʒʌstɪfaɪ/',
    exampleSentence: 'How can you justify spending so much money on a car?',
    exampleTranslationJa: '車にそんな大金を使うことをどう正当化できるのか。',
    collocations: ['justify a decision', 'justify spending', 'hard to justify'],
    wordFormation: 'just=正しい + -ify=〜にする →「正しいと示す」。',
    relatedWords: ['justification', 'justice', 'defend'],
  },
  {
    id: 'keen',
    word: 'keen',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['熱心な、〜したがっている', '(感覚などが)鋭い'],
    pronunciation: '/kiːn/',
    exampleSentence: 'She is very keen to learn more about Japanese culture.',
    exampleTranslationJa: '彼女は日本文化についてもっと学びたいととても熱心だ。',
    collocations: ['keen to do', 'keen on', 'keen interest'],
    relatedWords: ['eager', 'enthusiastic', 'interested'],
  },
  {
    id: 'keep-up-with',
    word: 'keep up with',
    level: 'B2',
    partOfSpeech: '句動詞',
    meaningsJa: ['〜に遅れずについていく', '(情報・流行を)追い続ける'],
    pronunciation: '/ˌkiːp ˈʌp wɪð/',
    exampleSentence: 'He walks so fast that I can hardly keep up with him.',
    exampleTranslationJa: '彼は歩くのがとても速いので、私はほとんどついていけない。',
    collocations: ['keep up with the news', 'keep up with changes', 'keep up with demand'],
    relatedWords: ['catch up with', 'fall behind', 'keep on'],
  },
  {
    id: 'knowledge',
    word: 'knowledge',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['知識'],
    pronunciation: '/ˈnɑːlɪdʒ/',
    exampleSentence: 'She has a deep knowledge of European history.',
    exampleTranslationJa: '彼女はヨーロッパ史について深い知識を持っている。',
    collocations: ['general knowledge', 'knowledge of', 'gain knowledge'],
    wordFormation: 'know=知る + -ledge(名詞語尾)。先頭の k は発音しない。',
    relatedWords: ['know', 'knowledgeable', 'wisdom'],
  },
  {
    id: 'label',
    word: 'label',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ラベル、表示', '(動詞)ラベルを貼る、〜と分類する'],
    pronunciation: '/ˈleɪbəl/',
    exampleSentence: 'Always read the label before you take any medicine.',
    exampleTranslationJa: '薬を飲む前には必ずラベルを読みなさい。',
    collocations: ['read the label', 'warning label', 'put a label on'],
    relatedWords: ['tag', 'sticker', 'brand'],
  },
  {
    id: 'labor',
    word: 'labor',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['労働', '労働力、労働者(全体)'],
    pronunciation: '/ˈleɪbər/',
    exampleSentence: 'The cost of labor has risen sharply in recent years.',
    exampleTranslationJa: '近年、人件費が急激に上昇している。',
    collocations: ['labor costs', 'labor market', 'manual labor'],
    etymology: 'ラテン語 labor「労働、骨折り」に由来。イギリス英語では labour とつづる。',
    relatedWords: ['laborer', 'laboratory', 'work', 'employment'],
  },
  {
    id: 'laboratory',
    word: 'laboratory',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['実験室、研究室'],
    pronunciation: '/ˈlæbrətɔːri/',
    exampleSentence: 'The students did the experiment in the school laboratory.',
    exampleTranslationJa: '生徒たちは学校の実験室でその実験を行った。',
    collocations: ['research laboratory', 'laboratory test', 'laboratory equipment'],
    wordFormation: 'labor=働く(ラテン語 laborare)+ -ory=場所 →「作業をする場所」。口語では lab と略す。',
    relatedWords: ['lab', 'experiment', 'scientist'],
  },
  {
    id: 'lack',
    word: 'lack',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['不足、欠如', '(動詞)〜を欠いている'],
    pronunciation: '/læk/',
    exampleSentence: 'The project failed because of a lack of money.',
    exampleTranslationJa: 'そのプロジェクトは資金不足のために失敗した。',
    collocations: ['lack of', 'lack confidence', 'lack experience'],
    relatedWords: ['shortage', 'absence', 'missing'],
  },
  {
    id: 'landscape',
    word: 'landscape',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['風景、景観', '(比喩的に)状況、情勢'],
    pronunciation: '/ˈlændskeɪp/',
    exampleSentence: 'The train passed through a beautiful landscape of mountains and lakes.',
    exampleTranslationJa: '列車は山と湖の美しい風景の中を走り抜けた。',
    collocations: ['rural landscape', 'political landscape', 'landscape painting'],
    wordFormation: 'land=土地 + -scape=眺め(オランダ語の絵画用語 -schap に由来)。',
    relatedWords: ['scenery', 'view', 'countryside'],
  },
  {
    id: 'largely',
    word: 'largely',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['主に、大部分は'],
    pronunciation: '/ˈlɑːrdʒli/',
    exampleSentence: 'The event was largely a success, despite the rain.',
    exampleTranslationJa: '雨にもかかわらず、そのイベントはおおむね成功だった。',
    collocations: ['largely because of', 'largely responsible for', 'largely ignored'],
    wordFormation: 'large=大きい + -ly(副詞語尾)。',
    relatedWords: ['mainly', 'mostly', 'primarily'],
  },
  {
    id: 'lately',
    word: 'lately',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['最近、近ごろ(現在完了とともに使うことが多い)'],
    pronunciation: '/ˈleɪtli/',
    exampleSentence: 'Have you seen any good movies lately?',
    exampleTranslationJa: '最近、何かいい映画を見ましたか。',
    collocations: ['only lately', 'until lately'],
    wordFormation: 'late=遅い、最近の + -ly(副詞語尾)。',
    relatedWords: ['recently', 'these days', 'nowadays'],
  },
  {
    id: 'latest',
    word: 'latest',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['最新の'],
    pronunciation: '/ˈleɪtɪst/',
    exampleSentence: 'Have you heard the latest news about the new stadium?',
    exampleTranslationJa: '新しいスタジアムについての最新のニュースを聞きましたか。',
    collocations: ['the latest news', 'latest version', 'latest fashion'],
    wordFormation: 'late の最上級から。「最も遅く出た」→最新の。',
    relatedWords: ['late', 'newest', 'recent', 'up to date'],
  },
  {
    id: 'latter',
    word: 'latter',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['(二つのうち)後者の', '後半の'],
    pronunciation: '/ˈlætər/',
    exampleSentence: 'Between tea and coffee, I prefer the latter.',
    exampleTranslationJa: '紅茶とコーヒーなら、私は後者の方が好きだ。',
    collocations: ['the latter half', 'the former and the latter'],
    etymology: 'late の古い比較級。「あとの方の」が原義。',
    mnemonic: 'former(前者)とペアで「フォーマー前・ラター後」とセットで覚える。',
    relatedWords: ['former', 'later', 'last'],
  },
  {
    id: 'launch',
    word: 'launch',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(事業・商品を)開始する、売り出す', '(ロケットを)打ち上げる', '(名詞)発売、開始'],
    pronunciation: '/lɔːntʃ/',
    exampleSentence: 'The company will launch its new smartphone in October.',
    exampleTranslationJa: 'その会社は10月に新しいスマートフォンを発売する。',
    collocations: ['launch a product', 'launch a campaign', 'launch a rocket'],
    etymology: '古フランス語 lancier「槍を投げる」に由来。lance(槍)と同語源。',
    relatedWords: ['release', 'start', 'introduce'],
  },
  {
    id: 'layer',
    word: 'layer',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['層、重なり'],
    pronunciation: '/ˈleɪər/',
    exampleSentence: 'There was a thick layer of snow on the roof this morning.',
    exampleTranslationJa: '今朝、屋根には厚い雪の層があった。',
    collocations: ['layer of', 'thin layer', 'ozone layer'],
    wordFormation: 'lay=置く + -er →「置き重ねられたもの」。',
    relatedWords: ['level', 'coating', 'surface'],
  },
  {
    id: 'lead',
    word: 'lead',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['導く、先頭に立つ', '(lead to で)〜につながる', '(名詞)先頭、リード'],
    pronunciation: '/liːd/',
    exampleSentence: 'She will lead the new project team starting next month.',
    exampleTranslationJa: '彼女は来月から新しいプロジェクトチームを率いる。',
    collocations: ['lead to', 'lead a team', 'take the lead'],
    relatedWords: ['leader', 'leadership', 'leading'],
  },
  {
    id: 'leadership',
    word: 'leadership',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['リーダーシップ、指導力', '指導者の地位、指導部'],
    pronunciation: '/ˈliːdərʃɪp/',
    exampleSentence: 'Under her leadership, the company doubled its sales.',
    exampleTranslationJa: '彼女の指導のもと、会社は売上を2倍にした。',
    collocations: ['strong leadership', 'leadership skills', 'under the leadership of'],
    wordFormation: 'leader=指導者 + -ship(状態・地位を表す名詞語尾)。',
    relatedWords: ['leader', 'lead', 'management'],
  },
  {
    id: 'lean',
    word: 'lean',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['傾く、体を傾ける', '寄りかかる', '(形容詞)引き締まった、脂肪の少ない'],
    pronunciation: '/liːn/',
    exampleSentence: 'He leaned against the wall and waited for the bus.',
    exampleTranslationJa: '彼は壁に寄りかかってバスを待った。',
    collocations: ['lean against', 'lean on', 'lean forward'],
    relatedWords: ['bend', 'rest', 'slim'],
  },
  {
    id: 'leather',
    word: 'leather',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['革、レザー'],
    pronunciation: '/ˈleðər/',
    exampleSentence: 'He bought a black leather jacket for the winter.',
    exampleTranslationJa: '彼は冬に備えて黒い革のジャケットを買った。',
    collocations: ['leather jacket', 'leather shoes', 'made of leather'],
    relatedWords: ['fur', 'wool', 'material'],
  },
  {
    id: 'lecture',
    word: 'lecture',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['講義、講演', '説教、小言', '(動詞)講義する'],
    pronunciation: '/ˈlektʃər/',
    exampleSentence: 'The professor gave an interesting lecture on modern art.',
    exampleTranslationJa: 'その教授は現代美術について興味深い講義を行った。',
    collocations: ['give a lecture', 'attend a lecture', 'lecture on'],
    etymology: 'ラテン語 legere「読む」の語根 lect から。「読んで聞かせること」が原義。',
    relatedWords: ['lecturer', 'seminar', 'presentation'],
  },
  {
    id: 'legal',
    word: 'legal',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['合法的な', '法律の、法律に関する'],
    pronunciation: '/ˈliːɡəl/',
    exampleSentence: 'Is it legal to ride an electric scooter on the sidewalk here?',
    exampleTranslationJa: 'ここでは歩道で電動キックボードに乗るのは合法ですか。',
    collocations: ['legal advice', 'legal action', 'perfectly legal'],
    wordFormation: 'leg(ラテン語 lex, legis=法)+ -al(形容詞語尾)。',
    relatedWords: ['illegal', 'legally', 'law'],
  },
  {
    id: 'leisure',
    word: 'leisure',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['余暇、自由時間'],
    pronunciation: '/ˈliːʒər/',
    exampleSentence: 'She spends most of her leisure time reading novels.',
    exampleTranslationJa: '彼女は余暇のほとんどを小説を読んで過ごす。',
    collocations: ['leisure time', 'leisure activities', 'at leisure'],
    relatedWords: ['free time', 'hobby', 'relaxation'],
  },
  {
    id: 'length',
    word: 'length',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['長さ', '(時間の)長さ、期間'],
    pronunciation: '/leŋθ/',
    exampleSentence: 'The pool is fifty meters in length.',
    exampleTranslationJa: 'そのプールは長さ50メートルだ。',
    collocations: ['in length', 'the length of', 'full length'],
    wordFormation: 'long=長い + -th(名詞語尾)。strong→strength と同じパターン。',
    relatedWords: ['long', 'lengthen', 'width', 'height'],
  },
  {
    id: 'level',
    word: 'level',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['水準、レベル', '高さ、階', '(形容詞)平らな、同じ高さの'],
    pronunciation: '/ˈlevəl/',
    exampleSentence: 'Her English has reached a very high level.',
    exampleTranslationJa: '彼女の英語は非常に高いレベルに達している。',
    collocations: ['high level', 'sea level', 'level of'],
    relatedWords: ['standard', 'degree', 'grade'],
  },
  {
    id: 'license',
    word: 'license',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['免許(証)、認可', '(動詞)認可する'],
    pronunciation: '/ˈlaɪsəns/',
    exampleSentence: 'You need a license to drive a motorcycle in Japan.',
    exampleTranslationJa: '日本でバイクを運転するには免許が必要だ。',
    collocations: ["driver's license", 'get a license', 'license fee'],
    wordFormation: 'イギリス英語では名詞を licence とつづる。',
    relatedWords: ['permit', 'permission', 'qualification'],
  },
  {
    id: 'likely',
    word: 'likely',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['ありそうな、〜しそうな'],
    pronunciation: '/ˈlaɪkli/',
    exampleSentence: 'It is likely to rain later this afternoon, so take an umbrella.',
    exampleTranslationJa: '午後遅くに雨が降りそうなので、傘を持って行きなさい。',
    collocations: ['be likely to do', 'most likely', 'highly likely'],
    wordFormation: 'like + -ly。この -ly は形容詞を作る語尾で、副詞ではない点に注意。',
    relatedWords: ['unlikely', 'likelihood', 'probable', 'probably'],
  },
  {
    id: 'limit',
    word: 'limit',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['限界、制限', '(動詞)制限する'],
    pronunciation: '/ˈlɪmɪt/',
    exampleSentence: 'There is a speed limit of thirty miles per hour in this area.',
    exampleTranslationJa: 'この地域には時速30マイルの速度制限がある。',
    collocations: ['speed limit', 'time limit', 'set a limit'],
    etymology: 'ラテン語 limes「境界」に由来。',
    relatedWords: ['limited', 'limitation', 'restrict'],
  },
  {
    id: 'limited',
    word: 'limited',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['限られた、わずかな'],
    pronunciation: '/ˈlɪmɪtɪd/',
    exampleSentence: 'We only had a limited amount of time to finish the test.',
    exampleTranslationJa: '私たちにはテストを終えるための限られた時間しかなかった。',
    collocations: ['limited time', 'limited number', 'limited resources'],
    wordFormation: 'limit=制限する + -ed(形容詞化)。',
    relatedWords: ['limit', 'limitation', 'unlimited'],
  },
  {
    id: 'link',
    word: 'link',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['つながり、関連', '(ウェブの)リンク', '(動詞)つなぐ、関連づける'],
    pronunciation: '/lɪŋk/',
    exampleSentence: 'Studies show a clear link between diet and health.',
    exampleTranslationJa: '研究は食事と健康の間の明確な関連を示している。',
    collocations: ['link between', 'close link', 'click a link'],
    relatedWords: ['connection', 'connect', 'relate'],
  },
  {
    id: 'liquid',
    word: 'liquid',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['液体', '(形容詞)液体の'],
    pronunciation: '/ˈlɪkwɪd/',
    exampleSentence: 'Drink plenty of liquids when you have a fever.',
    exampleTranslationJa: '熱があるときは水分をたっぷりとりなさい。',
    collocations: ['clear liquid', 'liquid soap'],
    etymology: 'ラテン語 liquidus「流れる、澄んだ」に由来。',
    relatedWords: ['solid', 'gas', 'fluid'],
  },
  {
    id: 'literally',
    word: 'literally',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['文字どおり', '(口語の強調で)本当に、まさに'],
    pronunciation: '/ˈlɪtərəli/',
    exampleSentence: 'The word samurai literally means one who serves.',
    exampleTranslationJa: 'サムライという言葉は文字どおりには仕える者を意味する。',
    collocations: ['literally translated', 'quite literally'],
    wordFormation: 'literal=文字どおりの + -ly。ラテン語 littera「文字」が語根。',
    relatedWords: ['literal', 'literary', 'exactly'],
  },
  {
    id: 'literature',
    word: 'literature',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['文学', '(ある分野の)文献'],
    pronunciation: '/ˈlɪtərətʃər/',
    exampleSentence: 'She is studying English literature at university.',
    exampleTranslationJa: '彼女は大学で英文学を勉強している。',
    collocations: ['English literature', 'classic literature', 'scientific literature'],
    etymology: 'ラテン語 littera「文字」に由来。',
    relatedWords: ['literary', 'novel', 'poetry'],
  },
  {
    id: 'load',
    word: 'load',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['積み荷、荷', '負担、負荷', '(動詞)積む、読み込む'],
    pronunciation: '/loʊd/',
    exampleSentence: 'The truck was carrying a heavy load of sand.',
    exampleTranslationJa: 'そのトラックは大量の砂を積んで運んでいた。',
    collocations: ['heavy load', 'a load of', 'load a truck'],
    relatedWords: ['unload', 'download', 'burden'],
  },
  {
    id: 'loan',
    word: 'loan',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['ローン、貸付金', '(動詞)貸す'],
    pronunciation: '/loʊn/',
    exampleSentence: 'They took out a loan to buy their first house.',
    exampleTranslationJa: '彼らは初めての家を買うためにローンを組んだ。',
    collocations: ['take out a loan', 'student loan', 'pay off a loan'],
    relatedWords: ['lend', 'borrow', 'mortgage', 'debt'],
  },
  {
    id: 'local',
    word: 'local',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['地元の、その土地の', '(名詞)地元の人'],
    pronunciation: '/ˈloʊkəl/',
    exampleSentence: 'We bought fresh vegetables at the local market.',
    exampleTranslationJa: '私たちは地元の市場で新鮮な野菜を買った。',
    collocations: ['local people', 'local news', 'local government'],
    wordFormation: 'loc(ラテン語 locus=場所)+ -al(形容詞語尾)。',
    relatedWords: ['locally', 'location', 'regional'],
  },
  {
    id: 'locate',
    word: 'locate',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(位置を)突き止める、見つける', '(be located で)〜に位置する'],
    pronunciation: '/ˈloʊkeɪt/',
    exampleSentence: 'The police were finally able to locate the missing car.',
    exampleTranslationJa: '警察はついに行方不明の車の場所を突き止めることができた。',
    collocations: ['be located in', 'locate the source'],
    wordFormation: 'loc=場所(ラテン語 locus)+ -ate(動詞語尾)。',
    relatedWords: ['location', 'local', 'find', 'position'],
  },
  {
    id: 'location',
    word: 'location',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['場所、位置'],
    pronunciation: '/loʊˈkeɪʃən/',
    exampleSentence: 'The hotel is in a perfect location near the beach.',
    exampleTranslationJa: 'そのホテルはビーチ近くの絶好の場所にある。',
    collocations: ['perfect location', 'central location', 'exact location'],
    wordFormation: 'locate=位置を定める + -ion(名詞語尾)。',
    relatedWords: ['locate', 'place', 'site', 'position'],
  },
  {
    id: 'logical',
    word: 'logical',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['論理的な、筋の通った'],
    pronunciation: '/ˈlɑːdʒɪkəl/',
    exampleSentence: 'It seems logical to start with the easiest questions first.',
    exampleTranslationJa: 'まず一番簡単な問題から始めるのが筋が通っているように思える。',
    collocations: ['logical explanation', 'logical conclusion', 'logical order'],
    wordFormation: 'logic=論理(ギリシャ語 logos=言葉・理性)+ -al(形容詞語尾)。',
    relatedWords: ['logic', 'logically', 'reasonable', 'rational'],
  },
  {
    id: 'look-after',
    word: 'look after',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['〜の世話をする', '〜に気を配る、管理する'],
    pronunciation: '/ˌlʊk ˈæftər/',
    exampleSentence: "Can you look after my dog while I'm away next week?",
    exampleTranslationJa: '来週留守にする間、私の犬の世話をしてもらえますか。',
    collocations: ['look after children', 'look after yourself'],
    relatedWords: ['take care of', 'care for', 'babysit'],
  },
  {
    id: 'look-forward-to',
    word: 'look forward to',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['〜を楽しみに待つ(to の後は名詞・動名詞)'],
    pronunciation: '/ˌlʊk ˈfɔːrwərd tə/',
    exampleSentence: 'I really look forward to seeing you again next month.',
    exampleTranslationJa: '来月またあなたに会えるのを本当に楽しみにしています。',
    collocations: ['look forward to hearing from you', 'look forward to the weekend'],
    relatedWords: ['expect', 'anticipate', "can't wait"],
  },
  {
    id: 'loose',
    word: 'loose',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['ゆるい、ゆるんだ', 'つながれていない、放たれた'],
    pronunciation: '/luːs/',
    exampleSentence: 'These jeans feel a little loose around the waist.',
    exampleTranslationJa: 'このジーンズはウエストまわりが少しゆるく感じる。',
    collocations: ['loose clothes', 'come loose', 'loose change'],
    mnemonic: 'lose(失う、o が1つ)と loose(ゆるい、o が2つ)はつづりの o の数で区別して覚える。',
    relatedWords: ['loosen', 'tight', 'lose'],
  },
  {
    id: 'lord',
    word: 'lord',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['領主、貴族', '(Lord で)神、主'],
    pronunciation: '/lɔːrd/',
    exampleSentence: 'The castle once belonged to a powerful lord.',
    exampleTranslationJa: 'その城はかつて有力な領主のものだった。',
    collocations: ['the House of Lords', 'lord of the castle'],
    etymology: '古英語 hlaford「パンを守る者」(hlaf=パン + weard=番人)に由来。',
    relatedWords: ['lady', 'noble', 'master'],
  },
  {
    id: 'loss',
    word: 'loss',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['失うこと、喪失', '損失、赤字'],
    pronunciation: '/lɔːs/',
    exampleSentence: 'The loss of his job came as a complete shock.',
    exampleTranslationJa: '職を失ったことは彼にとってまったくの衝撃だった。',
    collocations: ['loss of', 'weight loss', 'make a loss'],
    wordFormation: 'lose=失う の名詞形。',
    relatedWords: ['lose', 'lost', 'gain', 'damage'],
  },
  {
    id: 'lower',
    word: 'lower',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['下げる、低くする', '(形容詞)下の方の'],
    pronunciation: '/ˈloʊər/',
    exampleSentence: 'The store lowered its prices to attract more customers.',
    exampleTranslationJa: 'その店はより多くの客を引きつけるために値段を下げた。',
    collocations: ['lower prices', 'lower the risk', 'lower your voice'],
    wordFormation: 'low=低い の比較級 lower が動詞としても使われる。',
    relatedWords: ['low', 'raise', 'reduce'],
  },
  {
    id: 'loyal',
    word: 'loyal',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['忠実な、誠実な'],
    pronunciation: '/ˈlɔɪəl/',
    exampleSentence: "The team's loyal fans supported them even after the defeat.",
    exampleTranslationJa: 'そのチームの忠実なファンは、敗北の後でさえチームを支え続けた。',
    collocations: ['loyal customer', 'loyal friend', 'remain loyal to'],
    etymology: '古フランス語を経てラテン語 legalis「法にかなった」に由来。legal と同語源。',
    relatedWords: ['loyalty', 'faithful', 'devoted'],
  },
  {
    id: 'luxury',
    word: 'luxury',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ぜいたく(品)', '(形容詞的に)高級な'],
    pronunciation: '/ˈlʌkʃəri/',
    exampleSentence: 'For most people, eating out every day is a luxury.',
    exampleTranslationJa: 'ほとんどの人にとって、毎日外食することはぜいたくだ。',
    collocations: ['luxury hotel', 'luxury goods', 'live in luxury'],
    etymology: 'ラテン語 luxus「過剰、ぜいたく」に由来。',
    relatedWords: ['luxurious', 'comfort', 'expensive'],
  },
  {
    id: 'mainly',
    word: 'mainly',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['主に、大部分は'],
    pronunciation: '/ˈmeɪnli/',
    exampleSentence: 'The audience was mainly young people in their twenties.',
    exampleTranslationJa: '観客は主に20代の若者だった。',
    collocations: ['mainly because', 'mainly used for'],
    wordFormation: 'main=主要な + -ly(副詞語尾)。',
    relatedWords: ['main', 'mostly', 'largely', 'primarily'],
  },
  {
    id: 'maintain',
    word: 'maintain',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['維持する、保つ', '整備する', '(意見を)主張し続ける'],
    pronunciation: '/meɪnˈteɪn/',
    exampleSentence: 'Regular exercise helps you maintain a healthy weight.',
    exampleTranslationJa: '定期的な運動は健康的な体重を維持するのに役立つ。',
    collocations: ['maintain a relationship', 'maintain standards', 'maintain equipment'],
    etymology: 'ラテン語 manu tenere「手で保持する」(manus=手 + tenere=保つ)に由来。',
    relatedWords: ['maintenance', 'keep', 'preserve'],
  },
  {
    id: 'major',
    word: 'major',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['主要な、重大な', '(名詞)専攻', '(major in で)専攻する'],
    pronunciation: '/ˈmeɪdʒər/',
    exampleSentence: 'Traffic is a major problem in most big cities.',
    exampleTranslationJa: '交通渋滞はほとんどの大都市で重大な問題だ。',
    collocations: ['major problem', 'major role', 'major in economics'],
    etymology: 'ラテン語 major「より大きい」(magnus「大きい」の比較級)に由来。',
    relatedWords: ['majority', 'minor', 'main', 'significant'],
  },
  {
    id: 'majority',
    word: 'majority',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['大多数', '過半数'],
    pronunciation: '/məˈdʒɔːrəti/',
    exampleSentence: 'The majority of students voted for a longer lunch break.',
    exampleTranslationJa: '大多数の生徒がより長い昼休みに賛成票を投じた。',
    collocations: ['the majority of', 'vast majority', 'majority vote'],
    wordFormation: 'major=より大きい + -ity(名詞語尾)。反対語は minority。',
    relatedWords: ['major', 'minority', 'most'],
  },
  {
    id: 'manage',
    word: 'manage',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['管理する、経営する', '(manage to do で)なんとか〜する'],
    pronunciation: '/ˈmænɪdʒ/',
    exampleSentence: 'She manages a small team of five designers.',
    exampleTranslationJa: '彼女は5人のデザイナーからなる小さなチームを管理している。',
    collocations: ['manage to do', 'manage a company', 'manage time'],
    etymology: 'イタリア語 maneggiare「(馬を)扱う」に由来。ラテン語 manus「手」が語根。',
    relatedWords: ['management', 'manager', 'handle'],
  },
  {
    id: 'management',
    word: 'management',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['経営、管理', '経営陣'],
    pronunciation: '/ˈmænɪdʒmənt/',
    exampleSentence: 'Good time management is essential for busy students.',
    exampleTranslationJa: '忙しい学生にとって、上手な時間管理は不可欠だ。',
    collocations: ['time management', 'senior management', 'under new management'],
    wordFormation: 'manage=管理する + -ment(名詞語尾)。',
    relatedWords: ['manage', 'manager', 'administration'],
  },
]
