import type { VocabularyEntry } from '../types'

export const batch06: VocabularyEntry[] = [
  {
    id: 'personality',
    word: 'personality',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['性格、個性', '(テレビなどの)有名人'],
    pronunciation: '/ˌpɜːrsəˈnæləti/',
    exampleSentence: 'She has a warm and friendly personality.',
    exampleTranslationJa: '彼女は温かく親しみやすい性格をしている。',
    collocations: ['a strong personality', 'personality traits'],
    wordFormation: 'personal(個人の)+ -ity(名詞化)。',
    relatedWords: ['personal', 'character', 'individual'],
  },
  {
    id: 'perspective',
    word: 'perspective',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['視点、観点', '大局的な見方', '遠近法'],
    pronunciation: '/pərˈspektɪv/',
    exampleSentence: 'Traveling abroad gave me a new perspective on my own country.',
    exampleTranslationJa: '海外旅行は、自分の国に対する新しい視点を与えてくれた。',
    collocations: ['from my perspective', 'a different perspective', 'put things in perspective'],
    wordFormation: 'per-(通して)+ spect(見る)。spect は inspect, respect と同語源。',
    relatedWords: ['viewpoint', 'outlook', 'standpoint'],
  },
  {
    id: 'persuade',
    word: 'persuade',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['説得する、説得して〜させる'],
    pronunciation: '/pərˈsweɪd/',
    exampleSentence: 'I persuaded my parents to let me study abroad.',
    exampleTranslationJa: '私は両親を説得して留学させてもらった。',
    collocations: ['persuade someone to do', 'try to persuade'],
    relatedWords: ['persuasion', 'persuasive', 'convince'],
  },
  {
    id: 'phase',
    word: 'phase',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['段階、局面', '(一時的な)時期'],
    pronunciation: '/feɪz/',
    exampleSentence: 'The project is now in its final phase.',
    exampleTranslationJa: 'そのプロジェクトは今、最終段階にある。',
    collocations: ['the final phase', 'a new phase', 'go through a phase'],
    relatedWords: ['stage', 'period', 'step'],
  },
  {
    id: 'phenomenon',
    word: 'phenomenon',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['現象', '驚くべき出来事・人'],
    pronunciation: '/fəˈnɑːmɪnən/',
    exampleSentence: 'Global warming is a phenomenon that affects the whole planet.',
    exampleTranslationJa: '地球温暖化は、地球全体に影響を及ぼす現象だ。',
    collocations: ['a natural phenomenon', 'a social phenomenon'],
    relatedWords: ['event', 'occurrence', 'trend'],
  },
  {
    id: 'philosophy',
    word: 'philosophy',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['哲学', '人生観、考え方'],
    pronunciation: '/fəˈlɑːsəfi/',
    exampleSentence: 'She studied philosophy at university in London.',
    exampleTranslationJa: '彼女はロンドンの大学で哲学を学んだ。',
    collocations: ['a philosophy of life', 'study philosophy'],
    relatedWords: ['philosopher', 'philosophical', 'theory'],
  },
  {
    id: 'physical',
    word: 'physical',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['身体の、肉体の', '物理的な、物質の'],
    pronunciation: '/ˈfɪzɪkl/',
    exampleSentence: 'Regular physical exercise keeps your body healthy.',
    exampleTranslationJa: '定期的な運動は体を健康に保つ。',
    collocations: ['physical exercise', 'physical activity', 'physical contact'],
    relatedWords: ['physically', 'mental', 'physics'],
  },
  {
    id: 'pick up',
    word: 'pick up',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['拾い上げる', '(車で)迎えに行く', '(言語・技術を)自然に身につける'],
    pronunciation: '/ˌpɪk ˈʌp/',
    exampleSentence: 'I will pick you up at the station at seven.',
    exampleTranslationJa: '7時に駅まで車で迎えに行くよ。',
    collocations: ['pick up the phone', 'pick up a language', 'pick someone up'],
    relatedWords: ['drop off', 'collect', 'lift'],
  },
  {
    id: 'pile',
    word: 'pile',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(積み重ねた)山', '(動詞)積み重ねる'],
    pronunciation: '/paɪl/',
    exampleSentence: 'There is a pile of books on my desk.',
    exampleTranslationJa: '私の机の上には本の山がある。',
    collocations: ['a pile of papers', 'pile up'],
    relatedWords: ['heap', 'stack', 'mountain'],
  },
  {
    id: 'pity',
    word: 'pity',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['哀れみ、同情', '残念なこと'],
    pronunciation: '/ˈpɪti/',
    exampleSentence: "It's a pity that you can't come to the party.",
    exampleTranslationJa: 'あなたがパーティーに来られないのは残念だ。',
    collocations: ["it's a pity that", 'feel pity for', 'what a pity'],
    relatedWords: ['sympathy', 'shame', 'mercy'],
  },
  {
    id: 'plain',
    word: 'plain',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['明白な', '飾りのない、無地の', '(名詞)平原'],
    pronunciation: '/pleɪn/',
    exampleSentence: 'She wore a plain white shirt to the interview.',
    exampleTranslationJa: '彼女は面接に無地の白いシャツを着ていった。',
    collocations: ['plain English', 'a plain T-shirt', 'make it plain'],
    relatedWords: ['simple', 'clear', 'obvious'],
  },
  {
    id: 'plenty',
    word: 'plenty',
    level: 'B1',
    partOfSpeech: '代名詞',
    meaningsJa: ['たくさん、十分な量'],
    pronunciation: '/ˈplenti/',
    exampleSentence: 'We have plenty of time before the train leaves.',
    exampleTranslationJa: '電車が出るまでたっぷり時間がある。',
    collocations: ['plenty of time', 'plenty of room'],
    relatedWords: ['enough', 'lots', 'abundance'],
  },
  {
    id: 'point out',
    word: 'point out',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['指摘する'],
    pronunciation: '/ˌpɔɪnt ˈaʊt/',
    exampleSentence: 'Please point out any mistakes you find in my report.',
    exampleTranslationJa: '私の報告書で間違いを見つけたら指摘してください。',
    collocations: ['point out a mistake', 'point out that'],
    relatedWords: ['indicate', 'mention', 'note'],
  },
  {
    id: 'policy',
    word: 'policy',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['政策、方針', '保険証券'],
    pronunciation: '/ˈpɑːləsi/',
    exampleSentence: 'The government announced a new policy on education.',
    exampleTranslationJa: '政府は教育に関する新しい政策を発表した。',
    collocations: ['government policy', 'foreign policy', 'an insurance policy'],
    relatedWords: ['politics', 'strategy', 'rule'],
  },
  {
    id: 'polite',
    word: 'polite',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['礼儀正しい、丁寧な'],
    pronunciation: '/pəˈlaɪt/',
    exampleSentence: 'It is polite to say thank you when someone helps you.',
    exampleTranslationJa: '誰かに助けてもらったらお礼を言うのが礼儀だ。',
    collocations: ['a polite way to ask', 'polite to strangers'],
    relatedWords: ['politely', 'politeness', 'rude'],
  },
  {
    id: 'political',
    word: 'political',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['政治の、政治的な'],
    pronunciation: '/pəˈlɪtɪkl/',
    exampleSentence: 'The country is facing a serious political crisis.',
    exampleTranslationJa: 'その国は深刻な政治的危機に直面している。',
    collocations: ['a political party', 'political power'],
    wordFormation: 'politics(政治)+ -al(形容詞化)。',
    relatedWords: ['politics', 'politician', 'policy'],
  },
  {
    id: 'politician',
    word: 'politician',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['政治家'],
    pronunciation: '/ˌpɑːləˈtɪʃn/',
    exampleSentence: 'The politician promised to create more jobs.',
    exampleTranslationJa: 'その政治家はより多くの雇用を生み出すと約束した。',
    collocations: ['a local politician', 'a leading politician'],
    wordFormation: 'politics(政治)+ -ian(〜する人)。',
    relatedWords: ['politics', 'political', 'government'],
  },
  {
    id: 'politics',
    word: 'politics',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['政治', '政治学'],
    pronunciation: '/ˈpɑːlətɪks/',
    exampleSentence: 'My father never talks about politics at dinner.',
    exampleTranslationJa: '父は夕食の席では決して政治の話をしない。',
    collocations: ['local politics', 'go into politics'],
    relatedWords: ['political', 'politician', 'policy'],
  },
  {
    id: 'pollution',
    word: 'pollution',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['汚染、公害'],
    pronunciation: '/pəˈluːʃn/',
    exampleSentence: 'Air pollution is a serious problem in many big cities.',
    exampleTranslationJa: '大気汚染は多くの大都市で深刻な問題だ。',
    collocations: ['air pollution', 'water pollution', 'reduce pollution'],
    wordFormation: 'pollute(汚染する)+ -ion(名詞化)。',
    relatedWords: ['pollute', 'environment', 'emission'],
  },
  {
    id: 'population',
    word: 'population',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['人口', '(ある地域の)住民'],
    pronunciation: '/ˌpɑːpjuˈleɪʃn/',
    exampleSentence: 'The population of the city has doubled in twenty years.',
    exampleTranslationJa: 'その都市の人口は20年で2倍になった。',
    collocations: ['a large population', 'the aging population'],
    relatedWords: ['popular', 'inhabitant', 'resident'],
  },
  {
    id: 'port',
    word: 'port',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['港、港町'],
    pronunciation: '/pɔːrt/',
    exampleSentence: 'The ship arrived at the port early in the morning.',
    exampleTranslationJa: '船は早朝に港に到着した。',
    collocations: ['a fishing port', 'leave port'],
    relatedWords: ['harbor', 'airport', 'dock'],
  },
  {
    id: 'portion',
    word: 'portion',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['部分', '(食事の)一人前、一盛り'],
    pronunciation: '/ˈpɔːrʃn/',
    exampleSentence: 'The restaurant serves large portions of pasta.',
    exampleTranslationJa: 'そのレストランはパスタを大盛りで出してくれる。',
    collocations: ['a large portion', 'a portion of the profits'],
    relatedWords: ['part', 'proportion', 'share'],
  },
  {
    id: 'portrait',
    word: 'portrait',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['肖像画、ポートレート', '(人物・時代の)描写'],
    pronunciation: '/ˈpɔːrtrət/',
    exampleSentence: 'A famous portrait of the queen hangs in the museum.',
    exampleTranslationJa: '美術館には女王の有名な肖像画が掛かっている。',
    collocations: ['paint a portrait', 'a family portrait'],
    relatedWords: ['painting', 'photograph', 'portray'],
  },
  {
    id: 'position',
    word: 'position',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['位置', '立場、状況', '職、地位'],
    pronunciation: '/pəˈzɪʃn/',
    exampleSentence: 'The company offered her a senior position in the sales team.',
    exampleTranslationJa: 'その会社は彼女に営業チームの上級職を打診した。',
    collocations: ['apply for a position', 'in a difficult position'],
    relatedWords: ['location', 'post', 'situation'],
  },
  {
    id: 'positive',
    word: 'positive',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['前向きな、肯定的な', '確信して', '(検査結果が)陽性の'],
    pronunciation: '/ˈpɑːzətɪv/',
    exampleSentence: 'Try to keep a positive attitude even in hard times.',
    exampleTranslationJa: 'つらい時でも前向きな姿勢を保つようにしよう。',
    collocations: ['a positive attitude', 'positive feedback', 'test positive'],
    relatedWords: ['negative', 'optimistic', 'positively'],
  },
  {
    id: 'possess',
    word: 'possess',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['所有する', '(能力・性質を)持つ'],
    pronunciation: '/pəˈzes/',
    exampleSentence: 'He possesses a rare talent for languages.',
    exampleTranslationJa: '彼は語学のまれな才能を持っている。',
    collocations: ['possess a skill', 'possess a weapon'],
    relatedWords: ['possession', 'own', 'belong'],
  },
  {
    id: 'possession',
    word: 'possession',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['所有', '(複数形で)所有物、財産'],
    pronunciation: '/pəˈzeʃn/',
    exampleSentence: 'She lost all her possessions in the fire.',
    exampleTranslationJa: '彼女は火事で全財産を失った。',
    collocations: ['personal possessions', 'in possession of'],
    wordFormation: 'possess(所有する)+ -ion(名詞化)。',
    relatedWords: ['possess', 'property', 'belongings'],
  },
  {
    id: 'possibility',
    word: 'possibility',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['可能性', '(複数形で)見込み、選択肢'],
    pronunciation: '/ˌpɑːsəˈbɪləti/',
    exampleSentence: 'There is a possibility of rain this weekend.',
    exampleTranslationJa: '今週末は雨の可能性がある。',
    collocations: ['a strong possibility', 'rule out the possibility'],
    wordFormation: 'possible(可能な)+ -ity(名詞化)。',
    relatedWords: ['possible', 'chance', 'probability'],
  },
  {
    id: 'potential',
    word: 'potential',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['潜在的な、可能性のある', '(名詞)潜在能力、可能性'],
    pronunciation: '/pəˈtenʃl/',
    exampleSentence: 'The new market has huge potential for growth.',
    exampleTranslationJa: 'その新しい市場には大きな成長の可能性がある。',
    collocations: ['potential customers', 'reach your full potential'],
    relatedWords: ['potentially', 'possibility', 'capacity'],
  },
  {
    id: 'pour',
    word: 'pour',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['注ぐ', '(雨が)激しく降る', '大量に流れ込む'],
    pronunciation: '/pɔːr/',
    exampleSentence: 'She poured hot tea into my cup.',
    exampleTranslationJa: '彼女は私のカップに熱いお茶を注いでくれた。',
    collocations: ['pour a drink', 'pouring rain'],
    relatedWords: ['spill', 'flow', 'fill'],
  },
  {
    id: 'poverty',
    word: 'poverty',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['貧困'],
    pronunciation: '/ˈpɑːvərti/',
    exampleSentence: 'Millions of people around the world live in poverty.',
    exampleTranslationJa: '世界中で何百万人もの人々が貧困の中で暮らしている。',
    collocations: ['live in poverty', 'reduce poverty', 'the poverty line'],
    relatedWords: ['poor', 'wealth', 'hunger'],
  },
  {
    id: 'powerful',
    word: 'powerful',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['強力な、力のある', '(影響力が)強い'],
    pronunciation: '/ˈpaʊərfl/',
    exampleSentence: 'The president is one of the most powerful people in the world.',
    exampleTranslationJa: '大統領は世界で最も力のある人物の一人だ。',
    collocations: ['a powerful engine', 'a powerful influence'],
    wordFormation: 'power(力)+ -ful(〜に満ちた)。',
    relatedWords: ['power', 'strong', 'influential'],
  },
  {
    id: 'practical',
    word: 'practical',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['実用的な', '現実的な', '実践的な'],
    pronunciation: '/ˈpræktɪkl/',
    exampleSentence: 'This book gives practical advice for new parents.',
    exampleTranslationJa: 'この本は新米の親向けに実用的なアドバイスを与えてくれる。',
    collocations: ['practical advice', 'practical experience'],
    relatedWords: ['practice', 'practically', 'useful'],
  },
  {
    id: 'praise',
    word: 'praise',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['ほめる、称賛する', '(名詞)称賛'],
    pronunciation: '/preɪz/',
    exampleSentence: 'The teacher praised the students for their hard work.',
    exampleTranslationJa: '先生は生徒たちの努力をほめた。',
    collocations: ['praise someone for', 'receive high praise'],
    relatedWords: ['compliment', 'admire', 'criticism'],
  },
  {
    id: 'pray',
    word: 'pray',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['祈る'],
    pronunciation: '/preɪ/',
    exampleSentence: 'They prayed for peace in the world.',
    exampleTranslationJa: '彼らは世界の平和を祈った。',
    collocations: ['pray for peace', 'pray to God'],
    relatedWords: ['prayer', 'wish', 'hope'],
  },
  {
    id: 'precious',
    word: 'precious',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['貴重な、大切な', '高価な、希少な'],
    pronunciation: '/ˈpreʃəs/',
    exampleSentence: 'Time with family is precious to me.',
    exampleTranslationJa: '家族と過ごす時間は私にとってかけがえのないものだ。',
    collocations: ['precious time', 'precious memories', 'precious metals'],
    relatedWords: ['valuable', 'priceless', 'treasure'],
  },
  {
    id: 'precise',
    word: 'precise',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['正確な、精密な', 'まさにその'],
    pronunciation: '/prɪˈsaɪs/',
    exampleSentence: 'We need precise measurements before we cut the wood.',
    exampleTranslationJa: '木材を切る前に正確な寸法が必要だ。',
    collocations: ['precise measurements', 'to be precise'],
    relatedWords: ['precisely', 'precision', 'accurate'],
  },
  {
    id: 'predict',
    word: 'predict',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['予測する、予言する'],
    pronunciation: '/prɪˈdɪkt/',
    exampleSentence: 'Scientists cannot predict exactly when an earthquake will happen.',
    exampleTranslationJa: '科学者は地震がいつ起こるかを正確には予測できない。',
    collocations: ['predict the future', 'hard to predict'],
    wordFormation: 'pre-(前もって)+ dict(言う)。dict は dictionary, dictate と同語源。',
    relatedWords: ['prediction', 'forecast', 'expect'],
  },
  {
    id: 'prediction',
    word: 'prediction',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['予測、予言'],
    pronunciation: '/prɪˈdɪkʃn/',
    exampleSentence: 'His prediction about the election result was correct.',
    exampleTranslationJa: '選挙結果についての彼の予測は正しかった。',
    collocations: ['make a prediction', 'an accurate prediction'],
    wordFormation: 'predict(予測する)+ -ion(名詞化)。',
    relatedWords: ['predict', 'forecast', 'estimate'],
  },
  {
    id: 'prefer',
    word: 'prefer',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['〜のほうを好む'],
    pronunciation: '/prɪˈfɜːr/',
    exampleSentence: 'I prefer tea to coffee in the morning.',
    exampleTranslationJa: '朝はコーヒーより紅茶のほうが好きだ。',
    collocations: ['prefer A to B', 'would prefer to do'],
    relatedWords: ['preference', 'favorite', 'rather'],
  },
  {
    id: 'pregnant',
    word: 'pregnant',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['妊娠している'],
    pronunciation: '/ˈpreɡnənt/',
    exampleSentence: 'My sister is pregnant with her second child.',
    exampleTranslationJa: '姉は二人目の子を妊娠している。',
    collocations: ['get pregnant', 'six months pregnant'],
    relatedWords: ['pregnancy', 'birth', 'baby'],
  },
  {
    id: 'preparation',
    word: 'preparation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['準備、用意'],
    pronunciation: '/ˌprepəˈreɪʃn/',
    exampleSentence: 'Good preparation is the key to passing the exam.',
    exampleTranslationJa: '十分な準備が試験合格の鍵だ。',
    collocations: ['in preparation for', 'make preparations'],
    wordFormation: 'prepare(準備する)+ -ation(名詞化)。',
    relatedWords: ['prepare', 'plan', 'arrangement'],
  },
  {
    id: 'presence',
    word: 'presence',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['存在、居合わせること', '存在感'],
    pronunciation: '/ˈprezns/',
    exampleSentence: 'Her presence at the meeting surprised everyone.',
    exampleTranslationJa: '彼女が会議に姿を見せたことに、みんなが驚いた。',
    collocations: ['in the presence of', 'a strong presence'],
    wordFormation: 'present(その場にいる)+ -ence(名詞化)。反意語は absence。',
    relatedWords: ['present', 'absence', 'attendance'],
  },
  {
    id: 'present',
    word: 'present',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['提示する、発表する', '贈呈する', '(形容詞)出席している、現在の', '(名詞)贈り物、現在'],
    pronunciation: '/prɪˈzent/',
    exampleSentence: 'The manager presented the report to the board.',
    exampleTranslationJa: '部長は役員会に報告書を提出した。',
    collocations: ['present a report', 'be present at', 'at present'],
    mnemonic: '動詞は後ろにアクセント(preSENT)、名詞・形容詞は前(PREsent)と覚える。',
    relatedWords: ['presentation', 'presence', 'gift'],
  },
  {
    id: 'preserve',
    word: 'preserve',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['保存する、保護する', '(状態を)維持する'],
    pronunciation: '/prɪˈzɜːrv/',
    exampleSentence: 'We must preserve the forest for future generations.',
    exampleTranslationJa: '私たちは将来の世代のために森を守らなければならない。',
    collocations: ['preserve the environment', 'well preserved'],
    wordFormation: 'pre-(前もって)+ serve(保つ)。serve は conserve, reserve と同語源。',
    relatedWords: ['preservation', 'conserve', 'protect'],
  },
  {
    id: 'pressure',
    word: 'pressure',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['圧力', '精神的圧迫、プレッシャー'],
    pronunciation: '/ˈpreʃər/',
    exampleSentence: 'He is under a lot of pressure at work these days.',
    exampleTranslationJa: '彼は最近、仕事で大きなプレッシャーを受けている。',
    collocations: ['under pressure', 'blood pressure', 'put pressure on'],
    wordFormation: 'press(押す)+ -ure(名詞化)。',
    relatedWords: ['press', 'stress', 'tension'],
  },
  {
    id: 'pretend',
    word: 'pretend',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['〜のふりをする'],
    pronunciation: '/prɪˈtend/',
    exampleSentence: 'The children pretended to be pirates on a ship.',
    exampleTranslationJa: '子どもたちは船に乗った海賊のふりをして遊んだ。',
    collocations: ['pretend to be', 'pretend that'],
    relatedWords: ['imagine', 'fake', 'act'],
  },
  {
    id: 'prevent',
    word: 'prevent',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['防ぐ、妨げる'],
    pronunciation: '/prɪˈvent/',
    exampleSentence: 'Washing your hands helps prevent the spread of disease.',
    exampleTranslationJa: '手を洗うことは病気の拡大を防ぐのに役立つ。',
    collocations: ['prevent an accident', 'prevent someone from doing'],
    wordFormation: 'pre-(前もって)+ vent(来る)。「先回りして止める」イメージ。',
    relatedWords: ['prevention', 'avoid', 'protect'],
  },
  {
    id: 'previous',
    word: 'previous',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['前の、以前の'],
    pronunciation: '/ˈpriːviəs/',
    exampleSentence: 'She has previous experience in customer service.',
    exampleTranslationJa: '彼女には接客の経験がある。',
    collocations: ['the previous day', 'previous experience'],
    relatedWords: ['previously', 'former', 'prior'],
  },
  {
    id: 'previously',
    word: 'previously',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['以前に、前もって'],
    pronunciation: '/ˈpriːviəsli/',
    exampleSentence: 'He previously worked as a teacher in Osaka.',
    exampleTranslationJa: '彼は以前、大阪で教師として働いていた。',
    collocations: ['as previously mentioned', 'previously unknown'],
    wordFormation: 'previous(以前の)+ -ly(副詞化)。',
    relatedWords: ['previous', 'before', 'formerly'],
  },
  {
    id: 'priest',
    word: 'priest',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['司祭、聖職者'],
    pronunciation: '/priːst/',
    exampleSentence: 'The priest gave a short speech at the wedding.',
    exampleTranslationJa: '司祭は結婚式で短いスピーチをした。',
    collocations: ['a Catholic priest', 'become a priest'],
    relatedWords: ['church', 'religion', 'monk'],
  },
  {
    id: 'primary',
    word: 'primary',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['主要な、第一の', '初等の'],
    pronunciation: '/ˈpraɪmeri/',
    exampleSentence: 'Safety is our primary concern at this factory.',
    exampleTranslationJa: 'この工場では安全が最優先事項だ。',
    collocations: ['the primary reason', 'primary school'],
    relatedWords: ['prime', 'primarily', 'secondary'],
  },
  {
    id: 'prime',
    word: 'prime',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['最も重要な、主要な', '最良の', '(名詞)全盛期'],
    pronunciation: '/praɪm/',
    exampleSentence: 'The prime minister will visit China next month.',
    exampleTranslationJa: '首相は来月中国を訪問する。',
    collocations: ['the prime minister', 'a prime example', 'in your prime'],
    relatedWords: ['primary', 'chief', 'main'],
  },
  {
    id: 'principle',
    word: 'principle',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['原則、原理', '主義、信条'],
    pronunciation: '/ˈprɪnsəpl/',
    exampleSentence: 'She refused to lie because it was against her principles.',
    exampleTranslationJa: '彼女は自分の信条に反するため、嘘をつくことを拒んだ。',
    collocations: ['in principle', 'basic principles', 'a matter of principle'],
    mnemonic: '同音の principal(校長・主要な)と混同しやすい。-le で終わるほうが rule(原則)と覚える。',
    relatedWords: ['principal', 'rule', 'theory'],
  },
  {
    id: 'priority',
    word: 'priority',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['優先事項', '優先'],
    pronunciation: '/praɪˈɔːrəti/',
    exampleSentence: 'Finishing the report is my top priority today.',
    exampleTranslationJa: '報告書を仕上げることが今日の最優先事項だ。',
    collocations: ['top priority', 'give priority to'],
    wordFormation: 'prior(先の)+ -ity(名詞化)。',
    relatedWords: ['prior', 'prioritize', 'preference'],
  },
  {
    id: 'prison',
    word: 'prison',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['刑務所'],
    pronunciation: '/ˈprɪzn/',
    exampleSentence: 'He spent five years in prison for robbery.',
    exampleTranslationJa: '彼は強盗の罪で5年間刑務所に入っていた。',
    collocations: ['go to prison', 'be sent to prison'],
    relatedWords: ['prisoner', 'jail', 'sentence'],
  },
  {
    id: 'prisoner',
    word: 'prisoner',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['囚人、捕虜'],
    pronunciation: '/ˈprɪznər/',
    exampleSentence: 'The prisoners are allowed to exercise for one hour a day.',
    exampleTranslationJa: '囚人たちは1日1時間の運動を許されている。',
    collocations: ['a political prisoner', 'take someone prisoner'],
    wordFormation: 'prison(刑務所)+ -er(人)。',
    relatedWords: ['prison', 'captive', 'guard'],
  },
  {
    id: 'privacy',
    word: 'privacy',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['プライバシー、私生活'],
    pronunciation: '/ˈpraɪvəsi/',
    exampleSentence: 'Everyone has the right to protect their privacy.',
    exampleTranslationJa: '誰にでも自分のプライバシーを守る権利がある。',
    collocations: ['protect your privacy', 'an invasion of privacy'],
    wordFormation: 'private(私的な)+ -acy(名詞化)。',
    relatedWords: ['private', 'personal', 'confidential'],
  },
  {
    id: 'private',
    word: 'private',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['私的な、個人の', '民間の、私立の', '人目につかない'],
    pronunciation: '/ˈpraɪvət/',
    exampleSentence: 'This is my private email address, so please do not share it.',
    exampleTranslationJa: 'これは私の個人用メールアドレスなので、共有しないでください。',
    collocations: ['a private school', 'in private', 'private life'],
    relatedWords: ['privacy', 'personal', 'public'],
  },
  {
    id: 'procedure',
    word: 'procedure',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['手順、手続き', '(医療の)処置'],
    pronunciation: '/prəˈsiːdʒər/',
    exampleSentence: 'Please follow the safety procedures at all times.',
    exampleTranslationJa: '常に安全手順に従ってください。',
    collocations: ['follow a procedure', 'standard procedure', 'a medical procedure'],
    wordFormation: 'proceed(進む)+ -ure(名詞化)。',
    relatedWords: ['proceed', 'process', 'method'],
  },
  {
    id: 'proceed',
    word: 'proceed',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['続行する、進む', '(proceed to do で)続けて〜する'],
    pronunciation: '/prəˈsiːd/',
    exampleSentence: 'After a short break, we proceeded with the meeting.',
    exampleTranslationJa: '短い休憩のあと、私たちは会議を再開した。',
    collocations: ['proceed with a plan', 'proceed to the gate'],
    wordFormation: 'pro-(前へ)+ ceed(行く)。ceed は succeed, exceed と同語源。',
    relatedWords: ['procedure', 'process', 'continue'],
  },
  {
    id: 'process',
    word: 'process',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['過程、プロセス', '製法、工程', '(動詞)処理する'],
    pronunciation: '/ˈprɑːses/',
    exampleSentence: 'Learning a language is a long process that takes years.',
    exampleTranslationJa: '言語の習得は何年もかかる長い過程だ。',
    collocations: ['a slow process', 'in the process of', 'process data'],
    relatedWords: ['procedure', 'progress', 'step'],
  },
  {
    id: 'produce',
    word: 'produce',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['生産する、製造する', '(結果を)生み出す', '(名詞)農産物'],
    pronunciation: '/prəˈduːs/',
    exampleSentence: 'The factory produces about five hundred cars a day.',
    exampleTranslationJa: 'その工場は1日に約500台の車を生産している。',
    collocations: ['produce goods', 'produce results', 'fresh produce'],
    wordFormation: 'pro-(前へ)+ duce(導く)。duce は introduce, reduce と同語源。',
    relatedWords: ['product', 'production', 'producer'],
  },
  {
    id: 'production',
    word: 'production',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['生産、製造', '(映画・番組などの)制作'],
    pronunciation: '/prəˈdʌkʃn/',
    exampleSentence: 'Car production has increased by ten percent this year.',
    exampleTranslationJa: '自動車の生産は今年10パーセント増加した。',
    collocations: ['mass production', 'production costs'],
    wordFormation: 'produce(生産する)+ -tion(名詞化)。',
    relatedWords: ['produce', 'product', 'manufacturing'],
  },
  {
    id: 'profession',
    word: 'profession',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['職業(専門職)'],
    pronunciation: '/prəˈfeʃn/',
    exampleSentence: 'She chose teaching as her profession.',
    exampleTranslationJa: '彼女は職業として教師を選んだ。',
    collocations: ['the medical profession', 'by profession'],
    relatedWords: ['professional', 'career', 'occupation'],
  },
  {
    id: 'professional',
    word: 'professional',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['職業の、プロの', '専門的な', '(名詞)専門家、プロ'],
    pronunciation: '/prəˈfeʃənl/',
    exampleSentence: 'You should get professional advice before you invest.',
    exampleTranslationJa: '投資する前に専門家の助言を受けるべきだ。',
    collocations: ['professional advice', 'a professional athlete'],
    wordFormation: 'profession(職業)+ -al(形容詞化)。',
    relatedWords: ['profession', 'expert', 'amateur'],
  },
  {
    id: 'profit',
    word: 'profit',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['利益', '(動詞)利益を得る'],
    pronunciation: '/ˈprɑːfɪt/',
    exampleSentence: 'The company made a large profit last year.',
    exampleTranslationJa: 'その会社は昨年大きな利益を上げた。',
    collocations: ['make a profit', 'profit and loss'],
    relatedWords: ['profitable', 'benefit', 'loss'],
  },
  {
    id: 'progress',
    word: 'progress',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['進歩、前進', '(動詞)進歩する'],
    pronunciation: '/ˈprɑːɡres/',
    exampleSentence: 'She has made great progress in English this year.',
    exampleTranslationJa: '彼女は今年、英語が大きく上達した。',
    collocations: ['make progress', 'in progress'],
    wordFormation: 'pro-(前へ)+ gress(歩む)。',
    relatedWords: ['progressive', 'advance', 'improvement'],
  },
  {
    id: 'prohibit',
    word: 'prohibit',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['禁止する'],
    pronunciation: '/proʊˈhɪbɪt/',
    exampleSentence: 'Smoking is prohibited in all public buildings.',
    exampleTranslationJa: 'すべての公共の建物内で喫煙は禁止されている。',
    collocations: ['strictly prohibited', 'prohibit someone from doing'],
    relatedWords: ['ban', 'forbid', 'prohibition'],
  },
  {
    id: 'project',
    word: 'project',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['計画、プロジェクト', '(学校の)課題研究', '(動詞)予測する、映し出す'],
    pronunciation: '/ˈprɑːdʒekt/',
    exampleSentence: 'Our team is working on a new project for the city.',
    exampleTranslationJa: '私たちのチームは市のための新しいプロジェクトに取り組んでいる。',
    collocations: ['work on a project', 'a research project'],
    relatedWords: ['plan', 'program', 'task'],
  },
  {
    id: 'promote',
    word: 'promote',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['促進する', '宣伝する', '昇進させる'],
    pronunciation: '/prəˈmoʊt/',
    exampleSentence: 'The campaign aims to promote healthy eating among children.',
    exampleTranslationJa: 'そのキャンペーンは子どもたちの健康的な食生活を促進することを目指している。',
    collocations: ['promote growth', 'be promoted to manager'],
    wordFormation: 'pro-(前へ)+ mote(動かす)。mote は motion, motor と同語源。',
    relatedWords: ['promotion', 'advertise', 'encourage'],
  },
  {
    id: 'promotion',
    word: 'promotion',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['昇進', '販売促進、宣伝'],
    pronunciation: '/prəˈmoʊʃn/',
    exampleSentence: 'She got a promotion after three years of hard work.',
    exampleTranslationJa: '彼女は3年間の努力の末に昇進した。',
    collocations: ['get a promotion', 'a sales promotion'],
    wordFormation: 'promote(昇進させる)+ -ion(名詞化)。',
    relatedWords: ['promote', 'advancement', 'marketing'],
  },
  {
    id: 'prompt',
    word: 'prompt',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['迅速な', '(動詞)促す、引き起こす'],
    pronunciation: '/prɑːmpt/',
    exampleSentence: 'Thank you for your prompt reply to my email.',
    exampleTranslationJa: 'メールへの迅速なご返信ありがとうございます。',
    collocations: ['a prompt reply', 'prompt action', 'prompt someone to do'],
    relatedWords: ['promptly', 'immediate', 'quick'],
  },
  {
    id: 'proof',
    word: 'proof',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['証拠、証明'],
    pronunciation: '/pruːf/',
    exampleSentence: 'Do you have any proof that he took the money?',
    exampleTranslationJa: '彼がお金を取ったという証拠はあるのですか。',
    collocations: ['proof of identity', 'clear proof'],
    relatedWords: ['prove', 'evidence', 'confirmation'],
  },
  {
    id: 'proper',
    word: 'proper',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['適切な、正しい', 'きちんとした'],
    pronunciation: '/ˈprɑːpər/',
    exampleSentence: 'You need proper shoes for hiking in the mountains.',
    exampleTranslationJa: '山でハイキングをするにはちゃんとした靴が必要だ。',
    collocations: ['proper training', 'the proper way'],
    relatedWords: ['properly', 'appropriate', 'correct'],
  },
  {
    id: 'properly',
    word: 'properly',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['適切に、きちんと'],
    pronunciation: '/ˈprɑːpərli/',
    exampleSentence: 'Make sure the door is properly locked before you leave.',
    exampleTranslationJa: '出かける前にドアがきちんと施錠されているか確認しなさい。',
    collocations: ['work properly', 'properly trained'],
    wordFormation: 'proper(適切な)+ -ly(副詞化)。',
    relatedWords: ['proper', 'correctly', 'appropriately'],
  },
  {
    id: 'property',
    word: 'property',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['財産、所有物', '不動産、物件', '(物質の)特性'],
    pronunciation: '/ˈprɑːpərti/',
    exampleSentence: 'The house is private property, so you cannot enter without permission.',
    exampleTranslationJa: 'その家は私有地なので、許可なく入ることはできない。',
    collocations: ['private property', 'buy a property', 'the properties of water'],
    relatedWords: ['possession', 'estate', 'asset'],
  },
  {
    id: 'proportion',
    word: 'proportion',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['割合、比率', '釣り合い、バランス'],
    pronunciation: '/prəˈpɔːrʃn/',
    exampleSentence: 'A large proportion of students walk to school.',
    exampleTranslationJa: '生徒の大部分は歩いて通学している。',
    collocations: ['a high proportion of', 'in proportion to'],
    relatedWords: ['ratio', 'percentage', 'portion'],
  },
  {
    id: 'proposal',
    word: 'proposal',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['提案', '結婚の申し込み、プロポーズ'],
    pronunciation: '/prəˈpoʊzl/',
    exampleSentence: 'The committee rejected the proposal to build a new stadium.',
    exampleTranslationJa: '委員会は新しいスタジアムを建設するという提案を却下した。',
    collocations: ['make a proposal', 'accept a proposal'],
    wordFormation: 'propose(提案する)+ -al(名詞化)。',
    relatedWords: ['propose', 'suggestion', 'offer'],
  },
  {
    id: 'propose',
    word: 'propose',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['提案する', '結婚を申し込む'],
    pronunciation: '/prəˈpoʊz/',
    exampleSentence: 'The mayor proposed a new plan to reduce traffic.',
    exampleTranslationJa: '市長は交通量を減らす新しい計画を提案した。',
    collocations: ['propose a plan', 'propose to someone'],
    wordFormation: 'pro-(前へ)+ pose(置く)。pose は suppose, purpose と同語源。',
    relatedWords: ['proposal', 'suggest', 'offer'],
  },
  {
    id: 'prospect',
    word: 'prospect',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['見込み、可能性', '(複数形で)将来性'],
    pronunciation: '/ˈprɑːspekt/',
    exampleSentence: 'The prospect of working abroad excites me.',
    exampleTranslationJa: '海外で働けるかもしれないと思うとわくわくする。',
    collocations: ['the prospect of', 'job prospects'],
    wordFormation: 'pro-(前を)+ spect(見る)。spect は inspect, respect と同語源。',
    relatedWords: ['prospective', 'possibility', 'outlook'],
  },
  {
    id: 'protect',
    word: 'protect',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['守る、保護する'],
    pronunciation: '/prəˈtekt/',
    exampleSentence: 'Sunscreen protects your skin from the sun.',
    exampleTranslationJa: '日焼け止めは肌を日差しから守る。',
    collocations: ['protect the environment', 'protect A from B'],
    relatedWords: ['protection', 'defend', 'guard'],
  },
  {
    id: 'protection',
    word: 'protection',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['保護'],
    pronunciation: '/prəˈtekʃn/',
    exampleSentence: 'This cream gives good protection against the sun.',
    exampleTranslationJa: 'このクリームは日差しからしっかり肌を守ってくれる。',
    collocations: ['environmental protection', 'protection against'],
    wordFormation: 'protect(守る)+ -ion(名詞化)。',
    relatedWords: ['protect', 'protective', 'security'],
  },
  {
    id: 'protest',
    word: 'protest',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['抗議、デモ', '(動詞)抗議する'],
    pronunciation: '/ˈproʊtest/',
    exampleSentence: 'Thousands of people joined the protest against the new law.',
    exampleTranslationJa: '何千人もの人々が新しい法律への抗議デモに参加した。',
    collocations: ['a protest against', 'in protest', 'a protest march'],
    relatedWords: ['demonstration', 'object', 'complain'],
  },
  {
    id: 'prove',
    word: 'prove',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['証明する', '(prove to be で)〜だと判明する'],
    pronunciation: '/pruːv/',
    exampleSentence: 'The evidence proved that he was innocent.',
    exampleTranslationJa: 'その証拠は彼が無実であることを証明した。',
    collocations: ['prove a point', 'prove to be difficult'],
    relatedWords: ['proof', 'demonstrate', 'confirm'],
  },
  {
    id: 'provide',
    word: 'provide',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['提供する、供給する'],
    pronunciation: '/prəˈvaɪd/',
    exampleSentence: 'The hotel provides free breakfast for all guests.',
    exampleTranslationJa: 'そのホテルは全宿泊客に無料の朝食を提供している。',
    collocations: ['provide A with B', 'provide information'],
    wordFormation: 'pro-(前もって)+ vide(見る)。「先を見て備える」が原義。',
    relatedWords: ['provider', 'supply', 'offer'],
  },
  {
    id: 'psychology',
    word: 'psychology',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['心理学', '心理'],
    pronunciation: '/saɪˈkɑːlədʒi/',
    exampleSentence: 'She is studying psychology to understand human behavior.',
    exampleTranslationJa: '彼女は人間の行動を理解するために心理学を学んでいる。',
    collocations: ['study psychology', 'child psychology'],
    relatedWords: ['psychologist', 'psychological', 'mental'],
  },
  {
    id: 'publish',
    word: 'publish',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['出版する、掲載する', '公表する'],
    pronunciation: '/ˈpʌblɪʃ/',
    exampleSentence: 'Her first novel was published last spring.',
    exampleTranslationJa: '彼女の最初の小説は昨春出版された。',
    collocations: ['publish a book', 'publish the results'],
    relatedWords: ['publisher', 'publication', 'print'],
  },
  {
    id: 'punish',
    word: 'punish',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['罰する'],
    pronunciation: '/ˈpʌnɪʃ/',
    exampleSentence: 'The school punished the students for cheating on the test.',
    exampleTranslationJa: '学校は試験で不正をした生徒たちを罰した。',
    collocations: ['punish someone for', 'be severely punished'],
    relatedWords: ['punishment', 'penalty', 'discipline'],
  },
  {
    id: 'punishment',
    word: 'punishment',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['罰、処罰'],
    pronunciation: '/ˈpʌnɪʃmənt/',
    exampleSentence: 'He had to clean the classroom as a punishment.',
    exampleTranslationJa: '彼は罰として教室を掃除しなければならなかった。',
    collocations: ['severe punishment', 'as a punishment'],
    wordFormation: 'punish(罰する)+ -ment(名詞化)。',
    relatedWords: ['punish', 'penalty', 'sentence'],
  },
  {
    id: 'purchase',
    word: 'purchase',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['購入する', '(名詞)購入、購入品'],
    pronunciation: '/ˈpɜːrtʃəs/',
    exampleSentence: 'You can purchase tickets online or at the station.',
    exampleTranslationJa: 'チケットはオンラインでも駅でも購入できます。',
    collocations: ['purchase a ticket', 'make a purchase'],
    mnemonic: 'buy のフォーマルな言い換え。ビジネス文書や案内表示でよく使われる。',
    relatedWords: ['buy', 'purchaser', 'sale'],
  },
  {
    id: 'pure',
    word: 'pure',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['純粋な、混じり気のない', 'まったくの'],
    pronunciation: '/pjʊr/',
    exampleSentence: 'This sweater is made of pure wool.',
    exampleTranslationJa: 'このセーターは純毛でできている。',
    collocations: ['pure gold', 'pure water', 'by pure chance'],
    relatedWords: ['purely', 'purity', 'clean'],
  },
  {
    id: 'purpose',
    word: 'purpose',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['目的', '(on purpose で)わざと'],
    pronunciation: '/ˈpɜːrpəs/',
    exampleSentence: "The purpose of this meeting is to plan next year's budget.",
    exampleTranslationJa: 'この会議の目的は来年度の予算を立てることだ。',
    collocations: ['the main purpose', 'on purpose', 'serve a purpose'],
    relatedWords: ['aim', 'goal', 'intention'],
  },
  {
    id: 'pursue',
    word: 'pursue',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['追求する', '(仕事・研究などを)続ける', '追跡する'],
    pronunciation: '/pərˈsuː/',
    exampleSentence: 'She moved to Tokyo to pursue her dream of becoming an actress.',
    exampleTranslationJa: '彼女は女優になる夢を追いかけて東京に引っ越した。',
    collocations: ['pursue a career', 'pursue a goal'],
    relatedWords: ['pursuit', 'chase', 'seek'],
  },
  {
    id: 'put off',
    word: 'put off',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['延期する', '(人を)不快にさせる、やる気をなくさせる'],
    pronunciation: '/ˌpʊt ˈɔːf/',
    exampleSentence: 'We had to put off the picnic because of the rain.',
    exampleTranslationJa: '雨のため、ピクニックを延期しなければならなかった。',
    collocations: ['put off a meeting', 'put off doing'],
    relatedWords: ['postpone', 'delay', 'cancel'],
  },
  {
    id: 'put up with',
    word: 'put up with',
    level: 'B2',
    partOfSpeech: '句動詞',
    meaningsJa: ['我慢する'],
    pronunciation: '/pʊt ˈʌp wɪð/',
    exampleSentence: "I can't put up with this noise any longer.",
    exampleTranslationJa: 'この騒音にはもうこれ以上我慢できない。',
    collocations: ['put up with the noise', 'put up with bad behavior'],
    relatedWords: ['tolerate', 'bear', 'stand'],
  },
  {
    id: 'qualification',
    word: 'qualification',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['資格、資格証明', '(必要な)能力・条件'],
    pronunciation: '/ˌkwɑːlɪfɪˈkeɪʃn/',
    exampleSentence: 'You need a teaching qualification to work at this school.',
    exampleTranslationJa: 'この学校で働くには教員資格が必要だ。',
    collocations: ['academic qualifications', 'have the right qualifications'],
    wordFormation: 'qualify(資格を得る)+ -ation(名詞化)。',
    relatedWords: ['qualify', 'qualified', 'certificate'],
  },
  {
    id: 'qualify',
    word: 'qualify',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['資格を得る、資格を与える', '(競技で)予選を通過する'],
    pronunciation: '/ˈkwɑːlɪfaɪ/',
    exampleSentence: 'She qualified as a doctor after six years of study.',
    exampleTranslationJa: '彼女は6年間の勉強を経て医師の資格を取った。',
    collocations: ['qualify as a lawyer', 'qualify for the final'],
    relatedWords: ['qualification', 'qualified', 'eligible'],
  },
  {
    id: 'quality',
    word: 'quality',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['質、品質', '(人の)資質、特性'],
    pronunciation: '/ˈkwɑːləti/',
    exampleSentence: 'This store sells clothes of very high quality.',
    exampleTranslationJa: 'この店はとても品質の高い服を売っている。',
    collocations: ['high quality', 'quality of life', 'leadership qualities'],
    relatedWords: ['quantity', 'standard', 'value'],
  },
  {
    id: 'quantity',
    word: 'quantity',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['量、数量'],
    pronunciation: '/ˈkwɑːntəti/',
    exampleSentence: 'The recipe needs a small quantity of salt.',
    exampleTranslationJa: 'そのレシピには少量の塩が必要だ。',
    collocations: ['a large quantity of', 'in large quantities'],
    relatedWords: ['quality', 'amount', 'number'],
  },
  {
    id: 'quit',
    word: 'quit',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(仕事などを)辞める', '(習慣などを)やめる'],
    pronunciation: '/kwɪt/',
    exampleSentence: 'He quit his job to start his own business.',
    exampleTranslationJa: '彼は自分の事業を始めるために仕事を辞めた。',
    collocations: ['quit a job', 'quit smoking'],
    relatedWords: ['resign', 'give up', 'stop'],
  },
  {
    id: 'quote',
    word: 'quote',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['引用する', '(名詞)引用文', '(名詞)見積もり'],
    pronunciation: '/kwoʊt/',
    exampleSentence: 'She quoted a famous line from Shakespeare in her speech.',
    exampleTranslationJa: '彼女はスピーチでシェイクスピアの有名な一節を引用した。',
    collocations: ['quote from a book', 'get a quote'],
    relatedWords: ['quotation', 'cite', 'estimate'],
  },
  {
    id: 'racial',
    word: 'racial',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['人種の、人種的な'],
    pronunciation: '/ˈreɪʃl/',
    exampleSentence: 'The company works hard to prevent racial discrimination.',
    exampleTranslationJa: 'その会社は人種差別を防ぐために努力している。',
    collocations: ['racial discrimination', 'racial equality'],
    wordFormation: 'race(人種)+ -ial(形容詞化)。',
    relatedWords: ['race', 'ethnic', 'discrimination'],
  },
  {
    id: 'raise',
    word: 'raise',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['上げる、持ち上げる', '(資金を)集める', '育てる', '(問題を)提起する'],
    pronunciation: '/reɪz/',
    exampleSentence: 'Raise your hand if you have a question.',
    exampleTranslationJa: '質問がある人は手を挙げてください。',
    collocations: ['raise your hand', 'raise money', 'raise children'],
    mnemonic: 'raise は他動詞(〜を上げる)、rise は自動詞(上がる)と区別して覚える。',
    relatedWords: ['rise', 'lift', 'increase'],
  },
  {
    id: 'range',
    word: 'range',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['範囲、幅', '(商品の)品ぞろえ', '(動詞)範囲に及ぶ'],
    pronunciation: '/reɪndʒ/',
    exampleSentence: 'The store offers a wide range of products.',
    exampleTranslationJa: 'その店は幅広い商品を取りそろえている。',
    collocations: ['a wide range of', 'price range', 'range from A to B'],
    relatedWords: ['variety', 'scope', 'extent'],
  },
  {
    id: 'rapid',
    word: 'rapid',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['急速な、速い'],
    pronunciation: '/ˈræpɪd/',
    exampleSentence: 'The city has seen rapid growth over the past decade.',
    exampleTranslationJa: 'その都市はこの10年で急速な成長を遂げた。',
    collocations: ['rapid growth', 'rapid change'],
    relatedWords: ['rapidly', 'quick', 'swift'],
  },
  {
    id: 'rapidly',
    word: 'rapidly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['急速に'],
    pronunciation: '/ˈræpɪdli/',
    exampleSentence: 'Technology is changing rapidly in every industry.',
    exampleTranslationJa: 'あらゆる業界でテクノロジーは急速に変化している。',
    collocations: ['grow rapidly', 'rapidly increasing'],
    wordFormation: 'rapid(急速な)+ -ly(副詞化)。',
    relatedWords: ['rapid', 'quickly', 'fast'],
  },
  {
    id: 'rare',
    word: 'rare',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['まれな、珍しい', '(肉が)レアの'],
    pronunciation: '/rer/',
    exampleSentence: 'It is rare to see snow in this part of the country.',
    exampleTranslationJa: 'この地方で雪を見るのは珍しい。',
    collocations: ['a rare disease', 'in rare cases'],
    relatedWords: ['rarely', 'unusual', 'common'],
  },
  {
    id: 'rarely',
    word: 'rarely',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['めったに〜ない'],
    pronunciation: '/ˈrerli/',
    exampleSentence: 'She rarely eats out because she loves cooking.',
    exampleTranslationJa: '彼女は料理が大好きなので、めったに外食しない。',
    collocations: ['rarely seen', 'very rarely'],
    wordFormation: 'rare(まれな)+ -ly(副詞化)。',
    relatedWords: ['rare', 'seldom', 'hardly'],
  },
  {
    id: 'rate',
    word: 'rate',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['率、割合', '速度、ペース', '料金', '(動詞)評価する'],
    pronunciation: '/reɪt/',
    exampleSentence: 'The unemployment rate fell to three percent last month.',
    exampleTranslationJa: '先月、失業率は3パーセントまで下がった。',
    collocations: ['exchange rate', 'at this rate', 'success rate'],
    relatedWords: ['rating', 'ratio', 'percentage'],
  },
  {
    id: 'rather',
    word: 'rather',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['かなり、いくぶん', '(rather than で)〜よりむしろ', '(would rather で)〜するほうがよい'],
    pronunciation: '/ˈræðər/',
    exampleSentence: 'I would rather stay home than go out tonight.',
    exampleTranslationJa: '今夜は出かけるより家にいたい。',
    collocations: ['rather than', 'would rather', 'rather cold'],
    relatedWords: ['quite', 'fairly', 'instead'],
  },
  {
    id: 'raw',
    word: 'raw',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['生の、加工していない', '未処理の(データなど)'],
    pronunciation: '/rɔː/',
    exampleSentence: 'You should not eat raw chicken because it is dangerous.',
    exampleTranslationJa: '生の鶏肉は危険なので食べてはいけない。',
    collocations: ['raw materials', 'raw fish', 'raw data'],
    relatedWords: ['fresh', 'uncooked', 'natural'],
  },
  {
    id: 'react',
    word: 'react',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['反応する'],
    pronunciation: '/riˈækt/',
    exampleSentence: 'How did she react when she heard the news?',
    exampleTranslationJa: 'その知らせを聞いたとき、彼女はどんな反応をしましたか。',
    collocations: ['react to the news', 'react quickly'],
    wordFormation: 're-(返して)+ act(行動する)。',
    relatedWords: ['reaction', 'respond', 'act'],
  },
  {
    id: 'reaction',
    word: 'reaction',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['反応'],
    pronunciation: '/riˈækʃn/',
    exampleSentence: 'His first reaction to the plan was very negative.',
    exampleTranslationJa: 'その計画に対する彼の最初の反応はとても否定的だった。',
    collocations: ['a chemical reaction', 'an allergic reaction', 'a first reaction'],
    wordFormation: 'react(反応する)+ -ion(名詞化)。',
    relatedWords: ['react', 'response', 'reply'],
  },
  {
    id: 'realistic',
    word: 'realistic',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['現実的な', '写実的な、リアルな'],
    pronunciation: '/ˌriːəˈlɪstɪk/',
    exampleSentence: 'Set realistic goals that you can actually achieve.',
    exampleTranslationJa: '実際に達成できる現実的な目標を立てなさい。',
    collocations: ['a realistic goal', 'be realistic about'],
    wordFormation: 'real(現実の)+ -istic(形容詞化)。',
    relatedWords: ['reality', 'practical', 'unrealistic'],
  },
  {
    id: 'reality',
    word: 'reality',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['現実'],
    pronunciation: '/riˈæləti/',
    exampleSentence: 'In reality, learning a language takes years of practice.',
    exampleTranslationJa: '実際には、言語の習得には何年もの練習が必要だ。',
    collocations: ['in reality', 'become a reality', 'virtual reality'],
    wordFormation: 'real(現実の)+ -ity(名詞化)。',
    relatedWords: ['real', 'realistic', 'fact'],
  },
  {
    id: 'reasonable',
    word: 'reasonable',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['理にかなった、妥当な', '(値段が)手ごろな'],
    pronunciation: '/ˈriːznəbl/',
    exampleSentence: 'The restaurant serves good food at reasonable prices.',
    exampleTranslationJa: 'そのレストランは手ごろな値段でおいしい料理を出す。',
    collocations: ['a reasonable price', 'a reasonable explanation'],
    wordFormation: 'reason(理性・理由)+ -able(〜できる)。',
    relatedWords: ['reason', 'reasonably', 'fair'],
  },
  {
    id: 'recall',
    word: 'recall',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['思い出す', '(欠陥製品を)回収する'],
    pronunciation: '/rɪˈkɔːl/',
    exampleSentence: 'I cannot recall where I met him before.',
    exampleTranslationJa: '以前どこで彼に会ったのか思い出せない。',
    collocations: ['recall a name', 'recall a product'],
    wordFormation: 're-(再び)+ call(呼ぶ)。「記憶を呼び戻す」イメージ。',
    relatedWords: ['remember', 'remind', 'memory'],
  },
  {
    id: 'receipt',
    word: 'receipt',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['レシート、領収書', '受領'],
    pronunciation: '/rɪˈsiːt/',
    exampleSentence: 'Keep your receipt in case you want to return the item.',
    exampleTranslationJa: '商品を返品したくなったときのために、レシートを取っておきなさい。',
    collocations: ['keep the receipt', 'ask for a receipt'],
    relatedWords: ['receive', 'invoice', 'refund'],
  },
  {
    id: 'recent',
    word: 'recent',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['最近の'],
    pronunciation: '/ˈriːsnt/',
    exampleSentence: 'The most recent version of the app is much faster.',
    exampleTranslationJa: 'そのアプリの最新バージョンはずっと速い。',
    collocations: ['in recent years', 'a recent study'],
    relatedWords: ['recently', 'latest', 'current'],
  },
  {
    id: 'recently',
    word: 'recently',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['最近'],
    pronunciation: '/ˈriːsntli/',
    exampleSentence: 'I recently moved to a new apartment near the station.',
    exampleTranslationJa: '最近、駅の近くの新しいアパートに引っ越した。',
    collocations: ['until recently', 'only recently'],
    wordFormation: 'recent(最近の)+ -ly(副詞化)。',
    relatedWords: ['recent', 'lately', 'nowadays'],
  },
  {
    id: 'recognize',
    word: 'recognize',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(見て・聞いて)それとわかる、見分ける', '認める、承認する', '(功績を)評価する'],
    pronunciation: '/ˈrekəɡnaɪz/',
    exampleSentence: 'I did not recognize her because she had changed so much.',
    exampleTranslationJa: '彼女があまりに変わっていたので、誰だかわからなかった。',
    collocations: ['recognize a face', 'be widely recognized'],
    wordFormation: 're-(再び)+ cogn(知る)+ -ize(動詞化)。「再び知る=見覚えがある」。',
    relatedWords: ['recognition', 'identify', 'realize'],
  },
  {
    id: 'recommend',
    word: 'recommend',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['推薦する、勧める'],
    pronunciation: '/ˌrekəˈmend/',
    exampleSentence: 'Can you recommend a good restaurant near here?',
    exampleTranslationJa: 'この近くのおいしいレストランを教えてもらえますか。',
    collocations: ['highly recommend', 'recommend doing'],
    relatedWords: ['recommendation', 'suggest', 'advise'],
  },
  {
    id: 'recover',
    word: 'recover',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['回復する', '取り戻す'],
    pronunciation: '/rɪˈkʌvər/',
    exampleSentence: 'It took him two months to recover from the operation.',
    exampleTranslationJa: '彼が手術から回復するのに2か月かかった。',
    collocations: ['recover from illness', 'fully recover'],
    relatedWords: ['recovery', 'heal', 'get over'],
  },
  {
    id: 'recovery',
    word: 'recovery',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['回復', '(経済の)回復、復興'],
    pronunciation: '/rɪˈkʌvəri/',
    exampleSentence: 'The doctor said she made a quick recovery after surgery.',
    exampleTranslationJa: '医師によれば、彼女は手術後すみやかに回復した。',
    collocations: ['a full recovery', 'economic recovery'],
    wordFormation: 'recover(回復する)+ -y(名詞化)。',
    relatedWords: ['recover', 'improvement', 'healing'],
  },
  {
    id: 'reduce',
    word: 'reduce',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['減らす、下げる'],
    pronunciation: '/rɪˈduːs/',
    exampleSentence: 'We need to reduce the amount of plastic we use.',
    exampleTranslationJa: '私たちは使うプラスチックの量を減らす必要がある。',
    collocations: ['reduce costs', 'reduce the risk of'],
    wordFormation: 're-(後ろへ)+ duce(導く)。duce は produce, introduce と同語源。',
    relatedWords: ['reduction', 'decrease', 'cut'],
  },
  {
    id: 'reduction',
    word: 'reduction',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['減少、削減', '値下げ'],
    pronunciation: '/rɪˈdʌkʃn/',
    exampleSentence: 'The store announced a big price reduction on winter clothes.',
    exampleTranslationJa: 'その店は冬物衣料の大幅な値下げを発表した。',
    collocations: ['a price reduction', 'a reduction in costs'],
    wordFormation: 'reduce(減らす)+ -tion(名詞化)。',
    relatedWords: ['reduce', 'decrease', 'discount'],
  },
  {
    id: 'refer',
    word: 'refer',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(refer to で)言及する', '(refer to で)参照する', '(人を専門家などに)差し向ける'],
    pronunciation: '/rɪˈfɜːr/',
    exampleSentence: 'Please refer to page ten for more details.',
    exampleTranslationJa: '詳しくは10ページをご参照ください。',
    collocations: ['refer to a document', 'refer to someone as'],
    wordFormation: 're-(元へ)+ fer(運ぶ)。fer は transfer, offer と同語源。',
    relatedWords: ['reference', 'mention', 'consult'],
  },
  {
    id: 'reference',
    word: 'reference',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['言及', '参照、参考文献', '推薦状、身元照会'],
    pronunciation: '/ˈrefrəns/',
    exampleSentence: 'The report contains many references to recent studies.',
    exampleTranslationJa: 'その報告書には最近の研究への言及が数多く含まれている。',
    collocations: ['make reference to', 'a reference book', 'for future reference'],
    wordFormation: 'refer(言及する)+ -ence(名詞化)。',
    relatedWords: ['refer', 'source', 'citation'],
  },
  {
    id: 'reflect',
    word: 'reflect',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['反射する、映す', '反映する', '(reflect on で)よく考える'],
    pronunciation: '/rɪˈflekt/',
    exampleSentence: 'The lake reflected the mountains like a mirror.',
    exampleTranslationJa: '湖は鏡のように山々を映していた。',
    collocations: ['reflect light', 'reflect on the past', 'reflect the situation'],
    wordFormation: 're-(後ろへ)+ flect(曲げる)。flect は flexible と同語源。',
    relatedWords: ['reflection', 'mirror', 'consider'],
  },
  {
    id: 'reform',
    word: 'reform',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['改革', '(動詞)改革する'],
    pronunciation: '/rɪˈfɔːrm/',
    exampleSentence: 'The government promised major reforms to the tax system.',
    exampleTranslationJa: '政府は税制の大幅な改革を約束した。',
    collocations: ['economic reform', 'reform the system'],
    wordFormation: 're-(再び)+ form(形づくる)。「作り直す」が原義。',
    mnemonic: '日本語の「リフォーム(住宅改装)」は和製英語。英語の家の改装は renovate を使う。',
    relatedWords: ['reformation', 'change', 'improvement'],
  },
]
