import type { VocabularyEntry } from '../types'

export const batch08: VocabularyEntry[] = [
  {
    id: 'sharp',
    word: 'sharp',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['鋭い、よく切れる', '(変化が)急激な', '(頭が)切れる'],
    pronunciation: '/ʃɑːrp/',
    exampleSentence: 'Be careful because that knife is very sharp.',
    exampleTranslationJa: 'そのナイフはとてもよく切れるので気をつけて。',
    collocations: ['a sharp knife', 'a sharp rise', 'a sharp turn'],
    relatedWords: ['sharply', 'sharpen', 'blunt'],
  },
  {
    id: 'shelter',
    word: 'shelter',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['避難所、シェルター', '雨風をしのげる場所、住まい'],
    pronunciation: '/ˈʃeltər/',
    exampleSentence: 'People ran to the shelter when the storm began.',
    exampleTranslationJa: '嵐が始まると、人々は避難所へ走った。',
    collocations: ['take shelter', 'an emergency shelter', 'food and shelter'],
    relatedWords: ['refuge', 'protect', 'shed'],
  },
  {
    id: 'shift',
    word: 'shift',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['移す、移る、変わる', '(名詞)変化', '(名詞)交代勤務、シフト'],
    pronunciation: '/ʃɪft/',
    exampleSentence: 'Public opinion has shifted in favor of the new policy.',
    exampleTranslationJa: '世論はその新政策を支持する方向へ変わった。',
    collocations: ['shift attention', 'a night shift', 'a shift in attitudes'],
    relatedWords: ['change', 'move', 'transfer'],
  },
  {
    id: 'shine',
    word: 'shine',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['輝く、光る', '(才能などが)際立つ'],
    pronunciation: '/ʃaɪn/',
    exampleSentence: 'The sun was shining brightly all afternoon.',
    exampleTranslationJa: '午後の間ずっと太陽がまぶしく輝いていた。',
    collocations: ['the sun shines', 'shine brightly', 'shine a light on'],
    relatedWords: ['shiny', 'bright', 'glow'],
  },
  {
    id: 'shock',
    word: 'shock',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['衝撃、ショック', '(動詞)ぎょっとさせる'],
    pronunciation: '/ʃɑːk/',
    exampleSentence: 'The news of his sudden death came as a great shock to us.',
    exampleTranslationJa: '彼の突然の死の知らせは、私たちに大きな衝撃を与えた。',
    collocations: ['come as a shock', 'in shock', 'culture shock'],
    etymology: 'フランス語 choc(衝突)から。',
    relatedWords: ['shocked', 'shocking', 'surprise'],
  },
  {
    id: 'shocked',
    word: 'shocked',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['ショックを受けた、ぎょっとした'],
    pronunciation: '/ʃɑːkt/',
    exampleSentence: 'I was shocked to hear that the factory would close.',
    exampleTranslationJa: 'その工場が閉鎖されると聞いてショックを受けた。',
    collocations: ['shocked to hear', 'deeply shocked'],
    wordFormation: 'shock + -ed。ショックを「受けた」側の気持ちを表す(shocking と対)。',
    relatedWords: ['shocking', 'surprised', 'upset'],
  },
  {
    id: 'shocking',
    word: 'shocking',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['衝撃的な、ひどい'],
    pronunciation: '/ˈʃɑːkɪŋ/',
    exampleSentence: 'The report revealed some shocking facts about food waste.',
    exampleTranslationJa: 'その報告書は食品廃棄に関する衝撃的な事実を明らかにした。',
    collocations: ['shocking news', 'a shocking discovery'],
    wordFormation: 'shock + -ing。ショックを「与える」側の性質を表す。',
    relatedWords: ['shocked', 'surprising', 'disturbing'],
  },
  {
    id: 'shoot',
    word: 'shoot',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['撃つ', '(ボールを)シュートする', '(写真・映画を)撮影する'],
    pronunciation: '/ʃuːt/',
    exampleSentence: 'He shot the ball into the goal in the final minute.',
    exampleTranslationJa: '彼は最後の1分でボールをゴールに打ち込んだ。',
    collocations: ['shoot a gun', 'shoot a film', 'shoot at the goal'],
    relatedWords: ['shot', 'fire', 'aim'],
  },
  {
    id: 'shortage',
    word: 'shortage',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['不足、欠乏'],
    pronunciation: '/ˈʃɔːrtɪdʒ/',
    exampleSentence: 'The hospital is facing a serious shortage of nurses.',
    exampleTranslationJa: 'その病院は深刻な看護師不足に直面している。',
    collocations: ['a labor shortage', 'a water shortage', 'face a shortage'],
    wordFormation: 'short(足りない)+ -age(名詞化)。',
    relatedWords: ['lack', 'scarce', 'surplus'],
  },
  {
    id: 'shortly',
    word: 'shortly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['まもなく、すぐに'],
    pronunciation: '/ˈʃɔːrtli/',
    exampleSentence: 'The manager will be with you shortly.',
    exampleTranslationJa: '担当者はまもなく参ります。',
    collocations: ['shortly after', 'shortly before', 'arrive shortly'],
    wordFormation: 'short + -ly。「短い時間のうちに」。',
    relatedWords: ['soon', 'briefly', 'immediately'],
  },
  {
    id: 'show up',
    word: 'show up',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['現れる、姿を見せる'],
    pronunciation: '/ˌʃoʊ ˈʌp/',
    exampleSentence: 'He promised to come but never showed up.',
    exampleTranslationJa: '彼は来ると約束したのに、結局現れなかった。',
    collocations: ['show up late', 'fail to show up'],
    relatedWords: ['turn up', 'appear', 'arrive'],
  },
  {
    id: 'sight',
    word: 'sight',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['視力、視覚', '光景', '(sights で)名所'],
    pronunciation: '/saɪt/',
    exampleSentence: 'The sight of the ocean from the hill was amazing.',
    exampleTranslationJa: '丘から見える海の光景は見事だった。',
    collocations: ['at first sight', 'lose sight of', 'catch sight of'],
    etymology: '古英語由来で、see(見る)と同語源。',
    relatedWords: ['view', 'vision', 'sightseeing'],
  },
  {
    id: 'sign',
    word: 'sign',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['標識、看板', '兆候、しるし', '(動詞)署名する'],
    pronunciation: '/saɪn/',
    exampleSentence: 'The road sign says you cannot park here.',
    exampleTranslationJa: 'その道路標識には、ここに駐車できないと書かれている。',
    collocations: ['a road sign', 'a sign of stress', 'sign a contract'],
    etymology: 'ラテン語 signum(印)から。signal, signature と同語源。',
    relatedWords: ['signal', 'signature', 'symptom'],
  },
  {
    id: 'signal',
    word: 'signal',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['信号、合図', '(動詞)合図を送る、示す'],
    pronunciation: '/ˈsɪɡnəl/',
    exampleSentence: 'The referee gave the signal to start the match.',
    exampleTranslationJa: '審判は試合開始の合図を出した。',
    collocations: ['send a signal', 'a clear signal', 'traffic signals'],
    wordFormation: 'sign(印)+ -al。',
    relatedWords: ['sign', 'gesture', 'indicate'],
  },
  {
    id: 'significant',
    word: 'significant',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['重要な、意義深い', '(数量が)かなりの'],
    pronunciation: '/sɪɡˈnɪfɪkənt/',
    exampleSentence: 'There has been a significant increase in online sales this year.',
    exampleTranslationJa: '今年はオンライン売上に大幅な増加が見られた。',
    collocations: ['a significant difference', 'a significant increase', 'play a significant role'],
    wordFormation: 'sign(印)+ fic(作る)+ -ant。「意味を作り出す」が原義。',
    etymology: 'ラテン語 significare(意味する)から。sign と同語源。',
    relatedWords: ['significantly', 'significance', 'important'],
  },
  {
    id: 'significantly',
    word: 'significantly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['大幅に、著しく'],
    pronunciation: '/sɪɡˈnɪfɪkəntli/',
    exampleSentence: 'Prices have risen significantly over the past ten years.',
    exampleTranslationJa: '物価はこの10年で大幅に上昇した。',
    collocations: ['significantly higher', 'increase significantly'],
    wordFormation: 'significant + -ly。',
    relatedWords: ['significant', 'considerably', 'greatly'],
  },
  {
    id: 'silence',
    word: 'silence',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['静けさ、沈黙'],
    pronunciation: '/ˈsaɪləns/',
    exampleSentence: 'There was a long silence after he asked the question.',
    exampleTranslationJa: '彼が質問したあと、長い沈黙が流れた。',
    collocations: ['break the silence', 'in silence', 'complete silence'],
    relatedWords: ['silent', 'quiet', 'noise'],
  },
  {
    id: 'silent',
    word: 'silent',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['静かな、無言の'],
    pronunciation: '/ˈsaɪlənt/',
    exampleSentence: 'The whole class remained silent during the test.',
    exampleTranslationJa: 'テストの間、クラス全体が静かなままだった。',
    collocations: ['remain silent', 'fall silent', 'a silent room'],
    etymology: 'ラテン語 silere(静かである)から。',
    relatedWords: ['silence', 'silently', 'quiet'],
  },
  {
    id: 'similar',
    word: 'similar',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['似ている、同様の'],
    pronunciation: '/ˈsɪmələr/',
    exampleSentence: 'Your phone is very similar to mine.',
    exampleTranslationJa: '君の電話は私のとよく似ている。',
    collocations: ['similar to', 'in a similar way', 'strikingly similar'],
    etymology: 'ラテン語 similis(似ている)から。simulate, assemble と同語源。',
    relatedWords: ['similarly', 'similarity', 'alike'],
  },
  {
    id: 'similarly',
    word: 'similarly',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['同様に'],
    pronunciation: '/ˈsɪmələrli/',
    exampleSentence: 'Boys and girls performed similarly on the test.',
    exampleTranslationJa: 'そのテストでは男子と女子は同じような成績だった。',
    collocations: ['behave similarly', 'similarly priced'],
    wordFormation: 'similar + -ly。',
    relatedWords: ['similar', 'likewise', 'equally'],
  },
  {
    id: 'simply',
    word: 'simply',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['単に、ただ', '簡単に、簡素に'],
    pronunciation: '/ˈsɪmpli/',
    exampleSentence: 'I simply forgot to bring my umbrella.',
    exampleTranslationJa: '単に傘を持ってくるのを忘れただけだ。',
    collocations: ['quite simply', 'put simply', 'live simply'],
    wordFormation: 'simple + -ly。',
    relatedWords: ['simple', 'just', 'merely'],
  },
  {
    id: 'sincere',
    word: 'sincere',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['誠実な、心からの'],
    pronunciation: '/sɪnˈsɪr/',
    exampleSentence: 'Please accept my sincere apologies for the delay.',
    exampleTranslationJa: '遅延について心よりお詫び申し上げます。',
    collocations: ['a sincere apology', 'sincere thanks'],
    etymology: 'ラテン語 sincerus(純粋な)から。',
    relatedWords: ['sincerely', 'sincerity', 'honest'],
  },
  {
    id: 'site',
    word: 'site',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['用地、現場', '遺跡', '(ウェブ)サイト'],
    pronunciation: '/saɪt/',
    exampleSentence: 'They chose this site for the new stadium.',
    exampleTranslationJa: '彼らは新しいスタジアムの用地としてこの場所を選んだ。',
    collocations: ['a construction site', 'a historic site', 'visit a site'],
    etymology: 'ラテン語 situs(位置)から。situation と同語源。',
    relatedWords: ['website', 'location', 'situation'],
  },
  {
    id: 'situation',
    word: 'situation',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['状況、事態'],
    pronunciation: '/ˌsɪtʃuˈeɪʃn/',
    exampleSentence: 'The economic situation is slowly getting better.',
    exampleTranslationJa: '経済状況は少しずつ良くなっている。',
    collocations: ['a difficult situation', 'handle a situation', 'the current situation'],
    etymology: 'ラテン語 situs(位置)から。site と同語源。',
    relatedWords: ['circumstance', 'condition', 'site'],
  },
  {
    id: 'skilled',
    word: 'skilled',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['熟練した、腕のいい'],
    pronunciation: '/skɪld/',
    exampleSentence: 'The company needs more skilled engineers.',
    exampleTranslationJa: 'その会社はもっと熟練したエンジニアを必要としている。',
    collocations: ['skilled workers', 'highly skilled', 'skilled at negotiation'],
    wordFormation: 'skill(技能)+ -ed。',
    relatedWords: ['skill', 'skillful', 'experienced'],
  },
  {
    id: 'skip',
    word: 'skip',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['飛ばす、抜かす', '(授業などを)さぼる'],
    pronunciation: '/skɪp/',
    exampleSentence: 'You can skip this chapter if you already know the basics.',
    exampleTranslationJa: '基礎をすでに知っているなら、この章は飛ばしてもよい。',
    collocations: ['skip breakfast', 'skip a class', 'skip a step'],
    relatedWords: ['miss', 'omit', 'leave out'],
  },
  {
    id: 'slice',
    word: 'slice',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(薄い)一切れ', '(動詞)薄く切る'],
    pronunciation: '/slaɪs/',
    exampleSentence: 'Would you like another slice of pizza?',
    exampleTranslationJa: 'ピザをもう一切れいかがですか。',
    collocations: ['a slice of bread', 'slice an onion', 'a thin slice'],
    relatedWords: ['piece', 'cut', 'chop'],
  },
  {
    id: 'slight',
    word: 'slight',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['わずかな、軽微な'],
    pronunciation: '/slaɪt/',
    exampleSentence: 'There has been a slight improvement in her condition.',
    exampleTranslationJa: '彼女の容体はわずかに改善した。',
    collocations: ['a slight difference', 'a slight increase', 'a slight headache'],
    relatedWords: ['slightly', 'minor', 'subtle'],
  },
  {
    id: 'slightly',
    word: 'slightly',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['わずかに、少し'],
    pronunciation: '/ˈslaɪtli/',
    exampleSentence: 'This jacket is slightly bigger than the one I tried before.',
    exampleTranslationJa: 'このジャケットは前に試着したものより少し大きい。',
    collocations: ['slightly different', 'slightly higher'],
    wordFormation: 'slight + -ly。',
    relatedWords: ['slight', 'a little', 'somewhat'],
  },
  {
    id: 'slip',
    word: 'slip',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['滑る、滑って転ぶ', 'そっと動く、そっと入れる', '(名詞)ちょっとしたミス'],
    pronunciation: '/slɪp/',
    exampleSentence: 'She slipped on the icy road and hurt her arm.',
    exampleTranslationJa: '彼女は凍った道で滑って腕を痛めた。',
    collocations: ['slip on the ice', 'slip out of the room', 'a slip of the tongue'],
    relatedWords: ['slide', 'slippery', 'fall'],
  },
  {
    id: 'slope',
    word: 'slope',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['坂、斜面', '(スキーの)ゲレンデ'],
    pronunciation: '/sloʊp/',
    exampleSentence: 'The house stands on a gentle slope facing the sea.',
    exampleTranslationJa: 'その家は海に面したゆるやかな斜面に建っている。',
    collocations: ['a steep slope', 'a gentle slope', 'a ski slope'],
    relatedWords: ['hill', 'steep', 'incline'],
  },
  {
    id: 'smart',
    word: 'smart',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['賢い、頭のいい', '(服装が)きちんとした'],
    pronunciation: '/smɑːrt/',
    exampleSentence: 'Asking for advice early was a smart decision.',
    exampleTranslationJa: '早めに助言を求めたのは賢明な判断だった。',
    collocations: ['a smart decision', 'a smart move', 'look smart'],
    relatedWords: ['clever', 'intelligent', 'wise'],
  },
  {
    id: 'smooth',
    word: 'smooth',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['滑らかな、すべすべした', '(進行が)順調な'],
    pronunciation: '/smuːð/',
    exampleSentence: 'Mix the flour and milk until the mixture is smooth.',
    exampleTranslationJa: '小麦粉と牛乳を、なめらかになるまで混ぜてください。',
    collocations: ['a smooth surface', 'smooth skin', 'a smooth start'],
    relatedWords: ['smoothly', 'rough', 'flat'],
  },
  {
    id: 'social',
    word: 'social',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['社会の、社会的な', '社交の'],
    pronunciation: '/ˈsoʊʃl/',
    exampleSentence: 'Loneliness is becoming a serious social problem.',
    exampleTranslationJa: '孤独は深刻な社会問題になりつつある。',
    collocations: ['social media', 'social problems', 'social skills'],
    etymology: 'ラテン語 socius(仲間)から。society と同語源。',
    relatedWords: ['society', 'sociable', 'community'],
  },
  {
    id: 'society',
    word: 'society',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['社会', '協会、会'],
    pronunciation: '/səˈsaɪəti/',
    exampleSentence: 'Every member of society has rights and responsibilities.',
    exampleTranslationJa: '社会の一員は誰もが権利と責任を持つ。',
    collocations: ['modern society', 'a member of society', 'an aging society'],
    etymology: 'ラテン語 socius(仲間)から。social と同語源。',
    relatedWords: ['social', 'community', 'culture'],
  },
  {
    id: 'solid',
    word: 'solid',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['固体の、固い', 'しっかりした、確かな'],
    pronunciation: '/ˈsɑːlɪd/',
    exampleSentence: 'We need solid evidence before we accuse anyone.',
    exampleTranslationJa: '誰かを責める前に、確かな証拠が必要だ。',
    collocations: ['solid evidence', 'a solid foundation', 'frozen solid'],
    etymology: 'ラテン語 solidus(固い)から。',
    relatedWords: ['liquid', 'firm', 'reliable'],
  },
  {
    id: 'solution',
    word: 'solution',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['解決策、解決法', '(問題の)解答'],
    pronunciation: '/səˈluːʃn/',
    exampleSentence: 'We finally found a solution to the parking problem.',
    exampleTranslationJa: '私たちはついに駐車問題の解決策を見つけた。',
    collocations: ['find a solution', 'a simple solution', 'a solution to a problem'],
    wordFormation: 'solve(解く)と同語源の名詞形。-tion(名詞化)。',
    relatedWords: ['solve', 'answer', 'resolve'],
  },
  {
    id: 'solve',
    word: 'solve',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['解決する', '(問題・パズルを)解く'],
    pronunciation: '/sɑːlv/',
    exampleSentence: 'It took me an hour to solve the puzzle.',
    exampleTranslationJa: 'そのパズルを解くのに1時間かかった。',
    collocations: ['solve a problem', 'solve a mystery', 'solve a puzzle'],
    etymology: 'ラテン語 solvere(ほどく、解く)から。resolve, dissolve と同語源。',
    relatedWords: ['solution', 'resolve', 'figure out'],
  },
  {
    id: 'somehow',
    word: 'somehow',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['どうにかして、なんとかして', 'どういうわけか'],
    pronunciation: '/ˈsʌmhaʊ/',
    exampleSentence: 'Somehow we managed to finish the project on time.',
    exampleTranslationJa: 'どうにかして私たちは期限どおりにプロジェクトを終わらせた。',
    collocations: ['somehow manage to', 'somehow or other'],
    wordFormation: 'some + how。「何らかの方法で」。',
    relatedWords: ['somewhat', 'anyway', 'manage'],
  },
  {
    id: 'sort',
    word: 'sort',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['種類', '(動詞)分類する、並べ替える'],
    pronunciation: '/sɔːrt/',
    exampleSentence: 'What sort of music do you listen to?',
    exampleTranslationJa: 'どんな種類の音楽を聴きますか。',
    collocations: ['this sort of thing', 'all sorts of', 'sort the files'],
    etymology: 'ラテン語 sors(くじ、運命)から。',
    relatedWords: ['kind', 'type', 'sort out'],
  },
  {
    id: 'sort out',
    word: 'sort out',
    level: 'B2',
    partOfSpeech: '句動詞',
    meaningsJa: ['(問題を)解決する', '整理する、仕分ける'],
    pronunciation: '/ˌsɔːrt ˈaʊt/',
    exampleSentence: 'We need to sort out the schedule before the meeting.',
    exampleTranslationJa: '会議の前に日程を整理しておく必要がある。',
    collocations: ['sort out a problem', 'sort out the mess', 'get things sorted out'],
    relatedWords: ['sort', 'solve', 'organize'],
  },
  {
    id: 'source',
    word: 'source',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['源、原因', '出所、情報源'],
    pronunciation: '/sɔːrs/',
    exampleSentence: 'The sun is our main source of energy.',
    exampleTranslationJa: '太陽は私たちの主なエネルギー源だ。',
    collocations: ['a source of energy', 'a reliable source', 'a source of income'],
    etymology: '古フランス語で「湧き出るところ」。ラテン語 surgere(昇る)から。',
    relatedWords: ['resource', 'origin', 'cause'],
  },
  {
    id: 'spare',
    word: 'spare',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['予備の', '(時間が)空いている', '(動詞)(時間などを)割く'],
    pronunciation: '/sper/',
    exampleSentence: 'We keep a spare key under the flower pot.',
    exampleTranslationJa: '私たちは植木鉢の下に予備の鍵を置いている。',
    collocations: ['a spare key', 'spare time', 'spare a few minutes'],
    relatedWords: ['extra', 'backup', 'available'],
  },
  {
    id: 'specialist',
    word: 'specialist',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['専門家、専門医'],
    pronunciation: '/ˈspeʃəlɪst/',
    exampleSentence: 'You should see a specialist about your back pain.',
    exampleTranslationJa: '腰痛については専門医に診てもらったほうがいい。',
    collocations: ['a heart specialist', 'a specialist in economics', 'specialist knowledge'],
    wordFormation: 'special + -ist(〜する人)。',
    relatedWords: ['expert', 'specialize', 'specialty'],
  },
  {
    id: 'species',
    word: 'species',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['(生物の)種'],
    pronunciation: '/ˈspiːʃiːz/',
    exampleSentence: 'This species of bird is found only on these islands.',
    exampleTranslationJa: 'この鳥の種はこれらの島だけに生息する。',
    collocations: ['an endangered species', 'a rare species', 'species of plants'],
    etymology: 'ラテン語 species(見た目、種類)から。specere(見る)が語根で、special と同語源。',
    relatedWords: ['specific', 'breed', 'endangered'],
  },
  {
    id: 'specific',
    word: 'specific',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['特定の', '具体的な、明確な'],
    pronunciation: '/spəˈsɪfɪk/',
    exampleSentence: 'Do you have a specific date in mind for the trip?',
    exampleTranslationJa: '旅行の具体的な日付は決めていますか。',
    collocations: ['a specific example', 'specific instructions', 'specific to'],
    wordFormation: 'ラテン語 species(種類)+ fic(作る)。「種類を特定する」が原義。',
    relatedWords: ['specifically', 'particular', 'general'],
  },
  {
    id: 'specifically',
    word: 'specifically',
    level: 'B2',
    partOfSpeech: '副詞',
    meaningsJa: ['特に、とりわけ', '具体的に(言えば)'],
    pronunciation: '/spəˈsɪfɪkli/',
    exampleSentence: 'This app was designed specifically for language learners.',
    exampleTranslationJa: 'このアプリは語学学習者のために特別に設計された。',
    collocations: ['designed specifically for', 'more specifically'],
    wordFormation: 'specific + -ally。',
    relatedWords: ['specific', 'particularly', 'especially'],
  },
  {
    id: 'spirit',
    word: 'spirit',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['精神、心', '気力、意気', '霊、魂'],
    pronunciation: '/ˈspɪrɪt/',
    exampleSentence: 'The team showed great fighting spirit until the end.',
    exampleTranslationJa: 'チームは最後まで見事な闘志を見せた。',
    collocations: ['team spirit', 'in high spirits', 'the spirit of the law'],
    etymology: 'ラテン語 spiritus(息)から。inspire, expire と同語源。',
    relatedWords: ['spiritual', 'soul', 'mood'],
  },
  {
    id: 'spiritual',
    word: 'spiritual',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['精神的な、心の', '宗教的な、霊的な'],
    pronunciation: '/ˈspɪrɪtʃuəl/',
    exampleSentence: 'Meditation is an important spiritual practice in many cultures.',
    exampleTranslationJa: '瞑想は多くの文化で重要な精神的修行である。',
    collocations: ['spiritual growth', 'spiritual needs', 'a spiritual leader'],
    wordFormation: 'spirit + -ual(形容詞化)。',
    relatedWords: ['spirit', 'religious', 'mental'],
  },
  {
    id: 'split',
    word: 'split',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['分ける、分裂する', '割る、裂く'],
    pronunciation: '/splɪt/',
    exampleSentence: "Let's split the bill between the four of us.",
    exampleTranslationJa: '4人で勘定を割り勘にしよう。',
    collocations: ['split the bill', 'split into groups', 'split in half'],
    relatedWords: ['divide', 'separate', 'share'],
  },
  {
    id: 'spread',
    word: 'spread',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['広がる、広める', '(バターなどを)塗る', '(名詞)拡大、まん延'],
    pronunciation: '/spred/',
    exampleSentence: 'The news spread quickly through the small town.',
    exampleTranslationJa: 'その知らせは小さな町にあっという間に広まった。',
    collocations: ['spread quickly', 'spread butter', 'spread rumors'],
    relatedWords: ['expand', 'scatter', 'distribute'],
  },
  {
    id: 'spot',
    word: 'spot',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['場所、地点', 'しみ、斑点', '(動詞)見つける、気づく'],
    pronunciation: '/spɑːt/',
    exampleSentence: 'This cafe is a popular spot for young people.',
    exampleTranslationJa: 'このカフェは若者に人気の場所だ。',
    collocations: ['a tourist spot', 'on the spot', 'spot a mistake'],
    relatedWords: ['place', 'stain', 'notice'],
  },
  {
    id: 'squeeze',
    word: 'squeeze',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(強く)握る、絞る', '押し込む、詰め込む'],
    pronunciation: '/skwiːz/',
    exampleSentence: 'Squeeze some fresh lemon juice over the salad.',
    exampleTranslationJa: 'サラダに新鮮なレモンの汁を絞りかけてください。',
    collocations: ['squeeze a lemon', 'squeeze into a small space', "squeeze someone's hand"],
    relatedWords: ['press', 'crush', 'grip'],
  },
  {
    id: 'stable',
    word: 'stable',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['安定した'],
    pronunciation: '/ˈsteɪbl/',
    exampleSentence: "The patient's condition is now stable.",
    exampleTranslationJa: '患者の容体は現在安定している。',
    collocations: ['a stable job', 'a stable relationship', 'remain stable'],
    etymology: 'ラテン語 stabilis(しっかり立つ)から。語根 sta(立つ)は stand, state と同語源。',
    relatedWords: ['stability', 'steady', 'unstable'],
  },
  {
    id: 'staff',
    word: 'staff',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['職員、スタッフ(集合的)'],
    pronunciation: '/stæf/',
    exampleSentence: 'The hotel staff were friendly and helpful.',
    exampleTranslationJa: 'そのホテルの従業員は親切で頼りになった。',
    collocations: ['a member of staff', 'medical staff', 'train the staff'],
    etymology: '原義は古英語の「棒、杖」。軍の司令部を経て「職員」の意味になった。',
    relatedWords: ['employee', 'personnel', 'crew'],
  },
  {
    id: 'stage',
    word: 'stage',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['段階', '舞台、ステージ'],
    pronunciation: '/steɪdʒ/',
    exampleSentence: 'The project is still at an early stage.',
    exampleTranslationJa: 'そのプロジェクトはまだ初期段階にある。',
    collocations: ['at an early stage', 'stage by stage', 'on stage'],
    etymology: '古フランス語 estage から。語根はラテン語 stare(立つ)。',
    relatedWords: ['phase', 'step', 'level'],
  },
  {
    id: 'standard',
    word: 'standard',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['基準、水準', '(形容詞)標準の'],
    pronunciation: '/ˈstændərd/',
    exampleSentence: 'The food at this restaurant is of a very high standard.',
    exampleTranslationJa: 'このレストランの料理は非常に水準が高い。',
    collocations: ['high standards', 'safety standards', 'the standard size'],
    etymology: '古フランス語 estandart(軍旗)から。「王の旗印」が「基準」の意味に発展した。',
    relatedWords: ['level', 'quality', 'normal'],
  },
  {
    id: 'stare',
    word: 'stare',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['じっと見る、見つめる'],
    pronunciation: '/ster/',
    exampleSentence: 'It is rude to stare at strangers.',
    exampleTranslationJa: '知らない人をじろじろ見るのは失礼だ。',
    collocations: ['stare at', 'stare blankly', 'stare out of the window'],
    relatedWords: ['gaze', 'glance', 'watch'],
  },
  {
    id: 'state',
    word: 'state',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['状態', '国家、州', '(動詞)はっきり述べる'],
    pronunciation: '/steɪt/',
    exampleSentence: 'The old bridge is in a dangerous state.',
    exampleTranslationJa: 'その古い橋は危険な状態にある。',
    collocations: ['a state of emergency', 'the state of the economy', 'state an opinion'],
    etymology: 'ラテン語 stare(立つ)の派生 status から。station, statue と同語源。',
    relatedWords: ['statement', 'status', 'condition'],
  },
  {
    id: 'statement',
    word: 'statement',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['声明、発言', '(銀行の)明細書'],
    pronunciation: '/ˈsteɪtmənt/',
    exampleSentence: 'The company issued a statement about the accident.',
    exampleTranslationJa: 'その会社は事故についての声明を発表した。',
    collocations: ['make a statement', 'an official statement', 'a bank statement'],
    wordFormation: 'state(述べる)+ -ment(名詞化)。',
    relatedWords: ['state', 'announcement', 'comment'],
  },
  {
    id: 'statistic',
    word: 'statistic',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['統計値、統計データ'],
    pronunciation: '/stəˈtɪstɪk/',
    exampleSentence: 'One shocking statistic is that a third of all food is wasted.',
    exampleTranslationJa: '衝撃的な統計の一つは、全食料の3分の1が廃棄されているということだ。',
    collocations: ['official statistics', 'according to statistics', 'a surprising statistic'],
    etymology: '元は「国家(state)に関する数値データ」を指した語。state, status と同語源。',
    relatedWords: ['statistics', 'data', 'figure'],
  },
  {
    id: 'status',
    word: 'status',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['地位、身分', '状況、状態'],
    pronunciation: '/ˈsteɪtəs/',
    exampleSentence: 'Doctors have a high social status in many countries.',
    exampleTranslationJa: '多くの国で医師は高い社会的地位を持つ。',
    collocations: ['social status', 'marital status', 'check the status of an order'],
    etymology: 'ラテン語 status(立っている状態)から。state と同語源。',
    relatedWords: ['state', 'position', 'rank'],
  },
  {
    id: 'steady',
    word: 'steady',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['着実な、一定の', '安定した、ぐらつかない'],
    pronunciation: '/ˈstedi/',
    exampleSentence: 'The patient is making steady progress.',
    exampleTranslationJa: '患者は着実な回復を見せている。',
    collocations: ['steady progress', 'a steady income', 'hold the camera steady'],
    relatedWords: ['stable', 'constant', 'firm'],
  },
  {
    id: 'steal',
    word: 'steal',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['盗む'],
    pronunciation: '/stiːl/',
    exampleSentence: 'Someone tried to steal my bike from the station last night.',
    exampleTranslationJa: '昨夜、誰かが駅で私の自転車を盗もうとした。',
    collocations: ['steal money', 'steal a car', 'steal from a shop'],
    relatedWords: ['thief', 'theft', 'rob'],
  },
  {
    id: 'steel',
    word: 'steel',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['鋼鉄、鋼'],
    pronunciation: '/stiːl/',
    exampleSentence: 'The bridge is made of steel and concrete.',
    exampleTranslationJa: 'その橋は鋼鉄とコンクリートでできている。',
    collocations: ['stainless steel', 'a steel frame', 'the steel industry'],
    mnemonic: 'steal(盗む)と同じ発音。「鋼を盗む steal steel」とセットで発音を覚える。',
    relatedWords: ['iron', 'metal', 'steal'],
  },
  {
    id: 'steep',
    word: 'steep',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['(坂が)急な', '(上昇・値段が)急激な、法外な'],
    pronunciation: '/stiːp/',
    exampleSentence: 'The path up the mountain is quite steep.',
    exampleTranslationJa: '山を登るその道はかなり急だ。',
    collocations: ['a steep hill', 'a steep rise in prices', 'steep stairs'],
    relatedWords: ['slope', 'sharp', 'gentle'],
  },
  {
    id: 'stick',
    word: 'stick',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['くっつく、貼る', '突き刺す', '(名詞)棒切れ'],
    pronunciation: '/stɪk/',
    exampleSentence: 'Stick this label on the box before you send it.',
    exampleTranslationJa: '送る前にこのラベルを箱に貼ってください。',
    collocations: ['stick a poster on the wall', 'stick to a plan', 'a walking stick'],
    relatedWords: ['sticky', 'sticker', 'attach'],
  },
  {
    id: 'stiff',
    word: 'stiff',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['硬い、曲がりにくい', '(体が)こわばった、凝った'],
    pronunciation: '/stɪf/',
    exampleSentence: 'My shoulders feel stiff after working at the computer all day.',
    exampleTranslationJa: '一日中パソコン作業をしたあとで肩が凝っている。',
    collocations: ['a stiff neck', 'stiff muscles', 'stiff competition'],
    relatedWords: ['rigid', 'firm', 'flexible'],
  },
  {
    id: 'still',
    word: 'still',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['まだ、今でも', 'それでも、それにもかかわらず', '(形容詞)静止した、じっとした'],
    pronunciation: '/stɪl/',
    exampleSentence: 'The job is hard, but I still enjoy it.',
    exampleTranslationJa: 'その仕事は大変だが、それでも私は楽しんでいる。',
    collocations: ['still waiting', 'sit still', 'still water'],
    relatedWords: ['yet', 'already', 'calm'],
  },
  {
    id: 'stir',
    word: 'stir',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['かき混ぜる', '(感情を)かき立てる'],
    pronunciation: '/stɜːr/',
    exampleSentence: 'Stir the soup slowly until it boils.',
    exampleTranslationJa: '沸騰するまでスープをゆっくりかき混ぜてください。',
    collocations: ['stir the mixture', 'stir well', 'stir up memories'],
    relatedWords: ['mix', 'blend', 'shake'],
  },
  {
    id: 'stock',
    word: 'stock',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['在庫、蓄え', '株、株式'],
    pronunciation: '/stɑːk/',
    exampleSentence: "I'm sorry, but that size is out of stock.",
    exampleTranslationJa: '申し訳ありませんが、そのサイズは在庫切れです。',
    collocations: ['in stock', 'out of stock', 'the stock market'],
    relatedWords: ['storage', 'supply', 'share'],
  },
  {
    id: 'storage',
    word: 'storage',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['保管、貯蔵', '収納(スペース)'],
    pronunciation: '/ˈstɔːrɪdʒ/',
    exampleSentence: 'This apartment has plenty of storage space.',
    exampleTranslationJa: 'このアパートには収納スペースがたくさんある。',
    collocations: ['storage space', 'in storage', 'data storage'],
    wordFormation: 'store(蓄える)+ -age(名詞化)。',
    relatedWords: ['store', 'stock', 'warehouse'],
  },
  {
    id: 'store',
    word: 'store',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['蓄える、保管する', '(名詞)店'],
    pronunciation: '/stɔːr/',
    exampleSentence: 'You can store your photos safely in the cloud.',
    exampleTranslationJa: '写真はクラウドに安全に保存できる。',
    collocations: ['store data', 'store food', 'a department store'],
    etymology: 'ラテン語 instaurare(補充する)に由来。restore と同語源。',
    relatedWords: ['storage', 'save', 'keep'],
  },
  {
    id: 'strategy',
    word: 'strategy',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['戦略、方策'],
    pronunciation: '/ˈstrætədʒi/',
    exampleSentence: 'We need a new strategy to attract younger customers.',
    exampleTranslationJa: '若い顧客を引きつけるための新しい戦略が必要だ。',
    collocations: ['develop a strategy', 'a marketing strategy', 'a long-term strategy'],
    etymology: 'ギリシャ語 strategos(将軍)から。元は軍事用語。',
    relatedWords: ['strategic', 'tactic', 'plan'],
  },
  {
    id: 'strength',
    word: 'strength',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['力、体力', '強さ、強度', '強み、長所'],
    pronunciation: '/streŋθ/',
    exampleSentence: 'It took all my strength to move the piano.',
    exampleTranslationJa: 'ピアノを動かすのに全力が必要だった。',
    collocations: ['physical strength', 'strengths and weaknesses', 'the strength of the economy'],
    wordFormation: 'strong(強い)の名詞形。long → length と同じパターン。',
    relatedWords: ['strong', 'strengthen', 'weakness'],
  },
  {
    id: 'strengthen',
    word: 'strengthen',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['強化する、強くなる'],
    pronunciation: '/ˈstreŋθn/',
    exampleSentence: 'Regular exercise strengthens your heart and muscles.',
    exampleTranslationJa: '定期的な運動は心臓と筋肉を強くする。',
    collocations: ['strengthen ties', 'strengthen the economy', 'strengthen muscles'],
    wordFormation: 'strength(強さ)+ -en(動詞化)。shorten, widen と同じパターン。',
    relatedWords: ['strength', 'reinforce', 'weaken'],
  },
  {
    id: 'stress',
    word: 'stress',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['ストレス、緊張', '強調', '(動詞)強調する'],
    pronunciation: '/stres/',
    exampleSentence: 'She has been under a lot of stress at work lately.',
    exampleTranslationJa: '彼女は最近、仕事で大きなストレスを抱えている。',
    collocations: ['under stress', 'reduce stress', 'stress the importance of'],
    etymology: 'distress の短縮形として生まれた語。語根はラテン語 stringere(締める)で、strict と同語源。',
    relatedWords: ['stressful', 'pressure', 'strain'],
  },
  {
    id: 'stretch',
    word: 'stretch',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['伸ばす、伸びる', '(体を)ストレッチする', '(土地などが)広がる'],
    pronunciation: '/stretʃ/',
    exampleSentence: 'Remember to stretch before you go running.',
    exampleTranslationJa: '走りに行く前に必ずストレッチをしなさい。',
    collocations: ['stretch your legs', 'stretch out', 'stretch for miles'],
    relatedWords: ['extend', 'expand', 'flexible'],
  },
  {
    id: 'strict',
    word: 'strict',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['厳しい、厳格な'],
    pronunciation: '/strɪkt/',
    exampleSentence: 'Our school has strict rules about mobile phones.',
    exampleTranslationJa: '私たちの学校には携帯電話に関する厳しい規則がある。',
    collocations: ['strict rules', 'a strict teacher', 'a strict diet'],
    etymology: 'ラテン語 stringere(締める)から。stress, strain と同語源。',
    relatedWords: ['strictly', 'severe', 'firm'],
  },
  {
    id: 'strike',
    word: 'strike',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['打つ、(災害などが)襲う', '(考えが)ふと心に浮かぶ', '(名詞)ストライキ'],
    pronunciation: '/straɪk/',
    exampleSentence: 'A powerful earthquake struck the region last night.',
    exampleTranslationJa: '昨夜、強い地震がその地域を襲った。',
    collocations: ['strike a balance', 'go on strike', 'lightning strikes'],
    relatedWords: ['hit', 'striking', 'attack'],
  },
  {
    id: 'structure',
    word: 'structure',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['構造、仕組み', '建造物', '(動詞)組み立てる、構成する'],
    pronunciation: '/ˈstrʌktʃər/',
    exampleSentence: 'The structure of the essay is clear and easy to follow.',
    exampleTranslationJa: 'その小論文の構成は明快で分かりやすい。',
    collocations: ['the structure of society', 'a wooden structure', 'sentence structure'],
    etymology: 'ラテン語 struere(積み上げる)から。construct, instruction と同語源。',
    relatedWords: ['structural', 'construct', 'framework'],
  },
  {
    id: 'struggle',
    word: 'struggle',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['奮闘する、苦労する', 'もがく', '(名詞)闘い、苦闘'],
    pronunciation: '/ˈstrʌɡl/',
    exampleSentence: 'Many families are struggling to pay their bills.',
    exampleTranslationJa: '多くの家庭が請求書の支払いに苦労している。',
    collocations: ['struggle to survive', 'struggle with a problem', 'a power struggle'],
    relatedWords: ['effort', 'fight', 'difficulty'],
  },
  {
    id: 'stuff',
    word: 'stuff',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['物、持ち物', '(漠然と)こと、内容', '(動詞)詰め込む'],
    pronunciation: '/stʌf/',
    exampleSentence: 'You can leave your stuff in my room.',
    exampleTranslationJa: '荷物は私の部屋に置いていっていいよ。',
    collocations: ['pack your stuff', 'and stuff like that', 'stuff a suitcase with clothes'],
    relatedWords: ['things', 'belongings', 'material'],
  },
  {
    id: 'subject',
    word: 'subject',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['科目、教科', '主題、話題', '(文法の)主語'],
    pronunciation: '/ˈsʌbdʒɪkt/',
    exampleSentence: 'Science was my favorite subject at school.',
    exampleTranslationJa: '理科は学校でいちばん好きな科目だった。',
    collocations: ['a school subject', 'change the subject', 'the subject of a sentence'],
    etymology: 'ラテン語 sub(下に)+ jacere(投げる)から。「下に置かれたもの」が原義。',
    relatedWords: ['topic', 'theme', 'object'],
  },
  {
    id: 'substance',
    word: 'substance',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['物質', '実質、中身'],
    pronunciation: '/ˈsʌbstəns/',
    exampleSentence: 'The police found an illegal substance in the car.',
    exampleTranslationJa: '警察は車内から違法な物質を発見した。',
    collocations: ['a chemical substance', 'a dangerous substance', 'lack substance'],
    wordFormation: 'sub-(下に)+ stance(立つこと)。「物事の下に立つ本体」が原義。',
    relatedWords: ['material', 'chemical', 'substantial'],
  },
  {
    id: 'substitute',
    word: 'substitute',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['代わりの人、代用品', '(動詞)代わりに使う、代える'],
    pronunciation: '/ˈsʌbstɪtuːt/',
    exampleSentence: 'You can use honey as a substitute for sugar.',
    exampleTranslationJa: '砂糖の代わりに蜂蜜を使うことができる。',
    collocations: ['a substitute for', 'a substitute teacher', 'substitute A for B'],
    wordFormation: 'sub-(代わりに)+ stitute(置く)。institute, constitute と同じ語根。',
    relatedWords: ['replace', 'replacement', 'alternative'],
  },
  {
    id: 'suburb',
    word: 'suburb',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['郊外(の住宅地)'],
    pronunciation: '/ˈsʌbɜːrb/',
    exampleSentence: 'They moved to a quiet suburb after their first child was born.',
    exampleTranslationJa: '最初の子どもが生まれたあと、彼らは静かな郊外へ引っ越した。',
    collocations: ['a suburb of Tokyo', 'live in the suburbs', 'a quiet suburb'],
    wordFormation: 'sub-(近くの、下の)+ urb(都市)。urban(都市の)と同語源。',
    relatedWords: ['suburban', 'urban', 'rural'],
  },
  {
    id: 'succeed',
    word: 'succeed',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['成功する', '(地位を)継ぐ'],
    pronunciation: '/səkˈsiːd/',
    exampleSentence: 'If you keep practicing, you will succeed in the end.',
    exampleTranslationJa: '練習を続ければ、最後には成功するだろう。',
    collocations: ['succeed in business', 'succeed in doing', 'succeed to the throne'],
    etymology: 'ラテン語 sub(後に)+ cedere(行く)から。「後に続く」が原義。',
    relatedWords: ['success', 'successful', 'fail'],
  },
  {
    id: 'success',
    word: 'success',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['成功'],
    pronunciation: '/səkˈses/',
    exampleSentence: 'The event was a great success and raised a lot of money.',
    exampleTranslationJa: 'そのイベントは大成功で、多額の資金を集めた。',
    collocations: ['a great success', 'the key to success', 'achieve success'],
    relatedWords: ['succeed', 'successful', 'failure'],
  },
  {
    id: 'successful',
    word: 'successful',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['成功した、うまくいった'],
    pronunciation: '/səkˈsesfl/',
    exampleSentence: 'She runs a successful online business.',
    exampleTranslationJa: '彼女は成功しているオンラインビジネスを経営している。',
    collocations: ['a successful career', 'highly successful', 'be successful in'],
    wordFormation: 'success + -ful(〜に満ちた)。',
    relatedWords: ['success', 'succeed', 'unsuccessful'],
  },
  {
    id: 'sudden',
    word: 'sudden',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['突然の、急な'],
    pronunciation: '/ˈsʌdn/',
    exampleSentence: 'There was a sudden change in the weather.',
    exampleTranslationJa: '天気が急変した。',
    collocations: ['a sudden change', 'all of a sudden', 'a sudden death'],
    relatedWords: ['suddenly', 'unexpected', 'gradual'],
  },
  {
    id: 'suddenly',
    word: 'suddenly',
    level: 'B1',
    partOfSpeech: '副詞',
    meaningsJa: ['突然、急に'],
    pronunciation: '/ˈsʌdənli/',
    exampleSentence: 'Suddenly all the lights went out.',
    exampleTranslationJa: '突然、すべての明かりが消えた。',
    collocations: ['suddenly appear', 'quite suddenly'],
    wordFormation: 'sudden + -ly。',
    relatedWords: ['sudden', 'unexpectedly', 'gradually'],
  },
  {
    id: 'suffer',
    word: 'suffer',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['苦しむ、患う', '(損害などを)受ける'],
    pronunciation: '/ˈsʌfər/',
    exampleSentence: 'He suffers from severe headaches.',
    exampleTranslationJa: '彼はひどい頭痛に悩まされている。',
    collocations: ['suffer from', 'suffer damage', 'suffer a loss'],
    etymology: 'ラテン語 sub(下で)+ ferre(運ぶ)から。「重みを下から支えて耐える」が原義。',
    relatedWords: ['suffering', 'pain', 'endure'],
  },
  {
    id: 'sufficient',
    word: 'sufficient',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['十分な'],
    pronunciation: '/səˈfɪʃnt/',
    exampleSentence: 'Make sure you have sufficient time to prepare.',
    exampleTranslationJa: '準備に十分な時間を確保するようにしなさい。',
    collocations: ['sufficient evidence', 'sufficient funds', 'sufficient time'],
    etymology: 'ラテン語 sub(下に)+ facere(作る)から。「必要を満たすだけ作る」が原義。',
    relatedWords: ['insufficient', 'enough', 'adequate'],
  },
  {
    id: 'suggest',
    word: 'suggest',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['提案する', '示唆する、暗示する'],
    pronunciation: '/səˈdʒest/',
    exampleSentence: 'I suggest taking a break before we continue.',
    exampleTranslationJa: '続ける前に休憩を取ることを提案します。',
    collocations: ['suggest an idea', 'suggest doing', 'evidence suggests that'],
    etymology: 'ラテン語 sub(下から)+ gerere(運ぶ)から。「下からそっと差し出す」イメージ。',
    relatedWords: ['suggestion', 'propose', 'recommend'],
  },
  {
    id: 'suggestion',
    word: 'suggestion',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['提案'],
    pronunciation: '/səˈdʒestʃən/',
    exampleSentence: 'Do you have any suggestions for improving the plan?',
    exampleTranslationJa: 'その計画を改善するための提案はありますか。',
    collocations: ['make a suggestion', 'a helpful suggestion', 'at my suggestion'],
    wordFormation: 'suggest + -ion(名詞化)。',
    relatedWords: ['suggest', 'proposal', 'advice'],
  },
  {
    id: 'suit',
    word: 'suit',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(人に)合う、都合がよい', '(服・色が)似合う', '(名詞)スーツ'],
    pronunciation: '/suːt/',
    exampleSentence: "Does ten o'clock suit you?",
    exampleTranslationJa: '10時はご都合よろしいですか。',
    collocations: ['suit your schedule', 'a business suit', 'suit you perfectly'],
    etymology: 'ラテン語 sequi(後に従う)に由来。pursue, sue と同語源。',
    relatedWords: ['suitable', 'fit', 'match'],
  },
  {
    id: 'suitable',
    word: 'suitable',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['適した、ふさわしい'],
    pronunciation: '/ˈsuːtəbl/',
    exampleSentence: 'This movie is not suitable for young children.',
    exampleTranslationJa: 'この映画は幼い子どもには適していない。',
    collocations: ['suitable for', 'a suitable candidate', 'highly suitable'],
    wordFormation: 'suit(合う)+ -able(〜できる)。',
    relatedWords: ['suit', 'appropriate', 'proper'],
  },
  {
    id: 'sum',
    word: 'sum',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['金額', '合計'],
    pronunciation: '/sʌm/',
    exampleSentence: 'They spent a large sum of money on the renovation.',
    exampleTranslationJa: '彼らは改装に多額の金を費やした。',
    collocations: ['a large sum of money', 'the sum of', 'in sum'],
    etymology: 'ラテン語 summa(最上のもの、合計)から。summit(頂上)と同語源。',
    relatedWords: ['total', 'amount', 'summarize'],
  },
  {
    id: 'summarize',
    word: 'summarize',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['要約する'],
    pronunciation: '/ˈsʌməraɪz/',
    exampleSentence: 'Can you summarize the report in a few sentences?',
    exampleTranslationJa: 'その報告書を数文で要約できますか。',
    collocations: ['summarize the main points', 'briefly summarize'],
    wordFormation: 'summary(要約)+ -ize(動詞化)。',
    relatedWords: ['summary', 'sum', 'outline'],
  },
  {
    id: 'supply',
    word: 'supply',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['供給、供給量', '(supplies で)必需品', '(動詞)供給する'],
    pronunciation: '/səˈplaɪ/',
    exampleSentence: 'The town depends on the river for its water supply.',
    exampleTranslationJa: 'その町は水の供給をその川に頼っている。',
    collocations: ['supply and demand', 'a power supply', 'supply A with B'],
    etymology: 'ラテン語 supplere(満たす)から。sub(下から)+ plere(満たす)で、complete と同語源。',
    relatedWords: ['demand', 'provide', 'supplier'],
  },
  {
    id: 'support',
    word: 'support',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['支持する、支援する', '支える', '(名詞)支援、支持'],
    pronunciation: '/səˈpɔːrt/',
    exampleSentence: 'My family supported me when I decided to change jobs.',
    exampleTranslationJa: '転職を決めたとき、家族は私を支えてくれた。',
    collocations: ['support a family', 'financial support', 'support a team'],
    etymology: 'ラテン語 sub(下から)+ portare(運ぶ)から。transport, portable と同語源。',
    relatedWords: ['supporter', 'supportive', 'assist'],
  },
  {
    id: 'suppose',
    word: 'suppose',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['(たぶん)〜だと思う', '仮定する', '(be supposed to で)〜することになっている'],
    pronunciation: '/səˈpoʊz/',
    exampleSentence: 'I suppose we should start without him.',
    exampleTranslationJa: '彼抜きで始めるべきだと思う。',
    collocations: ['I suppose so', 'be supposed to', 'suppose that'],
    etymology: 'ラテン語 sub(下に)+ ponere(置く)から。「下に置いて前提とする」。position と同語源。',
    relatedWords: ['assume', 'guess', 'presume'],
  },
  {
    id: 'surface',
    word: 'surface',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['表面', '外見、うわべ'],
    pronunciation: '/ˈsɜːrfɪs/',
    exampleSentence: "Two thirds of the Earth's surface is covered with water.",
    exampleTranslationJa: '地球の表面の3分の2は水に覆われている。',
    collocations: ['the surface of the water', 'a smooth surface', 'on the surface'],
    wordFormation: 'sur-(上の)+ face(面)。',
    relatedWords: ['face', 'exterior', 'depth'],
  },
  {
    id: 'surgery',
    word: 'surgery',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['手術', '外科'],
    pronunciation: '/ˈsɜːrdʒəri/',
    exampleSentence: 'He needs surgery on his left knee.',
    exampleTranslationJa: '彼は左ひざの手術が必要だ。',
    collocations: ['undergo surgery', 'heart surgery', 'plastic surgery'],
    etymology: 'ギリシャ語 kheir(手)+ ergon(仕事)に由来し、「手仕事」が原義。',
    relatedWords: ['surgeon', 'operation', 'treatment'],
  },
  {
    id: 'surround',
    word: 'surround',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['囲む、取り巻く'],
    pronunciation: '/səˈraʊnd/',
    exampleSentence: 'Tall trees surround the old house.',
    exampleTranslationJa: '高い木々がその古い家を囲んでいる。',
    collocations: ['be surrounded by', 'surround a city'],
    relatedWords: ['surrounding', 'surroundings', 'enclose'],
  },
  {
    id: 'surrounding',
    word: 'surrounding',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['周囲の、周辺の', '(surroundings で)環境、周囲の状況'],
    pronunciation: '/səˈraʊndɪŋ/',
    exampleSentence: 'The hotel offers great views of the surrounding mountains.',
    exampleTranslationJa: 'そのホテルからは周囲の山々のすばらしい眺めが楽しめる。',
    collocations: ['the surrounding area', 'surrounding villages', 'natural surroundings'],
    wordFormation: 'surround(囲む)+ -ing。',
    relatedWords: ['surround', 'nearby', 'environment'],
  },
  {
    id: 'survey',
    word: 'survey',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['(アンケート)調査', '(動詞)調査する'],
    pronunciation: '/ˈsɜːrveɪ/',
    exampleSentence: 'We carried out a survey of five hundred customers.',
    exampleTranslationJa: '私たちは500人の顧客を対象に調査を実施した。',
    collocations: ['conduct a survey', 'a recent survey', 'survey results'],
    etymology: 'sur-(上から)+ ラテン語 videre(見る)。「上から見渡す」が原義。',
    relatedWords: ['questionnaire', 'research', 'poll'],
  },
  {
    id: 'survive',
    word: 'survive',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['生き残る、生き延びる', '(困難を)乗り切る'],
    pronunciation: '/sərˈvaɪv/',
    exampleSentence: 'Only a few passengers survived the crash.',
    exampleTranslationJa: 'その事故で生き残った乗客はわずかだった。',
    collocations: ['survive an accident', 'survive the winter', 'struggle to survive'],
    etymology: 'ラテン語 super(超えて)+ vivere(生きる)から。vivid, revive と同語源。',
    relatedWords: ['survival', 'survivor', 'live'],
  },
  {
    id: 'suspect',
    word: 'suspect',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(〜ではないかと)疑う、思う', '(名詞)容疑者'],
    pronunciation: '/səˈspekt/',
    exampleSentence: 'I suspect that he already knows the truth.',
    exampleTranslationJa: '彼はすでに真実を知っているのではないかと思う。',
    collocations: ['suspect someone of lying', 'a murder suspect', 'strongly suspect'],
    etymology: 'ラテン語 sub(下から)+ specere(見る)から。「下からうかがい見る」が原義。inspect, respect と同語源。',
    relatedWords: ['suspicion', 'suspicious', 'doubt'],
  },
  {
    id: 'sustain',
    word: 'sustain',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['持続させる、維持する', '支える'],
    pronunciation: '/səˈsteɪn/',
    exampleSentence: 'It is hard to sustain this pace of growth for long.',
    exampleTranslationJa: 'この成長ペースを長く維持するのは難しい。',
    collocations: ['sustain growth', 'sustain interest', 'sustain life'],
    etymology: 'ラテン語 sub(下から)+ tenere(保つ)から。maintain, contain と同語源。',
    relatedWords: ['sustainable', 'maintain', 'sustainability'],
  },
  {
    id: 'sustainable',
    word: 'sustainable',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['持続可能な'],
    pronunciation: '/səˈsteɪnəbl/',
    exampleSentence: 'We need to find more sustainable ways of producing energy.',
    exampleTranslationJa: 'より持続可能なエネルギー生産の方法を見つける必要がある。',
    collocations: ['sustainable development', 'sustainable energy', 'environmentally sustainable'],
    wordFormation: 'sustain(持続させる)+ -able(〜できる)。',
    relatedWords: ['sustain', 'sustainability', 'renewable'],
  },
  {
    id: 'swear',
    word: 'swear',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['誓う、断言する', '悪態をつく、ののしる'],
    pronunciation: '/swer/',
    exampleSentence: 'I swear I locked the door before we left.',
    exampleTranslationJa: '出かける前に確かにドアに鍵をかけたと断言できる。',
    collocations: ['swear to tell the truth', 'swear at someone', 'swear by'],
    relatedWords: ['promise', 'oath', 'curse'],
  },
  {
    id: 'switch',
    word: 'switch',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['切り替える、変更する', '(名詞)スイッチ'],
    pronunciation: '/swɪtʃ/',
    exampleSentence: 'I switched to a cheaper phone plan last month.',
    exampleTranslationJa: '先月、もっと安い携帯プランに切り替えた。',
    collocations: ['switch off the lights', 'switch to a new system', 'a light switch'],
    relatedWords: ['change', 'swap', 'turn off'],
  },
  {
    id: 'symbol',
    word: 'symbol',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['象徴、シンボル', '記号'],
    pronunciation: '/ˈsɪmbl/',
    exampleSentence: 'The dove is a symbol of peace.',
    exampleTranslationJa: 'ハトは平和の象徴だ。',
    collocations: ['a symbol of peace', 'a status symbol', 'a chemical symbol'],
    etymology: 'ギリシャ語 symbolon(照合のしるし)から。syn(共に)+ ballein(投げる)。',
    relatedWords: ['symbolic', 'symbolize', 'sign'],
  },
  {
    id: 'sympathy',
    word: 'sympathy',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['同情、思いやり', '共感、支持'],
    pronunciation: '/ˈsɪmpəθi/',
    exampleSentence: 'I have great sympathy for the families who lost their homes.',
    exampleTranslationJa: '家を失った家族たちに深く同情する。',
    collocations: ['express sympathy', 'have sympathy for', 'a letter of sympathy'],
    wordFormation: 'sym-(共に)+ pathy(感情)。empathy, apathy と同じ語根。',
    etymology: 'ギリシャ語 syn(共に)+ pathos(感情)から。',
    relatedWords: ['sympathize', 'sympathetic', 'empathy'],
  },
  {
    id: 'symptom',
    word: 'symptom',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['症状', '(悪い)兆候'],
    pronunciation: '/ˈsɪmptəm/',
    exampleSentence: 'A high fever is a common symptom of the flu.',
    exampleTranslationJa: '高熱はインフルエンザによく見られる症状だ。',
    collocations: ['show symptoms', 'a common symptom', 'symptoms of stress'],
    etymology: 'ギリシャ語 syn(共に)+ piptein(落ちる)から。「病気に伴って起こること」が原義。',
    relatedWords: ['sign', 'disease', 'diagnosis'],
  },
  {
    id: 'system',
    word: 'system',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['制度、体系、システム', '(体の)器官系'],
    pronunciation: '/ˈsɪstəm/',
    exampleSentence: 'The school introduced a new system for reporting absences.',
    exampleTranslationJa: '学校は欠席を報告する新しい仕組みを導入した。',
    collocations: ['an education system', 'a computer system', 'the immune system'],
    etymology: 'ギリシャ語 systema(組み合わされたもの)から。syn(共に)+ histanai(立てる)。',
    relatedWords: ['systematic', 'structure', 'organization'],
  },
  {
    id: 'tackle',
    word: 'tackle',
    level: 'B2',
    partOfSpeech: '動詞',
    meaningsJa: ['(問題に)取り組む', '(スポーツで)タックルする'],
    pronunciation: '/ˈtækl/',
    exampleSentence: 'The government has promised to tackle climate change.',
    exampleTranslationJa: '政府は気候変動に取り組むと約束した。',
    collocations: ['tackle a problem', 'tackle crime', 'tackle an opponent'],
    relatedWords: ['deal with', 'address', 'handle'],
  },
  {
    id: 'take off',
    word: 'take off',
    level: 'B1',
    partOfSpeech: '句動詞',
    meaningsJa: ['(飛行機が)離陸する', '(服などを)脱ぐ', '(事業などが)急成長する'],
    pronunciation: '/ˌteɪk ˈɔːf/',
    exampleSentence: 'The plane will take off on time despite the rain.',
    exampleTranslationJa: '雨にもかかわらず、飛行機は定刻に離陸する予定だ。',
    collocations: ['take off your shoes', 'the plane takes off', 'sales took off'],
    relatedWords: ['land', 'remove', 'takeoff'],
  },
  {
    id: 'take over',
    word: 'take over',
    level: 'B2',
    partOfSpeech: '句動詞',
    meaningsJa: ['引き継ぐ', '(会社を)買収する、支配する'],
    pronunciation: '/ˌteɪk ˈoʊvər/',
    exampleSentence: 'She will take over the project when the manager retires.',
    exampleTranslationJa: '部長が退職したら、彼女がそのプロジェクトを引き継ぐ。',
    collocations: ['take over a company', 'take over responsibility', 'take over from someone'],
    relatedWords: ['takeover', 'replace', 'succeed'],
  },
  {
    id: 'talent',
    word: 'talent',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['才能', '才能ある人々'],
    pronunciation: '/ˈtælənt/',
    exampleSentence: 'She showed a talent for music at an early age.',
    exampleTranslationJa: '彼女は幼い頃から音楽の才能を見せた。',
    collocations: ['a talent for', 'natural talent', 'young talent'],
    etymology: 'ギリシャ語 talanton(はかり、貨幣単位)から。聖書のたとえ話を通じて「才能」の意味になった。',
    relatedWords: ['talented', 'gift', 'ability'],
  },
  {
    id: 'target',
    word: 'target',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['目標', '標的、的', '(動詞)対象にする'],
    pronunciation: '/ˈtɑːrɡɪt/',
    exampleSentence: 'Our sales target for this year is ten million yen.',
    exampleTranslationJa: '今年の売上目標は1000万円だ。',
    collocations: ['set a target', 'meet a target', 'a target audience'],
    etymology: '古フランス語 targe(小さな盾)から。「盾」から「射撃の的」へと意味が変化した。',
    relatedWords: ['goal', 'aim', 'objective'],
  },
  {
    id: 'task',
    word: 'task',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['仕事、課題、任務'],
    pronunciation: '/tæsk/',
    exampleSentence: 'My first task every morning is to check email.',
    exampleTranslationJa: '毎朝最初の仕事はメールの確認だ。',
    collocations: ['complete a task', 'a difficult task', 'daily tasks'],
    etymology: '中世ラテン語 taxa(課されたもの)から。tax(税)と同語源。',
    relatedWords: ['duty', 'assignment', 'job'],
  },
  {
    id: 'tax',
    word: 'tax',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['税、税金', '(動詞)課税する'],
    pronunciation: '/tæks/',
    exampleSentence: 'The government plans to raise the tax on cigarettes.',
    exampleTranslationJa: '政府はたばこ税を引き上げる計画だ。',
    collocations: ['pay taxes', 'raise taxes', 'income tax'],
    etymology: 'ラテン語 taxare(評価する、査定する)から。',
    relatedWords: ['taxpayer', 'income', 'duty'],
  },
  {
    id: 'technical',
    word: 'technical',
    level: 'B2',
    partOfSpeech: '形容詞',
    meaningsJa: ['技術的な、技術の', '専門的な'],
    pronunciation: '/ˈteknɪkl/',
    exampleSentence: 'The launch was delayed because of a technical problem.',
    exampleTranslationJa: '技術的な問題のため、発売は延期された。',
    collocations: ['a technical problem', 'technical support', 'technical terms'],
    etymology: 'ギリシャ語 tekhne(技術)から。technique, technology と同語源。',
    relatedWords: ['technique', 'technology', 'technically'],
  },
  {
    id: 'technique',
    word: 'technique',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['技術、技法、手法'],
    pronunciation: '/tekˈniːk/',
    exampleSentence: 'The doctor developed a new technique for treating burns.',
    exampleTranslationJa: 'その医師はやけどを治療する新しい技法を開発した。',
    collocations: ['develop a technique', 'a relaxation technique', 'basic techniques'],
    etymology: 'ギリシャ語 tekhne(技術)から。',
    relatedWords: ['technical', 'method', 'skill'],
  },
  {
    id: 'technology',
    word: 'technology',
    level: 'B1',
    partOfSpeech: '名詞',
    meaningsJa: ['科学技術、テクノロジー'],
    pronunciation: '/tekˈnɑːlədʒi/',
    exampleSentence: 'Modern technology has changed the way we communicate.',
    exampleTranslationJa: '現代の科学技術は私たちのコミュニケーションの方法を変えた。',
    collocations: ['modern technology', 'information technology', 'develop new technology'],
    wordFormation: 'techno(技術)+ -logy(学問、体系)。',
    relatedWords: ['technological', 'technical', 'science'],
  },
  {
    id: 'temporary',
    word: 'temporary',
    level: 'B1',
    partOfSpeech: '形容詞',
    meaningsJa: ['一時的な、臨時の'],
    pronunciation: '/ˈtempəreri/',
    exampleSentence: 'She found a temporary job for the summer.',
    exampleTranslationJa: '彼女は夏の間の臨時の仕事を見つけた。',
    collocations: ['a temporary job', 'a temporary solution', 'on a temporary basis'],
    etymology: 'ラテン語 tempus(時)から。contemporary と同語源。',
    relatedWords: ['temporarily', 'permanent', 'short-term'],
  },
  {
    id: 'tend',
    word: 'tend',
    level: 'B1',
    partOfSpeech: '動詞',
    meaningsJa: ['〜する傾向がある、〜しがちである'],
    pronunciation: '/tend/',
    exampleSentence: 'I tend to wake up early even on weekends.',
    exampleTranslationJa: '私は週末でも早く目が覚める傾向がある。',
    collocations: ['tend to do', 'tend to be'],
    etymology: 'ラテン語 tendere(伸ばす、向かう)から。extend, intend と同語源。',
    relatedWords: ['tendency', 'incline', 'likely'],
  },
  {
    id: 'tendency',
    word: 'tendency',
    level: 'B2',
    partOfSpeech: '名詞',
    meaningsJa: ['傾向、性向'],
    pronunciation: '/ˈtendənsi/',
    exampleSentence: 'He has a tendency to talk too much when he is nervous.',
    exampleTranslationJa: '彼は緊張するとしゃべりすぎる傾向がある。',
    collocations: ['have a tendency to', 'a growing tendency', 'a natural tendency'],
    wordFormation: 'tend(〜しがちである)+ -ency(名詞化)。',
    relatedWords: ['tend', 'trend', 'inclination'],
  },
]
