import type { VocabularyEntry } from '../types'

// 増補 第44弾。8,000語 → 8,800語 の増補の一部。m から p までの基礎語と機能語を100語。
export const plus44: VocabularyEntry[] = [
  {
    id: "magazines",
    word: "magazines",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["雑誌(複数形)"],
    pronunciation: "/ˌmæɡəˈziːnz/",
    exampleSentence: "She reads fashion magazines at the hairdresser's.",
    exampleTranslationJa: "彼女は美容院でファッション雑誌を読む。",
    collocations: ["fashion magazines", "read magazines", "a stack of magazines"],
    mnemonic: "magazine(雑誌)の複数形。本屋や待合室では複数冊まとめて目にするので、ふつうは s 付きで出会う。",
    relatedWords: ["magazine", "newspaper", "article"],
  },
  {
    id: "main",
    word: "main",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["主な、主要な", "一番大事な"],
    pronunciation: "/meɪn/",
    exampleSentence: "The main reason I called you is to say sorry.",
    exampleTranslationJa: "電話した主な理由は謝りたかったからです。",
    collocations: ["the main reason", "a main road", "the main course"],
    mnemonic: "「一番大きく中心になる」というコアイメージ。main street は町の目抜き通りを指す。",
    relatedWords: ["major", "chief", "important"],
  },
  {
    id: "man",
    word: "man",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["男性", "人、人間"],
    pronunciation: "/mæn/",
    exampleSentence: "An old man was feeding the birds in the park.",
    exampleTranslationJa: "年老いた男性が公園で鳥にえさをやっていた。",
    collocations: ["a young man", "an old man", "a man of his word"],
    mnemonic: "成人した男性を指す基本語で、複数形は man → men と母音が変わる不規則変化をする。",
    relatedWords: ["woman", "boy", "person"],
  },
  {
    id: "many",
    word: "many",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["多くの", "たくさんの"],
    pronunciation: "/ˈmeni/",
    exampleSentence: "Many students walk to school when the weather is nice.",
    exampleTranslationJa: "天気がいい日は多くの生徒が歩いて学校へ行く。",
    collocations: ["many people", "many times", "how many"],
    mnemonic: "数えられる名詞の複数形に付け「多くの」を表す。肯定文では a lot of のほうがよく使われる。",
    relatedWords: ["much", "a lot of", "few"],
  },
  {
    id: "married",
    word: "married",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["結婚している", "結婚の"],
    pronunciation: "/ˈmærid/",
    exampleSentence: "They have been married for ten years.",
    exampleTranslationJa: "彼らは結婚して10年になる。",
    collocations: ["get married", "a married couple", "be married to"],
    mnemonic: "marry(結婚する)の過去分詞から「結婚した状態」を表す。相手は be married to 人。",
    relatedWords: ["marry", "wedding", "single"],
  },
  {
    id: "match",
    word: "match",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["試合", "(色や柄が)合う、釣り合う", "マッチ(火をつける道具)"],
    pronunciation: "/mætʃ/",
    exampleSentence: "Our team won the match by two goals.",
    exampleTranslationJa: "私たちのチームは2点差で試合に勝った。",
    collocations: ["a football match", "win a match", "match the color"],
    mnemonic: "「対になるもの、張り合うもの」が核。試合という意味と、色が合うという意味に広がる。",
    relatedWords: ["game", "race", "pair"],
  },
  {
    id: "math",
    word: "math",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["数学"],
    pronunciation: "/mæθ/",
    exampleSentence: "Math is my favorite subject at school.",
    exampleTranslationJa: "数学は学校で一番好きな科目だ。",
    collocations: ["a math test", "math homework", "be good at math"],
    mnemonic: "mathematics を短くした語。米国では math、英国では maths と s が付く。",
    relatedWords: ["mathematics", "science", "subject"],
  },
  {
    id: "maybe",
    word: "maybe",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["たぶん、もしかすると"],
    pronunciation: "/ˈmeɪbi/",
    exampleSentence: "Maybe we should leave before the traffic gets bad.",
    exampleTranslationJa: "交通が混む前に出たほうがいいかもしれない。",
    collocations: ["maybe later", "maybe not", "maybe tomorrow"],
    mnemonic: "may(〜かもしれない)+ be が縮まった形。文頭に置いて、控えめに提案や推測をする。",
    relatedWords: ["perhaps", "probably", "possibly"],
  },
  {
    id: "me",
    word: "me",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["私を", "私に"],
    pronunciation: "/miː/",
    exampleSentence: "Please send me the photos from the party.",
    exampleTranslationJa: "パーティーの写真を私に送ってください。",
    collocations: ["give me", "tell me", "with me"],
    mnemonic: "I の目的格にあたる形。「私を」と「私に」の両方を担い、前置詞の後ろにも置ける。",
    relatedWords: ["I", "my", "mine"],
  },
  {
    id: "measuring cup",
    word: "measuring cup",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["計量カップ"],
    pronunciation: "/ˈmeʒərɪŋ kʌp/",
    exampleSentence: "She poured two measuring cups of flour into the bowl.",
    exampleTranslationJa: "彼女は小麦粉を計量カップ2杯分ボウルに入れた。",
    collocations: ["use a measuring cup", "a plastic measuring cup", "a measuring cup of milk"],
    mnemonic: "measure(計る)+ -ing + cup。目盛りが付いていて、料理で分量を量るためのカップ。",
    relatedWords: ["measure", "cup", "kitchen"],
  },
  {
    id: "meat",
    word: "meat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["肉", "食用の獣肉"],
    pronunciation: "/miːt/",
    exampleSentence: "We bought some meat for dinner at the market.",
    exampleTranslationJa: "夕食のために市場で肉を買った。",
    collocations: ["red meat", "cook meat", "a piece of meat"],
    mnemonic: "meet(会う)と発音が同じで、食べるほうの「肉」は ea と綴る。数えられない名詞として使う。",
    relatedWords: ["chicken", "beef", "fish"],
  },
  {
    id: "meet",
    word: "meet",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["会う、会合する", "(条件などを)満たす"],
    pronunciation: "/miːt/",
    exampleSentence: "Let's meet in front of the station at six.",
    exampleTranslationJa: "6時に駅の前で会いましょう。",
    collocations: ["meet a friend", "meet a deadline", "nice to meet you"],
    mnemonic: "「顔を合わせる」が核。meet a deadline なら「締め切りに間に合わせる」の意味になる。",
    relatedWords: ["see", "visit", "gather"],
  },
  {
    id: "member",
    word: "member",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["会員、メンバー", "一員"],
    pronunciation: "/ˈmembər/",
    exampleSentence: "She became a member of the tennis club last year.",
    exampleTranslationJa: "彼女は去年テニスクラブの会員になった。",
    collocations: ["a club member", "become a member", "a member of the team"],
    mnemonic: "「体の一部、集団を構成する一員」が原義。member of 〜 で所属する団体や組織を表す。",
    relatedWords: ["club", "group", "join"],
  },
  {
    id: "message",
    word: "message",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["伝言、メッセージ", "言いたいこと"],
    pronunciation: "/ˈmesɪdʒ/",
    exampleSentence: "He left a message on my phone this morning.",
    exampleTranslationJa: "彼は今朝、私の携帯に伝言を残した。",
    collocations: ["leave a message", "send a message", "a text message"],
    mnemonic: "「送り手から受け手へ届く短い伝え」が核。動詞にすると「伝言を送る」の意味でも使え、メールの本文も指す。",
    relatedWords: ["note", "mail", "phone"],
  },
  {
    id: "migraine",
    word: "migraine",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["片頭痛"],
    pronunciation: "/ˈmaɪɡreɪn/",
    exampleSentence: "Bright lights give her a terrible migraine.",
    exampleTranslationJa: "強い光は彼女にひどい片頭痛を起こさせる。",
    collocations: ["a migraine attack", "suffer from migraines", "a bad migraine"],
    mnemonic: "頭の片側だけが脈打つように痛む激しい頭痛。吐き気や光のまぶしさを伴うことが多い。",
    relatedWords: ["headache", "pain", "ache"],
  },
  {
    id: "mile",
    word: "mile",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["マイル(長さの単位)"],
    pronunciation: "/maɪl/",
    exampleSentence: "The beach is only a mile from our house.",
    exampleTranslationJa: "その浜辺は私たちの家から1マイルしかない。",
    collocations: ["a mile away", "miles per hour", "the last mile"],
    mnemonic: "長さの単位で1マイルは約1.6キロ。miles away で「ずっと遠くに」の意味にもなる。",
    relatedWords: ["kilometer", "meter", "distance"],
  },
  {
    id: "milk",
    word: "milk",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["牛乳、ミルク"],
    pronunciation: "/mɪlk/",
    exampleSentence: "He drinks a glass of milk before bed.",
    exampleTranslationJa: "彼は寝る前にコップ1杯の牛乳を飲む。",
    collocations: ["a glass of milk", "fresh milk", "pour milk"],
    mnemonic: "乳牛から取れる白い飲み物で、数えられない名詞。動詞で使うと「乳を搾る」の意味になる。",
    relatedWords: ["cheese", "butter", "cow"],
  },
  {
    id: "million",
    word: "million",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["100万", "多数"],
    pronunciation: "/ˈmɪljən/",
    exampleSentence: "The city has more than two million residents.",
    exampleTranslationJa: "その都市には200万人以上の住民がいる。",
    collocations: ["a million dollars", "millions of people", "two million"],
    mnemonic: "千の千倍にあたる数。hundred と違い、前に数があっても複数形の s を付けない。",
    relatedWords: ["billion", "thousand", "hundred"],
  },
  {
    id: "miss",
    word: "miss",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(人に会えず)寂しく思う", "逃す、乗り遅れる", "(的を)外す"],
    pronunciation: "/mɪs/",
    exampleSentence: "I miss my family when I travel alone.",
    exampleTranslationJa: "一人で旅をしていると家族に会えなくて寂しい。",
    collocations: ["miss the bus", "miss a chance", "miss you"],
    mnemonic: "「届かない、外れる」が核の語。会いたい人の不在を寂しく思う気持ちも miss で表す。",
    relatedWords: ["lose", "catch", "long for"],
  },
  {
    id: "mittens",
    word: "mittens",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ミトン(複数形)", "親指だけ分かれた手袋"],
    pronunciation: "/ˈmɪtnz/",
    exampleSentence: "She put on her wool mittens before going out.",
    exampleTranslationJa: "彼女は出かける前に毛糸のミトンをはめた。",
    collocations: ["wool mittens", "a pair of mittens", "put on mittens"],
    mnemonic: "親指だけ分かれ、ほかの指が1つにまとまった手袋。指が1本ずつ分かれるものは gloves。",
    relatedWords: ["gloves", "scarf", "winter"],
  },
  {
    id: "modern",
    word: "modern",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["現代の、近代的な", "最新の"],
    pronunciation: "/ˈmɑːdərn/",
    exampleSentence: "The museum is in a modern building near the river.",
    exampleTranslationJa: "その博物館は川の近くの近代的な建物にある。",
    collocations: ["modern life", "modern technology", "a modern building"],
    mnemonic: "「今の時代の、最新の」が核。反対語は old-fashioned や ancient になる。",
    relatedWords: ["new", "current", "ancient"],
  },
  {
    id: "moment",
    word: "moment",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["瞬間", "ちょっとした時間"],
    pronunciation: "/ˈmoʊmənt/",
    exampleSentence: "Wait a moment while I find my keys.",
    exampleTranslationJa: "鍵を探す間、ちょっと待ってください。",
    collocations: ["at the moment", "wait a moment", "for a moment"],
    mnemonic: "時間のごく短いひとかけら。at the moment で「今ちょうどその時」という意味になる。",
    relatedWords: ["minute", "second", "time"],
  },
  {
    id: "second-hand",
    word: "second-hand",
    level: "B1",
    partOfSpeech: "形容詞・副詞",
    meaningsJa: ["中古の、使い古しの", "中古で"],
    pronunciation: "/ˌsekəndˈhænd/",
    exampleSentence: "He bought a second-hand bike from his neighbor.",
    exampleTranslationJa: "彼は隣人から中古の自転車を買った。",
    collocations: ["second-hand clothes", "a second-hand shop", "buy second-hand"],
    mnemonic: "「2番目の手を経た」が原義で、一度使われた物を指す。店は second-hand shop。",
    relatedWords: ["used", "old", "cheap"],
  },
  {
    id: "money",
    word: "money",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["お金、金銭"],
    pronunciation: "/ˈmʌni/",
    exampleSentence: "I don't have enough money for a new phone.",
    exampleTranslationJa: "新しい携帯を買うお金が足りない。",
    collocations: ["make money", "save money", "a lot of money"],
    mnemonic: "数えられない名詞なので複数形にせず、a money とも言わない。金額は an amount of で数える。",
    relatedWords: ["cash", "coin", "pay"],
  },
  {
    id: "month",
    word: "month",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["月(暦の1か月)"],
    pronunciation: "/mʌnθ/",
    exampleSentence: "We are moving to a new flat next month.",
    exampleTranslationJa: "私たちは来月、新しいアパートに引っ越す。",
    collocations: ["last month", "next month", "once a month"],
    mnemonic: "moon(月)と同じ語源で、月が満ち欠けする1回分の期間を指す。複数形は months。",
    relatedWords: ["week", "year", "calendar"],
  },
  {
    id: "moonlight",
    word: "moonlight",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["月光、月明かり"],
    pronunciation: "/ˈmuːnlaɪt/",
    exampleSentence: "We walked along the beach in the moonlight.",
    exampleTranslationJa: "私たちは月明かりの中を浜辺に沿って歩いた。",
    collocations: ["in the moonlight", "bright moonlight", "a moonlight walk"],
    mnemonic: "moon(月)+ light(光)。in the moonlight で「月明かりの下で」の意味になる。",
    relatedWords: ["moon", "sunlight", "star"],
  },
  {
    id: "more",
    word: "more",
    level: "A2",
    partOfSpeech: "限定詞・副詞",
    meaningsJa: ["もっと多くの", "もっと、さらに"],
    pronunciation: "/mɔːr/",
    exampleSentence: "Would you like more tea or something cold?",
    exampleTranslationJa: "紅茶をもっと飲みますか、それとも冷たいものがいいですか。",
    collocations: ["more than", "a bit more", "more and more"],
    mnemonic: "many と much に共通する比較級。数えられる名詞にも数えられない名詞にも使える。",
    relatedWords: ["most", "less", "another"],
  },
  {
    id: "morning",
    word: "morning",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["朝、午前"],
    pronunciation: "/ˈmɔːrnɪŋ/",
    exampleSentence: "I usually go running early in the morning.",
    exampleTranslationJa: "私はふつう朝早く走りに行く。",
    collocations: ["in the morning", "good morning", "every morning"],
    mnemonic: "朝という時間帯を表すので前置詞は in を使う。時刻の一点を指す at とは役割が違う。",
    relatedWords: ["afternoon", "evening", "night"],
  },
  {
    id: "most",
    word: "most",
    level: "A2",
    partOfSpeech: "限定詞・副詞",
    meaningsJa: ["ほとんどの", "最も、一番"],
    pronunciation: "/moʊst/",
    exampleSentence: "Most of my friends live near the station.",
    exampleTranslationJa: "私の友達のほとんどは駅の近くに住んでいる。",
    collocations: ["most of the time", "most people", "the most important"],
    mnemonic: "many と much に共通する最上級の語。most of the 〜 で「〜の大部分」を表す。",
    relatedWords: ["more", "almost", "mainly"],
  },
  {
    id: "mother",
    word: "mother",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["母、お母さん"],
    pronunciation: "/ˈmʌðər/",
    exampleSentence: "My mother taught me how to cook rice.",
    exampleTranslationJa: "母は私にご飯の炊き方を教えてくれた。",
    collocations: ["my mother", "a mother of two", "mother tongue"],
    mnemonic: "「母」を表す基本語。父は father、両親は parents と複数形でまとめて表す。",
    relatedWords: ["father", "parent", "mum"],
  },
  {
    id: "mountain",
    word: "mountain",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["山", "山岳"],
    pronunciation: "/ˈmaʊntn/",
    exampleSentence: "They climbed the mountain in six hours.",
    exampleTranslationJa: "彼らは6時間でその山を登った。",
    collocations: ["climb a mountain", "a mountain range", "the top of the mountain"],
    mnemonic: "高くそびえる山を指す語。丘を表す hill より大きく、岩がちで険しいものをいう。",
    relatedWords: ["hill", "valley", "peak"],
  },
  {
    id: "mouth",
    word: "mouth",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["口", "(川の)河口"],
    pronunciation: "/maʊθ/",
    exampleSentence: "He burned his mouth on the hot soup.",
    exampleTranslationJa: "彼は熱いスープで口をやけどした。",
    collocations: ["open your mouth", "by word of mouth", "the mouth of a river"],
    mnemonic: "複数形は mouths で語尾が「ズ」と濁って読まれる。川が海に出る口も mouth と呼ぶ。",
    relatedWords: ["lip", "tongue", "tooth"],
  },
  {
    id: "mouthful",
    word: "mouthful",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ひと口", "ひと口分"],
    pronunciation: "/ˈmaʊθfʊl/",
    exampleSentence: "She took a mouthful of water and ran on.",
    exampleTranslationJa: "彼女は水をひと口含んで走り続けた。",
    collocations: ["a mouthful of rice", "take a mouthful", "a big mouthful"],
    mnemonic: "mouth(口)+ -ful(いっぱいの量)。spoonful や handful と同じ作り方の語。",
    relatedWords: ["handful", "spoonful", "bite"],
  },
  {
    id: "movie",
    word: "movie",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["映画"],
    pronunciation: "/ˈmuːvi/",
    exampleSentence: "We watched a funny movie at home last night.",
    exampleTranslationJa: "昨夜は家でおかしな映画を観た。",
    collocations: ["watch a movie", "a movie star", "go to the movies"],
    mnemonic: "moving picture(動く映像)を短くした語。英国では film のほうがよく使われる。",
    relatedWords: ["film", "cinema", "actor"],
  },
  {
    id: "mr",
    word: "mr",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["〜さん、〜氏(男性の姓に付ける敬称)"],
    pronunciation: "/ˈmɪstər/",
    exampleSentence: "Mr Brown lives next door with his two sons.",
    exampleTranslationJa: "ブラウンさんは息子2人と隣に住んでいる。",
    collocations: ["Mr Smith", "Mr and Mrs Green", "dear Mr Brown"],
    mnemonic: "男性の姓の前に付ける敬称で、mister と読む。下の名前だけには付けない決まりがある。",
    relatedWords: ["mrs", "ms", "sir"],
  },
  {
    id: "mrs",
    word: "mrs",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["〜夫人、〜さん(既婚の女性に付ける敬称)"],
    pronunciation: "/ˈmɪsɪz/",
    exampleSentence: "Mrs Green teaches history at our school.",
    exampleTranslationJa: "グリーン先生は私たちの学校で歴史を教えている。",
    collocations: ["Mrs Smith", "Mr and Mrs Green", "dear Mrs Brown"],
    mnemonic: "既婚の女性の姓に付ける敬称で、missis と読む。Mr と対になって使われる言い方。",
    relatedWords: ["mr", "ms", "madam"],
  },
  {
    id: "ms",
    word: "ms",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["〜さん(既婚・未婚を問わない女性の敬称)"],
    pronunciation: "/mɪz/",
    exampleSentence: "Ms Lee is the new manager of the shop.",
    exampleTranslationJa: "リーさんは店の新しい責任者だ。",
    collocations: ["Ms Smith", "Ms Jones and Ms Lee", "dear Ms Brown"],
    mnemonic: "既婚か未婚かを示さない女性の敬称で、mizz と読む。男性の Mr と対になる言い方。",
    relatedWords: ["mr", "mrs", "name"],
  },
  {
    id: "much",
    word: "much",
    level: "A2",
    partOfSpeech: "限定詞・副詞",
    meaningsJa: ["多くの", "ずっと、とても"],
    pronunciation: "/mʌtʃ/",
    exampleSentence: "I don't have much time this afternoon.",
    exampleTranslationJa: "今日の午後はあまり時間がない。",
    collocations: ["how much", "too much", "so much"],
    mnemonic: "数えられない名詞に付けるのが原則で、数えられる名詞には many を使い分ける。値段は how much と尋ねる。",
    relatedWords: ["many", "little", "a lot of"],
  },
  {
    id: "mum",
    word: "mum",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["お母さん"],
    pronunciation: "/mʌm/",
    exampleSentence: "My mum makes the best soup in the world.",
    exampleTranslationJa: "母は世界で一番おいしいスープを作る。",
    collocations: ["my mum", "mum and dad", "ask your mum"],
    mnemonic: "英国でよく使う「お母さん」にあたる語。米国では mom と綴り、発音も少し変わる。",
    relatedWords: ["mom", "mother", "dad"],
  },
  {
    id: "music",
    word: "music",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["音楽"],
    pronunciation: "/ˈmjuːzɪk/",
    exampleSentence: "She listens to music while she studies.",
    exampleTranslationJa: "彼女は勉強しながら音楽を聴く。",
    collocations: ["listen to music", "pop music", "a music teacher"],
    mnemonic: "数えられない名詞なので a music とは言わず、数えるときは a piece of music と表現する。",
    relatedWords: ["song", "band", "sing"],
  },
  {
    id: "must",
    word: "must",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜しなければならない", "〜にちがいない"],
    pronunciation: "/mʌst/",
    exampleSentence: "You must show your ticket before you get on.",
    exampleTranslationJa: "乗る前に切符を見せなければなりません。",
    collocations: ["must be", "must not", "you must remember"],
    mnemonic: "話し手の強い義務や確信を表す。過去や未来の内容は have to で代用する。否定の must not は「してはいけない」。",
    relatedWords: ["should", "have to", "may"],
  },
  {
    id: "my",
    word: "my",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["私の"],
    pronunciation: "/maɪ/",
    exampleSentence: "My brother works in a bank in the city.",
    exampleTranslationJa: "私の兄は市内の銀行で働いている。",
    collocations: ["my name", "my own", "in my opinion"],
    mnemonic: "I の所有格にあたる語で、必ず名詞の前に置く。単独で使う形は mine になる。",
    relatedWords: ["I", "me", "mine"],
  },
  {
    id: "name",
    word: "name",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["名前", "名づける、名前を言う"],
    pronunciation: "/neɪm/",
    exampleSentence: "Please write your name at the top of the page.",
    exampleTranslationJa: "ページの上のほうに名前を書いてください。",
    collocations: ["first name", "in the name of", "name a baby"],
    mnemonic: "人や物の「呼び名」が核の語。姓名を書くときは名を先に、姓を後に置くのが英語の基本の順。",
    relatedWords: ["surname", "call", "title"],
  },
  {
    id: "nappy",
    word: "nappy",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["おむつ"],
    pronunciation: "/ˈnæpi/",
    exampleSentence: "The baby needs a clean nappy.",
    exampleTranslationJa: "赤ちゃんはきれいなおむつが必要だ。",
    collocations: ["change a nappy", "a clean nappy", "disposable nappies"],
    mnemonic: "英国で使う「おむつ」にあたる語。米国では同じ物を diaper と呼ぶことが多い。",
    relatedWords: ["baby", "diaper", "change"],
  },
  {
    id: "nausea",
    word: "nausea",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["吐き気、むかつき"],
    pronunciation: "/ˈnɔːziə/",
    exampleSentence: "The smell of petrol gave me nausea.",
    exampleTranslationJa: "ガソリンのにおいで吐き気がした。",
    collocations: ["a feeling of nausea", "cause nausea", "waves of nausea"],
    mnemonic: "吐きそうな気分を指す名詞。形容詞は nauseous で「吐き気がする」の意味になる。",
    relatedWords: ["sick", "vomit", "illness"],
  },
  {
    id: "near",
    word: "near",
    level: "A2",
    partOfSpeech: "前置詞・形容詞",
    meaningsJa: ["〜の近くに", "近い"],
    pronunciation: "/nɪr/",
    exampleSentence: "There is a small bakery near my office.",
    exampleTranslationJa: "私の会社の近くに小さなパン屋がある。",
    collocations: ["near the station", "near here", "in the near future"],
    mnemonic: "「距離が短い」がコアイメージ。nearby は「すぐ近くの」を表す形容詞・副詞で、next to は「すぐ隣に」。",
    relatedWords: ["close", "beside", "next to"],
  },
  {
    id: "neighbor",
    word: "neighbor",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["隣人", "近所の人"],
    pronunciation: "/ˈneɪbər/",
    exampleSentence: "Our neighbor helped us move the heavy sofa.",
    exampleTranslationJa: "近所の人が重いソファを運ぶのを手伝ってくれた。",
    collocations: ["my next-door neighbor", "a good neighbor", "neighbor countries"],
    mnemonic: "「近くに住む人」が原義。英国式の綴りでは neighbour と u が入り、発音は同じ。",
    relatedWords: ["neighborhood", "neighbour", "local"],
  },
  {
    id: "neighborhood",
    word: "neighborhood",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["近所、地域"],
    pronunciation: "/ˈneɪbərhʊd/",
    exampleSentence: "We moved to a quiet neighborhood last spring.",
    exampleTranslationJa: "私たちは去年の春、静かな地域に引っ越した。",
    collocations: ["a quiet neighborhood", "in my neighborhood", "a poor neighborhood"],
    mnemonic: "neighbor(隣人)+ -hood(状態・集まり)。近所の人たちが住む一帯を指す。",
    relatedWords: ["neighbor", "area", "district"],
  },
  {
    id: "neighborhoods",
    word: "neighborhoods",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["近所、地域(複数形)"],
    pronunciation: "/ˈneɪbərhʊdz/",
    exampleSentence: "Some neighborhoods in the city are very noisy.",
    exampleTranslationJa: "その市のいくつかの地区はとても騒がしい。",
    collocations: ["different neighborhoods", "visit neighborhoods", "quiet neighborhoods"],
    mnemonic: "neighborhood(近所)の複数形。いくつかの地域を並べて比べるときに使う形。",
    relatedWords: ["neighborhood", "area", "town"],
  },
  {
    id: "never",
    word: "never",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["決して〜ない", "一度も〜ない"],
    pronunciation: "/ˈnevər/",
    exampleSentence: "I have never seen snow in this town.",
    exampleTranslationJa: "私はこの町で雪を見たことが一度もない。",
    collocations: ["never again", "never mind", "never before"],
    mnemonic: "not と ever が合わさった意味で、頻度が0であることを表す。never mind は「気にしないで」。",
    relatedWords: ["ever", "always", "sometimes"],
  },
  {
    id: "new",
    word: "new",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["新しい", "新品の"],
    pronunciation: "/nuː/",
    exampleSentence: "She bought a new coat for the winter.",
    exampleTranslationJa: "彼女は冬用に新しいコートを買った。",
    collocations: ["brand new", "a new job", "new to"],
    mnemonic: "「今までになかった」が核。新品であることを強めるときは brand new と言う。",
    relatedWords: ["old", "recent", "fresh"],
  },
  {
    id: "news",
    word: "news",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ニュース", "知らせ"],
    pronunciation: "/nuːz/",
    exampleSentence: "The news about the storm surprised everyone.",
    exampleTranslationJa: "嵐の知らせにみんな驚いた。",
    collocations: ["good news", "the news", "a piece of news"],
    mnemonic: "綴りは s で終わるが数えられない名詞。動詞は単数扱いにし、1つは a piece of news と数える。",
    relatedWords: ["newspaper", "report", "information"],
  },
  {
    id: "newspaper",
    word: "newspaper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["新聞"],
    pronunciation: "/ˈnuːzpeɪpər/",
    exampleSentence: "He reads the newspaper on the train every day.",
    exampleTranslationJa: "彼は毎日電車で新聞を読む。",
    collocations: ["a daily newspaper", "read the newspaper", "a newspaper article"],
    mnemonic: "news(知らせ)+ paper(紙)からなり、新しい知らせを印刷した紙が原義の語。",
    relatedWords: ["news", "article", "magazine"],
  },
  {
    id: "nice",
    word: "nice",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よい、感じのよい", "親切な"],
    pronunciation: "/naɪs/",
    exampleSentence: "It was nice of you to help me yesterday.",
    exampleTranslationJa: "昨日は手伝ってくれて親切でした。",
    collocations: ["nice to meet you", "a nice day", "nice and warm"],
    mnemonic: "人にも物にも使える褒め言葉。nice and warm で「ちょうどよく暖かい」を表す。",
    relatedWords: ["kind", "pleasant", "lovely"],
  },
  {
    id: "night",
    word: "night",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["夜", "夜間"],
    pronunciation: "/naɪt/",
    exampleSentence: "The baby cried three times during the night.",
    exampleTranslationJa: "赤ちゃんは夜の間に3回泣いた。",
    collocations: ["at night", "last night", "stay the night"],
    mnemonic: "前置詞は at night と at を使う。good night は寝る前や別れのあいさつ。",
    relatedWords: ["day", "evening", "dark"],
  },
  {
    id: "nine",
    word: "nine",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["9、九", "9つ"],
    pronunciation: "/naɪn/",
    exampleSentence: "The shop opens at nine in the morning.",
    exampleTranslationJa: "その店は朝9時に開く。",
    collocations: ["nine o'clock", "nine years old", "number nine"],
    mnemonic: "nine(9)に -teen を付けると19、-ty を付けると90になる。語尾の e は読まない。",
    relatedWords: ["nineteen", "ninety", "ninth"],
  },
  {
    id: "nineteen",
    word: "nineteen",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["19、十九", "19歳"],
    pronunciation: "/ˌnaɪnˈtiːn/",
    exampleSentence: "She was nineteen when she moved to Japan.",
    exampleTranslationJa: "彼女は19歳のときに日本へ引っ越した。",
    collocations: ["turn nineteen", "nineteen years old", "at nineteen"],
    mnemonic: "nine + -teen の作り。13から19までの数は、最後の音節に強勢を置いて読む。",
    relatedWords: ["nine", "ninety", "teenager"],
  },
  {
    id: "ninety",
    word: "ninety",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["90、九十", "90歳"],
    pronunciation: "/ˈnaɪnti/",
    exampleSentence: "My grandmother is ninety and still drives.",
    exampleTranslationJa: "祖母は90歳でまだ車を運転する。",
    collocations: ["ninety years old", "in his nineties", "around ninety"],
    mnemonic: "nine + -ty の作り。nineteen と違い、語尾の e を落として綴るのがポイントになる。",
    relatedWords: ["nine", "nineteen", "eighty"],
  },
  {
    id: "ninth",
    word: "ninth",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["9番目の", "9分の1"],
    pronunciation: "/naɪnθ/",
    exampleSentence: "She came ninth in the national competition.",
    exampleTranslationJa: "彼女は全国大会で9位だった。",
    collocations: ["the ninth of May", "come ninth", "a ninth of the total"],
    mnemonic: "nine + -th で e が落ちて ninth になる。the ninth of May で「5月9日」を表す。",
    relatedWords: ["nine", "number", "order"],
  },
  {
    id: "no",
    word: "no",
    level: "A2",
    partOfSpeech: "限定詞・間投詞",
    meaningsJa: ["1つも〜ない", "いいえ"],
    pronunciation: "/noʊ/",
    exampleSentence: "There is no milk left in the fridge.",
    exampleTranslationJa: "冷蔵庫に牛乳がもう残っていない。",
    collocations: ["no problem", "no one", "no longer"],
    mnemonic: "名詞の前に置くと「1つもない」を表す。返事として使うと「いいえ」の意味になり、no one は「だれも〜ない」。",
    relatedWords: ["not", "none", "never"],
  },
  {
    id: "nobody",
    word: "nobody",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["だれも〜ない"],
    pronunciation: "/ˈnoʊbədi/",
    exampleSentence: "Nobody knew the answer to the last question.",
    exampleTranslationJa: "最後の問題の答えをだれも知らなかった。",
    collocations: ["nobody knows", "nobody else", "nobody at all"],
    mnemonic: "no + body(人)でできた語で、文の主語にもなる。後ろに not は重ねない。",
    relatedWords: ["anybody", "somebody", "everybody"],
  },
  {
    id: "north",
    word: "north",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["北", "北の、北部の"],
    pronunciation: "/nɔːrθ/",
    exampleSentence: "Their farm is in the north of the country.",
    exampleTranslationJa: "彼らの農場はその国の北部にある。",
    collocations: ["in the north", "north of the city", "the North Pole"],
    mnemonic: "方角の北を表す基本語。the north of 〜 で「〜の北部」を指し、副詞としても使える。",
    relatedWords: ["south", "east", "west"],
  },
  {
    id: "nose",
    word: "nose",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["鼻"],
    pronunciation: "/noʊz/",
    exampleSentence: "The boy wiped his nose with a tissue.",
    exampleTranslationJa: "その男の子はティッシュで鼻をかんだ。",
    collocations: ["a runny nose", "blow your nose", "a blocked nose"],
    mnemonic: "顔の真ん中にあり、においをかぐ器官。語尾の e は読まず「ノウズ」と濁って発音し、複数形は noses。",
    relatedWords: ["ear", "eye", "smell"],
  },
  {
    id: "not",
    word: "not",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["〜でない", "〜しない"],
    pronunciation: "/nɑːt/",
    exampleSentence: "He is not coming to the meeting today.",
    exampleTranslationJa: "彼は今日の会議には来ない。",
    collocations: ["not at all", "not only", "why not"],
    mnemonic: "do・does・did と組んで動詞を打ち消す。not at all は「どういたしまして」の意味でも使う。",
    relatedWords: ["no", "never", "none"],
  },
  {
    id: "nothing",
    word: "nothing",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["何も〜ない", "無、取るに足らないもの"],
    pronunciation: "/ˈnʌθɪŋ/",
    exampleSentence: "There is nothing in the box but old photos.",
    exampleTranslationJa: "箱の中には古い写真のほか何も入っていない。",
    collocations: ["nothing else", "nothing at all", "have nothing to do"],
    mnemonic: "no + thing(もの)からなる語。文全体を否定するので後ろに not を重ねない。",
    relatedWords: ["nobody", "anything", "something"],
  },
  {
    id: "directions",
    word: "directions",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["道順、行き方", "指示、使い方"],
    pronunciation: "/dəˈrekʃnz/",
    exampleSentence: "Could you give me directions to the nearest bank?",
    exampleTranslationJa: "一番近い銀行への行き方を教えていただけますか。",
    collocations: ["ask for directions", "give directions", "follow the directions"],
    mnemonic: "direction(方向・指示)の複数形。道を尋ねるときは複数形で使うのがふつう。",
    relatedWords: ["direction", "map", "route"],
  },
  {
    id: "nun",
    word: "nun",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["修道女、尼僧"],
    pronunciation: "/nʌn/",
    exampleSentence: "The old nun taught at the village school.",
    exampleTranslationJa: "その年老いた修道女は村の学校で教えていた。",
    collocations: ["a Catholic nun", "become a nun", "a nun's habit"],
    mnemonic: "修道院で暮らし、祈りに生きる女性。男性の修道士は monk、修道服は habit という。",
    relatedWords: ["monk", "church", "prayer"],
  },
  {
    id: "moisture",
    word: "moisture",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["湿気、水分"],
    pronunciation: "/ˈmɔɪstʃər/",
    exampleSentence: "The cream keeps moisture in your skin.",
    exampleTranslationJa: "そのクリームは肌の水分を保つ。",
    collocations: ["traces of moisture", "moisture in the air", "keep moisture in"],
    mnemonic: "moist(しっとりした)+ -ure(状態・性質)。空気や肌に含まれる水分を指す。",
    relatedWords: ["moist", "damp", "humidity"],
  },
  {
    id: "of",
    word: "of",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜の", "〜のうちの、〜から"],
    pronunciation: "/əv/",
    exampleSentence: "The roof of the old house needs repairing.",
    exampleTranslationJa: "その古い家の屋根は修理が必要だ。",
    collocations: ["a lot of", "of course", "the end of the story"],
    mnemonic: "「〜に属する」が核で、所有・部分・材料など幅広くつなぐ前置詞。文中では弱く読んで「アヴ」と濁る。",
    relatedWords: ["from", "about", "for"],
  },
  {
    id: "off",
    word: "off",
    level: "A2",
    partOfSpeech: "副詞・前置詞",
    meaningsJa: ["(電源が)切れて", "〜から離れて", "休みで"],
    pronunciation: "/ɔːf/",
    exampleSentence: "Please turn off the lights when you leave.",
    exampleTranslationJa: "出るときは電気を消してください。",
    collocations: ["turn off", "off work", "off the road"],
    mnemonic: "of と1字違いの語で、on の反対にあたる。離れることと電源が切れた状態を表す。",
    relatedWords: ["on", "of", "away"],
  },
  {
    id: "office",
    word: "office",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["事務所、会社", "役所、窓口"],
    pronunciation: "/ˈɔːfɪs/",
    exampleSentence: "She works in an office near the station.",
    exampleTranslationJa: "彼女は駅の近くの事務所で働いている。",
    collocations: ["go to the office", "office work", "a post office"],
    mnemonic: "「仕事をする場所」が核。post office は郵便局を指し、その窓口の意味でも使う。",
    relatedWords: ["work", "desk", "company"],
  },
  {
    id: "often",
    word: "often",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["しばしば、よく"],
    pronunciation: "/ˈɔːfn/",
    exampleSentence: "We often eat out on Friday evenings.",
    exampleTranslationJa: "私たちは金曜の夕方によく外食する。",
    collocations: ["quite often", "how often", "more often than not"],
    mnemonic: "頻度を表す副詞で、always と sometimes の間にあたる。t は読んでも読まなくてもよい。",
    relatedWords: ["always", "usually", "sometimes"],
  },
  {
    id: "oh",
    word: "oh",
    level: "A2",
    partOfSpeech: "間投詞",
    meaningsJa: ["ああ、おや", "あっ"],
    pronunciation: "/oʊ/",
    exampleSentence: "Oh, I left my umbrella on the bus.",
    exampleTranslationJa: "ああ、バスに傘を忘れてしまった。",
    collocations: ["oh no", "oh dear", "oh well"],
    mnemonic: "驚きや気づきを表す短い叫びの語。oh no で「しまった」という気持ちを伝えられる。",
    relatedWords: ["ah", "wow", "well"],
  },
  {
    id: "ok",
    word: "ok",
    level: "A2",
    partOfSpeech: "形容詞・間投詞",
    meaningsJa: ["大丈夫な、問題ない", "はい、いいですよ"],
    pronunciation: "/ˌoʊˈkeɪ/",
    exampleSentence: "Is it ok if I open the window?",
    exampleTranslationJa: "窓を開けてもいいですか。",
    collocations: ["that's ok", "ok with me", "ok, let's go"],
    mnemonic: "同意や「大丈夫」を表すくだけた語。大文字で OK と書くことも多く、文頭にも置ける。",
    relatedWords: ["fine", "sure", "alright"],
  },
  {
    id: "old",
    word: "old",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["年老いた", "古い、昔の"],
    pronunciation: "/oʊld/",
    exampleSentence: "My grandfather is too old to drive at night.",
    exampleTranslationJa: "祖父は年を取りすぎて夜は運転できない。",
    collocations: ["how old", "an old friend", "old age"],
    mnemonic: "年齢にも物の古さにも使える語。人には young、物には new が反対語になる。how old は年齢を尋ねる言い方。",
    relatedWords: ["young", "new", "ancient"],
  },
  {
    id: "on",
    word: "on",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜の上に", "(電源が)入って", "〜について"],
    pronunciation: "/ɑːn/",
    exampleSentence: "Your keys are on the kitchen table.",
    exampleTranslationJa: "鍵は台所のテーブルの上にある。",
    collocations: ["on the table", "turn on", "on time"],
    mnemonic: "「接触して上にある」感じがコアイメージ。曜日や日付にも使い、電源が入っている状態も表す。",
    relatedWords: ["in", "off", "above"],
  },
  {
    id: "one",
    word: "one",
    level: "A2",
    partOfSpeech: "数詞・代名詞",
    meaningsJa: ["1、1つ", "人、だれか"],
    pronunciation: "/wʌn/",
    exampleSentence: "Only one student passed the difficult test.",
    exampleTranslationJa: "難しい試験に合格した生徒は1人だけだった。",
    collocations: ["one by one", "one day", "one of the best"],
    mnemonic: "数を数える最初の語。one by one で「1つずつ」、one day で「いつか」を表す。",
    relatedWords: ["two", "first", "once"],
  },
  {
    id: "online",
    word: "online",
    level: "A2",
    partOfSpeech: "形容詞・副詞",
    meaningsJa: ["オンラインの", "ネット上で"],
    pronunciation: "/ˌɑːnˈlaɪn/",
    exampleSentence: "I bought these shoes online last week.",
    exampleTranslationJa: "この靴は先週ネットで買った。",
    collocations: ["shop online", "an online course", "go online"],
    mnemonic: "on + line(回線)からなる語。回線につながった状態を指し、反対は offline。",
    relatedWords: ["internet", "website", "offline"],
  },
  {
    id: "only",
    word: "only",
    level: "A2",
    partOfSpeech: "副詞・形容詞",
    meaningsJa: ["ただ〜だけ", "唯一の"],
    pronunciation: "/ˈoʊnli/",
    exampleSentence: "She only drinks coffee in the morning.",
    exampleTranslationJa: "彼女は朝はコーヒーしか飲まない。",
    collocations: ["only a few", "the only one", "not only"],
    mnemonic: "「それだけ」と限定する語。置く位置で焦点が変わり、the only は「唯一の」を表す。",
    relatedWords: ["just", "alone", "single"],
  },
  {
    id: "open",
    word: "open",
    level: "A2",
    partOfSpeech: "動詞・形容詞",
    meaningsJa: ["開ける、開く", "開いている"],
    pronunciation: "/ˈoʊpən/",
    exampleSentence: "Could you open the door for me?",
    exampleTranslationJa: "ドアを開けてもらえますか。",
    collocations: ["open a window", "an open door", "open to the public"],
    mnemonic: "動詞と形容詞を兼ねる語。反対語は close(閉める)と closed(閉まった)。",
    relatedWords: ["close", "closed", "shut"],
  },
  {
    id: "opinion",
    word: "opinion",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["意見、考え", "世論"],
    pronunciation: "/əˈpɪnjən/",
    exampleSentence: "In my opinion, this plan is too expensive.",
    exampleTranslationJa: "私の意見では、この計画は費用がかかりすぎる。",
    collocations: ["in my opinion", "a strong opinion", "public opinion"],
    mnemonic: "「心に抱いている考え」が核。in my opinion と断ってから自分の意見を述べる。",
    relatedWords: ["idea", "view", "thought"],
  },
  {
    id: "opposite",
    word: "opposite",
    level: "A2",
    partOfSpeech: "形容詞・前置詞",
    meaningsJa: ["反対の", "〜の向かいに", "正反対のもの"],
    pronunciation: "/ˈɑːpəzɪt/",
    exampleSentence: "The bank is opposite the post office.",
    exampleTranslationJa: "銀行は郵便局の向かいにある。",
    collocations: ["the opposite side", "opposite each other", "the opposite of"],
    mnemonic: "「向かい合って反対の位置」が核。前置詞で「〜の向かいに」、名詞で「正反対のもの」を表す。",
    relatedWords: ["across", "against", "reverse"],
  },
  {
    id: "or",
    word: "or",
    level: "A2",
    partOfSpeech: "接続詞",
    meaningsJa: ["または、それとも", "〜かどうか"],
    pronunciation: "/ɔːr/",
    exampleSentence: "Would you like tea or coffee with your cake?",
    exampleTranslationJa: "ケーキと一緒に紅茶かコーヒーはいかがですか。",
    collocations: ["either or", "or so", "or else"],
    mnemonic: "選択肢をつなぐ接続詞。否定文の中では and の代わりに使われるという特徴がある。",
    relatedWords: ["and", "but", "either"],
  },
  {
    id: "orange",
    word: "orange",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["オレンジ", "オレンジ色の"],
    pronunciation: "/ˈɔːrɪndʒ/",
    exampleSentence: "She peeled an orange for the children.",
    exampleTranslationJa: "彼女は子どもたちのためにオレンジの皮をむいた。",
    collocations: ["orange juice", "peel an orange", "an orange tree"],
    mnemonic: "果物と色の両方を指す語。語頭の o は「オ」と長めに強く読み、語尾の ge は「ジ」と発音する。",
    relatedWords: ["fruit", "juice", "lemon"],
  },
  {
    id: "order",
    word: "order",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["注文", "順序、整理", "命じる"],
    pronunciation: "/ˈɔːrdər/",
    exampleSentence: "We placed an order for two pizzas.",
    exampleTranslationJa: "私たちはピザを2枚注文した。",
    collocations: ["place an order", "in order to", "out of order"],
    mnemonic: "「並べること」が核で、順序・命令・注文に意味が広がる。in order to は「〜するために」。",
    relatedWords: ["arrange", "ask", "request"],
  },
  {
    id: "other",
    word: "other",
    level: "A2",
    partOfSpeech: "形容詞・代名詞",
    meaningsJa: ["ほかの、別の", "もう一方の"],
    pronunciation: "/ˈʌðər/",
    exampleSentence: "Do you have this shirt in other colors?",
    exampleTranslationJa: "このシャツのほかの色はありますか。",
    collocations: ["other people", "each other", "on the other hand"],
    mnemonic: "「それ以外のもの」を指す語。複数形の others は名詞の代わりに単独で使える。",
    relatedWords: ["another", "else", "different"],
  },
  {
    id: "our",
    word: "our",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["私たちの"],
    pronunciation: "/ˈaʊər/",
    exampleSentence: "Our neighbors invited us to dinner.",
    exampleTranslationJa: "近所の人が夕食に招いてくれた。",
    collocations: ["our house", "our own", "in our opinion"],
    mnemonic: "we の所有格にあたる語で、必ず名詞の前に置く。単独で使う形は ours になる。",
    relatedWords: ["we", "us", "ours"],
  },
  {
    id: "out",
    word: "out",
    level: "A2",
    partOfSpeech: "副詞・前置詞",
    meaningsJa: ["外へ、外に", "なくなって"],
    pronunciation: "/aʊt/",
    exampleSentence: "He went out without saying a word.",
    exampleTranslationJa: "彼は何も言わずに出て行った。",
    collocations: ["go out", "find out", "out of order"],
    mnemonic: "in の反対にあたり「外へ」を表す語。go out で「外出する」、find out で「見つける」。",
    relatedWords: ["in", "outside", "away"],
  },
  {
    id: "oven glove",
    word: "oven glove",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["鍋つかみ、オーブンミトン"],
    pronunciation: "/ˈʌvn ɡlʌv/",
    exampleSentence: "Use an oven glove to lift the hot dish.",
    exampleTranslationJa: "熱い皿を持つときは鍋つかみを使いなさい。",
    collocations: ["a pair of oven gloves", "wear an oven glove", "a thick oven glove"],
    mnemonic: "oven(オーブン)+ glove(手袋)。熱い天板や皿をつかむための厚い手袋を指す。",
    relatedWords: ["oven", "gloves", "kitchen"],
  },
  {
    id: "over",
    word: "over",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜の上を越えて", "終わって", "〜を超えて"],
    pronunciation: "/ˈoʊvər/",
    exampleSentence: "The plane flew over the mountains at night.",
    exampleTranslationJa: "飛行機は夜、山の上を飛んでいった。",
    collocations: ["all over the world", "over there", "be over"],
    mnemonic: "「上を越えていく」がコアイメージ。会話では be over で「終わった」の意味になる。",
    relatedWords: ["above", "across", "under"],
  },
  {
    id: "page",
    word: "page",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ページ"],
    pronunciation: "/peɪdʒ/",
    exampleSentence: "Turn to page twenty in your book.",
    exampleTranslationJa: "本の20ページを開いてください。",
    collocations: ["the first page", "turn the page", "on page ten"],
    mnemonic: "本や新聞の1枚の面を指す語。turn the page で「ページをめくる」の意味になる。",
    relatedWords: ["book", "line", "sheet"],
  },
  {
    id: "paint",
    word: "paint",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["塗る、描く", "ペンキ、絵の具"],
    pronunciation: "/peɪnt/",
    exampleSentence: "They painted the kitchen walls light blue.",
    exampleTranslationJa: "彼らは台所の壁を淡い青に塗った。",
    collocations: ["paint a wall", "a coat of paint", "paint a picture"],
    mnemonic: "名詞では液体の塗料を指し、絵の具も同じ語で表す。動詞では「塗る」「描く」の意味になり、painter は絵を描く人。",
    relatedWords: ["painting", "color", "draw"],
  },
  {
    id: "paintbrush",
    word: "paintbrush",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["絵筆、はけ"],
    pronunciation: "/ˈpeɪntbrʌʃ/",
    exampleSentence: "He cleaned his paintbrush in the sink.",
    exampleTranslationJa: "彼は流しで絵筆を洗った。",
    collocations: ["a soft paintbrush", "clean a paintbrush", "a wide paintbrush"],
    mnemonic: "paint(塗る)+ brush(はけ)。絵の具用の筆と、壁塗り用のはけの両方を指す。",
    relatedWords: ["paint", "brush", "art"],
  },
  {
    id: "pair",
    word: "pair",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["1組、1対", "2人組"],
    pronunciation: "/per/",
    exampleSentence: "She bought a new pair of shoes yesterday.",
    exampleTranslationJa: "彼女は昨日新しい靴を1足買った。",
    collocations: ["a pair of shoes", "a pair of glasses", "in pairs"],
    mnemonic: "2つで1組になるものを数える語。靴は a pair of で数え、人なら2人組を指す。",
    relatedWords: ["double", "both", "couple"],
  },
  {
    id: "panda",
    word: "panda",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パンダ"],
    pronunciation: "/ˈpændə/",
    exampleSentence: "The panda at the zoo eats bamboo all day.",
    exampleTranslationJa: "動物園のパンダは一日中竹を食べている。",
    collocations: ["a giant panda", "a baby panda", "feed a panda"],
    mnemonic: "白黒の体毛を持つ中国原産の動物で、竹を主食にする。ジャイアントパンダが特に有名で、動物園の人気者。",
    relatedWords: ["bear", "zoo", "bamboo"],
  },
  {
    id: "paper",
    word: "paper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["紙", "新聞、論文"],
    pronunciation: "/ˈpeɪpər/",
    exampleSentence: "Write your answers on a sheet of paper.",
    exampleTranslationJa: "答えを紙1枚に書きなさい。",
    collocations: ["a sheet of paper", "a paper bag", "toilet paper"],
    mnemonic: "数えられない名詞なので、1枚と数えるときは a sheet of paper と表現する。",
    relatedWords: ["sheet", "newspaper", "card"],
  },
  {
    id: "parent",
    word: "parent",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["親"],
    pronunciation: "/ˈperənt/",
    exampleSentence: "Her parents came to watch the school play.",
    exampleTranslationJa: "彼女の両親は学校の劇を見に来た。",
    collocations: ["my parents", "a single parent", "parent and child"],
    mnemonic: "父か母のどちらか一方を指す語。複数形の parents にすると「両親」の意味になる。",
    relatedWords: ["mother", "father", "family"],
  },
  {
    id: "park",
    word: "park",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["公園", "駐車する"],
    pronunciation: "/pɑːrk/",
    exampleSentence: "We had a picnic in the park on Sunday.",
    exampleTranslationJa: "私たちは日曜に公園でピクニックをした。",
    collocations: ["a city park", "park the car", "a car park"],
    mnemonic: "木や芝生のある公共の場所を指す。車を止める動詞にもなり、a car park は駐車場。",
    relatedWords: ["garden", "car park", "drive"],
  },
  {
    id: "part",
    word: "part",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["部分", "役割", "(部品の)パーツ"],
    pronunciation: "/pɑːrt/",
    exampleSentence: "Learning grammar is only part of the work.",
    exampleTranslationJa: "文法を覚えるのは作業の一部分にすぎない。",
    collocations: ["a part of", "take part in", "a spare part"],
    mnemonic: "全体をいくつかに分けたひとかけらを指す。take part in は「参加する」を表す。",
    relatedWords: ["piece", "section", "whole"],
  },
  {
    id: "partner",
    word: "partner",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["相棒、パートナー", "配偶者、人生の伴侶"],
    pronunciation: "/ˈpɑːrtnər/",
    exampleSentence: "She works out with a partner every morning.",
    exampleTranslationJa: "彼女は毎朝パートナーと一緒に運動する。",
    collocations: ["a business partner", "a dance partner", "a life partner"],
    mnemonic: "「役割を分け合う相手」が核の語。仕事・ダンス・人生の相手まで幅広く使え、結婚相手にも使う。",
    relatedWords: ["pair", "team", "colleague"],
  },
]
