import type { VocabularyEntry } from '../types'

// 増補 第41弾。A2 の基礎語と身のまわりの名詞・身近な動詞を中心に100語。
// 基礎語は単体で覚えても使えないので、結びつく前置詞や不規則形の注意をヒントに残す。
export const plus41: VocabularyEntry[] = [
  {
    id: "candy",
    word: "candy",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["キャンディー、砂糖菓子"],
    pronunciation: "/ˈkændi/",
    exampleSentence: "The children ate too much candy at the party.",
    exampleTranslationJa: "子どもたちはパーティーでお菓子を食べすぎた。",
    collocations: ["a piece of candy", "a candy shop", "cotton candy"],
    mnemonic: "砂糖を煮固めた菓子の総称。英国では sweets と言うほうが普通で、米国では candy。",
    relatedWords: ["sugar", "sweet", "chocolate"],
  },
  {
    id: "cannot",
    word: "cannot",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜できない", "〜してはいけない"],
    pronunciation: "/ˈkænɑːt/",
    exampleSentence: "I cannot answer the phone right now.",
    exampleTranslationJa: "今は電話に出ることができない。",
    collocations: ["cannot afford", "cannot help doing", "cannot stand"],
    mnemonic: "can と not を1語につづった形。話し言葉ではふつう can't と縮める。",
    relatedWords: ["can", "cannot", "unable"],
  },
  {
    id: "capital",
    word: "capital",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["首都", "大文字", "資本"],
    pronunciation: "/ˈkæpɪtl/",
    exampleSentence: "Paris is the capital of France.",
    exampleTranslationJa: "パリはフランスの首都だ。",
    collocations: ["the capital city", "capital letters", "raise capital"],
    mnemonic: "capit(頭)+ -al で「頭にあたる場所」。文の頭の大文字の意味にも広がった。",
    relatedWords: ["city", "letter", "money"],
  },
  {
    id: "car",
    word: "car",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["車、自動車", "(列車の)車両"],
    pronunciation: "/kɑːr/",
    exampleSentence: "We washed the car in front of the house.",
    exampleTranslationJa: "私たちは家の前で車を洗った。",
    collocations: ["by car", "a used car", "park the car"],
    mnemonic: "carriage(馬車)と同じ語源で、もとは「荷を運ぶもの」。英語では自動車は car で通じる。",
    relatedWords: ["drive", "vehicle", "taxi"],
  },
  {
    id: "card",
    word: "card",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["カード", "はがき", "トランプの札"],
    pronunciation: "/kɑːrd/",
    exampleSentence: "She sent me a birthday card.",
    exampleTranslationJa: "彼女は私に誕生日カードを送ってくれた。",
    collocations: ["a birthday card", "pay by card", "a credit card"],
    mnemonic: "厚みのある小さな紙1枚を指す。cardboard(厚紙)や postcard も同じ語から出ている。",
    relatedWords: ["paper", "letter", "postcard"],
  },
  {
    id: "cardboard",
    word: "cardboard",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["厚紙、段ボール"],
    pronunciation: "/ˈkɑːrdbɔːrd/",
    exampleSentence: "The boxes were made of thick cardboard.",
    exampleTranslationJa: "その箱は厚い段ボールでできていた。",
    collocations: ["a cardboard box", "a sheet of cardboard", "cardboard packaging"],
    mnemonic: "card(厚い紙)+ board(板)で「板のように厚い紙」。荷物を入れる箱の材料になる。",
    relatedWords: ["box", "paper", "package"],
  },
  {
    id: "carnival",
    word: "carnival",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カーニバル、謝肉祭", "移動遊園地"],
    pronunciation: "/ˈkɑːrnɪvl/",
    exampleSentence: "The whole town dances during the carnival.",
    exampleTranslationJa: "カーニバルの間は町じゅうが踊る。",
    collocations: ["a carnival parade", "a carnival float", "join the carnival"],
    mnemonic: "ラテン語で「肉を取り去る」の意。節制に入る前に肉を食べ納める祭りが原義で、移動遊園地の意味もある。",
    relatedWords: ["festival", "parade", "costume"],
  },
  {
    id: "carry",
    word: "carry",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["運ぶ、持ち歩く"],
    pronunciation: "/ˈkæri/",
    exampleSentence: "Could you carry this bag for me?",
    exampleTranslationJa: "このかばんを運んでもらえますか。",
    collocations: ["carry a bag", "carry on", "carry out a plan"],
    mnemonic: "car(車)と同語源で、もとは「荷を載せて運ぶ」。carry on は「続ける」。",
    relatedWords: ["bring", "hold", "take"],
  },
  {
    id: "cat",
    word: "cat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["猫"],
    pronunciation: "/kæt/",
    exampleSentence: "The cat is sleeping on the sofa.",
    exampleTranslationJa: "猫がソファで寝ている。",
    collocations: ["feed the cat", "a pet cat", "a black cat"],
    mnemonic: "身近なペットの代表で、子猫は kitten という。複数形は cats と s を付けるだけ。",
    relatedWords: ["kitten", "dog", "pet"],
  },
  {
    id: "cd",
    word: "cd",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["CD、コンパクトディスク"],
    pronunciation: "/ˌsiː ˈdiː/",
    exampleSentence: "He still keeps his old CDs in a box.",
    exampleTranslationJa: "彼は今でも古いCDを箱に取ってある。",
    collocations: ["a music CD", "burn a CD", "a CD player"],
    mnemonic: "compact disc の頭文字。2文字を1文字ずつ「シー・ディー」と読む略語。",
    relatedWords: ["disc", "music", "player"],
  },
  {
    id: "ceiling fan",
    word: "ceiling fan",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["天井扇、シーリングファン"],
    pronunciation: "/ˈsiːlɪŋ fæn/",
    exampleSentence: "A ceiling fan turned slowly above the table.",
    exampleTranslationJa: "天井扇がテーブルの上でゆっくり回っていた。",
    collocations: ["install a ceiling fan", "a ceiling fan blade", "turn on the ceiling fan"],
    mnemonic: "ceiling は ciel(ラテン語で空)から天井の意に。fan は風を起こす羽根。",
    relatedWords: ["fan", "ceiling", "air"],
  },
  {
    id: "cent",
    word: "cent",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["セント(1ドルの100分の1)"],
    pronunciation: "/sent/",
    exampleSentence: "The old coin is worth fifty cents.",
    exampleTranslationJa: "その古い硬貨は50セントの価値がある。",
    collocations: ["fifty cents", "a cent coin", "not one cent"],
    mnemonic: "cent はラテン語で「100」。1ドル=100セントで、century(100年)と同じ語根。",
    relatedWords: ["dollar", "coin", "money"],
  },
  {
    id: "center",
    word: "center",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["中心、中央", "施設、センター"],
    pronunciation: "/ˈsentər/",
    exampleSentence: "The table stands in the center of the room.",
    exampleTranslationJa: "テーブルは部屋の中央に置かれている。",
    collocations: ["the city center", "a shopping center", "in the center of"],
    mnemonic: "米国式のつづり。英国式は centre と語尾が -re になり、発音は変わらない。",
    relatedWords: ["middle", "central", "focus"],
  },
  {
    id: "chalk",
    word: "chalk",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["チョーク、白墨"],
    pronunciation: "/tʃɔːk/",
    exampleSentence: "The teacher wrote the date in chalk.",
    exampleTranslationJa: "先生はチョークで日付を書いた。",
    collocations: ["a piece of chalk", "chalk marks", "write in chalk"],
    mnemonic: "石灰岩の一種で、黒板に字を書く白い筆記具を指す。日本語の「チョーク」とほぼ同じ音なので覚えやすい。",
    relatedWords: ["board", "write", "stone"],
  },
  {
    id: "child",
    word: "child",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["子ども"],
    pronunciation: "/tʃaɪld/",
    exampleSentence: "Every child in the class got a small gift.",
    exampleTranslationJa: "クラスのどの子どもも小さな贈り物をもらった。",
    collocations: ["an only child", "a young child", "raise a child"],
    mnemonic: "複数形は children と不規則に変わる。形容詞は childish(子どもっぽい)。",
    relatedWords: ["children", "kid", "adult"],
  },
  {
    id: "chimpanzee",
    word: "chimpanzee",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["チンパンジー"],
    pronunciation: "/ˌtʃɪmpænˈziː/",
    exampleSentence: "A chimpanzee used a stick to reach the fruit.",
    exampleTranslationJa: "チンパンジーは棒を使って果物に届いた。",
    collocations: ["a wild chimpanzee", "a chimpanzee troop", "study chimpanzees"],
    mnemonic: "ゴリラやオランウータンと同じ仲間の大型類人猿を指す。略して chimp とも呼び、知能が高いことで知られる。",
    relatedWords: ["ape", "monkey", "gorilla"],
  },
  {
    id: "chocolate",
    word: "chocolate",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["チョコレート"],
    pronunciation: "/ˈtʃɔːklət/",
    exampleSentence: "She gave me a bar of dark chocolate.",
    exampleTranslationJa: "彼女は私に板チョコをくれた。",
    collocations: ["a bar of chocolate", "hot chocolate", "dark chocolate"],
    mnemonic: "2つ目の o は読まないので「チョコレット」に近い音。a bar of で1本と数える。",
    relatedWords: ["candy", "sweet", "cocoa"],
  },
  {
    id: "choose",
    word: "choose",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["選ぶ、選択する"],
    pronunciation: "/tʃuːz/",
    exampleSentence: "You can choose any seat you like.",
    exampleTranslationJa: "好きな席をどれでも選んでよい。",
    collocations: ["choose between", "choose a seat", "choose carefully"],
    mnemonic: "過去形は chose、過去分詞は chosen。名詞は choice と母音のつづりが変わる。",
    relatedWords: ["choice", "select", "pick"],
  },
  {
    id: "cinema",
    word: "cinema",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["映画館", "映画(芸術として)"],
    pronunciation: "/ˈsɪnəmə/",
    exampleSentence: "We went to the cinema on Sunday.",
    exampleTranslationJa: "私たちは日曜日に映画館へ行った。",
    collocations: ["go to the cinema", "a cinema ticket", "at the cinema"],
    mnemonic: "ギリシャ語 kinema(動くもの)から。米国では movie theater と言う。",
    relatedWords: ["movie", "film", "theater"],
  },
  {
    id: "city",
    word: "city",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["都市、市"],
    pronunciation: "/ˈsɪti/",
    exampleSentence: "Kyoto is a beautiful city in spring.",
    exampleTranslationJa: "京都は春に美しい都市だ。",
    collocations: ["a big city", "the city center", "live in a city"],
    mnemonic: "citizen(市民)と同じ「住む」の語根から。town より大きく、正式な自治体を指す。",
    relatedWords: ["town", "citizen", "urban"],
  },
  {
    id: "clap",
    word: "clap",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["拍手する", "(手を)たたく"],
    pronunciation: "/klæp/",
    exampleSentence: "The audience began to clap after the song.",
    exampleTranslationJa: "歌のあとで観客は拍手し始めた。",
    collocations: ["clap your hands", "clap loudly", "a round of claps"],
    mnemonic: "手のひらを打つ音をまねた語。動詞が clap、名詞の「拍手喝采」は applause。",
    relatedWords: ["applause", "hands", "cheer"],
  },
  {
    id: "class",
    word: "class",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["授業", "クラス、組", "階級"],
    pronunciation: "/klæs/",
    exampleSentence: "Our English class starts at nine.",
    exampleTranslationJa: "英語の授業は9時に始まる。",
    collocations: ["attend a class", "after class", "the whole class"],
    mnemonic: "もとはラテン語で「呼び集められた集団」。classmate は同じクラスの仲間。",
    relatedWords: ["lesson", "student", "teacher"],
  },
  {
    id: "clean",
    word: "clean",
    level: "A2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["清潔な", "掃除する"],
    pronunciation: "/kliːn/",
    exampleSentence: "Please keep the kitchen clean and tidy.",
    exampleTranslationJa: "台所を清潔で整った状態に保ってください。",
    collocations: ["clean the room", "a clean towel", "clean up"],
    mnemonic: "形容詞と動詞を兼ねる語。cleaner(掃除する人・洗剤)や cleanup(一掃)も同じ語から作られる。",
    relatedWords: ["tidy", "wash", "dirty"],
  },
  {
    id: "cleaner",
    word: "cleaner",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["掃除人、清掃員", "洗剤、クリーナー"],
    pronunciation: "/ˈkliːnər/",
    exampleSentence: "The cleaner comes to our office twice a week.",
    exampleTranslationJa: "清掃員が週に2回、私たちの事務所に来る。",
    collocations: ["an office cleaner", "a window cleaner", "a vacuum cleaner"],
    mnemonic: "clean(掃除する)+ -er の形で、「する人」と「する道具」の両方を表せる。",
    relatedWords: ["clean", "maid", "vacuum"],
  },
  {
    id: "clipboard",
    word: "clipboard",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["クリップボード、紙ばさみ", "(パソコンの)一時保存領域"],
    pronunciation: "/ˈklɪpbɔːrd/",
    exampleSentence: "The nurse wrote the numbers on her clipboard.",
    exampleTranslationJa: "看護師はクリップボードに数字を書き留めた。",
    collocations: ["carry a clipboard", "on the clipboard", "copy to the clipboard"],
    mnemonic: "clip(はさむ)+ board(板)。パソコンでは一時的に貼り付ける場所を指す。",
    relatedWords: ["board", "paper", "copy"],
  },
  {
    id: "clothes",
    word: "clothes",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["衣服、服"],
    pronunciation: "/kloʊðz/",
    exampleSentence: "He hung his wet clothes near the fire.",
    exampleTranslationJa: "彼はぬれた服を火のそばにつるした。",
    collocations: ["put on clothes", "warm clothes", "a pile of clothes"],
    mnemonic: "cloth(布)から出た語で、いつも複数扱いにする。「クロウズ」と1音節で発音する点に注意。",
    relatedWords: ["clothing", "wear", "dress"],
  },
  {
    id: "clothesline",
    word: "clothesline",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["物干し綱、洗濯ひも"],
    pronunciation: "/ˈkloʊðzlaɪn/",
    exampleSentence: "She pinned the sheets to the clothesline.",
    exampleTranslationJa: "彼女はシーツを物干し綱にとめた。",
    collocations: ["hang washing on the clothesline", "a clothesline pole", "dry clothes on the clothesline"],
    mnemonic: "clothes(服)+ line(ひも)で、干すためのひもをそのまま1語にしたもの。",
    relatedWords: ["dryer", "laundry", "washing"],
  },
  {
    id: "club",
    word: "club",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["クラブ、部活動", "ナイトクラブ"],
    pronunciation: "/klʌb/",
    exampleSentence: "She joined the tennis club at school.",
    exampleTranslationJa: "彼女は学校のテニス部に入った。",
    collocations: ["join a club", "a sports club", "a club member"],
    mnemonic: "もとは「かたまり」の意。同じ目的の人が集まったかたまりを指すようになり、部活動の意味にも広がった。",
    relatedWords: ["team", "group", "member"],
  },
  {
    id: "coat",
    word: "coat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コート、上着", "(表面の)覆い"],
    pronunciation: "/koʊt/",
    exampleSentence: "Put on your coat before you go out.",
    exampleTranslationJa: "出かける前にコートを着なさい。",
    collocations: ["put on a coat", "a winter coat", "a coat of paint"],
    mnemonic: "体の外側に羽織る一枚が原義。ペンキの「一塗り」や動物の毛の「覆い」も coat。",
    relatedWords: ["jacket", "warm", "wear"],
  },
  {
    id: "coffee",
    word: "coffee",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コーヒー"],
    pronunciation: "/ˈkɔːfi/",
    exampleSentence: "I drink a cup of coffee every morning.",
    exampleTranslationJa: "私は毎朝コーヒーを1杯飲む。",
    collocations: ["a cup of coffee", "black coffee", "make coffee"],
    mnemonic: "数えられない名詞なので、「1杯」は a cup of coffee と数え方を添えて言う。",
    relatedWords: ["tea", "cafe", "drink"],
  },
  {
    id: "coffee maker",
    word: "coffee maker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["コーヒーメーカー"],
    pronunciation: "/ˈkɔːfi ˌmeɪkər/",
    exampleSentence: "The coffee maker in the office broke again.",
    exampleTranslationJa: "事務所のコーヒーメーカーがまた壊れた。",
    collocations: ["turn on the coffee maker", "clean the coffee maker", "a filter coffee maker"],
    mnemonic: "道具の名は動詞 + -er で作れる。make(作る)が maker(作る道具)になる。",
    relatedWords: ["coffee", "machine", "kitchen"],
  },
  {
    id: "cold",
    word: "cold",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["寒い、冷たい", "風邪"],
    pronunciation: "/koʊld/",
    exampleSentence: "It was very cold outside this morning.",
    exampleTranslationJa: "今朝は外がとても寒かった。",
    collocations: ["catch a cold", "cold water", "freezing cold"],
    mnemonic: "温度の低さと「風邪」の両方を表す。風邪をひくは catch a cold と言う。",
    relatedWords: ["cool", "warm", "illness"],
  },
  {
    id: "college",
    word: "college",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["大学", "単科大学、専門学校"],
    pronunciation: "/ˈkɑːlɪdʒ/",
    exampleSentence: "My sister studies law at college.",
    exampleTranslationJa: "姉は大学で法律を学んでいる。",
    collocations: ["go to college", "a college student", "college entrance"],
    mnemonic: "col-(共に)+ legare(選んで送る)が原義で「選ばれた仲間の集まり」。",
    relatedWords: ["university", "student", "campus"],
  },
  {
    id: "color",
    word: "color",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["色", "色合い"],
    pronunciation: "/ˈkʌlər/",
    exampleSentence: "What color is your new bag?",
    exampleTranslationJa: "新しいかばんは何色ですか。",
    collocations: ["a bright color", "change color", "color TV"],
    mnemonic: "米国式のつづり。英国式は colour と u が入る。形容詞は colorful。",
    relatedWords: ["colour", "paint", "bright"],
  },
  {
    id: "colour",
    word: "colour",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["色", "色合い"],
    pronunciation: "/ˈkʌlər/",
    exampleSentence: "Blue is her favourite colour for a winter coat.",
    exampleTranslationJa: "青は冬のコートに彼女が好む色だ。",
    collocations: ["a favourite colour", "bright colours", "colour in"],
    mnemonic: "英国式のつづりで u が入る。color と発音は同じで、意味もまったく変わらない。",
    relatedWords: ["color", "paint", "shade"],
  },
  {
    id: "come",
    word: "come",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["来る", "着く、到着する"],
    pronunciation: "/kʌm/",
    exampleSentence: "Please come to my house after school.",
    exampleTranslationJa: "放課後、私の家に来てください。",
    collocations: ["come home", "come true", "come from"],
    mnemonic: "話し手のいる方へ近づくのが come、そこから離れていくのが go という関係。",
    relatedWords: ["arrive", "go", "visit"],
  },
  {
    id: "come in",
    word: "come in",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["入ってくる", "(ノックへの返事として)お入りください"],
    pronunciation: "/ˌkʌm ˈɪn/",
    exampleSentence: "Come in and sit down by the window.",
    exampleTranslationJa: "入って来て、窓のそばに座ってください。",
    collocations: ["come in and sit down", "come in out of the rain", "please come in"],
    mnemonic: "come(来る)+ in(中へ)。ノックへの返事としてそのまま使える決まり文句。",
    relatedWords: ["enter", "come", "inside"],
  },
  {
    id: "coming",
    word: "coming",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["来るべき、次の", "やって来る"],
    pronunciation: "/ˈkʌmɪŋ/",
    exampleSentence: "We are busy preparing for the coming exams.",
    exampleTranslationJa: "私たちは今度の試験の準備で忙しい。",
    collocations: ["the coming week", "the coming year", "in the coming months"],
    mnemonic: "come の -ing 形が、そのまま「これから来る」という形容詞になったもの。",
    relatedWords: ["next", "future", "upcoming"],
  },
  {
    id: "commuting",
    word: "commuting",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["通勤"],
    pronunciation: "/kəˈmjuːtɪŋ/",
    exampleSentence: "Commuting by train takes about an hour.",
    exampleTranslationJa: "電車での通勤は1時間ほどかかる。",
    collocations: ["daily commuting", "commuting time", "a long commuting distance"],
    mnemonic: "com-(共に)+ mut(変える)で「乗り物を乗り継いで行き来する」こと。動詞は commute。",
    relatedWords: ["commute", "train", "office"],
  },
  {
    id: "company",
    word: "company",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["会社", "同席、仲間"],
    pronunciation: "/ˈkʌmpəni/",
    exampleSentence: "She works for a small software company.",
    exampleTranslationJa: "彼女は小さなソフトウェア会社で働いている。",
    collocations: ["work for a company", "a large company", "keep someone company"],
    mnemonic: "com-(共に)+ pan(パン)で「パンを共にする仲間」が原義。そこから「同席」の意味も。",
    relatedWords: ["firm", "business", "office"],
  },
  {
    id: "complete",
    word: "complete",
    level: "A2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["完全な、全部の", "完成させる、記入し終える"],
    pronunciation: "/kəmˈpliːt/",
    exampleSentence: "Please complete the form before Friday.",
    exampleTranslationJa: "金曜日までに用紙への記入を済ませてください。",
    collocations: ["complete a task", "a complete list", "complete the form"],
    mnemonic: "com-(すっかり)+ plet(満たす)で「すき間なく満たされた」状態を指す。",
    relatedWords: ["finish", "whole", "completely"],
  },
  {
    id: "computer",
    word: "computer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コンピューター"],
    pronunciation: "/kəmˈpjuːtər/",
    exampleSentence: "My computer is too old to run this game.",
    exampleTranslationJa: "私のコンピューターは古すぎてこのゲームは動かない。",
    collocations: ["use a computer", "a computer screen", "computer science"],
    mnemonic: "compute(計算する)+ -er で「計算する機械」。もとは計算機の意味だった。",
    relatedWords: ["laptop", "screen", "calculate"],
  },
  {
    id: "concert",
    word: "concert",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コンサート、演奏会"],
    pronunciation: "/ˈkɑːnsərt/",
    exampleSentence: "The concert starts at seven in the hall.",
    exampleTranslationJa: "コンサートは7時にホールで始まる。",
    collocations: ["go to a concert", "a live concert", "a concert hall"],
    mnemonic: "con-(共に)+ cert(競う)で「音を競わせる」。in concert は「協力して」。",
    relatedWords: ["music", "stage", "band"],
  },
  {
    id: "conversation",
    word: "conversation",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["会話、話し合い"],
    pronunciation: "/ˌkɑːnvərˈseɪʃn/",
    exampleSentence: "We had a long conversation about our plans.",
    exampleTranslationJa: "私たちは今後の予定について長く話し合った。",
    collocations: ["have a conversation", "a friendly conversation", "make conversation"],
    mnemonic: "con-(共に)+ vers(向きを変える)で、言葉を交わし合うこと。動詞は converse。",
    relatedWords: ["talk", "chat", "discussion"],
  },
  {
    id: "cooler",
    word: "cooler",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["保冷箱、クーラーボックス", "冷却器"],
    pronunciation: "/ˈkuːlər/",
    exampleSentence: "We put the drinks in a cooler by the pool.",
    exampleTranslationJa: "私たちは飲み物をプールのそばの保冷箱に入れた。",
    collocations: ["a picnic cooler", "pack a cooler", "put ice in the cooler"],
    mnemonic: "cool(冷やす)+ -er で「冷やす道具」。飲み物を冷たいまま保つ箱を指す。",
    relatedWords: ["ice", "box", "picnic"],
  },
  {
    id: "correct",
    word: "correct",
    level: "A2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["正しい", "訂正する"],
    pronunciation: "/kəˈrekt/",
    exampleSentence: "Only one of these answers is correct.",
    exampleTranslationJa: "これらの答えのうち正しいのは1つだけだ。",
    collocations: ["the correct answer", "correct a mistake", "you are correct"],
    mnemonic: "cor-(完全に)+ rect(まっすぐ)で「まっすぐ伸びた状態」。そこから「正しい」。",
    relatedWords: ["right", "wrong", "accurate"],
  },
  {
    id: "cost",
    word: "cost",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["費用がかかる", "費用、値段"],
    pronunciation: "/kɔːst/",
    exampleSentence: "How much does this ticket cost?",
    exampleTranslationJa: "この切符はいくらかかりますか。",
    collocations: ["the cost of living", "at any cost", "cost a lot of money"],
    mnemonic: "過去形も過去分詞も cost のままで変わらない。名詞の「値段・費用」も同じつづりで使える。",
    relatedWords: ["price", "pay", "expensive"],
  },
  {
    id: "cot",
    word: "cot",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["(柵付きの)ベビーベッド", "簡易ベッド"],
    pronunciation: "/kɑːt/",
    exampleSentence: "The baby is asleep in her cot.",
    exampleTranslationJa: "赤ちゃんはベビーベッドで眠っている。",
    collocations: ["put the baby in a cot", "a wooden cot", "a cot bed"],
    mnemonic: "英国では柵の付いたベッド。米国では crib と言い、簡易ベッドは camp bed。",
    relatedWords: ["bed", "crib", "baby"],
  },
  {
    id: "could",
    word: "could",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜できた", "〜してもいいですか", "〜かもしれない"],
    pronunciation: "/kʊd/",
    exampleSentence: "Could I borrow your pen for a moment?",
    exampleTranslationJa: "少しペンを借りてもいいですか。",
    collocations: ["could you help me", "could be", "could have done"],
    mnemonic: "can の過去形だが、今のことを丁寧に頼むときにも使う。発音では l を読まない点に注意。",
    relatedWords: ["can", "would", "should"],
  },
  {
    id: "country",
    word: "country",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["国", "田舎、地方"],
    pronunciation: "/ˈkʌntri/",
    exampleSentence: "He grew up in a small country town.",
    exampleTranslationJa: "彼は小さな田舎町で育った。",
    collocations: ["a foreign country", "in the country", "a country road"],
    mnemonic: "もとは「向かい側に広がる土地」。the country は「田舎」の意味になる。",
    relatedWords: ["nation", "state", "rural"],
  },
  {
    id: "courgette",
    word: "courgette",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ズッキーニ"],
    pronunciation: "/kʊrˈʒet/",
    exampleSentence: "She fried courgette slices with garlic.",
    exampleTranslationJa: "彼女はズッキーニの薄切りをニンニクと炒めた。",
    collocations: ["a courgette slice", "grow courgettes", "stuff a courgette"],
    mnemonic: "英国での呼び名で、米国では zucchini と言う。フランス語から入った夏野菜の名で、日本ではズッキーニ。",
    relatedWords: ["zucchini", "vegetable", "cucumber"],
  },
  {
    id: "courier",
    word: "courier",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["宅配業者", "配達人、使者"],
    pronunciation: "/ˈkʊriər/",
    exampleSentence: "A courier delivered the package this morning.",
    exampleTranslationJa: "宅配業者が今朝その荷物を届けた。",
    collocations: ["a courier service", "send it by courier", "a motorcycle courier"],
    mnemonic: "「走る」を意味する語から出たことばで、急いで荷物や手紙を届ける人やその業者を指す。",
    relatedWords: ["delivery", "package", "messenger"],
  },
  {
    id: "cow",
    word: "cow",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["雌牛、乳牛"],
    pronunciation: "/kaʊ/",
    exampleSentence: "The farmer milks the cow every morning.",
    exampleTranslationJa: "農家の人は毎朝その牛の乳をしぼる。",
    collocations: ["milk a cow", "a dairy cow", "a herd of cows"],
    mnemonic: "英語では雌牛を cow、雄牛を bull、子牛を calf と呼び分ける。乳を出すのは cow。",
    relatedWords: ["bull", "milk", "farm"],
  },
  {
    id: "crosswalk",
    word: "crosswalk",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["横断歩道"],
    pronunciation: "/ˈkrɔːswɔːk/",
    exampleSentence: "Wait for the green light at the crosswalk.",
    exampleTranslationJa: "横断歩道では青信号を待ちなさい。",
    collocations: ["cross at the crosswalk", "a marked crosswalk", "use the crosswalk"],
    mnemonic: "cross(横切る)+ walk(歩く)で「横切るための道」。英国では zebra crossing。",
    relatedWords: ["crossing", "road", "signal"],
  },
  {
    id: "cup",
    word: "cup",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["カップ、茶わん", "優勝カップ"],
    pronunciation: "/kʌp/",
    exampleSentence: "There is a clean cup on the shelf.",
    exampleTranslationJa: "棚の上に清潔なカップが1つある。",
    collocations: ["a cup of tea", "a paper cup", "win the cup"],
    mnemonic: "取っ手のない小さな飲み物用の器。取っ手が付いたものは mug、ガラス製は glass。",
    relatedWords: ["mug", "glass", "saucer"],
  },
  {
    id: "customer",
    word: "customer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["客、顧客"],
    pronunciation: "/ˈkʌstəmər/",
    exampleSentence: "The shop was full of customers at noon.",
    exampleTranslationJa: "その店は正午には客でいっぱいだった。",
    collocations: ["a regular customer", "serve a customer", "customer service"],
    mnemonic: "custom(習慣・なじみ)+ -er で、なじみの店に繰り返し来る人というのがもとの意味。",
    relatedWords: ["client", "shop", "service"],
  },
  {
    id: "cyclist",
    word: "cyclist",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["自転車に乗る人、サイクリスト"],
    pronunciation: "/ˈsaɪklɪst/",
    exampleSentence: "A cyclist rang her bell behind me.",
    exampleTranslationJa: "自転車に乗った人が私の後ろでベルを鳴らした。",
    collocations: ["a keen cyclist", "a helmet for cyclists", "watch out for cyclists"],
    mnemonic: "cycle(自転車)+ -ist(人)。tourist(旅行する人)と同じ作り方。",
    relatedWords: ["bicycle", "cycle", "helmet"],
  },
  {
    id: "dad",
    word: "dad",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["お父さん、パパ"],
    pronunciation: "/dæd/",
    exampleSentence: "My dad drives me to school on rainy days.",
    exampleTranslationJa: "雨の日はお父さんが車で学校まで送ってくれる。",
    collocations: ["my mum and dad", "become a dad", "dad jokes"],
    mnemonic: "赤ちゃん言葉から生まれた語で、daddy はさらに幼い響きの言い方。改まった場面では father を使う。",
    relatedWords: ["father", "mum", "parent"],
  },
  {
    id: "dance",
    word: "dance",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["踊る", "ダンス、踊り"],
    pronunciation: "/dæns/",
    exampleSentence: "They dance together every Friday night.",
    exampleTranslationJa: "彼らは毎週金曜の夜に一緒に踊る。",
    collocations: ["dance to music", "a folk dance", "ask someone to dance"],
    mnemonic: "動詞と名詞が同じ形で使える基礎語。dancer(踊る人)も同じ語から作られ、音楽に合わせて体を動かす。",
    relatedWords: ["dancer", "music", "move"],
  },
  {
    id: "dandelion",
    word: "dandelion",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["タンポポ"],
    pronunciation: "/ˈdændɪlaɪən/",
    exampleSentence: "A yellow dandelion grew by the gate.",
    exampleTranslationJa: "門のそばに黄色いタンポポが咲いていた。",
    collocations: ["a dandelion seed", "pick dandelions", "dandelion leaves"],
    mnemonic: "フランス語で「ライオンの歯」の意で、ぎざぎざした葉の形から付いた花の名。綿毛の種を飛ばして増える。",
    relatedWords: ["flower", "weed", "yellow"],
  },
  {
    id: "daughter",
    word: "daughter",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["娘"],
    pronunciation: "/ˈdɔːtər/",
    exampleSentence: "Their daughter is studying music in Vienna.",
    exampleTranslationJa: "彼らの娘はウィーンで音楽を勉強している。",
    collocations: ["an only daughter", "my eldest daughter", "a daughter of"],
    mnemonic: "gh は読まず「ドーター」と2音節で言う。息子にあたる語は son で、対にして覚えると整理しやすい。",
    relatedWords: ["son", "child", "parent"],
  },
  {
    id: "day",
    word: "day",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日、1日", "昼間"],
    pronunciation: "/deɪ/",
    exampleSentence: "It rained heavily all day yesterday.",
    exampleTranslationJa: "昨日は一日じゅう激しく雨が降っていた。",
    collocations: ["every day", "one day", "all day long"],
    mnemonic: "24時間の「日」と、明るい「昼間」の両方を指す。形容詞は daily で「毎日の」。",
    relatedWords: ["daily", "night", "week"],
  },

  {
    id: "decide",
    word: "decide",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["決める、決心する"],
    pronunciation: "/dɪˈsaɪd/",
    exampleSentence: "We must decide where to go this summer.",
    exampleTranslationJa: "この夏どこへ行くか決めなければならない。",
    collocations: ["decide to do", "decide between", "finally decide"],
    mnemonic: "de-(切り離す)+ cid(切る)で「ほかを切り捨てて1つに決める」。名詞は decision。",
    relatedWords: ["decision", "choose", "determine"],
  },
  {
    id: "dentistry",
    word: "dentistry",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["歯科、歯科医術"],
    pronunciation: "/ˈdentɪstri/",
    exampleSentence: "She studied dentistry for six years.",
    exampleTranslationJa: "彼女は6年間歯学を学んだ。",
    collocations: ["study dentistry", "a dentistry school", "modern dentistry"],
    mnemonic: "dent(歯)+ -ist(人)+ -ry(分野)。歯を扱う学問や仕事をまとめて指す。",
    relatedWords: ["dentist", "tooth", "dental"],
  },
  {
    id: "deodorant",
    word: "deodorant",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["制汗剤、デオドラント"],
    pronunciation: "/diˈoʊdərənt/",
    exampleSentence: "He bought deodorant at the drugstore.",
    exampleTranslationJa: "彼はドラッグストアで制汗剤を買った。",
    collocations: ["spray deodorant", "roll-on deodorant", "use deodorant"],
    mnemonic: "de-(取り除く)+ odor(におい)+ -ant(するもの)で、においを取り除く薬剤を指す。",
    relatedWords: ["odor", "spray", "hygiene"],
  },
  {
    id: "desk",
    word: "desk",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["机、事務机", "(受付などの)窓口"],
    pronunciation: "/desk/",
    exampleSentence: "There are three books on my desk.",
    exampleTranslationJa: "私の机の上に本が3冊ある。",
    collocations: ["sit at a desk", "a desk lamp", "the front desk"],
    mnemonic: "引き出しのある学習・事務用の机を指す。食事にも使える台のことは table と言って区別する。",
    relatedWords: ["table", "chair", "office"],
  },
  {
    id: "dictionary",
    word: "dictionary",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["辞書、事典"],
    pronunciation: "/ˈdɪkʃəneri/",
    exampleSentence: "Look the word up in your dictionary.",
    exampleTranslationJa: "その単語を辞書で調べなさい。",
    collocations: ["look up a word in a dictionary", "an English dictionary", "a bilingual dictionary"],
    mnemonic: "dict(言う)+ -ion + -ary(〜のもの)で「言葉を集めた本」が原義。辞書を引くは look up と言う。",
    relatedWords: ["word", "look up", "thesaurus"],
  },
  {
    id: "die",
    word: "die",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["死ぬ、亡くなる"],
    pronunciation: "/daɪ/",
    exampleSentence: "His grandfather died at the age of ninety.",
    exampleTranslationJa: "彼の祖父は90歳で亡くなった。",
    collocations: ["die of illness", "die out", "die young"],
    mnemonic: "死ぬ原因は die of、事故などでは die in。「絶えてなくなる」は die out。",
    relatedWords: ["death", "dead", "alive"],
  },
  {
    id: "difference",
    word: "difference",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["違い、差"],
    pronunciation: "/ˈdɪfrəns/",
    exampleSentence: "There is a big difference between the two plans.",
    exampleTranslationJa: "その2つの案には大きな違いがある。",
    collocations: ["make a difference", "a big difference", "the difference between"],
    mnemonic: "dif-(離して)+ fer(運ぶ)で「引き離して比べた差」。動詞は differ。",
    relatedWords: ["different", "gap", "compare"],
  },
  {
    id: "different",
    word: "different",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["違う、異なる", "さまざまな"],
    pronunciation: "/ˈdɪfrənt/",
    exampleSentence: "Her answer was different from mine.",
    exampleTranslationJa: "彼女の答えは私のとは違っていた。",
    collocations: ["different from", "completely different", "many different kinds"],
    mnemonic: "比べる相手は前置詞 from で結ぶ。名詞は difference と語尾が変わる。",
    relatedWords: ["difference", "various", "same"],
  },
  {
    id: "difficult",
    word: "difficult",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["難しい、困難な", "気難しい"],
    pronunciation: "/ˈdɪfɪkəlt/",
    exampleSentence: "This question is too difficult for me.",
    exampleTranslationJa: "この問題は私には難しすぎる。",
    collocations: ["a difficult question", "find it difficult to", "difficult times"],
    mnemonic: "dif-(〜でない)+ fac(する)で「簡単にはできない」。名詞は difficulty。",
    relatedWords: ["hard", "easy", "difficulty"],
  },
  {
    id: "dinosaur",
    word: "dinosaur",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["恐竜", "時代遅れの人・もの"],
    pronunciation: "/ˈdaɪnəsɔːr/",
    exampleSentence: "The museum has a huge dinosaur skeleton.",
    exampleTranslationJa: "その博物館には巨大な恐竜の骨格がある。",
    collocations: ["a dinosaur skeleton", "dinosaur bones", "dinosaurs died out"],
    mnemonic: "deino(恐ろしい)+ sauros(とかげ)で「恐ろしいとかげ」が原義。今は「時代遅れのもの」の比喩にも使う。",
    relatedWords: ["fossil", "museum", "extinct"],
  },
  {
    id: "dirty",
    word: "dirty",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["汚い、汚れた"],
    pronunciation: "/ˈdɜːrti/",
    exampleSentence: "His hands were dirty after the game.",
    exampleTranslationJa: "試合のあと彼の手は汚れていた。",
    collocations: ["dirty hands", "a dirty shirt", "get dirty"],
    mnemonic: "dirt(汚れ)+ -y(〜の多い)。clean の反対で、発音は「ダーティ」。",
    relatedWords: ["dirt", "clean", "messy"],
  },
  {
    id: "diving",
    word: "diving",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ダイビング、飛び込み"],
    pronunciation: "/ˈdaɪvɪŋ/",
    exampleSentence: "They went diving near the coral reef.",
    exampleTranslationJa: "彼らはサンゴ礁の近くでダイビングをした。",
    collocations: ["go diving", "a diving mask", "scuba diving"],
    mnemonic: "dive(飛び込む)の -ing 形。水中に潜るのも競技の飛び込みも同じ語で表す。",
    relatedWords: ["dive", "swim", "sea"],
  },
  {
    id: "do",
    word: "do",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["する、行う", "(疑問文・否定文を作る)"],
    pronunciation: "/duː/",
    exampleSentence: "What do you do on Sunday mornings?",
    exampleTranslationJa: "日曜の朝は何をしていますか。",
    collocations: ["do homework", "do the dishes", "do your best"],
    mnemonic: "動作の中身を指す一般動詞と、疑問文や否定文を組み立てる助動詞の働きを1語で兼ねている。",
    relatedWords: ["does", "done", "make"],
  },
  {
    id: "does",
    word: "does",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["do の三人称単数現在", "(疑問文・否定文で)〜しますか"],
    pronunciation: "/dʌz/",
    exampleSentence: "She does her homework before dinner.",
    exampleTranslationJa: "彼女は夕食の前に宿題をする。",
    collocations: ["what does he do", "does not", "does well"],
    mnemonic: "主語が he / she / it のときの do の形。発音は「ダズ」で、o を読まない。",
    relatedWords: ["do", "did", "done"],
  },
  {
    id: "dog",
    word: "dog",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["犬"],
    pronunciation: "/dɔːɡ/",
    exampleSentence: "Their dog barks at every passing car.",
    exampleTranslationJa: "彼らの犬は通る車ごとに吠える。",
    collocations: ["walk the dog", "a guide dog", "a dog owner"],
    mnemonic: "身近なペットの代表で、子犬は puppy という。複数形は dogs と s を付ける。",
    relatedWords: ["puppy", "cat", "pet"],
  },
  {
    id: "doing",
    word: "doing",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["している(進行形)", "すること"],
    pronunciation: "/ˈduːɪŋ/",
    exampleSentence: "What are you doing this afternoon?",
    exampleTranslationJa: "今日の午後は何をしていますか。",
    collocations: ["what are you doing", "keep doing", "enjoy doing"],
    mnemonic: "do の -ing 形で、be 動詞と組ませると「今しているところ」を表せる。名詞として「行い」の意味にもなる。",
    relatedWords: ["do", "done", "does"],
  },
  {
    id: "dollar",
    word: "dollar",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ドル"],
    pronunciation: "/ˈdɑːlər/",
    exampleSentence: "The book costs about ten dollars.",
    exampleTranslationJa: "その本は10ドルくらいする。",
    collocations: ["a hundred dollars", "a dollar bill", "spend a dollar"],
    mnemonic: "ドイツ語の Taler(ターレル銀貨)から。1ドルは100セントと決まっている。",
    relatedWords: ["cent", "money", "price"],
  },
  {
    id: "done",
    word: "done",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["終わった、済んだ", "(料理が)できあがった"],
    pronunciation: "/dʌn/",
    exampleSentence: "The work is done at last.",
    exampleTranslationJa: "その仕事はついに終わった。",
    collocations: ["well done", "be done with", "get the job done"],
    mnemonic: "do の過去分詞が「終わった」の形容詞に。Well done! はほめ言葉になる。",
    relatedWords: ["do", "finished", "ready"],
  },
  {
    id: "door",
    word: "door",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ドア、扉", "戸口"],
    pronunciation: "/dɔːr/",
    exampleSentence: "Please close the door behind you.",
    exampleTranslationJa: "後ろのドアを閉めてください。",
    collocations: ["open the door", "answer the door", "next door"],
    mnemonic: "部屋や家の出入り口を指す基礎語。next door と置くと「隣の家」の意味になり、よく使われる。",
    relatedWords: ["gate", "window", "key"],
  },
  {
    id: "down",
    word: "down",
    level: "A2",
    partOfSpeech: "副詞・前置詞",
    meaningsJa: ["下へ、下に", "〜を下って"],
    pronunciation: "/daʊn/",
    exampleSentence: "She walked down the stairs to the kitchen.",
    exampleTranslationJa: "彼女は台所へ階段を下りていった。",
    collocations: ["sit down", "down the street", "upside down"],
    mnemonic: "up の反対にあたる語で、動詞と組んで sit down や calm down などの句動詞をよく作る。",
    relatedWords: ["up", "below", "downstairs"],
  },
  {
    id: "downhill",
    word: "downhill",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["下り坂で、下り方向に", "悪化して"],
    pronunciation: "/ˌdaʊnˈhɪl/",
    exampleSentence: "The bike goes much faster downhill.",
    exampleTranslationJa: "自転車は下り坂ではずっと速く進む。",
    collocations: ["go downhill", "a downhill slope", "ski downhill"],
    mnemonic: "down(下)+ hill(丘)。go downhill は「物事が悪くなる」の意味にもなる。",
    relatedWords: ["uphill", "slope", "down"],
  },
  {
    id: "dress",
    word: "dress",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ワンピース", "服を着せる"],
    pronunciation: "/dres/",
    exampleSentence: "She wore a blue dress to the party.",
    exampleTranslationJa: "彼女はパーティーに青いワンピースを着て行った。",
    collocations: ["wear a dress", "a wedding dress", "get dressed"],
    mnemonic: "名詞では女性用のワンピースを指し、動詞では「服を着る・着せる」の意味になる。get dressed で「着替える」。",
    relatedWords: ["clothes", "skirt", "wear"],
  },
  {
    id: "drills",
    word: "drills",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["反復練習、ドリル", "(複数の)穴あけ工具"],
    pronunciation: "/drɪlz/",
    exampleSentence: "The class did grammar drills for ten minutes.",
    exampleTranslationJa: "クラスは10分間、文法の反復練習をした。",
    collocations: ["grammar drills", "do drills", "practice drills"],
    mnemonic: "同じ動作を繰り返す練習を指す語。穴をあける工具の意味も同じつづりで表し、複数形で使うことが多い。",
    relatedWords: ["practice", "exercise", "train"],
  },
  {
    id: "drink",
    word: "drink",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["飲む", "飲み物"],
    pronunciation: "/drɪŋk/",
    exampleSentence: "You should drink more water in summer.",
    exampleTranslationJa: "夏はもっと水を飲んだほうがよい。",
    collocations: ["drink water", "a cold drink", "have a drink"],
    mnemonic: "過去形は drank、過去分詞は drunk。名詞では「飲み物」そのものを指す。",
    relatedWords: ["drank", "water", "eat"],
  },
  {
    id: "driver",
    word: "driver",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["運転手、ドライバー"],
    pronunciation: "/ˈdraɪvər/",
    exampleSentence: "The bus driver waited for the last passenger.",
    exampleTranslationJa: "バスの運転手は最後の乗客を待った。",
    collocations: ["a taxi driver", "a careful driver", "the driver's seat"],
    mnemonic: "drive(運転する)+ -er(する人)で「運転する人」。ねじを回す道具の「ドライバー」も同じ形になる。",
    relatedWords: ["drive", "car", "passenger"],
  },
  {
    id: "drop by",
    word: "drop by",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["立ち寄る、ふらっと訪ねる"],
    pronunciation: "/ˌdrɑːp ˈbaɪ/",
    exampleSentence: "Drop by my office when you have time.",
    exampleTranslationJa: "時間があるとき私の事務所に立ち寄ってください。",
    collocations: ["drop by the office", "drop by to say hello", "drop by later"],
    mnemonic: "drop(ひょいと落ちる)+ by(そばに)で、予定になく短く立ち寄ることを表す。stop by とほぼ同じ。",
    relatedWords: ["visit", "stop by", "call in"],
  },
  {
    id: "dryer",
    word: "dryer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["乾燥機", "ドライヤー"],
    pronunciation: "/ˈdraɪər/",
    exampleSentence: "Put the wet towels in the dryer.",
    exampleTranslationJa: "ぬれたタオルを乾燥機に入れてください。",
    collocations: ["a hair dryer", "a clothes dryer", "a tumble dryer"],
    mnemonic: "dry(乾かす)+ -er(する道具)で「乾かす道具」。髪用か洗濯物用かで呼び分けて使う。",
    relatedWords: ["dry", "hair", "laundry"],
  },
  {
    id: "dummy",
    word: "dummy",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["(英国)おしゃぶり", "マネキン、にせ物"],
    pronunciation: "/ˈdʌmi/",
    exampleSentence: "The baby fell asleep with a dummy in her mouth.",
    exampleTranslationJa: "赤ちゃんはおしゃぶりをくわえたまま眠った。",
    collocations: ["suck a dummy", "a shop dummy", "a dummy run"],
    mnemonic: "dumb(ものを言わない)+ -y で「本物のふりをする物」が原義。英国では赤ちゃんのおしゃぶりも指す。",
    relatedWords: ["baby", "model", "fake"],
  },
  {
    id: "during",
    word: "during",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜の間(ずっと・のどこかで)"],
    pronunciation: "/ˈdʊrɪŋ/",
    exampleSentence: "He fell asleep during the film.",
    exampleTranslationJa: "彼は映画の途中で眠ってしまった。",
    collocations: ["during the day", "during the summer", "during the meeting"],
    mnemonic: "dure(続く)から出た語。for が長さ、during は「その期間の中のどこか」。",
    relatedWords: ["while", "for", "throughout"],
  },
  {
    id: "dusty",
    word: "dusty",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ほこりっぽい、ほこりをかぶった"],
    pronunciation: "/ˈdʌsti/",
    exampleSentence: "The shelves in the old room were dusty.",
    exampleTranslationJa: "古い部屋の棚はほこりをかぶっていた。",
    collocations: ["a dusty road", "dusty shelves", "dusty air"],
    mnemonic: "dust(ほこり)+ -y(〜の多い)で「ほこりっぽい」。名詞に -y を付けると形容詞になる型の1つ。",
    relatedWords: ["dust", "dirty", "dry"],
  },
  {
    id: "each",
    word: "each",
    level: "A2",
    partOfSpeech: "限定詞・代名詞",
    meaningsJa: ["それぞれの、おのおの", "それぞれ"],
    pronunciation: "/iːtʃ/",
    exampleSentence: "Each student received a new textbook.",
    exampleTranslationJa: "学生はそれぞれ新しい教科書を受け取った。",
    collocations: ["each other", "each of us", "each day"],
    mnemonic: "2つ以上を1つずつ取り出して見る語。every のほうは全部をひとまとめに見る点が違う。",
    relatedWords: ["every", "both", "all"],
  },
  {
    id: "ear",
    word: "ear",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["耳", "(音楽などを聞き分ける)耳"],
    pronunciation: "/ɪr/",
    exampleSentence: "The doctor looked inside my left ear.",
    exampleTranslationJa: "医者は私の左耳の中を診た。",
    collocations: ["a good ear for music", "an earache", "whisper in someone's ear"],
    mnemonic: "体の部位を表す基礎語。hear(聞く)や listen とはつづりが違う点に注意して覚えたい。",
    relatedWords: ["hear", "eye", "listen"],
  },
  {
    id: "early",
    word: "early",
    level: "A2",
    partOfSpeech: "形容詞・副詞",
    meaningsJa: ["早い、早く", "初期の"],
    pronunciation: "/ˈɜːrli/",
    exampleSentence: "I got up early to catch the first train.",
    exampleTranslationJa: "始発電車に乗るため早く起きた。",
    collocations: ["get up early", "an early start", "early in the morning"],
    mnemonic: "古英語の ere(前に)+ -ly から。late と対で覚えると時間の位置が定まる。",
    relatedWords: ["late", "soon", "morning"],
  },
  {
    id: "easel",
    word: "easel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["画架、イーゼル"],
    pronunciation: "/ˈiːzl/",
    exampleSentence: "The painter set her canvas on the easel.",
    exampleTranslationJa: "画家はイーゼルにカンバスを立てた。",
    collocations: ["a wooden easel", "set up an easel", "paint at an easel"],
    mnemonic: "オランダ語 ezel(ろば)から出た語。荷を支える「ろば」の役をする台が原義で、画家がカンバスを立てる。",
    relatedWords: ["paint", "canvas", "studio"],
  },
  {
    id: "east",
    word: "east",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["東", "東の"],
    pronunciation: "/iːst/",
    exampleSentence: "The sun rises in the east every morning.",
    exampleTranslationJa: "太陽は毎朝東からのぼる。",
    collocations: ["in the east", "the east coast", "east of the city"],
    mnemonic: "日の出る方角が east。west と対にして覚えると方角の位置が定まりやすく、eastern は「東の」。",
    relatedWords: ["west", "north", "south"],
  },
  {
    id: "easy",
    word: "easy",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["簡単な、やさしい", "気楽な"],
    pronunciation: "/ˈiːzi/",
    exampleSentence: "This puzzle is easy for young children.",
    exampleTranslationJa: "このパズルは幼い子どもにも簡単だ。",
    collocations: ["an easy question", "easy to use", "take it easy"],
    mnemonic: "ease(楽さ)+ -y。take it easy は「気楽にやろう」という決まり文句。",
    relatedWords: ["ease", "simple", "difficult"],
  },
  {
    id: "eat",
    word: "eat",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["食べる"],
    pronunciation: "/iːt/",
    exampleSentence: "We usually eat dinner at seven.",
    exampleTranslationJa: "私たちはたいてい7時に夕食を食べる。",
    collocations: ["eat breakfast", "eat out", "eat lunch"],
    mnemonic: "過去形は ate、過去分詞は eaten。外で食べることは eat out と言う。",
    relatedWords: ["ate", "food", "drink"],
  },
  {
    id: "sardine",
    word: "sardine",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["イワシ", "イワシの缶詰"],
    pronunciation: "/sɑːrˈdiːn/",
    exampleSentence: "We opened a tin of sardines for lunch.",
    exampleTranslationJa: "私たちは昼食にイワシの缶詰を開けた。",
    collocations: ["a tin of sardines", "grilled sardines", "packed like sardines"],
    mnemonic: "Sardinia(サルディニア島)の近海でよく取れたことから付いた名とされる。小さな魚で、缶詰が定番。",
    relatedWords: ["fish", "tin", "sea"],
  },
]
