import type { VocabularyEntry } from '../types'

// 増補 第21弾。派生名詞の残り(R-Z)と、-ive 形容詞。
// 取り違えやすい対(authoritative と authoritarian、compulsive と compulsory、
// descriptive と prescriptive、deductive と inductive)は覚えるヒントで区別する。
export const plus21: VocabularyEntry[] = [
  {
    id: "revocation",
    word: "revocation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["取り消し、撤回"],
    pronunciation: "/ˌrevəˈkeɪʃn/",
    exampleSentence: "Revocation of the licence follows a second offence.",
    exampleTranslationJa: "2度目の違反で免許は取り消される。",
    collocations: ["revocation of a licence", "the revocation of a law"],
    mnemonic: "revoke の名詞形。voice(声)と同語根で「呼び戻す」。",
    relatedWords: ["revoke", "cancellation", "withdrawal"],
  },
  {
    id: "salvation",
    word: "salvation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["救い、救済"],
    pronunciation: "/sælˈveɪʃn/",
    exampleSentence: "The loan proved to be their salvation.",
    exampleTranslationJa: "その融資が彼らの救いとなった。",
    collocations: ["find salvation", "the salvation of", "Salvation Army"],
    mnemonic: "save(救う)と同語根。宗教的な救いにも、現実の救いにも使う。",
    relatedWords: ["rescue", "redemption", "save"],
  },
  {
    id: "saturation",
    word: "saturation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["飽和、しみ込ませること"],
    pronunciation: "/ˌsætʃəˈreɪʃn/",
    exampleSentence: "The market has reached saturation.",
    exampleTranslationJa: "その市場は飽和に達した。",
    collocations: ["market saturation", "saturation point", "saturation coverage"],
    mnemonic: "saturate の名詞形。これ以上入らない状態。",
    relatedWords: ["saturate", "fullness", "glut"],
  },
  {
    id: "seclusion",
    word: "seclusion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["隠遁、人目を避けること"],
    pronunciation: "/sɪˈkluːʒn/",
    exampleSentence: "She lives in seclusion in the hills.",
    exampleTranslationJa: "彼女は丘で人目を避けて暮らしている。",
    collocations: ["live in seclusion", "complete seclusion"],
    mnemonic: "secluded(人目につかない)の名詞形。exclude と同語根。",
    relatedWords: ["isolation", "privacy", "retreat"],
  },
  {
    id: "secretion",
    word: "secretion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["分泌、分泌物"],
    pronunciation: "/sɪˈkriːʃn/",
    exampleSentence: "The gland controls the secretion of hormones.",
    exampleTranslationJa: "その腺はホルモンの分泌を調節する。",
    collocations: ["hormone secretion", "the secretion of"],
    mnemonic: "secrete(分泌する)の名詞形。secret(秘密)とはつづりが同じで別語。",
    relatedWords: ["secrete", "gland", "discharge"],
  },
  {
    id: "sedation",
    word: "sedation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["鎮静、鎮静処置"],
    pronunciation: "/sɪˈdeɪʃn/",
    exampleSentence: "The procedure is done under sedation.",
    exampleTranslationJa: "その処置は鎮静下で行われる。",
    collocations: ["under sedation", "light sedation"],
    mnemonic: "sedative(鎮静剤)と同語根。sit(座る)と同じ語根で「落ち着かせる」。",
    relatedWords: ["sedative", "calm", "anaesthesia"],
  },
  {
    id: "segregation",
    word: "segregation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["分離、隔離"],
    pronunciation: "/ˌseɡrɪˈɡeɪʃn/",
    exampleSentence: "Racial segregation was outlawed in 1964.",
    exampleTranslationJa: "人種隔離は1964年に違法とされた。",
    collocations: ["racial segregation", "segregation of waste"],
    mnemonic: "segregate の名詞形。反対は integration(統合)。",
    relatedWords: ["segregate", "separation", "integration"],
  },
  {
    id: "simplification",
    word: "simplification",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["単純化"],
    pronunciation: "/ˌsɪmplɪfɪˈkeɪʃn/",
    exampleSentence: "That is a gross simplification of the issue.",
    exampleTranslationJa: "それはその問題のひどい単純化だ。",
    collocations: ["a gross simplification", "the simplification of rules"],
    mnemonic: "simplify の名詞形。批判の文脈では「話を単純にしすぎ」。",
    relatedWords: ["simplify", "reduction", "complexity"],
  },
  {
    id: "specialisation",
    word: "specialisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["専門化、専攻"],
    pronunciation: "/ˌspeʃəlaɪˈzeɪʃn/",
    exampleSentence: "Early specialisation can narrow your options.",
    exampleTranslationJa: "早すぎる専門化は選択肢を狭めうる。",
    collocations: ["a high degree of specialisation", "specialisation in"],
    mnemonic: "specialise の名詞形。米つづりは specialization。",
    relatedWords: ["specialise", "expertise", "generalisation"],
  },
  {
    id: "stabilisation",
    word: "stabilisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["安定化"],
    pronunciation: "/ˌsteɪbəlaɪˈzeɪʃn/",
    exampleSentence: "Stabilisation of the currency took two years.",
    exampleTranslationJa: "通貨の安定化には2年かかった。",
    collocations: ["price stabilisation", "a stabilisation programme"],
    mnemonic: "stabilise の名詞形。経済や患者の容体について使う。",
    relatedWords: ["stabilise", "stability", "balance"],
  },
  {
    id: "standardisation",
    word: "standardisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["標準化、規格統一"],
    pronunciation: "/ˌstændərdaɪˈzeɪʃn/",
    exampleSentence: "Standardisation cut manufacturing costs.",
    exampleTranslationJa: "規格統一が製造費を下げた。",
    collocations: ["the standardisation of", "industry standardisation"],
    mnemonic: "standardise の名詞形。ばらばらの仕様を一つにそろえること。",
    relatedWords: ["standardise", "uniformity", "standard"],
  },
  {
    id: "starvation",
    word: "starvation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["飢餓、餓死"],
    pronunciation: "/stɑːrˈveɪʃn/",
    exampleSentence: "Thousands died of starvation that winter.",
    exampleTranslationJa: "その冬、何千人もが餓死した。",
    collocations: ["die of starvation", "starvation wages", "on the brink of starvation"],
    mnemonic: "starve の名詞形。hunger より重く、命に関わる状態。",
    relatedWords: ["starve", "famine", "hunger"],
  },
  {
    id: "sterilisation",
    word: "sterilisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["滅菌、不妊手術"],
    pronunciation: "/ˌsterəlaɪˈzeɪʃn/",
    exampleSentence: "Sterilisation of the instruments is essential.",
    exampleTranslationJa: "器具の滅菌は不可欠だ。",
    collocations: ["sterilisation of equipment", "heat sterilisation"],
    mnemonic: "sterile(無菌の)から。医療器具の滅菌が主な意味。",
    relatedWords: ["sterile", "disinfection", "hygiene"],
  },
  {
    id: "stimulation",
    word: "stimulation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["刺激"],
    pronunciation: "/ˌstɪmjuˈleɪʃn/",
    exampleSentence: "Babies need plenty of stimulation.",
    exampleTranslationJa: "赤ん坊には十分な刺激が必要だ。",
    collocations: ["mental stimulation", "visual stimulation"],
    mnemonic: "stimulate の名詞形。stimulus(刺激するもの)の複数形は stimuli。",
    relatedWords: ["stimulate", "stimulus", "encouragement"],
  },
  {
    id: "stipulation",
    word: "stipulation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["条件、規定"],
    pronunciation: "/ˌstɪpjuˈleɪʃn/",
    exampleSentence: "He agreed with one stipulation.",
    exampleTranslationJa: "彼は一つの条件つきで同意した。",
    collocations: ["on the stipulation that", "a strict stipulation"],
    mnemonic: "stipulate の名詞形。契約に明記された条件。",
    relatedWords: ["stipulate", "condition", "provision"],
  },
  {
    id: "subordination",
    word: "subordination",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["従属、下位に置くこと"],
    pronunciation: "/səˌbɔːrdɪˈneɪʃn/",
    exampleSentence: "The subordination of safety to profit is dangerous.",
    exampleTranslationJa: "安全を利益の下に置くのは危険だ。",
    collocations: ["the subordination of", "subordination to"],
    mnemonic: "subordinate の名詞形。sub-(下)+ order(順序)。",
    relatedWords: ["subordinate", "inferiority", "hierarchy"],
  },
  {
    id: "subsidence",
    word: "subsidence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["地盤沈下"],
    pronunciation: "/səbˈsaɪdns/",
    exampleSentence: "Cracks in the wall suggest subsidence.",
    exampleTranslationJa: "壁のひびは地盤沈下を示している。",
    collocations: ["signs of subsidence", "suffer from subsidence"],
    mnemonic: "subside(沈む)の名詞形。英の住宅売買で必ず確認される語。",
    relatedWords: ["subside", "sinking", "settlement"],
  },
  {
    id: "suffocation",
    word: "suffocation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["窒息"],
    pronunciation: "/ˌsʌfəˈkeɪʃn/",
    exampleSentence: "The cause of death was suffocation.",
    exampleTranslationJa: "死因は窒息だった。",
    collocations: ["die of suffocation", "the risk of suffocation"],
    mnemonic: "suffocate の名詞形。空気が吸えなくなること。",
    relatedWords: ["suffocate", "choking", "asphyxiation"],
  },
  {
    id: "suppression",
    word: "suppression",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["抑圧、鎮圧", "(情報の)握りつぶし"],
    pronunciation: "/səˈpreʃn/",
    exampleSentence: "The suppression of dissent continued for years.",
    exampleTranslationJa: "異論の抑圧は何年も続いた。",
    collocations: ["the suppression of dissent", "fire suppression"],
    mnemonic: "suppress の名詞形。repression が心理寄り、suppression は行為寄り。",
    relatedWords: ["suppress", "repression", "censorship"],
  },
  {
    id: "sustenance",
    word: "sustenance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["栄養、糧"],
    pronunciation: "/ˈsʌstənəns/",
    exampleSentence: "The soup provided little sustenance.",
    exampleTranslationJa: "そのスープではほとんど腹の足しにならなかった。",
    collocations: ["provide sustenance", "little sustenance"],
    mnemonic: "sustain(支える)の名詞形。命をつなぐ食べ物のこと。",
    relatedWords: ["nourishment", "food", "nutrition"],
  },
  {
    id: "symbolism",
    word: "symbolism",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["象徴性、象徴主義"],
    pronunciation: "/ˈsɪmbəlɪzəm/",
    exampleSentence: "The symbolism of the colours is deliberate.",
    exampleTranslationJa: "その色使いの象徴性は意図的だ。",
    collocations: ["religious symbolism", "heavy with symbolism"],
    mnemonic: "symbol + -ism。作品の中で何が何を表しているか、という話。",
    relatedWords: ["symbol", "imagery", "metaphor"],
  },
  {
    id: "termination",
    word: "termination",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["終了、解雇", "(妊娠の)中絶"],
    pronunciation: "/ˌtɜːrmɪˈneɪʃn/",
    exampleSentence: "Termination of the contract requires notice.",
    exampleTranslationJa: "契約の終了には予告が必要だ。",
    collocations: ["termination of employment", "early termination"],
    mnemonic: "terminate の名詞形。terminal(終着駅)と同語根。",
    relatedWords: ["terminate", "end", "dismissal"],
  },
  {
    id: "turbulence",
    word: "turbulence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["乱気流", "動乱"],
    pronunciation: "/ˈtɜːrbjələns/",
    exampleSentence: "We hit turbulence over the mountains.",
    exampleTranslationJa: "私たちは山の上空で乱気流に入った。",
    collocations: ["hit turbulence", "economic turbulence", "severe turbulence"],
    mnemonic: "turbulent の名詞形。飛行機の揺れと、社会の混乱の両方。",
    relatedWords: ["turbulent", "instability", "upheaval"],
  },
  {
    id: "unification",
    word: "unification",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["統一"],
    pronunciation: "/ˌjuːnɪfɪˈkeɪʃn/",
    exampleSentence: "German unification took place in 1990.",
    exampleTranslationJa: "ドイツ統一は1990年に実現した。",
    collocations: ["national unification", "the unification of"],
    mnemonic: "unify の名詞形。uni-(一つ)にすること。",
    relatedWords: ["unify", "union", "division"],
  },
  {
    id: "urbanisation",
    word: "urbanisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["都市化"],
    pronunciation: "/ˌɜːrbənaɪˈzeɪʃn/",
    exampleSentence: "Rapid urbanisation strained the water supply.",
    exampleTranslationJa: "急速な都市化が水道を圧迫した。",
    collocations: ["rapid urbanisation", "the pace of urbanisation"],
    mnemonic: "urban(都市の)+ -isation。urbane(洗練された)とは別語。",
    relatedWords: ["urban", "city", "development"],
  },
  {
    id: "utilisation",
    word: "utilisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["活用、利用率"],
    pronunciation: "/ˌjuːtəlaɪˈzeɪʃn/",
    exampleSentence: "Bed utilisation in the hospital is at 95 per cent.",
    exampleTranslationJa: "その病院の病床利用率は95%だ。",
    collocations: ["capacity utilisation", "efficient utilisation"],
    mnemonic: "utilise の名詞形。use より事務的で、率を語るときに使う。",
    relatedWords: ["utilise", "use", "efficiency"],
  },
  {
    id: "validation",
    word: "validation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["検証、承認", "認めてもらうこと"],
    pronunciation: "/ˌvælɪˈdeɪʃn/",
    exampleSentence: "The study provides validation of the theory.",
    exampleTranslationJa: "その研究はその理論の裏づけとなる。",
    collocations: ["seek validation", "data validation", "external validation"],
    mnemonic: "validate の名詞形。心理面で「認めてもらうこと」の意味も広まっている。",
    relatedWords: ["validate", "confirmation", "approval"],
  },
  {
    id: "ventilation",
    word: "ventilation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["換気、通風"],
    pronunciation: "/ˌventɪˈleɪʃn/",
    exampleSentence: "The room has poor ventilation.",
    exampleTranslationJa: "その部屋は換気が悪い。",
    collocations: ["poor ventilation", "a ventilation system", "natural ventilation"],
    mnemonic: "ventilate の名詞形。ラテン語 ventus(風)から。",
    relatedWords: ["ventilate", "airflow", "air"],
  },
  {
    id: "victimisation",
    word: "victimisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不当な扱い、いじめ"],
    pronunciation: "/ˌvɪktɪmaɪˈzeɪʃn/",
    exampleSentence: "Staff are protected against victimisation.",
    exampleTranslationJa: "職員は不当な扱いから守られている。",
    collocations: ["protection from victimisation", "workplace victimisation"],
    mnemonic: "victim(被害者)+ -isation。職場や学校で狙い撃ちにされること。",
    relatedWords: ["victim", "bullying", "persecution"],
  },
  {
    id: "vindication",
    word: "vindication",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["潔白の証明、正当性の立証"],
    pronunciation: "/ˌvɪndɪˈkeɪʃn/",
    exampleSentence: "The result was a vindication of her approach.",
    exampleTranslationJa: "その結果は彼女のやり方の正しさを証明した。",
    collocations: ["a vindication of", "complete vindication"],
    mnemonic: "vindicate の名詞形。批判されていた側が正しかったと示されること。",
    relatedWords: ["vindicate", "justification", "proof"],
  },
  {
    id: "visualisation",
    word: "visualisation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["視覚化、イメージ化"],
    pronunciation: "/ˌvɪʒuəlaɪˈzeɪʃn/",
    exampleSentence: "Data visualisation makes the trend obvious.",
    exampleTranslationJa: "データの視覚化がその傾向を明らかにする。",
    collocations: ["data visualisation", "a visualisation tool"],
    mnemonic: "visualise の名詞形。図やグラフにして見えるようにすること。",
    relatedWords: ["visualise", "graphic", "imagery"],
  },
  {
    id: "expensive",
    word: "expensive",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["高価な、費用のかかる"],
    pronunciation: "/ɪkˈspensɪv/",
    exampleSentence: "Running a car is expensive in this city.",
    exampleTranslationJa: "この街では車の維持は費用がかかる。",
    collocations: ["an expensive mistake", "prohibitively expensive", "less expensive"],
    mnemonic: "expense(費用)+ -ive。cheap の反対。an expensive mistake は「高くつく失敗」。",
    relatedWords: ["costly", "pricey", "cheap"],
  },
  {
    id: "abrasive",
    word: "abrasive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["研磨性の", "(人柄が)とげとげしい"],
    pronunciation: "/əˈbreɪsɪv/",
    exampleSentence: "His abrasive manner puts people off.",
    exampleTranslationJa: "彼のとげとげしい態度は人を遠ざける。",
    collocations: ["an abrasive manner", "an abrasive cleaner"],
    mnemonic: "こすって削る(abrade)から。人について言うと「角が立つ」。",
    relatedWords: ["harsh", "rough", "gentle"],
  },
  {
    id: "adhesive",
    word: "adhesive",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["粘着性の", "接着剤"],
    pronunciation: "/ədˈhiːsɪv/",
    exampleSentence: "Use a strong adhesive for tiles.",
    exampleTranslationJa: "タイルには強力な接着剤を使いなさい。",
    collocations: ["adhesive tape", "a strong adhesive"],
    mnemonic: "adhere(くっつく)の形容詞形。adhesive tape はセロテープ類。",
    relatedWords: ["adhere", "glue", "sticky"],
  },
  {
    id: "affirmative",
    word: "affirmative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["肯定の"],
    pronunciation: "/əˈfɜːrmətɪv/",
    exampleSentence: "The answer was in the affirmative.",
    exampleTranslationJa: "答えは肯定だった。",
    collocations: ["an affirmative answer", "affirmative action", "in the affirmative"],
    mnemonic: "affirm の形容詞形。affirmative action は「積極的差別是正措置」。",
    relatedWords: ["affirm", "positive", "negative"],
  },
  {
    id: "appreciative",
    word: "appreciative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感謝している、よさが分かる"],
    pronunciation: "/əˈpriːʃətɪv/",
    exampleSentence: "The audience was warm and appreciative.",
    exampleTranslationJa: "観客は温かく、よさを分かってくれた。",
    collocations: ["an appreciative audience", "appreciative of"],
    mnemonic: "appreciate の形容詞形。「ありがたく思う」と「価値が分かる」。",
    relatedWords: ["grateful", "thankful", "critical"],
  },
  {
    id: "argumentative",
    word: "argumentative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["理屈っぽい、議論好きの"],
    pronunciation: "/ˌɑːrɡjuˈmentətɪv/",
    exampleSentence: "He becomes argumentative after two drinks.",
    exampleTranslationJa: "彼は2杯飲むと理屈っぽくなる。",
    collocations: ["argumentative and rude", "in an argumentative mood"],
    mnemonic: "argument の形容詞形。よい意味では使わない。",
    relatedWords: ["quarrelsome", "combative", "agreeable"],
  },
  {
    id: "assertive",
    word: "assertive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自己主張のはっきりした"],
    pronunciation: "/əˈsɜːrtɪv/",
    exampleSentence: "She learned to be more assertive at work.",
    exampleTranslationJa: "彼女は職場でもっと自己主張することを覚えた。",
    collocations: ["assertive behaviour", "become more assertive"],
    mnemonic: "assert の形容詞形。aggressive(攻撃的)とは違い、ほめ言葉になりうる。",
    relatedWords: ["confident", "forceful", "passive"],
  },
  {
    id: "attentive",
    word: "attentive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["注意深い、気配りのある"],
    pronunciation: "/əˈtentɪv/",
    exampleSentence: "The staff were attentive without being intrusive.",
    exampleTranslationJa: "職員は出しゃばらずに気を配ってくれた。",
    collocations: ["an attentive audience", "attentive to detail"],
    mnemonic: "attend(注意を向ける)の形容詞形。「聞き手として熱心」の意味も。",
    relatedWords: ["alert", "considerate", "inattentive"],
  },
  {
    id: "authoritative",
    word: "authoritative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["権威ある、信頼できる", "威厳のある"],
    pronunciation: "/əˈθɔːrəteɪtɪv/",
    exampleSentence: "This is the authoritative account of the war.",
    exampleTranslationJa: "これはその戦争についての定説となる記述だ。",
    collocations: ["an authoritative source", "an authoritative tone"],
    mnemonic: "authority の形容詞形。authoritarian(権威主義的な)とは全く別物。",
    relatedWords: ["definitive", "reliable", "authoritarian"],
  },
  {
    id: "captive",
    word: "captive",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["捕らわれた", "捕虜"],
    pronunciation: "/ˈkæptɪv/",
    exampleSentence: "The birds were held captive for months.",
    exampleTranslationJa: "その鳥は何か月も捕らわれていた。",
    collocations: ["hold captive", "a captive audience", "take captive"],
    mnemonic: "capture と同語根。a captive audience は「逃げ場のない聴衆」。",
    relatedWords: ["captivity", "prisoner", "free"],
  },
  {
    id: "coercive",
    word: "coercive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["強制的な、威圧的な"],
    pronunciation: "/koʊˈɜːrsɪv/",
    exampleSentence: "The law bans coercive control.",
    exampleTranslationJa: "その法律は威圧による支配を禁じている。",
    collocations: ["coercive measures", "coercive control"],
    mnemonic: "coerce の形容詞形。力や脅しで従わせる性質。",
    relatedWords: ["coerce", "forceful", "voluntary"],
  },
  {
    id: "communicative",
    word: "communicative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["話好きの、意思疎通の"],
    pronunciation: "/kəˈmjuːnɪkətɪv/",
    exampleSentence: "He is not very communicative in the mornings.",
    exampleTranslationJa: "彼は朝はあまり口をきかない。",
    collocations: ["communicative skills", "a communicative approach"],
    mnemonic: "communicate の形容詞形。語学教育の「コミュニカティブ・アプローチ」。",
    relatedWords: ["talkative", "expressive", "reserved"],
  },
  {
    id: "compulsive",
    word: "compulsive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["抑えられない、癖になる"],
    pronunciation: "/kəmˈpʌlsɪv/",
    exampleSentence: "He is a compulsive collector of old maps.",
    exampleTranslationJa: "彼は古地図を集めずにいられない。",
    collocations: ["a compulsive liar", "compulsive behaviour", "compulsive reading"],
    mnemonic: "compel(強いる)の形容詞形。compulsory(義務の)とは別語。",
    relatedWords: ["obsessive", "irresistible", "compulsory"],
  },
  {
    id: "conclusive",
    word: "conclusive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["決定的な"],
    pronunciation: "/kənˈkluːsɪv/",
    exampleSentence: "There is no conclusive evidence either way.",
    exampleTranslationJa: "どちらにも決定的な証拠はない。",
    collocations: ["conclusive evidence", "conclusive proof"],
    mnemonic: "conclude の形容詞形。それで議論が終わるほど強い、という意味。",
    relatedWords: ["decisive", "definitive", "inconclusive"],
  },
  {
    id: "conducive",
    word: "conducive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(conducive to で)〜に役立つ、〜しやすい"],
    pronunciation: "/kənˈduːsɪv/",
    exampleSentence: "The noise is not conducive to study.",
    exampleTranslationJa: "その騒音は勉強に向かない。",
    collocations: ["conducive to learning", "not conducive to"],
    mnemonic: "conduce(導く)の形容詞形。必ず conducive to ... の形で使う。",
    relatedWords: ["favourable", "helpful", "hindering"],
  },
  {
    id: "constructive",
    word: "constructive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["建設的な"],
    pronunciation: "/kənˈstrʌktɪv/",
    exampleSentence: "She offered constructive criticism.",
    exampleTranslationJa: "彼女は建設的な批判を述べた。",
    collocations: ["constructive criticism", "constructive dialogue"],
    mnemonic: "construct の形容詞形。destructive(破壊的な)の反対。",
    relatedWords: ["helpful", "positive", "destructive"],
  },
  {
    id: "contemplative",
    word: "contemplative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["物思いにふける、瞑想的な"],
    pronunciation: "/kənˈtemplətɪv/",
    exampleSentence: "He was in a contemplative mood.",
    exampleTranslationJa: "彼は物思いにふけっていた。",
    collocations: ["a contemplative mood", "a contemplative life"],
    mnemonic: "contemplate の形容詞形。静かに深く考えている状態。",
    relatedWords: ["thoughtful", "reflective", "meditative"],
  },
  {
    id: "corrective",
    word: "corrective",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["是正の、矯正の"],
    pronunciation: "/kəˈrektɪv/",
    exampleSentence: "Corrective action must be taken at once.",
    exampleTranslationJa: "是正措置をただちに取らねばならない。",
    collocations: ["corrective action", "corrective lenses"],
    mnemonic: "correct の形容詞形。品質管理の corrective action(是正処置)。",
    relatedWords: ["correct", "remedial", "preventive"],
  },
  {
    id: "deductive",
    word: "deductive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["演繹的な"],
    pronunciation: "/dɪˈdʌktɪv/",
    exampleSentence: "Detectives use deductive reasoning.",
    exampleTranslationJa: "刑事は演繹的な推論を用いる。",
    collocations: ["deductive reasoning", "deductive logic"],
    mnemonic: "一般則から個々を導くのが deductive。逆は inductive(帰納的)。",
    relatedWords: ["deduce", "logical", "inductive"],
  },
  {
    id: "demonstrative",
    word: "demonstrative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感情を表に出す", "(文法の)指示の"],
    pronunciation: "/dɪˈmɑːnstrətɪv/",
    exampleSentence: "He is not a demonstrative man.",
    exampleTranslationJa: "彼は感情を表に出す人ではない。",
    collocations: ["a demonstrative person", "a demonstrative pronoun"],
    mnemonic: "demonstrate の形容詞形。this / that は demonstrative pronouns。",
    relatedWords: ["expressive", "open", "reserved"],
  },
  {
    id: "depressive",
    word: "depressive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うつの、憂うつにさせる"],
    pronunciation: "/dɪˈpresɪv/",
    exampleSentence: "She was treated for a depressive illness.",
    exampleTranslationJa: "彼女はうつ病の治療を受けた。",
    collocations: ["a depressive episode", "depressive symptoms"],
    mnemonic: "depress の形容詞形。医学用語としての「うつの」。",
    relatedWords: ["depression", "gloomy", "uplifting"],
  },
  {
    id: "derivative",
    word: "derivative",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["独創性のない", "派生物、金融派生商品"],
    pronunciation: "/dɪˈrɪvətɪv/",
    exampleSentence: "The novel is clever but derivative.",
    exampleTranslationJa: "その小説はうまいが独創性がない。",
    collocations: ["highly derivative", "financial derivatives"],
    mnemonic: "derive の形容詞形。作品の批評では「二番煎じ」という悪口。",
    relatedWords: ["derive", "unoriginal", "original"],
  },
  {
    id: "descriptive",
    word: "descriptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["描写的な、記述的な"],
    pronunciation: "/dɪˈskrɪptɪv/",
    exampleSentence: "The report is descriptive rather than analytical.",
    exampleTranslationJa: "その報告書は分析的というより記述的だ。",
    collocations: ["descriptive writing", "a descriptive study"],
    mnemonic: "describe の形容詞形。prescriptive(規範的な)と対で使う。",
    relatedWords: ["describe", "narrative", "prescriptive"],
  },
  {
    id: "digestive",
    word: "digestive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["消化の"],
    pronunciation: "/daɪˈdʒestɪv/",
    exampleSentence: "Fibre supports the digestive system.",
    exampleTranslationJa: "食物繊維は消化器系を助ける。",
    collocations: ["the digestive system", "digestive problems"],
    mnemonic: "digest の形容詞形。the digestive system(消化器系)で頻出。",
    relatedWords: ["digest", "digestion", "stomach"],
  },
  {
    id: "disruptive",
    word: "disruptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["混乱させる", "(業界を)一変させる"],
    pronunciation: "/dɪsˈrʌptɪv/",
    exampleSentence: "Disruptive behaviour is not tolerated.",
    exampleTranslationJa: "授業を乱す行為は認められない。",
    collocations: ["disruptive behaviour", "disruptive technology"],
    mnemonic: "disrupt の形容詞形。IT では「既存の仕組みを覆す」という良い意味も。",
    relatedWords: ["disrupt", "unsettling", "orderly"],
  },
  {
    id: "divisive",
    word: "divisive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["対立を生む、分断的な"],
    pronunciation: "/dɪˈvaɪsɪv/",
    exampleSentence: "The policy proved deeply divisive.",
    exampleTranslationJa: "その政策は深い分断を生んだ。",
    collocations: ["a divisive issue", "deeply divisive"],
    mnemonic: "divide の形容詞形。人々を二つに割ってしまう性質。",
    relatedWords: ["divide", "controversial", "unifying"],
  },
  {
    id: "emotive",
    word: "emotive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感情に訴える、感情的になりやすい"],
    pronunciation: "/ɪˈmoʊtɪv/",
    exampleSentence: "Immigration is an emotive subject.",
    exampleTranslationJa: "移民は感情を刺激する話題だ。",
    collocations: ["an emotive issue", "emotive language"],
    mnemonic: "emotional が「感情的な人」、emotive は「感情を呼び起こすもの」。",
    relatedWords: ["emotional", "charged", "neutral"],
  },
  {
    id: "evasive",
    word: "evasive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["言い逃れの、はっきりしない"],
    pronunciation: "/ɪˈveɪsɪv/",
    exampleSentence: "He gave an evasive answer.",
    exampleTranslationJa: "彼はあいまいな答えを返した。",
    collocations: ["an evasive answer", "evasive action"],
    mnemonic: "evade(逃れる)の形容詞形。take evasive action は「回避行動を取る」。",
    relatedWords: ["evade", "elusive", "direct"],
  },
  {
    id: "evocative",
    word: "evocative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(記憶や感情を)呼び起こす"],
    pronunciation: "/ɪˈvɑːkətɪv/",
    exampleSentence: "The smell is evocative of childhood.",
    exampleTranslationJa: "そのにおいは子ども時代を呼び起こす。",
    collocations: ["evocative of", "highly evocative"],
    mnemonic: "evoke の形容詞形。evocative of ... の形で使う。",
    relatedWords: ["evoke", "suggestive", "reminiscent"],
  },
  {
    id: "expansive",
    word: "expansive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["広々とした", "(態度が)おおらかな"],
    pronunciation: "/ɪkˈspænsɪv/",
    exampleSentence: "The house has an expansive view of the sea.",
    exampleTranslationJa: "その家からは海の広々とした眺めが見える。",
    collocations: ["an expansive view", "in expansive mood"],
    mnemonic: "expand の形容詞形。空間の広さと、人の打ち解けた様子。",
    relatedWords: ["expand", "broad", "narrow"],
  },
  {
    id: "expressive",
    word: "expressive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["表情豊かな、よく表す"],
    pronunciation: "/ɪkˈspresɪv/",
    exampleSentence: "She has a very expressive face.",
    exampleTranslationJa: "彼女はとても表情豊かだ。",
    collocations: ["an expressive face", "expressive language"],
    mnemonic: "express の形容詞形。感情がよく表に出ること。",
    relatedWords: ["express", "eloquent", "impassive"],
  },
  {
    id: "figurative",
    word: "figurative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["比喩的な"],
    pronunciation: "/ˈfɪɡjərətɪv/",
    exampleSentence: "He used the word in a figurative sense.",
    exampleTranslationJa: "彼はその語を比喩的な意味で使った。",
    collocations: ["a figurative sense", "figurative language"],
    mnemonic: "figure(あや)の形容詞形。literal(文字どおりの)の反対。",
    relatedWords: ["metaphorical", "literal", "symbolic"],
  },
  {
    id: "formative",
    word: "formative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["形成期の、人格を作る"],
    pronunciation: "/ˈfɔːrmətɪv/",
    exampleSentence: "Those were his formative years.",
    exampleTranslationJa: "あれが彼の人格形成期だった。",
    collocations: ["formative years", "a formative influence", "formative assessment"],
    mnemonic: "form の形容詞形。教育の formative assessment は「途中の見取り評価」。",
    relatedWords: ["form", "developmental", "decisive"],
  },
  {
    id: "furtive",
    word: "furtive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["こそこそした、人目を忍ぶ"],
    pronunciation: "/ˈfɜːrtɪv/",
    exampleSentence: "He cast a furtive glance at the door.",
    exampleTranslationJa: "彼はこっそり扉のほうを見た。",
    collocations: ["a furtive glance", "furtive movements"],
    mnemonic: "ラテン語 fur(泥棒)から。後ろめたさが表に出ている様子。",
    relatedWords: ["secretive", "sneaky", "open"],
  },
  {
    id: "illustrative",
    word: "illustrative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["例として示す、説明的な"],
    pronunciation: "/ɪˈlʌstrətɪv/",
    exampleSentence: "The case is illustrative of a wider problem.",
    exampleTranslationJa: "その事例はより広い問題を示す例だ。",
    collocations: ["illustrative of", "for illustrative purposes"],
    mnemonic: "illustrate の形容詞形。be illustrative of ... の形で使う。",
    relatedWords: ["illustrate", "representative", "typical"],
  },
  {
    id: "immersive",
    word: "immersive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["没入感のある"],
    pronunciation: "/ɪˈmɜːrsɪv/",
    exampleSentence: "The exhibition offers an immersive experience.",
    exampleTranslationJa: "その展示は没入感のある体験を提供する。",
    collocations: ["an immersive experience", "immersive technology"],
    mnemonic: "immerse の形容詞形。VR や展示の宣伝文句で近年よく使う。",
    relatedWords: ["immerse", "engrossing", "detached"],
  },
  {
    id: "indicative",
    word: "indicative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["示している", "(文法の)直説法の"],
    pronunciation: "/ɪnˈdɪkətɪv/",
    exampleSentence: "The figures are indicative of a wider trend.",
    exampleTranslationJa: "その数字はより広い傾向を示している。",
    collocations: ["indicative of", "an indicative price"],
    mnemonic: "indicate の形容詞形。be indicative of ... の形で使う。",
    relatedWords: ["indicate", "suggestive", "conclusive"],
  },
  {
    id: "inductive",
    word: "inductive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["帰納的な"],
    pronunciation: "/ɪnˈdʌktɪv/",
    exampleSentence: "Science relies on inductive reasoning.",
    exampleTranslationJa: "科学は帰納的な推論に頼っている。",
    collocations: ["inductive reasoning", "an inductive approach"],
    mnemonic: "個々の観察から一般則を導く。deductive(演繹的)の反対。",
    relatedWords: ["induce", "empirical", "deductive"],
  },
  {
    id: "inflammatory",
    word: "inflammatory",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["扇動的な", "炎症を起こす"],
    pronunciation: "/ɪnˈflæmətɔːri/",
    exampleSentence: "He was criticised for inflammatory remarks.",
    exampleTranslationJa: "彼は扇動的な発言で批判された。",
    collocations: ["inflammatory remarks", "anti-inflammatory drugs"],
    mnemonic: "flame(炎)が語根。人を怒らせる発言と、体の炎症の両方。",
    relatedWords: ["provocative", "incendiary", "soothing"],
  },
  {
    id: "instinctive",
    word: "instinctive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["本能的な、直感的な"],
    pronunciation: "/ɪnˈstɪŋktɪv/",
    exampleSentence: "Her reaction was instinctive.",
    exampleTranslationJa: "彼女の反応は本能的だった。",
    collocations: ["an instinctive reaction", "instinctive knowledge"],
    mnemonic: "instinct の形容詞形。考える前に体が動くこと。",
    relatedWords: ["instinct", "intuitive", "deliberate"],
  },
  {
    id: "instructive",
    word: "instructive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ためになる、示唆に富む"],
    pronunciation: "/ɪnˈstrʌktɪv/",
    exampleSentence: "The comparison is instructive.",
    exampleTranslationJa: "その比較はためになる。",
    collocations: ["an instructive example", "highly instructive"],
    mnemonic: "instruct の形容詞形。「教えられるところが多い」。",
    relatedWords: ["instruct", "informative", "enlightening"],
  },
  {
    id: "interpretive",
    word: "interpretive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["解釈の、解説の"],
    pronunciation: "/ɪnˈtɜːrprətɪv/",
    exampleSentence: "The centre provides interpretive displays.",
    exampleTranslationJa: "その施設は解説つきの展示を用意している。",
    collocations: ["interpretive dance", "an interpretive centre"],
    mnemonic: "interpret の形容詞形。英では interpretative とも書く。",
    relatedWords: ["interpret", "explanatory", "literal"],
  },
  {
    id: "intrusive",
    word: "intrusive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["立ち入りすぎた、じゃまな"],
    pronunciation: "/ɪnˈtruːsɪv/",
    exampleSentence: "The questions felt intrusive.",
    exampleTranslationJa: "その質問は立ち入りすぎに感じられた。",
    collocations: ["intrusive questions", "intrusive surveillance"],
    mnemonic: "intrude の形容詞形。相手の領域に踏み込みすぎる感じ。",
    relatedWords: ["intrude", "invasive", "discreet"],
  },
  {
    id: "intuitive",
    word: "intuitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["直感的な", "(操作が)分かりやすい"],
    pronunciation: "/ɪnˈtuːɪtɪv/",
    exampleSentence: "The interface is clean and intuitive.",
    exampleTranslationJa: "その画面は整理されていて直感的に使える。",
    collocations: ["an intuitive interface", "intuitive understanding"],
    mnemonic: "intuition の形容詞形。IT では「説明なしで使える」の意味。",
    relatedWords: ["intuition", "instinctive", "confusing"],
  },
  {
    id: "inventive",
    word: "inventive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["工夫に富んだ、独創的な"],
    pronunciation: "/ɪnˈventɪv/",
    exampleSentence: "She found an inventive solution.",
    exampleTranslationJa: "彼女は工夫に富んだ解決策を見つけた。",
    collocations: ["an inventive solution", "highly inventive"],
    mnemonic: "invent の形容詞形。creative に近いが「手立てを考え出す」寄り。",
    relatedWords: ["invent", "creative", "unimaginative"],
  },
  {
    id: "investigative",
    word: "investigative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["調査の"],
    pronunciation: "/ɪnˈvestɪɡeɪtɪv/",
    exampleSentence: "Investigative journalism uncovered the fraud.",
    exampleTranslationJa: "調査報道がその不正を暴いた。",
    collocations: ["investigative journalism", "investigative powers"],
    mnemonic: "investigate の形容詞形。investigative journalism が定型。",
    relatedWords: ["investigate", "inquiring", "research"],
  },
  {
    id: "manipulative",
    word: "manipulative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["人を操るような"],
    pronunciation: "/məˈnɪpjələtɪv/",
    exampleSentence: "He is charming but manipulative.",
    exampleTranslationJa: "彼は感じはいいが人を操るところがある。",
    collocations: ["manipulative behaviour", "emotionally manipulative"],
    mnemonic: "manipulate の形容詞形。必ず悪い意味で使う。",
    relatedWords: ["manipulate", "scheming", "honest"],
  },
  {
    id: "normative",
    word: "normative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["規範的な"],
    pronunciation: "/ˈnɔːrmətɪv/",
    exampleSentence: "The paper takes a normative approach.",
    exampleTranslationJa: "その論文は規範的な立場を取る。",
    collocations: ["a normative claim", "normative theory"],
    mnemonic: "norm(規範)の形容詞形。「どうあるべきか」を論じる立場。",
    relatedWords: ["norm", "prescriptive", "descriptive"],
  },
  {
    id: "obsessive",
    word: "obsessive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["取りつかれたような"],
    pronunciation: "/əbˈsesɪv/",
    exampleSentence: "He is obsessive about punctuality.",
    exampleTranslationJa: "彼は時間厳守に病的にこだわる。",
    collocations: ["obsessive about", "obsessive behaviour"],
    mnemonic: "obsess の形容詞形。compulsive と組んで obsessive-compulsive。",
    relatedWords: ["obsess", "compulsive", "casual"],
  },
  {
    id: "operative",
    word: "operative",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["有効な、稼働中の", "作業員、工作員"],
    pronunciation: "/ˈɑːpərətɪv/",
    exampleSentence: "The new rule becomes operative in May.",
    exampleTranslationJa: "新しい規則は5月に発効する。",
    collocations: ["become operative", "the operative word"],
    mnemonic: "the operative word は「肝心なのはこの語」という言い方。",
    relatedWords: ["operate", "effective", "inoperative"],
  },
  {
    id: "perceptive",
    word: "perceptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["洞察力のある、よく気づく"],
    pronunciation: "/pərˈseptɪv/",
    exampleSentence: "That is a perceptive comment.",
    exampleTranslationJa: "それは鋭い指摘だ。",
    collocations: ["a perceptive observation", "highly perceptive"],
    mnemonic: "perceive の形容詞形。perceptible(知覚できる)とは別語。",
    relatedWords: ["perceive", "insightful", "obtuse"],
  },
  {
    id: "permissive",
    word: "permissive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["寛容すぎる、放任の"],
    pronunciation: "/pərˈmɪsɪv/",
    exampleSentence: "Critics called the policy too permissive.",
    exampleTranslationJa: "批判する側はその政策を寛容すぎると呼んだ。",
    collocations: ["a permissive society", "too permissive"],
    mnemonic: "permit の形容詞形。ふつう「甘すぎる」という批判で使う。",
    relatedWords: ["permit", "lenient", "strict"],
  },
  {
    id: "pervasive",
    word: "pervasive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["行き渡った、まん延した"],
    pronunciation: "/pərˈveɪsɪv/",
    exampleSentence: "Corruption was pervasive at every level.",
    exampleTranslationJa: "汚職はあらゆる階層に行き渡っていた。",
    collocations: ["a pervasive influence", "pervasive corruption"],
    mnemonic: "pervade(行き渡る)の形容詞形。すみずみまで及んでいること。",
    relatedWords: ["pervade", "widespread", "rare"],
  },
  {
    id: "possessive",
    word: "possessive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["独占欲の強い", "(文法の)所有格の"],
    pronunciation: "/pəˈzesɪv/",
    exampleSentence: "He is very possessive about his tools.",
    exampleTranslationJa: "彼は自分の道具に強い独占欲を持つ。",
    collocations: ["possessive about", "a possessive pronoun"],
    mnemonic: "possess の形容詞形。my / your は possessive pronouns。",
    relatedWords: ["possess", "jealous", "generous"],
  },
  {
    id: "predictive",
    word: "predictive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["予測の"],
    pronunciation: "/prɪˈdɪktɪv/",
    exampleSentence: "The model has strong predictive power.",
    exampleTranslationJa: "そのモデルは高い予測力を持つ。",
    collocations: ["predictive power", "predictive text", "predictive analytics"],
    mnemonic: "predict の形容詞形。スマホの予測変換は predictive text。",
    relatedWords: ["predict", "forecasting", "reactive"],
  },
  {
    id: "prescriptive",
    word: "prescriptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["規範を押しつける、指示的な"],
    pronunciation: "/prɪˈskrɪptɪv/",
    exampleSentence: "The guidance is advisory, not prescriptive.",
    exampleTranslationJa: "その指針は助言であって指示ではない。",
    collocations: ["prescriptive rules", "a prescriptive approach"],
    mnemonic: "prescribe の形容詞形。descriptive(あるがままを記述する)の反対。",
    relatedWords: ["prescribe", "dictatorial", "descriptive"],
  },
  {
    id: "preventive",
    word: "preventive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["予防の"],
    pronunciation: "/prɪˈventɪv/",
    exampleSentence: "Preventive care saves money in the long run.",
    exampleTranslationJa: "予防医療は長い目で見れば費用を抑える。",
    collocations: ["preventive measures", "preventive medicine"],
    mnemonic: "prevent の形容詞形。preventative とも書く。",
    relatedWords: ["prevent", "precautionary", "curative"],
  },
  {
    id: "primitive",
    word: "primitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["原始的な、素朴な"],
    pronunciation: "/ˈprɪmətɪv/",
    exampleSentence: "The equipment was primitive but it worked.",
    exampleTranslationJa: "その装備は原始的だったが役には立った。",
    collocations: ["primitive tools", "a primitive society"],
    mnemonic: "prime(最初の)と同語根。「初期の」から「粗末な」へ。",
    relatedWords: ["prime", "basic", "advanced"],
  },
  {
    id: "prohibitive",
    word: "prohibitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(値段が)手が出ないほど高い", "禁止の"],
    pronunciation: "/prəˈhɪbətɪv/",
    exampleSentence: "The cost of repair was prohibitive.",
    exampleTranslationJa: "修理費は手が出ないほど高かった。",
    collocations: ["prohibitively expensive", "a prohibitive cost"],
    mnemonic: "prohibit の形容詞形。「高くて事実上できない」が主な使い方。",
    relatedWords: ["prohibit", "excessive", "affordable"],
  },
  {
    id: "provocative",
    word: "provocative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["挑発的な、議論を呼ぶ"],
    pronunciation: "/prəˈvɑːkətɪv/",
    exampleSentence: "The article was deliberately provocative.",
    exampleTranslationJa: "その記事はわざと挑発的だった。",
    collocations: ["a provocative question", "deliberately provocative"],
    mnemonic: "provoke の形容詞形。怒らせる意図と、考えさせる意図の両方。",
    relatedWords: ["provoke", "challenging", "soothing"],
  },
  {
    id: "punitive",
    word: "punitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["懲罰的な"],
    pronunciation: "/ˈpjuːnətɪv/",
    exampleSentence: "The tariffs were seen as punitive.",
    exampleTranslationJa: "その関税は懲罰的だと見られた。",
    collocations: ["punitive damages", "punitive measures", "punitive tariffs"],
    mnemonic: "punish と同語根。punitive damages は「懲罰的損害賠償」。",
    relatedWords: ["punish", "penal", "lenient"],
  },
  {
    id: "reactive",
    word: "reactive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["受け身の、後手の", "反応しやすい"],
    pronunciation: "/riˈæktɪv/",
    exampleSentence: "The response has been reactive rather than planned.",
    exampleTranslationJa: "対応は計画的というより後手に回っている。",
    collocations: ["reactive rather than proactive", "highly reactive"],
    mnemonic: "react の形容詞形。proactive(先手を打つ)の反対。",
    relatedWords: ["react", "responsive", "proactive"],
  },
  {
    id: "receptive",
    word: "receptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["受け入れる姿勢の"],
    pronunciation: "/rɪˈseptɪv/",
    exampleSentence: "The board was receptive to the idea.",
    exampleTranslationJa: "理事会はその案を前向きに受け止めた。",
    collocations: ["receptive to", "a receptive audience"],
    mnemonic: "receive の形容詞形。be receptive to ... の形で使う。",
    relatedWords: ["receive", "open", "resistant"],
  },
  {
    id: "reflective",
    word: "reflective",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よく考える", "反射する", "反映している"],
    pronunciation: "/rɪˈflektɪv/",
    exampleSentence: "She is in a reflective mood today.",
    exampleTranslationJa: "彼女は今日、物思いにふけっている。",
    collocations: ["a reflective mood", "reflective of", "reflective clothing"],
    mnemonic: "reflect の形容詞形。「振り返る」「反射する」「表している」の三義。",
    relatedWords: ["reflect", "thoughtful", "impulsive"],
  },
  {
    id: "regenerative",
    word: "regenerative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["再生の"],
    pronunciation: "/rɪˈdʒenərətɪv/",
    exampleSentence: "Regenerative farming rebuilds the soil.",
    exampleTranslationJa: "再生型農業は土壌を作り直す。",
    collocations: ["regenerative medicine", "regenerative agriculture"],
    mnemonic: "regenerate の形容詞形。医療にも農業にも使う近年の重要語。",
    relatedWords: ["regenerate", "renewable", "destructive"],
  },
  {
    id: "repressive",
    word: "repressive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["抑圧的な"],
    pronunciation: "/rɪˈpresɪv/",
    exampleSentence: "They fled a repressive regime.",
    exampleTranslationJa: "彼らは抑圧的な政権から逃れた。",
    collocations: ["a repressive regime", "repressive laws"],
    mnemonic: "repress の形容詞形。政治的な弾圧を語るときの定番。",
    relatedWords: ["repress", "oppressive", "liberal"],
  },
  {
    id: "reproductive",
    word: "reproductive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["生殖の"],
    pronunciation: "/ˌriːprəˈdʌktɪv/",
    exampleSentence: "The drug affects reproductive health.",
    exampleTranslationJa: "その薬は生殖の健康に影響する。",
    collocations: ["reproductive health", "the reproductive system"],
    mnemonic: "reproduce の形容詞形。reproductive rights(生殖に関する権利)。",
    relatedWords: ["reproduce", "fertility", "sexual"],
  },
  {
    id: "restorative",
    word: "restorative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["回復させる、修復の"],
    pronunciation: "/rɪˈstɔːrətɪv/",
    exampleSentence: "A restorative sleep made all the difference.",
    exampleTranslationJa: "ぐっすり眠れたことが大きな違いを生んだ。",
    collocations: ["restorative justice", "a restorative effect"],
    mnemonic: "restore の形容詞形。restorative justice は「修復的司法」。",
    relatedWords: ["restore", "healing", "damaging"],
  },
  {
    id: "restrictive",
    word: "restrictive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["制限的な、窮屈な"],
    pronunciation: "/rɪˈstrɪktɪv/",
    exampleSentence: "The rules are unnecessarily restrictive.",
    exampleTranslationJa: "その規則は不必要に制限的だ。",
    collocations: ["restrictive practices", "overly restrictive"],
    mnemonic: "restrict の形容詞形。自由を狭める性質。",
    relatedWords: ["restrict", "limiting", "permissive"],
  },
  {
    id: "speculative",
    word: "speculative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["推測に基づく", "投機的な"],
    pronunciation: "/ˈspekjələtɪv/",
    exampleSentence: "The report is largely speculative.",
    exampleTranslationJa: "その報告は大部分が推測だ。",
    collocations: ["highly speculative", "a speculative investment"],
    mnemonic: "speculate の形容詞形。証拠のない推測と、値上がり狙いの投機。",
    relatedWords: ["speculate", "conjectural", "factual"],
  },
  {
    id: "subjective",
    word: "subjective",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["主観的な"],
    pronunciation: "/səbˈdʒektɪv/",
    exampleSentence: "Beauty is largely subjective.",
    exampleTranslationJa: "美しさは多分に主観的だ。",
    collocations: ["a subjective judgement", "highly subjective"],
    mnemonic: "subject(主体)の形容詞形。objective(客観的な)の反対。",
    relatedWords: ["personal", "biased", "objective"],
  },
  {
    id: "submissive",
    word: "submissive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["従順な、言いなりの"],
    pronunciation: "/səbˈmɪsɪv/",
    exampleSentence: "She was expected to be quiet and submissive.",
    exampleTranslationJa: "彼女は静かで従順であることを期待された。",
    collocations: ["a submissive role", "submissive behaviour"],
    mnemonic: "submit(従う)の形容詞形。assertive(自己主張する)の反対。",
    relatedWords: ["submit", "obedient", "assertive"],
  },
]
