import type { VocabularyEntry } from '../types'

// 増補 第24弾。-ic / -ish の形容詞と、-en / -ify の動詞。
// 接尾辞の働き(-en は「〜にする」、-ify は「〜化する」、-ish は「〜っぽい」)を
// 覚えるヒントに書いて、初見の語も分解して読めるようにする。
export const plus24: VocabularyEntry[] = [
  {
    id: "patriotic",
    word: "patriotic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["愛国的な"],
    pronunciation: "/ˌpeɪtriˈɑːtɪk/",
    exampleSentence: "Flags went up in a patriotic display.",
    exampleTranslationJa: "愛国心を示して旗が掲げられた。",
    collocations: ["a patriotic duty", "patriotic songs"],
    mnemonic: "patriot(愛国者)の形容詞形。pater(父)が語根で「祖国の」。",
    relatedWords: ["patriot", "nationalistic", "unpatriotic"],
  },
  {
    id: "pathetic",
    word: "pathetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["情けない、みじめな", "痛ましい"],
    pronunciation: "/pəˈθetɪk/",
    exampleSentence: "That was a pathetic excuse.",
    exampleTranslationJa: "それは情けない言い訳だった。",
    collocations: ["a pathetic attempt", "look pathetic"],
    mnemonic: "pathos(感情)が語根。同情を誘う意味から「情けない」という非難へ。",
    relatedWords: ["pitiful", "feeble", "impressive"],
  },
  {
    id: "periodic",
    word: "periodic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["周期的な、定期的な"],
    pronunciation: "/ˌpɪriˈɑːdɪk/",
    exampleSentence: "The machine needs periodic maintenance.",
    exampleTranslationJa: "その機械は定期的な整備を必要とする。",
    collocations: ["periodic checks", "the periodic table"],
    mnemonic: "period の形容詞形。the periodic table は「周期表」。",
    relatedWords: ["period", "regular", "constant"],
  },
  {
    id: "phonetic",
    word: "phonetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["音声の、発音記号の"],
    pronunciation: "/fəˈnetɪk/",
    exampleSentence: "The dictionary gives a phonetic transcription.",
    exampleTranslationJa: "その辞書は発音表記を載せている。",
    collocations: ["a phonetic alphabet", "phonetic spelling"],
    mnemonic: "phone(音)が語根。telephone・symphony と同じ部品。",
    relatedWords: ["phonetics", "sound", "spelling"],
  },
  {
    id: "photographic",
    word: "photographic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["写真の", "(記憶が)写真のような"],
    pronunciation: "/ˌfoʊtəˈɡræfɪk/",
    exampleSentence: "She has an almost photographic memory.",
    exampleTranslationJa: "彼女はほとんど写真のような記憶力を持つ。",
    collocations: ["photographic evidence", "a photographic memory"],
    mnemonic: "photo(光)+ graph(描く)。a photographic memory は「一度見たら忘れない記憶」。",
    relatedWords: ["photograph", "visual", "image"],
  },
  {
    id: "poetic",
    word: "poetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["詩的な"],
    pronunciation: "/poʊˈetɪk/",
    exampleSentence: "The description was almost poetic.",
    exampleTranslationJa: "その描写はほとんど詩的だった。",
    collocations: ["poetic language", "poetic justice", "poetic licence"],
    mnemonic: "poetic justice は「因果応報」、poetic licence は「表現上の逸脱」。",
    relatedWords: ["poetry", "lyrical", "prosaic"],
  },
  {
    id: "prehistoric",
    word: "prehistoric",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有史以前の", "(口語)大昔の"],
    pronunciation: "/ˌpriːhɪˈstɔːrɪk/",
    exampleSentence: "The cave contains prehistoric paintings.",
    exampleTranslationJa: "その洞窟には有史以前の絵がある。",
    collocations: ["prehistoric times", "prehistoric remains"],
    mnemonic: "pre-(前)+ historic。文字記録が残る前の時代。",
    relatedWords: ["ancient", "primitive", "modern"],
  },
  {
    id: "prolific",
    word: "prolific",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["多作の、多産の"],
    pronunciation: "/prəˈlɪfɪk/",
    exampleSentence: "She was a prolific writer of short stories.",
    exampleTranslationJa: "彼女は短編を多く書いた作家だった。",
    collocations: ["a prolific writer", "a prolific scorer"],
    mnemonic: "proliferate(急増する)と同語根。次々に生み出すこと。",
    relatedWords: ["productive", "fertile", "unproductive"],
  },
  {
    id: "prophetic",
    word: "prophetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["予言的な、先を見通した"],
    pronunciation: "/prəˈfetɪk/",
    exampleSentence: "His warning turned out to be prophetic.",
    exampleTranslationJa: "彼の警告は予言的なものだった。",
    collocations: ["prophetic words", "prove prophetic"],
    mnemonic: "prophecy(予言)の形容詞形。あとから見て当たっていた発言に使う。",
    relatedWords: ["prophecy", "visionary", "shortsighted"],
  },
  {
    id: "rhetorical",
    word: "rhetorical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["修辞的な、言葉巧みな"],
    pronunciation: "/rɪˈtɔːrɪkl/",
    exampleSentence: "That was a rhetorical question.",
    exampleTranslationJa: "それは答えを求めない問いだった。",
    collocations: ["a rhetorical question", "rhetorical devices"],
    mnemonic: "a rhetorical question は「答えを期待しない問いかけ」。",
    relatedWords: ["rhetoric", "persuasive", "literal"],
  },
  {
    id: "rhythmic",
    word: "rhythmic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["リズミカルな、規則正しい"],
    pronunciation: "/ˈrɪðmɪk/",
    exampleSentence: "The rhythmic sound of the waves calmed her.",
    exampleTranslationJa: "波の規則正しい音が彼女を落ち着かせた。",
    collocations: ["a rhythmic beat", "rhythmic movement"],
    mnemonic: "rhythm の形容詞形。h の位置に注意するつづり。",
    relatedWords: ["rhythm", "regular", "erratic"],
  },
  {
    id: "robotic",
    word: "robotic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ロボットの、機械的な"],
    pronunciation: "/roʊˈbɑːtɪk/",
    exampleSentence: "His delivery was flat and robotic.",
    exampleTranslationJa: "彼の話し方は平板で機械的だった。",
    collocations: ["robotic surgery", "a robotic voice"],
    mnemonic: "robot の形容詞形。人の動きや話し方が「感情なく機械的」の意味も。",
    relatedWords: ["robot", "mechanical", "natural"],
  },
  {
    id: "sarcastic",
    word: "sarcastic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["皮肉な、あてこすりの"],
    pronunciation: "/sɑːrˈkæstɪk/",
    exampleSentence: "There was a sarcastic edge to his voice.",
    exampleTranslationJa: "彼の声には皮肉な調子があった。",
    collocations: ["a sarcastic remark", "sound sarcastic"],
    mnemonic: "sarcasm の形容詞形。相手を刺す意図がある点で、irony より攻撃的。",
    relatedWords: ["sarcasm", "cutting", "sincere"],
  },
  {
    id: "schematic",
    word: "schematic",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["図式的な", "配線図、概略図"],
    pronunciation: "/skiːˈmætɪk/",
    exampleSentence: "The diagram is schematic, not to scale.",
    exampleTranslationJa: "その図は図式的なもので、縮尺どおりではない。",
    collocations: ["a schematic diagram", "in schematic form"],
    mnemonic: "scheme(図式)の形容詞形。細部を省いて構造だけ示すこと。",
    relatedWords: ["scheme", "diagrammatic", "detailed"],
  },
  {
    id: "seismic",
    word: "seismic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["地震の", "(変化が)地殻変動的な"],
    pronunciation: "/ˈsaɪzmɪk/",
    exampleSentence: "The vote marked a seismic shift in politics.",
    exampleTranslationJa: "その投票は政治の地殻変動を示した。",
    collocations: ["seismic activity", "a seismic shift"],
    mnemonic: "ギリシャ語 seismos(揺れ)から。a seismic shift(大変動)が比喩の定型。",
    relatedWords: ["earthquake", "dramatic", "minor"],
  },
  {
    id: "semantic",
    word: "semantic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["意味の、語義の"],
    pronunciation: "/sɪˈmæntɪk/",
    exampleSentence: "The disagreement is purely semantic.",
    exampleTranslationJa: "その食い違いは単なる言葉の意味の問題だ。",
    collocations: ["a semantic argument", "semantic change"],
    mnemonic: "semantics(意味論)の形容詞形。「言葉尻の問題」という含みでも使う。",
    relatedWords: ["meaning", "semantics", "syntactic"],
  },
  {
    id: "simplistic",
    word: "simplistic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["単純すぎる、短絡的な"],
    pronunciation: "/sɪmˈplɪstɪk/",
    exampleSentence: "That view is simplistic.",
    exampleTranslationJa: "その見方は単純すぎる。",
    collocations: ["a simplistic view", "overly simplistic"],
    mnemonic: "simple(単純な)と違い、必ず批判の意味。「単純化しすぎ」。",
    relatedWords: ["superficial", "reductive", "nuanced"],
  },
  {
    id: "sonic",
    word: "sonic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["音の、音速の"],
    pronunciation: "/ˈsɑːnɪk/",
    exampleSentence: "A sonic boom shook the windows.",
    exampleTranslationJa: "衝撃波が窓を揺らした。",
    collocations: ["a sonic boom", "sonic waves"],
    mnemonic: "sound と同語根。supersonic は「超音速の」。",
    relatedWords: ["sound", "acoustic", "silent"],
  },
  {
    id: "stylistic",
    word: "stylistic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["文体の、様式上の"],
    pronunciation: "/staɪˈlɪstɪk/",
    exampleSentence: "The changes are stylistic rather than substantive.",
    exampleTranslationJa: "その変更は中身ではなく文体上のものだ。",
    collocations: ["stylistic differences", "a stylistic choice"],
    mnemonic: "style の形容詞形。stylish(おしゃれな)とは別語。",
    relatedWords: ["style", "aesthetic", "substantive"],
  },
  {
    id: "synthetic",
    word: "synthetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["合成の、人工の"],
    pronunciation: "/sɪnˈθetɪk/",
    exampleSentence: "The jacket is made of synthetic fibres.",
    exampleTranslationJa: "その上着は合成繊維でできている。",
    collocations: ["synthetic materials", "synthetic fibres"],
    mnemonic: "synthesis(合成)の形容詞形。natural(天然の)の反対。",
    relatedWords: ["artificial", "man-made", "natural"],
  },
  {
    id: "telescopic",
    word: "telescopic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["望遠の、伸縮する"],
    pronunciation: "/ˌteləˈskɑːpɪk/",
    exampleSentence: "The tripod has telescopic legs.",
    exampleTranslationJa: "その三脚は伸縮式の脚を持つ。",
    collocations: ["a telescopic lens", "telescopic legs"],
    mnemonic: "telescope の形容詞形。筒が入れ子で伸び縮みすることから。",
    relatedWords: ["telescope", "extendable", "fixed"],
  },
  {
    id: "therapeutic",
    word: "therapeutic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["治療の", "心が安らぐ"],
    pronunciation: "/ˌθerəˈpjuːtɪk/",
    exampleSentence: "Gardening is therapeutic for her.",
    exampleTranslationJa: "庭仕事は彼女にとって心を癒やすものだ。",
    collocations: ["therapeutic value", "therapeutic effects"],
    mnemonic: "therapy の形容詞形。医療の意味と、日常の「癒やされる」の両方。",
    relatedWords: ["therapy", "healing", "harmful"],
  },
  {
    id: "thematic",
    word: "thematic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["主題の、テーマ別の"],
    pronunciation: "/θɪˈmætɪk/",
    exampleSentence: "The exhibition is arranged thematically.",
    exampleTranslationJa: "その展示はテーマ別に構成されている。",
    collocations: ["a thematic approach", "thematic analysis"],
    mnemonic: "theme の形容詞形。研究の thematic analysis は「主題分析」。",
    relatedWords: ["theme", "topical", "random"],
  },
  {
    id: "traumatic",
    word: "traumatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["心に深い傷を残す"],
    pronunciation: "/trəˈmætɪk/",
    exampleSentence: "It was a traumatic experience for the family.",
    exampleTranslationJa: "それは家族にとって心に深い傷を残す経験だった。",
    collocations: ["a traumatic experience", "post-traumatic stress"],
    mnemonic: "trauma の形容詞形。PTSD は post-traumatic stress disorder。",
    relatedWords: ["trauma", "distressing", "soothing"],
  },
  {
    id: "volcanic",
    word: "volcanic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["火山の", "(感情が)激しい"],
    pronunciation: "/vɑːlˈkænɪk/",
    exampleSentence: "The island is volcanic in origin.",
    exampleTranslationJa: "その島は火山起源だ。",
    collocations: ["volcanic ash", "volcanic activity", "a volcanic temper"],
    mnemonic: "volcano の形容詞形。怒りが「噴火しそうな」意味にも使う。",
    relatedWords: ["volcano", "eruptive", "calm"],
  },
  {
    id: "bookish",
    word: "bookish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["本好きの、学者ぶった"],
    pronunciation: "/ˈbʊkɪʃ/",
    exampleSentence: "He was a quiet, bookish boy.",
    exampleTranslationJa: "彼は静かで本好きな少年だった。",
    collocations: ["a bookish child", "bookish language"],
    mnemonic: "book + -ish。-ish は「〜っぽい」。ややからかう響きがある。",
    relatedWords: ["studious", "scholarly", "outgoing"],
  },
  {
    id: "childish",
    word: "childish",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["子どもっぽい、幼稚な"],
    pronunciation: "/ˈtʃaɪldɪʃ/",
    exampleSentence: "Stop being so childish.",
    exampleTranslationJa: "そんなに幼稚なまねはやめなさい。",
    collocations: ["childish behaviour", "childish handwriting"],
    mnemonic: "childlike(子どものように純真な)は良い意味、childish は悪い意味。",
    relatedWords: ["immature", "juvenile", "childlike"],
  },
  {
    id: "foolish",
    word: "foolish",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["愚かな、ばかげた"],
    pronunciation: "/ˈfuːlɪʃ/",
    exampleSentence: "It was foolish to leave the door unlocked.",
    exampleTranslationJa: "戸に鍵をかけずに出るのは愚かだった。",
    collocations: ["a foolish mistake", "feel foolish"],
    mnemonic: "fool(愚か者)+ -ish。stupid よりやわらかい非難。",
    relatedWords: ["silly", "unwise", "sensible"],
  },
  {
    id: "greenish",
    word: "greenish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["緑がかった"],
    pronunciation: "/ˈɡriːnɪʃ/",
    exampleSentence: "The water had a greenish tinge.",
    exampleTranslationJa: "その水は緑がかった色合いをしていた。",
    collocations: ["a greenish colour", "greenish grey"],
    mnemonic: "-ish は色につくと「〜がかった」。reddish, bluish も同じ作り。",
    relatedWords: ["green", "tinted", "vivid"],
  },
  {
    id: "outlandish",
    word: "outlandish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["風変わりな、突拍子もない"],
    pronunciation: "/aʊtˈlændɪʃ/",
    exampleSentence: "He made some outlandish claims.",
    exampleTranslationJa: "彼は突拍子もない主張をいくつかした。",
    collocations: ["outlandish claims", "an outlandish outfit"],
    mnemonic: "out(外)+ land(国)。「よその国から来たような」が原義。",
    relatedWords: ["bizarre", "eccentric", "conventional"],
  },
  {
    id: "peckish",
    word: "peckish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["小腹がすいた(英)"],
    pronunciation: "/ˈpekɪʃ/",
    exampleSentence: "I am feeling a bit peckish.",
    exampleTranslationJa: "少し小腹がすいた。",
    collocations: ["feel peckish", "a bit peckish"],
    mnemonic: "peck(鳥がついばむ)+ -ish。hungry より軽い空腹。",
    relatedWords: ["hungry", "snackish", "full"],
  },
  {
    id: "reddish",
    word: "reddish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["赤みがかった"],
    pronunciation: "/ˈredɪʃ/",
    exampleSentence: "She has reddish brown hair.",
    exampleTranslationJa: "彼女は赤みがかった茶色の髪をしている。",
    collocations: ["reddish brown", "a reddish tint"],
    mnemonic: "red + -ish。d を重ねるつづりに注意。",
    relatedWords: ["red", "ruddy", "pale"],
  },
  {
    id: "sheepish",
    word: "sheepish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["きまり悪そうな"],
    pronunciation: "/ˈʃiːpɪʃ/",
    exampleSentence: "He gave a sheepish grin.",
    exampleTranslationJa: "彼はきまり悪そうに笑った。",
    collocations: ["a sheepish grin", "look sheepish"],
    mnemonic: "sheep(羊)+ -ish。羊のようにおどおどした、恥じ入った様子。",
    relatedWords: ["embarrassed", "abashed", "confident"],
  },
  {
    id: "snobbish",
    word: "snobbish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["お高くとまった"],
    pronunciation: "/ˈsnɑːbɪʃ/",
    exampleSentence: "They were snobbish about the neighbourhood.",
    exampleTranslationJa: "彼らはその界隈を見下していた。",
    collocations: ["snobbish attitude", "snobbish about"],
    mnemonic: "snob(俗物)+ -ish。身分や趣味で人を見下す態度。",
    relatedWords: ["superior", "condescending", "down-to-earth"],
  },
  {
    id: "squeamish",
    word: "squeamish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すぐ気分が悪くなる、神経質な"],
    pronunciation: "/ˈskwiːmɪʃ/",
    exampleSentence: "Look away if you are squeamish.",
    exampleTranslationJa: "気分が悪くなりやすい人は目をそらして。",
    collocations: ["squeamish about", "not for the squeamish"],
    mnemonic: "血やグロテスクなものに弱いこと。not for the squeamish が定型。",
    relatedWords: ["queasy", "sensitive", "tough"],
  },
  {
    id: "stylish",
    word: "stylish",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["おしゃれな、粋な"],
    pronunciation: "/ˈstaɪlɪʃ/",
    exampleSentence: "She always looks stylish.",
    exampleTranslationJa: "彼女はいつもおしゃれだ。",
    collocations: ["a stylish coat", "look stylish"],
    mnemonic: "style + -ish。stylistic(文体上の)とは意味が全く違う。",
    relatedWords: ["fashionable", "chic", "dowdy"],
  },
  {
    id: "blacken",
    word: "blacken",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["黒くする", "(評判を)傷つける"],
    pronunciation: "/ˈblækən/",
    exampleSentence: "Smoke had blackened the ceiling.",
    exampleTranslationJa: "煙が天井を黒くしていた。",
    collocations: ["blacken the walls", "blacken someone's name"],
    mnemonic: "black + -en(〜にする)。blacken someone's name は「名を汚す」。",
    relatedWords: ["darken", "tarnish", "whiten"],
  },
  {
    id: "brighten",
    word: "brighten",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["明るくする、明るくなる"],
    pronunciation: "/ˈbraɪtn/",
    exampleSentence: "Flowers brighten the room.",
    exampleTranslationJa: "花が部屋を明るくする。",
    collocations: ["brighten up", "brighten the room", "her face brightened"],
    mnemonic: "bright + -en。表情が「ぱっと明るくなる」意味も。",
    relatedWords: ["lighten", "cheer", "darken"],
  },
  {
    id: "dampen",
    word: "dampen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["湿らせる", "(熱意を)そぐ"],
    pronunciation: "/ˈdæmpən/",
    exampleSentence: "Nothing could dampen their enthusiasm.",
    exampleTranslationJa: "何も彼らの熱意をそぐことはできなかった。",
    collocations: ["dampen enthusiasm", "dampen a cloth"],
    mnemonic: "damp + -en。物を湿らせるのと、気持ちに水を差すのと両方。",
    relatedWords: ["moisten", "discourage", "boost"],
  },
  {
    id: "darken",
    word: "darken",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["暗くする、暗くなる"],
    pronunciation: "/ˈdɑːrkən/",
    exampleSentence: "The sky darkened before the storm.",
    exampleTranslationJa: "嵐の前に空が暗くなった。",
    collocations: ["the sky darkens", "darken his mood"],
    mnemonic: "dark + -en。天気にも表情にも使う。",
    relatedWords: ["dim", "shade", "brighten"],
  },
  {
    id: "deafen",
    word: "deafen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["耳を聞こえなくする"],
    pronunciation: "/ˈdefn/",
    exampleSentence: "The noise nearly deafened us.",
    exampleTranslationJa: "その音でこちらの耳が聞こえなくなりそうだった。",
    collocations: ["deafened by the noise", "a deafening roar"],
    mnemonic: "deaf + -en。形容詞 deafening(耳をつんざく)のほうがよく使う。",
    relatedWords: ["deaf", "stun", "soothe"],
  },
  {
    id: "deepen",
    word: "deepen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["深める、深まる"],
    pronunciation: "/ˈdiːpən/",
    exampleSentence: "The crisis deepened over the winter.",
    exampleTranslationJa: "その危機は冬の間に深まった。",
    collocations: ["deepen a crisis", "deepen understanding"],
    mnemonic: "deep + -en。物理的な深さにも、理解や危機の深まりにも使う。",
    relatedWords: ["intensify", "worsen", "ease"],
  },
  {
    id: "enlighten",
    word: "enlighten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["啓発する、教える"],
    pronunciation: "/ɪnˈlaɪtn/",
    exampleSentence: "Perhaps you could enlighten me.",
    exampleTranslationJa: "私に教えていただけませんか。",
    collocations: ["enlighten someone about", "an enlightening talk"],
    mnemonic: "en- + light(光)+ -en。知らないことに光を当てること。",
    relatedWords: ["inform", "educate", "confuse"],
  },
  {
    id: "harden",
    word: "harden",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["固くする、固くなる", "(態度を)硬化させる"],
    pronunciation: "/ˈhɑːrdn/",
    exampleSentence: "The glue hardens in ten minutes.",
    exampleTranslationJa: "その接着剤は10分で固まる。",
    collocations: ["harden into", "attitudes harden", "a hardened criminal"],
    mnemonic: "hard + -en。物にも態度にも使う。a hardened criminal は「札つきの犯罪者」。",
    relatedWords: ["solidify", "toughen", "soften"],
  },
  {
    id: "hasten",
    word: "hasten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["急がせる、早める", "急いで言う"],
    pronunciation: "/ˈheɪsn/",
    exampleSentence: "I hasten to add that this is only a guess.",
    exampleTranslationJa: "念のため申し添えますが、これは推測にすぎません。",
    collocations: ["hasten to add", "hasten the decline"],
    mnemonic: "haste(急ぎ)+ -en。t は読まない。I hasten to add ... が定型。",
    relatedWords: ["accelerate", "rush", "delay"],
  },
  {
    id: "lengthen",
    word: "lengthen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["長くする、長くなる"],
    pronunciation: "/ˈleŋθən/",
    exampleSentence: "The days lengthen after December.",
    exampleTranslationJa: "12月を過ぎると日が長くなる。",
    collocations: ["lengthen a skirt", "the days lengthen"],
    mnemonic: "length + -en。shorten の反対。",
    relatedWords: ["extend", "stretch", "shorten"],
  },
  {
    id: "lighten",
    word: "lighten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["軽くする", "明るくする"],
    pronunciation: "/ˈlaɪtn/",
    exampleSentence: "The reforms should lighten the workload.",
    exampleTranslationJa: "その改革は仕事の負担を軽くするはずだ。",
    collocations: ["lighten the load", "lighten up", "lighten the mood"],
    mnemonic: "light(軽い・明るい)の両方から。lighten up は「気を楽に」。",
    relatedWords: ["ease", "brighten", "darken"],
  },
  {
    id: "loosen",
    word: "loosen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["ゆるめる、ゆるむ"],
    pronunciation: "/ˈluːsn/",
    exampleSentence: "Loosen the screw half a turn.",
    exampleTranslationJa: "そのねじを半回転ゆるめてください。",
    collocations: ["loosen a screw", "loosen restrictions", "loosen your grip"],
    mnemonic: "loose + -en。規制を「緩和する」意味でも使う。",
    relatedWords: ["slacken", "relax", "tighten"],
  },
  {
    id: "moisten",
    word: "moisten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["湿らせる"],
    pronunciation: "/ˈmɔɪsn/",
    exampleSentence: "Moisten the edges of the pastry.",
    exampleTranslationJa: "生地のふちを湿らせてください。",
    collocations: ["moisten your lips", "moisten the cloth"],
    mnemonic: "moist + -en。t は読まない /ˈmɔɪsn/。",
    relatedWords: ["dampen", "wet", "dry"],
  },
  {
    id: "quicken",
    word: "quicken",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["速める、速くなる"],
    pronunciation: "/ˈkwɪkən/",
    exampleSentence: "She quickened her pace.",
    exampleTranslationJa: "彼女は歩調を速めた。",
    collocations: ["quicken your pace", "the pulse quickens"],
    mnemonic: "quick + -en。歩調や鼓動が速まることに使う。",
    relatedWords: ["accelerate", "hasten", "slow"],
  },
  {
    id: "ripen",
    word: "ripen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["熟す、熟させる"],
    pronunciation: "/ˈraɪpən/",
    exampleSentence: "Tomatoes ripen quickly on the windowsill.",
    exampleTranslationJa: "トマトは窓辺で早く熟す。",
    collocations: ["ripen in the sun", "let it ripen"],
    mnemonic: "ripe + -en。果物にも、計画が「機が熟す」意味にも使う。",
    relatedWords: ["mature", "develop", "rot"],
  },
  {
    id: "sharpen",
    word: "sharpen",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["とぐ、鋭くする", "(能力を)磨く"],
    pronunciation: "/ˈʃɑːrpən/",
    exampleSentence: "Sharpen the knife before you start.",
    exampleTranslationJa: "始める前に包丁をといでください。",
    collocations: ["sharpen a pencil", "sharpen your skills"],
    mnemonic: "sharp + -en。刃物にも技能にも使う。",
    relatedWords: ["hone", "whet", "blunt"],
  },
  {
    id: "shorten",
    word: "shorten",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["短くする、短くなる"],
    pronunciation: "/ˈʃɔːrtn/",
    exampleSentence: "Can you shorten the introduction?",
    exampleTranslationJa: "導入部を短くできますか。",
    collocations: ["shorten a list", "shorten the trousers"],
    mnemonic: "short + -en。lengthen の反対。",
    relatedWords: ["reduce", "trim", "lengthen"],
  },
  {
    id: "soften",
    word: "soften",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["やわらげる、やわらかくなる"],
    pronunciation: "/ˈsɔːfn/",
    exampleSentence: "Butter softens at room temperature.",
    exampleTranslationJa: "バターは室温でやわらかくなる。",
    collocations: ["soften the blow", "soften your tone"],
    mnemonic: "soft + -en。t は読まない。soften the blow は「衝撃を和らげる」。",
    relatedWords: ["ease", "mellow", "harden"],
  },
  {
    id: "stiffen",
    word: "stiffen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["こわばる、固くする", "(態度を)強める"],
    pronunciation: "/ˈstɪfn/",
    exampleSentence: "He stiffened when he heard the name.",
    exampleTranslationJa: "その名を聞いて彼は体をこわばらせた。",
    collocations: ["stiffen with fear", "stiffen the rules"],
    mnemonic: "stiff + -en。体のこわばりにも、規則の厳格化にも使う。",
    relatedWords: ["tense", "harden", "relax"],
  },
  {
    id: "straighten",
    word: "straighten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["まっすぐにする", "整える"],
    pronunciation: "/ˈstreɪtn/",
    exampleSentence: "He straightened his tie before entering.",
    exampleTranslationJa: "彼は入る前にネクタイを直した。",
    collocations: ["straighten up", "straighten your back", "straighten things out"],
    mnemonic: "straight + -en。straighten things out は「事態を収拾する」。",
    relatedWords: ["align", "tidy", "bend"],
  },
  {
    id: "sweeten",
    word: "sweeten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["甘くする", "(条件を)よくする"],
    pronunciation: "/ˈswiːtn/",
    exampleSentence: "They sweetened the offer with a bonus.",
    exampleTranslationJa: "彼らは賞与をつけて条件をよくした。",
    collocations: ["sweeten the deal", "sweeten with honey"],
    mnemonic: "sweet + -en。sweeten the deal は「条件を上乗せする」。",
    relatedWords: ["sugar", "improve", "sour"],
  },
  {
    id: "thicken",
    word: "thicken",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["濃くする、厚くする"],
    pronunciation: "/ˈθɪkən/",
    exampleSentence: "Stir until the sauce thickens.",
    exampleTranslationJa: "ソースにとろみがつくまでかき混ぜてください。",
    collocations: ["thicken the sauce", "the plot thickens"],
    mnemonic: "thick + -en。The plot thickens. は「話がややこしくなってきた」。",
    relatedWords: ["condense", "densify", "thin"],
  },
  {
    id: "toughen",
    word: "toughen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["強くする、厳しくする"],
    pronunciation: "/ˈtʌfn/",
    exampleSentence: "The government plans to toughen the rules.",
    exampleTranslationJa: "政府は規則を厳しくする方針だ。",
    collocations: ["toughen up", "toughen the law"],
    mnemonic: "tough + -en。規則の厳格化と、人が「たくましくなる」の両方。",
    relatedWords: ["strengthen", "harden", "soften"],
  },
  {
    id: "whiten",
    word: "whiten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["白くする"],
    pronunciation: "/ˈwaɪtn/",
    exampleSentence: "The paste is said to whiten teeth.",
    exampleTranslationJa: "そのペーストは歯を白くするとされる。",
    collocations: ["whiten teeth", "whitening cream"],
    mnemonic: "white + -en。歯磨き粉の宣伝でよく見る語。",
    relatedWords: ["bleach", "lighten", "blacken"],
  },
  {
    id: "worsen",
    word: "worsen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["悪化する、悪化させる"],
    pronunciation: "/ˈwɜːrsn/",
    exampleSentence: "Conditions worsened overnight.",
    exampleTranslationJa: "状況は一晩で悪化した。",
    collocations: ["conditions worsen", "worsen the situation"],
    mnemonic: "worse + -en。deteriorate のやさしい言い方。",
    relatedWords: ["deteriorate", "decline", "improve"],
  },
  {
    id: "diversify",
    word: "diversify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["多角化する、多様にする"],
    pronunciation: "/daɪˈvɜːrsɪfaɪ/",
    exampleSentence: "The farm diversified into tourism.",
    exampleTranslationJa: "その農場は観光にも手を広げた。",
    collocations: ["diversify into", "diversify your portfolio"],
    mnemonic: "diverse + -ify。事業や投資先を広げてリスクを分散すること。",
    relatedWords: ["diverse", "expand", "specialise"],
  },
  {
    id: "electrify",
    word: "electrify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["電化する", "(人を)興奮させる"],
    pronunciation: "/ɪˈlektrɪfaɪ/",
    exampleSentence: "The line was electrified in 1962.",
    exampleTranslationJa: "その路線は1962年に電化された。",
    collocations: ["electrify a railway", "electrify the crowd"],
    mnemonic: "electric + -ify。鉄道の電化と、聴衆を沸かせることの両方。",
    relatedWords: ["electric", "thrill", "excite"],
  },
  {
    id: "exemplify",
    word: "exemplify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["典型的に示す、例証する"],
    pronunciation: "/ɪɡˈzemplɪfaɪ/",
    exampleSentence: "This case exemplifies the problem.",
    exampleTranslationJa: "この事例はその問題を典型的に示している。",
    collocations: ["exemplify a trend", "perfectly exemplify"],
    mnemonic: "example + -ify。「よい例になっている」。",
    relatedWords: ["example", "illustrate", "obscure"],
  },
  {
    id: "falsify",
    word: "falsify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["改ざんする、偽る"],
    pronunciation: "/ˈfɔːlsɪfaɪ/",
    exampleSentence: "He was accused of falsifying the records.",
    exampleTranslationJa: "彼は記録の改ざんで告発された。",
    collocations: ["falsify records", "falsify data"],
    mnemonic: "false + -ify。科学では「反証する」の意味でも使う。",
    relatedWords: ["forge", "fake", "verify"],
  },
  {
    id: "gratify",
    word: "gratify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["満足させる"],
    pronunciation: "/ˈɡrætɪfaɪ/",
    exampleSentence: "It gratified her to see the results.",
    exampleTranslationJa: "その結果を見て彼女は満足した。",
    collocations: ["gratify a desire", "be gratified by"],
    mnemonic: "grateful と同語根。gratifying(満足のいく)の形でよく使う。",
    relatedWords: ["satisfy", "please", "frustrate"],
  },
  {
    id: "horrify",
    word: "horrify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["ぞっとさせる"],
    pronunciation: "/ˈhɔːrɪfaɪ/",
    exampleSentence: "The images horrified viewers.",
    exampleTranslationJa: "その映像は視聴者をぞっとさせた。",
    collocations: ["be horrified by", "horrified expression"],
    mnemonic: "horror + -ify。be horrified by ... の受け身が多い。",
    relatedWords: ["horror", "shock", "delight"],
  },
  {
    id: "pacify",
    word: "pacify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["なだめる、鎮める"],
    pronunciation: "/ˈpæsɪfaɪ/",
    exampleSentence: "She tried to pacify the crying child.",
    exampleTranslationJa: "彼女は泣いている子をなだめようとした。",
    collocations: ["pacify a crowd", "pacify a child"],
    mnemonic: "peace と同語根。Pacific Ocean(太平洋)も「穏やかな海」。",
    relatedWords: ["calm", "soothe", "provoke"],
  },
  {
    id: "personify",
    word: "personify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["体現する、擬人化する"],
    pronunciation: "/pərˈsɑːnɪfaɪ/",
    exampleSentence: "She personifies everything the club stands for.",
    exampleTranslationJa: "彼女はそのクラブの理念を体現している。",
    collocations: ["personify a quality", "the personification of"],
    mnemonic: "person + -ify。抽象的なものが人の形をとること。",
    relatedWords: ["embody", "represent", "abstract"],
  },
  {
    id: "purify",
    word: "purify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["浄化する、精製する"],
    pronunciation: "/ˈpjʊrɪfaɪ/",
    exampleSentence: "The filter purifies the water.",
    exampleTranslationJa: "そのフィルターが水を浄化する。",
    collocations: ["purify water", "purify the air"],
    mnemonic: "pure + -ify。水や空気から不純物を取り除くこと。",
    relatedWords: ["cleanse", "filter", "contaminate"],
  },
  {
    id: "signify",
    word: "signify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["意味する、示す"],
    pronunciation: "/ˈsɪɡnɪfaɪ/",
    exampleSentence: "A red flag signifies danger.",
    exampleTranslationJa: "赤旗は危険を示す。",
    collocations: ["signify agreement", "signify a change"],
    mnemonic: "sign(しるし)+ -ify。mean のかたい語。",
    relatedWords: ["indicate", "denote", "obscure"],
  },
  {
    id: "simplify",
    word: "simplify",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["単純にする、簡略化する"],
    pronunciation: "/ˈsɪmplɪfaɪ/",
    exampleSentence: "The form has been simplified.",
    exampleTranslationJa: "その用紙は簡略化された。",
    collocations: ["simplify the process", "greatly simplify"],
    mnemonic: "simple + -ify。complicate(複雑にする)の反対。",
    relatedWords: ["streamline", "clarify", "complicate"],
  },
  {
    id: "solidify",
    word: "solidify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["固まる、固める", "(立場を)固める"],
    pronunciation: "/səˈlɪdɪfaɪ/",
    exampleSentence: "The lava solidified into black rock.",
    exampleTranslationJa: "溶岩は固まって黒い岩になった。",
    collocations: ["solidify support", "solidify into"],
    mnemonic: "solid + -ify。物が固まるのと、支持や立場が固まるのと両方。",
    relatedWords: ["harden", "set", "liquefy"],
  },
  {
    id: "typify",
    word: "typify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["典型となる、特徴づける"],
    pronunciation: "/ˈtɪpɪfaɪ/",
    exampleSentence: "This building typifies the style of the period.",
    exampleTranslationJa: "この建物はその時代の様式の典型だ。",
    collocations: ["typify an era", "typify the approach"],
    mnemonic: "type + -ify。exemplify とほぼ同じ意味。",
    relatedWords: ["exemplify", "characterise", "differ"],
  },
]
