import type { VocabularyEntry } from '../types'

// 増補 第7弾。論説・学術で使う動詞。新聞の社説や論文でそのまま出てくる語をそろえる。
export const plus07: VocabularyEntry[] = [
  {
    id: "ascertain",
    word: "ascertain",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(調べて)確かめる、突き止める"],
    pronunciation: "/ˌæsərˈteɪn/",
    exampleSentence: "Police are trying to ascertain the cause of the fire.",
    exampleTranslationJa: "警察は火事の原因を突き止めようとしている。",
    collocations: ["ascertain the cause", "ascertain whether", "difficult to ascertain"],
    wordFormation: "as-(〜へ)+ certain(確かな)。「確かにする」。",
    mnemonic: "certain(確かな)が中にある。find out のかたい語。",
    relatedWords: ["determine", "establish", "verify"],
  },
  {
    id: "corroborate",
    word: "corroborate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(証言や説を)裏づける"],
    pronunciation: "/kəˈrɑːbəreɪt/",
    exampleSentence: "Two witnesses corroborated his account.",
    exampleTranslationJa: "2人の証人が彼の話を裏づけた。",
    collocations: ["corroborate evidence", "corroborate a story", "corroborated by"],
    wordFormation: "cor-(共に)+ robur(力)。「力を添える」。",
    mnemonic: "robust(頑丈な)と同語根。別の証拠が横から力を添えること。",
    relatedWords: ["confirm", "support", "verify"],
  },
  {
    id: "substantiate",
    word: "substantiate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(主張を)証拠で裏づける"],
    pronunciation: "/səbˈstænʃieɪt/",
    exampleSentence: "He could not substantiate his claim.",
    exampleTranslationJa: "彼は自分の主張を裏づけられなかった。",
    collocations: ["substantiate a claim", "substantiate allegations", "fail to substantiate"],
    wordFormation: "substance(実体)+ -ate。「中身を与える」。",
    mnemonic: "substance(中身)を与えること。中身のない主張を証拠で埋める。",
    relatedWords: ["prove", "corroborate", "evidence"],
  },
  {
    id: "refute",
    word: "refute",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["論破する、誤りだと示す"],
    pronunciation: "/rɪˈfjuːt/",
    exampleSentence: "The study refutes the earlier findings.",
    exampleTranslationJa: "その研究は以前の結果を覆している。",
    collocations: ["refute a claim", "refute the argument", "hard to refute"],
    mnemonic: "deny は「否定する」だけ、refute は「根拠を示して誤りだと証明する」。",
    relatedWords: ["disprove", "rebut", "deny"],
  },
  {
    id: "rebut",
    word: "rebut",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["反論する、言い返す"],
    pronunciation: "/rɪˈbʌt/",
    exampleSentence: "She rebutted each point in turn.",
    exampleTranslationJa: "彼女は各論点に順に反論した。",
    collocations: ["rebut an argument", "rebut the charge", "rebut point by point"],
    mnemonic: "refute が「誤りを証明する」、rebut は「反対の議論を返す」。名詞は rebuttal。",
    relatedWords: ["refute", "counter", "respond"],
  },
  {
    id: "contradict",
    word: "contradict",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["否定する、反対のことを言う", "矛盾する"],
    pronunciation: "/ˌkɑːntrəˈdɪkt/",
    exampleSentence: "The two reports contradict each other.",
    exampleTranslationJa: "その二つの報告は互いに矛盾している。",
    collocations: ["contradict yourself", "contradict each other", "flatly contradict"],
    wordFormation: "contra-(反対に)+ dict(言う)。",
    mnemonic: "contra(反対に)+ dict(言う)。dictionary・predict と同じ dict。",
    relatedWords: ["contradiction", "oppose", "conflict"],
  },
  {
    id: "reconcile",
    word: "reconcile",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(対立を)調停する、和解させる", "(食い違いを)整合させる"],
    pronunciation: "/ˈrekənsaɪl/",
    exampleSentence: "It is hard to reconcile the two accounts.",
    exampleTranslationJa: "その二つの説明を整合させるのは難しい。",
    collocations: ["reconcile differences", "be reconciled with", "reconcile A with B"],
    mnemonic: "人どうしなら「仲直りさせる」、数字や話なら「つじつまを合わせる」。",
    relatedWords: ["settle", "harmonise", "resolve"],
  },
  {
    id: "delineate",
    word: "delineate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(輪郭を)はっきり示す、詳しく述べる"],
    pronunciation: "/dɪˈlɪnieɪt/",
    exampleSentence: "The report delineates three possible routes.",
    exampleTranslationJa: "その報告書は三つの可能な道筋をはっきり示している。",
    collocations: ["clearly delineate", "delineate the boundaries", "delineate roles"],
    wordFormation: "de-(すっかり)+ linea(線)。「線を引いて示す」。",
    mnemonic: "line(線)が語根。線を引くように境目をはっきりさせる。",
    relatedWords: ["outline", "define", "describe"],
  },
  {
    id: "elucidate",
    word: "elucidate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(分かりにくいことを)解き明かす"],
    pronunciation: "/ɪˈluːsɪdeɪt/",
    exampleSentence: "Could you elucidate the second point?",
    exampleTranslationJa: "2点目を詳しく説明していただけますか。",
    collocations: ["elucidate the mechanism", "elucidate a point", "help to elucidate"],
    wordFormation: "e-(外へ)+ lucid(明るい)。「光の中に出す」。",
    mnemonic: "lucid(澄んだ)が語根。暗がりから光の中へ引き出すこと。",
    relatedWords: ["clarify", "explain", "illuminate"],
  },
  {
    id: "stipulate",
    word: "stipulate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(契約などで)明記する、条件として定める"],
    pronunciation: "/ˈstɪpjuleɪt/",
    exampleSentence: "The contract stipulates a 30-day notice period.",
    exampleTranslationJa: "その契約は30日の予告期間を定めている。",
    collocations: ["the contract stipulates", "stipulate that", "as stipulated in"],
    mnemonic: "契約書の定番動詞。「〜と書いてある」ではなく「条件として定めている」。",
    relatedWords: ["specify", "require", "contract"],
  },
  {
    id: "postulate",
    word: "postulate",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["仮定する、前提として置く", "仮定、公準"],
    pronunciation: "/ˈpɑːstʃuleɪt/",
    exampleSentence: "Early scientists postulated the existence of an unseen force.",
    exampleTranslationJa: "初期の科学者は目に見えない力の存在を仮定した。",
    collocations: ["postulate the existence of", "as postulated by"],
    mnemonic: "証明せずに「あることにして議論を進める」。assume のかたい語。",
    relatedWords: ["assume", "hypothesise", "premise"],
  },
  {
    id: "hypothesise",
    word: "hypothesise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["仮説を立てる"],
    pronunciation: "/haɪˈpɑːθəsaɪz/",
    exampleSentence: "Researchers hypothesise that sleep aids memory.",
    exampleTranslationJa: "研究者たちは睡眠が記憶を助けると仮説を立てている。",
    collocations: ["hypothesise that", "as hypothesised", "researchers hypothesise"],
    wordFormation: "hypothesis(仮説)+ -ise。",
    mnemonic: "米つづりは hypothesize。名詞 hypothesis の複数形は hypotheses。",
    relatedWords: ["hypothesis", "theorise", "predict"],
  },
  {
    id: "scrutinise",
    word: "scrutinise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["細かく調べる、精査する"],
    pronunciation: "/ˈskruːtənaɪz/",
    exampleSentence: "Auditors scrutinise every transaction.",
    exampleTranslationJa: "監査人はすべての取引を精査する。",
    collocations: ["closely scrutinise", "scrutinise the accounts", "scrutinise the evidence"],
    mnemonic: "米つづりは scrutinize。名詞 scrutiny は under scrutiny(監視下に)の形で頻出。",
    relatedWords: ["scrutiny", "examine", "inspect"],
  },
  {
    id: "appraise",
    word: "appraise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["評価する、値踏みする"],
    pronunciation: "/əˈpreɪz/",
    exampleSentence: "The expert appraised the painting at £40,000.",
    exampleTranslationJa: "専門家はその絵を4万ポンドと評価した。",
    collocations: ["appraise the value", "appraise performance", "critically appraise"],
    mnemonic: "praise(ほめる)と混同しやすい。appraise は「値打ちを測る」で、ほめるとは限らない。",
    relatedWords: ["appraisal", "evaluate", "assess"],
  },
  {
    id: "collate",
    word: "collate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(情報を)集めて照合する、そろえる"],
    pronunciation: "/kəˈleɪt/",
    exampleSentence: "We collated the results from all six sites.",
    exampleTranslationJa: "私たちは6か所すべての結果を集めて照合した。",
    collocations: ["collate data", "collate the results", "collate information"],
    mnemonic: "ただ集めるだけの collect と違い、突き合わせて整える含みがある。",
    relatedWords: ["compile", "gather", "combine"],
  },
  {
    id: "tabulate",
    word: "tabulate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["表にまとめる"],
    pronunciation: "/ˈtæbjuleɪt/",
    exampleSentence: "The findings are tabulated on page twelve.",
    exampleTranslationJa: "その結果は12ページに表としてまとめられている。",
    collocations: ["tabulate the results", "tabulated data", "tabulate responses"],
    wordFormation: "table(表)+ -ate。",
    mnemonic: "table(表)にすること。論文の Table 1 はこの作業の結果。",
    relatedWords: ["table", "chart", "list"],
  },
  {
    id: "quantify",
    word: "quantify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["数値で示す、量を測る"],
    pronunciation: "/ˈkwɑːntɪfaɪ/",
    exampleSentence: "It is hard to quantify the damage.",
    exampleTranslationJa: "その被害を数値で示すのは難しい。",
    collocations: ["difficult to quantify", "quantify the impact", "quantify the risk"],
    wordFormation: "quantity(量)+ -fy(〜にする)。",
    mnemonic: "quality(質)ではなく quantity(量)にすること。数字にできるかどうかの話。",
    relatedWords: ["measure", "calculate", "quantity"],
  },
  {
    id: "extrapolate",
    word: "extrapolate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(既知のデータから)推定する、外挿する"],
    pronunciation: "/ɪkˈstræpəleɪt/",
    exampleSentence: "You cannot extrapolate from such a small sample.",
    exampleTranslationJa: "そんなに小さな標本から推定することはできない。",
    collocations: ["extrapolate from", "extrapolate the trend", "dangerous to extrapolate"],
    wordFormation: "extra-(外へ)+ -polate(置く)。「範囲の外へ延ばす」。",
    mnemonic: "extra(外へ)。今あるデータの線を、その先へ延ばして予想すること。",
    relatedWords: ["infer", "predict", "project"],
  },
  {
    id: "entail",
    word: "entail",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(必然的に)伴う、必要とする"],
    pronunciation: "/ɪnˈteɪl/",
    exampleSentence: "The job entails a lot of travel.",
    exampleTranslationJa: "その仕事は出張が多い。",
    collocations: ["entail a risk", "what does it entail", "entail additional costs"],
    mnemonic: "What does it entail? は「それには何が伴うのか」＝「具体的に何をするのか」。",
    relatedWords: ["involve", "require", "imply"],
  },
  {
    id: "necessitate",
    word: "necessitate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["必要とさせる、やむを得なくさせる"],
    pronunciation: "/nəˈsesɪteɪt/",
    exampleSentence: "The delay necessitated a change of plan.",
    exampleTranslationJa: "その遅れのために計画の変更が必要になった。",
    collocations: ["necessitate a change", "necessitate action", "may necessitate"],
    wordFormation: "necessity(必要)+ -ate。",
    mnemonic: "人が必要とするのではなく、状況が「必要な事態にする」。主語は物や出来事。",
    relatedWords: ["require", "demand", "necessary"],
  },
  {
    id: "presuppose",
    word: "presuppose",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["前提とする、あらかじめ想定する"],
    pronunciation: "/ˌpriːsəˈpoʊz/",
    exampleSentence: "The argument presupposes that everyone has internet access.",
    exampleTranslationJa: "その議論は全員がネットを使えることを前提にしている。",
    collocations: ["presuppose that", "presuppose knowledge of"],
    wordFormation: "pre-(前もって)+ suppose(想定する)。",
    mnemonic: "議論を始める前に、すでに正しいものとして置いていること。",
    relatedWords: ["assume", "premise", "imply"],
  },
  {
    id: "ascribe",
    word: "ascribe",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(原因・作者を)〜のせいだとする、〜に帰する"],
    pronunciation: "/əˈskraɪb/",
    exampleSentence: "She ascribed her success to hard work.",
    exampleTranslationJa: "彼女は自分の成功を努力のおかげだとした。",
    collocations: ["ascribe A to B", "ascribe the failure to", "commonly ascribed to"],
    wordFormation: "a-(〜へ)+ scribe(書く)。「〜のものとして書きつける」。",
    mnemonic: "attribute とほぼ同じ。scribe(書く)が語根で、describe と親戚。",
    relatedWords: ["attribute", "credit", "assign"],
  },
  {
    id: "apportion",
    word: "apportion",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(公平に)割り当てる、配分する"],
    pronunciation: "/əˈpɔːrʃn/",
    exampleSentence: "The costs were apportioned between the three departments.",
    exampleTranslationJa: "費用は三つの部署に配分された。",
    collocations: ["apportion blame", "apportion the cost", "apportion resources"],
    wordFormation: "ap-(〜へ)+ portion(分け前)。",
    mnemonic: "portion(分け前)を割り当てる。apportion blame は「責任を分けて負わせる」。",
    relatedWords: ["allocate", "distribute", "divide"],
  },
  {
    id: "mitigate",
    word: "mitigate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(悪影響を)和らげる、軽減する"],
    pronunciation: "/ˈmɪtɪɡeɪt/",
    exampleSentence: "Planting trees can mitigate the effects of heat.",
    exampleTranslationJa: "木を植えることは暑さの影響を和らげうる。",
    collocations: ["mitigate the risk", "mitigate the effects", "mitigating circumstances"],
    mnemonic: "気候や災害の記事で頻出。mitigating circumstances は「情状酌量すべき事情」。",
    relatedWords: ["reduce", "alleviate", "ease"],
  },
  {
    id: "alleviate",
    word: "alleviate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(苦痛・問題を)やわらげる"],
    pronunciation: "/əˈliːvieɪt/",
    exampleSentence: "The medicine alleviated the pain within minutes.",
    exampleTranslationJa: "その薬は数分で痛みをやわらげた。",
    collocations: ["alleviate pain", "alleviate poverty", "alleviate suffering"],
    wordFormation: "al-(〜へ)+ levis(軽い)。「軽くする」。",
    mnemonic: "levis(軽い)が語根。elevator(持ち上げるもの)と同語根。",
    relatedWords: ["relieve", "ease", "mitigate"],
  },
  {
    id: "exacerbate",
    word: "exacerbate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(状況を)悪化させる"],
    pronunciation: "/ɪɡˈzæsərbeɪt/",
    exampleSentence: "Cutting staff will only exacerbate the problem.",
    exampleTranslationJa: "人員を減らせば問題は悪化するばかりだ。",
    collocations: ["exacerbate the problem", "exacerbate tensions", "only exacerbate"],
    mnemonic: "alleviate の正反対。「もともと悪いものをさらに悪くする」。",
    relatedWords: ["worsen", "aggravate", "alleviate"],
  },
  {
    id: "aggravate",
    word: "aggravate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["悪化させる", "(口語)いらだたせる"],
    pronunciation: "/ˈæɡrəveɪt/",
    exampleSentence: "Running on it will aggravate the injury.",
    exampleTranslationJa: "その状態で走ればけがが悪化する。",
    collocations: ["aggravate an injury", "aggravate the situation", "aggravating factors"],
    wordFormation: "ラテン語 gravis(重い)から。「より重くする」。",
    mnemonic: "gravity(重力)と同語根。「重くする」が原義。",
    relatedWords: ["worsen", "exacerbate", "irritate"],
  },
  {
    id: "curtail",
    word: "curtail",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(期間や権利を)切り詰める、制限する"],
    pronunciation: "/kɜːrˈteɪl/",
    exampleSentence: "The trip was curtailed because of the storm.",
    exampleTranslationJa: "嵐のため旅行は切り上げられた。",
    collocations: ["curtail spending", "curtail freedoms", "severely curtail"],
    mnemonic: "curt(そっけない)と同語根。予定や自由を「短く切る」。",
    relatedWords: ["reduce", "restrict", "shorten"],
  },
  {
    id: "truncate",
    word: "truncate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(端を切って)短くする、切り詰める"],
    pronunciation: "/ˈtrʌŋkeɪt/",
    exampleSentence: "The text was truncated at fifty characters.",
    exampleTranslationJa: "その文章は50字で切り詰められた。",
    collocations: ["a truncated version", "truncate the text", "truncate the data"],
    wordFormation: "ラテン語 truncus(幹・切り株)から。trunk と同語根。",
    mnemonic: "trunk(幹)と同語根。先を切り落として切り株のようにすること。",
    relatedWords: ["shorten", "cut", "abbreviate"],
  },
  {
    id: "abridge",
    word: "abridge",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(本などを)短縮する、要約する"],
    pronunciation: "/əˈbrɪdʒ/",
    exampleSentence: "This is an abridged edition of the novel.",
    exampleTranslationJa: "これはその小説の短縮版だ。",
    collocations: ["an abridged version", "abridge a text", "abridged edition"],
    mnemonic: "bridge(橋)とは無関係で、brief(短い)と同語根。本の「抄録版」に使う。",
    relatedWords: ["shorten", "condense", "summarise"],
  },
  {
    id: "condense",
    word: "condense",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(内容を)凝縮する", "(気体が)液体になる"],
    pronunciation: "/kənˈdens/",
    exampleSentence: "He condensed the report into two pages.",
    exampleTranslationJa: "彼は報告書を2ページに凝縮した。",
    collocations: ["condense into", "condensed milk", "water condenses"],
    wordFormation: "con-(共に)+ dense(濃い)。「濃くする」。",
    mnemonic: "dense(濃い)が中にある。内容も水蒸気も「濃く縮める」。",
    relatedWords: ["compress", "summarise", "dense"],
  },
  {
    id: "streamline",
    word: "streamline",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(手続きを)効率化する、無駄をなくす"],
    pronunciation: "/ˈstriːmlaɪn/",
    exampleSentence: "The company streamlined its approval process.",
    exampleTranslationJa: "その会社は承認手続きを効率化した。",
    collocations: ["streamline the process", "streamline operations", "a streamlined design"],
    wordFormation: "stream(流れ)+ line(線)。水の流れに沿った形から。",
    mnemonic: "もとは「流線形にする」。抵抗を減らす形にする→手続きの無駄をなくす。",
    relatedWords: ["simplify", "efficient", "optimise"],
  },
  {
    id: "augment",
    word: "augment",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["増やす、補強する"],
    pronunciation: "/ɔːɡˈment/",
    exampleSentence: "He augmented his income by teaching in the evenings.",
    exampleTranslationJa: "彼は夜に教えることで収入を増やした。",
    collocations: ["augment income", "augment the workforce", "augmented reality"],
    wordFormation: "ラテン語 augere(増やす)から。author・auction と同語根。",
    mnemonic: "augmented reality(拡張現実)の augment。足して大きくすること。",
    relatedWords: ["increase", "supplement", "boost"],
  },
  {
    id: "amplify",
    word: "amplify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(音や効果を)増幅する", "詳しく述べる"],
    pronunciation: "/ˈæmplɪfaɪ/",
    exampleSentence: "Social media amplifies rumours very quickly.",
    exampleTranslationJa: "SNSはうわさを非常に速く増幅する。",
    collocations: ["amplify the sound", "amplify the effect", "amplify a message"],
    wordFormation: "ample(十分な)+ -fy(〜にする)。",
    mnemonic: "ample(たっぷりの)にすること。音響機器のアンプ(amplifier)と同じ語。",
    relatedWords: ["increase", "magnify", "intensify"],
  },
  {
    id: "proliferate",
    word: "proliferate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["急増する、拡散する"],
    pronunciation: "/prəˈlɪfəreɪt/",
    exampleSentence: "Delivery apps have proliferated since the pandemic.",
    exampleTranslationJa: "配達アプリは感染症流行以来、急増した。",
    collocations: ["rapidly proliferate", "proliferate across", "weapons proliferate"],
    mnemonic: "細胞が増殖するイメージ。名詞 proliferation は核兵器の「拡散」でよく使う。",
    relatedWords: ["multiply", "spread", "increase"],
  },
  {
    id: "dwindle",
    word: "dwindle",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["だんだん減る、先細りになる"],
    pronunciation: "/ˈdwɪndl/",
    exampleSentence: "Their savings dwindled over the winter.",
    exampleTranslationJa: "彼らの貯金は冬の間にじりじり減った。",
    collocations: ["dwindle away", "dwindling numbers", "dwindle to nothing"],
    mnemonic: "急減ではなく「じわじわ減って小さくなる」。dwindling population が定番。",
    relatedWords: ["decline", "shrink", "diminish"],
  },
  {
    id: "degenerate",
    word: "degenerate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(質が)悪化する、堕落する"],
    pronunciation: "/dɪˈdʒenəreɪt/",
    exampleSentence: "The debate degenerated into a shouting match.",
    exampleTranslationJa: "その討論は怒鳴り合いに成り下がった。",
    collocations: ["degenerate into", "degenerate rapidly", "a degenerative disease"],
    wordFormation: "de-(下へ)+ genus(生まれ・種)。「もとの質から落ちる」。",
    mnemonic: "degenerate into ... で「〜に成り下がる」。この形で覚える。",
    relatedWords: ["deteriorate", "decline", "worsen"],
  },
  {
    id: "stagnate",
    word: "stagnate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["停滞する、伸び悩む"],
    pronunciation: "/ˈstæɡneɪt/",
    exampleSentence: "Wages have stagnated for a decade.",
    exampleTranslationJa: "賃金は10年間、伸び悩んでいる。",
    collocations: ["wages stagnate", "a stagnating economy", "stagnate for years"],
    mnemonic: "よどんだ水(stagnant water)から。動かず腐っていくイメージ。",
    relatedWords: ["stagnant", "stall", "decline"],
  },
  {
    id: "fluctuate",
    word: "fluctuate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["変動する、上下する"],
    pronunciation: "/ˈflʌktʃueɪt/",
    exampleSentence: "Prices fluctuate with the season.",
    exampleTranslationJa: "価格は季節によって変動する。",
    collocations: ["fluctuate wildly", "prices fluctuate", "fluctuate between"],
    wordFormation: "ラテン語 fluctus(波)から。fluid・flow と同語根。",
    mnemonic: "波(fluctus)のように上下する。名詞は fluctuation。",
    relatedWords: ["vary", "oscillate", "swing"],
  },
  {
    id: "conform",
    word: "conform",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(規則に)従う、適合する", "(周囲に)合わせる"],
    pronunciation: "/kənˈfɔːrm/",
    exampleSentence: "All products must conform to safety standards.",
    exampleTranslationJa: "すべての製品は安全基準に適合しなければならない。",
    collocations: ["conform to standards", "conform with the rules", "refuse to conform"],
    wordFormation: "con-(共に)+ form(形)。「同じ形になる」。",
    mnemonic: "con(共に)+ form(形)。基準と同じ形になること。名詞は conformity。",
    relatedWords: ["comply", "adapt", "obey"],
  },
  {
    id: "deviate",
    word: "deviate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(標準・進路から)外れる"],
    pronunciation: "/ˈdiːvieɪt/",
    exampleSentence: "Do not deviate from the agreed plan.",
    exampleTranslationJa: "合意した計画から外れないでください。",
    collocations: ["deviate from", "deviate slightly", "standard deviation"],
    wordFormation: "de-(離れて)+ via(道)。「道から離れる」。",
    mnemonic: "via(道)が語根。統計の「標準偏差」は standard deviation。",
    relatedWords: ["diverge", "stray", "differ"],
  },
  {
    id: "diverge",
    word: "diverge",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["分かれる、食い違う"],
    pronunciation: "/daɪˈvɜːrdʒ/",
    exampleSentence: "The two paths diverge just after the bridge.",
    exampleTranslationJa: "その二つの道は橋のすぐ先で分かれる。",
    collocations: ["diverge from", "opinions diverge", "diverging paths"],
    wordFormation: "di-(離れて)+ vergere(傾く)。",
    mnemonic: "converge(集まる)の反対。一つだったものが二つに分かれる。",
    relatedWords: ["converge", "separate", "differ"],
  },
  {
    id: "converge",
    word: "converge",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["一点に集まる、収束する"],
    pronunciation: "/kənˈvɜːrdʒ/",
    exampleSentence: "Three roads converge at the town square.",
    exampleTranslationJa: "三本の道が町の広場で合流する。",
    collocations: ["converge on", "converge at", "opinions converge"],
    wordFormation: "con-(共に)+ vergere(傾く)。",
    mnemonic: "con(共に)傾く＝集まる。diverge(分かれる)と対で覚える。",
    relatedWords: ["diverge", "merge", "meet"],
  },
  {
    id: "supersede",
    word: "supersede",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["取って代わる、廃止して置き換える"],
    pronunciation: "/ˌsuːpərˈsiːd/",
    exampleSentence: "This guidance supersedes all earlier versions.",
    exampleTranslationJa: "この指針は以前の版すべてに取って代わる。",
    collocations: ["supersede the old rules", "be superseded by", "supersedes all previous"],
    wordFormation: "super-(上に)+ sedere(座る)。「上に座る」。",
    mnemonic: "つづりは -sede(-cede ではない)。文書の版が古いものを無効にすること。",
    relatedWords: ["replace", "supplant", "override"],
  },
  {
    id: "supplant",
    word: "supplant",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(押しのけて)取って代わる"],
    pronunciation: "/səˈplænt/",
    exampleSentence: "Streaming has supplanted the DVD.",
    exampleTranslationJa: "ストリーミングがDVDに取って代わった。",
    collocations: ["supplant the old system", "gradually supplant", "be supplanted by"],
    mnemonic: "supersede が制度や文書、supplant は競争で押しのける感じ。",
    relatedWords: ["replace", "supersede", "displace"],
  },
  {
    id: "relegate",
    word: "relegate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["格下げする、追いやる"],
    pronunciation: "/ˈreləɡeɪt/",
    exampleSentence: "The team was relegated to the second division.",
    exampleTranslationJa: "そのチームは2部に降格した。",
    collocations: ["be relegated to", "relegate to the past", "face relegation"],
    wordFormation: "re-(後ろへ)+ legare(送る)。「後ろへ送る」。",
    mnemonic: "サッカーの「降格」がこれ。物なら「隅へ追いやる」。名詞は relegation。",
    relatedWords: ["demote", "downgrade", "promote"],
  },
  {
    id: "vindicate",
    word: "vindicate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(疑いを晴らして)正しさを証明する"],
    pronunciation: "/ˈvɪndɪkeɪt/",
    exampleSentence: "The results vindicated her decision.",
    exampleTranslationJa: "その結果は彼女の判断が正しかったことを示した。",
    collocations: ["vindicate a decision", "feel vindicated", "fully vindicated"],
    mnemonic: "「批判されていたが、あとで正しかったと分かる」場面の語。",
    relatedWords: ["justify", "exonerate", "prove"],
  },
  {
    id: "exonerate",
    word: "exonerate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(容疑を)晴らす、無罪とする"],
    pronunciation: "/ɪɡˈzɑːnəreɪt/",
    exampleSentence: "New evidence exonerated the two men.",
    exampleTranslationJa: "新しい証拠がその2人の容疑を晴らした。",
    collocations: ["exonerate someone", "be fully exonerated", "exonerate from blame"],
    wordFormation: "ex-(外へ)+ onus(重荷)。「重荷を下ろす」。",
    mnemonic: "onus(重荷・責任)が語根。責めの重荷を下ろしてやること。",
    relatedWords: ["acquit", "clear", "vindicate"],
  },
  {
    id: "absolve",
    word: "absolve",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(責任・罪を)免じる、許す"],
    pronunciation: "/əbˈzɑːlv/",
    exampleSentence: "The report absolved the company of blame.",
    exampleTranslationJa: "その報告書はその会社の責任を認めなかった。",
    collocations: ["absolve of blame", "absolve from responsibility", "absolve someone"],
    wordFormation: "ab-(離して)+ solvere(解く)。solve と同語根。",
    mnemonic: "solve(解く)が語根。責任の縛りを解いてやること。",
    relatedWords: ["exonerate", "forgive", "clear"],
  },
  {
    id: "impede",
    word: "impede",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["妨げる、進行を遅らせる"],
    pronunciation: "/ɪmˈpiːd/",
    exampleSentence: "Heavy snow impeded the rescue effort.",
    exampleTranslationJa: "大雪が救助活動を妨げた。",
    collocations: ["impede progress", "impede growth", "seriously impede"],
    wordFormation: "im-(中に)+ pes(足)。「足かせをはめる」。",
    mnemonic: "ped(足)が語根。pedal・pedestrian と親戚。足を取られて進めない。",
    relatedWords: ["hinder", "obstruct", "hamper"],
  },
  {
    id: "hinder",
    word: "hinder",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["じゃまをする、遅らせる"],
    pronunciation: "/ˈhɪndər/",
    exampleSentence: "Lack of funding hindered the research.",
    exampleTranslationJa: "資金不足がその研究を遅らせた。",
    collocations: ["hinder progress", "help or hinder", "seriously hinder"],
    mnemonic: "behind(後ろ)と同語源。後ろに引っぱって進ませないこと。",
    relatedWords: ["impede", "hamper", "obstruct"],
  },
  {
    id: "hamper",
    word: "hamper",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["妨げる、動きにくくする", "ふた付きのかご"],
    pronunciation: "/ˈhæmpər/",
    exampleSentence: "Thick fog hampered the search.",
    exampleTranslationJa: "濃い霧が捜索を妨げた。",
    collocations: ["hampered by", "severely hamper", "a picnic hamper"],
    mnemonic: "手足がからまって動きにくい感じ。hampered by ... の受け身が多い。",
    relatedWords: ["hinder", "impede", "restrict"],
  },
  {
    id: "thwart",
    word: "thwart",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(計画を)阻止する、くじく"],
    pronunciation: "/θwɔːrt/",
    exampleSentence: "Police thwarted an attempt to steal the painting.",
    exampleTranslationJa: "警察はその絵を盗もうとする企てを阻止した。",
    collocations: ["thwart a plan", "thwart an attempt", "be thwarted by"],
    mnemonic: "遅らせるのではなく「完全に失敗させる」。計画や企てが目的語。",
    relatedWords: ["foil", "prevent", "block"],
  },
  {
    id: "obstruct",
    word: "obstruct",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["ふさぐ、通行を妨げる", "(手続きを)妨害する"],
    pronunciation: "/əbˈstrʌkt/",
    exampleSentence: "A fallen tree obstructed the road.",
    exampleTranslationJa: "倒木が道路をふさいだ。",
    collocations: ["obstruct the view", "obstruct justice", "obstruct traffic"],
    wordFormation: "ob-(前に)+ struere(積む)。「前に積み上げる」。",
    mnemonic: "structure と同語根。前に物を積んで通れなくすること。",
    relatedWords: ["block", "impede", "hinder"],
  },
  {
    id: "forestall",
    word: "forestall",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["先手を打って防ぐ"],
    pronunciation: "/fɔːrˈstɔːl/",
    exampleSentence: "The bank cut rates to forestall a crisis.",
    exampleTranslationJa: "銀行は危機を未然に防ぐため金利を下げた。",
    collocations: ["forestall a crisis", "forestall criticism", "forestall any objection"],
    wordFormation: "fore-(前もって)+ stall(止める)。",
    mnemonic: "fore(前もって)+ stall(止める)。起きる前に手を打つ。",
    relatedWords: ["prevent", "preempt", "avert"],
  },
  {
    id: "instigate",
    word: "instigate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(争いなどを)引き起こす、扇動する", "(手続きを)始める"],
    pronunciation: "/ˈɪnstɪɡeɪt/",
    exampleSentence: "He was accused of instigating the riot.",
    exampleTranslationJa: "彼は暴動を扇動したとして告発された。",
    collocations: ["instigate a riot", "instigate proceedings", "instigate change"],
    mnemonic: "悪いことを仕向ける意味が強い。名詞は instigation、人は instigator。",
    relatedWords: ["provoke", "incite", "initiate"],
  },
  {
    id: "incite",
    word: "incite",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["あおる、扇動する"],
    pronunciation: "/ɪnˈsaɪt/",
    exampleSentence: "He was charged with inciting violence.",
    exampleTranslationJa: "彼は暴力を扇動したとして起訴された。",
    collocations: ["incite violence", "incite hatred", "incite a crowd"],
    wordFormation: "in-(中へ)+ citare(呼び起こす)。excite と同語根。",
    mnemonic: "excite(わくわくさせる)と同語根。悪い方向に火をつけるのが incite。",
    relatedWords: ["provoke", "instigate", "stir"],
  },
  {
    id: "spur",
    word: "spur",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["拍車をかける、駆り立てる", "拍車、刺激"],
    pronunciation: "/spɜːr/",
    exampleSentence: "Low prices spurred a rise in demand.",
    exampleTranslationJa: "安い価格が需要の伸びに拍車をかけた。",
    collocations: ["spur growth", "spur someone on", "on the spur of the moment"],
    mnemonic: "馬に当てる拍車が原義。on the spur of the moment は「とっさに」。",
    relatedWords: ["stimulate", "encourage", "prompt"],
  },
  {
    id: "galvanise",
    word: "galvanise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(人々を)奮い立たせて動かす"],
    pronunciation: "/ˈɡælvənaɪz/",
    exampleSentence: "The speech galvanised the whole movement.",
    exampleTranslationJa: "その演説は運動全体を奮い立たせた。",
    collocations: ["galvanise support", "galvanise into action", "galvanise public opinion"],
    mnemonic: "「電気を流したように動き出させる」。米つづりは galvanize。",
    relatedWords: ["motivate", "energise", "spur"],
  },
  {
    id: "withhold",
    word: "withhold",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["与えずにおく、差し控える"],
    pronunciation: "/wɪðˈhoʊld/",
    exampleSentence: "The company withheld the report for two months.",
    exampleTranslationJa: "その会社は報告書を2か月公表しなかった。",
    collocations: ["withhold information", "withhold payment", "withhold consent"],
    wordFormation: "with-(後ろへ)+ hold(持つ)。「手元に引きとめる」。",
    mnemonic: "活用は withhold-withheld-withheld。「渡さずに持っている」。",
    relatedWords: ["hold back", "retain", "conceal"],
  },
  {
    id: "relinquish",
    word: "relinquish",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(権利・地位を)手放す、放棄する"],
    pronunciation: "/rɪˈlɪŋkwɪʃ/",
    exampleSentence: "She relinquished her claim to the property.",
    exampleTranslationJa: "彼女はその不動産への権利を放棄した。",
    collocations: ["relinquish control", "relinquish a title", "reluctantly relinquish"],
    mnemonic: "give up のかたい語。権利・地位・支配を手放すときに使う。",
    relatedWords: ["surrender", "abandon", "yield"],
  },
  {
    id: "forfeit",
    word: "forfeit",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(罰として)失う、没収される", "没収物"],
    pronunciation: "/ˈfɔːrfət/",
    exampleSentence: "If you cancel late, you forfeit the deposit.",
    exampleTranslationJa: "直前に取り消すと手付金は返ってきません。",
    collocations: ["forfeit the deposit", "forfeit your right", "forfeit the match"],
    mnemonic: "自分の落ち度で失う点が relinquish と違う。t は発音する /ˈfɔːrfət/。",
    relatedWords: ["lose", "surrender", "penalty"],
  },
  {
    id: "divulge",
    word: "divulge",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(秘密を)明かす、漏らす"],
    pronunciation: "/daɪˈvʌldʒ/",
    exampleSentence: "He refused to divulge his sources.",
    exampleTranslationJa: "彼は情報源を明かすことを拒んだ。",
    collocations: ["divulge information", "refuse to divulge", "divulge details"],
    wordFormation: "di-(外へ)+ vulgus(大衆)。「大衆に広める」。",
    mnemonic: "vulgar(俗な)と同語根。秘密を「みんなの目に出す」。",
    relatedWords: ["disclose", "reveal", "leak"],
  },
  {
    id: "censor",
    word: "censor",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["検閲して削る", "検閲官"],
    pronunciation: "/ˈsensər/",
    exampleSentence: "The letters were censored before they were sent.",
    exampleTranslationJa: "その手紙は送られる前に検閲された。",
    collocations: ["censor the news", "heavily censored", "a government censor"],
    mnemonic: "sensor(感知器)と同音だが別語。名詞 censorship は「検閲」。",
    relatedWords: ["censorship", "ban", "suppress"],
  },
  {
    id: "ratify",
    word: "ratify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(条約などを)正式に承認する、批准する"],
    pronunciation: "/ˈrætɪfaɪ/",
    exampleSentence: "Parliament has yet to ratify the treaty.",
    exampleTranslationJa: "議会はまだその条約を批准していない。",
    collocations: ["ratify a treaty", "ratify an agreement", "formally ratify"],
    mnemonic: "署名した条約を、議会が正式に認めること。条約の記事の定番動詞。",
    relatedWords: ["approve", "endorse", "treaty"],
  },
  {
    id: "authorise",
    word: "authorise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["許可する、権限を与える"],
    pronunciation: "/ˈɔːθəraɪz/",
    exampleSentence: "Only the manager can authorise a refund.",
    exampleTranslationJa: "返金を承認できるのは店長だけだ。",
    collocations: ["authorise payment", "authorised personnel", "authorise access"],
    wordFormation: "author(権威)+ -ise。",
    mnemonic: "米つづりは authorize。Authorised personnel only. は「関係者以外立入禁止」。",
    relatedWords: ["permit", "approve", "authority"],
  },
  {
    id: "accredit",
    word: "accredit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(機関を)公認する、認定する"],
    pronunciation: "/əˈkredɪt/",
    exampleSentence: "The course is accredited by the medical board.",
    exampleTranslationJa: "その課程は医療委員会に認定されている。",
    collocations: ["an accredited course", "accredited by", "accredited journalists"],
    wordFormation: "ac-(〜へ)+ credit(信用)。",
    mnemonic: "credit(信用)を与えること。学校や資格の「認定」で使う。",
    relatedWords: ["certify", "approve", "recognise"],
  },
  {
    id: "certify",
    word: "certify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(書面で)証明する、認定する"],
    pronunciation: "/ˈsɜːrtɪfaɪ/",
    exampleSentence: "A doctor must certify the cause of death.",
    exampleTranslationJa: "医師が死因を証明しなければならない。",
    collocations: ["certify that", "a certified copy", "certified organic"],
    wordFormation: "certain(確かな)+ -fy。",
    mnemonic: "certain(確か)にすること。certified organic のように表示にも使う。",
    relatedWords: ["certificate", "accredit", "verify"],
  },
  {
    id: "plaintiff",
    word: "plaintiff",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["原告(民事訴訟で訴えた側)"],
    pronunciation: "/ˈpleɪntɪf/",
    exampleSentence: "The plaintiff is seeking damages of £50,000.",
    exampleTranslationJa: "原告は5万ポンドの損害賠償を求めている。",
    collocations: ["the plaintiff claims", "act for the plaintiff", "the plaintiff's case"],
    mnemonic: "complaint(苦情)と同語根。訴えた側が plaintiff、訴えられた側が defendant。",
    relatedWords: ["defendant", "lawsuit", "court"],
  },
  {
    id: "defendant",
    word: "defendant",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["被告"],
    pronunciation: "/dɪˈfendənt/",
    exampleSentence: "The defendant pleaded not guilty.",
    exampleTranslationJa: "被告は無罪を主張した。",
    collocations: ["the defendant pleaded", "represent the defendant", "the defendant's lawyer"],
    wordFormation: "defend(守る)+ -ant(人)。「身を守る側の人」。",
    mnemonic: "defend(守る)側。訴えられて自分を守る立場の人。",
    relatedWords: ["plaintiff", "accused", "trial"],
  },
  {
    id: "barrister",
    word: "barrister",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["法廷弁護士(英)"],
    pronunciation: "/ˈbærɪstər/",
    exampleSentence: "A barrister will argue the case in court.",
    exampleTranslationJa: "法廷弁護士が法廷で弁論する。",
    collocations: ["a defence barrister", "instruct a barrister", "a leading barrister"],
    mnemonic: "英国では、法廷に立つのが barrister、書類や相談が solicitor。米では lawyer 一語。",
    relatedWords: ["solicitor", "lawyer", "court"],
  },
  {
    id: "parole",
    word: "parole",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["仮釈放"],
    pronunciation: "/pəˈroʊl/",
    exampleSentence: "He was released on parole after four years.",
    exampleTranslationJa: "彼は4年後に仮釈放された。",
    collocations: ["release on parole", "a parole board", "be denied parole"],
    mnemonic: "「約束の言葉」が語源。守ると誓って早く出ること。",
    relatedWords: ["probation", "prison", "release"],
  },
  {
    id: "acquittal",
    word: "acquittal",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["無罪判決"],
    pronunciation: "/əˈkwɪtl/",
    exampleSentence: "The jury returned an acquittal on all charges.",
    exampleTranslationJa: "陪審はすべての訴因について無罪の評決を出した。",
    collocations: ["a full acquittal", "secure an acquittal", "acquittal on all charges"],
    wordFormation: "acquit(無罪とする)+ -al。",
    mnemonic: "動詞は acquit。有罪判決 conviction の反対。",
    relatedWords: ["acquit", "conviction", "verdict"],
  },
  {
    id: "litigation",
    word: "litigation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["訴訟、訴訟手続き"],
    pronunciation: "/ˌlɪtɪˈɡeɪʃn/",
    exampleSentence: "The dispute ended in years of litigation.",
    exampleTranslationJa: "その争いは何年もの訴訟に終わった。",
    collocations: ["costly litigation", "avoid litigation", "be in litigation"],
    mnemonic: "lawsuit が一件の訴訟、litigation は「訴訟という手段・過程」全体。",
    relatedWords: ["lawsuit", "court", "legal"],
  },
  {
    id: "injunction",
    word: "injunction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["差止命令"],
    pronunciation: "/ɪnˈdʒʌŋkʃn/",
    exampleSentence: "The court granted an injunction to stop the sale.",
    exampleTranslationJa: "裁判所は売却を止める差止命令を出した。",
    collocations: ["grant an injunction", "seek an injunction", "a temporary injunction"],
    wordFormation: "in-(〜に)+ jungere(結びつける)。join と同語根。",
    mnemonic: "「するな」と裁判所が縛る命令。報道差止めのニュースで出る語。",
    relatedWords: ["court", "order", "ban"],
  },
  {
    id: "subpoena",
    word: "subpoena",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["召喚状", "召喚する"],
    pronunciation: "/səˈpiːnə/",
    exampleSentence: "He was served with a subpoena to appear in court.",
    exampleTranslationJa: "彼は法廷に出るよう召喚状を渡された。",
    collocations: ["issue a subpoena", "serve a subpoena", "subpoena a witness"],
    mnemonic: "b は読まない /səˈpiːnə/。ラテン語の「罰のもとに」がそのまま名前に。",
    relatedWords: ["summons", "witness", "court"],
  },
  {
    id: "statute",
    word: "statute",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["制定法、法令"],
    pronunciation: "/ˈstætʃuːt/",
    exampleSentence: "The right is protected by statute.",
    exampleTranslationJa: "その権利は制定法で守られている。",
    collocations: ["by statute", "a statute of limitations", "under the statute"],
    mnemonic: "statue(像)と一字違い。議会が定めた成文の法。",
    relatedWords: ["law", "legislation", "act"],
  },
  {
    id: "decree",
    word: "decree",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["政令、命令", "布告する"],
    pronunciation: "/dɪˈkriː/",
    exampleSentence: "The president issued a decree banning the practice.",
    exampleTranslationJa: "大統領はその慣行を禁じる政令を出した。",
    collocations: ["issue a decree", "by decree", "a royal decree"],
    mnemonic: "議会を通さず、上から一方的に出される命令。rule by decree は「勅令政治」。",
    relatedWords: ["order", "edict", "law"],
  },
  {
    id: "manifesto",
    word: "manifesto",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(政党の)公約集、宣言"],
    pronunciation: "/ˌmænɪˈfestoʊ/",
    exampleSentence: "The pledge was in their election manifesto.",
    exampleTranslationJa: "その公約は彼らの選挙公約集に載っていた。",
    collocations: ["an election manifesto", "a manifesto pledge", "publish a manifesto"],
    mnemonic: "manifest(はっきり示す)から。複数形は manifestos。",
    relatedWords: ["pledge", "policy", "election"],
  },
  {
    id: "diplomacy",
    word: "diplomacy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["外交", "駆け引きのうまさ"],
    pronunciation: "/dɪˈploʊməsi/",
    exampleSentence: "The crisis was solved through quiet diplomacy.",
    exampleTranslationJa: "その危機は静かな外交によって解決された。",
    collocations: ["quiet diplomacy", "a triumph of diplomacy", "handle with diplomacy"],
    mnemonic: "diploma(二つ折りの公文書)と同語源。国どうしの交渉術にも、個人の気配りにも使う。",
    relatedWords: ["diplomat", "negotiation", "tact"],
  },
  {
    id: "embargo",
    word: "embargo",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["通商禁止、禁輸措置"],
    pronunciation: "/ɪmˈbɑːrɡoʊ/",
    exampleSentence: "The country faces an arms embargo.",
    exampleTranslationJa: "その国は武器の禁輸措置を受けている。",
    collocations: ["impose an embargo", "lift an embargo", "an oil embargo"],
    mnemonic: "特定の品や国との取引を止める措置。複数形は embargoes。",
    relatedWords: ["sanction", "ban", "trade"],
  },
  {
    id: "ceasefire",
    word: "ceasefire",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["停戦"],
    pronunciation: "/ˈsiːsfaɪər/",
    exampleSentence: "Both sides agreed to a temporary ceasefire.",
    exampleTranslationJa: "双方が一時的な停戦に合意した。",
    collocations: ["a ceasefire agreement", "declare a ceasefire", "violate the ceasefire"],
    wordFormation: "cease(やめる)+ fire(発砲)。",
    mnemonic: "cease(やめる)+ fire(撃つこと)。撃ち方やめ、がそのまま名詞に。",
    relatedWords: ["truce", "peace", "conflict"],
  },
  {
    id: "armistice",
    word: "armistice",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["休戦(協定)"],
    pronunciation: "/ˈɑːrmɪstɪs/",
    exampleSentence: "The armistice was signed in November 1918.",
    exampleTranslationJa: "その休戦協定は1918年11月に調印された。",
    collocations: ["sign an armistice", "an armistice agreement", "Armistice Day"],
    wordFormation: "arma(武器)+ -stice(止める)。",
    mnemonic: "ceasefire より正式で、協定として結ばれるもの。第一次大戦の Armistice Day で覚える。",
    relatedWords: ["ceasefire", "truce", "treaty"],
  },
  {
    id: "census",
    word: "census",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["国勢調査"],
    pronunciation: "/ˈsensəs/",
    exampleSentence: "The census is carried out every ten years.",
    exampleTranslationJa: "国勢調査は10年ごとに行われる。",
    collocations: ["a national census", "census data", "carry out a census"],
    mnemonic: "sense(感覚)とは無関係。人口を数え上げる公式調査。",
    relatedWords: ["population", "survey", "statistics"],
  },
  {
    id: "demographic",
    word: "demographic",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["人口動態の", "(特定の)客層、年齢層"],
    pronunciation: "/ˌdeməˈɡræfɪk/",
    exampleSentence: "The magazine targets a young demographic.",
    exampleTranslationJa: "その雑誌は若い層を狙っている。",
    collocations: ["demographic change", "a target demographic", "demographic data"],
    wordFormation: "demos(民衆)+ graph(書く)。democracy と同語根。",
    mnemonic: "demos(民衆)が語根。democracy と親戚。名詞では「客層」。",
    relatedWords: ["population", "census", "statistics"],
  },
  {
    id: "deportation",
    word: "deportation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["国外退去、強制送還"],
    pronunciation: "/ˌdiːpɔːrˈteɪʃn/",
    exampleSentence: "He is appealing against deportation.",
    exampleTranslationJa: "彼は国外退去に対して不服を申し立てている。",
    collocations: ["face deportation", "a deportation order", "appeal against deportation"],
    wordFormation: "de-(離れて)+ portare(運ぶ)。「運び出すこと」。",
    mnemonic: "portare(運ぶ)が語根。transport・porter と親戚。動詞は deport。",
    relatedWords: ["deport", "immigration", "asylum"],
  },
  {
    id: "bribery",
    word: "bribery",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["贈収賄、賄賂を贈ること"],
    pronunciation: "/ˈbraɪbəri/",
    exampleSentence: "Two officials were arrested for bribery.",
    exampleTranslationJa: "職員2人が贈収賄で逮捕された。",
    collocations: ["accused of bribery", "bribery and corruption", "a bribery scandal"],
    wordFormation: "bribe(賄賂)+ -ry。",
    mnemonic: "bribe(賄賂)が名詞にも動詞にもなる。行為全体が bribery。",
    relatedWords: ["bribe", "corruption", "scandal"],
  },
  {
    id: "remand",
    word: "remand",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(裁判まで)勾留する", "勾留"],
    pronunciation: "/rɪˈmænd/",
    exampleSentence: "He was remanded in custody until the trial.",
    exampleTranslationJa: "彼は公判まで勾留された。",
    collocations: ["remand in custody", "on remand", "remand on bail"],
    mnemonic: "判決前に身柄を留め置くこと。on remand は「未決勾留中」。",
    relatedWords: ["custody", "bail", "trial"],
  },
  {
    id: "scarcity",
    word: "scarcity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不足、希少性"],
    pronunciation: "/ˈskersəti/",
    exampleSentence: "Water scarcity affects millions of people.",
    exampleTranslationJa: "水不足が何百万もの人に影響している。",
    collocations: ["water scarcity", "food scarcity", "a scarcity of resources"],
    wordFormation: "scarce(乏しい)+ -ity。",
    mnemonic: "shortage が一時的な不足、scarcity は構造的に足りないこと。",
    relatedWords: ["shortage", "scarce", "abundance"],
  },
  {
    id: "onset",
    word: "onset",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(病気・季節などの)始まり、発症"],
    pronunciation: "/ˈɑːnset/",
    exampleSentence: "The onset of winter came early this year.",
    exampleTranslationJa: "今年は冬の訪れが早かった。",
    collocations: ["the onset of winter", "the onset of symptoms", "sudden onset"],
    mnemonic: "よくないことの始まりに使うことが多い。the onset of ... の形で覚える。",
    relatedWords: ["start", "beginning", "outset"],
  },
  {
    id: "outset",
    word: "outset",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["最初、出発点"],
    pronunciation: "/ˈaʊtset/",
    exampleSentence: "We agreed the terms at the outset.",
    exampleTranslationJa: "私たちは最初に条件を取り決めた。",
    collocations: ["at the outset", "from the outset", "from the very outset"],
    mnemonic: "ほぼ at / from the outset の形でしか使わない。onset は「発症」、outset は「始めに」。",
    relatedWords: ["beginning", "start", "onset"],
  },
  {
    id: "repercussion",
    word: "repercussion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(思わぬ)影響、余波"],
    pronunciation: "/ˌriːpərˈkʌʃn/",
    exampleSentence: "The decision had repercussions across Europe.",
    exampleTranslationJa: "その決定はヨーロッパ中に余波を及ぼした。",
    collocations: ["serious repercussions", "have repercussions for", "political repercussions"],
    wordFormation: "re-(返って)+ percussion(打つこと)。「打ち返し」。",
    mnemonic: "打楽器 percussion と同語根。打った音が返ってくるような後々の影響。",
    relatedWords: ["consequence", "effect", "aftermath"],
  },
  {
    id: "ramification",
    word: "ramification",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(複雑な)波及効果、影響"],
    pronunciation: "/ˌræmɪfɪˈkeɪʃn/",
    exampleSentence: "No one considered the legal ramifications.",
    exampleTranslationJa: "法的な波及効果を誰も考えていなかった。",
    collocations: ["legal ramifications", "far-reaching ramifications", "consider the ramifications"],
    wordFormation: "ラテン語 ramus(枝)から。「枝分かれ」。",
    mnemonic: "ramus(枝)が語根。一つの決定が枝分かれして広がる影響。ふつう複数形。",
    relatedWords: ["consequence", "implication", "effect"],
  },
  {
    id: "rationale",
    word: "rationale",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["根拠、論理的な理由づけ"],
    pronunciation: "/ˌræʃəˈnæl/",
    exampleSentence: "What is the rationale behind this change?",
    exampleTranslationJa: "この変更の根拠は何ですか。",
    collocations: ["the rationale behind", "provide a rationale", "the rationale for"],
    mnemonic: "reason より「筋道立てた説明」。最後の e を落とすと rational(理性的な)。",
    relatedWords: ["reason", "justification", "logic"],
  },
  {
    id: "yardstick",
    word: "yardstick",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["判断の基準、ものさし"],
    pronunciation: "/ˈjɑːrdstɪk/",
    exampleSentence: "Profit is not the only yardstick of success.",
    exampleTranslationJa: "利益だけが成功のものさしではない。",
    collocations: ["a yardstick for", "use as a yardstick", "the only yardstick"],
    wordFormation: "yard(ヤード)+ stick(棒)。1ヤードの物差しから。",
    mnemonic: "本物の物差しから比喩へ。benchmark とほぼ同じ使い方。",
    relatedWords: ["benchmark", "standard", "measure"],
  },
  {
    id: "paradox",
    word: "paradox",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["逆説、矛盾しているようで真実なこと"],
    pronunciation: "/ˈpærədɑːks/",
    exampleSentence: "It is a paradox that the busiest people find time to help.",
    exampleTranslationJa: "いちばん忙しい人が手伝う時間を見つけるのは逆説的だ。",
    collocations: ["an apparent paradox", "the paradox is that", "a paradox of"],
    wordFormation: "para-(反して)+ doxa(通念)。「常識に反すること」。",
    mnemonic: "doxa(通念)に para(反する)。矛盾に見えて実は正しい話。",
    relatedWords: ["contradiction", "irony", "anomaly"],
  },
  {
    id: "anomaly",
    word: "anomaly",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["異常、例外的なもの"],
    pronunciation: "/əˈnɑːməli/",
    exampleSentence: "The reading was an anomaly and was checked twice.",
    exampleTranslationJa: "その測定値は異常で、二度確認された。",
    collocations: ["a statistical anomaly", "an anomaly in the data", "explain the anomaly"],
    wordFormation: "an-(否定)+ homalos(等しい)。「そろっていないもの」。",
    mnemonic: "「ならびから外れたもの」。データの中の一点だけおかしい値。",
    relatedWords: ["irregularity", "exception", "deviation"],
  },
  {
    id: "discrepancy",
    word: "discrepancy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["食い違い、不一致"],
    pronunciation: "/dɪsˈkrepənsi/",
    exampleSentence: "There is a discrepancy between the two figures.",
    exampleTranslationJa: "その二つの数字には食い違いがある。",
    collocations: ["a discrepancy between", "explain the discrepancy", "a slight discrepancy"],
    mnemonic: "本来一致するはずの二つがずれていること。数字や証言に使う。",
    relatedWords: ["inconsistency", "difference", "gap"],
  },
  {
    id: "inconsistency",
    word: "inconsistency",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["一貫性のなさ、矛盾"],
    pronunciation: "/ˌɪnkənˈsɪstənsi/",
    exampleSentence: "There were inconsistencies in his statement.",
    exampleTranslationJa: "彼の供述には矛盾があった。",
    collocations: ["inconsistencies in", "point out an inconsistency", "logical inconsistency"],
    wordFormation: "in-(否定)+ consistency(一貫性)。",
    mnemonic: "discrepancy が二つの間のずれ、inconsistency は一つの中で筋が通らないこと。",
    relatedWords: ["discrepancy", "contradiction", "consistent"],
  },
  {
    id: "dissent",
    word: "dissent",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["異議、反対意見", "異を唱える"],
    pronunciation: "/dɪˈsent/",
    exampleSentence: "The government does not tolerate dissent.",
    exampleTranslationJa: "その政府は異論を認めない。",
    collocations: ["political dissent", "voices of dissent", "dissent from"],
    wordFormation: "dis-(離れて)+ sentire(感じる)。consent(同意)の反対。",
    mnemonic: "consent(共に感じる＝同意)の反対で dissent(離れて感じる)。",
    relatedWords: ["consent", "objection", "protest"],
  },
  {
    id: "backlash",
    word: "backlash",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["強い反発、反動"],
    pronunciation: "/ˈbæklæʃ/",
    exampleSentence: "The policy provoked a public backlash.",
    exampleTranslationJa: "その政策は世間の強い反発を招いた。",
    collocations: ["a public backlash", "provoke a backlash", "a backlash against"],
    wordFormation: "back(後ろへ)+ lash(打つ)。「打ち返し」。",
    mnemonic: "むちが back(後ろ)に lash(はねる)。押した分だけ返ってくる反発。",
    relatedWords: ["reaction", "outcry", "resistance"],
  },
  {
    id: "outcry",
    word: "outcry",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["抗議の声、激しい非難"],
    pronunciation: "/ˈaʊtkraɪ/",
    exampleSentence: "There was a public outcry over the closures.",
    exampleTranslationJa: "その閉鎖に対して世間から抗議の声が上がった。",
    collocations: ["a public outcry", "provoke an outcry", "an outcry over"],
    wordFormation: "out(外へ)+ cry(叫ぶ)。",
    mnemonic: "backlash が行動を伴う反発、outcry は「声」に重心がある。",
    relatedWords: ["protest", "backlash", "uproar"],
  },
  {
    id: "deterrent",
    word: "deterrent",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["抑止力、思いとどまらせるもの"],
    pronunciation: "/dɪˈterənt/",
    exampleSentence: "Higher fines act as a deterrent to speeding.",
    exampleTranslationJa: "罰金の引き上げは速度違反の抑止力になる。",
    collocations: ["act as a deterrent", "a nuclear deterrent", "a deterrent effect"],
    wordFormation: "deter(思いとどまらせる)+ -ent。",
    mnemonic: "incentive(やる気にさせるもの)の反対。「やらせないための仕掛け」。",
    relatedWords: ["deter", "incentive", "prevent"],
  },
  {
    id: "leverage",
    word: "leverage",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["交渉での強み、てこの力", "(資源を)活用する"],
    pronunciation: "/ˈlevərɪdʒ/",
    exampleSentence: "Small suppliers have little leverage in the talks.",
    exampleTranslationJa: "小さな供給業者は交渉でほとんど強みを持たない。",
    collocations: ["gain leverage", "financial leverage", "leverage your skills"],
    wordFormation: "lever(てこ)+ -age。",
    mnemonic: "lever(てこ)から。小さな力で大きく動かせる立場のこと。",
    relatedWords: ["lever", "influence", "advantage"],
  },
  {
    id: "inertia",
    word: "inertia",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["惰性、変わろうとしない性質", "(物理の)慣性"],
    pronunciation: "/ɪˈnɜːrʃə/",
    exampleSentence: "Institutional inertia slowed the reform.",
    exampleTranslationJa: "組織の惰性が改革を遅らせた。",
    collocations: ["institutional inertia", "overcome inertia", "the inertia of"],
    wordFormation: "in-(否定)+ ars(技・働き)。「働きがない」。",
    mnemonic: "物理の「慣性」から、組織や人の「変わりたがらなさ」へ。",
    relatedWords: ["stagnation", "resistance", "momentum"],
  },
  {
    id: "nuance",
    word: "nuance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["微妙な違い、ニュアンス"],
    pronunciation: "/ˈnuːɑːns/",
    exampleSentence: "The translation loses the nuance of the original.",
    exampleTranslationJa: "その訳は原文の微妙な含みを失っている。",
    collocations: ["subtle nuances", "lose the nuance", "a nuanced argument"],
    mnemonic: "もとは「色合いの差」。形容詞 nuanced は「細やかで一面的でない」。",
    relatedWords: ["subtlety", "shade", "connotation"],
  },
  {
    id: "connotation",
    word: "connotation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["言外の意味、含み"],
    pronunciation: "/ˌkɑːnəˈteɪʃn/",
    exampleSentence: "The word has negative connotations.",
    exampleTranslationJa: "その語には否定的な含みがある。",
    collocations: ["negative connotations", "carry connotations of", "positive connotations"],
    wordFormation: "con-(共に)+ notare(印をつける)。「一緒についてくる意味」。",
    mnemonic: "辞書に載る意味が denotation、それに付いてくる感じが connotation。",
    relatedWords: ["implication", "nuance", "meaning"],
  },
  {
    id: "hallmark",
    word: "hallmark",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["際立った特徴", "(貴金属の)品質証明の刻印"],
    pronunciation: "/ˈhɔːlmɑːrk/",
    exampleSentence: "Careful editing is the hallmark of her work.",
    exampleTranslationJa: "ていねいな推敲が彼女の仕事の際立った特徴だ。",
    collocations: ["the hallmark of", "bear all the hallmarks of", "a hallmark of quality"],
    mnemonic: "銀器の刻印が語源。bear all the hallmarks of ... で「〜の特徴をすべて備える」。",
    relatedWords: ["characteristic", "trademark", "feature"],
  },
  {
    id: "prerequisite",
    word: "prerequisite",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["前提条件、必須の要件"],
    pronunciation: "/ˌpriːˈrekwəzɪt/",
    exampleSentence: "A degree is a prerequisite for this course.",
    exampleTranslationJa: "この課程には学位が前提条件だ。",
    collocations: ["a prerequisite for", "an essential prerequisite", "meet the prerequisites"],
    wordFormation: "pre-(前に)+ requisite(必要なもの)。",
    mnemonic: "pre(前に)必要なもの。大学の履修条件でよく見る語。",
    relatedWords: ["requirement", "condition", "precondition"],
  },
  {
    id: "precondition",
    word: "precondition",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["前提条件"],
    pronunciation: "/ˌpriːkənˈdɪʃn/",
    exampleSentence: "A ceasefire is a precondition for talks.",
    exampleTranslationJa: "停戦が交渉の前提条件だ。",
    collocations: ["a precondition for", "set preconditions", "without preconditions"],
    wordFormation: "pre-(前に)+ condition(条件)。",
    mnemonic: "prerequisite が資格や能力、precondition は交渉や合意の前に満たす条件。",
    relatedWords: ["prerequisite", "condition", "requirement"],
  },
  {
    id: "caveat",
    word: "caveat",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["注意すべき点、但し書き"],
    pronunciation: "/ˈkæviæt/",
    exampleSentence: "The findings come with one important caveat.",
    exampleTranslationJa: "その結果には一つ重要な但し書きがつく。",
    collocations: ["with the caveat that", "an important caveat", "add a caveat"],
    mnemonic: "ラテン語の「用心せよ」がそのまま名詞に。論文の限界を述べるときの語。",
    relatedWords: ["warning", "condition", "proviso"],
  },
  {
    id: "setback",
    word: "setback",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["つまずき、後退"],
    pronunciation: "/ˈsetbæk/",
    exampleSentence: "The delay was a serious setback for the project.",
    exampleTranslationJa: "その遅れは計画にとって大きな痛手だった。",
    collocations: ["a major setback", "suffer a setback", "a temporary setback"],
    wordFormation: "句動詞 set back(後戻りさせる)が名詞に。",
    mnemonic: "前に進んでいたものが後ろに押し戻されること。完全な失敗ではない。",
    relatedWords: ["obstacle", "delay", "reverse"],
  },
  {
    id: "shortcoming",
    word: "shortcoming",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["欠点、至らない点"],
    pronunciation: "/ˈʃɔːrtkʌmɪŋ/",
    exampleSentence: "The report admits the shortcomings of the system.",
    exampleTranslationJa: "その報告書は制度の欠点を認めている。",
    collocations: ["admit your shortcomings", "the main shortcoming", "despite its shortcomings"],
    wordFormation: "short(足りない)+ coming(届くこと)。「求められる水準に届かないこと」。",
    mnemonic: "come short of(届かない)から。ふつう複数形で使う。",
    relatedWords: ["weakness", "defect", "flaw"],
  },
  {
    id: "pitfall",
    word: "pitfall",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["落とし穴、思わぬ危険"],
    pronunciation: "/ˈpɪtfɔːl/",
    exampleSentence: "The guide lists the common pitfalls for beginners.",
    exampleTranslationJa: "その手引きは初心者が陥りがちな落とし穴を挙げている。",
    collocations: ["common pitfalls", "avoid the pitfalls", "the pitfalls of"],
    wordFormation: "pit(穴)+ fall(落ちる)。動物を捕らえる落とし穴から。",
    mnemonic: "見えていない穴。気づかず踏み込むと失敗する点。",
    relatedWords: ["trap", "danger", "risk"],
  },
  {
    id: "loophole",
    word: "loophole",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(法律などの)抜け穴"],
    pronunciation: "/ˈluːphoʊl/",
    exampleSentence: "Companies exploited a loophole in the tax law.",
    exampleTranslationJa: "企業は税法の抜け穴を利用した。",
    collocations: ["a legal loophole", "exploit a loophole", "close a loophole"],
    mnemonic: "城壁の細い穴が語源。規則の文面をすり抜ける隙間。",
    relatedWords: ["gap", "flaw", "exploit"],
  },
  {
    id: "turmoil",
    word: "turmoil",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["混乱、動揺"],
    pronunciation: "/ˈtɜːrmɔɪl/",
    exampleSentence: "The country was in political turmoil for months.",
    exampleTranslationJa: "その国は数か月にわたって政治的混乱にあった。",
    collocations: ["political turmoil", "in turmoil", "emotional turmoil"],
    mnemonic: "in turmoil の形が多い。社会にも心にも使える「かき乱された状態」。",
    relatedWords: ["chaos", "unrest", "upheaval"],
  },
  {
    id: "upheaval",
    word: "upheaval",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大変動、激変"],
    pronunciation: "/ʌpˈhiːvl/",
    exampleSentence: "The merger caused a huge upheaval in the company.",
    exampleTranslationJa: "その合併は社内に大きな激変をもたらした。",
    collocations: ["social upheaval", "political upheaval", "cause upheaval"],
    wordFormation: "up(上へ)+ heave(持ち上げる)。地面が持ち上がる「隆起」から。",
    mnemonic: "地面がひっくり返るような変化。turmoil より「構造が変わる」感じ。",
    relatedWords: ["turmoil", "disruption", "revolution"],
  },
  {
    id: "unrest",
    word: "unrest",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(社会の)不安、騒乱"],
    pronunciation: "/ʌnˈrest/",
    exampleSentence: "Food shortages led to widespread unrest.",
    exampleTranslationJa: "食料不足が広範な騒乱を招いた。",
    collocations: ["social unrest", "civil unrest", "widespread unrest"],
    wordFormation: "un-(否定)+ rest(安らぎ)。",
    mnemonic: "rest(落ち着き)が un(ない)。デモやストライキを含む社会の不穏さ。",
    relatedWords: ["turmoil", "protest", "instability"],
  },
  {
    id: "disarray",
    word: "disarray",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["混乱、乱れた状態"],
    pronunciation: "/ˌdɪsəˈreɪ/",
    exampleSentence: "The party was in disarray after the defeat.",
    exampleTranslationJa: "その政党は敗北のあと混乱状態にあった。",
    collocations: ["in disarray", "throw into disarray", "complete disarray"],
    wordFormation: "dis-(否定)+ array(整列)。",
    mnemonic: "array(整列)が dis(崩れた)。in disarray の形でほぼ決まって使う。",
    relatedWords: ["chaos", "confusion", "mess"],
  },
  {
    id: "consolation",
    word: "consolation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["慰め、心の支え"],
    pronunciation: "/ˌkɑːnsəˈleɪʃn/",
    exampleSentence: "It was some consolation that nobody was hurt.",
    exampleTranslationJa: "誰もけがをしなかったのがせめてもの慰めだった。",
    collocations: ["some consolation", "a consolation prize", "little consolation"],
    wordFormation: "con-(共に)+ solari(なぐさめる)。",
    mnemonic: "動詞は console。a consolation prize は「残念賞」。",
    relatedWords: ["comfort", "console", "solace"],
  },
  {
    id: "reparation",
    word: "reparation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["賠償、償い"],
    pronunciation: "/ˌrepəˈreɪʃn/",
    exampleSentence: "The treaty required the payment of reparations.",
    exampleTranslationJa: "その条約は賠償金の支払いを求めた。",
    collocations: ["pay reparations", "war reparations", "make reparation for"],
    wordFormation: "repair(修復する)+ -ation。「元に戻すこと」。",
    mnemonic: "repair(直す)と同語根。国家間の賠償はふつう複数形 reparations。",
    relatedWords: ["compensation", "repair", "damages"],
  },
  {
    id: "philanthropy",
    word: "philanthropy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["慈善活動、社会貢献"],
    pronunciation: "/fɪˈlænθrəpi/",
    exampleSentence: "He devoted his later years to philanthropy.",
    exampleTranslationJa: "彼は晩年を慈善活動に捧げた。",
    collocations: ["corporate philanthropy", "a life of philanthropy", "philanthropy and charity"],
    wordFormation: "phil-(愛する)+ anthropos(人間)。「人間を愛すること」。",
    mnemonic: "phil(愛)+ anthropo(人)。philosophy・anthropology と部品を共有する。",
    relatedWords: ["charity", "donation", "generosity"],
  },
]
