import type { VocabularyEntry } from '../types'

// B2 到達に必要な語数(6,500〜7,500)への増補 第1弾。
// 台所・住まい・道具・身の回りの品。日常で毎日目にするのに既存4,500語から漏れていた具体名詞を優先した。
export const plus01: VocabularyEntry[] = [
  {
    id: "drawer",
    word: "drawer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["引き出し"],
    pronunciation: "/drɔːr/",
    exampleSentence: "She keeps her passport in the top drawer of her desk.",
    exampleTranslationJa: "彼女はパスポートを机の一番上の引き出しにしまっている。",
    collocations: ["open a drawer", "the top drawer", "a chest of drawers"],
    wordFormation: "draw(引く)+ -er(もの)。「引いて開けるもの」。",
    relatedWords: ["cabinet", "shelf", "cupboard"],
    mnemonic: "draw(引く)+ -er。「引くもの」がそのまま引き出し。発音は /drɔːr/ の一音節。",
  },
  {
    id: "faucet",
    word: "faucet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["蛇口(米)"],
    pronunciation: "/ˈfɔːsɪt/",
    exampleSentence: "Please turn off the faucet while you brush your teeth.",
    exampleTranslationJa: "歯を磨いている間は蛇口を閉めてください。",
    collocations: ["turn on the faucet", "a leaky faucet", "the kitchen faucet"],
    relatedWords: ["tap", "sink", "valve"],
    mnemonic: "米は faucet、英は tap。旅行先で「蛇口が壊れた」と言うとき使い分ける。",
  },
  {
    id: "kettle",
    word: "kettle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["やかん、電気ケトル"],
    pronunciation: "/ˈketl/",
    exampleSentence: "I put the kettle on as soon as the guests arrived.",
    exampleTranslationJa: "客が着くとすぐに私はやかんを火にかけた。",
    collocations: ["put the kettle on", "boil a kettle", "an electric kettle"],
    relatedWords: ["pot", "boil", "teapot"],
    mnemonic: "湯をわかす専用の道具。put the kettle on だけで「お茶をいれよう」の合図になる。",
  },
  {
    id: "saucepan",
    word: "saucepan",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["片手鍋"],
    pronunciation: "/ˈsɔːspæn/",
    exampleSentence: "Heat the milk in a small saucepan over low heat.",
    exampleTranslationJa: "小さな片手鍋で牛乳を弱火で温めなさい。",
    collocations: ["a small saucepan", "heat in a saucepan"],
    wordFormation: "sauce(ソース)+ pan(鍋)。「ソースを作る鍋」から。",
    relatedWords: ["pot", "pan", "frying pan"],
    mnemonic: "sauce(ソース)を作る pan(鍋)。取っ手が一本の深い鍋。",
  },
  {
    id: "frying pan",
    word: "frying pan",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["フライパン"],
    pronunciation: "/ˈfraɪɪŋ pæn/",
    exampleSentence: "He cracked two eggs into the hot frying pan.",
    exampleTranslationJa: "彼は熱したフライパンに卵を二つ割り入れた。",
    collocations: ["a nonstick frying pan", "heat a frying pan"],
    relatedWords: ["fry", "saucepan", "skillet"],
    mnemonic: "fry(油で焼く)ための平たい pan。out of the frying pan into the fire で「一難去ってまた一難」。",
  },
  {
    id: "blender",
    word: "blender",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ミキサー、ブレンダー"],
    pronunciation: "/ˈblendər/",
    exampleSentence: "Put the fruit and yogurt in a blender and mix for a minute.",
    exampleTranslationJa: "果物とヨーグルトをミキサーに入れて1分混ぜてください。",
    collocations: ["put in a blender", "an electric blender"],
    wordFormation: "blend(混ぜる)+ -er(道具)。",
    relatedWords: ["blend", "mixer", "grind"],
    mnemonic: "blend(混ぜ合わせる)機械。ジュースを作るあの機械は mixer より blender。",
  },
  {
    id: "toaster",
    word: "toaster",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トースター"],
    pronunciation: "/ˈtoʊstər/",
    exampleSentence: "The bread popped up from the toaster.",
    exampleTranslationJa: "パンがトースターから飛び出した。",
    collocations: ["put bread in the toaster", "a pop-up toaster"],
    relatedWords: ["toast", "oven", "grill"],
    mnemonic: "toast(こんがり焼く)機械。焼けたパンが pop up する。",
  },
  {
    id: "microwave",
    word: "microwave",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["電子レンジ", "電子レンジで温める"],
    pronunciation: "/ˈmaɪkroʊweɪv/",
    exampleSentence: "Microwave the soup for two minutes before serving.",
    exampleTranslationJa: "出す前にスープを電子レンジで2分温めてください。",
    collocations: ["in the microwave", "microwave a meal", "a microwave oven"],
    wordFormation: "micro-(極小の)+ wave(波)。「マイクロ波」で加熱する装置。",
    relatedWords: ["oven", "heat", "reheat"],
    mnemonic: "micro(極小)+ wave(波)。「小さな波」で食べ物を内側から温める。",
  },
  {
    id: "stove",
    word: "stove",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コンロ、レンジ台", "ストーブ、暖房器具"],
    pronunciation: "/stoʊv/",
    exampleSentence: "There was a pot simmering on the stove.",
    exampleTranslationJa: "コンロの上で鍋がぐつぐつ煮えていた。",
    collocations: ["on the stove", "a gas stove", "turn off the stove"],
    relatedWords: ["oven", "burner", "cooker"],
    mnemonic: "火を扱う台。日本語の「ストーブ(暖房)」もあるが、料理の「コンロ」の意味が主。",
  },
  {
    id: "freezer",
    word: "freezer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["冷凍庫"],
    pronunciation: "/ˈfriːzər/",
    exampleSentence: "Keep the ice cream in the freezer until dessert.",
    exampleTranslationJa: "デザートの時間までアイスは冷凍庫に入れておいて。",
    collocations: ["in the freezer", "a freezer bag", "freezer burn"],
    wordFormation: "freeze(凍らせる)+ -er(もの)。",
    relatedWords: ["fridge", "frozen", "refrigerator"],
    mnemonic: "freeze(凍る)+ -er。冷蔵室が fridge、冷凍室が freezer。",
  },
  {
    id: "dishwasher",
    word: "dishwasher",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["食器洗い機", "皿洗い係"],
    pronunciation: "/ˈdɪʃwɑːʃər/",
    exampleSentence: "Just load the plates into the dishwasher.",
    exampleTranslationJa: "皿は食器洗い機に入れておいてくれればいいよ。",
    collocations: ["load the dishwasher", "dishwasher safe"],
    wordFormation: "dish(皿)+ wash(洗う)+ -er。",
    relatedWords: ["dish", "sink", "detergent"],
    mnemonic: "dish(皿)を wash(洗う)もの。機械にも人にも使う。",
  },
  {
    id: "countertop",
    word: "countertop",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["調理台、カウンターの天板"],
    pronunciation: "/ˈkaʊntərtɑːp/",
    exampleSentence: "Wipe the countertop after you finish cooking.",
    exampleTranslationJa: "料理が終わったら調理台を拭いてね。",
    collocations: ["a granite countertop", "wipe the countertop"],
    wordFormation: "counter(カウンター)+ top(上面)。",
    relatedWords: ["counter", "surface", "worktop"],
    mnemonic: "counter(台)の top(天板)。料理をする面そのものを指す。",
  },
  {
    id: "mattress",
    word: "mattress",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["マットレス、敷き布団"],
    pronunciation: "/ˈmætrəs/",
    exampleSentence: "This mattress is too soft for my back.",
    exampleTranslationJa: "このマットレスは私の腰には柔らかすぎる。",
    collocations: ["a firm mattress", "a double mattress"],
    relatedWords: ["bed", "pillow", "sheet"],
    mnemonic: "ベッドの上に載る厚い寝床。firm(硬め)か soft(柔らかめ)かで選ぶ。",
  },
  {
    id: "pillow",
    word: "pillow",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["まくら"],
    pronunciation: "/ˈpɪloʊ/",
    exampleSentence: "She buried her face in the pillow and cried.",
    exampleTranslationJa: "彼女はまくらに顔をうずめて泣いた。",
    collocations: ["a soft pillow", "a pillow case", "fluff a pillow"],
    relatedWords: ["cushion", "bed", "blanket"],
    mnemonic: "頭を載せる小さな島。cry into your pillow で「まくらに泣く」。",
  },
  {
    id: "quilt",
    word: "quilt",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["キルト、掛け布団"],
    pronunciation: "/kwɪlt/",
    exampleSentence: "Her grandmother sewed the quilt from old shirts.",
    exampleTranslationJa: "祖母は古いシャツを使ってそのキルトを縫った。",
    collocations: ["a patchwork quilt", "under the quilt"],
    relatedWords: ["blanket", "duvet", "stitch"],
    mnemonic: "布を継ぎ合わせて綿を挟み、刺し縫いしたもの。patchwork quilt が典型。",
  },
  {
    id: "duvet",
    word: "duvet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["羽毛布団"],
    pronunciation: "/duːˈveɪ/",
    exampleSentence: "He pulled the duvet over his head and went back to sleep.",
    exampleTranslationJa: "彼は羽毛布団を頭までかぶって二度寝した。",
    collocations: ["a duvet cover", "under the duvet"],
    etymology: "フランス語 duvet(綿毛)から。",
    relatedWords: ["quilt", "blanket", "comforter"],
    mnemonic: "フランス語の「綿毛」。羽根を詰めた一枚もので、カバー(duvet cover)を掛けて使う。",
  },
  {
    id: "wardrobe",
    word: "wardrobe",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["洋服だんす、クローゼット", "(持っている)衣装一式"],
    pronunciation: "/ˈwɔːrdroʊb/",
    exampleSentence: "She needs a new wardrobe for her new job.",
    exampleTranslationJa: "彼女は新しい仕事のために服を一式そろえる必要がある。",
    collocations: ["a built-in wardrobe", "update your wardrobe"],
    etymology: "古フランス語 warder(守る)+ robe(衣)で「衣を守る場所」。",
    relatedWords: ["closet", "clothes", "cupboard"],
    mnemonic: "ward(守る)+ robe(衣)。服をしまう箱であり、持ち服全体でもある。",
  },
  {
    id: "closet",
    word: "closet",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["押し入れ、クローゼット"],
    pronunciation: "/ˈklɑːzət/",
    exampleSentence: "Hang your coat in the hall closet.",
    exampleTranslationJa: "コートは玄関のクローゼットに掛けてください。",
    collocations: ["a walk-in closet", "clean out a closet"],
    relatedWords: ["wardrobe", "cupboard", "storage"],
    mnemonic: "close(閉じる)から。閉じた小部屋。come out of the closet は「打ち明ける」。",
  },
  {
    id: "bookshelf",
    word: "bookshelf",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["本棚"],
    pronunciation: "/ˈbʊkʃelf/",
    exampleSentence: "The bookshelf reached from the floor to the ceiling.",
    exampleTranslationJa: "その本棚は床から天井まで届いていた。",
    collocations: ["on the bookshelf", "a wooden bookshelf"],
    wordFormation: "book(本)+ shelf(棚)。複数形は bookshelves。",
    relatedWords: ["shelf", "library", "cabinet"],
    mnemonic: "book + shelf。複数形は shelves にならって bookshelves。",
  },
  {
    id: "stool",
    word: "stool",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(背もたれのない)腰かけ、スツール"],
    pronunciation: "/stuːl/",
    exampleSentence: "He sat on a stool at the end of the bar.",
    exampleTranslationJa: "彼はバーの端のスツールに腰かけた。",
    collocations: ["a bar stool", "sit on a stool", "a folding stool"],
    relatedWords: ["chair", "bench", "seat"],
    mnemonic: "背もたれのない腰かけ。bar stool を思い浮かべると形が決まる。",
  },
  {
    id: "armchair",
    word: "armchair",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ひじ掛けいす"],
    pronunciation: "/ˈɑːrmtʃer/",
    exampleSentence: "My father fell asleep in his favourite armchair.",
    exampleTranslationJa: "父はお気に入りのひじ掛けいすで眠ってしまった。",
    collocations: ["sink into an armchair", "a leather armchair"],
    wordFormation: "arm(ひじ)+ chair(いす)。",
    relatedWords: ["chair", "sofa", "recliner"],
    mnemonic: "arm(ひじ)のついた chair。armchair critic は「座ったまま論じる人」。",
  },
  {
    id: "sofa",
    word: "sofa",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ソファー、長いす"],
    pronunciation: "/ˈsoʊfə/",
    exampleSentence: "The cat was asleep on the sofa again.",
    exampleTranslationJa: "猫はまたソファーで眠っていた。",
    collocations: ["sit on the sofa", "a three-seater sofa", "a sofa bed"],
    etymology: "アラビア語 suffah(ベンチ)に由来。",
    relatedWords: ["couch", "armchair", "cushion"],
    mnemonic: "アラビア語の「ベンチ」から。二人以上が座れる長いす。",
  },
  {
    id: "couch",
    word: "couch",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ソファー、寝いす"],
    pronunciation: "/kaʊtʃ/",
    exampleSentence: "We spent the whole evening on the couch watching films.",
    exampleTranslationJa: "私たちは一晩中ソファーで映画を見て過ごした。",
    collocations: ["lie on the couch", "a couch potato"],
    relatedWords: ["sofa", "cushion", "lounge"],
    mnemonic: "sofa とほぼ同義だが、寝ころぶ感じは couch。couch potato は「ごろ寝でテレビ漬けの人」。",
  },
  {
    id: "rug",
    word: "rug",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["敷物、じゅうたん(部屋の一部を覆うもの)"],
    pronunciation: "/rʌɡ/",
    exampleSentence: "A thick rug covered the middle of the wooden floor.",
    exampleTranslationJa: "板張りの床の中央を厚い敷物が覆っていた。",
    collocations: ["a Persian rug", "lay a rug", "sweep it under the rug"],
    relatedWords: ["carpet", "mat", "floor"],
    mnemonic: "carpet は床全体、rug は床の一部だけを覆う。",
  },
  {
    id: "bulb",
    word: "bulb",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["電球", "(植物の)球根"],
    pronunciation: "/bʌlb/",
    exampleSentence: "The bulb in the hallway burned out last night.",
    exampleTranslationJa: "廊下の電球が昨夜切れた。",
    collocations: ["a light bulb", "change a bulb", "plant bulbs"],
    relatedWords: ["lamp", "light", "socket"],
    mnemonic: "電球も球根も「丸くふくらんだもの」。形が同じだから同じ語。",
  },
  {
    id: "socket",
    word: "socket",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["コンセント、差し込み口", "(骨などの)くぼみ、受け口"],
    pronunciation: "/ˈsɑːkɪt/",
    exampleSentence: "There is only one socket in this room.",
    exampleTranslationJa: "この部屋にはコンセントが一つしかない。",
    collocations: ["a wall socket", "plug into a socket", "an eye socket"],
    relatedWords: ["plug", "outlet", "connector"],
    mnemonic: "差し込みを受けるくぼみ。壁のコンセントも眼窩(eye socket)も同じ「受け口」。",
  },
  {
    id: "cord",
    word: "cord",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["コード、細いひも", "電気コード"],
    pronunciation: "/kɔːrd/",
    exampleSentence: "Don't leave the cord across the doorway.",
    exampleTranslationJa: "コードを出入り口に横切らせて置かないで。",
    collocations: ["a power cord", "an extension cord", "unplug the cord"],
    relatedWords: ["cable", "wire", "rope"],
    mnemonic: "太さのある短いひも。細い電線が wire、束ねた電線が cable、家電の一本が cord。",
  },
  {
    id: "charger",
    word: "charger",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["充電器"],
    pronunciation: "/ˈtʃɑːrdʒər/",
    exampleSentence: "Can I borrow your phone charger?",
    exampleTranslationJa: "スマホの充電器を借りてもいい？",
    collocations: ["a phone charger", "a wireless charger"],
    wordFormation: "charge(充電する)+ -er(道具)。",
    relatedWords: ["charge", "battery", "plug"],
    mnemonic: "charge(充電する)+ -er。charge には「請求する」「突撃する」もある同じ語。",
  },
  {
    id: "clock",
    word: "clock",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["時計(置き時計・掛け時計)"],
    pronunciation: "/klɑːk/",
    exampleSentence: "The clock on the wall was ten minutes fast.",
    exampleTranslationJa: "壁の時計は10分進んでいた。",
    collocations: ["an alarm clock", "set the clock", "around the clock"],
    relatedWords: ["watch", "time", "alarm"],
    mnemonic: "身につけるのが watch、置く・掛けるのが clock。",
  },
  {
    id: "calendar",
    word: "calendar",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["カレンダー、暦", "予定表"],
    pronunciation: "/ˈkælɪndər/",
    exampleSentence: "I marked the date on my calendar.",
    exampleTranslationJa: "私はその日をカレンダーに印をつけた。",
    collocations: ["mark on the calendar", "a busy calendar", "the academic calendar"],
    etymology: "ラテン語 calendae(月の初日)に由来。",
    relatedWords: ["schedule", "date", "diary"],
    mnemonic: "ラテン語 calendae(月の一日)から。つづりは -dar、-der ではない。",
  },
  {
    id: "glue",
    word: "glue",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["のり、接着剤", "接着する"],
    pronunciation: "/ɡluː/",
    exampleSentence: "He glued the broken handle back onto the cup.",
    exampleTranslationJa: "彼は取れた取っ手をカップに接着し直した。",
    collocations: ["a tube of glue", "glue A to B", "be glued to the screen"],
    relatedWords: ["stick", "paste", "attach"],
    mnemonic: "接着剤。be glued to で「くぎづけになる」。",
  },
  {
    id: "stapler",
    word: "stapler",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ホチキス"],
    pronunciation: "/ˈsteɪplər/",
    exampleSentence: "Could you pass me the stapler?",
    exampleTranslationJa: "ホチキスを取ってもらえますか。",
    collocations: ["use a stapler", "run out of staples"],
    wordFormation: "staple(留め針で留める)+ -er(道具)。",
    relatedWords: ["staple", "clip", "fasten"],
    mnemonic: "英語で「ホチキス」は通じない。stapler が正しい。",
  },
  {
    id: "hammer",
    word: "hammer",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["金づち、ハンマー", "打ちつける"],
    pronunciation: "/ˈhæmər/",
    exampleSentence: "He hammered a nail into the wall to hang the picture.",
    exampleTranslationJa: "彼は絵を掛けるために壁に釘を打ちつけた。",
    collocations: ["hammer a nail", "a claw hammer", "hammer home a point"],
    relatedWords: ["nail", "tool", "strike"],
    mnemonic: "打つ道具であり、打つ動作でもある。hammer home で「くり返して分からせる」。",
  },
  {
    id: "screwdriver",
    word: "screwdriver",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ねじ回し、ドライバー"],
    pronunciation: "/ˈskruːdraɪvər/",
    exampleSentence: "You will need a small screwdriver to open the case.",
    exampleTranslationJa: "そのケースを開けるには小さなドライバーが要る。",
    collocations: ["a flathead screwdriver", "a Phillips screwdriver"],
    wordFormation: "screw(ねじ)+ driver(打ち込むもの)。",
    relatedWords: ["screw", "tool", "drill"],
    mnemonic: "車の運転手ではない。ねじを「回して進ませる」もの。",
  },
  {
    id: "drill",
    word: "drill",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ドリル、電動穴あけ機", "穴をあける", "反復訓練"],
    pronunciation: "/drɪl/",
    exampleSentence: "They drilled a hole in the wall for the pipe.",
    exampleTranslationJa: "彼らは配管のために壁に穴をあけた。",
    collocations: ["drill a hole", "an electric drill", "a fire drill"],
    relatedWords: ["bore", "practice", "exercise"],
    mnemonic: "同じ所を繰り返し掘る → 繰り返す練習も drill。",
  },
  {
    id: "saw",
    word: "saw",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["のこぎり", "のこぎりで切る"],
    pronunciation: "/sɔː/",
    exampleSentence: "He sawed the plank in half.",
    exampleTranslationJa: "彼は板をのこぎりで半分に切った。",
    collocations: ["a chain saw", "saw through", "saw off"],
    relatedWords: ["cut", "blade", "timber"],
    mnemonic: "see の過去形 saw と同じつづりだが別語。過去形は sawed。",
  },
  {
    id: "bolt",
    word: "bolt",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ボルト、太いねじ", "かんぬき、差し錠", "急に走り出す"],
    pronunciation: "/boʊlt/",
    exampleSentence: "Check that every bolt is tight before you ride.",
    exampleTranslationJa: "乗る前にすべてのボルトが締まっているか確認しなさい。",
    collocations: ["tighten a bolt", "bolt the door", "a bolt of lightning"],
    relatedWords: ["nut", "screw", "lock"],
    mnemonic: "太いねじ、戸のかんぬき、稲妻、そして「一目散に走る」。どれも「まっすぐ差し込む・走る」感じ。",
  },
  {
    id: "wrench",
    word: "wrench",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["スパナ、レンチ", "ねじる、ぐいと引く"],
    pronunciation: "/rentʃ/",
    exampleSentence: "She tightened the pipe with a wrench.",
    exampleTranslationJa: "彼女はレンチで配管を締めた。",
    collocations: ["an adjustable wrench", "wrench something free", "throw a wrench in"],
    relatedWords: ["twist", "tool", "spanner"],
    mnemonic: "ねじる道具であり、ぐいとねじる動作。throw a wrench in で「じゃまをする」。",
  },
  {
    id: "pliers",
    word: "pliers",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ペンチ"],
    pronunciation: "/ˈplaɪərz/",
    exampleSentence: "Use pliers to pull the nail out.",
    exampleTranslationJa: "釘を抜くにはペンチを使いなさい。",
    collocations: ["a pair of pliers", "grip with pliers"],
    relatedWords: ["grip", "tool", "tongs"],
    mnemonic: "scissors と同じく二枚一組なので常に複数形。a pair of pliers。",
  },
  {
    id: "toolbox",
    word: "toolbox",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["道具箱", "(比喩)手持ちの手段一式"],
    pronunciation: "/ˈtuːlbɑːks/",
    exampleSentence: "Every technique you learn goes into your toolbox.",
    exampleTranslationJa: "身につけた技法はどれも自分の道具箱に入っていく。",
    collocations: ["in the toolbox", "a toolbox of skills"],
    wordFormation: "tool(道具)+ box(箱)。",
    relatedWords: ["tool", "kit", "equipment"],
    mnemonic: "道具箱。身につけた技術のことも「自分の toolbox に入る」と言う。",
  },
  {
    id: "shovel",
    word: "shovel",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["シャベル、スコップ", "すくう、かき出す"],
    pronunciation: "/ˈʃʌvl/",
    exampleSentence: "They shovelled snow off the path all morning.",
    exampleTranslationJa: "彼らは午前中ずっと小道の雪をかき出していた。",
    collocations: ["shovel snow", "a garden shovel", "dig with a shovel"],
    relatedWords: ["dig", "spade", "scoop"],
    mnemonic: "すくい上げる道具。細長く土を掘るのが spade、すくうのが shovel。",
  },
  {
    id: "rake",
    word: "rake",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["くまで、レーキ", "かき集める"],
    pronunciation: "/reɪk/",
    exampleSentence: "He raked the fallen leaves into a pile.",
    exampleTranslationJa: "彼は落ち葉をかき集めて山にした。",
    collocations: ["rake leaves", "a garden rake", "rake in money"],
    relatedWords: ["gather", "sweep", "garden"],
    mnemonic: "熊手。落ち葉をかき集める → rake in money で「金をかき集める」。",
  },
  {
    id: "hose",
    word: "hose",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ホース"],
    pronunciation: "/hoʊz/",
    exampleSentence: "She watered the garden with a hose.",
    exampleTranslationJa: "彼女はホースで庭に水をやった。",
    collocations: ["a garden hose", "a fire hose", "turn on the hose"],
    relatedWords: ["pipe", "tube", "water"],
    mnemonic: "水を通す柔らかい管。庭の水まきにも消火にも使う。",
  },
  {
    id: "bucket",
    word: "bucket",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["バケツ", "バケツ一杯の量"],
    pronunciation: "/ˈbʌkɪt/",
    exampleSentence: "He filled a bucket with warm water.",
    exampleTranslationJa: "彼はバケツに温かい湯をいっぱいに入れた。",
    collocations: ["a bucket of water", "a bucket list", "rain buckets"],
    relatedWords: ["pail", "container", "tub"],
    mnemonic: "手さげのおけ。bucket list は「死ぬまでにやりたいことの一覧」。",
  },
  {
    id: "broom",
    word: "broom",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ほうき"],
    pronunciation: "/bruːm/",
    exampleSentence: "Sweep the floor with the broom in the corner.",
    exampleTranslationJa: "隅にあるほうきで床を掃いてください。",
    collocations: ["sweep with a broom", "a broom handle"],
    relatedWords: ["sweep", "mop", "brush"],
    mnemonic: "掃く道具。room と韻を踏むので「部屋を掃くほうき」で覚える。",
  },
  {
    id: "mop",
    word: "mop",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["モップ", "モップでふく", "(汗などを)ぬぐう"],
    pronunciation: "/mɑːp/",
    exampleSentence: "Please mop the kitchen floor before you leave.",
    exampleTranslationJa: "帰る前に台所の床をモップでふいてください。",
    collocations: ["mop the floor", "mop up a spill", "mop your brow"],
    relatedWords: ["wipe", "broom", "clean"],
    mnemonic: "水を含ませて床をふく道具。汗をぬぐうのも mop your brow。",
  },
  {
    id: "sponge",
    word: "sponge",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スポンジ", "海綿"],
    pronunciation: "/spʌndʒ/",
    exampleSentence: "Wipe the table with a damp sponge.",
    exampleTranslationJa: "湿らせたスポンジでテーブルを拭いてください。",
    collocations: ["a damp sponge", "soak up like a sponge", "a sponge cake"],
    relatedWords: ["absorb", "soak", "wipe"],
    mnemonic: "水を吸うもの。知識をぐんぐん吸う人は soak it up like a sponge。",
  },
  {
    id: "dustbin",
    word: "dustbin",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ごみ箱(英)"],
    pronunciation: "/ˈdʌstbɪn/",
    exampleSentence: "The dustbin is emptied every Tuesday morning.",
    exampleTranslationJa: "ごみ箱は毎週火曜の朝に空にされる。",
    collocations: ["empty the dustbin", "throw it in the dustbin"],
    wordFormation: "dust(ちり)+ bin(容器)。米語では trash can。",
    relatedWords: ["bin", "rubbish", "garbage"],
    mnemonic: "dust(ちり)の bin(容器)。英国のごみ箱。米国では trash can。",
  },
  {
    id: "shampoo",
    word: "shampoo",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["シャンプー", "髪を洗う"],
    pronunciation: "/ʃæmˈpuː/",
    exampleSentence: "This shampoo is gentle enough for daily use.",
    exampleTranslationJa: "このシャンプーは毎日使えるほど低刺激だ。",
    collocations: ["a bottle of shampoo", "shampoo your hair"],
    etymology: "ヒンディー語 chāmpo(もみほぐせ)に由来。",
    relatedWords: ["soap", "conditioner", "wash"],
    mnemonic: "ヒンディー語「もみほぐせ」から。髪を「もむ」動作が語の芯。",
  },
  {
    id: "toothbrush",
    word: "toothbrush",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["歯ブラシ"],
    pronunciation: "/ˈtuːθbrʌʃ/",
    exampleSentence: "You should replace your toothbrush every three months.",
    exampleTranslationJa: "歯ブラシは3か月ごとに換えたほうがよい。",
    collocations: ["a soft toothbrush", "an electric toothbrush"],
    wordFormation: "tooth(歯)+ brush(ブラシ)。",
    relatedWords: ["toothpaste", "brush", "dental"],
    mnemonic: "tooth(歯)の brush。tooth の複数形 teeth にはならない複合語。",
  },
  {
    id: "toothpaste",
    word: "toothpaste",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["歯みがき粉"],
    pronunciation: "/ˈtuːθpeɪst/",
    exampleSentence: "We have run out of toothpaste.",
    exampleTranslationJa: "歯みがき粉を切らしてしまった。",
    collocations: ["a tube of toothpaste", "squeeze the toothpaste"],
    wordFormation: "tooth(歯)+ paste(練り物)。",
    relatedWords: ["toothbrush", "paste", "dental"],
    mnemonic: "tooth の paste(練り物)。チューブから squeeze して出す。",
  },
  {
    id: "razor",
    word: "razor",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["かみそり、ひげそり"],
    pronunciation: "/ˈreɪzər/",
    exampleSentence: "He cut himself shaving with a blunt razor.",
    exampleTranslationJa: "彼は切れないかみそりでひげをそって切ってしまった。",
    collocations: ["an electric razor", "razor-sharp", "a razor blade"],
    relatedWords: ["shave", "blade", "sharp"],
    mnemonic: "そり落とす刃。razor-sharp で「かみそりのように鋭い」。",
  },
  {
    id: "comb",
    word: "comb",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["くし", "髪をとかす", "(場所を)くまなく探す"],
    pronunciation: "/koʊm/",
    exampleSentence: "Police combed the woods for the missing child.",
    exampleTranslationJa: "警察は行方不明の子どもを求めて森をくまなく捜索した。",
    collocations: ["comb your hair", "comb through the data", "a fine-tooth comb"],
    relatedWords: ["brush", "search", "hair"],
    mnemonic: "b は発音しない /koʊm/。くしの歯で細かくすく → くまなく探す。",
  },
  {
    id: "scissors",
    word: "scissors",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["はさみ"],
    pronunciation: "/ˈsɪzərz/",
    exampleSentence: "Cut along the dotted line with scissors.",
    exampleTranslationJa: "点線に沿ってはさみで切ってください。",
    collocations: ["a pair of scissors", "sharp scissors", "kitchen scissors"],
    relatedWords: ["cut", "blade", "shears"],
    mnemonic: "刃が二枚一組なので常に複数形。「一丁」は a pair of scissors。",
  },
  {
    id: "zipper",
    word: "zipper",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ファスナー、チャック"],
    pronunciation: "/ˈzɪpər/",
    exampleSentence: "The zipper on my jacket is stuck.",
    exampleTranslationJa: "上着のファスナーが引っかかって動かない。",
    collocations: ["a broken zipper", "do up the zipper"],
    wordFormation: "zip(シューッと動く)+ -er。動詞は zip up。",
    relatedWords: ["zip", "button", "fasten"],
    mnemonic: "zip はシューッという音。音がそのまま道具の名前になった。動詞は zip up。",
  },
  {
    id: "sleeve",
    word: "sleeve",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["そで"],
    pronunciation: "/sliːv/",
    exampleSentence: "He rolled up his sleeves and started to work.",
    exampleTranslationJa: "彼はそでをまくって仕事に取りかかった。",
    collocations: ["roll up your sleeves", "short sleeves", "up your sleeve"],
    relatedWords: ["shirt", "cuff", "collar"],
    mnemonic: "have something up your sleeve は「切り札を隠し持つ」。",
  },
  {
    id: "collar",
    word: "collar",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["えり", "(犬などの)首輪"],
    pronunciation: "/ˈkɑːlər/",
    exampleSentence: "His shirt collar was stiff and white.",
    exampleTranslationJa: "彼のシャツのえりは糊がきいて白かった。",
    collocations: ["a shirt collar", "a dog collar", "a white-collar job"],
    etymology: "ラテン語 collum(首)から。首まわりのもの。",
    relatedWords: ["neck", "cuff", "shirt"],
    mnemonic: "ラテン語 collum(首)。首まわりのもの。white-collar / blue-collar の collar もこれ。",
  },
  {
    id: "cuff",
    word: "cuff",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["そで口、カフス", "(複数形で)手錠"],
    pronunciation: "/kʌf/",
    exampleSentence: "He wrote the number on his shirt cuff.",
    exampleTranslationJa: "彼はその番号をシャツのそで口に書いた。",
    collocations: ["a shirt cuff", "off the cuff", "handcuffs"],
    relatedWords: ["sleeve", "collar", "wrist"],
    mnemonic: "off the cuff は「そで口のメモ程度で」→「即興で」。",
  },
  {
    id: "hem",
    word: "hem",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(布の)へり、すそ", "すそを縫う"],
    pronunciation: "/hem/",
    exampleSentence: "The hem of her dress had come undone.",
    exampleTranslationJa: "彼女のワンピースのすそがほつれていた。",
    collocations: ["take up a hem", "let down the hem"],
    relatedWords: ["edge", "sew", "seam"],
    mnemonic: "布のふちを折り返して縫った部分。すそ上げは take up the hem。",
  },
  {
    id: "apron",
    word: "apron",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["エプロン"],
    pronunciation: "/ˈeɪprən/",
    exampleSentence: "She wiped her hands on her apron.",
    exampleTranslationJa: "彼女はエプロンで手を拭いた。",
    collocations: ["put on an apron", "a kitchen apron"],
    etymology: "元は napron。a napron が誤って an apron と切られた語。",
    relatedWords: ["cook", "kitchen", "uniform"],
    mnemonic: "元は a napron。n が冠詞に吸い取られて an apron になった珍しい語。",
  },
  {
    id: "scarf",
    word: "scarf",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["マフラー、スカーフ"],
    pronunciation: "/skɑːrf/",
    exampleSentence: "She wrapped a woollen scarf around her neck.",
    exampleTranslationJa: "彼女は毛糸のマフラーを首に巻いた。",
    collocations: ["wear a scarf", "a silk scarf", "wrap a scarf"],
    relatedWords: ["shawl", "neck", "wool"],
    mnemonic: "複数形は scarves(または scarfs)。",
  },
  {
    id: "sandal",
    word: "sandal",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["サンダル"],
    pronunciation: "/ˈsændl/",
    exampleSentence: "She wore sandals on the beach.",
    exampleTranslationJa: "彼女は浜辺でサンダルを履いていた。",
    collocations: ["a pair of sandals", "leather sandals"],
    relatedWords: ["shoe", "slipper", "footwear"],
    mnemonic: "足の甲があいた履物。夏の浜辺の一足で覚える。",
  },
  {
    id: "boot",
    word: "boot",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ブーツ、長靴", "(英)車のトランク"],
    pronunciation: "/buːt/",
    exampleSentence: "Put your boots on; the ground is muddy.",
    exampleTranslationJa: "長靴を履いて。地面がぬかるんでいる。",
    collocations: ["a pair of boots", "rubber boots", "boot up a computer"],
    relatedWords: ["shoe", "footwear", "heel"],
    mnemonic: "くるぶしより上まである履物。英国では車のトランクも boot。",
  },
  {
    id: "slipper",
    word: "slipper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スリッパ、室内履き"],
    pronunciation: "/ˈslɪpər/",
    exampleSentence: "He shuffled into the kitchen in his slippers.",
    exampleTranslationJa: "彼はスリッパのまま台所へすり足で入ってきた。",
    collocations: ["a pair of slippers", "warm slippers"],
    wordFormation: "slip(するっと入れる)+ -er。足をすべり込ませる履物。",
    relatedWords: ["shoe", "sandal", "indoor"],
    mnemonic: "slip(するっと入れる)+ -er。足をすべり込ませるだけの履物。",
  },
  {
    id: "sneaker",
    word: "sneaker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スニーカー、運動靴"],
    pronunciation: "/ˈsniːkər/",
    exampleSentence: "He bought a new pair of sneakers for running.",
    exampleTranslationJa: "彼は走るために新しいスニーカーを買った。",
    collocations: ["a pair of sneakers", "white sneakers"],
    wordFormation: "sneak(忍び寄る)+ -er。「足音がしない靴」から。",
    relatedWords: ["shoe", "trainer", "boot"],
    mnemonic: "sneak(忍び寄る)+ -er。底が柔らかく足音がしないから。英国では trainer。",
  },
  {
    id: "ribbon",
    word: "ribbon",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["リボン、細長い帯"],
    pronunciation: "/ˈrɪbən/",
    exampleSentence: "The box was tied with a red ribbon.",
    exampleTranslationJa: "その箱は赤いリボンで結ばれていた。",
    collocations: ["tie a ribbon", "cut the ribbon", "a blue ribbon"],
    relatedWords: ["bow", "tape", "strip"],
    mnemonic: "細長い帯。開店の cut the ribbon(テープカット)でも使う。",
  },
  {
    id: "wallet",
    word: "wallet",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["財布(札入れ)"],
    pronunciation: "/ˈwɑːlɪt/",
    exampleSentence: "He left his wallet on the train.",
    exampleTranslationJa: "彼は電車に財布を忘れた。",
    collocations: ["open your wallet", "a leather wallet", "a digital wallet"],
    relatedWords: ["purse", "money", "card"],
    mnemonic: "折りたたむ札入れ。open your wallet で「金を出す」。",
  },
  {
    id: "purse",
    word: "purse",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["(米)ハンドバッグ", "(英)小銭入れ"],
    pronunciation: "/pɜːrs/",
    exampleSentence: "She rummaged in her purse for the keys.",
    exampleTranslationJa: "彼女はかばんの中を探って鍵をさがした。",
    collocations: ["a leather purse", "hold the purse strings"],
    relatedWords: ["wallet", "handbag", "bag"],
    mnemonic: "米ではハンドバッグ、英では小銭入れ。hold the purse strings は「財布のひもを握る」。",
  },
  {
    id: "backpack",
    word: "backpack",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["リュックサック、背負いかばん"],
    pronunciation: "/ˈbækpæk/",
    exampleSentence: "She swung her backpack over one shoulder.",
    exampleTranslationJa: "彼女はリュックを片方の肩にひょいと掛けた。",
    collocations: ["carry a backpack", "a heavy backpack"],
    wordFormation: "back(背中)+ pack(荷)。",
    relatedWords: ["rucksack", "bag", "luggage"],
    mnemonic: "back(背中)に pack(荷)。背負って歩く旅は backpacking。",
  },
  {
    id: "suitcase",
    word: "suitcase",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スーツケース"],
    pronunciation: "/ˈsuːtkeɪs/",
    exampleSentence: "My suitcase did not arrive with the flight.",
    exampleTranslationJa: "私のスーツケースはその便で届かなかった。",
    collocations: ["pack a suitcase", "a heavy suitcase"],
    wordFormation: "suit(一そろいの服)+ case(容器)。",
    relatedWords: ["luggage", "baggage", "trunk"],
    mnemonic: "suit(一そろいの服)を入れる case。旅の荷物そのもの。",
  },
  {
    id: "umbrella",
    word: "umbrella",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["かさ", "(比喩)全体を覆う枠組み"],
    pronunciation: "/ʌmˈbrelə/",
    exampleSentence: "These programmes fall under the umbrella of public health.",
    exampleTranslationJa: "これらの事業はいずれも公衆衛生という枠組みに入る。",
    collocations: ["put up an umbrella", "under the umbrella of", "an umbrella term"],
    etymology: "ラテン語 umbra(影)から。元は日よけ。",
    relatedWords: ["shade", "cover", "rain"],
    mnemonic: "ラテン語 umbra(影)。元は日よけ。全体を覆うので「傘下・総称」の意味にもなる。",
  },
]
