import type { VocabularyEntry } from '../types'

// 増補 第36弾。町・仕事・素材まわりの具体名詞。
export const plus36: VocabularyEntry[] = [
  {
    id: "pastry",
    word: "pastry",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["練り生地(パイ皮)", "焼き菓子"],
    pronunciation: "/ˈpeɪstri/",
    exampleSentence: "Roll out the pastry and line the tin.",
    exampleTranslationJa: "生地を伸ばして型に敷いて。",
    collocations: ["roll out the pastry", "puff pastry", "a Danish pastry"],
    mnemonic: "paste(練り物)+ -ry。生地そのものと、それで作る菓子の両方を指す。",
    relatedWords: ["dough", "pie", "bake"],
  },
  {
    id: "peacock",
    word: "peacock",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["クジャク(雄)"],
    pronunciation: "/ˈpiːkɑːk/",
    exampleSentence: "The peacock spread its tail feathers.",
    exampleTranslationJa: "クジャクが尾羽を広げた。",
    collocations: ["a peacock spreads its tail", "peacock feathers", "as proud as a peacock"],
    mnemonic: "羽を広げるのは雄だけ。as proud as a peacock は「得意満面」。",
    relatedWords: ["feather", "bird", "tail"],
  },
  {
    id: "pearl",
    word: "pearl",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["真珠"],
    pronunciation: "/pɜːrl/",
    exampleSentence: "She wore a string of pearls.",
    exampleTranslationJa: "彼女は真珠のネックレスをしていた。",
    collocations: ["a string of pearls", "a pearl necklace", "pearls of wisdom"],
    mnemonic: "貝の中で育つ宝石。pearls of wisdom は「ありがたい助言」。",
    relatedWords: ["oyster", "jewel", "necklace"],
  },
  {
    id: "pebble",
    word: "pebble",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["小石"],
    pronunciation: "/ˈpebl/",
    exampleSentence: "He threw a pebble into the water.",
    exampleTranslationJa: "彼は小石を水に投げ入れた。",
    collocations: ["a smooth pebble", "a pebble beach", "throw a pebble"],
    mnemonic: "波や川で角が取れた丸い小石。もっと大きいものが boulder。",
    relatedWords: ["stone", "boulder", "gravel"],
  },
  {
    id: "peg",
    word: "peg",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["くい、木くぎ", "洗濯ばさみ(英)", "掛けくぎ"],
    pronunciation: "/peɡ/",
    exampleSentence: "Hang your coat on the peg by the door.",
    exampleTranslationJa: "扉のそばの掛けくぎにコートを掛けて。",
    collocations: ["a clothes peg", "hang on a peg", "a tent peg"],
    mnemonic: "打ちこむ、または引っかける短い棒。テントを留めるのも tent peg。",
    relatedWords: ["hook", "nail", "tent"],
  },
  {
    id: "pencil",
    word: "pencil",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["鉛筆"],
    pronunciation: "/ˈpensl/",
    exampleSentence: "Write your name in pencil first.",
    exampleTranslationJa: "まず鉛筆で名前を書いて。",
    collocations: ["in pencil", "sharpen a pencil", "a pencil case"],
    mnemonic: "ラテン語 penicillus(小さな筆)から。penicillin と同じ語源。",
    relatedWords: ["pen", "eraser", "sharpener"],
  },
  {
    id: "penknife",
    word: "penknife",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小型の折りたたみナイフ"],
    pronunciation: "/ˈpennaɪf/",
    exampleSentence: "He cut the string with a penknife.",
    exampleTranslationJa: "彼は小型ナイフでひもを切った。",
    collocations: ["a small penknife", "open a penknife", "cut with a penknife"],
    mnemonic: "もとは羽ペンを削るための小刀。複数形は penknives。",
    relatedWords: ["knife", "blade", "fold"],
  },
  {
    id: "pepper",
    word: "pepper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["こしょう", "ピーマン、パプリカ"],
    pronunciation: "/ˈpepər/",
    exampleSentence: "Add salt and pepper to taste.",
    exampleTranslationJa: "塩とこしょうを好みで加えて。",
    collocations: ["salt and pepper", "black pepper", "a red pepper"],
    mnemonic: "香辛料と野菜の両方を指す。区別したいときは a bell pepper。",
    relatedWords: ["salt", "spice", "vegetable"],
  },
  {
    id: "perfume",
    word: "perfume",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["香水", "芳香"],
    pronunciation: "/ˈpɜːrfjuːm/",
    exampleSentence: "She wears the same perfume every day.",
    exampleTranslationJa: "彼女は毎日同じ香水をつけている。",
    collocations: ["wear perfume", "a bottle of perfume", "a strong perfume"],
    mnemonic: "ラテン語 per(通して)+ fumus(煙)。香を焚きしめた名残。",
    relatedWords: ["scent", "fragrance", "smell"],
  },
  {
    id: "pewter",
    word: "pewter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["しろめ(錫を主とする合金)"],
    pronunciation: "/ˈpjuːtər/",
    exampleSentence: "They drank from old pewter mugs.",
    exampleTranslationJa: "彼らは古いしろめのジョッキで飲んだ。",
    collocations: ["a pewter mug", "polished pewter", "a pewter plate"],
    mnemonic: "鈍い銀色の合金。昔の食器や酒器によく使われた。",
    relatedWords: ["tin", "metal", "alloy"],
  },
  {
    id: "piano",
    word: "piano",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ピアノ"],
    pronunciation: "/piˈænoʊ/",
    exampleSentence: "She has played the piano since she was six.",
    exampleTranslationJa: "彼女は6歳からピアノを弾いている。",
    collocations: ["play the piano", "a grand piano", "a piano lesson"],
    mnemonic: "イタリア語 pianoforte(弱く強く)の略。楽器は play the piano と the をつける。",
    relatedWords: ["keyboard", "music", "instrument"],
  },
  {
    id: "piglet",
    word: "piglet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["子ブタ"],
    pronunciation: "/ˈpɪɡlət/",
    exampleSentence: "The sow had eight piglets.",
    exampleTranslationJa: "その母ブタは8匹の子ブタを産んだ。",
    collocations: ["a newborn piglet", "a litter of piglets", "feed the piglets"],
    mnemonic: "pig + -let(小さいもの)。booklet・leaflet と同じ作り。",
    relatedWords: ["pig", "sow", "farm"],
  },
  {
    id: "pillowcase",
    word: "pillowcase",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["まくらカバー"],
    pronunciation: "/ˈpɪloʊkeɪs/",
    exampleSentence: "She changed the sheets and pillowcases.",
    exampleTranslationJa: "彼女はシーツとまくらカバーを替えた。",
    collocations: ["a clean pillowcase", "change the pillowcase", "a cotton pillowcase"],
    mnemonic: "pillow(まくら)+ case(覆い)。中身は pillow、外袋が pillowcase。",
    relatedWords: ["pillow", "sheet", "bedding"],
  },
  {
    id: "pinecone",
    word: "pinecone",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["松かさ、松ぼっくり"],
    pronunciation: "/ˈpaɪnkoʊn/",
    exampleSentence: "The children collected pinecones in the wood.",
    exampleTranslationJa: "子どもたちは林で松ぼっくりを集めた。",
    collocations: ["collect pinecones", "a dry pinecone", "a pinecone falls"],
    mnemonic: "pine(松)+ cone(円すい)。松の実が入った円すい形の実。",
    relatedWords: ["pine", "cone", "forest"],
  },
  {
    id: "pitcher",
    word: "pitcher",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["水差し(米)", "(野球の)投手"],
    pronunciation: "/ˈpɪtʃər/",
    exampleSentence: "He filled a pitcher with cold water.",
    exampleTranslationJa: "彼は水差しに冷たい水を満たした。",
    collocations: ["a pitcher of water", "fill a pitcher", "a baseball pitcher"],
    mnemonic: "英国では jug と言う。野球の投手も同じつづり。",
    relatedWords: ["jug", "water", "baseball"],
  },
  {
    id: "placemat",
    word: "placemat",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ランチョンマット"],
    pronunciation: "/ˈpleɪsmæt/",
    exampleSentence: "She set a placemat in front of each chair.",
    exampleTranslationJa: "彼女は各席の前にランチョンマットを置いた。",
    collocations: ["lay out placemats", "a cork placemat", "wipe the placemat"],
    mnemonic: "place(席)+ mat(敷物)。食器の下に一人分ずつ敷く。",
    relatedWords: ["tablecloth", "mat", "table"],
  },
  {
    id: "platter",
    word: "platter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大皿、盛り合わせ"],
    pronunciation: "/ˈplætər/",
    exampleSentence: "Cheese was served on a wooden platter.",
    exampleTranslationJa: "チーズが木の大皿で出された。",
    collocations: ["a cheese platter", "a serving platter", "on a platter"],
    mnemonic: "plate(皿)より大きく、取り分け用。on a platter は「お膳立てされて」。",
    relatedWords: ["plate", "dish", "serve"],
  },
  {
    id: "playground",
    word: "playground",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["遊び場、校庭"],
    pronunciation: "/ˈpleɪɡraʊnd/",
    exampleSentence: "The children ran out into the playground.",
    exampleTranslationJa: "子どもたちは遊び場へ走り出た。",
    collocations: ["in the playground", "a school playground", "playground equipment"],
    mnemonic: "play(遊ぶ)+ ground(場所)。学校では校庭も指す。",
    relatedWords: ["swing", "slide", "school"],
  },
  {
    id: "plough",
    word: "plough",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["すき、プラウ", "(畑を)耕す"],
    pronunciation: "/plaʊ/",
    exampleSentence: "The farmer will plough the field in spring.",
    exampleTranslationJa: "農夫は春にその畑を耕す。",
    collocations: ["plough a field", "a horse drawn plough", "plough through work"],
    mnemonic: "米国つづりは plow。plough through は「(仕事を)苦労して片づける」。",
    relatedWords: ["farm", "field", "tractor"],
  },
  {
    id: "plywood",
    word: "plywood",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["合板、ベニヤ板"],
    pronunciation: "/ˈplaɪwʊd/",
    exampleSentence: "The window was covered with a sheet of plywood.",
    exampleTranslationJa: "窓は合板の板でふさがれていた。",
    collocations: ["a sheet of plywood", "thin plywood", "cut plywood"],
    mnemonic: "ply(層)+ wood(木)。薄い板を何層も貼り合わせたもの。",
    relatedWords: ["timber", "board", "wood"],
  },
  {
    id: "policeman",
    word: "policeman",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["警察官(男性)"],
    pronunciation: "/pəˈliːsmən/",
    exampleSentence: "A policeman directed the traffic at the corner.",
    exampleTranslationJa: "警察官が角で交通整理をしていた。",
    collocations: ["ask a policeman", "an off duty policeman", "a policeman on duty"],
    mnemonic: "性別を問わない言い方は police officer。今はそちらが好まれる。",
    relatedWords: ["police officer", "police", "officer"],
  },
  {
    id: "polish",
    word: "polish",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["磨く", "つや出し剤", "(文章などを)推敲する"],
    pronunciation: "/ˈpɑːlɪʃ/",
    exampleSentence: "He polished his shoes until they shone.",
    exampleTranslationJa: "彼は靴が光るまで磨いた。",
    collocations: ["polish your shoes", "shoe polish", "polish up a speech"],
    mnemonic: "こすってつやを出す。polish up で「仕上げを整える」。",
    relatedWords: ["shine", "clean", "wax"],
  },
  {
    id: "postbox",
    word: "postbox",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["郵便ポスト(英)"],
    pronunciation: "/ˈpoʊstbɑːks/",
    exampleSentence: "She dropped the letter into the postbox.",
    exampleTranslationJa: "彼女は手紙を郵便ポストに投函した。",
    collocations: ["drop a letter in the postbox", "a red postbox", "the nearest postbox"],
    mnemonic: "英国の街角にある赤い円柱。受け取る側の箱は letterbox。",
    relatedWords: ["mailbox", "letter", "post"],
  },
  {
    id: "postcard",
    word: "postcard",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["はがき、絵はがき"],
    pronunciation: "/ˈpoʊstkɑːrd/",
    exampleSentence: "He sent a postcard from the seaside.",
    exampleTranslationJa: "彼は海辺から絵はがきを送った。",
    collocations: ["send a postcard", "a picture postcard", "write a postcard"],
    mnemonic: "post(郵便)+ card。封筒に入れずそのまま出す。",
    relatedWords: ["letter", "stamp", "souvenir"],
  },
  {
    id: "postcode",
    word: "postcode",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["郵便番号(英)"],
    pronunciation: "/ˈpoʊstkoʊd/",
    exampleSentence: "Please write your postcode on the form.",
    exampleTranslationJa: "用紙に郵便番号を書いてください。",
    collocations: ["enter your postcode", "a full postcode", "the wrong postcode"],
    mnemonic: "英国語。米国では ZIP code。英国のものは文字と数字が混ざる。",
    relatedWords: ["address", "post", "zip code"],
  },
  {
    id: "postman",
    word: "postman",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["郵便配達員(英)"],
    pronunciation: "/ˈpoʊstmən/",
    exampleSentence: "The postman comes before nine every morning.",
    exampleTranslationJa: "郵便配達員は毎朝9時前に来る。",
    collocations: ["the postman delivers", "wait for the postman", "a friendly postman"],
    mnemonic: "米国では mailman。性別を問わない言い方は postal worker。",
    relatedWords: ["post", "deliver", "letter"],
  },
  {
    id: "pothole",
    word: "pothole",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(道路の)くぼみ、穴"],
    pronunciation: "/ˈpɑːthoʊl/",
    exampleSentence: "The bike hit a deep pothole in the road.",
    exampleTranslationJa: "自転車が道路の深い穴にぶつかった。",
    collocations: ["hit a pothole", "a deep pothole", "repair potholes"],
    mnemonic: "pot(鍋)のようにへこんだ hole(穴)。舗装が抜けてできる。",
    relatedWords: ["road", "hole", "repair"],
  },
  {
    id: "potter",
    word: "potter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["陶芸家、陶工"],
    pronunciation: "/ˈpɑːtər/",
    exampleSentence: "The potter shaped the clay on a wheel.",
    exampleTranslationJa: "陶工はろくろの上で粘土を形づくった。",
    collocations: ["a skilled potter", "a potter's wheel", "work as a potter"],
    mnemonic: "pot(器)+ -er。ろくろは a potter's wheel。",
    relatedWords: ["pottery", "clay", "craft"],
  },
  {
    id: "pottery",
    word: "pottery",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["陶器", "陶芸"],
    pronunciation: "/ˈpɑːtəri/",
    exampleSentence: "She takes a pottery class on Saturdays.",
    exampleTranslationJa: "彼女は土曜に陶芸教室に通っている。",
    collocations: ["a pottery class", "make pottery", "ancient pottery"],
    mnemonic: "potter(陶工)+ -y。作る技も、できた品も指す。",
    relatedWords: ["potter", "clay", "ceramic"],
  },
  {
    id: "pram",
    word: "pram",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["乳母車(英)"],
    pronunciation: "/præm/",
    exampleSentence: "She pushed the pram along the path.",
    exampleTranslationJa: "彼女は小道に沿って乳母車を押した。",
    collocations: ["push a pram", "a baby in a pram", "fold up the pram"],
    mnemonic: "perambulator の略。赤ん坊が横になれるものを指す。",
    relatedWords: ["stroller", "baby", "push"],
  },
  {
    id: "prune",
    word: "prune",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(枝を)刈りこむ、剪定する", "(予算などを)切り詰める", "プルーン"],
    pronunciation: "/pruːn/",
    exampleSentence: "You should prune the roses in winter.",
    exampleTranslationJa: "バラは冬に剪定するとよい。",
    collocations: ["prune a tree", "prune the budget", "dried prunes"],
    mnemonic: "余分な枝を落として形を整えること。予算にも同じ動詞を使う。",
    relatedWords: ["trim", "cut", "garden"],
  },
  {
    id: "puddle",
    word: "puddle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["水たまり"],
    pronunciation: "/ˈpʌdl/",
    exampleSentence: "The child jumped into every puddle.",
    exampleTranslationJa: "その子はどの水たまりにも飛びこんだ。",
    collocations: ["step in a puddle", "a muddy puddle", "jump in puddles"],
    mnemonic: "雨のあと道にできる浅い水のたまり。pool より小さく一時的。",
    relatedWords: ["pool", "rain", "mud"],
  },
  {
    id: "puppet",
    word: "puppet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["あやつり人形", "(比喩)言いなりの人"],
    pronunciation: "/ˈpʌpɪt/",
    exampleSentence: "The puppet moved when she pulled the strings.",
    exampleTranslationJa: "彼女が糸を引くと人形が動いた。",
    collocations: ["a puppet show", "a hand puppet", "a puppet government"],
    mnemonic: "糸や手で動かす人形。裏で操られる政権は puppet government。",
    relatedWords: ["doll", "string", "theatre"],
  },
  {
    id: "puppy",
    word: "puppy",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["子犬"],
    pronunciation: "/ˈpʌpi/",
    exampleSentence: "The puppy chewed one of my shoes.",
    exampleTranslationJa: "子犬が私の靴を片方かんでしまった。",
    collocations: ["a playful puppy", "train a puppy", "a litter of puppies"],
    mnemonic: "dog の子。猫の子は kitten。",
    relatedWords: ["dog", "kitten", "pet"],
  },
  {
    id: "quartz",
    word: "quartz",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["石英、水晶"],
    pronunciation: "/kwɔːrts/",
    exampleSentence: "The rock contained veins of white quartz.",
    exampleTranslationJa: "その岩には白い石英の筋が入っていた。",
    collocations: ["a quartz crystal", "a quartz watch", "white quartz"],
    mnemonic: "規則正しく振動する性質から、時計の名にも使われる。",
    relatedWords: ["crystal", "mineral", "granite"],
  },
  {
    id: "racket",
    word: "racket",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ラケット", "騒音", "不正な金もうけ"],
    pronunciation: "/ˈrækɪt/",
    exampleSentence: "He bought a new tennis racket.",
    exampleTranslationJa: "彼は新しいテニスラケットを買った。",
    collocations: ["a tennis racket", "make a racket", "a protection racket"],
    mnemonic: "打つ道具と、うるさい音が同じつづり。英国では racquet とも書く。",
    relatedWords: ["tennis", "noise", "bat"],
  },
  {
    id: "raft",
    word: "raft",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["いかだ", "ゴムボート"],
    pronunciation: "/ræft/",
    exampleSentence: "They crossed the river on a wooden raft.",
    exampleTranslationJa: "彼らは木のいかだで川を渡った。",
    collocations: ["a wooden raft", "build a raft", "a rubber raft"],
    mnemonic: "板を並べて浮かべた平らな舟。a raft of で「たくさんの」の意味にもなる。",
    relatedWords: ["boat", "float", "river"],
  },
  {
    id: "railing",
    word: "railing",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["柵、手すり"],
    pronunciation: "/ˈreɪlɪŋ/",
    exampleSentence: "He leaned on the railing and looked down.",
    exampleTranslationJa: "彼は柵にもたれて下を見た。",
    collocations: ["lean on the railing", "iron railings", "a metal railing"],
    mnemonic: "rail(横棒)+ -ing。並んだ棒で作った柵や手すり。",
    relatedWords: ["fence", "handrail", "barrier"],
  },
  {
    id: "ramp",
    word: "ramp",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["傾斜路、スロープ"],
    pronunciation: "/ræmp/",
    exampleSentence: "A ramp leads up to the front door.",
    exampleTranslationJa: "玄関へは傾斜路が続いている。",
    collocations: ["a wheelchair ramp", "a loading ramp", "go up the ramp"],
    mnemonic: "段差を斜めにつないだ通路。車いすや台車が通れる。",
    relatedWords: ["slope", "wheelchair", "stairs"],
  },
  {
    id: "raven",
    word: "raven",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ワタリガラス"],
    pronunciation: "/ˈreɪvn/",
    exampleSentence: "A raven perched on the castle wall.",
    exampleTranslationJa: "ワタリガラスが城壁に止まっていた。",
    collocations: ["a black raven", "a raven perches", "raven black hair"],
    mnemonic: "crow より大きく、声も低い。真っ黒な髪を raven black と言う。",
    relatedWords: ["crow", "bird", "black"],
  },
  {
    id: "reed",
    word: "reed",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アシ、葦", "(楽器の)リード"],
    pronunciation: "/riːd/",
    exampleSentence: "Tall reeds grew along the riverbank.",
    exampleTranslationJa: "川岸に背の高いアシが生えていた。",
    collocations: ["tall reeds", "a reed bed", "a clarinet reed"],
    mnemonic: "水辺に生える細長い草。木管楽器の振動板も同じ語。",
    relatedWords: ["marsh", "grass", "clarinet"],
  },
  {
    id: "reel",
    word: "reel",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["糸巻き、リール", "よろめく"],
    pronunciation: "/riːl/",
    exampleSentence: "He wound the line back onto the reel.",
    exampleTranslationJa: "彼は糸をリールに巻き戻した。",
    collocations: ["a fishing reel", "wind in the reel", "reel in a fish"],
    mnemonic: "巻き取る円い道具。reel off は「すらすら並べ立てる」。",
    relatedWords: ["spool", "fishing", "wind"],
  },
  {
    id: "reflector",
    word: "reflector",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["反射板、反射器"],
    pronunciation: "/rɪˈflektər/",
    exampleSentence: "The bike has a red reflector at the back.",
    exampleTranslationJa: "その自転車は後ろに赤い反射板がついている。",
    collocations: ["a rear reflector", "a road reflector", "fit a reflector"],
    mnemonic: "reflect(反射する)+ -or。光を返して存在を知らせるもの。",
    relatedWords: ["reflect", "light", "bicycle"],
  },
  {
    id: "refrigerator",
    word: "refrigerator",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["冷蔵庫"],
    pronunciation: "/rɪˈfrɪdʒəreɪtər/",
    exampleSentence: "Keep the milk in the refrigerator.",
    exampleTranslationJa: "牛乳は冷蔵庫に入れておいて。",
    collocations: ["put in the refrigerator", "an empty refrigerator", "a large refrigerator"],
    mnemonic: "ラテン語 frigus(冷たい)から。日常では短く fridge。",
    relatedWords: ["fridge", "freezer", "kitchen"],
  },
  {
    id: "reindeer",
    word: "reindeer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["トナカイ"],
    pronunciation: "/ˈreɪndɪr/",
    exampleSentence: "Reindeer live in the far north.",
    exampleTranslationJa: "トナカイは極北に生息している。",
    collocations: ["a herd of reindeer", "reindeer antlers", "pull a sleigh"],
    mnemonic: "単数も複数も reindeer。rain(雨)とは関係なく、古ノルド語 hreinn から。",
    relatedWords: ["deer", "moose", "sleigh"],
  },
  {
    id: "reservoir",
    word: "reservoir",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["貯水池、ダム湖", "蓄え"],
    pronunciation: "/ˈrezərvwɑːr/",
    exampleSentence: "The reservoir supplies water to the whole city.",
    exampleTranslationJa: "その貯水池は市全体に水を供給している。",
    collocations: ["a water reservoir", "the reservoir is low", "a reservoir of talent"],
    mnemonic: "reserve(蓄える)+ -oir。フランス語由来で最後の r は読まない。",
    relatedWords: ["dam", "water", "supply"],
  },
  {
    id: "rhino",
    word: "rhino",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["サイ"],
    pronunciation: "/ˈraɪnoʊ/",
    exampleSentence: "A rhino grazed quietly on the plain.",
    exampleTranslationJa: "サイが草原で静かに草を食べていた。",
    collocations: ["a white rhino", "a rhino horn", "protect rhinos"],
    mnemonic: "rhinoceros の略。ギリシャ語で「鼻の角」。",
    relatedWords: ["hippo", "elephant", "horn"],
  },
  {
    id: "rim",
    word: "rim",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(器や車輪の)縁、ふち"],
    pronunciation: "/rɪm/",
    exampleSentence: "There was lipstick on the rim of the glass.",
    exampleTranslationJa: "グラスの縁に口紅がついていた。",
    collocations: ["the rim of a glass", "a wheel rim", "along the rim"],
    mnemonic: "円いものの外周そのもの。edge より丸い輪郭に使う。",
    relatedWords: ["edge", "wheel", "border"],
  },
  {
    id: "rind",
    word: "rind",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(果物・チーズなどの)厚い外皮"],
    pronunciation: "/raɪnd/",
    exampleSentence: "Cut the rind off the cheese before serving.",
    exampleTranslationJa: "出す前にチーズの外皮を切り落として。",
    collocations: ["lemon rind", "cheese rind", "cut off the rind"],
    mnemonic: "かたい外皮。りんごのような薄い皮は skin、むいた皮は peel。",
    relatedWords: ["peel", "skin", "cheese"],
  },
  {
    id: "roller",
    word: "roller",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ローラー、転がす筒", "ヘアカーラー"],
    pronunciation: "/ˈroʊlər/",
    exampleSentence: "He painted the wall with a roller.",
    exampleTranslationJa: "彼はローラーで壁を塗った。",
    collocations: ["a paint roller", "a road roller", "hair rollers"],
    mnemonic: "roll(転がる)+ -er。転がして塗る、ならす、巻く道具。",
    relatedWords: ["paint", "wheel", "cylinder"],
  },
]
