import type { VocabularyEntry } from '../types'

// 増補 第3弾。体・症状・医療。病院で言えないと困る語と、体の部位を細かく入れる。
export const plus03: VocabularyEntry[] = [
  {
    id: "jaw",
    word: "jaw",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["あご(骨格としての)"],
    pronunciation: "/dʒɔː/",
    exampleSentence: "He broke his jaw in the accident.",
    exampleTranslationJa: "彼はその事故であごの骨を折った。",
    collocations: ["a broken jaw", "clench your jaw", "your jaw drops"],
    mnemonic: "あごの骨全体。とがった先だけを指すのは chin。驚くと Your jaw drops.(あごが落ちる)。",
    relatedWords: ["chin", "bone", "mouth"],
  },
  {
    id: "chin",
    word: "chin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["あご先"],
    pronunciation: "/tʃɪn/",
    exampleSentence: "She rested her chin on her hands.",
    exampleTranslationJa: "彼女は両手にあごをのせた。",
    collocations: ["a pointed chin", "keep your chin up", "rest your chin"],
    mnemonic: "Keep your chin up. は「あごを上げて」＝「元気を出して」。",
    relatedWords: ["jaw", "face", "cheek"],
  },
  {
    id: "forehead",
    word: "forehead",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["額(ひたい)"],
    pronunciation: "/ˈfɔːrhed/",
    exampleSentence: "She put a hand on the child's forehead to check for fever.",
    exampleTranslationJa: "彼女は熱を見ようと子どもの額に手をあてた。",
    collocations: ["wipe your forehead", "a high forehead", "a wrinkled forehead"],
    wordFormation: "fore-(前)+ head(頭)。「頭の前面」。",
    mnemonic: "fore(前)+ head(頭)。熱をみるとき最初に手をあてる場所。",
    relatedWords: ["brow", "face", "temple"],
  },
  {
    id: "eyebrow",
    word: "eyebrow",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["まゆ毛"],
    pronunciation: "/ˈaɪbraʊ/",
    exampleSentence: "He raised an eyebrow at her answer.",
    exampleTranslationJa: "彼は彼女の答えに片方のまゆを上げた。",
    collocations: ["raise an eyebrow", "thick eyebrows", "pluck your eyebrows"],
    mnemonic: "raise an eyebrow で「意外そうな顔をする」。驚きと疑いのしぐさ。",
    relatedWords: ["eyelash", "eye", "brow"],
  },
  {
    id: "eyelid",
    word: "eyelid",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["まぶた"],
    pronunciation: "/ˈaɪlɪd/",
    exampleSentence: "Her eyelids grew heavy during the lecture.",
    exampleTranslationJa: "講義の間、彼女のまぶたは重くなった。",
    collocations: ["heavy eyelids", "close your eyelids", "not bat an eyelid"],
    wordFormation: "eye(目)+ lid(ふた)。「目のふた」。",
    mnemonic: "eye(目)の lid(ふた)。not bat an eyelid は「まばたきもしない＝平然としている」。",
    relatedWords: ["eyelash", "blink", "eye"],
  },
  {
    id: "eyelash",
    word: "eyelash",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["まつ毛"],
    pronunciation: "/ˈaɪlæʃ/",
    exampleSentence: "An eyelash fell into her eye.",
    exampleTranslationJa: "まつ毛が一本、彼女の目に入った。",
    collocations: ["long eyelashes", "false eyelashes"],
    wordFormation: "eye(目)+ lash(むち・細い毛)。",
    mnemonic: "lash はむちのように細く伸びるもの。目のふちの細い毛。",
    relatedWords: ["eyebrow", "eyelid", "eye"],
  },
  {
    id: "nostril",
    word: "nostril",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["鼻の穴"],
    pronunciation: "/ˈnɑːstrəl/",
    exampleSentence: "Breathe in slowly through both nostrils.",
    exampleTranslationJa: "両方の鼻の穴からゆっくり息を吸ってください。",
    collocations: ["through your nostrils", "flared nostrils"],
    etymology: "古英語 nosu(鼻)+ thyrel(穴)。「鼻の穴」そのもの。",
    mnemonic: "nose(鼻)+ 古語 thyrel(穴)。語源がそのまま意味。",
    relatedWords: ["nose", "breathe", "sniff"],
  },
  {
    id: "gum",
    word: "gum",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["歯ぐき", "チューインガム", "樹脂、ゴムのり"],
    pronunciation: "/ɡʌm/",
    exampleSentence: "His gums bled when he brushed his teeth.",
    exampleTranslationJa: "歯を磨くと彼の歯ぐきから血が出た。",
    collocations: ["bleeding gums", "chewing gum", "gum disease"],
    mnemonic: "歯ぐきもガムも同じ gum。歯ぐきはふつう複数形 gums。",
    relatedWords: ["tooth", "chew", "dental"],
  },
  {
    id: "tonsil",
    word: "tonsil",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["扁桃腺"],
    pronunciation: "/ˈtɑːnsl/",
    exampleSentence: "She had her tonsils removed as a child.",
    exampleTranslationJa: "彼女は子どものころ扁桃腺を取った。",
    collocations: ["swollen tonsils", "remove your tonsils", "tonsil surgery"],
    mnemonic: "のどの奥の左右に一つずつ。ふつう複数形 tonsils で言う。",
    relatedWords: ["throat", "swollen", "infection"],
  },
  {
    id: "collarbone",
    word: "collarbone",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["鎖骨"],
    pronunciation: "/ˈkɑːlərboʊn/",
    exampleSentence: "He fractured his collarbone falling off his bike.",
    exampleTranslationJa: "彼は自転車から落ちて鎖骨を折った。",
    collocations: ["break your collarbone", "a fractured collarbone"],
    wordFormation: "collar(えり)+ bone(骨)。えりの当たる位置の骨。",
    mnemonic: "シャツのえり(collar)が当たる場所の骨。医学用語は clavicle。",
    relatedWords: ["shoulder", "bone", "fracture"],
  },
  {
    id: "fingernail",
    word: "fingernail",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(手の)つめ"],
    pronunciation: "/ˈfɪŋɡərneɪl/",
    exampleSentence: "He bites his fingernails when he is nervous.",
    exampleTranslationJa: "彼は緊張すると爪をかむ。",
    collocations: ["bite your fingernails", "cut your fingernails"],
    wordFormation: "finger(指)+ nail(つめ)。足のつめは toenail。",
    mnemonic: "nail は「くぎ」でもあり「つめ」でもある。指のほうが fingernail。",
    relatedWords: ["nail", "finger", "toenail"],
  },
  {
    id: "waist",
    word: "waist",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["腰、ウエスト(胴のくびれ)"],
    pronunciation: "/weɪst/",
    exampleSentence: "The water came up to his waist.",
    exampleTranslationJa: "水は彼の腰まで来ていた。",
    collocations: ["a slim waist", "around the waist", "waist measurement"],
    mnemonic: "むだ waste と同音。腰まわりのいちばん細い所で、hip(尻の張り)とは別。",
    relatedWords: ["hip", "belt", "body"],
  },
  {
    id: "thigh",
    word: "thigh",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["太もも"],
    pronunciation: "/θaɪ/",
    exampleSentence: "He pulled a muscle in his left thigh.",
    exampleTranslationJa: "彼は左の太ももの筋を痛めた。",
    collocations: ["inner thigh", "thigh muscles", "a chicken thigh"],
    mnemonic: "高い high と韻を踏む /θaɪ/。鶏のもも肉も chicken thigh。",
    relatedWords: ["knee", "leg", "muscle"],
  },
  {
    id: "shin",
    word: "shin",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["すね"],
    pronunciation: "/ʃɪn/",
    exampleSentence: "He kicked me in the shin by accident.",
    exampleTranslationJa: "彼はうっかり私のすねを蹴った。",
    collocations: ["kick in the shin", "shin guards", "a bruised shin"],
    mnemonic: "サッカーの脛あては shin guards。骨が皮のすぐ下にあるので当たると痛い。",
    relatedWords: ["knee", "ankle", "leg"],
  },
  {
    id: "rib",
    word: "rib",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["あばら骨、肋骨", "(料理の)スペアリブ"],
    pronunciation: "/rɪb/",
    exampleSentence: "She cracked a rib in the fall.",
    exampleTranslationJa: "彼女は転んであばら骨にひびを入れた。",
    collocations: ["break a rib", "the rib cage", "barbecue ribs"],
    mnemonic: "胸を囲むかご状の骨 = the rib cage。料理のリブも同じ骨。",
    relatedWords: ["chest", "bone", "cage"],
  },
  {
    id: "pelvis",
    word: "pelvis",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["骨盤"],
    pronunciation: "/ˈpelvɪs/",
    exampleSentence: "The X-ray showed a crack in the pelvis.",
    exampleTranslationJa: "レントゲンで骨盤にひびが見つかった。",
    collocations: ["a fractured pelvis", "the pelvic bone"],
    etymology: "ラテン語 pelvis(たらい・鉢)から。器の形に似ているため。",
    mnemonic: "ラテン語で「たらい」。器のような形の骨。形容詞は pelvic。",
    relatedWords: ["hip", "bone", "spine"],
  },
  {
    id: "tendon",
    word: "tendon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["腱(けん)"],
    pronunciation: "/ˈtendən/",
    exampleSentence: "He tore a tendon in his shoulder.",
    exampleTranslationJa: "彼は肩の腱を断裂した。",
    collocations: ["the Achilles tendon", "tear a tendon", "a torn tendon"],
    etymology: "ラテン語 tendere(引き伸ばす)から。tense・extend と同語根。",
    mnemonic: "筋肉を骨に引っぱってつなぐひも。tense(張った)と同語根。",
    relatedWords: ["muscle", "ligament", "bone"],
  },
  {
    id: "ligament",
    word: "ligament",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["靭帯(じんたい)"],
    pronunciation: "/ˈlɪɡəmənt/",
    exampleSentence: "She tore a ligament in her knee playing football.",
    exampleTranslationJa: "彼女はサッカーで膝の靭帯を断裂した。",
    collocations: ["a torn ligament", "knee ligaments", "ligament damage"],
    etymology: "ラテン語 ligare(縛る)から。league や oblige と同語根。",
    mnemonic: "骨と骨を縛る(ligare)ひも。腱 tendon は骨と筋肉をつなぐほう。",
    relatedWords: ["tendon", "joint", "knee"],
  },
  {
    id: "cartilage",
    word: "cartilage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["軟骨"],
    pronunciation: "/ˈkɑːrtəlɪdʒ/",
    exampleSentence: "The cartilage in his knee had worn away.",
    exampleTranslationJa: "彼の膝の軟骨はすり減っていた。",
    collocations: ["knee cartilage", "damaged cartilage", "worn cartilage"],
    mnemonic: "骨と骨の間のクッション。耳と鼻の先も軟骨でできている。",
    relatedWords: ["bone", "joint", "knee"],
  },
  {
    id: "marrow",
    word: "marrow",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["骨髄", "(英)西洋かぼちゃ"],
    pronunciation: "/ˈmæroʊ/",
    exampleSentence: "He received a bone marrow transplant.",
    exampleTranslationJa: "彼は骨髄移植を受けた。",
    collocations: ["bone marrow", "a marrow transplant", "chilled to the marrow"],
    mnemonic: "骨の芯。chilled to the marrow は「骨の髄まで冷える」。",
    relatedWords: ["bone", "blood", "transplant"],
  },
  {
    id: "artery",
    word: "artery",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["動脈", "(交通の)幹線"],
    pronunciation: "/ˈɑːrtəri/",
    exampleSentence: "Fat can build up inside the arteries.",
    exampleTranslationJa: "動脈の内側には脂肪がたまることがある。",
    collocations: ["a blocked artery", "the main artery", "clogged arteries"],
    mnemonic: "心臓から出ていくのが artery、戻るのが vein。街の大通りも artery。",
    relatedWords: ["vein", "blood", "heart"],
  },
  {
    id: "capillary",
    word: "capillary",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["毛細血管"],
    pronunciation: "/ˈkæpəleri/",
    exampleSentence: "Oxygen passes into the tissue through the capillaries.",
    exampleTranslationJa: "酸素は毛細血管を通って組織に入る。",
    collocations: ["burst capillaries", "capillary walls"],
    etymology: "ラテン語 capillus(髪の毛)から。髪ほど細い管。",
    mnemonic: "capillus は「髪の毛」。髪の毛ほど細い血管。",
    relatedWords: ["artery", "vein", "blood"],
  },
  {
    id: "intestine",
    word: "intestine",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["腸"],
    pronunciation: "/ɪnˈtestɪn/",
    exampleSentence: "Nutrients are absorbed in the small intestine.",
    exampleTranslationJa: "栄養は小腸で吸収される。",
    collocations: ["the small intestine", "the large intestine", "intestinal problems"],
    mnemonic: "in-(内)から。体の内側の管。小腸 small / 大腸 large で分ける。",
    relatedWords: ["stomach", "bowel", "digest"],
  },
  {
    id: "bowel",
    word: "bowel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["腸、大腸"],
    pronunciation: "/ˈbaʊəl/",
    exampleSentence: "Fibre helps keep the bowels healthy.",
    exampleTranslationJa: "食物繊維は腸を健康に保つのに役立つ。",
    collocations: ["bowel movement", "bowel cancer", "empty the bowels"],
    mnemonic: "intestine の日常語。健康診断では bowel のほうをよく使う。",
    relatedWords: ["intestine", "digest", "stomach"],
  },
  {
    id: "bladder",
    word: "bladder",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["膀胱(ぼうこう)"],
    pronunciation: "/ˈblædər/",
    exampleSentence: "Coffee can irritate the bladder.",
    exampleTranslationJa: "コーヒーは膀胱を刺激することがある。",
    collocations: ["a full bladder", "bladder infection", "empty your bladder"],
    mnemonic: "ふくらむ袋。ボールの中のゴム袋も bladder と呼ぶ。",
    relatedWords: ["kidney", "urine", "organ"],
  },
  {
    id: "womb",
    word: "womb",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["子宮"],
    pronunciation: "/wuːm/",
    exampleSentence: "The baby moves inside the womb.",
    exampleTranslationJa: "赤ん坊は子宮の中で動く。",
    collocations: ["in the womb", "leave the womb"],
    mnemonic: "b は読まない /wuːm/。医学用語は uterus、日常語が womb。",
    relatedWords: ["pregnancy", "birth", "uterus"],
  },
  {
    id: "gland",
    word: "gland",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["腺(せん)"],
    pronunciation: "/ɡlænd/",
    exampleSentence: "The glands in his neck were swollen.",
    exampleTranslationJa: "彼の首の腺が腫れていた。",
    collocations: ["swollen glands", "sweat glands", "the thyroid gland"],
    mnemonic: "汗や唾液やホルモンを出す小さな器官。風邪で腫れるのは首の gland。",
    relatedWords: ["hormone", "swollen", "thyroid"],
  },
  {
    id: "thyroid",
    word: "thyroid",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["甲状腺"],
    pronunciation: "/ˈθaɪrɔɪd/",
    exampleSentence: "An underactive thyroid can make you feel tired.",
    exampleTranslationJa: "甲状腺の働きが弱いと疲れやすくなることがある。",
    collocations: ["the thyroid gland", "an overactive thyroid", "thyroid hormone"],
    mnemonic: "のどぼとけの下にある蝶の形の腺。代謝の速さを決める。",
    relatedWords: ["gland", "hormone", "neck"],
  },
  {
    id: "pancreas",
    word: "pancreas",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["すい臓"],
    pronunciation: "/ˈpæŋkriəs/",
    exampleSentence: "The pancreas produces insulin.",
    exampleTranslationJa: "すい臓はインスリンを作る。",
    collocations: ["the pancreas produces", "pancreatic cancer"],
    mnemonic: "インスリンを出す臓器。働きが落ちると diabetes(糖尿病)になる。",
    relatedWords: ["insulin", "diabetes", "organ"],
  },
  {
    id: "sneeze",
    word: "sneeze",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["くしゃみをする", "くしゃみ"],
    pronunciation: "/sniːz/",
    exampleSentence: "Cover your mouth when you sneeze.",
    exampleTranslationJa: "くしゃみをするときは口をおおいなさい。",
    collocations: ["sneeze into your elbow", "a loud sneeze", "nothing to sneeze at"],
    mnemonic: "英語ではくしゃみのあとに Bless you. と声をかける習慣がある。",
    relatedWords: ["cough", "nose", "allergy"],
  },
  {
    id: "cough",
    word: "cough",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["せきをする", "せき"],
    pronunciation: "/kɔːf/",
    exampleSentence: "He has had a dry cough for a week.",
    exampleTranslationJa: "彼は1週間、から咳が続いている。",
    collocations: ["a bad cough", "cough medicine", "a dry cough"],
    mnemonic: "つづり -ough を /ɔːf/ と読む。through(スルー)、though(ゾウ)とは別の読み。",
    relatedWords: ["sneeze", "throat", "cold"],
  },
  {
    id: "sniff",
    word: "sniff",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["鼻をすする", "においをかぐ"],
    pronunciation: "/snɪf/",
    exampleSentence: "The dog sniffed at the bag suspiciously.",
    exampleTranslationJa: "犬はそのかばんを疑わしげにくんくんかいだ。",
    collocations: ["sniff the air", "sniff at something", "a loud sniff"],
    mnemonic: "鼻から短く息を吸う音。犬がにおいをかぐのも、鼻水をすするのも sniff。",
    relatedWords: ["smell", "nose", "breathe"],
  },
  {
    id: "yawn",
    word: "yawn",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["あくびをする", "あくび"],
    pronunciation: "/jɔːn/",
    exampleSentence: "She yawned and looked at the clock.",
    exampleTranslationJa: "彼女はあくびをして時計を見た。",
    collocations: ["stifle a yawn", "yawn widely", "a big yawn"],
    mnemonic: "眠いときも退屈なときも yawn。つまらない話そのものを a yawn とも言う。",
    relatedWords: ["sleepy", "tired", "bored"],
  },
  {
    id: "hiccup",
    word: "hiccup",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["しゃっくり", "小さな支障"],
    pronunciation: "/ˈhɪkʌp/",
    exampleSentence: "There was a small hiccup in the schedule.",
    exampleTranslationJa: "予定に小さな支障が出た。",
    collocations: ["get the hiccups", "a minor hiccup", "cure hiccups"],
    mnemonic: "音をそのまま写した語。計画の「ちょっとしたつまずき」にも使う。",
    relatedWords: ["breath", "spasm", "setback"],
  },
  {
    id: "shiver",
    word: "shiver",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(寒さ・恐怖で)震える", "身震い"],
    pronunciation: "/ˈʃɪvər/",
    exampleSentence: "She shivered in the cold wind.",
    exampleTranslationJa: "彼女は冷たい風に震えた。",
    collocations: ["shiver with cold", "send shivers down your spine"],
    mnemonic: "寒さや恐怖で体が小刻みに揺れる。怒りで震えるのは tremble。",
    relatedWords: ["tremble", "shake", "cold"],
  },
  {
    id: "sweat",
    word: "sweat",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["汗", "汗をかく"],
    pronunciation: "/swet/",
    exampleSentence: "He was sweating after the long climb.",
    exampleTranslationJa: "彼は長い登りのあと汗をかいていた。",
    collocations: ["break into a sweat", "sweat heavily", "no sweat"],
    mnemonic: "発音は /swet/ で sweet とは別。No sweat. は「お安い御用」。",
    relatedWords: ["perspire", "heat", "gland"],
  },
  {
    id: "itch",
    word: "itch",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["かゆい", "かゆみ", "うずうずする"],
    pronunciation: "/ɪtʃ/",
    exampleSentence: "The wool sweater makes my arms itch.",
    exampleTranslationJa: "そのウールのセーターは腕がかゆくなる。",
    collocations: ["scratch an itch", "itch to do", "an itchy rash"],
    mnemonic: "be itching to do で「〜したくてうずうずする」。かゆみと同じ落ち着かなさ。",
    relatedWords: ["scratch", "rash", "skin"],
  },
  {
    id: "ache",
    word: "ache",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(鈍い)痛み", "うずく、痛む"],
    pronunciation: "/eɪk/",
    exampleSentence: "My legs ached after the hike.",
    exampleTranslationJa: "ハイキングのあと脚がうずいた。",
    collocations: ["a stomach ache", "aches and pains", "my head aches"],
    mnemonic: "ch を /k/ と読む /eɪk/。鋭い痛みが pain、じんわり続くのが ache。",
    relatedWords: ["pain", "sore", "hurt"],
  },
  {
    id: "sting",
    word: "sting",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["刺す、ひりひりさせる", "刺し傷"],
    pronunciation: "/stɪŋ/",
    exampleSentence: "Jellyfish can sting even when they are dead.",
    exampleTranslationJa: "クラゲは死んでいても刺すことがある。",
    collocations: ["a bee sting", "sting your eyes", "the sting of defeat"],
    mnemonic: "活用は sting-stung-stung。虫が刺すのも、傷口がひりひりするのも同じ。",
    relatedWords: ["bite", "bee", "pain"],
  },
  {
    id: "swell",
    word: "swell",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["腫れる、ふくらむ", "(数が)増大する"],
    pronunciation: "/swel/",
    exampleSentence: "His ankle began to swell after the fall.",
    exampleTranslationJa: "転んだあと彼の足首は腫れ始めた。",
    collocations: ["swell up", "the crowd swelled", "a swollen ankle"],
    mnemonic: "活用は swell-swelled-swollen。形容詞は swollen(腫れた)。",
    relatedWords: ["swollen", "expand", "grow"],
  },
  {
    id: "bruise",
    word: "bruise",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["あざ、打ち身", "あざができる"],
    pronunciation: "/bruːz/",
    exampleSentence: "She had a large bruise on her knee.",
    exampleTranslationJa: "彼女の膝には大きなあざがあった。",
    collocations: ["a nasty bruise", "bruise easily", "cuts and bruises"],
    mnemonic: "発音は /bruːz/。皮膚は切れずに内側で出血して青黒くなる。",
    relatedWords: ["injury", "wound", "swell"],
  },
  {
    id: "limp",
    word: "limp",
    level: "B2",
    partOfSpeech: "動詞・名詞・形容詞",
    meaningsJa: ["足を引きずって歩く", "びっこ", "ぐったりした"],
    pronunciation: "/lɪmp/",
    exampleSentence: "He limped off the field after the tackle.",
    exampleTranslationJa: "彼はタックルのあと足を引きずってフィールドを出た。",
    collocations: ["walk with a limp", "limp along", "go limp"],
    mnemonic: "歩き方の名詞にも動詞にもなる。形容詞では「力が抜けてぐにゃりとした」。",
    relatedWords: ["injury", "walk", "leg"],
  },
  {
    id: "faint",
    word: "faint",
    level: "B2",
    partOfSpeech: "動詞・形容詞",
    meaningsJa: ["気を失う", "かすかな、ぼんやりした"],
    pronunciation: "/feɪnt/",
    exampleSentence: "She fainted in the heat of the crowded hall.",
    exampleTranslationJa: "彼女は混み合ったホールの暑さで気を失った。",
    collocations: ["faint from hunger", "a faint smell", "not have the faintest idea"],
    mnemonic: "「意識がかすむ」から動詞は「気絶する」、形容詞は「かすかな」。",
    relatedWords: ["dizzy", "collapse", "dim"],
  },
  {
    id: "scar",
    word: "scar",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["傷あと", "心の傷", "傷あとを残す"],
    pronunciation: "/skɑːr/",
    exampleSentence: "The operation left a small scar on his chest.",
    exampleTranslationJa: "その手術は彼の胸に小さな傷あとを残した。",
    collocations: ["leave a scar", "emotional scars", "a scar on the face"],
    mnemonic: "治ったあとに残るしるし。心に残るものは emotional scars。",
    relatedWords: ["wound", "heal", "mark"],
  },
  {
    id: "blister",
    word: "blister",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["水ぶくれ、まめ", "水ぶくれができる"],
    pronunciation: "/ˈblɪstər/",
    exampleSentence: "New shoes gave her blisters on both heels.",
    exampleTranslationJa: "新しい靴のせいで彼女は両かかとにまめができた。",
    collocations: ["get a blister", "a blister on your heel", "burst a blister"],
    mnemonic: "皮膚の下に液がたまってふくらんだもの。靴ずれもやけども blister。",
    relatedWords: ["burn", "skin", "swell"],
  },
  {
    id: "rash",
    word: "rash",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["発疹、湿疹", "軽率な、向こう見ずな"],
    pronunciation: "/ræʃ/",
    exampleSentence: "The medicine gave him a rash on his neck.",
    exampleTranslationJa: "その薬で彼の首に発疹が出た。",
    collocations: ["come out in a rash", "an itchy rash", "a rash decision"],
    mnemonic: "皮膚にぱっと広がるもの → 考えずにぱっと動く「軽率な」も同じ語。",
    relatedWords: ["itch", "skin", "allergy"],
  },
  {
    id: "ulcer",
    word: "ulcer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["潰瘍(かいよう)"],
    pronunciation: "/ˈʌlsər/",
    exampleSentence: "Stress can make a stomach ulcer worse.",
    exampleTranslationJa: "ストレスは胃潰瘍を悪化させることがある。",
    collocations: ["a stomach ulcer", "a mouth ulcer", "develop an ulcer"],
    mnemonic: "粘膜がえぐれて治らない傷。口内炎も a mouth ulcer。",
    relatedWords: ["stomach", "wound", "inflammation"],
  },
  {
    id: "nauseous",
    word: "nauseous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["吐き気がする、むかつく"],
    pronunciation: "/ˈnɔːʃəs/",
    exampleSentence: "The smell of petrol makes me nauseous.",
    exampleTranslationJa: "ガソリンのにおいで吐き気がする。",
    collocations: ["feel nauseous", "become nauseous"],
    etymology: "ギリシャ語 naus(船)から。船酔いが語のもと。",
    mnemonic: "naus は「船」。船酔いの気持ち悪さがそのまま語になった。",
    relatedWords: ["sick", "vomit", "dizzy"],
  },
  {
    id: "sore",
    word: "sore",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["ひりひり痛む、はれて痛い", "傷、ただれ"],
    pronunciation: "/sɔːr/",
    exampleSentence: "I have a sore throat and a slight fever.",
    exampleTranslationJa: "のどが痛くて微熱がある。",
    collocations: ["a sore throat", "sore muscles", "a sore point"],
    mnemonic: "触ると痛い状態。a sore point は「触れられたくない話題」。",
    relatedWords: ["ache", "pain", "tender"],
  },
  {
    id: "numb",
    word: "numb",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["感覚がない、しびれた", "感覚を失わせる"],
    pronunciation: "/nʌm/",
    exampleSentence: "My fingers went numb in the cold.",
    exampleTranslationJa: "寒さで指の感覚がなくなった。",
    collocations: ["go numb", "numb with cold", "numb the pain"],
    mnemonic: "b は読まない /nʌm/。痛みも感情も感じなくなる状態。",
    relatedWords: ["feel", "cold", "paralyse"],
  },
  {
    id: "swollen",
    word: "swollen",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["腫れた、ふくれた"],
    pronunciation: "/ˈswoʊlən/",
    exampleSentence: "Her eyes were swollen from crying.",
    exampleTranslationJa: "彼女の目は泣いて腫れていた。",
    collocations: ["a swollen ankle", "swollen glands", "a swollen river"],
    mnemonic: "swell(腫れる)の過去分詞が形容詞に。増水した川も a swollen river。",
    relatedWords: ["swell", "puffy", "inflammation"],
  },
  {
    id: "feverish",
    word: "feverish",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["熱っぽい", "熱に浮かされたような、あわただしい"],
    pronunciation: "/ˈfiːvərɪʃ/",
    exampleSentence: "He felt feverish and went home early.",
    exampleTranslationJa: "彼は熱っぽさを感じて早退した。",
    collocations: ["feel feverish", "feverish activity", "feverish excitement"],
    wordFormation: "fever(熱)+ -ish(〜っぽい)。",
    mnemonic: "熱があるときの落ち着かなさ。仕事ぶりが feverish なら「熱に浮かされたような忙しさ」。",
    relatedWords: ["fever", "temperature", "ill"],
  },
  {
    id: "exhausted",
    word: "exhausted",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["疲れ果てた", "使い果たされた"],
    pronunciation: "/ɪɡˈzɔːstɪd/",
    exampleSentence: "After the night shift she was completely exhausted.",
    exampleTranslationJa: "夜勤のあと彼女は完全に疲れ果てていた。",
    collocations: ["utterly exhausted", "exhausted supplies", "feel exhausted"],
    wordFormation: "ex-(外へ)+ haurire(くみ出す)。中身をすっかりくみ出した状態。",
    mnemonic: "井戸の水をくみ尽くすイメージ。体力も資源も「空っぽ」。",
    relatedWords: ["tired", "worn out", "drain"],
  },
  {
    id: "breathless",
    word: "breathless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["息を切らした", "息をのむような"],
    pronunciation: "/ˈbreθləs/",
    exampleSentence: "He arrived breathless at the top of the stairs.",
    exampleTranslationJa: "彼は階段を上りきって息を切らしていた。",
    collocations: ["leave you breathless", "breathless with excitement"],
    wordFormation: "breath(息)+ -less(ない)。",
    mnemonic: "息が「ない」。運動で切らす場合も、感動で息をのむ場合も使う。",
    relatedWords: ["breath", "pant", "gasp"],
  },
  {
    id: "drowsy",
    word: "drowsy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["眠気を催した、うとうとする"],
    pronunciation: "/ˈdraʊzi/",
    exampleSentence: "This medicine may make you drowsy.",
    exampleTranslationJa: "この薬は眠気を催すことがあります。",
    collocations: ["feel drowsy", "make you drowsy", "a drowsy afternoon"],
    mnemonic: "薬の注意書きの定番。sleepy より「頭がぼんやりする」感じが強い。",
    relatedWords: ["sleepy", "tired", "yawn"],
  },
  {
    id: "contagious",
    word: "contagious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["接触で伝染する", "(笑いなどが)うつりやすい"],
    pronunciation: "/kənˈteɪdʒəs/",
    exampleSentence: "Chickenpox is highly contagious.",
    exampleTranslationJa: "水ぼうそうは非常に伝染しやすい。",
    collocations: ["highly contagious", "a contagious disease", "contagious laughter"],
    etymology: "ラテン語 con-(共に)+ tangere(触れる)。contact と同語根。",
    mnemonic: "contact(接触)と同語根。触れて広がるから contagious。",
    relatedWords: ["infectious", "spread", "disease"],
  },
  {
    id: "infectious",
    word: "infectious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感染性の", "(感情が)人にうつる"],
    pronunciation: "/ɪnˈfekʃəs/",
    exampleSentence: "Her enthusiasm was infectious.",
    exampleTranslationJa: "彼女の熱意は周りにうつった。",
    collocations: ["an infectious disease", "infectious enthusiasm"],
    mnemonic: "空気や水を通じても広がるのが infectious、触れて広がるのが contagious。",
    relatedWords: ["contagious", "infection", "virus"],
  },
  {
    id: "sterile",
    word: "sterile",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無菌の、殺菌した", "不妊の", "生気のない"],
    pronunciation: "/ˈsterəl/",
    exampleSentence: "The wound was covered with a sterile dressing.",
    exampleTranslationJa: "傷は滅菌したガーゼで覆われた。",
    collocations: ["a sterile needle", "sterile conditions", "a sterile debate"],
    mnemonic: "菌もいない、実も生まれない。「何も生まれない」が共通の芯。",
    relatedWords: ["germ", "clean", "sterilise"],
  },
  {
    id: "germ",
    word: "germ",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["細菌、ばい菌", "(考えの)芽、始まり"],
    pronunciation: "/dʒɜːrm/",
    exampleSentence: "Washing your hands kills most germs.",
    exampleTranslationJa: "手を洗えばほとんどのばい菌は死ぬ。",
    collocations: ["spread germs", "kill germs", "the germ of an idea"],
    mnemonic: "ラテン語で「芽」。ばい菌も、考えの芽も、そこから育つもの。",
    relatedWords: ["bacteria", "virus", "hygiene"],
  },
  {
    id: "hygiene",
    word: "hygiene",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["衛生、衛生管理"],
    pronunciation: "/ˈhaɪdʒiːn/",
    exampleSentence: "Food hygiene rules are strict in this kitchen.",
    exampleTranslationJa: "この厨房では食品衛生の規則が厳しい。",
    collocations: ["personal hygiene", "food hygiene", "poor hygiene"],
    etymology: "ギリシャ神話の健康の女神 Hygieia から。",
    mnemonic: "健康の女神ヒュギエイアの名。清潔を保って病気を防ぐこと全般。",
    relatedWords: ["sanitation", "clean", "health"],
  },
  {
    id: "sanitation",
    word: "sanitation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["公衆衛生設備、下水処理"],
    pronunciation: "/ˌsænɪˈteɪʃn/",
    exampleSentence: "Millions of people still lack basic sanitation.",
    exampleTranslationJa: "何百万もの人がいまだに基本的な衛生設備を欠いている。",
    collocations: ["basic sanitation", "poor sanitation", "water and sanitation"],
    mnemonic: "hygiene が個人の清潔、sanitation は上下水道など社会の仕組み。",
    relatedWords: ["hygiene", "sewage", "water"],
  },
  {
    id: "immunity",
    word: "immunity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["免疫", "(訴追などの)免除"],
    pronunciation: "/ɪˈmjuːnəti/",
    exampleSentence: "The vaccine gives immunity for about a year.",
    exampleTranslationJa: "そのワクチンは約1年の免疫を与える。",
    collocations: ["build immunity", "natural immunity", "diplomatic immunity"],
    mnemonic: "「義務や害を免れる」が芯。病気も、法の追及も免れる。",
    relatedWords: ["immune", "vaccine", "resistance"],
  },
  {
    id: "allergy",
    word: "allergy",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["アレルギー"],
    pronunciation: "/ˈælərdʒi/",
    exampleSentence: "She has a serious allergy to peanuts.",
    exampleTranslationJa: "彼女はピーナッツに重いアレルギーがある。",
    collocations: ["an allergy to", "a food allergy", "a pollen allergy"],
    mnemonic: "形容詞は allergic。be allergic to ... の形で使うほうが多い。",
    relatedWords: ["allergic", "reaction", "rash"],
  },
  {
    id: "asthma",
    word: "asthma",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ぜんそく"],
    pronunciation: "/ˈæzmə/",
    exampleSentence: "He carries an inhaler because of his asthma.",
    exampleTranslationJa: "彼はぜんそくのため吸入器を持ち歩いている。",
    collocations: ["an asthma attack", "suffer from asthma", "asthma medication"],
    mnemonic: "th は読まない /ˈæzmə/。つづりと音の差が大きい語。",
    relatedWords: ["breath", "inhaler", "lung"],
  },
  {
    id: "diabetes",
    word: "diabetes",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["糖尿病"],
    pronunciation: "/ˌdaɪəˈbiːtiːz/",
    exampleSentence: "Type 2 diabetes is linked to diet and exercise.",
    exampleTranslationJa: "2型糖尿病は食事と運動に関係がある。",
    collocations: ["type 2 diabetes", "develop diabetes", "manage diabetes"],
    mnemonic: "形容詞・名詞は diabetic。すい臓のインスリンがうまく働かない病気。",
    relatedWords: ["insulin", "pancreas", "sugar"],
  },
  {
    id: "tumour",
    word: "tumour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["腫瘍(しゅよう)"],
    pronunciation: "/ˈtuːmər/",
    exampleSentence: "The tumour turned out to be benign.",
    exampleTranslationJa: "その腫瘍は良性だと分かった。",
    collocations: ["a brain tumour", "a benign tumour", "remove a tumour"],
    mnemonic: "米つづりは tumor。良性が benign、悪性が malignant。",
    relatedWords: ["cancer", "growth", "benign"],
  },
  {
    id: "inflammation",
    word: "inflammation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["炎症"],
    pronunciation: "/ˌɪnfləˈmeɪʃn/",
    exampleSentence: "The cream reduces inflammation and pain.",
    exampleTranslationJa: "そのクリームは炎症と痛みを和らげる。",
    collocations: ["reduce inflammation", "chronic inflammation", "cause inflammation"],
    wordFormation: "flame(炎)と同語根。赤く熱を持つ状態から。",
    mnemonic: "flame(炎)が語根。赤く熱を持って腫れるから「炎症」。",
    relatedWords: ["swelling", "flame", "infection"],
  },
  {
    id: "fracture",
    word: "fracture",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["骨折、ひび", "骨折する"],
    pronunciation: "/ˈfræktʃər/",
    exampleSentence: "The X-ray showed a hairline fracture.",
    exampleTranslationJa: "レントゲンで細いひびが見つかった。",
    collocations: ["a hairline fracture", "suffer a fracture", "fracture your wrist"],
    etymology: "ラテン語 frangere(壊す)から。fragile・fragment と同語根。",
    mnemonic: "fragile(こわれやすい)・fragment(かけら)と同じ語根。折れること。",
    relatedWords: ["break", "bone", "crack"],
  },
  {
    id: "sprain",
    word: "sprain",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ねんざする", "ねんざ"],
    pronunciation: "/spreɪn/",
    exampleSentence: "She sprained her ankle on the stairs.",
    exampleTranslationJa: "彼女は階段で足首をねんざした。",
    collocations: ["sprain your ankle", "a bad sprain", "a sprained wrist"],
    mnemonic: "骨は折れず靭帯が伸びた状態。折れたら fracture、伸びたら sprain。",
    relatedWords: ["ankle", "ligament", "twist"],
  },
  {
    id: "dosage",
    word: "dosage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["服用量、投与量"],
    pronunciation: "/ˈdoʊsɪdʒ/",
    exampleSentence: "Do not exceed the recommended dosage.",
    exampleTranslationJa: "推奨される服用量を超えないでください。",
    collocations: ["the recommended dosage", "increase the dosage", "a daily dosage"],
    wordFormation: "dose(一回分)+ -age(量)。",
    mnemonic: "dose は一回分、dosage はその決め方・量全体。薬の箱に必ず書いてある語。",
    relatedWords: ["dose", "medicine", "prescription"],
  },
  {
    id: "capsule",
    word: "capsule",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["カプセル", "(宇宙船の)与圧室"],
    pronunciation: "/ˈkæpsl/",
    exampleSentence: "Take one capsule twice a day with water.",
    exampleTranslationJa: "1日2回、1カプセルを水で飲んでください。",
    collocations: ["take a capsule", "a space capsule", "a time capsule"],
    etymology: "ラテン語 capsa(箱)から。case と同語根。",
    mnemonic: "小さな入れ物。錠剤は tablet、中身が入った殻が capsule。",
    relatedWords: ["tablet", "pill", "medicine"],
  },
  {
    id: "ointment",
    word: "ointment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["軟膏(なんこう)、塗り薬"],
    pronunciation: "/ˈɔɪntmənt/",
    exampleSentence: "Apply the ointment twice a day.",
    exampleTranslationJa: "この軟膏を1日2回塗ってください。",
    collocations: ["apply ointment", "antiseptic ointment", "a fly in the ointment"],
    mnemonic: "a fly in the ointment は「玉にきず」。軟膏にハエ一匹で台無し、から。",
    relatedWords: ["cream", "medicine", "apply"],
  },
  {
    id: "bandage",
    word: "bandage",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["包帯", "包帯を巻く"],
    pronunciation: "/ˈbændɪdʒ/",
    exampleSentence: "The nurse bandaged his arm carefully.",
    exampleTranslationJa: "看護師は彼の腕に丁寧に包帯を巻いた。",
    collocations: ["put on a bandage", "a clean bandage", "bandage a wound"],
    wordFormation: "band(帯)+ -age。細長い帯を巻くもの。",
    mnemonic: "band(帯)を巻く。小さな絆創膏は英で plaster、米で Band-Aid。",
    relatedWords: ["wound", "plaster", "dressing"],
  },
  {
    id: "plaster",
    word: "plaster",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["絆創膏(英)", "しっくい、石こう", "ギプス"],
    pronunciation: "/ˈplæstər/",
    exampleSentence: "She put a plaster on the cut.",
    exampleTranslationJa: "彼女は切り傷に絆創膏を貼った。",
    collocations: ["put on a plaster", "a plaster cast", "plaster the wall"],
    mnemonic: "「塗って固めるもの」が芯。壁のしっくい、骨のギプス、傷の絆創膏。",
    relatedWords: ["bandage", "cast", "wall"],
  },
  {
    id: "stitch",
    word: "stitch",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ひと縫い、縫い目", "(傷の)縫合", "縫う"],
    pronunciation: "/stɪtʃ/",
    exampleSentence: "The cut needed five stitches.",
    exampleTranslationJa: "その切り傷は5針縫う必要があった。",
    collocations: ["put in stitches", "remove the stitches", "a stitch in time"],
    mnemonic: "A stitch in time saves nine.(早めのひと針が九針を省く)＝早めの手当てが肝心。",
    relatedWords: ["sew", "wound", "thread"],
  },
  {
    id: "vaccine",
    word: "vaccine",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ワクチン"],
    pronunciation: "/vækˈsiːn/",
    exampleSentence: "The vaccine was developed in under a year.",
    exampleTranslationJa: "そのワクチンは1年足らずで開発された。",
    collocations: ["develop a vaccine", "a flu vaccine", "a vaccine against"],
    etymology: "ラテン語 vacca(雌牛)から。牛痘を使った最初の種痘に由来。",
    mnemonic: "vacca は「雌牛」。牛の病気を使った最初の種痘が語のもと。",
    relatedWords: ["vaccination", "immunity", "injection"],
  },
  {
    id: "vaccination",
    word: "vaccination",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["予防接種"],
    pronunciation: "/ˌvæksɪˈneɪʃn/",
    exampleSentence: "Vaccination is free for children under five.",
    exampleTranslationJa: "5歳未満の子どもは予防接種が無料だ。",
    collocations: ["a vaccination programme", "get a vaccination", "vaccination rates"],
    mnemonic: "vaccine が「薬そのもの」、vaccination が「打つという行為」。",
    relatedWords: ["vaccine", "immunity", "injection"],
  },
  {
    id: "syringe",
    word: "syringe",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["注射器"],
    pronunciation: "/səˈrɪndʒ/",
    exampleSentence: "He disposed of the used syringe safely.",
    exampleTranslationJa: "彼は使用済みの注射器を安全に処分した。",
    collocations: ["a used syringe", "fill a syringe", "a sterile syringe"],
    mnemonic: "アクセントは後ろ /səˈrɪndʒ/。針(needle)がついた筒のほう。",
    relatedWords: ["needle", "injection", "vaccine"],
  },
  {
    id: "nurse",
    word: "nurse",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["看護師", "看病する", "(考えを)抱き続ける"],
    pronunciation: "/nɜːrs/",
    exampleSentence: "She nursed her father through his illness.",
    exampleTranslationJa: "彼女は父の病気を通して看病した。",
    collocations: ["a nurse practitioner", "nurse a patient", "nurse a grudge"],
    mnemonic: "「養い育てる」が芯。恨みを抱え続けるのも nurse a grudge。",
    relatedWords: ["doctor", "care", "hospital"],
  },
  {
    id: "midwife",
    word: "midwife",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["助産師"],
    pronunciation: "/ˈmɪdwaɪf/",
    exampleSentence: "The midwife arrived just before the birth.",
    exampleTranslationJa: "助産師は出産の直前に到着した。",
    collocations: ["a community midwife", "see a midwife"],
    etymology: "古英語 mid(共に)+ wif(女性)。「産む女性と共にいる人」。",
    mnemonic: "mid(共に)+ wife(女性)。産む人のそばに付き添う人。複数形は midwives。",
    relatedWords: ["birth", "pregnancy", "nurse"],
  },
  {
    id: "stretcher",
    word: "stretcher",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["担架(たんか)"],
    pronunciation: "/ˈstretʃər/",
    exampleSentence: "He was carried off the field on a stretcher.",
    exampleTranslationJa: "彼は担架でフィールドから運び出された。",
    collocations: ["on a stretcher", "carry a stretcher"],
    wordFormation: "stretch(伸ばす)+ -er。布をぴんと張った運搬具。",
    mnemonic: "布を stretch(ぴんと張って)人を寝かせて運ぶ道具。",
    relatedWords: ["ambulance", "carry", "injury"],
  },
  {
    id: "wheelchair",
    word: "wheelchair",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["車いす"],
    pronunciation: "/ˈwiːltʃer/",
    exampleSentence: "The station has ramps for wheelchair users.",
    exampleTranslationJa: "その駅には車いす利用者のためのスロープがある。",
    collocations: ["a wheelchair user", "wheelchair access", "in a wheelchair"],
    wordFormation: "wheel(車輪)+ chair(いす)。",
    mnemonic: "「車いすの人」は a wheelchair user が今の言い方。",
    relatedWords: ["disability", "ramp", "access"],
  },
  {
    id: "crutch",
    word: "crutch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["松葉づえ", "頼りにするもの"],
    pronunciation: "/krʌtʃ/",
    exampleSentence: "He walked on crutches for six weeks.",
    exampleTranslationJa: "彼は6週間、松葉づえで歩いた。",
    collocations: ["on crutches", "a pair of crutches", "an emotional crutch"],
    mnemonic: "ふつう二本一組で複数形 crutches。心の支えを an emotional crutch とも。",
    relatedWords: ["stick", "support", "injury"],
  },
  {
    id: "transplant",
    word: "transplant",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(臓器)移植", "移植する", "(植物を)植え替える"],
    pronunciation: "/ˈtrænsplænt/",
    exampleSentence: "He is waiting for a kidney transplant.",
    exampleTranslationJa: "彼は腎臓移植を待っている。",
    collocations: ["a heart transplant", "a transplant patient", "transplant a tree"],
    wordFormation: "trans-(越えて)+ plant(植える)。「別の場所に植えかえる」。",
    mnemonic: "trans(越えて)+ plant(植える)。木の植え替えと同じ発想で臓器を移す。",
    relatedWords: ["donor", "organ", "surgery"],
  },
  {
    id: "antibiotic",
    word: "antibiotic",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["抗生物質"],
    pronunciation: "/ˌæntibaɪˈɑːtɪk/",
    exampleSentence: "Antibiotics do not work against viruses.",
    exampleTranslationJa: "抗生物質はウイルスには効かない。",
    collocations: ["take antibiotics", "a course of antibiotics", "antibiotic resistance"],
    wordFormation: "anti-(対抗)+ bio(生命)+ -tic。「細菌の生命に対抗するもの」。",
    mnemonic: "anti(対)+ bio(生きもの)。細菌に効き、ウイルスには効かない。",
    relatedWords: ["bacteria", "medicine", "infection"],
  },
  {
    id: "painkiller",
    word: "painkiller",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["鎮痛剤"],
    pronunciation: "/ˈpeɪnkɪlər/",
    exampleSentence: "She took a painkiller for her headache.",
    exampleTranslationJa: "彼女は頭痛のため鎮痛剤を飲んだ。",
    collocations: ["take a painkiller", "strong painkillers", "over-the-counter painkillers"],
    wordFormation: "pain(痛み)+ killer(殺すもの)。",
    mnemonic: "痛み(pain)を殺す(kill)もの。そのままの名前。",
    relatedWords: ["pain", "medicine", "aspirin"],
  },
  {
    id: "aspirin",
    word: "aspirin",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["アスピリン"],
    pronunciation: "/ˈæsprɪn/",
    exampleSentence: "Take two aspirin and rest.",
    exampleTranslationJa: "アスピリンを2錠飲んで休みなさい。",
    collocations: ["take aspirin", "a low-dose aspirin"],
    mnemonic: "もとは商標名。今はふつうの名詞として使う。複数形も aspirin のことが多い。",
    relatedWords: ["painkiller", "medicine", "tablet"],
  },
  {
    id: "pharmacy",
    word: "pharmacy",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["薬局", "薬学"],
    pronunciation: "/ˈfɑːrməsi/",
    exampleSentence: "The pharmacy on the corner is open late.",
    exampleTranslationJa: "角の薬局は遅くまで開いている。",
    collocations: ["a 24-hour pharmacy", "collect from the pharmacy"],
    mnemonic: "英国では chemist's とも言う。薬をもらう場所。",
    relatedWords: ["pharmacist", "medicine", "prescription"],
  },
  {
    id: "pharmacist",
    word: "pharmacist",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["薬剤師"],
    pronunciation: "/ˈfɑːrməsɪst/",
    exampleSentence: "Ask the pharmacist which one is safe for children.",
    exampleTranslationJa: "どちらが子どもに安全か薬剤師に聞いてください。",
    collocations: ["ask a pharmacist", "a hospital pharmacist"],
    wordFormation: "pharmacy(薬局)+ -ist(人)。",
    mnemonic: "薬局(pharmacy)にいる人。処方せんを実際の薬にする専門家。",
    relatedWords: ["pharmacy", "prescription", "medicine"],
  },
  {
    id: "optician",
    word: "optician",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["眼鏡店、眼鏡技師"],
    pronunciation: "/ɑːpˈtɪʃn/",
    exampleSentence: "I need to see an optician about new glasses.",
    exampleTranslationJa: "新しい眼鏡のことで眼鏡店に行かないといけない。",
    collocations: ["go to the optician", "an optician's appointment"],
    wordFormation: "optic(目の)+ -ian(人)。",
    mnemonic: "optic(目の)+ -ian(職業の人)。眼科医は ophthalmologist。",
    relatedWords: ["glasses", "eye", "vision"],
  },
  {
    id: "checkup",
    word: "checkup",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["健康診断、定期検診"],
    pronunciation: "/ˈtʃekʌp/",
    exampleSentence: "He goes for a checkup once a year.",
    exampleTranslationJa: "彼は年に一度、健康診断を受ける。",
    collocations: ["a regular checkup", "go for a checkup", "a dental checkup"],
    wordFormation: "句動詞 check up(調べる)が名詞になった語。",
    mnemonic: "具合が悪くなくても受けるのが checkup。診察は examination。",
    relatedWords: ["examination", "doctor", "health"],
  },
  {
    id: "heartbeat",
    word: "heartbeat",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["心拍、鼓動"],
    pronunciation: "/ˈhɑːrtbiːt/",
    exampleSentence: "The doctor listened to the baby's heartbeat.",
    exampleTranslationJa: "医師は赤ん坊の心音を聞いた。",
    collocations: ["a rapid heartbeat", "listen to the heartbeat", "in a heartbeat"],
    wordFormation: "heart(心臓)+ beat(打つこと)。",
    mnemonic: "in a heartbeat は「一拍のうちに」＝「即座に」。",
    relatedWords: ["pulse", "heart", "rhythm"],
  },
  {
    id: "posture",
    word: "posture",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["姿勢", "(政治的な)構え、態度"],
    pronunciation: "/ˈpɑːstʃər/",
    exampleSentence: "Sitting all day can ruin your posture.",
    exampleTranslationJa: "一日中座っていると姿勢が悪くなる。",
    collocations: ["good posture", "poor posture", "improve your posture"],
    etymology: "ラテン語 ponere(置く)から。position と同語根。",
    mnemonic: "position(位置)と同語根。体をどう「置いている」か。",
    relatedWords: ["position", "stance", "back"],
  },
  {
    id: "stamina",
    word: "stamina",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["持久力、スタミナ"],
    pronunciation: "/ˈstæmɪnə/",
    exampleSentence: "Running every morning built up her stamina.",
    exampleTranslationJa: "毎朝走ることで彼女は持久力をつけた。",
    collocations: ["build stamina", "physical stamina", "lack stamina"],
    mnemonic: "瞬発力(strength)ではなく「長く続ける力」。数えられない名詞。",
    relatedWords: ["endurance", "energy", "fitness"],
  },
  {
    id: "exercise",
    word: "exercise",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["運動、体操", "練習問題", "(権利を)行使する"],
    pronunciation: "/ˈeksərsaɪz/",
    exampleSentence: "Regular exercise lowers the risk of heart disease.",
    exampleTranslationJa: "定期的な運動は心臓病の危険を下げる。",
    collocations: ["take exercise", "a breathing exercise", "exercise your right"],
    mnemonic: "体を動かす運動も、教科書の練習問題も、権利の行使も exercise。",
    relatedWords: ["workout", "practice", "training"],
  },
  {
    id: "massage",
    word: "massage",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["マッサージ", "もみほぐす"],
    pronunciation: "/məˈsɑːʒ/",
    exampleSentence: "She massaged his shoulders to ease the tension.",
    exampleTranslationJa: "彼女は緊張をほぐそうと彼の肩をもんだ。",
    collocations: ["have a massage", "a back massage", "massage your temples"],
    mnemonic: "アクセントは後ろ /məˈsɑːʒ/。message(伝言)と混同しないこと。",
    relatedWords: ["rub", "therapy", "relax"],
  },
  {
    id: "diet",
    word: "diet",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["食生活、日常の食事", "ダイエット、食事制限"],
    pronunciation: "/ˈdaɪət/",
    exampleSentence: "A balanced diet includes plenty of vegetables.",
    exampleTranslationJa: "バランスのとれた食生活には野菜がたっぷり含まれる。",
    collocations: ["a balanced diet", "go on a diet", "a healthy diet"],
    mnemonic: "「やせるための食事制限」だけでなく、ふだん何を食べているか全体を指す。",
    relatedWords: ["nutrition", "food", "eat"],
  },
  {
    id: "calorie",
    word: "calorie",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カロリー"],
    pronunciation: "/ˈkæləri/",
    exampleSentence: "This snack contains 200 calories.",
    exampleTranslationJa: "この軽食は200キロカロリーある。",
    collocations: ["burn calories", "count calories", "empty calories"],
    mnemonic: "ラテン語 calor(熱)から。食品表示の「カロリー」は正確には kcal。",
    relatedWords: ["energy", "diet", "nutrition"],
  },
  {
    id: "carbohydrate",
    word: "carbohydrate",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["炭水化物"],
    pronunciation: "/ˌkɑːrboʊˈhaɪdreɪt/",
    exampleSentence: "Rice and bread are rich in carbohydrates.",
    exampleTranslationJa: "米とパンは炭水化物が豊富だ。",
    collocations: ["complex carbohydrates", "cut carbohydrates", "low in carbohydrates"],
    wordFormation: "carbo-(炭素)+ hydrate(水と結びついたもの)。",
    mnemonic: "炭素と水からできているから carbo + hydrate。口語では carbs と略す。",
    relatedWords: ["protein", "sugar", "nutrition"],
  },
  {
    id: "overweight",
    word: "overweight",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["太りすぎの", "重量超過の"],
    pronunciation: "/ˌoʊvərˈweɪt/",
    exampleSentence: "My suitcase was three kilos overweight.",
    exampleTranslationJa: "私のスーツケースは3キロの重量超過だった。",
    collocations: ["slightly overweight", "an overweight bag", "become overweight"],
    wordFormation: "over-(超えて)+ weight(重さ)。",
    mnemonic: "人にも荷物にも使う。fat より角の立たない言い方。",
    relatedWords: ["obesity", "weight", "underweight"],
  },
  {
    id: "underweight",
    word: "underweight",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["やせすぎの、標準体重に満たない"],
    pronunciation: "/ˌʌndərˈweɪt/",
    exampleSentence: "The baby was underweight at birth.",
    exampleTranslationJa: "その赤ん坊は生まれたとき標準体重に足りなかった。",
    collocations: ["severely underweight", "an underweight child"],
    wordFormation: "under-(下回る)+ weight(重さ)。",
    mnemonic: "overweight の反対。医学的な基準を下回っている状態。",
    relatedWords: ["overweight", "thin", "weight"],
  },
  {
    id: "newborn",
    word: "newborn",
    level: "B1",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["新生児", "生まれたばかりの"],
    pronunciation: "/ˈnuːbɔːrn/",
    exampleSentence: "A newborn sleeps most of the day.",
    exampleTranslationJa: "新生児は一日の大半を眠って過ごす。",
    collocations: ["a newborn baby", "newborn twins", "care for a newborn"],
    wordFormation: "new(新しく)+ born(生まれた)。",
    mnemonic: "生後まもない時期。次が infant(乳児)、その次が toddler(よちよち歩き)。",
    relatedWords: ["baby", "infant", "birth"],
  },
  {
    id: "toddler",
    word: "toddler",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["よちよち歩きの幼児(1〜3歳ごろ)"],
    pronunciation: "/ˈtɑːdlər/",
    exampleSentence: "A toddler ran across the room and fell over.",
    exampleTranslationJa: "よちよち歩きの子が部屋を横切って転んだ。",
    collocations: ["a young toddler", "toddler groups", "chase a toddler"],
    wordFormation: "toddle(よちよち歩く)+ -er。",
    mnemonic: "toddle は「よちよち歩く」。歩き始めた子だけを指す語。",
    relatedWords: ["infant", "child", "newborn"],
  },
  {
    id: "puberty",
    word: "puberty",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["思春期(体が大人になる時期)"],
    pronunciation: "/ˈpjuːbərti/",
    exampleSentence: "Boys' voices change during puberty.",
    exampleTranslationJa: "男子の声は思春期に変わる。",
    collocations: ["reach puberty", "go through puberty", "the onset of puberty"],
    mnemonic: "体の変化に注目する語。心のほうを含む「青年期」は adolescence。",
    relatedWords: ["adolescence", "teenager", "growth"],
  },
  {
    id: "adolescence",
    word: "adolescence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["青年期、思春期"],
    pronunciation: "/ˌædəˈlesns/",
    exampleSentence: "Adolescence can be a difficult time for parents too.",
    exampleTranslationJa: "青年期は親にとっても難しい時期になりうる。",
    collocations: ["during adolescence", "late adolescence", "the stress of adolescence"],
    etymology: "ラテン語 adolescere(成長する)から。adult と同語根。",
    mnemonic: "adult(大人)と同語根で「大人になりつつある時期」。人は adolescent。",
    relatedWords: ["puberty", "teenager", "youth"],
  },
  {
    id: "menopause",
    word: "menopause",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["閉経、更年期"],
    pronunciation: "/ˈmenəpɔːz/",
    exampleSentence: "Many women experience hot flushes during the menopause.",
    exampleTranslationJa: "多くの女性は更年期にほてりを経験する。",
    collocations: ["go through the menopause", "early menopause"],
    wordFormation: "meno-(月経)+ pause(止まる)。",
    mnemonic: "meno(月のもの)+ pause(止まる)。語がそのまま意味。",
    relatedWords: ["hormone", "age", "women"],
  },
  {
    id: "ageing",
    word: "ageing",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["老化、高齢化", "年をとりつつある"],
    pronunciation: "/ˈeɪdʒɪŋ/",
    exampleSentence: "Japan has a rapidly ageing population.",
    exampleTranslationJa: "日本は急速に高齢化する人口を抱えている。",
    collocations: ["an ageing population", "the ageing process", "anti-ageing"],
    mnemonic: "米つづりは aging。an ageing population は新聞の定番表現。",
    relatedWords: ["age", "elderly", "old"],
  },
  {
    id: "deaf",
    word: "deaf",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["耳が聞こえない"],
    pronunciation: "/def/",
    exampleSentence: "The film has subtitles for deaf viewers.",
    exampleTranslationJa: "その映画には耳の聞こえない観客のための字幕がある。",
    collocations: ["deaf people", "go deaf", "fall on deaf ears"],
    mnemonic: "発音は /def/。fall on deaf ears は「聞き入れられない」。",
    relatedWords: ["hearing", "blind", "sign language"],
  },
  {
    id: "mute",
    word: "mute",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["無言の、音を出さない", "(音を)消す"],
    pronunciation: "/mjuːt/",
    exampleSentence: "He muted the microphone before coughing.",
    exampleTranslationJa: "彼はせきをする前にマイクをミュートにした。",
    collocations: ["mute the sound", "on mute", "stand mute"],
    mnemonic: "会議アプリの「ミュート」と同じ語。音を出さない状態にすること。",
    relatedWords: ["silent", "sound", "volume"],
  },
  {
    id: "addict",
    word: "addict",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["中毒者、依存症の人", "熱中している人"],
    pronunciation: "/ˈædɪkt/",
    exampleSentence: "He describes himself as a coffee addict.",
    exampleTranslationJa: "彼は自分をコーヒー中毒だと言っている。",
    collocations: ["a drug addict", "a recovering addict", "a TV addict"],
    mnemonic: "名詞は前にアクセント /ˈædɪkt/、動詞 addict は後ろ。軽い意味で「〜好き」にも使う。",
    relatedWords: ["addiction", "addicted", "habit"],
  },
  {
    id: "overdose",
    word: "overdose",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["過剰摂取", "薬を飲みすぎる"],
    pronunciation: "/ˈoʊvərdoʊs/",
    exampleSentence: "He was taken to hospital after an overdose.",
    exampleTranslationJa: "彼は過剰摂取のあと病院に運ばれた。",
    collocations: ["a drug overdose", "an accidental overdose", "overdose on"],
    wordFormation: "over-(超えて)+ dose(一回分の服用量)。",
    mnemonic: "dose(一回分)を over(超える)。口語では OD と略す。",
    relatedWords: ["dose", "drug", "addiction"],
  },
  {
    id: "sober",
    word: "sober",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["しらふの、酔っていない", "まじめな、冷静な"],
    pronunciation: "/ˈsoʊbər/",
    exampleSentence: "He has been sober for three years.",
    exampleTranslationJa: "彼は3年間、酒を断っている。",
    collocations: ["stay sober", "a sober assessment", "sober up"],
    mnemonic: "酔っていない状態から「浮かれず冷静な」の意味へ。a sober look at で「冷静に見る」。",
    relatedWords: ["drunk", "alcohol", "serious"],
  },
  {
    id: "intoxicated",
    word: "intoxicated",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["酔った(かたい語)", "うっとりした"],
    pronunciation: "/ɪnˈtɑːksɪkeɪtɪd/",
    exampleSentence: "He was arrested for driving while intoxicated.",
    exampleTranslationJa: "彼は酒気帯び運転で逮捕された。",
    collocations: ["driving while intoxicated", "intoxicated with power"],
    etymology: "ラテン語 toxicum(毒)から。toxic と同語根。",
    mnemonic: "toxic(毒)が語根。drunk のかたい言い方で、法律文書で使う。",
    relatedWords: ["drunk", "toxic", "alcohol"],
  },
]
