import type { VocabularyEntry } from '../types'

// 増補 第39弾(最終)。これで 7,500語 → 8,000語 の増補が完了する。
export const plus39: VocabularyEntry[] = [
  {
    id: "trampoline",
    word: "trampoline",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["トランポリン"],
    pronunciation: "/ˈtræmpəliːn/",
    exampleSentence: "The children bounced on the trampoline.",
    exampleTranslationJa: "子どもたちはトランポリンで跳ねていた。",
    collocations: ["bounce on a trampoline", "a garden trampoline", "jump on the trampoline"],
    mnemonic: "スペイン語 trampolín(飛び込み台)から。跳ねるのは bounce。",
    relatedWords: ["bounce", "jump", "spring"],
  },
  {
    id: "translator",
    word: "translator",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["翻訳者"],
    pronunciation: "/trænsˈleɪtər/",
    exampleSentence: "A translator turned the novel into English.",
    exampleTranslationJa: "翻訳者がその小説を英語にした。",
    collocations: ["a professional translator", "work as a translator", "a literary translator"],
    mnemonic: "translate(翻訳する)+ -or。話し言葉を訳す人は interpreter。",
    relatedWords: ["interpreter", "translate", "language"],
  },
  {
    id: "tray",
    word: "tray",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["盆、トレー"],
    pronunciation: "/treɪ/",
    exampleSentence: "He carried the cups on a tray.",
    exampleTranslationJa: "彼はカップを盆にのせて運んだ。",
    collocations: ["carry a tray", "a tea tray", "a baking tray"],
    mnemonic: "浅くて縁のある平たい運搬用の板。オーブン用は baking tray。",
    relatedWords: ["plate", "carry", "serve"],
  },
  {
    id: "treadmill",
    word: "treadmill",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ランニングマシン", "単調な繰り返しの生活"],
    pronunciation: "/ˈtredmɪl/",
    exampleSentence: "She runs on the treadmill every morning.",
    exampleTranslationJa: "彼女は毎朝ランニングマシンで走る。",
    collocations: ["run on a treadmill", "get off the treadmill", "a gym treadmill"],
    mnemonic: "tread(踏む)+ mill(臼)。進まないのに踏み続けることから比喩にも使う。",
    relatedWords: ["gym", "run", "exercise"],
  },
  {
    id: "trellis",
    word: "trellis",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["格子の垣、つる植物用の棚"],
    pronunciation: "/ˈtrelɪs/",
    exampleSentence: "Roses climbed up the wooden trellis.",
    exampleTranslationJa: "バラが木の格子垣を伝って伸びていた。",
    collocations: ["a wooden trellis", "climb a trellis", "fix a trellis to the wall"],
    mnemonic: "細い板を斜め格子に組んだ枠。つる植物を這わせる。",
    relatedWords: ["fence", "vine", "garden"],
  },
  {
    id: "tricycle",
    word: "tricycle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["三輪車"],
    pronunciation: "/ˈtraɪsɪkl/",
    exampleSentence: "The toddler rode a red tricycle.",
    exampleTranslationJa: "よちよち歩きの子が赤い三輪車に乗っていた。",
    collocations: ["ride a tricycle", "a child's tricycle", "a red tricycle"],
    mnemonic: "tri-(3)+ cycle(輪)。二輪は bicycle(bi-=2)。",
    relatedWords: ["bicycle", "child", "wheel"],
  },
  {
    id: "trimmer",
    word: "trimmer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["刈り込み機、トリマー"],
    pronunciation: "/ˈtrɪmər/",
    exampleSentence: "He cut the hedge with an electric trimmer.",
    exampleTranslationJa: "彼は電動の刈り込み機で生け垣を整えた。",
    collocations: ["a hedge trimmer", "an electric trimmer", "use a trimmer"],
    mnemonic: "trim(刈り整える)+ -er。庭の生け垣にも、ひげにも使う。",
    relatedWords: ["trim", "hedge", "shears"],
  },
  {
    id: "tripod",
    word: "tripod",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["三脚"],
    pronunciation: "/ˈtraɪpɑːd/",
    exampleSentence: "She mounted the camera on a tripod.",
    exampleTranslationJa: "彼女はカメラを三脚に取りつけた。",
    collocations: ["a camera tripod", "set up a tripod", "on a tripod"],
    mnemonic: "tri-(3)+ pod(足)。octopus・pedal と同じ「足」の語根。",
    relatedWords: ["camera", "stand", "telescope"],
  },
  {
    id: "trowel",
    word: "trowel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["移植ごて、こて"],
    pronunciation: "/ˈtraʊəl/",
    exampleSentence: "She dug a small hole with a trowel.",
    exampleTranslationJa: "彼女は移植ごてで小さな穴を掘った。",
    collocations: ["a garden trowel", "dig with a trowel", "a plastering trowel"],
    mnemonic: "片手で使う小さなこて。園芸用は先が丸く、左官用は平ら。",
    relatedWords: ["spade", "garden", "dig"],
  },
  {
    id: "tub",
    word: "tub",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["おけ、たらい", "(アイスなどの)容器"],
    pronunciation: "/tʌb/",
    exampleSentence: "He bought a tub of ice cream.",
    exampleTranslationJa: "彼はアイスクリームを1箱買った。",
    collocations: ["a tub of ice cream", "a plastic tub", "a hot tub"],
    mnemonic: "深くて丸い入れ物。浴槽は bathtub、屋外の温浴槽は hot tub。",
    relatedWords: ["bathtub", "container", "bucket"],
  },
  {
    id: "tumbler",
    word: "tumbler",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["タンブラー(取っ手のない平底のコップ)"],
    pronunciation: "/ˈtʌmblər/",
    exampleSentence: "He poured water into a heavy tumbler.",
    exampleTranslationJa: "彼は厚手のタンブラーに水を注いだ。",
    collocations: ["a glass tumbler", "fill a tumbler", "a heavy tumbler"],
    mnemonic: "もとは底が丸く倒れる(tumble)杯だった。今は平底で取っ手なし。",
    relatedWords: ["glass", "mug", "cup"],
  },
  {
    id: "turnip",
    word: "turnip",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カブ"],
    pronunciation: "/ˈtɜːrnɪp/",
    exampleSentence: "She added turnip to the winter stew.",
    exampleTranslationJa: "彼女は冬の煮込みにカブを加えた。",
    collocations: ["mashed turnip", "peel a turnip", "turnip soup"],
    mnemonic: "白く丸い根菜。細長い parsnip と並ぶ冬の野菜。",
    relatedWords: ["parsnip", "carrot", "vegetable"],
  },
  {
    id: "turret",
    word: "turret",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小塔、やぐら"],
    pronunciation: "/ˈtɜːrɪt/",
    exampleSentence: "A small turret stood at each corner of the castle.",
    exampleTranslationJa: "城の四隅に小さな塔が立っていた。",
    collocations: ["a castle turret", "a round turret", "a corner turret"],
    mnemonic: "tower(塔)の小さい形。城の角につく丸い塔。",
    relatedWords: ["tower", "castle", "spire"],
  },
  {
    id: "typewriter",
    word: "typewriter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["タイプライター"],
    pronunciation: "/ˈtaɪpraɪtər/",
    exampleSentence: "He wrote all his letters on an old typewriter.",
    exampleTranslationJa: "彼は手紙をすべて古いタイプライターで書いた。",
    collocations: ["an old typewriter", "on a typewriter", "a manual typewriter"],
    mnemonic: "type(活字を打つ)+ writer。キーボード配列 QWERTY はここから続いている。",
    relatedWords: ["keyboard", "type", "machine"],
  },
  {
    id: "underpass",
    word: "underpass",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["地下道、アンダーパス"],
    pronunciation: "/ˈʌndərpæs/",
    exampleSentence: "Use the underpass to cross the road safely.",
    exampleTranslationJa: "安全に道を渡るには地下道を使って。",
    collocations: ["go through the underpass", "a pedestrian underpass", "a dark underpass"],
    mnemonic: "under(下)+ pass(通る)。上を渡るのは footbridge や overpass。",
    relatedWords: ["tunnel", "crossing", "pedestrian"],
  },
  {
    id: "urn",
    word: "urn",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["つぼ、骨つぼ", "(大型の)給湯器"],
    pronunciation: "/ɜːrn/",
    exampleSentence: "An ancient urn stood in the museum case.",
    exampleTranslationJa: "古代のつぼが博物館のケースに置かれていた。",
    collocations: ["an ancient urn", "a funeral urn", "a tea urn"],
    mnemonic: "earn(稼ぐ)と同音。口が広く台のついた大きなつぼ。",
    relatedWords: ["vase", "pot", "ashes"],
  },
  {
    id: "utensil",
    word: "utensil",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(台所の)道具、器具"],
    pronunciation: "/juːˈtensl/",
    exampleSentence: "Keep the kitchen utensils in this drawer.",
    exampleTranslationJa: "台所道具はこの引き出しにしまって。",
    collocations: ["kitchen utensils", "cooking utensils", "wash the utensils"],
    mnemonic: "ラテン語 uti(使う)から。use・utility と同じ語根。",
    relatedWords: ["cutlery", "tool", "kitchen"],
  },
  {
    id: "valve",
    word: "valve",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["弁、バルブ"],
    pronunciation: "/vælv/",
    exampleSentence: "Turn the valve to stop the water.",
    exampleTranslationJa: "水を止めるにはバルブを回して。",
    collocations: ["open a valve", "close the valve", "a heart valve"],
    mnemonic: "流れを一方向にしたり止めたりする仕掛け。心臓の弁も valve。",
    relatedWords: ["pipe", "tap", "flow"],
  },
  {
    id: "vase",
    word: "vase",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["花びん"],
    pronunciation: "/veɪs/",
    exampleSentence: "She put the flowers in a tall vase.",
    exampleTranslationJa: "彼女は花を背の高い花びんに生けた。",
    collocations: ["a glass vase", "put flowers in a vase", "a tall vase"],
    mnemonic: "英国では /vɑːz/ と読むことが多い。骨つぼのような大つぼは urn。",
    relatedWords: ["flower", "urn", "pot"],
  },
  {
    id: "venison",
    word: "venison",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["シカ肉"],
    pronunciation: "/ˈvenɪsn/",
    exampleSentence: "The restaurant serves venison in autumn.",
    exampleTranslationJa: "その店は秋にシカ肉を出す。",
    collocations: ["roast venison", "a venison stew", "wild venison"],
    mnemonic: "beef(牛)・pork(豚)と同じく、動物名と肉の名が違う一群。",
    relatedWords: ["deer", "beef", "meat"],
  },
  {
    id: "veranda",
    word: "veranda",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ベランダ、屋根つきの縁側"],
    pronunciation: "/vəˈrændə/",
    exampleSentence: "They sat on the veranda after dinner.",
    exampleTranslationJa: "夕食のあと彼らはベランダに座った。",
    collocations: ["on the veranda", "a wide veranda", "a shaded veranda"],
    mnemonic: "ヒンディー語経由の語。屋根のある、建物沿いの細長い床。",
    relatedWords: ["balcony", "porch", "terrace"],
  },
  {
    id: "vet",
    word: "vet",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["獣医"],
    pronunciation: "/vet/",
    exampleSentence: "We took the cat to the vet.",
    exampleTranslationJa: "猫を獣医に連れていった。",
    collocations: ["take a pet to the vet", "a local vet", "the vet's surgery"],
    mnemonic: "veterinary surgeon の略。動物のための doctor。",
    relatedWords: ["doctor", "pet", "animal"],
  },
  {
    id: "viaduct",
    word: "viaduct",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["高架橋"],
    pronunciation: "/ˈvaɪədʌkt/",
    exampleSentence: "The train crossed a stone viaduct.",
    exampleTranslationJa: "列車は石造りの高架橋を渡った。",
    collocations: ["a railway viaduct", "cross a viaduct", "a stone viaduct"],
    mnemonic: "via(道)+ duct(導く)。谷をまたぐ、脚の並んだ長い橋。",
    relatedWords: ["bridge", "railway", "arch"],
  },
  {
    id: "village",
    word: "village",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["村"],
    pronunciation: "/ˈvɪlɪdʒ/",
    exampleSentence: "She grew up in a small fishing village.",
    exampleTranslationJa: "彼女は小さな漁村で育った。",
    collocations: ["a small village", "a fishing village", "the village shop"],
    mnemonic: "town より小さい集落。villa(別荘)と同じ語根で「田舎の家」が原義。",
    relatedWords: ["town", "city", "countryside"],
  },
  {
    id: "vineyard",
    word: "vineyard",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ぶどう園"],
    pronunciation: "/ˈvɪnjərd/",
    exampleSentence: "Rows of vines covered the hillside vineyard.",
    exampleTranslationJa: "丘のぶどう園はぶどうの木の列で覆われていた。",
    collocations: ["a family vineyard", "work in a vineyard", "a hillside vineyard"],
    mnemonic: "vine(ぶどうの木)+ yard。つづりに反して「ヴィニヤード」と読む。",
    relatedWords: ["vine", "wine", "orchard"],
  },
  {
    id: "vocabulary",
    word: "vocabulary",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["語彙、単語力"],
    pronunciation: "/voʊˈkæbjəleri/",
    exampleSentence: "Reading widely builds your vocabulary.",
    exampleTranslationJa: "幅広く読むことで語彙が増える。",
    collocations: ["build your vocabulary", "a wide vocabulary", "vocabulary test"],
    mnemonic: "ラテン語 vocabulum(語)から。voice・vocal と同じ語根。",
    relatedWords: ["word", "grammar", "language"],
  },
  {
    id: "waiter",
    word: "waiter",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["給仕、ウェイター"],
    pronunciation: "/ˈweɪtər/",
    exampleSentence: "The waiter brought us the menu.",
    exampleTranslationJa: "ウェイターが献立を持ってきてくれた。",
    collocations: ["call the waiter", "a friendly waiter", "work as a waiter"],
    mnemonic: "wait on(給仕する)+ -er。性別を問わない言い方は server や waiting staff。",
    relatedWords: ["restaurant", "menu", "serve"],
  },
  {
    id: "wallpaper",
    word: "wallpaper",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["壁紙", "壁紙を貼る"],
    pronunciation: "/ˈwɔːlpeɪpər/",
    exampleSentence: "They chose striped wallpaper for the hall.",
    exampleTranslationJa: "彼らは玄関に縞の壁紙を選んだ。",
    collocations: ["hang wallpaper", "striped wallpaper", "strip off wallpaper"],
    mnemonic: "wall(壁)+ paper(紙)。貼るのは hang、はがすのは strip off。",
    relatedWords: ["wall", "paint", "decorate"],
  },
  {
    id: "washbasin",
    word: "washbasin",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["洗面台(英)"],
    pronunciation: "/ˈwɑːʃbeɪsn/",
    exampleSentence: "He rinsed his hands in the washbasin.",
    exampleTranslationJa: "彼は洗面台で手をすすいだ。",
    collocations: ["at the washbasin", "a cracked washbasin", "clean the washbasin"],
    mnemonic: "wash(洗う)+ basin(鉢)。米国では sink。",
    relatedWords: ["sink", "basin", "bathroom"],
  },
  {
    id: "washer",
    word: "washer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(ねじの)座金、ワッシャー", "洗濯機"],
    pronunciation: "/ˈwɑːʃər/",
    exampleSentence: "The tap leaks because the washer is worn.",
    exampleTranslationJa: "座金がすり減っているので蛇口から水がもれる。",
    collocations: ["a rubber washer", "replace the washer", "a worn washer"],
    mnemonic: "ねじの下に挟む薄い輪。水もれを止めるゴムのものが身近。",
    relatedWords: ["bolt", "tap", "seal"],
  },
  {
    id: "wastebin",
    word: "wastebin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["くずかご、ごみ箱(英)"],
    pronunciation: "/ˈweɪstbɪn/",
    exampleSentence: "Throw the wrapper in the wastebin.",
    exampleTranslationJa: "包み紙はごみ箱に捨てて。",
    collocations: ["throw in the wastebin", "empty the wastebin", "a full wastebin"],
    mnemonic: "waste(くず)+ bin(容器)。英国では単に bin とも言う。",
    relatedWords: ["bin", "rubbish", "litter"],
  },
  {
    id: "watchdog",
    word: "watchdog",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["監視機関", "番犬"],
    pronunciation: "/ˈwɑːtʃdɔːɡ/",
    exampleSentence: "The consumer watchdog investigated the company.",
    exampleTranslationJa: "消費者監視機関がその会社を調査した。",
    collocations: ["a consumer watchdog", "an industry watchdog", "a watchdog report"],
    mnemonic: "watch(見張る)+ dog。番犬から転じて、不正を見張る機関を指す。",
    relatedWords: ["regulator", "monitor", "guard"],
  },
  {
    id: "watering can",
    word: "watering can",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["じょうろ"],
    pronunciation: "/ˈwɔːtərɪŋ kæn/",
    exampleSentence: "She filled the watering can at the tap.",
    exampleTranslationJa: "彼女は蛇口でじょうろに水を入れた。",
    collocations: ["fill a watering can", "a metal watering can", "use a watering can"],
    mnemonic: "watering(水やりの)+ can(缶)。先の穴の空いた口を rose と呼ぶ。",
    relatedWords: ["garden", "water", "plant"],
  },
  {
    id: "wax",
    word: "wax",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ろう、ワックス", "ワックスをかける"],
    pronunciation: "/wæks/",
    exampleSentence: "Melted wax ran down the side of the candle.",
    exampleTranslationJa: "溶けたろうがろうそくの横を流れ落ちた。",
    collocations: ["melted wax", "candle wax", "wax the floor"],
    mnemonic: "熱で溶け、冷えて固まる物質。耳あかも earwax と言う。",
    relatedWords: ["candle", "polish", "melt"],
  },
  {
    id: "weathervane",
    word: "weathervane",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["風見、風向計"],
    pronunciation: "/ˈweðərveɪn/",
    exampleSentence: "A weathervane turned on top of the barn.",
    exampleTranslationJa: "納屋の上で風見が回っていた。",
    collocations: ["a weathervane turns", "an iron weathervane", "a weathervane on the roof"],
    mnemonic: "weather(天気)+ vane(羽根)。屋根の上で風の向きを示す。ニワトリ型が定番。",
    relatedWords: ["wind", "roof", "direction"],
  },
  {
    id: "wetsuit",
    word: "wetsuit",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ウェットスーツ"],
    pronunciation: "/ˈwetsuːt/",
    exampleSentence: "He pulled on a wetsuit before the dive.",
    exampleTranslationJa: "彼は潜る前にウェットスーツを着た。",
    collocations: ["wear a wetsuit", "a thick wetsuit", "zip up a wetsuit"],
    mnemonic: "wet(濡れた)+ suit(服)。薄い水の層を体温で温めて保温する。",
    relatedWords: ["dive", "surf", "swim"],
  },
  {
    id: "wheelbarrow",
    word: "wheelbarrow",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["手押し車、一輪車"],
    pronunciation: "/ˈwiːlbæroʊ/",
    exampleSentence: "He pushed a wheelbarrow full of soil.",
    exampleTranslationJa: "彼は土を山盛りにした手押し車を押した。",
    collocations: ["push a wheelbarrow", "a wheelbarrow full of", "load a wheelbarrow"],
    mnemonic: "wheel(車輪)+ barrow(荷台)。前に車輪1つ、後ろに取っ手2本。",
    relatedWords: ["cart", "garden", "soil"],
  },
  {
    id: "whistle",
    word: "whistle",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["笛、口笛", "笛を吹く、口笛を吹く"],
    pronunciation: "/ˈwɪsl/",
    exampleSentence: "The referee blew his whistle to stop the game.",
    exampleTranslationJa: "審判は笛を吹いて試合を止めた。",
    collocations: ["blow a whistle", "a referee's whistle", "whistle a tune"],
    mnemonic: "t は読まない。blow the whistle on は「不正を告発する」。",
    relatedWords: ["referee", "blow", "signal"],
  },
  {
    id: "whiteboard",
    word: "whiteboard",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ホワイトボード"],
    pronunciation: "/ˈwaɪtbɔːrd/",
    exampleSentence: "The teacher wrote the date on the whiteboard.",
    exampleTranslationJa: "先生はホワイトボードに日付を書いた。",
    collocations: ["write on the whiteboard", "wipe the whiteboard", "an interactive whiteboard"],
    mnemonic: "white(白)+ board(板)。黒い板は blackboard。",
    relatedWords: ["blackboard", "marker", "classroom"],
  },
  {
    id: "wick",
    word: "wick",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(ろうそくやランプの)芯"],
    pronunciation: "/wɪk/",
    exampleSentence: "Trim the wick before lighting the candle.",
    exampleTranslationJa: "ろうそくに火をつける前に芯を切りそろえて。",
    collocations: ["trim the wick", "light the wick", "a burnt wick"],
    mnemonic: "ろうを吸い上げて燃やす糸。短く切ると炎が安定する。",
    relatedWords: ["candle", "flame", "lamp"],
  },
  {
    id: "windmill",
    word: "windmill",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["風車"],
    pronunciation: "/ˈwɪndmɪl/",
    exampleSentence: "An old windmill stood on the hill.",
    exampleTranslationJa: "古い風車が丘の上に立っていた。",
    collocations: ["an old windmill", "the windmill turns", "a windmill sail"],
    mnemonic: "wind(風)+ mill(製粉所)。発電用の現代的なものは wind turbine。",
    relatedWords: ["wind", "mill", "turbine"],
  },
  {
    id: "windowpane",
    word: "windowpane",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["窓ガラス"],
    pronunciation: "/ˈwɪndoʊpeɪn/",
    exampleSentence: "Rain streamed down the windowpane.",
    exampleTranslationJa: "雨が窓ガラスを流れ落ちた。",
    collocations: ["a cracked windowpane", "clean the windowpane", "frost on the windowpane"],
    mnemonic: "window(窓)+ pane(ガラス1枚)。痛みの pain と同音。",
    relatedWords: ["pane", "window", "glass"],
  },
  {
    id: "wineglass",
    word: "wineglass",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ワイングラス"],
    pronunciation: "/ˈwaɪnɡlæs/",
    exampleSentence: "He filled each wineglass halfway.",
    exampleTranslationJa: "彼はそれぞれのワイングラスを半分まで満たした。",
    collocations: ["fill a wineglass", "a tall wineglass", "raise a wineglass"],
    mnemonic: "wine(ワイン)+ glass。脚のついた杯。取っ手つきの筒は mug。",
    relatedWords: ["glass", "wine", "tumbler"],
  },
  {
    id: "wok",
    word: "wok",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["中華なべ"],
    pronunciation: "/wɑːk/",
    exampleSentence: "Stir-fry the vegetables in a hot wok.",
    exampleTranslationJa: "熱した中華なべで野菜を炒めて。",
    collocations: ["a hot wok", "stir-fry in a wok", "a cast iron wok"],
    mnemonic: "広東語から。底が丸く深いので強い火で一気に炒められる。",
    relatedWords: ["pan", "fry", "kitchen"],
  },
  {
    id: "woodpecker",
    word: "woodpecker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["キツツキ"],
    pronunciation: "/ˈwʊdpekər/",
    exampleSentence: "A woodpecker tapped loudly on the trunk.",
    exampleTranslationJa: "キツツキが幹を大きな音でつついた。",
    collocations: ["a woodpecker taps", "a green woodpecker", "hear a woodpecker"],
    mnemonic: "wood(木)+ pecker(つつくもの)。peck は「くちばしでつつく」。",
    relatedWords: ["peck", "tree", "bird"],
  },
  {
    id: "workbench",
    word: "workbench",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["作業台"],
    pronunciation: "/ˈwɜːrkbentʃ/",
    exampleSentence: "His tools were laid out on the workbench.",
    exampleTranslationJa: "彼の道具は作業台に並べられていた。",
    collocations: ["a wooden workbench", "on the workbench", "clear the workbench"],
    mnemonic: "work(作業)+ bench(台)。万力を固定して使う頑丈な台。",
    relatedWords: ["tool", "workshop", "bench"],
  },
  {
    id: "wrapper",
    word: "wrapper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["包み紙、包装"],
    pronunciation: "/ˈræpər/",
    exampleSentence: "He dropped the sweet wrapper on the floor.",
    exampleTranslationJa: "彼はお菓子の包み紙を床に落とした。",
    collocations: ["a sweet wrapper", "throw away the wrapper", "a chocolate wrapper"],
    mnemonic: "wrap(包む)+ -er。w は読まず、rapper(ラップ歌手)と同音。",
    relatedWords: ["wrap", "packaging", "paper"],
  },
  {
    id: "wrestling",
    word: "wrestling",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["レスリング、格闘"],
    pronunciation: "/ˈreslɪŋ/",
    exampleSentence: "He took up wrestling at university.",
    exampleTranslationJa: "彼は大学でレスリングを始めた。",
    collocations: ["a wrestling match", "take up wrestling", "professional wrestling"],
    mnemonic: "w と t は読まず「レスリング」。wrestle with は「問題と格闘する」。",
    relatedWords: ["boxing", "sport", "match"],
  },
  {
    id: "yarn",
    word: "yarn",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["毛糸、編み糸", "(長い)作り話"],
    pronunciation: "/jɑːrn/",
    exampleSentence: "She bought blue yarn to knit a scarf.",
    exampleTranslationJa: "彼女はマフラーを編むため青い毛糸を買った。",
    collocations: ["a ball of yarn", "knit with yarn", "spin a yarn"],
    mnemonic: "編み物用の太い糸。spin a yarn は「長い話をこしらえる」。",
    relatedWords: ["wool", "knitting", "thread"],
  },
  {
    id: "zinc",
    word: "zinc",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["亜鉛"],
    pronunciation: "/zɪŋk/",
    exampleSentence: "The roof was covered with sheets of zinc.",
    exampleTranslationJa: "屋根は亜鉛の板でふかれていた。",
    collocations: ["a zinc roof", "zinc supplements", "coated with zinc"],
    mnemonic: "さびに強い銀白色の金属。鉄に塗ってさびを防ぐ。",
    relatedWords: ["metal", "iron", "mineral"],
  },
]
