import type { VocabularyEntry } from '../types'

// 増補 第35弾。台所・食品・屋外の具体名詞。
export const plus35: VocabularyEntry[] = [
  {
    id: "locker",
    word: "locker",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ロッカー"],
    pronunciation: "/ˈlɑːkər/",
    exampleSentence: "Leave your bag in the locker at the entrance.",
    exampleTranslationJa: "かばんは入口のロッカーに預けて。",
    collocations: ["a locker room", "lock the locker", "a school locker"],
    mnemonic: "lock(鍵をかける)+ -er。鍵のかかる収納。更衣室は locker room。",
    relatedWords: ["lock", "cupboard", "changing room"],
  },
  {
    id: "locket",
    word: "locket",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ロケット(写真などを入れる小さな飾り)"],
    pronunciation: "/ˈlɑːkɪt/",
    exampleSentence: "She kept a photograph inside her locket.",
    exampleTranslationJa: "彼女はロケットの中に写真を入れていた。",
    collocations: ["open a locket", "a silver locket", "a locket on a chain"],
    mnemonic: "首から下げる、ふたの開く小さな入れ物。飛ぶ rocket とは別語。",
    relatedWords: ["necklace", "pendant", "chain"],
  },
  {
    id: "loft",
    word: "loft",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["屋根裏、ロフト"],
    pronunciation: "/lɔːft/",
    exampleSentence: "The old suitcases are stored in the loft.",
    exampleTranslationJa: "古いスーツケースは屋根裏にしまってある。",
    collocations: ["in the loft", "a loft conversion", "climb into the loft"],
    mnemonic: "英国では屋根裏収納をこう呼ぶ。米国では attic。",
    relatedWords: ["attic", "roof", "storage"],
  },
  {
    id: "lollipop",
    word: "lollipop",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["棒つきキャンディー"],
    pronunciation: "/ˈlɑːlipɑːp/",
    exampleSentence: "The child chose a strawberry lollipop.",
    exampleTranslationJa: "その子はイチゴの棒つきキャンディーを選んだ。",
    collocations: ["suck a lollipop", "a lollipop stick", "a strawberry lollipop"],
    mnemonic: "くだけて lolly とも。英国の横断歩道の旗を持つ人は lollipop lady。",
    relatedWords: ["sweet", "candy", "stick"],
  },
  {
    id: "loudspeaker",
    word: "loudspeaker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スピーカー、拡声器"],
    pronunciation: "/ˌlaʊdˈspiːkər/",
    exampleSentence: "An announcement came over the loudspeaker.",
    exampleTranslationJa: "スピーカーから案内が流れた。",
    collocations: ["over the loudspeaker", "a loudspeaker announcement", "a public loudspeaker"],
    mnemonic: "loud(大きい)+ speaker(話すもの)。短く speaker とも言う。",
    relatedWords: ["speaker", "microphone", "announcement"],
  },
  {
    id: "lounge",
    word: "lounge",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["居間、ラウンジ", "くつろぐ"],
    pronunciation: "/laʊndʒ/",
    exampleSentence: "We waited in the departure lounge.",
    exampleTranslationJa: "私たちは出発ラウンジで待った。",
    collocations: ["a departure lounge", "the hotel lounge", "lounge on the sofa"],
    mnemonic: "ゆったり座って過ごす部屋。動詞なら「だらりと過ごす」。",
    relatedWords: ["living room", "sofa", "relax"],
  },
  {
    id: "lunch",
    word: "lunch",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["昼食"],
    pronunciation: "/lʌntʃ/",
    exampleSentence: "We had lunch in a small café.",
    exampleTranslationJa: "小さなカフェで昼食をとった。",
    collocations: ["have lunch", "a packed lunch", "a lunch break"],
    mnemonic: "持参の弁当は packed lunch(英)。have lunch のように冠詞なしで使う。",
    relatedWords: ["breakfast", "dinner", "meal"],
  },
  {
    id: "mailbox",
    word: "mailbox",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["郵便受け、郵便ポスト(米)"],
    pronunciation: "/ˈmeɪlbɑːks/",
    exampleSentence: "There were three letters in the mailbox.",
    exampleTranslationJa: "郵便受けに手紙が3通入っていた。",
    collocations: ["check the mailbox", "an empty mailbox", "a full mailbox"],
    mnemonic: "米国語。英国では郵便受けが letterbox、投函する箱が postbox。",
    relatedWords: ["postbox", "letter", "post"],
  },
  {
    id: "mallet",
    word: "mallet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["木づち"],
    pronunciation: "/ˈmælɪt/",
    exampleSentence: "He tapped the peg in with a wooden mallet.",
    exampleTranslationJa: "彼は木づちでくいを打ちこんだ。",
    collocations: ["a wooden mallet", "tap with a mallet", "a rubber mallet"],
    mnemonic: "頭が木やゴムでできたつち。金属の hammer より当たりがやわらかい。",
    relatedWords: ["hammer", "peg", "tool"],
  },
  {
    id: "mantelpiece",
    word: "mantelpiece",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["暖炉の上の棚、マントルピース"],
    pronunciation: "/ˈmæntlpiːs/",
    exampleSentence: "Photographs stood along the mantelpiece.",
    exampleTranslationJa: "暖炉の上の棚に写真が並んでいた。",
    collocations: ["on the mantelpiece", "above the mantelpiece", "a stone mantelpiece"],
    mnemonic: "暖炉の上に渡した棚板。飾りや写真を置く場所。",
    relatedWords: ["fireplace", "shelf", "hearth"],
  },
  {
    id: "marble",
    word: "marble",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["大理石", "ビー玉"],
    pronunciation: "/ˈmɑːrbl/",
    exampleSentence: "The floor was made of white marble.",
    exampleTranslationJa: "床は白い大理石でできていた。",
    collocations: ["white marble", "a marble statue", "play marbles"],
    mnemonic: "磨くと光る石。同じ語でガラスのビー玉も指し、遊びは play marbles。",
    relatedWords: ["granite", "limestone", "statue"],
  },
  {
    id: "mascara",
    word: "mascara",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["マスカラ"],
    pronunciation: "/mæˈskærə/",
    exampleSentence: "Her mascara ran when she cried.",
    exampleTranslationJa: "泣いたときマスカラがにじんだ。",
    collocations: ["put on mascara", "waterproof mascara", "mascara runs"],
    mnemonic: "まつげに塗る化粧品。mask(覆う)と同じ語源。",
    relatedWords: ["lipstick", "makeup", "eyelash"],
  },
  {
    id: "mast",
    word: "mast",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(船の)マスト、帆柱", "(電波の)鉄塔"],
    pronunciation: "/mæst/",
    exampleSentence: "The flag flew from the top of the mast.",
    exampleTranslationJa: "旗がマストのてっぺんではためいていた。",
    collocations: ["the ship's mast", "climb the mast", "a radio mast"],
    mnemonic: "帆を張るための縦の柱。電波塔にも同じ語を使う。",
    relatedWords: ["sail", "ship", "pole"],
  },
  {
    id: "matchbox",
    word: "matchbox",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["マッチ箱"],
    pronunciation: "/ˈmætʃbɑːks/",
    exampleSentence: "He found an old matchbox in the drawer.",
    exampleTranslationJa: "彼は引き出しで古いマッチ箱を見つけた。",
    collocations: ["an empty matchbox", "a matchbox car", "strike a match on the matchbox"],
    mnemonic: "match(マッチ)+ box。とても小さいもののたとえにも使う。",
    relatedWords: ["match", "box", "fire"],
  },
  {
    id: "meal",
    word: "meal",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["食事"],
    pronunciation: "/miːl/",
    exampleSentence: "We had a light meal before the film.",
    exampleTranslationJa: "映画の前に軽い食事をとった。",
    collocations: ["a hot meal", "cook a meal", "three meals a day"],
    mnemonic: "朝昼晩をまとめて指す語。breakfast・lunch・dinner の総称。",
    relatedWords: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "mincer",
    word: "mincer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ひき肉器、ミンサー(英)"],
    pronunciation: "/ˈmɪnsər/",
    exampleSentence: "She put the beef through the mincer.",
    exampleTranslationJa: "彼女は牛肉をひき肉器にかけた。",
    collocations: ["put meat through a mincer", "an old mincer", "a hand mincer"],
    mnemonic: "mince(細かく刻む)+ -er。米国では meat grinder。",
    relatedWords: ["mince", "meat", "grinder"],
  },
  {
    id: "mitten",
    word: "mitten",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ミトン、親指だけ分かれた手袋"],
    pronunciation: "/ˈmɪtn/",
    exampleSentence: "The child lost one woollen mitten in the snow.",
    exampleTranslationJa: "その子は雪の中で毛糸のミトンを片方なくした。",
    collocations: ["a pair of mittens", "woollen mittens", "put on mittens"],
    mnemonic: "指が分かれた手袋は glove。親指だけ別れた形が mitten。",
    relatedWords: ["glove", "wool", "winter"],
  },
  {
    id: "mixer",
    word: "mixer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ミキサー、泡立て器具", "(飲み物の)割り材"],
    pronunciation: "/ˈmɪksər/",
    exampleSentence: "Beat the eggs with an electric mixer.",
    exampleTranslationJa: "電動ミキサーで卵を泡立てて。",
    collocations: ["an electric mixer", "a food mixer", "a cement mixer"],
    mnemonic: "mix(混ぜる)+ -er。液体を砕くものは blender と呼び分けることが多い。",
    relatedWords: ["blender", "whisk", "kitchen"],
  },
  {
    id: "moat",
    word: "moat",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["堀、外堀"],
    pronunciation: "/moʊt/",
    exampleSentence: "A deep moat surrounded the castle.",
    exampleTranslationJa: "深い堀が城を取り囲んでいた。",
    collocations: ["a deep moat", "cross the moat", "the castle moat"],
    mnemonic: "城の周りに水をたたえた溝。攻め手を近づけないための備え。",
    relatedWords: ["castle", "ditch", "fortress"],
  },
  {
    id: "moose",
    word: "moose",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヘラジカ"],
    pronunciation: "/muːs/",
    exampleSentence: "A moose stepped out of the forest.",
    exampleTranslationJa: "ヘラジカが森から出てきた。",
    collocations: ["a bull moose", "a moose crossing", "spot a moose"],
    mnemonic: "単数も複数も moose。ヨーロッパでは elk と呼ぶ。",
    relatedWords: ["deer", "reindeer", "forest"],
  },
  {
    id: "mosaic",
    word: "mosaic",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["モザイク(小片を並べた絵や模様)"],
    pronunciation: "/moʊˈzeɪɪk/",
    exampleSentence: "The floor was covered with a Roman mosaic.",
    exampleTranslationJa: "床はローマ時代のモザイクで覆われていた。",
    collocations: ["a mosaic floor", "a mosaic of tiles", "a colourful mosaic"],
    mnemonic: "小さなタイルを寄せて一枚の絵にする技法。寄せ集めの比喩にも使う。",
    relatedWords: ["tile", "pattern", "art"],
  },
  {
    id: "motorbike",
    word: "motorbike",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["オートバイ(英)"],
    pronunciation: "/ˈmoʊtərbaɪk/",
    exampleSentence: "He rides his motorbike to work.",
    exampleTranslationJa: "彼はオートバイで通勤している。",
    collocations: ["ride a motorbike", "a motorbike helmet", "a second hand motorbike"],
    mnemonic: "motor(発動機)+ bike。米国では motorcycle が普通。",
    relatedWords: ["motorcycle", "bicycle", "helmet"],
  },
  {
    id: "moustache",
    word: "moustache",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["口ひげ"],
    pronunciation: "/məˈstæʃ/",
    exampleSentence: "He grew a thick black moustache.",
    exampleTranslationJa: "彼は濃い黒い口ひげを伸ばした。",
    collocations: ["grow a moustache", "a thick moustache", "shave off a moustache"],
    mnemonic: "鼻の下の毛。あごひげは beard。米国つづりは mustache。",
    relatedWords: ["beard", "shave", "hair"],
  },
  {
    id: "mug",
    word: "mug",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["マグカップ", "(路上で)襲って奪う"],
    pronunciation: "/mʌɡ/",
    exampleSentence: "She poured tea into a large mug.",
    exampleTranslationJa: "彼女は大きなマグカップに紅茶を注いだ。",
    collocations: ["a mug of tea", "a coffee mug", "get mugged"],
    mnemonic: "取っ手つきで厚手の筒型。受け皿つきの薄いものは cup。",
    relatedWords: ["cup", "saucer", "tea"],
  },
  {
    id: "muggy",
    word: "muggy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["蒸し暑い"],
    pronunciation: "/ˈmʌɡi/",
    exampleSentence: "It was muggy and hard to sleep.",
    exampleTranslationJa: "蒸し暑くて眠りにくかった。",
    collocations: ["a muggy day", "muggy weather", "hot and muggy"],
    mnemonic: "humid よりくだけた言い方で、不快さの感じが強い。",
    relatedWords: ["humid", "damp", "sticky"],
  },
  {
    id: "mulberry",
    word: "mulberry",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["クワ、クワの実"],
    pronunciation: "/ˈmʌlberi/",
    exampleSentence: "Silkworms feed on mulberry leaves.",
    exampleTranslationJa: "カイコはクワの葉を食べる。",
    collocations: ["a mulberry tree", "mulberry leaves", "ripe mulberries"],
    mnemonic: "カイコを育てる木。実は黒紫で甘い。",
    relatedWords: ["berry", "silk", "tree"],
  },
  {
    id: "mussel",
    word: "mussel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ムール貝、イガイ"],
    pronunciation: "/ˈmʌsl/",
    exampleSentence: "We ate mussels cooked in white wine.",
    exampleTranslationJa: "白ワインで煮たムール貝を食べた。",
    collocations: ["a pot of mussels", "steamed mussels", "fresh mussels"],
    mnemonic: "筋肉の muscle と同じ発音。黒い殻の二枚貝。",
    relatedWords: ["oyster", "shellfish", "seafood"],
  },
  {
    id: "napkin",
    word: "napkin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ナプキン"],
    pronunciation: "/ˈnæpkɪn/",
    exampleSentence: "He wiped his mouth with a paper napkin.",
    exampleTranslationJa: "彼は紙ナプキンで口をぬぐった。",
    collocations: ["a paper napkin", "fold a napkin", "a linen napkin"],
    mnemonic: "英国では serviette とも。食卓で口や手をふく布や紙。",
    relatedWords: ["tissue", "tablecloth", "cutlery"],
  },
  {
    id: "neighbour",
    word: "neighbour",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["隣人、近所の人"],
    pronunciation: "/ˈneɪbər/",
    exampleSentence: "Our neighbour looks after the cat when we travel.",
    exampleTranslationJa: "旅行中は隣の人が猫の世話をしてくれる。",
    collocations: ["next door neighbour", "a friendly neighbour", "neighbouring countries"],
    mnemonic: "古英語 neah(近い)+ gebur(住む人)。米国つづりは neighbor。",
    relatedWords: ["neighbourhood", "resident", "community"],
  },
  {
    id: "notepad",
    word: "notepad",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["メモ帳"],
    pronunciation: "/ˈnoʊtpæd/",
    exampleSentence: "He wrote the number on a small notepad.",
    exampleTranslationJa: "彼は小さなメモ帳に番号を書いた。",
    collocations: ["a small notepad", "write on a notepad", "tear a page from a notepad"],
    mnemonic: "note(覚え書き)+ pad(とじた紙束)。とじた側から切り取って使う。",
    relatedWords: ["notebook", "paper", "note"],
  },
  {
    id: "nozzle",
    word: "nozzle",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(ホースなどの)筒先、ノズル"],
    pronunciation: "/ˈnɑːzl/",
    exampleSentence: "Point the nozzle away from your face.",
    exampleTranslationJa: "ノズルを顔から遠ざけて向けて。",
    collocations: ["a hose nozzle", "adjust the nozzle", "point the nozzle"],
    mnemonic: "nose(鼻)の小さい形から。細く絞って噴き出させる先端。",
    relatedWords: ["hose", "spray", "pipe"],
  },
  {
    id: "nutrient",
    word: "nutrient",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["栄養素"],
    pronunciation: "/ˈnuːtriənt/",
    exampleSentence: "Plants take nutrients from the soil.",
    exampleTranslationJa: "植物は土から栄養素を取り入れる。",
    collocations: ["essential nutrients", "rich in nutrients", "absorb nutrients"],
    mnemonic: "nutrition(栄養)と同じ語根。数えられる個々の成分を指す。",
    relatedWords: ["vitamin", "mineral", "nutrition"],
  },
  {
    id: "oatmeal",
    word: "oatmeal",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["オートミール、ひき割りオーツ麦"],
    pronunciation: "/ˈoʊtmiːl/",
    exampleSentence: "He eats oatmeal with milk every morning.",
    exampleTranslationJa: "彼は毎朝オートミールを牛乳で食べる。",
    collocations: ["a bowl of oatmeal", "oatmeal with milk", "instant oatmeal"],
    mnemonic: "oat(オーツ麦)+ meal(ひき割り)。煮たものは英国では porridge。",
    relatedWords: ["porridge", "cereal", "breakfast"],
  },
  {
    id: "octopus",
    word: "octopus",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["タコ"],
    pronunciation: "/ˈɑːktəpʊs/",
    exampleSentence: "An octopus hid among the rocks.",
    exampleTranslationJa: "タコが岩の間に隠れていた。",
    collocations: ["a giant octopus", "an octopus tentacle", "catch an octopus"],
    mnemonic: "octo-(8)+ pus(足)。October・octagon と同じ「8」の語根。",
    relatedWords: ["squid", "tentacle", "sea"],
  },
  {
    id: "omelette",
    word: "omelette",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["オムレツ"],
    pronunciation: "/ˈɑːmlət/",
    exampleSentence: "She made a cheese omelette for lunch.",
    exampleTranslationJa: "彼女は昼食にチーズのオムレツを作った。",
    collocations: ["a cheese omelette", "make an omelette", "a plain omelette"],
    mnemonic: "フランス語から。米国つづりは omelet。",
    relatedWords: ["egg", "pancake", "fry"],
  },
  {
    id: "onion",
    word: "onion",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["タマネギ"],
    pronunciation: "/ˈʌnjən/",
    exampleSentence: "Chopping onions always makes me cry.",
    exampleTranslationJa: "タマネギを刻むといつも涙が出る。",
    collocations: ["chop an onion", "a spring onion", "fried onions"],
    mnemonic: "ラテン語 unio(一つのもの)から。幾重にも重なるが球は一つ。",
    relatedWords: ["garlic", "vegetable", "carrot"],
  },
  {
    id: "orchard",
    word: "orchard",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["果樹園"],
    pronunciation: "/ˈɔːrtʃərd/",
    exampleSentence: "They picked apples in the orchard.",
    exampleTranslationJa: "彼らは果樹園でリンゴを摘んだ。",
    collocations: ["an apple orchard", "in the orchard", "a cherry orchard"],
    mnemonic: "果物の木を植えた畑。ぶどう畑は vineyard。",
    relatedWords: ["vineyard", "fruit", "farm"],
  },
  {
    id: "origami",
    word: "origami",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["折り紙"],
    pronunciation: "/ˌɔːrɪˈɡɑːmi/",
    exampleSentence: "She folded an origami crane in a minute.",
    exampleTranslationJa: "彼女は1分で折り紙の鶴を折った。",
    collocations: ["origami paper", "fold origami", "an origami crane"],
    mnemonic: "日本語がそのまま英語になった語。折ることは fold と言う。",
    relatedWords: ["fold", "paper", "crane"],
  },
  {
    id: "ornament",
    word: "ornament",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["飾り、装飾品"],
    pronunciation: "/ˈɔːrnəmənt/",
    exampleSentence: "Small ornaments stood on every shelf.",
    exampleTranslationJa: "どの棚にも小さな飾り物が置かれていた。",
    collocations: ["a china ornament", "Christmas ornaments", "a garden ornament"],
    mnemonic: "ラテン語 ornare(飾る)から。実用ではなく見せるための品。",
    relatedWords: ["decoration", "figure", "shelf"],
  },
  {
    id: "overcoat",
    word: "overcoat",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["オーバーコート、厚手の外套"],
    pronunciation: "/ˈoʊvərkoʊt/",
    exampleSentence: "He buttoned his overcoat against the cold.",
    exampleTranslationJa: "彼は寒さよけにオーバーのボタンを留めた。",
    collocations: ["a heavy overcoat", "put on an overcoat", "a woollen overcoat"],
    mnemonic: "over(上に)+ coat。他の服の上から着る丈の長い外套。",
    relatedWords: ["coat", "jacket", "winter"],
  },
  {
    id: "padlock",
    word: "padlock",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["南京錠", "南京錠をかける"],
    pronunciation: "/ˈpædlɑːk/",
    exampleSentence: "He fastened the gate with a heavy padlock.",
    exampleTranslationJa: "彼は重い南京錠で門を留めた。",
    collocations: ["a heavy padlock", "unlock a padlock", "padlock the gate"],
    mnemonic: "取り外しできる、U字の掛け金がついた錠。",
    relatedWords: ["lock", "key", "chain"],
  },
  {
    id: "pallet",
    word: "pallet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(荷を載せる)パレット、荷台"],
    pronunciation: "/ˈpælɪt/",
    exampleSentence: "Boxes were stacked on a wooden pallet.",
    exampleTranslationJa: "箱が木のパレットの上に積まれていた。",
    collocations: ["a wooden pallet", "stack on a pallet", "load a pallet"],
    mnemonic: "フォークリフトの爪を差しこめる台。絵の具板の palette とは別語。",
    relatedWords: ["crate", "warehouse", "forklift"],
  },
  {
    id: "pancake",
    word: "pancake",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パンケーキ、クレープ状の薄焼き"],
    pronunciation: "/ˈpænkeɪk/",
    exampleSentence: "He flipped the pancake in the air.",
    exampleTranslationJa: "彼はパンケーキを宙で返した。",
    collocations: ["flip a pancake", "a stack of pancakes", "Pancake Day"],
    mnemonic: "pan(平鍋)+ cake。英国のものは薄く、クレープに近い。",
    relatedWords: ["omelette", "batter", "syrup"],
  },
  {
    id: "pane",
    word: "pane",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["窓ガラスの一枚"],
    pronunciation: "/peɪn/",
    exampleSentence: "A single pane of glass had cracked.",
    exampleTranslationJa: "窓ガラスが一枚ひび割れていた。",
    collocations: ["a pane of glass", "a broken pane", "double glazed panes"],
    mnemonic: "痛みの pain と同音。枠にはまったガラス1枚を指す。",
    relatedWords: ["window", "glass", "frame"],
  },
  {
    id: "pantry",
    word: "pantry",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["食品庫、パントリー"],
    pronunciation: "/ˈpæntri/",
    exampleSentence: "There was plenty of rice in the pantry.",
    exampleTranslationJa: "食品庫には米がたっぷりあった。",
    collocations: ["a well stocked pantry", "in the pantry", "a walk in pantry"],
    mnemonic: "ラテン語 panis(パン)から。もとはパンをしまう小部屋。",
    relatedWords: ["cupboard", "larder", "kitchen"],
  },
  {
    id: "paperclip",
    word: "paperclip",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["クリップ、紙ばさみ"],
    pronunciation: "/ˈpeɪpərklɪp/",
    exampleSentence: "She held the pages together with a paperclip.",
    exampleTranslationJa: "彼女はクリップでページをまとめた。",
    collocations: ["a metal paperclip", "hold with a paperclip", "a box of paperclips"],
    mnemonic: "paper(紙)+ clip(はさむもの)。ホチキスは stapler で別物。",
    relatedWords: ["stapler", "clip", "paper"],
  },
  {
    id: "parachute",
    word: "parachute",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["パラシュート", "パラシュートで降りる"],
    pronunciation: "/ˈpærəʃuːt/",
    exampleSentence: "His parachute opened a few seconds later.",
    exampleTranslationJa: "数秒後に彼のパラシュートが開いた。",
    collocations: ["open a parachute", "a parachute jump", "parachute into an area"],
    mnemonic: "para-(防ぐ)+ chute(落下)。落下を防ぐもの、が原義。",
    relatedWords: ["jump", "aircraft", "fall"],
  },
  {
    id: "parasol",
    word: "parasol",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["日傘、パラソル"],
    pronunciation: "/ˈpærəsɔːl/",
    exampleSentence: "A striped parasol shaded the table.",
    exampleTranslationJa: "縞のパラソルがテーブルに日陰を作っていた。",
    collocations: ["a beach parasol", "under the parasol", "put up a parasol"],
    mnemonic: "para-(防ぐ)+ sol(太陽)。雨を防ぐのは umbrella。",
    relatedWords: ["umbrella", "shade", "sun"],
  },
  {
    id: "parcel",
    word: "parcel",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["小包(英)"],
    pronunciation: "/ˈpɑːrsl/",
    exampleSentence: "A parcel arrived for you this morning.",
    exampleTranslationJa: "今朝あなた宛ての小包が届いた。",
    collocations: ["send a parcel", "a parcel arrives", "wrap a parcel"],
    mnemonic: "英国語。米国では package。part(部分)と同じ語源。",
    relatedWords: ["package", "post", "delivery"],
  },
  {
    id: "parsnip",
    word: "parsnip",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["パースニップ(白いニンジンに似た根菜)"],
    pronunciation: "/ˈpɑːrsnɪp/",
    exampleSentence: "Roast parsnips are served with the meat.",
    exampleTranslationJa: "焼いたパースニップが肉に添えられる。",
    collocations: ["roast parsnips", "peel a parsnip", "parsnip soup"],
    mnemonic: "白く太い根菜で、carrot より甘みが強い。英国の定番の付け合わせ。",
    relatedWords: ["carrot", "turnip", "vegetable"],
  },
]
