import type { VocabularyEntry } from '../types'

// 増補 第12弾。論説・報道でよく出る抽象名詞。定型の言い回し(on the brink of, in jeopardy など)を
// 覚えるヒントとコロケーションに入れて、形ごと覚えられるようにする。
export const plus12: VocabularyEntry[] = [
  {
    id: "adversity",
    word: "adversity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["逆境、苦難"],
    pronunciation: "/ədˈvɜːrsəti/",
    exampleSentence: "She showed courage in the face of adversity.",
    exampleTranslationJa: "彼女は逆境にあって勇気を示した。",
    collocations: ["in the face of adversity", "overcome adversity"],
    wordFormation: "adverse(逆の)+ -ity。",
    mnemonic: "adverse(不利な)の名詞形。in the face of adversity が定型。",
    relatedWords: ["hardship", "misfortune", "struggle"],
  },
  {
    id: "affinity",
    word: "affinity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["親近感", "(化学の)親和性"],
    pronunciation: "/əˈfɪnəti/",
    exampleSentence: "He feels a strong affinity with the sea.",
    exampleTranslationJa: "彼は海に強い親近感を覚える。",
    collocations: ["an affinity with", "a natural affinity for"],
    wordFormation: "ad-(〜へ)+ finis(境)。「境を接している」。",
    mnemonic: "「境を接するほど近い」が原義。人にも物質にも使う。",
    relatedWords: ["attraction", "bond", "kinship"],
  },
  {
    id: "allegiance",
    word: "allegiance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["忠誠"],
    pronunciation: "/əˈliːdʒəns/",
    exampleSentence: "They swore allegiance to the new king.",
    exampleTranslationJa: "彼らは新しい王に忠誠を誓った。",
    collocations: ["swear allegiance", "owe allegiance to", "shift allegiance"],
    mnemonic: "liege(君主)から。国・党・チームへの忠誠に使う。",
    relatedWords: ["loyalty", "devotion", "fidelity"],
  },
  {
    id: "allure",
    word: "allure",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["魅力、人を引きつける力"],
    pronunciation: "/əˈlʊr/",
    exampleSentence: "The allure of the big city drew her north.",
    exampleTranslationJa: "大都市の魅力が彼女を北へ引き寄せた。",
    collocations: ["the allure of", "lose its allure", "a certain allure"],
    mnemonic: "lure(おびき寄せる)が中にある。抗いがたい引力。",
    relatedWords: ["attraction", "charm", "appeal"],
  },
  {
    id: "anguish",
    word: "anguish",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["深い苦悩、苦痛"],
    pronunciation: "/ˈæŋɡwɪʃ/",
    exampleSentence: "Her face was full of anguish.",
    exampleTranslationJa: "彼女の顔は苦悩に満ちていた。",
    collocations: ["mental anguish", "in anguish", "cry out in anguish"],
    wordFormation: "ラテン語 angustus(狭い)から。anxiety と同語根。",
    mnemonic: "anxiety と同語根で「胸が締めつけられる」。pain より心の苦しみ。",
    relatedWords: ["agony", "distress", "suffering"],
  },
  {
    id: "apathy",
    word: "apathy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["無関心、無気力"],
    pronunciation: "/ˈæpəθi/",
    exampleSentence: "Voter apathy is the party's biggest worry.",
    exampleTranslationJa: "有権者の無関心がその党の最大の悩みだ。",
    collocations: ["voter apathy", "public apathy", "widespread apathy"],
    wordFormation: "a-(なし)+ pathos(感情)。",
    mnemonic: "sympathy と同語根。感情が動かないこと。形容詞は apathetic。",
    relatedWords: ["indifference", "apathetic", "enthusiasm"],
  },
  {
    id: "ardour",
    word: "ardour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["熱意、情熱"],
    pronunciation: "/ˈɑːrdər/",
    exampleSentence: "He spoke with the ardour of a convert.",
    exampleTranslationJa: "彼は改宗者のような熱意で語った。",
    collocations: ["revolutionary ardour", "with ardour"],
    wordFormation: "ラテン語 ardere(燃える)から。",
    mnemonic: "米つづりは ardor。「燃える」が語根で、arson(放火)と親戚。",
    relatedWords: ["passion", "zeal", "enthusiasm"],
  },
  {
    id: "aversion",
    word: "aversion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["嫌悪、忌避"],
    pronunciation: "/əˈvɜːrʒn/",
    exampleSentence: "He has a strong aversion to crowds.",
    exampleTranslationJa: "彼は人ごみが大の苦手だ。",
    collocations: ["an aversion to", "a deep aversion", "risk aversion"],
    wordFormation: "a-(離れて)+ vertere(向ける)。",
    mnemonic: "avert と同語根。「目をそらしたくなるほど嫌」。",
    relatedWords: ["dislike", "hatred", "liking"],
  },
  {
    id: "backbone",
    word: "backbone",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["背骨", "中核", "気骨"],
    pronunciation: "/ˈbækboʊn/",
    exampleSentence: "Small firms are the backbone of the economy.",
    exampleTranslationJa: "中小企業は経済の中核だ。",
    collocations: ["the backbone of", "lack the backbone to", "have no backbone"],
    wordFormation: "back(背)+ bone(骨)。",
    mnemonic: "組織を支える中核。have no backbone は「気骨がない」。",
    relatedWords: ["spine", "core", "courage"],
  },
  {
    id: "bearing",
    word: "bearing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["関係、影響", "身のこなし", "方位"],
    pronunciation: "/ˈberɪŋ/",
    exampleSentence: "That has no bearing on the decision.",
    exampleTranslationJa: "それはその決定に関係がない。",
    collocations: ["have no bearing on", "get your bearings", "a dignified bearing"],
    mnemonic: "have a bearing on ... で「〜に関係する」。get your bearings は「現在地をつかむ」。",
    relatedWords: ["relevance", "posture", "direction"],
  },
  {
    id: "blueprint",
    word: "blueprint",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["青写真、設計図", "構想"],
    pronunciation: "/ˈbluːprɪnt/",
    exampleSentence: "The report is a blueprint for reform.",
    exampleTranslationJa: "その報告書は改革の青写真だ。",
    collocations: ["a blueprint for", "draw up a blueprint"],
    wordFormation: "blue(青)+ print(印刷)。昔の複写が青地だったことから。",
    mnemonic: "昔の設計図が青地に白線だったことから。今は「構想」の比喩が主。",
    relatedWords: ["plan", "design", "scheme"],
  },
  {
    id: "bout",
    word: "bout",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(病気などの)一時的な発作", "一勝負"],
    pronunciation: "/baʊt/",
    exampleSentence: "She had a bad bout of flu in January.",
    exampleTranslationJa: "彼女は1月にひどいインフルエンザにかかった。",
    collocations: ["a bout of flu", "a drinking bout", "a boxing bout"],
    mnemonic: "a bout of ... で「一時的な〜の期間」。病気にも気分にも使う。",
    relatedWords: ["attack", "spell", "episode"],
  },
  {
    id: "brink",
    word: "brink",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["瀬戸際、ふち"],
    pronunciation: "/brɪŋk/",
    exampleSentence: "The company was on the brink of collapse.",
    exampleTranslationJa: "その会社は倒産の瀬戸際にあった。",
    collocations: ["on the brink of", "pull back from the brink"],
    mnemonic: "on the brink of ... の形でほぼ決まって使う。edge のかたい語。",
    relatedWords: ["edge", "verge", "threshold"],
  },
  {
    id: "calibre",
    word: "calibre",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["力量、水準", "(銃の)口径"],
    pronunciation: "/ˈkælɪbər/",
    exampleSentence: "We need staff of the highest calibre.",
    exampleTranslationJa: "最高水準の人材が必要だ。",
    collocations: ["of high calibre", "the calibre of the candidates"],
    mnemonic: "米つづりは caliber。銃の口径から、人の「器」へ。",
    relatedWords: ["quality", "standard", "ability"],
  },
  {
    id: "chore",
    word: "chore",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["雑用、面倒な仕事"],
    pronunciation: "/tʃɔːr/",
    exampleSentence: "Washing up is my least favourite chore.",
    exampleTranslationJa: "皿洗いは一番いやな雑用だ。",
    collocations: ["household chores", "do the chores", "a real chore"],
    mnemonic: "家事の雑用が典型。「気の進まない決まりごと」の含み。",
    relatedWords: ["task", "duty", "housework"],
  },
  {
    id: "cohesion",
    word: "cohesion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["まとまり、結束"],
    pronunciation: "/koʊˈhiːʒn/",
    exampleSentence: "Sport can build social cohesion.",
    exampleTranslationJa: "スポーツは社会の結束を育てうる。",
    collocations: ["social cohesion", "team cohesion", "a lack of cohesion"],
    wordFormation: "co-(共に)+ haerere(くっつく)。adhere と同語根。",
    mnemonic: "adhere(くっつく)と同語根。文章の「つながり」にも使う。",
    relatedWords: ["unity", "solidarity", "adhesion"],
  },
  {
    id: "condolence",
    word: "condolence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["お悔やみ"],
    pronunciation: "/kənˈdoʊləns/",
    exampleSentence: "Please accept my condolences.",
    exampleTranslationJa: "お悔やみ申し上げます。",
    collocations: ["offer your condolences", "a letter of condolence"],
    wordFormation: "con-(共に)+ dolere(悲しむ)。",
    mnemonic: "「共に悲しむ」。お悔やみの場面ではふつう複数形 condolences。",
    relatedWords: ["sympathy", "sorrow", "comfort"],
  },
  {
    id: "conjunction",
    word: "conjunction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["接続詞", "組み合わせ"],
    pronunciation: "/kənˈdʒʌŋkʃn/",
    exampleSentence: "Use the app in conjunction with the website.",
    exampleTranslationJa: "そのアプリはサイトと併せてお使いください。",
    collocations: ["in conjunction with", "a coordinating conjunction"],
    wordFormation: "con-(共に)+ junct(つなぐ)。join と同語根。",
    mnemonic: "in conjunction with ... で「〜と併せて」。文法用語でもある。",
    relatedWords: ["combination", "and", "junction"],
  },
  {
    id: "contour",
    word: "contour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["輪郭、等高線"],
    pronunciation: "/ˈkɑːntʊr/",
    exampleSentence: "The map shows the contours of the hills.",
    exampleTranslationJa: "その地図は丘の等高線を示している。",
    collocations: ["the contours of", "a contour line", "follow the contours"],
    mnemonic: "地形図の等高線から、物や議論の「大まかな形」へ。",
    relatedWords: ["outline", "shape", "profile"],
  },
  {
    id: "curb",
    word: "curb",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["抑制", "抑える"],
    pronunciation: "/kɜːrb/",
    exampleSentence: "New rules curb the use of plastic.",
    exampleTranslationJa: "新しい規則がプラスチックの使用を抑える。",
    collocations: ["curb spending", "curb inflation", "put a curb on"],
    mnemonic: "米では歩道の縁石も curb(英は kerb)。抑える意味では英米共通。",
    relatedWords: ["restrain", "control", "limit"],
  },
  {
    id: "deadlock",
    word: "deadlock",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["行き詰まり、こう着状態"],
    pronunciation: "/ˈdedlɑːk/",
    exampleSentence: "The talks ended in deadlock.",
    exampleTranslationJa: "その交渉は行き詰まりに終わった。",
    collocations: ["break the deadlock", "reach a deadlock", "end in deadlock"],
    wordFormation: "dead(動かない)+ lock(錠)。",
    mnemonic: "どちらも譲らず動けない状態。break the deadlock は「打開する」。",
    relatedWords: ["stalemate", "impasse", "standstill"],
  },
  {
    id: "delusion",
    word: "delusion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["思い込み、妄想"],
    pronunciation: "/dɪˈluːʒn/",
    exampleSentence: "He is under the delusion that he is popular.",
    exampleTranslationJa: "彼は自分が人気者だと思い込んでいる。",
    collocations: ["under the delusion that", "delusions of grandeur"],
    wordFormation: "de-(すっかり)+ ludere(だます)。illusion と同語根。",
    mnemonic: "illusion が「錯覚」、delusion は「事実に反すると分かる思い込み」。",
    relatedWords: ["illusion", "misconception", "fantasy"],
  },
  {
    id: "destiny",
    word: "destiny",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["運命、宿命"],
    pronunciation: "/ˈdestəni/",
    exampleSentence: "She believes she controls her own destiny.",
    exampleTranslationJa: "彼女は自分の運命は自分で決めると信じている。",
    collocations: ["control your destiny", "a sense of destiny", "manifest destiny"],
    mnemonic: "fate が避けられない運命、destiny は「向かうべき先」で前向きな含み。",
    relatedWords: ["fate", "fortune", "future"],
  },
  {
    id: "detriment",
    word: "detriment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["損害、不利益"],
    pronunciation: "/ˈdetrɪmənt/",
    exampleSentence: "He worked late, to the detriment of his health.",
    exampleTranslationJa: "彼は遅くまで働き、健康を損なった。",
    collocations: ["to the detriment of", "without detriment to"],
    mnemonic: "to the detriment of ... で「〜を犠牲にして」。形容詞は detrimental。",
    relatedWords: ["harm", "damage", "disadvantage"],
  },
  {
    id: "disgrace",
    word: "disgrace",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["不名誉、恥", "面目を失わせる"],
    pronunciation: "/dɪsˈɡreɪs/",
    exampleSentence: "He resigned in disgrace.",
    exampleTranslationJa: "彼は不名誉のうちに辞任した。",
    collocations: ["in disgrace", "bring disgrace on", "a national disgrace"],
    wordFormation: "dis-(否定)+ grace(名誉・恵み)。",
    mnemonic: "grace(名誉)を失うこと。It is a disgrace. は強い非難。",
    relatedWords: ["shame", "dishonour", "humiliation"],
  },
  {
    id: "disguise",
    word: "disguise",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["変装", "偽装する、隠す"],
    pronunciation: "/dɪsˈɡaɪz/",
    exampleSentence: "He could not disguise his disappointment.",
    exampleTranslationJa: "彼は落胆を隠しきれなかった。",
    collocations: ["in disguise", "a blessing in disguise", "disguise your feelings"],
    mnemonic: "a blessing in disguise は「災い転じて福となる」。感情を隠す意味も重要。",
    relatedWords: ["conceal", "mask", "camouflage"],
  },
  {
    id: "distraction",
    word: "distraction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["気を散らすもの", "気晴らし"],
    pronunciation: "/dɪˈstrækʃn/",
    exampleSentence: "The noise is a constant distraction.",
    exampleTranslationJa: "その音はずっと気を散らす原因になっている。",
    collocations: ["a welcome distraction", "drive to distraction", "avoid distractions"],
    wordFormation: "dis-(離れて)+ trahere(引く)。attract と同語根。",
    mnemonic: "注意を「引き離す」もの。drive someone to distraction は「気を狂わせる」。",
    relatedWords: ["diversion", "interruption", "focus"],
  },
  {
    id: "downfall",
    word: "downfall",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["失脚、破滅の原因"],
    pronunciation: "/ˈdaʊnfɔːl/",
    exampleSentence: "Greed was his downfall.",
    exampleTranslationJa: "強欲が彼の身を滅ぼした。",
    collocations: ["lead to his downfall", "be your downfall"],
    wordFormation: "down(下へ)+ fall(落ちる)。",
    mnemonic: "地位から落ちること、またその原因。",
    relatedWords: ["ruin", "collapse", "failure"],
  },
  {
    id: "eligibility",
    word: "eligibility",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["資格があること"],
    pronunciation: "/ˌelɪdʒəˈbɪləti/",
    exampleSentence: "Check your eligibility before you apply.",
    exampleTranslationJa: "申請の前に資格を確認してください。",
    collocations: ["eligibility criteria", "check your eligibility"],
    wordFormation: "eligible(資格のある)+ -ity。",
    mnemonic: "制度や給付の「対象になるかどうか」。eligibility criteria が定型。",
    relatedWords: ["qualification", "entitlement", "eligible"],
  },
  {
    id: "envy",
    word: "envy",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ねたみ、うらやみ", "うらやむ"],
    pronunciation: "/ˈenvi/",
    exampleSentence: "I envy your ability to sleep anywhere.",
    exampleTranslationJa: "どこでも眠れる君の才能がうらやましい。",
    collocations: ["green with envy", "the envy of", "envy someone"],
    mnemonic: "green with envy は「うらやましさで顔が青くなる」。形容詞は envious。",
    relatedWords: ["jealousy", "envious", "covet"],
  },
  {
    id: "equilibrium",
    word: "equilibrium",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["均衡、平衡"],
    pronunciation: "/ˌiːkwɪˈlɪbriəm/",
    exampleSentence: "The market found a new equilibrium.",
    exampleTranslationJa: "市場は新たな均衡を見いだした。",
    collocations: ["maintain equilibrium", "restore equilibrium", "in equilibrium"],
    wordFormation: "equi-(等しい)+ libra(はかり)。",
    mnemonic: "equal(等しい)+ はかり。左右が釣り合っている状態。",
    relatedWords: ["balance", "stability", "harmony"],
  },
  {
    id: "esteem",
    word: "esteem",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["尊敬、評価", "高く評価する"],
    pronunciation: "/ɪˈstiːm/",
    exampleSentence: "She is held in high esteem by her colleagues.",
    exampleTranslationJa: "彼女は同僚から高く評価されている。",
    collocations: ["hold in high esteem", "self-esteem", "low self-esteem"],
    wordFormation: "ラテン語 aestimare(値をつける)から。estimate と同語根。",
    mnemonic: "estimate(見積もる)と同語根。self-esteem(自尊心)で覚えるとよい。",
    relatedWords: ["respect", "regard", "estimate"],
  },
  {
    id: "euphoria",
    word: "euphoria",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["強い高揚感、多幸感"],
    pronunciation: "/juːˈfɔːriə/",
    exampleSentence: "The euphoria after the win did not last.",
    exampleTranslationJa: "勝利のあとの高揚は長続きしなかった。",
    collocations: ["a sense of euphoria", "post-election euphoria"],
    wordFormation: "eu-(よい)+ pherein(運ぶ)。",
    mnemonic: "eu(よい)は euphemism・eulogy と共通。「よい気分に運ばれる」。",
    relatedWords: ["elation", "joy", "excitement"],
  },
  {
    id: "famine",
    word: "famine",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["飢饉(ききん)"],
    pronunciation: "/ˈfæmɪn/",
    exampleSentence: "Drought led to famine across the region.",
    exampleTranslationJa: "干ばつがその地域全体に飢饉をもたらした。",
    collocations: ["a severe famine", "famine relief", "the threat of famine"],
    mnemonic: "個人の空腹は hunger、社会規模の食料不足が famine。",
    relatedWords: ["hunger", "starvation", "drought"],
  },
  {
    id: "fatigue",
    word: "fatigue",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["疲労", "(金属の)疲労"],
    pronunciation: "/fəˈtiːɡ/",
    exampleSentence: "Fatigue is a common side effect.",
    exampleTranslationJa: "疲労はよくある副作用だ。",
    collocations: ["chronic fatigue", "mental fatigue", "metal fatigue"],
    mnemonic: "アクセントは後ろ /fəˈtiːɡ/。金属疲労も metal fatigue。",
    relatedWords: ["tiredness", "exhaustion", "weariness"],
  },
  {
    id: "fervour",
    word: "fervour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["熱情、熱烈さ"],
    pronunciation: "/ˈfɜːrvər/",
    exampleSentence: "He defended the plan with religious fervour.",
    exampleTranslationJa: "彼は宗教的な熱情でその計画を擁護した。",
    collocations: ["religious fervour", "with great fervour"],
    wordFormation: "ラテン語 fervere(沸く)から。",
    mnemonic: "米つづりは fervor。「沸き立つ」が語根。ardour とほぼ同じ。",
    relatedWords: ["passion", "zeal", "ardour"],
  },
  {
    id: "flair",
    word: "flair",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["才能、センス"],
    pronunciation: "/fler/",
    exampleSentence: "She has a flair for languages.",
    exampleTranslationJa: "彼女は語学の才がある。",
    collocations: ["a flair for", "artistic flair", "show flair"],
    mnemonic: "a flair for ... の形。生まれつきの「勘のよさ」を指す。",
    relatedWords: ["talent", "knack", "aptitude"],
  },
  {
    id: "fluctuation",
    word: "fluctuation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["変動"],
    pronunciation: "/ˌflʌktʃuˈeɪʃn/",
    exampleSentence: "Price fluctuations make planning hard.",
    exampleTranslationJa: "価格の変動が計画を難しくする。",
    collocations: ["price fluctuations", "seasonal fluctuation"],
    wordFormation: "fluctuate(変動する)+ -ion。",
    mnemonic: "波(fluctus)が語根。上下を繰り返す変化。",
    relatedWords: ["variation", "swing", "change"],
  },
  {
    id: "foresight",
    word: "foresight",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["先を見通す力"],
    pronunciation: "/ˈfɔːrsaɪt/",
    exampleSentence: "He had the foresight to buy land early.",
    exampleTranslationJa: "彼には早くに土地を買う先見の明があった。",
    collocations: ["have the foresight to", "with hindsight and foresight"],
    wordFormation: "fore-(前もって)+ sight(見ること)。",
    mnemonic: "hindsight(あとから分かること)と対で覚える。",
    relatedWords: ["vision", "hindsight", "prudence"],
  },
  {
    id: "fortitude",
    word: "fortitude",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不屈の精神、我慢強さ"],
    pronunciation: "/ˈfɔːrtɪtuːd/",
    exampleSentence: "She bore the pain with great fortitude.",
    exampleTranslationJa: "彼女はその痛みに耐え抜いた。",
    collocations: ["with fortitude", "show fortitude", "moral fortitude"],
    wordFormation: "ラテン語 fortis(強い)から。fort・effort と同語根。",
    mnemonic: "fort(とりで)と同語根。苦しみに静かに耐える強さ。",
    relatedWords: ["courage", "endurance", "resilience"],
  },
  {
    id: "frenzy",
    word: "frenzy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["熱狂、逆上"],
    pronunciation: "/ˈfrenzi/",
    exampleSentence: "The announcement caused a media frenzy.",
    exampleTranslationJa: "その発表は報道の過熱を招いた。",
    collocations: ["a feeding frenzy", "whip into a frenzy", "a media frenzy"],
    mnemonic: "我を忘れた興奮。frantic(取り乱した)と同語根。",
    relatedWords: ["hysteria", "craze", "excitement"],
  },
  {
    id: "fringe",
    word: "fringe",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["へり、周辺", "前髪"],
    pronunciation: "/frɪndʒ/",
    exampleSentence: "The party is on the fringe of politics.",
    exampleTranslationJa: "その党は政治の周縁にある。",
    collocations: ["on the fringe of", "fringe benefits", "the fringe of the crowd"],
    mnemonic: "fringe benefits は「給与以外の待遇」。中心から外れた部分。",
    relatedWords: ["edge", "margin", "periphery"],
  },
  {
    id: "fusion",
    word: "fusion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["融合", "(核)融合"],
    pronunciation: "/ˈfjuːʒn/",
    exampleSentence: "The dish is a fusion of two traditions.",
    exampleTranslationJa: "その料理は二つの伝統の融合だ。",
    collocations: ["a fusion of", "nuclear fusion", "fusion cuisine"],
    wordFormation: "ラテン語 fundere(注ぐ・溶かす)から。",
    mnemonic: "溶け合って一つになること。分裂は fission。",
    relatedWords: ["merger", "blend", "fission"],
  },
  {
    id: "gist",
    word: "gist",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["要点、大意"],
    pronunciation: "/dʒɪst/",
    exampleSentence: "I did not catch every word, but I got the gist.",
    exampleTranslationJa: "全部は聞き取れなかったが、要点はつかんだ。",
    collocations: ["get the gist", "the gist of", "the general gist"],
    mnemonic: "get the gist(要点をつかむ)の形で覚える。g は /dʒ/。",
    relatedWords: ["essence", "summary", "point"],
  },
  {
    id: "glimmer",
    word: "glimmer",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["かすかな光", "かすかに光る"],
    pronunciation: "/ˈɡlɪmər/",
    exampleSentence: "There is a glimmer of hope.",
    exampleTranslationJa: "かすかな希望がある。",
    collocations: ["a glimmer of hope", "a glimmer of light"],
    mnemonic: "a glimmer of hope(一筋の希望)がほぼ決まり文句。",
    relatedWords: ["gleam", "flicker", "spark"],
  },
  {
    id: "grievance",
    word: "grievance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不満、苦情"],
    pronunciation: "/ˈɡriːvəns/",
    exampleSentence: "Staff can raise a grievance with the union.",
    exampleTranslationJa: "職員は組合に苦情を申し立てられる。",
    collocations: ["air a grievance", "a grievance procedure", "a legitimate grievance"],
    wordFormation: "grieve(嘆く)+ -ance。",
    mnemonic: "職場の正式な「苦情申し立て」に使う。complaint より重い。",
    relatedWords: ["complaint", "protest", "grudge"],
  },
  {
    id: "gulf",
    word: "gulf",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大きな隔たり", "湾"],
    pronunciation: "/ɡʌlf/",
    exampleSentence: "There is a widening gulf between rich and poor.",
    exampleTranslationJa: "富裕層と貧困層の隔たりは広がっている。",
    collocations: ["a widening gulf", "the gulf between", "bridge the gulf"],
    mnemonic: "地理の「湾」と、埋めがたい「溝」の両方。gap より大きい。",
    relatedWords: ["gap", "chasm", "divide"],
  },
  {
    id: "haven",
    word: "haven",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["避難所、安息の場"],
    pronunciation: "/ˈheɪvn/",
    exampleSentence: "The library is a haven for students.",
    exampleTranslationJa: "その図書館は学生の憩いの場だ。",
    collocations: ["a safe haven", "a tax haven", "a haven for"],
    mnemonic: "a tax haven は「租税回避地」。heaven(天国)とは別語。",
    relatedWords: ["refuge", "sanctuary", "shelter"],
  },
  {
    id: "hindrance",
    word: "hindrance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["妨げ、じゃま"],
    pronunciation: "/ˈhɪndrəns/",
    exampleSentence: "The rules are more a hindrance than a help.",
    exampleTranslationJa: "その規則は助けというより妨げだ。",
    collocations: ["a hindrance to", "more a hindrance than a help"],
    wordFormation: "hinder(妨げる)+ -ance。",
    mnemonic: "hinder の名詞形。つづりに e が入らないのに注意。",
    relatedWords: ["obstacle", "obstruction", "help"],
  },
  {
    id: "hoax",
    word: "hoax",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["でっち上げ、いたずら"],
    pronunciation: "/hoʊks/",
    exampleSentence: "The bomb threat turned out to be a hoax.",
    exampleTranslationJa: "その爆破予告はいたずらだった。",
    collocations: ["a bomb hoax", "turn out to be a hoax", "a hoax call"],
    mnemonic: "人をだますための作り話や偽情報。scam(詐欺)は金銭目的。",
    relatedWords: ["trick", "deception", "fake"],
  },
  {
    id: "hub",
    word: "hub",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["中心、拠点"],
    pronunciation: "/hʌb/",
    exampleSentence: "The city is a hub for start-ups.",
    exampleTranslationJa: "その都市は新興企業の拠点だ。",
    collocations: ["a transport hub", "a hub for", "the hub of"],
    mnemonic: "車輪の中心の軸が原義。そこから路線や活動の「中枢」へ。",
    relatedWords: ["centre", "core", "focal point"],
  },
  {
    id: "hunch",
    word: "hunch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["勘、予感"],
    pronunciation: "/hʌntʃ/",
    exampleSentence: "I had a hunch she would say no.",
    exampleTranslationJa: "彼女は断るだろうという勘があった。",
    collocations: ["have a hunch", "play a hunch", "act on a hunch"],
    mnemonic: "根拠はないが当たりそうな感じ。動詞では「背を丸める」。",
    relatedWords: ["intuition", "feeling", "guess"],
  },
  {
    id: "hurdle",
    word: "hurdle",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["障害、乗り越えるべき壁"],
    pronunciation: "/ˈhɜːrdl/",
    exampleSentence: "Funding is the first hurdle.",
    exampleTranslationJa: "資金集めが最初の壁だ。",
    collocations: ["clear a hurdle", "the final hurdle", "overcome hurdles"],
    mnemonic: "陸上競技のハードルから。clear a hurdle は「関門を越える」。",
    relatedWords: ["obstacle", "barrier", "challenge"],
  },
  {
    id: "impetus",
    word: "impetus",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["はずみ、推進力"],
    pronunciation: "/ˈɪmpətəs/",
    exampleSentence: "The award gave fresh impetus to the campaign.",
    exampleTranslationJa: "その受賞は運動に新たなはずみを与えた。",
    collocations: ["give impetus to", "provide the impetus", "fresh impetus"],
    wordFormation: "im-(中へ)+ petere(向かう)。",
    mnemonic: "give impetus to ... で「〜を後押しする」。momentum に近い。",
    relatedWords: ["momentum", "stimulus", "drive"],
  },
  {
    id: "imprint",
    word: "imprint",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["刻印、跡", "刻みつける"],
    pronunciation: "/ˈɪmprɪnt/",
    exampleSentence: "The event left an imprint on a whole generation.",
    exampleTranslationJa: "その出来事は一世代全体に刻印を残した。",
    collocations: ["leave an imprint", "an imprint on", "imprint on the memory"],
    wordFormation: "im-(中に)+ print(押す)。",
    mnemonic: "物理的な跡と、記憶に残る印象の両方。",
    relatedWords: ["mark", "impression", "stamp"],
  },
  {
    id: "impulse",
    word: "impulse",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["衝動", "(電気の)パルス"],
    pronunciation: "/ˈɪmpʌls/",
    exampleSentence: "She bought it on impulse.",
    exampleTranslationJa: "彼女は衝動でそれを買った。",
    collocations: ["on impulse", "resist the impulse", "an impulse buy"],
    wordFormation: "im-(中へ)+ pellere(押す)。propel と同語根。",
    mnemonic: "on impulse(衝動的に)の形で覚える。形容詞は impulsive。",
    relatedWords: ["urge", "instinct", "impulsive"],
  },
  {
    id: "inclination",
    word: "inclination",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["傾向、意向", "傾き"],
    pronunciation: "/ˌɪnklɪˈneɪʃn/",
    exampleSentence: "I have no inclination to argue.",
    exampleTranslationJa: "言い争う気はない。",
    collocations: ["have no inclination to", "a natural inclination", "an inclination towards"],
    wordFormation: "incline(傾く)+ -ation。",
    mnemonic: "「心が傾く」から「〜したい気持ち」。have no inclination to ... が実用。",
    relatedWords: ["tendency", "desire", "incline"],
  },
  {
    id: "influx",
    word: "influx",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["流入、殺到"],
    pronunciation: "/ˈɪnflʌks/",
    exampleSentence: "The town saw an influx of visitors.",
    exampleTranslationJa: "その町には来訪者が押し寄せた。",
    collocations: ["an influx of", "a sudden influx", "stem the influx"],
    wordFormation: "in-(中へ)+ flux(流れ)。",
    mnemonic: "fluid・flow と同語根。人・金・物が一気に入ってくること。",
    relatedWords: ["inflow", "arrival", "outflow"],
  },
  {
    id: "intuition",
    word: "intuition",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["直感"],
    pronunciation: "/ˌɪntuˈɪʃn/",
    exampleSentence: "Her intuition told her something was wrong.",
    exampleTranslationJa: "彼女の直感が何かおかしいと告げていた。",
    collocations: ["trust your intuition", "female intuition", "go against intuition"],
    mnemonic: "理屈でなく分かる感覚。形容詞は intuitive(直感的に分かる)。",
    relatedWords: ["instinct", "hunch", "insight"],
  },
  {
    id: "jargon",
    word: "jargon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["専門用語、業界用語"],
    pronunciation: "/ˈdʒɑːrɡən/",
    exampleSentence: "The report is full of technical jargon.",
    exampleTranslationJa: "その報告書は専門用語だらけだ。",
    collocations: ["technical jargon", "legal jargon", "cut through the jargon"],
    mnemonic: "部外者に通じない言葉、という否定的な含みがある。",
    relatedWords: ["terminology", "slang", "language"],
  },
  {
    id: "jeopardy",
    word: "jeopardy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["危険、危機"],
    pronunciation: "/ˈdʒepərdi/",
    exampleSentence: "The whole project is in jeopardy.",
    exampleTranslationJa: "計画全体が危うくなっている。",
    collocations: ["in jeopardy", "put in jeopardy", "double jeopardy"],
    mnemonic: "in jeopardy(危機にある)の形でほぼ決まって使う。動詞は jeopardise。",
    relatedWords: ["danger", "risk", "peril"],
  },
  {
    id: "juncture",
    word: "juncture",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(重要な)時点、局面"],
    pronunciation: "/ˈdʒʌŋktʃər/",
    exampleSentence: "At this juncture, we cannot say more.",
    exampleTranslationJa: "現時点ではこれ以上申し上げられません。",
    collocations: ["at this juncture", "a critical juncture"],
    wordFormation: "junct(つなぐ)+ -ure。join と同語根。",
    mnemonic: "at this juncture は「この局面において」というかたい言い回し。",
    relatedWords: ["point", "moment", "stage"],
  },
  {
    id: "knack",
    word: "knack",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["こつ、要領"],
    pronunciation: "/næk/",
    exampleSentence: "There is a knack to opening this door.",
    exampleTranslationJa: "この戸を開けるにはこつがある。",
    collocations: ["get the knack of", "have a knack for", "the knack of"],
    mnemonic: "k は読まない /næk/。have a knack for ... は「〜が得意」。",
    relatedWords: ["skill", "talent", "flair"],
  },
  {
    id: "liability",
    word: "liability",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["法的責任", "不利になるもの"],
    pronunciation: "/ˌlaɪəˈbɪləti/",
    exampleSentence: "The company accepted liability for the damage.",
    exampleTranslationJa: "その会社は損害の責任を認めた。",
    collocations: ["accept liability", "limited liability", "a liability to the team"],
    wordFormation: "liable(責任がある)+ -ity。",
    mnemonic: "会計では「負債」。人について言うと「足を引っぱる存在」。",
    relatedWords: ["responsibility", "debt", "asset"],
  },
  {
    id: "lull",
    word: "lull",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["小康、一時的な静けさ", "なだめる"],
    pronunciation: "/lʌl/",
    exampleSentence: "There was a lull in the fighting at dawn.",
    exampleTranslationJa: "夜明けに戦闘が一時やんだ。",
    collocations: ["a lull in the conversation", "lull someone into", "a brief lull"],
    mnemonic: "lull someone into a false sense of security は「油断させる」。",
    relatedWords: ["pause", "break", "calm"],
  },
  {
    id: "lure",
    word: "lure",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["誘惑、おとり", "おびき寄せる"],
    pronunciation: "/lʊr/",
    exampleSentence: "The lure of easy money attracts many.",
    exampleTranslationJa: "楽な金もうけの誘惑が多くの人を引きつける。",
    collocations: ["the lure of", "lure someone into", "lure customers"],
    mnemonic: "釣りの疑似餌が原義。allure と同語根。",
    relatedWords: ["attraction", "bait", "allure"],
  },
  {
    id: "manoeuvre",
    word: "manoeuvre",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["巧みな動き、策略", "巧みに動かす"],
    pronunciation: "/məˈnuːvər/",
    exampleSentence: "It took three manoeuvres to park the van.",
    exampleTranslationJa: "そのバンを停めるのに3回の切り返しが要った。",
    collocations: ["a clever manoeuvre", "room for manoeuvre", "military manoeuvres"],
    wordFormation: "manu(手)+ opera(仕事)。「手仕事」。",
    mnemonic: "米つづりは maneuver。room for manoeuvre は「動ける余地」。",
    relatedWords: ["move", "tactic", "operation"],
  },
  {
    id: "mindset",
    word: "mindset",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ものの考え方、心構え"],
    pronunciation: "/ˈmaɪndset/",
    exampleSentence: "Changing the mindset is harder than changing the rules.",
    exampleTranslationJa: "考え方を変えるのは規則を変えるより難しい。",
    collocations: ["a fixed mindset", "change your mindset", "a growth mindset"],
    wordFormation: "mind(心)+ set(固まり)。",
    mnemonic: "a growth mindset(成長できるという考え方)は教育でよく使う。",
    relatedWords: ["attitude", "outlook", "mentality"],
  },
  {
    id: "mishap",
    word: "mishap",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ちょっとした災難、不運な出来事"],
    pronunciation: "/ˈmɪshæp/",
    exampleSentence: "The trip passed without mishap.",
    exampleTranslationJa: "その旅は何事もなく終わった。",
    collocations: ["without mishap", "a minor mishap", "a technical mishap"],
    wordFormation: "mis-(悪く)+ hap(偶然)。happen と同語根。",
    mnemonic: "happen と同語根。「悪いほうに転んだ偶然」。深刻すぎない事故。",
    relatedWords: ["accident", "misfortune", "incident"],
  },
  {
    id: "misconception",
    word: "misconception",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["誤解、思い違い"],
    pronunciation: "/ˌmɪskənˈsepʃn/",
    exampleSentence: "It is a common misconception that bats are blind.",
    exampleTranslationJa: "コウモリは目が見えないというのはよくある誤解だ。",
    collocations: ["a common misconception", "dispel a misconception"],
    wordFormation: "mis-(誤って)+ conception(考え)。",
    mnemonic: "a common misconception that ... の形で説明文によく出る。",
    relatedWords: ["fallacy", "misunderstanding", "myth"],
  },
  {
    id: "nuisance",
    word: "nuisance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["迷惑、やっかいなもの"],
    pronunciation: "/ˈnuːsns/",
    exampleSentence: "The roadworks are a real nuisance.",
    exampleTranslationJa: "その道路工事は本当に迷惑だ。",
    collocations: ["a real nuisance", "a public nuisance", "make a nuisance of yourself"],
    mnemonic: "つづりに反して /ˈnuːsns/。法律用語の「公的不法妨害」でもある。",
    relatedWords: ["annoyance", "bother", "inconvenience"],
  },
  {
    id: "omen",
    word: "omen",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["前兆、きざし"],
    pronunciation: "/ˈoʊmən/",
    exampleSentence: "Rain on your wedding day is said to be a good omen.",
    exampleTranslationJa: "結婚式の日の雨は吉兆だと言われる。",
    collocations: ["a good omen", "a bad omen", "an omen of"],
    mnemonic: "よい前兆にも悪い前兆にも使う。形容詞 ominous は悪いほうだけ。",
    relatedWords: ["sign", "warning", "ominous"],
  },
  {
    id: "onslaught",
    word: "onslaught",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["猛攻、殺到"],
    pronunciation: "/ˈɑːnslɔːt/",
    exampleSentence: "The shop could not cope with the onslaught of orders.",
    exampleTranslationJa: "その店は殺到する注文をさばききれなかった。",
    collocations: ["an onslaught of", "withstand the onslaught"],
    mnemonic: "軍事の猛攻から、批判や注文が「どっと来る」比喩へ。",
    relatedWords: ["attack", "assault", "barrage"],
  },
  {
    id: "ordeal",
    word: "ordeal",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["つらい試練"],
    pronunciation: "/ɔːrˈdiːl/",
    exampleSentence: "The hearing was an ordeal for the family.",
    exampleTranslationJa: "その審理は家族にとってつらい試練だった。",
    collocations: ["a terrible ordeal", "go through an ordeal", "survive the ordeal"],
    mnemonic: "中世の神明裁判が語源。長く苦しい経験を指す。",
    relatedWords: ["trial", "hardship", "suffering"],
  },
  {
    id: "overhaul",
    word: "overhaul",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["徹底的な見直し", "総点検する"],
    pronunciation: "/ˈoʊvərhɔːl/",
    exampleSentence: "The system needs a complete overhaul.",
    exampleTranslationJa: "その制度は全面的な見直しが必要だ。",
    collocations: ["a complete overhaul", "overhaul the system", "undergo an overhaul"],
    mnemonic: "機械の分解整備から、制度の抜本的な作り直しへ。",
    relatedWords: ["revamp", "reform", "renovate"],
  },
  {
    id: "oversight",
    word: "oversight",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["見落とし、手落ち", "監督"],
    pronunciation: "/ˈoʊvərsaɪt/",
    exampleSentence: "The omission was an oversight, not deliberate.",
    exampleTranslationJa: "その抜けは手落ちであって故意ではない。",
    collocations: ["an administrative oversight", "due to an oversight", "parliamentary oversight"],
    mnemonic: "「見落とし」と「監督」という正反対の意味を持つ珍しい語。",
    relatedWords: ["mistake", "supervision", "omission"],
  },
  {
    id: "panorama",
    word: "panorama",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["全景、見晴らし"],
    pronunciation: "/ˌpænəˈræmə/",
    exampleSentence: "The window offers a panorama of the valley.",
    exampleTranslationJa: "その窓からは谷の全景が見える。",
    collocations: ["a panorama of", "a sweeping panorama"],
    wordFormation: "pan-(すべて)+ horama(眺め)。",
    mnemonic: "pan(すべて)+ 眺め。形容詞 panoramic は「見晴らしのよい」。",
    relatedWords: ["view", "vista", "scene"],
  },
  {
    id: "paradigm",
    word: "paradigm",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ものの見方の枠組み、範例"],
    pronunciation: "/ˈpærədaɪm/",
    exampleSentence: "The discovery caused a paradigm shift.",
    exampleTranslationJa: "その発見は考え方の枠組みの転換をもたらした。",
    collocations: ["a paradigm shift", "the dominant paradigm"],
    mnemonic: "a paradigm shift(パラダイム転換)の形で覚える。g は読まない。",
    relatedWords: ["model", "framework", "pattern"],
  },
  {
    id: "peril",
    word: "peril",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["重大な危険"],
    pronunciation: "/ˈperəl/",
    exampleSentence: "They crossed the mountains at their peril.",
    exampleTranslationJa: "彼らは危険を承知で山を越えた。",
    collocations: ["at your peril", "in peril", "the perils of"],
    mnemonic: "danger のかたい語。at your peril は「危険を覚悟のうえで」。",
    relatedWords: ["danger", "risk", "jeopardy"],
  },
  {
    id: "pinnacle",
    word: "pinnacle",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["頂点、絶頂"],
    pronunciation: "/ˈpɪnəkl/",
    exampleSentence: "She reached the pinnacle of her career at forty.",
    exampleTranslationJa: "彼女は40歳でキャリアの頂点に達した。",
    collocations: ["the pinnacle of", "reach the pinnacle"],
    mnemonic: "建築の尖塔が原義。the pinnacle of ... で「〜の極み」。",
    relatedWords: ["peak", "summit", "height"],
  },
  {
    id: "plight",
    word: "plight",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["苦境、窮状"],
    pronunciation: "/plaɪt/",
    exampleSentence: "The report highlights the plight of refugees.",
    exampleTranslationJa: "その報告書は難民の窮状を浮き彫りにしている。",
    collocations: ["the plight of", "draw attention to the plight"],
    mnemonic: "the plight of ... の形で、同情を込めて他者の苦境を語る。",
    relatedWords: ["predicament", "hardship", "suffering"],
  },
  {
    id: "poise",
    word: "poise",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["落ち着き、物腰", "構える"],
    pronunciation: "/pɔɪz/",
    exampleSentence: "She answered with remarkable poise.",
    exampleTranslationJa: "彼女は見事な落ち着きで答えた。",
    collocations: ["with poise", "be poised to do", "lose your poise"],
    mnemonic: "be poised to do ... は「今にも〜しようとしている」。",
    relatedWords: ["composure", "balance", "calm"],
  },
  {
    id: "polarity",
    word: "polarity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["両極性、対立"],
    pronunciation: "/poʊˈlærəti/",
    exampleSentence: "There is a growing polarity in public opinion.",
    exampleTranslationJa: "世論の分極が進んでいる。",
    collocations: ["political polarity", "the polarity of", "reverse the polarity"],
    wordFormation: "polar(極の)+ -ity。",
    mnemonic: "磁石のN極S極から、意見が二極に分かれることへ。",
    relatedWords: ["opposition", "division", "polar"],
  },
  {
    id: "predicament",
    word: "predicament",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["苦しい立場、板ばさみ"],
    pronunciation: "/prɪˈdɪkəmənt/",
    exampleSentence: "He found himself in an awkward predicament.",
    exampleTranslationJa: "彼は厄介な立場に置かれた。",
    collocations: ["in a predicament", "face a predicament", "a difficult predicament"],
    mnemonic: "どちらを選んでも困る状況。plight より「自分の判断が絡む」。",
    relatedWords: ["dilemma", "plight", "difficulty"],
  },
  {
    id: "prestige",
    word: "prestige",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["名声、威信"],
    pronunciation: "/preˈstiːʒ/",
    exampleSentence: "The award carries great prestige.",
    exampleTranslationJa: "その賞には大きな威信がある。",
    collocations: ["carry prestige", "international prestige", "a prestige brand"],
    mnemonic: "アクセントは後ろ /preˈstiːʒ/。形容詞は prestigious。",
    relatedWords: ["status", "reputation", "honour"],
  },
  {
    id: "presumption",
    word: "presumption",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["推定、思い込み", "出過ぎた態度"],
    pronunciation: "/prɪˈzʌmpʃn/",
    exampleSentence: "There is a presumption of innocence.",
    exampleTranslationJa: "無罪の推定がある。",
    collocations: ["the presumption of innocence", "a reasonable presumption"],
    wordFormation: "presume(推定する)+ -tion。",
    mnemonic: "法律の「推定」が重要。動詞 presume の名詞形。",
    relatedWords: ["assumption", "supposition", "presume"],
  },
  {
    id: "prowess",
    word: "prowess",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["すぐれた腕前、力量"],
    pronunciation: "/ˈpraʊəs/",
    exampleSentence: "His sporting prowess was known nationwide.",
    exampleTranslationJa: "彼のスポーツの腕前は全国に知られていた。",
    collocations: ["sporting prowess", "military prowess", "technical prowess"],
    mnemonic: "proud(誇り高い)と同語根。ほめ言葉としての「実力」。",
    relatedWords: ["skill", "ability", "expertise"],
  },
  {
    id: "quirk",
    word: "quirk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["風変わりな癖", "偶然のいたずら"],
    pronunciation: "/kwɜːrk/",
    exampleSentence: "Everyone has their little quirks.",
    exampleTranslationJa: "誰にでもちょっとした癖がある。",
    collocations: ["a personal quirk", "a quirk of fate", "an odd quirk"],
    mnemonic: "a quirk of fate は「運命のいたずら」。形容詞は quirky。",
    relatedWords: ["peculiarity", "habit", "oddity"],
  },
  {
    id: "radius",
    word: "radius",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["半径", "(ある地点からの)範囲"],
    pronunciation: "/ˈreɪdiəs/",
    exampleSentence: "Everything within a five-mile radius was evacuated.",
    exampleTranslationJa: "半径5マイル以内はすべて避難させられた。",
    collocations: ["within a radius of", "a five-mile radius"],
    mnemonic: "複数形は radii。radio・radiate と同語根で「中心から出る線」。",
    relatedWords: ["diameter", "range", "circle"],
  },
  {
    id: "rapport",
    word: "rapport",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["打ち解けた関係、信頼関係"],
    pronunciation: "/ræˈpɔːr/",
    exampleSentence: "She quickly built a rapport with the class.",
    exampleTranslationJa: "彼女はすぐにクラスと打ち解けた関係を築いた。",
    collocations: ["build a rapport", "establish a rapport", "a good rapport"],
    mnemonic: "t は読まない /ræˈpɔːr/。フランス語から。build a rapport with が定型。",
    relatedWords: ["relationship", "bond", "understanding"],
  },
  {
    id: "reassurance",
    word: "reassurance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["安心させること、確約"],
    pronunciation: "/ˌriːəˈʃʊrəns/",
    exampleSentence: "Patients need reassurance as much as treatment.",
    exampleTranslationJa: "患者には治療と同じくらい安心が必要だ。",
    collocations: ["seek reassurance", "offer reassurance", "words of reassurance"],
    wordFormation: "re-(再び)+ assurance(確信)。",
    mnemonic: "不安な人に「大丈夫だ」と伝えること。動詞は reassure。",
    relatedWords: ["comfort", "assurance", "reassure"],
  },
  {
    id: "rebuke",
    word: "rebuke",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["叱責", "厳しくとがめる"],
    pronunciation: "/rɪˈbjuːk/",
    exampleSentence: "The minister issued a public rebuke.",
    exampleTranslationJa: "大臣は公に叱責を行った。",
    collocations: ["a sharp rebuke", "issue a rebuke", "rebuke someone for"],
    mnemonic: "tell off より公式でかたい。声明や記事で使う語。",
    relatedWords: ["reprimand", "criticism", "scold"],
  },
  {
    id: "reckoning",
    word: "reckoning",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["清算、報い", "計算"],
    pronunciation: "/ˈrekənɪŋ/",
    exampleSentence: "The day of reckoning finally came.",
    exampleTranslationJa: "ついに清算の日が来た。",
    collocations: ["a day of reckoning", "by my reckoning", "the final reckoning"],
    wordFormation: "reckon(数える・思う)+ -ing。",
    mnemonic: "by my reckoning は「私の計算では」。「報いを受ける時」の意味も重要。",
    relatedWords: ["calculation", "judgement", "reckon"],
  },
  {
    id: "recourse",
    word: "recourse",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["頼ること、手段"],
    pronunciation: "/ˈriːkɔːrs/",
    exampleSentence: "They settled it without recourse to the courts.",
    exampleTranslationJa: "彼らは裁判に訴えずに解決した。",
    collocations: ["have recourse to", "without recourse to", "the only recourse"],
    wordFormation: "re-(戻って)+ currere(走る)。course と同語根。",
    mnemonic: "have recourse to ... で「〜という手段に訴える」。",
    relatedWords: ["resort", "option", "remedy"],
  },
  {
    id: "reliance",
    word: "reliance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["依存、頼ること"],
    pronunciation: "/rɪˈlaɪəns/",
    exampleSentence: "Our reliance on imported food is growing.",
    exampleTranslationJa: "輸入食料への依存が高まっている。",
    collocations: ["reliance on", "heavy reliance", "reduce reliance"],
    wordFormation: "rely(頼る)+ -ance。",
    mnemonic: "rely on の名詞形。dependence とほぼ同じ。",
    relatedWords: ["dependence", "trust", "rely"],
  },
  {
    id: "remnant",
    word: "remnant",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["残り、名残"],
    pronunciation: "/ˈremnənt/",
    exampleSentence: "Only a remnant of the old wall survives.",
    exampleTranslationJa: "古い城壁は一部しか残っていない。",
    collocations: ["the remnants of", "a remnant of the past"],
    wordFormation: "remain(残る)と同語根。",
    mnemonic: "ふつう複数形 remnants。remain と同語根で「残ったもの」。",
    relatedWords: ["remains", "remainder", "trace"],
  },
  {
    id: "renown",
    word: "renown",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["名声"],
    pronunciation: "/rɪˈnaʊn/",
    exampleSentence: "The city is of international renown for its glass.",
    exampleTranslationJa: "その都市はガラス細工で国際的な名声がある。",
    collocations: ["of great renown", "international renown"],
    wordFormation: "re-(繰り返し)+ nomen(名)。",
    mnemonic: "nomen(名)が語根。形容詞 renowned(名高い)のほうがよく使う。",
    relatedWords: ["fame", "reputation", "renowned"],
  },
  {
    id: "respite",
    word: "respite",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ひと休み、小康"],
    pronunciation: "/ˈrespɪt/",
    exampleSentence: "The rain gave the firefighters brief respite.",
    exampleTranslationJa: "雨は消防士たちに短い休息を与えた。",
    collocations: ["a brief respite", "without respite", "respite care"],
    mnemonic: "苦しい状況が一時やむこと。介護の一時預かりも respite care。",
    relatedWords: ["break", "relief", "pause"],
  },
  {
    id: "reverence",
    word: "reverence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["深い敬意、崇敬"],
    pronunciation: "/ˈrevərəns/",
    exampleSentence: "He speaks of his teacher with reverence.",
    exampleTranslationJa: "彼は恩師について深い敬意をこめて語る。",
    collocations: ["treat with reverence", "hold in reverence"],
    wordFormation: "ラテン語 revereri(畏れ敬う)から。",
    mnemonic: "respect よりずっと強く、畏れを含む敬意。動詞は revere。",
    relatedWords: ["respect", "awe", "veneration"],
  },
  {
    id: "rift",
    word: "rift",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["亀裂、不和", "(地面の)裂け目"],
    pronunciation: "/rɪft/",
    exampleSentence: "The dispute caused a rift in the family.",
    exampleTranslationJa: "その争いは家族に亀裂を生んだ。",
    collocations: ["a rift between", "heal the rift", "a growing rift"],
    mnemonic: "地面の裂け目から、人間関係の「溝」へ。heal the rift は「関係を修復する」。",
    relatedWords: ["split", "division", "breach"],
  },
  {
    id: "rigour",
    word: "rigour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["厳密さ、厳しさ"],
    pronunciation: "/ˈrɪɡər/",
    exampleSentence: "The study lacks scientific rigour.",
    exampleTranslationJa: "その研究は科学的な厳密さを欠いている。",
    collocations: ["academic rigour", "scientific rigour", "the rigours of winter"],
    mnemonic: "米つづりは rigor。複数形 rigours は「(冬などの)厳しさ」。",
    relatedWords: ["strictness", "precision", "rigid"],
  },
  {
    id: "rivalry",
    word: "rivalry",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["競争、対抗意識"],
    pronunciation: "/ˈraɪvlri/",
    exampleSentence: "The rivalry between the two clubs goes back a century.",
    exampleTranslationJa: "その2クラブの対抗意識は100年前にさかのぼる。",
    collocations: ["intense rivalry", "sibling rivalry", "a long-standing rivalry"],
    wordFormation: "rival(競争相手)+ -ry。",
    mnemonic: "sibling rivalry は「きょうだい間の張り合い」。",
    relatedWords: ["competition", "rival", "contest"],
  },
  {
    id: "rubble",
    word: "rubble",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["がれき"],
    pronunciation: "/ˈrʌbl/",
    exampleSentence: "Rescuers searched the rubble for survivors.",
    exampleTranslationJa: "救助隊はがれきの中で生存者を探した。",
    collocations: ["reduced to rubble", "under the rubble", "clear the rubble"],
    mnemonic: "数えられない名詞。be reduced to rubble は「跡形もなく壊れる」。",
    relatedWords: ["debris", "ruins", "wreckage"],
  },
  {
    id: "sanctuary",
    word: "sanctuary",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["保護区", "避難所、聖域"],
    pronunciation: "/ˈsæŋktʃueri/",
    exampleSentence: "The island is a sanctuary for seabirds.",
    exampleTranslationJa: "その島は海鳥の保護区だ。",
    collocations: ["a wildlife sanctuary", "seek sanctuary", "a bird sanctuary"],
    wordFormation: "ラテン語 sanctus(聖なる)から。saint と同語根。",
    mnemonic: "教会の聖域が原義。今は動物の保護区の意味でよく使う。",
    relatedWords: ["refuge", "haven", "reserve"],
  },
  {
    id: "shortfall",
    word: "shortfall",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不足額、不足分"],
    pronunciation: "/ˈʃɔːrtfɔːl/",
    exampleSentence: "There is a shortfall of two million pounds.",
    exampleTranslationJa: "200万ポンドの不足がある。",
    collocations: ["a budget shortfall", "make up the shortfall", "a shortfall in funding"],
    wordFormation: "short(足りない)+ fall(落ちる)。",
    mnemonic: "予算や供給が予定に届かない分。make up the shortfall は「不足を埋める」。",
    relatedWords: ["deficit", "gap", "surplus"],
  },
  {
    id: "snag",
    word: "snag",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["思わぬ支障", "引っかかり"],
    pronunciation: "/snæɡ/",
    exampleSentence: "We hit a snag with the paperwork.",
    exampleTranslationJa: "書類の件で思わぬ支障が出た。",
    collocations: ["hit a snag", "a slight snag", "the only snag"],
    mnemonic: "木の切り株に引っかかることが原義。小さいが厄介な障害。",
    relatedWords: ["hitch", "problem", "obstacle"],
  },
  {
    id: "standpoint",
    word: "standpoint",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["観点、立場"],
    pronunciation: "/ˈstændpɔɪnt/",
    exampleSentence: "From a legal standpoint, the answer is clear.",
    exampleTranslationJa: "法律上の観点からは答えは明らかだ。",
    collocations: ["from a standpoint", "from the standpoint of"],
    wordFormation: "stand(立つ)+ point(点)。",
    mnemonic: "どこに立って見るか。point of view とほぼ同じ。",
    relatedWords: ["viewpoint", "perspective", "angle"],
  },
  {
    id: "stigma",
    word: "stigma",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["汚名、負のレッテル"],
    pronunciation: "/ˈstɪɡmə/",
    exampleSentence: "There is still a stigma attached to mental illness.",
    exampleTranslationJa: "精神の病にはいまだ負のレッテルがついている。",
    collocations: ["a stigma attached to", "reduce the stigma", "social stigma"],
    wordFormation: "ギリシャ語 stigma(焼き印)から。",
    mnemonic: "奴隷に押した焼き印が語源。社会が貼るレッテル。",
    relatedWords: ["shame", "disgrace", "label"],
  },
  {
    id: "strife",
    word: "strife",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["争い、対立"],
    pronunciation: "/straɪf/",
    exampleSentence: "Years of civil strife left the country poor.",
    exampleTranslationJa: "長年の内紛がその国を貧しくした。",
    collocations: ["civil strife", "industrial strife", "internal strife"],
    mnemonic: "strive(努力する)と同語根。集団どうしの争いに使う。",
    relatedWords: ["conflict", "discord", "dispute"],
  },
  {
    id: "stronghold",
    word: "stronghold",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["拠点、地盤"],
    pronunciation: "/ˈstrɔːŋhoʊld/",
    exampleSentence: "The region is a stronghold of the party.",
    exampleTranslationJa: "その地域はその党の地盤だ。",
    collocations: ["a party stronghold", "a traditional stronghold"],
    wordFormation: "strong(強い)+ hold(保つ)。",
    mnemonic: "もとは要塞。今は「支持の厚い地域」の意味で使う。",
    relatedWords: ["fortress", "base", "bastion"],
  },
  {
    id: "subtlety",
    word: "subtlety",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["微妙さ、繊細さ"],
    pronunciation: "/ˈsʌtlti/",
    exampleSentence: "The translation misses the subtlety of the original.",
    exampleTranslationJa: "その訳は原文の微妙さを取り落としている。",
    collocations: ["the subtlety of", "lack subtlety", "with great subtlety"],
    wordFormation: "subtle(微妙な)+ -ty。",
    mnemonic: "subtle の b は読まない /ˈsʌtlti/。nuance に近い。",
    relatedWords: ["nuance", "delicacy", "subtle"],
  },
  {
    id: "token",
    word: "token",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["しるし、代用貨幣", "形ばかりの"],
    pronunciation: "/ˈtoʊkən/",
    exampleSentence: "Please accept this as a token of our thanks.",
    exampleTranslationJa: "感謝のしるしとしてお受け取りください。",
    collocations: ["a token of", "a token gesture", "by the same token"],
    mnemonic: "a token gesture は「形だけの行為」。by the same token は「同じ理由で」。",
    relatedWords: ["symbol", "sign", "gesture"],
  },
  {
    id: "uproar",
    word: "uproar",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大騒ぎ、騒然"],
    pronunciation: "/ˈʌprɔːr/",
    exampleSentence: "The decision caused an uproar.",
    exampleTranslationJa: "その決定は大騒ぎを引き起こした。",
    collocations: ["cause an uproar", "in uproar", "a public uproar"],
    mnemonic: "roar(ほえる)が入っているが語源は別。怒りを伴う騒ぎ。",
    relatedWords: ["outcry", "commotion", "protest"],
  },
  {
    id: "vantage",
    word: "vantage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["有利な位置、見晴らしのきく地点"],
    pronunciation: "/ˈvæntɪdʒ/",
    exampleSentence: "From this vantage point you can see the whole bay.",
    exampleTranslationJa: "この地点からは湾全体が見える。",
    collocations: ["a vantage point", "from the vantage of"],
    wordFormation: "advantage の頭が落ちた語。",
    mnemonic: "ほぼ a vantage point(見晴らしのきく場所)の形で使う。",
    relatedWords: ["advantage", "viewpoint", "position"],
  },
  {
    id: "verge",
    word: "verge",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ふち、寸前", "(verge on で)〜に近い"],
    pronunciation: "/vɜːrdʒ/",
    exampleSentence: "She was on the verge of tears.",
    exampleTranslationJa: "彼女は今にも泣き出しそうだった。",
    collocations: ["on the verge of", "verge on the ridiculous"],
    mnemonic: "on the verge of ... は「今にも〜しそう」。brink とほぼ同じ。",
    relatedWords: ["brink", "edge", "border"],
  },
]
