import type { VocabularyEntry } from '../types'

// 増補 第46弾。8,000語 → 8,800語 の増補の一部で、s – t の基礎語を補う。
export const plus46: VocabularyEntry[] = [
  {
    id: "show",
    word: "show",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["見せる、示す", "番組、ショー"],
    pronunciation: "/ʃoʊ/",
    exampleSentence: "Please show me the photos from your trip.",
    exampleTranslationJa: "旅行の写真を見せてください。",
    collocations: ["show me the way", "a TV show", "show up"],
    mnemonic: "「見せる」と「番組」の2つの意味を持つ。show up で「現れる」、show off で「見せびらかす」、show around で「案内する」。",
    relatedWords: ["display", "exhibition", "program"],
  },
  {
    id: "shower",
    word: "shower",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["シャワー", "にわか雨", "シャワーを浴びる"],
    pronunciation: "/ˈʃaʊər/",
    exampleSentence: "I take a shower before breakfast every morning.",
    exampleTranslationJa: "私は毎朝、朝食前にシャワーを浴びる。",
    collocations: ["take a shower", "a heavy shower", "shower gel"],
    mnemonic: "「シャワー」とにわか雨の両方を指す。浴槽につかる bath と対で、take a shower の形でよく使われる。",
    relatedWords: ["bath", "soap", "rain"],
  },
  {
    id: "sick",
    word: "sick",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["病気の", "気分が悪い", "うんざりして"],
    pronunciation: "/sɪk/",
    exampleSentence: "She stayed home because she felt sick.",
    exampleTranslationJa: "彼女は気分が悪いので家にいた。",
    collocations: ["feel sick", "be off sick", "sick leave"],
    mnemonic: "体調が悪い状態を表す語。イギリス英語では be sick だけで「吐く」の意味にもなるので、文脈に注意する。",
    relatedWords: ["ill", "unwell", "health"],
  },
  {
    id: "sightsee",
    word: "sightsee",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["観光する、見物して回る"],
    pronunciation: "/ˈsaɪtsiː/",
    exampleSentence: "On Sundays we sightsee around the old town.",
    exampleTranslationJa: "私たちは日曜日に旧市街を歩いて観光する。",
    collocations: ["go sightseeing", "sightsee around town", "a sightseeing tour"],
    mnemonic: "sight(見るもの) + see(見る)で「名所を見て回る」。名詞形は sightseeing で、go sightseeing の形がよく使われる。",
    relatedWords: ["tourist", "visit", "travel"],
  },
  {
    id: "sing",
    word: "sing",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["歌う"],
    pronunciation: "/sɪŋ/",
    exampleSentence: "The children sing the same song every morning.",
    exampleTranslationJa: "子どもたちは毎朝同じ歌を歌う。",
    collocations: ["sing a song", "sing along", "sing in a choir"],
    mnemonic: "「歌う」。過去形は sang、過去分詞は sung と不規則に変化する。singer(歌手)・song(歌)とまとめて覚える。",
    relatedWords: ["singer", "song", "music"],
  },
  {
    id: "sister",
    word: "sister",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["姉、妹"],
    pronunciation: "/ˈsɪstər/",
    exampleSentence: "My sister is two years older than me.",
    exampleTranslationJa: "私の姉は私より2歳年上だ。",
    collocations: ["an older sister", "a younger sister", "my little sister"],
    mnemonic: "「姉妹」。brother と対になる語で、年上か年下かは older / younger を前につけて区別する。",
    relatedWords: ["brother", "family", "daughter"],
  },
  {
    id: "sit",
    word: "sit",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["座る", "位置する"],
    pronunciation: "/sɪt/",
    exampleSentence: "Please sit in this chair by the window.",
    exampleTranslationJa: "窓のそばのこの椅子に座ってください。",
    collocations: ["sit down", "sit still", "sit at a desk"],
    mnemonic: "「座る」。過去形は sat で不規則。sit down は腰を下ろす、sit up は上体を起こす動作を表す。",
    relatedWords: ["seat", "chair", "stand"],
  },
  {
    id: "sit down",
    word: "sit down",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["座る、腰を下ろす"],
    pronunciation: "/ˌsɪt ˈdaʊn/",
    exampleSentence: "Please sit down and wait for the doctor.",
    exampleTranslationJa: "どうぞ座って医師を待ってください。",
    collocations: ["sit down on the sofa", "sit down at the table", "ask someone to sit down"],
    mnemonic: "sit(座る) + down(下へ)。座った状態までの動作全体を表し、命令形の Sit down. は「座って」の定番の言い方。",
    relatedWords: ["sit", "seat", "stand up"],
  },
  {
    id: "six",
    word: "six",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["6、六", "6つ"],
    pronunciation: "/sɪks/",
    exampleSentence: "There are six eggs left in the fridge.",
    exampleTranslationJa: "冷蔵庫に卵が6個残っている。",
    collocations: ["six o'clock", "six years old", "at six"],
    mnemonic: "6を表す数。語末の x は /ks/ と2つの音を続けて出す。sixteen・sixty・sixth の土台になる語。",
    relatedWords: ["sixteen", "sixty", "sixth"],
  },
  {
    id: "sixteen",
    word: "sixteen",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["16、十六", "16歳"],
    pronunciation: "/ˌsɪkˈstiːn/",
    exampleSentence: "She is sixteen and studies at a high school.",
    exampleTranslationJa: "彼女は16歳で高校で勉強している。",
    collocations: ["turn sixteen", "sixteen years old", "at sixteen"],
    mnemonic: "six(6) + -teen(10の位)。13〜19は -teen で終わり、後ろの音に強勢が置かれる点が -ty の数と違う。",
    relatedWords: ["six", "sixty", "teenager"],
  },
  {
    id: "sixth",
    word: "sixth",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["6番目の", "6分の1"],
    pronunciation: "/sɪksθ/",
    exampleSentence: "Our team finished sixth in the school race.",
    exampleTranslationJa: "私たちのチームは学校のレースで6位だった。",
    collocations: ["the sixth floor", "the sixth of May", "finish sixth"],
    mnemonic: "six + -th(序数の接尾辞)。/ksθ/ と子音が3つ続くので、息を止めずに一息で出す。",
    relatedWords: ["six", "sixteen", "fourth"],
  },
  {
    id: "sixty",
    word: "sixty",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["60、六十", "60歳"],
    pronunciation: "/ˈsɪksti/",
    exampleSentence: "My father is sixty and still works every day.",
    exampleTranslationJa: "父は60歳で、今も毎日働いている。",
    collocations: ["sixty years old", "in his sixties", "around sixty"],
    mnemonic: "six(6) + -ty(10の倍数)。16の sixteen と綴りが似ているので、語尾の -teen と -ty を強勢の位置で聞き分ける。",
    relatedWords: ["six", "sixteen", "seventy"],
  },
  {
    id: "sketchbook",
    word: "sketchbook",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スケッチブック、写生帳"],
    pronunciation: "/ˈsketʃbʊk/",
    exampleSentence: "She draws trees in her sketchbook every weekend.",
    exampleTranslationJa: "彼女は毎週末、スケッチブックに木を描く。",
    collocations: ["draw in a sketchbook", "an artist's sketchbook", "fill a sketchbook"],
    mnemonic: "sketch(下書き・写生) + book(帳面)。仕上げの絵ではなく、線で形をとらえる練習に使う帳面を指す。",
    relatedWords: ["sketch", "drawing", "notebook"],
  },
  {
    id: "skirt",
    word: "skirt",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スカート"],
    pronunciation: "/skɜːrt/",
    exampleSentence: "She wore a blue skirt to the party.",
    exampleTranslationJa: "彼女はパーティーに青いスカートをはいていった。",
    collocations: ["a long skirt", "a pleated skirt", "wear a skirt"],
    mnemonic: "「スカート」。日本語の「スカート」とほぼ同じだが、英語では語末の -t まで短くはっきり発音する。",
    relatedWords: ["dress", "trousers", "clothes"],
  },
  {
    id: "sled",
    word: "sled",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["そり"],
    pronunciation: "/sled/",
    exampleSentence: "The children pulled a wooden sled up the hill.",
    exampleTranslationJa: "子どもたちは木のそりを丘の上まで引いていった。",
    collocations: ["pull a sled", "ride a sled", "a dog sled"],
    mnemonic: "雪の上を滑る手で引くそり。犬ぞりは dog sled で、動詞としても「そりで行く」の意味で使われる。",
    relatedWords: ["snow", "slide", "winter"],
  },
  {
    id: "small",
    word: "small",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["小さい", "少ない"],
    pronunciation: "/smɔːl/",
    exampleSentence: "They live in a small house near the river.",
    exampleTranslationJa: "彼らは川の近くの小さな家に住んでいる。",
    collocations: ["a small town", "small talk", "a small amount"],
    mnemonic: "大きさを客観的に言う語。little は「小さくてかわいい」という気持ちがこもり、small talk は世間話のこと。",
    relatedWords: ["little", "tiny", "large"],
  },
  {
    id: "sneakers",
    word: "sneakers",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スニーカー、運動靴"],
    pronunciation: "/ˈsniːkərz/",
    exampleSentence: "He put on his sneakers and went out for a run.",
    exampleTranslationJa: "彼はスニーカーをはいて走りに出かけた。",
    collocations: ["a pair of sneakers", "white sneakers", "wear sneakers"],
    mnemonic: "sneak(こっそり歩く)から。音を立てないゴム底の靴が原義で、イギリス英語では trainers という。",
    relatedWords: ["shoes", "boots", "sandals"],
  },
  {
    id: "snow",
    word: "snow",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["雪", "雪が降る"],
    pronunciation: "/snoʊ/",
    exampleSentence: "The snow covered the whole garden last night.",
    exampleTranslationJa: "昨夜、雪が庭全体をおおった。",
    collocations: ["heavy snow", "a snow storm", "play in the snow"],
    mnemonic: "「雪」。rain・wind と同じ天気の名詞で、動詞では「雪が降る」を表す。形容詞は snowy。",
    relatedWords: ["snowy", "ice", "winter"],
  },
  {
    id: "snowboarding",
    word: "snowboarding",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スノーボード"],
    pronunciation: "/ˈsnoʊbɔːrdɪŋ/",
    exampleSentence: "He goes snowboarding in the mountains every winter.",
    exampleTranslationJa: "彼は毎冬、山へスノーボードをしに行く。",
    collocations: ["go snowboarding", "a snowboarding trip", "learn snowboarding"],
    mnemonic: "snow(雪) + board(板) + -ing。板に乗って雪を滑る動作を表し、go snowboarding の形で使う。",
    wordFormation: "snow(雪) + board(板) + -ing(動作の名詞化)。go + -ing で「〜をしに行く」を表す。",
    relatedWords: ["snowboard", "skiing", "winter"],
  },
  {
    id: "so",
    word: "so",
    level: "A2",
    partOfSpeech: "副詞・接続詞",
    meaningsJa: ["とても、そんなに", "だから、それで"],
    pronunciation: "/soʊ/",
    exampleSentence: "It was so cold that we stayed inside all day.",
    exampleTranslationJa: "とても寒かったので、一日中家にいた。",
    collocations: ["so far", "so much", "and so on"],
    mnemonic: "程度を強める「とても」と、結果を導く「だから」の2つの働きを持つ。so that で「〜するために」。",
    relatedWords: ["very", "therefore", "such"],
  },
  {
    id: "some",
    word: "some",
    level: "A2",
    partOfSpeech: "限定詞・代名詞",
    meaningsJa: ["いくつかの、少しの", "いくらか"],
    pronunciation: "/səm/",
    exampleSentence: "Would you like some tea with your cake?",
    exampleTranslationJa: "ケーキと一緒にお茶はいかがですか。",
    collocations: ["some of them", "some more", "some time"],
    mnemonic: "数や量がはっきりしないときに使う。肯定文では some、疑問文と否定文では any が基本になる。",
    relatedWords: ["any", "several", "few"],
  },
  {
    id: "somebody",
    word: "somebody",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["だれか"],
    pronunciation: "/ˈsʌmbɑːdi/",
    exampleSentence: "Somebody left an umbrella on the train.",
    exampleTranslationJa: "だれかが電車に傘を置き忘れた。",
    collocations: ["somebody else", "somebody like you", "ask somebody for help"],
    mnemonic: "some(ある) + body(人)。someone とほぼ同じ意味で、話し言葉では somebody もよく使われる。",
    relatedWords: ["someone", "anybody", "nobody"],
  },
  {
    id: "someone",
    word: "someone",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["だれか"],
    pronunciation: "/ˈsʌmwʌn/",
    exampleSentence: "Someone is knocking at the front door.",
    exampleTranslationJa: "だれかが玄関のドアをノックしている。",
    collocations: ["someone else", "someone like me", "help someone"],
    mnemonic: "some(ある) + one(1人)。肯定文で「だれか」を表し、疑問文と否定文では anyone を使う。",
    relatedWords: ["somebody", "anyone", "everyone"],
  },
  {
    id: "something",
    word: "something",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["何か、ある物"],
    pronunciation: "/ˈsʌmθɪŋ/",
    exampleSentence: "I want something cold to drink.",
    exampleTranslationJa: "何か冷たい飲み物が欲しい。",
    collocations: ["something else", "something to eat", "something like that"],
    mnemonic: "some(ある) + thing(物事)。something to eat のように to 不定詞を続けて「何か食べるもの」となる。",
    relatedWords: ["anything", "everything", "nothing"],
  },
  {
    id: "sometimes",
    word: "sometimes",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["ときどき"],
    pronunciation: "/ˈsʌmtaɪmz/",
    exampleSentence: "I sometimes walk to school when the weather is fine.",
    exampleTranslationJa: "天気が良いときは、ときどき歩いて学校へ行く。",
    collocations: ["only sometimes", "sometimes I forget", "sometimes busy"],
    mnemonic: "some(ある) + times(回)。頻度を表す副詞で、always(いつも)と never(決して〜ない)の間を埋める。",
    relatedWords: ["often", "always", "never"],
  },
  {
    id: "son",
    word: "son",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["息子"],
    pronunciation: "/sʌn/",
    exampleSentence: "Their son is studying at a university in Tokyo.",
    exampleTranslationJa: "彼らの息子は東京の大学で勉強している。",
    collocations: ["an only son", "my eldest son", "a son and a daughter"],
    mnemonic: "「息子」。sun(太陽)と同音なので、文脈で聞き分ける。daughter(娘)と対にして覚える。",
    relatedWords: ["daughter", "child", "parents"],
  },
  {
    id: "song",
    word: "song",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["歌"],
    pronunciation: "/sɔːŋ/",
    exampleSentence: "That song always makes me feel happy.",
    exampleTranslationJa: "その歌を聴くといつも幸せな気分になる。",
    collocations: ["a pop song", "sing a song", "the same song"],
    mnemonic: "sing(歌う)の名詞形。sing-sang-sung と変化する動詞から生まれた語で、日本語の「ソング」と同じ。",
    relatedWords: ["sing", "singer", "music"],
  },
  {
    id: "soon",
    word: "soon",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["まもなく、すぐに"],
    pronunciation: "/suːn/",
    exampleSentence: "The bus will arrive soon, so please wait here.",
    exampleTranslationJa: "バスはまもなく来るので、ここで待っていてください。",
    collocations: ["as soon as", "see you soon", "too soon"],
    mnemonic: "「まもなく」。as soon as で「〜するとすぐに」、sooner or later で「遅かれ早かれ」の意味になる。",
    relatedWords: ["early", "quickly", "later"],
  },
  {
    id: "sorry",
    word: "sorry",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すまなく思って、残念で"],
    pronunciation: "/ˈsɑːri/",
    exampleSentence: "I am sorry for keeping you waiting so long.",
    exampleTranslationJa: "長く待たせてしまってごめんなさい。",
    collocations: ["be sorry for", "say sorry", "feel sorry for someone"],
    mnemonic: "「ごめんなさい」と「残念に思う」の2つ。I'm sorry to hear that. は相手の不幸への決まり文句。",
    relatedWords: ["apologize", "excuse", "regret"],
  },
  {
    id: "soup",
    word: "soup",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スープ"],
    pronunciation: "/suːp/",
    exampleSentence: "My mother made vegetable soup for dinner.",
    exampleTranslationJa: "母は夕食に野菜スープを作った。",
    collocations: ["a bowl of soup", "hot soup", "make soup"],
    mnemonic: "「スープ」。soap(せっけん)と1字違いなので、母音の綴り ou と oa を区別して覚える。",
    relatedWords: ["stew", "bowl", "meal"],
  },
  {
    id: "south",
    word: "south",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["南", "南の、南へ"],
    pronunciation: "/saʊθ/",
    exampleSentence: "They drove south along the coast for two hours.",
    exampleTranslationJa: "彼らは海岸沿いを南へ2時間車で走った。",
    collocations: ["in the south", "South America", "south of the city"],
    mnemonic: "4方位の1つで「南」。north・east・west と並び、名詞・形容詞・副詞のどの働きでも使える。",
    relatedWords: ["north", "east", "west"],
  },
  {
    id: "space",
    word: "space",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["空間、場所", "宇宙"],
    pronunciation: "/speɪs/",
    exampleSentence: "There is not enough space for another desk.",
    exampleTranslationJa: "もう1つ机を置くだけの場所がない。",
    collocations: ["a parking space", "outer space", "in space"],
    mnemonic: "「あいた場所」が中心の意味で、宇宙も広がった空間のこと。形容詞は spacious で「広々とした」。",
    relatedWords: ["room", "area", "universe"],
  },
  {
    id: "speak",
    word: "speak",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["話す、話をする"],
    pronunciation: "/spiːk/",
    exampleSentence: "She can speak three languages quite well.",
    exampleTranslationJa: "彼女は3つの言語をかなり上手に話せる。",
    collocations: ["speak English", "speak to someone", "speak up"],
    mnemonic: "speak は一方的に話す、talk は互いに話し合う、say は内容を言う、tell は人に伝える、と役割が分かれる。",
    relatedWords: ["talk", "say", "tell"],
  },
  {
    id: "special",
    word: "special",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["特別な、特別の"],
    pronunciation: "/ˈspeʃl/",
    exampleSentence: "Today is a special day for our family.",
    exampleTranslationJa: "今日は私たちの家族にとって特別な日だ。",
    collocations: ["a special day", "something special", "special offer"],
    mnemonic: "species(種)や specify(特定する)と同じく「他と区別される」が芯の意味。名詞形は specialty。",
    relatedWords: ["specialty", "particular", "ordinary"],
  },
  {
    id: "spoonful",
    word: "spoonful",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スプーン1杯(の量)"],
    pronunciation: "/ˈspuːnfʊl/",
    exampleSentence: "Add a spoonful of honey to the warm milk.",
    exampleTranslationJa: "温めたミルクにスプーン1杯のはちみつを加える。",
    collocations: ["a spoonful of sugar", "two spoonfuls of honey", "a spoonful at a time"],
    mnemonic: "spoon(スプーン) + -ful(いっぱい)。mouthful(ひと口)と同じ作りで、複数形は spoonfuls となる。",
    wordFormation: "spoon(スプーン) + -ful(〜でいっぱいの量)。cupful・mouthful と同じ作り。",
    relatedWords: ["spoon", "mouthful", "handful"],
  },
  {
    id: "sport",
    word: "sport",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["スポーツ、運動競技"],
    pronunciation: "/spɔːrt/",
    exampleSentence: "My favourite sport is tennis in summer.",
    exampleTranslationJa: "私の好きなスポーツは夏のテニスだ。",
    collocations: ["play a sport", "a team sport", "do sport"],
    mnemonic: "「スポーツ」。イギリス英語では do sport、アメリカ英語では play sports の形がよく使われる。",
    relatedWords: ["game", "exercise", "player"],
  },
  {
    id: "stairs",
    word: "stairs",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["階段"],
    pronunciation: "/sterz/",
    exampleSentence: "She ran up the stairs to her room.",
    exampleTranslationJa: "彼女は自分の部屋へ階段を駆け上がった。",
    collocations: ["go up the stairs", "a flight of stairs", "at the top of the stairs"],
    mnemonic: "「階段」。1段は a step、階段全体は複数形の stairs で、a flight of stairs とも言う。",
    relatedWords: ["step", "floor", "elevator"],
  },
  {
    id: "stand up",
    word: "stand up",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["立ち上がる", "立っている"],
    pronunciation: "/ˌstænd ˈʌp/",
    exampleSentence: "Please stand up and read the next page aloud.",
    exampleTranslationJa: "立って次のページを声に出して読んでください。",
    collocations: ["stand up for someone", "stand up straight", "stand up and speak"],
    mnemonic: "stand(立つ) + up(上へ)。座った状態から立ち上がる動作で、stand up for は「擁護する」の意味。",
    relatedWords: ["stand", "sit down", "rise"],
  },
  {
    id: "station",
    word: "station",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["駅", "署、局"],
    pronunciation: "/ˈsteɪʃn/",
    exampleSentence: "I will meet you at the station at six.",
    exampleTranslationJa: "6時に駅で会いましょう。",
    collocations: ["a train station", "a police station", "at the station"],
    mnemonic: "「駅」と「署・局」。stay(とどまる)と同じく「立っている場所」が原義で、police station は警察署。",
    relatedWords: ["platform", "train", "stop"],
  },
  {
    id: "stethoscope",
    word: "stethoscope",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["聴診器"],
    pronunciation: "/ˈsteθəskoʊp/",
    exampleSentence: "The doctor listened to my heart with a stethoscope.",
    exampleTranslationJa: "医師は聴診器で私の心臓の音を聞いた。",
    collocations: ["listen with a stethoscope", "a stethoscope around the neck", "use a stethoscope"],
    mnemonic: "stetho-(胸) + -scope(見る道具)。胸の音を聞く器具で、telescope の -scope と同じ「見る道具」。",
    wordFormation: "stetho-(胸) + -scope(観察する道具)。telescope・microscope と同じ接尾辞。",
    relatedWords: ["doctor", "heart", "examine"],
  },
  {
    id: "stickers",
    word: "stickers",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ステッカー、シール"],
    pronunciation: "/ˈstɪkərz/",
    exampleSentence: "The children put stickers on their notebooks.",
    exampleTranslationJa: "子どもたちはノートにステッカーを貼った。",
    collocations: ["put stickers on", "a sheet of stickers", "collect stickers"],
    mnemonic: "stick(貼りつく) + -er。貼ってはがせる小さな紙やシールを指し、動詞 stick とまとめて覚える。",
    relatedWords: ["sticker", "label", "notebook"],
  },
  {
    id: "sticky note",
    word: "sticky note",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["付箋"],
    pronunciation: "/ˌstɪki ˈnoʊt/",
    exampleSentence: "She left a sticky note on the fridge door.",
    exampleTranslationJa: "彼女は冷蔵庫の扉に付箋を貼っておいた。",
    collocations: ["write on a sticky note", "a sticky note on the desk", "peel off a sticky note"],
    mnemonic: "sticky(粘る) + note(書き留め)。貼ってはがせる小さな紙で、貼り直せるのが特徴。",
    wordFormation: "sticky(粘る) + note(書き留め)。名詞を形容詞が前から修飾する複合名詞。",
    relatedWords: ["sticker", "memo", "note"],
  },
  {
    id: "stop",
    word: "stop",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["止まる、止める", "停留所"],
    pronunciation: "/stɑːp/",
    exampleSentence: "The bus will stop in front of the school.",
    exampleTranslationJa: "バスは学校の前で止まる。",
    collocations: ["stop doing", "a bus stop", "stop by"],
    mnemonic: "stop doing は「するのをやめる」、stop to do は「するために立ち止まる」。続く形で意味が変わる。",
    relatedWords: ["halt", "quit", "start"],
  },
  {
    id: "story",
    word: "story",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["話、物語", "記事"],
    pronunciation: "/ˈstɔːri/",
    exampleSentence: "My grandfather told us a funny story.",
    exampleTranslationJa: "祖父は私たちにおもしろい話をしてくれた。",
    collocations: ["tell a story", "a true story", "a bedtime story"],
    mnemonic: "「話・物語」。history(歴史)にも同じ語が入る。複数形は -y が -ies に変わって stories。",
    relatedWords: ["tale", "novel", "history"],
  },
  {
    id: "street",
    word: "street",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["通り、街路"],
    pronunciation: "/striːt/",
    exampleSentence: "They live on a quiet street near the park.",
    exampleTranslationJa: "彼らは公園の近くの静かな通りに住んでいる。",
    collocations: ["on the street", "cross the street", "a busy street"],
    mnemonic: "「通り」。on the street は通りに面した場所、in the street は通りの真ん中を意識した言い方。",
    relatedWords: ["road", "avenue", "sidewalk"],
  },
  {
    id: "stressful",
    word: "stressful",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ストレスの多い、緊張する"],
    pronunciation: "/ˈstresfl/",
    exampleSentence: "The week before the exam was very stressful.",
    exampleTranslationJa: "試験の前の週はとてもストレスが多かった。",
    collocations: ["a stressful job", "a stressful week", "feel stressful"],
    mnemonic: "stress(緊張・圧力) + -ful(いっぱいの)。名詞と形容詞が同じ形の -ful に注意する。",
    wordFormation: "stress(緊張) + -ful(〜に満ちた)。useful・helpful と同じ形容詞の作り。",
    relatedWords: ["stress", "tiring", "relaxing"],
  },
  {
    id: "strong",
    word: "strong",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["強い", "丈夫な", "味が濃い"],
    pronunciation: "/strɔːŋ/",
    exampleSentence: "He is strong enough to lift that heavy box.",
    exampleTranslationJa: "彼はあの重い箱を持ち上げられるほど力がある。",
    collocations: ["strong wind", "strong coffee", "a strong team"],
    mnemonic: "「強い」。弱いを表す weak と対になり、味や香りの濃さにも使える。名詞形は strength。",
    relatedWords: ["strength", "weak", "powerful"],
  },
  {
    id: "student",
    word: "student",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["学生、生徒"],
    pronunciation: "/ˈstuːdnt/",
    exampleSentence: "Every student must bring a notebook to class.",
    exampleTranslationJa: "すべての学生は授業にノートを持参すること。",
    collocations: ["a university student", "a good student", "an exchange student"],
    mnemonic: "study(勉強する) + -ent(人)。勉強する人が student で、動詞から人を表す名詞を作る典型。",
    wordFormation: "study(勉強する) + -ent(〜する人)。-ent は動詞に付いて人を表す接尾辞。",
    relatedWords: ["study", "teacher", "pupil"],
  },
  {
    id: "study",
    word: "study",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["勉強する", "研究、勉強"],
    pronunciation: "/ˈstʌdi/",
    exampleSentence: "I study English for an hour every night.",
    exampleTranslationJa: "私は毎晩1時間英語を勉強する。",
    collocations: ["study for an exam", "study English", "study at home"],
    mnemonic: "「勉強する」と「研究」。learn が身につくことを指すのに対し、study は努力して取り組むことを指す。",
    relatedWords: ["learn", "student", "research"],
  },
  {
    id: "summer",
    word: "summer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["夏"],
    pronunciation: "/ˈsʌmər/",
    exampleSentence: "We swim in the sea every summer.",
    exampleTranslationJa: "私たちは毎年夏に海で泳ぐ。",
    collocations: ["this summer", "a summer holiday", "in summer"],
    mnemonic: "「夏」。四季を表す語で、前置詞は in を使う。名詞のまま summer holiday のように名詞を修飾する。",
    relatedWords: ["winter", "spring", "autumn"],
  },
  {
    id: "sun",
    word: "sun",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["太陽", "日光"],
    pronunciation: "/sʌn/",
    exampleSentence: "The sun rises early in the morning in June.",
    exampleTranslationJa: "6月は朝早く日が昇る。",
    collocations: ["the sun rises", "in the sun", "under the sun"],
    mnemonic: "「太陽」。son(息子)と同音なので、the sun rises のような決まった言い方で区別する。",
    relatedWords: ["sunny", "sunshine", "moon"],
  },
  {
    id: "sunbathe",
    word: "sunbathe",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["日光浴をする、日なたぼっこをする"],
    pronunciation: "/ˈsʌnbeɪð/",
    exampleSentence: "They sunbathe on the beach all afternoon.",
    exampleTranslationJa: "彼らは午後じゅう浜辺で日光浴をする。",
    collocations: ["sunbathe on the beach", "sunbathe in the garden", "lie and sunbathe"],
    mnemonic: "sun(太陽) + bathe(浴びる)。bath が名詞、bathe が動詞で、日光を浴びる動作を表す。",
    wordFormation: "sun(太陽) + bathe(浴びる)。bath(名詞)に対する動詞が bathe。",
    relatedWords: ["sunbathing", "sunburn", "beach"],
  },
  {
    id: "sunburn",
    word: "sunburn",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日焼け"],
    pronunciation: "/ˈsʌnbɜːrn/",
    exampleSentence: "He got a bad sunburn on his shoulders.",
    exampleTranslationJa: "彼は肩にひどい日焼けをした。",
    collocations: ["get a sunburn", "a bad sunburn", "protect against sunburn"],
    mnemonic: "sun(太陽) + burn(やけど)。赤く痛くなる日焼けを指し、健康的な小麦色は suntan という。",
    wordFormation: "sun(太陽) + burn(やけど)。同じ作りに suntan・sunshine がある。",
    relatedWords: ["sunbathe", "suntan", "skin"],
  },
  {
    id: "punctuality",
    word: "punctuality",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["時間を守ること、正確さ"],
    pronunciation: "/ˌpʌŋktʃuˈæləti/",
    exampleSentence: "Punctuality is important at this company.",
    exampleTranslationJa: "この会社では時間を守ることが大切だ。",
    collocations: ["the importance of punctuality", "strict about punctuality", "value punctuality"],
    mnemonic: "punctual(時間を守る) + -ity(性質)。point(点)と同じ語根で「ちょうどその時点」が芯の意味。",
    wordFormation: "punctual(時間を守る) + -ity(性質を表す名詞の接尾辞)。",
    relatedWords: ["punctual", "deadline", "schedule"],
  },
  {
    id: "sunglasses",
    word: "sunglasses",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["サングラス"],
    pronunciation: "/ˈsʌnɡlæsɪz/",
    exampleSentence: "She put on her sunglasses in the bright sun.",
    exampleTranslationJa: "彼女はまぶしい日差しの中でサングラスをかけた。",
    collocations: ["a pair of sunglasses", "wear sunglasses", "dark sunglasses"],
    mnemonic: "sun(太陽) + glasses(眼鏡)。レンズが2つで1組なので、常に複数形の sunglasses で使う。",
    wordFormation: "sun(太陽) + glasses(眼鏡)。2つの部分からなる物は複数形で使う。",
    relatedWords: ["glasses", "sun", "shade"],
  },
  {
    id: "sunshine",
    word: "sunshine",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日光、晴天"],
    pronunciation: "/ˈsʌnʃaɪn/",
    exampleSentence: "We had warm sunshine all weekend.",
    exampleTranslationJa: "週末はずっと暖かい日差しだった。",
    collocations: ["bright sunshine", "in the sunshine", "a day of sunshine"],
    mnemonic: "sun(太陽) + shine(輝き)。太陽の光そのものを指し、晴れた天気を表すのにも使われる。",
    wordFormation: "sun(太陽) + shine(輝く)。動詞と名詞が同形の語との複合。",
    relatedWords: ["sun", "sunny", "bright"],
  },
  {
    id: "swimsuit",
    word: "swimsuit",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["水着"],
    pronunciation: "/ˈswɪmsuːt/",
    exampleSentence: "She bought a new swimsuit for the summer.",
    exampleTranslationJa: "彼女は夏のために新しい水着を買った。",
    collocations: ["wear a swimsuit", "a new swimsuit", "a swimsuit for the pool"],
    mnemonic: "swim(泳ぐ) + suit(一式)。泳ぐときに着る服で、イギリス英語では swimming costume とも言う。",
    wordFormation: "swim(泳ぐ) + suit(一式)。同じ作りに tracksuit・wetsuit がある。",
    relatedWords: ["swim", "pool", "beach"],
  },
  {
    id: "synagogue",
    word: "synagogue",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["シナゴーグ、ユダヤ教の礼拝所"],
    pronunciation: "/ˈsɪnəɡɑːɡ/",
    exampleSentence: "They go to the synagogue on Friday evening.",
    exampleTranslationJa: "彼らは金曜の夕方に礼拝所へ行く。",
    collocations: ["go to the synagogue", "a local synagogue", "the synagogue service"],
    mnemonic: "「集まる」を意味するギリシャ語に由来するユダヤ教の礼拝所。church・mosque と並べて覚える。",
    relatedWords: ["church", "mosque", "temple"],
  },
  {
    id: "table",
    word: "table",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["テーブル、食卓", "表"],
    pronunciation: "/ˈteɪbl/",
    exampleSentence: "We put the plates on the kitchen table.",
    exampleTranslationJa: "私たちは皿を台所のテーブルに置いた。",
    collocations: ["at the table", "set the table", "a table for two"],
    mnemonic: "「食卓・机」と「表」の2つ。set the table は食卓の準備をすること。table の「表」は数表を指す。",
    relatedWords: ["desk", "chair", "chart"],
  },
  {
    id: "take",
    word: "take",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["取る、持っていく", "乗る", "時間がかかる"],
    pronunciation: "/teɪk/",
    exampleSentence: "Please take an umbrella with you today.",
    exampleTranslationJa: "今日は傘を持っていってください。",
    collocations: ["take a shower", "take care of", "take a photo"],
    mnemonic: "bring がこちらへ運ぶのに対し、take は話し手から離れる方向へ運ぶ。take a photo のように動作も表す。",
    relatedWords: ["bring", "carry", "get"],
  },
  {
    id: "take care of",
    word: "take care of",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["〜の世話をする", "〜に対処する"],
    pronunciation: "/ˌteɪk ˈker əv/",
    exampleSentence: "She takes care of her grandmother every weekend.",
    exampleTranslationJa: "彼女は毎週末、祖母の世話をする。",
    collocations: ["take care of a child", "take care of the plants", "take good care of"],
    mnemonic: "take(取る) + care(気づかい)。人や物の面倒を見る意味と、用事を片づける意味の両方がある。",
    relatedWords: ["care", "look after", "protect"],
  },
  {
    id: "tall",
    word: "tall",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["背が高い", "高い"],
    pronunciation: "/tɔːl/",
    exampleSentence: "My brother is taller than our father now.",
    exampleTranslationJa: "弟は今では父より背が高い。",
    collocations: ["a tall building", "tall enough", "grow tall"],
    mnemonic: "背が高いのは tall、物や山の高さは high。人について high を使うと不自然になるので区別する。",
    relatedWords: ["high", "short", "height"],
  },
  {
    id: "tambourine",
    word: "tambourine",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["タンバリン"],
    pronunciation: "/ˌtæmbəˈriːn/",
    exampleSentence: "She shook the tambourine and sang along.",
    exampleTranslationJa: "彼女はタンバリンを振って一緒に歌った。",
    collocations: ["play the tambourine", "shake a tambourine", "a tambourine in the band"],
    mnemonic: "手で持って振る小さな太鼓。drum(太鼓)の一種で、輪の側面に小さな金属の円盤がついている。",
    relatedWords: ["drum", "bell", "instrument"],
  },
  {
    id: "taxi",
    word: "taxi",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["タクシー"],
    pronunciation: "/ˈtæksi/",
    exampleSentence: "We took a taxi to the airport this morning.",
    exampleTranslationJa: "私たちは今朝、空港までタクシーに乗った。",
    collocations: ["take a taxi", "call a taxi", "by taxi"],
    mnemonic: "「タクシー」。乗るときは take a taxi、移動の手段として言うときは by taxi と前置詞を使い分ける。",
    relatedWords: ["cab", "driver", "fare"],
  },
  {
    id: "tea",
    word: "tea",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["茶、紅茶", "お茶の時間"],
    pronunciation: "/tiː/",
    exampleSentence: "She drinks a cup of tea after dinner.",
    exampleTranslationJa: "彼女は夕食後に紅茶を1杯飲む。",
    collocations: ["a cup of tea", "green tea", "make tea"],
    mnemonic: "「茶」。緑茶も紅茶も英語では tea で、ミルクを入れない紅茶は black tea という。",
    relatedWords: ["coffee", "cup", "drink"],
  },
  {
    id: "teach",
    word: "teach",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["教える"],
    pronunciation: "/tiːtʃ/",
    exampleSentence: "Our new teacher will teach us science this year.",
    exampleTranslationJa: "新しい先生は今年、私たちに理科を教える。",
    collocations: ["teach English", "teach someone to swim", "teach a class"],
    mnemonic: "「教える」。過去形は taught で不規則。学ぶ側から見た語が learn で、give と同様の変化をする。",
    relatedWords: ["teacher", "learn", "explain"],
  },
  {
    id: "teacher",
    word: "teacher",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["教師、先生"],
    pronunciation: "/ˈtiːtʃər/",
    exampleSentence: "Our English teacher speaks very clearly.",
    exampleTranslationJa: "私たちの英語の先生はとてもはっきり話す。",
    collocations: ["an English teacher", "a class teacher", "become a teacher"],
    mnemonic: "teach(教える) + -er(人)。教える人が teacher、学ぶ人が student。役割の対で覚える。",
    wordFormation: "teach(教える) + -er(人)。動詞に -er を付けると「する人」を表す。",
    relatedWords: ["teach", "student", "school"],
  },
  {
    id: "team",
    word: "team",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["チーム、組"],
    pronunciation: "/tiːm/",
    exampleSentence: "Our team won the game by two points.",
    exampleTranslationJa: "私たちのチームは2点差で試合に勝った。",
    collocations: ["a football team", "join a team", "work as a team"],
    mnemonic: "「チーム」。1つのまとまりとして扱うので、イギリス英語では複数扱いすることがある。",
    relatedWords: ["group", "member", "player"],
  },
  {
    id: "telephone",
    word: "telephone",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["電話", "電話をかける"],
    pronunciation: "/ˈtelɪfoʊn/",
    exampleSentence: "He answered the telephone on the first ring.",
    exampleTranslationJa: "彼は1回目の呼び出しで電話に出た。",
    collocations: ["answer the telephone", "by telephone", "a telephone call"],
    mnemonic: "tele-(遠く) + phone(音)。離れた相手と話す道具を指し、日常では phone と短く言う。",
    wordFormation: "tele-(遠く) + phone(音)。television の tele- と同じ接頭辞。",
    relatedWords: ["phone", "call", "mobile"],
  },
  {
    id: "television",
    word: "television",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["テレビ、テレビ放送"],
    pronunciation: "/ˈtelɪvɪʒn/",
    exampleSentence: "We watched the match on television last night.",
    exampleTranslationJa: "私たちは昨夜テレビで試合を見た。",
    collocations: ["watch television", "on television", "a television program"],
    mnemonic: "tele-(遠く) + vision(映像)。遠くの映像を届ける装置で、略して TV と呼ばれる。",
    wordFormation: "tele-(遠く) + vision(映像)。telephone の tele- と同じ接頭辞。",
    relatedWords: ["TV", "screen", "program"],
  },
  {
    id: "tell",
    word: "tell",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["話す、伝える", "見分ける"],
    pronunciation: "/tel/",
    exampleSentence: "Please tell me the truth about yesterday.",
    exampleTranslationJa: "昨日の本当のことを話してください。",
    collocations: ["tell a story", "tell someone the truth", "tell the difference"],
    mnemonic: "tell は人に伝える、say は内容を言う。tell A B の語順で「AにBを伝える」となる。",
    relatedWords: ["say", "speak", "inform"],
  },
  {
    id: "ten",
    word: "ten",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["10、十", "10歳"],
    pronunciation: "/ten/",
    exampleSentence: "The class starts at ten in the morning.",
    exampleTranslationJa: "授業は午前10時に始まる。",
    collocations: ["ten o'clock", "ten years old", "at ten"],
    mnemonic: "10を表す数。指の数と同じで、tenth(10番目)・teenager(10代)の土台になる語。",
    relatedWords: ["tenth", "teenager", "twenty"],
  },
  {
    id: "tennis",
    word: "tennis",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["テニス"],
    pronunciation: "/ˈtenɪs/",
    exampleSentence: "We play tennis on the court every Sunday.",
    exampleTranslationJa: "私たちは毎週日曜日にコートでテニスをする。",
    collocations: ["play tennis", "a tennis court", "a tennis match"],
    mnemonic: "球技の名は play と結びつく。play tennis のように、競技名の前に冠詞をつけない点に注意する。",
    relatedWords: ["sport", "court", "racket"],
  },
  {
    id: "tenth",
    word: "tenth",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["10番目の", "10分の1"],
    pronunciation: "/tenθ/",
    exampleSentence: "This is the tenth time I have called you.",
    exampleTranslationJa: "あなたに電話するのはこれで10回目だ。",
    collocations: ["the tenth floor", "the tenth of May", "finish tenth"],
    mnemonic: "ten + -th(序数の接尾辞)。-th の音は舌先を上の歯の間に軽く当てて息を出す。",
    relatedWords: ["ten", "ninth", "order"],
  },
  {
    id: "terrible",
    word: "terrible",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ひどい、恐ろしい", "とても下手な"],
    pronunciation: "/ˈterəbl/",
    exampleSentence: "The weather was terrible during our holiday.",
    exampleTranslationJa: "休暇中は天気がひどかった。",
    collocations: ["a terrible mistake", "terrible weather", "feel terrible"],
    mnemonic: "terror(恐怖)と同じ語源で「恐ろしいほど悪い」。副詞の terribly は「とても」の意味でも使う。",
    relatedWords: ["terribly", "awful", "wonderful"],
  },
  {
    id: "test",
    word: "test",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["試験、テスト", "試す、検査する"],
    pronunciation: "/test/",
    exampleSentence: "We have a math test on Friday morning.",
    exampleTranslationJa: "私たちは金曜日の朝に数学の試験がある。",
    collocations: ["take a test", "pass a test", "a test result"],
    mnemonic: "「試験」と「試す」。exam より小さめの確認テストを指すことが多く、take a test で「試験を受ける」。",
    relatedWords: ["exam", "quiz", "check"],
  },
  {
    id: "than",
    word: "than",
    level: "A2",
    partOfSpeech: "接続詞・前置詞",
    meaningsJa: ["〜より"],
    pronunciation: "/ðæn/",
    exampleSentence: "This bag is lighter than my old one.",
    exampleTranslationJa: "このかばんは前のものより軽い。",
    collocations: ["more than", "less than", "better than"],
    mnemonic: "比較級のあとに置く語。more than や better than のように、比べる相手を導く働きを持つ。",
    relatedWords: ["then", "more", "less"],
  },
  {
    id: "thank",
    word: "thank",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["感謝する、礼を言う"],
    pronunciation: "/θæŋk/",
    exampleSentence: "I want to thank you for your kind help.",
    exampleTranslationJa: "親切な助けに感謝したい。",
    collocations: ["thank you for", "thank someone for", "thank God"],
    mnemonic: "think と同じ th の音。thank someone for 〜 の形で「人に〜の礼を言う」となる。",
    relatedWords: ["thanks", "grateful", "appreciate"],
  },
  {
    id: "the",
    word: "the",
    level: "A2",
    partOfSpeech: "冠詞",
    meaningsJa: ["その、例の(特定のものを指す)"],
    pronunciation: "/ðə/",
    exampleSentence: "The book on the desk is mine.",
    exampleTranslationJa: "机の上の本は私のものだ。",
    collocations: ["the same as", "the other day", "the first time"],
    mnemonic: "話し手と聞き手がどれを指すか分かっているときに使う冠詞。母音の音の前では /ði/ と発音する。",
    relatedWords: ["a", "an", "this"],
  },
  {
    id: "theater",
    word: "theater",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["劇場、演劇"],
    pronunciation: "/ˈθiːətər/",
    exampleSentence: "We saw a musical at the theater last night.",
    exampleTranslationJa: "私たちは昨夜、劇場でミュージカルを見た。",
    collocations: ["go to the theater", "a movie theater", "at the theater"],
    mnemonic: "「劇場」。アメリカ綴りは theater、イギリス綴りは theatre で、発音はどちらも同じ。",
    relatedWords: ["theatre", "stage", "musical"],
  },
  {
    id: "theatre",
    word: "theatre",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["劇場、演劇"],
    pronunciation: "/ˈθiːətər/",
    exampleSentence: "The new theatre opens in the city centre.",
    exampleTranslationJa: "新しい劇場が市の中心に開く。",
    collocations: ["a theatre ticket", "go to the theatre", "the theatre company"],
    mnemonic: "theater のイギリス綴り。同じ意味で、演劇全体を指すのにも使われる。語尾は -tre と綴る。",
    relatedWords: ["theater", "stage", "drama"],
  },
  {
    id: "their",
    word: "their",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["彼らの、彼女らの"],
    pronunciation: "/ðer/",
    exampleSentence: "The students left their bags in the classroom.",
    exampleTranslationJa: "学生たちは教室にかばんを置き忘れた。",
    collocations: ["their own", "their parents", "in their opinion"],
    mnemonic: "they の所有格。there(そこに)・they're(they are)と同音なので、意味で書き分ける。",
    relatedWords: ["they", "them", "theirs"],
  },
  {
    id: "them",
    word: "them",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["彼らを、彼らに"],
    pronunciation: "/ðem/",
    exampleSentence: "I gave them the keys to the office.",
    exampleTranslationJa: "私は彼らに事務所の鍵を渡した。",
    collocations: ["tell them", "with them", "one of them"],
    mnemonic: "they の目的格。動詞や前置詞の目的語として使う。one of them で「彼らのうちの1人」。",
    relatedWords: ["they", "their", "us"],
  },
  {
    id: "then",
    word: "then",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["そのとき、それから", "そのうえ"],
    pronunciation: "/ðen/",
    exampleSentence: "We ate lunch and then walked to the museum.",
    exampleTranslationJa: "私たちは昼食を食べ、それから博物館まで歩いた。",
    collocations: ["and then", "by then", "since then"],
    mnemonic: "「そのとき」と「それから」。時間の順序をつなぐ語で、than(〜より)とは綴りが違う。",
    relatedWords: ["than", "now", "later"],
  },
  {
    id: "there",
    word: "there",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["そこに、そこへ", "〜がある"],
    pronunciation: "/ðer/",
    exampleSentence: "There is a small park behind the station.",
    exampleTranslationJa: "駅の後ろに小さな公園がある。",
    collocations: ["over there", "there is", "here and there"],
    mnemonic: "「そこに」と「〜がある」。there is / there are は、初めて話題にする物の存在を伝える形。",
    relatedWords: ["here", "where", "their"],
  },
  {
    id: "these",
    word: "these",
    level: "A2",
    partOfSpeech: "限定詞・代名詞",
    meaningsJa: ["これらの"],
    pronunciation: "/ðiːz/",
    exampleSentence: "These shoes are too small for me.",
    exampleTranslationJa: "この靴は私には小さすぎる。",
    collocations: ["these days", "one of these days", "these ones"],
    mnemonic: "this の複数形。話し手の近くにある複数を指し、遠くにある複数なら those を使う。",
    relatedWords: ["this", "those", "them"],
  },
  {
    id: "they",
    word: "they",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["彼らは、彼女らは、それらは"],
    pronunciation: "/ðeɪ/",
    exampleSentence: "They are waiting for us at the bus stop.",
    exampleTranslationJa: "彼らはバス停で私たちを待っている。",
    collocations: ["they say", "they are", "as they do"],
    mnemonic: "複数の人や物を指す主格の代名詞。所有格は their、目的格は them と形が変わる。",
    relatedWords: ["their", "them", "we"],
  },
  {
    id: "thing",
    word: "thing",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["物、こと", "事柄"],
    pronunciation: "/θɪŋ/",
    exampleSentence: "The first thing to do is open the windows.",
    exampleTranslationJa: "まず最初にすべきことは窓を開けることだ。",
    collocations: ["the first thing", "a good thing", "for one thing"],
    mnemonic: "「物」と「こと」。数えられる名詞で、something や anything の -thing と同じ語。",
    relatedWords: ["something", "object", "matter"],
  },
  {
    id: "think",
    word: "think",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["考える、思う"],
    pronunciation: "/θɪŋk/",
    exampleSentence: "I think it will rain this afternoon.",
    exampleTranslationJa: "午後は雨が降ると思う。",
    collocations: ["think about", "think of", "think so"],
    mnemonic: "think about は「じっくり考える」、think of は「思いつく」。過去形は thought で不規則。",
    relatedWords: ["thought", "believe", "idea"],
  },
  {
    id: "thirsty",
    word: "thirsty",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["のどが渇いて"],
    pronunciation: "/ˈθɜːrsti/",
    exampleSentence: "After the long walk we were very thirsty.",
    exampleTranslationJa: "長く歩いたあと、私たちはとてものどが渇いていた。",
    collocations: ["feel thirsty", "get thirsty", "hungry and thirsty"],
    mnemonic: "thirst(渇き) + -y。空腹を表す hungry と対で、何か飲みたい状態を指す。",
    wordFormation: "thirst(渇き) + -y(〜の状態の)。hungry・sleepy と同じ作り。",
    relatedWords: ["thirst", "hungry", "drink"],
  },
  {
    id: "thirteen",
    word: "thirteen",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["13、十三", "13歳"],
    pronunciation: "/ˌθɜːrˈtiːn/",
    exampleSentence: "My cousin is thirteen years old this year.",
    exampleTranslationJa: "いとこは今年13歳になる。",
    collocations: ["turn thirteen", "thirteen years old", "at thirteen"],
    mnemonic: "three(3) + -teen(10の位)。three の綴りが thir- に変わる点と、後ろの強勢に注意する。",
    relatedWords: ["three", "thirty", "teenager"],
  },
  {
    id: "thirty",
    word: "thirty",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["30、三十", "30歳"],
    pronunciation: "/ˈθɜːrti/",
    exampleSentence: "The meeting will start in thirty minutes.",
    exampleTranslationJa: "会議は30分後に始まる。",
    collocations: ["thirty years old", "in his thirties", "around thirty"],
    mnemonic: "three(3) + -ty(10の倍数)。13の thirteen と語尾だけが違うので、強勢の位置で聞き分ける。",
    relatedWords: ["three", "thirteen", "forty"],
  },
  {
    id: "those",
    word: "those",
    level: "A2",
    partOfSpeech: "限定詞・代名詞",
    meaningsJa: ["あれらの、それらの"],
    pronunciation: "/ðoʊz/",
    exampleSentence: "Those flowers in the garden are beautiful.",
    exampleTranslationJa: "庭のあの花は美しい。",
    collocations: ["those days", "one of those", "those people"],
    mnemonic: "that の複数形。話し手から遠い複数を指し、近くにある複数なら these を使う。",
    relatedWords: ["these", "that", "them"],
  },
  {
    id: "thousand",
    word: "thousand",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["1000、千", "多数の"],
    pronunciation: "/ˈθaʊznd/",
    exampleSentence: "The library has more than five thousand books.",
    exampleTranslationJa: "その図書館には5000冊以上の本がある。",
    collocations: ["a thousand years", "thousands of", "two thousand"],
    mnemonic: "1000を表す。ぴったりの数なら a thousand のまま、漠然と多数なら thousands of の形にする。",
    relatedWords: ["hundred", "million", "number"],
  },
  {
    id: "three",
    word: "three",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["3、三", "3つ"],
    pronunciation: "/θriː/",
    exampleSentence: "They have three children and a dog.",
    exampleTranslationJa: "彼らには3人の子どもと犬が1匹いる。",
    collocations: ["three years old", "in three days", "three times"],
    mnemonic: "3を表す数。th の音は舌先を上の歯の間に軽く当てる。third・thirteen の土台になる。",
    relatedWords: ["third", "thirteen", "thirty"],
  },
  {
    id: "through",
    word: "through",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜を通って、〜を貫いて", "〜の間じゅう"],
    pronunciation: "/θruː/",
    exampleSentence: "The train went through a long tunnel.",
    exampleTranslationJa: "列車は長いトンネルを通っていった。",
    collocations: ["go through", "all through the night", "through the window"],
    mnemonic: "「通り抜けて」。across が面を横切るのに対し、through は中を抜けていくイメージ。",
    relatedWords: ["across", "into", "past"],
  },
  {
    id: "planner",
    word: "planner",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["予定表、手帳", "計画する人"],
    pronunciation: "/ˈplænər/",
    exampleSentence: "She writes her schedule in a small planner.",
    exampleTranslationJa: "彼女は小さな手帳に予定を書き込む。",
    collocations: ["a weekly planner", "write in a planner", "a study planner"],
    mnemonic: "plan(計画) + -er。予定を書き込む手帳と、計画を立てる人の両方を指す。",
    wordFormation: "plan(計画) + -er(物・人)。同じ形で道具と人を表す。",
    relatedWords: ["plan", "schedule", "calendar"],
  },
  {
    id: "ticket",
    word: "ticket",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["切符、チケット", "違反切符"],
    pronunciation: "/ˈtɪkɪt/",
    exampleSentence: "I bought two tickets for the concert.",
    exampleTranslationJa: "私はコンサートのチケットを2枚買った。",
    collocations: ["a train ticket", "buy a ticket", "a ticket for the concert"],
    mnemonic: "「切符・チケット」。乗り物でも催しでも使う。違反切符の意味にもなる点に注意する。",
    relatedWords: ["fare", "pass", "seat"],
  },
  {
    id: "tidy up",
    word: "tidy up",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["片づける、整理する"],
    pronunciation: "/ˌtaɪdi ˈʌp/",
    exampleSentence: "Please tidy up your room before dinner.",
    exampleTranslationJa: "夕食の前に部屋を片づけてください。",
    collocations: ["tidy up the room", "tidy up after", "tidy up your desk"],
    mnemonic: "tidy(きちんとした) + up(すっかり)。散らかった物を元の場所へ戻して整える動作を表す。",
    relatedWords: ["tidy", "clean", "organize"],
  },
  {
    id: "tin opener",
    word: "tin opener",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["缶切り"],
    pronunciation: "/ˈtɪn ˌoʊpənər/",
    exampleSentence: "I cannot find the tin opener in this drawer.",
    exampleTranslationJa: "この引き出しに缶切りが見当たらない。",
    collocations: ["use a tin opener", "a tin opener for cans", "where is the tin opener"],
    mnemonic: "tin(ブリキ缶) + opener(開ける道具)。缶を開ける道具で、アメリカ英語では can opener。",
    wordFormation: "tin(缶) + opener(開ける道具)。open(開ける) + -er(道具)の複合名詞。",
    relatedWords: ["open", "can", "kitchen"],
  },
]
