import type { VocabularyEntry } from '../types'

// 増補 第16弾。ビジネス・金融、住まいと不動産、報道とネット。
// 和製英語との食い違い(mansion, prime time, ゴールデンタイム)は覚えるヒントで必ず注記する。
export const plus16: VocabularyEntry[] = [
  {
    id: "ledger",
    word: "ledger",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["元帳、取引記録簿"],
    pronunciation: "/ˈledʒər/",
    exampleSentence: "Every payment is entered in the ledger.",
    exampleTranslationJa: "すべての支払いは元帳に記入される。",
    collocations: ["a company ledger", "enter in the ledger", "a distributed ledger"],
    mnemonic: "帳簿。ブロックチェーンの「分散台帳」も a distributed ledger。",
    relatedWords: ["accounts", "record", "book"],
  },
  {
    id: "overhead",
    word: "overhead",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["経常経費、間接費", "頭上の"],
    pronunciation: "/ˈoʊvərhed/",
    exampleSentence: "Working from home cut their overheads.",
    exampleTranslationJa: "在宅勤務で彼らは経費を削減した。",
    collocations: ["reduce overheads", "overhead costs", "an overhead cable"],
    mnemonic: "家賃や光熱費など、売上に直結しない固定費。英では複数形 overheads。",
    relatedWords: ["expenses", "costs", "running costs"],
  },
  {
    id: "markup",
    word: "markup",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["利幅、上乗せ幅"],
    pronunciation: "/ˈmɑːrkʌp/",
    exampleSentence: "The markup on drinks is very high.",
    exampleTranslationJa: "飲み物の利幅はとても大きい。",
    collocations: ["a high markup", "the markup on"],
    mnemonic: "仕入れ値にいくら上乗せするか。margin は売値に対する割合で別物。",
    relatedWords: ["margin", "profit", "cost"],
  },
  {
    id: "dividend",
    word: "dividend",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["配当金", "(比喩)見返り"],
    pronunciation: "/ˈdɪvɪdend/",
    exampleSentence: "The company pays a dividend twice a year.",
    exampleTranslationJa: "その会社は年2回配当を出す。",
    collocations: ["pay a dividend", "a dividend yield", "pay dividends"],
    mnemonic: "pay dividends は比喩で「のちのち効いてくる」。divide(分ける)から。",
    relatedWords: ["profit", "payout", "share"],
  },
  {
    id: "stakeholder",
    word: "stakeholder",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["利害関係者"],
    pronunciation: "/ˈsteɪkhoʊldər/",
    exampleSentence: "All stakeholders were consulted.",
    exampleTranslationJa: "すべての利害関係者に意見が求められた。",
    collocations: ["key stakeholders", "stakeholder engagement"],
    mnemonic: "株主(shareholder)より広く、従業員・顧客・地域も含む。",
    relatedWords: ["shareholder", "party", "interest"],
  },
  {
    id: "equity",
    word: "equity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["純資産、株式", "公平"],
    pronunciation: "/ˈekwəti/",
    exampleSentence: "They raised money by selling equity.",
    exampleTranslationJa: "彼らは株式を売って資金を調達した。",
    collocations: ["private equity", "negative equity", "equity and fairness"],
    mnemonic: "equal と同語根。金融では「持ち分」、社会では「公平」。",
    relatedWords: ["shares", "fairness", "capital"],
  },
  {
    id: "broker",
    word: "broker",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["仲買人、ブローカー", "(合意を)仲介する"],
    pronunciation: "/ˈbroʊkər/",
    exampleSentence: "The UN brokered a ceasefire.",
    exampleTranslationJa: "国連が停戦を仲介した。",
    collocations: ["an insurance broker", "broker a deal", "a mortgage broker"],
    mnemonic: "金融の仲買人だけでなく、動詞で「取り決めをまとめる」意味が重要。",
    relatedWords: ["agent", "dealer", "mediate"],
  },
  {
    id: "valuation",
    word: "valuation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["評価額、査定"],
    pronunciation: "/ˌvæljuˈeɪʃn/",
    exampleSentence: "The company received a billion-dollar valuation.",
    exampleTranslationJa: "その会社は10億ドルの評価額をつけられた。",
    collocations: ["a high valuation", "get a valuation", "property valuation"],
    mnemonic: "value(価値)+ -ation。いくらの値がつくかという見積もり。",
    relatedWords: ["appraisal", "estimate", "value"],
  },
  {
    id: "takeover",
    word: "takeover",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["企業買収、乗っ取り"],
    pronunciation: "/ˈteɪkoʊvər/",
    exampleSentence: "The takeover was blocked by regulators.",
    exampleTranslationJa: "その買収は規制当局に阻止された。",
    collocations: ["a hostile takeover", "a takeover bid", "block a takeover"],
    mnemonic: "句動詞 take over が名詞に。相手が嫌がる場合は hostile takeover。",
    relatedWords: ["acquisition", "merger", "buyout"],
  },
  {
    id: "buyout",
    word: "buyout",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["買収、買い取り"],
    pronunciation: "/ˈbaɪaʊt/",
    exampleSentence: "Staff financed a management buyout.",
    exampleTranslationJa: "従業員が経営陣による買収に出資した。",
    collocations: ["a management buyout", "a leveraged buyout"],
    mnemonic: "持ち分を全部買い取ること。経営陣が買うのが a management buyout。",
    relatedWords: ["takeover", "acquisition", "purchase"],
  },
  {
    id: "cartel",
    word: "cartel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["カルテル、企業連合"],
    pronunciation: "/kɑːrˈtel/",
    exampleSentence: "The firms were fined for operating a cartel.",
    exampleTranslationJa: "それらの企業はカルテルを結んだとして制裁金を科された。",
    collocations: ["a price-fixing cartel", "break up a cartel"],
    mnemonic: "価格を申し合わせる違法な連合。麻薬組織にも使う。",
    relatedWords: ["monopoly", "syndicate", "collusion"],
  },
  {
    id: "antitrust",
    word: "antitrust",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["独占禁止の"],
    pronunciation: "/ˌæntiˈtrʌst/",
    exampleSentence: "The firm faces an antitrust investigation.",
    exampleTranslationJa: "その会社は独占禁止法の調査を受けている。",
    collocations: ["antitrust law", "an antitrust case", "antitrust regulators"],
    mnemonic: "米語。trust は昔の独占企業体。英では competition law。",
    relatedWords: ["monopoly", "competition", "regulation"],
  },
  {
    id: "tariff",
    word: "tariff",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["関税", "料金表"],
    pronunciation: "/ˈtærɪf/",
    exampleSentence: "New tariffs were imposed on steel.",
    exampleTranslationJa: "鉄鋼に新たな関税が課された。",
    collocations: ["impose tariffs", "tariff barriers", "a tariff on imports"],
    mnemonic: "輸入品にかける税。電気やホテルの「料金表」の意味もある。",
    relatedWords: ["duty", "tax", "import"],
  },
  {
    id: "procurement",
    word: "procurement",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["調達、購買"],
    pronunciation: "/prəˈkjʊrmənt/",
    exampleSentence: "Public procurement rules are strict.",
    exampleTranslationJa: "公共調達の規則は厳格だ。",
    collocations: ["public procurement", "procurement process", "defence procurement"],
    mnemonic: "procure(調達する)の名詞形。官公庁や大企業の購買部門の用語。",
    relatedWords: ["purchasing", "acquisition", "supply"],
  },
  {
    id: "logistics",
    word: "logistics",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["物流、段取り"],
    pronunciation: "/ləˈdʒɪstɪks/",
    exampleSentence: "The logistics of moving 300 people are complex.",
    exampleTranslationJa: "300人を移動させる段取りは複雑だ。",
    collocations: ["the logistics of", "a logistics company", "logistical problems"],
    mnemonic: "-ics で単数扱い。輸送だけでなく「手配全般」を指す。",
    relatedWords: ["transport", "supply chain", "organisation"],
  },
  {
    id: "distributor",
    word: "distributor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["卸売業者、販売代理店"],
    pronunciation: "/dɪˈstrɪbjətər/",
    exampleSentence: "They appointed a distributor in Europe.",
    exampleTranslationJa: "彼らはヨーロッパに販売代理店を置いた。",
    collocations: ["an exclusive distributor", "appoint a distributor"],
    mnemonic: "メーカーと小売の間に立つ業者。distribute の -or 形。",
    relatedWords: ["wholesaler", "supplier", "retailer"],
  },
  {
    id: "retailer",
    word: "retailer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["小売業者、小売店"],
    pronunciation: "/ˈriːteɪlər/",
    exampleSentence: "Online retailers now dominate the market.",
    exampleTranslationJa: "今やネット小売業者が市場を握っている。",
    collocations: ["a major retailer", "an online retailer", "high-street retailers"],
    mnemonic: "retail(小売り)+ -er。最終の消費者に売る側。",
    relatedWords: ["shop", "wholesaler", "store"],
  },
  {
    id: "wholesaler",
    word: "wholesaler",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["卸売業者"],
    pronunciation: "/ˈhoʊlseɪlər/",
    exampleSentence: "They buy direct from a wholesaler.",
    exampleTranslationJa: "彼らは卸売業者から直接仕入れる。",
    collocations: ["a food wholesaler", "buy from a wholesaler"],
    mnemonic: "whole(まとめて)+ sale。まとめて売る側。反対は retailer。",
    relatedWords: ["retailer", "distributor", "supplier"],
  },
  {
    id: "supplier",
    word: "supplier",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["納入業者、供給元"],
    pronunciation: "/səˈplaɪər/",
    exampleSentence: "We changed suppliers last year.",
    exampleTranslationJa: "私たちは昨年、納入業者を変えた。",
    collocations: ["a key supplier", "change suppliers", "a supplier contract"],
    mnemonic: "supply(供給する)+ -er。原料や部品を納める側。",
    relatedWords: ["vendor", "provider", "distributor"],
  },
  {
    id: "vendor",
    word: "vendor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["売り手、販売業者"],
    pronunciation: "/ˈvendər/",
    exampleSentence: "The vendor accepted our offer.",
    exampleTranslationJa: "売り手は私たちの申し出を受け入れた。",
    collocations: ["a street vendor", "a software vendor", "the vendor and the buyer"],
    mnemonic: "不動産取引の「売り主」も vendor。露天商にも使う。",
    relatedWords: ["seller", "supplier", "buyer"],
  },
  {
    id: "royalty",
    word: "royalty",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["印税、使用料", "王族"],
    pronunciation: "/ˈrɔɪəlti/",
    exampleSentence: "She earns royalties on every copy sold.",
    exampleTranslationJa: "彼女は売れた1冊ごとに印税を得る。",
    collocations: ["earn royalties", "a royalty payment", "a member of royalty"],
    mnemonic: "「王のもの」が原義。著作権使用料と王族の両方を指す。",
    relatedWords: ["fee", "payment", "monarch"],
  },
  {
    id: "licensing",
    word: "licensing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["許諾、ライセンス供与"],
    pronunciation: "/ˈlaɪsnsɪŋ/",
    exampleSentence: "The licensing deal runs for five years.",
    exampleTranslationJa: "その使用許諾契約は5年間続く。",
    collocations: ["a licensing agreement", "licensing rights"],
    mnemonic: "英では名詞 licence / 動詞 license。米は両方 license。",
    relatedWords: ["licence", "permission", "rights"],
  },
  {
    id: "infringement",
    word: "infringement",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["侵害、違反"],
    pronunciation: "/ɪnˈfrɪndʒmənt/",
    exampleSentence: "This is a clear infringement of copyright.",
    exampleTranslationJa: "これは明白な著作権侵害だ。",
    collocations: ["copyright infringement", "an infringement of rights"],
    mnemonic: "infringe(侵害する)の名詞形。権利や規則を踏み越えること。",
    relatedWords: ["violation", "breach", "infringe"],
  },
  {
    id: "counterfeit",
    word: "counterfeit",
    level: "B2",
    partOfSpeech: "形容詞・名詞・動詞",
    meaningsJa: ["偽造の", "偽造品", "偽造する"],
    pronunciation: "/ˈkaʊntərfɪt/",
    exampleSentence: "Counterfeit goods are seized at the border.",
    exampleTranslationJa: "偽造品は国境で押収される。",
    collocations: ["counterfeit goods", "counterfeit notes", "counterfeit money"],
    mnemonic: "counter-(対して)+ feit(作る)。本物に似せて作ったもの。",
    relatedWords: ["fake", "forged", "genuine"],
  },
  {
    id: "whistleblower",
    word: "whistleblower",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["内部告発者"],
    pronunciation: "/ˈwɪslbloʊər/",
    exampleSentence: "The whistleblower was protected by law.",
    exampleTranslationJa: "その内部告発者は法律で守られた。",
    collocations: ["a whistleblower policy", "protect whistleblowers"],
    mnemonic: "審判が笛(whistle)を吹いて反則を止めることから。",
    relatedWords: ["informant", "leak", "expose"],
  },
  {
    id: "downturn",
    word: "downturn",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["景気の落ち込み"],
    pronunciation: "/ˈdaʊntɜːrn/",
    exampleSentence: "The industry faces a sharp downturn.",
    exampleTranslationJa: "その業界は急激な落ち込みに直面している。",
    collocations: ["an economic downturn", "a sharp downturn"],
    mnemonic: "upturn(上向き)の反対。recession より軽い言い方。",
    relatedWords: ["recession", "slump", "upturn"],
  },
  {
    id: "deflation",
    word: "deflation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["デフレ、物価の下落"],
    pronunciation: "/dɪˈfleɪʃn/",
    exampleSentence: "Japan struggled with deflation for years.",
    exampleTranslationJa: "日本は長年デフレに苦しんだ。",
    collocations: ["persistent deflation", "fight deflation"],
    mnemonic: "inflation(物価上昇)の反対。空気が抜ける(deflate)から。",
    relatedWords: ["inflation", "recession", "price fall"],
  },
  {
    id: "austerity",
    word: "austerity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["緊縮財政、耐乏"],
    pronunciation: "/ɔːˈsterəti/",
    exampleSentence: "Years of austerity hit local services.",
    exampleTranslationJa: "何年もの緊縮財政が地域の行政サービスを直撃した。",
    collocations: ["austerity measures", "a decade of austerity"],
    mnemonic: "支出を厳しく切りつめる政策。austere(厳しい)の名詞形。",
    relatedWords: ["cuts", "frugality", "spending"],
  },
  {
    id: "bailout",
    word: "bailout",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["救済措置、公的支援"],
    pronunciation: "/ˈbeɪlaʊt/",
    exampleSentence: "The airline received a government bailout.",
    exampleTranslationJa: "その航空会社は政府の救済を受けた。",
    collocations: ["a government bailout", "a bailout package"],
    mnemonic: "句動詞 bail out が名詞に。沈む船から水をかき出すのが原義。",
    relatedWords: ["rescue", "bail out", "aid"],
  },
  {
    id: "profitability",
    word: "profitability",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["収益性"],
    pronunciation: "/ˌprɑːfɪtəˈbɪləti/",
    exampleSentence: "They improved profitability by closing two sites.",
    exampleTranslationJa: "彼らは2拠点を閉じて収益性を改善した。",
    collocations: ["improve profitability", "long-term profitability"],
    mnemonic: "profitable(もうかる)+ -ity。もうけを生む力があるかどうか。",
    relatedWords: ["profit", "margin", "viability"],
  },
  {
    id: "solvency",
    word: "solvency",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["支払い能力"],
    pronunciation: "/ˈsɑːlvənsi/",
    exampleSentence: "Regulators check the solvency of banks.",
    exampleTranslationJa: "当局は銀行の支払い能力を確認する。",
    collocations: ["financial solvency", "a solvency test"],
    mnemonic: "solvent(支払える)の名詞形。反対は insolvency(支払い不能)。",
    relatedWords: ["solvent", "liquidity", "insolvency"],
  },
  {
    id: "liquidity",
    word: "liquidity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["流動性、すぐ現金にできること"],
    pronunciation: "/lɪˈkwɪdəti/",
    exampleSentence: "The firm ran into liquidity problems.",
    exampleTranslationJa: "その会社は資金繰りに問題を抱えた。",
    collocations: ["liquidity problems", "market liquidity", "provide liquidity"],
    mnemonic: "liquid(液体)から。すぐ動かせる=現金化しやすい資産の量。",
    relatedWords: ["cash flow", "solvency", "assets"],
  },
  {
    id: "depreciation",
    word: "depreciation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["減価償却", "価値の下落"],
    pronunciation: "/dɪˌpriːʃiˈeɪʃn/",
    exampleSentence: "Depreciation is spread over five years.",
    exampleTranslationJa: "減価償却は5年に分けて計上される。",
    collocations: ["depreciation of assets", "currency depreciation"],
    mnemonic: "価値が下がること。会計では「使った分を毎年費用にする」処理。",
    relatedWords: ["decline", "devaluation", "appreciation"],
  },
  {
    id: "freelance",
    word: "freelance",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["フリーランスの、自由契約の"],
    pronunciation: "/ˈfriːlæns/",
    exampleSentence: "She works freelance for three magazines.",
    exampleTranslationJa: "彼女は3誌でフリーランスとして働いている。",
    collocations: ["work freelance", "a freelance journalist", "go freelance"],
    mnemonic: "中世の「主君を持たない槍(lance)兵」が語源。人は freelancer。",
    relatedWords: ["self-employed", "contractor", "staff"],
  },
  {
    id: "self-employed",
    word: "self-employed",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自営の、個人事業の"],
    pronunciation: "/ˌself ɪmˈplɔɪd/",
    exampleSentence: "He has been self-employed since 2015.",
    exampleTranslationJa: "彼は2015年から自営で働いている。",
    collocations: ["become self-employed", "the self-employed"],
    mnemonic: "the self-employed で「自営業者たち」という名詞にもなる。",
    relatedWords: ["freelance", "independent", "employed"],
  },
  {
    id: "payroll",
    word: "payroll",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["給与支払い名簿、人件費"],
    pronunciation: "/ˈpeɪroʊl/",
    exampleSentence: "The company has 200 people on the payroll.",
    exampleTranslationJa: "その会社は200人を雇用している。",
    collocations: ["on the payroll", "payroll costs", "the payroll department"],
    mnemonic: "be on the payroll は「そこに雇われている」。roll は名簿。",
    relatedWords: ["salary", "staff", "wages"],
  },
  {
    id: "severance",
    word: "severance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["解雇手当", "切り離すこと"],
    pronunciation: "/ˈsevərəns/",
    exampleSentence: "He received six months' severance.",
    exampleTranslationJa: "彼は6か月分の解雇手当を受け取った。",
    collocations: ["severance pay", "a severance package"],
    mnemonic: "sever(断ち切る)の名詞形。雇用関係を断つときの支払い。",
    relatedWords: ["redundancy", "compensation", "sever"],
  },
  {
    id: "perk",
    word: "perk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["役得、福利厚生の特典"],
    pronunciation: "/pɜːrk/",
    exampleSentence: "Free travel is one of the perks of the job.",
    exampleTranslationJa: "無料の交通費はその仕事の役得の一つだ。",
    collocations: ["a perk of the job", "staff perks"],
    mnemonic: "perquisite の短縮形。給料以外にもらえるうれしいもの。",
    relatedWords: ["benefit", "bonus", "privilege"],
  },
  {
    id: "attic",
    word: "attic",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["屋根裏部屋"],
    pronunciation: "/ˈætɪk/",
    exampleSentence: "The old letters were found in the attic.",
    exampleTranslationJa: "その古い手紙は屋根裏で見つかった。",
    collocations: ["in the attic", "an attic room", "clear out the attic"],
    mnemonic: "ギリシャのアッティカ地方の建築様式から。基本は物置。",
    relatedWords: ["loft", "roof", "basement"],
  },
  {
    id: "balcony",
    word: "balcony",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["バルコニー", "(劇場の)二階席"],
    pronunciation: "/ˈbælkəni/",
    exampleSentence: "The flat has a small balcony.",
    exampleTranslationJa: "その部屋には小さなバルコニーがある。",
    collocations: ["on the balcony", "a balcony seat"],
    mnemonic: "屋根がなく外に張り出した床。屋根つきで地上なら porch。",
    relatedWords: ["terrace", "veranda", "patio"],
  },
  {
    id: "porch",
    word: "porch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["玄関先の屋根つき部分、ポーチ"],
    pronunciation: "/pɔːrtʃ/",
    exampleSentence: "They sat on the porch until dark.",
    exampleTranslationJa: "彼らは暗くなるまでポーチに座っていた。",
    collocations: ["sit on the porch", "a front porch"],
    mnemonic: "玄関の外側で屋根のある部分。米の家では大きな居場所になる。",
    relatedWords: ["veranda", "entrance", "doorway"],
  },
  {
    id: "hallway",
    word: "hallway",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["玄関ホール、廊下"],
    pronunciation: "/ˈhɔːlweɪ/",
    exampleSentence: "Leave your boots in the hallway.",
    exampleTranslationJa: "長靴は玄関に置いておいて。",
    collocations: ["in the hallway", "a narrow hallway"],
    mnemonic: "家の中の通路。オフィスや学校の廊下は corridor。",
    relatedWords: ["corridor", "passage", "entrance"],
  },
  {
    id: "staircase",
    word: "staircase",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["階段(全体)"],
    pronunciation: "/ˈsterkeɪs/",
    exampleSentence: "A wooden staircase leads to the first floor.",
    exampleTranslationJa: "木の階段が2階に続いている。",
    collocations: ["a spiral staircase", "climb the staircase"],
    mnemonic: "stairs が段そのもの、staircase は手すりを含む構造全体。",
    relatedWords: ["stairs", "steps", "flight"],
  },
  {
    id: "floorboard",
    word: "floorboard",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["床板"],
    pronunciation: "/ˈflɔːrbɔːrd/",
    exampleSentence: "A loose floorboard creaked under his foot.",
    exampleTranslationJa: "ゆるんだ床板が彼の足の下できしんだ。",
    collocations: ["a loose floorboard", "bare floorboards"],
    mnemonic: "floor(床)+ board(板)。bare floorboards は「板張りのまま」。",
    relatedWords: ["floor", "plank", "timber"],
  },
  {
    id: "doorstep",
    word: "doorstep",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["玄関の上がり段", "すぐそば"],
    pronunciation: "/ˈdɔːrstep/",
    exampleSentence: "The parcel was left on the doorstep.",
    exampleTranslationJa: "小包は玄関先に置かれていた。",
    collocations: ["on the doorstep", "on your doorstep"],
    mnemonic: "on your doorstep は「すぐ目の前に」。宅配の定番の語。",
    relatedWords: ["threshold", "step", "entrance"],
  },
  {
    id: "doorway",
    word: "doorway",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["戸口、出入り口"],
    pronunciation: "/ˈdɔːrweɪ/",
    exampleSentence: "She stood in the doorway for a moment.",
    exampleTranslationJa: "彼女はしばらく戸口に立っていた。",
    collocations: ["stand in the doorway", "block the doorway"],
    mnemonic: "扉そのものではなく、扉のある「開口部」。",
    relatedWords: ["entrance", "threshold", "door"],
  },
  {
    id: "windowsill",
    word: "windowsill",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["窓台、窓の下枠"],
    pronunciation: "/ˈwɪndoʊsɪl/",
    exampleSentence: "Herbs grow on the kitchen windowsill.",
    exampleTranslationJa: "台所の窓台でハーブが育っている。",
    collocations: ["on the windowsill", "a wide windowsill"],
    mnemonic: "window(窓)+ sill(下枠)。鉢植えを置く定番の場所。",
    relatedWords: ["ledge", "window", "sill"],
  },
  {
    id: "shutter",
    word: "shutter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["よろい戸、シャッター", "(カメラの)シャッター"],
    pronunciation: "/ˈʃʌtər/",
    exampleSentence: "They closed the shutters against the heat.",
    exampleTranslationJa: "彼らは暑さをよけて雨戸を閉めた。",
    collocations: ["close the shutters", "a shutter speed", "roll down the shutter"],
    mnemonic: "窓の外側の板戸。カメラの機構も同じ語。",
    relatedWords: ["blind", "screen", "cover"],
  },
  {
    id: "chimney",
    word: "chimney",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["煙突"],
    pronunciation: "/ˈtʃɪmni/",
    exampleSentence: "Smoke rose from the chimney.",
    exampleTranslationJa: "煙突から煙が上がった。",
    collocations: ["a chimney sweep", "smoke from the chimney"],
    mnemonic: "a chimney sweep は「煙突掃除人」。smoke like a chimney は「ひどい愛煙家」。",
    relatedWords: ["flue", "smoke", "fireplace"],
  },
  {
    id: "fireplace",
    word: "fireplace",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["暖炉"],
    pronunciation: "/ˈfaɪərpleɪs/",
    exampleSentence: "A log fire burned in the fireplace.",
    exampleTranslationJa: "暖炉でまきの火が燃えていた。",
    collocations: ["an open fireplace", "light the fireplace"],
    mnemonic: "部屋の中の火をたく場所。煙を出す管が chimney。",
    relatedWords: ["hearth", "chimney", "stove"],
  },
  {
    id: "radiator",
    word: "radiator",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["暖房器、ラジエーター"],
    pronunciation: "/ˈreɪdieɪtər/",
    exampleSentence: "Dry your gloves on the radiator.",
    exampleTranslationJa: "手袋は暖房器の上で乾かして。",
    collocations: ["turn on the radiator", "a car radiator"],
    mnemonic: "radiate(放射する)+ -or。熱を放つもの。車の冷却器も同じ語。",
    relatedWords: ["heater", "heating", "radiate"],
  },
  {
    id: "boiler",
    word: "boiler",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ボイラー、給湯器"],
    pronunciation: "/ˈbɔɪlər/",
    exampleSentence: "The boiler broke down in midwinter.",
    exampleTranslationJa: "真冬に給湯器が壊れた。",
    collocations: ["a gas boiler", "the boiler broke down", "service the boiler"],
    mnemonic: "boil(沸かす)+ -er。英国の家では暖房と給湯を兼ねる。",
    relatedWords: ["heater", "furnace", "heating"],
  },
  {
    id: "thermostat",
    word: "thermostat",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["温度調節器、サーモスタット"],
    pronunciation: "/ˈθɜːrməstæt/",
    exampleSentence: "Turn the thermostat down at night.",
    exampleTranslationJa: "夜は温度設定を下げてください。",
    collocations: ["set the thermostat", "turn down the thermostat"],
    mnemonic: "thermo-(熱)+ -stat(一定に保つもの)。",
    relatedWords: ["temperature", "control", "heating"],
  },
  {
    id: "insulation",
    word: "insulation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["断熱、絶縁"],
    pronunciation: "/ˌɪnsəˈleɪʃn/",
    exampleSentence: "Better insulation would cut the heating bill.",
    exampleTranslationJa: "断熱をよくすれば暖房費が下がる。",
    collocations: ["loft insulation", "improve insulation", "sound insulation"],
    mnemonic: "insulate(隔てる)+ -ion。island(島)と同語根で「切り離す」。",
    relatedWords: ["insulate", "insulator", "heat"],
  },
  {
    id: "draught",
    word: "draught",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["すきま風", "(樽からの)生ビール"],
    pronunciation: "/dræft/",
    exampleSentence: "There is a draught coming under the door.",
    exampleTranslationJa: "戸の下からすきま風が入ってくる。",
    collocations: ["a cold draught", "draught beer", "block the draught"],
    mnemonic: "米つづりは draft。発音は /dræft/。生ビールは on draught。",
    relatedWords: ["breeze", "gust", "drift"],
  },
  {
    id: "damp",
    word: "damp",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["湿った", "湿気"],
    pronunciation: "/dæmp/",
    exampleSentence: "The walls are damp in winter.",
    exampleTranslationJa: "冬になると壁が湿る。",
    collocations: ["damp walls", "rising damp", "a damp cloth"],
    mnemonic: "wet より軽い「じっとり」。英の住宅では rising damp が問題語。",
    relatedWords: ["moist", "humid", "dry"],
  },
  {
    id: "mould",
    word: "mould",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["かび", "型"],
    pronunciation: "/moʊld/",
    exampleSentence: "Mould grew on the bathroom ceiling.",
    exampleTranslationJa: "浴室の天井にかびが生えた。",
    collocations: ["black mould", "a cake mould", "break the mould"],
    mnemonic: "米つづりは mold。break the mould は「型を破る」。",
    relatedWords: ["fungus", "damp", "cast"],
  },
  {
    id: "plumbing",
    word: "plumbing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["配管、水回り"],
    pronunciation: "/ˈplʌmɪŋ/",
    exampleSentence: "The plumbing in this house is ancient.",
    exampleTranslationJa: "この家の配管は古すぎる。",
    collocations: ["the plumbing", "indoor plumbing", "fix the plumbing"],
    mnemonic: "plumber(配管工)と同語根。b は読まない。",
    relatedWords: ["pipes", "plumber", "water"],
  },
  {
    id: "wiring",
    word: "wiring",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["配線"],
    pronunciation: "/ˈwaɪərɪŋ/",
    exampleSentence: "The wiring needs replacing.",
    exampleTranslationJa: "配線は取り替えが必要だ。",
    collocations: ["faulty wiring", "rewiring the house", "electrical wiring"],
    mnemonic: "wire(電線)+ -ing。faulty wiring(配線の不良)は火災原因の定番。",
    relatedWords: ["wire", "electrics", "cable"],
  },
  {
    id: "fuse",
    word: "fuse",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ヒューズ", "融合する"],
    pronunciation: "/fjuːz/",
    exampleSentence: "A fuse blew and the lights went out.",
    exampleTranslationJa: "ヒューズが飛んで明かりが消えた。",
    collocations: ["a fuse blows", "the fuse box", "fuse together"],
    mnemonic: "a fuse blows は「ヒューズが飛ぶ」。動詞では「溶け合う」。",
    relatedWords: ["circuit", "melt", "merge"],
  },
  {
    id: "gutter",
    word: "gutter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["雨どい、側溝"],
    pronunciation: "/ˈɡʌtər/",
    exampleSentence: "Leaves blocked the gutter.",
    exampleTranslationJa: "落ち葉が雨どいをふさいだ。",
    collocations: ["clear the gutters", "the gutter press"],
    mnemonic: "the gutter press は「低俗な新聞」。低い所を流れるもの。",
    relatedWords: ["drain", "channel", "ditch"],
  },
  {
    id: "patio",
    word: "patio",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["テラス、中庭"],
    pronunciation: "/ˈpætioʊ/",
    exampleSentence: "We eat on the patio in summer.",
    exampleTranslationJa: "夏はテラスで食事をする。",
    collocations: ["on the patio", "patio doors", "a paved patio"],
    mnemonic: "スペイン語から。地面に敷石を敷いた屋外の居場所。",
    relatedWords: ["terrace", "courtyard", "balcony"],
  },
  {
    id: "driveway",
    word: "driveway",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["私道、車の乗り入れ路"],
    pronunciation: "/ˈdraɪvweɪ/",
    exampleSentence: "There is space for two cars on the driveway.",
    exampleTranslationJa: "その私道には車2台分の空きがある。",
    collocations: ["park in the driveway", "a gravel driveway"],
    mnemonic: "道路から家や車庫までの敷地内の通路。",
    relatedWords: ["drive", "path", "garage"],
  },
  {
    id: "tenancy",
    word: "tenancy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["賃借、賃貸借契約期間"],
    pronunciation: "/ˈtenənsi/",
    exampleSentence: "The tenancy runs for twelve months.",
    exampleTranslationJa: "その賃貸契約は12か月間だ。",
    collocations: ["a tenancy agreement", "end a tenancy", "a joint tenancy"],
    mnemonic: "tenant(借り手)の名詞形。契約そのものは a tenancy agreement。",
    relatedWords: ["lease", "rent", "tenant"],
  },
  {
    id: "sublet",
    word: "sublet",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["又貸しする", "又貸し"],
    pronunciation: "/ˌsʌbˈlet/",
    exampleSentence: "You may not sublet without permission.",
    exampleTranslationJa: "許可なく又貸ししてはいけない。",
    collocations: ["sublet a flat", "sublet to a friend"],
    mnemonic: "sub-(下位の)+ let(貸す)。活用は sublet-sublet-sublet。",
    relatedWords: ["rent out", "lease", "tenant"],
  },
  {
    id: "eviction",
    word: "eviction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["立ち退かせること、明け渡し"],
    pronunciation: "/ɪˈvɪkʃn/",
    exampleSentence: "They face eviction at the end of the month.",
    exampleTranslationJa: "彼らは月末に立ち退きを迫られている。",
    collocations: ["face eviction", "an eviction notice"],
    mnemonic: "evict(立ち退かせる)の名詞形。法的な強制退去を指す。",
    relatedWords: ["evict", "removal", "tenancy"],
  },
  {
    id: "estate agent",
    word: "estate agent",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["不動産業者(英)"],
    pronunciation: "/ɪˈsteɪt eɪdʒənt/",
    exampleSentence: "The estate agent showed us three flats.",
    exampleTranslationJa: "不動産業者は3件の部屋を見せてくれた。",
    collocations: ["a local estate agent", "an estate agent's window"],
    mnemonic: "米では realtor / real estate agent。",
    relatedWords: ["realtor", "broker", "property"],
  },
  {
    id: "surveyor",
    word: "surveyor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["測量士、建物調査士"],
    pronunciation: "/sərˈveɪər/",
    exampleSentence: "A surveyor inspected the roof before the sale.",
    exampleTranslationJa: "売買の前に調査士が屋根を検査した。",
    collocations: ["a chartered surveyor", "hire a surveyor"],
    mnemonic: "survey(調べる)+ -or。英では住宅購入前の建物調査をする専門家。",
    relatedWords: ["survey", "inspector", "valuer"],
  },
  {
    id: "outskirts",
    word: "outskirts",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["郊外、はずれ"],
    pronunciation: "/ˈaʊtskɜːrts/",
    exampleSentence: "They live on the outskirts of the city.",
    exampleTranslationJa: "彼らは市のはずれに住んでいる。",
    collocations: ["on the outskirts of", "the northern outskirts"],
    mnemonic: "必ず複数形。on the outskirts of ... の形で使う。",
    relatedWords: ["suburbs", "edge", "fringe"],
  },
  {
    id: "borough",
    word: "borough",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["行政区"],
    pronunciation: "/ˈbɜːroʊ/",
    exampleSentence: "Each London borough sets its own rates.",
    exampleTranslationJa: "ロンドンの各区はそれぞれ税率を決める。",
    collocations: ["a London borough", "the borough council"],
    mnemonic: "gh は読まない /ˈbɜːroʊ/。ニューヨークやロンドンの「区」。",
    relatedWords: ["district", "council", "municipality"],
  },
  {
    id: "terrace",
    word: "terrace",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["テラスハウスの並び", "段々畑", "テラス"],
    pronunciation: "/ˈterəs/",
    exampleSentence: "They bought a house in a Victorian terrace.",
    exampleTranslationJa: "彼らはビクトリア朝の連棟住宅の一軒を買った。",
    collocations: ["a terraced house", "a row of terraces", "rice terraces"],
    mnemonic: "英では「連なった同型の家並み」。段々畑も terraces。",
    relatedWords: ["row", "patio", "tier"],
  },
  {
    id: "semi-detached",
    word: "semi-detached",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["二軒続きの(住宅)"],
    pronunciation: "/ˌsemi dɪˈtætʃt/",
    exampleSentence: "They live in a semi-detached house.",
    exampleTranslationJa: "彼らは二軒続きの家に住んでいる。",
    collocations: ["a semi-detached house", "semi-detached property"],
    mnemonic: "一方の壁だけ隣家と接する家。口語では a semi。",
    relatedWords: ["detached", "terraced", "house"],
  },
  {
    id: "bungalow",
    word: "bungalow",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["平屋建ての家"],
    pronunciation: "/ˈbʌŋɡəloʊ/",
    exampleSentence: "A bungalow suits them now they are older.",
    exampleTranslationJa: "年をとった今、平屋が彼らに合っている。",
    collocations: ["a modern bungalow", "live in a bungalow"],
    mnemonic: "ヒンディー語 bangla(ベンガル風の家)から。階段のない家。",
    relatedWords: ["house", "cottage", "flat"],
  },
  {
    id: "mansion",
    word: "mansion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大邸宅"],
    pronunciation: "/ˈmænʃn/",
    exampleSentence: "The mansion has forty rooms.",
    exampleTranslationJa: "その大邸宅には40の部屋がある。",
    collocations: ["a country mansion", "a grand mansion"],
    mnemonic: "日本語の「マンション」とは全く違い、豪邸のこと。集合住宅は flat / apartment。",
    relatedWords: ["manor", "estate", "palace"],
  },
  {
    id: "penthouse",
    word: "penthouse",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["最上階の高級住戸"],
    pronunciation: "/ˈpenthaʊs/",
    exampleSentence: "The penthouse has a view of the whole city.",
    exampleTranslationJa: "その最上階住戸からは街全体が見渡せる。",
    collocations: ["a penthouse suite", "a penthouse flat"],
    mnemonic: "もとは屋上の付属小屋。今は最上階の高級な部屋。",
    relatedWords: ["apartment", "suite", "flat"],
  },
  {
    id: "byline",
    word: "byline",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["署名記事の筆者名"],
    pronunciation: "/ˈbaɪlaɪn/",
    exampleSentence: "The article carried her byline.",
    exampleTranslationJa: "その記事には彼女の署名が入っていた。",
    collocations: ["carry a byline", "a byline in the paper"],
    mnemonic: "by(〜による)+ line(行)。記事の冒頭にある「文・◯◯」の行。",
    relatedWords: ["credit", "author", "article"],
  },
  {
    id: "scoop",
    word: "scoop",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["特ダネ", "すくう", "ひとすくい"],
    pronunciation: "/skuːp/",
    exampleSentence: "The paper got a scoop on the resignation.",
    exampleTranslationJa: "その新聞は辞任について特ダネをつかんだ。",
    collocations: ["get a scoop", "a scoop of ice cream", "scoop up"],
    mnemonic: "すくう道具から、他社を出し抜いた記事へ。",
    relatedWords: ["exclusive", "spoon", "story"],
  },
  {
    id: "tabloid",
    word: "tabloid",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["タブロイド紙、大衆紙"],
    pronunciation: "/ˈtæblɔɪd/",
    exampleSentence: "The story was splashed across the tabloids.",
    exampleTranslationJa: "その話は大衆紙で大きく報じられた。",
    collocations: ["the tabloid press", "a tabloid newspaper"],
    mnemonic: "もとは小型の紙面。今は「扇情的な大衆紙」の意味が強い。",
    relatedWords: ["broadsheet", "press", "newspaper"],
  },
  {
    id: "broadsheet",
    word: "broadsheet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["高級紙、大判の新聞"],
    pronunciation: "/ˈbrɔːdʃiːt/",
    exampleSentence: "The broadsheets covered it more soberly.",
    exampleTranslationJa: "高級紙のほうはより淡々と報じた。",
    collocations: ["a broadsheet newspaper", "the broadsheets"],
    mnemonic: "tabloid の対。大判で、まじめな報道をする新聞。",
    relatedWords: ["tabloid", "newspaper", "press"],
  },
  {
    id: "bulletin",
    word: "bulletin",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["短報、ニュース速報", "会報"],
    pronunciation: "/ˈbʊlətɪn/",
    exampleSentence: "A news bulletin interrupted the programme.",
    exampleTranslationJa: "ニュース速報が番組を中断した。",
    collocations: ["a news bulletin", "a weather bulletin", "an email bulletin"],
    mnemonic: "短くまとめた知らせ。定期の会報にも使う。",
    relatedWords: ["report", "newsletter", "update"],
  },
  {
    id: "presenter",
    word: "presenter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(番組の)司会者、発表者"],
    pronunciation: "/prɪˈzentər/",
    exampleSentence: "The presenter interviewed three guests.",
    exampleTranslationJa: "司会者は3人の客に話を聞いた。",
    collocations: ["a TV presenter", "a radio presenter"],
    mnemonic: "英では番組の司会者。米では host / anchor。",
    relatedWords: ["host", "anchor", "announcer"],
  },
  {
    id: "pundit",
    word: "pundit",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["評論家、解説者"],
    pronunciation: "/ˈpʌndɪt/",
    exampleSentence: "Pundits predicted a close result.",
    exampleTranslationJa: "評論家たちは接戦を予想した。",
    collocations: ["political pundits", "pundits predict"],
    mnemonic: "サンスクリット語 paṇḍita(学者)から。皮肉を込めて使うこともある。",
    relatedWords: ["commentator", "expert", "analyst"],
  },
  {
    id: "press release",
    word: "press release",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["報道発表資料"],
    pronunciation: "/pres rɪˈliːs/",
    exampleSentence: "The company issued a press release.",
    exampleTranslationJa: "その会社は報道発表資料を出した。",
    collocations: ["issue a press release", "a joint press release"],
    mnemonic: "報道機関向けに配る公式文書。issue / put out と組む。",
    relatedWords: ["announcement", "statement", "media"],
  },
  {
    id: "censorship",
    word: "censorship",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["検閲"],
    pronunciation: "/ˈsensərʃɪp/",
    exampleSentence: "The film was banned under wartime censorship.",
    exampleTranslationJa: "その映画は戦時の検閲で上映禁止になった。",
    collocations: ["state censorship", "impose censorship", "self-censorship"],
    mnemonic: "censor(検閲する)+ -ship。self-censorship(自主規制)も重要。",
    relatedWords: ["censor", "ban", "suppression"],
  },
  {
    id: "libel",
    word: "libel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["名誉毀損(文書による)"],
    pronunciation: "/ˈlaɪbl/",
    exampleSentence: "He sued the paper for libel.",
    exampleTranslationJa: "彼はその新聞を名誉毀損で訴えた。",
    collocations: ["sue for libel", "a libel case", "libel laws"],
    mnemonic: "書かれたものが libel、口頭は slander。英の報道では頻出。",
    relatedWords: ["slander", "defamation", "sue"],
  },
  {
    id: "slander",
    word: "slander",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["名誉毀損(口頭による)", "中傷する"],
    pronunciation: "/ˈslændər/",
    exampleSentence: "The claim amounted to slander.",
    exampleTranslationJa: "その主張は中傷にあたるものだった。",
    collocations: ["a slander case", "slander someone"],
    mnemonic: "話し言葉での中傷。書いたものは libel。合わせて defamation。",
    relatedWords: ["libel", "defamation", "smear"],
  },
  {
    id: "defamation",
    word: "defamation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["名誉毀損"],
    pronunciation: "/ˌdefəˈmeɪʃn/",
    exampleSentence: "She won a defamation case against the site.",
    exampleTranslationJa: "彼女はそのサイトに対する名誉毀損訴訟に勝った。",
    collocations: ["a defamation case", "defamation of character"],
    mnemonic: "libel と slander を合わせた総称。fame(名声)と同語根。",
    relatedWords: ["libel", "slander", "reputation"],
  },
  {
    id: "retraction",
    word: "retraction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["撤回、取り消し"],
    pronunciation: "/rɪˈtrækʃn/",
    exampleSentence: "The journal issued a retraction.",
    exampleTranslationJa: "その学術誌は撤回を公表した。",
    collocations: ["issue a retraction", "demand a retraction"],
    mnemonic: "retract(引っこめる)の名詞形。論文や報道の取り消しに使う。",
    relatedWords: ["withdrawal", "correction", "retract"],
  },
  {
    id: "disclaimer",
    word: "disclaimer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["免責事項、断り書き"],
    pronunciation: "/dɪsˈkleɪmər/",
    exampleSentence: "The site carries a legal disclaimer.",
    exampleTranslationJa: "そのサイトには法的な免責事項が載っている。",
    collocations: ["a legal disclaimer", "carry a disclaimer"],
    mnemonic: "disclaim(責任を否認する)+ -er。「これは保証しません」という断り。",
    relatedWords: ["waiver", "notice", "warning"],
  },
  {
    id: "ratings",
    word: "ratings",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["視聴率、評価"],
    pronunciation: "/ˈreɪtɪŋz/",
    exampleSentence: "The show's ratings fell in the second series.",
    exampleTranslationJa: "その番組の視聴率は第2期で落ちた。",
    collocations: ["high ratings", "ratings fell", "a ratings war"],
    mnemonic: "この意味では複数形。番組の視聴率にも、企業の格付けにも使う。",
    relatedWords: ["audience", "score", "rating"],
  },
  {
    id: "viewership",
    word: "viewership",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["視聴者数、視聴者層"],
    pronunciation: "/ˈvjuːərʃɪp/",
    exampleSentence: "The channel lost half its viewership.",
    exampleTranslationJa: "そのチャンネルは視聴者の半分を失った。",
    collocations: ["a large viewership", "viewership figures"],
    mnemonic: "viewer(視聴者)+ -ship(集合)。readership と同じ作り。",
    relatedWords: ["audience", "ratings", "readership"],
  },
  {
    id: "prime time",
    word: "prime time",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ゴールデンタイム、視聴率の高い時間帯"],
    pronunciation: "/praɪm taɪm/",
    exampleSentence: "The debate was shown in prime time.",
    exampleTranslationJa: "その討論はゴールデンタイムに放送された。",
    collocations: ["in prime time", "prime-time television"],
    mnemonic: "日本語の「ゴールデンタイム」は和製英語。英語では prime time。",
    relatedWords: ["peak time", "broadcast", "evening"],
  },
  {
    id: "livestream",
    word: "livestream",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["生配信", "生配信する"],
    pronunciation: "/ˈlaɪvstriːm/",
    exampleSentence: "They livestream every home match.",
    exampleTranslationJa: "彼らはホームの試合をすべて生配信する。",
    collocations: ["livestream an event", "watch the livestream"],
    mnemonic: "live(生の)+ stream(流す)。録画は on demand。",
    relatedWords: ["broadcast", "stream", "live"],
  },
  {
    id: "podcast",
    word: "podcast",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ポッドキャスト"],
    pronunciation: "/ˈpɑːdkæst/",
    exampleSentence: "She listens to a news podcast on the train.",
    exampleTranslationJa: "彼女は電車でニュースのポッドキャストを聴く。",
    collocations: ["a weekly podcast", "listen to a podcast", "host a podcast"],
    mnemonic: "iPod + broadcast のかばん語。今は機器と無関係に使う。",
    relatedWords: ["broadcast", "audio", "episode"],
  },
  {
    id: "blog",
    word: "blog",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ブログ", "ブログを書く"],
    pronunciation: "/blɑːɡ/",
    exampleSentence: "He blogs about food and travel.",
    exampleTranslationJa: "彼は食と旅についてブログを書いている。",
    collocations: ["write a blog", "a blog post", "blog about"],
    mnemonic: "web + log の短縮。人は blogger。",
    relatedWords: ["post", "website", "journal"],
  },
  {
    id: "influencer",
    word: "influencer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["インフルエンサー、影響力のある発信者"],
    pronunciation: "/ˈɪnfluənsər/",
    exampleSentence: "Brands pay influencers to promote products.",
    exampleTranslationJa: "ブランドは商品の宣伝にインフルエンサーへ報酬を払う。",
    collocations: ["a social media influencer", "work with influencers"],
    mnemonic: "influence(影響を与える)+ -er。SNS上で人を動かす発信者。",
    relatedWords: ["influence", "celebrity", "promoter"],
  },
  {
    id: "hashtag",
    word: "hashtag",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハッシュタグ"],
    pronunciation: "/ˈhæʃtæɡ/",
    exampleSentence: "The campaign spread through a single hashtag.",
    exampleTranslationJa: "その運動は一つのハッシュタグで広まった。",
    collocations: ["use a hashtag", "a trending hashtag"],
    mnemonic: "hash(#記号)+ tag(札)。#記号そのものは hash / pound sign。",
    relatedWords: ["tag", "trend", "social media"],
  },
  {
    id: "viral",
    word: "viral",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["急速に広まる、バズる", "ウイルスの"],
    pronunciation: "/ˈvaɪrəl/",
    exampleSentence: "The clip went viral overnight.",
    exampleTranslationJa: "その動画は一晩で急速に広まった。",
    collocations: ["go viral", "a viral video", "a viral infection"],
    mnemonic: "go viral(バズる)の形で覚える。ウイルスのように広がることから。",
    relatedWords: ["virus", "spread", "trending"],
  },
  {
    id: "trending",
    word: "trending",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["話題になっている、急上昇の"],
    pronunciation: "/ˈtrendɪŋ/",
    exampleSentence: "The topic was trending all afternoon.",
    exampleTranslationJa: "その話題は午後じゅう急上昇していた。",
    collocations: ["trending on social media", "a trending topic"],
    mnemonic: "trend(流行)の -ing 形。SNSの「トレンド入り」。",
    relatedWords: ["popular", "viral", "trend"],
  },
  {
    id: "moderation",
    word: "moderation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(投稿の)管理、節度"],
    pronunciation: "/ˌmɑːdəˈreɪʃn/",
    exampleSentence: "The site relies on volunteer moderation.",
    exampleTranslationJa: "そのサイトは有志による投稿管理に頼っている。",
    collocations: ["content moderation", "in moderation", "drink in moderation"],
    mnemonic: "in moderation は「ほどほどに」。ネットでは「投稿の監視・削除」。",
    relatedWords: ["moderate", "control", "restraint"],
  },
  {
    id: "troll",
    word: "troll",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["荒らし", "荒らす"],
    pronunciation: "/troʊl/",
    exampleSentence: "Do not feed the troll.",
    exampleTranslationJa: "荒らしは相手にしないこと。",
    collocations: ["an internet troll", "troll someone", "feed the trolls"],
    mnemonic: "北欧神話の妖怪から。わざと怒らせる書き込みをする人。",
    relatedWords: ["harass", "provoke", "abuse"],
  },
  {
    id: "clickbait",
    word: "clickbait",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["釣り見出し"],
    pronunciation: "/ˈklɪkbeɪt/",
    exampleSentence: "The headline was pure clickbait.",
    exampleTranslationJa: "その見出しは完全な釣りだった。",
    collocations: ["pure clickbait", "a clickbait headline"],
    mnemonic: "click(押す)+ bait(えさ)。中身の薄い記事に誘い込む見出し。",
    relatedWords: ["bait", "headline", "sensational"],
  },
  {
    id: "paywall",
    word: "paywall",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["有料の壁、課金の仕切り"],
    pronunciation: "/ˈpeɪwɔːl/",
    exampleSentence: "The article is behind a paywall.",
    exampleTranslationJa: "その記事は有料会員向けだ。",
    collocations: ["behind a paywall", "a soft paywall"],
    mnemonic: "behind a paywall(課金しないと読めない)の形で使う。",
    relatedWords: ["subscription", "barrier", "pay"],
  },
  {
    id: "misinformation",
    word: "misinformation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["誤情報"],
    pronunciation: "/ˌmɪsɪnfərˈmeɪʃn/",
    exampleSentence: "Misinformation spread faster than the correction.",
    exampleTranslationJa: "誤情報は訂正より速く広まった。",
    collocations: ["spread misinformation", "tackle misinformation"],
    mnemonic: "故意でなく広まる誤りが misinformation、故意なら disinformation。",
    relatedWords: ["disinformation", "falsehood", "error"],
  },
  {
    id: "disinformation",
    word: "disinformation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["偽情報(意図的なもの)"],
    pronunciation: "/ˌdɪsɪnfərˈmeɪʃn/",
    exampleSentence: "The report documents a disinformation campaign.",
    exampleTranslationJa: "その報告書は偽情報の流布工作を記録している。",
    collocations: ["a disinformation campaign", "state disinformation"],
    mnemonic: "dis- は「悪意をもって」。だますつもりで流す情報。",
    relatedWords: ["misinformation", "propaganda", "lie"],
  },
  {
    id: "fact-check",
    word: "fact-check",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["事実関係を検証する", "事実検証"],
    pronunciation: "/ˈfækt tʃek/",
    exampleSentence: "Reporters fact-check every claim.",
    exampleTranslationJa: "記者はすべての主張を事実確認する。",
    collocations: ["fact-check a claim", "a fact-check unit"],
    mnemonic: "報道の基本作業。人は fact-checker。",
    relatedWords: ["verify", "check", "verification"],
  },
  {
    id: "verification",
    word: "verification",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["検証、確認"],
    pronunciation: "/ˌverɪfɪˈkeɪʃn/",
    exampleSentence: "Verification of the data took two weeks.",
    exampleTranslationJa: "そのデータの検証には2週間かかった。",
    collocations: ["independent verification", "require verification"],
    mnemonic: "verify(確かめる)の名詞形。true(真)と同語根。",
    relatedWords: ["confirmation", "validation", "verify"],
  },
  {
    id: "framing",
    word: "framing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(問題の)提示のしかた、枠づけ"],
    pronunciation: "/ˈfreɪmɪŋ/",
    exampleSentence: "The framing of the question shapes the answer.",
    exampleTranslationJa: "問いの立て方が答えを左右する。",
    collocations: ["the framing of the debate", "careful framing"],
    mnemonic: "frame(枠)から。同じ事実でも「どう切り取るか」で印象が変わる。",
    relatedWords: ["presentation", "angle", "frame"],
  },
]
