import type { VocabularyEntry } from '../types'

// 増補 第13弾。論説・実務でよく出る形容詞。よく取り違える対(definitive と definite、
// eminent と imminent、discreet と discrete、invaluable と valueless)は覚えるヒントで区別する。
export const plus13: VocabularyEntry[] = [
  {
    id: "adept",
    word: "adept",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["熟達した、うまい"],
    pronunciation: "/əˈdept/",
    exampleSentence: "She is adept at handling difficult clients.",
    exampleTranslationJa: "彼女は難しい客の対応がうまい。",
    collocations: ["adept at", "adept in", "highly adept"],
    mnemonic: "adept at + -ing の形。skilled とほぼ同じで、少しかたい。",
    relatedWords: ["skilled", "proficient", "expert"],
  },
  {
    id: "akin",
    word: "akin",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(akin to で)〜に似ている"],
    pronunciation: "/əˈkɪn/",
    exampleSentence: "The feeling was akin to relief.",
    exampleTranslationJa: "その気持ちは安堵に近いものだった。",
    collocations: ["akin to", "something akin to"],
    wordFormation: "a-(〜へ)+ kin(血縁)。",
    mnemonic: "kin(親族)が語根。「血の近さ」から「似ている」へ。akin to の形だけで使う。",
    relatedWords: ["similar", "related", "kin"],
  },
  {
    id: "aloof",
    word: "aloof",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よそよそしい、距離を置いた"],
    pronunciation: "/əˈluːf/",
    exampleSentence: "He remained aloof from office politics.",
    exampleTranslationJa: "彼は社内政治から距離を置いていた。",
    collocations: ["remain aloof", "aloof from", "seem aloof"],
    mnemonic: "冷たいというより「関わらない」。remain aloof from ... の形。",
    relatedWords: ["distant", "detached", "reserved"],
  },
  {
    id: "ambivalent",
    word: "ambivalent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["相反する気持ちの、どっちつかずの"],
    pronunciation: "/æmˈbɪvələnt/",
    exampleSentence: "She feels ambivalent about moving abroad.",
    exampleTranslationJa: "彼女は海外に移ることに気持ちが揺れている。",
    collocations: ["ambivalent about", "deeply ambivalent"],
    wordFormation: "ambi-(両方)+ valere(力がある)。",
    mnemonic: "「両方に引っぱられる」。無関心(indifferent)ではなく、両方の気持ちがある。",
    relatedWords: ["conflicted", "uncertain", "indifferent"],
  },
  {
    id: "amiable",
    word: "amiable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感じのよい、人当たりのよい"],
    pronunciation: "/ˈeɪmiəbl/",
    exampleSentence: "He is an amiable man with time for everyone.",
    exampleTranslationJa: "彼は誰にでも時間を割く感じのよい人だ。",
    collocations: ["an amiable manner", "amiable and polite"],
    wordFormation: "ラテン語 amare(愛する)から。",
    mnemonic: "amateur・amorous と同語根。friendly のやや上品な語。",
    relatedWords: ["friendly", "genial", "pleasant"],
  },
  {
    id: "analogous",
    word: "analogous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["類似した、似通った"],
    pronunciation: "/əˈnæləɡəs/",
    exampleSentence: "The situation is analogous to the 2008 crisis.",
    exampleTranslationJa: "その状況は2008年の危機に似ている。",
    collocations: ["analogous to", "broadly analogous"],
    wordFormation: "analogy(類推)+ -ous。",
    mnemonic: "g は /ɡ/。analogous to ... の形。名詞は analogy。",
    relatedWords: ["similar", "comparable", "analogy"],
  },
  {
    id: "apt",
    word: "apt",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["適切な", "(be apt to で)〜しがちだ"],
    pronunciation: "/æpt/",
    exampleSentence: "That is an apt description of the problem.",
    exampleTranslationJa: "それはその問題の的確な言い表し方だ。",
    collocations: ["an apt description", "be apt to do", "apt to forget"],
    mnemonic: "「ぴたりと合う」が芯。be apt to do は「〜する傾向がある」。",
    relatedWords: ["suitable", "fitting", "liable"],
  },
  {
    id: "astute",
    word: "astute",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["抜け目のない、鋭い"],
    pronunciation: "/əˈstuːt/",
    exampleSentence: "It was an astute political move.",
    exampleTranslationJa: "それは抜け目のない政治的一手だった。",
    collocations: ["an astute observation", "a politically astute"],
    mnemonic: "shrewd とほぼ同じ。ほめ言葉として使われる。",
    relatedWords: ["shrewd", "perceptive", "clever"],
  },
  {
    id: "audible",
    word: "audible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["聞こえる、聞き取れる"],
    pronunciation: "/ˈɔːdəbl/",
    exampleSentence: "Her voice was barely audible.",
    exampleTranslationJa: "彼女の声はかろうじて聞き取れる程度だった。",
    collocations: ["barely audible", "clearly audible", "an audible sigh"],
    wordFormation: "audire(聞く)+ -ible。",
    mnemonic: "audio と同語根。反対は inaudible。visible(見える)と同じ作り。",
    relatedWords: ["inaudible", "hearable", "sound"],
  },
  {
    id: "autonomous",
    word: "autonomous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自律した、自治の"],
    pronunciation: "/ɔːˈtɑːnəməs/",
    exampleSentence: "The region became autonomous in 1998.",
    exampleTranslationJa: "その地域は1998年に自治権を得た。",
    collocations: ["an autonomous region", "autonomous vehicles"],
    wordFormation: "auto-(自ら)+ nomos(法)。",
    mnemonic: "「自分で法を持つ」。自動運転車は autonomous vehicles。",
    relatedWords: ["independent", "self-governing", "autonomy"],
  },
  {
    id: "barren",
    word: "barren",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不毛の、実りのない"],
    pronunciation: "/ˈbærən/",
    exampleSentence: "Nothing grows on the barren hillside.",
    exampleTranslationJa: "その不毛の斜面には何も育たない。",
    collocations: ["barren land", "a barren landscape", "barren of ideas"],
    mnemonic: "土地にも、成果のない議論にも使う。fertile の反対。",
    relatedWords: ["infertile", "bleak", "fertile"],
  },
  {
    id: "benign",
    word: "benign",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(腫瘍が)良性の", "穏やかな、害のない"],
    pronunciation: "/bɪˈnaɪn/",
    exampleSentence: "The lump turned out to be benign.",
    exampleTranslationJa: "そのしこりは良性だった。",
    collocations: ["a benign tumour", "a benign smile", "benign neglect"],
    wordFormation: "bene-(よい)+ -gn(生まれ)。",
    mnemonic: "g は読まない /bɪˈnaɪn/。医学では malignant(悪性)の反対。",
    relatedWords: ["harmless", "kindly", "malignant"],
  },
  {
    id: "bleak",
    word: "bleak",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["荒涼とした", "見通しが暗い"],
    pronunciation: "/bliːk/",
    exampleSentence: "The outlook for jobs is bleak.",
    exampleTranslationJa: "雇用の見通しは暗い。",
    collocations: ["a bleak outlook", "a bleak landscape", "bleak prospects"],
    mnemonic: "風景の寒々しさと、将来の暗さの両方。gloomy に近い。",
    relatedWords: ["grim", "desolate", "gloomy"],
  },
  {
    id: "blatant",
    word: "blatant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["露骨な、あからさまな"],
    pronunciation: "/ˈbleɪtnt/",
    exampleSentence: "It was a blatant breach of the rules.",
    exampleTranslationJa: "それは露骨な規則違反だった。",
    collocations: ["a blatant lie", "a blatant breach", "blatant disregard"],
    mnemonic: "隠そうともしない悪さ。obvious と違い、必ず非難の色がつく。",
    relatedWords: ["obvious", "flagrant", "subtle"],
  },
  {
    id: "candid",
    word: "candid",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["率直な、包み隠さない"],
    pronunciation: "/ˈkændɪd/",
    exampleSentence: "She gave a candid account of the failure.",
    exampleTranslationJa: "彼女はその失敗を包み隠さず語った。",
    collocations: ["a candid interview", "to be candid", "a candid photograph"],
    wordFormation: "ラテン語 candidus(白い)から。candidate と同語根。",
    mnemonic: "「白い＝混じり気がない」が語源。写真では「自然な、隠し撮りの」。",
    relatedWords: ["frank", "honest", "open"],
  },
  {
    id: "coherent",
    word: "coherent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["筋の通った、一貫した"],
    pronunciation: "/koʊˈhɪrənt/",
    exampleSentence: "We need a coherent strategy, not a list of wishes.",
    exampleTranslationJa: "願望の一覧ではなく、筋の通った戦略が要る。",
    collocations: ["a coherent argument", "a coherent strategy", "barely coherent"],
    wordFormation: "co-(共に)+ haerere(くっつく)。",
    mnemonic: "部分どうしがつながって筋が通っていること。反対は incoherent。",
    relatedWords: ["logical", "consistent", "cohesion"],
  },
  {
    id: "cohesive",
    word: "cohesive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["まとまりのある、結束した"],
    pronunciation: "/koʊˈhiːsɪv/",
    exampleSentence: "They built a cohesive team in six months.",
    exampleTranslationJa: "彼らは半年でまとまりのあるチームを作った。",
    collocations: ["a cohesive team", "socially cohesive"],
    wordFormation: "cohesion(結束)+ -ive。",
    mnemonic: "coherent が「論理のつながり」、cohesive は「人や部分のまとまり」。",
    relatedWords: ["united", "coherent", "cohesion"],
  },
  {
    id: "commonplace",
    word: "commonplace",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["ありふれた", "ありふれたこと"],
    pronunciation: "/ˈkɑːmənpleɪs/",
    exampleSentence: "Video calls are now commonplace.",
    exampleTranslationJa: "ビデオ通話は今やありふれている。",
    collocations: ["become commonplace", "a commonplace occurrence"],
    wordFormation: "common(ふつうの)+ place(所)。",
    mnemonic: "become commonplace(当たり前になる)の形が実用的。",
    relatedWords: ["ordinary", "usual", "rare"],
  },
  {
    id: "compatible",
    word: "compatible",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["両立できる、互換性のある"],
    pronunciation: "/kəmˈpætəbl/",
    exampleSentence: "The charger is compatible with most phones.",
    exampleTranslationJa: "その充電器はたいていの携帯に対応している。",
    collocations: ["compatible with", "fully compatible", "compatible systems"],
    wordFormation: "com-(共に)+ pati(耐える)。",
    mnemonic: "機器の互換性にも、人の相性にも使う。反対は incompatible。",
    relatedWords: ["consistent", "suited", "incompatible"],
  },
  {
    id: "complacent",
    word: "complacent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["現状に甘んじた、油断した"],
    pronunciation: "/kəmˈpleɪsnt/",
    exampleSentence: "We cannot afford to be complacent about safety.",
    exampleTranslationJa: "安全について油断してはいられない。",
    collocations: ["become complacent", "dangerously complacent"],
    mnemonic: "satisfied(満足した)と違い、必ず批判の含みがある。名詞は complacency。",
    relatedWords: ["smug", "satisfied", "vigilant"],
  },
  {
    id: "conceivable",
    word: "conceivable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["考えられる、ありうる"],
    pronunciation: "/kənˈsiːvəbl/",
    exampleSentence: "They tried every conceivable method.",
    exampleTranslationJa: "彼らは考えうるあらゆる方法を試した。",
    collocations: ["every conceivable", "it is conceivable that"],
    wordFormation: "conceive(思いつく)+ -able。",
    mnemonic: "every conceivable ... で「考えつく限りの」。反対は inconceivable。",
    relatedWords: ["possible", "imaginable", "inconceivable"],
  },
  {
    id: "concise",
    word: "concise",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["簡潔な"],
    pronunciation: "/kənˈsaɪs/",
    exampleSentence: "Keep your answer clear and concise.",
    exampleTranslationJa: "答えは明確かつ簡潔にしてください。",
    collocations: ["clear and concise", "a concise summary"],
    wordFormation: "con-(すっかり)+ caedere(切る)。",
    mnemonic: "「切りつめた」が語源。短いだけでなく「必要が全部入って短い」。",
    relatedWords: ["brief", "succinct", "brevity"],
  },
  {
    id: "concurrent",
    word: "concurrent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["同時に起こる、並行する"],
    pronunciation: "/kənˈkɜːrənt/",
    exampleSentence: "He is serving two concurrent sentences.",
    exampleTranslationJa: "彼は二つの刑を同時に服している。",
    collocations: ["concurrent sessions", "run concurrently"],
    wordFormation: "con-(共に)+ currere(走る)。",
    mnemonic: "「共に走る」。副詞 concurrently(同時並行で)のほうがよく使う。",
    relatedWords: ["simultaneous", "parallel", "consecutive"],
  },
  {
    id: "condescending",
    word: "condescending",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["見下すような、恩着せがましい"],
    pronunciation: "/ˌkɑːndɪˈsendɪŋ/",
    exampleSentence: "His tone was polite but condescending.",
    exampleTranslationJa: "彼の口調は丁寧だが見下すようだった。",
    collocations: ["a condescending tone", "sound condescending"],
    wordFormation: "con-(共に)+ descend(下りる)。",
    mnemonic: "「わざわざ下りてきてやる」感じ。patronising とほぼ同じ。",
    relatedWords: ["patronising", "superior", "humble"],
  },
  {
    id: "confidential",
    word: "confidential",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["秘密の、部外秘の"],
    pronunciation: "/ˌkɑːnfɪˈdenʃl/",
    exampleSentence: "This information is strictly confidential.",
    exampleTranslationJa: "この情報は厳重に部外秘だ。",
    collocations: ["strictly confidential", "keep it confidential", "confidential information"],
    wordFormation: "confide(打ち明ける)+ -ential。",
    mnemonic: "confide(信頼して打ち明ける)から。secret より事務的な語。",
    relatedWords: ["private", "secret", "confidentiality"],
  },
  {
    id: "conscientious",
    word: "conscientious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["まじめで念入りな、良心的な"],
    pronunciation: "/ˌkɑːnʃiˈenʃəs/",
    exampleSentence: "She is a conscientious worker who checks everything.",
    exampleTranslationJa: "彼女はすべてを確認する念入りな働き手だ。",
    collocations: ["a conscientious student", "a conscientious objector"],
    wordFormation: "conscience(良心)+ -ous。",
    mnemonic: "conscience(良心)が語根。a conscientious objector は「良心的兵役拒否者」。",
    relatedWords: ["careful", "diligent", "thorough"],
  },
  {
    id: "conspicuous",
    word: "conspicuous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["目立つ、人目を引く"],
    pronunciation: "/kənˈspɪkjuəs/",
    exampleSentence: "He felt conspicuous in his bright coat.",
    exampleTranslationJa: "彼は明るい色のコートで目立っている気がした。",
    collocations: ["conspicuous by his absence", "conspicuous consumption"],
    wordFormation: "con-(すっかり)+ specere(見る)。",
    mnemonic: "spectacle・inspect と同語根。conspicuous by your absence は「いないことが目立つ」。",
    relatedWords: ["noticeable", "prominent", "inconspicuous"],
  },
  {
    id: "contentious",
    word: "contentious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["議論を呼ぶ、異論の多い"],
    pronunciation: "/kənˈtenʃəs/",
    exampleSentence: "Immigration remains a contentious issue.",
    exampleTranslationJa: "移民は今も議論を呼ぶ問題だ。",
    collocations: ["a contentious issue", "highly contentious"],
    wordFormation: "contend(争う)+ -ious。",
    mnemonic: "contend(論争する)から。controversial とほぼ同じ。",
    relatedWords: ["controversial", "disputed", "contend"],
  },
  {
    id: "contradictory",
    word: "contradictory",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["矛盾した"],
    pronunciation: "/ˌkɑːntrəˈdɪktəri/",
    exampleSentence: "The two reports give contradictory accounts.",
    exampleTranslationJa: "その二つの報告は矛盾する説明をしている。",
    collocations: ["contradictory evidence", "seemingly contradictory"],
    wordFormation: "contradict(矛盾する)+ -ory。",
    mnemonic: "contra(反対)+ dict(言う)。両方は同時に成り立たない。",
    relatedWords: ["conflicting", "inconsistent", "contradict"],
  },
  {
    id: "courteous",
    word: "courteous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["礼儀正しい、丁重な"],
    pronunciation: "/ˈkɜːrtiəs/",
    exampleSentence: "The staff were courteous and efficient.",
    exampleTranslationJa: "職員は礼儀正しく手際がよかった。",
    collocations: ["courteous service", "polite and courteous"],
    wordFormation: "court(宮廷)+ -eous。",
    mnemonic: "宮廷(court)にふさわしい態度。polite よりあらたまった語。",
    relatedWords: ["polite", "civil", "respectful"],
  },
  {
    id: "cumulative",
    word: "cumulative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["累積の、積み重なる"],
    pronunciation: "/ˈkjuːmjələtɪv/",
    exampleSentence: "The cumulative effect of small savings is large.",
    exampleTranslationJa: "小さな節約の累積効果は大きい。",
    collocations: ["a cumulative effect", "cumulative total"],
    wordFormation: "cumulate(積み上げる)+ -ive。",
    mnemonic: "accumulate と同語根。一つずつは小さくても積み上がる。",
    relatedWords: ["accumulated", "total", "aggregate"],
  },
  {
    id: "deficient",
    word: "deficient",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不足している、欠けている"],
    pronunciation: "/dɪˈfɪʃnt/",
    exampleSentence: "The diet was deficient in iron.",
    exampleTranslationJa: "その食事は鉄分が不足していた。",
    collocations: ["deficient in", "nutritionally deficient"],
    wordFormation: "de-(下に)+ facere(作る)。",
    mnemonic: "deficient in ... の形。名詞は deficiency。",
    relatedWords: ["lacking", "inadequate", "deficiency"],
  },
  {
    id: "definitive",
    word: "definitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["決定的な、最終的な"],
    pronunciation: "/dɪˈfɪnətɪv/",
    exampleSentence: "This is the definitive study on the subject.",
    exampleTranslationJa: "これはその主題に関する決定版の研究だ。",
    collocations: ["a definitive answer", "the definitive edition", "definitive proof"],
    wordFormation: "define(定義する)+ -itive。",
    mnemonic: "definite(明確な)と混同注意。definitive は「これ以上のものはない」。",
    relatedWords: ["conclusive", "final", "definite"],
  },
  {
    id: "derogatory",
    word: "derogatory",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["軽蔑的な、けなす"],
    pronunciation: "/dɪˈrɑːɡətɔːri/",
    exampleSentence: "He was suspended for derogatory remarks.",
    exampleTranslationJa: "彼は侮辱的な発言で停職になった。",
    collocations: ["a derogatory remark", "derogatory language"],
    mnemonic: "人を低く扱う言い方。ニュースや懲戒の文脈で使う。",
    relatedWords: ["insulting", "disparaging", "offensive"],
  },
  {
    id: "desolate",
    word: "desolate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["荒れ果てた", "打ちひしがれた"],
    pronunciation: "/ˈdesələt/",
    exampleSentence: "They crossed a desolate stretch of moorland.",
    exampleTranslationJa: "彼らは荒涼とした荒れ野を横切った。",
    collocations: ["a desolate landscape", "feel desolate"],
    mnemonic: "人けがなく寂しい風景。人について言うと「打ちのめされた」。",
    relatedWords: ["bleak", "barren", "deserted"],
  },
  {
    id: "detrimental",
    word: "detrimental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有害な、不利な"],
    pronunciation: "/ˌdetrɪˈmentl/",
    exampleSentence: "Long hours are detrimental to health.",
    exampleTranslationJa: "長時間労働は健康に有害だ。",
    collocations: ["detrimental to", "have a detrimental effect"],
    wordFormation: "detriment(損害)+ -al。",
    mnemonic: "detrimental to ... の形。harmful のかたい語。",
    relatedWords: ["harmful", "damaging", "beneficial"],
  },
  {
    id: "devious",
    word: "devious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ずるい、遠回りな"],
    pronunciation: "/ˈdiːviəs/",
    exampleSentence: "He got the job by devious means.",
    exampleTranslationJa: "彼はずるい手を使ってその職を得た。",
    collocations: ["devious means", "a devious plan"],
    wordFormation: "de-(離れて)+ via(道)。",
    mnemonic: "「まっすぐな道から外れた」が原義。deviate と同語根。",
    relatedWords: ["cunning", "sly", "straightforward"],
  },
  {
    id: "devoid",
    word: "devoid",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(devoid of で)〜が全くない"],
    pronunciation: "/dɪˈvɔɪd/",
    exampleSentence: "The room was devoid of furniture.",
    exampleTranslationJa: "その部屋には家具が全くなかった。",
    collocations: ["devoid of", "completely devoid of"],
    wordFormation: "de-(すっかり)+ void(空)。",
    mnemonic: "void(空)が語根。devoid of ... の形だけで使う。",
    relatedWords: ["empty", "lacking", "void"],
  },
  {
    id: "discreet",
    word: "discreet",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["慎重な、口の堅い"],
    pronunciation: "/dɪˈskriːt/",
    exampleSentence: "Please be discreet about what you heard.",
    exampleTranslationJa: "聞いたことは口外しないでください。",
    collocations: ["be discreet", "a discreet enquiry", "discreet about"],
    mnemonic: "discrete(別々の)と同音・別語。こちらは「目立たず慎重な」。",
    relatedWords: ["tactful", "cautious", "discrete"],
  },
  {
    id: "disparate",
    word: "disparate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["まるで異なる、種類の違う"],
    pronunciation: "/ˈdɪspərət/",
    exampleSentence: "The group brings together disparate interests.",
    exampleTranslationJa: "その集団はまるで異なる利害を束ねている。",
    collocations: ["disparate groups", "disparate sources"],
    wordFormation: "dis-(離れて)+ par(等しい)。",
    mnemonic: "「等しくない」が語源。ただ違うのでなく「並べにくいほど違う」。",
    relatedWords: ["different", "diverse", "similar"],
  },
  {
    id: "dormant",
    word: "dormant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["休眠中の、活動していない"],
    pronunciation: "/ˈdɔːrmənt/",
    exampleSentence: "The volcano has been dormant for centuries.",
    exampleTranslationJa: "その火山は何世紀も休眠している。",
    collocations: ["a dormant volcano", "lie dormant", "a dormant account"],
    wordFormation: "ラテン語 dormire(眠る)から。dormitory と同語根。",
    mnemonic: "dormitory(寮)と同語根。「眠っている」が芯。",
    relatedWords: ["inactive", "sleeping", "active"],
  },
  {
    id: "drastic",
    word: "drastic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["思い切った、抜本的な"],
    pronunciation: "/ˈdræstɪk/",
    exampleSentence: "Drastic measures were needed.",
    exampleTranslationJa: "思い切った措置が必要だった。",
    collocations: ["drastic measures", "a drastic change", "drastic action"],
    mnemonic: "程度が大きく、しばしば急な変化。drastic measures が定型。",
    relatedWords: ["radical", "severe", "extreme"],
  },
  {
    id: "dubious",
    word: "dubious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["疑わしい", "半信半疑の"],
    pronunciation: "/ˈduːbiəs/",
    exampleSentence: "The claim rests on dubious evidence.",
    exampleTranslationJa: "その主張は疑わしい証拠に基づいている。",
    collocations: ["dubious evidence", "dubious about", "of dubious quality"],
    wordFormation: "doubt(疑い)と同語根。",
    mnemonic: "doubt と同語根。物が「怪しい」ことにも、人が「半信半疑」にも使う。",
    relatedWords: ["doubtful", "questionable", "doubt"],
  },
  {
    id: "eccentric",
    word: "eccentric",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["風変わりな"],
    pronunciation: "/ɪkˈsentrɪk/",
    exampleSentence: "Her eccentric habits amused the neighbours.",
    exampleTranslationJa: "彼女の風変わりな習慣は近所を面白がらせた。",
    collocations: ["an eccentric character", "slightly eccentric"],
    wordFormation: "ex-(外)+ centrum(中心)。",
    mnemonic: "「中心から外れた」が語源。悪意はなく、むしろ愛される変わり者。",
    relatedWords: ["odd", "unconventional", "quirky"],
  },
  {
    id: "elusive",
    word: "elusive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["とらえどころのない、なかなか手に入らない"],
    pronunciation: "/ɪˈluːsɪv/",
    exampleSentence: "A solution has proved elusive.",
    exampleTranslationJa: "解決策はなかなか見つからないままだ。",
    collocations: ["prove elusive", "an elusive goal", "an elusive answer"],
    wordFormation: "elude(逃れる)+ -ive。",
    mnemonic: "elude(するりと逃げる)から。追っても捕まえられないもの。",
    relatedWords: ["elude", "slippery", "obtainable"],
  },
  {
    id: "eminent",
    word: "eminent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["著名な、傑出した"],
    pronunciation: "/ˈemɪnənt/",
    exampleSentence: "An eminent historian opened the conference.",
    exampleTranslationJa: "著名な歴史学者が会議の口火を切った。",
    collocations: ["an eminent scholar", "eminently sensible"],
    wordFormation: "e-(外へ)+ minere(突き出る)。",
    mnemonic: "imminent(差し迫った)と混同注意。こちらは「抜きん出た」。",
    relatedWords: ["distinguished", "renowned", "imminent"],
  },
  {
    id: "erroneous",
    word: "erroneous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["誤った"],
    pronunciation: "/ɪˈroʊniəs/",
    exampleSentence: "The report was based on erroneous data.",
    exampleTranslationJa: "その報告は誤ったデータに基づいていた。",
    collocations: ["an erroneous assumption", "erroneous information"],
    wordFormation: "error(誤り)+ -eous。",
    mnemonic: "error の形容詞形。wrong のかたい書き言葉版。",
    relatedWords: ["incorrect", "mistaken", "error"],
  },
  {
    id: "exhaustive",
    word: "exhaustive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["徹底的な、網羅的な"],
    pronunciation: "/ɪɡˈzɔːstɪv/",
    exampleSentence: "They carried out an exhaustive search.",
    exampleTranslationJa: "彼らは徹底的な捜索を行った。",
    collocations: ["an exhaustive list", "an exhaustive search", "not exhaustive"],
    wordFormation: "exhaust(くみ尽くす)+ -ive。",
    mnemonic: "exhausted(疲れ果てた)と混同注意。こちらは「調べ尽くした」。",
    relatedWords: ["thorough", "comprehensive", "exhausted"],
  },
  {
    id: "feeble",
    word: "feeble",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["弱々しい", "(説明が)苦しい"],
    pronunciation: "/ˈfiːbl/",
    exampleSentence: "He gave a feeble excuse for being late.",
    exampleTranslationJa: "彼は遅刻について苦しい言い訳をした。",
    collocations: ["a feeble excuse", "a feeble attempt", "grow feeble"],
    mnemonic: "体力にも、言い訳や試みの弱さにも使う。",
    relatedWords: ["weak", "frail", "strong"],
  },
  {
    id: "fertile",
    word: "fertile",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["肥沃な、実り多い"],
    pronunciation: "/ˈfɜːrtl/",
    exampleSentence: "The valley has fertile soil.",
    exampleTranslationJa: "その谷は肥沃な土壌を持つ。",
    collocations: ["fertile soil", "fertile ground for", "a fertile imagination"],
    mnemonic: "fertile ground for ... は「〜が育ちやすい土壌」の比喩。",
    relatedWords: ["productive", "rich", "barren"],
  },
  {
    id: "finite",
    word: "finite",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有限の"],
    pronunciation: "/ˈfaɪnaɪt/",
    exampleSentence: "We have a finite amount of time.",
    exampleTranslationJa: "私たちが使える時間は有限だ。",
    collocations: ["finite resources", "a finite number", "finite and infinite"],
    wordFormation: "finis(終わり)+ -ite。",
    mnemonic: "fin(終わり)が語根。infinite(無限の)の反対。発音は /ˈfaɪnaɪt/。",
    relatedWords: ["limited", "infinite", "bounded"],
  },
  {
    id: "fluent",
    word: "fluent",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["流ちょうな、よどみない"],
    pronunciation: "/ˈfluːənt/",
    exampleSentence: "She is fluent in three languages.",
    exampleTranslationJa: "彼女は3か国語を流ちょうに話す。",
    collocations: ["fluent in", "fluent English", "become fluent"],
    wordFormation: "ラテン語 fluere(流れる)から。fluid と同語根。",
    mnemonic: "fluid(流れる)と同語根。fluent in + 言語 の形。",
    relatedWords: ["fluid", "smooth", "fluency"],
  },
  {
    id: "formidable",
    word: "formidable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["手ごわい、恐るべき"],
    pronunciation: "/ˈfɔːrmɪdəbl/",
    exampleSentence: "They face a formidable opponent.",
    exampleTranslationJa: "彼らは手ごわい相手と対戦する。",
    collocations: ["a formidable opponent", "a formidable task", "a formidable reputation"],
    wordFormation: "ラテン語 formidare(恐れる)から。",
    mnemonic: "恐れさせるほど強い、というほめ言葉にもなる。",
    relatedWords: ["daunting", "impressive", "tough"],
  },
  {
    id: "frantic",
    word: "frantic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["取り乱した、大慌ての"],
    pronunciation: "/ˈfræntɪk/",
    exampleSentence: "There was a frantic search for the missing child.",
    exampleTranslationJa: "行方不明の子を探して必死の捜索が行われた。",
    collocations: ["a frantic search", "frantic with worry", "a frantic pace"],
    mnemonic: "frenzy と同語根。落ち着きを失った急ぎ方。",
    relatedWords: ["hectic", "desperate", "calm"],
  },
  {
    id: "frugal",
    word: "frugal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["質素な、倹約する"],
    pronunciation: "/ˈfruːɡl/",
    exampleSentence: "They live a frugal life on one income.",
    exampleTranslationJa: "彼らは収入ひとつで質素に暮らしている。",
    collocations: ["a frugal lifestyle", "frugal with money"],
    mnemonic: "stingy(けち)と違い、frugal はほめ言葉になりうる。",
    relatedWords: ["thrifty", "economical", "extravagant"],
  },
  {
    id: "futile",
    word: "futile",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["むだな、効果のない"],
    pronunciation: "/ˈfjuːtl/",
    exampleSentence: "Further argument would be futile.",
    exampleTranslationJa: "これ以上議論してもむだだろう。",
    collocations: ["a futile attempt", "futile efforts", "prove futile"],
    mnemonic: "やっても実らないこと。名詞は futility。",
    relatedWords: ["pointless", "useless", "effective"],
  },
  {
    id: "glaring",
    word: "glaring",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["目に余る、明白な", "まぶしい"],
    pronunciation: "/ˈɡlerɪŋ/",
    exampleSentence: "There is a glaring error on page two.",
    exampleTranslationJa: "2ページ目に目に余る誤りがある。",
    collocations: ["a glaring error", "a glaring omission", "glaring sunlight"],
    wordFormation: "glare(ぎらつく)+ -ing。",
    mnemonic: "glare(ぎらつく)から。「目に飛び込んでくる」ほど明らかな欠点。",
    relatedWords: ["obvious", "blatant", "subtle"],
  },
  {
    id: "graceful",
    word: "graceful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["優雅な、上品な"],
    pronunciation: "/ˈɡreɪsfl/",
    exampleSentence: "She made a graceful exit from politics.",
    exampleTranslationJa: "彼女は政界から優雅に身を引いた。",
    collocations: ["a graceful movement", "a graceful exit"],
    wordFormation: "grace(優美)+ -ful。",
    mnemonic: "動きの美しさにも、身の引き方の見事さにも使う。",
    relatedWords: ["elegant", "smooth", "clumsy"],
  },
  {
    id: "grim",
    word: "grim",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["厳しい、暗い", "険しい表情の"],
    pronunciation: "/ɡrɪm/",
    exampleSentence: "The news from the hospital was grim.",
    exampleTranslationJa: "病院からの知らせは厳しいものだった。",
    collocations: ["a grim outlook", "grim news", "a grim expression"],
    mnemonic: "bleak に近いが、より重く不吉。grim determination は「固い決意」。",
    relatedWords: ["bleak", "harsh", "cheerful"],
  },
  {
    id: "hazardous",
    word: "hazardous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["危険な、有害な"],
    pronunciation: "/ˈhæzərdəs/",
    exampleSentence: "Hazardous waste must be stored separately.",
    exampleTranslationJa: "有害廃棄物は分けて保管しなければならない。",
    collocations: ["hazardous waste", "hazardous conditions", "potentially hazardous"],
    wordFormation: "hazard(危険)+ -ous。",
    mnemonic: "hazardous waste(有害廃棄物)が定型。dangerous より制度的な語。",
    relatedWords: ["dangerous", "risky", "safe"],
  },
  {
    id: "hectic",
    word: "hectic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["目が回るほど忙しい"],
    pronunciation: "/ˈhektɪk/",
    exampleSentence: "It has been a hectic week.",
    exampleTranslationJa: "目の回るような一週間だった。",
    collocations: ["a hectic schedule", "a hectic week", "hectic pace"],
    mnemonic: "忙しさに追われて落ち着かない感じ。busy より強い。",
    relatedWords: ["frantic", "busy", "calm"],
  },
  {
    id: "ignorant",
    word: "ignorant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["知らない、無知な"],
    pronunciation: "/ˈɪɡnərənt/",
    exampleSentence: "I was ignorant of the rule until today.",
    exampleTranslationJa: "私は今日までその規則を知らなかった。",
    collocations: ["ignorant of", "wilfully ignorant", "politically ignorant"],
    wordFormation: "ignore(無視する)と同語根。",
    mnemonic: "be ignorant of ... の形。stupid とは違い「知識がない」だけ。",
    relatedWords: ["unaware", "uninformed", "ignorance"],
  },
  {
    id: "immaculate",
    word: "immaculate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["非の打ちどころのない、真っさらな"],
    pronunciation: "/ɪˈmækjələt/",
    exampleSentence: "The kitchen was immaculate.",
    exampleTranslationJa: "その台所はちりひとつなかった。",
    collocations: ["in immaculate condition", "an immaculate record"],
    wordFormation: "im-(否定)+ macula(しみ)。",
    mnemonic: "「しみ一つない」が語源。清潔さにも記録の完璧さにも使う。",
    relatedWords: ["spotless", "perfect", "flawed"],
  },
  {
    id: "impartial",
    word: "impartial",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["公平な、偏らない"],
    pronunciation: "/ɪmˈpɑːrʃl/",
    exampleSentence: "A judge must remain impartial.",
    exampleTranslationJa: "裁判官は公平でなければならない。",
    collocations: ["an impartial observer", "remain impartial", "impartial advice"],
    wordFormation: "im-(否定)+ partial(えこひいきの)。",
    mnemonic: "partial(一方に加担する)の否定。neutral に近い。",
    relatedWords: ["neutral", "fair", "biased"],
  },
  {
    id: "impeccable",
    word: "impeccable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["申し分のない、完璧な"],
    pronunciation: "/ɪmˈpekəbl/",
    exampleSentence: "Her English is impeccable.",
    exampleTranslationJa: "彼女の英語は申し分ない。",
    collocations: ["impeccable manners", "impeccable timing", "impeccable credentials"],
    wordFormation: "im-(否定)+ peccare(罪を犯す)。",
    mnemonic: "「罪のない」が語源。マナーや技量をほめるときに使う。",
    relatedWords: ["flawless", "perfect", "faulty"],
  },
  {
    id: "imperative",
    word: "imperative",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["絶対に必要な", "必須のこと", "(文法の)命令法"],
    pronunciation: "/ɪmˈperətɪv/",
    exampleSentence: "It is imperative that we act now.",
    exampleTranslationJa: "今すぐ動くことが絶対に必要だ。",
    collocations: ["it is imperative that", "a moral imperative"],
    wordFormation: "imperare(命じる)から。emperor と同語根。",
    mnemonic: "It is imperative that + 動詞の原形。仮定法現在をとるのが特徴。",
    relatedWords: ["essential", "crucial", "urgent"],
  },
  {
    id: "implicit",
    word: "implicit",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["暗黙の、言外の", "絶対的な"],
    pronunciation: "/ɪmˈplɪsɪt/",
    exampleSentence: "There was an implicit threat in his tone.",
    exampleTranslationJa: "彼の口調には言外の脅しがあった。",
    collocations: ["implicit in", "an implicit assumption", "implicit trust"],
    wordFormation: "im-(中に)+ plicare(折る)。",
    mnemonic: "「折り込まれている」が語源。explicit(明示的な)の反対。",
    relatedWords: ["implied", "tacit", "explicit"],
  },
  {
    id: "incessant",
    word: "incessant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["絶え間ない"],
    pronunciation: "/ɪnˈsesnt/",
    exampleSentence: "The incessant noise made sleep impossible.",
    exampleTranslationJa: "絶え間ない騒音で眠れなかった。",
    collocations: ["incessant rain", "incessant noise", "incessant demands"],
    wordFormation: "in-(否定)+ cessare(やむ)。cease と同語根。",
    mnemonic: "cease(やむ)の否定。うんざりする響きがある。",
    relatedWords: ["constant", "continual", "cease"],
  },
  {
    id: "incidental",
    word: "incidental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["付随的な、主目的ではない"],
    pronunciation: "/ˌɪnsɪˈdentl/",
    exampleSentence: "Travel costs are incidental to the main budget.",
    exampleTranslationJa: "旅費は本予算に付随するものだ。",
    collocations: ["incidental expenses", "incidental to", "incidental music"],
    wordFormation: "incident(出来事)+ -al。",
    mnemonic: "主でなく、ついでに生じるもの。incidental expenses は「雑費」。",
    relatedWords: ["minor", "secondary", "essential"],
  },
  {
    id: "inclusive",
    word: "inclusive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すべてを含む", "誰も排除しない"],
    pronunciation: "/ɪnˈkluːsɪv/",
    exampleSentence: "The price is inclusive of breakfast.",
    exampleTranslationJa: "その料金は朝食込みです。",
    collocations: ["inclusive of", "an inclusive society", "all-inclusive"],
    wordFormation: "include(含む)+ -ive。",
    mnemonic: "料金の「込み」と、社会の「包摂的な」の両方で頻出。",
    relatedWords: ["comprehensive", "include", "exclusive"],
  },
  {
    id: "incompatible",
    word: "incompatible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["両立しない、互換性のない"],
    pronunciation: "/ˌɪnkəmˈpætəbl/",
    exampleSentence: "The two aims are incompatible.",
    exampleTranslationJa: "その二つの目標は両立しない。",
    collocations: ["incompatible with", "fundamentally incompatible"],
    wordFormation: "in-(否定)+ compatible。",
    mnemonic: "機器の非互換にも、価値観の相いれなさにも使う。",
    relatedWords: ["conflicting", "compatible", "clash"],
  },
  {
    id: "indispensable",
    word: "indispensable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["なくてはならない"],
    pronunciation: "/ˌɪndɪˈspensəbl/",
    exampleSentence: "She has made herself indispensable to the team.",
    exampleTranslationJa: "彼女はチームになくてはならない存在になった。",
    collocations: ["indispensable to", "an indispensable tool"],
    wordFormation: "in-(否定)+ dispensable(なくてもよい)。",
    mnemonic: "dispense with(なしですませる)の否定。essential より強い。",
    relatedWords: ["essential", "vital", "dispensable"],
  },
  {
    id: "inferior",
    word: "inferior",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["劣った、下位の"],
    pronunciation: "/ɪnˈfɪriər/",
    exampleSentence: "The copy is inferior to the original.",
    exampleTranslationJa: "その複製は原作に劣る。",
    collocations: ["inferior to", "inferior quality", "feel inferior"],
    wordFormation: "ラテン語 inferus(下の)の比較級。",
    mnemonic: "than ではなく to をとる(inferior to)。反対は superior。",
    relatedWords: ["worse", "lower", "superior"],
  },
  {
    id: "infinite",
    word: "infinite",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無限の"],
    pronunciation: "/ˈɪnfɪnət/",
    exampleSentence: "She showed infinite patience with the children.",
    exampleTranslationJa: "彼女は子どもたちに限りない忍耐を示した。",
    collocations: ["infinite patience", "an infinite number", "almost infinite"],
    wordFormation: "in-(否定)+ finite(有限の)。",
    mnemonic: "アクセントは前 /ˈɪnfɪnət/。finite とアクセントも音も違う。",
    relatedWords: ["endless", "limitless", "finite"],
  },
  {
    id: "innate",
    word: "innate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["生まれつきの"],
    pronunciation: "/ɪˈneɪt/",
    exampleSentence: "Children have an innate sense of fairness.",
    exampleTranslationJa: "子どもには生まれつき公平さの感覚がある。",
    collocations: ["an innate ability", "innate talent"],
    wordFormation: "in-(中に)+ natus(生まれた)。nature と同語根。",
    mnemonic: "nature・native と同語根。学んで身につけたものは acquired。",
    relatedWords: ["inborn", "natural", "acquired"],
  },
  {
    id: "intermittent",
    word: "intermittent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["断続的な"],
    pronunciation: "/ˌɪntərˈmɪtnt/",
    exampleSentence: "There will be intermittent rain all day.",
    exampleTranslationJa: "一日中、雨が降ったりやんだりするだろう。",
    collocations: ["intermittent rain", "intermittent faults", "intermittent fasting"],
    wordFormation: "inter-(間に)+ mittere(送る)。",
    mnemonic: "途切れては再開する。constant(絶え間ない)の反対。",
    relatedWords: ["occasional", "sporadic", "constant"],
  },
  {
    id: "intricate",
    word: "intricate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["入り組んだ、複雑で精巧な"],
    pronunciation: "/ˈɪntrɪkət/",
    exampleSentence: "The carving has an intricate pattern.",
    exampleTranslationJa: "その彫刻は入り組んだ文様をもつ。",
    collocations: ["an intricate pattern", "intricate detail", "intricate rules"],
    wordFormation: "in-(中に)+ tricae(もつれ)。",
    mnemonic: "複雑さの中に「作りの細かさ」への感嘆が入る。",
    relatedWords: ["complex", "elaborate", "simple"],
  },
  {
    id: "intrinsic",
    word: "intrinsic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["本来備わっている、本質的な"],
    pronunciation: "/ɪnˈtrɪnzɪk/",
    exampleSentence: "The painting has little intrinsic value.",
    exampleTranslationJa: "その絵にはそれ自体の価値はほとんどない。",
    collocations: ["intrinsic value", "intrinsic to", "intrinsic motivation"],
    mnemonic: "外から与えられるのが extrinsic、もともと備わるのが intrinsic。",
    relatedWords: ["inherent", "essential", "extrinsic"],
  },
  {
    id: "invaluable",
    word: "invaluable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["非常に貴重な"],
    pronunciation: "/ɪnˈvæljuəbl/",
    exampleSentence: "Your help has been invaluable.",
    exampleTranslationJa: "あなたの助けは非常に貴重でした。",
    collocations: ["invaluable help", "prove invaluable", "an invaluable resource"],
    wordFormation: "in-(否定)+ valuable。「値がつけられないほど」。",
    mnemonic: "「価値がない」ではない。値がつけられないほど貴重、という強調。",
    relatedWords: ["priceless", "precious", "worthless"],
  },
  {
    id: "irreversible",
    word: "irreversible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["元に戻せない、不可逆の"],
    pronunciation: "/ˌɪrɪˈvɜːrsəbl/",
    exampleSentence: "The damage may be irreversible.",
    exampleTranslationJa: "その損害は元に戻せないかもしれない。",
    collocations: ["irreversible damage", "an irreversible decision"],
    wordFormation: "ir-(否定)+ reversible(戻せる)。",
    mnemonic: "環境や健康の記事で頻出。reverse(戻す)の否定形。",
    relatedWords: ["permanent", "final", "reversible"],
  },
  {
    id: "lucrative",
    word: "lucrative",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["もうかる、実入りのよい"],
    pronunciation: "/ˈluːkrətɪv/",
    exampleSentence: "Consulting turned out to be lucrative work.",
    exampleTranslationJa: "コンサルティングは実入りのよい仕事だと分かった。",
    collocations: ["a lucrative contract", "highly lucrative", "a lucrative market"],
    wordFormation: "ラテン語 lucrum(利益)から。",
    mnemonic: "profitable とほぼ同じ。契約や市場について言うことが多い。",
    relatedWords: ["profitable", "well-paid", "unprofitable"],
  },
  {
    id: "lucid",
    word: "lucid",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["明快な", "意識がはっきりした"],
    pronunciation: "/ˈluːsɪd/",
    exampleSentence: "He gave a lucid explanation of the theory.",
    exampleTranslationJa: "彼はその理論を明快に説明した。",
    collocations: ["a lucid explanation", "a lucid moment", "lucid dreaming"],
    wordFormation: "ラテン語 lux(光)から。elucidate と同語根。",
    mnemonic: "lux(光)が語根。elucidate と親戚。病人が「意識がはっきりしている」意味も。",
    relatedWords: ["clear", "coherent", "confused"],
  },
  {
    id: "literal",
    word: "literal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["文字どおりの、逐語の"],
    pronunciation: "/ˈlɪtərəl/",
    exampleSentence: "That is the literal meaning, not what he meant.",
    exampleTranslationJa: "それは文字どおりの意味で、彼の言いたいことではない。",
    collocations: ["the literal meaning", "a literal translation", "in the literal sense"],
    wordFormation: "letter(文字)と同語根。",
    mnemonic: "figurative(比喩的な)の反対。副詞 literally は強調でも使われる。",
    relatedWords: ["exact", "word-for-word", "figurative"],
  },
  {
    id: "lukewarm",
    word: "lukewarm",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ぬるい", "気乗りしない"],
    pronunciation: "/ˌluːkˈwɔːrm/",
    exampleSentence: "The response was lukewarm at best.",
    exampleTranslationJa: "反応はよくてもぬるいものだった。",
    collocations: ["lukewarm water", "a lukewarm response", "lukewarm about"],
    mnemonic: "湯のぬるさから、反応の「熱のなさ」へ。批判的に使う。",
    relatedWords: ["tepid", "half-hearted", "enthusiastic"],
  },
  {
    id: "malicious",
    word: "malicious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["悪意のある"],
    pronunciation: "/məˈlɪʃəs/",
    exampleSentence: "The rumour was malicious and untrue.",
    exampleTranslationJa: "そのうわさは悪意があり事実でもなかった。",
    collocations: ["malicious gossip", "malicious damage", "malicious software"],
    wordFormation: "ラテン語 malus(悪い)から。",
    mnemonic: "mal(悪)が語根。malware・malignant と親戚。「わざと害を与える」。",
    relatedWords: ["spiteful", "vicious", "kind"],
  },
  {
    id: "manual",
    word: "manual",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["手作業の", "手引き書"],
    pronunciation: "/ˈmænjuəl/",
    exampleSentence: "Manual work is still needed at this stage.",
    exampleTranslationJa: "この段階ではまだ手作業が必要だ。",
    collocations: ["manual labour", "a user manual", "manual control"],
    wordFormation: "ラテン語 manus(手)から。",
    mnemonic: "manus(手)が語根。manuscript・manufacture と親戚。",
    relatedWords: ["hand", "handbook", "automatic"],
  },
  {
    id: "mediocre",
    word: "mediocre",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["平凡な、二流の"],
    pronunciation: "/ˌmiːdiˈoʊkər/",
    exampleSentence: "The food was expensive and mediocre.",
    exampleTranslationJa: "その料理は高いわりに平凡だった。",
    collocations: ["mediocre performance", "distinctly mediocre"],
    wordFormation: "medius(中間)+ ocris(山)。「山の中腹」。",
    mnemonic: "「山の中腹どまり」が語源。悪くはないが物足りない、という批判。",
    relatedWords: ["average", "ordinary", "excellent"],
  },
  {
    id: "merciless",
    word: "merciless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["容赦のない"],
    pronunciation: "/ˈmɜːrsɪləs/",
    exampleSentence: "The sun was merciless that afternoon.",
    exampleTranslationJa: "その午後の日差しは容赦がなかった。",
    collocations: ["merciless criticism", "a merciless attack"],
    wordFormation: "mercy(慈悲)+ -less。",
    mnemonic: "mercy(慈悲)が less(ない)。ruthless とほぼ同じ。",
    relatedWords: ["ruthless", "cruel", "merciful"],
  },
  {
    id: "methodical",
    word: "methodical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["きちんと手順を踏む、几帳面な"],
    pronunciation: "/məˈθɑːdɪkl/",
    exampleSentence: "She is methodical in everything she does.",
    exampleTranslationJa: "彼女は何をするにも手順をきちんと踏む。",
    collocations: ["a methodical approach", "methodical and patient"],
    wordFormation: "method(方法)+ -ical。",
    mnemonic: "順序立ててやること。meticulous は「細かさ」、methodical は「手順」。",
    relatedWords: ["systematic", "orderly", "haphazard"],
  },
  {
    id: "mundane",
    word: "mundane",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ありふれた、平凡な"],
    pronunciation: "/mʌnˈdeɪn/",
    exampleSentence: "Most of the job is fairly mundane.",
    exampleTranslationJa: "その仕事の大半はかなり平凡だ。",
    collocations: ["mundane tasks", "the mundane details", "seem mundane"],
    wordFormation: "ラテン語 mundus(世界)から。",
    mnemonic: "「この世の」が語源。俗っぽくて面白みがない、という含み。",
    relatedWords: ["ordinary", "routine", "exciting"],
  },
  {
    id: "negligible",
    word: "negligible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["取るに足らない、無視できるほど小さい"],
    pronunciation: "/ˈneɡlɪdʒəbl/",
    exampleSentence: "The difference is negligible.",
    exampleTranslationJa: "その差は無視できるほど小さい。",
    collocations: ["a negligible amount", "negligible impact", "virtually negligible"],
    wordFormation: "neglect(無視する)+ -ible。",
    mnemonic: "neglect(無視する)から。「無視してよいほど小さい」。",
    relatedWords: ["insignificant", "tiny", "significant"],
  },
  {
    id: "nominal",
    word: "nominal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["名目上の", "(金額が)ごくわずかな"],
    pronunciation: "/ˈnɑːmɪnl/",
    exampleSentence: "He is the nominal head of the company.",
    exampleTranslationJa: "彼はその会社の名目上の代表だ。",
    collocations: ["a nominal fee", "the nominal head", "nominal value"],
    wordFormation: "ラテン語 nomen(名)から。",
    mnemonic: "「名前だけ」が芯。a nominal fee は「ごくわずかな手数料」。",
    relatedWords: ["in name only", "token", "actual"],
  },
  {
    id: "noticeable",
    word: "noticeable",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["目につく、はっきり分かる"],
    pronunciation: "/ˈnoʊtɪsəbl/",
    exampleSentence: "There has been a noticeable improvement.",
    exampleTranslationJa: "はっきり分かる改善があった。",
    collocations: ["a noticeable difference", "barely noticeable"],
    wordFormation: "notice(気づく)+ -able。",
    mnemonic: "「気づける」。obvious ほど強くない。",
    relatedWords: ["visible", "obvious", "imperceptible"],
  },
  {
    id: "obscure",
    word: "obscure",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["よく知られていない、不明瞭な", "覆い隠す"],
    pronunciation: "/əbˈskjʊr/",
    exampleSentence: "He quoted an obscure nineteenth-century poet.",
    exampleTranslationJa: "彼はあまり知られていない19世紀の詩人を引用した。",
    collocations: ["an obscure reference", "obscure the view", "for obscure reasons"],
    mnemonic: "「暗い」が芯。無名なことにも、視界や意味を「ぼかす」ことにも使う。",
    relatedWords: ["unknown", "unclear", "obscurity"],
  },
  {
    id: "obsolete",
    word: "obsolete",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すたれた、時代遅れの"],
    pronunciation: "/ˌɑːbsəˈliːt/",
    exampleSentence: "The format became obsolete within a decade.",
    exampleTranslationJa: "その形式は10年でお払い箱になった。",
    collocations: ["become obsolete", "obsolete technology", "render obsolete"],
    mnemonic: "壊れたのではなく「新しいものに置き換えられた」。",
    relatedWords: ["outdated", "outmoded", "current"],
  },
  {
    id: "ominous",
    word: "ominous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不吉な"],
    pronunciation: "/ˈɑːmɪnəs/",
    exampleSentence: "There was an ominous silence on the line.",
    exampleTranslationJa: "電話口に不吉な沈黙があった。",
    collocations: ["an ominous sign", "ominous clouds", "sound ominous"],
    wordFormation: "omen(前兆)+ -ous。",
    mnemonic: "omen(前兆)から。omen は吉凶両方だが、ominous は悪いほうだけ。",
    relatedWords: ["threatening", "sinister", "omen"],
  },
  {
    id: "optimal",
    word: "optimal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["最適の"],
    pronunciation: "/ˈɑːptɪməl/",
    exampleSentence: "This is the optimal temperature for storage.",
    exampleTranslationJa: "これが保管に最適な温度だ。",
    collocations: ["optimal conditions", "the optimal solution"],
    wordFormation: "optimum(最適)+ -al。",
    mnemonic: "best が「一番よい」、optimal は「条件のもとで最も適した」。",
    relatedWords: ["ideal", "best", "optimum"],
  },
  {
    id: "overt",
    word: "overt",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["公然の、あからさまな"],
    pronunciation: "/oʊˈvɜːrt/",
    exampleSentence: "There was no overt sign of trouble.",
    exampleTranslationJa: "もめごとの公然のきざしはなかった。",
    collocations: ["overt hostility", "overt discrimination"],
    mnemonic: "covert(ひそかな)の反対。t を発音する /oʊˈvɜːrt/。",
    relatedWords: ["open", "obvious", "covert"],
  },
  {
    id: "painstaking",
    word: "painstaking",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["念入りな、骨の折れる"],
    pronunciation: "/ˈpeɪnzteɪkɪŋ/",
    exampleSentence: "The restoration was painstaking work.",
    exampleTranslationJa: "その修復は骨の折れる作業だった。",
    collocations: ["painstaking research", "painstaking detail", "painstaking care"],
    wordFormation: "pains(骨折り)+ taking(取ること)。",
    mnemonic: "take pains(骨を折る)が形容詞に。手間を惜しまない丁寧さ。",
    relatedWords: ["thorough", "meticulous", "careless"],
  },
  {
    id: "paramount",
    word: "paramount",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["最も重要な"],
    pronunciation: "/ˈpærəmaʊnt/",
    exampleSentence: "Safety is paramount on this site.",
    exampleTranslationJa: "この現場では安全が最優先だ。",
    collocations: ["of paramount importance", "safety is paramount"],
    mnemonic: "of paramount importance(最重要の)の形も頻出。",
    relatedWords: ["supreme", "chief", "minor"],
  },
  {
    id: "perpetual",
    word: "perpetual",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["絶え間ない、永続する"],
    pronunciation: "/pərˈpetʃuəl/",
    exampleSentence: "He lives in a perpetual state of worry.",
    exampleTranslationJa: "彼は絶えず心配している状態にある。",
    collocations: ["perpetual motion", "in perpetual fear"],
    mnemonic: "「終わりが来ない」。incessant より落ち着いた語。",
    relatedWords: ["constant", "eternal", "temporary"],
  },
  {
    id: "pertinent",
    word: "pertinent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["適切な、関連のある"],
    pronunciation: "/ˈpɜːrtnənt/",
    exampleSentence: "She asked a very pertinent question.",
    exampleTranslationJa: "彼女は非常に的を射た質問をした。",
    collocations: ["a pertinent question", "pertinent to", "highly pertinent"],
    wordFormation: "pertain(関係する)+ -ent。",
    mnemonic: "pertain to(関係する)の形容詞形。relevant とほぼ同じ。",
    relatedWords: ["relevant", "apt", "irrelevant"],
  },
  {
    id: "petty",
    word: "petty",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ささいな", "了見の狭い"],
    pronunciation: "/ˈpeti/",
    exampleSentence: "They argue over petty details.",
    exampleTranslationJa: "彼らはささいな点で言い争う。",
    collocations: ["petty crime", "petty cash", "petty jealousy"],
    wordFormation: "フランス語 petit(小さい)から。",
    mnemonic: "petty crime(軽犯罪)、petty cash(小口現金)。人について言うと「器が小さい」。",
    relatedWords: ["trivial", "minor", "significant"],
  },
  {
    id: "picturesque",
    word: "picturesque",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["絵のように美しい"],
    pronunciation: "/ˌpɪktʃəˈresk/",
    exampleSentence: "They stayed in a picturesque village.",
    exampleTranslationJa: "彼らは絵のように美しい村に滞在した。",
    collocations: ["a picturesque village", "picturesque scenery"],
    wordFormation: "picture(絵)+ -esque(〜風の)。",
    mnemonic: "-esque は「〜のような」。絵にしたくなる風景に使う。",
    relatedWords: ["scenic", "charming", "ugly"],
  },
  {
    id: "plausible",
    word: "plausible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["もっともらしい、ありそうな"],
    pronunciation: "/ˈplɔːzəbl/",
    exampleSentence: "That is a plausible explanation.",
    exampleTranslationJa: "それはもっともらしい説明だ。",
    collocations: ["a plausible explanation", "seem plausible", "perfectly plausible"],
    wordFormation: "ラテン語 plaudere(拍手する)から。applaud と同語根。",
    mnemonic: "「拍手できる」が語源。ありそうに聞こえるだけで、真実とは限らない。",
    relatedWords: ["believable", "credible", "implausible"],
  },
  {
    id: "potent",
    word: "potent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["効き目の強い、有力な"],
    pronunciation: "/ˈpoʊtnt/",
    exampleSentence: "This is a potent painkiller.",
    exampleTranslationJa: "これは効き目の強い鎮痛剤だ。",
    collocations: ["a potent weapon", "a potent symbol", "potent medicine"],
    wordFormation: "ラテン語 potens(力のある)から。power と同語根。",
    mnemonic: "power と同語根。薬にも象徴にも「効き目の強さ」を言う。",
    relatedWords: ["powerful", "strong", "weak"],
  },
  {
    id: "pragmatic",
    word: "pragmatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["現実的な、実利を重んじる"],
    pronunciation: "/præɡˈmætɪk/",
    exampleSentence: "They took a pragmatic approach to the problem.",
    exampleTranslationJa: "彼らはその問題に現実的な対処をした。",
    collocations: ["a pragmatic approach", "pragmatic and flexible"],
    wordFormation: "ギリシャ語 pragma(行い)から。practice と同語根。",
    mnemonic: "理想より「実際に何がうまくいくか」で判断する姿勢。",
    relatedWords: ["practical", "realistic", "idealistic"],
  },
  {
    id: "precarious",
    word: "precarious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不安定な、危なっかしい"],
    pronunciation: "/prɪˈkeriəs/",
    exampleSentence: "Many workers are in precarious employment.",
    exampleTranslationJa: "多くの労働者が不安定な雇用にある。",
    collocations: ["a precarious position", "precarious employment", "precariously balanced"],
    mnemonic: "いつ崩れてもおかしくない状態。雇用や財政の記事で頻出。",
    relatedWords: ["unstable", "insecure", "secure"],
  },
  {
    id: "prevalent",
    word: "prevalent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["広く行き渡った、よく見られる"],
    pronunciation: "/ˈprevələnt/",
    exampleSentence: "The practice is prevalent across the region.",
    exampleTranslationJa: "その慣行はその地域全体でよく見られる。",
    collocations: ["widely prevalent", "prevalent among", "become prevalent"],
    wordFormation: "pre-(前に)+ valere(力がある)。",
    mnemonic: "「勢力が強い」が語源。common よりかたく、統計的な語り口で使う。",
    relatedWords: ["widespread", "common", "rare"],
  },
  {
    id: "prone",
    word: "prone",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(prone to で)〜しがちな", "うつ伏せの"],
    pronunciation: "/proʊn/",
    exampleSentence: "This model is prone to overheating.",
    exampleTranslationJa: "この機種は過熱しやすい。",
    collocations: ["prone to", "accident-prone", "lie prone"],
    mnemonic: "be prone to + 名詞/-ing。よくないことに使う点が liable と共通。",
    relatedWords: ["liable", "susceptible", "resistant"],
  },
  {
    id: "prosperous",
    word: "prosperous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["繁栄している、裕福な"],
    pronunciation: "/ˈprɑːspərəs/",
    exampleSentence: "The town grew prosperous on the wool trade.",
    exampleTranslationJa: "その町は羊毛貿易で豊かになった。",
    collocations: ["a prosperous city", "become prosperous"],
    wordFormation: "prosper(栄える)+ -ous。",
    mnemonic: "名詞は prosperity。個人の裕福さにも、地域の繁栄にも使う。",
    relatedWords: ["wealthy", "thriving", "poor"],
  },
  {
    id: "provisional",
    word: "provisional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["暫定の、仮の"],
    pronunciation: "/prəˈvɪʒənl/",
    exampleSentence: "These are provisional figures only.",
    exampleTranslationJa: "これはあくまで暫定の数字です。",
    collocations: ["a provisional agreement", "provisional results", "a provisional licence"],
    wordFormation: "provide(備える)+ -ional。",
    mnemonic: "「とりあえず備えた」。あとで確定版が出ることが前提。",
    relatedWords: ["temporary", "interim", "final"],
  },
  {
    id: "rampant",
    word: "rampant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["はびこっている、猛威をふるう"],
    pronunciation: "/ˈræmpənt/",
    exampleSentence: "Corruption was rampant at the time.",
    exampleTranslationJa: "当時は汚職がはびこっていた。",
    collocations: ["rampant inflation", "run rampant", "rampant corruption"],
    mnemonic: "悪いものが抑えきかず広がる様子。run rampant の形も多い。",
    relatedWords: ["widespread", "unchecked", "controlled"],
  },
  {
    id: "redundant",
    word: "redundant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["余分な、不要な", "(英)解雇された"],
    pronunciation: "/rɪˈdʌndənt/",
    exampleSentence: "The last paragraph is redundant.",
    exampleTranslationJa: "最後の段落は不要だ。",
    collocations: ["be made redundant", "a redundant phrase", "redundant systems"],
    mnemonic: "英国では be made redundant で「人員整理で解雇される」。",
    relatedWords: ["unnecessary", "superfluous", "redundancy"],
  },
  {
    id: "relentless",
    word: "relentless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["容赦ない、絶え間ない"],
    pronunciation: "/rɪˈlentləs/",
    exampleSentence: "The pressure has been relentless.",
    exampleTranslationJa: "その圧力は絶え間なかった。",
    collocations: ["relentless pressure", "a relentless pace", "relentless criticism"],
    wordFormation: "relent(手を緩める)+ -less。",
    mnemonic: "relent(手を緩める)が less(ない)。ほめる文脈でも使える。",
    relatedWords: ["persistent", "unyielding", "merciful"],
  },
  {
    id: "repetitive",
    word: "repetitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["繰り返しの多い、単調な"],
    pronunciation: "/rɪˈpetətɪv/",
    exampleSentence: "The work is repetitive but well paid.",
    exampleTranslationJa: "その仕事は単調だが給料はよい。",
    collocations: ["repetitive work", "repetitive strain injury"],
    wordFormation: "repeat(繰り返す)+ -itive。",
    mnemonic: "repetitive strain injury(反復性ストレス障害)は労働衛生の用語。",
    relatedWords: ["monotonous", "routine", "varied"],
  },
  {
    id: "reputable",
    word: "reputable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["評判のよい、信頼できる"],
    pronunciation: "/ˈrepjətəbl/",
    exampleSentence: "Buy only from a reputable dealer.",
    exampleTranslationJa: "評判のよい業者からだけ買いなさい。",
    collocations: ["a reputable company", "a reputable source"],
    wordFormation: "repute(評判)+ -able。",
    mnemonic: "アクセントは前 /ˈrepjətəbl/。反対は disreputable。",
    relatedWords: ["respected", "trustworthy", "dubious"],
  },
  {
    id: "resilient",
    word: "resilient",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["立ち直りが早い、弾力のある"],
    pronunciation: "/rɪˈzɪliənt/",
    exampleSentence: "Children are remarkably resilient.",
    exampleTranslationJa: "子どもは驚くほど立ち直りが早い。",
    collocations: ["a resilient economy", "emotionally resilient", "a resilient material"],
    wordFormation: "re-(戻る)+ salire(跳ぶ)。",
    mnemonic: "「跳ね返る」が語源。心にも素材にも経済にも使う。名詞は resilience。",
    relatedWords: ["tough", "flexible", "fragile"],
  },
  {
    id: "rigorous",
    word: "rigorous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["厳密な、厳しい"],
    pronunciation: "/ˈrɪɡərəs/",
    exampleSentence: "The drug went through rigorous testing.",
    exampleTranslationJa: "その薬は厳密な試験を経た。",
    collocations: ["rigorous testing", "a rigorous standard", "rigorous analysis"],
    wordFormation: "rigour(厳密さ)+ -ous。",
    mnemonic: "手加減しない厳しさ。研究や検査についてよく使う。",
    relatedWords: ["strict", "thorough", "lax"],
  },
  {
    id: "scenic",
    word: "scenic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["景色のよい"],
    pronunciation: "/ˈsiːnɪk/",
    exampleSentence: "We took the scenic route home.",
    exampleTranslationJa: "私たちは景色のよい道を通って帰った。",
    collocations: ["a scenic route", "scenic beauty", "a scenic view"],
    wordFormation: "scene(景色)+ -ic。",
    mnemonic: "the scenic route は「遠回りだが景色のよい道」。",
    relatedWords: ["picturesque", "beautiful", "view"],
  },
  {
    id: "secluded",
    word: "secluded",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["人目につかない、ひっそりした"],
    pronunciation: "/sɪˈkluːdɪd/",
    exampleSentence: "They found a secluded spot by the river.",
    exampleTranslationJa: "彼らは川辺の人目につかない場所を見つけた。",
    collocations: ["a secluded beach", "a secluded garden"],
    wordFormation: "se-(離して)+ claudere(閉じる)。exclude と同語根。",
    mnemonic: "exclude・include と同語根。周りから切り離されて静か。",
    relatedWords: ["isolated", "private", "exposed"],
  },
  {
    id: "simultaneous",
    word: "simultaneous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["同時の"],
    pronunciation: "/ˌsaɪmlˈteɪniəs/",
    exampleSentence: "The two events were simultaneous.",
    exampleTranslationJa: "その二つの出来事は同時だった。",
    collocations: ["simultaneous translation", "a simultaneous release"],
    wordFormation: "ラテン語 simul(同時に)から。similar と同語根。",
    mnemonic: "simultaneous translation(同時通訳)で覚える。副詞は simultaneously。",
    relatedWords: ["concurrent", "at once", "consecutive"],
  },
  {
    id: "sleek",
    word: "sleek",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["つやのある、洗練された"],
    pronunciation: "/sliːk/",
    exampleSentence: "The car has a sleek modern design.",
    exampleTranslationJa: "その車はつややかで洗練された現代的な意匠だ。",
    collocations: ["a sleek design", "sleek hair", "sleek and modern"],
    mnemonic: "なめらかで無駄がなく、見た目が上等。製品の宣伝文句によく出る。",
    relatedWords: ["smooth", "polished", "rough"],
  },
]
