import type { VocabularyEntry } from '../types'

// 増補 第4弾。動物・植物・地形・天気。多読本文にそのまま出てくる自然の語をまとめて入れる。
export const plus04: VocabularyEntry[] = [
  {
    id: "mammal",
    word: "mammal",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ほ乳類"],
    pronunciation: "/ˈmæml/",
    exampleSentence: "Whales are mammals, not fish.",
    exampleTranslationJa: "クジラは魚ではなくほ乳類だ。",
    collocations: ["marine mammals", "a small mammal", "mammals and birds"],
    etymology: "ラテン語 mamma(乳房)から。乳で子を育てる動物。",
    mnemonic: "mamma(乳)が語根。乳で子を育てるのがほ乳類。",
    relatedWords: ["reptile", "animal", "milk"],
  },
  {
    id: "reptile",
    word: "reptile",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["は虫類"],
    pronunciation: "/ˈreptaɪl/",
    exampleSentence: "Snakes and lizards are reptiles.",
    exampleTranslationJa: "ヘビやトカゲはは虫類だ。",
    collocations: ["a cold-blooded reptile", "reptile skin"],
    etymology: "ラテン語 repere(はう)から。「はうもの」。",
    mnemonic: "repere(はう)が語根。地をはう冷血の動物。",
    relatedWords: ["mammal", "snake", "lizard"],
  },
  {
    id: "amphibian",
    word: "amphibian",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["両生類"],
    pronunciation: "/æmˈfɪbiən/",
    exampleSentence: "Frogs are amphibians that live both in water and on land.",
    exampleTranslationJa: "カエルは水中でも陸上でも生きる両生類だ。",
    collocations: ["amphibians and reptiles", "an aquatic amphibian"],
    wordFormation: "amphi-(両方)+ bios(生)。「二つの生を持つもの」。",
    mnemonic: "amphi(両方)+ bio(生)。水と陸の両方で生きる。",
    relatedWords: ["frog", "reptile", "water"],
  },
  {
    id: "rodent",
    word: "rodent",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["げっ歯類(ネズミ・リスなど)"],
    pronunciation: "/ˈroʊdnt/",
    exampleSentence: "Rats and squirrels are rodents.",
    exampleTranslationJa: "ネズミやリスはげっ歯類だ。",
    collocations: ["a small rodent", "rodent control"],
    etymology: "ラテン語 rodere(かじる)から。corrode(むしばむ)と同語根。",
    mnemonic: "rodere(かじる)が語根。前歯でかじり続ける動物のなかま。",
    relatedWords: ["mouse", "rat", "squirrel"],
  },
  {
    id: "snail",
    word: "snail",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カタツムリ"],
    pronunciation: "/sneɪl/",
    exampleSentence: "A snail crossed the wet path very slowly.",
    exampleTranslationJa: "カタツムリがぬれた小道をとてもゆっくり横切った。",
    collocations: ["at a snail's pace", "a garden snail"],
    mnemonic: "at a snail's pace は「かたつむりの速さで」＝「のろのろと」。",
    relatedWords: ["slug", "shell", "slow"],
  },
  {
    id: "slug",
    word: "slug",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ナメクジ"],
    pronunciation: "/slʌɡ/",
    exampleSentence: "Slugs had eaten most of the lettuce.",
    exampleTranslationJa: "ナメクジがレタスのほとんどを食べてしまっていた。",
    collocations: ["a garden slug", "slugs and snails"],
    mnemonic: "殻のないカタツムリ。sluggish(のろい)はここから。",
    relatedWords: ["snail", "sluggish", "garden"],
  },
  {
    id: "beetle",
    word: "beetle",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["甲虫(カブトムシ・テントウムシなど)"],
    pronunciation: "/ˈbiːtl/",
    exampleSentence: "A black beetle scurried under the log.",
    exampleTranslationJa: "黒い甲虫が丸太の下へ走り込んだ。",
    collocations: ["a stag beetle", "a dung beetle", "beetle larvae"],
    mnemonic: "かたい前ばねを持つ虫の総称。世界で最も種類の多い虫のなかま。",
    relatedWords: ["insect", "bug", "wing"],
  },
  {
    id: "ant",
    word: "ant",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["アリ"],
    pronunciation: "/ænt/",
    exampleSentence: "A line of ants marched across the kitchen floor.",
    exampleTranslationJa: "アリの行列が台所の床を横切って進んだ。",
    collocations: ["an ant colony", "a line of ants", "worker ants"],
    mnemonic: "叔母 aunt と同音になる方言もある。集団で暮らす代表的な昆虫。",
    relatedWords: ["insect", "colony", "bee"],
  },
  {
    id: "wasp",
    word: "wasp",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スズメバチ、ハチ(刺す種類)"],
    pronunciation: "/wɑːsp/",
    exampleSentence: "A wasp flew in through the open window.",
    exampleTranslationJa: "開いた窓からハチが飛び込んできた。",
    collocations: ["a wasp sting", "a wasp nest", "swat a wasp"],
    mnemonic: "蜜を作る bee と違い、wasp は刺すほう。腰が細くくびれている。",
    relatedWords: ["bee", "sting", "insect"],
  },
  {
    id: "moth",
    word: "moth",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ガ(蛾)"],
    pronunciation: "/mɔːθ/",
    exampleSentence: "A moth circled the lamp all evening.",
    exampleTranslationJa: "ガが一晩じゅうランプのまわりを回っていた。",
    collocations: ["a moth to a flame", "moth holes", "a clothes moth"],
    mnemonic: "like a moth to a flame は「引き寄せられて危険に近づく」。",
    relatedWords: ["butterfly", "insect", "wing"],
  },
  {
    id: "butterfly",
    word: "butterfly",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["チョウ(蝶)"],
    pronunciation: "/ˈbʌtərflaɪ/",
    exampleSentence: "A blue butterfly landed on the flower.",
    exampleTranslationJa: "青いチョウが花にとまった。",
    collocations: ["butterflies in your stomach", "a butterfly effect"],
    mnemonic: "have butterflies in your stomach は「緊張でそわそわする」。",
    relatedWords: ["moth", "caterpillar", "insect"],
  },
  {
    id: "mosquito",
    word: "mosquito",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["蚊"],
    pronunciation: "/məˈskiːtoʊ/",
    exampleSentence: "A mosquito bit me twice on the ankle.",
    exampleTranslationJa: "蚊が私の足首を2か所刺した。",
    collocations: ["a mosquito bite", "a mosquito net", "mosquito repellent"],
    etymology: "スペイン語 mosca(ハエ)の指小形。「小さいハエ」。",
    mnemonic: "スペイン語で「小さいハエ」。複数形は mosquitoes。",
    relatedWords: ["bite", "insect", "malaria"],
  },
  {
    id: "grasshopper",
    word: "grasshopper",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["バッタ、キリギリス"],
    pronunciation: "/ˈɡræshɑːpər/",
    exampleSentence: "A grasshopper jumped out of the long grass.",
    exampleTranslationJa: "バッタが丈の高い草から飛び出した。",
    collocations: ["a green grasshopper", "the ant and the grasshopper"],
    wordFormation: "grass(草)+ hopper(跳ぶもの)。",
    mnemonic: "草(grass)を跳ぶ(hop)もの。イソップの「アリとキリギリス」の相手役。",
    relatedWords: ["cricket", "insect", "jump"],
  },
  {
    id: "cricket",
    word: "cricket",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["コオロギ", "クリケット(競技)"],
    pronunciation: "/ˈkrɪkɪt/",
    exampleSentence: "You could hear crickets outside the tent.",
    exampleTranslationJa: "テントの外でコオロギの声が聞こえた。",
    collocations: ["a cricket chirping", "play cricket", "a cricket match"],
    mnemonic: "虫のコオロギと球技のクリケットが同じつづり。文脈で見分ける。",
    relatedWords: ["grasshopper", "insect", "sport"],
  },
  {
    id: "cockroach",
    word: "cockroach",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ゴキブリ"],
    pronunciation: "/ˈkɑːkroʊtʃ/",
    exampleSentence: "A cockroach ran under the fridge.",
    exampleTranslationJa: "ゴキブリが冷蔵庫の下に走り込んだ。",
    collocations: ["kill a cockroach", "a cockroach infestation"],
    mnemonic: "口語では roach と短くする。米国では roach のほうが普通。",
    relatedWords: ["insect", "pest", "kitchen"],
  },
  {
    id: "termite",
    word: "termite",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["シロアリ"],
    pronunciation: "/ˈtɜːrmaɪt/",
    exampleSentence: "Termites had eaten through the wooden beam.",
    exampleTranslationJa: "シロアリが木の梁を食い荒らしていた。",
    collocations: ["termite damage", "a termite nest"],
    mnemonic: "アリ(ant)ではなくゴキブリの近縁。木材を食べる害虫。",
    relatedWords: ["ant", "wood", "pest"],
  },
  {
    id: "caterpillar",
    word: "caterpillar",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["イモムシ、毛虫"],
    pronunciation: "/ˈkætərpɪlər/",
    exampleSentence: "The caterpillar ate its way through the leaf.",
    exampleTranslationJa: "イモムシは葉を食べながら進んだ。",
    collocations: ["a hairy caterpillar", "a caterpillar turns into a butterfly"],
    mnemonic: "チョウやガの幼虫。工事車両のキャタピラも同じ語で、はう動きから。",
    relatedWords: ["butterfly", "moth", "larva"],
  },
  {
    id: "sparrow",
    word: "sparrow",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["スズメ"],
    pronunciation: "/ˈspæroʊ/",
    exampleSentence: "A sparrow hopped along the windowsill.",
    exampleTranslationJa: "スズメが窓の桟をぴょんぴょん歩いた。",
    collocations: ["a house sparrow", "a flock of sparrows"],
    mnemonic: "町でいちばん見かける小さな茶色い鳥。",
    relatedWords: ["bird", "pigeon", "nest"],
  },
  {
    id: "pigeon",
    word: "pigeon",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハト"],
    pronunciation: "/ˈpɪdʒɪn/",
    exampleSentence: "Pigeons gathered around the old woman feeding them.",
    exampleTranslationJa: "餌をやる老女のまわりにハトが集まった。",
    collocations: ["feed the pigeons", "a carrier pigeon", "a pigeon coop"],
    mnemonic: "平和の象徴の白いハトは dove。街のハトは pigeon。",
    relatedWords: ["dove", "bird", "city"],
  },
  {
    id: "crow",
    word: "crow",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["カラス", "(鶏が)時をつくる", "得意げに言う"],
    pronunciation: "/kroʊ/",
    exampleSentence: "A crow perched on the telephone wire.",
    exampleTranslationJa: "カラスが電話線にとまった。",
    collocations: ["as the crow flies", "a crow cawing", "crow about"],
    mnemonic: "as the crow flies は「カラスが飛ぶように」＝「直線距離で」。",
    relatedWords: ["raven", "bird", "black"],
  },
  {
    id: "eagle",
    word: "eagle",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ワシ"],
    pronunciation: "/ˈiːɡl/",
    exampleSentence: "An eagle circled high above the valley.",
    exampleTranslationJa: "ワシが谷のはるか上空を旋回していた。",
    collocations: ["a bald eagle", "eagle-eyed", "a golden eagle"],
    mnemonic: "eagle-eyed は「目が鋭い、見逃さない」。米国の国鳥。",
    relatedWords: ["hawk", "bird", "prey"],
  },
  {
    id: "hawk",
    word: "hawk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["タカ", "(政治の)強硬派"],
    pronunciation: "/hɔːk/",
    exampleSentence: "A hawk hovered above the field, watching for mice.",
    exampleTranslationJa: "タカが野原の上に静止し、ネズミを狙っていた。",
    collocations: ["watch like a hawk", "hawks and doves"],
    mnemonic: "watch someone like a hawk で「じっと見張る」。政治では強硬派を hawk、穏健派を dove。",
    relatedWords: ["eagle", "dove", "prey"],
  },
  {
    id: "owl",
    word: "owl",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["フクロウ"],
    pronunciation: "/aʊl/",
    exampleSentence: "An owl hooted somewhere in the dark wood.",
    exampleTranslationJa: "暗い森のどこかでフクロウが鳴いた。",
    collocations: ["a night owl", "an owl hoots", "wise as an owl"],
    mnemonic: "a night owl は「夜型の人」。英語圏では知恵の象徴。",
    relatedWords: ["bird", "night", "hunt"],
  },
  {
    id: "swan",
    word: "swan",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ハクチョウ"],
    pronunciation: "/swɑːn/",
    exampleSentence: "Two swans glided across the still lake.",
    exampleTranslationJa: "2羽のハクチョウが静かな湖を滑るように進んだ。",
    collocations: ["a swan song", "a pair of swans", "a black swan"],
    mnemonic: "a swan song は「最後の作品・引退作」。死ぬ間際に歌うという伝説から。",
    relatedWords: ["duck", "goose", "bird"],
  },
  {
    id: "duck",
    word: "duck",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["カモ、アヒル", "さっと頭を下げる"],
    pronunciation: "/dʌk/",
    exampleSentence: "He ducked to avoid the low branch.",
    exampleTranslationJa: "彼は低い枝をよけようとさっと頭を下げた。",
    collocations: ["feed the ducks", "duck out of the way", "a sitting duck"],
    mnemonic: "水に頭をつっこむ動きから、動詞で「さっとかがむ」。a sitting duck は「格好の的」。",
    relatedWords: ["goose", "swan", "bird"],
  },
  {
    id: "goose",
    word: "goose",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ガチョウ、ガン"],
    pronunciation: "/ɡuːs/",
    exampleSentence: "A wild goose landed on the pond.",
    exampleTranslationJa: "野生のガンが池に降り立った。",
    collocations: ["a wild goose chase", "goose bumps", "a Christmas goose"],
    mnemonic: "複数形は geese。a wild goose chase は「むだ足」。",
    relatedWords: ["duck", "swan", "bird"],
  },
  {
    id: "chicken",
    word: "chicken",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["ニワトリ、鶏肉", "(口語)臆病な"],
    pronunciation: "/ˈtʃɪkɪn/",
    exampleSentence: "They keep six chickens in the back garden.",
    exampleTranslationJa: "彼らは裏庭でニワトリを6羽飼っている。",
    collocations: ["roast chicken", "chicken out", "count your chickens"],
    mnemonic: "chicken out は「怖じ気づいてやめる」。臆病者の代名詞。",
    relatedWords: ["rooster", "hen", "poultry"],
  },
  {
    id: "rooster",
    word: "rooster",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["おんどり"],
    pronunciation: "/ˈruːstər/",
    exampleSentence: "A rooster crowed before sunrise.",
    exampleTranslationJa: "日の出前におんどりが鳴いた。",
    collocations: ["a rooster crows", "a rooster in the yard"],
    mnemonic: "roost(とまり木で休む)+ -er。英国では cock とも言う。めんどりは hen。",
    relatedWords: ["chicken", "hen", "crow"],
  },
  {
    id: "turkey",
    word: "turkey",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["七面鳥"],
    pronunciation: "/ˈtɜːrki/",
    exampleSentence: "They roast a turkey every Christmas.",
    exampleTranslationJa: "彼らは毎年クリスマスに七面鳥を焼く。",
    collocations: ["roast turkey", "cold turkey", "talk turkey"],
    mnemonic: "go cold turkey は「(薬や習慣を)一気にやめる」。",
    relatedWords: ["chicken", "poultry", "Christmas"],
  },
  {
    id: "parrot",
    word: "parrot",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["オウム", "おうむ返しに言う"],
    pronunciation: "/ˈpærət/",
    exampleSentence: "The students just parroted what the teacher said.",
    exampleTranslationJa: "生徒たちは先生の言うことをおうむ返しにしただけだった。",
    collocations: ["a talking parrot", "parrot a phrase", "parrot fashion"],
    mnemonic: "動詞で「意味も分からず繰り返す」。learn parrot fashion は「丸暗記する」。",
    relatedWords: ["bird", "repeat", "mimic"],
  },
  {
    id: "penguin",
    word: "penguin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ペンギン"],
    pronunciation: "/ˈpeŋɡwɪn/",
    exampleSentence: "Penguins huddle together to keep warm.",
    exampleTranslationJa: "ペンギンは体を寄せ合って暖をとる。",
    collocations: ["a colony of penguins", "an emperor penguin"],
    mnemonic: "飛べないが泳ぎのうまい鳥。gu は /ɡw/ と読む。",
    relatedWords: ["bird", "Antarctic", "swim"],
  },
  {
    id: "toad",
    word: "toad",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヒキガエル"],
    pronunciation: "/toʊd/",
    exampleSentence: "A fat toad sat by the pond.",
    exampleTranslationJa: "太ったヒキガエルが池のそばに座っていた。",
    collocations: ["a common toad", "toads and frogs"],
    mnemonic: "frog より皮膚がざらつき、地上で暮らす。road と韻を踏む。",
    relatedWords: ["frog", "amphibian", "pond"],
  },
  {
    id: "lizard",
    word: "lizard",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["トカゲ"],
    pronunciation: "/ˈlɪzərd/",
    exampleSentence: "A lizard darted across the hot stone.",
    exampleTranslationJa: "トカゲが熱い石の上をさっと横切った。",
    collocations: ["a green lizard", "a lizard basking in the sun"],
    mnemonic: "日なたで体を温める冷血動物。しっぽを切って逃げる。",
    relatedWords: ["reptile", "snake", "tail"],
  },
  {
    id: "snake",
    word: "snake",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ヘビ", "(道が)くねくね続く"],
    pronunciation: "/sneɪk/",
    exampleSentence: "A snake slid silently into the grass.",
    exampleTranslationJa: "ヘビが音もなく草むらへ滑り込んだ。",
    collocations: ["a poisonous snake", "a snake bite", "the road snakes through"],
    mnemonic: "a snake in the grass は「信用できない人」。道がくねるのも動詞 snake。",
    relatedWords: ["reptile", "bite", "venom"],
  },
  {
    id: "turtle",
    word: "turtle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["カメ(主に海ガメ)"],
    pronunciation: "/ˈtɜːrtl/",
    exampleSentence: "A sea turtle laid her eggs on the beach.",
    exampleTranslationJa: "ウミガメが浜辺で卵を産んだ。",
    collocations: ["a sea turtle", "a turtle shell", "turn turtle"],
    mnemonic: "米では陸ガメも turtle。英では海が turtle、陸が tortoise。",
    relatedWords: ["tortoise", "shell", "reptile"],
  },
  {
    id: "tortoise",
    word: "tortoise",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["リクガメ"],
    pronunciation: "/ˈtɔːrtəs/",
    exampleSentence: "The tortoise beat the hare in the old story.",
    exampleTranslationJa: "あの古い話ではリクガメがウサギに勝った。",
    collocations: ["a giant tortoise", "the tortoise and the hare"],
    mnemonic: "つづりの oi は /ə/ と弱く読む /ˈtɔːrtəs/。イソップの「ウサギとカメ」のカメ。",
    relatedWords: ["turtle", "shell", "slow"],
  },
  {
    id: "crocodile",
    word: "crocodile",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ワニ"],
    pronunciation: "/ˈkrɑːkədaɪl/",
    exampleSentence: "A crocodile lay motionless at the water's edge.",
    exampleTranslationJa: "ワニが水ぎわで身動きせず横たわっていた。",
    collocations: ["crocodile tears", "a saltwater crocodile"],
    mnemonic: "crocodile tears は「うそ泣き」。獲物を食べながら涙を流すという言い伝えから。",
    relatedWords: ["alligator", "reptile", "river"],
  },
  {
    id: "alligator",
    word: "alligator",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アリゲーター(ワニの一種)"],
    pronunciation: "/ˈælɪɡeɪtər/",
    exampleSentence: "An alligator surfaced slowly in the swamp.",
    exampleTranslationJa: "アリゲーターが沼にゆっくり浮かび上がった。",
    collocations: ["an American alligator", "alligator skin"],
    etymology: "スペイン語 el lagarto(そのトカゲ)がなまった語。",
    mnemonic: "口を閉じると下の歯が隠れるのが alligator、見えるのが crocodile。",
    relatedWords: ["crocodile", "swamp", "reptile"],
  },
  {
    id: "wolf",
    word: "wolf",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["オオカミ"],
    pronunciation: "/wʊlf/",
    exampleSentence: "A lone wolf howled in the distance.",
    exampleTranslationJa: "遠くで一匹のオオカミが遠ぼえした。",
    collocations: ["a lone wolf", "a wolf in sheep's clothing", "cry wolf"],
    mnemonic: "複数形は wolves。cry wolf は「うそをついて助けを呼ぶ」。",
    relatedWords: ["dog", "howl", "pack"],
  },
  {
    id: "fox",
    word: "fox",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["キツネ", "ずる賢い人"],
    pronunciation: "/fɑːks/",
    exampleSentence: "A fox crossed the road just before dawn.",
    exampleTranslationJa: "夜明け前にキツネが道を横切った。",
    collocations: ["a red fox", "as sly as a fox", "a fox hole"],
    mnemonic: "英語でもずる賢さの象徴。形容詞 foxy は「ずる賢い」。",
    relatedWords: ["wolf", "sly", "cunning"],
  },
  {
    id: "deer",
    word: "deer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["シカ"],
    pronunciation: "/dɪr/",
    exampleSentence: "A deer froze in the headlights.",
    exampleTranslationJa: "シカがヘッドライトの中で凍りついた。",
    collocations: ["a herd of deer", "like a deer in the headlights"],
    mnemonic: "単数も複数も deer。dear(親愛な)と同音。",
    relatedWords: ["antler", "forest", "herd"],
  },
  {
    id: "rabbit",
    word: "rabbit",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ウサギ"],
    pronunciation: "/ˈræbɪt/",
    exampleSentence: "A rabbit disappeared into its burrow.",
    exampleTranslationJa: "ウサギが巣穴に消えた。",
    collocations: ["a wild rabbit", "breed like rabbits", "pull a rabbit out of a hat"],
    mnemonic: "野ウサギ(耳と脚が長い)は hare。飼える小型のほうが rabbit。",
    relatedWords: ["hare", "burrow", "carrot"],
  },
  {
    id: "squirrel",
    word: "squirrel",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["リス", "(squirrel away で)ためこむ"],
    pronunciation: "/ˈskwɜːrəl/",
    exampleSentence: "A squirrel buried a nut under the tree.",
    exampleTranslationJa: "リスが木の下に木の実を埋めた。",
    collocations: ["a grey squirrel", "squirrel away money"],
    mnemonic: "木の実をためる習性から、動詞 squirrel away で「こつこつためこむ」。",
    relatedWords: ["nut", "rodent", "tree"],
  },
  {
    id: "mouse",
    word: "mouse",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ネズミ(小型)", "(パソコンの)マウス"],
    pronunciation: "/maʊs/",
    exampleSentence: "A mouse ran along the skirting board.",
    exampleTranslationJa: "ネズミが幅木に沿って走った。",
    collocations: ["a computer mouse", "as quiet as a mouse", "catch a mouse"],
    mnemonic: "複数形は mice。パソコンの装置は mouses ではなく mice も mouses も使われる。",
    relatedWords: ["rat", "rodent", "trap"],
  },
  {
    id: "hedgehog",
    word: "hedgehog",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハリネズミ"],
    pronunciation: "/ˈhedʒhɑːɡ/",
    exampleSentence: "A hedgehog curled into a ball when we approached.",
    exampleTranslationJa: "近づくとハリネズミは丸くなった。",
    collocations: ["a curled-up hedgehog", "a hedgehog's spines"],
    wordFormation: "hedge(生け垣)+ hog(ブタ)。生け垣にすむブタ鼻の動物。",
    mnemonic: "hedge(生け垣)+ hog(ブタ)。鼻がブタに似ていて生け垣にすむから。",
    relatedWords: ["spine", "hedge", "curl"],
  },
  {
    id: "otter",
    word: "otter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["カワウソ"],
    pronunciation: "/ˈɑːtər/",
    exampleSentence: "An otter slipped into the river without a sound.",
    exampleTranslationJa: "カワウソが音もなく川に滑り込んだ。",
    collocations: ["a sea otter", "a river otter"],
    mnemonic: "water(水)と語源が同じ。水辺にすむ小さな肉食動物。",
    relatedWords: ["river", "seal", "swim"],
  },
  {
    id: "whale",
    word: "whale",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["クジラ"],
    pronunciation: "/weɪl/",
    exampleSentence: "A whale surfaced beside the boat.",
    exampleTranslationJa: "クジラが船の横に浮上した。",
    collocations: ["a blue whale", "whale watching", "have a whale of a time"],
    mnemonic: "have a whale of a time は「大いに楽しむ」。大きさが誇張の元。",
    relatedWords: ["dolphin", "mammal", "ocean"],
  },
  {
    id: "dolphin",
    word: "dolphin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["イルカ"],
    pronunciation: "/ˈdɑːlfɪn/",
    exampleSentence: "Dolphins followed the ship for an hour.",
    exampleTranslationJa: "イルカが1時間、船についてきた。",
    collocations: ["a school of dolphins", "a bottlenose dolphin"],
    mnemonic: "魚ではなくほ乳類。群れは a school of dolphins。",
    relatedWords: ["whale", "mammal", "ocean"],
  },
  {
    id: "shark",
    word: "shark",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["サメ", "(比喩)強欲な人"],
    pronunciation: "/ʃɑːrk/",
    exampleSentence: "A shark circled slowly beneath the boat.",
    exampleTranslationJa: "サメが船の下をゆっくり旋回した。",
    collocations: ["a great white shark", "a loan shark", "shark attack"],
    mnemonic: "a loan shark は「高利貸し」。食いつく強欲さの比喩。",
    relatedWords: ["fish", "ocean", "predator"],
  },
  {
    id: "bull",
    word: "bull",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["雄牛", "(相場の)強気筋"],
    pronunciation: "/bʊl/",
    exampleSentence: "The farmer kept the bull in a separate field.",
    exampleTranslationJa: "農家はその雄牛を別の牧草地に入れていた。",
    collocations: ["a bull market", "take the bull by the horns", "a raging bull"],
    mnemonic: "take the bull by the horns は「困難に正面から立ち向かう」。",
    relatedWords: ["cow", "cattle", "calf"],
  },
  {
    id: "calf",
    word: "calf",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["子牛", "ふくらはぎ"],
    pronunciation: "/kæf/",
    exampleSentence: "The cow licked her newborn calf.",
    exampleTranslationJa: "母牛は生まれたばかりの子牛をなめた。",
    collocations: ["a newborn calf", "calf muscles", "calf leather"],
    mnemonic: "l は読まない /kæf/。複数形は calves。ふくらはぎも同じ語。",
    relatedWords: ["cow", "bull", "cattle"],
  },
  {
    id: "goat",
    word: "goat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヤギ"],
    pronunciation: "/ɡoʊt/",
    exampleSentence: "The goat ate everything within reach.",
    exampleTranslationJa: "そのヤギは手の届くものを何でも食べた。",
    collocations: ["goat's cheese", "a mountain goat", "get someone's goat"],
    mnemonic: "get someone's goat は「いらいらさせる」。coat と韻を踏む。",
    relatedWords: ["sheep", "milk", "farm"],
  },
  {
    id: "donkey",
    word: "donkey",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ロバ"],
    pronunciation: "/ˈdɑːŋki/",
    exampleSentence: "A donkey carried the load up the narrow path.",
    exampleTranslationJa: "ロバが狭い道を荷を積んで登った。",
    collocations: ["donkey work", "for donkey's years", "ride a donkey"],
    mnemonic: "donkey work は「単調な重労働」。for donkey's years は「長年」。",
    relatedWords: ["horse", "mule", "carry"],
  },
  {
    id: "camel",
    word: "camel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ラクダ"],
    pronunciation: "/ˈkæml/",
    exampleSentence: "A camel can go for days without water.",
    exampleTranslationJa: "ラクダは何日も水なしで過ごせる。",
    collocations: ["ride a camel", "a camel's hump", "the straw that breaks the camel's back"],
    mnemonic: "the last straw that breaks the camel's back は「我慢の限界を超える最後のひと押し」。",
    relatedWords: ["desert", "hump", "caravan"],
  },
  {
    id: "elephant",
    word: "elephant",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ゾウ"],
    pronunciation: "/ˈelɪfənt/",
    exampleSentence: "An elephant never forgets, people say.",
    exampleTranslationJa: "ゾウは決して忘れない、と人は言う。",
    collocations: ["a herd of elephants", "the elephant in the room", "a white elephant"],
    mnemonic: "the elephant in the room は「誰もが気づいているのに口に出さない問題」。",
    relatedWords: ["tusk", "trunk", "herd"],
  },
  {
    id: "lion",
    word: "lion",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ライオン"],
    pronunciation: "/ˈlaɪən/",
    exampleSentence: "The lion rested in the shade all afternoon.",
    exampleTranslationJa: "ライオンは午後じゅう日陰で休んでいた。",
    collocations: ["a lion's share", "a pride of lions", "roar like a lion"],
    mnemonic: "the lion's share は「いちばん大きな取り分」。群れは a pride。",
    relatedWords: ["tiger", "roar", "mane"],
  },
  {
    id: "tiger",
    word: "tiger",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トラ"],
    pronunciation: "/ˈtaɪɡər/",
    exampleSentence: "A tiger moved silently through the tall grass.",
    exampleTranslationJa: "トラが丈の高い草の中を音もなく進んだ。",
    collocations: ["a Bengal tiger", "a paper tiger", "tiger stripes"],
    mnemonic: "a paper tiger は「見かけ倒しの強敵」。",
    relatedWords: ["lion", "stripe", "predator"],
  },
  {
    id: "ape",
    word: "ape",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["類人猿(ゴリラ・チンパンジーなど)", "まねる"],
    pronunciation: "/eɪp/",
    exampleSentence: "Great apes share most of our genes.",
    exampleTranslationJa: "大型類人猿は私たちの遺伝子の大半を共有している。",
    collocations: ["the great apes", "ape someone's style", "go ape"],
    mnemonic: "しっぽのないのが ape、あるのが monkey。動詞で「まねる」。",
    relatedWords: ["monkey", "gorilla", "primate"],
  },
  {
    id: "gorilla",
    word: "gorilla",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ゴリラ"],
    pronunciation: "/ɡəˈrɪlə/",
    exampleSentence: "A gorilla sat quietly, watching the visitors.",
    exampleTranslationJa: "ゴリラは静かに座って来園者を見ていた。",
    collocations: ["a mountain gorilla", "a silverback gorilla"],
    mnemonic: "guerrilla(ゲリラ)と発音がほぼ同じ。つづりで見分ける。",
    relatedWords: ["ape", "chimpanzee", "primate"],
  },
  {
    id: "giraffe",
    word: "giraffe",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["キリン"],
    pronunciation: "/dʒəˈræf/",
    exampleSentence: "A giraffe stretched up to reach the highest leaves.",
    exampleTranslationJa: "キリンが一番高い葉に届こうと首を伸ばした。",
    collocations: ["a tall giraffe", "a giraffe's neck"],
    mnemonic: "アクセントは後ろ /dʒəˈræf/。f が二つ。",
    relatedWords: ["neck", "zebra", "savanna"],
  },
  {
    id: "zebra",
    word: "zebra",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["シマウマ"],
    pronunciation: "/ˈziːbrə/",
    exampleSentence: "A herd of zebra grazed near the water hole.",
    exampleTranslationJa: "シマウマの群れが水場の近くで草を食べていた。",
    collocations: ["zebra stripes", "a zebra crossing"],
    mnemonic: "英国では横断歩道を a zebra crossing と言う。白黒のしま模様から。",
    relatedWords: ["stripe", "horse", "giraffe"],
  },
  {
    id: "hoof",
    word: "hoof",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ひづめ"],
    pronunciation: "/hʊf/",
    exampleSentence: "The horse had a stone stuck in its hoof.",
    exampleTranslationJa: "その馬はひづめに石がはさまっていた。",
    collocations: ["a horse's hoof", "hooves on cobblestones"],
    mnemonic: "複数形は hooves(または hoofs)。ウマ・ウシ・ヤギの足の先。",
    relatedWords: ["horse", "paw", "claw"],
  },
  {
    id: "paw",
    word: "paw",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(イヌ・ネコなどの)足、前足"],
    pronunciation: "/pɔː/",
    exampleSentence: "The dog put a muddy paw on my knee.",
    exampleTranslationJa: "犬が泥だらけの前足を私の膝にのせた。",
    collocations: ["a muddy paw", "paw prints", "give me your paw"],
    mnemonic: "肉球のある柔らかい足。ひづめは hoof、鋭いつめは claw。",
    relatedWords: ["claw", "hoof", "dog"],
  },
  {
    id: "claw",
    word: "claw",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["かぎづめ、はさみ", "つめでひっかく"],
    pronunciation: "/klɔː/",
    exampleSentence: "The cat clawed at the door until it opened.",
    exampleTranslationJa: "猫は戸が開くまでつめでひっかいた。",
    collocations: ["sharp claws", "a crab's claw", "claw your way back"],
    mnemonic: "claw your way to the top は「はい上がるように出世する」。",
    relatedWords: ["paw", "nail", "scratch"],
  },
  {
    id: "beak",
    word: "beak",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["くちばし"],
    pronunciation: "/biːk/",
    exampleSentence: "The bird carried a twig in its beak.",
    exampleTranslationJa: "その鳥は小枝をくちばしにくわえていた。",
    collocations: ["a sharp beak", "a curved beak", "in its beak"],
    mnemonic: "peak(頂上)と韻を踏む。鳥の口のかたい部分。",
    relatedWords: ["bird", "bill", "feather"],
  },
  {
    id: "tusk",
    word: "tusk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["きば(ゾウ・イノシシなどの長い牙)"],
    pronunciation: "/tʌsk/",
    exampleSentence: "Elephants are killed for their tusks.",
    exampleTranslationJa: "ゾウはきばのために殺されている。",
    collocations: ["ivory tusks", "an elephant's tusks"],
    mnemonic: "口の外に長く突き出た牙だけを tusk と言う。普通の牙は fang。",
    relatedWords: ["ivory", "elephant", "fang"],
  },
  {
    id: "fin",
    word: "fin",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ひれ"],
    pronunciation: "/fɪn/",
    exampleSentence: "A dark fin cut through the surface of the water.",
    exampleTranslationJa: "黒いひれが水面を切り裂いて進んだ。",
    collocations: ["a dorsal fin", "a shark's fin", "fins and tail"],
    mnemonic: "魚が向きを変えるための板。背びれは dorsal fin。",
    relatedWords: ["fish", "shark", "tail"],
  },
  {
    id: "burrow",
    word: "burrow",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["巣穴", "穴を掘る、もぐりこむ"],
    pronunciation: "/ˈbɜːroʊ/",
    exampleSentence: "The rabbit burrowed deeper into the soft earth.",
    exampleTranslationJa: "ウサギは柔らかい土をさらに深く掘り進んだ。",
    collocations: ["dig a burrow", "burrow into", "a rabbit burrow"],
    mnemonic: "borrow(借りる)と混同注意。動物が掘る穴とその動作。",
    relatedWords: ["dig", "hole", "rabbit"],
  },
  {
    id: "herd",
    word: "herd",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(牛・羊などの)群れ", "追い集める"],
    pronunciation: "/hɜːrd/",
    exampleSentence: "A herd of cattle blocked the road.",
    exampleTranslationJa: "牛の群れが道をふさいでいた。",
    collocations: ["a herd of cattle", "herd instinct", "herd people into"],
    mnemonic: "四つ足の大きな動物は herd、鳥や羊は flock、虫や魚は swarm / school。",
    relatedWords: ["flock", "cattle", "group"],
  },
  {
    id: "flock",
    word: "flock",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(鳥・羊の)群れ", "群がって行く"],
    pronunciation: "/flɑːk/",
    exampleSentence: "Tourists flocked to the island every summer.",
    exampleTranslationJa: "観光客は毎年夏にその島へ押し寄せた。",
    collocations: ["a flock of birds", "a flock of sheep", "flock to"],
    mnemonic: "鳥と羊の群れが flock。人が押し寄せるのも動詞で flock to。",
    relatedWords: ["herd", "swarm", "crowd"],
  },
  {
    id: "swarm",
    word: "swarm",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(虫の)大群", "群がる"],
    pronunciation: "/swɔːrm/",
    exampleSentence: "A swarm of bees settled on the branch.",
    exampleTranslationJa: "ミツバチの大群が枝にとまった。",
    collocations: ["a swarm of bees", "swarm with tourists", "swarm around"],
    mnemonic: "be swarming with で「〜でごった返している」。虫がわく感じ。",
    relatedWords: ["herd", "flock", "bee"],
  },
  {
    id: "oak",
    word: "oak",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カシ、ナラ(の木)"],
    pronunciation: "/oʊk/",
    exampleSentence: "An old oak stood at the edge of the field.",
    exampleTranslationJa: "古いカシの木が畑のはずれに立っていた。",
    collocations: ["an oak tree", "solid oak", "an oak table"],
    mnemonic: "英語圏で「強くて長生きの木」の代表。家具の材にもなる。",
    relatedWords: ["tree", "acorn", "timber"],
  },
  {
    id: "pine",
    word: "pine",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["マツ(松)", "(pine for で)恋しがる"],
    pronunciation: "/paɪn/",
    exampleSentence: "The air smelled of pine after the rain.",
    exampleTranslationJa: "雨のあと、空気は松の香りがした。",
    collocations: ["a pine tree", "a pine forest", "pine for home"],
    mnemonic: "動詞 pine for は「やせ細るほど恋しがる」。木の名と同じつづり。",
    relatedWords: ["tree", "needle", "forest"],
  },
  {
    id: "maple",
    word: "maple",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カエデ、モミジ"],
    pronunciation: "/ˈmeɪpl/",
    exampleSentence: "The maple turns bright red in autumn.",
    exampleTranslationJa: "カエデは秋に真っ赤に色づく。",
    collocations: ["a maple leaf", "maple syrup", "a maple tree"],
    mnemonic: "カナダの国旗の葉。樹液から maple syrup を作る。",
    relatedWords: ["leaf", "syrup", "autumn"],
  },
  {
    id: "birch",
    word: "birch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["カバノキ、シラカバ"],
    pronunciation: "/bɜːrtʃ/",
    exampleSentence: "White birch trees lined the path.",
    exampleTranslationJa: "白いシラカバが小道に並んでいた。",
    collocations: ["a silver birch", "birch bark", "a birch forest"],
    mnemonic: "白い樹皮が特徴。寒い地方の代表的な木。",
    relatedWords: ["tree", "bark", "forest"],
  },
  {
    id: "willow",
    word: "willow",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヤナギ"],
    pronunciation: "/ˈwɪloʊ/",
    exampleSentence: "A willow leaned over the edge of the pond.",
    exampleTranslationJa: "ヤナギが池のふちに枝を垂らしていた。",
    collocations: ["a weeping willow", "willow branches"],
    mnemonic: "枝が垂れる種類は a weeping willow(しだれ柳)。",
    relatedWords: ["tree", "branch", "pond"],
  },
  {
    id: "bamboo",
    word: "bamboo",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["竹"],
    pronunciation: "/ˌbæmˈbuː/",
    exampleSentence: "The floor was made of polished bamboo.",
    exampleTranslationJa: "床は磨いた竹でできていた。",
    collocations: ["a bamboo forest", "bamboo shoots", "a bamboo pole"],
    mnemonic: "アクセントは後ろ /ˌbæmˈbuː/。木ではなく巨大なイネ科の草。",
    relatedWords: ["grass", "shoot", "wood"],
  },
  {
    id: "cactus",
    word: "cactus",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["サボテン"],
    pronunciation: "/ˈkæktəs/",
    exampleSentence: "A tall cactus threw a long shadow on the sand.",
    exampleTranslationJa: "背の高いサボテンが砂に長い影を落としていた。",
    collocations: ["a desert cactus", "cactus spines"],
    mnemonic: "複数形は cacti または cactuses。砂漠で水をためる植物。",
    relatedWords: ["desert", "thorn", "plant"],
  },
  {
    id: "fern",
    word: "fern",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["シダ"],
    pronunciation: "/fɜːrn/",
    exampleSentence: "Ferns covered the damp forest floor.",
    exampleTranslationJa: "シダが湿った森の地面を覆っていた。",
    collocations: ["a tree fern", "ferns and moss"],
    mnemonic: "花を咲かせず胞子で増える古い植物。日陰と湿気を好む。",
    relatedWords: ["moss", "forest", "plant"],
  },
  {
    id: "moss",
    word: "moss",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["コケ"],
    pronunciation: "/mɔːs/",
    exampleSentence: "Green moss grew on the north side of the stones.",
    exampleTranslationJa: "石の北側に緑のコケが生えていた。",
    collocations: ["a rolling stone gathers no moss", "covered in moss"],
    mnemonic: "A rolling stone gathers no moss.(転石コケむさず)ということわざで覚える。",
    relatedWords: ["fern", "damp", "stone"],
  },
  {
    id: "vine",
    word: "vine",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["つる植物、ぶどうの木"],
    pronunciation: "/vaɪn/",
    exampleSentence: "A vine climbed the whole wall of the cottage.",
    exampleTranslationJa: "つるが小屋の壁一面をはい上がっていた。",
    collocations: ["a grape vine", "climbing vines", "on the vine"],
    mnemonic: "wine(ワイン)と同語源。ぶどうの木から「つる植物」全般へ。",
    relatedWords: ["grape", "climb", "wine"],
  },
  {
    id: "shrub",
    word: "shrub",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["低木、かん木"],
    pronunciation: "/ʃrʌb/",
    exampleSentence: "Low shrubs grew along the garden wall.",
    exampleTranslationJa: "庭の塀に沿って低木が生えていた。",
    collocations: ["a flowering shrub", "plant shrubs", "shrubs and trees"],
    mnemonic: "幹が一本ではなく根元から枝分かれする背の低い木。bush とほぼ同じ。",
    relatedWords: ["bush", "tree", "garden"],
  },
  {
    id: "hedge",
    word: "hedge",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["生け垣", "(損失を)避ける手を打つ", "言葉を濁す"],
    pronunciation: "/hedʒ/",
    exampleSentence: "A neat hedge separated the two gardens.",
    exampleTranslationJa: "きれいに刈られた生け垣が二つの庭を隔てていた。",
    collocations: ["trim a hedge", "hedge your bets", "a hedge fund"],
    mnemonic: "hedge your bets は「両方に賭けて損を防ぐ」。hedge fund の hedge もこれ。",
    relatedWords: ["fence", "shrub", "boundary"],
  },
  {
    id: "trunk",
    word: "trunk",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["幹", "(ゾウの)鼻", "(米)車のトランク", "大型の旅行かばん"],
    pronunciation: "/trʌŋk/",
    exampleSentence: "He carved his initials into the trunk of the tree.",
    exampleTranslationJa: "彼は木の幹に自分の頭文字を刻んだ。",
    collocations: ["a tree trunk", "an elephant's trunk", "the car trunk"],
    mnemonic: "「太い本体」が芯。木の幹、ゾウの鼻、車の荷物入れ、大きなかばん。",
    relatedWords: ["branch", "stem", "elephant"],
  },
  {
    id: "twig",
    word: "twig",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小枝"],
    pronunciation: "/twɪɡ/",
    exampleSentence: "A twig snapped under his boot.",
    exampleTranslationJa: "彼のブーツの下で小枝がぽきりと折れた。",
    collocations: ["a dry twig", "snap a twig", "twigs and leaves"],
    mnemonic: "branch(枝)より細い、指ほどの枝。折ると小さな音がする。",
    relatedWords: ["branch", "stick", "tree"],
  },
  {
    id: "bud",
    word: "bud",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["つぼみ、芽", "芽を出す"],
    pronunciation: "/bʌd/",
    exampleSentence: "The buds opened after a week of warm weather.",
    exampleTranslationJa: "暖かい日が一週間続いてつぼみが開いた。",
    collocations: ["a flower bud", "nip it in the bud", "buds appear"],
    mnemonic: "nip it in the bud は「つぼみのうちに摘む」＝「早めに芽を摘む」。",
    relatedWords: ["blossom", "flower", "sprout"],
  },
  {
    id: "blossom",
    word: "blossom",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(果樹の)花", "花が咲く、開花する"],
    pronunciation: "/ˈblɑːsəm/",
    exampleSentence: "The cherry trees blossom in early spring.",
    exampleTranslationJa: "桜は早春に花を咲かせる。",
    collocations: ["cherry blossom", "in full blossom", "blossom into"],
    mnemonic: "blossom into で「〜へと大きく育つ」。人の成長にも使う。",
    relatedWords: ["bloom", "flower", "bud"],
  },
  {
    id: "petal",
    word: "petal",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["花びら"],
    pronunciation: "/ˈpetl/",
    exampleSentence: "Pink petals covered the pavement.",
    exampleTranslationJa: "ピンクの花びらが歩道を覆っていた。",
    collocations: ["rose petals", "fallen petals", "pull off the petals"],
    mnemonic: "metal と韻を踏む。花の色のついた一枚一枚。",
    relatedWords: ["flower", "blossom", "stem"],
  },
  {
    id: "thorn",
    word: "thorn",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["とげ"],
    pronunciation: "/θɔːrn/",
    exampleSentence: "A thorn went straight through her glove.",
    exampleTranslationJa: "とげが彼女の手袋を突き抜けた。",
    collocations: ["a rose thorn", "a thorn in your side", "thorns and roses"],
    mnemonic: "a thorn in someone's side は「悩みの種」。刺さり続ける痛み。",
    relatedWords: ["spine", "rose", "prick"],
  },
  {
    id: "pollen",
    word: "pollen",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["花粉"],
    pronunciation: "/ˈpɑːlən/",
    exampleSentence: "The pollen count is high today.",
    exampleTranslationJa: "今日は花粉の飛散量が多い。",
    collocations: ["the pollen count", "pollen allergy", "spread pollen"],
    mnemonic: "動詞は pollinate(受粉させる)。花粉症は hay fever。",
    relatedWords: ["allergy", "bee", "flower"],
  },
  {
    id: "sap",
    word: "sap",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["樹液", "(力を)徐々に奪う"],
    pronunciation: "/sæp/",
    exampleSentence: "Sap ran down the cut in the bark.",
    exampleTranslationJa: "樹皮の切り口から樹液が流れ出た。",
    collocations: ["maple sap", "sap your strength", "sticky sap"],
    mnemonic: "木の中を流れる汁。動詞では「じわじわ体力を吸い取る」。",
    relatedWords: ["tree", "bark", "resin"],
  },
  {
    id: "bark",
    word: "bark",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["樹皮", "(犬が)ほえる", "ほえ声"],
    pronunciation: "/bɑːrk/",
    exampleSentence: "The bark of this tree peels off in strips.",
    exampleTranslationJa: "この木の樹皮は帯状にはがれる。",
    collocations: ["tree bark", "a dog barks", "his bark is worse than his bite"],
    mnemonic: "樹皮も犬の鳴き声も bark。His bark is worse than his bite. は「口ほど怖くない」。",
    relatedWords: ["trunk", "dog", "tree"],
  },
  {
    id: "meadow",
    word: "meadow",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["牧草地、草原"],
    pronunciation: "/ˈmedoʊ/",
    exampleSentence: "Wild flowers filled the meadow in June.",
    exampleTranslationJa: "6月には野の花が草原を埋めつくした。",
    collocations: ["a flower meadow", "across the meadow", "a hay meadow"],
    mnemonic: "ea を /e/ と読む /ˈmedoʊ/。花が咲く平らな草地。",
    relatedWords: ["field", "pasture", "grass"],
  },
  {
    id: "pasture",
    word: "pasture",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["牧草地"],
    pronunciation: "/ˈpæstʃər/",
    exampleSentence: "The cows were let out into the pasture.",
    exampleTranslationJa: "牛たちは牧草地に放された。",
    collocations: ["graze in the pasture", "green pastures", "put out to pasture"],
    mnemonic: "put out to pasture は「引退させる」。働いた馬を牧草地に放つことから。",
    relatedWords: ["meadow", "graze", "cattle"],
  },
  {
    id: "swamp",
    word: "swamp",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["沼地、湿地", "圧倒する、殺到する"],
    pronunciation: "/swɑːmp/",
    exampleSentence: "The road disappeared into the swamp.",
    exampleTranslationJa: "道は沼地の中に消えていた。",
    collocations: ["a tropical swamp", "be swamped with work", "swamp land"],
    mnemonic: "be swamped with work は「仕事に埋もれる」。沼にはまるイメージ。",
    relatedWords: ["marsh", "wetland", "mud"],
  },
  {
    id: "marsh",
    word: "marsh",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["湿地、沼沢地"],
    pronunciation: "/mɑːrʃ/",
    exampleSentence: "Birds nest in the marsh every spring.",
    exampleTranslationJa: "毎春、鳥たちはその湿地で巣を作る。",
    collocations: ["a salt marsh", "marsh birds", "cross the marsh"],
    mnemonic: "swamp より水が浅く、草が生えているほう。海辺のものは salt marsh。",
    relatedWords: ["swamp", "wetland", "bog"],
  },
  {
    id: "dune",
    word: "dune",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["砂丘"],
    pronunciation: "/duːn/",
    exampleSentence: "They climbed the dune to see the sea.",
    exampleTranslationJa: "彼らは海を見ようと砂丘に登った。",
    collocations: ["a sand dune", "shifting dunes", "climb a dune"],
    mnemonic: "風で形が変わる砂の丘。sand dune の形でよく使う。",
    relatedWords: ["sand", "desert", "beach"],
  },
  {
    id: "canyon",
    word: "canyon",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["峡谷"],
    pronunciation: "/ˈkænjən/",
    exampleSentence: "The river cut a deep canyon through the rock.",
    exampleTranslationJa: "川は岩を削って深い峡谷を作った。",
    collocations: ["a deep canyon", "the Grand Canyon", "the canyon floor"],
    etymology: "スペイン語 cañón(筒)から。両側が切り立った細長い谷。",
    mnemonic: "スペイン語で「筒」。両側が壁のように切り立った谷。",
    relatedWords: ["valley", "gorge", "cliff"],
  },
  {
    id: "plateau",
    word: "plateau",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["高原、台地", "(伸びが)頭打ちになる"],
    pronunciation: "/plæˈtoʊ/",
    exampleSentence: "Sales have reached a plateau this year.",
    exampleTranslationJa: "売上は今年、頭打ちになった。",
    collocations: ["a high plateau", "reach a plateau", "plateau out"],
    mnemonic: "フランス語 plat(平ら)から。地形の「平らな高台」→グラフの「横ばい」。",
    relatedWords: ["plain", "highland", "level"],
  },
  {
    id: "ridge",
    word: "ridge",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["尾根、稜線", "細長い盛り上がり"],
    pronunciation: "/rɪdʒ/",
    exampleSentence: "They walked along the ridge for two hours.",
    exampleTranslationJa: "彼らは2時間、尾根を歩いた。",
    collocations: ["a mountain ridge", "along the ridge", "the ridge of a roof"],
    mnemonic: "山の背中の細長い高まり。屋根の一番上の線も ridge。",
    relatedWords: ["peak", "slope", "mountain"],
  },
  {
    id: "creek",
    word: "creek",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小川(米)、入り江(英)"],
    pronunciation: "/kriːk/",
    exampleSentence: "The children waded across the shallow creek.",
    exampleTranslationJa: "子どもたちは浅い小川を歩いて渡った。",
    collocations: ["a shallow creek", "up the creek", "along the creek"],
    mnemonic: "米では小川、英では細い入り江。be up the creek は「困った状況にある」。",
    relatedWords: ["stream", "brook", "river"],
  },
  {
    id: "waterfall",
    word: "waterfall",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["滝"],
    pronunciation: "/ˈwɔːtərfɔːl/",
    exampleSentence: "You can hear the waterfall from the path.",
    exampleTranslationJa: "その小道から滝の音が聞こえる。",
    collocations: ["a spectacular waterfall", "behind the waterfall"],
    wordFormation: "water(水)+ fall(落ちること)。",
    mnemonic: "water(水)が fall(落ちる)所。そのままの名前。",
    relatedWords: ["river", "cliff", "cascade"],
  },
  {
    id: "glacier",
    word: "glacier",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["氷河"],
    pronunciation: "/ˈɡleɪʃər/",
    exampleSentence: "The glacier has retreated by two kilometres.",
    exampleTranslationJa: "その氷河は2キロ後退した。",
    collocations: ["a melting glacier", "glacier retreat", "a mountain glacier"],
    etymology: "フランス語 glace(氷)から。glass や glaze と同語根。",
    mnemonic: "glace(氷)が語根。ゆっくり流れる氷の川。",
    relatedWords: ["ice", "melt", "mountain"],
  },
  {
    id: "iceberg",
    word: "iceberg",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["氷山"],
    pronunciation: "/ˈaɪsbɜːrɡ/",
    exampleSentence: "That is just the tip of the iceberg.",
    exampleTranslationJa: "それは氷山の一角にすぎない。",
    collocations: ["the tip of the iceberg", "hit an iceberg"],
    wordFormation: "ice(氷)+ オランダ語 berg(山)。",
    mnemonic: "the tip of the iceberg は「氷山の一角」。9割は水面下にある。",
    relatedWords: ["glacier", "ice", "ocean"],
  },
  {
    id: "breeze",
    word: "breeze",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["そよ風", "(口語)たやすいこと"],
    pronunciation: "/briːz/",
    exampleSentence: "A cool breeze came off the sea.",
    exampleTranslationJa: "海から涼しいそよ風が吹いてきた。",
    collocations: ["a gentle breeze", "a sea breeze", "a breeze to do"],
    mnemonic: "It's a breeze. は「朝飯前だ」。心地よい弱い風。",
    relatedWords: ["wind", "gale", "air"],
  },
  {
    id: "gale",
    word: "gale",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["強風、疾風"],
    pronunciation: "/ɡeɪl/",
    exampleSentence: "A gale blew the fence down overnight.",
    exampleTranslationJa: "強風が一晩でフェンスを吹き倒した。",
    collocations: ["a gale warning", "gale-force winds", "a howling gale"],
    mnemonic: "breeze(そよ風)と storm(嵐)の間の強さ。天気予報の gale warning は暴風警報。",
    relatedWords: ["wind", "storm", "breeze"],
  },
  {
    id: "thunder",
    word: "thunder",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["雷鳴、かみなりの音", "とどろく"],
    pronunciation: "/ˈθʌndər/",
    exampleSentence: "Thunder rolled across the valley.",
    exampleTranslationJa: "雷鳴が谷にとどろいた。",
    collocations: ["a clap of thunder", "thunder and lightning", "steal someone's thunder"],
    mnemonic: "光が lightning、音が thunder。steal someone's thunder は「手柄を横取りする」。",
    relatedWords: ["lightning", "storm", "rain"],
  },
  {
    id: "lightning",
    word: "lightning",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["いなずま、雷光"],
    pronunciation: "/ˈlaɪtnɪŋ/",
    exampleSentence: "Lightning struck the tall tree in the field.",
    exampleTranslationJa: "いなずまが野原の高い木を打った。",
    collocations: ["a flash of lightning", "struck by lightning", "lightning fast"],
    mnemonic: "つづりに e はない(lightening は「明るくする」の別語)。光のほうが lightning。",
    relatedWords: ["thunder", "storm", "flash"],
  },
  {
    id: "sleet",
    word: "sleet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["みぞれ"],
    pronunciation: "/sliːt/",
    exampleSentence: "Rain turned to sleet as the temperature fell.",
    exampleTranslationJa: "気温が下がって雨はみぞれに変わった。",
    collocations: ["driving sleet", "rain and sleet", "sleet showers"],
    mnemonic: "雨と雪の中間。粒の氷が降るのは hail(ひょう)。",
    relatedWords: ["hail", "snow", "rain"],
  },
  {
    id: "frost",
    word: "frost",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["霜、霜が降りるほどの寒さ"],
    pronunciation: "/frɔːst/",
    exampleSentence: "There was frost on the car windows this morning.",
    exampleTranslationJa: "今朝は車の窓に霜がついていた。",
    collocations: ["a heavy frost", "the first frost", "frost damage"],
    mnemonic: "freeze(凍る)と同語根。地表や窓につく白い氷の結晶。",
    relatedWords: ["ice", "freeze", "dew"],
  },
  {
    id: "dew",
    word: "dew",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["露(つゆ)"],
    pronunciation: "/duː/",
    exampleSentence: "The grass was wet with dew at dawn.",
    exampleTranslationJa: "夜明け、草は露にぬれていた。",
    collocations: ["morning dew", "wet with dew", "the dew point"],
    mnemonic: "due(期限の)と同音。朝、草につく水滴。凍ると frost。",
    relatedWords: ["frost", "moisture", "morning"],
  },
  {
    id: "mist",
    word: "mist",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["もや、薄い霧"],
    pronunciation: "/mɪst/",
    exampleSentence: "A thin mist hung over the river.",
    exampleTranslationJa: "薄いもやが川の上に垂れこめていた。",
    collocations: ["a morning mist", "shrouded in mist", "mist clears"],
    mnemonic: "fog より薄く、向こうが見える程度。濃いのが fog。",
    relatedWords: ["fog", "haze", "cloud"],
  },
  {
    id: "fog",
    word: "fog",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["霧(濃いもの)"],
    pronunciation: "/fɔːɡ/",
    exampleSentence: "Thick fog closed the airport for six hours.",
    exampleTranslationJa: "濃い霧で空港は6時間閉鎖された。",
    collocations: ["thick fog", "fog lights", "in a fog"],
    mnemonic: "in a fog は「頭がぼんやりして」。mist より濃くて前が見えない。",
    relatedWords: ["mist", "haze", "cloud"],
  },
  {
    id: "drizzle",
    word: "drizzle",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["霧雨", "霧雨が降る", "(料理で)細く垂らす"],
    pronunciation: "/ˈdrɪzl/",
    exampleSentence: "It drizzled all afternoon.",
    exampleTranslationJa: "午後じゅう霧雨が降っていた。",
    collocations: ["light drizzle", "drizzle with olive oil", "a cold drizzle"],
    mnemonic: "細かい雨。料理でオイルを細く垂らすのも drizzle。",
    relatedWords: ["rain", "shower", "mist"],
  },
  {
    id: "downpour",
    word: "downpour",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["どしゃぶり"],
    pronunciation: "/ˈdaʊnpɔːr/",
    exampleSentence: "We were caught in a sudden downpour.",
    exampleTranslationJa: "私たちは突然のどしゃぶりにあった。",
    collocations: ["a sudden downpour", "a heavy downpour", "caught in a downpour"],
    wordFormation: "down(下へ)+ pour(注ぐ)。",
    mnemonic: "空から pour(注ぐ)ように降る。drizzle の正反対。",
    relatedWords: ["rain", "storm", "shower"],
  },
  {
    id: "sunrise",
    word: "sunrise",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日の出"],
    pronunciation: "/ˈsʌnraɪz/",
    exampleSentence: "We set off before sunrise.",
    exampleTranslationJa: "私たちは日の出前に出発した。",
    collocations: ["at sunrise", "watch the sunrise", "before sunrise"],
    wordFormation: "sun(太陽)+ rise(のぼる)。",
    mnemonic: "太陽が「のぼる」瞬間。空が明るくなり始めるのは dawn。",
    relatedWords: ["dawn", "sunset", "morning"],
  },
  {
    id: "sunset",
    word: "sunset",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日没、夕焼け"],
    pronunciation: "/ˈsʌnset/",
    exampleSentence: "The sky turned orange at sunset.",
    exampleTranslationJa: "日没の空はオレンジ色に染まった。",
    collocations: ["at sunset", "a beautiful sunset", "ride off into the sunset"],
    wordFormation: "sun(太陽)+ set(沈む)。",
    mnemonic: "ride off into the sunset は物語の「めでたし」の終わり方。",
    relatedWords: ["dusk", "sunrise", "evening"],
  },
  {
    id: "dusk",
    word: "dusk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["夕暮れ、たそがれ"],
    pronunciation: "/dʌsk/",
    exampleSentence: "Bats come out at dusk.",
    exampleTranslationJa: "コウモリは夕暮れに出てくる。",
    collocations: ["at dusk", "from dawn till dusk", "in the dusk"],
    mnemonic: "dawn(夜明け)の反対。日が沈んだあとの薄暗い時間。",
    relatedWords: ["dawn", "twilight", "sunset"],
  },
  {
    id: "twilight",
    word: "twilight",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["薄明かり、たそがれ", "(比喩)晩年、末期"],
    pronunciation: "/ˈtwaɪlaɪt/",
    exampleSentence: "They walked home in the twilight.",
    exampleTranslationJa: "彼らは薄明かりの中を歩いて帰った。",
    collocations: ["in the twilight", "the twilight years", "twilight hours"],
    wordFormation: "twi-(二つ・半分)+ light(光)。「半分の光」。",
    mnemonic: "twi(半分)+ light(光)。「半分だけ明るい時間」。晩年も the twilight years。",
    relatedWords: ["dusk", "dawn", "dim"],
  },
]
