import type { VocabularyEntry } from '../types'

// 増補 第11弾。論説・実務でよく使う動詞の残りと、人・職業を表す名詞。
export const plus11: VocabularyEntry[] = [
  {
    id: "affirm",
    word: "affirm",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["断言する、肯定する"],
    pronunciation: "/əˈfɜːrm/",
    exampleSentence: "The court affirmed the earlier decision.",
    exampleTranslationJa: "裁判所は先の判断を支持した。",
    collocations: ["affirm a decision", "affirm your commitment"],
    wordFormation: "ad-(〜へ)+ firm(確かな)。",
    mnemonic: "firm(確かな)にすること。deny の反対で、かたい語。",
    relatedWords: ["confirm", "assert", "deny"],
  },
  {
    id: "approximate",
    word: "approximate",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["おおよその", "近づく"],
    pronunciation: "/əˈprɑːksɪmət/",
    exampleSentence: "The approximate cost is two thousand pounds.",
    exampleTranslationJa: "おおよその費用は2千ポンドだ。",
    collocations: ["an approximate figure", "approximate to", "approximately equal"],
    wordFormation: "ap-(〜へ)+ proximus(最も近い)。",
    mnemonic: "proximity(近さ)と同語根。「近い値」。副詞 approximately が頻出。",
    relatedWords: ["rough", "estimate", "exact"],
  },
  {
    id: "avert",
    word: "avert",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(危機を)避ける", "(目を)そらす"],
    pronunciation: "/əˈvɜːrt/",
    exampleSentence: "Quick action averted a much worse accident.",
    exampleTranslationJa: "素早い対応がもっとひどい事故を防いだ。",
    collocations: ["avert a crisis", "avert your eyes", "avert disaster"],
    wordFormation: "a-(離れて)+ vertere(向ける)。",
    mnemonic: "vert(向ける)が語根。危機を向こうへそらす、目をそらす。",
    relatedWords: ["prevent", "avoid", "divert"],
  },
  {
    id: "bestow",
    word: "bestow",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(名誉などを)授ける"],
    pronunciation: "/bɪˈstoʊ/",
    exampleSentence: "The king bestowed the title on his cousin.",
    exampleTranslationJa: "王はいとこにその称号を授けた。",
    collocations: ["bestow an honour on", "bestow a gift"],
    mnemonic: "上から下へ、名誉や賜り物を与える。bestow A on B の形。",
    relatedWords: ["grant", "confer", "award"],
  },
  {
    id: "bolster",
    word: "bolster",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["支える、補強する"],
    pronunciation: "/ˈboʊlstər/",
    exampleSentence: "New data bolstered their case.",
    exampleTranslationJa: "新しいデータが彼らの主張を補強した。",
    collocations: ["bolster confidence", "bolster the economy", "bolster an argument"],
    mnemonic: "bolster は長まくら。下から支えて持ち上げるイメージ。",
    relatedWords: ["support", "strengthen", "reinforce"],
  },
  {
    id: "broaden",
    word: "broaden",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["広げる、広がる"],
    pronunciation: "/ˈbrɔːdn/",
    exampleSentence: "Travel broadens the mind.",
    exampleTranslationJa: "旅は視野を広げる。",
    collocations: ["broaden your horizons", "broaden the appeal", "the river broadens"],
    wordFormation: "broad(広い)+ -en(〜にする)。",
    mnemonic: "widen が幅、broaden は範囲や視野に使うことが多い。",
    relatedWords: ["widen", "expand", "narrow"],
  },
  {
    id: "crave",
    word: "crave",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["切望する、無性に欲しがる"],
    pronunciation: "/kreɪv/",
    exampleSentence: "Pregnant women often crave odd foods.",
    exampleTranslationJa: "妊婦は妙なものを無性に食べたくなることがある。",
    collocations: ["crave attention", "crave sugar", "crave affection"],
    mnemonic: "体が求めるような強い欲求。名詞は craving。",
    relatedWords: ["desire", "long for", "yearn"],
  },
  {
    id: "defer",
    word: "defer",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["延期する", "(defer to で)従う"],
    pronunciation: "/dɪˈfɜːr/",
    exampleSentence: "They deferred the decision until March.",
    exampleTranslationJa: "彼らはその決定を3月まで先送りした。",
    collocations: ["defer payment", "defer to someone's judgement"],
    wordFormation: "de-(離れて)+ ferre(運ぶ)。",
    mnemonic: "後ろへ運ぶ＝延期。defer to ... なら「相手の判断を立てる」。",
    relatedWords: ["postpone", "delay", "yield"],
  },
  {
    id: "denote",
    word: "denote",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["示す、意味する"],
    pronunciation: "/dɪˈnoʊt/",
    exampleSentence: "A red line denotes the border.",
    exampleTranslationJa: "赤い線は国境を示す。",
    collocations: ["denote a change", "the symbol denotes"],
    wordFormation: "de-(強意)+ note(印)。",
    mnemonic: "記号や語が「指し示す」意味。connote(含みを持つ)と対。",
    relatedWords: ["indicate", "signify", "connote"],
  },
  {
    id: "deter",
    word: "deter",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["思いとどまらせる"],
    pronunciation: "/dɪˈtɜːr/",
    exampleSentence: "Higher fines deter most drivers.",
    exampleTranslationJa: "罰金の引き上げはたいていの運転者を思いとどまらせる。",
    collocations: ["deter crime", "deter someone from doing"],
    wordFormation: "de-(離れて)+ terrere(怖がらせる)。terror と同語根。",
    mnemonic: "terror(恐怖)と同語根。名詞は deterrent(抑止力)。",
    relatedWords: ["discourage", "prevent", "deterrent"],
  },
  {
    id: "discern",
    word: "discern",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["見分ける、識別する"],
    pronunciation: "/dɪˈsɜːrn/",
    exampleSentence: "It is hard to discern any pattern in the data.",
    exampleTranslationJa: "そのデータに何か規則を見いだすのは難しい。",
    collocations: ["discern a pattern", "hard to discern", "discern the difference"],
    wordFormation: "dis-(分けて)+ cernere(ふるい分ける)。",
    mnemonic: "注意深く見て見分けること。形容詞 discerning は「目の肥えた」。",
    relatedWords: ["distinguish", "perceive", "detect"],
  },
  {
    id: "dispatch",
    word: "dispatch",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["発送する、急派する", "発送"],
    pronunciation: "/dɪˈspætʃ/",
    exampleSentence: "The parts will dispatch within 24 hours.",
    exampleTranslationJa: "部品は24時間以内に発送されます。",
    collocations: ["dispatch an order", "dispatch troops", "a news dispatch"],
    mnemonic: "荷物にも人員にも使う。ニュースの「特電」の意味もある。",
    relatedWords: ["send", "forward", "deploy"],
  },
  {
    id: "disperse",
    word: "disperse",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["散らす、散る"],
    pronunciation: "/dɪˈspɜːrs/",
    exampleSentence: "Police asked the crowd to disperse.",
    exampleTranslationJa: "警察は群衆に解散するよう求めた。",
    collocations: ["disperse a crowd", "the fog disperses", "widely dispersed"],
    wordFormation: "dis-(あちこちに)+ spargere(まく)。",
    mnemonic: "一か所にあったものが四方に散る。scatter よりかたい。",
    relatedWords: ["scatter", "spread", "gather"],
  },
  {
    id: "dwell",
    word: "dwell",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["住む(古風)", "(dwell on で)くよくよ考える"],
    pronunciation: "/dwel/",
    exampleSentence: "Try not to dwell on your mistakes.",
    exampleTranslationJa: "失敗をくよくよ考えないようにしなさい。",
    collocations: ["dwell on the past", "dwell in a village", "dwell upon"],
    mnemonic: "「住む」は古めかしい。今は dwell on(いつまでも考える)で使う。",
    relatedWords: ["live", "reside", "ponder"],
  },
  {
    id: "elicit",
    word: "elicit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(反応・情報を)引き出す"],
    pronunciation: "/ɪˈlɪsɪt/",
    exampleSentence: "The question elicited an unexpected answer.",
    exampleTranslationJa: "その質問は思いがけない答えを引き出した。",
    collocations: ["elicit a response", "elicit information", "elicit sympathy"],
    wordFormation: "e-(外へ)+ lacere(誘い出す)。",
    mnemonic: "illicit(違法な)と同音。相手から反応を引っぱり出すこと。",
    relatedWords: ["draw out", "provoke", "obtain"],
  },
  {
    id: "emit",
    word: "emit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(光・音・ガスを)出す"],
    pronunciation: "/ɪˈmɪt/",
    exampleSentence: "The factory emits less carbon than before.",
    exampleTranslationJa: "その工場は以前より炭素の排出が少ない。",
    collocations: ["emit carbon", "emit light", "emit a sound"],
    wordFormation: "e-(外へ)+ mittere(送る)。mission と同語根。",
    mnemonic: "mission・transmit と同語根。名詞は emission。",
    relatedWords: ["release", "give off", "emission"],
  },
  {
    id: "emphasise",
    word: "emphasise",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["強調する"],
    pronunciation: "/ˈemfəsaɪz/",
    exampleSentence: "He emphasised the need for care.",
    exampleTranslationJa: "彼は慎重さの必要を強調した。",
    collocations: ["emphasise the importance", "strongly emphasise"],
    wordFormation: "emphasis(強調)+ -ise。",
    mnemonic: "米つづりは emphasize。名詞 emphasis の複数形は emphases。",
    relatedWords: ["stress", "highlight", "emphasis"],
  },
  {
    id: "enlarge",
    word: "enlarge",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["拡大する"],
    pronunciation: "/ɪnˈlɑːrdʒ/",
    exampleSentence: "Could you enlarge the photo a little?",
    exampleTranslationJa: "その写真を少し拡大してもらえますか。",
    collocations: ["enlarge a photograph", "enlarge on a point"],
    wordFormation: "en-(〜にする)+ large(大きい)。",
    mnemonic: "写真や画像の拡大が典型。enlarge on ... は「詳しく述べる」。",
    relatedWords: ["expand", "magnify", "reduce"],
  },
  {
    id: "entrust",
    word: "entrust",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(人に)任せる、委ねる"],
    pronunciation: "/ɪnˈtrʌst/",
    exampleSentence: "She entrusted the keys to a neighbour.",
    exampleTranslationJa: "彼女は鍵を隣人に預けた。",
    collocations: ["entrust A to B", "entrust someone with"],
    wordFormation: "en-(〜にする)+ trust(信頼)。",
    mnemonic: "trust(信頼)して預ける。entrust A with B / entrust A to B の二通り。",
    relatedWords: ["trust", "delegate", "assign"],
  },
  {
    id: "envisage",
    word: "envisage",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["思い描く、予想する"],
    pronunciation: "/ɪnˈvɪzɪdʒ/",
    exampleSentence: "I do not envisage any problems.",
    exampleTranslationJa: "問題が起きるとは思っていません。",
    collocations: ["envisage a future", "do not envisage", "envisage doing"],
    wordFormation: "en-(中に)+ visage(顔・姿)。",
    mnemonic: "頭の中に姿を思い描くこと。米では envision が多い。",
    relatedWords: ["imagine", "foresee", "envision"],
  },
  {
    id: "equate",
    word: "equate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["同一視する、等しいとみなす"],
    pronunciation: "/ɪˈkweɪt/",
    exampleSentence: "Do not equate wealth with happiness.",
    exampleTranslationJa: "富と幸福を同一視してはいけない。",
    collocations: ["equate A with B", "equate to", "wrongly equate"],
    wordFormation: "equal(等しい)と同語根。",
    mnemonic: "equate A with B の形。数学の equation(方程式)と同語根。",
    relatedWords: ["identify", "compare", "equal"],
  },
  {
    id: "exempt",
    word: "exempt",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["免除された", "免除する"],
    pronunciation: "/ɪɡˈzempt/",
    exampleSentence: "Books are exempt from the tax.",
    exampleTranslationJa: "本はその税を免除されている。",
    collocations: ["exempt from tax", "be exempt from", "exempt someone from"],
    wordFormation: "ex-(外へ)+ emere(取る)。「外へ取り出す」。",
    mnemonic: "be exempt from ... の形が基本。名詞は exemption。",
    relatedWords: ["excuse", "free", "liable"],
  },
  {
    id: "expel",
    word: "expel",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["追放する、退学させる", "(空気などを)吐き出す"],
    pronunciation: "/ɪkˈspel/",
    exampleSentence: "He was expelled from school at fifteen.",
    exampleTranslationJa: "彼は15歳で退学処分になった。",
    collocations: ["expel a student", "expel from the country", "expel air"],
    wordFormation: "ex-(外へ)+ pellere(押す)。",
    mnemonic: "compel・propel と同語根。外へ押し出すこと。名詞は expulsion。",
    relatedWords: ["eject", "banish", "exclude"],
  },
  {
    id: "fabricate",
    word: "fabricate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["でっち上げる", "(部品を)製作する"],
    pronunciation: "/ˈfæbrɪkeɪt/",
    exampleSentence: "He fabricated the whole story.",
    exampleTranslationJa: "彼はその話をまるごとでっち上げた。",
    collocations: ["fabricate evidence", "fabricate a story", "fabricate parts"],
    wordFormation: "fabric(織物・構造)+ -ate。",
    mnemonic: "fabric(布)と同語根。「組み立てる」から「話を作る」へ。",
    relatedWords: ["invent", "forge", "manufacture"],
  },
  {
    id: "falter",
    word: "falter",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["よろめく、勢いが衰える", "口ごもる"],
    pronunciation: "/ˈfɔːltər/",
    exampleSentence: "Sales began to falter in the autumn.",
    exampleTranslationJa: "売上は秋に伸び悩み始めた。",
    collocations: ["never falter", "the economy falters", "falter in your speech"],
    mnemonic: "確かだった歩みや声が揺らぐこと。without faltering は「ひるまずに」。",
    relatedWords: ["waver", "stumble", "hesitate"],
  },
  {
    id: "furnish",
    word: "furnish",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["家具を備える", "(情報を)提供する"],
    pronunciation: "/ˈfɜːrnɪʃ/",
    exampleSentence: "The flat comes furnished.",
    exampleTranslationJa: "そのアパートは家具付きだ。",
    collocations: ["a furnished flat", "furnish evidence", "furnish someone with"],
    mnemonic: "furniture(家具)と同語根。furnish A with B で「AにBを備える」。",
    relatedWords: ["equip", "supply", "furniture"],
  },
  {
    id: "gauge",
    word: "gauge",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["測る、判断する", "計器、基準"],
    pronunciation: "/ɡeɪdʒ/",
    exampleSentence: "It is hard to gauge public opinion from here.",
    exampleTranslationJa: "ここから世論を測るのは難しい。",
    collocations: ["gauge the reaction", "a fuel gauge", "gauge public opinion"],
    mnemonic: "つづりが読みにくいが /ɡeɪdʒ/。心の動きや反応を「測る」のにも使う。",
    relatedWords: ["measure", "assess", "meter"],
  },
  {
    id: "harness",
    word: "harness",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(力を)利用する", "馬具、安全帯"],
    pronunciation: "/ˈhɑːrnɪs/",
    exampleSentence: "They harness the wind to make electricity.",
    exampleTranslationJa: "彼らは風を利用して電気を作る。",
    collocations: ["harness energy", "harness the power of", "a safety harness"],
    mnemonic: "馬に harness(馬具)をつけて働かせることから、自然の力を「使いこなす」へ。",
    relatedWords: ["utilise", "exploit", "control"],
  },
  {
    id: "hoist",
    word: "hoist",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["引き上げる、掲げる"],
    pronunciation: "/hɔɪst/",
    exampleSentence: "They hoist the flag every morning.",
    exampleTranslationJa: "彼らは毎朝、旗を掲げる。",
    collocations: ["hoist a flag", "hoist a sail", "hoist into place"],
    mnemonic: "綱や機械で重いものを持ち上げること。旗や帆に使うことが多い。",
    relatedWords: ["lift", "raise", "haul"],
  },
  {
    id: "ignite",
    word: "ignite",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["火をつける、発火する", "(感情を)かき立てる"],
    pronunciation: "/ɪɡˈnaɪt/",
    exampleSentence: "A spark can ignite the gas.",
    exampleTranslationJa: "火花一つでそのガスに引火しうる。",
    collocations: ["ignite a fire", "ignite a debate", "ignite passion"],
    wordFormation: "ラテン語 ignis(火)から。",
    mnemonic: "ignis(火)が語根。議論に火をつける比喩でもよく使う。",
    relatedWords: ["light", "spark", "kindle"],
  },
  {
    id: "immerse",
    word: "immerse",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["浸す", "没頭させる"],
    pronunciation: "/ɪˈmɜːrs/",
    exampleSentence: "She immersed herself in the language for a year.",
    exampleTranslationJa: "彼女は1年間その言語にどっぷり浸かった。",
    collocations: ["immerse yourself in", "fully immersed", "immerse in water"],
    wordFormation: "im-(中に)+ mergere(沈める)。",
    mnemonic: "merge と同語根。水に沈めることから「没頭する」へ。",
    relatedWords: ["absorb", "submerge", "engross"],
  },
  {
    id: "inhabit",
    word: "inhabit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(場所に)住む、生息する"],
    pronunciation: "/ɪnˈhæbɪt/",
    exampleSentence: "Only seabirds inhabit the island.",
    exampleTranslationJa: "その島には海鳥しか生息していない。",
    collocations: ["inhabit an area", "inhabited by", "densely inhabited"],
    wordFormation: "in-(中に)+ habitare(住む)。",
    mnemonic: "habitat(生息地)と同語根。人にも動物にも使う。",
    relatedWords: ["occupy", "populate", "habitat"],
  },
  {
    id: "inscribe",
    word: "inscribe",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["刻む、書き入れる"],
    pronunciation: "/ɪnˈskraɪb/",
    exampleSentence: "Their names are inscribed on the memorial.",
    exampleTranslationJa: "彼らの名は記念碑に刻まれている。",
    collocations: ["inscribe a name", "inscribed on the stone", "inscribe a book"],
    wordFormation: "in-(中に)+ scribere(書く)。",
    mnemonic: "describe・scribe と同語根。石や金属に刻むこと。名詞は inscription。",
    relatedWords: ["engrave", "carve", "write"],
  },
  {
    id: "instil",
    word: "instil",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(考え・習慣を)少しずつ植えつける"],
    pronunciation: "/ɪnˈstɪl/",
    exampleSentence: "Her parents instilled a love of reading in her.",
    exampleTranslationJa: "両親は彼女に読書好きを育てた。",
    collocations: ["instil confidence", "instil values in", "instil discipline"],
    wordFormation: "in-(中に)+ stillare(したたらせる)。",
    mnemonic: "米つづりは instill。したたらせるように少しずつ心に入れること。",
    relatedWords: ["implant", "teach", "inspire"],
  },
  {
    id: "intrigue",
    word: "intrigue",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["興味をそそる", "陰謀"],
    pronunciation: "/ɪnˈtriːɡ/",
    exampleSentence: "The title intrigues me.",
    exampleTranslationJa: "その題名に興味をそそられる。",
    collocations: ["intrigue someone", "political intrigue", "be intrigued by"],
    mnemonic: "be intrigued by ... で「〜に強く興味を引かれる」。名詞は「陰謀」。",
    relatedWords: ["fascinate", "interest", "plot"],
  },
  {
    id: "legislate",
    word: "legislate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["法律を制定する"],
    pronunciation: "/ˈledʒɪsleɪt/",
    exampleSentence: "Parliament may legislate on the issue this year.",
    exampleTranslationJa: "議会は今年その問題について立法するかもしれない。",
    collocations: ["legislate against", "legislate on", "legislate for"],
    wordFormation: "legis(法)+ latus(運ぶ)。",
    mnemonic: "legal・legislation と同語根。「法を定める」。",
    relatedWords: ["legislation", "enact", "law"],
  },
  {
    id: "lessen",
    word: "lessen",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["減らす、弱める"],
    pronunciation: "/ˈlesn/",
    exampleSentence: "The drug lessens the pain but does not cure it.",
    exampleTranslationJa: "その薬は痛みを和らげるが治しはしない。",
    collocations: ["lessen the risk", "lessen the impact", "lessen the pain"],
    wordFormation: "less(より少ない)+ -en(〜にする)。",
    mnemonic: "lesson(授業)と同音。つづりが一字違うので注意。",
    relatedWords: ["reduce", "diminish", "increase"],
  },
  {
    id: "liberate",
    word: "liberate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["解放する"],
    pronunciation: "/ˈlɪbəreɪt/",
    exampleSentence: "The city was liberated in 1944.",
    exampleTranslationJa: "その都市は1944年に解放された。",
    collocations: ["liberate a city", "liberate from", "feel liberated"],
    wordFormation: "ラテン語 liber(自由な)から。liberty と同語根。",
    mnemonic: "liberty(自由)と同語根。束縛から解き放つこと。",
    relatedWords: ["free", "release", "liberty"],
  },
  {
    id: "lodge",
    word: "lodge",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(苦情を)申し立てる", "泊まる", "山小屋"],
    pronunciation: "/lɑːdʒ/",
    exampleSentence: "She lodged a formal complaint with the council.",
    exampleTranslationJa: "彼女は議会に正式な苦情を申し立てた。",
    collocations: ["lodge a complaint", "lodge an appeal", "a hunting lodge"],
    mnemonic: "lodge a complaint(苦情を出す)の形が実用的。宿の意味もある。",
    relatedWords: ["file", "submit", "accommodation"],
  },
  {
    id: "magnify",
    word: "magnify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["拡大する", "大げさにする"],
    pronunciation: "/ˈmæɡnɪfaɪ/",
    exampleSentence: "The lens magnifies the image ten times.",
    exampleTranslationJa: "そのレンズは像を10倍に拡大する。",
    collocations: ["magnify an image", "a magnifying glass", "magnify the problem"],
    wordFormation: "magnus(大きい)+ -fy。",
    mnemonic: "magnitude・magnificent と同語根。虫めがねは a magnifying glass。",
    relatedWords: ["enlarge", "exaggerate", "microscope"],
  },
  {
    id: "marginalise",
    word: "marginalise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["わきに追いやる、軽んじる"],
    pronunciation: "/ˈmɑːrdʒɪnəlaɪz/",
    exampleSentence: "The policy marginalises small businesses.",
    exampleTranslationJa: "その政策は小規模事業者をわきに追いやる。",
    collocations: ["marginalised groups", "feel marginalised"],
    wordFormation: "margin(へり)+ -alise。",
    mnemonic: "margin(欄外)に押しやること。米つづりは marginalize。",
    relatedWords: ["exclude", "sideline", "margin"],
  },
  {
    id: "mediate",
    word: "mediate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["仲裁する、間を取り持つ"],
    pronunciation: "/ˈmiːdieɪt/",
    exampleSentence: "The UN tried to mediate between the two sides.",
    exampleTranslationJa: "国連は両者の間を取り持とうとした。",
    collocations: ["mediate a dispute", "mediate between", "mediate talks"],
    wordFormation: "ラテン語 medius(中間)から。medium と同語根。",
    mnemonic: "medium(中間)と同語根。真ん中に立つ人が mediator。",
    relatedWords: ["negotiate", "arbitrate", "mediator"],
  },
  {
    id: "memorise",
    word: "memorise",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["暗記する"],
    pronunciation: "/ˈmeməraɪz/",
    exampleSentence: "He memorised the whole speech.",
    exampleTranslationJa: "彼はその演説を丸ごと暗記した。",
    collocations: ["memorise a poem", "memorise vocabulary", "memorise by heart"],
    wordFormation: "memory(記憶)+ -ise。",
    mnemonic: "米つづりは memorize。learn by heart とほぼ同じ。",
    relatedWords: ["learn", "remember", "memory"],
  },
  {
    id: "minimise",
    word: "minimise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["最小限にする", "過小評価する"],
    pronunciation: "/ˈmɪnɪmaɪz/",
    exampleSentence: "Wash your hands to minimise the risk.",
    exampleTranslationJa: "危険を最小限にするため手を洗ってください。",
    collocations: ["minimise the risk", "minimise costs", "minimise the damage"],
    wordFormation: "minimum(最小)+ -ise。",
    mnemonic: "maximise の反対。画面を「最小化する」のもこれ。",
    relatedWords: ["reduce", "maximise", "limit"],
  },
  {
    id: "narrate",
    word: "narrate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["語る、ナレーションをつける"],
    pronunciation: "/ˈnæreɪt/",
    exampleSentence: "A famous actor narrates the documentary.",
    exampleTranslationJa: "有名な俳優がその記録映画のナレーションをしている。",
    collocations: ["narrate a story", "narrate a film"],
    mnemonic: "名詞は narrative(物語)/ narrator(語り手)。",
    relatedWords: ["tell", "recount", "narrator"],
  },
  {
    id: "navigate",
    word: "navigate",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["進路をとる、うまく進む", "(画面を)たどる"],
    pronunciation: "/ˈnævɪɡeɪt/",
    exampleSentence: "It is hard to navigate the benefits system.",
    exampleTranslationJa: "給付制度を渡っていくのは難しい。",
    collocations: ["navigate a ship", "navigate a website", "navigate the process"],
    wordFormation: "navis(船)+ agere(進める)。",
    mnemonic: "navy(海軍)と同語根。船の航行から、複雑な手続きを「渡る」比喩へ。",
    relatedWords: ["steer", "guide", "navigation"],
  },
  {
    id: "negate",
    word: "negate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["打ち消す、無効にする"],
    pronunciation: "/nɪˈɡeɪt/",
    exampleSentence: "The extra cost negates the savings.",
    exampleTranslationJa: "余分な費用が節約分を打ち消す。",
    collocations: ["negate the benefits", "negate the effect"],
    wordFormation: "ラテン語 negare(否定する)から。",
    mnemonic: "negative(否定の)と同語根。効果を帳消しにすること。",
    relatedWords: ["cancel", "nullify", "negative"],
  },
  {
    id: "normalise",
    word: "normalise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["正常化する", "(異常を)当たり前にする"],
    pronunciation: "/ˈnɔːrməlaɪz/",
    exampleSentence: "The two countries normalised relations in 1972.",
    exampleTranslationJa: "両国は1972年に国交を正常化した。",
    collocations: ["normalise relations", "normalise behaviour"],
    wordFormation: "normal(正常な)+ -ise。",
    mnemonic: "国交の正常化に加え、「よくないことを普通のことにしてしまう」批判にも使う。",
    relatedWords: ["standardise", "normal", "stabilise"],
  },
  {
    id: "nurture",
    word: "nurture",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["育てる、はぐくむ", "養育"],
    pronunciation: "/ˈnɜːrtʃər/",
    exampleSentence: "Good teachers nurture curiosity.",
    exampleTranslationJa: "よい教師は好奇心をはぐくむ。",
    collocations: ["nurture talent", "nature versus nurture", "nurture a relationship"],
    mnemonic: "nature versus nurture(生まれか育ちか)の対で覚える。",
    relatedWords: ["raise", "foster", "nourish"],
  },
  {
    id: "offset",
    word: "offset",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["相殺する", "埋め合わせ"],
    pronunciation: "/ˌɔːfˈset/",
    exampleSentence: "Higher sales offset the rising costs.",
    exampleTranslationJa: "売上増が費用増を相殺した。",
    collocations: ["offset the cost", "carbon offset", "offset losses"],
    mnemonic: "活用は offset-offset-offset。carbon offset(炭素の埋め合わせ)で頻出。",
    relatedWords: ["balance", "compensate", "counteract"],
  },
  {
    id: "omit",
    word: "omit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["省く、抜かす"],
    pronunciation: "/oʊˈmɪt/",
    exampleSentence: "He omitted his last job from the form.",
    exampleTranslationJa: "彼は用紙から前職を省いた。",
    collocations: ["omit a detail", "omit to mention", "be omitted from"],
    wordFormation: "ob-(向かって)+ mittere(送る)。",
    mnemonic: "mission・emit と同語根。名詞は omission。t を重ねて omitted。",
    relatedWords: ["leave out", "exclude", "omission"],
  },
  {
    id: "optimise",
    word: "optimise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["最適化する"],
    pronunciation: "/ˈɑːptɪmaɪz/",
    exampleSentence: "The site is optimised for mobile phones.",
    exampleTranslationJa: "そのサイトは携帯電話向けに最適化されている。",
    collocations: ["optimise performance", "optimise for search", "optimise resources"],
    wordFormation: "optimum(最適)+ -ise。",
    mnemonic: "米つづりは optimize。「一番よい状態にする」。",
    relatedWords: ["improve", "maximise", "efficiency"],
  },
  {
    id: "orchestrate",
    word: "orchestrate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(周到に)仕組む、まとめ上げる"],
    pronunciation: "/ˈɔːrkɪstreɪt/",
    exampleSentence: "Someone orchestrated the whole campaign.",
    exampleTranslationJa: "誰かがその運動全体を仕組んだ。",
    collocations: ["orchestrate a campaign", "carefully orchestrated"],
    wordFormation: "orchestra(管弦楽団)+ -ate。",
    mnemonic: "指揮者が楽団をまとめるように、裏で全体を組み立てること。",
    relatedWords: ["arrange", "coordinate", "stage"],
  },
  {
    id: "outweigh",
    word: "outweigh",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜に勝る、上回る"],
    pronunciation: "/ˌaʊtˈweɪ/",
    exampleSentence: "The benefits outweigh the risks.",
    exampleTranslationJa: "利点は危険を上回る。",
    collocations: ["outweigh the risks", "far outweigh", "the advantages outweigh"],
    wordFormation: "out-(勝って)+ weigh(重さがある)。",
    mnemonic: "はかりにかけて重いほう。議論の締めでよく使う型。",
    relatedWords: ["exceed", "surpass", "weigh"],
  },
  {
    id: "overlap",
    word: "overlap",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["部分的に重なる", "重なり"],
    pronunciation: "/ˌoʊvərˈlæp/",
    exampleSentence: "Our roles overlap in several areas.",
    exampleTranslationJa: "私たちの役割はいくつかの点で重なっている。",
    collocations: ["overlap with", "a significant overlap", "overlapping duties"],
    wordFormation: "over(上に)+ lap(重ねる)。",
    mnemonic: "完全に同じではなく「一部が重なる」。名詞はアクセントが前。",
    relatedWords: ["coincide", "intersect", "duplicate"],
  },
  {
    id: "penetrate",
    word: "penetrate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["貫く、入り込む", "(市場に)食い込む"],
    pronunciation: "/ˈpenətreɪt/",
    exampleSentence: "Light cannot penetrate the thick canopy.",
    exampleTranslationJa: "光はその厚い樹冠を貫けない。",
    collocations: ["penetrate the market", "penetrate deeply", "penetrate the surface"],
    mnemonic: "物理的に貫くのと、市場や組織に入り込むのが同じ語。",
    relatedWords: ["pierce", "enter", "infiltrate"],
  },
  {
    id: "permeate",
    word: "permeate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["しみ渡る、行き渡る"],
    pronunciation: "/ˈpɜːrmieɪt/",
    exampleSentence: "A sense of unease permeated the whole office.",
    exampleTranslationJa: "不安な空気が事務所全体にしみ渡っていた。",
    collocations: ["permeate the culture", "permeate through", "permeate every level"],
    wordFormation: "per-(通って)+ meare(進む)。",
    mnemonic: "水がしみ通るように、においや空気や考えが全体に広がる。",
    relatedWords: ["spread", "pervade", "soak"],
  },
  {
    id: "pertain",
    word: "pertain",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(pertain to で)関係する、当てはまる"],
    pronunciation: "/pərˈteɪn/",
    exampleSentence: "This rule pertains only to full-time staff.",
    exampleTranslationJa: "この規則は常勤職員にのみ当てはまる。",
    collocations: ["pertain to", "matters pertaining to"],
    wordFormation: "per-(通して)+ tenere(保つ)。",
    mnemonic: "かたい語で、契約書や法文でよく出る。relate to と同じ意味。",
    relatedWords: ["relate", "apply", "concern"],
  },
  {
    id: "pinpoint",
    word: "pinpoint",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["正確に突き止める"],
    pronunciation: "/ˈpɪnpɔɪnt/",
    exampleSentence: "Engineers could not pinpoint the fault.",
    exampleTranslationJa: "技術者たちはその不具合を特定できなかった。",
    collocations: ["pinpoint the cause", "pinpoint the location", "pinpoint accuracy"],
    wordFormation: "pin(ピン)+ point(先)。",
    mnemonic: "ピンの先ほど狭い範囲に絞り込むこと。",
    relatedWords: ["identify", "locate", "specify"],
  },
  {
    id: "populate",
    word: "populate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(場所に)住む", "(データを)入れる"],
    pronunciation: "/ˈpɑːpjuleɪt/",
    exampleSentence: "Farmers populate the northern valleys.",
    exampleTranslationJa: "北の谷には農家が住んでいる。",
    collocations: ["densely populated", "populate a database", "sparsely populated"],
    wordFormation: "population(人口)と同語根。",
    mnemonic: "densely / sparsely populated(人口が密／まばら)の形で頻出。",
    relatedWords: ["inhabit", "occupy", "population"],
  },
  {
    id: "prioritise",
    word: "prioritise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["優先順位をつける、優先する"],
    pronunciation: "/praɪˈɔːrɪtaɪz/",
    exampleSentence: "We must prioritise safety over speed.",
    exampleTranslationJa: "速さより安全を優先しなければならない。",
    collocations: ["prioritise tasks", "prioritise A over B"],
    wordFormation: "priority(優先)+ -ise。",
    mnemonic: "米つづりは prioritize。prioritise A over B の形。",
    relatedWords: ["rank", "priority", "emphasise"],
  },
  {
    id: "procure",
    word: "procure",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(苦労して)手に入れる、調達する"],
    pronunciation: "/prəˈkjʊr/",
    exampleSentence: "They procured the parts from overseas.",
    exampleTranslationJa: "彼らは部品を海外から調達した。",
    collocations: ["procure supplies", "procure funding", "difficult to procure"],
    wordFormation: "pro-(前に)+ curare(世話する)。",
    mnemonic: "官公庁の「調達」の意味で使うことが多い。名詞は procurement。",
    relatedWords: ["obtain", "acquire", "supply"],
  },
  {
    id: "prolong",
    word: "prolong",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["長引かせる、延長する"],
    pronunciation: "/prəˈlɔːŋ/",
    exampleSentence: "The treatment can prolong life by years.",
    exampleTranslationJa: "その治療は寿命を数年延ばしうる。",
    collocations: ["prolong the agony", "prolong life", "prolonged exposure"],
    wordFormation: "pro-(前へ)+ long(長い)。",
    mnemonic: "形容詞 prolonged(長引く)のほうがよく使う。",
    relatedWords: ["extend", "lengthen", "shorten"],
  },
  {
    id: "propel",
    word: "propel",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["推し進める、駆り立てる"],
    pronunciation: "/prəˈpel/",
    exampleSentence: "Rising demand propels the price upward.",
    exampleTranslationJa: "需要の高まりが価格を押し上げる。",
    collocations: ["propel forward", "propel someone to fame", "jet-propelled"],
    wordFormation: "pro-(前へ)+ pellere(押す)。",
    mnemonic: "expel・compel と同語根。名詞 propeller は「押し進めるもの」。",
    relatedWords: ["push", "drive", "thrust"],
  },
  {
    id: "quench",
    word: "quench",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(渇きを)いやす", "(火を)消す"],
    pronunciation: "/kwentʃ/",
    exampleSentence: "Water is the only thing that quenches thirst properly.",
    exampleTranslationJa: "渇きをきちんといやすのは水だけだ。",
    collocations: ["quench your thirst", "quench a fire"],
    mnemonic: "quench your thirst(渇きをいやす)がほぼ決まり文句。",
    relatedWords: ["satisfy", "extinguish", "thirst"],
  },
  {
    id: "radiate",
    word: "radiate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["放射する", "(感情を)発散する"],
    pronunciation: "/ˈreɪdieɪt/",
    exampleSentence: "The stove radiates heat for hours.",
    exampleTranslationJa: "そのストーブは何時間も熱を放射する。",
    collocations: ["radiate heat", "radiate confidence", "radiate outwards"],
    wordFormation: "ラテン語 radius(光線)から。",
    mnemonic: "radius・radio と同語根。中心から四方へ出ること。",
    relatedWords: ["emit", "radiation", "spread"],
  },
  {
    id: "reap",
    word: "reap",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(作物を)刈り取る", "(成果を)得る"],
    pronunciation: "/riːp/",
    exampleSentence: "You reap what you sow.",
    exampleTranslationJa: "まいた種は自分で刈り取ることになる。",
    collocations: ["reap the benefits", "reap a reward", "reap what you sow"],
    mnemonic: "reap the benefits(恩恵を得る)の形が実用的。sow(まく)と対。",
    relatedWords: ["harvest", "gain", "sow"],
  },
  {
    id: "reclaim",
    word: "reclaim",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["取り戻す", "(土地を)埋め立てる"],
    pronunciation: "/rɪˈkleɪm/",
    exampleSentence: "You can reclaim the tax on business travel.",
    exampleTranslationJa: "出張分の税は還付を受けられる。",
    collocations: ["reclaim tax", "reclaim land", "reclaim your luggage"],
    wordFormation: "re-(再び)+ claim(要求する)。",
    mnemonic: "返してもらう手続きにも、海を埋め立てて土地にすることにも使う。",
    relatedWords: ["recover", "regain", "claim"],
  },
  {
    id: "reconstruct",
    word: "reconstruct",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["再建する", "(事件を)再現する"],
    pronunciation: "/ˌriːkənˈstrʌkt/",
    exampleSentence: "Police reconstruct the crime step by step.",
    exampleTranslationJa: "警察は事件を一歩ずつ再現する。",
    collocations: ["reconstruct a building", "reconstruct the events"],
    wordFormation: "re-(再び)+ construct(組み立てる)。",
    mnemonic: "物を建て直すのと、出来事を組み立て直すのが同じ語。",
    relatedWords: ["rebuild", "restore", "construct"],
  },
  {
    id: "rectify",
    word: "rectify",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(誤りを)正す、是正する"],
    pronunciation: "/ˈrektɪfaɪ/",
    exampleSentence: "We will rectify the error immediately.",
    exampleTranslationJa: "その誤りはただちに是正します。",
    collocations: ["rectify a mistake", "rectify the situation"],
    wordFormation: "rectus(まっすぐな)+ -fy。correct と同語根。",
    mnemonic: "correct と同語根で「まっすぐにする」。かたい謝罪文の定番。",
    relatedWords: ["correct", "fix", "remedy"],
  },
  {
    id: "redeem",
    word: "redeem",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(点数などを)引き換える", "名誉を挽回する"],
    pronunciation: "/rɪˈdiːm/",
    exampleSentence: "You can redeem the points for a free coffee.",
    exampleTranslationJa: "そのポイントは無料のコーヒーと引き換えられます。",
    collocations: ["redeem points", "redeem yourself", "a redeeming feature"],
    wordFormation: "re-(再び)+ emere(買う)。",
    mnemonic: "「買い戻す」が原義。a redeeming feature は「救いになる点」。",
    relatedWords: ["exchange", "recover", "atone"],
  },
  {
    id: "refrain",
    word: "refrain",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["差し控える", "(歌の)繰り返し部分"],
    pronunciation: "/rɪˈfreɪn/",
    exampleSentence: "Please refrain from smoking here.",
    exampleTranslationJa: "ここでの喫煙はご遠慮ください。",
    collocations: ["refrain from doing", "refrain from comment"],
    mnemonic: "refrain from -ing の形。掲示や機内放送で必ず出る。",
    relatedWords: ["abstain", "avoid", "chorus"],
  },
  {
    id: "rehabilitate",
    word: "rehabilitate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["社会復帰させる、機能を回復させる"],
    pronunciation: "/ˌriːhəˈbɪlɪteɪt/",
    exampleSentence: "The programme rehabilitates young offenders.",
    exampleTranslationJa: "その事業は少年犯罪者の社会復帰を支援する。",
    collocations: ["rehabilitate offenders", "rehabilitate a patient"],
    wordFormation: "re-(再び)+ habilis(適した)。ability と同語根。",
    mnemonic: "体の機能にも、社会での立場にも使う。名詞は rehabilitation。",
    relatedWords: ["restore", "recover", "reform"],
  },
  {
    id: "reinstate",
    word: "reinstate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(地位に)復帰させる、復活させる"],
    pronunciation: "/ˌriːɪnˈsteɪt/",
    exampleSentence: "The court ordered the company to reinstate her.",
    exampleTranslationJa: "裁判所は会社に彼女の復職を命じた。",
    collocations: ["reinstate an employee", "reinstate a rule"],
    wordFormation: "re-(再び)+ instate(地位に就ける)。",
    mnemonic: "解雇や廃止を取り消して、元の状態に戻すこと。",
    relatedWords: ["restore", "reappoint", "dismiss"],
  },
  {
    id: "reiterate",
    word: "reiterate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["繰り返して言う"],
    pronunciation: "/riˈɪtəreɪt/",
    exampleSentence: "She reiterated her earlier warning.",
    exampleTranslationJa: "彼女は先の警告を改めて述べた。",
    collocations: ["reiterate a point", "reiterate the message"],
    wordFormation: "re-(再び)+ iterare(繰り返す)。",
    mnemonic: "repeat のかたい語。声明文や会見でよく使う。",
    relatedWords: ["repeat", "restate", "emphasise"],
  },
  {
    id: "rejoice",
    word: "rejoice",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["大いに喜ぶ"],
    pronunciation: "/rɪˈdʒɔɪs/",
    exampleSentence: "The whole town rejoiced at the news.",
    exampleTranslationJa: "町中がその知らせを喜んだ。",
    collocations: ["rejoice at", "rejoice in", "cause to rejoice"],
    mnemonic: "joy(喜び)と同語根。文語的で、宗教や祝いの場面に多い。",
    relatedWords: ["celebrate", "joy", "delight"],
  },
  {
    id: "renounce",
    word: "renounce",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(権利・信条を)公に捨てる"],
    pronunciation: "/rɪˈnaʊns/",
    exampleSentence: "He renounced his claim to the throne.",
    exampleTranslationJa: "彼は王位への権利を放棄した。",
    collocations: ["renounce violence", "renounce a claim", "renounce citizenship"],
    wordFormation: "re-(反対に)+ nuntiare(告げる)。announce と同語根。",
    mnemonic: "announce と同語根で「公に言う」。公式に手放すこと。",
    relatedWords: ["give up", "abandon", "relinquish"],
  },
  {
    id: "reorganise",
    word: "reorganise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["再編する、組み直す"],
    pronunciation: "/riˈɔːrɡənaɪz/",
    exampleSentence: "The company plans to reorganise its sales teams.",
    exampleTranslationJa: "その会社は営業チームの再編を計画している。",
    collocations: ["reorganise the department", "completely reorganise"],
    wordFormation: "re-(再び)+ organise(組織する)。",
    mnemonic: "米つづりは reorganize。名詞は reorganisation。",
    relatedWords: ["restructure", "reform", "organise"],
  },
  {
    id: "repel",
    word: "repel",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["撃退する、はじく", "不快にさせる"],
    pronunciation: "/rɪˈpel/",
    exampleSentence: "The coating repels water.",
    exampleTranslationJa: "その塗膜は水をはじく。",
    collocations: ["repel water", "repel an attack", "insect repellent"],
    wordFormation: "re-(後ろへ)+ pellere(押す)。",
    mnemonic: "expel・propel と同語根。虫よけは insect repellent。",
    relatedWords: ["drive back", "resist", "attract"],
  },
  {
    id: "replicate",
    word: "replicate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["再現する、複製する"],
    pronunciation: "/ˈreplɪkeɪt/",
    exampleSentence: "Other teams could not replicate the result.",
    exampleTranslationJa: "他のチームはその結果を再現できなかった。",
    collocations: ["replicate a study", "replicate the results", "replicate itself"],
    mnemonic: "科学で「同じ条件でやり直して同じ結果が出るか」の意味で重要。",
    relatedWords: ["reproduce", "copy", "duplicate"],
  },
  {
    id: "restrain",
    word: "restrain",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["抑える、取り押さえる"],
    pronunciation: "/rɪˈstreɪn/",
    exampleSentence: "He could hardly restrain his anger.",
    exampleTranslationJa: "彼は怒りをほとんど抑えられなかった。",
    collocations: ["restrain yourself", "restrain a suspect", "restrain spending"],
    wordFormation: "re-(後ろへ)+ stringere(締める)。",
    mnemonic: "strain(張る)と同語根。名詞は restraint(自制・拘束)。",
    relatedWords: ["hold back", "control", "restraint"],
  },
  {
    id: "revoke",
    word: "revoke",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(免許などを)取り消す"],
    pronunciation: "/rɪˈvoʊk/",
    exampleSentence: "His licence was revoked for a year.",
    exampleTranslationJa: "彼の免許は1年間取り消された。",
    collocations: ["revoke a licence", "revoke permission", "revoke an order"],
    wordFormation: "re-(戻して)+ vocare(呼ぶ)。voice と同語根。",
    mnemonic: "「呼び戻す」が原義。一度与えた許可を取り上げること。",
    relatedWords: ["cancel", "withdraw", "annul"],
  },
  {
    id: "safeguard",
    word: "safeguard",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["守る", "安全策"],
    pronunciation: "/ˈseɪfɡɑːrd/",
    exampleSentence: "New rules safeguard the rights of tenants.",
    exampleTranslationJa: "新しい規則は借り手の権利を守る。",
    collocations: ["safeguard against", "safeguard the interests of", "put safeguards in place"],
    wordFormation: "safe(安全)+ guard(守る)。",
    mnemonic: "名詞では「万一に備えた仕組み」。put safeguards in place の形。",
    relatedWords: ["protect", "secure", "guard"],
  },
  {
    id: "scatter",
    word: "scatter",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["まき散らす、散らばる"],
    pronunciation: "/ˈskætər/",
    exampleSentence: "Papers scatter across the desk in the wind.",
    exampleTranslationJa: "風で紙が机じゅうに散らばる。",
    collocations: ["scatter seeds", "scattered showers", "scatter in all directions"],
    mnemonic: "天気予報の scattered showers は「所により雨」。",
    relatedWords: ["disperse", "spread", "strew"],
  },
  {
    id: "soothe",
    word: "soothe",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["なだめる、和らげる"],
    pronunciation: "/suːð/",
    exampleSentence: "A warm bath soothes tired muscles.",
    exampleTranslationJa: "温かい風呂は疲れた筋肉を和らげる。",
    collocations: ["soothe a baby", "soothe the pain", "a soothing voice"],
    mnemonic: "th は /ð/。人の気持ちにも、体の痛みにも使う。",
    relatedWords: ["calm", "relieve", "comfort"],
  },
  {
    id: "sprout",
    word: "sprout",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["芽を出す", "芽、もやし"],
    pronunciation: "/spraʊt/",
    exampleSentence: "Seeds sprout within a week in warm soil.",
    exampleTranslationJa: "暖かい土では種は1週間で芽を出す。",
    collocations: ["sprout leaves", "bean sprouts", "Brussels sprouts"],
    mnemonic: "急に数が増えることにも使う。豆もやしは bean sprouts。",
    relatedWords: ["germinate", "grow", "bud"],
  },
  {
    id: "stabilise",
    word: "stabilise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["安定させる、安定する"],
    pronunciation: "/ˈsteɪbəlaɪz/",
    exampleSentence: "Prices stabilised after the summer.",
    exampleTranslationJa: "価格は夏のあと安定した。",
    collocations: ["stabilise the economy", "stabilise a patient", "prices stabilise"],
    wordFormation: "stable(安定した)+ -ise。",
    mnemonic: "米つづりは stabilize。医療では「容体を安定させる」。",
    relatedWords: ["steady", "balance", "stable"],
  },
  {
    id: "subscribe",
    word: "subscribe",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["定期購読する、加入する", "(subscribe to で)賛同する"],
    pronunciation: "/səbˈskraɪb/",
    exampleSentence: "I subscribe to two weekly magazines.",
    exampleTranslationJa: "私は週刊誌を2誌購読している。",
    collocations: ["subscribe to a magazine", "subscribe to a view", "a subscription service"],
    wordFormation: "sub-(下に)+ scribere(書く)。",
    mnemonic: "書類の下に署名することが原義。subscribe to a view は「その考えに賛成する」。",
    relatedWords: ["subscription", "join", "agree"],
  },
  {
    id: "suffice",
    word: "suffice",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["足りる、事足りる"],
    pronunciation: "/səˈfaɪs/",
    exampleSentence: "A short note will suffice.",
    exampleTranslationJa: "短いメモで足ります。",
    collocations: ["suffice to say", "that will suffice"],
    mnemonic: "Suffice it to say that ... は「〜とだけ言っておこう」という定型。",
    relatedWords: ["be enough", "satisfy", "sufficient"],
  },
  {
    id: "surpass",
    word: "surpass",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["上回る、しのぐ"],
    pronunciation: "/sərˈpæs/",
    exampleSentence: "Sales surpassed all expectations.",
    exampleTranslationJa: "売上はすべての予想を上回った。",
    collocations: ["surpass expectations", "surpass a record", "surpass yourself"],
    wordFormation: "sur-(超えて)+ pass(通る)。",
    mnemonic: "exceed とほぼ同じだが、「他より優れる」含みが強い。",
    relatedWords: ["exceed", "outdo", "outweigh"],
  },
  {
    id: "swap",
    word: "swap",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["交換する", "交換"],
    pronunciation: "/swɑːp/",
    exampleSentence: "Shall we swap seats?",
    exampleTranslationJa: "席を替わりましょうか。",
    collocations: ["swap places", "swap stories", "a swap shop"],
    mnemonic: "exchange のくだけた言い方。p を重ねて swapped。",
    relatedWords: ["exchange", "trade", "switch"],
  },
  {
    id: "sway",
    word: "sway",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["揺れる", "(意見を)動かす", "支配力"],
    pronunciation: "/sweɪ/",
    exampleSentence: "The trees sway in the evening wind.",
    exampleTranslationJa: "木々が夕方の風に揺れる。",
    collocations: ["sway gently", "sway public opinion", "hold sway over"],
    mnemonic: "物の揺れから、人の考えを「動かす」意味へ。hold sway は「支配する」。",
    relatedWords: ["swing", "influence", "rock"],
  },
  {
    id: "symbolise",
    word: "symbolise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["象徴する"],
    pronunciation: "/ˈsɪmbəlaɪz/",
    exampleSentence: "The dove symbolises peace.",
    exampleTranslationJa: "ハトは平和を象徴する。",
    collocations: ["symbolise hope", "symbolise the struggle"],
    wordFormation: "symbol(象徴)+ -ise。",
    mnemonic: "米つづりは symbolize。A symbolises B の形。",
    relatedWords: ["represent", "stand for", "symbol"],
  },
  {
    id: "sympathise",
    word: "sympathise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["同情する、共感する"],
    pronunciation: "/ˈsɪmpəθaɪz/",
    exampleSentence: "I sympathise with your position.",
    exampleTranslationJa: "あなたの立場には同情します。",
    collocations: ["sympathise with", "deeply sympathise"],
    wordFormation: "sym-(共に)+ pathos(感情)。",
    mnemonic: "米つづりは sympathize。sympathise with ... の形で使う。",
    relatedWords: ["empathise", "understand", "sympathy"],
  },
  {
    id: "synthesise",
    word: "synthesise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["合成する", "(情報を)統合する"],
    pronunciation: "/ˈsɪnθəsaɪz/",
    exampleSentence: "The body cannot synthesise this vitamin.",
    exampleTranslationJa: "人体はこのビタミンを合成できない。",
    collocations: ["synthesise a compound", "synthesise information"],
    wordFormation: "syn-(共に)+ thesis(置くこと)。",
    mnemonic: "化学の合成にも、複数の情報を一つにまとめることにも使う。",
    relatedWords: ["combine", "produce", "synthesis"],
  },
  {
    id: "tally",
    word: "tally",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["集計する", "(数字が)一致する", "集計"],
    pronunciation: "/ˈtæli/",
    exampleSentence: "The two accounts do not tally.",
    exampleTranslationJa: "その二つの説明は食い違っている。",
    collocations: ["tally the votes", "the figures tally", "keep a tally"],
    mnemonic: "数字が「合う」意味が重要。keep a tally は「数を記録しておく」。",
    relatedWords: ["count", "match", "total"],
  },
  {
    id: "uncover",
    word: "uncover",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["明らかにする、暴く"],
    pronunciation: "/ʌnˈkʌvər/",
    exampleSentence: "Auditors uncovered serious errors.",
    exampleTranslationJa: "監査人が重大な誤りを見つけ出した。",
    collocations: ["uncover the truth", "uncover evidence", "uncover a plot"],
    wordFormation: "un-(取り去る)+ cover(覆い)。",
    mnemonic: "覆いを取ること。discover よりも「隠されていた」含みが強い。",
    relatedWords: ["reveal", "expose", "discover"],
  },
  {
    id: "underline",
    word: "underline",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["下線を引く", "強調する"],
    pronunciation: "/ˌʌndərˈlaɪn/",
    exampleSentence: "The report underlines the need for reform.",
    exampleTranslationJa: "その報告書は改革の必要を強調している。",
    collocations: ["underline a word", "underline the importance"],
    wordFormation: "under(下に)+ line(線)。",
    mnemonic: "線を引くことから「際立たせる」へ。underscore とほぼ同じ。",
    relatedWords: ["highlight", "emphasise", "stress"],
  },
  {
    id: "underpin",
    word: "underpin",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["下支えする、根拠となる"],
    pronunciation: "/ˌʌndərˈpɪn/",
    exampleSentence: "These figures underpin the whole argument.",
    exampleTranslationJa: "これらの数字が議論全体を支えている。",
    collocations: ["underpin an argument", "underpin the economy"],
    wordFormation: "under(下)+ pin(支柱)。",
    mnemonic: "建物を下から支える工法が原義。論の土台になること。",
    relatedWords: ["support", "sustain", "base"],
  },
  {
    id: "utilise",
    word: "utilise",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["活用する"],
    pronunciation: "/ˈjuːtəlaɪz/",
    exampleSentence: "The centre utilises rainwater for the garden.",
    exampleTranslationJa: "その施設は庭に雨水を活用している。",
    collocations: ["utilise resources", "fully utilise", "utilise space"],
    wordFormation: "utility(有用性)+ -ise。",
    mnemonic: "米つづりは utilize。use のかたい語で、書き言葉向き。",
    relatedWords: ["use", "employ", "exploit"],
  },
  {
    id: "validate",
    word: "validate",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["正当性を確かめる、有効にする"],
    pronunciation: "/ˈvælɪdeɪt/",
    exampleSentence: "The results validate the earlier theory.",
    exampleTranslationJa: "その結果は先の理論を裏づける。",
    collocations: ["validate a theory", "validate a ticket", "validate feelings"],
    wordFormation: "valid(有効な)+ -ate。",
    mnemonic: "切符に「有効の刻印を押す」意味もある。反対は invalidate。",
    relatedWords: ["confirm", "verify", "valid"],
  },
  {
    id: "withstand",
    word: "withstand",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["耐える、持ちこたえる"],
    pronunciation: "/wɪðˈstænd/",
    exampleSentence: "The bridge can withstand a strong earthquake.",
    exampleTranslationJa: "その橋は強い地震に耐えられる。",
    collocations: ["withstand pressure", "withstand the heat", "withstand scrutiny"],
    wordFormation: "with-(に対して)+ stand(立つ)。",
    mnemonic: "活用は withstand-withstood-withstood。「対して立ち続ける」。",
    relatedWords: ["resist", "endure", "survive"],
  },
  {
    id: "bystander",
    word: "bystander",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["居合わせた人、傍観者"],
    pronunciation: "/ˈbaɪstændər/",
    exampleSentence: "An innocent bystander was hurt in the crash.",
    exampleTranslationJa: "その衝突事故で無関係の通行人がけがをした。",
    collocations: ["an innocent bystander", "the bystander effect"],
    wordFormation: "by(そばに)+ stander(立つ人)。",
    mnemonic: "the bystander effect は「大勢いると誰も助けない」心理。",
    relatedWords: ["onlooker", "witness", "spectator"],
  },
  {
    id: "eyewitness",
    word: "eyewitness",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["目撃者"],
    pronunciation: "/ˈaɪwɪtnəs/",
    exampleSentence: "Two eyewitnesses gave the same account.",
    exampleTranslationJa: "2人の目撃者が同じ証言をした。",
    collocations: ["an eyewitness account", "call an eyewitness"],
    wordFormation: "eye(目)+ witness(証人)。",
    mnemonic: "自分の目で見た証人。an eyewitness account は「目撃証言」。",
    relatedWords: ["witness", "observer", "testimony"],
  },
  {
    id: "newcomer",
    word: "newcomer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["新参者、新しく来た人"],
    pronunciation: "/ˈnuːkʌmər/",
    exampleSentence: "The club welcomes newcomers every autumn.",
    exampleTranslationJa: "そのクラブは毎秋、新入りを迎える。",
    collocations: ["a newcomer to", "welcome newcomers", "a relative newcomer"],
    wordFormation: "new(新しい)+ comer(来る人)。",
    mnemonic: "a newcomer to ... の形で「〜の分野に入って日が浅い人」。",
    relatedWords: ["beginner", "novice", "veteran"],
  },
  {
    id: "breadwinner",
    word: "breadwinner",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["一家の稼ぎ手"],
    pronunciation: "/ˈbredwɪnər/",
    exampleSentence: "She became the family's only breadwinner.",
    exampleTranslationJa: "彼女は一家で唯一の稼ぎ手になった。",
    collocations: ["the main breadwinner", "the sole breadwinner"],
    wordFormation: "bread(パン)+ winner(得る人)。",
    mnemonic: "パン(bread)を得てくる人。「大黒柱」に当たる語。",
    relatedWords: ["earner", "provider", "income"],
  },
  {
    id: "caretaker",
    word: "caretaker",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["管理人", "(caretaker government で)暫定政権"],
    pronunciation: "/ˈkerteɪkər/",
    exampleSentence: "The caretaker locks the building at ten.",
    exampleTranslationJa: "管理人は10時に建物を施錠する。",
    collocations: ["a school caretaker", "a caretaker government"],
    wordFormation: "care(世話)+ taker(する人)。",
    mnemonic: "建物の管理人。政治では「次が決まるまでの暫定の」。",
    relatedWords: ["janitor", "custodian", "warden"],
  },
  {
    id: "babysitter",
    word: "babysitter",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ベビーシッター、子守"],
    pronunciation: "/ˈbeɪbisɪtər/",
    exampleSentence: "We need a babysitter for Friday night.",
    exampleTranslationJa: "金曜の夜に子守が必要だ。",
    collocations: ["find a babysitter", "hire a babysitter"],
    wordFormation: "baby(赤ん坊)+ sitter(そばにいる人)。",
    mnemonic: "動詞は babysit(活用は babysat)。",
    relatedWords: ["nanny", "childminder", "sitter"],
  },
  {
    id: "apprentice",
    word: "apprentice",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["見習い、徒弟"],
    pronunciation: "/əˈprentɪs/",
    exampleSentence: "He started as an apprentice at sixteen.",
    exampleTranslationJa: "彼は16歳で見習いとして始めた。",
    collocations: ["an apprentice electrician", "take on an apprentice"],
    wordFormation: "ラテン語 apprehendere(つかむ)から。",
    mnemonic: "働きながら技を「つかむ」人。制度は apprenticeship。",
    relatedWords: ["trainee", "learner", "apprenticeship"],
  },
  {
    id: "trainee",
    word: "trainee",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["研修生"],
    pronunciation: "/ˌtreɪˈniː/",
    exampleSentence: "Trainees spend two weeks in each department.",
    exampleTranslationJa: "研修生は各部署に2週間ずつ入る。",
    collocations: ["a graduate trainee", "a trainee teacher"],
    wordFormation: "train(訓練する)+ -ee(される側)。",
    mnemonic: "-ee は「される側」。訓練する側は trainer。",
    relatedWords: ["intern", "apprentice", "trainer"],
  },
  {
    id: "intern",
    word: "intern",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["インターン、研修生"],
    pronunciation: "/ˈɪntɜːrn/",
    exampleSentence: "The office takes three interns each summer.",
    exampleTranslationJa: "その事務所は毎夏3人のインターンを受け入れる。",
    collocations: ["a summer intern", "hire an intern", "an unpaid intern"],
    mnemonic: "名詞は前にアクセント。医学では「研修医」。制度は internship。",
    relatedWords: ["trainee", "internship", "student"],
  },
  {
    id: "negotiator",
    word: "negotiator",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["交渉担当者"],
    pronunciation: "/nɪˈɡoʊʃieɪtər/",
    exampleSentence: "A senior negotiator flew in overnight.",
    exampleTranslationJa: "上級の交渉担当者が夜のうちに飛んできた。",
    collocations: ["a skilled negotiator", "the chief negotiator"],
    wordFormation: "negotiate(交渉する)+ -or。",
    mnemonic: "交渉の場に立つ人。名詞は negotiation。",
    relatedWords: ["negotiate", "mediator", "diplomat"],
  },
  {
    id: "mediator",
    word: "mediator",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["仲介者、調停者"],
    pronunciation: "/ˈmiːdieɪtər/",
    exampleSentence: "An outside mediator was brought in.",
    exampleTranslationJa: "外部の調停者が招かれた。",
    collocations: ["act as a mediator", "an independent mediator"],
    wordFormation: "mediate(仲裁する)+ -or。",
    mnemonic: "真ん中(medi-)に立つ人。判断を下すのは arbitrator。",
    relatedWords: ["mediate", "arbitrator", "go-between"],
  },
  {
    id: "auditor",
    word: "auditor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["会計監査人"],
    pronunciation: "/ˈɔːdɪtər/",
    exampleSentence: "The auditors found no irregularities.",
    exampleTranslationJa: "監査人は不正を見つけなかった。",
    collocations: ["an external auditor", "the auditors report"],
    wordFormation: "ラテン語 audire(聞く)から。もとは口頭で会計を聞く人。",
    mnemonic: "audio・audience と同語根。もとは帳簿を「聞いて」検めた人。",
    relatedWords: ["audit", "accountant", "inspector"],
  },
  {
    id: "technician",
    word: "technician",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["技術者、技師"],
    pronunciation: "/tekˈnɪʃn/",
    exampleSentence: "A technician will come to fix the line.",
    exampleTranslationJa: "技術者が回線を直しに来ます。",
    collocations: ["a laboratory technician", "a service technician"],
    wordFormation: "technic(技術)+ -ian(人)。",
    mnemonic: "engineer が設計側、technician は現場で手を動かす側。",
    relatedWords: ["engineer", "specialist", "mechanic"],
  },
  {
    id: "plumber",
    word: "plumber",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["配管工"],
    pronunciation: "/ˈplʌmər/",
    exampleSentence: "We called a plumber about the leaking pipe.",
    exampleTranslationJa: "漏れている配管のことで配管工を呼んだ。",
    collocations: ["call a plumber", "a qualified plumber"],
    wordFormation: "ラテン語 plumbum(鉛)から。昔の管は鉛製。",
    mnemonic: "b は読まない /ˈplʌmər/。鉛(plumbum)の管を扱う人が語源。",
    relatedWords: ["pipe", "leak", "electrician"],
  },
  {
    id: "electrician",
    word: "electrician",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["電気技師、電気工"],
    pronunciation: "/ɪˌlekˈtrɪʃn/",
    exampleSentence: "An electrician rewired the whole flat.",
    exampleTranslationJa: "電気工が部屋全体を配線し直した。",
    collocations: ["a qualified electrician", "call an electrician"],
    wordFormation: "electric(電気の)+ -ian(人)。",
    mnemonic: "アクセントは -tri- の次 /ɪˌlekˈtrɪʃn/。",
    relatedWords: ["electric", "plumber", "wiring"],
  },
  {
    id: "carpenter",
    word: "carpenter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["大工"],
    pronunciation: "/ˈkɑːrpəntər/",
    exampleSentence: "A carpenter built the shelves by hand.",
    exampleTranslationJa: "大工がその棚を手作りした。",
    collocations: ["a skilled carpenter", "work as a carpenter"],
    mnemonic: "木を扱う職人。仕事は carpentry。",
    relatedWords: ["builder", "joiner", "wood"],
  },
  {
    id: "butcher",
    word: "butcher",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["肉屋"],
    pronunciation: "/ˈbʊtʃər/",
    exampleSentence: "The butcher on the corner sells local beef.",
    exampleTranslationJa: "角の肉屋は地元の牛肉を売っている。",
    collocations: ["the local butcher", "a butcher's shop"],
    mnemonic: "店を指すときは the butcher's と所有格で言う。",
    relatedWords: ["baker", "meat", "shop"],
  },
  {
    id: "baker",
    word: "baker",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パン職人、パン屋"],
    pronunciation: "/ˈbeɪkər/",
    exampleSentence: "The baker starts work at four in the morning.",
    exampleTranslationJa: "そのパン職人は朝4時に仕事を始める。",
    collocations: ["the local baker", "a baker's dozen"],
    wordFormation: "bake(焼く)+ -er。",
    mnemonic: "a baker's dozen は13個。昔おまけを1つ足した習慣から。",
    relatedWords: ["bakery", "bread", "butcher"],
  },
  {
    id: "tailor",
    word: "tailor",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["仕立屋", "(要望に)合わせて作る"],
    pronunciation: "/ˈteɪlər/",
    exampleSentence: "The course is tailored to each student.",
    exampleTranslationJa: "その講座は学生一人ひとりに合わせて作られている。",
    collocations: ["tailor to your needs", "a tailored suit", "a tailor-made solution"],
    mnemonic: "動詞の「合わせて作る」が実務で頻出。tailor-made(あつらえの)。",
    relatedWords: ["custom", "adapt", "suit"],
  },
  {
    id: "hairdresser",
    word: "hairdresser",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["美容師、理髪師"],
    pronunciation: "/ˈherdresər/",
    exampleSentence: "I have an appointment at the hairdresser's.",
    exampleTranslationJa: "美容院の予約がある。",
    collocations: ["go to the hairdresser's", "a hairdresser's salon"],
    wordFormation: "hair(髪)+ dresser(整える人)。",
    mnemonic: "店を指すときは the hairdresser's。男性向けの床屋は barber。",
    relatedWords: ["barber", "salon", "stylist"],
  },
  {
    id: "gardener",
    word: "gardener",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["庭師、園芸をする人"],
    pronunciation: "/ˈɡɑːrdnər/",
    exampleSentence: "A gardener comes once a fortnight.",
    exampleTranslationJa: "庭師が2週に一度来る。",
    collocations: ["a keen gardener", "employ a gardener"],
    wordFormation: "garden(庭)+ -er。",
    mnemonic: "職業にも、趣味で庭いじりをする人にも使う。",
    relatedWords: ["garden", "landscaper", "grower"],
  },
  {
    id: "farmer",
    word: "farmer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["農場主、農業をする人"],
    pronunciation: "/ˈfɑːrmər/",
    exampleSentence: "Farmers here grow mostly wheat.",
    exampleTranslationJa: "ここの農家はおもに小麦を育てている。",
    collocations: ["a dairy farmer", "local farmers", "a farmers' market"],
    wordFormation: "farm(農場)+ -er。",
    mnemonic: "a farmers' market(直売市)はアポストロフィの位置に注意。",
    relatedWords: ["farm", "agriculture", "grower"],
  },
  {
    id: "labourer",
    word: "labourer",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["肉体労働者"],
    pronunciation: "/ˈleɪbərər/",
    exampleSentence: "He worked as a labourer on building sites.",
    exampleTranslationJa: "彼は建設現場で肉体労働者として働いた。",
    collocations: ["a manual labourer", "a farm labourer"],
    wordFormation: "labour(労働)+ -er。",
    mnemonic: "米つづりは laborer。技能を要しない体力仕事の従事者。",
    relatedWords: ["worker", "labour", "manual"],
  },
]
