import type { VocabularyEntry } from '../types'

// 増補 第22弾。-ous / -able / -ful / -less の形容詞。
// 一字違いで意味が変わる対(ingenious と ingenuous、momentous と momentary、
// enviable と envious、tasteful と tasty)は覚えるヒントで区別する。
export const plus22: VocabularyEntry[] = [
  {
    id: "dangerous",
    word: "dangerous",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["危険な"],
    pronunciation: "/ˈdeɪndʒərəs/",
    exampleSentence: "Swimming here is dangerous at high tide.",
    exampleTranslationJa: "満潮時にここで泳ぐのは危険だ。",
    collocations: ["a dangerous situation", "potentially dangerous", "dangerous driving"],
    mnemonic: "danger(危険)+ -ous。危険を及ぼす側に使う。危険にさらされているのは in danger。",
    relatedWords: ["risky", "hazardous", "safe"],
  },
  {
    id: "famous",
    word: "famous",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有名な"],
    pronunciation: "/ˈfeɪməs/",
    exampleSentence: "The town is famous for its cheese.",
    exampleTranslationJa: "その町はチーズで有名だ。",
    collocations: ["famous for", "world-famous", "become famous"],
    mnemonic: "fame(名声)+ -ous。famous for(よいことで有名)、notorious for(悪いことで有名)。",
    relatedWords: ["well-known", "renowned", "obscure"],
  },
  {
    id: "deceptive",
    word: "deceptive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["人を惑わす、見かけによらない"],
    pronunciation: "/dɪˈseptɪv/",
    exampleSentence: "Appearances can be deceptive.",
    exampleTranslationJa: "見かけは当てにならないことがある。",
    collocations: ["appearances can be deceptive", "deceptive simplicity"],
    mnemonic: "deceive(だます)の形容詞形。だます意図がなくても「紛らわしい」に使う。",
    relatedWords: ["deceive", "misleading", "honest"],
  },
  {
    id: "ambiguous",
    word: "ambiguous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["あいまいな、二通りに取れる"],
    pronunciation: "/æmˈbɪɡjuəs/",
    exampleSentence: "The wording is deliberately ambiguous.",
    exampleTranslationJa: "その文言は意図的にあいまいだ。",
    collocations: ["deliberately ambiguous", "an ambiguous answer"],
    mnemonic: "ambi-(両方)。二通りに解釈できるのが ambiguous、ぼんやりが vague。",
    relatedWords: ["vague", "unclear", "clear"],
  },
  {
    id: "arduous",
    word: "arduous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["骨の折れる、困難な"],
    pronunciation: "/ˈɑːrdʒuəs/",
    exampleSentence: "It was an arduous climb to the summit.",
    exampleTranslationJa: "頂上までは骨の折れる登りだった。",
    collocations: ["an arduous task", "an arduous journey"],
    mnemonic: "ラテン語 arduus(険しい)から。長く続く重労働に使う。",
    relatedWords: ["difficult", "strenuous", "easy"],
  },
  {
    id: "atrocious",
    word: "atrocious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ひどい、極悪な"],
    pronunciation: "/əˈtroʊʃəs/",
    exampleSentence: "The weather was atrocious all week.",
    exampleTranslationJa: "天気は一週間ずっとひどかった。",
    collocations: ["atrocious weather", "atrocious conditions"],
    mnemonic: "atrocity(残虐行為)と同語根だが、日常では「ひどい」の強調。",
    relatedWords: ["appalling", "dreadful", "excellent"],
  },
  {
    id: "audacious",
    word: "audacious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["大胆不敵な、ずうずうしい"],
    pronunciation: "/ɔːˈdeɪʃəs/",
    exampleSentence: "It was an audacious plan that nearly worked.",
    exampleTranslationJa: "それは危うく成功しかけた大胆な計画だった。",
    collocations: ["an audacious plan", "an audacious attempt"],
    mnemonic: "audacity(大胆さ)の形容詞形。ほめ言葉にも非難にもなる。",
    relatedWords: ["bold", "daring", "timid"],
  },
  {
    id: "boisterous",
    word: "boisterous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["騒がしく元気な"],
    pronunciation: "/ˈbɔɪstərəs/",
    exampleSentence: "A boisterous crowd filled the square.",
    exampleTranslationJa: "にぎやかな群衆が広場を埋めた。",
    collocations: ["a boisterous crowd", "boisterous children"],
    mnemonic: "元気がありすぎてうるさい感じ。悪意はない。",
    relatedWords: ["rowdy", "lively", "quiet"],
  },
  {
    id: "ferocious",
    word: "ferocious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["どう猛な、激烈な"],
    pronunciation: "/fəˈroʊʃəs/",
    exampleSentence: "The dog gave a ferocious growl.",
    exampleTranslationJa: "その犬はどう猛にうなった。",
    collocations: ["a ferocious attack", "ferocious competition"],
    mnemonic: "ferocity(獰猛さ)の形容詞形。動物にも競争にも使う。",
    relatedWords: ["fierce", "savage", "gentle"],
  },
  {
    id: "frivolous",
    word: "frivolous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["軽薄な、ふまじめな", "(訴訟が)いいかげんな"],
    pronunciation: "/ˈfrɪvələs/",
    exampleSentence: "The court dismissed the claim as frivolous.",
    exampleTranslationJa: "裁判所はその請求を根拠のないものとして退けた。",
    collocations: ["a frivolous lawsuit", "frivolous spending"],
    mnemonic: "まじめに取り合う価値がない、という含み。serious の反対。",
    relatedWords: ["trivial", "silly", "serious"],
  },
  {
    id: "gracious",
    word: "gracious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["丁重な、寛大な"],
    pronunciation: "/ˈɡreɪʃəs/",
    exampleSentence: "She was gracious in defeat.",
    exampleTranslationJa: "彼女は負けても潔かった。",
    collocations: ["gracious in defeat", "a gracious host"],
    mnemonic: "grace(優美・恵み)の形容詞形。負けたときの態度をほめる語。",
    relatedWords: ["courteous", "generous", "rude"],
  },
  {
    id: "hideous",
    word: "hideous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ぞっとするほど醜い、ひどい"],
    pronunciation: "/ˈhɪdiəs/",
    exampleSentence: "They painted the room a hideous green.",
    exampleTranslationJa: "彼らはその部屋をぞっとするような緑に塗った。",
    collocations: ["a hideous mistake", "hideous colours"],
    mnemonic: "ugly より強い。見た目にも出来事にも使う。",
    relatedWords: ["ghastly", "repulsive", "beautiful"],
  },
  {
    id: "homogeneous",
    word: "homogeneous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["同質の、均一な"],
    pronunciation: "/ˌhoʊməˈdʒiːniəs/",
    exampleSentence: "The population is remarkably homogeneous.",
    exampleTranslationJa: "その人口は驚くほど同質的だ。",
    collocations: ["a homogeneous group", "homogeneous in composition"],
    mnemonic: "homo-(同じ)+ genos(種類)。反対は heterogeneous。",
    relatedWords: ["uniform", "similar", "heterogeneous"],
  },
  {
    id: "ingenious",
    word: "ingenious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["巧妙な、独創的な"],
    pronunciation: "/ɪnˈdʒiːniəs/",
    exampleSentence: "She found an ingenious way round the problem.",
    exampleTranslationJa: "彼女はその問題を巧妙に回避する方法を見つけた。",
    collocations: ["an ingenious solution", "an ingenious device"],
    mnemonic: "ingenuous(純朴な)と一字違いで意味が全く違う。engine と同語根。",
    relatedWords: ["clever", "inventive", "ingenuous"],
  },
  {
    id: "innocuous",
    word: "innocuous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["害のない、当たりさわりのない"],
    pronunciation: "/ɪˈnɑːkjuəs/",
    exampleSentence: "It seemed an innocuous question at the time.",
    exampleTranslationJa: "当時それは当たりさわりのない質問に思えた。",
    collocations: ["an innocuous remark", "apparently innocuous"],
    mnemonic: "in-(否定)+ nocuous(有害な)。noxious の反対。",
    relatedWords: ["harmless", "inoffensive", "harmful"],
  },
  {
    id: "laborious",
    word: "laborious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["骨の折れる、手間のかかる"],
    pronunciation: "/ləˈbɔːriəs/",
    exampleSentence: "Copying the records was laborious work.",
    exampleTranslationJa: "記録を書き写すのは手間のかかる仕事だった。",
    collocations: ["a laborious process", "laborious work"],
    mnemonic: "labour(労働)の形容詞形。arduous に近いが「単調で手間がかかる」寄り。",
    relatedWords: ["tedious", "arduous", "effortless"],
  },
  {
    id: "ludicrous",
    word: "ludicrous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ばかげた、笑止な"],
    pronunciation: "/ˈluːdɪkrəs/",
    exampleSentence: "The price is frankly ludicrous.",
    exampleTranslationJa: "その値段は率直に言ってばかげている。",
    collocations: ["a ludicrous idea", "frankly ludicrous"],
    mnemonic: "ludo(遊び)が語根。笑ってしまうほどばかげていること。",
    relatedWords: ["absurd", "ridiculous", "sensible"],
  },
  {
    id: "luminous",
    word: "luminous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["光る、明るい"],
    pronunciation: "/ˈluːmɪnəs/",
    exampleSentence: "The hands of the watch are luminous.",
    exampleTranslationJa: "その時計の針は暗い所で光る。",
    collocations: ["luminous paint", "a luminous glow"],
    mnemonic: "lumen(光)が語根。illuminate と同語根。",
    relatedWords: ["glowing", "bright", "dark"],
  },
  {
    id: "luxurious",
    word: "luxurious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ぜいたくな、豪華な"],
    pronunciation: "/lʌɡˈʒʊriəs/",
    exampleSentence: "They stayed in a luxurious hotel.",
    exampleTranslationJa: "彼らは豪華なホテルに泊まった。",
    collocations: ["a luxurious hotel", "luxurious fabric"],
    mnemonic: "luxury の形容詞形。luxuriant(生い茂った)とは別語。",
    relatedWords: ["lavish", "opulent", "modest"],
  },
  {
    id: "marvellous",
    word: "marvellous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すばらしい、驚くべき"],
    pronunciation: "/ˈmɑːrvələs/",
    exampleSentence: "She has a marvellous sense of humour.",
    exampleTranslationJa: "彼女はすばらしいユーモアの感覚を持っている。",
    collocations: ["a marvellous time", "absolutely marvellous"],
    mnemonic: "marvel(驚嘆)の形容詞形。米つづりは marvelous(l が一つ)。",
    relatedWords: ["wonderful", "splendid", "awful"],
  },
  {
    id: "miraculous",
    word: "miraculous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["奇跡的な"],
    pronunciation: "/mɪˈrækjələs/",
    exampleSentence: "He made a miraculous recovery.",
    exampleTranslationJa: "彼は奇跡的な回復を遂げた。",
    collocations: ["a miraculous escape", "a miraculous recovery"],
    mnemonic: "miracle の形容詞形。admire と同語根で「驚く」。",
    relatedWords: ["miracle", "amazing", "ordinary"],
  },
  {
    id: "mischievous",
    word: "mischievous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["いたずら好きな"],
    pronunciation: "/ˈmɪstʃɪvəs/",
    exampleSentence: "She gave a mischievous grin.",
    exampleTranslationJa: "彼女はいたずらっぽく笑った。",
    collocations: ["a mischievous smile", "a mischievous child"],
    mnemonic: "発音は3音節 /ˈmɪstʃɪvəs/。-vious と読まないのが要注意。",
    relatedWords: ["naughty", "playful", "obedient"],
  },
  {
    id: "momentous",
    word: "momentous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["重大な、歴史的な"],
    pronunciation: "/moʊˈmentəs/",
    exampleSentence: "It was a momentous decision for the country.",
    exampleTranslationJa: "それはその国にとって重大な決断だった。",
    collocations: ["a momentous occasion", "a momentous decision"],
    mnemonic: "momentary(一瞬の)とは全く別。こちらは「重みのある」。",
    relatedWords: ["significant", "historic", "trivial"],
  },
  {
    id: "monotonous",
    word: "monotonous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["単調な、退屈な"],
    pronunciation: "/məˈnɑːtənəs/",
    exampleSentence: "The work is well paid but monotonous.",
    exampleTranslationJa: "その仕事は給料はよいが単調だ。",
    collocations: ["a monotonous voice", "monotonous work"],
    mnemonic: "mono-(一つ)+ tone(調子)。同じ調子が続くこと。",
    relatedWords: ["tedious", "repetitive", "varied"],
  },
  {
    id: "mountainous",
    word: "mountainous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["山の多い", "山のような"],
    pronunciation: "/ˈmaʊntənəs/",
    exampleSentence: "The north of the country is mountainous.",
    exampleTranslationJa: "その国の北部は山が多い。",
    collocations: ["mountainous terrain", "mountainous debts"],
    mnemonic: "mountain の形容詞形。「山積みの」という比喩にも使う。",
    relatedWords: ["hilly", "rugged", "flat"],
  },
  {
    id: "noxious",
    word: "noxious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有毒な、有害な"],
    pronunciation: "/ˈnɑːkʃəs/",
    exampleSentence: "Noxious fumes filled the tunnel.",
    exampleTranslationJa: "有毒な煙がトンネルに充満した。",
    collocations: ["noxious fumes", "noxious gases"],
    mnemonic: "innocuous(無害な)の反対。obnoxious(不快な)と語根を共有する。",
    relatedWords: ["toxic", "harmful", "harmless"],
  },
  {
    id: "obnoxious",
    word: "obnoxious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["非常に不快な、鼻もちならない"],
    pronunciation: "/əbˈnɑːkʃəs/",
    exampleSentence: "His obnoxious behaviour cost him the job.",
    exampleTranslationJa: "彼の鼻もちならない振る舞いが職を失わせた。",
    collocations: ["obnoxious behaviour", "utterly obnoxious"],
    mnemonic: "noxious(有毒な)と同語根。人の態度について言う。",
    relatedWords: ["offensive", "rude", "pleasant"],
  },
  {
    id: "outrageous",
    word: "outrageous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["とんでもない、法外な"],
    pronunciation: "/aʊtˈreɪdʒəs/",
    exampleSentence: "The prices in that shop are outrageous.",
    exampleTranslationJa: "あの店の値段は法外だ。",
    collocations: ["outrageous prices", "an outrageous claim"],
    mnemonic: "outrage(激しい怒り)の形容詞形。怒りを買うほどひどいこと。",
    relatedWords: ["shocking", "scandalous", "reasonable"],
  },
  {
    id: "perilous",
    word: "perilous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["きわめて危険な"],
    pronunciation: "/ˈperələs/",
    exampleSentence: "They made a perilous journey across the desert.",
    exampleTranslationJa: "彼らは砂漠を横断する危険な旅をした。",
    collocations: ["a perilous journey", "perilously close"],
    mnemonic: "peril(重大な危険)の形容詞形。dangerous のかたい語。",
    relatedWords: ["dangerous", "hazardous", "safe"],
  },
  {
    id: "pompous",
    word: "pompous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["もったいぶった、尊大な"],
    pronunciation: "/ˈpɑːmpəs/",
    exampleSentence: "He has a pompous way of speaking.",
    exampleTranslationJa: "彼はもったいぶった話し方をする。",
    collocations: ["a pompous manner", "sound pompous"],
    mnemonic: "pomp(華美)の形容詞形。自分を大きく見せようとする態度。",
    relatedWords: ["arrogant", "self-important", "humble"],
  },
  {
    id: "populous",
    word: "populous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["人口の多い"],
    pronunciation: "/ˈpɑːpjələs/",
    exampleSentence: "It is the most populous city in the region.",
    exampleTranslationJa: "そこはその地域で最も人口の多い都市だ。",
    collocations: ["a populous region", "the most populous"],
    mnemonic: "population の形容詞形。popular(人気のある)とは別語。",
    relatedWords: ["crowded", "populated", "deserted"],
  },
  {
    id: "porous",
    word: "porous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["穴の多い、水を通す", "(国境が)ざるの"],
    pronunciation: "/ˈpɔːrəs/",
    exampleSentence: "The rock is porous and absorbs water.",
    exampleTranslationJa: "その岩は多孔質で水を吸う。",
    collocations: ["porous rock", "a porous border"],
    mnemonic: "pore(小さな穴)の形容詞形。国境が「素通りできる」意味にも。",
    relatedWords: ["permeable", "absorbent", "sealed"],
  },
  {
    id: "pretentious",
    word: "pretentious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["気取った、もったいぶった"],
    pronunciation: "/prɪˈtenʃəs/",
    exampleSentence: "The menu is pretentious and overpriced.",
    exampleTranslationJa: "そのメニューは気取っていて高すぎる。",
    collocations: ["pretentious language", "sound pretentious"],
    mnemonic: "pretend(ふりをする)と同語根。実力以上に見せようとすること。",
    relatedWords: ["pompous", "affected", "modest"],
  },
  {
    id: "rebellious",
    word: "rebellious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["反抗的な"],
    pronunciation: "/rɪˈbeljəs/",
    exampleSentence: "He went through a rebellious phase at sixteen.",
    exampleTranslationJa: "彼は16歳で反抗期を通り抜けた。",
    collocations: ["a rebellious teenager", "a rebellious streak"],
    mnemonic: "rebel(反逆する)の形容詞形。10代について言うことが多い。",
    relatedWords: ["defiant", "disobedient", "obedient"],
  },
  {
    id: "illustrious",
    word: "illustrious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["著名な、輝かしい"],
    pronunciation: "/ɪˈlʌstriəs/",
    exampleSentence: "She comes from an illustrious family of scientists.",
    exampleTranslationJa: "彼女は科学者の名門の出だ。",
    collocations: ["an illustrious career", "an illustrious predecessor"],
    mnemonic: "lustre(輝き)と同語根。eminent よりさらに格式ばった語。",
    relatedWords: ["distinguished", "renowned", "obscure"],
  },
  {
    id: "admirable",
    word: "admirable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["立派な、感心な"],
    pronunciation: "/ˈædmərəbl/",
    exampleSentence: "Her restraint was admirable.",
    exampleTranslationJa: "彼女の自制は立派だった。",
    collocations: ["an admirable achievement", "admirable restraint"],
    mnemonic: "admire の形容詞形。アクセントは前 /ˈædmərəbl/。",
    relatedWords: ["admire", "commendable", "deplorable"],
  },
  {
    id: "advisable",
    word: "advisable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["賢明な、望ましい"],
    pronunciation: "/ədˈvaɪzəbl/",
    exampleSentence: "It is advisable to book in advance.",
    exampleTranslationJa: "事前に予約するのが賢明だ。",
    collocations: ["it is advisable to", "not advisable"],
    mnemonic: "advise の形容詞形。It is advisable to ... の形で使う。",
    relatedWords: ["advise", "wise", "inadvisable"],
  },
  {
    id: "agreeable",
    word: "agreeable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感じのよい", "(agreeable to で)同意して"],
    pronunciation: "/əˈɡriːəbl/",
    exampleSentence: "We spent an agreeable evening together.",
    exampleTranslationJa: "私たちは気持ちのよい夜を一緒に過ごした。",
    collocations: ["an agreeable manner", "agreeable to the terms"],
    mnemonic: "agree の形容詞形。人柄なら「感じがよい」、条件なら「承知して」。",
    relatedWords: ["pleasant", "amiable", "disagreeable"],
  },
  {
    id: "arguable",
    word: "arguable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["議論の余地がある", "主張できる"],
    pronunciation: "/ˈɑːrɡjuəbl/",
    exampleSentence: "It is arguable that the reverse is true.",
    exampleTranslationJa: "逆が正しいとも主張できる。",
    collocations: ["it is arguable that", "arguable point"],
    mnemonic: "argue の形容詞形。副詞 arguably は「おそらく〜と言ってよい」。",
    relatedWords: ["debatable", "questionable", "certain"],
  },
  {
    id: "attainable",
    word: "attainable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["達成可能な"],
    pronunciation: "/əˈteɪnəbl/",
    exampleSentence: "Set goals that are actually attainable.",
    exampleTranslationJa: "実際に達成できる目標を立てなさい。",
    collocations: ["an attainable goal", "realistically attainable"],
    mnemonic: "attain の形容詞形。achievable とほぼ同じ。",
    relatedWords: ["achievable", "realistic", "impossible"],
  },
  {
    id: "avoidable",
    word: "avoidable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["避けられる"],
    pronunciation: "/əˈvɔɪdəbl/",
    exampleSentence: "Most of these delays were avoidable.",
    exampleTranslationJa: "これらの遅れの大半は避けられた。",
    collocations: ["easily avoidable", "an avoidable death"],
    mnemonic: "avoid の形容詞形。unavoidable(避けられない)の反対。",
    relatedWords: ["preventable", "unnecessary", "unavoidable"],
  },
  {
    id: "bearable",
    word: "bearable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["耐えられる"],
    pronunciation: "/ˈberəbl/",
    exampleSentence: "The heat is just about bearable.",
    exampleTranslationJa: "その暑さはかろうじて耐えられる。",
    collocations: ["barely bearable", "make it bearable"],
    mnemonic: "bear(耐える)の形容詞形。unbearable(耐えがたい)の反対。",
    relatedWords: ["tolerable", "endurable", "unbearable"],
  },
  {
    id: "believable",
    word: "believable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["信じられる、真実味のある"],
    pronunciation: "/bɪˈliːvəbl/",
    exampleSentence: "The character is not believable.",
    exampleTranslationJa: "その登場人物には真実味がない。",
    collocations: ["a believable story", "hardly believable"],
    mnemonic: "believe の形容詞形。credible とほぼ同じ。",
    relatedWords: ["credible", "plausible", "unbelievable"],
  },
  {
    id: "changeable",
    word: "changeable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["変わりやすい"],
    pronunciation: "/ˈtʃeɪndʒəbl/",
    exampleSentence: "The weather is changeable at this time of year.",
    exampleTranslationJa: "この時期は天気が変わりやすい。",
    collocations: ["changeable weather", "a changeable mood"],
    mnemonic: "change の形容詞形。e を残すつづりに注意。",
    relatedWords: ["variable", "unpredictable", "stable"],
  },
  {
    id: "charitable",
    word: "charitable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["慈善の", "寛大な"],
    pronunciation: "/ˈtʃærətəbl/",
    exampleSentence: "The money went to a charitable trust.",
    exampleTranslationJa: "その金は慈善信託に渡った。",
    collocations: ["a charitable donation", "a charitable interpretation"],
    mnemonic: "charity の形容詞形。人の解釈が「好意的な」意味にもなる。",
    relatedWords: ["charity", "generous", "uncharitable"],
  },
  {
    id: "commendable",
    word: "commendable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["賞賛に値する"],
    pronunciation: "/kəˈmendəbl/",
    exampleSentence: "Her honesty is commendable.",
    exampleTranslationJa: "彼女の正直さは賞賛に値する。",
    collocations: ["commendable effort", "highly commendable"],
    mnemonic: "commend(ほめる)の形容詞形。recommend と同語根。",
    relatedWords: ["praiseworthy", "admirable", "deplorable"],
  },
  {
    id: "curable",
    word: "curable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["治療可能な"],
    pronunciation: "/ˈkjʊrəbl/",
    exampleSentence: "The disease is curable if caught early.",
    exampleTranslationJa: "その病気は早期に見つかれば治せる。",
    collocations: ["a curable condition", "perfectly curable"],
    mnemonic: "cure の形容詞形。反対は incurable(不治の)。",
    relatedWords: ["treatable", "cure", "incurable"],
  },
  {
    id: "debatable",
    word: "debatable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["議論の余地がある"],
    pronunciation: "/dɪˈbeɪtəbl/",
    exampleSentence: "Whether it saved money is debatable.",
    exampleTranslationJa: "それが金を節約したかは議論の余地がある。",
    collocations: ["highly debatable", "a debatable point"],
    mnemonic: "debate の形容詞形。「そうとも言い切れない」という控えめな否定。",
    relatedWords: ["arguable", "questionable", "certain"],
  },
  {
    id: "despicable",
    word: "despicable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["卑劣な、軽蔑すべき"],
    pronunciation: "/dɪˈspɪkəbl/",
    exampleSentence: "It was a despicable act.",
    exampleTranslationJa: "それは卑劣な行いだった。",
    collocations: ["a despicable act", "utterly despicable"],
    mnemonic: "despise(軽蔑する)の形容詞形。強い非難の語。",
    relatedWords: ["contemptible", "vile", "admirable"],
  },
  {
    id: "dispensable",
    word: "dispensable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["なくてもすむ"],
    pronunciation: "/dɪˈspensəbl/",
    exampleSentence: "No one on this team is dispensable.",
    exampleTranslationJa: "このチームに代わりのきく者はいない。",
    collocations: ["easily dispensable", "not dispensable"],
    mnemonic: "dispense with(なしですませる)の形容詞形。反対は indispensable。",
    relatedWords: ["expendable", "unnecessary", "indispensable"],
  },
  {
    id: "enviable",
    word: "enviable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うらやましい"],
    pronunciation: "/ˈenviəbl/",
    exampleSentence: "She is in the enviable position of having two offers.",
    exampleTranslationJa: "彼女は二つの内定を持つうらやましい立場にいる。",
    collocations: ["an enviable position", "an enviable record"],
    mnemonic: "envy の形容詞形。envious は「うらやむ側」、enviable は「うらやまれる側」。",
    relatedWords: ["envy", "desirable", "pitiable"],
  },
  {
    id: "equitable",
    word: "equitable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["公平な、公正な"],
    pronunciation: "/ˈekwɪtəbl/",
    exampleSentence: "They want a more equitable distribution.",
    exampleTranslationJa: "彼らはより公平な分配を望んでいる。",
    collocations: ["an equitable solution", "equitable distribution"],
    mnemonic: "equity(公平)の形容詞形。equal(均等)より「事情を踏まえた公正さ」。",
    relatedWords: ["fair", "just", "unfair"],
  },
  {
    id: "excusable",
    word: "excusable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["許される、無理もない"],
    pronunciation: "/ɪkˈskjuːzəbl/",
    exampleSentence: "The mistake was understandable and excusable.",
    exampleTranslationJa: "その誤りは無理もないもので、許されるものだった。",
    collocations: ["perfectly excusable", "an excusable error"],
    mnemonic: "excuse の形容詞形。反対は inexcusable(弁解の余地がない)。",
    relatedWords: ["forgivable", "understandable", "inexcusable"],
  },
  {
    id: "flammable",
    word: "flammable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["燃えやすい"],
    pronunciation: "/ˈflæməbl/",
    exampleSentence: "Keep flammable liquids away from heat.",
    exampleTranslationJa: "可燃性の液体は熱源から離しておくこと。",
    collocations: ["highly flammable", "flammable materials"],
    mnemonic: "inflammable も同じ「燃えやすい」。in- が否定と誤解されるため flammable が推奨される。",
    relatedWords: ["inflammable", "combustible", "fireproof"],
  },
  {
    id: "honourable",
    word: "honourable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["名誉ある、立派な"],
    pronunciation: "/ˈɑːnərəbl/",
    exampleSentence: "He made an honourable decision.",
    exampleTranslationJa: "彼は立派な決断をした。",
    collocations: ["an honourable man", "an honourable discharge"],
    mnemonic: "honour の形容詞形。h は読まない。米つづりは honorable。",
    relatedWords: ["honour", "noble", "dishonourable"],
  },
  {
    id: "hospitable",
    word: "hospitable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["もてなしのよい", "(環境が)住みやすい"],
    pronunciation: "/hɑːˈspɪtəbl/",
    exampleSentence: "The islanders were extremely hospitable.",
    exampleTranslationJa: "島の人々はきわめてもてなしがよかった。",
    collocations: ["a hospitable welcome", "a hospitable climate"],
    mnemonic: "hospital・host と同語根。土地の「暮らしやすさ」にも使う。",
    relatedWords: ["welcoming", "friendly", "inhospitable"],
  },
  {
    id: "identifiable",
    word: "identifiable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["特定できる、見分けがつく"],
    pronunciation: "/aɪˌdentɪˈfaɪəbl/",
    exampleSentence: "The bird is identifiable by its red beak.",
    exampleTranslationJa: "その鳥は赤いくちばしで見分けられる。",
    collocations: ["easily identifiable", "identifiable by"],
    mnemonic: "identify の形容詞形。個人情報の「識別可能な」でも使う。",
    relatedWords: ["recognisable", "distinguishable", "anonymous"],
  },
  {
    id: "imaginable",
    word: "imaginable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["想像できる限りの"],
    pronunciation: "/ɪˈmædʒɪnəbl/",
    exampleSentence: "They tried every method imaginable.",
    exampleTranslationJa: "彼らは考えつく限りの方法を試した。",
    collocations: ["every method imaginable", "the worst imaginable"],
    mnemonic: "imagine の形容詞形。名詞のあとに置いて最上級を強める。",
    relatedWords: ["conceivable", "possible", "unimaginable"],
  },
  {
    id: "impenetrable",
    word: "impenetrable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["通り抜けられない", "理解できない"],
    pronunciation: "/ɪmˈpenɪtrəbl/",
    exampleSentence: "The prose is almost impenetrable.",
    exampleTranslationJa: "その文章はほとんど歯が立たない。",
    collocations: ["impenetrable jungle", "impenetrable prose"],
    mnemonic: "penetrate の否定形。森にも難解な文章にも使う。",
    relatedWords: ["impassable", "incomprehensible", "clear"],
  },
  {
    id: "impressionable",
    word: "impressionable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["影響を受けやすい"],
    pronunciation: "/ɪmˈpreʃənəbl/",
    exampleSentence: "Children are impressionable at that age.",
    exampleTranslationJa: "その年ごろの子どもは影響を受けやすい。",
    collocations: ["at an impressionable age", "young and impressionable"],
    mnemonic: "impression の形容詞形。心に跡がつきやすいこと。",
    relatedWords: ["susceptible", "gullible", "hardened"],
  },
  {
    id: "improbable",
    word: "improbable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ありそうにない"],
    pronunciation: "/ɪmˈprɑːbəbl/",
    exampleSentence: "It is improbable but not impossible.",
    exampleTranslationJa: "ありそうにないが、不可能ではない。",
    collocations: ["highly improbable", "an improbable story"],
    mnemonic: "probable の否定。impossible(不可能)より弱い。",
    relatedWords: ["unlikely", "doubtful", "probable"],
  },
  {
    id: "incomparable",
    word: "incomparable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["比べようもない、無比の"],
    pronunciation: "/ɪnˈkɑːmpərəbl/",
    exampleSentence: "The view from the top is incomparable.",
    exampleTranslationJa: "頂上からの眺めは比べようもない。",
    collocations: ["incomparable beauty", "simply incomparable"],
    mnemonic: "アクセントは前より /ɪnˈkɑːmpərəbl/。ほめ言葉として使う。",
    relatedWords: ["unmatched", "unique", "ordinary"],
  },
  {
    id: "incurable",
    word: "incurable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不治の", "救いがたい"],
    pronunciation: "/ɪnˈkjʊrəbl/",
    exampleSentence: "He has an incurable condition.",
    exampleTranslationJa: "彼は治らない病を抱えている。",
    collocations: ["an incurable disease", "an incurable optimist"],
    mnemonic: "curable の否定。an incurable optimist は「筋金入りの楽天家」。",
    relatedWords: ["untreatable", "terminal", "curable"],
  },
  {
    id: "indefensible",
    word: "indefensible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["弁護のしようがない"],
    pronunciation: "/ˌɪndɪˈfensəbl/",
    exampleSentence: "The delay is indefensible.",
    exampleTranslationJa: "その遅れは弁解の余地がない。",
    collocations: ["morally indefensible", "an indefensible position"],
    mnemonic: "defend の否定形。守りようがない立場や行為に使う。",
    relatedWords: ["inexcusable", "unjustifiable", "defensible"],
  },
  {
    id: "inexcusable",
    word: "inexcusable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["弁解の余地がない"],
    pronunciation: "/ˌɪnɪkˈskjuːzəbl/",
    exampleSentence: "Such rudeness is inexcusable.",
    exampleTranslationJa: "そんな失礼は許されない。",
    collocations: ["utterly inexcusable", "inexcusable behaviour"],
    mnemonic: "excusable の否定。indefensible より感情がこもる。",
    relatedWords: ["unforgivable", "indefensible", "excusable"],
  },
  {
    id: "interchangeable",
    word: "interchangeable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["取り替えのきく、互換性のある"],
    pronunciation: "/ˌɪntərˈtʃeɪndʒəbl/",
    exampleSentence: "The two parts are interchangeable.",
    exampleTranslationJa: "その二つの部品は互換性がある。",
    collocations: ["interchangeable parts", "used interchangeably"],
    mnemonic: "inter-(互いに)+ change。語について言えば「同義に使える」。",
    relatedWords: ["exchangeable", "equivalent", "unique"],
  },
  {
    id: "irreplaceable",
    word: "irreplaceable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["かけがえのない"],
    pronunciation: "/ˌɪrɪˈpleɪsəbl/",
    exampleSentence: "These records are irreplaceable.",
    exampleTranslationJa: "これらの記録はかけがえがない。",
    collocations: ["irreplaceable loss", "truly irreplaceable"],
    mnemonic: "replace の否定形。失ったら二度と手に入らないもの。",
    relatedWords: ["priceless", "unique", "replaceable"],
  },
  {
    id: "irresistible",
    word: "irresistible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["抗しがたい、たまらなく魅力的な"],
    pronunciation: "/ˌɪrɪˈzɪstəbl/",
    exampleSentence: "The smell of fresh bread is irresistible.",
    exampleTranslationJa: "焼きたてのパンの香りには抗いがたい。",
    collocations: ["an irresistible urge", "irresistible charm"],
    mnemonic: "resist の否定形。つづりは -ible(-able ではない)。",
    relatedWords: ["compelling", "tempting", "resistible"],
  },
  {
    id: "justifiable",
    word: "justifiable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["正当と認められる"],
    pronunciation: "/ˈdʒʌstɪfaɪəbl/",
    exampleSentence: "The expense is justifiable given the results.",
    exampleTranslationJa: "その成果を考えれば費用は正当だ。",
    collocations: ["justifiable pride", "perfectly justifiable"],
    mnemonic: "justify の形容詞形。「理由を説明できる」。",
    relatedWords: ["defensible", "legitimate", "unjustifiable"],
  },
  {
    id: "knowledgeable",
    word: "knowledgeable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よく知っている、博識な"],
    pronunciation: "/ˈnɑːlɪdʒəbl/",
    exampleSentence: "The guide was very knowledgeable about birds.",
    exampleTranslationJa: "その案内人は鳥にとても詳しかった。",
    collocations: ["knowledgeable about", "highly knowledgeable"],
    mnemonic: "knowledge + -able。e を残すつづりに注意。",
    relatedWords: ["well-informed", "expert", "ignorant"],
  },
  {
    id: "laughable",
    word: "laughable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["笑ってしまうほどひどい"],
    pronunciation: "/ˈlæfəbl/",
    exampleSentence: "The offer was laughable.",
    exampleTranslationJa: "その申し出は話にならなかった。",
    collocations: ["a laughable attempt", "frankly laughable"],
    mnemonic: "funny(おかしい)ではなく「ばかばかしい」という非難。",
    relatedWords: ["ridiculous", "absurd", "serious"],
  },
  {
    id: "manageable",
    word: "manageable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["扱いやすい、何とかなる量の"],
    pronunciation: "/ˈmænɪdʒəbl/",
    exampleSentence: "Break the task into manageable pieces.",
    exampleTranslationJa: "その仕事を扱える大きさに分けなさい。",
    collocations: ["manageable chunks", "a manageable size"],
    mnemonic: "manage の形容詞形。「多すぎず何とかこなせる」。",
    relatedWords: ["controllable", "feasible", "unmanageable"],
  },
  {
    id: "measurable",
    word: "measurable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["測定できる、目に見えるほどの"],
    pronunciation: "/ˈmeʒərəbl/",
    exampleSentence: "There has been a measurable improvement.",
    exampleTranslationJa: "目に見える改善があった。",
    collocations: ["a measurable difference", "measurable outcomes"],
    mnemonic: "measure の形容詞形。「数字で示せる」という含み。",
    relatedWords: ["quantifiable", "noticeable", "negligible"],
  },
  {
    id: "boastful",
    word: "boastful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自慢げな"],
    pronunciation: "/ˈboʊstfl/",
    exampleSentence: "He is confident without being boastful.",
    exampleTranslationJa: "彼は自慢げにならずに自信を持っている。",
    collocations: ["boastful claims", "sound boastful"],
    mnemonic: "boast(自慢する)+ -ful。confident との違いがポイント。",
    relatedWords: ["bragging", "arrogant", "modest"],
  },
  {
    id: "deceitful",
    word: "deceitful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うそをつく、人を欺く"],
    pronunciation: "/dɪˈsiːtfl/",
    exampleSentence: "His account was deliberately deceitful.",
    exampleTranslationJa: "彼の説明は意図的に人を欺くものだった。",
    collocations: ["deceitful behaviour", "a deceitful man"],
    mnemonic: "deceit(欺き)+ -ful。deceptive が「紛らわしい」、deceitful は「だます意図がある」。",
    relatedWords: ["dishonest", "deceptive", "honest"],
  },
  {
    id: "disgraceful",
    word: "disgraceful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恥ずべき、けしからん"],
    pronunciation: "/dɪsˈɡreɪsfl/",
    exampleSentence: "The state of the toilets was disgraceful.",
    exampleTranslationJa: "トイレの状態はひどいものだった。",
    collocations: ["disgraceful behaviour", "absolutely disgraceful"],
    mnemonic: "disgrace(不名誉)+ -ful。強い非難の口語表現。",
    relatedWords: ["shameful", "appalling", "admirable"],
  },
  {
    id: "doubtful",
    word: "doubtful",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["疑わしい、確信が持てない"],
    pronunciation: "/ˈdaʊtfl/",
    exampleSentence: "It is doubtful whether they will finish in time.",
    exampleTranslationJa: "彼らが間に合うかは疑わしい。",
    collocations: ["doubtful whether", "highly doubtful", "look doubtful"],
    mnemonic: "doubt の形容詞形。b は読まない。",
    relatedWords: ["uncertain", "unlikely", "certain"],
  },
  {
    id: "dreadful",
    word: "dreadful",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["ひどい、恐ろしい"],
    pronunciation: "/ˈdredfl/",
    exampleSentence: "The food was dreadful.",
    exampleTranslationJa: "その食事はひどかった。",
    collocations: ["a dreadful mistake", "feel dreadful"],
    mnemonic: "dread(恐れ)+ -ful。英ではごく日常的に「ひどい」の意味で使う。",
    relatedWords: ["terrible", "awful", "wonderful"],
  },
  {
    id: "eventful",
    word: "eventful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["出来事の多い、波乱に富んだ"],
    pronunciation: "/ɪˈventfl/",
    exampleSentence: "It has been an eventful year.",
    exampleTranslationJa: "波乱に富んだ一年だった。",
    collocations: ["an eventful journey", "an eventful life"],
    mnemonic: "event(出来事)+ -ful。よくも悪くも「いろいろあった」。",
    relatedWords: ["busy", "dramatic", "uneventful"],
  },
  {
    id: "forceful",
    word: "forceful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["力強い、説得力のある"],
    pronunciation: "/ˈfɔːrsfl/",
    exampleSentence: "She made a forceful case for change.",
    exampleTranslationJa: "彼女は変革を力強く主張した。",
    collocations: ["a forceful argument", "a forceful personality"],
    mnemonic: "force(力)+ -ful。人にも議論にも使う。",
    relatedWords: ["powerful", "assertive", "weak"],
  },
  {
    id: "fruitful",
    word: "fruitful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["実りある、有意義な"],
    pronunciation: "/ˈfruːtfl/",
    exampleSentence: "The talks were fruitful.",
    exampleTranslationJa: "その会談は実りあるものだった。",
    collocations: ["a fruitful discussion", "a fruitful collaboration"],
    mnemonic: "fruit(実)+ -ful。反対は fruitless(実りのない)。",
    relatedWords: ["productive", "rewarding", "fruitless"],
  },
  {
    id: "insightful",
    word: "insightful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["洞察に富んだ"],
    pronunciation: "/ˈɪnsaɪtfl/",
    exampleSentence: "Her comments were insightful.",
    exampleTranslationJa: "彼女の指摘は洞察に富んでいた。",
    collocations: ["an insightful analysis", "deeply insightful"],
    mnemonic: "insight(洞察)+ -ful。ものごとの内側が見えていること。",
    relatedWords: ["perceptive", "astute", "shallow"],
  },
  {
    id: "joyful",
    word: "joyful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["喜びに満ちた"],
    pronunciation: "/ˈdʒɔɪfl/",
    exampleSentence: "It was a joyful reunion.",
    exampleTranslationJa: "それは喜びに満ちた再会だった。",
    collocations: ["a joyful occasion", "joyful news"],
    mnemonic: "joy(喜び)+ -ful。happy よりあらたまった、晴れやかな喜び。",
    relatedWords: ["joyous", "delighted", "sorrowful"],
  },
  {
    id: "mournful",
    word: "mournful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["悲しげな、もの悲しい"],
    pronunciation: "/ˈmɔːrnfl/",
    exampleSentence: "A mournful tune drifted from the church.",
    exampleTranslationJa: "もの悲しい調べが教会から流れてきた。",
    collocations: ["a mournful expression", "a mournful sound"],
    mnemonic: "mourn(嘆く)+ -ful。音や表情の悲しさに使う。",
    relatedWords: ["sorrowful", "melancholy", "cheerful"],
  },
  {
    id: "pitiful",
    word: "pitiful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["哀れな", "(量が)情けないほど少ない"],
    pronunciation: "/ˈpɪtɪfl/",
    exampleSentence: "They were paid a pitiful wage.",
    exampleTranslationJa: "彼らは情けないほど安い賃金しかもらえなかった。",
    collocations: ["a pitiful sight", "a pitiful amount"],
    mnemonic: "pity(あわれみ)+ -ful。同情を誘う場合と、あきれる場合の両方。",
    relatedWords: ["pathetic", "miserable", "impressive"],
  },
  {
    id: "regretful",
    word: "regretful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["残念に思っている、悔いている"],
    pronunciation: "/rɪˈɡretfl/",
    exampleSentence: "He sounded genuinely regretful.",
    exampleTranslationJa: "彼は心から悔いているようだった。",
    collocations: ["a regretful tone", "sound regretful"],
    mnemonic: "regret + -ful。regrettable は「(事柄が)残念な」で主語が違う。",
    relatedWords: ["sorry", "remorseful", "unrepentant"],
  },
  {
    id: "resourceful",
    word: "resourceful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["機転がきく、工夫上手な"],
    pronunciation: "/rɪˈsɔːrsfl/",
    exampleSentence: "She is resourceful in a crisis.",
    exampleTranslationJa: "彼女は危機の場面で機転がきく。",
    collocations: ["highly resourceful", "a resourceful approach"],
    mnemonic: "resource(手立て)+ -ful。ないものを何とかする力。",
    relatedWords: ["inventive", "capable", "helpless"],
  },
  {
    id: "respectful",
    word: "respectful",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["敬意のこもった、礼儀正しい"],
    pronunciation: "/rɪˈspektfl/",
    exampleSentence: "Please be respectful of other guests.",
    exampleTranslationJa: "ほかの客への配慮をお願いします。",
    collocations: ["respectful of", "a respectful silence"],
    mnemonic: "respect + -ful。respectable(まともな)、respective(それぞれの)と混同注意。",
    relatedWords: ["polite", "courteous", "disrespectful"],
  },
  {
    id: "rightful",
    word: "rightful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["正当な権利をもつ"],
    pronunciation: "/ˈraɪtfl/",
    exampleSentence: "The painting was returned to its rightful owner.",
    exampleTranslationJa: "その絵は正当な持ち主に返された。",
    collocations: ["the rightful owner", "the rightful heir"],
    mnemonic: "right(権利)+ -ful。法的に正しい持ち主や地位に使う。",
    relatedWords: ["legitimate", "lawful", "wrongful"],
  },
  {
    id: "scornful",
    word: "scornful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["軽蔑した、あざけるような"],
    pronunciation: "/ˈskɔːrnfl/",
    exampleSentence: "She gave a scornful laugh.",
    exampleTranslationJa: "彼女はあざけるように笑った。",
    collocations: ["scornful of", "a scornful look"],
    mnemonic: "scorn(軽蔑)+ -ful。be scornful of ... の形で使う。",
    relatedWords: ["contemptuous", "disdainful", "admiring"],
  },
  {
    id: "skilful",
    word: "skilful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["巧みな、腕のよい"],
    pronunciation: "/ˈskɪlfl/",
    exampleSentence: "It was a skilful piece of negotiation.",
    exampleTranslationJa: "それは巧みな交渉だった。",
    collocations: ["a skilful player", "skilful handling"],
    mnemonic: "skill + -ful。英つづりは l が一つ、米つづりは skillful。",
    relatedWords: ["skilled", "adept", "clumsy"],
  },
  {
    id: "spiteful",
    word: "spiteful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["意地の悪い、悪意のある"],
    pronunciation: "/ˈspaɪtfl/",
    exampleSentence: "That was a spiteful thing to say.",
    exampleTranslationJa: "それは意地の悪い言い方だった。",
    collocations: ["a spiteful remark", "spiteful behaviour"],
    mnemonic: "spite(悪意)+ -ful。out of spite は「腹いせに」。",
    relatedWords: ["malicious", "vindictive", "kind"],
  },
  {
    id: "tasteful",
    word: "tasteful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["趣味のよい、品のよい"],
    pronunciation: "/ˈteɪstfl/",
    exampleSentence: "The room was decorated in a tasteful style.",
    exampleTranslationJa: "その部屋は品のよい様式で飾られていた。",
    collocations: ["tasteful decor", "a tasteful choice"],
    mnemonic: "taste(趣味)+ -ful。食べ物の「おいしい」は tasty で別語。",
    relatedWords: ["elegant", "refined", "tasteless"],
  },
  {
    id: "truthful",
    word: "truthful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["正直な、真実の"],
    pronunciation: "/ˈtruːθfl/",
    exampleSentence: "Please give a truthful answer.",
    exampleTranslationJa: "正直な答えをください。",
    collocations: ["a truthful account", "be truthful with"],
    mnemonic: "truth + -ful。honest とほぼ同じだが「事実に忠実」寄り。",
    relatedWords: ["honest", "sincere", "deceitful"],
  },
  {
    id: "watchful",
    word: "watchful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["油断のない、注意深く見守る"],
    pronunciation: "/ˈwɑːtʃfl/",
    exampleSentence: "The children played under a watchful eye.",
    exampleTranslationJa: "子どもたちは見守られながら遊んだ。",
    collocations: ["a watchful eye", "remain watchful"],
    mnemonic: "watch + -ful。under a watchful eye が定型。",
    relatedWords: ["vigilant", "alert", "careless"],
  },
  {
    id: "aimless",
    word: "aimless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["目的のない、当てもない"],
    pronunciation: "/ˈeɪmləs/",
    exampleSentence: "They spent an aimless afternoon in town.",
    exampleTranslationJa: "彼らは町で当てもない午後を過ごした。",
    collocations: ["aimless wandering", "an aimless life"],
    mnemonic: "aim(目的)+ -less。方向が定まっていないこと。",
    relatedWords: ["purposeless", "directionless", "purposeful"],
  },
  {
    id: "boundless",
    word: "boundless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["限りない"],
    pronunciation: "/ˈbaʊndləs/",
    exampleSentence: "She has boundless energy.",
    exampleTranslationJa: "彼女は尽きることのない気力を持っている。",
    collocations: ["boundless energy", "boundless enthusiasm"],
    mnemonic: "bound(境界)+ -less。よい性質について使うことが多い。",
    relatedWords: ["limitless", "infinite", "limited"],
  },
  {
    id: "effortless",
    word: "effortless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["楽々とした、苦もない"],
    pronunciation: "/ˈefərtləs/",
    exampleSentence: "Her style looks effortless.",
    exampleTranslationJa: "彼女の身のこなしは苦もないように見える。",
    collocations: ["effortless grace", "appear effortless"],
    mnemonic: "effort + -less。実際は努力していても「そう見えない」のがほめ言葉。",
    relatedWords: ["easy", "smooth", "laboured"],
  },
  {
    id: "fearless",
    word: "fearless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恐れを知らない"],
    pronunciation: "/ˈfɪrləs/",
    exampleSentence: "She was a fearless reporter.",
    exampleTranslationJa: "彼女は恐れを知らない記者だった。",
    collocations: ["fearless in the face of", "a fearless critic"],
    mnemonic: "fear + -less。brave が「恐れても向かう」、fearless は「恐れない」。",
    relatedWords: ["brave", "bold", "timid"],
  },
  {
    id: "flawless",
    word: "flawless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["欠点のない、完璧な"],
    pronunciation: "/ˈflɔːləs/",
    exampleSentence: "Her performance was flawless.",
    exampleTranslationJa: "彼女の演技は完璧だった。",
    collocations: ["a flawless performance", "flawless skin"],
    mnemonic: "flaw(傷)+ -less。perfect よりも「傷ひとつない」に近い。",
    relatedWords: ["perfect", "impeccable", "flawed"],
  },
]
