import type { VocabularyEntry } from '../types'

// 増補 第29弾(最終)。話をつなぐ慣用表現と、身のまわりの具体名詞。
// これで 4,500語 → 7,500語 の増補が完了する。
export const plus29: VocabularyEntry[] = [
  {
    id: "as a matter of fact",
    word: "as a matter of fact",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["実のところ、実は"],
    pronunciation: "/æz ə ˈmætər ʌv fækt/",
    exampleSentence: "As a matter of fact, I have already read it.",
    exampleTranslationJa: "実のところ、それはもう読みました。",
    collocations: ["as a matter of fact", "in point of fact"],
    mnemonic: "相手の想定を訂正するときの前置き。in fact とほぼ同じ。",
    relatedWords: ["in fact", "actually", "supposedly"],
  },
  {
    id: "as far as I know",
    word: "as far as I know",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["私の知る限りでは"],
    pronunciation: "/æz fɑːr æz aɪ noʊ/",
    exampleSentence: "As far as I know, the shop is still open.",
    exampleTranslationJa: "私の知る限り、その店はまだ開いている。",
    collocations: ["as far as I know", "as far as I can tell"],
    mnemonic: "断言を避ける前置き。略して AFAIK と書くこともある。",
    relatedWords: ["to my knowledge", "apparently", "definitely"],
  },
  {
    id: "at any rate",
    word: "at any rate",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["いずれにせよ、とにかく"],
    pronunciation: "/æt ˈeni reɪt/",
    exampleSentence: "At any rate, we should start now.",
    exampleTranslationJa: "いずれにせよ、今始めるべきだ。",
    collocations: ["at any rate", "at any rate for now"],
    mnemonic: "話を切り替えるときのつなぎ。anyway のややかたい形。",
    relatedWords: ["anyway", "in any case", "specifically"],
  },
  {
    id: "in a nutshell",
    word: "in a nutshell",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["ひと言で言えば"],
    pronunciation: "/ɪn ə ˈnʌtʃel/",
    exampleSentence: "In a nutshell, the plan is too expensive.",
    exampleTranslationJa: "ひと言で言えば、その計画は高すぎる。",
    collocations: ["in a nutshell", "that is it in a nutshell"],
    mnemonic: "クルミの殻に収まるほど短く、が原義。要約の前置き。",
    relatedWords: ["in short", "briefly", "in detail"],
  },
  {
    id: "in other words",
    word: "in other words",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["言い換えれば"],
    pronunciation: "/ɪn ˈʌðər wɜːrdz/",
    exampleSentence: "In other words, we cannot afford it.",
    exampleTranslationJa: "言い換えれば、それを買う余裕はない。",
    collocations: ["in other words", "or in other words"],
    mnemonic: "直前の内容をやさしく言い直すときのつなぎ。",
    relatedWords: ["that is to say", "namely", "conversely"],
  },
  {
    id: "in short",
    word: "in short",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["要するに"],
    pronunciation: "/ɪn ʃɔːrt/",
    exampleSentence: "In short, the answer is no.",
    exampleTranslationJa: "要するに、答えは否だ。",
    collocations: ["in short", "to be short"],
    mnemonic: "長い説明のあとに結論をひと言でまとめる。",
    relatedWords: ["in brief", "in summary", "in detail"],
  },
  {
    id: "in brief",
    word: "in brief",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["手短に言えば"],
    pronunciation: "/ɪn briːf/",
    exampleSentence: "In brief, the trial failed.",
    exampleTranslationJa: "手短に言えば、その試験は失敗した。",
    collocations: ["in brief", "news in brief"],
    mnemonic: "新聞の「短信」欄も News in Brief。",
    relatedWords: ["in short", "briefly", "at length"],
  },
  {
    id: "needless to say",
    word: "needless to say",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["言うまでもなく"],
    pronunciation: "/ˈniːdləs tuː seɪ/",
    exampleSentence: "Needless to say, everyone was late.",
    exampleTranslationJa: "言うまでもなく、全員が遅刻した。",
    collocations: ["needless to say", "needless to say, however"],
    mnemonic: "needless(不必要な)+ to say。分かりきったことを前置きする。",
    relatedWords: ["obviously", "of course", "surprisingly"],
  },
  {
    id: "not to mention",
    word: "not to mention",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["〜は言うまでもなく"],
    pronunciation: "/nɑːt tuː ˈmenʃn/",
    exampleSentence: "The trip costs a fortune, not to mention the time.",
    exampleTranslationJa: "その旅行は大金がかかる、時間は言うまでもなく。",
    collocations: ["not to mention the cost", "not to mention"],
    mnemonic: "追加の理由を挙げて畳みかけるときに使う。",
    relatedWords: ["let alone", "besides", "excluding"],
  },
  {
    id: "so to speak",
    word: "so to speak",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["いわば"],
    pronunciation: "/soʊ tuː spiːk/",
    exampleSentence: "He is the engine of the team, so to speak.",
    exampleTranslationJa: "彼はいわばチームの心臓部だ。",
    collocations: ["so to speak", "as it were"],
    mnemonic: "比喩を使ったあとに「言葉のあやですが」と添える。",
    relatedWords: ["as it were", "in a sense", "literally"],
  },
  {
    id: "that is to say",
    word: "that is to say",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["すなわち、つまり"],
    pronunciation: "/ðæt ɪz tuː seɪ/",
    exampleSentence: "We leave on Friday, that is to say tomorrow.",
    exampleTranslationJa: "私たちは金曜、つまり明日出発する。",
    collocations: ["that is to say", "or that is to say"],
    mnemonic: "i.e. の話し言葉版。直前をより正確に言い直す。",
    relatedWords: ["namely", "in other words", "roughly"],
  },
  {
    id: "to be honest",
    word: "to be honest",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["正直なところ"],
    pronunciation: "/tuː biː ˈɑːnɪst/",
    exampleSentence: "To be honest, I had forgotten.",
    exampleTranslationJa: "正直なところ、忘れていました。",
    collocations: ["to be honest", "to be honest with you"],
    mnemonic: "言いにくいことの前置き。略して TBH とも書く。",
    relatedWords: ["frankly", "honestly", "supposedly"],
  },
  {
    id: "to put it simply",
    word: "to put it simply",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["簡単に言えば"],
    pronunciation: "/tuː pʊt ɪt ˈsɪmpli/",
    exampleSentence: "To put it simply, we ran out of money.",
    exampleTranslationJa: "簡単に言えば、資金が尽きた。",
    collocations: ["to put it simply", "to put it another way"],
    mnemonic: "to put it + 副詞 の形で言い方を調整できる(to put it bluntly など)。",
    relatedWords: ["simply put", "in short", "technically"],
  },
  {
    id: "what is more",
    word: "what is more",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["さらに、そのうえ"],
    pronunciation: "/wʌt ɪz mɔːr/",
    exampleSentence: "It is cheap, and what is more, it works.",
    exampleTranslationJa: "安いし、そのうえよく効く。",
    collocations: ["what is more", "and what is more"],
    mnemonic: "あとに続く内容のほうが重い、というときに使う。",
    relatedWords: ["moreover", "besides", "however"],
  },
  {
    id: "above all",
    word: "above all",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["とりわけ、何よりも"],
    pronunciation: "/əˈbʌv ɔːl/",
    exampleSentence: "Above all, stay calm.",
    exampleTranslationJa: "何よりも落ち着いていて。",
    collocations: ["above all else", "above all"],
    mnemonic: "複数挙げた中で最も重要なものを示す。",
    relatedWords: ["most importantly", "especially", "least of all"],
  },
  {
    id: "after all",
    word: "after all",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["結局", "何といっても"],
    pronunciation: "/ˈæftər ɔːl/",
    exampleSentence: "He came after all.",
    exampleTranslationJa: "彼は結局来た。",
    collocations: ["after all", "after all this time"],
    mnemonic: "「予想に反して結局」と「なんといっても〜だから」の二つの用法。",
    relatedWords: ["in the end", "anyway", "initially"],
  },
  {
    id: "at most",
    word: "at most",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["多くとも"],
    pronunciation: "/æt moʊst/",
    exampleSentence: "It will take an hour at most.",
    exampleTranslationJa: "かかってもせいぜい1時間だ。",
    collocations: ["at most", "at the very most"],
    mnemonic: "at least(少なくとも)と対で覚える。",
    relatedWords: ["no more than", "maximum", "at least"],
  },
  {
    id: "at once",
    word: "at once",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["すぐに", "同時に"],
    pronunciation: "/æt wʌns/",
    exampleSentence: "Come here at once.",
    exampleTranslationJa: "すぐにここへ来なさい。",
    collocations: ["at once", "all at once"],
    mnemonic: "「ただちに」と「一度に」の二つ。all at once は「突然」。",
    relatedWords: ["immediately", "simultaneously", "later"],
  },
  {
    id: "at present",
    word: "at present",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["現在のところ"],
    pronunciation: "/æt ˈpreznt/",
    exampleSentence: "At present there is no cure.",
    exampleTranslationJa: "現在のところ治療法はない。",
    collocations: ["at present", "at the present time"],
    mnemonic: "currently のかたい言い方。文頭にも文末にも置ける。",
    relatedWords: ["currently", "now", "formerly"],
  },
  {
    id: "by chance",
    word: "by chance",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["偶然に"],
    pronunciation: "/baɪ tʃæns/",
    exampleSentence: "I met her by chance at the station.",
    exampleTranslationJa: "駅で偶然彼女に会った。",
    collocations: ["quite by chance", "by any chance"],
    mnemonic: "by any chance は「ひょっとして」と丁寧に尋ねる形。",
    relatedWords: ["accidentally", "by accident", "deliberately"],
  },
  {
    id: "by contrast",
    word: "by contrast",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["対照的に"],
    pronunciation: "/baɪ ˈkɑːntræst/",
    exampleSentence: "By contrast, sales rose in the south.",
    exampleTranslationJa: "対照的に、南部では売上が伸びた。",
    collocations: ["by contrast", "in contrast to"],
    mnemonic: "前の文と対比させる文頭のつなぎ。",
    relatedWords: ["conversely", "on the other hand", "similarly"],
  },
  {
    id: "by far",
    word: "by far",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["断然、はるかに"],
    pronunciation: "/baɪ fɑːr/",
    exampleSentence: "This is by far the best option.",
    exampleTranslationJa: "これが断然いちばんよい選択肢だ。",
    collocations: ["by far the best", "by far the largest"],
    mnemonic: "最上級を強める。比較級なら far + 比較級。",
    relatedWords: ["much", "considerably", "slightly"],
  },
  {
    id: "for good",
    word: "for good",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["永久に、これきり"],
    pronunciation: "/fɔːr ɡʊd/",
    exampleSentence: "She has left for good this time.",
    exampleTranslationJa: "今度こそ彼女は永久に去った。",
    collocations: ["leave for good", "gone for good"],
    mnemonic: "good(よい)とは無関係で「永遠に」。for good and all の短縮。",
    relatedWords: ["permanently", "forever", "temporarily"],
  },
  {
    id: "for now",
    word: "for now",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["今のところは、さしあたり"],
    pronunciation: "/fɔːr naʊ/",
    exampleSentence: "That will do for now.",
    exampleTranslationJa: "さしあたりそれで足りる。",
    collocations: ["for now", "that is all for now"],
    mnemonic: "あとで変わるかもしれない、という含みがある。",
    relatedWords: ["for the moment", "temporarily", "permanently"],
  },
  {
    id: "for the time being",
    word: "for the time being",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["当分の間"],
    pronunciation: "/fɔːr ðə taɪm ˈbiːɪŋ/",
    exampleSentence: "We will stay here for the time being.",
    exampleTranslationJa: "当分の間ここにいます。",
    collocations: ["for the time being", "stay for the time being"],
    mnemonic: "for now のかたい形。暫定的な取り決めに使う。",
    relatedWords: ["temporarily", "meanwhile", "permanently"],
  },
  {
    id: "in detail",
    word: "in detail",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["詳細に"],
    pronunciation: "/ɪn ˈdiːteɪl/",
    exampleSentence: "He explained the process in detail.",
    exampleTranslationJa: "彼はその工程を詳しく説明した。",
    collocations: ["in great detail", "go into detail"],
    mnemonic: "go into detail は「細部に立ち入る」。",
    relatedWords: ["thoroughly", "fully", "briefly"],
  },
  {
    id: "in effect",
    word: "in effect",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["事実上", "(規則が)有効で"],
    pronunciation: "/ɪn ɪˈfekt/",
    exampleSentence: "In effect, the rule has been abandoned.",
    exampleTranslationJa: "事実上、その規則は放棄された。",
    collocations: ["in effect", "come into effect"],
    mnemonic: "「実質的には」と「効力をもって」の二つ。文脈で見分ける。",
    relatedWords: ["effectively", "in force", "nominally"],
  },
  {
    id: "in practice",
    word: "in practice",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["実際には"],
    pronunciation: "/ɪn ˈpræktɪs/",
    exampleSentence: "In theory it works; in practice it does not.",
    exampleTranslationJa: "理屈のうえでは動くが、実際には動かない。",
    collocations: ["in practice", "in theory and in practice"],
    mnemonic: "in theory(理屈では)と対で使うのが定番。",
    relatedWords: ["actually", "in reality", "in theory"],
  },
  {
    id: "in public",
    word: "in public",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["人前で、公然と"],
    pronunciation: "/ɪn ˈpʌblɪk/",
    exampleSentence: "He rarely speaks in public.",
    exampleTranslationJa: "彼はめったに人前で話さない。",
    collocations: ["speak in public", "appear in public"],
    mnemonic: "in private(内々に)の反対。",
    relatedWords: ["publicly", "openly", "in private"],
  },
  {
    id: "in theory",
    word: "in theory",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["理論上は"],
    pronunciation: "/ɪn ˈθɪəri/",
    exampleSentence: "In theory anyone can apply.",
    exampleTranslationJa: "理論上は誰でも応募できる。",
    collocations: ["in theory", "in theory at least"],
    mnemonic: "「実際は違うが」という含みを伴うことが多い。",
    relatedWords: ["theoretically", "in principle", "in practice"],
  },
  {
    id: "in turn",
    word: "in turn",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["順番に", "その結果として"],
    pronunciation: "/ɪn tɜːrn/",
    exampleSentence: "Each speaker addressed the room in turn.",
    exampleTranslationJa: "各話者が順番に会場に語りかけた。",
    collocations: ["in turn", "each in turn"],
    mnemonic: "「順に」と「それが今度は」の二つ。因果の連鎖を示す用法が重要。",
    relatedWords: ["successively", "consequently", "simultaneously"],
  },
  {
    id: "of course",
    word: "of course",
    level: "A2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["もちろん"],
    pronunciation: "/ʌv kɔːrs/",
    exampleSentence: "Of course you may borrow it.",
    exampleTranslationJa: "もちろん借りていいですよ。",
    collocations: ["of course not", "but of course"],
    mnemonic: "当然のこととして認めるときの返事。course のつづりに注意。",
    relatedWords: ["certainly", "naturally", "hardly"],
  },
  {
    id: "on time",
    word: "on time",
    level: "A2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["時間どおりに"],
    pronunciation: "/ɑːn taɪm/",
    exampleSentence: "The train arrived on time.",
    exampleTranslationJa: "その電車は定刻に到着した。",
    collocations: ["arrive on time", "run on time"],
    mnemonic: "on time(定刻に)と in time(間に合って)は別。",
    relatedWords: ["punctually", "promptly", "late"],
  },
  {
    id: "once and for all",
    word: "once and for all",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["これを最後に、きっぱりと"],
    pronunciation: "/wʌns ənd fɔːr ɔːl/",
    exampleSentence: "Let us settle this once and for all.",
    exampleTranslationJa: "この件をこれきりで決着させよう。",
    collocations: ["settle it once and for all", "once and for all"],
    mnemonic: "何度も繰り返してきたことに終止符を打つ、という含み。",
    relatedWords: ["finally", "conclusively", "temporarily"],
  },
  {
    id: "so far",
    word: "so far",
    level: "A2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["今のところ、これまでは"],
    pronunciation: "/soʊ fɑːr/",
    exampleSentence: "So far everything has gone well.",
    exampleTranslationJa: "今のところすべて順調だ。",
    collocations: ["so far so good", "so far this year"],
    mnemonic: "現在完了と組むことが多い。So far, so good. は「今のところ順調」。",
    relatedWords: ["up to now", "hitherto", "henceforth"],
  },
  {
    id: "sooner or later",
    word: "sooner or later",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["遅かれ早かれ"],
    pronunciation: "/ˈsuːnər ɔːr ˈleɪtər/",
    exampleSentence: "Sooner or later they will find out.",
    exampleTranslationJa: "遅かれ早かれ彼らは気づく。",
    collocations: ["sooner or later", "sooner rather than later"],
    mnemonic: "いつかは必ず起きる、という断定。",
    relatedWords: ["eventually", "in time", "never"],
  },
  {
    id: "to some degree",
    word: "to some degree",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["ある程度は"],
    pronunciation: "/tuː sʌm dɪˈɡriː/",
    exampleSentence: "To some degree, everyone is responsible.",
    exampleTranslationJa: "ある程度は誰にも責任がある。",
    collocations: ["to some degree", "to a degree"],
    mnemonic: "to some extent とほぼ同じ。部分的に認める言い方。",
    relatedWords: ["partly", "somewhat", "entirely"],
  },
  {
    id: "up to a point",
    word: "up to a point",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["ある程度までは"],
    pronunciation: "/ʌp tuː ə pɔɪnt/",
    exampleSentence: "I agree with you up to a point.",
    exampleTranslationJa: "ある程度まではあなたに同意します。",
    collocations: ["agree up to a point", "true up to a point"],
    mnemonic: "「そこから先は別」という留保が必ず含まれる。",
    relatedWords: ["partly", "to an extent", "completely"],
  },
  {
    id: "without doubt",
    word: "without doubt",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["疑いなく"],
    pronunciation: "/wɪðˈaʊt daʊt/",
    exampleSentence: "She is without doubt the finest player here.",
    exampleTranslationJa: "彼女は疑いなくここで最高の選手だ。",
    collocations: ["without doubt", "without a doubt"],
    mnemonic: "no doubt(たぶん)より強く、断定に近い。",
    relatedWords: ["undoubtedly", "certainly", "possibly"],
  },
  {
    id: "more or less",
    word: "more or less",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["だいたい、ほぼ"],
    pronunciation: "/mɔːr ɔːr les/",
    exampleSentence: "The work is more or less finished.",
    exampleTranslationJa: "その作業はほぼ終わっている。",
    collocations: ["more or less finished", "more or less the same"],
    mnemonic: "数にも状態にも使える便利な言い方。",
    relatedWords: ["approximately", "roughly", "exactly"],
  },
  {
    id: "as such",
    word: "as such",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["それ自体としては", "したがって"],
    pronunciation: "/æz sʌtʃ/",
    exampleSentence: "There is no rule as such, only custom.",
    exampleTranslationJa: "規則そのものはなく、慣習があるだけだ。",
    collocations: ["not ... as such", "as such, we agreed"],
    mnemonic: "「厳密にそう呼べるものは」と限定する用法が難しい。",
    relatedWords: ["strictly speaking", "therefore", "broadly"],
  },
  {
    id: "if anything",
    word: "if anything",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["どちらかといえば、むしろ"],
    pronunciation: "/ɪf ˈeniθɪŋ/",
    exampleSentence: "If anything, the problem has got worse.",
    exampleTranslationJa: "どちらかといえば、問題は悪化している。",
    collocations: ["if anything", "if anything, more so"],
    mnemonic: "予想と逆の方向に傾いていると示す。",
    relatedWords: ["rather", "on the contrary", "equally"],
  },
  {
    id: "let alone",
    word: "let alone",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["まして〜ない"],
    pronunciation: "/let əˈloʊn/",
    exampleSentence: "He cannot boil an egg, let alone cook a meal.",
    exampleTranslationJa: "彼は卵もゆでられない、まして料理などできない。",
    collocations: ["let alone", "cannot ... let alone"],
    mnemonic: "必ず否定文のあとに置く。程度の重いほうを後ろに置く。",
    relatedWords: ["much less", "not to mention", "including"],
  },
  {
    id: "no wonder",
    word: "no wonder",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["道理で〜なわけだ"],
    pronunciation: "/noʊ ˈwʌndər/",
    exampleSentence: "No wonder you are tired.",
    exampleTranslationJa: "道理で疲れているわけだ。",
    collocations: ["no wonder", "it is no wonder that"],
    mnemonic: "納得したときの一言。it is no wonder that の省略形。",
    relatedWords: ["not surprising", "naturally", "strangely"],
  },
  {
    id: "on the one hand",
    word: "on the one hand",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["一方では"],
    pronunciation: "/ɑːn ðə wʌn hænd/",
    exampleSentence: "On the one hand it is cheap.",
    exampleTranslationJa: "一方では、それは安い。",
    collocations: ["on the one hand", "on the one hand ... on the other"],
    mnemonic: "必ず on the other hand と対で使う。",
    relatedWords: ["firstly", "one view", "on the other hand"],
  },
  {
    id: "on the other hand",
    word: "on the other hand",
    level: "B1",
    partOfSpeech: "慣用表現",
    meaningsJa: ["他方では、その一方で"],
    pronunciation: "/ɑːn ði ˈʌðər hænd/",
    exampleSentence: "On the other hand, the quality is poor.",
    exampleTranslationJa: "その一方で、品質は劣る。",
    collocations: ["on the other hand", "but on the other hand"],
    mnemonic: "対立する二つの見方を並べる定型。単独でも使える。",
    relatedWords: ["conversely", "however", "similarly"],
  },
  {
    id: "to say the least",
    word: "to say the least",
    level: "B2",
    partOfSpeech: "慣用表現",
    meaningsJa: ["控えめに言っても"],
    pronunciation: "/tuː seɪ ðə liːst/",
    exampleSentence: "The result was disappointing, to say the least.",
    exampleTranslationJa: "控えめに言っても、その結果は期待外れだった。",
    collocations: ["to say the least", "surprising, to say the least"],
    mnemonic: "文末に置いて、直前の控えめな表現を強める。",
    relatedWords: ["at the very least", "mildly put", "overstating"],
  },
  {
    id: "acorn",
    word: "acorn",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["どんぐり"],
    pronunciation: "/ˈeɪkɔːrn/",
    exampleSentence: "Squirrels bury acorns in autumn.",
    exampleTranslationJa: "リスは秋にどんぐりを埋める。",
    collocations: ["collect acorns", "from a tiny acorn"],
    mnemonic: "オークの実。Great oaks from little acorns grow.(大器晩成)。",
    relatedWords: ["oak", "nut", "seed"],
  },
  {
    id: "antler",
    word: "antler",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(シカの)角"],
    pronunciation: "/ˈæntlər/",
    exampleSentence: "The stag had huge antlers.",
    exampleTranslationJa: "その雄ジカは巨大な角を持っていた。",
    collocations: ["a pair of antlers", "shed its antlers"],
    mnemonic: "シカの角は毎年生え変わる。牛の角は horn で別語。",
    relatedWords: ["horn", "deer", "stag"],
  },
  {
    id: "cocoon",
    word: "cocoon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["まゆ、繭"],
    pronunciation: "/kəˈkuːn/",
    exampleSentence: "The caterpillar spins a cocoon.",
    exampleTranslationJa: "イモムシはまゆを作る。",
    collocations: ["spin a cocoon", "emerge from a cocoon"],
    mnemonic: "守られた居心地のよい場所の比喩にも使う。",
    relatedWords: ["chrysalis", "silk", "caterpillar"],
  },
  {
    id: "gill",
    word: "gill",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["えら"],
    pronunciation: "/ɡɪl/",
    exampleSentence: "Fish take in oxygen through their gills.",
    exampleTranslationJa: "魚はえらから酸素を取り入れる。",
    collocations: ["fish gills", "green about the gills"],
    mnemonic: "ふつう複数形。green about the gills は「顔色が悪い」。",
    relatedWords: ["fish", "breathe", "fin"],
  },
  {
    id: "hive",
    word: "hive",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ミツバチの巣", "(比喩)活気ある場所"],
    pronunciation: "/haɪv/",
    exampleSentence: "The office was a hive of activity.",
    exampleTranslationJa: "その事務所は活気に満ちていた。",
    collocations: ["a beehive", "a hive of activity"],
    mnemonic: "a hive of activity(蜂の巣のような賑わい)が定型。",
    relatedWords: ["beehive", "swarm", "colony"],
  },
  {
    id: "mane",
    word: "mane",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["たてがみ"],
    pronunciation: "/meɪn/",
    exampleSentence: "The lion shook its mane.",
    exampleTranslationJa: "そのライオンはたてがみを振った。",
    collocations: ["a lion's mane", "a mane of hair"],
    mnemonic: "人の豊かな髪にも a mane of hair と使う。main と同音。",
    relatedWords: ["hair", "fur", "lion"],
  },
  {
    id: "pouch",
    word: "pouch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小袋", "(有袋類の)袋"],
    pronunciation: "/paʊtʃ/",
    exampleSentence: "The kangaroo carries its young in a pouch.",
    exampleTranslationJa: "カンガルーは子を袋に入れて運ぶ。",
    collocations: ["a leather pouch", "a kangaroo's pouch"],
    mnemonic: "小さな袋。動物の育児嚢にも、たばこ入れにも使う。",
    relatedWords: ["bag", "sack", "purse"],
  },
  {
    id: "talon",
    word: "talon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(猛禽の)かぎづめ"],
    pronunciation: "/ˈtælən/",
    exampleSentence: "The eagle gripped the fish in its talons.",
    exampleTranslationJa: "そのワシは魚をかぎづめでつかんだ。",
    collocations: ["sharp talons", "in its talons"],
    mnemonic: "猛禽類の鋭いつめだけを talon と呼ぶ。犬猫は claw。",
    relatedWords: ["claw", "eagle", "grip"],
  },
  {
    id: "whisker",
    word: "whisker",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ひげ(動物の)", "わずかな差"],
    pronunciation: "/ˈwɪskər/",
    exampleSentence: "The cat twitched its whiskers.",
    exampleTranslationJa: "猫はひげをぴくりと動かした。",
    collocations: ["by a whisker", "cat's whiskers"],
    mnemonic: "by a whisker は「ごくわずかの差で」。人のあごひげは beard。",
    relatedWords: ["moustache", "hair", "margin"],
  },
  {
    id: "clover",
    word: "clover",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["クローバー、シロツメクサ"],
    pronunciation: "/ˈkloʊvər/",
    exampleSentence: "She searched for a four-leaf clover.",
    exampleTranslationJa: "彼女は四つ葉のクローバーを探した。",
    collocations: ["a four-leaf clover", "in clover"],
    mnemonic: "a four-leaf clover は幸運のしるし。in clover は「安楽に暮らして」。",
    relatedWords: ["grass", "plant", "luck"],
  },
  {
    id: "daffodil",
    word: "daffodil",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ラッパズイセン"],
    pronunciation: "/ˈdæfədɪl/",
    exampleSentence: "Daffodils appear in early spring.",
    exampleTranslationJa: "ラッパズイセンは早春に咲く。",
    collocations: ["a bunch of daffodils", "daffodils in bloom"],
    mnemonic: "英国で春の到来を告げる黄色い花。ウェールズの象徴。",
    relatedWords: ["narcissus", "flower", "spring"],
  },
  {
    id: "daisy",
    word: "daisy",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ヒナギク、デイジー"],
    pronunciation: "/ˈdeɪzi/",
    exampleSentence: "The lawn was covered in daisies.",
    exampleTranslationJa: "芝生はヒナギクで覆われていた。",
    collocations: ["a daisy chain", "fresh as a daisy"],
    mnemonic: "day's eye(日の目)が語源。as fresh as a daisy は「元気はつらつ」。",
    relatedWords: ["flower", "lawn", "chain"],
  },
  {
    id: "ivy",
    word: "ivy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ツタ、キヅタ"],
    pronunciation: "/ˈaɪvi/",
    exampleSentence: "Ivy covered the whole north wall.",
    exampleTranslationJa: "ツタが北の壁一面を覆っていた。",
    collocations: ["ivy-covered walls", "climbing ivy"],
    mnemonic: "the Ivy League は建物をツタが覆う名門大学群のこと。",
    relatedWords: ["vine", "creeper", "climber"],
  },
  {
    id: "lily",
    word: "lily",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ユリ"],
    pronunciation: "/ˈlɪli/",
    exampleSentence: "White lilies filled the church.",
    exampleTranslationJa: "白いユリが教会を埋めた。",
    collocations: ["a water lily", "white lilies"],
    mnemonic: "複数形は lilies。睡蓮は a water lily。",
    relatedWords: ["flower", "bloom", "bulb"],
  },
  {
    id: "orchid",
    word: "orchid",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ラン"],
    pronunciation: "/ˈɔːrkɪd/",
    exampleSentence: "The orchid needs very little water.",
    exampleTranslationJa: "そのランはほとんど水を必要としない。",
    collocations: ["a wild orchid", "grow orchids"],
    mnemonic: "ch を /k/ と読む /ˈɔːrkɪd/。手入れが難しい花の代表。",
    relatedWords: ["flower", "bloom", "exotic"],
  },
  {
    id: "sunflower",
    word: "sunflower",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヒマワリ"],
    pronunciation: "/ˈsʌnflaʊər/",
    exampleSentence: "The field of sunflowers stretched for miles.",
    exampleTranslationJa: "ヒマワリ畑が何マイルも続いていた。",
    collocations: ["a field of sunflowers", "sunflower oil"],
    mnemonic: "sun + flower。太陽を追って向きを変えることから。",
    relatedWords: ["flower", "seed", "oil"],
  },
  {
    id: "tulip",
    word: "tulip",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["チューリップ"],
    pronunciation: "/ˈtuːlɪp/",
    exampleSentence: "Tulips open fully in the sun.",
    exampleTranslationJa: "チューリップは日を浴びると大きく開く。",
    collocations: ["a bed of tulips", "red tulips"],
    mnemonic: "トルコ語の「ターバン」から。形が似ていることに由来。",
    relatedWords: ["flower", "bulb", "spring"],
  },
  {
    id: "cage",
    word: "cage",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["おり、かご", "閉じ込める"],
    pronunciation: "/keɪdʒ/",
    exampleSentence: "The bird escaped from its cage.",
    exampleTranslationJa: "その鳥はかごから逃げた。",
    collocations: ["a bird cage", "keep in a cage", "rattle someone's cage"],
    mnemonic: "rattle someone's cage は「人をいらつかせる」。",
    relatedWords: ["pen", "enclosure", "freedom"],
  },
  {
    id: "cushion",
    word: "cushion",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["クッション", "衝撃を和らげる"],
    pronunciation: "/ˈkʊʃn/",
    exampleSentence: "Savings can cushion the blow of job loss.",
    exampleTranslationJa: "貯蓄は失職の打撃を和らげうる。",
    collocations: ["a sofa cushion", "cushion the blow", "a financial cushion"],
    mnemonic: "動詞の「衝撃を和らげる」が実用的。a cushion は「余裕」の意味にも。",
    relatedWords: ["pad", "buffer", "impact"],
  },
  {
    id: "funnel",
    word: "funnel",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["じょうご", "(資金を)流し込む"],
    pronunciation: "/ˈfʌnl/",
    exampleSentence: "They funnelled money into the campaign.",
    exampleTranslationJa: "彼らはその運動に資金を注ぎ込んだ。",
    collocations: ["a plastic funnel", "funnel money into"],
    mnemonic: "じょうごの形から、狭い所に集めて流すこと。",
    relatedWords: ["channel", "direct", "spread"],
  },
  {
    id: "jar",
    word: "jar",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["瓶、つぼ"],
    pronunciation: "/dʒɑːr/",
    exampleSentence: "She keeps the coins in a glass jar.",
    exampleTranslationJa: "彼女は硬貨をガラス瓶に入れている。",
    collocations: ["a jam jar", "a jar of honey", "open a jar"],
    mnemonic: "口の広いふた付きの容器。細長い瓶は bottle。",
    relatedWords: ["pot", "container", "bottle"],
  },
  {
    id: "jug",
    word: "jug",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["水差し、ジョッキ"],
    pronunciation: "/dʒʌɡ/",
    exampleSentence: "Please fill the jug with water.",
    exampleTranslationJa: "水差しに水を入れてください。",
    collocations: ["a jug of water", "a milk jug"],
    mnemonic: "注ぎ口と取っ手がついた容器。米では pitcher。",
    relatedWords: ["pitcher", "container", "carafe"],
  },
  {
    id: "lantern",
    word: "lantern",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ランタン、手さげランプ"],
    pronunciation: "/ˈlæntərn/",
    exampleSentence: "A lantern hung by the door.",
    exampleTranslationJa: "戸口にランタンが下がっていた。",
    collocations: ["a paper lantern", "light a lantern"],
    mnemonic: "風よけの囲いがついた携帯用の明かり。",
    relatedWords: ["lamp", "light", "torch"],
  },
  {
    id: "lever",
    word: "lever",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["てこ、レバー", "てこで動かす"],
    pronunciation: "/ˈlevər/",
    exampleSentence: "Pull the lever to release the seat.",
    exampleTranslationJa: "そのレバーを引いて座席を外してください。",
    collocations: ["pull a lever", "use as a lever"],
    mnemonic: "leverage(てこの力・強み)と同語根。",
    relatedWords: ["handle", "bar", "leverage"],
  },
  {
    id: "mat",
    word: "mat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["マット、敷物"],
    pronunciation: "/mæt/",
    exampleSentence: "Wipe your feet on the mat.",
    exampleTranslationJa: "マットで足をふいてください。",
    collocations: ["a door mat", "a yoga mat", "a place mat"],
    mnemonic: "rug より小さく、用途が決まった敷物。",
    relatedWords: ["rug", "carpet", "pad"],
  },
  {
    id: "oar",
    word: "oar",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["オール、かい"],
    pronunciation: "/ɔːr/",
    exampleSentence: "He pulled hard on the oars.",
    exampleTranslationJa: "彼はオールを力いっぱいこいだ。",
    collocations: ["pull on the oars", "a pair of oars"],
    mnemonic: "or と同音。両手で引く長いかい。paddle は両端で水をかく。",
    relatedWords: ["paddle", "row", "boat"],
  },
  {
    id: "paddle",
    word: "paddle",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["パドル", "(浅瀬を)歩く", "こぐ"],
    pronunciation: "/ˈpædl/",
    exampleSentence: "The children paddled in the shallow water.",
    exampleTranslationJa: "子どもたちは浅瀬で水遊びをした。",
    collocations: ["paddle a canoe", "paddle in the sea"],
    mnemonic: "英では「浅瀬を歩く」の意味が日常的。カヌーのかいも paddle。",
    relatedWords: ["oar", "row", "wade"],
  },
  {
    id: "pillar",
    word: "pillar",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["柱", "中心的な存在"],
    pronunciation: "/ˈpɪlər/",
    exampleSentence: "She is a pillar of the community.",
    exampleTranslationJa: "彼女は地域の中心的な存在だ。",
    collocations: ["a stone pillar", "a pillar of society", "a pillar of strength"],
    mnemonic: "建物の柱から、支えとなる人や制度の比喩へ。",
    relatedWords: ["column", "support", "post"],
  },
  {
    id: "plank",
    word: "plank",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["厚板", "(政策の)柱"],
    pronunciation: "/plæŋk/",
    exampleSentence: "A loose plank creaked underfoot.",
    exampleTranslationJa: "ゆるんだ厚板が足下できしんだ。",
    collocations: ["a wooden plank", "a plank of the policy"],
    mnemonic: "board より厚く長い板。政策の「主要項目」の意味も。",
    relatedWords: ["board", "timber", "beam"],
  },
  {
    id: "saddle",
    word: "saddle",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["鞍(くら)", "(重荷を)負わせる"],
    pronunciation: "/ˈsædl/",
    exampleSentence: "They were saddled with huge debts.",
    exampleTranslationJa: "彼らは巨額の負債を背負わされた。",
    collocations: ["a bicycle saddle", "be saddled with"],
    mnemonic: "be saddled with は「(いやなものを)押しつけられる」。",
    relatedWords: ["seat", "burden", "relieve"],
  },
  {
    id: "spade",
    word: "spade",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["すき、シャベル"],
    pronunciation: "/speɪd/",
    exampleSentence: "He dug the bed with a spade.",
    exampleTranslationJa: "彼はすきで花壇を掘った。",
    collocations: ["dig with a spade", "call a spade a spade"],
    mnemonic: "call a spade a spade は「率直に言う」。shovel はすくう道具。",
    relatedWords: ["shovel", "dig", "garden"],
  },
  {
    id: "bib",
    word: "bib",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["よだれかけ、胸当て"],
    pronunciation: "/bɪb/",
    exampleSentence: "Put a bib on the baby before feeding.",
    exampleTranslationJa: "食べさせる前に赤ちゃんによだれかけをつけて。",
    collocations: ["a baby's bib", "a race bib"],
    mnemonic: "競技のゼッケンも bib と呼ぶ。",
    relatedWords: ["apron", "cloth", "napkin"],
  },
  {
    id: "blouse",
    word: "blouse",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ブラウス"],
    pronunciation: "/blaʊs/",
    exampleSentence: "She wore a white blouse to the interview.",
    exampleTranslationJa: "彼女は面接に白いブラウスを着ていった。",
    collocations: ["a silk blouse", "a white blouse"],
    mnemonic: "女性用のシャツ。男性用は shirt。",
    relatedWords: ["shirt", "top", "garment"],
  },
  {
    id: "bracelet",
    word: "bracelet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ブレスレット、腕輪"],
    pronunciation: "/ˈbreɪslət/",
    exampleSentence: "He gave her a silver bracelet.",
    exampleTranslationJa: "彼は彼女に銀のブレスレットを贈った。",
    collocations: ["a gold bracelet", "wear a bracelet"],
    mnemonic: "ラテン語 bracchium(腕)から。腕につける輪。",
    relatedWords: ["bangle", "jewellery", "necklace"],
  },
  {
    id: "brooch",
    word: "brooch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ブローチ"],
    pronunciation: "/broʊtʃ/",
    exampleSentence: "She pinned a brooch to her coat.",
    exampleTranslationJa: "彼女はコートにブローチを留めた。",
    collocations: ["wear a brooch", "a diamond brooch"],
    mnemonic: "つづりに反して /broʊtʃ/ と読む。留め針で服につける飾り。",
    relatedWords: ["pin", "jewellery", "badge"],
  },
  {
    id: "cardigan",
    word: "cardigan",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カーディガン"],
    pronunciation: "/ˈkɑːrdɪɡən/",
    exampleSentence: "Take a cardigan; it gets cold later.",
    exampleTranslationJa: "カーディガンを持って。あとで冷えるから。",
    collocations: ["a woollen cardigan", "put on a cardigan"],
    mnemonic: "クリミア戦争のカーディガン伯爵の名から。前開きのニット。",
    relatedWords: ["jumper", "sweater", "jacket"],
  },
  {
    id: "cloak",
    word: "cloak",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["マント", "覆い隠す"],
    pronunciation: "/kloʊk/",
    exampleSentence: "The talks were cloaked in secrecy.",
    exampleTranslationJa: "その会談は秘密のベールに包まれていた。",
    collocations: ["a black cloak", "cloaked in secrecy"],
    mnemonic: "衣服のマントから、「覆い隠す」という動詞へ。",
    relatedWords: ["cape", "mantle", "reveal"],
  },
  {
    id: "earring",
    word: "earring",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["イヤリング、ピアス"],
    pronunciation: "/ˈɪrɪŋ/",
    exampleSentence: "She lost one of her earrings.",
    exampleTranslationJa: "彼女はイヤリングの片方をなくした。",
    collocations: ["a pair of earrings", "gold earrings"],
    mnemonic: "ear + ring。穴を開けるものも英語では earring。",
    relatedWords: ["jewellery", "stud", "necklace"],
  },
  {
    id: "gown",
    word: "gown",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ガウン、式服"],
    pronunciation: "/ɡaʊn/",
    exampleSentence: "Graduates wore black gowns.",
    exampleTranslationJa: "卒業生は黒い式服を着ていた。",
    collocations: ["a dressing gown", "an evening gown", "a hospital gown"],
    mnemonic: "式典の式服、夜会服、病院着まで幅広い。",
    relatedWords: ["robe", "dress", "garment"],
  },
  {
    id: "handkerchief",
    word: "handkerchief",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ハンカチ"],
    pronunciation: "/ˈhæŋkərtʃɪf/",
    exampleSentence: "He offered her a clean handkerchief.",
    exampleTranslationJa: "彼は彼女に清潔なハンカチを差し出した。",
    collocations: ["a cotton handkerchief", "wave a handkerchief"],
    mnemonic: "hand + kerchief(頭布)。口語では hanky。",
    relatedWords: ["tissue", "cloth", "napkin"],
  },
  {
    id: "hood",
    word: "hood",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["フード、ずきん", "(米)車のボンネット"],
    pronunciation: "/hʊd/",
    exampleSentence: "Put your hood up; it is raining.",
    exampleTranslationJa: "フードをかぶって。雨が降っている。",
    collocations: ["put your hood up", "a hooded top"],
    mnemonic: "英では車の前部の覆いは bonnet、米では hood。",
    relatedWords: ["cap", "cover", "bonnet"],
  },
  {
    id: "jumper",
    word: "jumper",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["セーター(英)"],
    pronunciation: "/ˈdʒʌmpər/",
    exampleSentence: "She knitted him a woollen jumper.",
    exampleTranslationJa: "彼女は彼に毛糸のセーターを編んだ。",
    collocations: ["a woollen jumper", "put on a jumper"],
    mnemonic: "英ではセーター、米では sweater。米の jumper はジャンパースカート。",
    relatedWords: ["sweater", "pullover", "cardigan"],
  },
  {
    id: "knot",
    word: "knot",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["結び目", "結ぶ"],
    pronunciation: "/nɑːt/",
    exampleSentence: "He tied the rope in a tight knot.",
    exampleTranslationJa: "彼はロープをきつく結んだ。",
    collocations: ["tie a knot", "a knot in your stomach"],
    mnemonic: "k は読まない /nɑːt/。not と同音。船の速さの単位も knot。",
    relatedWords: ["tie", "bow", "untie"],
  },
  {
    id: "lace",
    word: "lace",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["レース(布)", "靴ひも"],
    pronunciation: "/leɪs/",
    exampleSentence: "Tie your laces before you run.",
    exampleTranslationJa: "走る前に靴ひもを結びなさい。",
    collocations: ["shoe laces", "a lace collar", "tie your laces"],
    mnemonic: "繊細な透かし織りの布と、靴ひもの両方。",
    relatedWords: ["shoelace", "ribbon", "fabric"],
  },
  {
    id: "necklace",
    word: "necklace",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ネックレス、首飾り"],
    pronunciation: "/ˈnekləs/",
    exampleSentence: "She wore a pearl necklace.",
    exampleTranslationJa: "彼女は真珠のネックレスをつけていた。",
    collocations: ["a pearl necklace", "wear a necklace"],
    mnemonic: "neck + lace。ここでの lace は「ひも」の意味。",
    relatedWords: ["chain", "pendant", "jewellery"],
  },
  {
    id: "pendant",
    word: "pendant",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ペンダント、下げ飾り"],
    pronunciation: "/ˈpendənt/",
    exampleSentence: "The pendant hung on a fine chain.",
    exampleTranslationJa: "そのペンダントは細い鎖に下がっていた。",
    collocations: ["a silver pendant", "wear a pendant"],
    mnemonic: "pend(ぶら下がる)が語根。depend・pending と同語根。",
    relatedWords: ["necklace", "charm", "chain"],
  },
  {
    id: "robe",
    word: "robe",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ローブ、上っ張り"],
    pronunciation: "/roʊb/",
    exampleSentence: "The judge put on his robe.",
    exampleTranslationJa: "裁判官はローブを着た。",
    collocations: ["a bath robe", "judicial robes"],
    mnemonic: "儀式や職務で着る長い衣。風呂上がりの bathrobe も。",
    relatedWords: ["gown", "cloak", "garment"],
  },
  {
    id: "sash",
    word: "sash",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["飾り帯", "(窓の)枠"],
    pronunciation: "/sæʃ/",
    exampleSentence: "The mayor wore a ceremonial sash.",
    exampleTranslationJa: "市長は儀礼用の飾り帯をつけていた。",
    collocations: ["a ceremonial sash", "a sash window"],
    mnemonic: "肩や腰にかける帯。上下に開く窓は a sash window。",
    relatedWords: ["belt", "band", "ribbon"],
  },
  {
    id: "stocking",
    word: "stocking",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ストッキング、長靴下"],
    pronunciation: "/ˈstɑːkɪŋ/",
    exampleSentence: "She hung a stocking by the fireplace.",
    exampleTranslationJa: "彼女は暖炉のそばに靴下をつるした。",
    collocations: ["a Christmas stocking", "a pair of stockings"],
    mnemonic: "クリスマスに贈り物を入れる靴下も stocking。",
    relatedWords: ["sock", "tights", "hosiery"],
  },
  {
    id: "strap",
    word: "strap",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ひも、ベルト", "締めつける"],
    pronunciation: "/stræp/",
    exampleSentence: "Strap the box down before you drive.",
    exampleTranslationJa: "運転する前に箱をひもで固定して。",
    collocations: ["a shoulder strap", "strap in", "a watch strap"],
    mnemonic: "strap in は「シートベルトを締める」。",
    relatedWords: ["belt", "band", "fasten"],
  },
  {
    id: "tights",
    word: "tights",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["タイツ"],
    pronunciation: "/taɪts/",
    exampleSentence: "She wore thick tights in winter.",
    exampleTranslationJa: "彼女は冬は厚手のタイツをはいていた。",
    collocations: ["a pair of tights", "black tights"],
    mnemonic: "必ず複数形。米では pantyhose と呼ぶことも。",
    relatedWords: ["stockings", "leggings", "hosiery"],
  },
  {
    id: "trousers",
    word: "trousers",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ズボン(英)"],
    pronunciation: "/ˈtraʊzərz/",
    exampleSentence: "These trousers are too long.",
    exampleTranslationJa: "このズボンは長すぎる。",
    collocations: ["a pair of trousers", "wear trousers"],
    mnemonic: "必ず複数形。米では pants。英で pants は下着を指す。",
    relatedWords: ["pants", "slacks", "shorts"],
  },
  {
    id: "veil",
    word: "veil",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ベール、覆い", "覆い隠す"],
    pronunciation: "/veɪl/",
    exampleSentence: "The talks were held behind a veil of secrecy.",
    exampleTranslationJa: "その会談は秘密のベールの陰で行われた。",
    collocations: ["a wedding veil", "a veil of secrecy", "draw a veil over"],
    mnemonic: "draw a veil over ... は「〜には触れないでおく」。",
    relatedWords: ["cover", "screen", "reveal"],
  },
  {
    id: "vest",
    word: "vest",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["肌着(英)、ベスト(米)"],
    pronunciation: "/vest/",
    exampleSentence: "He wore a vest under his shirt.",
    exampleTranslationJa: "彼はシャツの下に肌着を着ていた。",
    collocations: ["a safety vest", "a bulletproof vest"],
    mnemonic: "英では肌着、米ではベスト(英の waistcoat)。国で意味が逆転する。",
    relatedWords: ["waistcoat", "undershirt", "jacket"],
  },
  {
    id: "waistcoat",
    word: "waistcoat",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ベスト、チョッキ(英)"],
    pronunciation: "/ˈweskoʊt/",
    exampleSentence: "He wore a waistcoat under his jacket.",
    exampleTranslationJa: "彼は上着の下にベストを着ていた。",
    collocations: ["a three-piece suit with waistcoat"],
    mnemonic: "つづりに反して /ˈweskoʊt/ と読むことが多い。米では vest。",
    relatedWords: ["vest", "suit", "jacket"],
  },
  {
    id: "wig",
    word: "wig",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["かつら"],
    pronunciation: "/wɪɡ/",
    exampleSentence: "Barristers still wear wigs in court.",
    exampleTranslationJa: "法廷弁護士は今も法廷でかつらをつける。",
    collocations: ["wear a wig", "a curly wig"],
    mnemonic: "periwig の短縮。英国の法廷の伝統として有名。",
    relatedWords: ["hairpiece", "toupee", "hair"],
  },
  {
    id: "zip",
    word: "zip",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ファスナー(英)", "ファスナーを閉める"],
    pronunciation: "/zɪp/",
    exampleSentence: "Zip up your coat.",
    exampleTranslationJa: "コートのファスナーを閉めて。",
    collocations: ["zip up", "do up the zip", "a broken zip"],
    mnemonic: "英では zip、米では zipper。動詞は zip up。",
    relatedWords: ["zipper", "fasten", "unzip"],
  },
  {
    id: "gauze",
    word: "gauze",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ガーゼ"],
    pronunciation: "/ɡɔːz/",
    exampleSentence: "Cover the wound with sterile gauze.",
    exampleTranslationJa: "傷は滅菌ガーゼで覆ってください。",
    collocations: ["sterile gauze", "a gauze dressing"],
    mnemonic: "薄く目の粗い布。傷の手当てに使う。",
    relatedWords: ["bandage", "dressing", "cloth"],
  },
  {
    id: "sling",
    word: "sling",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["つり包帯", "投石器"],
    pronunciation: "/slɪŋ/",
    exampleSentence: "His arm was in a sling for six weeks.",
    exampleTranslationJa: "彼の腕は6週間つり包帯に入っていた。",
    collocations: ["an arm in a sling", "a baby sling"],
    mnemonic: "腕をつるす布。赤ちゃんの抱っこひもも a baby sling。",
    relatedWords: ["bandage", "support", "strap"],
  },
  {
    id: "splint",
    word: "splint",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["添え木"],
    pronunciation: "/splɪnt/",
    exampleSentence: "The nurse applied a splint to his finger.",
    exampleTranslationJa: "看護師は彼の指に添え木を当てた。",
    collocations: ["apply a splint", "a finger splint"],
    mnemonic: "折れた部分を動かないよう固定する板。",
    relatedWords: ["support", "brace", "cast"],
  },
  {
    id: "swab",
    word: "swab",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["綿棒、検体", "ぬぐい取る"],
    pronunciation: "/swɑːb/",
    exampleSentence: "They took a swab from her throat.",
    exampleTranslationJa: "彼らは彼女ののどから検体を採った。",
    collocations: ["a cotton swab", "take a swab"],
    mnemonic: "検査用の綿棒と、それで採った検体の両方を指す。",
    relatedWords: ["cotton bud", "sample", "test"],
  },
  {
    id: "thermometer",
    word: "thermometer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["体温計、温度計"],
    pronunciation: "/θərˈmɑːmɪtər/",
    exampleSentence: "Put the thermometer under your tongue.",
    exampleTranslationJa: "体温計を舌の下に入れてください。",
    collocations: ["a digital thermometer", "read the thermometer"],
    mnemonic: "thermo-(熱)+ meter(計器)。thermostat と同語根。",
    relatedWords: ["temperature", "gauge", "measure"],
  },
  {
    id: "tweezers",
    word: "tweezers",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ピンセット、毛抜き"],
    pronunciation: "/ˈtwiːzərz/",
    exampleSentence: "Remove the splinter with tweezers.",
    exampleTranslationJa: "ピンセットでとげを抜いてください。",
    collocations: ["a pair of tweezers", "use tweezers"],
    mnemonic: "scissors と同じく必ず複数形。a pair of tweezers。",
    relatedWords: ["pincers", "forceps", "tool"],
  },
  {
    id: "beehive",
    word: "beehive",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ミツバチの巣箱"],
    pronunciation: "/ˈbiːhaɪv/",
    exampleSentence: "The beehive stood at the end of the garden.",
    exampleTranslationJa: "巣箱は庭の奥に置かれていた。",
    collocations: ["keep a beehive", "a beehive hairstyle"],
    mnemonic: "bee + hive。高く盛った髪型も a beehive と呼ぶ。",
    relatedWords: ["hive", "apiary", "bee"],
  },
  {
    id: "lotus",
    word: "lotus",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハス"],
    pronunciation: "/ˈloʊtəs/",
    exampleSentence: "A lotus flowered in the temple pond.",
    exampleTranslationJa: "寺の池でハスが花を咲かせた。",
    collocations: ["a lotus flower", "the lotus position"],
    mnemonic: "座禅の結跏趺坐は the lotus position。",
    relatedWords: ["water lily", "flower", "pond"],
  },
]
