import type { VocabularyEntry } from '../types'

// 増補 第17弾。音と動きを表す動詞、家族・人生の出来事、時を表す語。
// 音の語は「どんな音か」を覚えるヒントで具体的に書き分ける。
export const plus17: VocabularyEntry[] = [
  {
    id: "growl",
    word: "growl",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(犬などが)うなる", "不機嫌に言う"],
    pronunciation: "/ɡraʊl/",
    exampleSentence: "The dog began to growl at the stranger.",
    exampleTranslationJa: "犬は見知らぬ人にうなり始めた。",
    collocations: ["a low growl", "growl at someone", "growl a warning"],
    mnemonic: "低く長く出す威嚇の声。腹が鳴るのも My stomach growled.",
    relatedWords: ["snarl", "rumble", "bark"],
  },
  {
    id: "howl",
    word: "howl",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["遠ぼえする、泣きわめく", "(風が)うなる"],
    pronunciation: "/haʊl/",
    exampleSentence: "Wolves howl at night in these hills.",
    exampleTranslationJa: "この丘では夜、オオカミが遠ぼえする。",
    collocations: ["howl with laughter", "the wind howls", "a howl of pain"],
    mnemonic: "長く尾を引く声。風にも笑い声にも使う。",
    relatedWords: ["wail", "yell", "cry"],
  },
  {
    id: "purr",
    word: "purr",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(猫が)のどを鳴らす", "(機械が)静かに回る"],
    pronunciation: "/pɜːr/",
    exampleSentence: "The cat began to purr on her lap.",
    exampleTranslationJa: "猫は彼女のひざでのどを鳴らし始めた。",
    collocations: ["a contented purr", "the engine purrs"],
    mnemonic: "満足しているときの音。よく調整された機械の音にも使う。",
    relatedWords: ["hum", "rumble", "meow"],
  },
  {
    id: "hiss",
    word: "hiss",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["シューッと音を立てる", "(不満で)シッと言う"],
    pronunciation: "/hɪs/",
    exampleSentence: "Steam began to hiss from the valve.",
    exampleTranslationJa: "弁から蒸気がシューッと出始めた。",
    collocations: ["hiss with steam", "a hiss of disapproval"],
    mnemonic: "ヘビ・蒸気・観客の不満、どれも同じ音の語。",
    relatedWords: ["whistle", "sizzle", "boo"],
  },
  {
    id: "chirp",
    word: "chirp",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(小鳥や虫が)チッチッと鳴く"],
    pronunciation: "/tʃɜːrp/",
    exampleSentence: "Sparrows chirp outside the window at dawn.",
    exampleTranslationJa: "夜明けに窓の外でスズメがさえずる。",
    collocations: ["birds chirp", "a cheerful chirp"],
    mnemonic: "短く高い鳴き声。長く続く歌のような声は sing。",
    relatedWords: ["tweet", "chirrup", "sing"],
  },
  {
    id: "buzz",
    word: "buzz",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ブンブン鳴る", "ざわめき、うわさ"],
    pronunciation: "/bʌz/",
    exampleSentence: "Flies buzz around the fruit.",
    exampleTranslationJa: "ハエが果物のまわりをブンブン飛ぶ。",
    collocations: ["a buzz of excitement", "the phone buzzes", "create a buzz"],
    mnemonic: "虫の羽音から、話題の「ざわめき」へ。携帯の振動音も buzz。",
    relatedWords: ["hum", "drone", "excitement"],
  },
  {
    id: "croak",
    word: "croak",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(カエルが)ゲロゲロ鳴く", "しゃがれ声で言う"],
    pronunciation: "/kroʊk/",
    exampleSentence: "Frogs croak all night by the pond.",
    exampleTranslationJa: "池のそばで一晩中カエルが鳴く。",
    collocations: ["frogs croak", "croak a reply"],
    mnemonic: "カエルの声と、風邪でつぶれた声が同じ語。",
    relatedWords: ["rasp", "grunt", "frog"],
  },
  {
    id: "roar",
    word: "roar",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ほえる、とどろく", "ほえ声、轟音"],
    pronunciation: "/rɔːr/",
    exampleSentence: "The crowd roared when the goal went in.",
    exampleTranslationJa: "得点が入ると観衆がどよめいた。",
    collocations: ["a lion roars", "a roar of laughter", "the roar of the engine"],
    mnemonic: "ライオン、群衆、エンジンなど、腹に響く大きな音。",
    relatedWords: ["bellow", "thunder", "shout"],
  },
  {
    id: "squeak",
    word: "squeak",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["キーキー鳴る", "かすれた高い声"],
    pronunciation: "/skwiːk/",
    exampleSentence: "The door squeaks every time you open it.",
    exampleTranslationJa: "その戸は開けるたびにキーッと鳴る。",
    collocations: ["a mouse squeaks", "a squeaky door", "squeak through"],
    mnemonic: "油の切れた蝶番やネズミの声。squeak through は「かろうじて通る」。",
    relatedWords: ["creak", "screech", "squeal"],
  },
  {
    id: "bang",
    word: "bang",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["どんと打つ", "バンという音"],
    pronunciation: "/bæŋ/",
    exampleSentence: "He banged the door shut.",
    exampleTranslationJa: "彼は戸をバタンと閉めた。",
    collocations: ["bang the door", "a loud bang", "bang your head"],
    mnemonic: "一回の大きな衝突音。go with a bang は「大成功に終わる」。",
    relatedWords: ["slam", "thump", "crash"],
  },
  {
    id: "clatter",
    word: "clatter",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ガタガタ鳴る", "がちゃがちゃいう音"],
    pronunciation: "/ˈklætər/",
    exampleSentence: "Plates clatter in the kitchen sink.",
    exampleTranslationJa: "台所の流しで皿がガチャガチャ鳴る。",
    collocations: ["a clatter of plates", "clatter down the stairs"],
    mnemonic: "かたい物がぶつかり合って続く音。皿や馬のひづめ。",
    relatedWords: ["rattle", "clang", "clank"],
  },
  {
    id: "clang",
    word: "clang",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ガーンと鳴る", "金属音"],
    pronunciation: "/klæŋ/",
    exampleSentence: "The gate clangs when it shuts.",
    exampleTranslationJa: "その門は閉まるとガーンと鳴る。",
    collocations: ["a metallic clang", "the bell clangs"],
    mnemonic: "金属どうしが当たる一発の響き。鐘や鉄の門。",
    relatedWords: ["clatter", "ring", "chime"],
  },
  {
    id: "rattle",
    word: "rattle",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ガタガタ鳴る", "(人を)動揺させる"],
    pronunciation: "/ˈrætl/",
    exampleSentence: "The windows rattle in the wind.",
    exampleTranslationJa: "風で窓がガタガタ鳴る。",
    collocations: ["rattle the windows", "rattle someone", "a death rattle"],
    mnemonic: "小刻みに揺れて鳴る音。動詞で「動揺させる」意味も重要。",
    relatedWords: ["shake", "clatter", "unnerve"],
  },
  {
    id: "rustle",
    word: "rustle",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["カサカサ音を立てる"],
    pronunciation: "/ˈrʌsl/",
    exampleSentence: "Leaves rustle underfoot in autumn.",
    exampleTranslationJa: "秋には足下で落ち葉がカサカサ鳴る。",
    collocations: ["leaves rustle", "a rustle of paper"],
    mnemonic: "t は読まない /ˈrʌsl/。紙や葉のこすれる小さな音。",
    relatedWords: ["whisper", "swish", "crackle"],
  },
  {
    id: "creak",
    word: "creak",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ギシギシ鳴る"],
    pronunciation: "/kriːk/",
    exampleSentence: "The old stairs creak under your weight.",
    exampleTranslationJa: "その古い階段は体重をかけるときしむ。",
    collocations: ["the floor creaks", "a creaking door"],
    mnemonic: "creek(小川)と同音。古い木材のきしむ音。",
    relatedWords: ["squeak", "groan", "grind"],
  },
  {
    id: "squeal",
    word: "squeal",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["キーッと甲高い音を出す", "悲鳴を上げる"],
    pronunciation: "/skwiːl/",
    exampleSentence: "The tyres squealed as the car turned.",
    exampleTranslationJa: "車が曲がるときタイヤがキーッと鳴った。",
    collocations: ["squeal with delight", "tyres squeal"],
    mnemonic: "squeak より長く大きい。喜びの叫びにも使う。",
    relatedWords: ["screech", "shriek", "squeak"],
  },
  {
    id: "screech",
    word: "screech",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["キーッと耳障りな音を出す"],
    pronunciation: "/skriːtʃ/",
    exampleSentence: "The car screeched to a halt.",
    exampleTranslationJa: "車はキーッと音を立てて止まった。",
    collocations: ["screech to a halt", "a screech of brakes"],
    mnemonic: "screech to a halt(急停止する)の形で頻出。",
    relatedWords: ["squeal", "shriek", "scream"],
  },
  {
    id: "thud",
    word: "thud",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ドスンという鈍い音"],
    pronunciation: "/θʌd/",
    exampleSentence: "The book fell to the floor with a thud.",
    exampleTranslationJa: "本はドサッと床に落ちた。",
    collocations: ["with a thud", "a dull thud", "land with a thud"],
    mnemonic: "重い物が落ちる鈍い音。響かない、低い一発。",
    relatedWords: ["thump", "bump", "bang"],
  },
  {
    id: "thump",
    word: "thump",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ドンと打つ、どきどきする", "ドンという音"],
    pronunciation: "/θʌmp/",
    exampleSentence: "Her heart was thumping as she waited.",
    exampleTranslationJa: "待つ間、彼女の心臓はどきどきしていた。",
    collocations: ["heart thumps", "thump the table", "a loud thump"],
    mnemonic: "thud より「打つ動作」寄り。心臓の鼓動にも使う。",
    relatedWords: ["thud", "pound", "beat"],
  },
  {
    id: "splash",
    word: "splash",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["水をはねかす", "水しぶき", "(記事の)大きな扱い"],
    pronunciation: "/splæʃ/",
    exampleSentence: "The children splash in the shallow water.",
    exampleTranslationJa: "子どもたちが浅瀬で水しぶきを上げる。",
    collocations: ["splash water", "a splash of colour", "make a splash"],
    mnemonic: "make a splash は「あっと言わせる」。a splash of ... は「少量の」。",
    relatedWords: ["spray", "spatter", "soak"],
  },
  {
    id: "trickle",
    word: "trickle",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ちょろちょろ流れる", "細い流れ"],
    pronunciation: "/ˈtrɪkl/",
    exampleSentence: "Water trickles down the wall after rain.",
    exampleTranslationJa: "雨のあと、壁を水がちょろちょろ伝う。",
    collocations: ["trickle down", "a trickle of water", "a trickle of visitors"],
    mnemonic: "人が少しずつ来るのも a trickle。trickle-down は経済の「したたり落ち」。",
    relatedWords: ["drip", "seep", "flow"],
  },
  {
    id: "gush",
    word: "gush",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["どっと噴き出す", "感情を込めて話す"],
    pronunciation: "/ɡʌʃ/",
    exampleSentence: "Water began to gush from the broken pipe.",
    exampleTranslationJa: "割れた管から水がどっと噴き出した。",
    collocations: ["gush out", "gush with praise", "a gush of water"],
    mnemonic: "trickle の正反対。人が「べた褒めする」意味にもなる。",
    relatedWords: ["spurt", "pour", "trickle"],
  },
  {
    id: "drip",
    word: "drip",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["したたる", "しずく", "点滴"],
    pronunciation: "/drɪp/",
    exampleSentence: "The tap drips all night.",
    exampleTranslationJa: "蛇口が一晩中したたる。",
    collocations: ["a dripping tap", "drip with sweat", "on a drip"],
    mnemonic: "一滴ずつ落ちること。病院の点滴も a drip。",
    relatedWords: ["trickle", "drop", "leak"],
  },
  {
    id: "ooze",
    word: "ooze",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["じわじわしみ出る", "(自信などを)にじませる"],
    pronunciation: "/uːz/",
    exampleSentence: "Mud oozed between his toes.",
    exampleTranslationJa: "泥が彼の足の指の間からにじみ出た。",
    collocations: ["ooze out", "ooze confidence", "ooze from"],
    mnemonic: "ゆっくり粘り気のあるものが出る。ooze confidence は「自信たっぷり」。",
    relatedWords: ["seep", "leak", "exude"],
  },
  {
    id: "seep",
    word: "seep",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["しみ込む、しみ出る"],
    pronunciation: "/siːp/",
    exampleSentence: "Water seeped through the ceiling.",
    exampleTranslationJa: "水が天井からしみ出た。",
    collocations: ["seep into", "seep through", "seep away"],
    mnemonic: "ooze より静かにゆっくり。液体にも情報にも使う。",
    relatedWords: ["ooze", "leak", "filter"],
  },
  {
    id: "spurt",
    word: "spurt",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ほとばしる", "急な伸び"],
    pronunciation: "/spɜːrt/",
    exampleSentence: "Blood spurted from the cut.",
    exampleTranslationJa: "切り傷から血がほとばしった。",
    collocations: ["a growth spurt", "spurt out", "a final spurt"],
    mnemonic: "a growth spurt は「急に背が伸びること」。短く勢いよく。",
    relatedWords: ["gush", "squirt", "burst"],
  },
  {
    id: "spray",
    word: "spray",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["吹きかける", "しぶき、スプレー"],
    pronunciation: "/spreɪ/",
    exampleSentence: "Spray the leaves with water each morning.",
    exampleTranslationJa: "毎朝、葉に水を吹きかけてください。",
    collocations: ["spray paint", "sea spray", "a spray bottle"],
    mnemonic: "細かい粒にして飛ばすこと。海のしぶきも sea spray。",
    relatedWords: ["mist", "sprinkle", "splash"],
  },
  {
    id: "swirl",
    word: "swirl",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["渦を巻く", "渦"],
    pronunciation: "/swɜːrl/",
    exampleSentence: "Leaves swirled in the wind.",
    exampleTranslationJa: "落ち葉が風で渦を巻いた。",
    collocations: ["swirl around", "a swirl of colour", "swirling snow"],
    mnemonic: "円を描いて回りながら動く。液体にも雪にもうわさにも使う。",
    relatedWords: ["whirl", "spin", "eddy"],
  },
  {
    id: "ripple",
    word: "ripple",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["さざ波が立つ", "さざ波、波及"],
    pronunciation: "/ˈrɪpl/",
    exampleSentence: "A breeze rippled the surface of the lake.",
    exampleTranslationJa: "そよ風が湖面にさざ波を立てた。",
    collocations: ["a ripple effect", "ripples spread", "a ripple of laughter"],
    mnemonic: "a ripple effect は「波及効果」。小さな波が広がるイメージ。",
    relatedWords: ["wave", "wrinkle", "spread"],
  },
  {
    id: "flicker",
    word: "flicker",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ちらちら光る、明滅する", "かすかなきざし"],
    pronunciation: "/ˈflɪkər/",
    exampleSentence: "The candle flickered in the draught.",
    exampleTranslationJa: "ろうそくがすきま風でちらついた。",
    collocations: ["a flicker of hope", "lights flicker", "flicker on and off"],
    mnemonic: "a flicker of hope は「かすかな希望」。安定しない光。",
    relatedWords: ["glimmer", "waver", "flash"],
  },
  {
    id: "blaze",
    word: "blaze",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["赤々と燃える", "炎、火事"],
    pronunciation: "/bleɪz/",
    exampleSentence: "A fire blazed in the hearth.",
    exampleTranslationJa: "暖炉で火が赤々と燃えていた。",
    collocations: ["a blazing fire", "tackle a blaze", "blaze a trail"],
    mnemonic: "blaze a trail は「先駆けとなる」。強く明るい燃え方。",
    relatedWords: ["burn", "flame", "glow"],
  },
  {
    id: "glow",
    word: "glow",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ぼうっと光る、赤らむ", "輝き"],
    pronunciation: "/ɡloʊ/",
    exampleSentence: "Embers glow in the fireplace.",
    exampleTranslationJa: "暖炉で残り火がぼうっと光っている。",
    collocations: ["a warm glow", "glow with pride", "glowing reviews"],
    mnemonic: "炎を出さずに光ること。glowing reviews は「絶賛の評」。",
    relatedWords: ["shine", "radiate", "gleam"],
  },
  {
    id: "gleam",
    word: "gleam",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["きらりと光る", "かすかな光"],
    pronunciation: "/ɡliːm/",
    exampleSentence: "The polished floor gleamed in the sunlight.",
    exampleTranslationJa: "磨かれた床が日差しにきらりと光った。",
    collocations: ["a gleam of light", "eyes gleam", "gleaming white"],
    mnemonic: "表面がなめらかで反射する光。目が光るのも gleam。",
    relatedWords: ["shine", "glint", "glow"],
  },
  {
    id: "sparkle",
    word: "sparkle",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["きらきら光る", "輝き"],
    pronunciation: "/ˈspɑːrkl/",
    exampleSentence: "Frost sparkled on the grass.",
    exampleTranslationJa: "霜が草の上できらきら光っていた。",
    collocations: ["eyes sparkle", "sparkling water", "sparkle with wit"],
    mnemonic: "小さな光が点々と瞬く。炭酸水は sparkling water。",
    relatedWords: ["glitter", "twinkle", "shine"],
  },
  {
    id: "glitter",
    word: "glitter",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["きらきら輝く", "きらめき、ラメ"],
    pronunciation: "/ˈɡlɪtər/",
    exampleSentence: "All that glitters is not gold.",
    exampleTranslationJa: "光るもの必ずしも金ならず。",
    collocations: ["glitter with jewels", "a glitter of gold"],
    mnemonic: "ことわざ All that glitters is not gold. で覚える。",
    relatedWords: ["sparkle", "shimmer", "shine"],
  },
  {
    id: "shimmer",
    word: "shimmer",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["かすかに揺らめいて光る"],
    pronunciation: "/ˈʃɪmər/",
    exampleSentence: "The road shimmered in the heat.",
    exampleTranslationJa: "道路が熱でゆらめいて見えた。",
    collocations: ["shimmer in the heat", "a shimmer of light"],
    mnemonic: "光がゆらゆら揺れる。陽炎や水面の反射に使う。",
    relatedWords: ["gleam", "glisten", "sparkle"],
  },
  {
    id: "dazzle",
    word: "dazzle",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["目をくらませる", "感嘆させる"],
    pronunciation: "/ˈdæzl/",
    exampleSentence: "Oncoming headlights dazzled him.",
    exampleTranslationJa: "対向車のヘッドライトが彼の目をくらませた。",
    collocations: ["dazzle the audience", "be dazzled by"],
    mnemonic: "強すぎる光で見えなくすること。人を「圧倒する」意味にも。",
    relatedWords: ["blind", "impress", "glare"],
  },
  {
    id: "crumble",
    word: "crumble",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["ぼろぼろ崩れる", "(体制が)崩壊する"],
    pronunciation: "/ˈkrʌmbl/",
    exampleSentence: "The old wall is starting to crumble.",
    exampleTranslationJa: "その古い壁は崩れ始めている。",
    collocations: ["crumble away", "crumble into dust", "support crumbles"],
    mnemonic: "crumb(パンくず)と同語根。粉々になって崩れること。",
    relatedWords: ["disintegrate", "collapse", "crumb"],
  },
  {
    id: "flake",
    word: "flake",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["薄片", "はがれ落ちる"],
    pronunciation: "/fleɪk/",
    exampleSentence: "Paint flakes off the window frame.",
    exampleTranslationJa: "窓枠から塗料がはがれ落ちる。",
    collocations: ["flakes of snow", "paint flakes off", "cornflakes"],
    mnemonic: "薄く平たいかけら。雪片は snowflake。",
    relatedWords: ["chip", "peel", "scale"],
  },
  {
    id: "dent",
    word: "dent",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["へこみ", "へこませる、傷つける"],
    pronunciation: "/dent/",
    exampleSentence: "There is a small dent in the car door.",
    exampleTranslationJa: "車のドアに小さなへこみがある。",
    collocations: ["a dent in the door", "make a dent in", "dent your confidence"],
    mnemonic: "make a dent in ... は「〜を少し減らす・進める」。",
    relatedWords: ["hollow", "damage", "bump"],
  },
  {
    id: "flatten",
    word: "flatten",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["平らにする、押しつぶす"],
    pronunciation: "/ˈflætn/",
    exampleSentence: "The storm flattened the crops.",
    exampleTranslationJa: "嵐が作物をなぎ倒した。",
    collocations: ["flatten a box", "flatten the curve", "be flattened"],
    mnemonic: "flat(平らな)+ -en。flatten the curve は感染症報道の定番。",
    relatedWords: ["level", "crush", "smooth"],
  },
  {
    id: "wobble",
    word: "wobble",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ぐらぐらする", "ぐらつき"],
    pronunciation: "/ˈwɑːbl/",
    exampleSentence: "The table wobbles on the uneven floor.",
    exampleTranslationJa: "でこぼこの床でテーブルがぐらつく。",
    collocations: ["wobble on your feet", "a wobble in the market"],
    mnemonic: "安定せず左右に揺れる。決意や市場の「ぐらつき」にも。",
    relatedWords: ["shake", "totter", "steady"],
  },
  {
    id: "tilt",
    word: "tilt",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["傾ける、傾く", "傾き"],
    pronunciation: "/tɪlt/",
    exampleSentence: "She tilted her head to one side.",
    exampleTranslationJa: "彼女は首を片方に傾げた。",
    collocations: ["tilt your head", "tilt the balance", "at a tilt"],
    mnemonic: "tilt the balance は「形勢を傾ける」。角度をつけること。",
    relatedWords: ["lean", "slant", "incline"],
  },
  {
    id: "topple",
    word: "topple",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["倒れる、倒す", "(政権を)転覆させる"],
    pronunciation: "/ˈtɑːpl/",
    exampleSentence: "The pile of books toppled over.",
    exampleTranslationJa: "積み上げた本が倒れた。",
    collocations: ["topple over", "topple a government", "topple from power"],
    mnemonic: "物理的に倒れることと、政権を倒すことの両方。",
    relatedWords: ["overturn", "collapse", "overthrow"],
  },
  {
    id: "crumple",
    word: "crumple",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["くしゃくしゃにする、くずおれる"],
    pronunciation: "/ˈkrʌmpl/",
    exampleSentence: "He crumpled the letter and threw it away.",
    exampleTranslationJa: "彼は手紙をくしゃくしゃにして捨てた。",
    collocations: ["crumple a piece of paper", "crumple to the ground"],
    mnemonic: "紙を丸めることと、人がくずおれることの両方。",
    relatedWords: ["crush", "wrinkle", "collapse"],
  },
  {
    id: "bob",
    word: "bob",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["上下に揺れる、ひょいと動く"],
    pronunciation: "/bɑːb/",
    exampleSentence: "A cork bobbed on the water.",
    exampleTranslationJa: "コルクが水面で上下に揺れていた。",
    collocations: ["bob up and down", "bob about", "bob your head"],
    mnemonic: "軽いものが水面で上下すること。うなずくのも bob。",
    relatedWords: ["float", "nod", "dip"],
  },
  {
    id: "whirl",
    word: "whirl",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ぐるぐる回る", "旋回、めまぐるしさ"],
    pronunciation: "/wɜːrl/",
    exampleSentence: "Snow whirled around the lamp post.",
    exampleTranslationJa: "雪が街灯のまわりでぐるぐる舞った。",
    collocations: ["whirl around", "a whirl of activity", "my head is in a whirl"],
    mnemonic: "swirl より速く激しい回転。頭が混乱するのも in a whirl。",
    relatedWords: ["spin", "swirl", "twirl"],
  },
  {
    id: "revolve",
    word: "revolve",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["回転する", "(revolve around で)〜を中心とする"],
    pronunciation: "/rɪˈvɑːlv/",
    exampleSentence: "The Earth revolves around the Sun.",
    exampleTranslationJa: "地球は太陽のまわりを回る。",
    collocations: ["revolve around", "a revolving door", "revolve slowly"],
    mnemonic: "revolution(回転・革命)と同語根。話題が「〜を中心に回る」意味も。",
    relatedWords: ["rotate", "spin", "orbit"],
  },
  {
    id: "tumble",
    word: "tumble",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["転がり落ちる", "急落する"],
    pronunciation: "/ˈtʌmbl/",
    exampleSentence: "Share prices tumbled after the news.",
    exampleTranslationJa: "その知らせのあと株価は急落した。",
    collocations: ["tumble down", "prices tumble", "take a tumble"],
    mnemonic: "転げ落ちる動きから、価格の急落へ。",
    relatedWords: ["fall", "plunge", "roll"],
  },
  {
    id: "uncle",
    word: "uncle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["おじ"],
    pronunciation: "/ˈʌŋkl/",
    exampleSentence: "My uncle taught me to fish.",
    exampleTranslationJa: "おじが釣りを教えてくれた。",
    collocations: ["my uncle", "a great-uncle", "an uncle by marriage"],
    mnemonic: "父母の兄弟にも、その配偶者にも使う。おばは aunt。",
    relatedWords: ["aunt", "nephew", "relative"],
  },
  {
    id: "aunt",
    word: "aunt",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["おば"],
    pronunciation: "/ænt/",
    exampleSentence: "My aunt lives in Scotland.",
    exampleTranslationJa: "おばはスコットランドに住んでいる。",
    collocations: ["my aunt", "a great-aunt", "an aunt by marriage"],
    mnemonic: "アリの ant と同音になる発音もある。おじは uncle。",
    relatedWords: ["uncle", "niece", "relative"],
  },
  {
    id: "nephew",
    word: "nephew",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["おい(兄弟姉妹の息子)"],
    pronunciation: "/ˈnefjuː/",
    exampleSentence: "He took his nephew to the match.",
    exampleTranslationJa: "彼はおいを試合に連れていった。",
    collocations: ["my nephew", "a young nephew"],
    mnemonic: "ph を /f/ と読む。姉妹の娘は niece。",
    relatedWords: ["niece", "uncle", "cousin"],
  },
  {
    id: "niece",
    word: "niece",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["めい(兄弟姉妹の娘)"],
    pronunciation: "/niːs/",
    exampleSentence: "Her niece is starting school this year.",
    exampleTranslationJa: "彼女のめいは今年入学する。",
    collocations: ["my niece", "a baby niece"],
    mnemonic: "つづりは i が先(ie)。おいは nephew。",
    relatedWords: ["nephew", "aunt", "cousin"],
  },
  {
    id: "cousin",
    word: "cousin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["いとこ"],
    pronunciation: "/ˈkʌzn/",
    exampleSentence: "We visited our cousins in Wales.",
    exampleTranslationJa: "私たちはウェールズのいとこを訪ねた。",
    collocations: ["a first cousin", "a distant cousin", "my cousin"],
    mnemonic: "s は /z/。男女どちらにも使う。またいとこは second cousin。",
    relatedWords: ["relative", "family", "kin"],
  },
  {
    id: "stepmother",
    word: "stepmother",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["継母"],
    pronunciation: "/ˈstepmʌðər/",
    exampleSentence: "Her stepmother came to the wedding.",
    exampleTranslationJa: "彼女の継母が結婚式に来た。",
    collocations: ["a wicked stepmother", "my stepmother"],
    mnemonic: "step- は血のつながらない家族関係を表す。継父は stepfather。",
    relatedWords: ["stepfather", "stepson", "family"],
  },
  {
    id: "stepfather",
    word: "stepfather",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["継父"],
    pronunciation: "/ˈstepfɑːðər/",
    exampleSentence: "His stepfather raised him from the age of six.",
    exampleTranslationJa: "彼の継父は6歳から彼を育てた。",
    collocations: ["my stepfather", "a kind stepfather"],
    mnemonic: "stepmother と対。子は stepson / stepdaughter。",
    relatedWords: ["stepmother", "stepdaughter", "family"],
  },
  {
    id: "in-laws",
    word: "in-laws",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["義理の親族"],
    pronunciation: "/ˈɪn lɔːz/",
    exampleSentence: "We spend Christmas with my in-laws.",
    exampleTranslationJa: "私たちはクリスマスを義理の家族と過ごす。",
    collocations: ["my in-laws", "stay with the in-laws"],
    mnemonic: "個別には mother-in-law(義母)、brother-in-law(義兄弟)。",
    relatedWords: ["relatives", "family", "marriage"],
  },
  {
    id: "fiancé",
    word: "fiancé",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["婚約者(男性)"],
    pronunciation: "/fiˈɑːnseɪ/",
    exampleSentence: "She introduced her fiancé to the family.",
    exampleTranslationJa: "彼女は婚約者を家族に紹介した。",
    collocations: ["her fiancé", "meet the fiancé"],
    mnemonic: "フランス語から。女性は fiancée と e を重ねる。発音は同じ。",
    relatedWords: ["fiancée", "engagement", "partner"],
  },
  {
    id: "fiancée",
    word: "fiancée",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["婚約者(女性)"],
    pronunciation: "/fiˈɑːnseɪ/",
    exampleSentence: "His fiancée works at the hospital.",
    exampleTranslationJa: "彼の婚約者は病院で働いている。",
    collocations: ["his fiancée", "the bride and her fiancée"],
    mnemonic: "男性の fiancé と発音は同じ。つづりの e の数だけが違う。",
    relatedWords: ["fiancé", "engagement", "partner"],
  },
  {
    id: "widower",
    word: "widower",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["男やもめ、夫を亡くした人に対する語"],
    pronunciation: "/ˈwɪdoʊər/",
    exampleSentence: "He has been a widower for ten years.",
    exampleTranslationJa: "彼は妻を亡くして10年になる。",
    collocations: ["a recent widower", "left a widower"],
    mnemonic: "妻を亡くした男性。女性は widow。-er がつくほうが男性。",
    relatedWords: ["widow", "bereavement", "spouse"],
  },
  {
    id: "orphan",
    word: "orphan",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["孤児", "孤児にする"],
    pronunciation: "/ˈɔːrfn/",
    exampleSentence: "The war left thousands of children orphans.",
    exampleTranslationJa: "戦争は何千人もの子を孤児にした。",
    collocations: ["an orphan child", "be orphaned by", "an orphanage"],
    mnemonic: "施設は orphanage。be orphaned で「親を失う」。",
    relatedWords: ["orphanage", "parentless", "adopt"],
  },
  {
    id: "guardian",
    word: "guardian",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["後見人、保護者", "守る人"],
    pronunciation: "/ˈɡɑːrdiən/",
    exampleSentence: "A legal guardian must sign the form.",
    exampleTranslationJa: "法定後見人が用紙に署名する必要がある。",
    collocations: ["a legal guardian", "a parent or guardian"],
    mnemonic: "学校の書類の a parent or guardian が定型。guard(守る)から。",
    relatedWords: ["custodian", "protector", "parent"],
  },
  {
    id: "heir",
    word: "heir",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["相続人、後継者"],
    pronunciation: "/er/",
    exampleSentence: "She is the sole heir to the estate.",
    exampleTranslationJa: "彼女はその財産の唯一の相続人だ。",
    collocations: ["the rightful heir", "an heir to the throne", "the sole heir"],
    mnemonic: "h は読まない /er/。air と同音。女性形は heiress。",
    relatedWords: ["successor", "inheritance", "beneficiary"],
  },
  {
    id: "teenager",
    word: "teenager",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["10代の若者(13〜19歳)"],
    pronunciation: "/ˈtiːneɪdʒər/",
    exampleSentence: "The film is aimed at teenagers.",
    exampleTranslationJa: "その映画は10代を対象にしている。",
    collocations: ["a typical teenager", "teenagers today"],
    mnemonic: "thirteen 〜 nineteen の -teen から。12歳以下は含まない。",
    relatedWords: ["adolescent", "youth", "teen"],
  },
  {
    id: "bachelor",
    word: "bachelor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["独身男性", "学士"],
    pronunciation: "/ˈbætʃələr/",
    exampleSentence: "He remained a bachelor all his life.",
    exampleTranslationJa: "彼は生涯独身のままだった。",
    collocations: ["a confirmed bachelor", "a bachelor's degree", "a bachelor flat"],
    mnemonic: "a bachelor's degree(学士号)の意味も重要。",
    relatedWords: ["single", "degree", "unmarried"],
  },
  {
    id: "newlywed",
    word: "newlywed",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["新婚の人"],
    pronunciation: "/ˈnuːliwed/",
    exampleSentence: "The newlyweds moved into a small flat.",
    exampleTranslationJa: "新婚の二人は小さな部屋に移り住んだ。",
    collocations: ["the newlyweds", "a newlywed couple"],
    mnemonic: "newly(新しく)+ wed(結婚した)。ふつう複数形。",
    relatedWords: ["bride", "groom", "marriage"],
  },
  {
    id: "acquaintance",
    word: "acquaintance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["知り合い", "面識"],
    pronunciation: "/əˈkweɪntəns/",
    exampleSentence: "He is an acquaintance rather than a friend.",
    exampleTranslationJa: "彼は友人というより知り合いだ。",
    collocations: ["a mutual acquaintance", "make the acquaintance of", "a passing acquaintance"],
    mnemonic: "friend より距離がある。make someone's acquaintance は「知り合いになる」。",
    relatedWords: ["contact", "associate", "friend"],
  },
  {
    id: "comrade",
    word: "comrade",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["同志、仲間"],
    pronunciation: "/ˈkɑːmræd/",
    exampleSentence: "He lost two comrades in the campaign.",
    exampleTranslationJa: "彼はその作戦で2人の戦友を失った。",
    collocations: ["a former comrade", "comrades in arms"],
    mnemonic: "もとは「同じ部屋の者」。軍隊や政治運動の仲間に使う。",
    relatedWords: ["companion", "ally", "colleague"],
  },
  {
    id: "foe",
    word: "foe",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["敵(文語)"],
    pronunciation: "/foʊ/",
    exampleSentence: "He treated every rival as a foe.",
    exampleTranslationJa: "彼はどの競争相手も敵とみなした。",
    collocations: ["friend or foe", "a sworn foe", "old foes"],
    mnemonic: "enemy の文語。friend or foe(味方か敵か)の対で使う。",
    relatedWords: ["enemy", "adversary", "friend"],
  },
  {
    id: "courtship",
    word: "courtship",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["求愛、交際期間"],
    pronunciation: "/ˈkɔːrtʃɪp/",
    exampleSentence: "Their courtship lasted only three months.",
    exampleTranslationJa: "彼らの交際期間はわずか3か月だった。",
    collocations: ["a long courtship", "courtship behaviour"],
    mnemonic: "court(言い寄る)+ -ship。動物の求愛行動にも使う。",
    relatedWords: ["romance", "dating", "engagement"],
  },
  {
    id: "honeymoon",
    word: "honeymoon",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["新婚旅行", "(比喩)蜜月期間"],
    pronunciation: "/ˈhʌnimuːn/",
    exampleSentence: "They went to Italy on honeymoon.",
    exampleTranslationJa: "彼らは新婚旅行でイタリアへ行った。",
    collocations: ["go on honeymoon", "a honeymoon period"],
    mnemonic: "a honeymoon period は「就任直後の批判されない時期」。",
    relatedWords: ["wedding", "marriage", "holiday"],
  },
  {
    id: "cremation",
    word: "cremation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["火葬"],
    pronunciation: "/krɪˈmeɪʃn/",
    exampleSentence: "Cremation is now more common than burial.",
    exampleTranslationJa: "今では火葬のほうが土葬より一般的だ。",
    collocations: ["a private cremation", "cremation or burial"],
    mnemonic: "burial(土葬)と対。動詞は cremate。",
    relatedWords: ["burial", "funeral", "cremate"],
  },
  {
    id: "tomb",
    word: "tomb",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["墓、墓所"],
    pronunciation: "/tuːm/",
    exampleSentence: "They found an untouched tomb in the valley.",
    exampleTranslationJa: "彼らは谷で手つかずの墓を発見した。",
    collocations: ["an ancient tomb", "the tomb of", "a tomb raider"],
    mnemonic: "b は読まない /tuːm/。grave より大きく作られた墓。",
    relatedWords: ["grave", "burial", "monument"],
  },
  {
    id: "mourning",
    word: "mourning",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["喪、悲しみ"],
    pronunciation: "/ˈmɔːrnɪŋ/",
    exampleSentence: "The country was in mourning for a week.",
    exampleTranslationJa: "その国は一週間、喪に服した。",
    collocations: ["in mourning", "a period of mourning", "mourning clothes"],
    mnemonic: "morning(朝)と同音。動詞は mourn。",
    relatedWords: ["grief", "bereavement", "mourn"],
  },
  {
    id: "bereavement",
    word: "bereavement",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["近親者との死別"],
    pronunciation: "/bɪˈriːvmənt/",
    exampleSentence: "She took bereavement leave for a week.",
    exampleTranslationJa: "彼女は忌引きで一週間休んだ。",
    collocations: ["bereavement leave", "suffer a bereavement"],
    mnemonic: "bereave(奪う)から。人を失うことそのものを指す語。",
    relatedWords: ["loss", "grief", "mourning"],
  },
  {
    id: "inheritance",
    word: "inheritance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["相続財産、遺産", "受け継いだもの"],
    pronunciation: "/ɪnˈherɪtəns/",
    exampleSentence: "He used his inheritance to start a business.",
    exampleTranslationJa: "彼は遺産で事業を始めた。",
    collocations: ["an inheritance tax", "receive an inheritance", "a genetic inheritance"],
    mnemonic: "財産だけでなく、遺伝や文化的に受け継ぐものにも使う。",
    relatedWords: ["heritage", "legacy", "heir"],
  },
  {
    id: "upbringing",
    word: "upbringing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["育て方、育ち"],
    pronunciation: "/ˈʌpbrɪŋɪŋ/",
    exampleSentence: "She had a strict upbringing.",
    exampleTranslationJa: "彼女は厳しく育てられた。",
    collocations: ["a strict upbringing", "a religious upbringing"],
    mnemonic: "bring up(育てる)が名詞に。本人ではなく「育てられ方」。",
    relatedWords: ["childhood", "parenting", "education"],
  },
  {
    id: "parenting",
    word: "parenting",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["子育て"],
    pronunciation: "/ˈperəntɪŋ/",
    exampleSentence: "Parenting is harder than they expected.",
    exampleTranslationJa: "子育ては彼らが思っていたより大変だ。",
    collocations: ["parenting skills", "a parenting class", "shared parenting"],
    mnemonic: "parent が動詞にもなった比較的新しい語。",
    relatedWords: ["childcare", "upbringing", "raise"],
  },
  {
    id: "curfew",
    word: "curfew",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["外出禁止令", "門限"],
    pronunciation: "/ˈkɜːrfjuː/",
    exampleSentence: "A curfew was imposed after the riots.",
    exampleTranslationJa: "暴動のあと外出禁止令が出された。",
    collocations: ["impose a curfew", "break a curfew", "a ten o'clock curfew"],
    mnemonic: "フランス語 couvre-feu(火を覆え)から。中世に火を消させた合図。",
    relatedWords: ["restriction", "ban", "deadline"],
  },
  {
    id: "ancestry",
    word: "ancestry",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["祖先、家系"],
    pronunciation: "/ˈænsestri/",
    exampleSentence: "She traced her ancestry back four centuries.",
    exampleTranslationJa: "彼女は家系を4世紀さかのぼって調べた。",
    collocations: ["trace your ancestry", "of Irish ancestry"],
    mnemonic: "ancestor(祖先)の集合。trace your ancestry で「ルーツをたどる」。",
    relatedWords: ["ancestor", "lineage", "descent"],
  },
  {
    id: "lineage",
    word: "lineage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["血統、系譜"],
    pronunciation: "/ˈlɪniɪdʒ/",
    exampleSentence: "The family claims a royal lineage.",
    exampleTranslationJa: "その一族は王家の血筋を主張している。",
    collocations: ["a direct lineage", "of noble lineage"],
    mnemonic: "line(線)から。まっすぐつながる家の筋。",
    relatedWords: ["ancestry", "descent", "bloodline"],
  },
  {
    id: "kinship",
    word: "kinship",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["血縁関係", "親近感"],
    pronunciation: "/ˈkɪnʃɪp/",
    exampleSentence: "He felt a kinship with the other newcomers.",
    exampleTranslationJa: "彼はほかの新参者たちに親近感を覚えた。",
    collocations: ["kinship ties", "a sense of kinship"],
    mnemonic: "kin(親族)+ -ship。血縁だけでなく「気持ちの近さ」にも使う。",
    relatedWords: ["relationship", "affinity", "kin"],
  },
  {
    id: "clan",
    word: "clan",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["氏族、一族"],
    pronunciation: "/klæn/",
    exampleSentence: "The clan gathered every summer.",
    exampleTranslationJa: "その一族は毎夏集まった。",
    collocations: ["a Scottish clan", "the whole clan", "clan loyalty"],
    mnemonic: "スコットランドの氏族が典型。大きな親族集団。",
    relatedWords: ["tribe", "family", "kin"],
  },
  {
    id: "extended family",
    word: "extended family",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["拡大家族(親族を含む家族)"],
    pronunciation: "/ɪkˈstendɪd ˈfæməli/",
    exampleSentence: "The whole extended family came to the party.",
    exampleTranslationJa: "親族一同がそのパーティーに来た。",
    collocations: ["the extended family", "live with the extended family"],
    mnemonic: "祖父母やおじおばまで含む家族。対は nuclear family。",
    relatedWords: ["nuclear family", "relatives", "household"],
  },
  {
    id: "nuclear family",
    word: "nuclear family",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["核家族"],
    pronunciation: "/ˈnuːkliər ˈfæməli/",
    exampleSentence: "The nuclear family is no longer the norm.",
    exampleTranslationJa: "核家族はもはや標準ではない。",
    collocations: ["the nuclear family", "a traditional nuclear family"],
    mnemonic: "nucleus(核)から。親と子だけの単位。",
    relatedWords: ["extended family", "household", "parents"],
  },
  {
    id: "midday",
    word: "midday",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["正午、真昼"],
    pronunciation: "/ˌmɪdˈdeɪ/",
    exampleSentence: "We stop for lunch at midday.",
    exampleTranslationJa: "私たちは正午に昼食で手を止める。",
    collocations: ["at midday", "the midday sun", "a midday meal"],
    mnemonic: "noon とほぼ同じ。真夜中は midnight。",
    relatedWords: ["noon", "midnight", "lunchtime"],
  },
  {
    id: "midnight",
    word: "midnight",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["真夜中、午前0時"],
    pronunciation: "/ˈmɪdnaɪt/",
    exampleSentence: "The shop closes at midnight.",
    exampleTranslationJa: "その店は0時に閉まる。",
    collocations: ["at midnight", "burn the midnight oil", "just after midnight"],
    mnemonic: "burn the midnight oil は「夜遅くまで励む」。",
    relatedWords: ["midday", "night", "twelve"],
  },
  {
    id: "fortnight",
    word: "fortnight",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["2週間(英)"],
    pronunciation: "/ˈfɔːrtnaɪt/",
    exampleSentence: "We meet once a fortnight.",
    exampleTranslationJa: "私たちは2週間に一度会う。",
    collocations: ["once a fortnight", "a fortnight's holiday"],
    mnemonic: "fourteen nights の短縮。米では two weeks と言う。",
    relatedWords: ["two weeks", "week", "month"],
  },
  {
    id: "century",
    word: "century",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["世紀、100年"],
    pronunciation: "/ˈsentʃəri/",
    exampleSentence: "The building dates from the sixteenth century.",
    exampleTranslationJa: "その建物は16世紀のものだ。",
    collocations: ["the twentieth century", "a century ago", "over a century"],
    mnemonic: "cent(100)が語根。西暦1601〜1700年が the seventeenth century。",
    relatedWords: ["decade", "millennium", "era"],
  },
  {
    id: "millennium",
    word: "millennium",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["千年、千年紀"],
    pronunciation: "/mɪˈleniəm/",
    exampleSentence: "The cathedral has stood for nearly a millennium.",
    exampleTranslationJa: "その大聖堂は千年近く立っている。",
    collocations: ["the new millennium", "for a millennium"],
    mnemonic: "mille(千)+ annus(年)。複数形は millennia。n が二つ。",
    relatedWords: ["century", "decade", "era"],
  },
  {
    id: "epoch",
    word: "epoch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["時代、画期"],
    pronunciation: "/ˈepək/",
    exampleSentence: "The invention marked a new epoch.",
    exampleTranslationJa: "その発明は新しい時代の始まりを画した。",
    collocations: ["a new epoch", "epoch-making"],
    mnemonic: "era より「区切り」を意識した語。epoch-making は「画期的な」。",
    relatedWords: ["era", "age", "period"],
  },
  {
    id: "weekday",
    word: "weekday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["平日"],
    pronunciation: "/ˈwiːkdeɪ/",
    exampleSentence: "The museum is quiet on weekdays.",
    exampleTranslationJa: "その博物館は平日は空いている。",
    collocations: ["on weekdays", "a weekday morning"],
    mnemonic: "月曜から金曜。土日は the weekend。",
    relatedWords: ["weekend", "working day", "Monday"],
  },
  {
    id: "weekend",
    word: "weekend",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["週末"],
    pronunciation: "/ˈwiːkend/",
    exampleSentence: "We are away for the weekend.",
    exampleTranslationJa: "私たちは週末は出かけている。",
    collocations: ["at the weekend", "a long weekend", "this weekend"],
    mnemonic: "英では at the weekend、米では on the weekend。",
    relatedWords: ["weekday", "Saturday", "holiday"],
  },
  {
    id: "holiday",
    word: "holiday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["休日、休暇"],
    pronunciation: "/ˈhɑːlədi/",
    exampleSentence: "They take a holiday every August.",
    exampleTranslationJa: "彼らは毎年8月に休暇を取る。",
    collocations: ["a public holiday", "go on holiday", "a bank holiday"],
    mnemonic: "英では休暇全般、米では祝日のみ。米の長期休暇は vacation。",
    relatedWords: ["vacation", "break", "leave"],
  },
  {
    id: "vacation",
    word: "vacation",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["休暇(米)、(大学の)休み"],
    pronunciation: "/veɪˈkeɪʃn/",
    exampleSentence: "They are on vacation in Florida.",
    exampleTranslationJa: "彼らはフロリダで休暇中だ。",
    collocations: ["on vacation", "a summer vacation", "take a vacation"],
    mnemonic: "vacant(空の)と同語根。米では holiday の代わりにこちらを使う。",
    relatedWords: ["holiday", "break", "leave"],
  },
  {
    id: "semester",
    word: "semester",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["学期(2学期制の)"],
    pronunciation: "/sɪˈmestər/",
    exampleSentence: "The course runs for one semester.",
    exampleTranslationJa: "その講座は1学期続く。",
    collocations: ["the spring semester", "a semester abroad"],
    mnemonic: "ラテン語 sex(6)+ mensis(月)で「6か月」。3学期制なら term。",
    relatedWords: ["term", "quarter", "academic year"],
  },
  {
    id: "quarter",
    word: "quarter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["4分の1", "四半期", "地区"],
    pronunciation: "/ˈkwɔːrtər/",
    exampleSentence: "Profits rose in the third quarter.",
    exampleTranslationJa: "第3四半期に利益が伸びた。",
    collocations: ["a quarter of an hour", "the first quarter", "the old quarter"],
    mnemonic: "時間・数量・会計期間・街の一区画、どれも「4分の1」から。",
    relatedWords: ["fourth", "period", "district"],
  },
  {
    id: "overdue",
    word: "overdue",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["期限を過ぎた、遅れている"],
    pronunciation: "/ˌoʊvərˈduː/",
    exampleSentence: "The book is three weeks overdue.",
    exampleTranslationJa: "その本は3週間の延滞だ。",
    collocations: ["long overdue", "an overdue payment", "an overdue apology"],
    mnemonic: "long overdue は「とっくにあってしかるべきだった」。",
    relatedWords: ["late", "unpaid", "punctual"],
  },
  {
    id: "lasting",
    word: "lasting",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["長続きする、永続的な"],
    pronunciation: "/ˈlæstɪŋ/",
    exampleSentence: "The visit made a lasting impression.",
    exampleTranslationJa: "その訪問は長く残る印象を与えた。",
    collocations: ["a lasting impression", "lasting peace", "lasting damage"],
    mnemonic: "last(続く)+ -ing。a lasting impression が定型。",
    relatedWords: ["enduring", "permanent", "temporary"],
  },
  {
    id: "momentary",
    word: "momentary",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["一瞬の、つかのまの"],
    pronunciation: "/ˈmoʊmənteri/",
    exampleSentence: "There was a momentary silence.",
    exampleTranslationJa: "一瞬の沈黙があった。",
    collocations: ["a momentary lapse", "momentary hesitation"],
    mnemonic: "moment(瞬間)+ -ary。momentous(重大な)とは全く別語。",
    relatedWords: ["brief", "fleeting", "lasting"],
  },
  {
    id: "recurrence",
    word: "recurrence",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["再発、繰り返し"],
    pronunciation: "/rɪˈkɜːrəns/",
    exampleSentence: "They want to prevent a recurrence of the fault.",
    exampleTranslationJa: "彼らはその不具合の再発を防ぎたいと考えている。",
    collocations: ["prevent a recurrence", "the recurrence of symptoms"],
    mnemonic: "recur(再発する)の名詞形。病気にも事故にも使う。",
    relatedWords: ["repetition", "relapse", "recur"],
  },
]
