import type { VocabularyEntry } from '../types'

// 増補 第40弾。8,000語 → 8,800語 の増補の一部で、基礎語の抜けを補う。
export const plus40: VocabularyEntry[] = [
  {
    id: "a",
    word: "a",
    level: "A2",
    partOfSpeech: "冠詞",
    meaningsJa: ["ある〜、1つの〜"],
    pronunciation: "/ə/",
    exampleSentence: "I saw a dog in the park.",
    exampleTranslationJa: "公園で犬を1匹見かけた。",
    collocations: ["a lot of", "a few", "once a week"],
    mnemonic: "母音の前では an(an apple)。「どれか1つ」を指す冠詞で、特定のものを指す the と対になる。",
    relatedWords: ["an", "the", "one"],
  },
  {
    id: "about",
    word: "about",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜について", "およそ、約"],
    pronunciation: "/əˈbaʊt/",
    exampleSentence: "We talked about the new plan for an hour.",
    exampleTranslationJa: "私たちは新しい計画について1時間話した。",
    collocations: ["talk about", "about two hours", "what about you"],
    mnemonic: "a-+ bout(一回り)。話題の周りをぐるっと回るのが原義で、「〜について」「およそ」に広がった。",
    relatedWords: ["around", "approximately", "regarding"],
  },
  {
    id: "above",
    word: "above",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜の上に(離れて)", "上記の、前述の"],
    pronunciation: "/əˈbʌv/",
    exampleSentence: "The plane flew above the thick clouds.",
    exampleTranslationJa: "飛行機は厚い雲の上を飛んだ。",
    collocations: ["above the clouds", "above average", "as stated above"],
    mnemonic: "on は接触して上、above は離れて上、over は覆うように上を表す。反対語は below。",
    relatedWords: ["over", "on", "below"],
  },
  {
    id: "across",
    word: "across",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜を横切って、〜の向こう側に"],
    pronunciation: "/əˈkrɔːs/",
    exampleSentence: "She walked across the bridge to the market.",
    exampleTranslationJa: "彼女は市場へ橋を渡って歩いた。",
    collocations: ["across the street", "come across", "swim across a river"],
    mnemonic: "a-+ cross(十字・横切る)。線を横に越えて向こう側まで届くのがコアイメージで、道や橋に使う。",
    relatedWords: ["cross", "over", "through"],
  },
  {
    id: "adapter",
    word: "adapter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["変換アダプター", "適合させる人・もの"],
    pronunciation: "/əˈdæptər/",
    exampleSentence: "I bought a travel adapter for my trip to Europe.",
    exampleTranslationJa: "ヨーロッパ旅行のために変換アダプターを買った。",
    collocations: ["a travel adapter", "a power adapter", "use an adapter"],
    mnemonic: "adapt(合わせる)+ -er。形や電圧を機器に合わせる道具。日本語ではアダプターとも書く。",
    relatedWords: ["adapt", "plug", "converter"],
  },
  {
    id: "advice",
    word: "advice",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["助言、忠告"],
    pronunciation: "/ədˈvaɪs/",
    exampleSentence: "My teacher gave me good advice about studying.",
    exampleTranslationJa: "先生は勉強について良い助言をくれた。",
    collocations: ["give advice", "a piece of advice", "follow someone's advice"],
    mnemonic: "数えられない名詞なので an advice とは言わず a piece of advice。動詞は advise とつづりが変わる。",
    relatedWords: ["advise", "suggestion", "tip"],
  },
  {
    id: "afraid",
    word: "afraid",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恐れて、怖がって"],
    pronunciation: "/əˈfreɪd/",
    exampleSentence: "The child is afraid of the big dog.",
    exampleTranslationJa: "その子は大きな犬を怖がっている。",
    collocations: ["afraid of dogs", "I'm afraid so", "afraid to ask"],
    mnemonic: "be afraid of 〜 の形で使う形容詞。名詞の fear と違い、「〜が怖い状態」を表す。",
    relatedWords: ["fear", "scared", "frightened"],
  },
  {
    id: "afternoon",
    word: "afternoon",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["午後"],
    pronunciation: "/ˌæftərˈnuːn/",
    exampleSentence: "We play tennis every Saturday afternoon.",
    exampleTranslationJa: "私たちは毎週土曜の午後にテニスをする。",
    collocations: ["in the afternoon", "this afternoon", "a late afternoon"],
    mnemonic: "after(〜の後)+ noon(正午)。正午の後が午後。午前は morning、夜は evening と言う。",
    relatedWords: ["morning", "evening", "noon"],
  },
  {
    id: "again",
    word: "again",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["もう一度、また"],
    pronunciation: "/əˈɡen/",
    exampleSentence: "Could you say that again more slowly?",
    exampleTranslationJa: "もう一度ゆっくり言ってもらえますか。",
    collocations: ["again and again", "see you again", "once again"],
    mnemonic: "「もう一度」を表す副詞。again and again で「何度も繰り返して」。ふつう文末か助動詞の後に置く。",
    relatedWords: ["once", "repeat", "twice"],
  },
  {
    id: "ago",
    word: "ago",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["〜前に"],
    pronunciation: "/əˈɡoʊ/",
    exampleSentence: "They moved to this town two years ago.",
    exampleTranslationJa: "彼らは2年前にこの町へ引っ越してきた。",
    collocations: ["two years ago", "a long time ago", "not long ago"],
    mnemonic: "「今から〜前」を表し、期間を表す語の後ろに置く。before は基準になる時点の前に置く点が違う。",
    relatedWords: ["before", "since", "last"],
  },
  {
    id: "air conditioner",
    word: "air conditioner",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["エアコン、空調機"],
    pronunciation: "/ˈer kəndɪʃənər/",
    exampleSentence: "We turned on the air conditioner in the car.",
    exampleTranslationJa: "私たちは車のエアコンの電源を入れた。",
    collocations: ["a new air conditioner", "turn on the air conditioner", "install an air conditioner"],
    mnemonic: "air(空気)+ conditioner(調整する装置)。部屋の空気を冷やしたり暖めたりする機械。",
    relatedWords: ["heater", "fan", "temperature"],
  },
  {
    id: "aloud",
    word: "aloud",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["声に出して"],
    pronunciation: "/əˈlaʊd/",
    exampleSentence: "The teacher asked us to read the poem aloud.",
    exampleTranslationJa: "先生は私たちにその詩を声に出して読むように言った。",
    collocations: ["read aloud", "think aloud", "say it aloud"],
    mnemonic: "a-+ loud(大きな音)。心の中でなく声に出して読むこと。allowed(許された)と同音なので注意。",
    relatedWords: ["loud", "silent", "read"],
  },
  {
    id: "also",
    word: "also",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["〜もまた、そのうえ"],
    pronunciation: "/ˈɔːlsoʊ/",
    exampleSentence: "She speaks French and also a little Italian.",
    exampleTranslationJa: "彼女はフランス語を話し、イタリア語も少し話す。",
    collocations: ["not only but also", "also known as", "and also"],
    mnemonic: "all(すべて)+ so(そのように)で「同様に」。too より書き言葉寄りで、ふつう一般動詞の前に置く。",
    relatedWords: ["too", "as well", "either"],
  },
  {
    id: "always",
    word: "always",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["いつも、常に"],
    pronunciation: "/ˈɔːlweɪz/",
    exampleSentence: "He always arrives at the office before eight.",
    exampleTranslationJa: "彼はいつも8時前に会社に着く。",
    collocations: ["always late", "as always", "not always"],
    mnemonic: "all(すべて)+ ways(道)で「どの道でも」。頻度100%を表し、一般動詞の前に置く。",
    relatedWords: ["usually", "often", "never"],
  },
  {
    id: "am",
    word: "am",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜である、〜にいる(主語がIのときのbe動詞)"],
    pronunciation: "/æm/",
    exampleSentence: "I am a student at this university.",
    exampleTranslationJa: "私はこの大学の学生です。",
    collocations: ["I am ready", "am I right", "here I am"],
    mnemonic: "be動詞の現在形で、主語が I のときの形。you や複数なら are、he や she なら is を使う。",
    relatedWords: ["is", "are", "be"],
  },
  {
    id: "an",
    word: "an",
    level: "A2",
    partOfSpeech: "冠詞",
    meaningsJa: ["ある〜、1つの〜(母音の前で使う)"],
    pronunciation: "/ən/",
    exampleSentence: "She ate an orange after lunch.",
    exampleTranslationJa: "彼女は昼食のあとにオレンジを1つ食べた。",
    collocations: ["an hour", "an apple", "half an hour"],
    mnemonic: "a と同じ冠詞だが、母音の音の前では an を使う。an hour は h を発音しないので an になる。",
    relatedWords: ["a", "the", "one"],
  },
  {
    id: "and",
    word: "and",
    level: "A2",
    partOfSpeech: "接続詞",
    meaningsJa: ["〜と、そして", "そうすれば"],
    pronunciation: "/ænd/",
    exampleSentence: "Tom and I are good friends.",
    exampleTranslationJa: "トムと私は仲の良い友達だ。",
    collocations: ["you and I", "now and then", "and so on"],
    mnemonic: "語や文を対等につなぐ接続詞。now and then(時々)のような決まった組み合わせも多い。",
    relatedWords: ["or", "but", "with"],
  },
  {
    id: "angry",
    word: "angry",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["怒った、腹を立てた"],
    pronunciation: "/ˈæŋɡri/",
    exampleSentence: "She was angry with me for being late.",
    exampleTranslationJa: "彼女は私が遅刻したことで怒っていた。",
    collocations: ["angry with someone", "get angry", "an angry look"],
    mnemonic: "anger(怒り)の形容詞形。人に対しては angry with、物事に対しては angry about を使う。",
    relatedWords: ["anger", "upset", "mad"],
  },
  {
    id: "animal",
    word: "animal",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["動物"],
    pronunciation: "/ˈænɪml/",
    exampleSentence: "The lion is a wild animal in Africa.",
    exampleTranslationJa: "ライオンはアフリカにいる野生動物だ。",
    collocations: ["a wild animal", "animal welfare", "farm animals"],
    mnemonic: "ラテン語 anima(息・命)から。息をする生き物のこと。animation(動き)も同じ語根。",
    relatedWords: ["plant", "wildlife", "pet"],
  },
  {
    id: "another",
    word: "another",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["もう1つの、別の"],
    pronunciation: "/əˈnʌðər/",
    exampleSentence: "Would you like another cup of coffee?",
    exampleTranslationJa: "コーヒーをもう1杯いかがですか。",
    collocations: ["another one", "one another", "another time"],
    mnemonic: "an + other(ほかの)で「もう1つの」。複数を表すときは other や more を使う。",
    relatedWords: ["other", "more", "else"],
  },
  {
    id: "answer",
    word: "answer",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["答え、返事", "答える"],
    pronunciation: "/ˈænsər/",
    exampleSentence: "Nobody could answer the teacher's question.",
    exampleTranslationJa: "だれも先生の質問に答えられなかった。",
    collocations: ["answer a question", "the answer to a question", "answer the phone"],
    mnemonic: "動詞では answer a question、名詞では the answer to a question と前置詞が変わる点に注意。",
    relatedWords: ["reply", "question", "respond"],
  },
  {
    id: "antique",
    word: "antique",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["骨董の、古風な", "骨董品"],
    pronunciation: "/ænˈtiːk/",
    exampleSentence: "She collects antique clocks from Europe.",
    exampleTranslationJa: "彼女はヨーロッパの骨董の時計を集めている。",
    collocations: ["an antique shop", "antique furniture", "an antique dealer"],
    mnemonic: "ラテン語 ante(以前)から。「古い」が芯の語で、100年以上前の品を指すことが多い。",
    relatedWords: ["vintage", "collector", "old"],
  },
  {
    id: "anyone",
    word: "anyone",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["だれか、だれでも"],
    pronunciation: "/ˈeniwʌn/",
    exampleSentence: "Does anyone know the answer to this question?",
    exampleTranslationJa: "この質問の答えが分かる人はいますか。",
    collocations: ["anyone else", "anyone at all", "not anyone"],
    mnemonic: "any(どれでも)+ one(人)。肯定文では「だれでも」、疑問文と否定文では「だれか」の意味になる。",
    relatedWords: ["someone", "everyone", "nobody"],
  },
  {
    id: "anything",
    word: "anything",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["何か、何でも"],
    pronunciation: "/ˈeniθɪŋ/",
    exampleSentence: "I didn't eat anything this morning.",
    exampleTranslationJa: "今朝は何も食べなかった。",
    collocations: ["anything else", "not anything", "anything at all"],
    mnemonic: "any + thing で「どんなものでも」。否定文では not ... anything の形で「何も〜ない」を表す。",
    relatedWords: ["something", "everything", "nothing"],
  },
  {
    id: "apartment",
    word: "apartment",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["アパート、マンションの1室(米)"],
    pronunciation: "/əˈpɑːrtmənt/",
    exampleSentence: "They rented a small apartment near the station.",
    exampleTranslationJa: "彼らは駅の近くの小さなアパートを借りた。",
    collocations: ["rent an apartment", "a furnished apartment", "a studio apartment"],
    mnemonic: "a-+ part(分ける)+ -ment。建物を区切った1区画のこと。英国では flat と言う。",
    relatedWords: ["flat", "rent", "building"],
  },
  {
    id: "apple",
    word: "apple",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["りんご"],
    pronunciation: "/ˈæpl/",
    exampleSentence: "She cut an apple into four pieces.",
    exampleTranslationJa: "彼女はりんごを4つに切った。",
    collocations: ["an apple tree", "apple juice", "the apple of one's eye"],
    mnemonic: "「りんご」。the apple of one's eye は「目に入れても痛くないほど大切な人」の意味。",
    relatedWords: ["fruit", "orange", "juice"],
  },
  {
    id: "archery",
    word: "archery",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["アーチェリー、弓術"],
    pronunciation: "/ˈɑːrtʃəri/",
    exampleSentence: "She took up archery at summer camp.",
    exampleTranslationJa: "彼女はサマーキャンプでアーチェリーを始めた。",
    collocations: ["practice archery", "an archery target", "archery lessons"],
    mnemonic: "arch(弓)+ -ery(術)。弓で的を射る競技で、弓は bow、矢は arrow、射手は archer。",
    relatedWords: ["bow", "arrow", "target"],
  },
  {
    id: "are",
    word: "are",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜である、〜にいる(you・複数のbe動詞)"],
    pronunciation: "/ɑːr/",
    exampleSentence: "You are welcome to stay for dinner.",
    exampleTranslationJa: "夕食に泊まっていってかまいませんよ。",
    collocations: ["you are welcome", "we are ready", "they are here"],
    mnemonic: "be動詞の現在形で、you・we・they と複数名詞に使う。主語が I なら am、he なら is。",
    relatedWords: ["am", "is", "be"],
  },
  {
    id: "area",
    word: "area",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["地域、区域", "面積"],
    pronunciation: "/ˈeriə/",
    exampleSentence: "This area of the city is very quiet.",
    exampleTranslationJa: "市のこの地域はとても静かだ。",
    collocations: ["a rural area", "a parking area", "the area around here"],
    mnemonic: "「平らな場所」が原義。地域・面積・分野まで、まとまった範囲を広く指す語で、複数形は areas。",
    relatedWords: ["region", "zone", "district"],
  },
  {
    id: "around",
    word: "around",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜の周りに、あちこちに", "およそ"],
    pronunciation: "/əˈraʊnd/",
    exampleSentence: "They walked around the old town together.",
    exampleTranslationJa: "彼らは一緒に旧市街を歩き回った。",
    collocations: ["around the world", "look around", "around ten people"],
    mnemonic: "a-+ round(丸)。円を描くように周囲を回るイメージで、およその数量にも使う。",
    relatedWords: ["round", "about", "nearby"],
  },
  {
    id: "arrive",
    word: "arrive",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["到着する、着く"],
    pronunciation: "/əˈraɪv/",
    exampleSentence: "The train will arrive at the station soon.",
    exampleTranslationJa: "列車はまもなく駅に着きます。",
    collocations: ["arrive at the station", "arrive in Japan", "arrive on time"],
    mnemonic: "ar-+ rive(岸)。船が岸に着くのが原義。狭い場所には at、広い場所には in を続ける。",
    relatedWords: ["reach", "leave", "depart"],
  },
  {
    id: "art",
    word: "art",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["芸術、美術"],
    pronunciation: "/ɑːrt/",
    exampleSentence: "She studies art at a college in London.",
    exampleTranslationJa: "彼女はロンドンの大学で美術を学んでいる。",
    collocations: ["modern art", "an art gallery", "art class"],
    mnemonic: "「技」が原義。絵や彫刻だけでなく、技法や人文学も指す。artist は「技を持つ人」。",
    relatedWords: ["artist", "painting", "music"],
  },
  {
    id: "ask",
    word: "ask",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["たずねる、頼む"],
    pronunciation: "/æsk/",
    exampleSentence: "May I ask you a personal question?",
    exampleTranslationJa: "個人的な質問をしてもいいですか。",
    collocations: ["ask a question", "ask for help", "ask someone to do"],
    mnemonic: "「たずねる」と「頼む」の両方の意味がある。物を頼むときは ask for と for を伴う。",
    relatedWords: ["question", "request", "answer"],
  },
  {
    id: "at",
    word: "at",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜に(地点・時点)"],
    pronunciation: "/æt/",
    exampleSentence: "We met at the bus stop at eight.",
    exampleTranslationJa: "私たちは8時にバス停で会った。",
    collocations: ["at home", "at night", "at the station"],
    mnemonic: "点を指す前置詞。狭い場所の一点と時刻の一点に使う。広がりは in、接触は on。",
    relatedWords: ["in", "on", "to"],
  },
  {
    id: "aubergine",
    word: "aubergine",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ナス(英)"],
    pronunciation: "/ˈoʊbərʒiːn/",
    exampleSentence: "She roasted an aubergine with olive oil.",
    exampleTranslationJa: "彼女はナスをオリーブ油で焼いた。",
    collocations: ["a grilled aubergine", "an aubergine dish", "slice an aubergine"],
    mnemonic: "フランス語由来の英国名。米国では eggplant(卵植物)と呼ぶ、紫の長い野菜。",
    relatedWords: ["eggplant", "vegetable", "tomato"],
  },
  {
    id: "autumn",
    word: "autumn",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["秋(英)"],
    pronunciation: "/ˈɔːtəm/",
    exampleSentence: "The leaves turn red and gold in autumn.",
    exampleTranslationJa: "秋には葉が赤や金色に変わる。",
    collocations: ["in autumn", "autumn leaves", "early autumn"],
    mnemonic: "英国での「秋」。米国では fall と言う。autumn leaves は「紅葉」のこと。",
    relatedWords: ["fall", "season", "winter"],
  },
  {
    id: "avalanche",
    word: "avalanche",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["雪崩"],
    pronunciation: "/ˈævəlæntʃ/",
    exampleSentence: "The avalanche blocked the mountain road.",
    exampleTranslationJa: "雪崩が山道をふさいだ。",
    collocations: ["a sudden avalanche", "trigger an avalanche", "be caught in an avalanche"],
    mnemonic: "フランス語経由の語で、雪や岩が山肌を滑り落ちる現象を指す。手紙などが殺到する意味でも使う。",
    relatedWords: ["snow", "mountain", "landslide"],
  },
  {
    id: "avocado",
    word: "avocado",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["アボカド"],
    pronunciation: "/ˌævəˈkɑːdoʊ/",
    exampleSentence: "He put slices of avocado on the toast.",
    exampleTranslationJa: "彼はトーストにアボカドの薄切りをのせた。",
    collocations: ["avocado toast", "a ripe avocado", "avocado salad"],
    mnemonic: "ナワトル語 ahuacatl 由来。脂肪分が多く「森のバター」とも呼ばれる緑色の果実。",
    relatedWords: ["fruit", "salad", "toast"],
  },
  {
    id: "away",
    word: "away",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["離れて、向こうへ", "不在で"],
    pronunciation: "/əˈweɪ/",
    exampleSentence: "He ran away when he saw the dog.",
    exampleTranslationJa: "彼は犬を見て逃げ出した。",
    collocations: ["go away", "far away", "away from home"],
    mnemonic: "a-+ way(道)で「道を離れて」。go away は「あっちへ行って」、far away は「遠く」。",
    relatedWords: ["far", "off", "absent"],
  },
  {
    id: "axe",
    word: "axe",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["おの、斧"],
    pronunciation: "/æks/",
    exampleSentence: "He cut the firewood with a sharp axe.",
    exampleTranslationJa: "彼はよく切れる斧でまきを割った。",
    collocations: ["a sharp axe", "chop wood with an axe", "an axe handle"],
    mnemonic: "薪を割る刃物で、米国つづりは ax。動詞では「大幅に削減する」の意味でも使う。get the axe は「首になる」。",
    relatedWords: ["saw", "tool", "wood"],
  },
  {
    id: "baby",
    word: "baby",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["赤ちゃん、乳児"],
    pronunciation: "/ˈbeɪbi/",
    exampleSentence: "The baby smiled at her mother.",
    exampleTranslationJa: "赤ちゃんは母親にほほえんだ。",
    collocations: ["a baby boy", "have a baby", "baby food"],
    mnemonic: "「赤ん坊」。baby-sit は「赤ちゃんの番をする」で、甘えた呼びかけにも使う。",
    relatedWords: ["child", "infant", "toddler"],
  },
  {
    id: "babysit",
    word: "babysit",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["(留守中の)子どもの世話をする"],
    pronunciation: "/ˈbeɪbisɪt/",
    exampleSentence: "I often babysit my friend's children on Fridays.",
    exampleTranslationJa: "私はよく金曜日に友人の子どもの世話を頼まれる。",
    collocations: ["babysit for a friend", "babysit on Saturday night", "ask someone to babysit"],
    mnemonic: "baby(赤ちゃん)+ sit(座って番をする)。留守中の子どもの世話をすること。名詞は babysitter。",
    relatedWords: ["baby", "childcare", "sitter"],
  },
  {
    id: "bad",
    word: "bad",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["悪い、下手な", "ひどい"],
    pronunciation: "/bæd/",
    exampleSentence: "The weather was bad all weekend.",
    exampleTranslationJa: "週末はずっと天気が悪かった。",
    collocations: ["a bad idea", "bad weather", "be bad at"],
    mnemonic: "good の反対語。be bad at で「〜が苦手」。比較級は worse、最上級は worst と不規則。",
    relatedWords: ["good", "wrong", "terrible"],
  },
  {
    id: "bag",
    word: "bag",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["かばん、袋"],
    pronunciation: "/bæɡ/",
    exampleSentence: "She put her keys in the bag.",
    exampleTranslationJa: "彼女はかばんに鍵を入れた。",
    collocations: ["a plastic bag", "pack a bag", "a shopping bag"],
    mnemonic: "紙袋から肩掛けかばんまで広く使う語で、荷物をまとめて持ち運ぶ入れ物。動詞では「袋に入れる」。",
    relatedWords: ["case", "suitcase", "box"],
  },
  {
    id: "ball",
    word: "ball",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ボール", "球"],
    pronunciation: "/bɔːl/",
    exampleSentence: "The children kicked the ball in the park.",
    exampleTranslationJa: "子どもたちは公園でボールを蹴った。",
    collocations: ["play ball", "throw a ball", "a tennis ball"],
    mnemonic: "丸いもの。ダンス会の「舞踏会」も同じつづりで、そちらは「舞う」が語源。球技は ball games。",
    relatedWords: ["sphere", "play", "round"],
  },
  {
    id: "banana",
    word: "banana",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["バナナ"],
    pronunciation: "/bəˈnænə/",
    exampleSentence: "He ate a banana before the race.",
    exampleTranslationJa: "彼はレースの前にバナナを食べた。",
    collocations: ["a ripe banana", "peel a banana", "banana bread"],
    mnemonic: "西アフリカの言語に由来する語。房になって実る細長い果物で、皮をむくのは peel。",
    relatedWords: ["fruit", "peel", "plantain"],
  },
  {
    id: "banjo",
    word: "banjo",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["バンジョー"],
    pronunciation: "/ˈbændʒoʊ/",
    exampleSentence: "He played the banjo in a folk band.",
    exampleTranslationJa: "彼はフォークバンドでバンジョーを弾いた。",
    collocations: ["play the banjo", "a five-string banjo", "a banjo player"],
    mnemonic: "丸い胴に弦を張った撥弦楽器。米国の民俗音楽やカントリーでよく使われ、指にはめたピックで弾く。",
    relatedWords: ["guitar", "folk", "string"],
  },
  {
    id: "bank",
    word: "bank",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["銀行", "土手、岸"],
    pronunciation: "/bæŋk/",
    exampleSentence: "I need to go to the bank this morning.",
    exampleTranslationJa: "今朝は銀行に行かないといけない。",
    collocations: ["a bank account", "the river bank", "go to the bank"],
    mnemonic: "「土手・台」が原義。両替商の台から「銀行」が生まれ、川の bank は土手を指す。",
    relatedWords: ["account", "money", "shore"],
  },
  {
    id: "barber",
    word: "barber",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["理髪師、床屋"],
    pronunciation: "/ˈbɑːrbər/",
    exampleSentence: "He gets a haircut at the barber every month.",
    exampleTranslationJa: "彼は毎月床屋で髪を切ってもらう。",
    collocations: ["a barber shop", "go to the barber", "a barber's chair"],
    mnemonic: "ラテン語 barba(ひげ)から。ひげをそり髪を切る職人。女性向けの美容師は hairdresser。",
    relatedWords: ["hairdresser", "haircut", "shave"],
  },
  {
    id: "bath",
    word: "bath",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["入浴、浴槽"],
    pronunciation: "/bæθ/",
    exampleSentence: "She had a hot bath after the long walk.",
    exampleTranslationJa: "彼女は長い散歩のあと熱い風呂に入った。",
    collocations: ["take a bath", "a hot bath", "a bath towel"],
    mnemonic: "湯につかる行為とその浴槽の両方を指す。動詞の bathe は「体を洗う・泳ぐ」。",
    relatedWords: ["shower", "bathe", "bathroom"],
  },
  {
    id: "batter",
    word: "batter",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["(料理の)衣、生地", "打ちつける、殴打する"],
    pronunciation: "/ˈbætər/",
    exampleSentence: "Dip the fish in batter and fry it.",
    exampleTranslationJa: "魚を衣にくぐらせて揚げて。",
    collocations: ["fish in batter", "a thin batter", "batter the door down"],
    mnemonic: "beat(打つ)から。混ぜて打った柔らかい生地が「衣」で、たたく意味では「連打する」。",
    relatedWords: ["dough", "fry", "mix"],
  },
  {
    id: "be",
    word: "be",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜である、〜にいる"],
    pronunciation: "/biː/",
    exampleSentence: "I want to be a doctor in the future.",
    exampleTranslationJa: "将来医者になりたい。",
    collocations: ["be careful", "be quiet", "to be honest"],
    mnemonic: "be動詞の原形。am / is / are / was / were と形を変え、to の後に置ける唯一の形。",
    relatedWords: ["am", "is", "are"],
  },
  {
    id: "beach",
    word: "beach",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["浜辺、ビーチ"],
    pronunciation: "/biːtʃ/",
    exampleSentence: "We spent the afternoon on the beach.",
    exampleTranslationJa: "私たちは午後を浜辺で過ごした。",
    collocations: ["on the beach", "a sandy beach", "go to the beach"],
    mnemonic: "波に洗われた砂や小石の浜。湖岸の浜も beach と言い、岩がちな海岸は coast。",
    relatedWords: ["shore", "sand", "sea"],
  },
  {
    id: "beautiful",
    word: "beautiful",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["美しい、きれいな"],
    pronunciation: "/ˈbjuːtɪfl/",
    exampleSentence: "The garden looks beautiful in early summer.",
    exampleTranslationJa: "その庭は初夏に美しく見える。",
    collocations: ["a beautiful view", "beautiful weather", "look beautiful"],
    mnemonic: "beauty(美)+ -ful(〜に満ちた)。人・景色・天気まで広くほめるのに使える語。",
    relatedWords: ["beauty", "pretty", "lovely"],
  },
  {
    id: "because",
    word: "because",
    level: "A2",
    partOfSpeech: "接続詞",
    meaningsJa: ["〜だから、〜なので"],
    pronunciation: "/bɪˈkɔːz/",
    exampleSentence: "We stayed inside because it was raining hard.",
    exampleTranslationJa: "雨がひどく降っていたので、私たちは中にいた。",
    collocations: ["because of", "just because", "because I said so"],
    mnemonic: "理由を導く接続詞。後に名詞を続けるときは because of のように of を付ける。",
    relatedWords: ["since", "as", "so"],
  },
  {
    id: "become",
    word: "become",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜になる"],
    pronunciation: "/bɪˈkʌm/",
    exampleSentence: "She wants to become a nurse.",
    exampleTranslationJa: "彼女は看護師になりたがっている。",
    collocations: ["become famous", "become a teacher", "become clear"],
    mnemonic: "be-+ come(来る)で「ある状態に来る」。get より改まった言い方で、変化の結果に注目する。",
    relatedWords: ["get", "grow", "turn"],
  },
  {
    id: "bed",
    word: "bed",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ベッド、寝床"],
    pronunciation: "/bed/",
    exampleSentence: "He made his bed before leaving the room.",
    exampleTranslationJa: "彼は部屋を出る前にベッドを整えた。",
    collocations: ["go to bed", "make the bed", "in bed"],
    mnemonic: "「寝床」のこと。go to bed は「寝る」で、to を付けたまま冠詞は付けない。",
    relatedWords: ["sleep", "pillow", "bedroom"],
  },
  {
    id: "beer",
    word: "beer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ビール"],
    pronunciation: "/bɪr/",
    exampleSentence: "They ordered two glasses of beer.",
    exampleTranslationJa: "彼らはビールを2杯注文した。",
    collocations: ["a glass of beer", "cold beer", "a beer bottle"],
    mnemonic: "麦芽から造る飲み物。数えられない名詞なので a beer は「1杯・1本」の意味になる。",
    relatedWords: ["wine", "drink", "pub"],
  },
  {
    id: "beetroot",
    word: "beetroot",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ビート、テンサイの根(英)"],
    pronunciation: "/ˈbiːtruːt/",
    exampleSentence: "The salad was served with slices of beetroot.",
    exampleTranslationJa: "サラダにはビートの薄切りが添えられていた。",
    collocations: ["pickled beetroot", "a beetroot salad", "grow beetroot"],
    mnemonic: "beet(ビート)+ root(根)。赤い根を食べる野菜で、米国では beet と呼ぶ。",
    relatedWords: ["beet", "vegetable", "salad"],
  },
  {
    id: "begin",
    word: "begin",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["始める、始まる"],
    pronunciation: "/bɪˈɡɪn/",
    exampleSentence: "The concert will begin at seven o'clock.",
    exampleTranslationJa: "コンサートは7時に始まります。",
    collocations: ["begin with", "begin to rain", "the beginning of"],
    mnemonic: "start より改まった語。過去形は began、過去分詞は begun と母音が変わる。",
    relatedWords: ["start", "end", "finish"],
  },
  {
    id: "beginner",
    word: "beginner",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["初心者"],
    pronunciation: "/bɪˈɡɪnər/",
    exampleSentence: "This class is designed for complete beginners.",
    exampleTranslationJa: "このクラスはまったくの初心者向けに作られている。",
    collocations: ["a beginner's course", "for beginners", "a complete beginner"],
    mnemonic: "begin(始める)+ -er で、始めたばかりの人。上級者は advanced learner と言う。",
    relatedWords: ["begin", "novice", "advanced"],
  },
  {
    id: "behind",
    word: "behind",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜の後ろに", "遅れて"],
    pronunciation: "/bɪˈhaɪnd/",
    exampleSentence: "The cat is hiding behind the sofa.",
    exampleTranslationJa: "猫がソファの後ろに隠れている。",
    collocations: ["behind the house", "fall behind", "leave behind"],
    mnemonic: "be-+ hind(後ろ)で「後ろ側」。in front of の反対語で、遅れの意味にも広がる。",
    relatedWords: ["front", "after", "under"],
  },
  {
    id: "believe",
    word: "believe",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["信じる、〜だと思う"],
    pronunciation: "/bɪˈliːv/",
    exampleSentence: "I believe she is telling the truth.",
    exampleTranslationJa: "彼女は本当のことを言っていると思う。",
    collocations: ["believe in", "believe it or not", "hard to believe"],
    mnemonic: "be-+ lieve(愛する・大事にする)。「大切に思う」から「本当だと信じる」へ意味が広がった。",
    relatedWords: ["belief", "trust", "doubt"],
  },
  {
    id: "below",
    word: "below",
    level: "A2",
    partOfSpeech: "前置詞・副詞",
    meaningsJa: ["〜より下に、以下の"],
    pronunciation: "/bɪˈloʊ/",
    exampleSentence: "The temperature fell below zero last night.",
    exampleTranslationJa: "昨夜は気温が0度を下回った。",
    collocations: ["below zero", "below average", "as shown below"],
    mnemonic: "be-+ low(低い)で、基準より下を表す。above の反対語。under は真下・覆われた感じ。",
    relatedWords: ["under", "above", "beneath"],
  },
  {
    id: "big",
    word: "big",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["大きい", "重要な"],
    pronunciation: "/bɪɡ/",
    exampleSentence: "They live in a big house near the lake.",
    exampleTranslationJa: "彼らは湖の近くの大きな家に住んでいる。",
    collocations: ["a big city", "a big difference", "make a big decision"],
    mnemonic: "large より口語的で、大きさと重要性の両方に使う。反対語は small や little。",
    relatedWords: ["large", "huge", "small"],
  },
  {
    id: "bike",
    word: "bike",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["自転車(口語)"],
    pronunciation: "/baɪk/",
    exampleSentence: "She rides her bike to school every day.",
    exampleTranslationJa: "彼女は毎日自転車で学校へ行く。",
    collocations: ["ride a bike", "a mountain bike", "get on a bike"],
    mnemonic: "bicycle の短縮形。オートバイは motorbike や motor bike と言うので区別する。",
    relatedWords: ["bicycle", "cycle", "motorbike"],
  },
  {
    id: "bikini",
    word: "bikini",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ビキニ(水着)"],
    pronunciation: "/bɪˈkiːni/",
    exampleSentence: "She packed a bikini for the beach holiday.",
    exampleTranslationJa: "彼女は海の休暇用にビキニを詰めた。",
    collocations: ["wear a bikini", "a bikini top", "a new bikini"],
    mnemonic: "原爆実験が行われたビキニ環礁にちなんだ命名で、上下2点でできた水着。top と bottom に分かれる。",
    relatedWords: ["swimsuit", "beach", "swim"],
  },
  {
    id: "bird",
    word: "bird",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["鳥"],
    pronunciation: "/bɜːrd/",
    exampleSentence: "A small bird was singing in the tree.",
    exampleTranslationJa: "小さな鳥が木で鳴いていた。",
    collocations: ["a wild bird", "bird watching", "a flock of birds"],
    mnemonic: "羽とくちばしを持ち、卵を産む生き物。英国英語では若い女性を指す口語的な呼び方にもなる。",
    relatedWords: ["animal", "wing", "nest"],
  },
  {
    id: "birthday",
    word: "birthday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["誕生日"],
    pronunciation: "/ˈbɜːrθdeɪ/",
    exampleSentence: "My birthday is on the tenth of May.",
    exampleTranslationJa: "私の誕生日は5月10日です。",
    collocations: ["a birthday party", "Happy birthday", "a birthday cake"],
    mnemonic: "birth(誕生)+ day(日)。Happy birthday to you の歌は世界中で歌われている。",
    relatedWords: ["birth", "party", "cake"],
  },
  {
    id: "black",
    word: "black",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["黒い", "黒"],
    pronunciation: "/blæk/",
    exampleSentence: "He wore a black coat and a hat.",
    exampleTranslationJa: "彼は黒いコートと帽子を身につけていた。",
    collocations: ["black coffee", "a black cat", "black and white"],
    mnemonic: "光をすべて吸収する色。black coffee は「ミルクを入れないコーヒー」のこと。",
    relatedWords: ["white", "dark", "shade"],
  },
  {
    id: "blackboard",
    word: "blackboard",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["黒板"],
    pronunciation: "/ˈblækbɔːrd/",
    exampleSentence: "The teacher wrote the date on the blackboard.",
    exampleTranslationJa: "先生は黒板に日付を書いた。",
    collocations: ["on the blackboard", "write on the blackboard", "clean the blackboard"],
    mnemonic: "black(黒)+ board(板)。今は緑色のものが多く、白い板は whiteboard と言う。",
    relatedWords: ["board", "chalk", "whiteboard"],
  },
  {
    id: "blazer",
    word: "blazer",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ブレザー、上着"],
    pronunciation: "/ˈbleɪzər/",
    exampleSentence: "He wears a navy blazer to work.",
    exampleTranslationJa: "彼は紺のブレザーを着て仕事に行く。",
    collocations: ["a navy blazer", "wear a blazer", "a school blazer"],
    mnemonic: "blaze(燃える)から。もとは燃えるような赤い上着を指し、今は学校や会社の制服の上着も指す。",
    relatedWords: ["jacket", "suit", "uniform"],
  },
  {
    id: "blue",
    word: "blue",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["青い", "青"],
    pronunciation: "/bluː/",
    exampleSentence: "The sky was clear and blue all day.",
    exampleTranslationJa: "空は一日中澄んで青かった。",
    collocations: ["dark blue", "a blue sky", "out of the blue"],
    mnemonic: "「青」。out of the blue は「突然」。気分が沈む「憂うつ」の意味もある。",
    relatedWords: ["sky", "green", "sea"],
  },
  {
    id: "boat",
    word: "boat",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ボート、小舟"],
    pronunciation: "/boʊt/",
    exampleSentence: "We crossed the lake in a small boat.",
    exampleTranslationJa: "私たちは小さなボートで湖を渡った。",
    collocations: ["by boat", "a fishing boat", "row a boat"],
    mnemonic: "小型の船。大型の船は ship で、移動手段として使うときは by boat と言う。",
    relatedWords: ["ship", "sail", "ferry"],
  },
  {
    id: "body",
    word: "body",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["体、身体", "団体"],
    pronunciation: "/ˈbɑːdi/",
    exampleSentence: "Regular exercise keeps the body healthy.",
    exampleTranslationJa: "定期的な運動は体を健康に保つ。",
    collocations: ["the human body", "body language", "keep the body warm"],
    mnemonic: "「胴・本体」が原義。そこから「団体」の意味も生まれ、student body は「学生全体」。",
    relatedWords: ["head", "health", "shape"],
  },
  {
    id: "bored",
    word: "bored",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["退屈した、飽きた"],
    pronunciation: "/bɔːrd/",
    exampleSentence: "The students looked bored during the long lecture.",
    exampleTranslationJa: "学生たちは長い講義の間、退屈そうだった。",
    collocations: ["bored with", "get bored", "look bored"],
    mnemonic: "bore(退屈させる)の形容詞。人が退屈した状態が bored、物が退屈なのが boring。",
    relatedWords: ["boring", "tired", "dull"],
  },
  {
    id: "boring",
    word: "boring",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["退屈な、つまらない"],
    pronunciation: "/ˈbɔːrɪŋ/",
    exampleSentence: "The film was so boring that I fell asleep.",
    exampleTranslationJa: "その映画はとても退屈で、私は眠ってしまった。",
    collocations: ["a boring film", "boring work", "find it boring"],
    mnemonic: "物や話が人を退屈させるのが boring。自分が退屈しているときは bored を使う。",
    relatedWords: ["bored", "dull", "tiring"],
  },
  {
    id: "born",
    word: "born",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["生まれた"],
    pronunciation: "/bɔːrn/",
    exampleSentence: "She was born in a small village in Spain.",
    exampleTranslationJa: "彼女はスペインの小さな村で生まれた。",
    collocations: ["be born in", "be born on", "a born leader"],
    mnemonic: "bear(産む)の過去分詞。受け身の be born で「生まれる」。場所は in、日は on を続ける。",
    relatedWords: ["birth", "bear", "child"],
  },
  {
    id: "both",
    word: "both",
    level: "A2",
    partOfSpeech: "限定詞・代名詞",
    meaningsJa: ["両方の、どちらも"],
    pronunciation: "/boʊθ/",
    exampleSentence: "Both of my sisters play the piano.",
    exampleTranslationJa: "姉妹は2人ともピアノを弾く。",
    collocations: ["both of them", "both of us", "we both"],
    mnemonic: "2つのものをまとめて指す語。3つ以上には all を使い、片方だけなら either を使う。",
    relatedWords: ["all", "either", "neither"],
  },
  {
    id: "bottle opener",
    word: "bottle opener",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["栓抜き"],
    pronunciation: "/ˈbɑːtl oʊpənər/",
    exampleSentence: "Could you pass me the bottle opener?",
    exampleTranslationJa: "栓抜きを取ってもらえますか。",
    collocations: ["a beer bottle opener", "use a bottle opener", "a wall bottle opener"],
    mnemonic: "bottle(びん)+ opener(開ける道具)。王冠のふたをてこの原理で外す道具。",
    relatedWords: ["opener", "bottle", "corkscrew"],
  },
  {
    id: "box",
    word: "box",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["箱"],
    pronunciation: "/bɑːks/",
    exampleSentence: "He put the old photos in a box.",
    exampleTranslationJa: "彼は古い写真を箱に入れた。",
    collocations: ["a cardboard box", "a box of chocolates", "open a box"],
    mnemonic: "四角い入れ物。動詞では「箱に詰める」で、ボクシングの box(打ち合う)は別の語源。",
    relatedWords: ["case", "container", "packet"],
  },
  {
    id: "boxer",
    word: "boxer",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ボクサー、拳闘家", "ボクサー犬"],
    pronunciation: "/ˈbɑːksər/",
    exampleSentence: "The young boxer won his first fight.",
    exampleTranslationJa: "その若いボクサーは初めての試合に勝った。",
    collocations: ["a professional boxer", "a heavyweight boxer", "a boxer dog"],
    mnemonic: "box(打ち合う)+ -er で、拳で戦う人。犬種のボクサーも同じつづりで表す。",
    relatedWords: ["boxing", "fight", "ring"],
  },
  {
    id: "boy",
    word: "boy",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["男の子、少年"],
    pronunciation: "/bɔɪ/",
    exampleSentence: "The boy ran to catch the school bus.",
    exampleTranslationJa: "その少年は学校のバスに間に合うよう走った。",
    collocations: ["a little boy", "a school boy", "boys and girls"],
    mnemonic: "「男の子」を表す基礎語。大人の男性は man、対になる女の子は girl と言う。",
    relatedWords: ["girl", "man", "child"],
  },
  {
    id: "bread",
    word: "bread",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パン"],
    pronunciation: "/bred/",
    exampleSentence: "She bought fresh bread at the bakery.",
    exampleTranslationJa: "彼女はパン屋で焼きたてのパンを買った。",
    collocations: ["a slice of bread", "fresh bread", "bread and butter"],
    mnemonic: "数えられない名詞なので a bread ではなく a slice や a loaf of bread と言う。",
    relatedWords: ["bakery", "butter", "flour"],
  },
  {
    id: "break",
    word: "break",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["壊す、割る", "休憩"],
    pronunciation: "/breɪk/",
    exampleSentence: "Be careful not to break the glass.",
    exampleTranslationJa: "ガラスを割らないよう気をつけて。",
    collocations: ["take a break", "break the rules", "break a window"],
    mnemonic: "「壊す」と「休憩」の2つの意味。仕事を中断する break time が休憩の意味につながる。",
    relatedWords: ["breakable", "rest", "pause"],
  },
  {
    id: "bring",
    word: "bring",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["持ってくる、連れてくる"],
    pronunciation: "/brɪŋ/",
    exampleSentence: "Please bring your notebook to the next class.",
    exampleTranslationJa: "次の授業にノートを持ってきてください。",
    collocations: ["bring a friend", "bring back", "bring up"],
    mnemonic: "話し手の方へ「持ってくる」のが bring。向こうへ持っていくのは take。過去形は brought。",
    relatedWords: ["take", "carry", "fetch"],
  },
  {
    id: "brother",
    word: "brother",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["兄、弟"],
    pronunciation: "/ˈbrʌðər/",
    exampleSentence: "My older brother works in a hospital.",
    exampleTranslationJa: "私の兄は病院で働いている。",
    collocations: ["an older brother", "a younger brother", "a big brother"],
    mnemonic: "男性のきょうだい。姉妹は sister。兄か弟かは older や younger を付けて示す。",
    relatedWords: ["sister", "sibling", "family"],
  },
  {
    id: "brown",
    word: "brown",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["茶色の", "茶色"],
    pronunciation: "/braʊn/",
    exampleSentence: "She has long brown hair and dark eyes.",
    exampleTranslationJa: "彼女は長い茶色の髪と黒い目をしている。",
    collocations: ["brown hair", "brown eyes", "dark brown"],
    mnemonic: "「茶色」。焼けた色が原義とされ、bear(熊)と同じ語根だと言われる。brown sugar は茶色の砂糖。",
    relatedWords: ["tan", "black", "dark"],
  },
  {
    id: "build",
    word: "build",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["建てる、組み立てる"],
    pronunciation: "/bɪld/",
    exampleSentence: "They plan to build a new bridge here.",
    exampleTranslationJa: "彼らはここに新しい橋を架ける計画だ。",
    collocations: ["build a house", "build up", "build a relationship"],
    mnemonic: "材料を積み上げて形にすること。過去形も過去分詞も built で同じ形。build up は「少しずつ増やす」。",
    relatedWords: ["building", "make", "construct"],
  },
  {
    id: "building",
    word: "building",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["建物、ビル"],
    pronunciation: "/ˈbɪldɪŋ/",
    exampleSentence: "That tall building is a famous hotel.",
    exampleTranslationJa: "あの高い建物は有名なホテルだ。",
    collocations: ["a tall building", "an office building", "a historic building"],
    mnemonic: "build(建てる)+ -ing で、建てられた物そのもの。日本語の「ビル」もこの語から。",
    relatedWords: ["build", "house", "tower"],
  },
  {
    id: "bus",
    word: "bus",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["バス"],
    pronunciation: "/bʌs/",
    exampleSentence: "I take the bus to work every morning.",
    exampleTranslationJa: "私は毎朝バスで仕事に行く。",
    collocations: ["take a bus", "a bus stop", "miss the bus"],
    mnemonic: "omnibus(すべての人のための)の短縮形。移動手段として使うときは by bus と言う。",
    relatedWords: ["coach", "transport", "stop"],
  },
  {
    id: "business",
    word: "business",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["仕事、商売", "会社"],
    pronunciation: "/ˈbɪznəs/",
    exampleSentence: "He runs a small business in the city.",
    exampleTranslationJa: "彼は市内で小さな商売を営んでいる。",
    collocations: ["do business", "a small business", "business trip"],
    mnemonic: "busy(忙しい)+ -ness。忙しく働くことが商売。発音は「ビズネス」で i が抜ける。",
    relatedWords: ["busy", "company", "trade"],
  },
  {
    id: "busy",
    word: "busy",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["忙しい", "にぎわった"],
    pronunciation: "/ˈbɪzi/",
    exampleSentence: "She is too busy to answer the phone.",
    exampleTranslationJa: "彼女は忙しすぎて電話に出られない。",
    collocations: ["a busy day", "busy with work", "a busy street"],
    mnemonic: "仕事が多い状態と人通りが多い状態の両方を指す。be busy with / be busy doing の形を取る。",
    relatedWords: ["business", "free", "crowded"],
  },
  {
    id: "buy",
    word: "buy",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["買う"],
    pronunciation: "/baɪ/",
    exampleSentence: "I want to buy a gift for my mother.",
    exampleTranslationJa: "母に贈り物を買いたい。",
    collocations: ["buy a present", "buy online", "buy time"],
    mnemonic: "お金を払って手に入れること。過去形も過去分詞も bought。by(そばに)と同音。",
    relatedWords: ["sell", "purchase", "pay"],
  },
  {
    id: "cake",
    word: "cake",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ケーキ、菓子"],
    pronunciation: "/keɪk/",
    exampleSentence: "She baked a chocolate cake for his birthday.",
    exampleTranslationJa: "彼女は彼の誕生日にチョコレートケーキを焼いた。",
    collocations: ["a birthday cake", "bake a cake", "a piece of cake"],
    mnemonic: "焼き菓子全般を指す。a piece of cake は「とても簡単なこと」の口語表現。",
    relatedWords: ["bake", "dessert", "bread"],
  },
  {
    id: "call",
    word: "call",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["電話する、呼ぶ", "通話"],
    pronunciation: "/kɔːl/",
    exampleSentence: "I will call you as soon as I arrive.",
    exampleTranslationJa: "着いたらすぐに電話します。",
    collocations: ["call back", "make a call", "call the police"],
    mnemonic: "声を上げて名を呼ぶのが原義。そこから「呼ぶ・電話する・名づける」に意味が広がった。",
    relatedWords: ["phone", "name", "ring"],
  },
  {
    id: "came",
    word: "came",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["来た(come の過去形)"],
    pronunciation: "/keɪm/",
    exampleSentence: "She came to Japan three years ago.",
    exampleTranslationJa: "彼女は3年前に日本へ来た。",
    collocations: ["came back", "came from", "came to see"],
    mnemonic: "come の過去形。過去分詞は come と同じつづりなので、came は過去だけの形。",
    relatedWords: ["come", "go", "arrive"],
  },
  {
    id: "camera",
    word: "camera",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["カメラ"],
    pronunciation: "/ˈkæmərə/",
    exampleSentence: "He took photos with a new digital camera.",
    exampleTranslationJa: "彼は新しいデジタルカメラで写真を撮った。",
    collocations: ["a digital camera", "take a camera", "on camera"],
    mnemonic: "ラテン語 camera(部屋)から。camera obscura(暗い部屋)が写真機の起源。",
    relatedWords: ["photo", "lens", "photograph"],
  },
  {
    id: "herring",
    word: "herring",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ニシン"],
    pronunciation: "/ˈherɪŋ/",
    exampleSentence: "We ate pickled herring with boiled potatoes.",
    exampleTranslationJa: "私たちはゆでたじゃがいもと一緒にニシンの酢漬けを食べた。",
    collocations: ["pickled herring", "smoked herring", "a shoal of herring"],
    mnemonic: "ニシンを表す語。salt herring は塩漬け、red herring は「本題からそらす手がかり」。",
    relatedWords: ["fish", "salmon", "tuna"],
  },
  {
    id: "mackerel",
    word: "mackerel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["サバ"],
    pronunciation: "/ˈmækərəl/",
    exampleSentence: "We bought fresh mackerel at the fish market.",
    exampleTranslationJa: "私たちは魚市場で新鮮なサバを買った。",
    collocations: ["smoked mackerel", "fresh mackerel", "a mackerel fillet"],
    mnemonic: "背中に縞模様のある青い魚。日本ではサバ、英国では smoked mackerel が定番。",
    relatedWords: ["fish", "tuna", "sardine"],
  },
]
