import type { VocabularyEntry } from '../types'

// 増補 第47弾。8,000語 → 8,800語 の増補計画の一部。
export const plus47: VocabularyEntry[] = [
  {
    id: "tired",
    word: "tired",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["疲れた", "飽きて"],
    pronunciation: "/ˈtaɪərd/",
    exampleSentence: "I was too tired to cook dinner last night.",
    exampleTranslationJa: "昨夜は疲れすぎて夕食を作れなかった。",
    collocations: ["feel tired", "too tired to", "dead tired"],
    mnemonic: "tire(疲れさせる)+ -ed。be tired of 〜 で「〜に飽きている」という別の意味になる。",
    relatedWords: ["tire", "exhausted", "sleepy"],
  },
  {
    id: "to",
    word: "to",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜へ、〜に", "〜のために", "(不定詞を作る)"],
    pronunciation: "/tuː/",
    exampleSentence: "She walked to the station with her friend.",
    exampleTranslationJa: "彼女は友達と駅まで歩いた。",
    collocations: ["go to school", "from A to B", "listen to music"],
    mnemonic: "方向と到達点を示す前置詞。動詞の前に置くと「〜すること」の不定詞を作り、be going to のような表現にも使う。",
    relatedWords: ["towards", "into", "for"],
  },
  {
    id: "toasters",
    word: "toasters",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トースター(複数形)"],
    pronunciation: "/ˈtoʊstərz/",
    exampleSentence: "The shop sells toasters, kettles and coffee makers.",
    exampleTranslationJa: "その店はトースターや電気ケトル、コーヒーメーカーを売っている。",
    collocations: ["electric toasters", "two toasters", "sell toasters"],
    mnemonic: "toast(パンを焼く)+ -er の複数形。数えられる名詞なので、2台以上なら -s を付ける。",
    relatedWords: ["toaster", "toast", "kettle"],
  },
  {
    id: "today",
    word: "today",
    level: "A2",
    partOfSpeech: "副詞・名詞",
    meaningsJa: ["今日", "今日は"],
    pronunciation: "/təˈdeɪ/",
    exampleSentence: "Today is the last day of the school year.",
    exampleTranslationJa: "今日は学年最後の日だ。",
    collocations: ["today's news", "later today", "from today"],
    mnemonic: "to + day で「今日この日」。yesterday(昨日)・tomorrow(明日)と3語そろえて覚える。",
    relatedWords: ["yesterday", "tomorrow", "tonight"],
  },
  {
    id: "together",
    word: "together",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["一緒に", "まとめて"],
    pronunciation: "/təˈɡeðər/",
    exampleSentence: "We studied together for the exam all week.",
    exampleTranslationJa: "私たちは一週間ずっと一緒に試験勉強をした。",
    collocations: ["work together", "get together", "all together"],
    mnemonic: "to + gather(集める)と考えると覚えやすい。「一か所に集まって」から「まとめて」の意味にも広がる。",
    relatedWords: ["gather", "apart", "alone"],
  },
  {
    id: "toilet",
    word: "toilet",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トイレ、便所", "化粧、身づくろい"],
    pronunciation: "/ˈtɔɪlɪt/",
    exampleSentence: "The toilet is at the end of the corridor.",
    exampleTranslationJa: "トイレは廊下の突き当たりにある。",
    collocations: ["go to the toilet", "a public toilet", "toilet paper"],
    mnemonic: "もとは「身づくろい」の意味で、その名残が toilet water(化粧水)にある。今は便器や便所を指す。",
    relatedWords: ["bathroom", "lavatory", "sink"],
  },
  {
    id: "tomato",
    word: "tomato",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トマト"],
    pronunciation: "/təˈmeɪtoʊ/",
    exampleSentence: "She added a fresh tomato to the salad.",
    exampleTranslationJa: "彼女はサラダに新鮮なトマトを加えた。",
    collocations: ["a fresh tomato", "tomato sauce", "cherry tomatoes"],
    mnemonic: "複数形は tomatoes と -es を付ける。potato も同じ仲間で、-o の前が子音の語は -es になる。",
    relatedWords: ["potato", "vegetable", "sauce"],
  },
  {
    id: "tomorrow",
    word: "tomorrow",
    level: "A2",
    partOfSpeech: "副詞・名詞",
    meaningsJa: ["明日", "明日は"],
    pronunciation: "/təˈmɑːroʊ/",
    exampleSentence: "I will call you tomorrow after work.",
    exampleTranslationJa: "明日、仕事のあとで電話します。",
    collocations: ["tomorrow morning", "see you tomorrow", "the day after tomorrow"],
    mnemonic: "to + morrow(morning の古い形)で「次の朝」。yesterday と today に挟まれた1日を指す。",
    relatedWords: ["today", "yesterday", "tonight"],
  },
  {
    id: "tongs",
    word: "tongs",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["トング、はさみ(台所用)"],
    pronunciation: "/tɔːŋz/",
    exampleSentence: "He turned the sausages with a pair of tongs.",
    exampleTranslationJa: "彼はトングでソーセージをひっくり返した。",
    collocations: ["a pair of tongs", "kitchen tongs", "pick up with tongs"],
    mnemonic: "2本の腕が1組になった道具なので、いつも複数形で使う。数えるときは a pair of tongs と言う。",
    relatedWords: ["tweezers", "spoon", "kitchen"],
  },
  {
    id: "tonight",
    word: "tonight",
    level: "A2",
    partOfSpeech: "副詞・名詞",
    meaningsJa: ["今夜", "今夜は"],
    pronunciation: "/təˈnaɪt/",
    exampleSentence: "There is a concert in the park tonight.",
    exampleTranslationJa: "今夜、公園でコンサートがある。",
    collocations: ["tonight's dinner", "later tonight", "stay in tonight"],
    mnemonic: "to + night で「今夜」。today が昼の部分、tonight が夜の部分を受け持つ。",
    relatedWords: ["today", "night", "evening"],
  },
  {
    id: "too",
    word: "too",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["〜もまた", "〜すぎる"],
    pronunciation: "/tuː/",
    exampleSentence: "The soup is too hot to eat right now.",
    exampleTranslationJa: "そのスープは今すぐ食べるには熱すぎる。",
    collocations: ["too much", "me too", "too late"],
    mnemonic: "文末に置くと「〜もまた」、形容詞の前に置くと「〜すぎる」。two・to と発音が同じなので文脈で見分ける。",
    relatedWords: ["also", "enough", "two"],
  },
  {
    id: "tooth",
    word: "tooth",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["歯", "(くしやのこぎりの)歯"],
    pronunciation: "/tuːθ/",
    exampleSentence: "The dentist checked every tooth in my mouth.",
    exampleTranslationJa: "歯科医は私の口の中の歯を一本ずつ診た。",
    collocations: ["a sweet tooth", "brush your teeth", "a baby tooth"],
    mnemonic: "複数形は teeth と母音が変わる。foot → feet と同じ変化なので、2つを並べて覚える。",
    relatedWords: ["teeth", "dentist", "mouth"],
  },
  {
    id: "toothpick",
    word: "toothpick",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["つまようじ"],
    pronunciation: "/ˈtuːθpɪk/",
    exampleSentence: "She picked the olive out with a toothpick.",
    exampleTranslationJa: "彼女はつまようじでオリーブを刺して取った。",
    collocations: ["use a toothpick", "a wooden toothpick", "a box of toothpicks"],
    mnemonic: "tooth(歯)+ pick(つつく道具)。食後の口直しや料理の飾りに使う細い木の棒。",
    relatedWords: ["pick", "tooth", "skewer"],
  },
  {
    id: "topic",
    word: "topic",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["話題、テーマ"],
    pronunciation: "/ˈtɑːpɪk/",
    exampleSentence: "The main topic of the meeting was the new plan.",
    exampleTranslationJa: "会議の主な議題は新しい計画だった。",
    collocations: ["change the topic", "the main topic", "a hot topic"],
    mnemonic: "話の「主題」を指す語。話を元に戻すときは back to the topic と言う。",
    relatedWords: ["subject", "theme", "issue"],
  },
  {
    id: "tornado",
    word: "tornado",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["竜巻"],
    pronunciation: "/tɔːrˈneɪdoʊ/",
    exampleSentence: "The tornado tore the roof off the barn.",
    exampleTranslationJa: "竜巻は納屋の屋根を吹き飛ばした。",
    collocations: ["a violent tornado", "a tornado warning", "tornado season"],
    mnemonic: "turn(回る)と同じ語根で「回転する風」を指す。日本語の「トルネード」と同じ語で、地上に強い渦を作る。",
    relatedWords: ["storm", "typhoon", "wind"],
  },
  {
    id: "town",
    word: "town",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["町", "中心街"],
    pronunciation: "/taʊn/",
    exampleSentence: "She grew up in a small town near the sea.",
    exampleTranslationJa: "彼女は海の近くの小さな町で育った。",
    collocations: ["a small town", "go into town", "the town centre"],
    mnemonic: "村(village)より大きく、市(city)より小さい。go into town は「中心街へ出かける」。",
    relatedWords: ["village", "city", "street"],
  },
  {
    id: "town hall",
    word: "town hall",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["市役所、町役場", "市民会館"],
    pronunciation: "/ˌtaʊn ˈhɔːl/",
    exampleSentence: "They got married at the town hall last spring.",
    exampleTranslationJa: "彼らは昨年の春、市役所で結婚した。",
    collocations: ["at the town hall", "a town hall meeting", "the old town hall"],
    mnemonic: "town(町)+ hall(大広間)。行政の窓口と式場を兼ねた公共の建物を指す。",
    relatedWords: ["city hall", "office", "council"],
  },
  {
    id: "tracksuit",
    word: "tracksuit",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ジャージ、トレーニング着"],
    pronunciation: "/ˈtræksuːt/",
    exampleSentence: "He wore a grey tracksuit to the gym.",
    exampleTranslationJa: "彼は体育館へ灰色のジャージを着ていった。",
    collocations: ["wear a tracksuit", "a grey tracksuit", "tracksuit trousers"],
    mnemonic: "track(競走路)+ suit(服)で、運動場や街で着る上下そろいの服を指す。上は top、下は trousers と呼ぶ。",
    relatedWords: ["sweatshirt", "shorts", "gym"],
  },
  {
    id: "trade-off",
    word: "trade-off",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(二者択一の)妥協、トレードオフ"],
    pronunciation: "/ˈtreɪdɔːf/",
    exampleSentence: "There is always a trade-off between speed and safety.",
    exampleTranslationJa: "速さと安全の間には、常にどちらかを犠牲にする関係がある。",
    collocations: ["a trade-off between", "accept a trade-off", "a difficult trade-off"],
    mnemonic: "trade(交換する)+ off。一方を取れば他方を手放す関係を指し、between A and B と組む。",
    relatedWords: ["compromise", "balance", "choice"],
  },
  {
    id: "traffic",
    word: "traffic",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["交通、通行", "(人や車の)流れ"],
    pronunciation: "/ˈtræfɪk/",
    exampleSentence: "The traffic was heavy on the road to the airport.",
    exampleTranslationJa: "空港へ向かう道路は交通が混んでいた。",
    collocations: ["heavy traffic", "traffic lights", "a traffic jam"],
    mnemonic: "数えられない名詞なので a traffic とは言わない。渋滞は a traffic jam と表現する。",
    relatedWords: ["car", "road", "jam"],
  },
  {
    id: "travel",
    word: "travel",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["旅をする", "旅行"],
    pronunciation: "/ˈtrævl/",
    exampleSentence: "They travel to Italy every summer by train.",
    exampleTranslationJa: "彼らは毎年夏に列車でイタリアへ旅行する。",
    collocations: ["travel abroad", "air travel", "travel light"],
    mnemonic: "動詞の travel は「旅をする」、名詞の trip は「1回の旅行」。名詞の travel は数えられない。",
    relatedWords: ["trip", "journey", "tourist"],
  },
  {
    id: "tree",
    word: "tree",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["木", "(家系などの)樹形図"],
    pronunciation: "/triː/",
    exampleSentence: "A tall tree grew beside the old gate.",
    exampleTranslationJa: "古い門のそばに高い木が育っていた。",
    collocations: ["plant a tree", "a tall tree", "in the shade of a tree"],
    mnemonic: "幹が1本で高く伸びる木を指す。低く枝分かれする茂みは bush で、この2語は区別して覚える。",
    relatedWords: ["leaf", "branch", "forest"],
  },
  {
    id: "true",
    word: "true",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["本当の、正しい", "(夢が)実現して"],
    pronunciation: "/truː/",
    exampleSentence: "The story he told us was completely true.",
    exampleTranslationJa: "彼が話してくれた話は完全に本当だった。",
    collocations: ["come true", "a true story", "true or false"],
    mnemonic: "truth(真実)の形容詞。come true で「(夢が)実現する」という意味になる。",
    relatedWords: ["truth", "real", "false"],
  },
  {
    id: "grower",
    word: "grower",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["栽培者、生産者"],
    pronunciation: "/ˈɡroʊər/",
    exampleSentence: "The coffee grower sold his beans to a local trader.",
    exampleTranslationJa: "そのコーヒー栽培者は豆を地元の商人に売った。",
    collocations: ["a coffee grower", "a fruit grower", "a local grower"],
    mnemonic: "grow(育てる)+ -er。作物を育てて出荷する人を指し、農家の意味に近い。coffee grower のように作物名を前に置く。",
    relatedWords: ["grow", "farmer", "trader"],
  },
  {
    id: "turn",
    word: "turn",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["曲がる、回す", "順番", "変わる"],
    pronunciation: "/tɜːrn/",
    exampleSentence: "Turn left at the corner and walk a short way.",
    exampleTranslationJa: "角を左に曲がって、少し歩いてください。",
    collocations: ["turn left", "take a turn", "in turn"],
    mnemonic: "向きを変える動作を表す。名詞では「順番」の意味になり、It's your turn で「君の番だ」。",
    relatedWords: ["rotate", "change", "order"],
  },
  {
    id: "twelfth",
    word: "twelfth",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["12番目の", "12分の1"],
    pronunciation: "/twelfθ/",
    exampleSentence: "Her office is on the twelfth floor of the building.",
    exampleTranslationJa: "彼女の事務所はその建物の12階にある。",
    collocations: ["the twelfth floor", "the twelfth of May", "the twelfth time"],
    mnemonic: "twelve から ve が f に変わり、-th が付く。five → fifth と同じ変化をする。",
    relatedWords: ["twelve", "twentieth", "fifth"],
  },
  {
    id: "twelve",
    word: "twelve",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["12、十二", "12歳"],
    pronunciation: "/twelv/",
    exampleSentence: "There are twelve months in a year.",
    exampleTranslationJa: "1年には12か月ある。",
    collocations: ["twelve months", "twelve years old", "at twelve"],
    mnemonic: "eleven(11)と twelve(12)は -teen が付かない特別な数。複合語の twelfth では f に変わる。",
    relatedWords: ["eleven", "twenty", "twelfth"],
  },
  {
    id: "twentieth",
    word: "twentieth",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["20番目の", "20分の1"],
    pronunciation: "/ˈtwentiəθ/",
    exampleSentence: "The twentieth century brought many changes to the town.",
    exampleTranslationJa: "20世紀はその町に多くの変化をもたらした。",
    collocations: ["the twentieth century", "the twentieth time", "on the twentieth of June"],
    mnemonic: "twenty の y を i に変えて -eth を付ける。fifty → fiftieth と同じ作り方。",
    relatedWords: ["twenty", "twelfth", "century"],
  },
  {
    id: "twenty",
    word: "twenty",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["20、二十", "20歳"],
    pronunciation: "/ˈtwenti/",
    exampleSentence: "The class has twenty students this year.",
    exampleTranslationJa: "今年、そのクラスには20人の生徒がいる。",
    collocations: ["twenty minutes", "twenty years old", "in her twenties"],
    mnemonic: "-ty は10の倍数を作る接尾辞。20代は twenties と複数形で表し、強勢は前に置く。",
    relatedWords: ["twelve", "twentieth", "thirty"],
  },
  {
    id: "twice",
    word: "twice",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["2回、2度"],
    pronunciation: "/twaɪs/",
    exampleSentence: "She visits her grandmother twice a month.",
    exampleTranslationJa: "彼女は月に2回、祖母を訪ねる。",
    collocations: ["twice a week", "twice as much", "think twice"],
    mnemonic: "two + -ce で「2回」。3回以上は three times のように -times を使って数える。",
    relatedWords: ["two", "once", "again"],
  },
  {
    id: "two",
    word: "two",
    level: "A2",
    partOfSpeech: "数詞",
    meaningsJa: ["2、二", "2つ"],
    pronunciation: "/tuː/",
    exampleSentence: "Two of the windows were open.",
    exampleTranslationJa: "窓のうち2つが開いていた。",
    collocations: ["two years", "in two weeks", "two of them"],
    mnemonic: "to・too と発音が同じで、つづりは two だけが「2」を表す。twelve や twenty の tw- もここから。",
    relatedWords: ["twice", "twelve", "second"],
  },
  {
    id: "typhoon",
    word: "typhoon",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["台風"],
    pronunciation: "/taɪˈfuːn/",
    exampleSentence: "The typhoon brought heavy rain to the coast.",
    exampleTranslationJa: "台風は海岸に激しい雨をもたらした。",
    collocations: ["a strong typhoon", "a typhoon warning", "the typhoon season"],
    mnemonic: "中国語の「大風」が英語に入った語。日本語の「台風」と同じ由来で、形もよく似ている。",
    relatedWords: ["storm", "tornado", "wind"],
  },
  {
    id: "uncertain",
    word: "uncertain",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["確信がない", "はっきりしない、不確かな"],
    pronunciation: "/ʌnˈsɜːrtn/",
    exampleSentence: "I am uncertain about the date of the meeting.",
    exampleTranslationJa: "会議の日付について確信が持てない。",
    collocations: ["uncertain about", "an uncertain future", "remain uncertain"],
    mnemonic: "un-(否定)+ certain(確かな)。be uncertain about 〜 で「〜について迷っている」となる。",
    relatedWords: ["certain", "doubt", "unsure"],
  },
  {
    id: "under",
    word: "under",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜の下に", "〜未満の", "〜の支配下で"],
    pronunciation: "/ˈʌndər/",
    exampleSentence: "The cat is sleeping under the kitchen table.",
    exampleTranslationJa: "猫は台所のテーブルの下で眠っている。",
    collocations: ["under the table", "under ten minutes", "under control"],
    mnemonic: "「下」を表す前置詞。単に下を指す below と違い、何かに覆われている感じを伴う。",
    relatedWords: ["below", "over", "underneath"],
  },
  {
    id: "understand",
    word: "understand",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["理解する、わかる"],
    pronunciation: "/ˌʌndərˈstænd/",
    exampleSentence: "I do not understand this question at all.",
    exampleTranslationJa: "私はこの質問がまったく分からない。",
    collocations: ["understand a question", "fully understand", "make yourself understood"],
    mnemonic: "under + stand(立つ)で「下に立って支える」。ここから内容をつかむ意味が生まれたとされる。",
    relatedWords: ["under", "realize", "explain"],
  },
  {
    id: "university",
    word: "university",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["大学"],
    pronunciation: "/ˌjuːnɪˈvɜːrsəti/",
    exampleSentence: "She studies history at a university in Tokyo.",
    exampleTranslationJa: "彼女は東京の大学で歴史を学んでいる。",
    collocations: ["go to university", "a university student", "at university"],
    mnemonic: "universe(全体)と同じ語根で「多くの学問を1つにまとめた場」。英では「通う」の意味なら冠詞を付けない。",
    relatedWords: ["college", "student", "degree"],
  },
  {
    id: "untie",
    word: "untie",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["ほどく、結びを解く"],
    pronunciation: "/ʌnˈtaɪ/",
    exampleSentence: "He could not untie the knot in the rope.",
    exampleTranslationJa: "彼はロープの結び目をほどけなかった。",
    collocations: ["untie a knot", "untie the laces", "untie a rope"],
    mnemonic: "un-(反対)+ tie(結ぶ)。靴ひもやひもの結びを解く場面でよく使い、反対の動作は tie で「結ぶ」。",
    relatedWords: ["tie", "loosen", "undo"],
  },
  {
    id: "until",
    word: "until",
    level: "A2",
    partOfSpeech: "前置詞・接続詞",
    meaningsJa: ["〜まで(ずっと)", "〜するまで(は)"],
    pronunciation: "/ənˈtɪl/",
    exampleSentence: "We waited at the station until the last train left.",
    exampleTranslationJa: "私たちは最終列車が出るまで駅で待った。",
    collocations: ["until then", "not until later", "wait until"],
    mnemonic: "「その時まで続く」を表す。till とほぼ同じ意味だが、文頭では until のほうが好まれる。",
    relatedWords: ["till", "by", "since"],
  },
  {
    id: "unwrap",
    word: "unwrap",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["包みを解く、開ける"],
    pronunciation: "/ʌnˈræp/",
    exampleSentence: "The children unwrapped their presents early in the morning.",
    exampleTranslationJa: "子どもたちは朝早くにプレゼントの包みを開けた。",
    collocations: ["unwrap a present", "unwrap a parcel", "unwrap the plastic"],
    mnemonic: "un-(反対)+ wrap(包む)。贈り物の包みを開ける意味で特によく使う。包む紙は wrapping paper。",
    relatedWords: ["wrap", "open", "package"],
  },
  {
    id: "up",
    word: "up",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["上へ", "起きて", "(動作の完了)すっかり"],
    pronunciation: "/ʌp/",
    exampleSentence: "She looked up at the sky and smiled.",
    exampleTranslationJa: "彼女は空を見上げてほほえんだ。",
    collocations: ["get up", "look up", "up and down"],
    mnemonic: "下から上への動きを表す。動詞と組んで get up(起きる)や wash up(食器を洗う)を作る。",
    relatedWords: ["down", "above", "raise"],
  },
  {
    id: "uphill",
    word: "uphill",
    level: "A2",
    partOfSpeech: "形容詞・副詞",
    meaningsJa: ["上り坂の、上り坂で", "困難な"],
    pronunciation: "/ˌʌpˈhɪl/",
    exampleSentence: "The last part of the walk was steep and uphill.",
    exampleTranslationJa: "散歩の最後の区間は急で上り坂だった。",
    collocations: ["an uphill walk", "go uphill", "an uphill struggle"],
    mnemonic: "up(上)+ hill(丘)。坂を上る意味から「苦労の多い」という比喩にも使われる。",
    relatedWords: ["downhill", "hill", "steep"],
  },
  {
    id: "us",
    word: "us",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["私たちを", "私たちに"],
    pronunciation: "/ʌs/",
    exampleSentence: "Our teacher gave us a lot of homework.",
    exampleTranslationJa: "先生は私たちにたくさんの宿題を出した。",
    collocations: ["help us", "with us", "tell us"],
    mnemonic: "we の目的格で、「私たちを」と「私たちに」の両方を担う。前置詞の後ろにもそのまま置ける。",
    relatedWords: ["we", "our", "ourselves"],
  },
  {
    id: "useful",
    word: "useful",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["役に立つ、便利な"],
    pronunciation: "/ˈjuːsfl/",
    exampleSentence: "This app is useful for learning new words.",
    exampleTranslationJa: "このアプリは新しい単語を覚えるのに役に立つ。",
    collocations: ["useful for", "a useful tool", "very useful"],
    mnemonic: "use(使う)+ -ful(〜に満ちた)。反対は useless で、-less は「〜がない」を表す。",
    relatedWords: ["use", "useless", "helpful"],
  },
  {
    id: "usually",
    word: "usually",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["たいてい、ふつうは"],
    pronunciation: "/ˈjuːʒuəli/",
    exampleSentence: "I usually walk to work in fine weather.",
    exampleTranslationJa: "私は天気のよい日はたいてい歩いて仕事に行く。",
    collocations: ["usually get up early", "as usual", "usually quiet"],
    mnemonic: "usual(ふつうの)+ -ly。always と often の間の頻度を表し、習慣的な行動に使う。",
    relatedWords: ["usual", "often", "always"],
  },
  {
    id: "vacuum cleaner",
    word: "vacuum cleaner",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["電気掃除機"],
    pronunciation: "/ˈvækjuːm ˌkliːnər/",
    exampleSentence: "He ran the vacuum cleaner over the living room carpet.",
    exampleTranslationJa: "彼は居間のじゅうたんに掃除機をかけた。",
    collocations: ["use a vacuum cleaner", "a vacuum cleaner bag", "run the vacuum cleaner"],
    mnemonic: "vacuum(真空)+ cleaner(掃除するもの)。吸い込む力でほこりを取る道具。動詞なら vacuum だけで使える。",
    relatedWords: ["vacuum", "carpet", "dust"],
  },
  {
    id: "vegetable",
    word: "vegetable",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["野菜"],
    pronunciation: "/ˈvedʒtəbl/",
    exampleSentence: "She grows vegetables in the small garden behind the house.",
    exampleTranslationJa: "彼女は家の裏の小さな庭で野菜を育てている。",
    collocations: ["fresh vegetables", "a vegetable garden", "green vegetables"],
    mnemonic: "数えられる名詞で、複数形 vegetables がふつう。名詞を修飾する vegetable soup では単数形にする。",
    relatedWords: ["fruit", "garden", "carrot"],
  },
  {
    id: "video",
    word: "video",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["動画、ビデオ", "(動画の)録画"],
    pronunciation: "/ˈvɪdioʊ/",
    exampleSentence: "She posted a short video of her cat online.",
    exampleTranslationJa: "彼女は猫の短い動画をネットに投稿した。",
    collocations: ["watch a video", "a short video", "video call"],
    mnemonic: "ラテン語 videre(見る)から来た語。動画そのものと、録画した映像の両方を指す。",
    relatedWords: ["film", "camera", "record"],
  },
  {
    id: "violet",
    word: "violet",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["すみれ色の", "すみれ"],
    pronunciation: "/ˈvaɪələt/",
    exampleSentence: "She wore a violet dress to the party.",
    exampleTranslationJa: "彼女はパーティーにすみれ色のドレスを着ていった。",
    collocations: ["a violet dress", "light violet", "a violet flower"],
    mnemonic: "すみれの花の名がそのまま色の名になった語。紫より青みが強く明るい。英語の色名は花や果物に由来するものが多い。",
    relatedWords: ["purple", "flower", "colour"],
  },
  {
    id: "visit",
    word: "visit",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["訪れる、訪問する", "訪問"],
    pronunciation: "/ˈvɪzɪt/",
    exampleSentence: "We visit our grandparents every summer holiday.",
    exampleTranslationJa: "私たちは毎年夏休みに祖父母を訪ねる。",
    collocations: ["visit a friend", "a short visit", "pay a visit"],
    mnemonic: "人や場所に会いに行くことを表す。名詞では pay a visit(訪問する)という組み合わせが定番。",
    relatedWords: ["visitor", "stay", "call"],
  },
  {
    id: "wagon",
    word: "wagon",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["荷馬車、四輪の荷車", "(英)貨車"],
    pronunciation: "/ˈwæɡən/",
    exampleSentence: "The farmer loaded the hay onto the wagon.",
    exampleTranslationJa: "農夫は干し草を荷車に積んだ。",
    collocations: ["a horse-drawn wagon", "load a wagon", "a railway wagon"],
    mnemonic: "4つの車輪が付いた荷車を指す。屋根のない小型の運搬車にも使い、英では貨車の意味にもなる。",
    relatedWords: ["cart", "wheel", "load"],
  },
  {
    id: "wake",
    word: "wake",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["目を覚ます、起こす"],
    pronunciation: "/weɪk/",
    exampleSentence: "I wake up at six every weekday morning.",
    exampleTranslationJa: "私は平日は毎朝6時に目を覚ます。",
    collocations: ["wake up", "wake someone up", "wake early"],
    mnemonic: "wake up で「目が覚める」。布団から出る段階は get up なので、目覚める動作と区別する。",
    relatedWords: ["awake", "sleep", "rise"],
  },
  {
    id: "walk",
    word: "walk",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["歩く", "散歩"],
    pronunciation: "/wɔːk/",
    exampleSentence: "I walk to the station every morning.",
    exampleTranslationJa: "私は毎朝、駅まで歩く。",
    collocations: ["go for a walk", "walk home", "walk the dog"],
    mnemonic: "l を読まないので「ウォーク」と発音する。名詞では go for a walk の形が定番。",
    relatedWords: ["step", "run", "stroll"],
  },
  {
    id: "wall",
    word: "wall",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["壁、塀"],
    pronunciation: "/wɔːl/",
    exampleSentence: "A large map hung on the classroom wall.",
    exampleTranslationJa: "教室の壁に大きな地図が掛かっていた。",
    collocations: ["on the wall", "a brick wall", "climb the wall"],
    mnemonic: "部屋の内側の面も、外を囲む塀も wall で表す。壁紙は wallpaper という複合語になる。",
    relatedWords: ["floor", "ceiling", "wallpaper"],
  },
  {
    id: "want",
    word: "want",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["ほしいと思う、〜したい", "必要とする"],
    pronunciation: "/wɑːnt/",
    exampleSentence: "I want a cup of tea after this long day.",
    exampleTranslationJa: "こんなに長い一日のあとは紅茶が一杯ほしい。",
    collocations: ["want to go", "want a drink", "what do you want"],
    mnemonic: "want to 〜 で「〜したい」。need が「必要」、want は「欲しい」という気持ちを表す。",
    relatedWords: ["need", "wish", "hope"],
  },
  {
    id: "was",
    word: "was",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜だった、〜にいた(be の過去形)"],
    pronunciation: "/wʌz/",
    exampleSentence: "The film was much better than I expected.",
    exampleTranslationJa: "その映画は思っていたよりずっとよかった。",
    collocations: ["was born", "was not there", "it was"],
    mnemonic: "be動詞の過去形で、主語が I・he・she・it のときの形。you や複数の主語には were を使う。",
    relatedWords: ["were", "is", "been"],
  },
  {
    id: "wash up",
    word: "wash up",
    level: "A2",
    partOfSpeech: "句動詞",
    meaningsJa: ["食器を洗う(英)", "手を洗う(米)"],
    pronunciation: "/ˌwɑːʃ ˈʌp/",
    exampleSentence: "I will wash up after dinner tonight.",
    exampleTranslationJa: "今夜は夕食のあとで食器を洗います。",
    collocations: ["wash up after dinner", "help wash up", "wash up the plates"],
    mnemonic: "up が「すっかり終える」という感じを添える。英では食器洗い、米では手洗いを指す。",
    relatedWords: ["wash", "dish", "clean"],
  },
  {
    id: "watch",
    word: "watch",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["腕時計", "じっと見る、見物する"],
    pronunciation: "/wɑːtʃ/",
    exampleSentence: "He looked at his watch and stood up quickly.",
    exampleTranslationJa: "彼は腕時計を見て、すばやく立ち上がった。",
    collocations: ["watch a film", "look at your watch", "keep watch"],
    mnemonic: "動きを追い続けるのが watch。目に入るだけの see、意識して目を向ける look と区別する。",
    relatedWords: ["see", "look", "clock"],
  },
  {
    id: "we",
    word: "we",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["私たちは", "私たちが"],
    pronunciation: "/wiː/",
    exampleSentence: "We are planning a trip to the mountains.",
    exampleTranslationJa: "私たちは山への旅行を計画している。",
    collocations: ["we all", "here we are", "we should"],
    mnemonic: "話し手を含む複数を指す主格。目的格は us、所有格は our と、文中の役割で形が変わる。",
    relatedWords: ["us", "our", "they"],
  },
  {
    id: "wear",
    word: "wear",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["身につけている、着ている", "(衣類が)すり減る"],
    pronunciation: "/wer/",
    exampleSentence: "She likes to wear bright colours in summer.",
    exampleTranslationJa: "彼女は夏に明るい色を着るのが好きだ。",
    collocations: ["wear a hat", "wear glasses", "wear out"],
    mnemonic: "着ている状態を表す語。着る動作の put on とは違い、そのままの状態が続くことを示す。",
    relatedWords: ["put on", "dress", "clothes"],
  },
  {
    id: "weather",
    word: "weather",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["天気、気象"],
    pronunciation: "/ˈweðər/",
    exampleSentence: "The weather was warm and sunny all weekend.",
    exampleTranslationJa: "週末はずっと暖かく晴れた天気だった。",
    collocations: ["good weather", "the weather forecast", "in all weathers"],
    mnemonic: "天気は名詞の weather。接続詞の whether(〜かどうか)と発音が同じで、意味は全く違う。",
    relatedWords: ["whether", "rain", "climate"],
  },
  {
    id: "website",
    word: "website",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ウェブサイト、ホームページ"],
    pronunciation: "/ˈwebsaɪt/",
    exampleSentence: "The school website has a list of all the classes.",
    exampleTranslationJa: "学校のウェブサイトには全授業の一覧がある。",
    collocations: ["visit a website", "the official website", "a website address"],
    mnemonic: "web(網)+ site(場所)で、インターネット上のある1つの場所を指す語。複数形は websites となる。",
    relatedWords: ["web", "page", "internet"],
  },
  {
    id: "websites",
    word: "websites",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ウェブサイト(複数形)"],
    pronunciation: "/ˈwebsaɪts/",
    exampleSentence: "Many websites offer free lessons in English.",
    exampleTranslationJa: "多くのウェブサイトが無料の英語講座を提供している。",
    collocations: ["many websites", "visit websites", "popular websites"],
    mnemonic: "website の複数形。数えられる名詞なので、2つ以上を指すときは -s を付ける。",
    relatedWords: ["website", "page", "internet"],
  },
  {
    id: "trader",
    word: "trader",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["商人、トレーダー"],
    pronunciation: "/ˈtreɪdər/",
    exampleSentence: "A trader sold fruit and bread at the morning market.",
    exampleTranslationJa: "商人が朝市で果物とパンを売っていた。",
    collocations: ["a market trader", "a local trader", "a small trader"],
    mnemonic: "trade(商売する)+ -er。市場や取引所で物を売買する人を指し、株を売買する人にも使う。",
    relatedWords: ["trade", "merchant", "grower"],
  },
  {
    id: "week",
    word: "week",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["週、1週間"],
    pronunciation: "/wiːk/",
    exampleSentence: "We stayed at the seaside for a week in August.",
    exampleTranslationJa: "私たちは8月に1週間、海辺で過ごした。",
    collocations: ["last week", "a week ago", "once a week"],
    mnemonic: "7日間のまとまりを指す。weak(弱い)と発音が同じなので、つづりで見分ける。週末は weekend。",
    relatedWords: ["weekend", "day", "month"],
  },
  {
    id: "went",
    word: "went",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["行った(go の過去形)"],
    pronunciation: "/went/",
    exampleSentence: "She went to the library to study for the test.",
    exampleTranslationJa: "彼女は試験勉強のために図書館へ行った。",
    collocations: ["went home", "went out", "went abroad"],
    mnemonic: "go の過去形は went で、goed とは言わない。過去分詞は gone と、3つの形をそろえて覚える。",
    relatedWords: ["go", "gone", "came"],
  },
  {
    id: "were",
    word: "were",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜だった、〜にいた(be の過去形・複数)"],
    pronunciation: "/wɜːr/",
    exampleSentence: "They were very happy with the new house.",
    exampleTranslationJa: "彼らは新しい家にとても満足していた。",
    collocations: ["were born", "there were", "we were"],
    mnemonic: "be動詞の過去形で、you や複数の主語に使う。単数の I・he・she には was を使う。",
    relatedWords: ["was", "are", "been"],
  },
  {
    id: "west",
    word: "west",
    level: "A2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["西、西部", "西の、西側の"],
    pronunciation: "/west/",
    exampleSentence: "The sun sets in the west every evening.",
    exampleTranslationJa: "太陽は毎夕、西に沈む。",
    collocations: ["in the west", "the west coast", "west of the city"],
    mnemonic: "方角を表す4語のうちの1つ。形容詞では west coast のように名詞の前に置く。",
    relatedWords: ["east", "north", "south"],
  },
  {
    id: "what",
    word: "what",
    level: "A2",
    partOfSpeech: "代名詞・限定詞",
    meaningsJa: ["何、どんなもの", "なんという"],
    pronunciation: "/wʌt/",
    exampleSentence: "What did you buy at the shop this morning?",
    exampleTranslationJa: "今朝、店で何を買ったのですか。",
    collocations: ["what time", "what about", "what do you mean"],
    mnemonic: "ものや事柄を尋ねる疑問詞。名詞の前に置くと what time のように「どんな〜」の意味になる。",
    relatedWords: ["which", "who", "how"],
  },
  {
    id: "when",
    word: "when",
    level: "A2",
    partOfSpeech: "副詞・接続詞",
    meaningsJa: ["いつ", "〜するときに"],
    pronunciation: "/wen/",
    exampleSentence: "When does the next bus leave for the city?",
    exampleTranslationJa: "次の市行きのバスはいつ出ますか。",
    collocations: ["when I was young", "since when", "when it rains"],
    mnemonic: "時を尋ねる疑問副詞と、「〜のとき」を導く接続詞の両方の働きを1語で担う。関係副詞としても使える。",
    relatedWords: ["where", "while", "time"],
  },
  {
    id: "where",
    word: "where",
    level: "A2",
    partOfSpeech: "副詞・接続詞",
    meaningsJa: ["どこで、どこへ", "〜する場所に"],
    pronunciation: "/wer/",
    exampleSentence: "Where did you put the keys to the front door?",
    exampleTranslationJa: "玄関の鍵をどこに置きましたか。",
    collocations: ["where are you from", "where I live", "the place where"],
    mnemonic: "場所を尋ねる疑問副詞。the place where 〜 の形では「〜する場所」とつなぐ接続詞になる。",
    relatedWords: ["when", "here", "place"],
  },
  {
    id: "which",
    word: "which",
    level: "A2",
    partOfSpeech: "代名詞・限定詞",
    meaningsJa: ["どちら、どれ", "〜する(関係代名詞)"],
    pronunciation: "/wɪtʃ/",
    exampleSentence: "Which of these two bags is yours?",
    exampleTranslationJa: "この二つのうち、どちらのかばんがあなたのですか。",
    collocations: ["which one", "which of them", "the house which"],
    mnemonic: "限られた数の中から選ぶときに使う疑問詞。数の決まっていない what と役割を分ける。",
    relatedWords: ["what", "who", "that"],
  },
  {
    id: "white",
    word: "white",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["白い", "白、白色"],
    pronunciation: "/waɪt/",
    exampleSentence: "The walls of the new room are white.",
    exampleTranslationJa: "新しい部屋の壁は白い。",
    collocations: ["white hair", "a white shirt", "pure white"],
    mnemonic: "色の基本語。wine や winter と同じく、wh- のあとに i が来るつづりになる。",
    relatedWords: ["black", "pale", "colour"],
  },
  {
    id: "who",
    word: "who",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["だれ、だれが", "〜する人(関係代名詞)"],
    pronunciation: "/huː/",
    exampleSentence: "Who is the woman standing by the window?",
    exampleTranslationJa: "窓のそばに立っている女の人はだれですか。",
    collocations: ["who is it", "who else", "the man who"],
    mnemonic: "人を尋ねる疑問詞。wh- とつづるが発音は h だけの「フー」。所有格は whose で、物にも使える。",
    relatedWords: ["whose", "whom", "what"],
  },
  {
    id: "why",
    word: "why",
    level: "A2",
    partOfSpeech: "副詞",
    meaningsJa: ["なぜ、どうして"],
    pronunciation: "/waɪ/",
    exampleSentence: "Why did you leave the meeting so early?",
    exampleTranslationJa: "なぜそんなに早く会議を出たのですか。",
    collocations: ["why not", "the reason why", "why did you"],
    mnemonic: "理由を尋ねる疑問副詞。why not は「〜してはどう」という提案の言い方にもなる。",
    relatedWords: ["how", "reason", "because"],
  },
  {
    id: "wife",
    word: "wife",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["妻"],
    pronunciation: "/waɪf/",
    exampleSentence: "His wife works as a nurse at the hospital.",
    exampleTranslationJa: "彼の妻は病院で看護師として働いている。",
    collocations: ["his wife", "husband and wife", "wife and mother"],
    mnemonic: "複数形は wives と f が v に変わる。life → lives と同じ変化をする語。",
    relatedWords: ["husband", "married", "woman"],
  },
  {
    id: "window",
    word: "window",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["窓", "(コンピュータの)ウィンドウ"],
    pronunciation: "/ˈwɪndoʊ/",
    exampleSentence: "She opened the window to let in fresh air.",
    exampleTranslationJa: "彼女は新鮮な空気を入れるために窓を開けた。",
    collocations: ["open a window", "look out of the window", "a shop window"],
    mnemonic: "風を通す開口部を指す。店の飾り窓も、パソコン画面の中の枠も同じ window で表す。",
    relatedWords: ["glass", "door", "pane"],
  },
  {
    id: "wine",
    word: "wine",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ワイン、ぶどう酒"],
    pronunciation: "/waɪn/",
    exampleSentence: "They shared a bottle of red wine at dinner.",
    exampleTranslationJa: "彼らは夕食に赤ワインを一本分け合った。",
    collocations: ["red wine", "a glass of wine", "wine glasses"],
    mnemonic: "ぶどうから作る酒。液体なので数えられないが、種類やボトルを指すときは a wine とも言う。",
    relatedWords: ["vineyard", "glass", "drink"],
  },
  {
    id: "winter",
    word: "winter",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["冬"],
    pronunciation: "/ˈwɪntər/",
    exampleSentence: "The lake freezes over every winter.",
    exampleTranslationJa: "その湖は毎年、冬に凍る。",
    collocations: ["in winter", "a cold winter", "winter clothes"],
    mnemonic: "四季のうち最も寒い季節。wh- ではなく w- で始まり、発音は「ウィンター」。",
    relatedWords: ["summer", "snow", "cold"],
  },
  {
    id: "with",
    word: "with",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜と一緒に", "〜を使って", "〜のある"],
    pronunciation: "/wɪð/",
    exampleSentence: "I went to the market with my sister.",
    exampleTranslationJa: "私は妹と一緒に市場へ行った。",
    collocations: ["with me", "a cup with a lid", "with care"],
    mnemonic: "同伴・道具・付属を表す前置詞で、「〜のある」という説明にも使う。反対の意味は without になる。",
    relatedWords: ["without", "together", "and"],
  },
  {
    id: "without",
    word: "without",
    level: "A2",
    partOfSpeech: "前置詞",
    meaningsJa: ["〜なしで、〜がなければ"],
    pronunciation: "/wɪˈðaʊt/",
    exampleSentence: "He left the house without his umbrella.",
    exampleTranslationJa: "彼は傘を持たずに家を出た。",
    collocations: ["without a doubt", "go without", "without help"],
    mnemonic: "with + out で「〜がなくて」。without a doubt は「疑いなく」という決まり文句。",
    relatedWords: ["with", "lack", "except"],
  },
  {
    id: "woman",
    word: "woman",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["女性、女の人"],
    pronunciation: "/ˈwʊmən/",
    exampleSentence: "A young woman asked me for directions.",
    exampleTranslationJa: "若い女性が私に道をたずねた。",
    collocations: ["a young woman", "a woman doctor", "women and men"],
    mnemonic: "複数形は women で、発音が「ウィミン」に変わる。man → men と同じ不規則変化。",
    relatedWords: ["man", "girl", "wife"],
  },
  {
    id: "wonderful",
    word: "wonderful",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すばらしい、素敵な"],
    pronunciation: "/ˈwʌndərfl/",
    exampleSentence: "We had a wonderful time at the seaside.",
    exampleTranslationJa: "私たちは海辺ですばらしい時間を過ごした。",
    collocations: ["a wonderful time", "wonderful news", "feel wonderful"],
    mnemonic: "wonder(驚き)+ -ful。もとは「驚くほどすばらしい」という意味合いの語。",
    relatedWords: ["wonder", "great", "lovely"],
  },
  {
    id: "word",
    word: "word",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["単語、言葉", "(口にした)約束"],
    pronunciation: "/wɜːrd/",
    exampleSentence: "I learned ten new words in class today.",
    exampleTranslationJa: "今日の授業で新しい単語を10覚えた。",
    collocations: ["a new word", "in other words", "keep your word"],
    mnemonic: "「単語」と「約束」の両方を表す。keep your word は「約束を守る」という意味になる。",
    relatedWords: ["vocabulary", "phrase", "promise"],
  },
  {
    id: "work",
    word: "work",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["仕事", "働く", "(機械が)動く"],
    pronunciation: "/wɜːrk/",
    exampleSentence: "My father works in a bank in the city.",
    exampleTranslationJa: "父は市内の銀行で働いている。",
    collocations: ["go to work", "work hard", "hard work"],
    mnemonic: "名詞と動詞で形が変わらない。職場にいることは at work、失業中は out of work と言う。",
    relatedWords: ["job", "worker", "office"],
  },
  {
    id: "world",
    word: "world",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["世界", "世の中"],
    pronunciation: "/wɜːrld/",
    exampleSentence: "People all over the world watch this sport.",
    exampleTranslationJa: "世界中の人々がこのスポーツを観戦する。",
    collocations: ["around the world", "the whole world", "in the world"],
    mnemonic: "地球とそこに住む人々の全体を指す。all over the world で「世界中で」となる。",
    relatedWords: ["earth", "global", "country"],
  },
  {
    id: "would",
    word: "would",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["〜だろう", "(丁寧に)〜していただけますか", "(過去の習慣)よく〜した"],
    pronunciation: "/wʊd/",
    exampleSentence: "Would you like a cup of coffee?",
    exampleTranslationJa: "コーヒーを一杯いかがですか。",
    collocations: ["would like", "would you mind", "would rather"],
    mnemonic: "will の過去形だが、今のことを丁寧に言うときにも使う。would like で「〜がほしい」。",
    relatedWords: ["will", "should", "could"],
  },
  {
    id: "wrapping paper",
    word: "wrapping paper",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["包装紙"],
    pronunciation: "/ˈræpɪŋ ˌpeɪpər/",
    exampleSentence: "She covered the box with bright wrapping paper.",
    exampleTranslationJa: "彼女は箱を明るい色の包装紙で包んだ。",
    collocations: ["wrapping paper", "a roll of wrapping paper", "tear the wrapping paper"],
    mnemonic: "wrapping(包むための)+ paper(紙)。贈り物を包む薄い紙で、a roll of で数える。",
    relatedWords: ["wrap", "paper", "present"],
  },
  {
    id: "wring",
    word: "wring",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["(布などを)絞る、ひねる"],
    pronunciation: "/rɪŋ/",
    exampleSentence: "She had to wring the wet towel over the sink.",
    exampleTranslationJa: "彼女は流しの上で濡れたタオルを絞らなければならなかった。",
    collocations: ["wring a towel", "wring out the cloth", "wring your hands"],
    mnemonic: "w は読まず「リング」と発音する。wring out で「水気を絞り出す」という意味になる。",
    relatedWords: ["squeeze", "twist", "towel"],
  },
  {
    id: "write",
    word: "write",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["書く", "手紙を書く、執筆する"],
    pronunciation: "/raɪt/",
    exampleSentence: "Please write your name at the top of the page.",
    exampleTranslationJa: "ページの一番上に名前を書いてください。",
    collocations: ["write a letter", "write down", "write an email"],
    mnemonic: "w は読まず「ライト」と発音する。right と同音なのでつづりで見分け、過去形は wrote と不規則に変わる。",
    relatedWords: ["writing", "read", "pen"],
  },
  {
    id: "yacht",
    word: "yacht",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヨット"],
    pronunciation: "/jɑːt/",
    exampleSentence: "They sailed their yacht along the south coast.",
    exampleTranslationJa: "彼らはヨットで南の海岸沿いを航海した。",
    collocations: ["sail a yacht", "a luxury yacht", "a yacht club"],
    mnemonic: "ch を読まず「ヨット」と発音する。オランダ語から入った海事の語で、つづりと発音が大きく離れている。",
    relatedWords: ["sail", "boat", "ship"],
  },
  {
    id: "yam",
    word: "yam",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヤム、山いも"],
    pronunciation: "/jæm/",
    exampleSentence: "She roasted a yam and served it with butter.",
    exampleTranslationJa: "彼女はヤムを焼いてバターを添えた。",
    collocations: ["roast a yam", "peel a yam", "yam soup"],
    mnemonic: "熱帯原産のいもを指す。日本語の「山いも」にあたり、さつまいもは sweet potato という別の語。",
    relatedWords: ["potato", "sweet potato", "vegetable"],
  },
  {
    id: "year",
    word: "year",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["年、1年", "歳"],
    pronunciation: "/jɪr/",
    exampleSentence: "She has worked here for three years.",
    exampleTranslationJa: "彼女はここで3年間働いている。",
    collocations: ["last year", "a year ago", "all year round"],
    mnemonic: "1年という期間を表す。年齢を言うときは 〜 years old と複数形にする。",
    relatedWords: ["month", "day", "annual"],
  },
  {
    id: "yellow",
    word: "yellow",
    level: "A2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["黄色い", "黄色"],
    pronunciation: "/ˈjeloʊ/",
    exampleSentence: "The old car is bright yellow.",
    exampleTranslationJa: "その古い車は鮮やかな黄色だ。",
    collocations: ["bright yellow", "a yellow dress", "turn yellow"],
    mnemonic: "レモンや卵の黄身のような色を指す。yell(叫ぶ)とはつづりが似ているだけの別の語。",
    relatedWords: ["red", "orange", "colour"],
  },
  {
    id: "yes",
    word: "yes",
    level: "A2",
    partOfSpeech: "間投詞",
    meaningsJa: ["はい", "そうだ"],
    pronunciation: "/jes/",
    exampleSentence: "Yes, I would like to join the class.",
    exampleTranslationJa: "はい、そのクラスに参加したいです。",
    collocations: ["say yes", "yes please", "yes or no"],
    mnemonic: "肯定の返事を表す語。目上の人には yes, sir や yes, madam と添えることもある。",
    relatedWords: ["no", "sure", "okay"],
  },
  {
    id: "yesterday",
    word: "yesterday",
    level: "A2",
    partOfSpeech: "副詞・名詞",
    meaningsJa: ["昨日", "昨日は"],
    pronunciation: "/ˈjestərdeɪ/",
    exampleSentence: "Yesterday we walked along the river for an hour.",
    exampleTranslationJa: "昨日、私たちは1時間、川沿いを歩いた。",
    collocations: ["yesterday morning", "the day before yesterday", "only yesterday"],
    mnemonic: "yester-(昨〜)+ day という組み立て。today と tomorrow を合わせた3語で時の流れを作る。",
    relatedWords: ["today", "tomorrow", "last night"],
  },
  {
    id: "yoga",
    word: "yoga",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ヨガ"],
    pronunciation: "/ˈjoʊɡə/",
    exampleSentence: "She does yoga every morning before breakfast.",
    exampleTranslationJa: "彼女は毎朝、朝食の前にヨガをする。",
    collocations: ["do yoga", "a yoga class", "yoga mat"],
    mnemonic: "サンスクリット語から入った語で「結びつき」が原義。数えられない名詞なので a yoga とは言わない。",
    relatedWords: ["exercise", "stretch", "meditation"],
  },
  {
    id: "you",
    word: "you",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["あなたは", "あなたに、あなたを"],
    pronunciation: "/juː/",
    exampleSentence: "You can leave your bag by the door.",
    exampleTranslationJa: "かばんはドアのそばに置いておいてください。",
    collocations: ["you and I", "thank you", "see you"],
    mnemonic: "相手を指す代名詞。1人にも大勢にも使え、主格も目的格も同じ形なので位置で役割が決まる。",
    relatedWords: ["your", "yourself", "we"],
  },
  {
    id: "your",
    word: "your",
    level: "A2",
    partOfSpeech: "限定詞",
    meaningsJa: ["あなたの", "あなた方の"],
    pronunciation: "/jɔːr/",
    exampleSentence: "Please take off your shoes at the door.",
    exampleTranslationJa: "ドアのところで靴を脱いでください。",
    collocations: ["your name", "your own", "your help"],
    mnemonic: "you の所有格で、必ず名詞の前に置く。名詞を伴わず単独で使う形は yours になる。",
    relatedWords: ["you", "yours", "my"],
  },
  {
    id: "yourself",
    word: "yourself",
    level: "A2",
    partOfSpeech: "代名詞",
    meaningsJa: ["あなた自身", "自分で"],
    pronunciation: "/jɔːrˈself/",
    exampleSentence: "You should be proud of yourself for finishing the race.",
    exampleTranslationJa: "レースを完走したことを自分で誇りに思っていいよ。",
    collocations: ["by yourself", "enjoy yourself", "look after yourself"],
    mnemonic: "your + self で「自分自身」。by yourself は「1人で、独力で」という意味になる。",
    relatedWords: ["your", "myself", "self"],
  },
  {
    id: "zoo",
    word: "zoo",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["動物園"],
    pronunciation: "/zuː/",
    exampleSentence: "The children saw a baby elephant at the zoo.",
    exampleTranslationJa: "子どもたちは動物園で赤ちゃんゾウを見た。",
    collocations: ["go to the zoo", "a city zoo", "a zoo keeper"],
    mnemonic: "zoological garden(動物学の庭)を短くした語。to や too と同じ長い「ウー」の音で終わる。",
    relatedWords: ["animal", "keeper", "elephant"],
  },
]
