import type { VocabularyEntry } from '../types'

// 増補 第5弾。買い物・お金・手続き・服の素材。窓口や店で言えないと困る語を集めた。
export const plus05: VocabularyEntry[] = [
  {
    id: "warranty",
    word: "warranty",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["保証、保証書"],
    pronunciation: "/ˈwɔːrənti/",
    exampleSentence: "The laptop comes with a two-year warranty.",
    exampleTranslationJa: "そのノートパソコンには2年の保証がついている。",
    collocations: ["under warranty", "a two-year warranty", "the warranty expires"],
    mnemonic: "guarantee が広く「約束」全般、warranty は製品につく書面の保証。",
    relatedWords: ["guarantee", "repair", "refund"],
  },
  {
    id: "voucher",
    word: "voucher",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["引換券、商品券"],
    pronunciation: "/ˈvaʊtʃər/",
    exampleSentence: "She was given a voucher instead of a refund.",
    exampleTranslationJa: "彼女は返金の代わりに商品券を渡された。",
    collocations: ["a gift voucher", "redeem a voucher", "a meal voucher"],
    mnemonic: "vouch(保証する)+ -er。「これで受け取れる」と保証する紙。",
    relatedWords: ["coupon", "token", "refund"],
  },
  {
    id: "coupon",
    word: "coupon",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["クーポン、割引券"],
    pronunciation: "/ˈkuːpɑːn/",
    exampleSentence: "Cut out the coupon and bring it to the shop.",
    exampleTranslationJa: "そのクーポンを切り取って店にお持ちください。",
    collocations: ["a discount coupon", "use a coupon", "cut out a coupon"],
    mnemonic: "couper(切る)が語源。切り取って使うから coupon。",
    relatedWords: ["voucher", "discount", "offer"],
  },
  {
    id: "clearance",
    word: "clearance",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["在庫一掃、処分売り", "許可、認可", "すき間"],
    pronunciation: "/ˈklɪrəns/",
    exampleSentence: "Everything on this rack is on clearance.",
    exampleTranslationJa: "この棚のものはすべて処分価格だ。",
    collocations: ["a clearance sale", "security clearance", "on clearance"],
    wordFormation: "clear(片づける・通す)+ -ance。",
    mnemonic: "「片づける」から在庫一掃、「通す」から許可。どちらも clear が芯。",
    relatedWords: ["sale", "permission", "discount"],
  },
  {
    id: "checkout",
    word: "checkout",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["レジ、会計場所", "(ホテルの)チェックアウト時刻"],
    pronunciation: "/ˈtʃekaʊt/",
    exampleSentence: "There was a long queue at the checkout.",
    exampleTranslationJa: "レジには長い列ができていた。",
    collocations: ["at the checkout", "a self-service checkout", "checkout time"],
    mnemonic: "句動詞 check out(精算して出る)が名詞になった語。ネット通販の会計画面も checkout。",
    relatedWords: ["cashier", "till", "pay"],
  },
  {
    id: "cashier",
    word: "cashier",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["レジ係、会計係"],
    pronunciation: "/kæˈʃɪr/",
    exampleSentence: "The cashier asked if I wanted a bag.",
    exampleTranslationJa: "レジ係に袋がいるかと聞かれた。",
    collocations: ["ask the cashier", "a supermarket cashier"],
    mnemonic: "cash(現金)を扱う人。アクセントは後ろ /kæˈʃɪr/。",
    relatedWords: ["checkout", "till", "clerk"],
  },
  {
    id: "trolley",
    word: "trolley",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["買い物カート、台車(英)"],
    pronunciation: "/ˈtrɑːli/",
    exampleSentence: "He pushed the trolley down the frozen food aisle.",
    exampleTranslationJa: "彼は冷凍食品の通路にカートを押していった。",
    collocations: ["a shopping trolley", "push a trolley", "a luggage trolley"],
    mnemonic: "米では shopping cart。英では trolley。空港の荷物カートも trolley。",
    relatedWords: ["cart", "basket", "luggage"],
  },
  {
    id: "aisle",
    word: "aisle",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["通路(店の棚の間、飛行機・劇場の席の間)"],
    pronunciation: "/aɪl/",
    exampleSentence: "I would like an aisle seat, please.",
    exampleTranslationJa: "通路側の席をお願いします。",
    collocations: ["an aisle seat", "the frozen food aisle", "walk down the aisle"],
    mnemonic: "s は読まない /aɪl/。island と同じ音。walk down the aisle は「結婚する」。",
    relatedWords: ["corridor", "passage", "seat"],
  },
  {
    id: "inventory",
    word: "inventory",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["在庫、在庫目録", "棚卸し"],
    pronunciation: "/ˈɪnvəntɔːri/",
    exampleSentence: "The shop takes inventory at the end of each month.",
    exampleTranslationJa: "その店は毎月末に棚卸しをする。",
    collocations: ["take inventory", "inventory management", "reduce inventory"],
    mnemonic: "invent(見つけ出す)と同語根。「何があるか数え上げたもの」。",
    relatedWords: ["stock", "supply", "list"],
  },
  {
    id: "invoice",
    word: "invoice",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["請求書、送り状", "請求書を送る"],
    pronunciation: "/ˈɪnvɔɪs/",
    exampleSentence: "Please pay the invoice within 30 days.",
    exampleTranslationJa: "請求書は30日以内にお支払いください。",
    collocations: ["issue an invoice", "pay an invoice", "an unpaid invoice"],
    mnemonic: "bill が広く「請求」、invoice は取引先に出す正式な請求書。",
    relatedWords: ["bill", "payment", "receipt"],
  },
  {
    id: "overdraft",
    word: "overdraft",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["当座貸越、残高を超えた引き出し"],
    pronunciation: "/ˈoʊvərdræft/",
    exampleSentence: "The bank charged him for going into overdraft.",
    exampleTranslationJa: "銀行は残高不足での引き出しに手数料をかけた。",
    collocations: ["go into overdraft", "an overdraft facility", "overdraft charges"],
    wordFormation: "over-(超えて)+ draft(引き出す)。",
    mnemonic: "over(超えて)draw(引き出す)。口座残高を超えて引き出せる仕組み。",
    relatedWords: ["account", "debt", "bank"],
  },
  {
    id: "instalment",
    word: "instalment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["分割払いの1回分", "(連載の)1回分"],
    pronunciation: "/ɪnˈstɔːlmənt/",
    exampleSentence: "You can pay in twelve monthly instalments.",
    exampleTranslationJa: "12回の月払いにできます。",
    collocations: ["pay in instalments", "a monthly instalment", "the final instalment"],
    mnemonic: "米つづりは installment。連載小説の「第◯回」も instalment。",
    relatedWords: ["payment", "repayment", "monthly"],
  },
  {
    id: "repayment",
    word: "repayment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["返済、返済金"],
    pronunciation: "/rɪˈpeɪmənt/",
    exampleSentence: "The monthly repayment is higher than she expected.",
    exampleTranslationJa: "毎月の返済額は彼女の予想より高い。",
    collocations: ["monthly repayments", "loan repayment", "miss a repayment"],
    wordFormation: "re-(戻して)+ payment(支払い)。",
    mnemonic: "re(戻して)+ payment。借りた分を戻す支払い。",
    relatedWords: ["loan", "instalment", "debt"],
  },
  {
    id: "interest",
    word: "interest",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["利子、利息", "関心、興味", "利害、権益"],
    pronunciation: "/ˈɪntrəst/",
    exampleSentence: "The loan carries an interest rate of three per cent.",
    exampleTranslationJa: "そのローンの金利は3パーセントだ。",
    collocations: ["an interest rate", "earn interest", "a conflict of interest"],
    mnemonic: "「関わり」が芯。心が関わるのが興味、金が関わるのが利子、立場が関わるのが利害。",
    relatedWords: ["rate", "profit", "concern"],
  },
  {
    id: "savings",
    word: "savings",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["貯金、蓄え"],
    pronunciation: "/ˈseɪvɪŋz/",
    exampleSentence: "They spent their savings on a house.",
    exampleTranslationJa: "彼らは家に貯金を使った。",
    collocations: ["a savings account", "life savings", "dip into your savings"],
    mnemonic: "この意味では必ず複数形 savings。単数 saving は「節約」。",
    relatedWords: ["save", "account", "deposit"],
  },
  {
    id: "deduction",
    word: "deduction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["天引き、控除", "推論、演繹"],
    pronunciation: "/dɪˈdʌkʃn/",
    exampleSentence: "Tax deductions are shown on your payslip.",
    exampleTranslationJa: "税の控除は給与明細に示されている。",
    collocations: ["a tax deduction", "after deductions", "by deduction"],
    wordFormation: "de-(下へ)+ ducere(導く)。「引き下ろす」。",
    mnemonic: "「引く」が芯。給料から引くのが控除、事実から結論を引き出すのが推論。",
    relatedWords: ["deduct", "tax", "inference"],
  },
  {
    id: "exchange rate",
    word: "exchange rate",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["為替レート"],
    pronunciation: "/ɪksˈtʃeɪndʒ reɪt/",
    exampleSentence: "The exchange rate has moved against the yen.",
    exampleTranslationJa: "為替レートは円安に動いた。",
    collocations: ["the exchange rate", "a favourable exchange rate", "exchange rate fluctuations"],
    mnemonic: "exchange(交換)の rate(割合)。両替所の掲示板に出る数字。",
    relatedWords: ["currency", "rate", "foreign"],
  },
  {
    id: "banknote",
    word: "banknote",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["紙幣、お札"],
    pronunciation: "/ˈbæŋknoʊt/",
    exampleSentence: "He folded the banknote and put it in his pocket.",
    exampleTranslationJa: "彼は紙幣を折ってポケットに入れた。",
    collocations: ["a forged banknote", "a 20-pound banknote"],
    wordFormation: "bank(銀行)+ note(手形)。もとは銀行が出す支払い約束の紙。",
    mnemonic: "英では note、米では bill だけでも「お札」を指す。",
    relatedWords: ["note", "coin", "cash"],
  },
  {
    id: "change",
    word: "change",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["おつり", "小銭", "変化", "変える、変わる"],
    pronunciation: "/tʃeɪndʒ/",
    exampleSentence: "Keep the change.",
    exampleTranslationJa: "おつりは取っておいてください。",
    collocations: ["keep the change", "small change", "change your mind"],
    mnemonic: "「取り替え」が芯。払った金と品物の差を取り替えたものが「おつり」。",
    relatedWords: ["coin", "cash", "alter"],
  },
  {
    id: "debit",
    word: "debit",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["引き落とし、借方", "口座から引き落とす"],
    pronunciation: "/ˈdebɪt/",
    exampleSentence: "The fee will be debited from your account each month.",
    exampleTranslationJa: "その手数料は毎月あなたの口座から引き落とされます。",
    collocations: ["a debit card", "a direct debit", "debit an account"],
    mnemonic: "credit(入る)の反対で debit(出る)。デビットカードは即時引き落とし。",
    relatedWords: ["credit", "account", "withdraw"],
  },
  {
    id: "repay",
    word: "repay",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["返済する", "(恩に)報いる"],
    pronunciation: "/rɪˈpeɪ/",
    exampleSentence: "It will take ten years to repay the loan.",
    exampleTranslationJa: "そのローンを返すのに10年かかるだろう。",
    collocations: ["repay a loan", "repay a debt", "repay kindness"],
    wordFormation: "re-(戻して)+ pay(払う)。",
    mnemonic: "活用は repay-repaid-repaid。金だけでなく親切に報いるのも repay。",
    relatedWords: ["pay", "refund", "debt"],
  },
  {
    id: "spend",
    word: "spend",
    level: "A2",
    partOfSpeech: "動詞",
    meaningsJa: ["(お金を)使う", "(時間を)過ごす"],
    pronunciation: "/spend/",
    exampleSentence: "They spend too much on takeaway food.",
    exampleTranslationJa: "彼らは持ち帰りの食べ物に使いすぎている。",
    collocations: ["spend money on", "spend time doing", "spend a fortune"],
    mnemonic: "活用は spend-spent-spent。金にも時間にも使える。spend + 時間 + doing の形。",
    relatedWords: ["pay", "waste", "save"],
  },
  {
    id: "bankrupt",
    word: "bankrupt",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["破産した", "破産させる"],
    pronunciation: "/ˈbæŋkrʌpt/",
    exampleSentence: "The airline went bankrupt last winter.",
    exampleTranslationJa: "その航空会社は昨冬に倒産した。",
    collocations: ["go bankrupt", "declare bankrupt", "morally bankrupt"],
    mnemonic: "banca rotta(壊れた台)。払えなくなった両替商の台を壊した習慣が語源。",
    relatedWords: ["bankruptcy", "debt", "insolvent"],
  },
  {
    id: "bankruptcy",
    word: "bankruptcy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["破産、倒産"],
    pronunciation: "/ˈbæŋkrʌptsi/",
    exampleSentence: "The company filed for bankruptcy in March.",
    exampleTranslationJa: "その会社は3月に破産を申請した。",
    collocations: ["file for bankruptcy", "declare bankruptcy", "face bankruptcy"],
    mnemonic: "file for bankruptcy(破産を申請する)が定型。bankrupt の名詞形。",
    relatedWords: ["bankrupt", "debt", "creditor"],
  },
  {
    id: "insolvent",
    word: "insolvent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["支払い不能の、債務超過の"],
    pronunciation: "/ɪnˈsɑːlvənt/",
    exampleSentence: "The firm was declared insolvent by the court.",
    exampleTranslationJa: "その会社は裁判所に支払い不能と宣告された。",
    collocations: ["become insolvent", "an insolvent company"],
    wordFormation: "in-(否定)+ solvent(支払える)。solve(解く)と同語根。",
    mnemonic: "solvent は「支払える」。in- がついて「支払えない」。",
    relatedWords: ["bankrupt", "debt", "liquidation"],
  },
  {
    id: "creditor",
    word: "creditor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["債権者、貸した側"],
    pronunciation: "/ˈkredɪtər/",
    exampleSentence: "The creditors met to discuss the company's debts.",
    exampleTranslationJa: "債権者たちがその会社の負債について話し合うため集まった。",
    collocations: ["repay creditors", "a major creditor", "creditors' meeting"],
    wordFormation: "credit(信用して貸す)+ -or(人)。",
    mnemonic: "貸したほうが creditor、借りたほうが debtor。",
    relatedWords: ["debtor", "loan", "debt"],
  },
  {
    id: "debtor",
    word: "debtor",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["債務者、借りた側"],
    pronunciation: "/ˈdetər/",
    exampleSentence: "The debtor agreed to a new repayment plan.",
    exampleTranslationJa: "債務者は新しい返済計画に同意した。",
    collocations: ["a major debtor", "debtor nations", "chase a debtor"],
    mnemonic: "debt と同じく b は読まない /ˈdetər/。借りた側。",
    relatedWords: ["creditor", "debt", "owe"],
  },
  {
    id: "collateral",
    word: "collateral",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["担保", "付随的な"],
    pronunciation: "/kəˈlætərəl/",
    exampleSentence: "He used his house as collateral for the loan.",
    exampleTranslationJa: "彼は家をそのローンの担保にした。",
    collocations: ["use as collateral", "collateral damage", "put up collateral"],
    wordFormation: "col-(共に)+ lateral(側の)。「本体の横に添えるもの」。",
    mnemonic: "本体の横(lateral)に添えるもの。借金の横に置く担保、戦闘の横で出る被害。",
    relatedWords: ["security", "loan", "guarantee"],
  },
  {
    id: "lease",
    word: "lease",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["賃貸契約、借地権", "賃貸する、賃借する"],
    pronunciation: "/liːs/",
    exampleSentence: "They signed a three-year lease on the office.",
    exampleTranslationJa: "彼らはそのオフィスの3年契約を結んだ。",
    collocations: ["sign a lease", "renew a lease", "a new lease of life"],
    mnemonic: "a new lease of life は「新たな活力」。契約が延びるイメージから。",
    relatedWords: ["rent", "tenant", "contract"],
  },
  {
    id: "receptionist",
    word: "receptionist",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["受付係"],
    pronunciation: "/rɪˈsepʃənɪst/",
    exampleSentence: "The receptionist asked me to sign in.",
    exampleTranslationJa: "受付係に記帳するよう言われた。",
    collocations: ["a hotel receptionist", "ask the receptionist"],
    wordFormation: "reception(受付)+ -ist(人)。",
    mnemonic: "reception(受付)にいる人。ホテルでも会社でも同じ語。",
    relatedWords: ["reception", "clerk", "desk"],
  },
  {
    id: "form",
    word: "form",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["用紙、申込書", "形、形式", "形づくる"],
    pronunciation: "/fɔːrm/",
    exampleSentence: "Please fill in this form in block capitals.",
    exampleTranslationJa: "この用紙にブロック体で記入してください。",
    collocations: ["fill in a form", "an application form", "in the form of"],
    mnemonic: "「決まった形」が芯。決まった形に書き込む紙が「用紙」。",
    relatedWords: ["shape", "document", "application"],
  },
  {
    id: "passport",
    word: "passport",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パスポート、旅券", "(比喩)〜への切り札"],
    pronunciation: "/ˈpæspɔːrt/",
    exampleSentence: "My passport expires next year.",
    exampleTranslationJa: "私のパスポートは来年切れる。",
    collocations: ["renew your passport", "a passport photo", "a passport to success"],
    wordFormation: "pass(通る)+ port(港)。「港を通るための書き付け」。",
    mnemonic: "pass(通る)+ port(港)。港を通す紙。「成功への切符」の比喩にも。",
    relatedWords: ["visa", "travel", "identity"],
  },
  {
    id: "linen",
    word: "linen",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["麻(リネン)", "シーツ・タオル類"],
    pronunciation: "/ˈlɪnɪn/",
    exampleSentence: "He wore a white linen shirt in the heat.",
    exampleTranslationJa: "暑さの中、彼は白い麻のシャツを着ていた。",
    collocations: ["a linen shirt", "bed linen", "table linen"],
    mnemonic: "亜麻(flax)から作る布。シーツやタオル一式も bed linen と呼ぶ。",
    relatedWords: ["cotton", "fabric", "sheet"],
  },
  {
    id: "denim",
    word: "denim",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["デニム(生地)"],
    pronunciation: "/ˈdenɪm/",
    exampleSentence: "She wore a denim jacket over her dress.",
    exampleTranslationJa: "彼女はワンピースの上にデニムのジャケットを着ていた。",
    collocations: ["a denim jacket", "blue denim", "denim jeans"],
    mnemonic: "フランスのニーム(Nîmes)産の布 de Nîmes がなまった語。",
    relatedWords: ["jeans", "cotton", "fabric"],
  },
  {
    id: "nylon",
    word: "nylon",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ナイロン"],
    pronunciation: "/ˈnaɪlɑːn/",
    exampleSentence: "The rope is made of nylon and does not rot.",
    exampleTranslationJa: "そのロープはナイロン製で腐らない。",
    collocations: ["a nylon rope", "nylon stockings", "made of nylon"],
    mnemonic: "世界初の合成繊維。軽くて丈夫で水に強い。",
    relatedWords: ["polyester", "synthetic", "fibre"],
  },
  {
    id: "polyester",
    word: "polyester",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ポリエステル"],
    pronunciation: "/ˌpɑːliˈestər/",
    exampleSentence: "The shirt is 60 per cent cotton and 40 per cent polyester.",
    exampleTranslationJa: "そのシャツは綿60パーセント、ポリエステル40パーセントだ。",
    collocations: ["polyester fabric", "a cotton-polyester blend"],
    wordFormation: "poly-(多くの)+ ester(エステル)。",
    mnemonic: "しわになりにくく乾きやすい合成繊維。綿と混ぜて使うことが多い。",
    relatedWords: ["nylon", "cotton", "synthetic"],
  },
  {
    id: "velvet",
    word: "velvet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ビロード、ベルベット"],
    pronunciation: "/ˈvelvɪt/",
    exampleSentence: "The box was lined with dark red velvet.",
    exampleTranslationJa: "その箱の内側は暗い赤のビロードで張られていた。",
    collocations: ["red velvet", "a velvet curtain", "as soft as velvet"],
    mnemonic: "短い毛が密に立った、なめらかで厚い布。高級品の裏張りの定番。",
    relatedWords: ["silk", "fabric", "smooth"],
  },
  {
    id: "sew",
    word: "sew",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["縫う"],
    pronunciation: "/soʊ/",
    exampleSentence: "She sewed a button back onto his coat.",
    exampleTranslationJa: "彼女は彼のコートにボタンを縫いつけ直した。",
    collocations: ["sew on a button", "sew up a hole", "sew by hand"],
    mnemonic: "発音は so と同じ /soʊ/。活用は sew-sewed-sewn。",
    relatedWords: ["stitch", "needle", "thread"],
  },
  {
    id: "knit",
    word: "knit",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["編む", "(骨が)くっつく"],
    pronunciation: "/nɪt/",
    exampleSentence: "She knits a scarf every winter.",
    exampleTranslationJa: "彼女は毎冬マフラーを編む。",
    collocations: ["knit a jumper", "a close-knit family", "knit your brows"],
    mnemonic: "k は読まない /nɪt/。a close-knit family は「結束の固い家族」。",
    relatedWords: ["sew", "wool", "weave"],
  },
  {
    id: "mend",
    word: "mend",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["直す、繕う", "(関係を)修復する"],
    pronunciation: "/mend/",
    exampleSentence: "He mended the torn pocket with a needle and thread.",
    exampleTranslationJa: "彼は破れたポケットを針と糸で繕った。",
    collocations: ["mend a hole", "mend fences", "on the mend"],
    mnemonic: "on the mend は「快方に向かって」。mend fences は「仲直りする」。",
    relatedWords: ["repair", "fix", "patch"],
  },
  {
    id: "baggy",
    word: "baggy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["だぶだぶの"],
    pronunciation: "/ˈbæɡi/",
    exampleSentence: "He turned up in baggy trousers and old boots.",
    exampleTranslationJa: "彼はだぶだぶのズボンと古いブーツで現れた。",
    collocations: ["baggy trousers", "a baggy jumper", "go baggy"],
    wordFormation: "bag(袋)+ -y。「袋のような」。",
    mnemonic: "bag(袋)のようにたるんだ形。loose よりくだけた言い方。",
    relatedWords: ["loose", "tight", "fit"],
  },
  {
    id: "fitted",
    word: "fitted",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["体にぴったりした", "作りつけの"],
    pronunciation: "/ˈfɪtɪd/",
    exampleSentence: "She wore a fitted jacket over a plain shirt.",
    exampleTranslationJa: "彼女は無地のシャツの上に体に沿ったジャケットを着ていた。",
    collocations: ["a fitted shirt", "a fitted kitchen", "fitted wardrobes"],
    mnemonic: "服なら「体に沿った」、家具なら「壁に合わせて作りつけた」。",
    relatedWords: ["tight", "loose", "tailored"],
  },
  {
    id: "shabby",
    word: "shabby",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["みすぼらしい、着古した", "(扱いが)ひどい"],
    pronunciation: "/ˈʃæbi/",
    exampleSentence: "He was wearing a shabby old coat.",
    exampleTranslationJa: "彼はみすぼらしい古いコートを着ていた。",
    collocations: ["a shabby coat", "shabby treatment", "look shabby"],
    mnemonic: "not too shabby は「悪くない」というほめ言葉。逆説的な使い方。",
    relatedWords: ["worn", "tattered", "scruffy"],
  },
  {
    id: "trendy",
    word: "trendy",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["流行の、おしゃれな"],
    pronunciation: "/ˈtrendi/",
    exampleSentence: "They opened a trendy café near the station.",
    exampleTranslationJa: "彼らは駅の近しくにおしゃれなカフェを開いた。",
    collocations: ["a trendy bar", "trendy clothes", "look trendy"],
    wordFormation: "trend(流行)+ -y。",
    mnemonic: "trend(流行)に乗っている。fashionable よりくだけた語。",
    relatedWords: ["fashionable", "stylish", "trend"],
  },
  {
    id: "commuter",
    word: "commuter",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["通勤者"],
    pronunciation: "/kəˈmjuːtər/",
    exampleSentence: "Commuters packed the platform at eight in the morning.",
    exampleTranslationJa: "朝8時、通勤客がホームを埋めつくした。",
    collocations: ["a commuter train", "commuter traffic", "daily commuters"],
    wordFormation: "commute(通勤する)+ -er(人)。",
    mnemonic: "commute は元「(定期券で)まとめて払う」。そこから毎日の通勤へ。",
    relatedWords: ["commute", "train", "rush hour"],
  },
  {
    id: "timetable",
    word: "timetable",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["時刻表", "時間割"],
    pronunciation: "/ˈtaɪmteɪbl/",
    exampleSentence: "Check the timetable before you leave.",
    exampleTranslationJa: "出る前に時刻表を確認しなさい。",
    collocations: ["a train timetable", "a school timetable", "behind timetable"],
    wordFormation: "time(時間)+ table(表)。",
    mnemonic: "米では schedule。電車も授業も同じ timetable。",
    relatedWords: ["schedule", "train", "class"],
  },
  {
    id: "luggage",
    word: "luggage",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["手荷物、旅行かばん(全体)"],
    pronunciation: "/ˈlʌɡɪdʒ/",
    exampleSentence: "How much luggage are you taking?",
    exampleTranslationJa: "荷物はどのくらい持っていきますか。",
    collocations: ["hand luggage", "a piece of luggage", "collect your luggage"],
    mnemonic: "数えられない名詞。「かばん1つ」は a piece of luggage。",
    relatedWords: ["baggage", "suitcase", "bag"],
  },
  {
    id: "baggage",
    word: "baggage",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["手荷物(米)", "(心の)重荷"],
    pronunciation: "/ˈbæɡɪdʒ/",
    exampleSentence: "Baggage claim is on the lower floor.",
    exampleTranslationJa: "手荷物受取所は下の階です。",
    collocations: ["baggage claim", "excess baggage", "emotional baggage"],
    mnemonic: "emotional baggage は「引きずっている心の重荷」。luggage の米語版。",
    relatedWords: ["luggage", "suitcase", "airport"],
  },
  {
    id: "porter",
    word: "porter",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["荷物運び、ポーター", "(建物の)管理人"],
    pronunciation: "/ˈpɔːrtər/",
    exampleSentence: "A porter carried our bags to the room.",
    exampleTranslationJa: "ポーターが荷物を部屋まで運んでくれた。",
    collocations: ["call a porter", "a hotel porter", "a hospital porter"],
    mnemonic: "portare(運ぶ)が語根。transport(運ぶ)と親戚。",
    relatedWords: ["carry", "luggage", "hotel"],
  },
  {
    id: "boarding",
    word: "boarding",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["搭乗、乗船", "(学校の)寄宿"],
    pronunciation: "/ˈbɔːrdɪŋ/",
    exampleSentence: "Boarding begins thirty minutes before departure.",
    exampleTranslationJa: "搭乗は出発の30分前に始まります。",
    collocations: ["a boarding pass", "boarding gate", "a boarding school"],
    mnemonic: "board(乗り込む)+ -ing。搭乗券は a boarding pass。",
    relatedWords: ["board", "gate", "flight"],
  },
  {
    id: "duty-free",
    word: "duty-free",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["免税の", "免税品店"],
    pronunciation: "/ˌduːti ˈfriː/",
    exampleSentence: "She bought perfume in the duty-free shop.",
    exampleTranslationJa: "彼女は免税店で香水を買った。",
    collocations: ["duty-free shopping", "a duty-free allowance"],
    wordFormation: "duty(関税)+ free(免れた)。",
    mnemonic: "duty には「関税」の意味がある。それが free(かからない)。",
    relatedWords: ["tax", "customs", "airport"],
  },
  {
    id: "layover",
    word: "layover",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["乗り継ぎの待ち時間、途中降機"],
    pronunciation: "/ˈleɪoʊvər/",
    exampleSentence: "We had a six-hour layover in Dubai.",
    exampleTranslationJa: "私たちはドバイで6時間の乗り継ぎ待ちがあった。",
    collocations: ["a long layover", "a layover in", "an overnight layover"],
    mnemonic: "lay over(途中でとどまる)が名詞に。英では stopover。",
    relatedWords: ["stopover", "transit", "flight"],
  },
  {
    id: "itinerary",
    word: "itinerary",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["旅程、旅行日程表"],
    pronunciation: "/aɪˈtɪnəreri/",
    exampleSentence: "The travel agent emailed us the full itinerary.",
    exampleTranslationJa: "旅行代理店が全旅程表をメールで送ってきた。",
    collocations: ["a detailed itinerary", "change the itinerary", "a travel itinerary"],
    mnemonic: "iter(旅路)が語根。どこにいつ行くかを並べた表。",
    relatedWords: ["schedule", "route", "travel"],
  },
  {
    id: "sightseeing",
    word: "sightseeing",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["観光、名所めぐり"],
    pronunciation: "/ˈsaɪtsiːɪŋ/",
    exampleSentence: "We spent the first day sightseeing in the old town.",
    exampleTranslationJa: "私たちは初日を旧市街の観光に使った。",
    collocations: ["go sightseeing", "a sightseeing tour", "a sightseeing bus"],
    wordFormation: "sight(名所)+ seeing(見ること)。",
    mnemonic: "go sightseeing の形で使う。名所(sights)を見て回ること。",
    relatedWords: ["tourism", "tour", "visit"],
  },
  {
    id: "souvenir",
    word: "souvenir",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["みやげ、記念品"],
    pronunciation: "/ˌsuːvəˈnɪr/",
    exampleSentence: "He bought a small souvenir for his sister.",
    exampleTranslationJa: "彼は妹に小さなみやげを買った。",
    collocations: ["a souvenir shop", "buy a souvenir", "as a souvenir"],
    mnemonic: "フランス語で「思い出す」。思い出のためのしるし。",
    relatedWords: ["memento", "gift", "memory"],
  },
  {
    id: "guidebook",
    word: "guidebook",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ガイドブック、旅行案内書"],
    pronunciation: "/ˈɡaɪdbʊk/",
    exampleSentence: "The guidebook says the museum closes on Mondays.",
    exampleTranslationJa: "ガイドブックによれば博物館は月曜休みだ。",
    collocations: ["consult a guidebook", "a travel guidebook"],
    wordFormation: "guide(案内)+ book(本)。",
    mnemonic: "案内(guide)の本。人の案内人も guide なので文脈で見分ける。",
    relatedWords: ["guide", "map", "tourist"],
  },
  {
    id: "hostel",
    word: "hostel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["簡易宿泊所、ユースホステル"],
    pronunciation: "/ˈhɑːstl/",
    exampleSentence: "We stayed in a hostel to save money.",
    exampleTranslationJa: "私たちは節約のため簡易宿に泊まった。",
    collocations: ["a youth hostel", "stay in a hostel", "a hostel bed"],
    mnemonic: "hotel と一字違いだが、相部屋で安い宿。hospital と同語源。",
    relatedWords: ["hotel", "accommodation", "dormitory"],
  },
  {
    id: "excursion",
    word: "excursion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小旅行、遠足"],
    pronunciation: "/ɪkˈskɜːrʒn/",
    exampleSentence: "The hotel offers a day excursion to the islands.",
    exampleTranslationJa: "そのホテルは島への日帰り旅行を用意している。",
    collocations: ["a day excursion", "go on an excursion", "a boat excursion"],
    wordFormation: "ex-(外へ)+ currere(走る)。「外へ走り出ること」。",
    mnemonic: "ex(外へ)+ curr(走る)。本筋から少し外へ出る短い旅。",
    relatedWords: ["trip", "outing", "tour"],
  },
  {
    id: "detour",
    word: "detour",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["回り道、迂回", "迂回する"],
    pronunciation: "/ˈdiːtʊr/",
    exampleSentence: "We made a detour to avoid the roadworks.",
    exampleTranslationJa: "私たちは道路工事を避けて回り道をした。",
    collocations: ["make a detour", "take a detour", "a long detour"],
    wordFormation: "de-(離れて)+ tour(回る)。",
    mnemonic: "本来の道から離れて(de)回る(tour)。工事や渋滞のときの語。",
    relatedWords: ["diversion", "route", "bypass"],
  },
  {
    id: "shortcut",
    word: "shortcut",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["近道", "手っ取り早いやり方"],
    pronunciation: "/ˈʃɔːrtkʌt/",
    exampleSentence: "He took a shortcut through the park.",
    exampleTranslationJa: "彼は公園を抜ける近道をした。",
    collocations: ["take a shortcut", "a keyboard shortcut", "no shortcut to success"],
    wordFormation: "short(短い)+ cut(切る)。「短く切る道」。",
    mnemonic: "道の近道もキーボードのショートカットも同じ語。",
    relatedWords: ["route", "path", "quick"],
  },
  {
    id: "roundabout",
    word: "roundabout",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["環状交差点(英)", "遠回りの、遠まわしの"],
    pronunciation: "/ˈraʊndəbaʊt/",
    exampleSentence: "Take the second exit at the roundabout.",
    exampleTranslationJa: "その環状交差点で2番目の出口を出てください。",
    collocations: ["at the roundabout", "in a roundabout way", "the second exit"],
    mnemonic: "in a roundabout way は「遠回しに」。ぐるっと回る形から。",
    relatedWords: ["junction", "circle", "indirect"],
  },
  {
    id: "intersection",
    word: "intersection",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["交差点(米)", "交わり"],
    pronunciation: "/ˌɪntərˈsekʃn/",
    exampleSentence: "Turn left at the next intersection.",
    exampleTranslationJa: "次の交差点を左に曲がってください。",
    collocations: ["at the intersection", "a busy intersection", "the intersection of"],
    wordFormation: "inter-(間で)+ sect(切る)。「互いに切り合う所」。",
    mnemonic: "inter(互いに)+ sect(切る)。道が切り合う所。英では junction。",
    relatedWords: ["junction", "crossroads", "corner"],
  },
  {
    id: "crossroads",
    word: "crossroads",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["十字路", "(人生の)岐路"],
    pronunciation: "/ˈkrɔːsroʊdz/",
    exampleSentence: "The company is at a crossroads.",
    exampleTranslationJa: "その会社は岐路に立っている。",
    collocations: ["at a crossroads", "reach a crossroads"],
    mnemonic: "単数でも s がつく。at a crossroads は「重大な選択の時」。",
    relatedWords: ["intersection", "junction", "choice"],
  },
  {
    id: "pavement",
    word: "pavement",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["歩道(英)", "舗装面(米)"],
    pronunciation: "/ˈpeɪvmənt/",
    exampleSentence: "Children were drawing on the pavement with chalk.",
    exampleTranslationJa: "子どもたちがチョークで歩道に絵を描いていた。",
    collocations: ["on the pavement", "a wet pavement", "pavement café"],
    wordFormation: "pave(舗装する)+ -ment。",
    mnemonic: "英では歩道、米では車道を含む「舗装面」。国で意味がずれる語。",
    relatedWords: ["sidewalk", "path", "road"],
  },
  {
    id: "sidewalk",
    word: "sidewalk",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["歩道(米)"],
    pronunciation: "/ˈsaɪdwɔːk/",
    exampleSentence: "They waited on the sidewalk for a taxi.",
    exampleTranslationJa: "彼らは歩道でタクシーを待った。",
    collocations: ["on the sidewalk", "a crowded sidewalk"],
    wordFormation: "side(わき)+ walk(歩く所)。",
    mnemonic: "道のわき(side)を歩く(walk)所。英では pavement。",
    relatedWords: ["pavement", "path", "street"],
  },
  {
    id: "kerb",
    word: "kerb",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["縁石(えんせき)、歩道の縁"],
    pronunciation: "/kɜːrb/",
    exampleSentence: "She tripped over the kerb and dropped her bag.",
    exampleTranslationJa: "彼女は縁石につまずいてかばんを落とした。",
    collocations: ["step off the kerb", "park at the kerb", "the kerb side"],
    mnemonic: "米つづりは curb。同音の curb には「抑制する」の意味もある。",
    relatedWords: ["curb", "pavement", "edge"],
  },
  {
    id: "motorway",
    word: "motorway",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["高速道路(英)"],
    pronunciation: "/ˈmoʊtərweɪ/",
    exampleSentence: "There was an accident on the motorway.",
    exampleTranslationJa: "高速道路で事故があった。",
    collocations: ["on the motorway", "a motorway junction", "leave the motorway"],
    wordFormation: "motor(自動車)+ way(道)。",
    mnemonic: "米では freeway / highway、英では motorway。",
    relatedWords: ["highway", "freeway", "road"],
  },
  {
    id: "ferry",
    word: "ferry",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["フェリー、渡し船", "船で運ぶ"],
    pronunciation: "/ˈferi/",
    exampleSentence: "The ferry crosses the strait four times a day.",
    exampleTranslationJa: "そのフェリーは1日4回、海峡を渡る。",
    collocations: ["take the ferry", "a car ferry", "a ferry terminal"],
    mnemonic: "行ったり来たりして人や車を運ぶ船。動詞で「送り迎えする」意味にも。",
    relatedWords: ["boat", "ship", "cross"],
  },
  {
    id: "dock",
    word: "dock",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["埠頭、ドック", "(船が)接岸する", "(法廷の)被告席"],
    pronunciation: "/dɑːk/",
    exampleSentence: "The ship docked just after midnight.",
    exampleTranslationJa: "その船は真夜中すぎに接岸した。",
    collocations: ["dock at a port", "a dry dock", "in the dock"],
    mnemonic: "in the dock は「被告席にいる」＝「裁かれている」。",
    relatedWords: ["harbour", "port", "pier"],
  },
  {
    id: "pier",
    word: "pier",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["桟橋、埠頭"],
    pronunciation: "/pɪr/",
    exampleSentence: "They walked to the end of the pier to watch the sunset.",
    exampleTranslationJa: "彼らは夕日を見ようと桟橋の先まで歩いた。",
    collocations: ["at the end of the pier", "a wooden pier", "the fishing pier"],
    mnemonic: "peer(のぞく)と同音 /pɪr/。海に突き出た細長い台。",
    relatedWords: ["dock", "harbour", "jetty"],
  },
  {
    id: "wharf",
    word: "wharf",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["波止場、荷揚げ場"],
    pronunciation: "/wɔːrf/",
    exampleSentence: "Crates were stacked along the wharf.",
    exampleTranslationJa: "木箱が波止場に沿って積み上げられていた。",
    collocations: ["along the wharf", "unload at the wharf"],
    mnemonic: "複数形は wharves(または wharfs)。荷の積み下ろしをする岸。",
    relatedWords: ["dock", "pier", "harbour"],
  },
  {
    id: "diesel",
    word: "diesel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["軽油、ディーゼル(燃料・エンジン)"],
    pronunciation: "/ˈdiːzl/",
    exampleSentence: "The van runs on diesel, not petrol.",
    exampleTranslationJa: "そのバンはガソリンではなく軽油で走る。",
    collocations: ["a diesel engine", "run on diesel", "diesel fumes"],
    mnemonic: "発明者の名前がそのまま燃料の名に。ガソリンは英 petrol / 米 gas。",
    relatedWords: ["petrol", "fuel", "engine"],
  },
  {
    id: "brake",
    word: "brake",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ブレーキ", "ブレーキをかける"],
    pronunciation: "/breɪk/",
    exampleSentence: "He braked hard to avoid the dog.",
    exampleTranslationJa: "彼は犬を避けようと急ブレーキをかけた。",
    collocations: ["put on the brakes", "the handbrake", "brake suddenly"],
    mnemonic: "break(壊す)と同音。put the brakes on ... で「〜に歯止めをかける」。",
    relatedWords: ["stop", "accelerate", "car"],
  },
  {
    id: "clutch",
    word: "clutch",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["クラッチ", "ぎゅっとつかむ"],
    pronunciation: "/klʌtʃ/",
    exampleSentence: "She clutched her bag tightly on the crowded train.",
    exampleTranslationJa: "彼女は混んだ電車でかばんをしっかり抱えていた。",
    collocations: ["clutch at straws", "press the clutch", "clutch your bag"],
    mnemonic: "clutch at straws は「わらにもすがる」。強くつかむのが芯。",
    relatedWords: ["grip", "grasp", "gear"],
  },
  {
    id: "steering",
    word: "steering",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ハンドル操作、かじ取り"],
    pronunciation: "/ˈstɪrɪŋ/",
    exampleSentence: "He gripped the steering wheel with both hands.",
    exampleTranslationJa: "彼は両手でハンドルを握った。",
    collocations: ["a steering wheel", "power steering", "a steering committee"],
    mnemonic: "車の「ハンドル」は英語で steering wheel。handle とは言わない。",
    relatedWords: ["steer", "wheel", "drive"],
  },
  {
    id: "windscreen",
    word: "windscreen",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["フロントガラス(英)"],
    pronunciation: "/ˈwɪndskriːn/",
    exampleSentence: "A stone cracked the windscreen on the motorway.",
    exampleTranslationJa: "高速道路で石がフロントガラスにひびを入れた。",
    collocations: ["a windscreen wiper", "crack the windscreen"],
    wordFormation: "wind(風)+ screen(仕切り)。",
    mnemonic: "風(wind)をよける screen。米では windshield。",
    relatedWords: ["windshield", "glass", "wiper"],
  },
  {
    id: "bonnet",
    word: "bonnet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ボンネット(英)", "(あごひも付きの)帽子"],
    pronunciation: "/ˈbɑːnɪt/",
    exampleSentence: "He lifted the bonnet to check the oil.",
    exampleTranslationJa: "彼はオイルを見ようとボンネットを開けた。",
    collocations: ["under the bonnet", "lift the bonnet"],
    mnemonic: "米では hood。under the bonnet は「内部の仕組み」の比喩にも。",
    relatedWords: ["hood", "engine", "car"],
  },
  {
    id: "dashboard",
    word: "dashboard",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(車の)ダッシュボード", "(画面の)管理画面"],
    pronunciation: "/ˈdæʃbɔːrd/",
    exampleSentence: "A warning light came on the dashboard.",
    exampleTranslationJa: "ダッシュボードに警告灯がついた。",
    collocations: ["on the dashboard", "a dashboard warning light", "an admin dashboard"],
    mnemonic: "もとは馬車で泥がはねる(dash)のを防ぐ板。今は計器板や管理画面。",
    relatedWords: ["panel", "car", "display"],
  },
  {
    id: "puncture",
    word: "puncture",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["パンク、小さな穴", "穴をあける"],
    pronunciation: "/ˈpʌŋktʃər/",
    exampleSentence: "We got a puncture ten miles from home.",
    exampleTranslationJa: "家から10マイルの所でパンクした。",
    collocations: ["get a puncture", "a puncture repair kit", "puncture a tyre"],
    mnemonic: "point(先)・punctual(時間ぴったり)と同語根。「刺して穴をあける」。",
    relatedWords: ["tyre", "hole", "flat"],
  },
  {
    id: "tow",
    word: "tow",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["けん引する、レッカー移動する"],
    pronunciation: "/toʊ/",
    exampleSentence: "The van towed the broken car to a garage.",
    exampleTranslationJa: "そのバンは故障車を修理工場までけん引した。",
    collocations: ["tow a car", "a tow truck", "get towed away"],
    mnemonic: "つま先 toe と同音 /toʊ/。違法駐車は get towed away(レッカー移動される)。",
    relatedWords: ["pull", "drag", "truck"],
  },
  {
    id: "stroll",
    word: "stroll",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ぶらぶら歩く", "散歩"],
    pronunciation: "/stroʊl/",
    exampleSentence: "They strolled along the river after dinner.",
    exampleTranslationJa: "彼らは夕食後、川沿いをぶらぶら歩いた。",
    collocations: ["go for a stroll", "stroll along", "a leisurely stroll"],
    mnemonic: "目的地を急がない、のんびりした歩き。walk よりゆったり。",
    relatedWords: ["walk", "wander", "amble"],
  },
  {
    id: "stride",
    word: "stride",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["大股で歩く", "大股の一歩、進歩"],
    pronunciation: "/straɪd/",
    exampleSentence: "He strode into the room without knocking.",
    exampleTranslationJa: "彼はノックもせず大股で部屋に入ってきた。",
    collocations: ["make great strides", "take it in your stride", "stride across"],
    mnemonic: "活用は stride-strode-stridden。make great strides で「大きく進歩する」。",
    relatedWords: ["step", "walk", "progress"],
  },
  {
    id: "roam",
    word: "roam",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["あてもなく歩き回る、放浪する"],
    pronunciation: "/roʊm/",
    exampleSentence: "Wild horses roam freely across the plain.",
    exampleTranslationJa: "野生の馬が平原を自由に歩き回っている。",
    collocations: ["roam freely", "roam the streets", "roaming charges"],
    mnemonic: "携帯電話の「ローミング」も同じ語。決まった場所を離れて動き回ること。",
    relatedWords: ["wander", "ramble", "stray"],
  },
  {
    id: "ramble",
    word: "ramble",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["のんびり歩き回る", "とりとめなく話す"],
    pronunciation: "/ˈræmbl/",
    exampleSentence: "He rambled on for twenty minutes without making a point.",
    exampleTranslationJa: "彼は要点もなく20分もだらだら話し続けた。",
    collocations: ["ramble on", "go for a ramble", "a rambling speech"],
    mnemonic: "足がさまようのも話がさまようのも ramble。ramble on は「だらだら話す」。",
    relatedWords: ["wander", "roam", "digress"],
  },
  {
    id: "hike",
    word: "hike",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["ハイキング、山歩き", "(値段の)引き上げ"],
    pronunciation: "/haɪk/",
    exampleSentence: "We went on a long hike through the hills.",
    exampleTranslationJa: "私たちは丘を越える長いハイキングに出かけた。",
    collocations: ["go for a hike", "a price hike", "hike up a hill"],
    mnemonic: "「ぐいと上げる」意味もあり、a price hike は「値上げ」。",
    relatedWords: ["walk", "trek", "climb"],
  },
  {
    id: "trek",
    word: "trek",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["長く骨の折れる旅、トレッキング"],
    pronunciation: "/trek/",
    exampleSentence: "It was a two-day trek to the base camp.",
    exampleTranslationJa: "ベースキャンプまでは2日がかりの行程だった。",
    collocations: ["a long trek", "trek through the jungle", "a trek to"],
    mnemonic: "hike より長く苦しい歩き。もとは南アフリカで牛車の旅を指した語。",
    relatedWords: ["hike", "journey", "march"],
  },
  {
    id: "stagger",
    word: "stagger",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["よろめく、ふらつく", "(時間を)ずらす", "ひどく驚かせる"],
    pronunciation: "/ˈstæɡər/",
    exampleSentence: "He staggered under the weight of the box.",
    exampleTranslationJa: "彼は箱の重さによろめいた。",
    collocations: ["stagger to your feet", "stagger the start times", "a staggering figure"],
    mnemonic: "「ふらつく」から、時間をずらす(重ならないよう互い違いにする)意味も出た。",
    relatedWords: ["stumble", "sway", "shock"],
  },
  {
    id: "tiptoe",
    word: "tiptoe",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["つま先立ちで歩く", "つま先立ち"],
    pronunciation: "/ˈtɪptoʊ/",
    exampleSentence: "She tiptoed past the sleeping baby.",
    exampleTranslationJa: "彼女は眠っている赤ん坊の横をつま先立ちで通り過ぎた。",
    collocations: ["on tiptoe", "tiptoe past", "tiptoe around an issue"],
    wordFormation: "tip(先)+ toe(つま先)。",
    mnemonic: "tiptoe around an issue は「問題に触れないよう気を遣う」。",
    relatedWords: ["creep", "sneak", "quiet"],
  },
  {
    id: "sprint",
    word: "sprint",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["全力疾走する", "短距離走"],
    pronunciation: "/sprɪnt/",
    exampleSentence: "He sprinted for the last hundred metres.",
    exampleTranslationJa: "彼は最後の100メートルを全力で走った。",
    collocations: ["a final sprint", "sprint for the bus", "the 100-metre sprint"],
    mnemonic: "短い距離を全力で。長く走るのは jog / run。",
    relatedWords: ["dash", "run", "race"],
  },
  {
    id: "jog",
    word: "jog",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ゆっくり走る、ジョギングする", "軽くつつく"],
    pronunciation: "/dʒɑːɡ/",
    exampleSentence: "She jogs around the park every morning.",
    exampleTranslationJa: "彼女は毎朝、公園を走っている。",
    collocations: ["go for a jog", "jog around the park", "jog your memory"],
    mnemonic: "jog someone's memory は「記憶を呼び起こす」。軽くつつく感じから。",
    relatedWords: ["run", "sprint", "exercise"],
  },
  {
    id: "trot",
    word: "trot",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(馬が)速足で行く", "小走りする"],
    pronunciation: "/trɑːt/",
    exampleSentence: "The pony trotted around the field.",
    exampleTranslationJa: "その子馬は野原を速足で回った。",
    collocations: ["trot along", "at a trot", "on the trot"],
    mnemonic: "馬の歩調は walk < trot < canter < gallop の順に速くなる。",
    relatedWords: ["gallop", "run", "horse"],
  },
  {
    id: "gallop",
    word: "gallop",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["(馬が)全速力で駆ける", "疾走"],
    pronunciation: "/ˈɡæləp/",
    exampleSentence: "The horse galloped across the open field.",
    exampleTranslationJa: "その馬は開けた野原を全速力で駆けた。",
    collocations: ["at a gallop", "gallop away", "galloping inflation"],
    mnemonic: "馬の最速の走り。galloping inflation は「暴走するインフレ」。",
    relatedWords: ["trot", "run", "horse"],
  },
  {
    id: "hop",
    word: "hop",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["片足で跳ぶ、ぴょんと跳ぶ", "(乗り物に)ひょいと乗る"],
    pronunciation: "/hɑːp/",
    exampleSentence: "The bird hopped from branch to branch.",
    exampleTranslationJa: "その鳥は枝から枝へぴょんぴょん移った。",
    collocations: ["hop on a bus", "hop over", "a short hop"],
    mnemonic: "jump より小さく軽い跳躍。Hop in! で「(車に)乗って！」。",
    relatedWords: ["jump", "leap", "skip"],
  },
  {
    id: "glare",
    word: "glare",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["にらみつける", "まぶしい光、ぎらつき"],
    pronunciation: "/ɡler/",
    exampleSentence: "She glared at him across the table.",
    exampleTranslationJa: "彼女はテーブル越しに彼をにらみつけた。",
    collocations: ["glare at someone", "the glare of the sun", "the glare of publicity"],
    mnemonic: "光が「ぎらつく」から、目つきが「ぎらつく」＝にらむ。",
    relatedWords: ["stare", "scowl", "dazzle"],
  },
  {
    id: "squint",
    word: "squint",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["目を細めて見る"],
    pronunciation: "/skwɪnt/",
    exampleSentence: "He squinted at the small print on the label.",
    exampleTranslationJa: "彼はラベルの小さな字を目を細めて見た。",
    collocations: ["squint at", "squint into the sun", "squint in the light"],
    mnemonic: "まぶしいときや細かい字を見るときの目つき。",
    relatedWords: ["peer", "blink", "stare"],
  },
  {
    id: "blink",
    word: "blink",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["まばたきする", "(明かりが)点滅する"],
    pronunciation: "/blɪŋk/",
    exampleSentence: "He blinked several times in the bright light.",
    exampleTranslationJa: "彼は明るい光の中で何度もまばたきした。",
    collocations: ["blink your eyes", "in the blink of an eye", "a blinking light"],
    mnemonic: "in the blink of an eye は「まばたきの間に」＝「あっという間に」。",
    relatedWords: ["wink", "flash", "eyelid"],
  },
  {
    id: "wink",
    word: "wink",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ウインクする", "ウインク"],
    pronunciation: "/wɪŋk/",
    exampleSentence: "He winked at her to show he was joking.",
    exampleTranslationJa: "彼は冗談だと示すため彼女にウインクした。",
    collocations: ["wink at someone", "a knowing wink", "not sleep a wink"],
    mnemonic: "両目が blink、片目が wink。not sleep a wink は「一睡もしない」。",
    relatedWords: ["blink", "signal", "eye"],
  },
  {
    id: "peek",
    word: "peek",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["こっそりのぞく", "ちらっと見ること"],
    pronunciation: "/piːk/",
    exampleSentence: "She peeked through the curtains at the street.",
    exampleTranslationJa: "彼女はカーテンのすき間から通りをのぞいた。",
    collocations: ["take a peek", "peek through", "a sneak peek"],
    mnemonic: "peak(頂上)・pique と同音。a sneak peek は「先行公開のちら見せ」。",
    relatedWords: ["glance", "peep", "glimpse"],
  },
  {
    id: "mutter",
    word: "mutter",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["ぶつぶつ言う、小声で不平を言う"],
    pronunciation: "/ˈmʌtər/",
    exampleSentence: "He muttered something about the price and walked out.",
    exampleTranslationJa: "彼は値段について何かぶつぶつ言って出ていった。",
    collocations: ["mutter under your breath", "mutter something", "mutter darkly"],
    mnemonic: "不満をこめて低く言う。ただ小さい声なら whisper。",
    relatedWords: ["mumble", "murmur", "grumble"],
  },
  {
    id: "mumble",
    word: "mumble",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["もごもご言う、口ごもる"],
    pronunciation: "/ˈmʌmbl/",
    exampleSentence: "Stop mumbling and speak clearly.",
    exampleTranslationJa: "もごもご言わずにはっきり話しなさい。",
    collocations: ["mumble an apology", "mumble something", "stop mumbling"],
    mnemonic: "口を開けずに言うので聞き取れない。mutter は不満、mumble は不明瞭さが芯。",
    relatedWords: ["mutter", "murmur", "slur"],
  },
  {
    id: "murmur",
    word: "murmur",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["つぶやく、ささやく", "ざわめき、小さな音"],
    pronunciation: "/ˈmɜːrmər/",
    exampleSentence: "She murmured a few words and closed her eyes.",
    exampleTranslationJa: "彼女はひとことふたことつぶやいて目を閉じた。",
    collocations: ["a murmur of approval", "murmur softly", "the murmur of the stream"],
    mnemonic: "水や人の声が低く続くやわらかい音。mutter より穏やか。",
    relatedWords: ["whisper", "mutter", "hum"],
  },
  {
    id: "shriek",
    word: "shriek",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["金切り声をあげる", "悲鳴"],
    pronunciation: "/ʃriːk/",
    exampleSentence: "She shrieked when the light suddenly went out.",
    exampleTranslationJa: "明かりが突然消えて彼女は金切り声をあげた。",
    collocations: ["shriek with laughter", "a shriek of terror", "let out a shriek"],
    mnemonic: "scream より高く鋭い。喜びでも恐怖でも出る。",
    relatedWords: ["scream", "yell", "screech"],
  },
  {
    id: "groan",
    word: "groan",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["うめく、うんざりした声を出す", "うめき声"],
    pronunciation: "/ɡroʊn/",
    exampleSentence: "The class groaned when he mentioned homework.",
    exampleTranslationJa: "彼が宿題の話をすると教室からうめき声が上がった。",
    collocations: ["groan with pain", "let out a groan", "groan inwardly"],
    mnemonic: "grown(育った)と同音。痛みにも「またか」といううんざりにも使う。",
    relatedWords: ["moan", "sigh", "complain"],
  },
  {
    id: "moan",
    word: "moan",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["うめく", "ぐちをこぼす"],
    pronunciation: "/moʊn/",
    exampleSentence: "He moaned about the weather all week.",
    exampleTranslationJa: "彼は一週間ずっと天気の文句を言っていた。",
    collocations: ["moan about", "a low moan", "stop moaning"],
    mnemonic: "groan が短い一声、moan は長く続く声。「ぐちる」意味は英でよく使う。",
    relatedWords: ["groan", "complain", "grumble"],
  },
  {
    id: "chuckle",
    word: "chuckle",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["くすくす笑う", "含み笑い"],
    pronunciation: "/ˈtʃʌkl/",
    exampleSentence: "He chuckled quietly at his own joke.",
    exampleTranslationJa: "彼は自分の冗談に静かにくすりと笑った。",
    collocations: ["chuckle to yourself", "a quiet chuckle", "chuckle at"],
    mnemonic: "のどの奥で低く笑う、大人の笑い。giggle は高くて子どもっぽい。",
    relatedWords: ["giggle", "laugh", "grin"],
  },
  {
    id: "giggle",
    word: "giggle",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["くすくす笑う(高い声で)", "くすくす笑い"],
    pronunciation: "/ˈɡɪɡl/",
    exampleSentence: "The children giggled behind their hands.",
    exampleTranslationJa: "子どもたちは手で口をおおってくすくす笑った。",
    collocations: ["giggle nervously", "get the giggles", "a fit of giggles"],
    mnemonic: "get the giggles は「笑いが止まらなくなる」。高くて抑えきれない笑い。",
    relatedWords: ["chuckle", "laugh", "titter"],
  },
  {
    id: "smirk",
    word: "smirk",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["にやにや笑う", "したり顔の笑み"],
    pronunciation: "/smɜːrk/",
    exampleSentence: "He smirked when he heard she had failed.",
    exampleTranslationJa: "彼女が失敗したと聞いて彼はにやりとした。",
    collocations: ["a self-satisfied smirk", "wipe that smirk off", "smirk at"],
    mnemonic: "感じの悪い笑み。得意げか、人を見下している。smile とは別物。",
    relatedWords: ["grin", "sneer", "smile"],
  },
  {
    id: "frown",
    word: "frown",
    level: "B1",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["まゆをひそめる", "しかめ面"],
    pronunciation: "/fraʊn/",
    exampleSentence: "She frowned at the strange noise.",
    exampleTranslationJa: "彼女は妙な音にまゆをひそめた。",
    collocations: ["frown at", "frown upon", "a puzzled frown"],
    mnemonic: "frown upon ... は「〜をよしとしない」。まゆの寄せ方が不賛成のしるし。",
    relatedWords: ["scowl", "grimace", "smile"],
  },
  {
    id: "scowl",
    word: "scowl",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["険しい顔をする、にらみつける"],
    pronunciation: "/skaʊl/",
    exampleSentence: "The guard scowled but let us through.",
    exampleTranslationJa: "警備員は険しい顔をしたが、通してくれた。",
    collocations: ["scowl at someone", "a deep scowl", "scowl darkly"],
    mnemonic: "frown より怒りが強い。owl と韻を踏む /skaʊl/。",
    relatedWords: ["frown", "glare", "grimace"],
  },
  {
    id: "sob",
    word: "sob",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["すすり泣く", "むせび泣き"],
    pronunciation: "/sɑːb/",
    exampleSentence: "She sobbed quietly into her pillow.",
    exampleTranslationJa: "彼女はまくらに顔をうずめて静かにすすり泣いた。",
    collocations: ["sob quietly", "burst into sobs", "a sob story"],
    mnemonic: "息を詰まらせながら泣く。a sob story は「同情を引く作り話」。",
    relatedWords: ["weep", "cry", "tears"],
  },
  {
    id: "weep",
    word: "weep",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(静かに)涙を流す、泣く"],
    pronunciation: "/wiːp/",
    exampleSentence: "Grown men weep at the end of that film.",
    exampleTranslationJa: "大の大人がその映画の結末で涙を流す。",
    collocations: ["weep for joy", "weep bitterly", "weep openly"],
    mnemonic: "活用は weep-wept-wept。cry よりかたく、文章向きの語。",
    relatedWords: ["cry", "sob", "tears"],
  },
  {
    id: "snatch",
    word: "snatch",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["ひったくる、さっと取る", "(短い)切れはし"],
    pronunciation: "/snætʃ/",
    exampleSentence: "Someone snatched her bag on the escalator.",
    exampleTranslationJa: "エスカレーターで誰かが彼女のかばんをひったくった。",
    collocations: ["snatch a bag", "snatch some sleep", "snatches of conversation"],
    mnemonic: "素早く乱暴に取る。snatch some sleep は「わずかな睡眠をとる」。",
    relatedWords: ["grab", "seize", "steal"],
  },
  {
    id: "fling",
    word: "fling",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["勢いよく投げる、放り出す", "短い恋"],
    pronunciation: "/flɪŋ/",
    exampleSentence: "Do not fling your coat onto the chair like that.",
    exampleTranslationJa: "そんなふうに上着をいすに放り投げないで。",
    collocations: ["fling open", "fling yourself into", "a brief fling"],
    mnemonic: "活用は fling-flung-flung。感情まかせに投げる感じ。",
    relatedWords: ["throw", "hurl", "toss"],
  },
  {
    id: "hurl",
    word: "hurl",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["力いっぱい投げつける", "(悪口を)浴びせる"],
    pronunciation: "/hɜːrl/",
    exampleSentence: "Protesters hurled stones at the fence.",
    exampleTranslationJa: "抗議者たちがフェンスに石を投げつけた。",
    collocations: ["hurl a stone", "hurl abuse at", "hurl yourself at"],
    mnemonic: "throw の中で一番激しい。hurl abuse で「罵声を浴びせる」。",
    relatedWords: ["throw", "fling", "toss"],
  },
  {
    id: "shove",
    word: "shove",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["乱暴に押す、押しのける", "ひと押し"],
    pronunciation: "/ʃʌv/",
    exampleSentence: "He shoved the door open with his shoulder.",
    exampleTranslationJa: "彼は肩でドアを押し開けた。",
    collocations: ["shove someone aside", "give it a shove", "push and shove"],
    mnemonic: "push より荒っぽい。love と韻を踏む /ʃʌv/。",
    relatedWords: ["push", "thrust", "nudge"],
  },
]
