import type { VocabularyEntry } from '../types'

// 増補 第30弾。7,500語 → 8,000語の増補。曜日・月と、家まわりの具体名詞。
export const plus30: VocabularyEntry[] = [
  {
    id: "january",
    word: "January",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["1月"],
    pronunciation: "/ˈdʒænjueri/",
    exampleSentence: "The new term starts in January.",
    exampleTranslationJa: "新学期は1月に始まる。",
    collocations: ["in January", "early January", "last January"],
    mnemonic: "ローマ神話の入口の神ヤヌス(Janus)から。前と後ろに顔を持ち、年の境目を見張る月。",
    relatedWords: ["February", "month", "winter"],
  },
  {
    id: "february",
    word: "February",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["2月"],
    pronunciation: "/ˈfebruəri/",
    exampleSentence: "February is the shortest month of the year.",
    exampleTranslationJa: "2月は一年でいちばん短い月だ。",
    collocations: ["in February", "late February", "February weather"],
    mnemonic: "ローマの清めの祭り Februa から。最初の r を落として読みがちなので注意。",
    relatedWords: ["January", "March", "month"],
  },
  {
    id: "april",
    word: "April",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["4月"],
    pronunciation: "/ˈeɪprəl/",
    exampleSentence: "The cherry trees bloom in April.",
    exampleTranslationJa: "桜は4月に咲く。",
    collocations: ["in April", "early April", "April showers"],
    mnemonic: "ラテン語 aperire(開く)が語源とされる。つぼみが開く月。",
    relatedWords: ["March", "May", "spring"],
  },
  {
    id: "june",
    word: "June",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["6月"],
    pronunciation: "/dʒuːn/",
    exampleSentence: "We were married in June.",
    exampleTranslationJa: "私たちは6月に結婚した。",
    collocations: ["in June", "mid June", "June wedding"],
    mnemonic: "女神ユノ(Juno)から。結婚の守り神なので June bride の言い方がある。",
    relatedWords: ["July", "May", "summer"],
  },
  {
    id: "july",
    word: "July",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["7月"],
    pronunciation: "/dʒuˈlaɪ/",
    exampleSentence: "The festival is held every July.",
    exampleTranslationJa: "その祭りは毎年7月に開かれる。",
    collocations: ["in July", "early July", "the fourth of July"],
    mnemonic: "ユリウス・カエサル(Julius)の月。後ろにアクセントが来る。",
    relatedWords: ["June", "August", "summer"],
  },
  {
    id: "august",
    word: "August",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["8月"],
    pronunciation: "/ˈɔːɡəst/",
    exampleSentence: "We usually take a holiday in August.",
    exampleTranslationJa: "うちはたいてい8月に休みを取る。",
    collocations: ["in August", "late August", "August heat"],
    mnemonic: "初代皇帝アウグストゥス(Augustus)の月。形容詞の august(荘厳な)は後ろにアクセント。",
    relatedWords: ["July", "September", "summer"],
  },
  {
    id: "september",
    word: "September",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["9月"],
    pronunciation: "/sepˈtembər/",
    exampleSentence: "School begins again in September.",
    exampleTranslationJa: "学校は9月にまた始まる。",
    collocations: ["in September", "early September", "September term"],
    mnemonic: "ラテン語 septem(7)。昔は3月始まりだったので7番目の月だった。",
    relatedWords: ["October", "autumn", "month"],
  },
  {
    id: "october",
    word: "October",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["10月"],
    pronunciation: "/ɑːkˈtoʊbər/",
    exampleSentence: "The leaves turn red in October.",
    exampleTranslationJa: "葉は10月に赤くなる。",
    collocations: ["in October", "mid October", "October sky"],
    mnemonic: "ラテン語 octo(8)。octopus(8本足)と同じ語根。",
    relatedWords: ["September", "November", "autumn"],
  },
  {
    id: "november",
    word: "November",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["11月"],
    pronunciation: "/noʊˈvembər/",
    exampleSentence: "It gets dark early in November.",
    exampleTranslationJa: "11月は暗くなるのが早い。",
    collocations: ["in November", "late November", "November rain"],
    mnemonic: "ラテン語 novem(9)。nine と同じ流れ。",
    relatedWords: ["October", "December", "autumn"],
  },
  {
    id: "december",
    word: "December",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["12月"],
    pronunciation: "/dɪˈsembər/",
    exampleSentence: "The shops are busy in December.",
    exampleTranslationJa: "12月は店が忙しい。",
    collocations: ["in December", "early December", "December holidays"],
    mnemonic: "ラテン語 decem(10)。decimal(十進法)と同じ語根。",
    relatedWords: ["November", "January", "winter"],
  },
  {
    id: "monday",
    word: "Monday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["月曜日"],
    pronunciation: "/ˈmʌndeɪ/",
    exampleSentence: "The meeting is on Monday morning.",
    exampleTranslationJa: "その会議は月曜の朝だ。",
    collocations: ["on Monday", "every Monday", "Monday morning"],
    mnemonic: "Moon(月)の日。日本語の「月曜」とそのまま重なる。",
    relatedWords: ["Tuesday", "weekday", "week"],
  },
  {
    id: "tuesday",
    word: "Tuesday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["火曜日"],
    pronunciation: "/ˈtuːzdeɪ/",
    exampleSentence: "I have a class every Tuesday.",
    exampleTranslationJa: "毎週火曜日に授業がある。",
    collocations: ["on Tuesday", "every Tuesday", "last Tuesday"],
    mnemonic: "北欧の軍神ティール(Tiw)の日。軍神＝火星＝火曜とつながる。",
    relatedWords: ["Monday", "Wednesday", "weekday"],
  },
  {
    id: "wednesday",
    word: "Wednesday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["水曜日"],
    pronunciation: "/ˈwenzdeɪ/",
    exampleSentence: "The shop closes early on Wednesday.",
    exampleTranslationJa: "その店は水曜は早く閉まる。",
    collocations: ["on Wednesday", "every Wednesday", "Wednesday afternoon"],
    mnemonic: "主神オーディン(Woden)の日。つづりの d は読まず「ウェンズデイ」。",
    relatedWords: ["Tuesday", "Thursday", "weekday"],
  },
  {
    id: "thursday",
    word: "Thursday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["木曜日"],
    pronunciation: "/ˈθɜːrzdeɪ/",
    exampleSentence: "We play football on Thursday evenings.",
    exampleTranslationJa: "木曜の夕方にサッカーをする。",
    collocations: ["on Thursday", "every Thursday", "Thursday night"],
    mnemonic: "雷神トール(Thor)の日。Thor's day がつまった形。",
    relatedWords: ["Wednesday", "Friday", "weekday"],
  },
  {
    id: "friday",
    word: "Friday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["金曜日"],
    pronunciation: "/ˈfraɪdeɪ/",
    exampleSentence: "Let us meet on Friday after work.",
    exampleTranslationJa: "金曜の仕事のあとに会おう。",
    collocations: ["on Friday", "every Friday", "Friday night"],
    mnemonic: "女神フリッグ(Frigg)の日。愛の女神＝金星＝金曜とつながる。",
    relatedWords: ["Thursday", "Saturday", "weekend"],
  },
  {
    id: "saturday",
    word: "Saturday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["土曜日"],
    pronunciation: "/ˈsætərdeɪ/",
    exampleSentence: "The market is open on Saturday.",
    exampleTranslationJa: "市場は土曜日に開いている。",
    collocations: ["on Saturday", "every Saturday", "Saturday morning"],
    mnemonic: "農耕神サトゥルヌス(Saturn)の日。土星＝土曜とそのまま重なる。",
    relatedWords: ["Friday", "Sunday", "weekend"],
  },
  {
    id: "sunday",
    word: "Sunday",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["日曜日"],
    pronunciation: "/ˈsʌndeɪ/",
    exampleSentence: "We have a big lunch on Sunday.",
    exampleTranslationJa: "日曜日にはしっかり昼食をとる。",
    collocations: ["on Sunday", "every Sunday", "Sunday roast"],
    mnemonic: "Sun(太陽)の日。日本語の「日曜」とそのまま重なる。",
    relatedWords: ["Saturday", "Monday", "weekend"],
  },
  {
    id: "air",
    word: "air",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["空気、大気", "(部屋を)換気する", "(考えを)公にする"],
    pronunciation: "/er/",
    exampleSentence: "Open the window and let some fresh air in.",
    exampleTranslationJa: "窓を開けて新鮮な空気を入れて。",
    collocations: ["fresh air", "in the air", "air quality"],
    mnemonic: "ギリシャ語 aēr。目に見えず全体を満たすもの。air a room は部屋に空気を通す＝換気する。",
    relatedWords: ["atmosphere", "breeze", "oxygen"],
  },
  {
    id: "allotment",
    word: "allotment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["市民農園、貸し菜園(英)", "割り当て分"],
    pronunciation: "/əˈlɑːtmənt/",
    exampleSentence: "He grows vegetables on his allotment every weekend.",
    exampleTranslationJa: "彼は毎週末、自分の貸し菜園で野菜を育てている。",
    collocations: ["an allotment garden", "rent an allotment", "allotment holder"],
    mnemonic: "allot(割り当てる)の名詞形。市が区画を割り当てて貸す小さな畑。",
    relatedWords: ["garden", "plot", "vegetable"],
  },
  {
    id: "amber",
    word: "amber",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["琥珀(こはく)", "琥珀色の", "(信号の)黄色"],
    pronunciation: "/ˈæmbər/",
    exampleSentence: "The traffic light turned amber before it went red.",
    exampleTranslationJa: "信号は赤になる前に黄色に変わった。",
    collocations: ["amber light", "a piece of amber", "amber warning"],
    mnemonic: "樹液が固まった宝石。英国の信号の黄は yellow ではなく amber と言う。",
    relatedWords: ["resin", "gold", "traffic light"],
  },
  {
    id: "apricot",
    word: "apricot",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["アンズ、アプリコット"],
    pronunciation: "/ˈeɪprɪkɑːt/",
    exampleSentence: "She spread apricot jam on her toast.",
    exampleTranslationJa: "彼女はトーストにアンズのジャムを塗った。",
    collocations: ["apricot jam", "dried apricots", "apricot tree"],
    mnemonic: "peach より小ぶりでオレンジがかった実。乾かした dried apricots が一般的。",
    relatedWords: ["peach", "plum", "fruit"],
  },
  {
    id: "ashtray",
    word: "ashtray",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["灰皿"],
    pronunciation: "/ˈæʃtreɪ/",
    exampleSentence: "There was an old ashtray on the table.",
    exampleTranslationJa: "テーブルの上に古い灰皿があった。",
    collocations: ["an ashtray on the table", "empty the ashtray", "a full ashtray"],
    mnemonic: "ash(灰)+ tray(受け皿)。そのまま灰を受ける皿。",
    relatedWords: ["ash", "tray", "cigarette"],
  },
  {
    id: "awning",
    word: "awning",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["日よけ、雨よけの張り出し"],
    pronunciation: "/ˈɔːnɪŋ/",
    exampleSentence: "We sat under the awning to escape the sun.",
    exampleTranslationJa: "日差しを避けようと張り出しの下に座った。",
    collocations: ["under the awning", "a striped awning", "roll out the awning"],
    mnemonic: "店先や窓の上から布を張り出したもの。umbrella が持ち運ぶ日よけなら、こちらは据え付け。",
    relatedWords: ["canopy", "shade", "shelter"],
  },
  {
    id: "backpacker",
    word: "backpacker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["バックパッカー、リュック旅行者"],
    pronunciation: "/ˈbækpækər/",
    exampleSentence: "The hostel is popular with young backpackers.",
    exampleTranslationJa: "その宿は若いバックパッカーに人気だ。",
    collocations: ["a young backpacker", "backpacker hostel", "backpackers travel"],
    mnemonic: "backpack(背負い袋)+ -er。荷を背負って安く長く旅する人。",
    relatedWords: ["hostel", "traveller", "rucksack"],
  },
  {
    id: "backyard",
    word: "backyard",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["裏庭"],
    pronunciation: "/ˌbækˈjɑːrd/",
    exampleSentence: "The children were playing in the backyard.",
    exampleTranslationJa: "子どもたちは裏庭で遊んでいた。",
    collocations: ["in the backyard", "a small backyard", "backyard barbecue"],
    mnemonic: "back(後ろ)+ yard(庭)。not in my backyard は「自分の裏庭では困る」＝身近では反対。",
    relatedWords: ["garden", "yard", "lawn"],
  },
  {
    id: "badger",
    word: "badger",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["アナグマ", "しつこくせがむ"],
    pronunciation: "/ˈbædʒər/",
    exampleSentence: "A badger came out of the hedge at night.",
    exampleTranslationJa: "夜、生け垣からアナグマが出てきた。",
    collocations: ["a wild badger", "badger sett", "badger someone into"],
    mnemonic: "白黒の縞の顔をした穴掘り動物。しつこく追い回すことから「せがむ」の動詞にもなる。",
    relatedWords: ["fox", "burrow", "wildlife"],
  },
  {
    id: "bakery",
    word: "bakery",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["パン屋、製パン所"],
    pronunciation: "/ˈbeɪkəri/",
    exampleSentence: "The bakery on the corner sells fresh bread.",
    exampleTranslationJa: "角のパン屋は焼きたてのパンを売っている。",
    collocations: ["a local bakery", "at the bakery", "bakery products"],
    mnemonic: "bake(焼く)+ -ery(場所)。brewery(醸造所)と同じ作り。",
    relatedWords: ["bread", "baker", "pastry"],
  },
  {
    id: "banister",
    word: "banister",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["階段の手すり"],
    pronunciation: "/ˈbænɪstər/",
    exampleSentence: "Hold the banister when you come down the stairs.",
    exampleTranslationJa: "階段を降りるときは手すりにつかまって。",
    collocations: ["hold the banister", "slide down the banister", "a wooden banister"],
    mnemonic: "階段に沿って手を滑らせる棒。廊下やバルコニーの手すりは handrail。",
    relatedWords: ["handrail", "staircase", "railing"],
  },
  {
    id: "barbecue",
    word: "barbecue",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["バーベキュー、野外の炭火焼き", "炭火で焼く"],
    pronunciation: "/ˈbɑːrbɪkjuː/",
    exampleSentence: "They had a barbecue in the garden on Sunday.",
    exampleTranslationJa: "日曜に庭でバーベキューをした。",
    collocations: ["have a barbecue", "a barbecue grill", "barbecue sauce"],
    mnemonic: "カリブ先住民の言葉 barbacoa(木の焼き台)から。BBQ と略される。",
    relatedWords: ["grill", "picnic", "charcoal"],
  },
  {
    id: "barn",
    word: "barn",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["納屋、家畜小屋"],
    pronunciation: "/bɑːrn/",
    exampleSentence: "The horses were kept in the barn all winter.",
    exampleTranslationJa: "馬は冬のあいだずっと納屋に入れられていた。",
    collocations: ["an old barn", "in the barn", "barn door"],
    mnemonic: "古英語 bere(大麦)+ ærn(家)。もとは麦をしまう建物。",
    relatedWords: ["farm", "stable", "hay"],
  },
  {
    id: "basin",
    word: "basin",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["洗面器、たらい", "洗面台", "(地形の)盆地、流域"],
    pronunciation: "/ˈbeɪsn/",
    exampleSentence: "She filled the basin with warm water.",
    exampleTranslationJa: "彼女はたらいにぬるま湯を満たした。",
    collocations: ["a washing basin", "fill the basin", "the river basin"],
    mnemonic: "くぼんで水をためる形。地形でも水が集まるくぼみ＝盆地・流域を指す。",
    relatedWords: ["bowl", "sink", "valley"],
  },
  {
    id: "bathroom",
    word: "bathroom",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["浴室、洗面所", "(米)トイレ"],
    pronunciation: "/ˈbæθruːm/",
    exampleSentence: "The bathroom is at the end of the corridor.",
    exampleTranslationJa: "浴室は廊下の突き当たりです。",
    collocations: ["go to the bathroom", "a shared bathroom", "bathroom mirror"],
    mnemonic: "bath(風呂)+ room。米国では遠回しにトイレを指す語としても使う。",
    relatedWords: ["bathtub", "toilet", "shower"],
  },
  {
    id: "bathtub",
    word: "bathtub",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["浴槽、バスタブ"],
    pronunciation: "/ˈbæθtʌb/",
    exampleSentence: "He lay in the bathtub and closed his eyes.",
    exampleTranslationJa: "彼は浴槽に横たわって目を閉じた。",
    collocations: ["in the bathtub", "fill the bathtub", "a deep bathtub"],
    mnemonic: "bath(風呂)+ tub(おけ)。英国では単に bath とも言う。",
    relatedWords: ["bathroom", "tub", "shower"],
  },
  {
    id: "beard",
    word: "beard",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["あごひげ"],
    pronunciation: "/bɪrd/",
    exampleSentence: "He has grown a thick grey beard.",
    exampleTranslationJa: "彼は濃い白いあごひげを伸ばした。",
    collocations: ["grow a beard", "a full beard", "shave off a beard"],
    mnemonic: "あごの毛。口ひげは moustache、もみあげは sideburns と区別する。",
    relatedWords: ["moustache", "shave", "chin"],
  },
  {
    id: "beaver",
    word: "beaver",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ビーバー"],
    pronunciation: "/ˈbiːvər/",
    exampleSentence: "A beaver had built a dam across the stream.",
    exampleTranslationJa: "ビーバーが小川にダムを作っていた。",
    collocations: ["a beaver dam", "busy as a beaver", "beaver lodge"],
    mnemonic: "木をかじって川をせき止める動物。よく働くことから eager beaver(働き者)の言い方がある。",
    relatedWords: ["dam", "otter", "rodent"],
  },
  {
    id: "bedbug",
    word: "bedbug",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["トコジラミ、南京虫"],
    pronunciation: "/ˈbedbʌɡ/",
    exampleSentence: "The hotel had to close because of bedbugs.",
    exampleTranslationJa: "そのホテルはトコジラミのせいで閉鎖せざるを得なかった。",
    collocations: ["a bedbug bite", "bedbug infestation", "check for bedbugs"],
    mnemonic: "bed(寝床)+ bug(虫)。寝ている間に刺す小さな虫。",
    relatedWords: ["flea", "insect", "mattress"],
  },
  {
    id: "bedding",
    word: "bedding",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["寝具一式(シーツ・毛布など)"],
    pronunciation: "/ˈbedɪŋ/",
    exampleSentence: "Clean bedding is provided every week.",
    exampleTranslationJa: "清潔な寝具が毎週用意される。",
    collocations: ["clean bedding", "change the bedding", "spare bedding"],
    mnemonic: "bed(寝床)+ -ing。数えられない名詞で、シーツも毛布もまとめて指す。",
    relatedWords: ["sheet", "blanket", "duvet"],
  },
  {
    id: "bedroom",
    word: "bedroom",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["寝室"],
    pronunciation: "/ˈbedruːm/",
    exampleSentence: "The flat has two bedrooms and a small kitchen.",
    exampleTranslationJa: "そのアパートは寝室が2つと小さな台所がある。",
    collocations: ["a spare bedroom", "master bedroom", "a two bedroom flat"],
    mnemonic: "bed(ベッド)+ room。英国の物件広告では部屋数をこの語で数える。",
    relatedWords: ["bed", "flat", "kitchen"],
  },
  {
    id: "bicycle",
    word: "bicycle",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["自転車"],
    pronunciation: "/ˈbaɪsɪkl/",
    exampleSentence: "She rides her bicycle to work every day.",
    exampleTranslationJa: "彼女は毎日自転車で通勤している。",
    collocations: ["ride a bicycle", "a bicycle lane", "bicycle helmet"],
    mnemonic: "bi-(2)+ cycle(輪)。三輪車は tricycle(tri-=3)。話し言葉では bike。",
    relatedWords: ["bike", "tricycle", "cycling"],
  },
  {
    id: "billboard",
    word: "billboard",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["(屋外の)大型広告板"],
    pronunciation: "/ˈbɪlbɔːrd/",
    exampleSentence: "A huge billboard advertised the new film.",
    exampleTranslationJa: "巨大な広告板が新作映画を宣伝していた。",
    collocations: ["a huge billboard", "billboard advertising", "put up a billboard"],
    mnemonic: "bill(ここでは貼り紙)+ board(板)。道路脇の大きな看板。",
    relatedWords: ["poster", "advertisement", "sign"],
  },
  {
    id: "binoculars",
    word: "binoculars",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["双眼鏡"],
    pronunciation: "/bɪˈnɑːkjələrz/",
    exampleSentence: "He watched the birds through his binoculars.",
    exampleTranslationJa: "彼は双眼鏡で鳥を観察した。",
    collocations: ["a pair of binoculars", "look through binoculars", "powerful binoculars"],
    mnemonic: "bin-(2つ)+ ocul(目)。両目で見るので常に複数形。数えるときは a pair of。",
    relatedWords: ["telescope", "lens", "magnify"],
  },
  {
    id: "bleach",
    word: "bleach",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["漂白剤", "漂白する、色を抜く"],
    pronunciation: "/bliːtʃ/",
    exampleSentence: "Do not mix bleach with other cleaning products.",
    exampleTranslationJa: "漂白剤を他の洗剤と混ぜてはいけない。",
    collocations: ["household bleach", "bleach the sheets", "smell of bleach"],
    mnemonic: "black とは逆に、色を抜いて白くする。日に当てて髪が抜けるのも bleached。",
    relatedWords: ["detergent", "whiten", "disinfect"],
  },
  {
    id: "blizzard",
    word: "blizzard",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["猛吹雪"],
    pronunciation: "/ˈblɪzərd/",
    exampleSentence: "The road was closed during the blizzard.",
    exampleTranslationJa: "猛吹雪の間、その道路は閉鎖された。",
    collocations: ["a severe blizzard", "caught in a blizzard", "blizzard conditions"],
    mnemonic: "ただの snowstorm より強く、風で前が見えなくなる雪。",
    relatedWords: ["snowstorm", "storm", "snow"],
  },
  {
    id: "bookcase",
    word: "bookcase",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["本棚、書棚"],
    pronunciation: "/ˈbʊkkeɪs/",
    exampleSentence: "The bookcase reached from the floor to the ceiling.",
    exampleTranslationJa: "その本棚は床から天井まで届いていた。",
    collocations: ["a wooden bookcase", "fill the bookcase", "a tall bookcase"],
    mnemonic: "book(本)+ case(入れ物)。棚板1枚は shelf、家具としての棚全体が bookcase。",
    relatedWords: ["shelf", "library", "furniture"],
  },
  {
    id: "bookmark",
    word: "bookmark",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["しおり", "(ページを)ブックマークする"],
    pronunciation: "/ˈbʊkmɑːrk/",
    exampleSentence: "She used a train ticket as a bookmark.",
    exampleTranslationJa: "彼女は電車の切符をしおりにした。",
    collocations: ["a leather bookmark", "bookmark a page", "save a bookmark"],
    mnemonic: "book(本)+ mark(印)。読みかけの位置に印を残す。ブラウザの機能も同じ発想。",
    relatedWords: ["page", "book", "save"],
  },
  {
    id: "bottle",
    word: "bottle",
    level: "A2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["びん、ボトル", "びん詰めにする"],
    pronunciation: "/ˈbɑːtl/",
    exampleSentence: "He drank a whole bottle of water.",
    exampleTranslationJa: "彼は水を1本まるごと飲んだ。",
    collocations: ["a bottle of water", "an empty bottle", "bottle opener"],
    mnemonic: "首の細い容器。bottle up は感情をびんに詰めるように押しこめること。",
    relatedWords: ["jar", "can", "container"],
  },
  {
    id: "boulder",
    word: "boulder",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["大きな丸い岩"],
    pronunciation: "/ˈboʊldər/",
    exampleSentence: "A huge boulder blocked the mountain path.",
    exampleTranslationJa: "大きな岩が山道をふさいでいた。",
    collocations: ["a huge boulder", "climb over a boulder", "fallen boulders"],
    mnemonic: "rock より大きく、人の力では動かせない丸い岩。小石は pebble。",
    relatedWords: ["rock", "pebble", "cliff"],
  },
  {
    id: "bouquet",
    word: "bouquet",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["花束"],
    pronunciation: "/boʊˈkeɪ/",
    exampleSentence: "He gave her a bouquet of white roses.",
    exampleTranslationJa: "彼は彼女に白いバラの花束を贈った。",
    collocations: ["a bouquet of flowers", "a wedding bouquet", "present a bouquet"],
    mnemonic: "フランス語から。つづりの t は読まず「ブーケイ」。",
    relatedWords: ["flower", "rose", "wedding"],
  },
  {
    id: "boxing",
    word: "boxing",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ボクシング"],
    pronunciation: "/ˈbɑːksɪŋ/",
    exampleSentence: "He took up boxing to get fit.",
    exampleTranslationJa: "彼は体を鍛えるためにボクシングを始めた。",
    collocations: ["a boxing match", "boxing gloves", "take up boxing"],
    mnemonic: "box(こぶしで打つ)の -ing 形。英国の Boxing Day は贈り物の箱に由来する別語源。",
    relatedWords: ["wrestling", "glove", "ring"],
  },
  {
    id: "braid",
    word: "braid",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["編んだ髪、三つ編み", "編む"],
    pronunciation: "/breɪd/",
    exampleSentence: "She wore her hair in a long braid.",
    exampleTranslationJa: "彼女は髪を長い三つ編みにしていた。",
    collocations: ["wear a braid", "braid your hair", "a thick braid"],
    mnemonic: "三本の束を交差させて編むこと。英国では plait とも言う。",
    relatedWords: ["plait", "hair", "weave"],
  },
]
