import type { VocabularyEntry } from '../types'

// 増補 第10弾。文章・文学・芸術と、理科の基礎語。多読本文と説明文の下地になる語をそろえる。
export const plus10: VocabularyEntry[] = [
  {
    id: "apostrophe",
    word: "apostrophe",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アポストロフィ(')"],
    pronunciation: "/əˈpɑːstrəfi/",
    exampleSentence: "Put an apostrophe before the s in the possessive.",
    exampleTranslationJa: "所有格では s の前にアポストロフィを置きます。",
    collocations: ["an apostrophe before the s", "misuse of the apostrophe"],
    mnemonic: "所有(John's)と短縮(don't)の二つの働きがある。複数形には付けない。",
    relatedWords: ["punctuation", "comma", "possessive"],
  },
  {
    id: "comma",
    word: "comma",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["コンマ(,)"],
    pronunciation: "/ˈkɑːmə/",
    exampleSentence: "Use a comma to separate items in a list.",
    exampleTranslationJa: "並べるときはコンマで区切ります。",
    collocations: ["a comma splice", "insert a comma", "the Oxford comma"],
    mnemonic: "最後の and の前に置くコンマを the Oxford comma と呼ぶ。",
    relatedWords: ["punctuation", "full stop", "semicolon"],
  },
  {
    id: "semicolon",
    word: "semicolon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["セミコロン(;)"],
    pronunciation: "/ˈsemikoʊlən/",
    exampleSentence: "A semicolon joins two closely related sentences.",
    exampleTranslationJa: "セミコロンは密接に関係する2文をつなぐ。",
    collocations: ["use a semicolon", "separate with a semicolon"],
    wordFormation: "semi-(半分)+ colon(コロン)。",
    mnemonic: "コンマより強く、ピリオドより弱い切れ目。",
    relatedWords: ["colon", "comma", "punctuation"],
  },
  {
    id: "colon",
    word: "colon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["コロン(:)", "結腸"],
    pronunciation: "/ˈkoʊlən/",
    exampleSentence: "A colon introduces a list or an explanation.",
    exampleTranslationJa: "コロンは列挙や説明を導く。",
    collocations: ["a colon introduces", "after the colon", "colon cancer"],
    mnemonic: "記号のコロンと、大腸の「結腸」が同じつづり。",
    relatedWords: ["semicolon", "punctuation", "intestine"],
  },
  {
    id: "bracket",
    word: "bracket",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["かっこ", "(所得などの)区分"],
    pronunciation: "/ˈbrækɪt/",
    exampleSentence: "Put the year in brackets after the name.",
    exampleTranslationJa: "名前のあとに年をかっこで入れてください。",
    collocations: ["in brackets", "a tax bracket", "square brackets"],
    mnemonic: "英では ( ) が brackets、米では parentheses。所得の「区分」の意味も重要。",
    relatedWords: ["parenthesis", "category", "punctuation"],
  },
  {
    id: "parenthesis",
    word: "parenthesis",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["丸かっこ", "挿入句"],
    pronunciation: "/pəˈrenθəsɪs/",
    exampleSentence: "The note appears in parenthesis at the end.",
    exampleTranslationJa: "その注は最後に丸かっこで示されている。",
    collocations: ["in parenthesis", "a parenthesis in the text"],
    mnemonic: "複数形は parentheses。文法では「挿入句」も指す。",
    relatedWords: ["bracket", "aside", "punctuation"],
  },
  {
    id: "hyphen",
    word: "hyphen",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハイフン(-)"],
    pronunciation: "/ˈhaɪfn/",
    exampleSentence: "Write it with a hyphen: well-known.",
    exampleTranslationJa: "ハイフンをつけて well-known と書きます。",
    collocations: ["with a hyphen", "a hyphen between", "insert a hyphen"],
    mnemonic: "語をつなぐ短い線。文を区切る長い線は dash。",
    relatedWords: ["dash", "punctuation", "compound"],
  },
  {
    id: "asterisk",
    word: "asterisk",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アスタリスク(*)、星印"],
    pronunciation: "/ˈæstərɪsk/",
    exampleSentence: "An asterisk marks the items that are optional.",
    exampleTranslationJa: "アスタリスクは任意の項目を示す。",
    collocations: ["mark with an asterisk", "an asterisk indicates"],
    wordFormation: "ギリシャ語 aster(星)から。",
    mnemonic: "aster(星)が語根。astronomy と同語根の小さな星。",
    relatedWords: ["star", "symbol", "footnote"],
  },
  {
    id: "paragraph",
    word: "paragraph",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["段落"],
    pronunciation: "/ˈpærəɡræf/",
    exampleSentence: "Start a new paragraph for each idea.",
    exampleTranslationJa: "考えごとに段落を変えなさい。",
    collocations: ["a short paragraph", "the opening paragraph", "paragraph three"],
    wordFormation: "para-(横に)+ graph(書く)。",
    mnemonic: "一つの段落に一つの話題、が英作文の原則。",
    relatedWords: ["sentence", "passage", "text"],
  },
  {
    id: "phrase",
    word: "phrase",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["句、言い回し", "言い表す"],
    pronunciation: "/freɪz/",
    exampleSentence: "He used a phrase I had never heard before.",
    exampleTranslationJa: "彼は私が聞いたことのない言い回しを使った。",
    collocations: ["a useful phrase", "a set phrase", "phrase it carefully"],
    mnemonic: "主語と動詞の組を持たないまとまりが phrase、持つのが clause。",
    relatedWords: ["clause", "expression", "word"],
  },
  {
    id: "syllable",
    word: "syllable",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["音節"],
    pronunciation: "/ˈsɪləbl/",
    exampleSentence: "The word has three syllables.",
    exampleTranslationJa: "その語は3音節ある。",
    collocations: ["a stressed syllable", "count the syllables", "the first syllable"],
    mnemonic: "母音を核とする音のかたまり。アクセントは音節単位で置く。",
    relatedWords: ["stress", "vowel", "pronunciation"],
  },
  {
    id: "vowel",
    word: "vowel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["母音"],
    pronunciation: "/ˈvaʊəl/",
    exampleSentence: "English has five vowel letters but many vowel sounds.",
    exampleTranslationJa: "英語の母音字は5つだが母音の音は多い。",
    collocations: ["a long vowel", "a vowel sound", "the vowel letters"],
    mnemonic: "a, e, i, o, u の5字に対し、音は20を超える。ここが英語の難所。",
    relatedWords: ["consonant", "sound", "syllable"],
  },
  {
    id: "consonant",
    word: "consonant",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["子音"],
    pronunciation: "/ˈkɑːnsənənt/",
    exampleSentence: "Two consonants together can be hard to say.",
    exampleTranslationJa: "子音が二つ続くと言いにくいことがある。",
    collocations: ["a consonant cluster", "a final consonant", "consonant sounds"],
    wordFormation: "con-(共に)+ sonare(鳴る)。「母音と共に鳴る音」。",
    mnemonic: "母音(vowel)と共に鳴るから consonant。sound と同語根。",
    relatedWords: ["vowel", "sound", "syllable"],
  },
  {
    id: "prefix",
    word: "prefix",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["接頭辞"],
    pronunciation: "/ˈpriːfɪks/",
    exampleSentence: "The prefix un- makes the word negative.",
    exampleTranslationJa: "接頭辞 un- はその語を否定にする。",
    collocations: ["a negative prefix", "add a prefix", "the prefix re-"],
    wordFormation: "pre-(前に)+ fix(付ける)。",
    mnemonic: "語の前に付くのが prefix、後ろが suffix。",
    relatedWords: ["suffix", "root", "word formation"],
  },
  {
    id: "suffix",
    word: "suffix",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["接尾辞"],
    pronunciation: "/ˈsʌfɪks/",
    exampleSentence: "The suffix -ness turns an adjective into a noun.",
    exampleTranslationJa: "接尾辞 -ness は形容詞を名詞に変える。",
    collocations: ["add a suffix", "the suffix -ly", "a noun suffix"],
    wordFormation: "suf-(下に・後に)+ fix(付ける)。",
    mnemonic: "-ness や -ity がこれ。品詞を変える働きをもつ。",
    relatedWords: ["prefix", "root", "word formation"],
  },
  {
    id: "synonym",
    word: "synonym",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["同義語"],
    pronunciation: "/ˈsɪnənɪm/",
    exampleSentence: "Find a synonym for the word big.",
    exampleTranslationJa: "big の同義語を探しなさい。",
    collocations: ["a synonym for", "find a synonym", "near synonyms"],
    wordFormation: "syn-(同じ)+ onyma(名)。",
    mnemonic: "syn(同じ)+ nym(名)。反対は antonym。",
    relatedWords: ["antonym", "meaning", "thesaurus"],
  },
  {
    id: "antonym",
    word: "antonym",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["反意語"],
    pronunciation: "/ˈæntənɪm/",
    exampleSentence: "The antonym of hot is cold.",
    exampleTranslationJa: "hot の反意語は cold だ。",
    collocations: ["the antonym of", "synonyms and antonyms"],
    wordFormation: "anti-(反対)+ onyma(名)。",
    mnemonic: "anti(反対)+ nym(名)。synonym と対で覚える。",
    relatedWords: ["synonym", "opposite", "meaning"],
  },
  {
    id: "grammar",
    word: "grammar",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["文法"],
    pronunciation: "/ˈɡræmər/",
    exampleSentence: "Her grammar is better than her pronunciation.",
    exampleTranslationJa: "彼女は発音より文法のほうが得意だ。",
    collocations: ["English grammar", "a grammar book", "check the grammar"],
    mnemonic: "つづりは -ar(-er ではない)。glamour と同語源なのが面白いところ。",
    relatedWords: ["syntax", "rule", "language"],
  },
  {
    id: "punctuation",
    word: "punctuation",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["句読点、句読法"],
    pronunciation: "/ˌpʌŋktʃuˈeɪʃn/",
    exampleSentence: "Punctuation changes the meaning of a sentence.",
    exampleTranslationJa: "句読点は文の意味を変える。",
    collocations: ["punctuation marks", "check the punctuation", "correct punctuation"],
    wordFormation: "ラテン語 punctum(点)から。point と同語根。",
    mnemonic: "point(点)が語根。コンマもピリオドも punctuation marks。",
    relatedWords: ["comma", "period", "grammar"],
  },
  {
    id: "spelling",
    word: "spelling",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["つづり、つづり方"],
    pronunciation: "/ˈspelɪŋ/",
    exampleSentence: "American spelling differs from British spelling.",
    exampleTranslationJa: "米式のつづりは英式と異なる。",
    collocations: ["a spelling mistake", "check the spelling", "spelling rules"],
    mnemonic: "colour / color のような英米差もこの語で語る。",
    relatedWords: ["spell", "write", "grammar"],
  },
  {
    id: "handwriting",
    word: "handwriting",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["手書きの字、筆跡"],
    pronunciation: "/ˈhændraɪtɪŋ/",
    exampleSentence: "I cannot read his handwriting.",
    exampleTranslationJa: "彼の字は読めない。",
    collocations: ["neat handwriting", "recognise the handwriting", "poor handwriting"],
    wordFormation: "hand(手)+ writing(書くこと)。",
    mnemonic: "字のうまさも、筆跡鑑定の「筆跡」も同じ語。",
    relatedWords: ["writing", "script", "signature"],
  },
  {
    id: "footnote",
    word: "footnote",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["脚注"],
    pronunciation: "/ˈfʊtnoʊt/",
    exampleSentence: "The source is given in a footnote.",
    exampleTranslationJa: "出典は脚注に示されている。",
    collocations: ["in a footnote", "add a footnote", "a footnote to history"],
    wordFormation: "foot(下部)+ note(注)。",
    mnemonic: "ページの下(foot)の注。a footnote to history は「歴史の片隅の出来事」。",
    relatedWords: ["note", "citation", "reference"],
  },
  {
    id: "bibliography",
    word: "bibliography",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["参考文献一覧"],
    pronunciation: "/ˌbɪbliˈɑːɡrəfi/",
    exampleSentence: "Include a bibliography at the end of the essay.",
    exampleTranslationJa: "小論の最後に参考文献一覧を付けなさい。",
    collocations: ["compile a bibliography", "a select bibliography"],
    wordFormation: "biblio-(書物)+ graphy(書くこと)。",
    mnemonic: "biblio(本)が語根。Bible と同語源。",
    relatedWords: ["reference", "citation", "source"],
  },
  {
    id: "citation",
    word: "citation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["引用、出典表示", "表彰状"],
    pronunciation: "/saɪˈteɪʃn/",
    exampleSentence: "Every claim needs a citation.",
    exampleTranslationJa: "どの主張にも出典が要る。",
    collocations: ["a citation index", "provide a citation", "cite a source"],
    wordFormation: "cite(引用する)+ -ation。",
    mnemonic: "論文の引用のほか、軍や警察の「表彰」の意味もある。",
    relatedWords: ["quote", "reference", "source"],
  },
  {
    id: "appendix",
    word: "appendix",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["付録", "虫垂"],
    pronunciation: "/əˈpendɪks/",
    exampleSentence: "The full data appear in the appendix.",
    exampleTranslationJa: "全データは付録に載っている。",
    collocations: ["see the appendix", "in the appendix", "have your appendix out"],
    mnemonic: "複数形は appendices(本の付録)/ appendixes(臓器)。本にも体にも付いている。",
    relatedWords: ["supplement", "attachment", "organ"],
  },
  {
    id: "glossary",
    word: "glossary",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["用語集"],
    pronunciation: "/ˈɡlɑːsəri/",
    exampleSentence: "There is a glossary of legal terms at the back.",
    exampleTranslationJa: "巻末に法律用語の用語集がある。",
    collocations: ["a glossary of terms", "consult the glossary"],
    mnemonic: "本の中で使う専門語を短く説明した一覧。索引(index)とは別。",
    relatedWords: ["dictionary", "index", "terminology"],
  },
  {
    id: "preface",
    word: "preface",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["序文、まえがき"],
    pronunciation: "/ˈprefəs/",
    exampleSentence: "In the preface she thanks her students.",
    exampleTranslationJa: "序文で彼女は学生に謝意を述べている。",
    collocations: ["in the preface", "write a preface"],
    wordFormation: "pre-(前に)+ fari(語る)。",
    mnemonic: "著者本人が書く前置き。他人が書くのが foreword。",
    relatedWords: ["foreword", "introduction", "preamble"],
  },
  {
    id: "foreword",
    word: "foreword",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["序文(著者以外が書くもの)"],
    pronunciation: "/ˈfɔːrwɜːrd/",
    exampleSentence: "The foreword was written by a former minister.",
    exampleTranslationJa: "その序文は元大臣によって書かれた。",
    collocations: ["write the foreword", "in the foreword"],
    wordFormation: "fore-(前)+ word(言葉)。",
    mnemonic: "forward(前へ)とつづりが違う。人が寄せる推薦文的な前書き。",
    relatedWords: ["preface", "introduction", "preamble"],
  },
  {
    id: "prose",
    word: "prose",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["散文(詩でない文章)"],
    pronunciation: "/proʊz/",
    exampleSentence: "He writes clear, plain prose.",
    exampleTranslationJa: "彼は明晰で平明な散文を書く。",
    collocations: ["clear prose", "prose and poetry", "a prose style"],
    mnemonic: "詩(verse / poetry)に対する語。ふつうの文章全般。",
    relatedWords: ["poetry", "verse", "writing"],
  },
  {
    id: "nonfiction",
    word: "nonfiction",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ノンフィクション、事実に基づく読み物"],
    pronunciation: "/ˌnɑːnˈfɪkʃn/",
    exampleSentence: "The prize is for nonfiction only.",
    exampleTranslationJa: "その賞はノンフィクションのみが対象だ。",
    collocations: ["a work of nonfiction", "narrative nonfiction"],
    wordFormation: "non-(〜でない)+ fiction(作り話)。",
    mnemonic: "fiction の否定。伝記も歴史書もエッセイも含む。",
    relatedWords: ["fiction", "biography", "factual"],
  },
  {
    id: "narrator",
    word: "narrator",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["語り手"],
    pronunciation: "/ˈnæreɪtər/",
    exampleSentence: "The narrator turns out to be unreliable.",
    exampleTranslationJa: "その語り手は信頼できないと分かる。",
    collocations: ["an unreliable narrator", "the first-person narrator"],
    wordFormation: "narrate(語る)+ -or(人)。",
    mnemonic: "小説の「語り手」は作者とは別人格。an unreliable narrator は文学の重要概念。",
    relatedWords: ["narrate", "author", "voice"],
  },
  {
    id: "simile",
    word: "simile",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["直喩(like や as を使うたとえ)"],
    pronunciation: "/ˈsɪməli/",
    exampleSentence: "As white as snow is a simile.",
    exampleTranslationJa: "「雪のように白い」は直喩だ。",
    collocations: ["use a simile", "a simile and a metaphor"],
    mnemonic: "like / as を使うのが simile、使わず断定するのが metaphor。similar と同語根。",
    relatedWords: ["metaphor", "comparison", "figure of speech"],
  },
  {
    id: "satire",
    word: "satire",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["風刺"],
    pronunciation: "/ˈsætaɪər/",
    exampleSentence: "The play is a satire on modern politics.",
    exampleTranslationJa: "その劇は現代政治への風刺だ。",
    collocations: ["political satire", "a satire on", "biting satire"],
    mnemonic: "笑いを使って批判する表現。形容詞は satirical。",
    relatedWords: ["parody", "irony", "mockery"],
  },
  {
    id: "publisher",
    word: "publisher",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["出版社、発行者"],
    pronunciation: "/ˈpʌblɪʃər/",
    exampleSentence: "The publisher rejected the manuscript twice.",
    exampleTranslationJa: "出版社はその原稿を二度断った。",
    collocations: ["a book publisher", "find a publisher", "the publisher's address"],
    wordFormation: "publish(出版する)+ -er。",
    mnemonic: "会社にも個人にも使う。publish は「公(public)にする」。",
    relatedWords: ["publish", "press", "editor"],
  },
  {
    id: "proofread",
    word: "proofread",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["校正する"],
    pronunciation: "/ˈpruːfriːd/",
    exampleSentence: "Could you proofread this before I send it?",
    exampleTranslationJa: "送る前にこれを校正してもらえますか。",
    collocations: ["proofread a document", "proofread carefully"],
    wordFormation: "proof(校正刷り)+ read(読む)。",
    mnemonic: "活用は proofread-proofread-proofread(発音は過去形だけ /red/)。",
    relatedWords: ["edit", "check", "revise"],
  },
  {
    id: "paperback",
    word: "paperback",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ペーパーバック、並製本"],
    pronunciation: "/ˈpeɪpərbæk/",
    exampleSentence: "Wait for the paperback if you want it cheaper.",
    exampleTranslationJa: "安く買いたいならペーパーバックを待って。",
    collocations: ["in paperback", "a paperback edition"],
    wordFormation: "paper(紙)+ back(背)。",
    mnemonic: "表紙が紙の安い版。ふつう単行本より後に出る。",
    relatedWords: ["hardback", "book", "edition"],
  },
  {
    id: "hardback",
    word: "hardback",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ハードカバー本、上製本"],
    pronunciation: "/ˈhɑːrdbæk/",
    exampleSentence: "The hardback costs twice as much.",
    exampleTranslationJa: "ハードカバー版は倍の値段だ。",
    collocations: ["in hardback", "a hardback edition"],
    wordFormation: "hard(硬い)+ back(背)。",
    mnemonic: "米では hardcover。先に出るのはこちら。",
    relatedWords: ["paperback", "book", "edition"],
  },
  {
    id: "readership",
    word: "readership",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["読者層、購読者数"],
    pronunciation: "/ˈriːdərʃɪp/",
    exampleSentence: "The paper has a readership of two million.",
    exampleTranslationJa: "その新聞の読者は200万人いる。",
    collocations: ["a wide readership", "a readership of", "target readership"],
    wordFormation: "reader(読者)+ -ship(集合)。",
    mnemonic: "-ship は「立場・集合」。membership と同じ作り。",
    relatedWords: ["audience", "circulation", "reader"],
  },
  {
    id: "bestseller",
    word: "bestseller",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ベストセラー"],
    pronunciation: "/ˌbestˈselər/",
    exampleSentence: "Her first novel became an instant bestseller.",
    exampleTranslationJa: "彼女の最初の小説はたちまちベストセラーになった。",
    collocations: ["an instant bestseller", "a bestseller list"],
    wordFormation: "best(最も)+ seller(売れるもの)。",
    mnemonic: "よく売れた本や商品。形容詞は best-selling。",
    relatedWords: ["hit", "success", "novel"],
  },
  {
    id: "mural",
    word: "mural",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["壁画"],
    pronunciation: "/ˈmjʊrəl/",
    exampleSentence: "Children painted a mural on the school wall.",
    exampleTranslationJa: "子どもたちが校舎の壁に壁画を描いた。",
    collocations: ["paint a mural", "a mural on the wall"],
    wordFormation: "ラテン語 murus(壁)から。",
    mnemonic: "murus(壁)が語根。壁に直接描く絵。",
    relatedWords: ["painting", "wall", "fresco"],
  },
  {
    id: "palette",
    word: "palette",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["パレット", "(作品の)色づかい"],
    pronunciation: "/ˈpælət/",
    exampleSentence: "She works with a limited palette of greys.",
    exampleTranslationJa: "彼女は灰色を中心とした限られた色づかいで描く。",
    collocations: ["a colour palette", "a limited palette"],
    mnemonic: "絵の具を混ぜる板から、作品全体の「色の幅」へ。pallet(荷台)と同音。",
    relatedWords: ["colour", "paint", "canvas"],
  },
  {
    id: "conductor",
    word: "conductor",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["指揮者", "車掌", "(電気の)導体"],
    pronunciation: "/kənˈdʌktər/",
    exampleSentence: "The conductor raised his baton.",
    exampleTranslationJa: "指揮者は指揮棒を上げた。",
    collocations: ["an orchestral conductor", "a bus conductor", "a good conductor of heat"],
    wordFormation: "conduct(導く)+ -or。",
    mnemonic: "「導く人・もの」。オーケストラも、電車も、電気も同じ語。",
    relatedWords: ["orchestra", "lead", "insulator"],
  },
  {
    id: "symphony",
    word: "symphony",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["交響曲"],
    pronunciation: "/ˈsɪmfəni/",
    exampleSentence: "They played Beethoven's fifth symphony.",
    exampleTranslationJa: "彼らはベートーベンの交響曲第5番を演奏した。",
    collocations: ["a symphony orchestra", "compose a symphony"],
    wordFormation: "sym-(共に)+ phone(音)。",
    mnemonic: "sym(共に)+ phon(音)。telephone・phonics と同じ phon。",
    relatedWords: ["orchestra", "concerto", "music"],
  },
  {
    id: "chorus",
    word: "chorus",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["合唱、合唱団", "(歌の)サビ"],
    pronunciation: "/ˈkɔːrəs/",
    exampleSentence: "Everyone joined in on the chorus.",
    exampleTranslationJa: "みんながサビで一緒に歌った。",
    collocations: ["sing the chorus", "a chorus of complaints", "join the chorus"],
    mnemonic: "歌の繰り返し部分(サビ)も chorus。a chorus of ... で「一斉の〜」。",
    relatedWords: ["choir", "refrain", "sing"],
  },
  {
    id: "soloist",
    word: "soloist",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["独奏者、独唱者"],
    pronunciation: "/ˈsoʊloʊɪst/",
    exampleSentence: "The soloist received a standing ovation.",
    exampleTranslationJa: "その独奏者は総立ちの喝采を受けた。",
    collocations: ["a violin soloist", "the soloist performs"],
    wordFormation: "solo(独奏)+ -ist(人)。",
    mnemonic: "一人で演奏・歌唱する人。solo の -ist 形。",
    relatedWords: ["solo", "musician", "performer"],
  },
  {
    id: "rehearsal",
    word: "rehearsal",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["リハーサル、下けいこ"],
    pronunciation: "/rɪˈhɜːrsl/",
    exampleSentence: "The final rehearsal is on Thursday.",
    exampleTranslationJa: "最終リハーサルは木曜だ。",
    collocations: ["a dress rehearsal", "the final rehearsal", "during rehearsals"],
    wordFormation: "rehearse(けいこする)+ -al。",
    mnemonic: "a dress rehearsal は衣装をつけた本番同様の通しけいこ。",
    relatedWords: ["rehearse", "practice", "performance"],
  },
  {
    id: "encore",
    word: "encore",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アンコール"],
    pronunciation: "/ˈɑːnkɔːr/",
    exampleSentence: "The band played two songs as an encore.",
    exampleTranslationJa: "バンドはアンコールに2曲演奏した。",
    collocations: ["play an encore", "demand an encore"],
    wordFormation: "フランス語 encore(もう一度)から。",
    mnemonic: "フランス語の「もう一度」。英語ではそのまま名詞として使う。",
    relatedWords: ["performance", "concert", "applause"],
  },
  {
    id: "violin",
    word: "violin",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["バイオリン"],
    pronunciation: "/ˌvaɪəˈlɪn/",
    exampleSentence: "She has played the violin since she was five.",
    exampleTranslationJa: "彼女は5歳からバイオリンを弾いている。",
    collocations: ["play the violin", "a violin concerto"],
    mnemonic: "楽器名には the をつける(play the violin)。奏者は violinist。",
    relatedWords: ["cello", "orchestra", "instrument"],
  },
  {
    id: "cello",
    word: "cello",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["チェロ"],
    pronunciation: "/ˈtʃeloʊ/",
    exampleSentence: "The cello carries the melody in this section.",
    exampleTranslationJa: "この部分ではチェロが旋律を担う。",
    collocations: ["play the cello", "a cello suite"],
    mnemonic: "c を /tʃ/ と読む /ˈtʃeloʊ/。violoncello の短縮形。",
    relatedWords: ["violin", "bass", "instrument"],
  },
  {
    id: "flute",
    word: "flute",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["フルート"],
    pronunciation: "/fluːt/",
    exampleSentence: "He plays the flute in a local band.",
    exampleTranslationJa: "彼は地元の楽団でフルートを吹いている。",
    collocations: ["play the flute", "a flute solo"],
    mnemonic: "横に構えて吹く木管楽器。奏者は flautist / flutist。",
    relatedWords: ["clarinet", "instrument", "wind"],
  },
  {
    id: "trumpet",
    word: "trumpet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["トランペット"],
    pronunciation: "/ˈtrʌmpɪt/",
    exampleSentence: "A trumpet sounded from the far end of the hall.",
    exampleTranslationJa: "ホールの向こう端からトランペットが鳴った。",
    collocations: ["play the trumpet", "blow your own trumpet"],
    mnemonic: "blow your own trumpet は「自慢する」。",
    relatedWords: ["horn", "brass", "instrument"],
  },
  {
    id: "guitar",
    word: "guitar",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ギター"],
    pronunciation: "/ɡɪˈtɑːr/",
    exampleSentence: "He taught himself to play the guitar.",
    exampleTranslationJa: "彼は独学でギターを覚えた。",
    collocations: ["play the guitar", "an acoustic guitar", "an electric guitar"],
    mnemonic: "アクセントは後ろ /ɡɪˈtɑːr/。奏者は guitarist。",
    relatedWords: ["bass", "instrument", "string"],
  },
  {
    id: "tempo",
    word: "tempo",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["テンポ、速度", "(物事の)進み方"],
    pronunciation: "/ˈtempoʊ/",
    exampleSentence: "The tempo picks up in the second movement.",
    exampleTranslationJa: "第2楽章でテンポが上がる。",
    collocations: ["a fast tempo", "change tempo", "the tempo of change"],
    mnemonic: "ラテン語 tempus(時)から。temporary と同語根。音楽以外にも使う。",
    relatedWords: ["speed", "rhythm", "pace"],
  },
  {
    id: "chord",
    word: "chord",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["和音、コード"],
    pronunciation: "/kɔːrd/",
    exampleSentence: "He can play three chords on the guitar.",
    exampleTranslationJa: "彼はギターで3つの和音を弾ける。",
    collocations: ["a guitar chord", "strike a chord", "play a chord"],
    mnemonic: "cord(ひも)と同音。strike a chord は「共感を呼ぶ」。",
    relatedWords: ["note", "harmony", "music"],
  },
  {
    id: "playwright",
    word: "playwright",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["劇作家"],
    pronunciation: "/ˈpleɪraɪt/",
    exampleSentence: "She is Ireland's best-known living playwright.",
    exampleTranslationJa: "彼女はアイルランドで最もよく知られた存命の劇作家だ。",
    collocations: ["a young playwright", "the playwright's work"],
    wordFormation: "play(劇)+ wright(作る人)。",
    mnemonic: "-wright は「作る人」(shipwright と同じ)。write ではないのに注意。",
    relatedWords: ["dramatist", "author", "theatre"],
  },
  {
    id: "rehearse",
    word: "rehearse",
    level: "B1",
    partOfSpeech: "動詞",
    meaningsJa: ["けいこする、下読みする"],
    pronunciation: "/rɪˈhɜːrs/",
    exampleSentence: "The cast rehearse every evening this week.",
    exampleTranslationJa: "出演者たちは今週、毎晩けいこしている。",
    collocations: ["rehearse a scene", "rehearse for a concert"],
    mnemonic: "もとは「くり返し引く(harrow)」。台本や式次第を通しで練習すること。",
    relatedWords: ["practise", "rehearsal", "prepare"],
  },
  {
    id: "audition",
    word: "audition",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["オーディション", "選考を受ける"],
    pronunciation: "/ɔːˈdɪʃn/",
    exampleSentence: "She auditioned for the lead role.",
    exampleTranslationJa: "彼女は主役のオーディションを受けた。",
    collocations: ["audition for a part", "hold auditions", "a successful audition"],
    wordFormation: "ラテン語 audire(聞く)から。audio と同語根。",
    mnemonic: "audio(音)と同語根。もとは「聞いて選ぶこと」。",
    relatedWords: ["try out", "casting", "interview"],
  },
  {
    id: "friction",
    word: "friction",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["摩擦", "(人間関係の)あつれき"],
    pronunciation: "/ˈfrɪkʃn/",
    exampleSentence: "Friction between the two departments slowed the work.",
    exampleTranslationJa: "二つの部署のあつれきが仕事を遅らせた。",
    collocations: ["reduce friction", "friction between", "cause friction"],
    mnemonic: "物理の摩擦から、人と人のぎくしゃくへ。",
    relatedWords: ["resistance", "conflict", "tension"],
  },
  {
    id: "velocity",
    word: "velocity",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["速度(向きを含む)"],
    pronunciation: "/vəˈlɑːsəti/",
    exampleSentence: "The velocity of the wind was measured hourly.",
    exampleTranslationJa: "風の速度は1時間ごとに測定された。",
    collocations: ["at high velocity", "measure the velocity", "escape velocity"],
    mnemonic: "speed が単なる速さ、velocity は向きも含む物理量。",
    relatedWords: ["speed", "rate", "acceleration"],
  },
  {
    id: "acceleration",
    word: "acceleration",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["加速、加速度"],
    pronunciation: "/əkˌseləˈreɪʃn/",
    exampleSentence: "The car is praised for its acceleration.",
    exampleTranslationJa: "その車は加速のよさで評価されている。",
    collocations: ["rapid acceleration", "the acceleration of change"],
    wordFormation: "accelerate(加速する)+ -ion。",
    mnemonic: "物理の加速度と、変化が「速まること」の両方。",
    relatedWords: ["accelerate", "speed", "deceleration"],
  },
  {
    id: "atom",
    word: "atom",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["原子"],
    pronunciation: "/ˈætəm/",
    exampleSentence: "Everything around us is made of atoms.",
    exampleTranslationJa: "身のまわりのすべては原子でできている。",
    collocations: ["a hydrogen atom", "split the atom", "atoms and molecules"],
    wordFormation: "ギリシャ語 atomos(分けられない)から。",
    mnemonic: "「これ以上分けられないもの」が語源。実際には分けられると後に分かった。",
    relatedWords: ["molecule", "particle", "element"],
  },
  {
    id: "molecule",
    word: "molecule",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["分子"],
    pronunciation: "/ˈmɑːlɪkjuːl/",
    exampleSentence: "A water molecule has three atoms.",
    exampleTranslationJa: "水の分子は3個の原子からなる。",
    collocations: ["a water molecule", "molecules of gas"],
    mnemonic: "原子(atom)がいくつか結びついたもの。形容詞は molecular。",
    relatedWords: ["atom", "compound", "particle"],
  },
  {
    id: "particle",
    word: "particle",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["粒子", "(文法の)不変化詞"],
    pronunciation: "/ˈpɑːrtɪkl/",
    exampleSentence: "Dust particles hang in the sunlight.",
    exampleTranslationJa: "ほこりの粒子が日差しの中に漂う。",
    collocations: ["dust particles", "a subatomic particle", "particle physics"],
    wordFormation: "part(部分)+ -icle(小さい)。",
    mnemonic: "part(部分)の小さいもの。物理でも文法でも使う。",
    relatedWords: ["atom", "grain", "fragment"],
  },
  {
    id: "electron",
    word: "electron",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["電子"],
    pronunciation: "/ɪˈlektrɑːn/",
    exampleSentence: "Electrons carry a negative charge.",
    exampleTranslationJa: "電子は負の電荷を持つ。",
    collocations: ["a free electron", "electron microscope"],
    mnemonic: "マイナスの電気を持つ粒子。electric と同語根。",
    relatedWords: ["proton", "neutron", "atom"],
  },
  {
    id: "proton",
    word: "proton",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["陽子"],
    pronunciation: "/ˈproʊtɑːn/",
    exampleSentence: "The nucleus contains protons and neutrons.",
    exampleTranslationJa: "原子核は陽子と中性子を含む。",
    collocations: ["a proton and a neutron", "the number of protons"],
    wordFormation: "ギリシャ語 protos(第一の)から。",
    mnemonic: "protos(第一の)が語根。prototype と同語根。プラスの電荷。",
    relatedWords: ["electron", "neutron", "nucleus"],
  },
  {
    id: "neutron",
    word: "neutron",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["中性子"],
    pronunciation: "/ˈnuːtrɑːn/",
    exampleSentence: "A neutron has no electric charge.",
    exampleTranslationJa: "中性子は電荷を持たない。",
    collocations: ["a neutron star", "protons and neutrons"],
    mnemonic: "neutral(中立)から。電気的に中性だから neutron。",
    relatedWords: ["proton", "electron", "nucleus"],
  },
  {
    id: "nucleus",
    word: "nucleus",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["原子核、(細胞の)核", "中心となるもの"],
    pronunciation: "/ˈnuːkliəs/",
    exampleSentence: "These five players form the nucleus of the team.",
    exampleTranslationJa: "この5人がチームの中核をなす。",
    collocations: ["the nucleus of a cell", "the nucleus of the team"],
    wordFormation: "ラテン語 nux(木の実)から。",
    mnemonic: "nux(木の実)が語源。硬い中心部。複数形は nuclei。",
    relatedWords: ["core", "centre", "atom"],
  },
  {
    id: "solvent",
    word: "solvent",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["溶媒", "支払い能力のある"],
    pronunciation: "/ˈsɑːlvənt/",
    exampleSentence: "Water is the most common solvent.",
    exampleTranslationJa: "水は最もありふれた溶媒だ。",
    collocations: ["an organic solvent", "remain solvent", "a powerful solvent"],
    wordFormation: "solve(溶かす)+ -ent。",
    mnemonic: "solve(解く・溶かす)から。会計では「支払える」で insolvent の反対。",
    relatedWords: ["solution", "dissolve", "insolvent"],
  },
  {
    id: "catalyst",
    word: "catalyst",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["触媒", "(変化の)きっかけ"],
    pronunciation: "/ˈkætəlɪst/",
    exampleSentence: "The strike was a catalyst for reform.",
    exampleTranslationJa: "そのストライキは改革のきっかけとなった。",
    collocations: ["a catalyst for change", "act as a catalyst"],
    mnemonic: "自分は変わらずに反応を速めるもの。比喩で「変化の引き金」。",
    relatedWords: ["trigger", "stimulus", "reaction"],
  },
  {
    id: "oxidation",
    word: "oxidation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["酸化"],
    pronunciation: "/ˌɑːksɪˈdeɪʃn/",
    exampleSentence: "Rust is caused by the oxidation of iron.",
    exampleTranslationJa: "さびは鉄の酸化によって起きる。",
    collocations: ["prevent oxidation", "the oxidation of metal"],
    wordFormation: "oxide(酸化物)+ -ation。",
    mnemonic: "酸素と結びつくこと。さびも、切ったりんごの変色も酸化。",
    relatedWords: ["rust", "oxygen", "reaction"],
  },
  {
    id: "combustion",
    word: "combustion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["燃焼"],
    pronunciation: "/kəmˈbʌstʃən/",
    exampleSentence: "The internal combustion engine changed the century.",
    exampleTranslationJa: "内燃機関はその世紀を変えた。",
    collocations: ["internal combustion", "complete combustion", "spontaneous combustion"],
    mnemonic: "the internal combustion engine(内燃機関)の形で頻出。",
    relatedWords: ["burning", "fuel", "fire"],
  },
  {
    id: "voltage",
    word: "voltage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["電圧"],
    pronunciation: "/ˈvoʊltɪdʒ/",
    exampleSentence: "Check the voltage before you plug it in.",
    exampleTranslationJa: "差し込む前に電圧を確かめて。",
    collocations: ["high voltage", "mains voltage", "the voltage drops"],
    mnemonic: "電池の発明者ボルタ(Volta)の名から。海外旅行で必ず確認する語。",
    relatedWords: ["current", "electricity", "power"],
  },
  {
    id: "insulator",
    word: "insulator",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["絶縁体、断熱材"],
    pronunciation: "/ˈɪnsəleɪtər/",
    exampleSentence: "Rubber is an excellent insulator.",
    exampleTranslationJa: "ゴムは優れた絶縁体だ。",
    collocations: ["a good insulator", "an electrical insulator"],
    wordFormation: "insulate(絶縁する)+ -or。",
    mnemonic: "island(島)と同語根。「島のように切り離す」もの。",
    relatedWords: ["conductor", "insulation", "rubber"],
  },
  {
    id: "magnet",
    word: "magnet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["磁石", "人を引きつけるもの"],
    pronunciation: "/ˈmæɡnət/",
    exampleSentence: "The city is a magnet for young artists.",
    exampleTranslationJa: "その街は若い芸術家を引きつけている。",
    collocations: ["a fridge magnet", "a magnet for tourists"],
    mnemonic: "物を引きつける磁石から、人を引き寄せる場所へ。",
    relatedWords: ["magnetism", "attract", "iron"],
  },
  {
    id: "magnetism",
    word: "magnetism",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["磁気", "(人の)引きつける力"],
    pronunciation: "/ˈmæɡnətɪzəm/",
    exampleSentence: "His personal magnetism filled the room.",
    exampleTranslationJa: "彼の人間的な魅力が部屋を満たした。",
    collocations: ["personal magnetism", "the force of magnetism"],
    wordFormation: "magnet(磁石)+ -ism。",
    mnemonic: "物理の磁気と、人の「引力」の両方。",
    relatedWords: ["magnet", "attraction", "charisma"],
  },
  {
    id: "telescope",
    word: "telescope",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["望遠鏡"],
    pronunciation: "/ˈteləskoʊp/",
    exampleSentence: "They looked at Saturn through a telescope.",
    exampleTranslationJa: "彼らは望遠鏡で土星を見た。",
    collocations: ["through a telescope", "a space telescope"],
    wordFormation: "tele-(遠く)+ scope(見る)。",
    mnemonic: "tele(遠く)+ scope(見る道具)。television と同じ tele。",
    relatedWords: ["microscope", "lens", "astronomy"],
  },
  {
    id: "microscope",
    word: "microscope",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["顕微鏡"],
    pronunciation: "/ˈmaɪkrəskoʊp/",
    exampleSentence: "Bacteria are visible under a microscope.",
    exampleTranslationJa: "細菌は顕微鏡で見える。",
    collocations: ["under a microscope", "an electron microscope"],
    wordFormation: "micro-(小さい)+ scope(見る)。",
    mnemonic: "under the microscope は「細かく調べられて」という比喩にもなる。",
    relatedWords: ["telescope", "lens", "laboratory"],
  },
  {
    id: "chromosome",
    word: "chromosome",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["染色体"],
    pronunciation: "/ˈkroʊməsoʊm/",
    exampleSentence: "Humans have 23 pairs of chromosomes.",
    exampleTranslationJa: "人間には23対の染色体がある。",
    collocations: ["the X chromosome", "a pair of chromosomes"],
    wordFormation: "chroma(色)+ soma(体)。染色で見えることから。",
    mnemonic: "「色のつく体」が語源。染色液で染まって見えたことから。",
    relatedWords: ["gene", "DNA", "cell"],
  },
  {
    id: "organism",
    word: "organism",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["生物、有機体"],
    pronunciation: "/ˈɔːrɡənɪzəm/",
    exampleSentence: "A single-celled organism can survive here.",
    exampleTranslationJa: "単細胞生物はここでも生きられる。",
    collocations: ["a living organism", "a single-celled organism"],
    wordFormation: "organ(器官)+ -ism。",
    mnemonic: "器官(organ)が集まって働く一つのまとまり。",
    relatedWords: ["creature", "life", "cell"],
  },
  {
    id: "mutation",
    word: "mutation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["突然変異"],
    pronunciation: "/mjuːˈteɪʃn/",
    exampleSentence: "A single mutation can change the whole protein.",
    exampleTranslationJa: "たった一つの変異がタンパク質全体を変えうる。",
    collocations: ["a genetic mutation", "undergo mutation"],
    wordFormation: "mutate(変異する)+ -ion。",
    mnemonic: "mutate は「変わる」。ウイルスの変異株の話で頻出。",
    relatedWords: ["mutate", "gene", "variation"],
  },
  {
    id: "photosynthesis",
    word: "photosynthesis",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["光合成"],
    pronunciation: "/ˌfoʊtoʊˈsɪnθəsɪs/",
    exampleSentence: "Plants make sugar through photosynthesis.",
    exampleTranslationJa: "植物は光合成によって糖を作る。",
    collocations: ["the process of photosynthesis", "carry out photosynthesis"],
    wordFormation: "photo-(光)+ synthesis(合成)。",
    mnemonic: "photo(光)+ synthesis(合成)。語のつくりがそのまま意味。",
    relatedWords: ["plant", "chlorophyll", "respiration"],
  },
  {
    id: "respiration",
    word: "respiration",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["呼吸(作用)"],
    pronunciation: "/ˌrespəˈreɪʃn/",
    exampleSentence: "Respiration releases energy from sugar.",
    exampleTranslationJa: "呼吸は糖からエネルギーを取り出す。",
    collocations: ["cellular respiration", "artificial respiration"],
    wordFormation: "re-(繰り返し)+ spirare(息をする)。spirit と同語根。",
    mnemonic: "spirit(息・魂)と同語根。生物学では「細胞が糖を分解すること」。",
    relatedWords: ["breathing", "oxygen", "photosynthesis"],
  },
  {
    id: "digestion",
    word: "digestion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["消化"],
    pronunciation: "/daɪˈdʒestʃən/",
    exampleSentence: "Fibre helps digestion.",
    exampleTranslationJa: "食物繊維は消化を助ける。",
    collocations: ["aid digestion", "poor digestion", "the digestion of food"],
    wordFormation: "digest(消化する)+ -ion。",
    mnemonic: "食べ物にも、情報を「消化する」比喩にも digest を使う。",
    relatedWords: ["digest", "stomach", "nutrition"],
  },
  {
    id: "ecosystem",
    word: "ecosystem",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["生態系"],
    pronunciation: "/ˈiːkoʊsɪstəm/",
    exampleSentence: "The whole ecosystem depends on that one fish.",
    exampleTranslationJa: "生態系全体がその一種の魚に依存している。",
    collocations: ["a fragile ecosystem", "the marine ecosystem", "a digital ecosystem"],
    wordFormation: "eco-(生息環境)+ system。",
    mnemonic: "生き物と環境のひとまとまり。IT でも「エコシステム」と比喩的に使う。",
    relatedWords: ["habitat", "environment", "biodiversity"],
  },
  {
    id: "food chain",
    word: "food chain",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["食物連鎖"],
    pronunciation: "/fuːd tʃeɪn/",
    exampleSentence: "Toxins build up as you move up the food chain.",
    exampleTranslationJa: "食物連鎖の上にいくほど毒素がたまる。",
    collocations: ["the food chain", "move up the food chain", "at the top of the food chain"],
    mnemonic: "組織の序列を指す比喩にもなる(at the top of the food chain)。",
    relatedWords: ["ecosystem", "predator", "prey"],
  },
  {
    id: "orbit",
    word: "orbit",
    level: "B1",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["軌道", "周回する"],
    pronunciation: "/ˈɔːrbɪt/",
    exampleSentence: "The satellite orbits the Earth every 90 minutes.",
    exampleTranslationJa: "その衛星は90分ごとに地球を周回する。",
    collocations: ["in orbit", "put into orbit", "orbit the sun"],
    mnemonic: "天体の軌道から、影響の及ぶ「圏内」の比喩へ。",
    relatedWords: ["satellite", "revolve", "circle"],
  },
  {
    id: "galaxy",
    word: "galaxy",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["銀河"],
    pronunciation: "/ˈɡæləksi/",
    exampleSentence: "Our galaxy contains billions of stars.",
    exampleTranslationJa: "私たちの銀河には何十億もの星がある。",
    collocations: ["a distant galaxy", "the Milky Way galaxy"],
    wordFormation: "ギリシャ語 gala(乳)から。天の川の白さより。",
    mnemonic: "gala(乳)が語源。天の川の白さから「乳の道」と呼ばれた。",
    relatedWords: ["universe", "star", "space"],
  },
  {
    id: "comet",
    word: "comet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["彗星(すいせい)"],
    pronunciation: "/ˈkɑːmɪt/",
    exampleSentence: "The comet returns every 76 years.",
    exampleTranslationJa: "その彗星は76年ごとに戻ってくる。",
    collocations: ["a comet passes", "the tail of a comet"],
    wordFormation: "ギリシャ語 kometes(長い髪の)から。",
    mnemonic: "「長い髪の星」が語源。尾を髪に見立てた。",
    relatedWords: ["asteroid", "meteor", "orbit"],
  },
  {
    id: "asteroid",
    word: "asteroid",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["小惑星"],
    pronunciation: "/ˈæstərɔɪd/",
    exampleSentence: "An asteroid passed close to the Earth.",
    exampleTranslationJa: "小惑星が地球のそばを通過した。",
    collocations: ["an asteroid belt", "an asteroid impact"],
    wordFormation: "aster(星)+ -oid(のようなもの)。",
    mnemonic: "aster(星)+ oid(のような)。asterisk と同語根。",
    relatedWords: ["comet", "planet", "space"],
  },
  {
    id: "eclipse",
    word: "eclipse",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["日食、月食", "かすませる、しのぐ"],
    pronunciation: "/ɪˈklɪps/",
    exampleSentence: "A solar eclipse will be visible next spring.",
    exampleTranslationJa: "来春、日食が見られる。",
    collocations: ["a solar eclipse", "a lunar eclipse", "eclipse a rival"],
    mnemonic: "天体が隠れることから、人の名声を「かすませる」意味へ。",
    relatedWords: ["shadow", "sun", "moon"],
  },
  {
    id: "ozone",
    word: "ozone",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["オゾン"],
    pronunciation: "/ˈoʊzoʊn/",
    exampleSentence: "The ozone layer absorbs harmful rays.",
    exampleTranslationJa: "オゾン層は有害な光線を吸収する。",
    collocations: ["the ozone layer", "ozone depletion"],
    mnemonic: "the ozone layer(オゾン層)の形でほぼ決まって使う。",
    relatedWords: ["atmosphere", "layer", "oxygen"],
  },
  {
    id: "sediment",
    word: "sediment",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["堆積物、沈殿物"],
    pronunciation: "/ˈsedɪmənt/",
    exampleSentence: "Sediment builds up at the mouth of the river.",
    exampleTranslationJa: "堆積物が川の河口にたまる。",
    collocations: ["sediment builds up", "layers of sediment"],
    wordFormation: "ラテン語 sedere(座る)から。「沈んで座るもの」。",
    mnemonic: "sedere(座る)が語根。沈んで底に「座る」もの。",
    relatedWords: ["deposit", "silt", "layer"],
  },
  {
    id: "erosion",
    word: "erosion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["浸食", "(権利などの)侵食"],
    pronunciation: "/ɪˈroʊʒn/",
    exampleSentence: "Coastal erosion threatens the village.",
    exampleTranslationJa: "海岸の浸食がその村を脅かしている。",
    collocations: ["soil erosion", "coastal erosion", "the erosion of trust"],
    wordFormation: "erode(削る)+ -ion。",
    mnemonic: "土地が削られることから、信頼や権利が「じわじわ失われる」比喩へ。",
    relatedWords: ["erode", "wear", "weathering"],
  },
  {
    id: "volcano",
    word: "volcano",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["火山"],
    pronunciation: "/vɑːlˈkeɪnoʊ/",
    exampleSentence: "The volcano has been quiet for 200 years.",
    exampleTranslationJa: "その火山は200年間静かだ。",
    collocations: ["an active volcano", "a dormant volcano", "the volcano erupts"],
    wordFormation: "ローマの火の神 Vulcan から。",
    mnemonic: "ローマの火の神の名から。複数形は volcanoes。",
    relatedWords: ["eruption", "lava", "mountain"],
  },
  {
    id: "renewable",
    word: "renewable",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["再生可能な"],
    pronunciation: "/rɪˈnuːəbl/",
    exampleSentence: "Half the country's power is now renewable.",
    exampleTranslationJa: "その国の電力の半分は今や再生可能だ。",
    collocations: ["renewable energy", "renewable resources", "a renewable contract"],
    wordFormation: "renew(更新する)+ -able。",
    mnemonic: "エネルギーの話では「使っても尽きない」。契約なら「更新できる」。",
    relatedWords: ["sustainable", "solar", "fossil fuel"],
  },
  {
    id: "fossil fuel",
    word: "fossil fuel",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["化石燃料"],
    pronunciation: "/ˈfɑːsl fjuːəl/",
    exampleSentence: "Fossil fuels still supply most of the world's energy.",
    exampleTranslationJa: "化石燃料はいまだ世界のエネルギーの大半をまかなう。",
    collocations: ["burn fossil fuels", "fossil fuel emissions", "dependence on fossil fuels"],
    mnemonic: "石炭・石油・天然ガス。大昔の生き物(fossil)からできた燃料。",
    relatedWords: ["coal", "oil", "renewable"],
  },
  {
    id: "sustainability",
    word: "sustainability",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["持続可能性"],
    pronunciation: "/səˌsteɪnəˈbɪləti/",
    exampleSentence: "The report measures the sustainability of the supply chain.",
    exampleTranslationJa: "その報告書は供給網の持続可能性を測っている。",
    collocations: ["environmental sustainability", "long-term sustainability"],
    wordFormation: "sustainable(持続可能な)+ -ity。",
    mnemonic: "sustain(支え続ける)から。将来も同じやり方を続けられるか。",
    relatedWords: ["sustainable", "environment", "renewable"],
  },
  {
    id: "recycling",
    word: "recycling",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["再生利用、リサイクル"],
    pronunciation: "/ˌriːˈsaɪklɪŋ/",
    exampleSentence: "Recycling rates have risen every year.",
    exampleTranslationJa: "リサイクル率は毎年上がっている。",
    collocations: ["a recycling bin", "recycling rates", "kerbside recycling"],
    wordFormation: "re-(再び)+ cycle(循環)+ -ing。",
    mnemonic: "re(再び)+ cycle(回す)。動詞は recycle。",
    relatedWords: ["recycle", "waste", "reuse"],
  },
  {
    id: "landfill",
    word: "landfill",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["埋め立て地、ごみ埋め立て"],
    pronunciation: "/ˈlændfɪl/",
    exampleSentence: "Most of the waste still goes to landfill.",
    exampleTranslationJa: "廃棄物の大半はいまだ埋め立てに回される。",
    collocations: ["go to landfill", "a landfill site", "reduce landfill"],
    wordFormation: "land(土地)+ fill(埋める)。",
    mnemonic: "冠詞なしで go to landfill と言うことが多い。",
    relatedWords: ["waste", "dump", "rubbish"],
  },
  {
    id: "shrine",
    word: "shrine",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["聖堂、神社、聖地"],
    pronunciation: "/ʃraɪn/",
    exampleSentence: "Pilgrims still visit the shrine every spring.",
    exampleTranslationJa: "巡礼者は今も毎春その聖地を訪れる。",
    collocations: ["visit a shrine", "a shrine to", "a roadside shrine"],
    mnemonic: "聖なるものをまつる場所。人を敬う「記念の場」にも使う(a shrine to his memory)。",
    relatedWords: ["temple", "altar", "sacred"],
  },
  {
    id: "monastery",
    word: "monastery",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["修道院"],
    pronunciation: "/ˈmɑːnəsteri/",
    exampleSentence: "The monastery has stood on the hill for 900 years.",
    exampleTranslationJa: "その修道院は900年間その丘に立っている。",
    collocations: ["a Buddhist monastery", "live in a monastery"],
    wordFormation: "ギリシャ語 monos(ひとり)から。",
    mnemonic: "monos(ひとり)が語根。俗世を離れて暮らす場所。女子は convent。",
    relatedWords: ["convent", "monk", "abbey"],
  },
  {
    id: "cathedral",
    word: "cathedral",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["大聖堂"],
    pronunciation: "/kəˈθiːdrəl/",
    exampleSentence: "The cathedral took two centuries to build.",
    exampleTranslationJa: "その大聖堂は建てるのに2世紀かかった。",
    collocations: ["a Gothic cathedral", "the cathedral spire"],
    wordFormation: "ギリシャ語 kathedra(座)から。司教の座がある教会。",
    mnemonic: "司教の「座(kathedra)」がある教会。だから church より格上。",
    relatedWords: ["church", "chapel", "basilica"],
  },
  {
    id: "chapel",
    word: "chapel",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["礼拝堂"],
    pronunciation: "/ˈtʃæpl/",
    exampleSentence: "There is a small chapel inside the hospital.",
    exampleTranslationJa: "病院の中に小さな礼拝堂がある。",
    collocations: ["a private chapel", "a wedding chapel"],
    mnemonic: "教会より小さい、施設内などの礼拝の部屋。",
    relatedWords: ["church", "cathedral", "prayer"],
  },
  {
    id: "altar",
    word: "altar",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["祭壇"],
    pronunciation: "/ˈɔːltər/",
    exampleSentence: "Flowers were placed on the altar.",
    exampleTranslationJa: "祭壇に花が供えられた。",
    collocations: ["at the altar", "before the altar", "the high altar"],
    mnemonic: "alter(変える)と同音。leave someone at the altar は「結婚式で置き去りにする」。",
    relatedWords: ["shrine", "church", "sacrifice"],
  },
  {
    id: "pilgrimage",
    word: "pilgrimage",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["巡礼、聖地への旅"],
    pronunciation: "/ˈpɪlɡrɪmɪdʒ/",
    exampleSentence: "She made a pilgrimage to her grandfather's village.",
    exampleTranslationJa: "彼女は祖父の村への巡礼の旅をした。",
    collocations: ["make a pilgrimage", "a pilgrimage to", "an annual pilgrimage"],
    wordFormation: "pilgrim(巡礼者)+ -age。",
    mnemonic: "宗教の巡礼から、思い入れのある場所への旅一般へ。",
    relatedWords: ["pilgrim", "journey", "shrine"],
  },
  {
    id: "folklore",
    word: "folklore",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["民間伝承"],
    pronunciation: "/ˈfoʊklɔːr/",
    exampleSentence: "The story survives in local folklore.",
    exampleTranslationJa: "その話は土地の民間伝承として残っている。",
    collocations: ["local folklore", "part of folklore", "in folklore"],
    wordFormation: "folk(民衆)+ lore(言い伝え)。",
    mnemonic: "folk(民衆)の lore(言い伝え)。書き残されず口で伝わったもの。",
    relatedWords: ["legend", "myth", "tradition"],
  },
  {
    id: "superstition",
    word: "superstition",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["迷信"],
    pronunciation: "/ˌsuːpərˈstɪʃn/",
    exampleSentence: "Walking under a ladder is bad luck, according to superstition.",
    exampleTranslationJa: "迷信では、はしごの下を通るのは不吉だ。",
    collocations: ["an old superstition", "according to superstition"],
    mnemonic: "根拠なく信じられている言い伝え。形容詞は superstitious。",
    relatedWords: ["myth", "belief", "luck"],
  },
  {
    id: "prophecy",
    word: "prophecy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["予言"],
    pronunciation: "/ˈprɑːfəsi/",
    exampleSentence: "The prophecy turned out to be wrong.",
    exampleTranslationJa: "その予言は外れた。",
    collocations: ["fulfil a prophecy", "a self-fulfilling prophecy"],
    mnemonic: "名詞は prophecy /-si/、動詞は prophesy /-saɪ/。つづりと音が違う。",
    relatedWords: ["prediction", "prophet", "forecast"],
  },
  {
    id: "scripture",
    word: "scripture",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["聖典、聖書"],
    pronunciation: "/ˈskrɪptʃər/",
    exampleSentence: "He quoted from scripture at the funeral.",
    exampleTranslationJa: "彼は葬儀で聖典から引用した。",
    collocations: ["holy scripture", "quote from scripture"],
    wordFormation: "ラテン語 scribere(書く)から。",
    mnemonic: "script・describe と同語根。「書かれたもの」の中でも神聖なもの。",
    relatedWords: ["bible", "text", "holy"],
  },
  {
    id: "sermon",
    word: "sermon",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["説教"],
    pronunciation: "/ˈsɜːrmən/",
    exampleSentence: "The sermon lasted twenty minutes.",
    exampleTranslationJa: "その説教は20分続いた。",
    collocations: ["give a sermon", "preach a sermon", "a long sermon"],
    mnemonic: "教会の説教から、長い小言の比喩へ。",
    relatedWords: ["preach", "lecture", "speech"],
  },
  {
    id: "monarchy",
    word: "monarchy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["君主制、王室"],
    pronunciation: "/ˈmɑːnərki/",
    exampleSentence: "The country abolished the monarchy in 1946.",
    exampleTranslationJa: "その国は1946年に君主制を廃止した。",
    collocations: ["a constitutional monarchy", "abolish the monarchy"],
    wordFormation: "mono-(ひとり)+ arch(支配)。",
    mnemonic: "mono(一人)+ arch(支配)。anarchy(無政府)と同じ arch。",
    relatedWords: ["monarch", "king", "republic"],
  },
  {
    id: "dynasty",
    word: "dynasty",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["王朝、一族の支配"],
    pronunciation: "/ˈdaɪnəsti/",
    exampleSentence: "The dynasty ruled for four hundred years.",
    exampleTranslationJa: "その王朝は400年間統治した。",
    collocations: ["found a dynasty", "the Ming dynasty", "a political dynasty"],
    mnemonic: "血筋で続く支配。政治家一家や企業一族にも使う。",
    relatedWords: ["family", "empire", "reign"],
  },
  {
    id: "conquest",
    word: "conquest",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["征服"],
    pronunciation: "/ˈkɑːŋkwest/",
    exampleSentence: "The conquest changed the language of the island.",
    exampleTranslationJa: "その征服はその島の言語を変えた。",
    collocations: ["the Norman Conquest", "the conquest of space"],
    wordFormation: "conquer(征服する)+ -est。",
    mnemonic: "動詞は conquer。宇宙や病気の「克服」にも使う。",
    relatedWords: ["conquer", "invasion", "victory"],
  },
  {
    id: "revolt",
    word: "revolt",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["反乱", "反抗する"],
    pronunciation: "/rɪˈvoʊlt/",
    exampleSentence: "Farmers revolt when the tax rises again.",
    exampleTranslationJa: "税がまた上がると農民は反乱を起こす。",
    collocations: ["a peasant revolt", "revolt against", "spark a revolt"],
    wordFormation: "re-(反対に)+ volvere(回る)。revolution と同語根。",
    mnemonic: "revolution と同語根。より小規模で自然発生的なのが revolt。",
    relatedWords: ["rebellion", "uprising", "revolution"],
  },
  {
    id: "siege",
    word: "siege",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["包囲、攻囲"],
    pronunciation: "/siːdʒ/",
    exampleSentence: "The city was under siege for six months.",
    exampleTranslationJa: "その都市は6か月間包囲されていた。",
    collocations: ["under siege", "lay siege to", "lift the siege"],
    wordFormation: "ラテン語 sedere(座る)から。「座り込む」。",
    mnemonic: "sedere(座る)が語根。城の前に居座って攻めること。",
    relatedWords: ["blockade", "surround", "attack"],
  },
  {
    id: "feudal",
    word: "feudal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["封建の、封建的な"],
    pronunciation: "/ˈfjuːdl/",
    exampleSentence: "The feudal system tied peasants to the land.",
    exampleTranslationJa: "封建制は農民を土地に縛りつけた。",
    collocations: ["the feudal system", "feudal lords", "a feudal society"],
    mnemonic: "中世の土地と忠誠の仕組み。今は「時代遅れで上下の厳しい」の比喩にも。",
    relatedWords: ["medieval", "lord", "hierarchy"],
  },
  {
    id: "archaeology",
    word: "archaeology",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["考古学"],
    pronunciation: "/ˌɑːrkiˈɑːlədʒi/",
    exampleSentence: "She studied archaeology at university.",
    exampleTranslationJa: "彼女は大学で考古学を学んだ。",
    collocations: ["study archaeology", "industrial archaeology"],
    wordFormation: "archaeo-(古い)+ -logy(学問)。",
    mnemonic: "米つづりは archeology も可。遺物から過去を読む学問。",
    relatedWords: ["excavation", "artefact", "history"],
  },
  {
    id: "excavation",
    word: "excavation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["発掘、掘削"],
    pronunciation: "/ˌekskəˈveɪʃn/",
    exampleSentence: "The excavation uncovered a Roman floor.",
    exampleTranslationJa: "その発掘でローマ時代の床が現れた。",
    collocations: ["an archaeological excavation", "begin excavation"],
    wordFormation: "ex-(外へ)+ cavus(穴)。cave と同語根。",
    mnemonic: "cave(洞窟)と同語根。掘って外に出すこと。動詞は excavate。",
    relatedWords: ["dig", "archaeology", "site"],
  },
  {
    id: "artefact",
    word: "artefact",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["人工遺物、出土品"],
    pronunciation: "/ˈɑːrtɪfækt/",
    exampleSentence: "The museum holds artefacts from the Bronze Age.",
    exampleTranslationJa: "その博物館は青銅器時代の遺物を所蔵している。",
    collocations: ["ancient artefacts", "a cultural artefact"],
    wordFormation: "art(技)+ fact(作られたもの)。",
    mnemonic: "米つづりは artifact。人の手で作られた物、という意味が語源そのまま。",
    relatedWords: ["relic", "object", "archaeology"],
  },
  {
    id: "relic",
    word: "relic",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["遺物、名残"],
    pronunciation: "/ˈrelɪk/",
    exampleSentence: "The law is a relic of the colonial period.",
    exampleTranslationJa: "その法律は植民地時代の名残だ。",
    collocations: ["a relic of the past", "holy relics"],
    wordFormation: "ラテン語 relinquere(残す)から。relinquish と同語根。",
    mnemonic: "relinquish(手放す)と同語根。「あとに残されたもの」。",
    relatedWords: ["remains", "artefact", "survival"],
  },
  {
    id: "ruins",
    word: "ruins",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["廃虚、遺跡"],
    pronunciation: "/ˈruːɪnz/",
    exampleSentence: "We walked around the ruins of the castle.",
    exampleTranslationJa: "私たちは城の廃虚を歩いて回った。",
    collocations: ["ancient ruins", "the ruins of", "lie in ruins"],
    mnemonic: "遺跡の意味では必ず複数形。lie in ruins は「荒廃している」。",
    relatedWords: ["remains", "wreck", "ruin"],
  },
  {
    id: "descendant",
    word: "descendant",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["子孫"],
    pronunciation: "/dɪˈsendənt/",
    exampleSentence: "She is a descendant of the first settlers.",
    exampleTranslationJa: "彼女は最初の入植者の子孫だ。",
    collocations: ["a direct descendant", "descendants of"],
    wordFormation: "descend(下る)+ -ant(人)。",
    mnemonic: "血筋を下って(descend)きた人。反対は ancestor(祖先)。",
    relatedWords: ["ancestor", "offspring", "heir"],
  },
  {
    id: "umpire",
    word: "umpire",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["審判(テニス・野球など)"],
    pronunciation: "/ˈʌmpaɪər/",
    exampleSentence: "The umpire overruled the line judge.",
    exampleTranslationJa: "主審は線審の判定を覆した。",
    collocations: ["the umpire's decision", "a tennis umpire"],
    mnemonic: "サッカーやラグビーは referee、テニスや野球は umpire。",
    relatedWords: ["referee", "judge", "official"],
  },
  {
    id: "qualifier",
    word: "qualifier",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["予選(試合)", "限定する語句"],
    pronunciation: "/ˈkwɑːlɪfaɪər/",
    exampleSentence: "They lost the qualifier and missed the finals.",
    exampleTranslationJa: "彼らは予選で敗れ、決勝を逃した。",
    collocations: ["a World Cup qualifier", "win the qualifier"],
    wordFormation: "qualify(資格を得る)+ -er。",
    mnemonic: "本戦に出る資格(qualify)を争う試合。文法では「限定語」。",
    relatedWords: ["qualify", "preliminary", "heat"],
  },
  {
    id: "draw",
    word: "draw",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["引き分け", "抽選"],
    pronunciation: "/drɔː/",
    exampleSentence: "The match ended in a goalless draw.",
    exampleTranslationJa: "その試合は0対0の引き分けに終わった。",
    collocations: ["end in a draw", "a goalless draw", "the draw for the cup"],
    mnemonic: "動詞「描く・引く」と同じ語。試合の引き分けは英でよく使う(米は tie)。",
    relatedWords: ["tie", "match", "lottery"],
  },
]
