import type { VocabularyEntry } from '../types'

// 増補 第23弾。-less / -al / -ic の形容詞。
// 一字違いの別語(elemental と elementary、climatic と climactic、topical と typical、
// medicinal と medical、temporal と temporary)は覚えるヒントで区別する。
export const plus23: VocabularyEntry[] = [
  {
    id: "natural",
    word: "natural",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自然の、生まれつきの", "当然の"],
    pronunciation: "/ˈnætʃrəl/",
    exampleSentence: "It is natural to feel nervous before an exam.",
    exampleTranslationJa: "試験前に緊張するのは当然だ。",
    collocations: ["natural resources", "a natural talent", "it is natural to"],
    mnemonic: "nature の形容詞形。「自然界の」と「無理のない・当然の」の両方。",
    relatedWords: ["nature", "innate", "artificial"],
  },
  {
    id: "personal",
    word: "personal",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["個人の、私的な"],
    pronunciation: "/ˈpɜːrsənl/",
    exampleSentence: "Please do not share personal information.",
    exampleTranslationJa: "個人情報は共有しないでください。",
    collocations: ["personal details", "a personal opinion", "take it personally"],
    mnemonic: "person の形容詞形。personnel(職員)とはつづりもアクセントも違う。",
    relatedWords: ["private", "individual", "public"],
  },
  {
    id: "mindless",
    word: "mindless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["何も考えていない、無分別な"],
    pronunciation: "/ˈmaɪndləs/",
    exampleSentence: "It was mindless vandalism.",
    exampleTranslationJa: "それは無分別な破壊行為だった。",
    collocations: ["mindless violence", "mindless work"],
    mnemonic: "mind(考え)+ -less。単調で頭を使わない作業にも使う。",
    relatedWords: ["thoughtless", "senseless", "thoughtful"],
  },
  {
    id: "motionless",
    word: "motionless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["身動きしない"],
    pronunciation: "/ˈmoʊʃnləs/",
    exampleSentence: "The heron stood motionless in the water.",
    exampleTranslationJa: "サギは水の中で身動きせず立っていた。",
    collocations: ["stand motionless", "lie motionless"],
    mnemonic: "motion(動き)+ -less。still とほぼ同じだが、より完全な静止。",
    relatedWords: ["still", "static", "moving"],
  },
  {
    id: "nameless",
    word: "nameless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["名前のない、無名の"],
    pronunciation: "/ˈneɪmləs/",
    exampleSentence: "A nameless donor paid for the repairs.",
    exampleTranslationJa: "名を伏せた寄付者が修繕費を出した。",
    collocations: ["a nameless fear", "shall remain nameless"],
    mnemonic: "who shall remain nameless は「名前は伏せておくが」。",
    relatedWords: ["anonymous", "unnamed", "named"],
  },
  {
    id: "needless",
    word: "needless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不必要な"],
    pronunciation: "/ˈniːdləs/",
    exampleSentence: "Needless to say, they were furious.",
    exampleTranslationJa: "言うまでもなく、彼らは激怒していた。",
    collocations: ["needless to say", "needless suffering"],
    mnemonic: "Needless to say, ... は「言うまでもないが」という定型。",
    relatedWords: ["unnecessary", "pointless", "necessary"],
  },
  {
    id: "odourless",
    word: "odourless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["においのない"],
    pronunciation: "/ˈoʊdərləs/",
    exampleSentence: "The gas is colourless and odourless.",
    exampleTranslationJa: "そのガスは無色無臭だ。",
    collocations: ["colourless and odourless", "an odourless liquid"],
    mnemonic: "odour(におい)+ -less。米つづりは odorless。安全表示で頻出。",
    relatedWords: ["scentless", "unscented", "fragrant"],
  },
  {
    id: "painless",
    word: "painless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["痛みのない、楽な"],
    pronunciation: "/ˈpeɪnləs/",
    exampleSentence: "The procedure is quick and painless.",
    exampleTranslationJa: "その処置は早くて痛みがない。",
    collocations: ["quick and painless", "a painless process"],
    mnemonic: "手続きが「面倒でない」という比喩でもよく使う。",
    relatedWords: ["easy", "effortless", "painful"],
  },
  {
    id: "penniless",
    word: "penniless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無一文の"],
    pronunciation: "/ˈpenɪləs/",
    exampleSentence: "He arrived in the city penniless.",
    exampleTranslationJa: "彼は無一文でその街に着いた。",
    collocations: ["arrive penniless", "left penniless"],
    mnemonic: "penny(1ペニー)+ -less。1円も持たない、の意味。",
    relatedWords: ["broke", "destitute", "wealthy"],
  },
  {
    id: "pointless",
    word: "pointless",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["無意味な、むだな"],
    pronunciation: "/ˈpɔɪntləs/",
    exampleSentence: "Arguing further would be pointless.",
    exampleTranslationJa: "これ以上言い争ってもむだだ。",
    collocations: ["utterly pointless", "a pointless exercise"],
    mnemonic: "point(意味・要点)+ -less。futile のくだけた語。",
    relatedWords: ["futile", "useless", "worthwhile"],
  },
  {
    id: "powerless",
    word: "powerless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無力な、なすすべのない"],
    pronunciation: "/ˈpaʊərləs/",
    exampleSentence: "They felt powerless to stop it.",
    exampleTranslationJa: "彼らはそれを止める力がないと感じた。",
    collocations: ["powerless to do", "feel powerless"],
    mnemonic: "powerless to do の形で使う。政治的な無力さにも。",
    relatedWords: ["helpless", "impotent", "powerful"],
  },
  {
    id: "priceless",
    word: "priceless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["値がつけられないほど貴重な"],
    pronunciation: "/ˈpraɪsləs/",
    exampleSentence: "The collection is priceless.",
    exampleTranslationJa: "そのコレクションは値がつけられないほど貴重だ。",
    collocations: ["a priceless work of art", "priceless experience"],
    mnemonic: "「値段がない」ではなく「高すぎて値がつかない」。worthless が反対。",
    relatedWords: ["invaluable", "precious", "worthless"],
  },
  {
    id: "remorseless",
    word: "remorseless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["容赦のない、後悔のない"],
    pronunciation: "/rɪˈmɔːrsləs/",
    exampleSentence: "The pressure was remorseless.",
    exampleTranslationJa: "その圧力は容赦がなかった。",
    collocations: ["remorseless pressure", "a remorseless killer"],
    mnemonic: "remorse(後悔)+ -less。relentless に近い。",
    relatedWords: ["relentless", "merciless", "merciful"],
  },
  {
    id: "seamless",
    word: "seamless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["継ぎ目のない、滑らかにつながった"],
    pronunciation: "/ˈsiːmləs/",
    exampleSentence: "The transition was seamless.",
    exampleTranslationJa: "その移行はつなぎ目を感じさせなかった。",
    collocations: ["a seamless transition", "seamless integration"],
    mnemonic: "seam(縫い目)+ -less。IT やサービスの宣伝で頻出。",
    relatedWords: ["smooth", "continuous", "disjointed"],
  },
  {
    id: "senseless",
    word: "senseless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無意味な、正気を失った"],
    pronunciation: "/ˈsensləs/",
    exampleSentence: "It was a senseless act of violence.",
    exampleTranslationJa: "それは無意味な暴力行為だった。",
    collocations: ["senseless violence", "knocked senseless"],
    mnemonic: "sense(意味・意識)+ -less。「意識を失った」の意味もある。",
    relatedWords: ["pointless", "meaningless", "sensible"],
  },
  {
    id: "shameless",
    word: "shameless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恥知らずの"],
    pronunciation: "/ˈʃeɪmləs/",
    exampleSentence: "It was a shameless attempt to get attention.",
    exampleTranslationJa: "それは注目を集めようとする恥知らずな試みだった。",
    collocations: ["a shameless lie", "shameless self-promotion"],
    mnemonic: "shame(恥)+ -less。恥じるべきなのに恥じない、という非難。",
    relatedWords: ["brazen", "unashamed", "modest"],
  },
  {
    id: "sleepless",
    word: "sleepless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["眠れない"],
    pronunciation: "/ˈsliːpləs/",
    exampleSentence: "She spent a sleepless night worrying.",
    exampleTranslationJa: "彼女は心配して眠れない夜を過ごした。",
    collocations: ["a sleepless night", "lie sleepless"],
    mnemonic: "a sleepless night(眠れぬ夜)の形で使うことが多い。",
    relatedWords: ["wakeful", "restless", "restful"],
  },
  {
    id: "spotless",
    word: "spotless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ちりひとつない、しみのない"],
    pronunciation: "/ˈspɑːtləs/",
    exampleSentence: "The kitchen was spotless.",
    exampleTranslationJa: "その台所はちりひとつなかった。",
    collocations: ["spotless kitchen", "a spotless record"],
    mnemonic: "spot(しみ)+ -less。経歴が「傷ひとつない」意味にも。",
    relatedWords: ["immaculate", "clean", "filthy"],
  },
  {
    id: "stainless",
    word: "stainless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["さびない、しみのつかない"],
    pronunciation: "/ˈsteɪnləs/",
    exampleSentence: "The sink is made of stainless steel.",
    exampleTranslationJa: "その流しはステンレス製だ。",
    collocations: ["stainless steel", "a stainless reputation"],
    mnemonic: "stain(しみ・さび)+ -less。stainless steel でほぼ決まって使う。",
    relatedWords: ["rustproof", "clean", "stained"],
  },
  {
    id: "tasteless",
    word: "tasteless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["味のない", "下品な"],
    pronunciation: "/ˈteɪstləs/",
    exampleSentence: "The joke was tasteless.",
    exampleTranslationJa: "その冗談は下品だった。",
    collocations: ["a tasteless joke", "tasteless food"],
    mnemonic: "tasteful(品がよい)の反対。食べ物なら「味がしない」。",
    relatedWords: ["bland", "vulgar", "tasteful"],
  },
  {
    id: "thankless",
    word: "thankless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["感謝されない、報われない"],
    pronunciation: "/ˈθæŋkləs/",
    exampleSentence: "Cleaning up after everyone is a thankless task.",
    exampleTranslationJa: "みんなの後片づけは報われない仕事だ。",
    collocations: ["a thankless task", "thankless work"],
    mnemonic: "a thankless task(割に合わない仕事)の形で覚える。",
    relatedWords: ["unrewarding", "unappreciated", "rewarding"],
  },
  {
    id: "timeless",
    word: "timeless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["時代を超えた、古びない"],
    pronunciation: "/ˈtaɪmləs/",
    exampleSentence: "The design has a timeless quality.",
    exampleTranslationJa: "その意匠には古びない良さがある。",
    collocations: ["timeless appeal", "a timeless classic"],
    mnemonic: "time(時)+ -less。流行に左右されない良さ。",
    relatedWords: ["enduring", "classic", "dated"],
  },
  {
    id: "tireless",
    word: "tireless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["疲れを知らない、たゆまぬ"],
    pronunciation: "/ˈtaɪərləs/",
    exampleSentence: "She was a tireless campaigner for the cause.",
    exampleTranslationJa: "彼女はその運動のたゆまぬ活動家だった。",
    collocations: ["a tireless worker", "tireless efforts"],
    mnemonic: "tire(疲れる)+ -less。ほめ言葉として使う。",
    relatedWords: ["indefatigable", "persistent", "lazy"],
  },
  {
    id: "toothless",
    word: "toothless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["歯のない", "(制度が)実効性のない"],
    pronunciation: "/ˈtuːθləs/",
    exampleSentence: "Critics called the new law toothless.",
    exampleTranslationJa: "批判者たちはその新法を骨抜きだと呼んだ。",
    collocations: ["a toothless regulator", "toothless legislation"],
    mnemonic: "tooth + -less。制度に「かみつく力がない」という比喩が重要。",
    relatedWords: ["powerless", "ineffective", "effective"],
  },
  {
    id: "valueless",
    word: "valueless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["価値のない"],
    pronunciation: "/ˈvæljuːləs/",
    exampleSentence: "Without the certificate the item is valueless.",
    exampleTranslationJa: "証明書がなければその品は無価値だ。",
    collocations: ["practically valueless", "a valueless asset"],
    mnemonic: "invaluable(きわめて貴重)とは正反対。混同しやすい対。",
    relatedWords: ["worthless", "invaluable", "priceless"],
  },
  {
    id: "weightless",
    word: "weightless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無重力の、重さのない"],
    pronunciation: "/ˈweɪtləs/",
    exampleSentence: "Astronauts are weightless in orbit.",
    exampleTranslationJa: "宇宙飛行士は軌道上では無重力状態にある。",
    collocations: ["feel weightless", "weightless in space"],
    mnemonic: "weight(重さ)+ -less。宇宙飛行の文脈で使う。",
    relatedWords: ["floating", "light", "heavy"],
  },
  {
    id: "worthless",
    word: "worthless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["価値のない、役に立たない"],
    pronunciation: "/ˈwɜːrθləs/",
    exampleSentence: "The shares turned out to be worthless.",
    exampleTranslationJa: "その株は無価値だと分かった。",
    collocations: ["become worthless", "feel worthless"],
    mnemonic: "worth(価値)+ -less。人が「自分は無価値だ」と感じる意味も。",
    relatedWords: ["valueless", "useless", "priceless"],
  },
  {
    id: "accidental",
    word: "accidental",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["偶然の、事故による"],
    pronunciation: "/ˌæksɪˈdentl/",
    exampleSentence: "The discovery was entirely accidental.",
    exampleTranslationJa: "その発見はまったくの偶然だった。",
    collocations: ["accidental damage", "purely accidental"],
    mnemonic: "accident の形容詞形。deliberate(故意の)の反対。",
    relatedWords: ["unintentional", "chance", "deliberate"],
  },
  {
    id: "ceremonial",
    word: "ceremonial",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["儀式の、儀礼的な"],
    pronunciation: "/ˌserɪˈmoʊniəl/",
    exampleSentence: "The role is largely ceremonial.",
    exampleTranslationJa: "その役職はほぼ儀礼的なものだ。",
    collocations: ["a ceremonial role", "ceremonial dress"],
    mnemonic: "ceremony の形容詞形。実権のない「名誉職」を説明するときに使う。",
    relatedWords: ["ritual", "formal", "practical"],
  },
  {
    id: "consequential",
    word: "consequential",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["重大な", "結果として生じる"],
    pronunciation: "/ˌkɑːnsɪˈkwenʃl/",
    exampleSentence: "It was the most consequential decision of his career.",
    exampleTranslationJa: "それは彼の経歴で最も重大な決断だった。",
    collocations: ["a consequential decision", "consequential loss"],
    mnemonic: "consequence の形容詞形。inconsequential は「取るに足りない」。",
    relatedWords: ["significant", "important", "trivial"],
  },
  {
    id: "continental",
    word: "continental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["大陸の"],
    pronunciation: "/ˌkɑːntɪˈnentl/",
    exampleSentence: "Britain has a milder climate than continental Europe.",
    exampleTranslationJa: "英国は大陸ヨーロッパより温暖だ。",
    collocations: ["continental Europe", "a continental breakfast"],
    mnemonic: "continent の形容詞形。a continental breakfast は軽い朝食。",
    relatedWords: ["continent", "mainland", "insular"],
  },
  {
    id: "departmental",
    word: "departmental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["部門の、部署の"],
    pronunciation: "/ˌdiːpɑːrtˈmentl/",
    exampleSentence: "Departmental budgets were cut by ten per cent.",
    exampleTranslationJa: "部門予算は1割削減された。",
    collocations: ["a departmental meeting", "departmental budgets"],
    mnemonic: "department の形容詞形。組織図の話で使う。",
    relatedWords: ["department", "divisional", "organisational"],
  },
  {
    id: "developmental",
    word: "developmental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["発達の、開発段階の"],
    pronunciation: "/dɪˌveləpˈmentl/",
    exampleSentence: "The delay is a developmental issue.",
    exampleTranslationJa: "その遅れは発達上の問題だ。",
    collocations: ["developmental stages", "a developmental disorder"],
    mnemonic: "development の形容詞形。子どもの発達と、製品の開発段階の両方。",
    relatedWords: ["development", "formative", "growth"],
  },
  {
    id: "dimensional",
    word: "dimensional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["次元の"],
    pronunciation: "/dɪˈmenʃənl/",
    exampleSentence: "The scanner produces three-dimensional images.",
    exampleTranslationJa: "そのスキャナーは三次元の画像を作る。",
    collocations: ["three-dimensional", "two-dimensional"],
    mnemonic: "dimension の形容詞形。three-dimensional(3D)の形でほぼ使う。",
    relatedWords: ["dimension", "spatial", "flat"],
  },
  {
    id: "elemental",
    word: "elemental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["根源的な、自然の力の"],
    pronunciation: "/ˌelɪˈmentl/",
    exampleSentence: "There is an elemental force to the storm.",
    exampleTranslationJa: "その嵐には根源的な力がある。",
    collocations: ["elemental forces", "an elemental fear"],
    mnemonic: "element の形容詞形。elementary(初歩の)とは別語なので注意。",
    relatedWords: ["basic", "primal", "elementary"],
  },
  {
    id: "factual",
    word: "factual",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["事実に基づく"],
    pronunciation: "/ˈfæktʃuəl/",
    exampleSentence: "The account is factual, not fictional.",
    exampleTranslationJa: "その記述は作り話ではなく事実に基づく。",
    collocations: ["factual accuracy", "a factual error"],
    mnemonic: "fact の形容詞形。fictional(虚構の)の反対。",
    relatedWords: ["fact", "accurate", "fictional"],
  },
  {
    id: "fictional",
    word: "fictional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["架空の、小説の"],
    pronunciation: "/ˈfɪkʃənl/",
    exampleSentence: "The town is fictional but feels real.",
    exampleTranslationJa: "その町は架空だが実在するように感じられる。",
    collocations: ["a fictional character", "a fictional account"],
    mnemonic: "fiction の形容詞形。fictitious(でっち上げの)とはニュアンスが違う。",
    relatedWords: ["imaginary", "invented", "factual"],
  },
  {
    id: "governmental",
    word: "governmental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["政府の"],
    pronunciation: "/ˌɡʌvərnˈmentl/",
    exampleSentence: "The report criticises governmental inaction.",
    exampleTranslationJa: "その報告は政府の不作為を批判している。",
    collocations: ["governmental policy", "non-governmental organisation"],
    mnemonic: "government の形容詞形。NGO は non-governmental organisation。",
    relatedWords: ["government", "official", "state"],
  },
  {
    id: "grammatical",
    word: "grammatical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["文法の、文法にかなった"],
    pronunciation: "/ɡrəˈmætɪkl/",
    exampleSentence: "The sentence is grammatical but odd.",
    exampleTranslationJa: "その文は文法的には正しいが妙だ。",
    collocations: ["a grammatical error", "grammatically correct"],
    mnemonic: "grammar の形容詞形。a が一つ増えるつづりに注意。",
    relatedWords: ["grammar", "syntactic", "ungrammatical"],
  },
  {
    id: "habitual",
    word: "habitual",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["習慣的な、常習の"],
    pronunciation: "/həˈbɪtʃuəl/",
    exampleSentence: "He is a habitual latecomer.",
    exampleTranslationJa: "彼は常習的な遅刻者だ。",
    collocations: ["a habitual offender", "habitual behaviour"],
    mnemonic: "habit の形容詞形。悪い習慣について言うことが多い。",
    relatedWords: ["habit", "customary", "occasional"],
  },
  {
    id: "horizontal",
    word: "horizontal",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["水平の"],
    pronunciation: "/ˌhɔːrɪˈzɑːntl/",
    exampleSentence: "Draw a horizontal line across the page.",
    exampleTranslationJa: "ページに横線を一本引きなさい。",
    collocations: ["a horizontal line", "horizontal integration"],
    mnemonic: "horizon(地平線)の形容詞形。vertical(垂直の)の反対。",
    relatedWords: ["horizon", "level", "vertical"],
  },
  {
    id: "hypothetical",
    word: "hypothetical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["仮定の"],
    pronunciation: "/ˌhaɪpəˈθetɪkl/",
    exampleSentence: "Let us take a hypothetical example.",
    exampleTranslationJa: "仮の例を取り上げてみましょう。",
    collocations: ["a hypothetical situation", "purely hypothetical"],
    mnemonic: "hypothesis の形容詞形。「実際にはないが、もしあれば」の話。",
    relatedWords: ["hypothesis", "theoretical", "actual"],
  },
  {
    id: "imperial",
    word: "imperial",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["帝国の", "(度量衡が)ヤードポンド法の"],
    pronunciation: "/ɪmˈpɪriəl/",
    exampleSentence: "The imperial system uses feet and pounds.",
    exampleTranslationJa: "ヤードポンド法はフィートとポンドを使う。",
    collocations: ["imperial rule", "imperial measurements"],
    mnemonic: "empire の形容詞形。英国の度量衡単位も imperial units。",
    relatedWords: ["empire", "royal", "metric"],
  },
  {
    id: "impersonal",
    word: "impersonal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よそよそしい、人間味のない"],
    pronunciation: "/ɪmˈpɜːrsənl/",
    exampleSentence: "The reply was polite but impersonal.",
    exampleTranslationJa: "その返事は丁寧だが人間味がなかった。",
    collocations: ["an impersonal style", "cold and impersonal"],
    mnemonic: "personal の否定。事務的で温かみがないこと。",
    relatedWords: ["detached", "cold", "personal"],
  },
  {
    id: "intentional",
    word: "intentional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["意図的な、故意の"],
    pronunciation: "/ɪnˈtenʃənl/",
    exampleSentence: "The omission was not intentional.",
    exampleTranslationJa: "その抜け落ちは故意ではなかった。",
    collocations: ["intentional harm", "not intentional"],
    mnemonic: "intention の形容詞形。deliberate とほぼ同じ。",
    relatedWords: ["deliberate", "planned", "accidental"],
  },
  {
    id: "maternal",
    word: "maternal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["母の、母方の"],
    pronunciation: "/məˈtɜːrnl/",
    exampleSentence: "She has strong maternal instincts.",
    exampleTranslationJa: "彼女は強い母性本能を持っている。",
    collocations: ["maternal instinct", "maternal grandmother", "maternity leave"],
    mnemonic: "mater(母)が語根。母方の祖母は maternal grandmother。",
    relatedWords: ["mother", "motherly", "paternal"],
  },
  {
    id: "medicinal",
    word: "medicinal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["薬効のある、薬用の"],
    pronunciation: "/məˈdɪsɪnl/",
    exampleSentence: "The plant has medicinal properties.",
    exampleTranslationJa: "その植物には薬効がある。",
    collocations: ["medicinal properties", "for medicinal purposes"],
    mnemonic: "medicine の形容詞形。medical(医学の)とは別語。",
    relatedWords: ["medicine", "therapeutic", "medical"],
  },
  {
    id: "monumental",
    word: "monumental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["記念碑的な、途方もない"],
    pronunciation: "/ˌmɑːnjuˈmentl/",
    exampleSentence: "It was a monumental achievement.",
    exampleTranslationJa: "それは記念碑的な業績だった。",
    collocations: ["a monumental task", "a monumental error"],
    mnemonic: "monument の形容詞形。よいことにも悪いことにも「けた外れの」。",
    relatedWords: ["monument", "enormous", "trivial"],
  },
  {
    id: "nutritional",
    word: "nutritional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["栄養の"],
    pronunciation: "/nuˈtrɪʃənl/",
    exampleSentence: "Check the nutritional information on the label.",
    exampleTranslationJa: "ラベルの栄養情報を確認してください。",
    collocations: ["nutritional value", "nutritional information"],
    mnemonic: "nutrition の形容詞形。食品表示の定番語。",
    relatedWords: ["nutrition", "dietary", "nourishing"],
  },
  {
    id: "optional",
    word: "optional",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["任意の、自由選択の"],
    pronunciation: "/ˈɑːpʃənl/",
    exampleSentence: "Attendance is optional.",
    exampleTranslationJa: "出席は任意です。",
    collocations: ["optional extras", "strictly optional"],
    mnemonic: "option の形容詞形。compulsory / mandatory の反対。",
    relatedWords: ["option", "voluntary", "compulsory"],
  },
  {
    id: "ornamental",
    word: "ornamental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["装飾用の"],
    pronunciation: "/ˌɔːrnəˈmentl/",
    exampleSentence: "The pond is purely ornamental.",
    exampleTranslationJa: "その池はもっぱら装飾用だ。",
    collocations: ["ornamental plants", "purely ornamental"],
    mnemonic: "ornament(飾り)の形容詞形。実用でなく見た目のためのもの。",
    relatedWords: ["decorative", "ornament", "functional"],
  },
  {
    id: "paternal",
    word: "paternal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["父の、父方の"],
    pronunciation: "/pəˈtɜːrnl/",
    exampleSentence: "He took paternal leave for six months.",
    exampleTranslationJa: "彼は6か月の育児休業を取った。",
    collocations: ["paternal grandfather", "paternal instinct"],
    mnemonic: "pater(父)が語根。maternal(母の)と対。patriot と同語根。",
    relatedWords: ["father", "fatherly", "maternal"],
  },
  {
    id: "pivotal",
    word: "pivotal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["きわめて重要な、要となる"],
    pronunciation: "/ˈpɪvətl/",
    exampleSentence: "She played a pivotal role in the reform.",
    exampleTranslationJa: "彼女はその改革で要となる役割を果たした。",
    collocations: ["a pivotal role", "a pivotal moment"],
    mnemonic: "pivot(回転の軸)の形容詞形。そこを軸に全体が動く点。",
    relatedWords: ["crucial", "central", "minor"],
  },
  {
    id: "seasonal",
    word: "seasonal",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["季節の、季節限定の"],
    pronunciation: "/ˈsiːzənl/",
    exampleSentence: "The work is seasonal and ends in October.",
    exampleTranslationJa: "その仕事は季節労働で10月に終わる。",
    collocations: ["seasonal work", "seasonal variation"],
    mnemonic: "season の形容詞形。seasoned(味つけした・熟練した)とは別語。",
    relatedWords: ["season", "periodic", "permanent"],
  },
  {
    id: "sensational",
    word: "sensational",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["扇情的な", "すばらしい"],
    pronunciation: "/senˈseɪʃənl/",
    exampleSentence: "The paper gave the story a sensational headline.",
    exampleTranslationJa: "その新聞はその記事に扇情的な見出しをつけた。",
    collocations: ["sensational headlines", "absolutely sensational"],
    mnemonic: "sensation の形容詞形。報道では「あおる」、口語では「最高の」。",
    relatedWords: ["sensation", "dramatic", "understated"],
  },
  {
    id: "sequential",
    word: "sequential",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["連続した、順を追った"],
    pronunciation: "/sɪˈkwenʃl/",
    exampleSentence: "The chapters are in sequential order.",
    exampleTranslationJa: "その章は順を追って並んでいる。",
    collocations: ["sequential order", "sequential numbering"],
    mnemonic: "sequence の形容詞形。決まった順に並んでいること。",
    relatedWords: ["sequence", "consecutive", "random"],
  },
  {
    id: "situational",
    word: "situational",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["状況による"],
    pronunciation: "/ˌsɪtʃuˈeɪʃənl/",
    exampleSentence: "The rule is situational, not absolute.",
    exampleTranslationJa: "その規則は状況次第で、絶対ではない。",
    collocations: ["situational awareness", "situational factors"],
    mnemonic: "situation の形容詞形。situational awareness は「周囲の状況把握」。",
    relatedWords: ["situation", "contextual", "absolute"],
  },
  {
    id: "spatial",
    word: "spatial",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["空間の"],
    pronunciation: "/ˈspeɪʃl/",
    exampleSentence: "Children develop spatial awareness through play.",
    exampleTranslationJa: "子どもは遊びを通して空間認識を育てる。",
    collocations: ["spatial awareness", "spatial relationships"],
    mnemonic: "space の形容詞形だがつづりが大きく変わる。発音は /ˈspeɪʃl/。",
    relatedWords: ["space", "dimensional", "temporal"],
  },
  {
    id: "supplemental",
    word: "supplemental",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["補足の、追加の"],
    pronunciation: "/ˌsʌplɪˈmentl/",
    exampleSentence: "Supplemental funding was approved.",
    exampleTranslationJa: "追加の資金が承認された。",
    collocations: ["supplemental income", "supplemental materials"],
    mnemonic: "supplement の形容詞形。英では supplementary が普通。",
    relatedWords: ["supplementary", "additional", "primary"],
  },
  {
    id: "temporal",
    word: "temporal",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["時間の", "世俗の"],
    pronunciation: "/ˈtempərəl/",
    exampleSentence: "The study looks at temporal patterns.",
    exampleTranslationJa: "その研究は時間的な傾向を見ている。",
    collocations: ["temporal patterns", "spatial and temporal"],
    mnemonic: "tempus(時)が語根。temporary(一時的な)とは別語。",
    relatedWords: ["time", "chronological", "spatial"],
  },
  {
    id: "territorial",
    word: "territorial",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["領土の", "縄張り意識の強い"],
    pronunciation: "/ˌterəˈtɔːriəl/",
    exampleSentence: "The dispute is territorial.",
    exampleTranslationJa: "その紛争は領土をめぐるものだ。",
    collocations: ["territorial waters", "a territorial dispute", "territorial behaviour"],
    mnemonic: "territory の形容詞形。動物や人の「縄張り意識」にも使う。",
    relatedWords: ["territory", "regional", "possessive"],
  },
  {
    id: "topical",
    word: "topical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["時事的な、今話題の"],
    pronunciation: "/ˈtɑːpɪkl/",
    exampleSentence: "The debate covered several topical issues.",
    exampleTranslationJa: "その討論はいくつかの時事的な問題を扱った。",
    collocations: ["a topical issue", "topical humour"],
    mnemonic: "topic の形容詞形。「今まさに話題の」という意味で、typical と混同注意。",
    relatedWords: ["topic", "current", "outdated"],
  },
  {
    id: "transitional",
    word: "transitional",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["移行期の、過渡的な"],
    pronunciation: "/trænˈzɪʃənl/",
    exampleSentence: "This is a transitional arrangement.",
    exampleTranslationJa: "これは移行期の取り決めだ。",
    collocations: ["a transitional period", "a transitional government"],
    mnemonic: "transition の形容詞形。次の形が決まるまでの一時的な状態。",
    relatedWords: ["transition", "interim", "permanent"],
  },
  {
    id: "vocational",
    word: "vocational",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["職業訓練の"],
    pronunciation: "/voʊˈkeɪʃənl/",
    exampleSentence: "He took a vocational course in plumbing.",
    exampleTranslationJa: "彼は配管の職業訓練課程を受けた。",
    collocations: ["vocational training", "a vocational qualification"],
    mnemonic: "vocation(天職)の形容詞形。学問より実務に直結した教育。",
    relatedWords: ["vocation", "professional", "academic"],
  },
  {
    id: "acidic",
    word: "acidic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["酸性の", "(口調が)辛らつな"],
    pronunciation: "/əˈsɪdɪk/",
    exampleSentence: "The soil here is too acidic for roses.",
    exampleTranslationJa: "ここの土はバラには酸性が強すぎる。",
    collocations: ["acidic soil", "highly acidic"],
    mnemonic: "acid(酸)の形容詞形。反対は alkaline(アルカリ性の)。",
    relatedWords: ["acid", "sour", "alkaline"],
  },
  {
    id: "aerobic",
    word: "aerobic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有酸素の"],
    pronunciation: "/eˈroʊbɪk/",
    exampleSentence: "Aerobic exercise strengthens the heart.",
    exampleTranslationJa: "有酸素運動は心臓を強くする。",
    collocations: ["aerobic exercise", "aerobic capacity"],
    mnemonic: "aero-(空気)+ bio(生命)。酸素を使う運動。反対は anaerobic。",
    relatedWords: ["oxygen", "exercise", "anaerobic"],
  },
  {
    id: "analytic",
    word: "analytic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["分析的な"],
    pronunciation: "/ˌænəˈlɪtɪk/",
    exampleSentence: "She has a highly analytic mind.",
    exampleTranslationJa: "彼女はきわめて分析的な頭脳を持つ。",
    collocations: ["an analytic approach", "analytic skills"],
    mnemonic: "analysis の形容詞形。analytical とも書き、意味はほぼ同じ。",
    relatedWords: ["analytical", "logical", "intuitive"],
  },
  {
    id: "apologetic",
    word: "apologetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["申し訳なさそうな"],
    pronunciation: "/əˌpɑːləˈdʒetɪk/",
    exampleSentence: "He sent an apologetic email.",
    exampleTranslationJa: "彼は申し訳なさそうなメールを送ってきた。",
    collocations: ["an apologetic smile", "sound apologetic"],
    mnemonic: "apology の形容詞形。謝る態度がにじんでいること。",
    relatedWords: ["sorry", "regretful", "unrepentant"],
  },
  {
    id: "athletic",
    word: "athletic",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["運動の得意な、たくましい"],
    pronunciation: "/æθˈletɪk/",
    exampleSentence: "He has an athletic build.",
    exampleTranslationJa: "彼はたくましい体つきをしている。",
    collocations: ["an athletic build", "athletic ability"],
    mnemonic: "athlete の形容詞形。体格にも能力にも使う。",
    relatedWords: ["athlete", "sporty", "unfit"],
  },
  {
    id: "catastrophic",
    word: "catastrophic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["壊滅的な"],
    pronunciation: "/ˌkætəˈstrɑːfɪk/",
    exampleSentence: "The failure had catastrophic consequences.",
    exampleTranslationJa: "その失敗は壊滅的な結果を招いた。",
    collocations: ["catastrophic failure", "catastrophic damage"],
    mnemonic: "catastrophe(大惨事)の形容詞形。disastrous より強い。",
    relatedWords: ["catastrophe", "disastrous", "minor"],
  },
  {
    id: "chaotic",
    word: "chaotic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["混沌とした、大混乱の"],
    pronunciation: "/keɪˈɑːtɪk/",
    exampleSentence: "The first day was chaotic.",
    exampleTranslationJa: "初日は大混乱だった。",
    collocations: ["chaotic scenes", "a chaotic situation"],
    mnemonic: "chaos の形容詞形。ch を /k/ と読む。",
    relatedWords: ["chaos", "disorderly", "orderly"],
  },
  {
    id: "climatic",
    word: "climatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["気候の"],
    pronunciation: "/klaɪˈmætɪk/",
    exampleSentence: "Climatic conditions vary widely.",
    exampleTranslationJa: "気候条件は大きく異なる。",
    collocations: ["climatic conditions", "climatic change"],
    mnemonic: "climate の形容詞形。climactic(クライマックスの)と一字違いで別語。",
    relatedWords: ["climate", "weather", "climactic"],
  },
  {
    id: "cosmetic",
    word: "cosmetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["化粧の", "うわべだけの"],
    pronunciation: "/kɑːzˈmetɪk/",
    exampleSentence: "The changes were purely cosmetic.",
    exampleTranslationJa: "その変更はうわべだけのものだった。",
    collocations: ["cosmetic surgery", "purely cosmetic", "cosmetic changes"],
    mnemonic: "化粧品の意味から、「見た目だけ直す」という批判へ。",
    relatedWords: ["superficial", "surface", "substantial"],
  },
  {
    id: "cryptic",
    word: "cryptic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["謎めいた、分かりにくい"],
    pronunciation: "/ˈkrɪptɪk/",
    exampleSentence: "He left a cryptic message.",
    exampleTranslationJa: "彼は謎めいた伝言を残した。",
    collocations: ["a cryptic remark", "a cryptic crossword"],
    mnemonic: "crypt(隠された)が語根。encryption と同語根。",
    relatedWords: ["mysterious", "obscure", "clear"],
  },
  {
    id: "diagnostic",
    word: "diagnostic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["診断の"],
    pronunciation: "/ˌdaɪəɡˈnɑːstɪk/",
    exampleSentence: "The clinic runs diagnostic tests.",
    exampleTranslationJa: "その診療所は診断検査を行う。",
    collocations: ["a diagnostic test", "diagnostic tools"],
    mnemonic: "diagnosis の形容詞形。機械の「故障診断」にも使う。",
    relatedWords: ["diagnosis", "analytical", "test"],
  },
  {
    id: "elastic",
    word: "elastic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["伸縮する、融通のきく"],
    pronunciation: "/ɪˈlæstɪk/",
    exampleSentence: "The rules are more elastic than they look.",
    exampleTranslationJa: "その規則は見た目より融通がきく。",
    collocations: ["an elastic band", "elastic demand"],
    mnemonic: "物の伸縮から、規則や需要の「柔軟さ」へ。輪ゴムは an elastic band。",
    relatedWords: ["flexible", "stretchy", "rigid"],
  },
  {
    id: "emphatic",
    word: "emphatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["断固とした、強調した"],
    pronunciation: "/ɪmˈfætɪk/",
    exampleSentence: "She was emphatic that she had not agreed.",
    exampleTranslationJa: "彼女は同意していないと強く言った。",
    collocations: ["an emphatic denial", "an emphatic win"],
    mnemonic: "emphasis の形容詞形。「はっきり強く」示すこと。",
    relatedWords: ["emphasis", "forceful", "tentative"],
  },
  {
    id: "energetic",
    word: "energetic",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["精力的な、活発な"],
    pronunciation: "/ˌenərˈdʒetɪk/",
    exampleSentence: "She is energetic despite her age.",
    exampleTranslationJa: "彼女は年のわりに精力的だ。",
    collocations: ["an energetic approach", "highly energetic"],
    mnemonic: "energy の形容詞形。動きが活発なこと。",
    relatedWords: ["energy", "lively", "lethargic"],
  },
  {
    id: "fantastic",
    word: "fantastic",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["すばらしい", "空想的な"],
    pronunciation: "/fænˈtæstɪk/",
    exampleSentence: "You did a fantastic job.",
    exampleTranslationJa: "すばらしい仕事をしてくれました。",
    collocations: ["a fantastic idea", "sound fantastic"],
    mnemonic: "fantasy の形容詞形。もとは「空想の」だが今は「最高の」が主。",
    relatedWords: ["wonderful", "excellent", "terrible"],
  },
  {
    id: "geographic",
    word: "geographic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["地理の、地理的な"],
    pronunciation: "/ˌdʒiːəˈɡræfɪk/",
    exampleSentence: "The data shows clear geographic patterns.",
    exampleTranslationJa: "そのデータは明確な地理的傾向を示している。",
    collocations: ["geographic location", "geographic distribution"],
    mnemonic: "geography の形容詞形。geographical とも書く。",
    relatedWords: ["geography", "regional", "spatial"],
  },
  {
    id: "heroic",
    word: "heroic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["英雄的な、必死の"],
    pronunciation: "/həˈroʊɪk/",
    exampleSentence: "Rescuers made heroic efforts.",
    exampleTranslationJa: "救助隊は必死の努力をした。",
    collocations: ["heroic efforts", "a heroic figure"],
    mnemonic: "hero の形容詞形。heroic efforts は「(結果はどうあれ)懸命の努力」。",
    relatedWords: ["hero", "brave", "cowardly"],
  },
  {
    id: "horrific",
    word: "horrific",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ぞっとするような、恐ろしい"],
    pronunciation: "/həˈrɪfɪk/",
    exampleSentence: "The photographs were horrific.",
    exampleTranslationJa: "その写真はぞっとするものだった。",
    collocations: ["horrific injuries", "a horrific accident"],
    mnemonic: "horror の形容詞形。terrible より生々しい恐ろしさ。",
    relatedWords: ["horror", "appalling", "pleasant"],
  },
  {
    id: "hygienic",
    word: "hygienic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["衛生的な"],
    pronunciation: "/haɪˈdʒiːnɪk/",
    exampleSentence: "The kitchen must be kept hygienic.",
    exampleTranslationJa: "その台所は衛生的に保たれねばならない。",
    collocations: ["hygienic conditions", "not very hygienic"],
    mnemonic: "hygiene の形容詞形。clean よりも「菌がいない」に近い。",
    relatedWords: ["hygiene", "sanitary", "unhygienic"],
  },
  {
    id: "hysterical",
    word: "hysterical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["取り乱した", "(口語)大爆笑の"],
    pronunciation: "/hɪˈsterɪkl/",
    exampleSentence: "She became hysterical when she heard.",
    exampleTranslationJa: "それを聞いて彼女は取り乱した。",
    collocations: ["become hysterical", "hysterical laughter"],
    mnemonic: "感情が抑えられない状態。口語では「おかしくてたまらない」。",
    relatedWords: ["frantic", "uncontrolled", "calm"],
  },
  {
    id: "iconic",
    word: "iconic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["象徴的な、誰もが知る"],
    pronunciation: "/aɪˈkɑːnɪk/",
    exampleSentence: "The building has become iconic.",
    exampleTranslationJa: "その建物は街の象徴になった。",
    collocations: ["an iconic image", "an iconic building"],
    mnemonic: "icon の形容詞形。「その分野を代表するほど有名な」。",
    relatedWords: ["icon", "emblematic", "obscure"],
  },
  {
    id: "idiomatic",
    word: "idiomatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["慣用的な、こなれた"],
    pronunciation: "/ˌɪdiəˈmætɪk/",
    exampleSentence: "His English is fluent and idiomatic.",
    exampleTranslationJa: "彼の英語は流ちょうでこなれている。",
    collocations: ["idiomatic English", "an idiomatic expression"],
    mnemonic: "idiom の形容詞形。文法的に正しいだけでなく「自然な言い回し」。",
    relatedWords: ["idiom", "natural", "stilted"],
  },
  {
    id: "linguistic",
    word: "linguistic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["言語の、言語学の"],
    pronunciation: "/lɪŋˈɡwɪstɪk/",
    exampleSentence: "There are linguistic differences between the regions.",
    exampleTranslationJa: "地域間に言語的な違いがある。",
    collocations: ["linguistic diversity", "linguistic skills"],
    mnemonic: "lingua(舌・言語)が語根。language と同語根。",
    relatedWords: ["language", "verbal", "linguistics"],
  },
  {
    id: "majestic",
    word: "majestic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["堂々とした、荘厳な"],
    pronunciation: "/məˈdʒestɪk/",
    exampleSentence: "The mountains looked majestic at sunset.",
    exampleTranslationJa: "日没時の山々は荘厳だった。",
    collocations: ["a majestic view", "majestic scenery"],
    mnemonic: "majesty(威厳)の形容詞形。王を呼ぶ Your Majesty と同語根。",
    relatedWords: ["majesty", "grand", "modest"],
  },
  {
    id: "metallic",
    word: "metallic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["金属の、金属質の"],
    pronunciation: "/məˈtælɪk/",
    exampleSentence: "The water had a metallic taste.",
    exampleTranslationJa: "その水は金属のような味がした。",
    collocations: ["a metallic taste", "metallic paint"],
    mnemonic: "metal の形容詞形。味・音・色について「金属のような」。",
    relatedWords: ["metal", "shiny", "dull"],
  },
  {
    id: "microscopic",
    word: "microscopic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["顕微鏡でしか見えない、極小の"],
    pronunciation: "/ˌmaɪkrəˈskɑːpɪk/",
    exampleSentence: "The damage was microscopic but real.",
    exampleTranslationJa: "その損傷は極小だが確かにあった。",
    collocations: ["microscopic organisms", "in microscopic detail"],
    mnemonic: "microscope の形容詞形。「非常に細かい」という比喩にも。",
    relatedWords: ["microscope", "tiny", "huge"],
  },
]
