import type { VocabularyEntry } from '../types'

// 増補 第6弾。感情・性格の形容詞。似た語の差（irritated と enraged、frank と blunt など）を
// 覚えるヒントで書き分ける。
export const plus06: VocabularyEntry[] = [
  {
    id: "gloomy",
    word: "gloomy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["薄暗い", "陰気な、悲観的な"],
    pronunciation: "/ˈɡluːmi/",
    exampleSentence: "The forecast for the economy is gloomy.",
    exampleTranslationJa: "経済の見通しは暗い。",
    collocations: ["a gloomy room", "a gloomy outlook", "look gloomy"],
    mnemonic: "光が足りない暗さから、気分や見通しの暗さへ。天気にも人にも使う。",
    relatedWords: ["dark", "pessimistic", "dismal"],
  },
  {
    id: "discontented",
    word: "discontented",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["不満な、満足していない"],
    pronunciation: "/ˌdɪskənˈtentɪd/",
    exampleSentence: "Workers grew discontented with the new rules.",
    exampleTranslationJa: "労働者たちは新しい規則に不満を募らせた。",
    collocations: ["discontented with", "grow discontented", "a discontented workforce"],
    wordFormation: "dis-(否定)+ contented(満足した)。",
    mnemonic: "content(満足した)に dis- がついた形。怒りではなく「これでは足りない」感じ。",
    relatedWords: ["content", "dissatisfied", "unhappy"],
  },
  {
    id: "ecstatic",
    word: "ecstatic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["有頂天の、狂喜した"],
    pronunciation: "/ɪkˈstætɪk/",
    exampleSentence: "She was ecstatic when she got the offer.",
    exampleTranslationJa: "内定をもらって彼女は有頂天だった。",
    collocations: ["absolutely ecstatic", "an ecstatic welcome", "ecstatic about"],
    etymology: "ギリシャ語 ekstasis(自分の外に立つこと)から。",
    mnemonic: "「自分の外に出てしまう」ほどの喜び。happy の最上級のような語。",
    relatedWords: ["delighted", "thrilled", "elated"],
  },
  {
    id: "elated",
    word: "elated",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["意気揚々とした、大喜びの"],
    pronunciation: "/iˈleɪtɪd/",
    exampleSentence: "The team felt elated after the win.",
    exampleTranslationJa: "勝利のあとチームは意気揚々としていた。",
    collocations: ["feel elated", "elated by the news", "elated and exhausted"],
    wordFormation: "ラテン語 elatus(持ち上げられた)から。",
    mnemonic: "気分が「持ち上げられた」状態。よい知らせのあとの高揚。",
    relatedWords: ["ecstatic", "thrilled", "uplifted"],
  },
  {
    id: "irritated",
    word: "irritated",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["いらいらした", "(皮膚が)炎症を起こした"],
    pronunciation: "/ˈɪrɪteɪtɪd/",
    exampleSentence: "He sounded irritated on the phone.",
    exampleTranslationJa: "電話の彼はいらだっているようだった。",
    collocations: ["irritated by", "get irritated", "irritated skin"],
    mnemonic: "小さな刺激が積み重なった軽い怒り。怒りの強さは irritated < angry < furious。",
    relatedWords: ["annoyed", "angry", "irritate"],
  },
  {
    id: "enraged",
    word: "enraged",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["激怒した"],
    pronunciation: "/ɪnˈreɪdʒd/",
    exampleSentence: "Residents were enraged by the decision.",
    exampleTranslationJa: "住民はその決定に激怒した。",
    collocations: ["enraged by", "become enraged", "an enraged crowd"],
    wordFormation: "en-(〜にする)+ rage(激怒)。",
    mnemonic: "rage(激怒)の状態にされた。furious と同じ強さ。",
    relatedWords: ["furious", "rage", "irate"],
  },
  {
    id: "resentful",
    word: "resentful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恨みがましい、腹に据えかねている"],
    pronunciation: "/rɪˈzentfl/",
    exampleSentence: "She felt resentful about being left out.",
    exampleTranslationJa: "彼女は仲間はずれにされたことを腹に据えかねていた。",
    collocations: ["resentful of", "grow resentful", "a resentful tone"],
    mnemonic: "その場で爆発せず、不公平感を抱え続ける怒り。名詞は resentment。",
    relatedWords: ["resentment", "bitter", "grudge"],
  },
  {
    id: "jealous",
    word: "jealous",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["嫉妬した、やきもちを焼く"],
    pronunciation: "/ˈdʒeləs/",
    exampleSentence: "He gets jealous when she talks to other people.",
    exampleTranslationJa: "彼女がほかの人と話すと彼はやきもちを焼く。",
    collocations: ["jealous of", "a jealous husband", "make someone jealous"],
    mnemonic: "自分のものを取られる不安が jealous、人のものが欲しいのが envious。",
    relatedWords: ["envious", "jealousy", "possessive"],
  },
  {
    id: "envious",
    word: "envious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うらやましがる"],
    pronunciation: "/ˈenviəs/",
    exampleSentence: "I am envious of your free time.",
    exampleTranslationJa: "あなたの自由な時間がうらやましい。",
    collocations: ["envious of", "an envious glance", "make someone envious"],
    mnemonic: "envy(うらやみ)の形容詞。相手が持っているものが欲しい気持ち。",
    relatedWords: ["jealous", "envy", "covet"],
  },
  {
    id: "uneasy",
    word: "uneasy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["落ち着かない、不安な"],
    pronunciation: "/ʌnˈiːzi/",
    exampleSentence: "She felt uneasy about leaving the door unlocked.",
    exampleTranslationJa: "彼女は戸に鍵をかけずに出ることが落ち着かなかった。",
    collocations: ["uneasy about", "an uneasy silence", "grow uneasy"],
    wordFormation: "un-(否定)+ easy(気楽な)。",
    mnemonic: "「気楽 easy でない」。はっきりした恐怖ではなく、何か引っかかる感じ。",
    relatedWords: ["anxious", "nervous", "unsettled"],
  },
  {
    id: "apprehensive",
    word: "apprehensive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["(これから起きることが)心配な、気がかりな"],
    pronunciation: "/ˌæprɪˈhensɪv/",
    exampleSentence: "He was apprehensive about the interview.",
    exampleTranslationJa: "彼は面接のことが気がかりだった。",
    collocations: ["apprehensive about", "feel apprehensive", "slightly apprehensive"],
    mnemonic: "これから起きることへの不安に限る。すでに起きたことには使わない。",
    relatedWords: ["anxious", "nervous", "worried"],
  },
  {
    id: "panicky",
    word: "panicky",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うろたえた、パニック気味の"],
    pronunciation: "/ˈpænɪki/",
    exampleSentence: "Her voice sounded panicky on the phone.",
    exampleTranslationJa: "電話の彼女の声はうろたえていた。",
    collocations: ["feel panicky", "a panicky voice", "get panicky"],
    wordFormation: "panic(恐慌)+ -y。c のあとに k を入れて panicky。",
    mnemonic: "panic に -y をつけるとき k が入る(panicky, panicked)。つづりの注意語。",
    relatedWords: ["panic", "frantic", "anxious"],
  },
  {
    id: "terrified",
    word: "terrified",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["ひどくおびえた"],
    pronunciation: "/ˈterɪfaɪd/",
    exampleSentence: "The child was terrified of the dark.",
    exampleTranslationJa: "その子は暗闇をひどく怖がっていた。",
    collocations: ["terrified of", "absolutely terrified", "a terrified scream"],
    mnemonic: "怖さの強さは afraid < scared < terrified < petrified。",
    relatedWords: ["scared", "petrified", "terror"],
  },
  {
    id: "petrified",
    word: "petrified",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恐怖で動けない", "石化した"],
    pronunciation: "/ˈpetrɪfaɪd/",
    exampleSentence: "She stood petrified at the top of the ladder.",
    exampleTranslationJa: "彼女ははしごの上で恐怖に固まって立っていた。",
    collocations: ["petrified of", "petrified with fear", "petrified wood"],
    etymology: "ギリシャ語 petra(岩)から。petrol と同語根。",
    mnemonic: "petra(岩)が語根。「石になったように固まる」ほどの恐怖。",
    relatedWords: ["terrified", "frozen", "stone"],
  },
  {
    id: "startled",
    word: "startled",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["びくっとした、はっと驚いた"],
    pronunciation: "/ˈstɑːrtld/",
    exampleSentence: "A startled bird flew out of the bush.",
    exampleTranslationJa: "驚いた鳥が茂みから飛び出した。",
    collocations: ["a startled look", "startled by the noise", "look startled"],
    mnemonic: "surprised が「意外」なのに対し、startled は「びくっと体が動く」瞬間の驚き。",
    relatedWords: ["surprised", "shocked", "startle"],
  },
  {
    id: "composed",
    word: "composed",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["落ち着いた、冷静な"],
    pronunciation: "/kəmˈpoʊzd/",
    exampleSentence: "She stayed composed throughout the questioning.",
    exampleTranslationJa: "彼女は尋問の間ずっと落ち着いていた。",
    collocations: ["remain composed", "cool and composed", "a composed manner"],
    mnemonic: "compose(組み立てる)から「自分を整えている」。動揺を見せない冷静さ。",
    relatedWords: ["calm", "collected", "poised"],
  },
  {
    id: "serene",
    word: "serene",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["穏やかな、静かで落ち着いた"],
    pronunciation: "/səˈriːn/",
    exampleSentence: "The lake was serene in the early morning.",
    exampleTranslationJa: "早朝の湖は穏やかだった。",
    collocations: ["a serene smile", "serene beauty", "look serene"],
    mnemonic: "波風のない静けさ。人の表情にも風景にも使える上品な語。",
    relatedWords: ["calm", "peaceful", "tranquil"],
  },
  {
    id: "laid-back",
    word: "laid-back",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["のんびりした、あくせくしない"],
    pronunciation: "/ˌleɪd ˈbæk/",
    exampleSentence: "He has a laid-back approach to deadlines.",
    exampleTranslationJa: "彼は締め切りに対してのんびり構えている。",
    collocations: ["a laid-back attitude", "very laid-back", "a laid-back atmosphere"],
    mnemonic: "いすに「後ろへ寝かせた(laid back)」姿勢。ほめ言葉にも皮肉にもなる。",
    relatedWords: ["relaxed", "easygoing", "casual"],
  },
  {
    id: "easygoing",
    word: "easygoing",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["おおらかな、こだわらない"],
    pronunciation: "/ˌiːziˈɡoʊɪŋ/",
    exampleSentence: "My easygoing boss never raises his voice.",
    exampleTranslationJa: "おおらかな上司は決して声を荒げない。",
    collocations: ["an easygoing person", "easygoing about", "friendly and easygoing"],
    wordFormation: "easy(気楽に)+ going(進む)。",
    mnemonic: "人柄をほめる語。細かいことを気にせず人と付き合える性質。",
    relatedWords: ["relaxed", "laid-back", "tolerant"],
  },
  {
    id: "tense",
    word: "tense",
    level: "B1",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["緊張した、張りつめた", "(文法の)時制"],
    pronunciation: "/tens/",
    exampleSentence: "The atmosphere in the room was tense.",
    exampleTranslationJa: "部屋の空気は張りつめていた。",
    collocations: ["a tense moment", "tense muscles", "the past tense"],
    mnemonic: "ラテン語 tendere(引き伸ばす)から。ぴんと張った状態。文法の「時制」も同じつづり。",
    relatedWords: ["tension", "nervous", "strained"],
  },
  {
    id: "edgy",
    word: "edgy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["いらいらした、神経質な", "(作品が)攻めた、とがった"],
    pronunciation: "/ˈedʒi/",
    exampleSentence: "He gets edgy before a big presentation.",
    exampleTranslationJa: "彼は大きな発表の前になると神経質になる。",
    collocations: ["feel edgy", "an edgy performance", "a bit edgy"],
    wordFormation: "edge(縁・刃)+ -y。",
    mnemonic: "edge(刃)のようにぴりぴりしている。作品なら「とがっていて刺激的」。",
    relatedWords: ["nervous", "tense", "irritable"],
  },
  {
    id: "restless",
    word: "restless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["落ち着かない、じっとしていられない"],
    pronunciation: "/ˈrestləs/",
    exampleSentence: "The children grew restless during the long wait.",
    exampleTranslationJa: "長い待ち時間に子どもたちは落ち着かなくなった。",
    collocations: ["a restless night", "grow restless", "restless energy"],
    wordFormation: "rest(休息)+ -less(ない)。",
    mnemonic: "rest(休み)が less(ない)。体が動いてしまう落ち着かなさ。",
    relatedWords: ["fidgety", "impatient", "uneasy"],
  },
  {
    id: "self-assured",
    word: "self-assured",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自信のある、物おじしない"],
    pronunciation: "/ˌself əˈʃʊrd/",
    exampleSentence: "She gave a self-assured answer to every question.",
    exampleTranslationJa: "彼女はどの質問にも自信をもって答えた。",
    collocations: ["a self-assured manner", "calm and self-assured"],
    wordFormation: "self(自分)+ assured(確信した)。",
    mnemonic: "confident とほぼ同じだが、態度に表れている落ち着きを指す。",
    relatedWords: ["confident", "assured", "poised"],
  },
  {
    id: "arrogant",
    word: "arrogant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["傲慢な、横柄な"],
    pronunciation: "/ˈærəɡənt/",
    exampleSentence: "His arrogant tone annoyed everyone in the room.",
    exampleTranslationJa: "彼の横柄な口調は部屋の全員をいらだたせた。",
    collocations: ["an arrogant attitude", "sound arrogant", "arrogant and rude"],
    mnemonic: "confident をこえて人を見下しているところが arrogant。名詞は arrogance。",
    relatedWords: ["conceited", "humble", "proud"],
  },
  {
    id: "conceited",
    word: "conceited",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["うぬぼれた"],
    pronunciation: "/kənˈsiːtɪd/",
    exampleSentence: "He is clever but rather conceited.",
    exampleTranslationJa: "彼は頭はいいが、いささかうぬぼれている。",
    collocations: ["a conceited young man", "sound conceited"],
    mnemonic: "arrogant が人を見下す態度、conceited は自分を高く見る中身。",
    relatedWords: ["arrogant", "vain", "modest"],
  },
  {
    id: "timid",
    word: "timid",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["おずおずした、気弱な"],
    pronunciation: "/ˈtɪmɪd/",
    exampleSentence: "She gave a timid knock at the door.",
    exampleTranslationJa: "彼女はおずおずと戸をノックした。",
    collocations: ["a timid voice", "too timid to ask", "a timid smile"],
    mnemonic: "shy が人見知り、timid は行動に踏み出せない気弱さ。",
    relatedWords: ["shy", "bashful", "bold"],
  },
  {
    id: "bashful",
    word: "bashful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恥ずかしがりの、はにかんだ"],
    pronunciation: "/ˈbæʃfl/",
    exampleSentence: "He gave a bashful grin and looked away.",
    exampleTranslationJa: "彼ははにかんだ笑みを浮かべて目をそらした。",
    collocations: ["a bashful smile", "look bashful", "too bashful to speak"],
    mnemonic: "abash(恥じ入らせる)から。人前で顔が赤くなるような恥ずかしがり。",
    relatedWords: ["shy", "timid", "modest"],
  },
  {
    id: "obstinate",
    word: "obstinate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["がんこな、意地を張る"],
    pronunciation: "/ˈɑːbstɪnət/",
    exampleSentence: "He was obstinate and refused to change his mind.",
    exampleTranslationJa: "彼はがんこで、考えを変えようとしなかった。",
    collocations: ["obstinate refusal", "an obstinate child", "remain obstinate"],
    mnemonic: "stubborn とほぼ同じだが、かたく否定的な響き。文章で使う語。",
    relatedWords: ["stubborn", "inflexible", "persistent"],
  },
  {
    id: "adaptable",
    word: "adaptable",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["順応性のある、融通のきく"],
    pronunciation: "/əˈdæptəbl/",
    exampleSentence: "Employers look for adaptable staff.",
    exampleTranslationJa: "雇い主は順応性のある人材を求めている。",
    collocations: ["highly adaptable", "adaptable to change", "an adaptable design"],
    wordFormation: "adapt(適応する)+ -able(できる)。",
    mnemonic: "flexible が「曲げられる」、adaptable は「新しい環境に合わせられる」。",
    relatedWords: ["flexible", "adapt", "versatile"],
  },
  {
    id: "rigid",
    word: "rigid",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["硬直した、曲がらない", "融通のきかない"],
    pronunciation: "/ˈrɪdʒɪd/",
    exampleSentence: "The school has rigid rules about uniform.",
    exampleTranslationJa: "その学校は制服について融通のきかない規則がある。",
    collocations: ["rigid rules", "a rigid structure", "rigid thinking"],
    mnemonic: "物が「曲がらない」から、考えや制度が「融通がきかない」へ。flexible の反対。",
    relatedWords: ["stiff", "inflexible", "strict"],
  },
  {
    id: "lenient",
    word: "lenient",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["寛大な、罰が甘い"],
    pronunciation: "/ˈliːniənt/",
    exampleSentence: "The judge was lenient because it was a first offence.",
    exampleTranslationJa: "初犯だったので裁判官は寛大だった。",
    collocations: ["a lenient sentence", "lenient with", "too lenient"],
    mnemonic: "罰や規則を緩くするほう。strict の反対で、法廷や学校の話でよく出る。",
    relatedWords: ["strict", "merciful", "tolerant"],
  },
  {
    id: "tolerant",
    word: "tolerant",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["寛容な、受け入れる"],
    pronunciation: "/ˈtɑːlərənt/",
    exampleSentence: "A tolerant society accepts many ways of living.",
    exampleTranslationJa: "寛容な社会は多くの生き方を受け入れる。",
    collocations: ["tolerant of", "a tolerant society", "become more tolerant"],
    mnemonic: "lenient は罰を緩めること、tolerant は違いを受け入れること。名詞は tolerance。",
    relatedWords: ["tolerance", "accepting", "open-minded"],
  },
  {
    id: "stingy",
    word: "stingy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["けちな"],
    pronunciation: "/ˈstɪndʒi/",
    exampleSentence: "He is too stingy to buy a round of drinks.",
    exampleTranslationJa: "彼はけちすぎて、みんなに一杯おごろうとしない。",
    collocations: ["stingy with money", "a stingy portion", "too stingy"],
    mnemonic: "g は /dʒ/。generous の反対。料理の量が少ないのも a stingy portion。",
    relatedWords: ["mean", "generous", "miserly"],
  },
  {
    id: "mean",
    word: "mean",
    level: "A2",
    partOfSpeech: "動詞・形容詞・名詞",
    meaningsJa: ["意味する", "意地悪な", "(英)けちな", "平均"],
    pronunciation: "/miːn/",
    exampleSentence: "What do you mean by that?",
    exampleTranslationJa: "それはどういう意味ですか。",
    collocations: ["mean to do", "be mean to someone", "the mean value"],
    mnemonic: "活用は mean-meant-meant。動詞は「意味する・つもりである」、形容詞は「意地悪な」。",
    relatedWords: ["meaning", "intend", "average"],
  },
  {
    id: "selfish",
    word: "selfish",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["自分勝手な、利己的な"],
    pronunciation: "/ˈselfɪʃ/",
    exampleSentence: "It was selfish of him to take the last seat.",
    exampleTranslationJa: "最後の席を取るとは彼も自分勝手だった。",
    collocations: ["a selfish decision", "selfish reasons", "purely selfish"],
    wordFormation: "self(自分)+ -ish(〜がち)。",
    mnemonic: "self(自分)ばかり。反対は selfless(無私の)。",
    relatedWords: ["selfless", "greedy", "inconsiderate"],
  },
  {
    id: "selfless",
    word: "selfless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無私の、自分を後回しにする"],
    pronunciation: "/ˈselfləs/",
    exampleSentence: "Her selfless work in the shelter went unnoticed.",
    exampleTranslationJa: "避難所での彼女の無私の働きは気づかれずにいた。",
    collocations: ["selfless devotion", "a selfless act", "selfless service"],
    wordFormation: "self(自分)+ -less(ない)。",
    mnemonic: "self(自分)が less(ない)。selfish の正反対。",
    relatedWords: ["selfish", "generous", "altruistic"],
  },
  {
    id: "inconsiderate",
    word: "inconsiderate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["思いやりのない、無神経な"],
    pronunciation: "/ˌɪnkənˈsɪdərət/",
    exampleSentence: "It was inconsiderate to call so late.",
    exampleTranslationJa: "あんなに遅くに電話するのは思いやりがなかった。",
    collocations: ["inconsiderate behaviour", "inconsiderate of you", "rude and inconsiderate"],
    wordFormation: "in-(否定)+ considerate(思いやりのある)。",
    mnemonic: "considerate(相手を考える)に in- がついた形。悪意より「気が回らない」。",
    relatedWords: ["considerate", "thoughtless", "rude"],
  },
  {
    id: "frank",
    word: "frank",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["率直な、ざっくばらんな"],
    pronunciation: "/fræŋk/",
    exampleSentence: "To be frank, I did not enjoy the film.",
    exampleTranslationJa: "率直に言うと、あの映画は楽しめなかった。",
    collocations: ["to be frank", "a frank discussion", "frank about"],
    mnemonic: "To be frank, ... は「率直に言うと」。相手を傷つける鋭さはない。",
    relatedWords: ["honest", "blunt", "candid"],
  },
  {
    id: "blunt",
    word: "blunt",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["歯に衣着せない、無遠慮な", "(刃が)鈍い", "鈍らせる"],
    pronunciation: "/blʌnt/",
    exampleSentence: "To be blunt, your report is not good enough.",
    exampleTranslationJa: "はっきり言うと、あなたの報告書は水準に達していない。",
    collocations: ["a blunt knife", "to be blunt", "blunt criticism"],
    mnemonic: "刃が「鈍い」から、言い方が「遠慮なくずばり」。frank より角が立つ。",
    relatedWords: ["frank", "direct", "sharp"],
  },
  {
    id: "tactful",
    word: "tactful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["気配りのある、そつのない"],
    pronunciation: "/ˈtæktfl/",
    exampleSentence: "She found a tactful way to refuse the invitation.",
    exampleTranslationJa: "彼女は角の立たない断り方を見つけた。",
    collocations: ["a tactful reply", "be tactful about", "tactful and kind"],
    wordFormation: "tact(気配り)+ -ful。",
    mnemonic: "tact は「相手を傷つけない感覚」。blunt の正反対。",
    relatedWords: ["diplomatic", "tactless", "considerate"],
  },
  {
    id: "tactless",
    word: "tactless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無神経な、配慮に欠ける"],
    pronunciation: "/ˈtæktləs/",
    exampleSentence: "It was tactless to mention her age.",
    exampleTranslationJa: "彼女の年齢に触れるのは無神経だった。",
    collocations: ["a tactless remark", "tactless of you", "clumsy and tactless"],
    wordFormation: "tact(気配り)+ -less(ない)。",
    mnemonic: "tact が less(ない)。悪気はなくても言ってはいけないことを言う。",
    relatedWords: ["tactful", "insensitive", "blunt"],
  },
  {
    id: "hypocritical",
    word: "hypocritical",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["偽善的な、言行不一致の"],
    pronunciation: "/ˌhɪpəˈkrɪtɪkl/",
    exampleSentence: "It is hypocritical to preach honesty and then lie.",
    exampleTranslationJa: "正直を説いておいてうそをつくのは偽善だ。",
    collocations: ["hypocritical behaviour", "sound hypocritical"],
    etymology: "ギリシャ語 hypokrites(役者)から。「役を演じる者」。",
    mnemonic: "ギリシャ語で「役者」。中身と違う役を演じているのが偽善。名詞は hypocrite。",
    relatedWords: ["hypocrite", "insincere", "two-faced"],
  },
  {
    id: "treacherous",
    word: "treacherous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["裏切りの、不実な", "(道などが)見た目より危険な"],
    pronunciation: "/ˈtretʃərəs/",
    exampleSentence: "The path becomes treacherous after rain.",
    exampleTranslationJa: "その小道は雨のあと危険になる。",
    collocations: ["treacherous conditions", "a treacherous friend", "treacherous ice"],
    mnemonic: "「見かけと違って裏切る」が芯。人にも路面にも使う。",
    relatedWords: ["betray", "disloyal", "dangerous"],
  },
  {
    id: "diligent",
    word: "diligent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["勤勉な、こつこつ努める"],
    pronunciation: "/ˈdɪlɪdʒənt/",
    exampleSentence: "She is a diligent student who never misses a class.",
    exampleTranslationJa: "彼女は授業を一度も欠かさない勤勉な学生だ。",
    collocations: ["a diligent worker", "diligent research", "diligent in"],
    mnemonic: "急がずていねいに続ける勤勉さ。名詞は diligence。",
    relatedWords: ["hardworking", "industrious", "conscientious"],
  },
  {
    id: "industrious",
    word: "industrious",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["勤勉な、よく働く"],
    pronunciation: "/ɪnˈdʌstriəs/",
    exampleSentence: "The town has a reputation for industrious people.",
    exampleTranslationJa: "その町はよく働く人々で知られている。",
    collocations: ["an industrious worker", "industrious and honest"],
    mnemonic: "industrial(産業の)とは別語。industrious は人が「よく働く」。",
    relatedWords: ["diligent", "hardworking", "industry"],
  },
  {
    id: "hardworking",
    word: "hardworking",
    level: "A2",
    partOfSpeech: "形容詞",
    meaningsJa: ["よく働く、努力家の"],
    pronunciation: "/ˌhɑːrdˈwɜːrkɪŋ/",
    exampleSentence: "He is honest and hardworking.",
    exampleTranslationJa: "彼は正直でよく働く。",
    collocations: ["a hardworking student", "honest and hardworking"],
    wordFormation: "hard(懸命に)+ working(働く)。",
    mnemonic: "diligent の日常語版。履歴書や推薦状の定番の形容詞。",
    relatedWords: ["diligent", "industrious", "lazy"],
  },
  {
    id: "idle",
    word: "idle",
    level: "B2",
    partOfSpeech: "形容詞・動詞",
    meaningsJa: ["何もしていない、遊んでいる", "怠惰な", "(機械が)空回りする"],
    pronunciation: "/ˈaɪdl/",
    exampleSentence: "The machines stood idle for a month.",
    exampleTranslationJa: "その機械は1か月動かないままだった。",
    collocations: ["stand idle", "idle chatter", "an idle threat"],
    mnemonic: "idol(偶像)と同音。「動いていない」が芯で、人なら怠惰、機械なら停止。",
    relatedWords: ["lazy", "inactive", "unused"],
  },
  {
    id: "sloppy",
    word: "sloppy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["いいかげんな、雑な", "だらしない"],
    pronunciation: "/ˈslɑːpi/",
    exampleSentence: "The report was full of sloppy mistakes.",
    exampleTranslationJa: "その報告書は雑なミスだらけだった。",
    collocations: ["sloppy work", "sloppy handwriting", "get sloppy"],
    mnemonic: "こぼす slop から。ていねいさを欠いた仕事や身なり。",
    relatedWords: ["careless", "untidy", "meticulous"],
  },
  {
    id: "meticulous",
    word: "meticulous",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["細部まで行き届いた、几帳面な"],
    pronunciation: "/məˈtɪkjələs/",
    exampleSentence: "He kept meticulous records of every payment.",
    exampleTranslationJa: "彼はすべての支払いについて几帳面な記録をつけていた。",
    collocations: ["meticulous attention to detail", "meticulous records", "meticulous in"],
    mnemonic: "careful より徹底している。meticulous attention to detail が定番の言い回し。",
    relatedWords: ["thorough", "careful", "sloppy"],
  },
  {
    id: "inquisitive",
    word: "inquisitive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["知りたがる、詮索好きな"],
    pronunciation: "/ɪnˈkwɪzətɪv/",
    exampleSentence: "Children are naturally inquisitive about the world.",
    exampleTranslationJa: "子どもは生まれつき世界を知りたがる。",
    collocations: ["an inquisitive mind", "inquisitive about", "naturally inquisitive"],
    wordFormation: "inquire(尋ねる)と同語根。",
    mnemonic: "curious のかたい語。よい意味なら探究心、悪い意味なら詮索。",
    relatedWords: ["curious", "nosy", "inquire"],
  },
  {
    id: "nosy",
    word: "nosy",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["せんさく好きな、詮索好きの"],
    pronunciation: "/ˈnoʊzi/",
    exampleSentence: "Our nosy neighbour watches everyone who comes in.",
    exampleTranslationJa: "せんさく好きの隣人は出入りする人を全部見ている。",
    collocations: ["a nosy neighbour", "don't be nosy", "nosy questions"],
    wordFormation: "nose(鼻)+ -y。「鼻をつっこむ」から。",
    mnemonic: "人のことに nose(鼻)をつっこむ。curious の悪い側。",
    relatedWords: ["curious", "inquisitive", "meddling"],
  },
  {
    id: "apathetic",
    word: "apathetic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無関心な、やる気のない"],
    pronunciation: "/ˌæpəˈθetɪk/",
    exampleSentence: "Young voters were apathetic about the election.",
    exampleTranslationJa: "若い有権者はその選挙に無関心だった。",
    collocations: ["apathetic about", "an apathetic response", "politically apathetic"],
    wordFormation: "a-(否定)+ pathos(感情)。「感じない」。",
    mnemonic: "a(なし)+ pathos(感情)。sympathy・pathetic と同語根。名詞は apathy。",
    relatedWords: ["indifferent", "apathy", "uninterested"],
  },
  {
    id: "witty",
    word: "witty",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["機知に富んだ、当意即妙の"],
    pronunciation: "/ˈwɪti/",
    exampleSentence: "Her witty reply made everyone laugh.",
    exampleTranslationJa: "彼女の機知に富んだ返しはみんなを笑わせた。",
    collocations: ["a witty remark", "witty and charming", "a witty reply"],
    wordFormation: "wit(機知)+ -y。",
    mnemonic: "funny が「おかしい」、witty は「頭のよい面白さ」。",
    relatedWords: ["wit", "clever", "humorous"],
  },
  {
    id: "shrewd",
    word: "shrewd",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["抜け目のない、鋭い判断力のある"],
    pronunciation: "/ʃruːd/",
    exampleSentence: "It was a shrewd business decision.",
    exampleTranslationJa: "それは抜け目のない経営判断だった。",
    collocations: ["a shrewd investor", "a shrewd move", "shrewd judgement"],
    mnemonic: "利益や人の思惑を見抜く賢さ。cunning と違って悪い意味は薄い。",
    relatedWords: ["astute", "cunning", "clever"],
  },
  {
    id: "cunning",
    word: "cunning",
    level: "B2",
    partOfSpeech: "形容詞・名詞",
    meaningsJa: ["ずる賢い", "悪知恵"],
    pronunciation: "/ˈkʌnɪŋ/",
    exampleSentence: "The fox came up with a cunning plan.",
    exampleTranslationJa: "キツネはずる賢い計画を思いついた。",
    collocations: ["a cunning plan", "cunning and ruthless", "sheer cunning"],
    mnemonic: "shrewd が中立、cunning は「だます」含みがある。日本語の「カンニング」は和製英語。",
    relatedWords: ["sly", "shrewd", "crafty"],
  },
  {
    id: "naive",
    word: "naive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["世間知らずの、うぶな"],
    pronunciation: "/naɪˈiːv/",
    exampleSentence: "It was naive to think the job would be easy.",
    exampleTranslationJa: "その仕事が楽だと思ったのは甘かった。",
    collocations: ["naive to think", "politically naive", "a naive question"],
    etymology: "フランス語 naïf(生まれたままの)から。native と同語根。",
    mnemonic: "native(生まれたままの)と同語根。経験がないゆえの単純さ。",
    relatedWords: ["innocent", "gullible", "inexperienced"],
  },
  {
    id: "gullible",
    word: "gullible",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["だまされやすい"],
    pronunciation: "/ˈɡʌləbl/",
    exampleSentence: "Scammers target gullible people online.",
    exampleTranslationJa: "詐欺師はネット上でだまされやすい人を狙う。",
    collocations: ["gullible enough to believe", "target the gullible"],
    mnemonic: "gull には古語で「だます」の意味。naive より「実際にだまされる」に近い。",
    relatedWords: ["naive", "credulous", "trusting"],
  },
  {
    id: "thankful",
    word: "thankful",
    level: "B1",
    partOfSpeech: "形容詞",
    meaningsJa: ["ありがたく思う、感謝している"],
    pronunciation: "/ˈθæŋkfl/",
    exampleSentence: "I am thankful that nobody was hurt.",
    exampleTranslationJa: "誰もけがをしなくてありがたい。",
    collocations: ["thankful for", "thankful that", "deeply thankful"],
    wordFormation: "thank(感謝)+ -ful。",
    mnemonic: "grateful が人への感謝、thankful は「よかった」という安堵を含む。",
    relatedWords: ["grateful", "thanks", "relieved"],
  },
  {
    id: "ungrateful",
    word: "ungrateful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["恩知らずの、感謝しない"],
    pronunciation: "/ʌnˈɡreɪtfl/",
    exampleSentence: "I do not want to sound ungrateful, but this is not what I ordered.",
    exampleTranslationJa: "恩知らずに聞こえたくはないのですが、これは注文したものと違います。",
    collocations: ["sound ungrateful", "an ungrateful child"],
    wordFormation: "un-(否定)+ grateful(感謝している)。",
    mnemonic: "I don't want to sound ungrateful, but ... は文句の前置きの定番。",
    relatedWords: ["grateful", "thankless", "rude"],
  },
  {
    id: "compassionate",
    word: "compassionate",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["思いやりのある、情け深い"],
    pronunciation: "/kəmˈpæʃənət/",
    exampleSentence: "She was given compassionate leave to visit her father.",
    exampleTranslationJa: "彼女は父を見舞うため慶弔休暇を与えられた。",
    collocations: ["compassionate care", "compassionate leave", "kind and compassionate"],
    wordFormation: "com-(共に)+ passion(苦しみ)。「共に苦しむ」。",
    mnemonic: "com(共に)+ passion(苦しみ)。相手の痛みを自分も感じること。",
    relatedWords: ["sympathetic", "compassion", "kind"],
  },
  {
    id: "ruthless",
    word: "ruthless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["容赦のない、非情な"],
    pronunciation: "/ˈruːθləs/",
    exampleSentence: "He was ruthless in cutting costs.",
    exampleTranslationJa: "彼は容赦なく費用を削った。",
    collocations: ["ruthless efficiency", "a ruthless dictator", "be ruthless about"],
    wordFormation: "ruth(古語で「あわれみ」)+ -less(ない)。",
    mnemonic: "今は使われない ruth(あわれみ)が less(ない)。悪い意味だけでなく「徹底した」の意にも。",
    relatedWords: ["merciless", "brutal", "merciful"],
  },
  {
    id: "merciful",
    word: "merciful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["慈悲深い、情けをかける"],
    pronunciation: "/ˈmɜːrsɪfl/",
    exampleSentence: "The judge was merciful and reduced the sentence.",
    exampleTranslationJa: "裁判官は情けをかけて刑を軽くした。",
    collocations: ["a merciful God", "merciful towards", "a merciful release"],
    wordFormation: "mercy(慈悲)+ -ful。",
    mnemonic: "罰する力を持つ側が手を緩めるのが merciful。反対は merciless / ruthless。",
    relatedWords: ["mercy", "ruthless", "lenient"],
  },
  {
    id: "remorseful",
    word: "remorseful",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["深く後悔している、悔い改めた"],
    pronunciation: "/rɪˈmɔːrsfl/",
    exampleSentence: "He seemed genuinely remorseful in court.",
    exampleTranslationJa: "法廷で彼は心から悔いているように見えた。",
    collocations: ["deeply remorseful", "appear remorseful", "remorseful about"],
    wordFormation: "re-(繰り返し)+ mordere(かむ)+ -ful。「良心がかみ続ける」。",
    mnemonic: "良心が繰り返しかむ(mordere)。regret より重く、罪悪感を含む。",
    relatedWords: ["remorse", "regret", "guilty"],
  },
  {
    id: "smug",
    word: "smug",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["ひとりよがりに得意げな、したり顔の"],
    pronunciation: "/smʌɡ/",
    exampleSentence: "Do not look so smug just because you were right.",
    exampleTranslationJa: "正しかったからといって、そんなに得意顔をしないで。",
    collocations: ["a smug smile", "look smug", "smug satisfaction"],
    mnemonic: "proud と違い、必ず悪い意味。まわりをいらだたせる自己満足。",
    relatedWords: ["smirk", "complacent", "arrogant"],
  },
  {
    id: "nostalgic",
    word: "nostalgic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["懐かしい、郷愁を誘う"],
    pronunciation: "/nɑːˈstældʒɪk/",
    exampleSentence: "The song made her nostalgic for her school days.",
    exampleTranslationJa: "その歌は彼女に学生時代を懐かしく思わせた。",
    collocations: ["nostalgic for", "feel nostalgic", "a nostalgic mood"],
    etymology: "ギリシャ語 nostos(帰郷)+ algos(痛み)。「帰りたい痛み」。",
    mnemonic: "nostos(帰郷)+ algos(痛み)。帰れない場所や時への甘い痛み。",
    relatedWords: ["nostalgia", "homesick", "sentimental"],
  },
  {
    id: "melancholy",
    word: "melancholy",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["物思いに沈んだ悲しみ、憂うつ"],
    pronunciation: "/ˈmelənkɑːli/",
    exampleSentence: "A melancholy tune drifted from the next room.",
    exampleTranslationJa: "もの悲しい調べが隣の部屋から流れてきた。",
    collocations: ["a melancholy mood", "deep melancholy", "a melancholy song"],
    etymology: "ギリシャ語 melas(黒)+ kholē(胆汁)。「黒い胆汁」という古代医学から。",
    mnemonic: "「黒い胆汁」が語源。sad より静かで、どこか美しさを含む悲しみ。",
    relatedWords: ["sad", "gloomy", "sorrow"],
  },
  {
    id: "cheerless",
    word: "cheerless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["わびしい、気の滅入る"],
    pronunciation: "/ˈtʃɪrləs/",
    exampleSentence: "They ate in a cheerless room with bare walls.",
    exampleTranslationJa: "彼らは何も飾りのない、わびしい部屋で食事した。",
    collocations: ["a cheerless room", "a cheerless winter", "cold and cheerless"],
    wordFormation: "cheer(元気・明るさ)+ -less(ない)。",
    mnemonic: "cheerful の正反対。人ではなく場所や天気に使うことが多い。",
    relatedWords: ["cheerful", "gloomy", "bleak"],
  },
  {
    id: "idealistic",
    word: "idealistic",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["理想主義の、現実離れした"],
    pronunciation: "/aɪˌdiːəˈlɪstɪk/",
    exampleSentence: "His plan is idealistic but hard to fund.",
    exampleTranslationJa: "彼の計画は理想的だが、資金を集めるのが難しい。",
    collocations: ["young and idealistic", "an idealistic view", "overly idealistic"],
    wordFormation: "ideal(理想)+ -istic。",
    mnemonic: "realistic の対。ほめ言葉にも「現実を見ていない」という批判にもなる。",
    relatedWords: ["realistic", "ideal", "optimistic"],
  },
  {
    id: "impulsive",
    word: "impulsive",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["衝動的な、思いつきで動く"],
    pronunciation: "/ɪmˈpʌlsɪv/",
    exampleSentence: "Buying the car was an impulsive decision.",
    exampleTranslationJa: "その車を買ったのは衝動的な決断だった。",
    collocations: ["an impulsive decision", "impulsive buying", "act impulsively"],
    wordFormation: "impulse(衝動)+ -ive。",
    mnemonic: "考える前に動く。reckless(無謀)より軽く、「思いつきで」に近い。",
    relatedWords: ["impulse", "spontaneous", "rash"],
  },
  {
    id: "reckless",
    word: "reckless",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["無謀な、後先を考えない"],
    pronunciation: "/ˈrekləs/",
    exampleSentence: "He was fined for reckless driving.",
    exampleTranslationJa: "彼は無謀運転で罰金を科された。",
    collocations: ["reckless driving", "reckless spending", "reckless with money"],
    wordFormation: "reck(古語で「気にかける」)+ -less(ない)。",
    mnemonic: "危険を「気にかけない」。法律用語としても reckless driving のように使う。",
    relatedWords: ["careless", "rash", "cautious"],
  },
  {
    id: "prudent",
    word: "prudent",
    level: "B2",
    partOfSpeech: "形容詞",
    meaningsJa: ["慎重な、思慮深い"],
    pronunciation: "/ˈpruːdnt/",
    exampleSentence: "It would be prudent to check the figures again.",
    exampleTranslationJa: "数字をもう一度確認するのが賢明だろう。",
    collocations: ["a prudent decision", "prudent to do", "financially prudent"],
    mnemonic: "careful に「先を読む賢さ」が加わった語。お金の話で特によく出る。",
    relatedWords: ["cautious", "wise", "reckless"],
  },
  {
    id: "vacancy",
    word: "vacancy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["欠員、求人枠", "(宿の)空き部屋"],
    pronunciation: "/ˈveɪkənsi/",
    exampleSentence: "There is a vacancy in the accounts department.",
    exampleTranslationJa: "経理部に欠員が一つある。",
    collocations: ["fill a vacancy", "no vacancies", "a job vacancy"],
    wordFormation: "vacant(空いている)+ -cy。",
    mnemonic: "宿の看板の No Vacancies は「満室」。会社なら「募集中の枠」。",
    relatedWords: ["vacant", "opening", "position"],
  },
  {
    id: "shortlist",
    word: "shortlist",
    level: "B2",
    partOfSpeech: "名詞・動詞",
    meaningsJa: ["最終候補者名簿", "最終候補に残す"],
    pronunciation: "/ˈʃɔːrtlɪst/",
    exampleSentence: "Four candidates were shortlisted for the post.",
    exampleTranslationJa: "その職には4人が最終候補に残された。",
    collocations: ["be shortlisted for", "draw up a shortlist", "on the shortlist"],
    wordFormation: "short(短い)+ list(名簿)。「絞り込んだ名簿」。",
    mnemonic: "長い応募者名簿を short(短く)した list。賞のノミネートにも使う。",
    relatedWords: ["candidate", "select", "nominate"],
  },
  {
    id: "interviewee",
    word: "interviewee",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["面接を受ける人、インタビューされる人"],
    pronunciation: "/ˌɪntərvjuːˈiː/",
    exampleSentence: "Each interviewee was given fifteen minutes.",
    exampleTranslationJa: "面接を受ける人にはそれぞれ15分が与えられた。",
    collocations: ["the next interviewee", "brief the interviewee"],
    wordFormation: "interview + -ee(される側)。する側は interviewer。",
    mnemonic: "-ee は「される側」(employee, trainee)。-er が「する側」。",
    relatedWords: ["interviewer", "candidate", "interview"],
  },
  {
    id: "probation",
    word: "probation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["試用期間", "執行猶予、保護観察"],
    pronunciation: "/proʊˈbeɪʃn/",
    exampleSentence: "New staff are on probation for three months.",
    exampleTranslationJa: "新入社員は3か月の試用期間中だ。",
    collocations: ["on probation", "a probation period", "a probation officer"],
    wordFormation: "ラテン語 probare(試す)から。prove・probe と同語根。",
    mnemonic: "probare(試す)が語根。仕事の試用も、刑の執行猶予も「様子を見る期間」。",
    relatedWords: ["trial", "prove", "parole"],
  },
  {
    id: "internship",
    word: "internship",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["インターンシップ、実務研修"],
    pronunciation: "/ˈɪntɜːrnʃɪp/",
    exampleSentence: "She did a summer internship at a law firm.",
    exampleTranslationJa: "彼女は法律事務所で夏のインターンシップをした。",
    collocations: ["a paid internship", "do an internship", "an internship programme"],
    wordFormation: "intern(研修生)+ -ship(立場)。",
    mnemonic: "学生が短期間、実務を経験する制度。人は intern。",
    relatedWords: ["intern", "trainee", "placement"],
  },
  {
    id: "apprenticeship",
    word: "apprenticeship",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["徒弟制度、見習い期間"],
    pronunciation: "/əˈprentɪʃɪp/",
    exampleSentence: "He served a four-year apprenticeship as a carpenter.",
    exampleTranslationJa: "彼は大工として4年の見習い期間を勤めた。",
    collocations: ["serve an apprenticeship", "a modern apprenticeship"],
    wordFormation: "apprentice(見習い)+ -ship。",
    mnemonic: "職人の技を働きながら身につける制度。internship より長く、技能職向け。",
    relatedWords: ["apprentice", "trainee", "craft"],
  },
  {
    id: "subordinate",
    word: "subordinate",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["部下", "下位の、従属的な"],
    pronunciation: "/səˈbɔːrdɪnət/",
    exampleSentence: "A good manager listens to their subordinates.",
    exampleTranslationJa: "よい管理職は部下の話を聞く。",
    collocations: ["a subordinate role", "treat as subordinate", "a subordinate clause"],
    wordFormation: "sub-(下)+ ordin(順序)。「順位が下の」。",
    mnemonic: "sub(下)+ order(順序)。文法の「従属節」も a subordinate clause。",
    relatedWords: ["superior", "junior", "staff"],
  },
  {
    id: "staffing",
    word: "staffing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["人員配置、人員体制"],
    pronunciation: "/ˈstæfɪŋ/",
    exampleSentence: "Staffing levels fell over the winter.",
    exampleTranslationJa: "冬の間に人員体制は手薄になった。",
    collocations: ["staffing levels", "a staffing shortage", "staffing costs"],
    wordFormation: "staff(職員)+ -ing。",
    mnemonic: "何人をどこに置くかという話。ニュースでは staffing shortage(人手不足)。",
    relatedWords: ["staff", "recruitment", "personnel"],
  },
  {
    id: "rota",
    word: "rota",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["当番表、勤務表(英)"],
    pronunciation: "/ˈroʊtə/",
    exampleSentence: "Your name is on the rota for Saturday.",
    exampleTranslationJa: "土曜の当番表にあなたの名前がある。",
    collocations: ["on the rota", "a cleaning rota", "draw up a rota"],
    etymology: "ラテン語 rota(車輪)から。順に回ってくる表。",
    mnemonic: "ラテン語で「車輪」。順番が回ってくる表。米では schedule / roster。",
    relatedWords: ["roster", "shift", "schedule"],
  },
  {
    id: "roster",
    word: "roster",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["勤務名簿、登録メンバー表"],
    pronunciation: "/ˈrɑːstər/",
    exampleSentence: "He is not on the roster this week.",
    exampleTranslationJa: "彼は今週の勤務名簿に入っていない。",
    collocations: ["on the roster", "a duty roster", "the team roster"],
    mnemonic: "誰が働くか・誰が所属するかの一覧。スポーツでは選手登録名簿。",
    relatedWords: ["rota", "list", "schedule"],
  },
  {
    id: "sabbatical",
    word: "sabbatical",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["長期休暇、研究休暇"],
    pronunciation: "/səˈbætɪkl/",
    exampleSentence: "She is on sabbatical for a year to write a book.",
    exampleTranslationJa: "彼女は本を書くため1年の研究休暇中だ。",
    collocations: ["on sabbatical", "take a sabbatical", "a sabbatical year"],
    etymology: "Sabbath(安息日)から。7年ごとの休みという考え方に由来。",
    mnemonic: "Sabbath(安息日)が語源。大学教員が数年に一度取る長期の休み。",
    relatedWords: ["leave", "break", "research"],
  },
  {
    id: "redundancy",
    word: "redundancy",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["人員整理、解雇(英)", "余分、重複"],
    pronunciation: "/rɪˈdʌndənsi/",
    exampleSentence: "The factory announced 200 redundancies.",
    exampleTranslationJa: "その工場は200人の人員整理を発表した。",
    collocations: ["face redundancy", "voluntary redundancy", "redundancy pay"],
    mnemonic: "英で「必要でなくなったので解雇」。be made redundant で「解雇される」。",
    relatedWords: ["layoff", "dismissal", "redundant"],
  },
  {
    id: "demotion",
    word: "demotion",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["降格"],
    pronunciation: "/dɪˈmoʊʃn/",
    exampleSentence: "He accepted a demotion rather than leave the company.",
    exampleTranslationJa: "彼は会社を去るより降格を受け入れた。",
    collocations: ["face demotion", "accept a demotion"],
    wordFormation: "de-(下へ)+ motion(動き)。promotion の反対。",
    mnemonic: "pro(前へ)motion が昇進、de(下へ)motion が降格。",
    relatedWords: ["promotion", "demote", "rank"],
  },
  {
    id: "appraisal",
    word: "appraisal",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["人事評価、査定", "評価、見積もり"],
    pronunciation: "/əˈpreɪzl/",
    exampleSentence: "Every employee has an annual appraisal.",
    exampleTranslationJa: "全社員が年に一度、人事評価を受ける。",
    collocations: ["an annual appraisal", "a performance appraisal", "a critical appraisal"],
    wordFormation: "appraise(値踏みする)+ -al。price と同語根。",
    mnemonic: "price(値段)と同語根。値打ちを見きわめること。",
    relatedWords: ["evaluation", "assessment", "review"],
  },
  {
    id: "minutes",
    word: "minutes",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["議事録"],
    pronunciation: "/ˈmɪnɪts/",
    exampleSentence: "Who is taking the minutes today?",
    exampleTranslationJa: "今日は誰が議事録を取りますか。",
    collocations: ["take the minutes", "approve the minutes", "the minutes of the meeting"],
    mnemonic: "「分」の minutes と同じつづりだが別語。会議の記録は必ず複数形。",
    relatedWords: ["meeting", "record", "agenda"],
  },
  {
    id: "briefing",
    word: "briefing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["説明会、事前説明"],
    pronunciation: "/ˈbriːfɪŋ/",
    exampleSentence: "There is a briefing for all staff at nine.",
    exampleTranslationJa: "9時に全職員向けの説明会がある。",
    collocations: ["a press briefing", "attend a briefing", "a security briefing"],
    wordFormation: "brief(手短に伝える)+ -ing。",
    mnemonic: "brief(短い)が動詞で「要点を伝える」。事後の報告は debriefing。",
    relatedWords: ["brief", "meeting", "update"],
  },
  {
    id: "brainstorm",
    word: "brainstorm",
    level: "B2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["意見を出し合う、ブレインストーミングする"],
    pronunciation: "/ˈbreɪnstɔːrm/",
    exampleSentence: "Let us brainstorm a few ideas before lunch.",
    exampleTranslationJa: "昼食前にいくつか案を出し合いましょう。",
    collocations: ["brainstorm ideas", "a brainstorming session"],
    wordFormation: "brain(頭)+ storm(嵐)。「頭の中の嵐」。",
    mnemonic: "批判せずに数を出す会議のやり方。動詞でそのまま使える。",
    relatedWords: ["idea", "discuss", "session"],
  },
  {
    id: "keynote",
    word: "keynote",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["基調講演", "基調、主題"],
    pronunciation: "/ˈkiːnoʊt/",
    exampleSentence: "She gave the keynote at the annual conference.",
    exampleTranslationJa: "彼女は年次大会で基調講演を行った。",
    collocations: ["a keynote speech", "the keynote speaker", "deliver the keynote"],
    wordFormation: "key(かなめ)+ note(音)。音楽で主音を指す語から。",
    mnemonic: "音楽の「主音」から。全体の調子を決める最初の講演。",
    relatedWords: ["speech", "conference", "address"],
  },
  {
    id: "spreadsheet",
    word: "spreadsheet",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["表計算シート"],
    pronunciation: "/ˈspredʃiːt/",
    exampleSentence: "He keeps the budget in a spreadsheet.",
    exampleTranslationJa: "彼は予算を表計算シートで管理している。",
    collocations: ["a budget spreadsheet", "update the spreadsheet"],
    wordFormation: "spread(広げる)+ sheet(紙)。",
    mnemonic: "もとは会計の「見開き用紙」。それが画面上の表計算になった。",
    relatedWords: ["table", "data", "software"],
  },
  {
    id: "server",
    word: "server",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["サーバー", "給仕係"],
    pronunciation: "/ˈsɜːrvər/",
    exampleSentence: "The server went down for two hours last night.",
    exampleTranslationJa: "昨夜サーバーが2時間停止した。",
    collocations: ["a web server", "the server is down", "a mail server"],
    wordFormation: "serve(供する)+ -er。",
    mnemonic: "サービスを serve(出す)側の機械。飲食店の給仕も server。",
    relatedWords: ["client", "network", "host"],
  },
  {
    id: "upload",
    word: "upload",
    level: "A2",
    partOfSpeech: "動詞・名詞",
    meaningsJa: ["アップロードする"],
    pronunciation: "/ˌʌpˈloʊd/",
    exampleSentence: "Please upload the file before Friday.",
    exampleTranslationJa: "金曜までにそのファイルをアップロードしてください。",
    collocations: ["upload a file", "upload speed", "upload to the server"],
    wordFormation: "up(上へ)+ load(積む)。",
    mnemonic: "自分から向こうへ送るのが upload、こちらに落とすのが download。",
    relatedWords: ["download", "file", "server"],
  },
  {
    id: "bandwidth",
    word: "bandwidth",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["通信容量、帯域幅", "(比喩)対応できる余力"],
    pronunciation: "/ˈbændwɪdθ/",
    exampleSentence: "Video calls use a lot of bandwidth.",
    exampleTranslationJa: "ビデオ通話は通信容量を多く使う。",
    collocations: ["limited bandwidth", "bandwidth usage", "not have the bandwidth"],
    wordFormation: "band(帯)+ width(幅)。",
    mnemonic: "I don't have the bandwidth. で「今それに手が回らない」。",
    relatedWords: ["network", "speed", "capacity"],
  },
  {
    id: "firewall",
    word: "firewall",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["ファイアウォール、防火壁"],
    pronunciation: "/ˈfaɪərwɔːl/",
    exampleSentence: "The firewall blocked the connection.",
    exampleTranslationJa: "ファイアウォールがその接続を遮断した。",
    collocations: ["behind a firewall", "a firewall blocks", "configure the firewall"],
    wordFormation: "fire(火)+ wall(壁)。建物の防火壁が語のもと。",
    mnemonic: "火が広がるのを止める壁。ネットでは不正な通信を止める仕組み。",
    relatedWords: ["security", "network", "block"],
  },
  {
    id: "encryption",
    word: "encryption",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["暗号化"],
    pronunciation: "/ɪnˈkrɪpʃn/",
    exampleSentence: "The app uses end-to-end encryption.",
    exampleTranslationJa: "そのアプリは端末間の暗号化を使っている。",
    collocations: ["end-to-end encryption", "strong encryption", "break the encryption"],
    wordFormation: "en-(〜にする)+ crypt(隠された)。crypt(地下室)と同語根。",
    mnemonic: "crypt(隠された)が語根。読めない形に変えること。動詞は encrypt。",
    relatedWords: ["encrypt", "security", "code"],
  },
  {
    id: "plugin",
    word: "plugin",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["プラグイン、拡張機能"],
    pronunciation: "/ˈplʌɡɪn/",
    exampleSentence: "Install the plugin to enable spell checking.",
    exampleTranslationJa: "つづり確認を有効にするにはそのプラグインを入れてください。",
    collocations: ["install a plugin", "a browser plugin", "disable a plugin"],
    wordFormation: "句動詞 plug in(差し込む)が名詞になった語。",
    mnemonic: "本体に「差し込む(plug in)」あと付けの部品。",
    relatedWords: ["extension", "add-on", "software"],
  },
  {
    id: "cursor",
    word: "cursor",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["カーソル"],
    pronunciation: "/ˈkɜːrsər/",
    exampleSentence: "Move the cursor to the end of the line.",
    exampleTranslationJa: "カーソルを行末まで動かしてください。",
    collocations: ["move the cursor", "the cursor blinks", "place the cursor"],
    etymology: "ラテン語 currere(走る)から。current・course と同語根。",
    mnemonic: "currere(走る)が語根。画面を走り回る印。",
    relatedWords: ["mouse", "pointer", "screen"],
  },
  {
    id: "folder",
    word: "folder",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["フォルダー、書類ばさみ"],
    pronunciation: "/ˈfoʊldər/",
    exampleSentence: "Save the file in the shared folder.",
    exampleTranslationJa: "そのファイルは共有フォルダーに保存してください。",
    collocations: ["a shared folder", "create a folder", "in the folder"],
    wordFormation: "fold(折る)+ -er。紙を折って挟むものから。",
    mnemonic: "紙を折って挟む道具の名が、そのまま画面上の入れ物になった。",
    relatedWords: ["file", "directory", "document"],
  },
  {
    id: "username",
    word: "username",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ユーザー名"],
    pronunciation: "/ˈjuːzərneɪm/",
    exampleSentence: "Enter your username and password.",
    exampleTranslationJa: "ユーザー名とパスワードを入力してください。",
    collocations: ["enter your username", "choose a username", "a valid username"],
    wordFormation: "user(利用者)+ name(名前)。",
    mnemonic: "ログイン画面で必ず出る語。password と対で覚える。",
    relatedWords: ["password", "login", "account"],
  },
  {
    id: "login",
    word: "login",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ログイン、ログイン情報"],
    pronunciation: "/ˈlɔːɡɪn/",
    exampleSentence: "Your login will expire after 30 days.",
    exampleTranslationJa: "ログイン情報は30日で期限切れになります。",
    collocations: ["login details", "a login screen", "a failed login"],
    mnemonic: "名詞は login(一語)、動詞は log in(二語)。書き分けに注意。",
    relatedWords: ["logout", "password", "account"],
  },
  {
    id: "logout",
    word: "logout",
    level: "A2",
    partOfSpeech: "名詞",
    meaningsJa: ["ログアウト"],
    pronunciation: "/ˈlɔːɡaʊt/",
    exampleSentence: "There is a logout button in the top corner.",
    exampleTranslationJa: "右上にログアウトのボタンがあります。",
    collocations: ["a logout button", "automatic logout"],
    mnemonic: "login と同じで、名詞は一語 logout、動詞は log out。",
    relatedWords: ["login", "sign out", "session"],
  },
  {
    id: "malware",
    word: "malware",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["悪意のあるソフト、マルウェア"],
    pronunciation: "/ˈmælwer/",
    exampleSentence: "The laptop was infected with malware.",
    exampleTranslationJa: "そのノートパソコンはマルウェアに感染していた。",
    collocations: ["infected with malware", "malware protection", "detect malware"],
    wordFormation: "mal-(悪い)+ software。",
    mnemonic: "mal(悪い)+ ware。virus はその一種で、malware のほうが広い言い方。",
    relatedWords: ["virus", "security", "hacker"],
  },
  {
    id: "phishing",
    word: "phishing",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["フィッシング詐欺(偽サイトで情報を盗むこと)"],
    pronunciation: "/ˈfɪʃɪŋ/",
    exampleSentence: "That email is a phishing attempt.",
    exampleTranslationJa: "そのメールはフィッシング詐欺の手口だ。",
    collocations: ["a phishing email", "a phishing attack", "fall for phishing"],
    mnemonic: "fishing(釣り)のもじり。えさをまいて情報を釣り上げる。",
    relatedWords: ["scam", "fraud", "malware"],
  },
  {
    id: "hacker",
    word: "hacker",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["ハッカー、不正侵入者"],
    pronunciation: "/ˈhækər/",
    exampleSentence: "Hackers stole thousands of customer records.",
    exampleTranslationJa: "ハッカーが数千件の顧客記録を盗んだ。",
    collocations: ["a computer hacker", "hackers break into", "an ethical hacker"],
    mnemonic: "本来は「技術に詳しい人」。悪用する人は正確には cracker だが、今は hacker が一般的。",
    relatedWords: ["hack", "security", "breach"],
  },
  {
    id: "glitch",
    word: "glitch",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["(一時的な)不具合、故障"],
    pronunciation: "/ɡlɪtʃ/",
    exampleSentence: "A software glitch delayed the flights.",
    exampleTranslationJa: "ソフトの不具合で便が遅れた。",
    collocations: ["a technical glitch", "a software glitch", "a minor glitch"],
    mnemonic: "bug が仕組みの欠陥、glitch は一時的でよく分からない不調。",
    relatedWords: ["bug", "fault", "error"],
  },
  {
    id: "debug",
    word: "debug",
    level: "B2",
    partOfSpeech: "動詞",
    meaningsJa: ["(プログラムの)不具合を取り除く"],
    pronunciation: "/ˌdiːˈbʌɡ/",
    exampleSentence: "It took two days to debug the program.",
    exampleTranslationJa: "そのプログラムの不具合を取り除くのに2日かかった。",
    collocations: ["debug the code", "debug a program", "a debug log"],
    wordFormation: "de-(取り除く)+ bug(虫・不具合)。",
    mnemonic: "初期の計算機に本物の蛾が挟まった逸話から bug。それを取り除くのが debug。",
    relatedWords: ["bug", "fix", "code"],
  },
  {
    id: "algorithm",
    word: "algorithm",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["アルゴリズム、計算手順"],
    pronunciation: "/ˈælɡərɪðəm/",
    exampleSentence: "The algorithm decides what appears in your feed.",
    exampleTranslationJa: "そのアルゴリズムが、あなたの画面に何を出すかを決める。",
    collocations: ["a search algorithm", "the algorithm decides", "a ranking algorithm"],
    etymology: "9世紀の数学者アル・フワーリズミー(al-Khwārizmī)の名から。",
    mnemonic: "9世紀の数学者の名前がもと。決まった手順の集まり。",
    relatedWords: ["formula", "program", "data"],
  },
  {
    id: "dataset",
    word: "dataset",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["データセット、データの集まり"],
    pronunciation: "/ˈdeɪtəset/",
    exampleSentence: "The model was trained on a large dataset.",
    exampleTranslationJa: "そのモデルは大きなデータセットで学習された。",
    collocations: ["a large dataset", "train on a dataset", "an open dataset"],
    wordFormation: "data(データ)+ set(組)。",
    mnemonic: "分析や学習に使う、ひとまとまりのデータ。",
    relatedWords: ["data", "database", "sample"],
  },
  {
    id: "analytics",
    word: "analytics",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["分析、データ分析(の手法)"],
    pronunciation: "/ˌænəˈlɪtɪks/",
    exampleSentence: "Web analytics show most visitors leave in ten seconds.",
    exampleTranslationJa: "アクセス分析によれば、訪問者の大半は10秒で去る。",
    collocations: ["web analytics", "data analytics", "analytics tools"],
    mnemonic: "-ics で終わるので単数扱い。analysis(一件の分析)とは別。",
    relatedWords: ["analysis", "data", "statistics"],
  },
  {
    id: "automation",
    word: "automation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["自動化"],
    pronunciation: "/ˌɔːtəˈmeɪʃn/",
    exampleSentence: "Automation has changed the way factories work.",
    exampleTranslationJa: "自動化は工場の働き方を変えた。",
    collocations: ["office automation", "the rise of automation", "increased automation"],
    wordFormation: "auto-(自ら)+ -mation。",
    mnemonic: "auto(自ら)動くようにすること。動詞は automate。",
    relatedWords: ["automatic", "robot", "efficiency"],
  },
  {
    id: "dormitory",
    word: "dormitory",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["寮、学生寮"],
    pronunciation: "/ˈdɔːrmətɔːri/",
    exampleSentence: "She lived in a dormitory during her first year.",
    exampleTranslationJa: "彼女は1年目は学生寮に住んでいた。",
    collocations: ["a university dormitory", "live in a dormitory"],
    etymology: "ラテン語 dormire(眠る)から。",
    mnemonic: "dormire(眠る)が語根。口語では dorm と短く言う。",
    relatedWords: ["hostel", "campus", "accommodation"],
  },
  {
    id: "syllabus",
    word: "syllabus",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["授業計画、シラバス"],
    pronunciation: "/ˈsɪləbəs/",
    exampleSentence: "That topic is not on the syllabus.",
    exampleTranslationJa: "その話題は授業計画に入っていない。",
    collocations: ["on the syllabus", "cover the syllabus", "a course syllabus"],
    mnemonic: "複数形は syllabuses または syllabi。curriculum は学校全体、syllabus は科目ごと。",
    relatedWords: ["curriculum", "course", "outline"],
  },
  {
    id: "tutorial",
    word: "tutorial",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["少人数の指導、チュートリアル", "手順の解説"],
    pronunciation: "/tuːˈtɔːriəl/",
    exampleSentence: "I watched a tutorial on how to change a tyre.",
    exampleTranslationJa: "タイヤの替え方の解説動画を見た。",
    collocations: ["an online tutorial", "attend a tutorial", "a video tutorial"],
    wordFormation: "tutor(個別指導者)+ -ial。",
    mnemonic: "大学では少人数のゼミ、ネットでは「やり方の解説」。",
    relatedWords: ["tutor", "lesson", "guide"],
  },
  {
    id: "coursework",
    word: "coursework",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["平常課題(試験以外の提出物)"],
    pronunciation: "/ˈkɔːrswɜːrk/",
    exampleSentence: "Half the marks come from coursework.",
    exampleTranslationJa: "評点の半分は平常課題から出る。",
    collocations: ["submit coursework", "coursework and exams", "assessed coursework"],
    wordFormation: "course(科目)+ work(課題)。",
    mnemonic: "試験(exam)ではないほうの評価。レポートや実習をまとめて指す。",
    relatedWords: ["assignment", "exam", "essay"],
  },
  {
    id: "dissertation",
    word: "dissertation",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["学位論文"],
    pronunciation: "/ˌdɪsərˈteɪʃn/",
    exampleSentence: "He is writing a dissertation on urban planning.",
    exampleTranslationJa: "彼は都市計画についての学位論文を書いている。",
    collocations: ["write a dissertation", "a doctoral dissertation", "a dissertation on"],
    mnemonic: "英では学部・修士が dissertation、博士が thesis。米では逆になることが多い。",
    relatedWords: ["thesis", "research", "degree"],
  },
  {
    id: "plagiarism",
    word: "plagiarism",
    level: "B2",
    partOfSpeech: "名詞",
    meaningsJa: ["盗用、剽窃(ひょうせつ)"],
    pronunciation: "/ˈpleɪdʒərɪzəm/",
    exampleSentence: "The university has strict rules on plagiarism.",
    exampleTranslationJa: "その大学は盗用について厳しい規則を持つ。",
    collocations: ["accused of plagiarism", "avoid plagiarism", "a plagiarism checker"],
    etymology: "ラテン語 plagiarius(誘拐犯)から。「人の子をさらう者」。",
    mnemonic: "語源は「誘拐犯」。他人の文章をさらってくること。動詞は plagiarise。",
    relatedWords: ["copy", "citation", "originality"],
  },
  {
    id: "diploma",
    word: "diploma",
    level: "B1",
    partOfSpeech: "名詞",
    meaningsJa: ["修了証書、ディプロマ"],
    pronunciation: "/dɪˈploʊmə/",
    exampleSentence: "She earned a diploma in nursing.",
    exampleTranslationJa: "彼女は看護の修了証を取得した。",
    collocations: ["a diploma in", "earn a diploma", "a high school diploma"],
    etymology: "ギリシャ語 diploma(二つ折りの紙)から。diplomat と同語根。",
    mnemonic: "「二つ折りの公文書」が語源。diplomat(外交官)も同じ語から。",
    relatedWords: ["degree", "certificate", "qualification"],
  },
  {
    id: "postgraduate",
    word: "postgraduate",
    level: "B2",
    partOfSpeech: "名詞・形容詞",
    meaningsJa: ["大学院生", "大学院の"],
    pronunciation: "/ˌpoʊstˈɡrædʒuət/",
    exampleSentence: "She is doing postgraduate research in physics.",
    exampleTranslationJa: "彼女は物理学で大学院の研究をしている。",
    collocations: ["a postgraduate student", "postgraduate study", "a postgraduate degree"],
    wordFormation: "post-(後)+ graduate(卒業する)。",
    mnemonic: "post(後)+ graduate(卒業)。学部卒業のあと。米では graduate student。",
    relatedWords: ["undergraduate", "graduate", "degree"],
  },
]
