import type { GrammarUnit } from '../../types'

// U21 動名詞・不定詞の発展 — 意味が変わる動詞、動詞 + 目的語 + to不定詞、形容詞 + 不定詞

export const u21: GrammarUnit = {
  id: 'u21',
  level: 'B1+',
  title: '動名詞・不定詞の発展',
  lessons: [
    {
      id: 'u21-l1',
      unitId: 'u21',
      level: 'B1+',
      title: '意味が変わる動詞',
      objective: 'stop / remember / forget / try のあとに to不定詞と動名詞のどちらを選ぶかで変わる意味を理解し、伝えたい内容に合わせて正しく使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u10-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '行動と記憶・目的の関係を見る',
          body:
            'stop / remember / forget / try は、**to do と -ing で意味が変わる**動詞です。まず remember で、行動と記憶の順序を比べましょう。\n\n- I remember **locking** the door. → 鍵をかけた記憶があります。行動をあとから思い出しています。\n- I must remember **to lock** the door. → 忘れずに鍵をかけなければなりません。行動をこれからする必要があります。\n\nただし、「-ing は必ず過去、to do は必ず未来」というルールではありません。Try **restarting** your phone. は、これから再起動を試す提案です。**動詞ごとの意味と、後ろの行動との関係**をセットで確認しましょう。',
        },
        {
          type: 'contrast',
          title: 'remember to do vs remember doing',
          left: {
            label: 'remember to do(これから)',
            items: [
              { en: 'Please remember to bring your passport tomorrow.', ja: '明日は忘れずにパスポートを持ってきてください。', highlight: 'remember to bring' },
              { en: 'I remembered to send the invoice this morning.', ja: '今朝、忘れずに請求書を送りました。', highlight: 'remembered to send' },
            ],
            pointJa: 'これからすべきことを覚えている → 忘れずに〜する',
          },
          right: {
            label: 'remember doing(過去)',
            items: [
              { en: 'I remember visiting this town as a child.', ja: '子どものころにこの町を訪れたのを覚えています。', highlight: 'remember visiting' },
              { en: "I don't remember saying that.", ja: 'そんなことを言った覚えはありません。', highlight: 'remember saying' },
            ],
            pointJa: '過去にしたことの記憶がある → 〜したことを覚えている',
          },
          note: 'remember のあとの形が、話の向き(未来か過去か)を決めます。forget も同じ対比です。',
        },
        {
          type: 'table',
          title: '意味が変わる4動詞の一覧',
          headers: ['動詞', '+ to do', '+ -ing'],
          rows: [
            ['remember', '忘れずに〜する(これからのこと)', '〜したことを覚えている(過去のこと)'],
            ['forget', '〜し忘れる', '〜したことを忘れる'],
            ['stop', '〜するために手を止める・立ち止まる', '〜するのをやめる'],
            ['try', '〜しようと努力する(難しいこと)', '試しに〜してみる(気軽な実験)'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: "Don't forget to take your medicine after dinner.", ja: '夕食後に薬を飲むのを忘れないでください。', highlight: 'forget to take' },
            { en: "I'll never forget seeing the northern lights in Canada.", ja: 'カナダでオーロラを見たことは決して忘れません。', highlight: 'forget seeing', note: '「〜したことを忘れる」は never forget doing の形でよく使います。' },
            { en: 'She stopped working at six and went home.', ja: '彼女は6時に仕事をやめて帰宅しました。', highlight: 'stopped working' },
            { en: 'On the way home, we stopped to look at the ocean.', ja: '帰り道、海を見るために立ち寄りました。', highlight: 'stopped to look' },
            { en: 'I tried to open the window, but it was stuck.', ja: '窓を開けようとしましたが、動きませんでした。', highlight: 'tried to open', note: '努力したができなかった、という文脈の try to do です。' },
            { en: 'Try adding a little salt if the soup tastes flat.', ja: 'スープの味が物足りなければ、試しに塩を少し足してみてください。', highlight: 'Try adding' },
          ],
        },
        {
          type: 'explanation',
          title: 'try は「努力」か「実験」か',
          body:
            '**try to do は達成を目指すこと、try doing は方法として試すこと**に注目します。\n\n- I tried to move the piano, but it was too heavy. → 動かそうとしましたが、重すぎました。\n- I tried moving the piano, but the room still looked small. → 試しに動かしてみましたが、部屋は狭く見えたままでした。\n\n最初の文で失敗したと分かるのは、but it was too heavy という続きがあるためです。**try to do だけでは成功・失敗は決まりません**。try doing も、簡単な動作にしか使えないわけではありません。「達成を目指す」か「効果を確かめる」かが違いです。',
        },
      ],
      quiz: [
        {
          id: 'u21-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Please remember ___ the lights when you leave the office.',
          sentenceJa: 'オフィスを出るときは、忘れずに電気を消してください。',
          choices: ['turning off', 'to turn off', 'turn off', 'turned off'],
          correctIndex: 1,
          explanation: 'これからする行動を「忘れずにしてください」と頼んでいるので、remember to do を使います。',
          choiceNotes: ['remember doing は「〜したことを覚えている」で、過去の記憶の話になってしまいます。', null, 'remember のあとに動詞の原形を直接は続けられません。', '過去形は続けられません。'],
          audioEn: 'Please remember to turn off the lights when you leave the office.',
        },
        {
          id: 'u21-l1-q2',
          prompt: 'この文の意味として正しいものを選んでください。',
          sentence: 'I remember meeting her at a conference two years ago.',
          choices: ['2年前の会議で彼女に会ったことを覚えている。', '2年前の会議で忘れずに彼女に会った。', 'これから会議で彼女に会う予定を覚えている。', '彼女に会ったかどうか思い出せない。'],
          correctIndex: 0,
          explanation: 'remember doing は「(過去に)〜したことを覚えている」です。two years ago という過去の時点とも一致します。',
          choiceNotes: [null, '「忘れずに〜した」なら remembered to meet の形になります。', 'これからのことなら remember to meet です。', "思い出せないなら I don't remember や I can't remember を使います。"],
          audioEn: 'I remember meeting her at a conference two years ago.',
        },
        {
          id: 'u21-l1-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: "The Wi-Fi isn't working. Try ___ the router.",
          sentenceJa: 'Wi-Fiがつながりません。試しにルーターを再起動してみてください。',
          choices: ['restart', 'to restart', 'restarting', 'restarted'],
          correctIndex: 2,
          explanation: '解決策として「試しにやってみて」と提案しているので try doing を使います。再起動すること自体は簡単で、努力は必要ありません。',
          choiceNotes: ['try のあとに動詞の原形を直接は続けられません。', 'try to do は「(難しいことを)しようと努力する」で、気軽な提案には合いません。', null, '過去形は続けられません。'],
          audioEn: "The Wi-Fi isn't working. Try restarting the router.",
        },
        {
          id: 'u21-l1-q4',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼は健康のために甘いものを食べるのをやめました」と言いたいとき。',
          choices: ['He stopped to eat sweets for his health.', 'He stopped eating sweets for his health.', 'He stopped eat sweets for his health.', 'He stopped to eating sweets for his health.'],
          correctIndex: 1,
          explanation: '「〜するのをやめる」は stop doing です。stop to do だと「食べるために手を止めた」という別の意味になってしまいます。',
          choiceNotes: ['stop to do は「甘いものを食べるために立ち止まった」という意味になります。', null, 'stop のあとに動詞の原形を直接は続けられません。', 'to と -ing は組み合わせられません。'],
          audioEn: 'He stopped eating sweets for his health.',
        },
      ],
      summary: [
        'remember / forget / stop / try は、to不定詞と -ing のどちらを続けるかで意味が変わる。',
        'to do はこれからすること: remember to do(忘れずに〜する)/ forget to do(〜し忘れる)/ stop to do(〜するために手を止める)。',
        '-ing はすでにしたこと: remember doing(〜した記憶がある)/ stop doing(〜するのをやめる)。',
        'try to do は「〜しようと努力する」、try doing は「試しに〜してみる」。',
      ],
    },
    {
      id: 'u21-l2',
      unitId: 'u21',
      level: 'B1+',
      title: '動詞 + 目的語 + to不定詞',
      objective: 'want / ask / tell / allow などのあとに「人 + to不定詞」を続けて、「人に〜してほしい」「人に〜するよう頼む」と言えるようになります。',
      minutes: 10,
      prereqs: ['u21-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '「人に〜してほしい」は 動詞 + 人 + to do',
          body:
            '「あなたに来てほしい」「彼に手伝うよう頼んだ」のように、**他の人の行動**について言うときは、動詞のあとに「人 + to不定詞」を続けます。\n\n- I want **you to come** to the party.(あなたにパーティーに来てほしい)\n- She asked **me to help** her.(彼女は私に手伝ってくれるよう頼んだ)\n\n日本人学習者に多い誤りが「× I want that you come.」です。**want は that節をとれません**。「人に〜してほしい」は必ず want + 人 + to do の形にします。',
        },
        {
          type: 'structure',
          title: '語順',
          parts: [
            { label: '主語', text: 'I' },
            { label: '動詞', text: 'want' },
            { label: '人(行動する人)', text: 'you' },
            { label: 'to不定詞(してほしいこと)', text: 'to come' },
          ],
          caption: 'to のあとの行動をするのは、主語ではなく直前の「人」です。',
        },
        {
          type: 'table',
          title: 'このパターンをとる代表的な動詞',
          headers: ['表現', '意味', '例'],
          rows: [
            ['want 人 to do', '人に〜してほしい', 'I want him to stay.'],
            ['ask 人 to do', '人に〜するよう頼む', 'She asked me to wait.'],
            ['tell 人 to do', '人に〜するよう言う', 'He told us to be quiet.'],
            ['allow 人 to do', '人が〜するのを許可する', 'They allowed her to leave early.'],
            ['advise 人 to do', '人に〜するよう助言する', 'The doctor advised him to rest.'],
            ['remind 人 to do', '人に〜するのを思い出させる', 'Remind me to call her.'],
            ['expect 人 to do', '人が〜すると思っている', 'I expect them to arrive soon.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I want you to check this report by Friday.', ja: '金曜日までにこの報告書を確認してほしいのですが。', highlight: 'want you to check' },
            { en: 'She asked the staff to bring another chair.', ja: '彼女はスタッフに椅子をもう1脚持ってくるよう頼みました。', highlight: 'asked the staff to bring' },
            { en: 'My boss told me to take a day off.', ja: '上司は私に1日休みを取るように言いました。', highlight: 'told me to take' },
            { en: "My parents didn't allow me to have a smartphone until high school.", ja: '両親は高校までスマートフォンを持たせてくれませんでした。', highlight: 'allow me to have' },
            { en: 'Please remind me to buy milk on the way home.', ja: '帰りに牛乳を買うのを思い出させてください。', highlight: 'remind me to buy' },
          ],
        },
        {
          type: 'explanation',
          title: '「〜しないように」は not を to の前に',
          body:
            '「人に〜しないように頼む・言う」ときは、**not を to の直前**に置きます。\n\n- She asked me **not to tell** anyone.(誰にも言わないよう頼んだ)\n- The doctor told him **not to skip** breakfast.(朝食を抜かないように言った)\n\nもう1つの注意点は say との違いです。tell はこのパターンをとれますが、**say + 人 + to do という形はありません**。「人に〜するよう言う」は tell を使いましょう。',
        },
      ],
      quiz: [
        {
          id: 'u21-l2-q1',
          prompt: '空所に入る語句を選んでください。',
          sentence: 'I want ___ the documents before the meeting.',
          sentenceJa: 'あなたには会議の前にその書類を読んでおいてほしいです。',
          choices: ['you to read', 'that you read', 'you reading', 'to you read'],
          correctIndex: 0,
          explanation: '「人に〜してほしい」は want + 人 + to不定詞の語順です。',
          choiceNotes: [null, 'want は that節をとれません。', 'want は「人 + -ing」の形をとりません。人 + to do にします。', 'to は人のあとに置きます。to you read という語順はありません。'],
          audioEn: 'I want you to read the documents before the meeting.',
        },
        {
          id: 'u21-l2-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「先生は生徒たちに辞書を持ってくるように言いました」と言いたいとき。',
          choices: ['The teacher said the students to bring dictionaries.', 'The teacher told the students to bring dictionaries.', 'The teacher told to the students bring dictionaries.', 'The teacher told the students bringing dictionaries.'],
          correctIndex: 1,
          explanation: '「人に〜するよう言う」は tell + 人 + to do です。say はこの形をとれません。',
          choiceNotes: ['say + 人 + to do という形はありません。tell を使います。', null, 'tell のあとは to を挟まずに人を置きます。', 'tell 人 のあとは to不定詞です。-ing は続けられません。'],
          audioEn: 'The teacher told the students to bring dictionaries.',
        },
        {
          id: 'u21-l2-q3',
          prompt: '空所に入る語句を選んでください。',
          sentence: 'She asked me ___ anyone about the surprise party.',
          sentenceJa: '彼女はサプライズパーティーのことを誰にも言わないよう私に頼みました。',
          choices: ['not to tell', 'to not telling', "don't tell", 'not telling'],
          correctIndex: 0,
          explanation: '「〜しないように頼む」は ask + 人 + not to do の形で、not は to の直前に置きます。',
          choiceNotes: [null, 'to のあとは動詞の原形です。-ing は続けられません。', "don't は文全体の動詞を否定する形で、この位置には置けません。", 'ask 人 のあとは to不定詞が必要です。'],
          audioEn: 'She asked me not to tell anyone about the surprise party.',
        },
        {
          id: 'u21-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['My parents allowed me to study abroad.', 'The doctor advised her to get more sleep.', 'She wants that I call her tonight.', 'I expect the train to be crowded at this hour.'],
          correctIndex: 2,
          explanation: 'want は that節をとれない動詞です。She wants me to call her tonight. のように want + 人 + to do の形にします。',
          choiceNotes: ['正しい文です。allow 人 to do の形です。', '正しい文です。advise 人 to do の形です。', null, '正しい文です。expect は人だけでなく「もの + to do」も続けられます。'],
          audioEn: 'She wants me to call her tonight.',
        },
      ],
      summary: [
        '「人に〜してほしい・するよう頼む」は 動詞 + 人 + to不定詞。to のあとの行動をするのは直前の「人」。',
        'want / ask / tell / allow / advise / remind / expect がこのパターンをとる。',
        '「〜しないように」は not to do。not は to の直前に置く。',
        'want は that節をとれない(× I want that you come.)。say + 人 + to do という形もない。',
      ],
    },
    {
      id: 'u21-l3',
      unitId: 'u21',
      level: 'B1+',
      title: '形容詞 + 不定詞 / It is ... to do',
      objective: '仮主語の It is ... to do と、easy to use のような「形容詞 + to不定詞」を使って、感想や評価を自然に表現できるようになります。',
      minutes: 10,
      prereqs: ['u21-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '長い主語は it に任せる',
          body:
            '「毎日英語を勉強することは大切です」は、**It is important to study English every day.** と言えます。先に「大切です」と評価を伝え、そのあとに内容を続ける形です。\n\nこの it は具体的な物を指す「それ」ではありません。主語の位置を埋め、to以下の長い内容を文の後ろに置くために使っています。\n\n**To study English every day is important.** も正しい文です。行動自体を主語として取り上げたいときに使えます。まずは会話で使いやすい It is ... to do の形から練習しましょう。',
        },
        {
          type: 'structure',
          title: 'It is ... to do の語順',
          parts: [
            { label: '仮主語', text: 'It' },
            { label: 'be動詞', text: 'is' },
            { label: '形容詞', text: 'important' },
            { label: '本当の主語', text: 'to study English' },
          ],
          caption: 'it が先に席だけ確保して、中身(to以下)はあとから届くイメージです。',
        },
        {
          type: 'explanation',
          title: '「誰にとって」は for 人',
          body:
            '「私にとって難しい」「初心者にとって簡単だ」のように**動作をする人**を示したいときは、**for 人** を to の前に入れます。\n\n- It is difficult **for me** to get up before six.(私には6時前に起きるのは難しい)\n- It was easy **for her** to pass the test.(彼女にはテストに合格するのは簡単だった)\n\nkind / nice / careless など、**その行動から人の性質を評価する形容詞**では of を使います。ほめる場合だけでなく、注意や批判にも使えます。\n\n- It was kind **of you** to help me.(手伝ってくれるなんて優しいですね)',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'It is important to back up your files regularly.', ja: 'ファイルを定期的にバックアップすることは大切です。', highlight: 'It is important to back up' },
            { en: 'It was hard for me to explain the problem in English.', ja: 'その問題を英語で説明するのは私には大変でした。', highlight: 'for me to explain' },
            { en: "It's dangerous to use your phone while driving.", ja: '運転中に携帯を使うのは危険です。', highlight: "It's dangerous to use" },
            { en: 'It was kind of you to carry my bags.', ja: '荷物を運んでくださってありがとうございました。', highlight: 'kind of you to carry' },
            { en: 'This app is easy to use on a small screen.', ja: 'このアプリは小さな画面でも使いやすいです。', highlight: 'easy to use' },
          ],
        },
        {
          type: 'explanation',
          title: 'easy to use 型と happy to do 型',
          body:
            'it を使わずに、**ふつうの主語 + be + 形容詞 + to do** の形もよく使います。2つのタイプがあります。\n\n**1. easy to use 型(ものの性質)**\n\n- This app **is easy to use**.(このアプリは使いやすい)\n- His handwriting **is hard to read**.(彼の字は読みにくい)\n\n主語(this app)は to以下の動詞の**目的語**にあたるので、× easy to use it のように it を重ねてはいけません。\n\n**2. happy to do 型(感情の理由)**\n\n- I was **happy to see** her again.(また彼女に会えてうれしかった)\n- We were **surprised to hear** the news.(その知らせを聞いて驚きました)\n\nhappy / glad / sorry / surprised など感情の形容詞のあとの to do は、「〜して」という**感情の理由**を表します。',
        },
        {
          type: 'table',
          title: '3つの型とよく使う形容詞',
          headers: ['型', 'よく使う形容詞', '例'],
          rows: [
            ['It is ... to do', 'important / necessary / difficult / impossible', 'It is impossible to finish today.'],
            ['もの + be + ... to do', 'easy / hard / safe / dangerous', 'This question is hard to answer.'],
            ['感情の形容詞 + to do', 'happy / glad / sorry / surprised', 'I was glad to see her again.'],
          ],
        },
      ],
      quiz: [
        {
          id: 'u21-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'It is impossible ___ this report by noon.',
          sentenceJa: '正午までにこの報告書を終えるのは不可能です。',
          choices: ['finish', 'to finish', 'finishing', 'finished'],
          correctIndex: 1,
          explanation: '仮主語 It が指す「本当の主語」は to不定詞で表します。It is 形容詞 to do が基本の形です。',
          choiceNotes: ['It is 形容詞 のあとに動詞の原形を直接は続けられません。', null, 'この構文の本当の主語は to不定詞で表すのが基本の形です。', '過去分詞では「終えること」という意味になりません。'],
          audioEn: 'It is impossible to finish this report by noon.',
        },
        {
          id: 'u21-l3-q2',
          prompt: '空所に入る語句を選んでください。',
          sentence: 'It was difficult ___ the instructions.',
          sentenceJa: '私にはその説明書を理解するのが難しかったです。',
          choices: ['for me to understand', 'to me for understand', 'for me understanding', 'of me to understand'],
          correctIndex: 0,
          explanation: '「〜にとって」と動作をする人を示すときは、for 人 を to不定詞の直前に置きます。',
          choiceNotes: [null, 'この語順はありません。for 人 + to do の順にします。', 'for 人 のあとは to不定詞です。-ing は続けられません。', 'of 人 は kind / nice など人柄をほめる形容詞のときだけ使います。difficult には for を使います。'],
          audioEn: 'It was difficult for me to understand the instructions.',
        },
        {
          id: 'u21-l3-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「この地図アプリはとても使いやすい」と言いたいとき。',
          choices: ['This map app is very easy to use.', 'This map app is very easy to use it.', 'This map app is very easy using.', 'This map app is very easy for use.'],
          correctIndex: 0,
          explanation: 'easy to use 型では、主語の this map app が use の目的語を兼ねるので、to use のあとに it を繰り返しません。',
          choiceNotes: [null, '主語がすでに use の目的語にあたるので、it を重ねると誤りです。', 'easy のあとは to不定詞です。', 'for のあとに動詞の原形は置けません。to use にします。'],
          audioEn: 'This map app is very easy to use.',
        },
        {
          id: 'u21-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ["I'm glad to hear that you passed the exam.", 'It was kind of you to drive me home.', 'It is dangerous to swim in this river.', 'It is hard for foreigners understand Japanese jokes.'],
          correctIndex: 3,
          explanation: '仮主語の構文では for 人 のあとに to不定詞が必要です。It is hard for foreigners to understand Japanese jokes. が正しい形です。',
          choiceNotes: ['正しい文です。感情の理由を表す to hear です。', '正しい文です。人柄をほめる kind には of 人 を使います。', '正しい文です。It is 形容詞 to do の形です。', null],
          audioEn: 'It is hard for foreigners to understand Japanese jokes.',
        },
      ],
      summary: [
        '長い to不定詞の主語は仮主語 it に置き換え、It is 形容詞 to do の形にする。',
        '動作をする人は for 人 で示す。kind / nice など人柄の形容詞のときだけ of 人。',
        'easy to use 型では主語が to以下の目的語を兼ねるので、目的語を繰り返さない(× easy to use it)。',
        'happy / glad / sorry など感情の形容詞 + to do は「〜して」という感情の理由を表す。',
      ],
    },
  ],
}
