import type { GrammarUnit } from '../../types'

// U09 助動詞の基礎

export const u09: GrammarUnit = {
  id: 'u09',
  level: 'A2+',
  title: '助動詞の基礎',
  lessons: [
    {
      id: 'u09-l1',
      unitId: 'u09',
      level: 'A2+',
      title: 'can / could',
      objective: 'can / could で能力・許可・依頼を表し、助動詞に共通するルール(あとは原形・do 不要)を使いこなせるようになります。',
      minutes: 10,
      prereqs: ['u01-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '助動詞は動詞に「気持ち」を足す',
          body:
            'can や must のような**助動詞**は、動詞の前に置いて「できる」「しなければならない」といった話し手の気持ちやニュアンスを足す言葉です。\n\nすべての助動詞に共通する3つのルールがあります。\n\n- あとに続く動詞は必ず**原形**: She can swim.(× swims)\n- 主語が he / she / it でも助動詞自体に -s は付かない(× cans)\n- 否定文・疑問文は do / does を使わず、**助動詞が自分で作る**: He can\'t swim. / Can he swim?\n\nbe動詞と同じく「自分で否定・疑問を作れる」仲間だと考えると整理しやすいです。',
        },
        {
          type: 'table',
          title: 'can / could の意味まとめ',
          headers: ['形', '働き', '例'],
          rows: [
            ['can', '能力(〜できる)', 'She can drive.'],
            ['can', '許可(〜してもよい)', 'You can sit here.'],
            ['Can you ...?', '気軽な依頼', 'Can you open the door?'],
            ['could', '過去の能力(〜できた)', 'I could run fast at school.'],
            ['Could you ...?', '丁寧な依頼', 'Could you wait a moment?'],
          ],
        },
        {
          type: 'structure',
          title: '助動詞の文の骨組み',
          parts: [
            { label: '主語', text: 'She' },
            { label: '助動詞', text: 'can' },
            { label: '動詞は必ず原形', text: 'drive' },
          ],
          caption: '主語が she でも助動詞に -s は付かず(× cans)、後ろの動詞も原形のままです(× can drives)。疑問文は Can she drive? と助動詞を主語の前に出します。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'My daughter can ride a bike now.', ja: '娘は今では自転車に乗れます。', highlight: 'can ride' },
            { en: 'You can use my charger.', ja: '私の充電器を使っていいですよ。', highlight: 'can use', note: '許可を与える can です。' },
            { en: "I can't hear you well.", ja: 'あなたの声がよく聞こえません。', highlight: "can't hear" },
            { en: 'Can you help me with this box?', ja: 'この箱を運ぶのを手伝ってくれますか。', highlight: 'Can you', note: '友達や家族への気軽な依頼です。' },
            { en: 'Could you say that again, please?', ja: 'もう一度言っていただけますか。', highlight: 'Could you', note: 'Can you より丁寧な依頼になります。' },
          ],
        },
        {
          type: 'explanation',
          title: 'could の2つの顔',
          body:
            'could は can の過去形として「〜できた」を表します。\n\n- When I was a child, I could run for hours.(子どものころは何時間でも走れました)\n\nもう1つ大切なのが、**丁寧な依頼**の Could you ...? です。これは過去の話ではなく、「〜していただけますか」と今お願いする表現です。\n\n- Can you ...?(気軽な頼み方: 友達・家族向け)\n- Could you ...?(丁寧な頼み方: 店員さん・上司・初対面の人にも安心して使える)',
        },
      ],
      quiz: [
        {
          id: 'u09-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My grandfather ___ very fast when he was young.',
          sentenceJa: '祖父は若いころ、とても速く泳げました。',
          choices: ['can swim', 'could swim', 'could swam', 'can swims'],
          correctIndex: 1,
          explanation: 'when he was young とあるので過去の能力です。could + 原形で「〜できた」を表します。',
          choiceNotes: ['can は現在の能力に使います。ここは過去の話です。', null, '助動詞のあとは原形です。過去形 swam は続けられません。', '助動詞のあとの動詞に -s は付けません。時制も合っていません。'],
          audioEn: 'My grandfather could swim very fast when he was young.',
        },
        {
          id: 'u09-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼女はピアノが弾けます」と言いたいとき。',
          choices: ['She cans play the piano.', 'She can plays the piano.', 'She can play the piano.', 'She can to play the piano.'],
          correctIndex: 2,
          explanation: '助動詞 can のあとは動詞の原形です。can にも動詞にも -s は付けません。',
          choiceNotes: ['助動詞 can に三単現の -s は付きません。', '助動詞のあとの動詞は原形です。plays にはしません。', null, '助動詞のあとに to は不要です。can play の形で使います。'],
          audioEn: 'She can play the piano.',
        },
        {
          id: 'u09-l1-q3',
          prompt: '丁寧な依頼として正しい文を選んでください。',
          sentenceJa: 'お店で「袋をもう1枚いただけますか」とお願いしたいとき。',
          choices: ['Could you gave me another bag?', 'Could you give me another bag?', 'Do you could give me another bag?', 'You could give me another bag?'],
          correctIndex: 1,
          explanation: 'Could you + 原形で丁寧な依頼になります。could を使っていますが、過去の意味はありません。',
          choiceNotes: ['助動詞のあとは原形です。gave は使えません。', null, '助動詞の疑問文に do は使いません。Could を主語の前に出します。', '疑問文の語順になっていないので、依頼として伝わりません。'],
          audioEn: 'Could you give me another bag?',
        },
        {
          id: 'u09-l1-q4',
          prompt: '正しい否定文を選んでください。',
          sentenceJa: '「彼は今日の会議に出られません」と言いたいとき。',
          choices: ["He doesn't can come to the meeting today.", "He can't come to the meeting today.", 'He cans not come to the meeting today.', "He isn't can come to the meeting today."],
          correctIndex: 1,
          explanation: "助動詞は自分で否定文を作ります。can の否定は cannot(can't)です。",
          choiceNotes: ['助動詞の否定に do は使いません。can 自身が否定文を作ります。', null, "can に -s は付きません。否定形は cannot(can't)です。", 'be動詞と can を並べることはできません。'],
          audioEn: "He can't come to the meeting today.",
        },
      ],
      summary: [
        '助動詞のあとの動詞は必ず原形。助動詞自体に -s も付かない。',
        'can は能力(〜できる)と許可(〜してもよい)、Can you ...? は気軽な依頼。',
        'could は過去の能力のほか、Could you ...? で丁寧な依頼を表す。',
        '否定・疑問は do / does を使わず、助動詞が自分で作る。',
      ],
    },
    {
      id: 'u09-l2',
      unitId: 'u09',
      level: 'A2+',
      title: 'must / have to',
      objective: "must と have to で義務を表し、意味が正反対になる mustn't(禁止)と don't have to(不要)を正しく使い分けられるようになります。",
      minutes: 12,
      prereqs: ['u09-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '2つの「しなければならない」',
          body:
            'must と have to はどちらも「〜しなければならない」という義務を表します。多くの場面でどちらも使えますが、ニュアンスに違いがあります。\n\n- **must**: 話し手が「絶対に必要だ」と感じている強い義務。規則・掲示・注意書きでもよく使われます\n- **have to**: 状況や決まりなど、周りの事情からくる義務。日常会話ではこちらが圧倒的によく使われます\n\nまずは「会話では have to、強いルールは must」という感覚で大丈夫です。本当に注意が必要なのは**否定文**で、このレッスンの後半で扱います。',
        },
        {
          type: 'explanation',
          title: 'have to は一般動詞のように変化する',
          body:
            'must は助動詞なので形が変わりませんが、have to の have は一般動詞と同じように変化します。\n\n- 三単現: She **has to** work on Saturdays.\n- 疑問文: **Do** you **have to** leave now?(must の疑問文はかたい響きなので、日常では Do you have to ...? が普通です)\n- 過去: must には過去形がないので、**had to** を使います: I **had to** stay home yesterday.',
        },
        {
          type: 'table',
          title: 'must と have to の形の整理',
          headers: ['', 'must', 'have to'],
          rows: [
            ['現在の肯定', 'You must go.', 'You have to go.(三単現は has to)'],
            ['疑問文', 'ほとんど使わない', 'Do you have to go?'],
            ['過去', 'なし(had to を使う)', 'I had to go.'],
            ['否定の意味', '禁止(してはいけない)', '不要(しなくてもよい)'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'You must wear a helmet on this site.', ja: 'この現場ではヘルメットを着用しなければなりません。', highlight: 'must wear', note: 'ルール・掲示に使われる強い義務です。' },
            { en: 'I have to get up early tomorrow.', ja: '明日は早起きしなければなりません。', highlight: 'have to' },
            { en: 'She has to take medicine every day.', ja: '彼女は毎日薬を飲まなければなりません。', highlight: 'has to', note: '主語が3人称単数なら has to です。' },
            { en: 'Do we have to finish this today?', ja: 'これを今日終わらせないといけませんか。', highlight: 'Do we have to', note: '疑問文は do / does で作ります。' },
            { en: 'I had to wait for an hour at the clinic.', ja: '病院で1時間待たなければなりませんでした。', highlight: 'had to', note: 'must に過去形はないので had to を使います。' },
          ],
        },
        {
          type: 'contrast',
          title: "mustn't と don't have to は正反対",
          left: {
            label: "mustn't = してはいけない(禁止)",
            items: [
              { en: "You mustn't use your phone during the test.", ja: '試験中に携帯を使ってはいけません。', highlight: "mustn't use" },
              { en: "You mustn't tell anyone about this.", ja: 'このことは誰にも言ってはいけません。', highlight: "mustn't tell" },
            ],
            pointJa: '「する」という選択肢がない。強い禁止。',
          },
          right: {
            label: "don't have to = しなくてもよい(不要)",
            items: [
              { en: "You don't have to wear a tie at our office.", ja: 'うちの会社ではネクタイをしなくてもよいです。', highlight: "don't have to wear" },
              { en: "She doesn't have to come to the morning meeting.", ja: '彼女は朝の会議に出なくてもよいです。', highlight: "doesn't have to come" },
            ],
            pointJa: 'してもしなくてもよい。義務がないだけ。',
          },
          note: '肯定文ではほぼ同じ意味の must と have to が、否定文では「禁止」と「不要」に分かれます。日本人学習者が最も混同しやすいポイントです。',
        },
      ],
      quiz: [
        {
          id: 'u09-l2-q1',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: "You don't have to bring lunch tomorrow.",
          choices: ['明日は昼食を持ってきてはいけません。', '明日は昼食を持ってこなくてもよいです。', '明日は昼食を持ってこなければなりません。', '明日は昼食を持ってくるかもしれません。'],
          correctIndex: 1,
          explanation: "don't have to は「しなくてもよい」という不要の意味です。禁止ではありません。",
          choiceNotes: ["それは You mustn't bring lunch. の意味です。don't have to に禁止の意味はありません。", null, 'それは肯定文 must / have to の意味です。', "「〜かもしれない」は may / might の意味で、don't have to にはありません。"],
          audioEn: "You don't have to bring lunch tomorrow.",
        },
        {
          id: 'u09-l2-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: 'You ___ swim here. The river is very dangerous.',
          sentenceJa: 'ここで泳いではいけません。この川はとても危険です。',
          choices: ["mustn't", "don't have to", 'must', 'have to'],
          correctIndex: 0,
          explanation: "危険を伝えて泳ぐことを禁止する場面なので、mustn't(してはいけない)を使います。",
          choiceNotes: [null, "don't have to は「泳がなくてもよい」で、危険を伝える禁止にはなりません。", 'must では「泳がなければならない」という逆の意味になります。', 'have to も「泳がなければならない」という義務の意味になってしまいます。'],
          audioEn: "You mustn't swim here. The river is very dangerous.",
        },
        {
          id: 'u09-l2-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The train was canceled, so I ___ take a taxi.',
          sentenceJa: '電車が運休したので、タクシーに乗らなければなりませんでした。',
          choices: ['must', 'have to', 'had to', 'musted'],
          correctIndex: 2,
          explanation: 'must に過去形はありません。過去の義務は had to で表します。',
          choiceNotes: ['must は過去の文では使えません。', '過去の話なので have to のままでは使えません。', null, 'musted という形はありません。'],
          audioEn: 'The train was canceled, so I had to take a taxi.',
        },
        {
          id: 'u09-l2-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「彼は制服を着なければなりませんか」と尋ねたいとき。',
          choices: ['Does he have to wear a uniform?', 'Does he has to wear a uniform?', 'Must he has to wear a uniform?', 'He have to wear a uniform?'],
          correctIndex: 0,
          explanation: 'have to の疑問文は do / does で作ります。Does が三単現を引き受けるので、後ろは原形 have に戻します。',
          choiceNotes: [null, 'Does のあとの動詞は原形に戻します。has は使えません。', 'must と have to を重ねて使うことはできません。', '疑問文は Does を文頭に置きます。語順を変えずに尋ねることはできません。'],
          audioEn: 'Does he have to wear a uniform?',
        },
      ],
      summary: [
        'must も have to も「〜しなければならない」。日常会話では have to が中心。',
        "mustn't は「してはいけない」(禁止)、don't have to は「しなくてもよい」(不要)。否定では意味がまったく違う。",
        'must に過去形はない。過去の義務は had to。',
        'have to の疑問文・否定文は do / does / did で作る。',
      ],
    },
    {
      id: 'u09-l3',
      unitId: 'u09',
      level: 'A2+',
      title: 'should / had better',
      objective: 'should でアドバイスを、had better で警告を含む忠告を伝え、状況に合った強さの表現を選べるようになります。',
      minutes: 10,
      prereqs: ['u09-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'should は「〜したほうがいいよ」',
          body:
            'should は**アドバイスや自分の意見**を伝える助動詞です。「〜したほうがいい」「〜すべきだ」という意味ですが、must ほど強くなく、押し付けない提案として日常会話で頻繁に使われます。\n\n- 否定: **shouldn\'t**(〜しないほうがいい)\n- 疑問: **Should I ...?**(〜したほうがいいですか)と、相手にアドバイスを求めるときにも使えます\n\n軽いおすすめ(You should try this cafe.)から真面目な助言まで、幅広く使える便利な助動詞です。',
        },
        {
          type: 'explanation',
          title: 'had better は警告つきの忠告',
          body:
            'had better は「〜したほうがいい、**さもないと悪いことが起こる**」という警告のニュアンスを持つ強い忠告です。\n\n- 会話では **\'d better** と短縮されることがほとんどです: You\'d better hurry.\n- あとに続く動詞は**原形**です(to は付けません)\n- 否定は **had better not + 原形**: You\'d better not be late.\n- had という形ですが、**過去の意味はありません**\n\n強い表現なので、目上の人へのアドバイスには should を使うほうが安全です。',
        },
        {
          type: 'table',
          title: '強さの比較',
          headers: ['表現', 'ニュアンス', '例'],
          rows: [
            ['should', 'アドバイス(したほうがいい)', 'You should see a doctor.'],
            ['had better', '警告(しないとまずい)', "You'd better see a doctor now."],
            ['must / have to', '義務(しなければならない)', 'You must see a doctor today.'],
          ],
        },
        {
          type: 'contrast',
          title: '同じ場面でも、忠告の強さが変わる',
          left: {
            label: 'should — 選択の余地を残すアドバイス',
            items: [
              { en: 'You should check the weather before you go.', ja: '出かける前に天気を確認したほうがいいですよ。', highlight: 'should check' },
              { en: "You shouldn't drink coffee so late.", ja: 'そんなに遅くにコーヒーを飲まないほうがいいですよ。', highlight: "shouldn't drink" },
            ],
            pointJa: '「そうするのがよい」という提案。目上の人にも安心して使えます。',
          },
          right: {
            label: 'had better — 従わないと困る結果になる警告',
            items: [
              { en: "You'd better check the weather, or you'll get soaked.", ja: '天気を確認したほうがいいですよ。さもないとびしょぬれになります。', highlight: "'d better check" },
              { en: "You'd better not miss the deadline.", ja: '締め切りに遅れないほうがいいですよ。', highlight: "'d better not miss" },
            ],
            pointJa: '「さもないと悪いことが起こる」という警告。強く響くので相手を選びます。',
          },
          note: '強さのイメージは should < had better < must。had better のあとは to を付けず原形です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'You should try this restaurant.', ja: 'このレストラン、行ってみるといいですよ。', highlight: 'should try', note: '軽いおすすめにも should を使います。' },
            { en: "You shouldn't eat so much sugar.", ja: '砂糖をそんなにとらないほうがいいですよ。', highlight: "shouldn't eat" },
            { en: 'Should I bring anything to the party?', ja: 'パーティーに何か持って行ったほうがいいですか。', highlight: 'Should I', note: '相手にアドバイスを求める疑問文です。' },
            { en: "We'd better leave now, or we'll miss the train.", ja: 'もう出ないと電車に乗り遅れますよ。', highlight: "'d better leave" },
            { en: "You'd better not be late again.", ja: '二度と遅刻しないほうがいいですよ。', highlight: "'d better not be", note: '否定は had better not + 原形です。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u09-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'You look pale. You ___ go home and rest.',
          sentenceJa: '顔色が悪いですよ。家に帰って休んだほうがいいです。',
          choices: ['should', 'should to', 'had', 'would better'],
          correctIndex: 0,
          explanation: '相手を気づかうアドバイスなので should + 原形を使います。',
          choiceNotes: [null, 'should のあとに to は付けません。', 'had だけでは忠告の意味になりません。had better の形で使います。', 'would better という形はありません。had better です。'],
          audioEn: 'You look pale. You should go home and rest.',
        },
        {
          id: 'u09-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: "You'd better ___ that button. It's for emergencies.",
          sentenceJa: 'そのボタンには触らないほうがいいですよ。緊急用ですから。',
          choices: ['not touch', "don't touch", 'not to touch', 'touch not'],
          correctIndex: 0,
          explanation: 'had better の否定は had better not + 原形の語順です。',
          choiceNotes: [null, "had better の否定に don't は使いません。", 'had better のあとに to は付けません。', 'not は動詞の前に置きます。'],
          audioEn: "You'd better not touch that button. It's for emergencies.",
        },
        {
          id: 'u09-l3-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「医者に診てもらったほうがいい(すぐ行かないとまずい)」と強めに忠告したいとき。',
          choices: ['You had better to see a doctor.', 'You had better saw a doctor.', 'You had better see a doctor.', 'You have better see a doctor.'],
          correctIndex: 2,
          explanation: 'had better のあとは to の付かない動詞の原形です。',
          choiceNotes: ['had better のあとに to は付けません。', 'had better のあとは原形です。過去形にはしません。', null, 'have better という形はありません。現在のことでも had better です。'],
          audioEn: 'You had better see a doctor.',
        },
        {
          id: 'u09-l3-q4',
          prompt: '友達に映画を軽くおすすめするとき、最も自然な文を選んでください。',
          choices: ["You'd better watch this movie.", 'You should watch this movie.', 'You must watch this movie right now.', "You shouldn't watch this movie."],
          correctIndex: 1,
          explanation: '軽いおすすめには押し付けのない should が最も自然です。',
          choiceNotes: ['had better は「見ないとまずい」という警告のニュアンスで、軽いおすすめには強すぎます。', null, 'must right now は命令のように響き、おすすめとしては強すぎます。', 'これは「見ないほうがいい」という逆の意味です。'],
          audioEn: 'You should watch this movie.',
        },
      ],
      summary: [
        "should は「〜したほうがいい」という押し付けないアドバイス。否定は shouldn't。",
        "had better は「しないとまずい」という警告つきの忠告。会話では 'd better + 原形。",
        'had better の否定は had better not + 原形。had でも過去の意味はない。',
        '強さのイメージは should < had better < must。目上の人には should が安全。',
      ],
    },
    {
      id: 'u09-l4',
      unitId: 'u09',
      level: 'A2+',
      title: 'may / might / will の推量',
      objective: 'will / may / might を使って「どのくらいありそうか」という確信の度合いを表し分けられるようになります。',
      minutes: 10,
      prereqs: ['u09-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '「どのくらいありそうか」を助動詞で表す',
          body:
            '予測を述べるとき、助動詞で**話し手がどこまで確信しているか**を伝えられます。\n\n- **will**: 「〜だろう」。そうなると見込んで述べる予測です。\n- **may / might**: 「〜かもしれない」。可能性を示し、断言を避けます。\n\nmay と might に「50%」「30%」のような固定の確率はありません。might が控えめに響くことはありますが、いつも may より低い確率になるわけではありません。まずは **「そうなると見込む」か「可能性として挙げる」か**を、文脈と一緒に考えましょう。',
        },
        {
          type: 'table',
          title: '確信度のまとめ',
          headers: ['助動詞', '確信度', '例'],
          rows: [
            ['will', 'かなり確実(〜だろう)', 'She will pass the exam.'],
            ['may', '可能性あり(〜かもしれない)', 'It may rain tonight.'],
            ['might', '可能性あり(〜かもしれない)', 'He might be late.'],
          ],
        },
        {
          type: 'contrast',
          title: '同じ予測を、確信の度合いで言い分ける',
          left: {
            label: 'will — 自信のある予測',
            items: [
              { en: 'It will rain tonight.', ja: '今夜は雨が降るでしょう。', highlight: 'will rain' },
              { en: 'The train will be crowded this morning.', ja: '今朝の電車は混むでしょう。', highlight: 'will be' },
            ],
            pointJa: '天気予報や経験から「そうなる」と踏み込んで言うとき。',
          },
          right: {
            label: 'may / might — 断言しない可能性',
            items: [
              { en: 'It may rain tonight.', ja: '今夜は雨が降るかもしれません。', highlight: 'may rain' },
              { en: 'The train might be crowded this morning.', ja: '今朝の電車は混むかもしれません。', highlight: 'might be' },
            ],
            pointJa: '可能性を示します。may と might の違いは、文脈や話し方にもよります。',
          },
          note: '助動詞は2つ重ねられません(× will might)。否定は may not / might not です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: "Don't worry. She will be here soon.", ja: '心配いりません。彼女はすぐ来ますよ。', highlight: 'will be' },
            { en: 'It may snow this weekend.', ja: '今週末は雪が降るかもしれません。', highlight: 'may snow' },
            { en: "He might come to the party, but I'm not sure.", ja: '彼はパーティーに来るかもしれませんが、確かではありません。', highlight: 'might come' },
            { en: 'I may be a little late tonight.', ja: '今夜は少し遅れるかもしれません。', highlight: 'may be' },
            { en: "They won't arrive before noon.", ja: '彼らは正午より前には着かないでしょう。', highlight: "won't arrive", note: 'will not の短縮形です。「〜しないだろう」という確信のある予測です。' },
          ],
        },
        {
          type: 'explanation',
          title: 'maybe と may be の違い',
          body:
            '見た目がそっくりな maybe と may be は、品詞がまったく違います。\n\n- **maybe** は「たぶん」という**副詞**。文頭に置くのが基本です: Maybe she is tired.\n- **may be** は**助動詞 may + be動詞**: She may be tired.\n\n2つの文の意味はほぼ同じですが、maybe は動詞の代わりにはなれません(× She maybe tired.)。\n\n否定の推量は **may not / might not**(〜ないかもしれない)で、**won\'t**(〜ないだろう)より確信が弱くなります。',
        },
      ],
      quiz: [
        {
          id: 'u09-l4-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'He ___ join us, but he has a lot of work today.',
          sentenceJa: '彼は来るかもしれませんが、今日は仕事が多いのです。',
          choices: ['will', 'might', 'must', "won't"],
          correctIndex: 1,
          explanation: '「仕事が多いので来られないかもしれない」という不確かな状況なので、控えめな推量の might が合います。',
          choiceNotes: ['あとに「仕事が多い」と続くので、確信のある will は合いません。', null, 'must では「参加しなければならない」という義務の意味になります。', "won't では「来ないだろう」となり、but 以下と意味がつながりません。"],
          audioEn: 'He might join us, but he has a lot of work today.',
        },
        {
          id: 'u09-l4-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼女は疲れているのかもしれません」と言いたいとき。',
          choices: ['She maybe tired.', 'She may be tired.', 'She may tired.', 'She is may be tired.'],
          correctIndex: 1,
          explanation: '助動詞 may のあとに be動詞の原形 be を続けて、She may be tired. とします。',
          choiceNotes: ['maybe は副詞なので、動詞の代わりにはなれません。Maybe she is tired. なら正しい形です。', null, 'may のあとに形容詞を直接は続けられません。be が必要です。', '助動詞はbe動詞より前に置きます。is と may be は並べられません。'],
          audioEn: 'She may be tired.',
        },
        {
          id: 'u09-l4-q3',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'It may rain this afternoon.',
          choices: ['今日の午後は必ず雨が降ります。', '今日の午後は雨が降るかもしれません。', '今日の午後は雨が降ってもよいです。', '今日の午後は雨が降りませんでした。'],
          correctIndex: 1,
          explanation: 'この may は「〜かもしれない」という推量です。',
          choiceNotes: ['may は「必ず」ではなく可能性を表します。確信があるなら will を使います。', null, 'may には許可の意味もありますが、天気に許可は与えられないので、ここでは推量です。', 'may に過去の意味はありません。'],
          audioEn: 'It may rain this afternoon.',
        },
        {
          id: 'u09-l4-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Ask Emi. She ___ the answer. She studied this at college.',
          sentenceJa: 'エミに聞いてみてください。大学でこれを勉強していたので、きっと答えを知っていますよ。',
          choices: ['will know', 'might know', 'may not know', 'will knows'],
          correctIndex: 0,
          explanation: '「大学で勉強した」という強い根拠があるので、確信のある予測 will を使います。',
          choiceNotes: [null, '文法的には正しい形ですが、強い根拠があるのに「知っているかも」では文の流れに合いません。', '「知らないかもしれない」では、エミに聞くよう勧める理由になりません。', '助動詞のあとの動詞は原形です。-s は付けません。'],
          audioEn: 'Ask Emi. She will know the answer. She studied this at college.',
        },
      ],
      summary: [
        'will は確信のある予測「〜だろう」、may / might は「〜かもしれない」。',
        'might は 可能性あり(〜かもしれない)だが、日常会話ではほぼ同じように使える。',
        'maybe は副詞(Maybe she is tired.)、may be は助動詞 + be動詞(She may be tired.)。',
        "「〜ないかもしれない」は may not / might not、「〜ないだろう」は won't。",
      ],
    },
  ],
}
