import type { GrammarUnit } from '../../types'

// U10 不定詞と動名詞の基礎

export const u10: GrammarUnit = {
  id: 'u10',
  level: 'A2+',
  title: '不定詞と動名詞の基礎',
  lessons: [
    {
      id: 'u10-l1',
      unitId: 'u10',
      level: 'A2+',
      title: 'to不定詞の基本',
      objective: 'want / decide / hope などのあとに to不定詞を続けて「〜すること」を表し、「〜するために」という目的も言えるようになります。',
      minutes: 10,
      prereqs: ['u01-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'to + 原形は「これからすること」への矢印',
          body:
            '**to + 動詞の原形**(to不定詞)は、「〜すること」というかたまりを作ります。\n\n- I want **to see** that movie.(その映画を「見ること」をしたい → 見たい)\n\nto はもともと「〜へ向かう」という方向の言葉です。そのイメージ通り、want(したい)・hope(望む)・decide(決める)など、**これからすることに気持ちが向かう動詞**と相性がよいのが特徴です。\n\n**to不定詞の to のあとは動詞の原形**です。前置詞の to とは役割が違うため、U10-l4で区別を学びます。',
        },
        {
          type: 'table',
          title: 'to不定詞をとる代表的な動詞',
          headers: ['動詞', '意味', '例'],
          rows: [
            ['want to do', '〜したい', 'I want to sleep.'],
            ['hope to do', '〜することを望む', 'We hope to win.'],
            ['decide to do', '〜することに決める', 'She decided to move.'],
            ['plan to do', '〜する計画だ', 'They plan to travel.'],
            ['need to do', '〜する必要がある', 'You need to rest.'],
            ['learn to do', '〜できるようになる', 'He learned to cook.'],
          ],
        },
        {
          type: 'structure',
          title: 'to は「これからすること」への矢印',
          parts: [
            { label: '主語', text: 'I' },
            { label: '気持ちを表す動詞', text: 'want' },
            { label: 'to + 原形', text: 'to see that movie' },
          ],
          caption: 'want・hope・decide・plan など、これからの行動へ気持ちが向かう動詞と結びつきます。to のあとは主語や時制に関係なく必ず原形です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I want to see that new movie.', ja: 'その新しい映画が見たいです。', highlight: 'want to see' },
            { en: 'She decided to change jobs.', ja: '彼女は転職することに決めました。', highlight: 'decided to change' },
            { en: 'We hope to visit Okinawa next spring.', ja: '来年の春に沖縄に行けたらと思っています。', highlight: 'hope to visit' },
            { en: 'He went to the store to buy milk.', ja: '彼は牛乳を買うためにお店に行きました。', highlight: 'to buy', note: '「〜するために」という目的を表す to です。' },
            { en: "I'm saving money to study abroad.", ja: '留学するためにお金を貯めています。', highlight: 'to study' },
          ],
        },
        {
          type: 'explanation',
          title: '「〜するために」の to',
          body:
            'to不定詞のもう1つの大きな仕事が、**目的**を表すことです。文の後ろに to do を足すと「〜するために」という理由を付け加えられます。\n\n- I went to the gym **to swim**.(泳ぐためにジムへ行きました)\n- She called me **to say** thank you.(お礼を言うために電話をくれました)\n\nWhy ...?(なぜ?)と聞かれたときの答えとしても使える、会話で大活躍する形です。',
        },
      ],
      quiz: [
        {
          id: 'u10-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'She decided ___ a new computer.',
          sentenceJa: '彼女は新しいパソコンを買うことに決めました。',
          choices: ['buy', 'to buy', 'buying', 'bought'],
          correctIndex: 1,
          explanation: 'decide は to不定詞をとる動詞です。decided to buy で「買うことに決めた」となります。',
          choiceNotes: ['decide のあとに動詞の原形を直接は続けられません。', null, 'decide は動名詞ではなく to不定詞をとる動詞です。', '動詞の過去形をそのまま続けることはできません。'],
          audioEn: 'She decided to buy a new computer.',
        },
        {
          id: 'u10-l1-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I went to the library ___ some books.',
          sentenceJa: '本を借りるために図書館へ行きました。',
          choices: ['for borrow', 'to borrow', 'borrowing', 'to borrowed'],
          correctIndex: 1,
          explanation: '「〜するために」という目的は to + 原形で表します。',
          choiceNotes: ['「〜するために」を for + 動詞の原形では表せません。', null, '-ing を置くだけでは目的の意味になりません。', 'to のあとは原形です。過去形は続けられません。'],
          audioEn: 'I went to the library to borrow some books.',
        },
        {
          id: 'u10-l1-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「家に帰りたい」と言いたいとき。',
          choices: ['I want go home.', 'I want to go home.', 'I want going home.', 'I want to going home.'],
          correctIndex: 1,
          explanation: 'want は to不定詞をとる動詞です。want to go の形にします。',
          choiceNotes: ['want と動詞の間に to が必要です。', null, 'want は -ing ではなく to不定詞をとります。', 'to のあとは原形です。going にはしません。'],
          audioEn: 'I want to go home.',
        },
        {
          id: 'u10-l1-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My son is learning ___ the violin.',
          sentenceJa: '息子はバイオリンを弾けるように習っています。',
          choices: ['to play', 'to plays', 'to played', 'to playing'],
          correctIndex: 0,
          explanation: 'learn to do で「〜できるようになる(ために習う)」。to のあとは必ず原形です。',
          choiceNotes: [null, 'to のあとの動詞に -s は付けません。', 'to のあとに過去形は続けられません。', 'to不定詞と -ing を組み合わせることはできません。'],
          audioEn: 'My son is learning to play the violin.',
        },
      ],
      summary: [
        'to + 動詞の原形で「〜すること」を表せる。to のあとは必ず原形。',
        'want / hope / decide / plan / need / learn は to不定詞をとる代表的な動詞。',
        '文の後ろに to do を足すと「〜するために」という目的を表せる。',
      ],
    },
    {
      id: 'u10-l2',
      unitId: 'u10',
      level: 'A2+',
      title: '動名詞の基本',
      objective: 'enjoy / finish / mind などのあとに動名詞(-ing)を続けられるようになり、-ing のかたまりを文の主語としても使えるようになります。',
      minutes: 10,
      prereqs: ['u10-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '動詞に -ing を付けて名詞にする',
          body:
            '動詞の -ing 形を**「〜すること」という名詞のかたまり**として使うとき、動名詞と呼びます。\n\n- I enjoy **cooking**. → 料理することを楽しみます。\n- **Cooking** is fun. → 料理することは楽しいです。\n\n進行形と形は同じでも、文の中の役割が違います。I **am cooking** now. は「今、料理している」という動作、My hobby is **cooking**. は「趣味は料理すること」という説明です。**be動詞のあとだから必ず進行形、とは限りません**。「〜している最中」なのか「〜すること」を名詞として置いているのかを確認しましょう。',
        },
        {
          type: 'table',
          title: '動名詞をとる代表的な動詞',
          headers: ['動詞', '意味', '例'],
          rows: [
            ['enjoy -ing', '〜して楽しむ', 'I enjoy running.'],
            ['finish -ing', '〜し終える', 'He finished eating.'],
            ['mind -ing', '〜するのを気にする', 'Would you mind waiting?'],
            ['keep -ing', '〜し続ける', 'She kept talking.'],
            ['practice -ing', '〜する練習をする', 'We practice speaking English.'],
            ['give up -ing', '〜するのをやめる', 'He gave up smoking.'],
          ],
        },
        {
          type: 'contrast',
          title: '形は同じ -ing、役割は別',
          left: {
            label: '進行形の -ing — be動詞とセット',
            items: [
              { en: 'I am cooking now.', ja: '私は今、料理をしています。', highlight: 'am cooking' },
              { en: 'They are running in the park.', ja: '彼らは公園で走っています。', highlight: 'are running' },
            ],
            pointJa: '今おこなっている動作。前に必ず be動詞があります。',
          },
          right: {
            label: '動名詞の -ing — 名詞の席に入る',
            items: [
              { en: 'I enjoy cooking for my family.', ja: '家族のために料理をするのが楽しみです。', highlight: 'cooking' },
              { en: 'Running is good exercise.', ja: '走ることはよい運動です。', highlight: 'Running' },
            ],
            pointJa: '「〜すること」という名詞のかたまり。主語や目的語の席に入ります。',
          },
          note: 'be動詞とセットなら進行形、名詞が入る席にあれば動名詞です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I enjoy cooking on weekends.', ja: '週末に料理をするのが楽しみです。', highlight: 'enjoy cooking' },
            { en: 'Have you finished packing for the trip?', ja: '旅行の荷造りは終わりましたか。', highlight: 'finished packing' },
            { en: 'Would you mind closing the window?', ja: '窓を閉めていただけますか。', highlight: 'mind closing', note: '直訳は「閉めるのを気にしますか」。丁寧な依頼の定番表現です。' },
            { en: 'My baby kept crying all night.', ja: '赤ちゃんは一晩中泣き続けました。', highlight: 'kept crying' },
            { en: 'Swimming is good exercise.', ja: '水泳はよい運動です。', highlight: 'Swimming', note: '動名詞は文の主語にもなれます。' },
          ],
        },
        {
          type: 'explanation',
          title: '主語になる -ing',
          body:
            '動名詞は名詞なので、**文の主語**にもなれます。\n\n- **Getting up early** is hard for me.(早起きすることは私にはつらい)\n- **Learning a language** takes time.(言語を学ぶことは時間がかかる)\n\nポイントは、動名詞の主語は「〜すること」という**ひとかたまりで単数扱い**になることです。中に複数形の名詞が入っていても、be動詞は is を使います。\n\n- Eating vegetables **is** good for you.(× are)',
        },
      ],
      quiz: [
        {
          id: 'u10-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Have you finished ___ your homework?',
          sentenceJa: '宿題はやり終えましたか。',
          choices: ['do', 'to do', 'doing', 'did'],
          correctIndex: 2,
          explanation: 'finish は動名詞をとる動詞です。finish doing で「し終える」となります。',
          choiceNotes: ['finish のあとに原形を直接は続けられません。', 'finish は to不定詞ではなく動名詞をとります。', null, '過去形は続けられません。'],
          audioEn: 'Have you finished doing your homework?',
        },
        {
          id: 'u10-l2-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「私たちは昨夜、その試合を見て楽しみました」と言いたいとき。',
          choices: ['We enjoyed to watch the game last night.', 'We enjoyed watching the game last night.', 'We enjoyed watch the game last night.', 'We enjoyed to watching the game last night.'],
          correctIndex: 1,
          explanation: 'enjoy は動名詞をとる動詞です。enjoyed watching が正しい形です。',
          choiceNotes: ['enjoy は to不定詞をとりません。', null, '動詞の原形を直接は続けられません。', 'to と -ing を組み合わせることはできません。'],
          audioEn: 'We enjoyed watching the game last night.',
        },
        {
          id: 'u10-l2-q3',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Eating vegetables ___ good for your health.',
          sentenceJa: '野菜を食べることは健康によいです。',
          choices: ['is', 'are', 'be', 'am'],
          correctIndex: 0,
          explanation: '主語は Eating vegetables「野菜を食べること」というひとかたまりで、単数扱いなので is を使います。',
          choiceNotes: [null, 'vegetables は複数形ですが、主語全体は「〜すること」という単数のかたまりです。', '原形の be はそのまま現在の文には使えません。', 'am は主語が I のときだけ使います。'],
          audioEn: 'Eating vegetables is good for your health.',
        },
        {
          id: 'u10-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['She gave up eating sweets.', 'He kept practicing every day.', 'I finished to read the book.', 'They enjoy playing tennis.'],
          correctIndex: 2,
          explanation: 'finish は to不定詞ではなく動名詞をとる動詞です。I finished reading the book. が正しい形です。',
          choiceNotes: ['正しい文です。give up は -ing をとります。', '正しい文です。keep は -ing をとります。', null, '正しい文です。enjoy は -ing をとります。'],
          audioEn: 'I finished reading the book.',
        },
      ],
      summary: [
        '動詞 + -ing(動名詞)は「〜すること」という名詞のかたまり。',
        'enjoy / finish / mind / keep / practice / give up は動名詞をとる代表的な動詞。',
        '動名詞は主語にもなれる。主語のときはひとかたまりで単数扱い(be動詞は is)。',
        '進行形の -ing(be動詞とセット)と動名詞の -ing は形が同じでも役割が違う。',
      ],
    },
    {
      id: 'u10-l3',
      unitId: 'u10',
      level: 'A2+',
      title: '不定詞 vs 動名詞(基礎)',
      objective: '動詞ごとに「to不定詞・動名詞のどちらをとるか」を判断でき、like / start などの両方使える動詞も自信を持って使えるようになります。',
      minutes: 12,
      prereqs: ['u10-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '動詞によって「後ろの形」が決まっている',
          body:
            'ここまでのレッスンで見たとおり、動詞のあとに「〜すること」を続けるとき、**どの形を使えるかは前の動詞が決めます**。動詞は3つのタイプに分かれます。\n\n- **to不定詞だけ**: want / hope / decide / plan / need\n- **動名詞だけ**: enjoy / finish / mind / keep / give up\n- **どちらも OK(意味はほぼ同じ)**: like / love / hate / start / begin / continue\n\n「×I enjoy to watch」「×I want watching」のような組み合わせの誤りは、日本人学習者に非常に多いミスです。まずタイプごとに動詞を覚えるのが確実な近道です。',
        },
        {
          type: 'contrast',
          title: 'to をとる動詞 vs -ing をとる動詞',
          left: {
            label: 'to不定詞だけをとる動詞',
            items: [
              { en: 'I want to learn the guitar.', ja: 'ギターを習いたいです。', highlight: 'want to learn' },
              { en: 'She decided to stay home.', ja: '彼女は家にいることに決めました。', highlight: 'decided to stay' },
            ],
            pointJa: '「これからすること」に気持ちが向かう動詞が多い(want / hope / decide / plan)。',
          },
          right: {
            label: '動名詞だけをとる動詞',
            items: [
              { en: 'I enjoy learning new things.', ja: '新しいことを学ぶのが楽しいです。', highlight: 'enjoy learning' },
              { en: 'He finished cleaning his room.', ja: '彼は部屋の掃除を終えました。', highlight: 'finished cleaning' },
            ],
            pointJa: '「実際にしている・したこと」を指す動詞が多い(enjoy / finish / give up)。',
          },
          note: '「to = これから、-ing = 現実にしていること」は覚えるための大まかな傾向です。例外もあるので、最終的には動詞ごとに覚えましょう。',
        },
        {
          type: 'table',
          title: '3つのタイプ',
          headers: ['タイプ', '代表的な動詞', '例'],
          rows: [
            ['to不定詞だけ', 'want / hope / decide / plan / need', 'I hope to see you soon.'],
            ['動名詞だけ', 'enjoy / finish / mind / keep / give up', 'I enjoy taking photos.'],
            ['どちらも OK(意味ほぼ同じ)', 'like / love / hate / start / begin / continue', 'It started to rain. = It started raining.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I like to read before bed.', ja: '寝る前に本を読むのが好きです。', highlight: 'like to read' },
            { en: 'I like reading before bed.', ja: '寝る前に本を読むのが好きです。', highlight: 'like reading', note: '意味はほぼ同じです。どちらも自然に使えます。' },
            { en: 'It started to rain during the game.', ja: '試合中に雨が降り始めました。', highlight: 'started to rain' },
            { en: 'She continued working after the baby was born.', ja: '彼女は出産後も働き続けました。', highlight: 'continued working' },
            { en: 'He hates being late.', ja: '彼は遅刻するのが大嫌いです。', highlight: 'hates being' },
          ],
        },
        {
          type: 'explanation',
          title: '意味が変わる動詞もある(入口)',
          body:
            '少数ですが、to不定詞と動名詞で**意味が変わる動詞**もあります。代表は stop です。\n\n- He stopped **smoking**.(タバコを**やめた**: smoking は stop の目的語)\n- He stopped **to smoke**.(タバコを**吸うために立ち止まった**: to smoke は目的を表す to)\n\nremember / forget / try も同じように意味が変わりますが、詳しくは B1+ で学びます。ここでは「stop の2つの意味」だけしっかり押さえておきましょう。',
        },
      ],
      quiz: [
        {
          id: 'u10-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I want ___ shopping this weekend, but I have to work.',
          sentenceJa: '今週末は買い物に行きたいのですが、仕事があります。',
          choices: ['go', 'to go', 'going', 'went'],
          correctIndex: 1,
          explanation: 'want は to不定詞だけをとる動詞です。want to go の形にします。',
          choiceNotes: ['want と動詞の間に to が必要です。', null, 'want は動名詞をとりません。', '過去形は続けられません。'],
          audioEn: 'I want to go shopping this weekend, but I have to work.',
        },
        {
          id: 'u10-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My grandfather gave up ___ five years ago.',
          sentenceJa: '祖父は5年前にタバコをやめました。',
          choices: ['smoke', 'to smoke', 'smoking', 'smoked'],
          correctIndex: 2,
          explanation: 'give up は動名詞だけをとる動詞です。gave up smoking で「タバコをやめた」となります。',
          choiceNotes: ['give up のあとに原形を直接は続けられません。', 'give up は to不定詞をとりません。', null, '過去形は続けられません。'],
          audioEn: 'My grandfather gave up smoking five years ago.',
        },
        {
          id: 'u10-l3-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: ['It began to snow in the evening.', 'It began snowing in the evening.', 'I hope seeing you again soon.', 'I love watching old movies.'],
          correctIndex: 2,
          explanation: 'hope は to不定詞だけをとる動詞です。I hope to see you again soon. が正しい形です。',
          choiceNotes: ['正しい文です。begin は両方の形をとれます。', '正しい文です。begin は両方の形をとれます。', null, '正しい文です。love は両方の形をとれます。'],
          audioEn: 'I hope to see you again soon.',
        },
        {
          id: 'u10-l3-q4',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'He stopped to drink some water.',
          choices: ['彼は水を飲むのをやめました。', '彼は水を飲むために立ち止まりました。', '彼は水を飲み続けました。', '彼は水を飲みたくありませんでした。'],
          correctIndex: 1,
          explanation: 'stop to do は「〜するために立ち止まる・手を止める」です。「飲むのをやめた」なら stopped drinking になります。',
          choiceNotes: ['「やめた」なら stopped drinking(動名詞)です。', null, '「し続けた」は kept drinking です。', '「したくない」という意味はこの文にはありません。'],
          audioEn: 'He stopped to drink some water.',
        },
      ],
      summary: [
        '動詞には「to だけ」「-ing だけ」「どちらも OK」の3タイプがある。',
        'like / love / hate / start / begin / continue はどちらも使えて意味はほぼ同じ。',
        '「to = これからすること、-ing = 実際にしていること」は覚えるための大まかな傾向。',
        'stop -ing は「やめる」、stop to do は「するために立ち止まる」。意味が変わる動詞は B1+ で詳しく学ぶ。',
      ],
    },
    {
      id: 'u10-l4',
      unitId: 'u10',
      level: 'A2+',
      title: '前置詞 + 動名詞',
      objective: 'be good at -ing や before -ing のように、前置詞のあとには必ず動名詞を置けるようになります。',
      minutes: 10,
      prereqs: ['u10-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '前置詞のあとは名詞の指定席',
          body:
            'at / in / for / about / before / after / without などの**前置詞のあとに置けるのは名詞だけ**です。\n\nそこで、前置詞のあとに「〜すること」を続けたいときは、必ず**動名詞(-ing)**を使います。動名詞は動詞を名詞化したものなので、名詞の指定席に入れるのです。\n\n- She is good **at making** sweets.(○)\n- × She is good at **to make** sweets.\n\n**前置詞 + to不定詞は使えない**、と覚えてしまいましょう。',
        },
        {
          type: 'table',
          title: 'よく使う「前置詞 + -ing」の表現',
          headers: ['表現', '意味', '例'],
          rows: [
            ['be good at -ing', '〜するのが得意だ', 'She is good at singing.'],
            ['be interested in -ing', '〜することに興味がある', "I'm interested in learning French."],
            ['thank you for -ing', '〜してくれてありがとう', 'Thank you for helping me.'],
            ['before / after -ing', '〜する前に / したあとに', 'Wash your hands before eating.'],
            ['without -ing', '〜しないで', 'He left without saying goodbye.'],
            ['How about -ing?', '〜するのはどう?', 'How about going for a walk?'],
          ],
        },
        {
          type: 'contrast',
          title: '同じ to でも、正体が違う',
          left: {
            label: '不定詞の to — あとは原形',
            items: [
              { en: 'I want to visit your new office.', ja: 'あなたの新しいオフィスを訪ねたいです。', highlight: 'to visit' },
              { en: 'We decided to move to Sendai.', ja: '私たちは仙台へ引っ越すことに決めました。', highlight: 'to move' },
            ],
            pointJa: 'want / decide / hope などのあとの to は不定詞の印です。',
          },
          right: {
            label: '前置詞の to — あとは -ing',
            items: [
              { en: 'I am looking forward to visiting your new office.', ja: 'あなたの新しいオフィスを訪ねるのを楽しみにしています。', highlight: 'to visiting' },
              { en: 'She is used to working night shifts.', ja: '彼女は夜勤に慣れています。', highlight: 'to working' },
            ],
            pointJa: 'look forward to / be used to の to は前置詞。名詞の席なので -ing にします。',
          },
          note: 'to を見ただけで原形と決めず、直前の表現までひとかたまりで役割を判定します。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'My sister is good at making sweets.', ja: '姉はお菓子作りが得意です。', highlight: 'good at making' },
            { en: "I'm interested in working overseas.", ja: '海外で働くことに興味があります。', highlight: 'interested in working' },
            { en: 'Thank you for inviting me today.', ja: '今日は招待してくれてありがとうございます。', highlight: 'for inviting' },
            { en: 'Check the map before leaving the hotel.', ja: 'ホテルを出る前に地図を確認してください。', highlight: 'before leaving' },
            { en: 'She passed the exam without studying much.', ja: '彼女はあまり勉強せずに試験に合格しました。', highlight: 'without studying' },
          ],
        },
        {
          type: 'explanation',
          title: '要注意: look forward to の to',
          body:
            'look forward to(〜を楽しみにする)の to は、不定詞の to ではなく**前置詞の to** です。だから後ろは -ing になります。\n\n- I\'m looking forward **to seeing** you.(○ 会えるのを楽しみにしています)\n- × I\'m looking forward to see you.\n\nメールや手紙の締めくくりの定番表現なので、**looking forward to -ing** の形で丸ごと覚えてしまうのがおすすめです。',
        },
      ],
      quiz: [
        {
          id: 'u10-l4-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My brother is good at ___ computers.',
          sentenceJa: '兄はパソコンを直すのが得意です。',
          choices: ['fix', 'to fix', 'fixing', 'fixed'],
          correctIndex: 2,
          explanation: 'at は前置詞なので、あとに続く動詞は動名詞 fixing にします。',
          choiceNotes: ['前置詞のあとに動詞の原形は置けません。', '前置詞のあとに to不定詞は置けません。', null, '過去形は続けられません。'],
          audioEn: 'My brother is good at fixing computers.',
        },
        {
          id: 'u10-l4-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: "I'm looking forward to ___ you next month.",
          sentenceJa: '来月お会いできるのを楽しみにしています。',
          choices: ['see', 'seeing', 'saw', 'be seen'],
          correctIndex: 1,
          explanation: 'look forward to の to は前置詞なので、あとは動名詞 seeing にします。',
          choiceNotes: ['この to は前置詞なので、原形は続けられません。', null, '過去形は続けられません。', '受け身の形にする必要はありません。「会う」のは自分です。'],
          audioEn: "I'm looking forward to seeing you next month.",
        },
        {
          id: 'u10-l4-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼は何も言わずに部屋を出ていきました」と言いたいとき。',
          choices: ['He left the room without to say anything.', 'He left the room without saying anything.', 'He left the room without say anything.', 'He left the room without said anything.'],
          correctIndex: 1,
          explanation: 'without は前置詞なので、あとは動名詞 saying を続けます。',
          choiceNotes: ['前置詞のあとに to不定詞は置けません。', null, '前置詞のあとに動詞の原形は置けません。', '前置詞のあとに過去形は置けません。'],
          audioEn: 'He left the room without saying anything.',
        },
        {
          id: 'u10-l4-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['Thank you for coming today.', 'How about eating out tonight?', 'She is interested in to study art.', 'Think carefully before answering.'],
          correctIndex: 2,
          explanation: 'in は前置詞なので、あとは動名詞 studying にします。She is interested in studying art. が正しい形です。',
          choiceNotes: ['正しい文です。for のあとに -ing が続いています。', '正しい文です。How about のあとに -ing が続いています。', null, '正しい文です。before のあとに -ing が続いています。'],
          audioEn: 'She is interested in studying art.',
        },
      ],
      summary: [
        '前置詞のあとに動詞を続けるときは必ず -ing(動名詞)。前置詞 + to不定詞は使えない。',
        'be good at -ing / be interested in -ing / thank you for -ing / before -ing / without -ing を定番表現として覚える。',
        "look forward to の to は前置詞。後ろは -ing(I'm looking forward to seeing you.)。",
      ],
    },
  ],
}
