import type { GrammarUnit } from '../../types'

// U11 現在完了 — カリキュラム中もっとも重要なユニット。
// 全レッスンで timeline を使い、「過去と今をつなぐ」イメージを軸に4用法と過去形との使い分けを扱う。

export const u11: GrammarUnit = {
  id: 'u11',
  level: 'B1',
  title: '現在完了',
  lessons: [
    {
      id: 'u11-l1',
      unitId: 'u11',
      level: 'B1',
      title: '現在完了の基本概念',
      objective: '「have + 過去分詞」の形を作り、過去の出来事を「今」と結びつけて伝える現在完了の基本イメージをつかめるようになります。',
      minutes: 10,
      prereqs: ['u02-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '過去の出来事を「今」の状況として伝える',
          body:
            '**現在完了は、過去に起きたことを「今どうなのか」という視点で伝える形**です。\n\n- I lost my key yesterday. → 昨日カギをなくしました。昨日の出来事を報告しています。\n- I have lost my key. → カギをなくしてしまいました。「今カギがない」という状況を伝えています。\n\n現在完了の形は **have / has + 過去分詞**。過去から今へ橋をかけるイメージです。過去形を使ったからといって「今はもう見つかった」と決まるわけではありません。違うのは、出来事そのものよりも**話し手がどこに注目しているか**です。',
        },
        {
          type: 'structure',
          title: '形: have / has + 過去分詞',
          parts: [
            { label: '主語', text: 'I' },
            { label: 'have / has', text: 'have' },
            { label: '過去分詞', text: 'lost' },
            { label: 'その他', text: 'my key' },
          ],
          caption: "主語が he / she / it のときは has。否定は have not(haven't)/ has not(hasn't)、疑問は Have / Has を主語の前に出します。",
        },
        {
          type: 'timeline',
          title: '過去形と現在完了のイメージ',
          timelines: [
            {
              title: '過去形: I lost my key.',
              point: 40,
              pointLabel: 'カギをなくした',
              caption: '過去の一点の出来事。今どうなっているかは語りません。',
            },
            {
              title: '現在完了: I have lost my key.',
              point: 40,
              pointLabel: 'カギをなくした',
              range: [40, 100],
              arrowToNow: true,
              rangeLabel: '今も見つかっていない',
              caption: '過去の出来事の影響が「今」まで届いています。',
            },
          ],
        },
        {
          type: 'table',
          title: '過去分詞の作り方',
          headers: ['タイプ', '原形 → 過去形 → 過去分詞', '同じパターンの例'],
          rows: [
            ['規則動詞(過去形と同じ)', 'play → played → played', 'work, live, visit'],
            ['不規則(3つとも違う)', 'go → went → gone', 'see → saw → seen / eat → ate → eaten / break → broke → broken'],
            ['不規則(過去形と過去分詞が同じ)', 'have → had → had', 'make → made → made / buy → bought → bought'],
            ['不規則(3つとも同じ形)', 'put → put → put', 'cut → cut → cut / read → read → read(発音は変化)'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have lost my key.', ja: 'カギをなくしてしまいました(今もありません)。', highlight: 'have lost' },
            { en: 'She has broken her arm.', ja: '彼女は腕を骨折しています(今も治っていません)。', highlight: 'has broken' },
            { en: 'We have sold our car.', ja: '車を売りました(だから今は車がありません)。', highlight: 'have sold' },
            { en: "The bus hasn't arrived.", ja: 'バスはまだ着いていません。', highlight: "hasn't arrived", note: '否定文は have / has のあとに not を置きます。' },
            { en: 'Have you seen my glasses?', ja: '私のメガネを見かけませんでしたか(今探しています)。', highlight: 'Have you seen', note: '疑問文は Have / Has を主語の前に出します。' },
          ],
        },
        {
          type: 'explanation',
          title: '経験・継続・結果に共通する視点',
          body:
            '現在完了は、経験・継続・完了・結果を**今までの情報**として伝えます。\n\n- I have been to Kyoto. → 今までに京都へ行った経験があります。\n- I have lived here for three years. → 3年前から今まで、ここに住んでいます。\n- I have lost my key. → カギをなくして、今も見つかっていません。\n\nこの have は「持つ」という一般動詞ではなく、**現在完了を作る助動詞**です。「過去の経験や結果を今につなげる」というイメージを使い、have を毎回「持っている」と訳す必要はありません。',
        },
      ],
      quiz: [
        {
          id: 'u11-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Look! Someone ___ the window.',
          sentenceJa: '見て!誰かが窓を割ってしまっています。',
          choices: ['has broken', 'has broke', 'have broken', 'breaks'],
          correctIndex: 0,
          explanation: '割れた窓が今目の前にある、という現在の結果を伝える場面です。主語 someone は単数なので has + 過去分詞 broken を使います。',
          choiceNotes: [null, 'broke は過去形です。has のあとには過去分詞 broken を使います。', '主語 someone は単数なので have ではなく has です。', '現在形は習慣や事実を表すので、目の前の結果を伝えるこの場面には合いません。'],
          audioEn: 'Look! Someone has broken the window.',
        },
        {
          id: 'u11-l1-q2',
          prompt: '「今もそのカギが見つかっていない」ことを最も自然に伝える文を選んでください。',
          choices: ['I lost my key.', 'I have lost my key.', 'I was losing my key.', 'I lose my key.'],
          correctIndex: 1,
          explanation: '現在完了は「なくした → 今もない」という過去の出来事と今のつながりを伝えます。過去形はなくした事実だけを述べ、今どうかは語りません。',
          choiceNotes: ['過去形は「なくした」という過去の事実だけで、今も見つかっていないかどうかは伝えません。', null, '過去進行形は「なくしつつあった」という不自然な意味になります。', '現在形は習慣・事実を表す形で、この場面では使えません。'],
          audioEn: 'I have lost my key.',
        },
        {
          id: 'u11-l1-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼はもう帰宅しています(今は家にいます)」と伝えたいとき。',
          choices: ['He has go home.', 'He has gone home.', 'He has went home.', 'He have gone home.'],
          correctIndex: 1,
          explanation: '現在完了は have / has + 過去分詞。go の過去分詞は gone で、主語 he には has を使います。',
          choiceNotes: ['go は原形です。過去分詞 gone にします。', null, 'went は過去形です。現在完了では過去分詞 gone を使います。', '主語が he なので have ではなく has です。'],
          audioEn: 'He has gone home.',
        },
        {
          id: 'u11-l1-q4',
          prompt: '自然な疑問文を選んでください。',
          sentenceJa: '今スマートフォンを探していて、「私の電話を見かけていない?」と尋ねたいとき。',
          choices: ['Did you see my phone yesterday?', 'Have you seen my phone?', 'Do you see my phone?', 'Have you saw my phone?'],
          correctIndex: 1,
          explanation: '「(今までに)見かけていないか」と今の状況について尋ねるので現在完了です。Have を主語の前に出し、動詞は過去分詞 seen にします。',
          choiceNotes: ['「昨日見たか」という過去の一点の質問になり、今探している状況とはずれます。', null, '現在形では「ふだん見るか」という習慣の質問になってしまいます。', 'saw は過去形です。過去分詞 seen を使います。'],
          audioEn: 'Have you seen my phone?',
        },
      ],
      summary: [
        '現在完了は have / has + 過去分詞。過去の出来事を「今」とつなげて伝える形。',
        '過去形は過去だけの話で今とは切れている。現在完了は出来事の結果・影響が今に届いている。',
        '否定は have / has + not、疑問は Have / Has を主語の前へ。',
        '不規則動詞の過去分詞(gone / seen / eaten / broken など)は過去形と区別して覚える。',
      ],
    },
    {
      id: 'u11-l2',
      unitId: 'u11',
      level: 'B1',
      title: '経験を表す現在完了',
      objective: '「〜したことがある」という経験を現在完了で表し、ever / never / before / 回数の表現を正しく使えるようになります。',
      minutes: 10,
      prereqs: ['u11-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '経験 =「今までの人生」の中身',
          body:
            '「京都に3回行ったことがある」「納豆は食べたことがない」——こうした**経験**は現在完了で表します。\n\nなぜ現在完了なのでしょうか。経験とは「生まれてから今までの時間の中に何があるか」という話だからです。「今までの人生」は今とつながった期間なので、過去と今をつなぐ現在完了の出番になります。\n\n大事な特徴がひとつ。経験の文では**「いつしたか」は言いません**。いつしたかを言いたくなったら、それは過去形の仕事です(l5で詳しく学びます)。',
        },
        {
          type: 'timeline',
          title: '経験のイメージ',
          timelines: [
            {
              title: 'I have visited Kyoto three times.',
              range: [0, 100],
              arrowToNow: true,
              rangeLabel: '生まれてから今まで',
              caption: '「今までの人生」という期間の中に、京都訪問が3回ある、という言い方です。',
            },
          ],
        },
        {
          type: 'explanation',
          title: 'ever / never / before / 回数',
          body:
            '経験の文でよく使う表現です。\n\n- **ever**(今までに): 疑問文で使う。Have you **ever** tried natto?\n- **never**(一度も〜ない): それ自体が否定を表すので not は不要。I have **never** been to Okinawa.\n- **before**(以前に): 文末に置く。I have seen this movie **before**.\n- **回数**: once(1回)、twice(2回)、three times(3回)… を文末に置く。\n\never と never は have / has と過去分詞の間に置きます。',
        },
        {
          type: 'explanation',
          title: 'have been to と have gone to',
          body:
            '「行ったことがある」は **have been to** を使います。\n\n- I **have been to** Paris twice.(2回行ったことがある = 行って帰ってきた)\n- He **has gone to** Paris.(パリへ行ってしまった = 今ここにいない)\n\nhave gone to は「行った結果、今ここにいない」という意味になるので、経験のつもりで使うと誤解されます。「自分の経験」を語るときは have been to、と覚えておきましょう。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have visited Kyoto three times.', ja: '京都には3回行ったことがあります。', highlight: 'have visited' },
            { en: 'Have you ever tried natto?', ja: '納豆を食べてみたことはありますか。', highlight: 'ever' },
            { en: 'She has never driven a car.', ja: '彼女は一度も車を運転したことがありません。', highlight: 'has never driven', note: 'never が not の代わりに否定を表します。' },
            { en: 'I have seen this movie before.', ja: 'この映画は前に見たことがあります。', highlight: 'before' },
            { en: 'We have been to that restaurant once.', ja: 'あのレストランには一度行ったことがあります。', highlight: 'have been to' },
            { en: 'My parents have never traveled abroad.', ja: '両親は海外旅行をしたことがありません。', highlight: 'have never traveled' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u11-l2-q1',
          prompt: '空所に入る表現を選んでください。',
          sentence: "Ken isn't here this week. He ___ to Hokkaido.",
          sentenceJa: 'ケンは今週ここにいません。北海道に行っています。',
          choices: ['has been', 'has gone', 'has never been', 'was going'],
          correctIndex: 1,
          explanation: '「行ってしまって今ここにいない」は has gone to で表します。has been to だと「行ったことがある(今はここにいる)」という経験の意味になります。',
          choiceNotes: ['has been to は「行ったことがある」という経験を表し、今ここにいない理由の説明になりません。', null, '「一度も行ったことがない」では意味が逆です。', '過去進行形では「今いない」という現在の状況を説明できません。'],
          audioEn: "Ken isn't here this week. He has gone to Hokkaido.",
        },
        {
          id: 'u11-l2-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「私はこの本を以前に読んだことがあります」と言いたいとき。',
          choices: ['I have ever read this book.', 'I have read this book before.', 'I have read before this book.', 'I readed this book before.'],
          correctIndex: 1,
          explanation: '「以前に」は before を文末に置いて表します。ever は基本的に疑問文で使う語で、ふつうの肯定文には使いません。',
          choiceNotes: ['ever をこの形の肯定文で使うことはできません。', null, 'before は文末に置きます。目的語の前には入れません。', 'read の過去分詞は read(つづりは同じで発音が変わります)。readed という形はありません。'],
          audioEn: 'I have read this book before.',
        },
        {
          id: 'u11-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「祖母は一度も飛行機に乗ったことがありません」と言いたいとき。',
          choices: ["My grandmother hasn't never flown.", 'My grandmother has never flown.', 'My grandmother never has flown.', "My grandmother doesn't never fly."],
          correctIndex: 1,
          explanation: 'never 自体が否定の意味を持つので、not と重ねません。never は has と過去分詞の間に置きます。',
          choiceNotes: ['not と never を重ねる二重否定は使えません。', null, 'never は has と過去分詞の間に置くのが基本の位置です。', '現在完了の文なので do の否定形は使いません。'],
          audioEn: 'My grandmother has never flown.',
        },
        {
          id: 'u11-l2-q4',
          prompt: '会話の空所に入るものを選んでください。',
          sentence: 'Have you ever seen a sumo match? — Yes, ___',
          sentenceJa: '相撲を見たことはありますか。— はい、去年初めて見ました。',
          choices: ['I have seen one last year.', 'I saw one last year.', 'I have ever seen one.', 'I see one last year.'],
          correctIndex: 1,
          explanation: '経験を尋ねるのは現在完了ですが、「去年」という特定の時点を答えるときは過去形に切り替えます。現在完了は last year のような特定の過去の時点とは一緒に使えません。',
          choiceNotes: ['現在完了は last year のような特定の過去の時点を表す語句とは一緒に使えません。', null, 'ever は肯定の答えの文では使いません。', '過去の出来事なので現在形は使えません。'],
          audioEn: 'Yes, I saw one last year.',
        },
      ],
      summary: [
        '経験(〜したことがある)は「今までの人生」の中の出来事なので現在完了で表す。',
        'ever は疑問文、never は否定(not は不要)。どちらも have と過去分詞の間。before や回数(once / twice / three times)は文末。',
        '「行ったことがある」は have been to。have gone to は「行ってしまって今いない」。',
        '「いつしたか」を具体的に言うときは過去形に切り替える。',
      ],
    },
    {
      id: 'u11-l3',
      unitId: 'u11',
      level: 'B1',
      title: '継続を表す現在完了',
      objective: '「ずっと〜している」という継続を現在完了で表し、for と since を使い分け、How long で期間を尋ねられるようになります。',
      minutes: 10,
      prereqs: ['u11-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '日本語の「〜しています」に注意',
          body:
            '**過去に始まって今も続く状態を、期間と一緒に伝える**ときは現在完了を使います。\n\n- I live in Tokyo. → 東京に住んでいます。現在の居住地を伝えています。\n- I have lived in Tokyo for three years. → 東京に3年間住んでいます。過去から今までの期間を含めて伝えています。\n\n「3年前から今も住んでいる」の意味で I live in Tokyo for three years. とは言いません。現在形に for を足すだけでは、ここで伝えたい継続を表せないためです。**今の状態だけか、今まで続いた期間も含むか**を確認しましょう。',
        },
        {
          type: 'timeline',
          title: '継続のイメージ',
          timelines: [
            {
              title: 'I have lived in Tokyo since 2020.',
              range: [55, 100],
              arrowToNow: true,
              rangeLabel: 'since 2020(起点から今まで)',
              caption: 'since は「始まった時点」を指します。2020年に始まり、今も続いています。',
            },
            {
              title: 'We have known each other for ten years.',
              range: [40, 100],
              arrowToNow: true,
              rangeLabel: 'for ten years(10年という長さ)',
              caption: 'for は「続いている期間の長さ」を表します。',
            },
          ],
        },
        {
          type: 'table',
          title: 'for と since の使い分け',
          headers: ['語', '後ろに続くもの', '例'],
          rows: [
            ['for', '期間の長さ', 'for three years / for a week / for a long time'],
            ['since', '始まった時点', 'since 2020 / since last month / since April'],
            ['since + 文', '「〜して以来」(主語 + 過去形)', 'since we met / since I was a child'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have lived in Tokyo for three years.', ja: '東京に3年間住んでいます。', highlight: 'for three years' },
            { en: 'She has worked at this hospital since 2021.', ja: '彼女は2021年からこの病院で働いています。', highlight: 'since 2021' },
            { en: 'We have known each other since we were in high school.', ja: '私たちは高校時代からの知り合いです。', highlight: 'since we were in high school', note: 'since のあとには文(主語 + 過去形)も置けます。' },
            { en: "I haven't seen him for a month.", ja: '彼にはこの1か月会っていません。', highlight: 'for a month', note: '「会っていない状態」が続いている、という否定の継続です。' },
            { en: 'How long have you had that phone?', ja: 'その電話はどれくらい使っているのですか。', highlight: 'How long' },
          ],
        },
        {
          type: 'explanation',
          title: 'How long で期間を尋ねる',
          body:
            '「どれくらい(の間)〜していますか」は **How long have you + 過去分詞 ...?** で尋ねます。\n\n- How long have you lived here? — For five years. / Since 2021.\n\n答えは for / since を使って短く返せます。\n\nもうひとつ大事な注意。know / have(持っている)/ be / like のような**状態動詞**の継続は、この現在完了が基本の形です。U02で学んだとおり状態動詞は進行形にしないので、「ずっと知っている」を × I am knowing とは言えません。',
        },
      ],
      quiz: [
        {
          id: 'u11-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'We have been friends ___ we were children.',
          sentenceJa: '私たちは子どものころからの友達です。',
          choices: ['for', 'since', 'from', 'during'],
          correctIndex: 1,
          explanation: '後ろに「始まった時点」を表す文(we were children)が続いているので since を使います。for の後ろには期間の長さが来ます。',
          choiceNotes: ['for の後ろは three years のような期間の長さです。', null, '現在完了の継続では from ではなく since を使います。', 'during は「〜の間に」という意味で、この形では使えません。'],
          audioEn: 'We have been friends since we were children.',
        },
        {
          id: 'u11-l3-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「私はこの会社で5年間働いています(今も働いています)」と言いたいとき。',
          choices: [
            'I work for this company for five years.',
            'I am working for this company for five years.',
            'I have worked for this company for five years.',
            'I worked for this company since five years.',
          ],
          correctIndex: 2,
          explanation: '過去に始まり今も続いていることは現在完了で表します。現在形や現在進行形は「どれくらい続いているか」という期間と組み合わせられません。',
          choiceNotes: ['現在形は「今の習慣・事実」を表すだけで、for five years のような継続期間とは組み合わせられません。', '現在進行形も「今までどれくらい続いたか」は表せません。', null, 'since の後ろは「始まった時点」です。five years という長さには for を使い、時制も現在完了にします。'],
          audioEn: 'I have worked for this company for five years.',
        },
        {
          id: 'u11-l3-q3',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'Mr. Tanaka lived in Osaka for ten years.',
          choices: ['田中さんは今も大阪に住んでいる。', '田中さんは今は大阪に住んでいない可能性が高い。', '田中さんは10年前に大阪に引っ越した。', '田中さんはこれから10年間大阪に住む予定だ。'],
          correctIndex: 1,
          explanation: '過去形 + for ten years は「(過去に)10年間住んでいた」という終わった期間を表し、今は住んでいないことを示唆します。今も続いているなら has lived と現在完了にします。',
          choiceNotes: ['今も続いているなら現在完了 has lived を使うはずです。', null, '「10年間住んだ」という期間の話で、10年前に引っ越したとは限りません。', '過去形なので未来の予定ではありません。'],
          audioEn: 'Mr. Tanaka lived in Osaka for ten years.',
        },
        {
          id: 'u11-l3-q4',
          prompt: '自然な質問文を選んでください。',
          sentenceJa: '相手に「その犬はどれくらい飼っているの?」と尋ねたいとき。',
          choices: ['How long do you have your dog?', 'How long have you had your dog?', 'How long are you having your dog?', 'When have you had your dog?'],
          correctIndex: 1,
          explanation: '今まで続いている期間は How long + 現在完了で尋ねます。have(飼っている)は状態動詞なので進行形にはしません。',
          choiceNotes: ['現在形では「どれくらい続いているか」を尋ねられません。', null, 'have(飼っている・持っている)は状態動詞なので進行形にしません。', 'When は「いつ」という一点を尋ねる語で、期間を尋ねることはできません。'],
          audioEn: 'How long have you had your dog?',
        },
      ],
      summary: [
        '過去に始まって今も続く状態は現在完了で表す。「東京に3年住んでいます」= I have lived in Tokyo for three years.',
        'for + 期間の長さ(for three years)、since + 始まった時点(since 2020 / since I was a child)。',
        '期間を尋ねるときは How long have you + 過去分詞。答えは For … / Since … で短く返せる。',
        '過去形 + for は「終わった期間」。今も続くなら現在完了。時制で意味が変わる。',
      ],
    },
    {
      id: 'u11-l4',
      unitId: 'u11',
      level: 'B1',
      title: '完了・結果を表す現在完了',
      objective: 'just / already / yet を使って「ちょうど〜した」「もう〜した」「まだ〜していない」という完了・結果を表せるようになります。',
      minutes: 10,
      prereqs: ['u11-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '「たった今」の完了が「今」を説明する',
          body:
            '「ちょうど宿題が終わった」「もう昼ご飯を食べた」「まだメールを送っていない」——これらはどれも、**完了したこと(または未完了のこと)で今の状況を説明**しています。\n\n- 宿題が終わった → だから今は遊べる\n- もう食べた → だから今はお腹がすいていない\n- まだ送っていない → だから今も送る必要がある\n\n伝えたいのは「今どういう状態か」。だからここでも現在完了を使います。',
        },
        {
          type: 'timeline',
          title: '完了・結果のイメージ',
          timelines: [
            {
              title: 'I have just finished my homework.',
              point: 90,
              pointLabel: '宿題が終わった',
              range: [90, 100],
              arrowToNow: true,
              rangeLabel: '「終わった状態」が今も',
              caption: '「今」のすぐ手前で完了し、その結果が今に残っています。',
            },
          ],
        },
        {
          type: 'table',
          title: 'just / already / yet の整理',
          headers: ['語', '意味', '位置', '使う文'],
          rows: [
            ['just', 'ちょうど・たった今', 'have / has と過去分詞の間', '肯定文'],
            ['already', 'もう・すでに', 'have / has と過去分詞の間', '肯定文'],
            ['yet', '否定文で「まだ」/ 疑問文で「もう」', '文末', '否定文・疑問文'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have just finished my homework.', ja: 'ちょうど宿題が終わったところです。', highlight: 'just' },
            { en: 'The train has just left.', ja: '電車はたった今出たところです。', highlight: 'has just left' },
            { en: 'She has already eaten lunch.', ja: '彼女はもう昼食を食べました。', highlight: 'already' },
            { en: "I haven't sent the email yet.", ja: 'まだそのメールを送っていません。', highlight: 'yet', note: '否定文の yet は「まだ〜していない」。' },
            { en: 'Have you packed your bag yet?', ja: 'もうかばんの準備はできましたか。', highlight: 'yet', note: '疑問文の yet は「もう〜したか」。' },
          ],
        },
        {
          type: 'explanation',
          title: '結果を伝える現在完了',
          body:
            'just / already / yet がなくても、現在完了は「〜した結果、今こうだ」を伝えられます。\n\n- I **have washed** the car.(洗った → 今きれい)\n- Someone **has taken** my umbrella.(持って行かれた → 今ない)\n\n聞き手が知りたいのは「今どうなのか」。それを直前の出来事で説明するのが、この用法の心臓部です。',
        },
      ],
      quiz: [
        {
          id: 'u11-l4-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Dinner is ready, but the kids ___ their hands yet.',
          sentenceJa: '夕食の準備ができましたが、子どもたちはまだ手を洗っていません。',
          choices: ["haven't washed", "haven't wash", "hasn't washed", "didn't washed"],
          correctIndex: 0,
          explanation: "主語 the kids は複数なので haven't を使い、そのあとは過去分詞 washed を続けます。",
          choiceNotes: [null, "haven't のあとは過去分詞です。原形 wash は使えません。", "主語が複数なので hasn't は使えません。", "didn't のあとは原形が来るので didn't washed という形はありません。"],
          audioEn: "Dinner is ready, but the kids haven't washed their hands yet.",
        },
        {
          id: 'u11-l4-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「電車はたった今出たところです」と言いたいとき。',
          choices: ['The train has just left.', 'The train just has left.', 'The train has left just.', 'Just the train has left.'],
          correctIndex: 0,
          explanation: 'just は have / has と過去分詞の間に置きます。',
          choiceNotes: [null, 'just は has の前ではなく、has と過去分詞の間に置きます。', 'この意味の just を文末に置くことはできません。', '文頭の Just は「〜だけ」という別の意味に見えてしまいます。'],
          audioEn: 'The train has just left.',
        },
        {
          id: 'u11-l4-q3',
          prompt: '次の文から分かる「今の状況」を選んでください。',
          sentence: 'Someone has taken my umbrella.',
          choices: ['傘は今、手元にない。', '傘は今、手元にある。', '傘は昔からずっと持っていない。', 'これから傘を取られそうだ。'],
          correctIndex: 0,
          explanation: '現在完了は「持って行かれた結果、今ない」という現在の状況を伝えます。',
          choiceNotes: [null, '「取られた」結果なので、今は手元にありません。', '「昔からずっと」という継続ではなく、出来事の結果が今に残っている文です。', '未来の予測ではなく、すでに起きたことです。'],
          audioEn: 'Someone has taken my umbrella.',
        },
        {
          id: 'u11-l4-q4',
          prompt: '会話として自然なものを選んでください。',
          sentence: "___ — No, not yet. I'll do it after dinner.",
          sentenceJa: '「もうレポートは書き終えた?」—「いや、まだ。夕食のあとにやるよ。」',
          choices: ['Have you finished the report yet?', 'Did you finish the report yesterday?', 'Have you finished the report never?', 'Do you finish the report yet?'],
          correctIndex: 0,
          explanation: '「もう〜した?」は現在完了の疑問文 + 文末の yet で表します。答えの Not yet.(まだ)とも自然にかみ合います。',
          choiceNotes: [null, '「昨日終えたか」という過去の一点の質問になり、Not yet.(まだこれからやる)という答えとかみ合いません。', 'never を疑問文の文末に置くことはできません。', '「もう終えたか」という完了の質問は現在形では表せません。'],
          audioEn: 'Have you finished the report yet?',
        },
      ],
      summary: [
        'just(ちょうど)と already(もう)は have / has と過去分詞の間、yet は文末に置く。',
        'yet は否定文で「まだ〜していない」、疑問文で「もう〜したか」。',
        '完了・結果の現在完了は「〜した結果、今どうなのか」を伝える表現。',
      ],
    },
    {
      id: 'u11-l5',
      unitId: 'u11',
      level: 'B1',
      title: '現在完了 vs 過去形',
      objective: '文が「今」とつながっているかどうかを基準に、現在完了と過去形を正しく使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u11-l4'],
      blocks: [
        {
          type: 'explanation',
          title: 'まず「話している時間の範囲」を確認する',
          body:
            'まず、**どの時間をひとまとまりとして話しているか**を確認します。\n\n- **終わった過去の時点・期間**を指定する → 過去形。I lost my key yesterday.\n- **今までの経験・継続や、今に残る結果**を伝える → 現在完了。I have lost my key.\n\n過去形でも、現在に関係する出来事は話せます。違いは「今に影響があるかどうか」だけではなく、どの時間に注目して伝えるかです。\n\nアメリカ英語では、Did you eat yet? / I just finished. のように、yet や just と過去形を使うこともよくあります。**特定の単語だけで時制を決めず、文脈と合わせて判断**しましょう。',
        },
        {
          type: 'timeline',
          title: '同じ for five years でも意味が違う',
          timelines: [
            {
              title: '過去形: I worked there for five years.',
              range: [30, 60],
              rangeLabel: '5年間(もう終わった)',
              caption: '期間は過去の中で完結しています。今は働いていません。',
            },
            {
              title: '現在完了: I have worked there for five years.',
              range: [60, 100],
              arrowToNow: true,
              rangeLabel: '5年間(今も継続中)',
              caption: '期間が今まで続いています。今も働いています。',
            },
          ],
        },
        {
          type: 'contrast',
          title: '過去形 vs 現在完了',
          left: {
            label: '過去形(今とは切れている)',
            items: [
              { en: 'I lost my key yesterday.', ja: '昨日カギをなくしました。', highlight: 'lost' },
              { en: 'She lived in Paris for two years.', ja: '彼女は2年間パリに住んでいました(今は住んでいません)。', highlight: 'lived' },
              { en: 'When did you buy that bike?', ja: 'その自転車はいつ買ったのですか。', highlight: 'did you buy' },
            ],
            pointJa: '「いつ」が言える・尋ねられる。yesterday / last week / ago / when と使う',
          },
          right: {
            label: '現在完了(今とつながっている)',
            items: [
              { en: 'I have lost my key.', ja: 'カギをなくしてしまいました(今もありません)。', highlight: 'have lost' },
              { en: 'She has lived in Paris for two years.', ja: '彼女はパリに2年間住んでいます(今も住んでいます)。', highlight: 'has lived' },
              { en: 'How long have you had that bike?', ja: 'その自転車はどれくらい使っているのですか。', highlight: 'have you had' },
            ],
            pointJa: '「今どうか」を伝える。「いつ」は言わない',
          },
          note: '現在完了は yesterday / last year / two days ago / when など、**特定の過去の時点を表す語句と一緒に使えません**。',
        },
        {
          type: 'explanation',
          title: '時の表現との相性(ただし過信は禁物)',
          body:
            "目安としての相性はあります。\n\n- 過去形と使う: yesterday / last week / three days ago / in 2019 / when I was a child\n- 現在完了と使う: since / ever / never / yet / just / already / How long\n\nただし **for は両方で使えます**。I worked there for five years.(終わった5年間)/ I have worked there for five years.(今も続く5年間)。\n\nまた、today や this morning は「その時間がまだ続いているか」で変わります。今が午前中なら I haven't seen him this morning.(今朝はまだ会っていない)、午後になってからなら I didn't see him this morning.(今朝は会わなかった = 朝はもう終わった時間)です。",
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I saw that movie last weekend.', ja: 'その映画は先週末に見ました。', highlight: 'saw', note: 'last weekend という過去の時点があるので過去形。' },
            { en: 'I have seen that movie three times.', ja: 'その映画は3回見たことがあります。', highlight: 'have seen', note: '「いつ」は言わず、今までの経験として。' },
            { en: 'My grandfather worked at a bank for 40 years.', ja: '祖父は銀行に40年間勤めていました(今は勤めていません)。', highlight: 'worked' },
            { en: 'Emi has worked at the bank since April.', ja: 'エミは4月からその銀行で働いています。', highlight: 'has worked' },
            { en: 'When did you arrive in Japan?', ja: 'いつ日本に着いたのですか。', highlight: 'When did', note: 'When(いつ)は必ず過去形と使います。× When have you arrived?' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u11-l5-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'When ___ your first smartphone?',
          sentenceJa: '初めてのスマートフォンはいつ買ったのですか。',
          choices: ['have you bought', 'did you buy', 'do you buy', 'have you buy'],
          correctIndex: 1,
          explanation: 'When(いつ)は特定の過去の時点を尋ねる語なので、必ず過去形と使います。「いつ」を問題にしない現在完了とは組み合わせられません。',
          choiceNotes: ['現在完了は「いつ」を問題にしない形なので、When とは一緒に使えません。', null, '現在形では過去の出来事を尋ねられません。', 'have のあとに原形 buy を置くこの形は文法的に成り立ちません。'],
          audioEn: 'When did you buy your first smartphone?',
        },
        {
          id: 'u11-l5-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My uncle ___ in London for six years before he came back to Japan.',
          sentenceJa: 'おじは日本に戻る前、ロンドンに6年間住んでいました。',
          choices: ['has lived', 'lives', 'lived', 'has been living'],
          correctIndex: 2,
          explanation: 'before he came back(戻る前)から、この6年間はすでに終わった過去の期間だと分かります。for があっても、終わった期間なら過去形です。',
          choiceNotes: ['現在完了だと「今もロンドンに住んでいる」ことになり、日本に戻ったという内容と矛盾します。', '現在形は今の事実を表すので合いません。', null, 'この形も「今も住み続けている」という意味になってしまいます。'],
          audioEn: 'My uncle lived in London for six years before he came back to Japan.',
        },
        {
          id: 'u11-l5-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「夏目漱石は多くの小説を書いた」と言いたいとき。',
          choices: [
            'Natsume Soseki has written many novels.',
            'Natsume Soseki wrote many novels.',
            'Natsume Soseki writes many novels.',
            'Natsume Soseki has been writing many novels.',
          ],
          correctIndex: 1,
          explanation: '漱石はすでに亡くなっているので、「今」につながる現在完了は使えません。完結した過去の事実として過去形で述べます。',
          choiceNotes: ['現在完了は「今」につながる形なので、すでに亡くなった人の業績には使いません。', null, '現在形では過去の業績を述べられません。', '「今も書き続けている」という意味になってしまいます。'],
          audioEn: 'Natsume Soseki wrote many novels.',
        },
        {
          id: 'u11-l5-q4',
          prompt: '状況に合う文を選んでください。',
          sentenceJa: '今は午後8時。「今朝はコーヒーを飲まなかった」と言いたいとき。',
          choices: [
            "I haven't drunk coffee this morning.",
            "I didn't drink coffee this morning.",
            "I don't drink coffee this morning.",
            "I haven't drunk coffee since this morning.",
          ],
          correctIndex: 1,
          explanation: '午後8時の時点で「今朝」はすでに終わった時間です。終わった時間の中の話は過去形で表します。',
          choiceNotes: ['現在完了が使えるのは「今朝」がまだ続いている(= 今が午前中の)ときです。', null, '現在形は習慣を表すので、この場面には合いません。', 'since this morning は「今朝から今までずっと飲んでいない」という別の意味になります。'],
          audioEn: "I didn't drink coffee this morning.",
        },
      ],
      summary: [
        '基準は「今」の話かどうか。今の状態を伝えるなら現在完了、過去の時点の話なら過去形。',
        'yesterday / ago / last … / when など特定の過去の時点を表す語句は過去形とだけ使う。',
        'for は両方で使える。終わった期間なら過去形、今も続く期間なら現在完了。',
        'this morning / today は、その時間が終わっていれば過去形、まだ続いていれば現在完了。',
      ],
    },
    {
      id: 'u11-l6',
      unitId: 'u11',
      level: 'B1',
      title: '現在完了 総合練習',
      objective: '経験・継続・完了・結果の用法を文脈から見分け、過去形も含めて適切な形を選べるようになります。',
      minutes: 12,
      prereqs: ['u11-l5'],
      blocks: [
        {
          type: 'explanation',
          title: '4つの顔、1つの心臓',
          body:
            '現在完了には「経験」「継続」「完了・結果」という顔がありますが、心臓部はすべて同じ——**過去の出来事で「今」を語る**ことです。\n\n- 経験: 今までの人生に何があるか → I have been to Kyoto three times.\n- 継続: 過去に始まり今も続く → I have lived here since 2020.\n- 完了・結果: 完了した結果が今こうだ → I have just finished lunch.\n\n用法を分類すること自体が目的ではありません。「この文は今について何を言っているのか」を読み取れれば十分です。',
        },
        {
          type: 'timeline',
          title: '3つの用法をタイムラインで',
          timelines: [
            {
              title: '経験: I have seen this movie twice.',
              range: [0, 100],
              arrowToNow: true,
              rangeLabel: '今までの人生',
              caption: '人生という期間の中に出来事が2回。',
            },
            {
              title: '継続: I have lived here since 2020.',
              range: [60, 100],
              arrowToNow: true,
              rangeLabel: '2020年から今もずっと',
              caption: '始まりから今まで途切れずに続く。',
            },
            {
              title: '完了・結果: I have just finished lunch.',
              point: 92,
              pointLabel: '食べ終えた',
              caption: '直前の完了。その結果が今の状態を作る。',
            },
          ],
        },
        {
          type: 'table',
          title: '用法の見分けチャート',
          headers: ['用法', 'よく一緒に使う表現', '例', '伝えたい「今」'],
          rows: [
            ['経験', 'ever / never / before / 回数', 'Have you ever been to Nara?', '今までにその経験を持っているか'],
            ['継続', 'for / since / How long', 'She has worked here for ten years.', '今も続いている'],
            ['完了・結果', 'just / already / yet', 'The bus has just left.', '完了した結果、今こうだ'],
          ],
        },
        {
          type: 'examples',
          title: '例文(用法を意識しながら)',
          items: [
            { en: 'I have never eaten oysters.', ja: 'カキは一度も食べたことがありません。', highlight: 'have never eaten', note: '経験。' },
            { en: 'We have been busy since Monday.', ja: '月曜日からずっと忙しいです。', highlight: 'have been busy', note: '継続。' },
            { en: 'She has already booked the tickets.', ja: '彼女はもうチケットを予約しました。', highlight: 'has already booked', note: '完了・結果。' },
            { en: 'Have you two met before?', ja: 'お二人は以前に会ったことがありますか。', highlight: 'met before', note: '経験。' },
            { en: "My phone has died, so I can't check the map.", ja: '携帯の電池が切れてしまって、地図が確認できません。', highlight: 'has died', note: '結果が今に残っています。' },
          ],
        },
        {
          type: 'explanation',
          title: 'キーワードに頼りすぎない',
          body:
            '時を表す語句は手がかりになりますが、それだけで時制を決められるわけではありません。\n\n- for は過去形とも現在完了とも使える(l5で学習)\n- just には「ただ〜だけ」という時制と無関係な意味もある(I just want tea.)\n- 質問が現在完了でも、特定の時点を答えるなら過去形に切り替える(Yes, I saw it last year.)\n\n最後の判断は常に**文脈**です。「この文は今について語っているか?」と自分に問いかけましょう。',
        },
      ],
      quiz: [
        {
          id: 'u11-l6-q1',
          prompt: '次の文が伝えている内容として正しいものを選んでください。',
          sentence: 'Aya has been a nurse for twenty years.',
          choices: ['アヤは今も看護師をしている。', 'アヤは昔20年間看護師だったが、今は違う。', 'アヤは一度だけ看護師をしたことがある。', 'アヤは20年後に看護師になる予定だ。'],
          correctIndex: 0,
          explanation: '現在完了 + for は「過去に始まり今も続いている」という継続を表します。アヤは今も看護師です。',
          choiceNotes: [null, '「昔〜だったが今は違う」なら過去形 was a nurse for twenty years を使います。', '回数や before がなく for twenty years があるので、経験ではなく継続の意味です。', '現在完了は未来のことを表しません。'],
          audioEn: 'Aya has been a nurse for twenty years.',
        },
        {
          id: 'u11-l6-q2',
          prompt: '会話の空所に入るものを選んでください。',
          sentence: "Where's Mari? — She ___ to the post office. She'll be back in ten minutes.",
          sentenceJa: '「マリはどこ?」—「郵便局に行っています。10分で戻りますよ。」',
          choices: ['has gone', 'has been', 'has never gone', 'was'],
          correctIndex: 0,
          explanation: '「行ってしまって今ここにいない」ので has gone to を使います。has been to だと「行ったことがある」という経験になります。',
          choiceNotes: [null, 'has been to は「行ったことがある」という経験で、今いない理由の説明になりません。', '「一度も行ったことがない」では会話が成り立ちません。', 'be動詞の過去形をこの形(was to + 場所)で使うことはできません。'],
          audioEn: "She has gone to the post office. She'll be back in ten minutes.",
        },
        {
          id: 'u11-l6-q3',
          prompt: '正しい文を選んでください。',
          choices: [
            'I have visited Korea last year.',
            'How long do you know Mr. Sato?',
            'We have been friends since 2015.',
            'She has finished the report two days ago.',
          ],
          correctIndex: 2,
          explanation: 'since 2015(2015年から今まで)と現在完了の組み合わせは正しい継続の形です。他の文は、特定の過去の時点と現在完了を組み合わせたり、継続を現在形で表したりしている点が誤りです。',
          choiceNotes: ['last year という特定の過去の時点があるので過去形 visited を使います。', '「どれくらい前から知っているか」という継続は現在完了 have you known で尋ねます。', null, 'two days ago があるので過去形 finished を使います。'],
          audioEn: 'We have been friends since 2015.',
        },
        {
          id: 'u11-l6-q4',
          prompt: '会話の空所に入る形を選んでください。',
          sentence: 'Have you seen the new Godzilla movie? — Yes, I ___ it with my brother on Saturday.',
          sentenceJa: '「新しいゴジラ映画はもう見た?」—「うん、土曜日に弟と見たよ。」',
          choices: ['have seen', 'saw', 'have watched', 'see'],
          correctIndex: 1,
          explanation: '質問は現在完了でも、「土曜日に」という特定の時点を添えて答えるときは過去形に切り替えます。',
          choiceNotes: ['on Saturday という特定の時点があるので現在完了は使えません。', null, '動詞を watch に変えても、on Saturday がある以上、現在完了にはできません。', '過去の出来事なので現在形は使えません。'],
          audioEn: 'Yes, I saw it with my brother on Saturday.',
        },
      ],
      summary: [
        '現在完了の心臓部は「過去の出来事で今を語る」。経験・継続・完了・結果はその表れ方の違い。',
        '経験は ever / never / 回数、継続は for / since / How long、完了・結果は just / already / yet が目印になりやすい。',
        'ただしキーワードは万能ではない。特定の過去の時点が出てきたら過去形に切り替える。',
        '迷ったら「この文は今について何を言っているか」を考える。',
      ],
    },
  ],
}
