import type { GrammarUnit } from '../../types'

// U12 未来表現の発展 — A2で学んだ will / be going to に「現在進行形の予定」を加え、
// 3つの未来表現の使い分けと、時・条件の副詞節のルールまでを扱う。

export const u12: GrammarUnit = {
  id: 'u12',
  level: 'B1',
  title: '未来表現の発展',
  lessons: [
    {
      id: 'u12-l1',
      unitId: 'u12',
      level: 'B1',
      title: '現在進行形で表す予定',
      objective: '現在進行形を使って、すでに約束や手配が済んだ「確定した予定」を自然に伝えられるようになります。',
      minutes: 10,
      prereqs: ['u02-l1', 'u02-l6'],
      blocks: [
        {
          type: 'explanation',
          title: '現在進行形は「手帳に書いてある予定」も表す',
          body:
            '現在進行形は「今まさにしていること」を表す形でした。実はもうひとつ、とても大事な使い方があります。**すでに決まっていて、手配や約束まで済んでいる予定**です。\n\n- I **am meeting** Ken tomorrow.(明日ケンと会うことになっています)\n\nケンと連絡を取り、時間と場所を決めてある——つまり**手帳やカレンダーに書き込めるくらい確定した予定**、というニュアンスです。ネイティブは自分の予定を話すとき、この形をとてもよく使います。\n\n未来の話だと分かるように、tomorrow / next week / on Friday のような**時を表す語句**を添えるのが基本です。',
        },
        {
          type: 'timeline',
          title: '同じ形が表す2つの時間',
          timelines: [
            {
              title: '今の動作: I am having lunch now.',
              range: [92, 100],
              arrowToNow: true,
              rangeLabel: '今まさに進行中',
              caption: 'これまで学んだ「今している最中」の使い方です。',
            },
            {
              title: '確定した予定: I am meeting Ken tomorrow.',
              point: 115,
              pointLabel: '明日ケンと会う(約束済み)',
              caption: '未来の一点の予定。約束・手配はすでに済んでいます。tomorrow が未来の目印です。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I am meeting Emi for lunch tomorrow.', ja: '明日エミとランチを食べることになっています。', highlight: 'am meeting' },
            { en: 'We are flying to Okinawa next Friday.', ja: '来週の金曜日、飛行機で沖縄に行きます。', highlight: 'are flying', note: 'チケットを買ってある、というニュアンスまで伝わります。' },
            { en: 'She is seeing the dentist at three.', ja: '彼女は3時に歯医者の予約があります。', highlight: 'is seeing' },
            { en: 'What are you doing this weekend?', ja: '今週末は何か予定ある?', highlight: 'are you doing', note: '相手の予定を尋ねる定番の言い方です。' },
            { en: 'I am not working next Monday.', ja: '来週の月曜日は仕事が休みです。', highlight: 'am not working', note: 'すでに休みを取ってある、という確定した予定です。' },
          ],
        },
        {
          type: 'explanation',
          title: '「確定」の中身は、相手との約束や手配',
          body:
            'この使い方のポイントは、**自分の頭の中だけで決めた話ではない**ということです。\n\n- 相手と約束した(会う時間・場所が決まっている)\n- チケットや席を予約した\n- 職場に休みを申請した\n\nこうした「外の世界との段取り」が済んでいるとき、現在進行形がぴったりきます。\n\n「行こうと決めてはいるけれど、まだ何も手配していない」段階なら be going to の出番です。この線引きは次のレッスンでじっくり整理します。',
        },
      ],
      quiz: [
        {
          id: 'u12-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: "I can't come to the party tonight. I ___ my grandmother in Nagoya.",
          sentenceJa: '今夜のパーティーには行けません。名古屋の祖母を訪ねることになっているんです。',
          choices: ['am visiting', 'visit', 'will visiting', 'am visit'],
          correctIndex: 0,
          explanation: 'すでに決まっている確定した予定なので現在進行形 am visiting を使います。パーティーを断る理由になるほど固まった予定です。',
          choiceNotes: [null, '現在形は習慣やいつでも成り立つ事実を表すので、特定の日の予定には使えません。', 'will の後ろは動詞の原形です。will visiting という形はありません。', 'be動詞の後ろに動詞の原形は置けません。-ing形が必要です。'],
          audioEn: "I can't come to the party tonight. I am visiting my grandmother in Nagoya.",
        },
        {
          id: 'u12-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '来週の火曜日に医者の予約を取ってあり、「火曜日に診てもらいます」と伝えたいとき。',
          choices: [
            'I see the doctor next Tuesday.',
            "I'm seeing the doctor next Tuesday.",
            "I'm see the doctor next Tuesday.",
            'I will seeing the doctor next Tuesday.',
          ],
          correctIndex: 1,
          explanation: '予約済みの確定した予定は現在進行形で表します。be動詞 + -ing形の組み合わせを崩さないことにも注意しましょう。',
          choiceNotes: ['現在形は「毎週火曜に診てもらう」という習慣に聞こえてしまいます。', null, "I'm の後ろに動詞の原形 see は置けません。seeing にします。", 'will の後ろは原形です。will see なら形は正しくなります。'],
          audioEn: "I'm seeing the doctor next Tuesday.",
        },
        {
          id: 'u12-l1-q3',
          prompt: '次の文から分かることを選んでください。',
          sentence: "We're having a barbecue on Saturday.",
          choices: [
            '土曜日のバーベキューはすでに決まっていて、準備が進んでいる。',
            '今まさにバーベキューをしている最中だ。',
            'バーベキューをするかどうか、まだ迷っている。',
            '毎週土曜日にバーベキューをする習慣がある。',
          ],
          correctIndex: 0,
          explanation: 'on Saturday という未来の時を表す語句があるので、これは「今の動作」ではなく確定した予定の現在進行形です。人を誘い、日取りを決めてある状況が伝わります。',
          choiceNotes: [null, 'on Saturday(土曜日に)という未来の語句があるので、今の動作ではありません。', '迷っている段階の話なら、確定を表すこの形は使いません。', '習慣を表すのは現在形(We have a barbecue every Saturday.)です。'],
          audioEn: "We're having a barbecue on Saturday.",
        },
        {
          id: 'u12-l1-q4',
          prompt: '会話の空所に入るものを選んでください。',
          sentence: '___ anything this weekend? — Not yet. Why?',
          sentenceJa: '「今週末、何か予定ある?」—「まだ何も。どうして?」',
          choices: ['Are you doing', 'Do you do', 'Will you doing', 'Did you do'],
          correctIndex: 0,
          explanation: '相手の「決まっている予定」を尋ねるので現在進行形の疑問文 Are you doing ...? を使います。週末の予定を聞く定番表現です。',
          choiceNotes: [null, '現在形では「ふだん週末に何をするか」という習慣の質問になってしまいます。', 'will の後ろは原形なので Will you doing という形はありません。', '過去形では「先週末何をしたか」という過去の質問になります。'],
          audioEn: 'Are you doing anything this weekend?',
        },
      ],
      summary: [
        '現在進行形は「今の動作」だけでなく、約束・手配まで済んだ確定した予定も表す。',
        'tomorrow / next week など時を表す語句を添えて、未来の話だと分かるようにする。',
        '相手との約束、予約、休みの申請など「段取りが済んでいる」ことがこの形の合図。',
        '決めただけでまだ手配していないなら be going to(次のレッスンで整理)。',
      ],
    },
    {
      id: 'u12-l2',
      unitId: 'u12',
      level: 'B1',
      title: 'will vs be going to vs 現在進行形',
      objective: '「いつ・どこまで決まっているか」を基準に、will / be going to / 現在進行形の3つの未来表現を使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u12-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '未来表現は「何を伝えるか」で選ぶ',
          body:
            '同じ未来の出来事でも、**今の決定・前からの意図・具体的な予定のどれを伝えるか**で表現を選びます。\n\n- **will**: その場で「そうしよう」と決める、申し出る、約束する。\n- **be going to**: すでに持っている「そうするつもり」を伝える。\n- **現在進行形**: 相手との約束や予約など、具体的な予定を伝える。\n\nこの3つは、必ず順番に上がる「確実さの階段」ではありません。手配済みの予定を be going to で話すこともできます。また、will と be going to には**予測**の用法もあるので、まず「予定の話か、予測の話か」を分けて考えましょう。',
        },
        {
          type: 'table',
          title: '3つの未来表現の整理',
          headers: ['形', '中心の意味', '典型的な場面', '例'],
          rows: [
            ['will + 原形', 'その場の決定・申し出・予測', '頼まれて引き受ける、注文する', "I'll help you with that."],
            ['be going to + 原形', '前から決めていた意図・根拠のある予測', '計画を語る、目の前の兆候から予測する', "I'm going to learn Spanish next year."],
            ['現在進行形', '手配・約束まで済んだ確定した予定', '手帳に書いてある予定を伝える', "I'm meeting Ken at six."],
          ],
        },
        {
          type: 'contrast',
          title: 'will vs be going to: いつ決めたか',
          left: {
            label: 'will(その場で決めた)',
            items: [
              { en: "The phone is ringing. I'll get it.", ja: '電話が鳴ってる。私が出るよ。', highlight: "I'll get" },
              { en: "I'll have the salmon, please.", ja: 'サーモンをお願いします。', highlight: "I'll have", note: 'メニューを見て今決めた注文です。' },
            ],
            pointJa: '決めるのは話しているまさにその瞬間',
          },
          right: {
            label: 'be going to(前から決めていた)',
            items: [
              { en: "I'm going to sell my car. I decided last month.", ja: '車を売るつもりです。先月決めました。', highlight: "I'm going to sell" },
              { en: "We're going to visit my parents this summer.", ja: 'この夏は両親のところへ行くつもりです。', highlight: "We're going to visit" },
            ],
            pointJa: '話す前からすでに決めてあった意図',
          },
          note: '相手の話を聞いて「じゃあ私が〜するよ」と引き受けるのは、その場の決定なので必ず will です。× 電話が鳴った瞬間に I\'m going to get it. と言うと「前から出るつもりだった」ように響きます。',
        },
        {
          type: 'timeline',
          title: '「決めた瞬間」がどこにあるか',
          timelines: [
            {
              title: "will: I'll get it.",
              point: 115,
              pointLabel: '未来の出来事',
              caption: '決めるのは「今」この瞬間。決心と発言が同時です。',
            },
            {
              title: "be going to / 現在進行形: I'm going to sell my car.",
              range: [70, 100],
              arrowToNow: true,
              rangeLabel: '意図・手配がすでにある',
              point: 115,
              pointLabel: '未来の出来事',
              caption: '決めたのは過去。その意図(または手配)を今も持ったまま、未来の出来事を語ります。',
            },
          ],
        },
        {
          type: 'explanation',
          title: '予測の使い分けと、be going to vs 現在進行形',
          body:
            '**予測**にも使い分けがあります。\n\n- **will**: 自分の考え・経験にもとづく予測。I think it **will** rain tomorrow.(たぶん降ると思う)\n- **be going to**: **目の前の根拠**から言う予測。Look at those black clouds. It**\'s going to** rain.(あの黒い雲を見て。降るよ)\n\n黒い雲という証拠が見えているときは be going to が自然です。\n\nもうひとつ、**be going to と現在進行形**の線引きは「手配が済んでいるか」です。\n\n- I**\'m going to** visit Hokkaido someday.(いつか行くつもり。手配なし)\n- I**\'m visiting** Hokkaido next week.(来週行く。チケットも宿も取ってある)\n\nただし両者の境界はゆるやかで、手配済みの予定を be going to で言っても間違いではありません。「確定した予定は現在進行形のほうがより自然」という感覚で十分です。',
        },
        {
          type: 'examples',
          title: '例文(決まり具合を意識しながら)',
          items: [
            { en: "It's hot in here. I'll open the window.", ja: 'ここ暑いね。窓を開けるよ。', highlight: "I'll open", note: '今気づいて、今決めた。' },
            { en: "I'm going to start jogging next month.", ja: '来月からジョギングを始めるつもりです。', highlight: "I'm going to start", note: '前から決めている意図。' },
            { en: "I'm playing tennis with Aya on Sunday.", ja: '日曜日はアヤとテニスをすることになっています。', highlight: "I'm playing", note: 'アヤと約束済みの確定した予定。' },
            { en: 'I think our team will win.', ja: 'うちのチームが勝つと思うよ。', highlight: 'will win', note: '自分の考えにもとづく予測。' },
            { en: "Slow down! We're going to miss the exit.", ja: 'スピード落として!出口を通り過ぎちゃうよ。', highlight: "We're going to miss", note: '目の前の状況が根拠の予測。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u12-l2-q1',
          prompt: '会話の空所に入るものを選んでください。',
          sentence: "It's cold in here. — OK, I ___ the window.",
          sentenceJa: '「ここ寒いね。」—「わかった、窓を閉めるよ。」',
          choices: ['will close', 'am going to close', 'am closing', 'closed'],
          correctIndex: 0,
          explanation: '相手の言葉を聞いて、その場で「閉めよう」と決めています。その場の決定は will で表します。',
          choiceNotes: [null, 'be going to だと「前から閉めるつもりだった」ことになり、会話の流れに合いません。', '現在進行形の予定は約束や手配が済んでいる場合に使います。その場の決定には合いません。', '過去形ではこれからする行動を表せません。'],
          audioEn: 'OK, I will close the window.',
        },
        {
          id: 'u12-l2-q2',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'Look at those black clouds. It ___ soon.',
          sentenceJa: 'あの黒い雲を見て。もうすぐ雨が降るよ。',
          choices: ['is going to rain', 'will rain', 'is raining', 'rains'],
          correctIndex: 0,
          explanation: '黒い雲という目の前の根拠があって「降る」と言っているので、be going to が最も自然です。',
          choiceNotes: [null, '文法的には可能ですが、目の前の証拠から言う予測は be going to が自然です。will は自分の考えによる予測に使います。', '現在進行形だと「今降っている」ことになり、soon(もうすぐ)と合いません。', '現在形は習慣や事実を表すので、この場面の予測には使えません。'],
          audioEn: 'Look at those black clouds. It is going to rain soon.',
        },
        {
          id: 'u12-l2-q3',
          prompt: '状況に最も合う文を選んでください。',
          sentenceJa: '来週の月曜にパリへ発ちます。航空券もホテルも予約済みで、それを友人に伝えたいとき。',
          choices: [
            "I'm flying to Paris next Monday.",
            "I think I'll fly to Paris next Monday.",
            "I'm going to fly to Paris someday.",
            'I fly to Paris every Monday.',
          ],
          correctIndex: 0,
          explanation: '航空券もホテルも手配済みの確定した予定なので、現在進行形が最も自然です。',
          choiceNotes: [null, "I think I'll ... は「たぶん行くと思う」という不確かな予測に聞こえ、予約済みの状況に合いません。", 'someday(いつか)では、来週という確定した予定を伝えられません。', '現在形のこの文は「毎週月曜に行く」という習慣の意味になってしまいます。'],
          audioEn: "I'm flying to Paris next Monday.",
        },
        {
          id: 'u12-l2-q4',
          prompt: '次の文から分かることを選んでください。',
          sentence: "We're going to buy a house next year.",
          choices: [
            '前から家を買うと決めていて、その計画を語っている。',
            'たった今、家を買うことを思いついた。',
            '今まさに家の購入手続きの最中だ。',
            '毎年家を買っている。',
          ],
          correctIndex: 0,
          explanation: 'be going to は前から決めていた意図・計画を表します。「来年買うつもりで準備している」という話し手の計画が伝わります。',
          choiceNotes: [null, 'その場の決定なら will を使います。be going to は前からの計画です。', 'be going to + 原形は未来の意図です。今の動作なら現在進行形(are buying)だけで表します。', '習慣を表すのは現在形です。この文は来年の計画の話です。'],
          audioEn: "We're going to buy a house next year.",
        },
      ],
      summary: [
        '使い分けの基準は「決まり具合」: その場の決定は will、前からの意図は be going to、手配済みの確定した予定は現在進行形。',
        '頼まれて引き受ける・注文するなど、話しながら決めることは必ず will。',
        '予測は、自分の考えなら will、目の前に根拠があるなら be going to。',
        'be going to と現在進行形の境界はゆるやか。確定した予定ほど現在進行形が自然になる。',
      ],
    },
    {
      id: 'u12-l3',
      unitId: 'u12',
      level: 'B1',
      title: '時・条件の副詞節と未来',
      objective: 'when や if などで始まる時・条件の節の中では、未来のことでも will を使わず現在形で表せるようになります。',
      minutes: 10,
      prereqs: ['u12-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '未来の話なのに現在形?',
          body:
            '「彼が着いたら電話するね」を英語にしてみましょう。「着く」のも「電話する」のも未来ですが——\n\n- **When he arrives**, I **will call** you.\n\nwhen の節の中は **arrives(現在形)** です。× When he will arrive とは言いません。\n\nこれが英語の大事なルールです: **時や条件を表す節(when 〜, if 〜 など)の中では、未来のことでも現在形を使う**。未来だという情報は主節の will が示してくれるので、節の中で繰り返す必要がない、と考えると納得しやすいでしょう。\n\n日本語の「着い**たら**」「終わっ**たら**」も過去形に見えて未来の話をしますね。「節の中の形は見た目どおりの時間ではない」という点は日英共通です。',
        },
        {
          type: 'table',
          title: 'このルールが働く接続詞',
          headers: ['接続詞', '意味', '例'],
          rows: [
            ['when', '〜するとき・〜したら', "When she gets home, we'll have dinner."],
            ['if', 'もし〜なら', "If it rains, we'll cancel the picnic."],
            ['before / after', '〜する前に / あとに', "I'll clean the room before the guests arrive."],
            ['until', '〜するまでずっと', "I'll wait here until the store opens."],
            ['as soon as', '〜したらすぐに', "I'll text you as soon as I arrive."],
          ],
        },
        {
          type: 'timeline',
          title: 'どちらの出来事も未来にある',
          timelines: [
            {
              title: 'when節: he arrives(形は現在形)',
              point: 110,
              pointLabel: '彼が着く',
              caption: '出来事としては未来ですが、when節の中なので現在形で書きます。',
            },
            {
              title: '主節: I will call you(willで未来を示す)',
              point: 120,
              pointLabel: '私が電話する',
              caption: '未来だという情報は主節の will が担当します。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'When he arrives, I will call you.', ja: '彼が着いたら電話しますね。', highlight: 'arrives' },
            { en: "If it rains tomorrow, we'll cancel the picnic.", ja: '明日雨が降ったら、ピクニックは中止にします。', highlight: 'rains', note: 'tomorrow があっても if 節の中は現在形です。' },
            { en: "I'll wait here until the store opens.", ja: '店が開くまでここで待ちます。', highlight: 'opens' },
            { en: "As soon as I get home, I'm going to take a shower.", ja: '家に着いたらすぐシャワーを浴びるつもりです。', highlight: 'get', note: '主節は will でなくても構いません。be going to や命令文も使えます。' },
            { en: 'Before you leave, please turn off the lights.', ja: '出る前に電気を消してください。', highlight: 'leave' },
          ],
        },
        {
          type: 'explanation',
          title: '落とし穴: 「〜かどうか」「いつ〜か」の if / when は will が使える',
          body:
            'このルールが働くのは、時・条件を表す**副詞の働きをする節**だけです。同じ if / when でも、「〜かどうか」「いつ〜か」という**名詞のかたまり**(動詞の目的語など)になっているときは、未来はそのまま will で表します。\n\n- I don\'t know **if she will come**.(彼女が来る**かどうか**分からない)← know の目的語\n- **If she comes**, we\'ll start the meeting.(彼女が来**たら**始めます)← 条件\n\n- Please tell me **when he will arrive**.(彼が**いつ着くのか**教えて)← tell の内容\n- **When he arrives**, please tell me.(彼が着い**たら**教えて)← 時\n\n見分け方はシンプルです。「〜かどうか」「いつ〜か」と訳せるなら名詞のかたまりなので will を使えます。「〜したら・〜するとき」と訳せるなら時・条件の節なので現在形です。',
        },
      ],
      quiz: [
        {
          id: 'u12-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: "I'll text you when I ___ at the station.",
          sentenceJa: '駅に着いたらメッセージを送りますね。',
          choices: ['arrive', 'will arrive', 'arrived', 'am going to arrive'],
          correctIndex: 0,
          explanation: 'when で始まる時の節の中では、未来のことでも現在形を使います。未来の情報は主節の will が示しています。',
          choiceNotes: [null, '時を表す when 節の中では will を使いません。', '過去形にすると過去の話になってしまいます。これから起こることです。', '時の節の中では be going to も使わず、現在形にします。'],
          audioEn: "I'll text you when I arrive at the station.",
        },
        {
          id: 'u12-l3-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「宿題が終わったら出かけていいよ」と言いたいとき。',
          choices: [
            'You can go out after you finish your homework.',
            'You can go out after you will finish your homework.',
            'You can went out after you finish your homework.',
            'You can go out after you finished your homework.',
          ],
          correctIndex: 0,
          explanation: 'after で始まる時の節の中は、未来のことでも現在形 finish を使います。',
          choiceNotes: [null, '時を表す after 節の中では will を使いません。', 'can の後ろは動詞の原形です。went は置けません。', 'まだ終えていない未来の話なので、過去形 finished は使えません。'],
          audioEn: 'You can go out after you finish your homework.',
        },
        {
          id: 'u12-l3-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            "I'll call you as soon as the meeting ends.",
            "We'll leave when Dad gets home.",
            'If you will be late, please tell me.',
            "Let's stay inside until the rain stops.",
          ],
          correctIndex: 2,
          explanation: '条件を表す if 節の中では未来のことも現在形で表すので、If you are late, please tell me. が正しい形です。他の3文は時の節の中が正しく現在形になっています。',
          choiceNotes: ['as soon as 節の中が現在形 ends になっていて正しい文です。', 'when 節の中が現在形 gets になっていて正しい文です。', null, 'until 節の中が現在形 stops になっていて正しい文です。'],
          audioEn: 'If you are late, please tell me.',
        },
        {
          id: 'u12-l3-q4',
          prompt: '空所に入る形を選んでください。',
          sentence: "I don't know if she ___ to the party.",
          sentenceJa: '彼女がパーティーに来るかどうか分かりません。',
          choices: ['will come', 'comes', 'came', 'is come'],
          correctIndex: 0,
          explanation: 'この if は「〜かどうか」という意味で、know の目的語になる名詞のかたまりです。条件の節ではないので、未来はそのまま will で表します。',
          choiceNotes: [null, '現在形にすると「ふだん来るかどうか」という習慣の意味になってしまいます。「もし来たら」という条件の if 節ではありません。', '過去形では「来たかどうか」という過去の話になります。', 'be動詞と原形 come は並べられません。'],
          audioEn: "I don't know if she will come to the party.",
        },
      ],
      summary: [
        '時・条件を表す節(when / if / before / after / until / as soon as など)の中では、未来のことでも現在形を使う。',
        '未来だという情報は主節の will や be going to が示す。主節は命令文でもよい。',
        '「〜かどうか」「いつ〜か」という名詞のかたまりの if / when 節では、未来はそのまま will で表す。',
        '見分け方: 「〜したら・〜するとき」と訳せれば現在形、「〜かどうか・いつ〜か」と訳せれば will。',
      ],
    },
  ],
}
