import type { GrammarUnit } from '../../types'

// U13 受動態 — 「be + 過去分詞」の形から、by句の省略判断、助動詞・完了との組み合わせ、
// 能動態との使い分けまで。「受動態は書き換え練習ではなく、話し手が選ぶもの」を軸に構成する。

export const u13: GrammarUnit = {
  id: 'u13',
  level: 'B1',
  title: '受動態',
  lessons: [
    {
      id: 'u13-l1',
      unitId: 'u13',
      level: 'B1',
      title: '受動態の基本(現在・過去)',
      objective: '「be動詞 + 過去分詞」で「〜される」という受動態の文を作り、能動態の文と正しく対応させられるようになります。',
      minutes: 10,
      prereqs: ['u11-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '主語を「する側」から「される側」へ',
          body:
            'これまで学んだ文の主語は「する側」でした。Ken cleaned this room.(ケンがこの部屋を掃除した)——これが**能動態**です。\n\n同じ出来事を「される側」を主語にして言うこともできます。This room was cleaned by Ken.(この部屋はケンによって掃除された)——これが**受動態**です。\n\n形は **be動詞 + 過去分詞**。ポイントは役割分担です。\n\n- **be動詞**が時制(現在か過去か)と主語との一致を引き受ける\n- **過去分詞**は「される」という意味を担当し、形は変わらない',
        },
        {
          type: 'structure',
          title: '受動態の語順',
          parts: [
            { label: '主語(される側)', text: 'This room' },
            { label: 'be動詞(時制担当)', text: 'was' },
            { label: '過去分詞', text: 'cleaned' },
            { label: 'by + する側(省略可)', text: 'by Ken' },
          ],
          caption: '能動態の目的語 this room が受動態の主語になり、動詞は be + 過去分詞に変わります。「する側」は by で示します。',
        },
        {
          type: 'table',
          title: '能動態 ↔ 受動態の対応',
          headers: ['時制', '能動態', '受動態'],
          rows: [
            ['現在', 'They clean the office every night.', 'The office is cleaned every night.'],
            ['現在(単数の主語)', 'Everyone loves this park.', 'This park is loved by everyone.'],
            ['過去', 'A famous architect designed this hotel.', 'This hotel was designed by a famous architect.'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'This temple was built in 1603.', ja: 'この寺は1603年に建てられました。', highlight: 'was built' },
            { en: 'These cookies are made with rice flour.', ja: 'このクッキーは米粉で作られています。', highlight: 'are made' },
            { en: 'The song was written by a high school student.', ja: 'その歌は高校生によって書かれました。', highlight: 'was written by' },
            { en: "The office isn't cleaned on weekends.", ja: '事務所は週末には掃除されません。', highlight: "isn't cleaned", note: '否定文は be動詞のあとに not を置くだけです。' },
            { en: 'Was this photo taken in Okinawa?', ja: 'この写真は沖縄で撮られたのですか。', highlight: 'Was this photo taken', note: '疑問文は be動詞を主語の前に出します。' },
          ],
        },
        {
          type: 'explanation',
          title: '否定・疑問は be動詞のルール、そして受動態にできない動詞',
          body:
            '受動態は be動詞の文なので、否定文・疑問文の作り方は U01 で学んだ be動詞のルールそのままです。do / does / did は使いません。\n\n- 否定: The office **is not cleaned** on weekends.\n- 疑問: **Was** this photo **taken** in Okinawa?\n\nもうひとつ大事な注意。受動態にできるのは、**目的語を取る動詞(他動詞)だけ**です。happen(起こる)や arrive(着く)のように「される側」が存在しない動詞は受動態にできません。\n\n- × The accident **was happened** last night.\n- ○ The accident **happened** last night.\n\n「事故が起こされた」とは言えない、と考えると分かりやすいです。',
        },
      ],
      quiz: [
        {
          id: 'u13-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'This castle ___ about four hundred years ago.',
          sentenceJa: 'この城は約400年前に建てられました。',
          choices: ['built', 'was built', 'is built', 'was build'],
          correctIndex: 1,
          explanation: '城は「建てられる」側なので受動態 be + 過去分詞を使います。ago があるので be動詞は過去形 was です。',
          choiceNotes: ['built だけでは「城が(何かを)建てた」という能動の過去形になってしまいます。', null, 'ago は過去の話を表すので、現在形 is built は使えません。', 'be動詞のあとは過去分詞 built です。原形 build は使えません。'],
          audioEn: 'This castle was built about four hundred years ago.',
        },
        {
          id: 'u13-l1-q2',
          prompt: '次の文を受動態にした文として正しいものを選んでください。',
          sentence: 'My uncle grows these tomatoes.',
          sentenceJa: 'おじがこのトマトを育てています。',
          choices: ['These tomatoes are grown by my uncle.', 'These tomatoes are grow by my uncle.', 'These tomatoes were grown by my uncle.', 'My uncle is grown by these tomatoes.'],
          correctIndex: 0,
          explanation: '能動態の目的語 these tomatoes を主語にし、be + 過去分詞 grown にします。元の文が現在形なので be動詞も現在形 are です。',
          choiceNotes: [null, 'be動詞のあとは過去分詞 grown が必要です。原形 grow は使えません。', '元の文は現在形なので、過去形 were にすると時制が変わってしまいます。', 'する側とされる側が逆です。「おじがトマトに育てられる」ことになってしまいます。'],
          audioEn: 'These tomatoes are grown by my uncle.',
        },
        {
          id: 'u13-l1-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: ['The accident was happened last night.', 'The window was broken by the wind.', 'These photos were taken in Kyoto.', 'This cheese is made from goat milk.'],
          correctIndex: 0,
          explanation: 'happen は目的語を取らない動詞(自動詞)なので受動態にできません。The accident happened last night. が正しい形です。',
          choiceNotes: [null, '正しい文です。窓は「割られる」側なので受動態が使えます。', '正しい文です。主語が複数なので were を使っています。', '正しい文です。チーズは「作られる」側なので受動態が自然です。'],
          audioEn: 'The accident happened last night.',
        },
        {
          id: 'u13-l1-q4',
          prompt: '次の文の内容として正しいものを選んでください。',
          sentence: 'Ken was invited to the party by Mari.',
          choices: ['マリがケンをパーティーに招待した。', 'ケンがマリをパーティーに招待した。', 'ケンとマリが一緒にパーティーを開いた。', 'ケンはマリのパーティーに行かなかった。'],
          correctIndex: 0,
          explanation: '受動態の主語 Ken は「される側」、by のあとの Mari が「する側」です。招待したのはマリです。',
          choiceNotes: [null, 'する側とされる側が逆です。by Mari の Mari が招待した側です。', 'パーティーを開いたのが誰かは、この文からは分かりません。', '行ったかどうかではなく「招待された」ことを述べた文です。'],
          audioEn: 'Ken was invited to the party by Mari.',
        },
      ],
      summary: [
        '受動態は「される側」を主語にした文。形は be動詞 + 過去分詞。',
        'be動詞が時制と主語との一致を引き受け、過去分詞は形が変わらない。',
        '否定文・疑問文は be動詞のルールで作る。do / does / did は使わない。',
        'happen / arrive など目的語を取らない動詞は受動態にできない。',
      ],
    },
    {
      id: 'u13-l2',
      unitId: 'u13',
      level: 'B1',
      title: 'by句と行為者の省略',
      objective: '「誰がしたか」を言う必要があるかどうかを判断し、by句を付けるか省略するかを正しく選べるようになります。',
      minutes: 10,
      prereqs: ['u13-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '実際の受動態は「by なし」が多数派',
          body:
            '書き換え練習では必ず by 句を付けますが、実際の英語では、**受動態の文の大部分に by 句がありません**。\n\nなぜでしょうか。そもそも受動態を選ぶのは、「する側」を言えない・言う必要がない場面が多いからです。\n\n- My bike **was stolen** last night.(誰が盗んだか分からない)\n- The thief **was arrested**.(逮捕するのは警察に決まっている)\n\n「by 句を付けるかどうか」は文法の問題ではなく、**その情報が聞き手に必要かどうか**の問題です。',
        },
        {
          type: 'table',
          title: 'by句を省略する3つの場合',
          headers: ['省略する理由', '例', '補足'],
          rows: [
            ['誰がしたか分からない', 'My bike was stolen last night.', '盗んだ人は不明'],
            ['誰がしたか明らか・重要でない', 'The thief was arrested.', '逮捕するのは警察に決まっている'],
            ['「人々一般」がする', 'Portuguese is spoken in Brazil.', 'by people は言わなくても分かる'],
          ],
        },
        {
          type: 'explanation',
          title: 'by句を残すのは「誰が」が大事な情報のとき',
          body:
            '逆に、「する側」が文の伝えたいポイントなら by 句を残します。\n\n- This novel **was written by Natsume Soseki**.(作者が誰かがこの文の核心)\n- The winning goal **was scored by a sixteen-year-old**.(「16歳が決めた」ことがニュース)\n\n判断に迷ったら、**by 以下を消してみて、伝えたいことが変わらなければ省略**——これが実用的な基準です。by someone や by people のように情報がゼロの by 句は、付けないのが自然な英語です。',
        },
        {
          type: 'contrast',
          title: 'by句を省略する vs 残す',
          left: {
            label: 'by句を省略',
            items: [
              { en: 'My passport was stolen during the trip.', ja: '旅行中にパスポートを盗まれました。', highlight: 'was stolen' },
              { en: 'The game was canceled because of the rain.', ja: '試合は雨のため中止になりました。', highlight: 'was canceled' },
            ],
            pointJa: 'する側が不明・明らか・重要でないとき',
          },
          right: {
            label: 'by句を残す',
            items: [
              { en: 'This portrait was painted by Picasso.', ja: 'この肖像画はピカソによって描かれました。', highlight: 'by Picasso' },
              { en: 'The winning goal was scored by a sixteen-year-old.', ja: '決勝ゴールは16歳の選手によって決められました。', highlight: 'by a sixteen-year-old' },
            ],
            pointJa: '「誰がしたか」が文の伝えたいポイントのとき',
          },
          note: 'by 以下を消しても伝えたいことが変わらないなら省略する、が実用的な判断基準です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'My passport was stolen during the trip.', ja: '旅行中にパスポートを盗まれました。', highlight: 'was stolen', note: '誰が盗んだか分からないので by句はありません。' },
            { en: 'I was invited to the wedding.', ja: '私はその結婚式に招待されました。', highlight: 'was invited', note: '誰に招待されたかは文脈から明らかです。' },
            { en: 'Portuguese is spoken in Brazil.', ja: 'ブラジルではポルトガル語が話されています。', highlight: 'is spoken', note: '「人々一般」がする側なので by句は不要です。' },
            { en: 'This bridge was designed by a French engineer.', ja: 'この橋はフランス人技師によって設計されました。', highlight: 'by a French engineer', note: '「誰が設計したか」が伝えたい情報なので by句を残します。' },
            { en: 'The meeting room is cleaned every morning.', ja: '会議室は毎朝掃除されます。', highlight: 'is cleaned' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u13-l2-q1',
          prompt: '最も自然な文を選んでください。',
          sentenceJa: '「昨夜、私の自転車が盗まれました」と言いたいとき。',
          choices: ['My bike was stolen by someone last night.', 'My bike was stolen last night.', 'Someone was stolen my bike last night.', 'My bike stole last night.'],
          correctIndex: 1,
          explanation: '誰が盗んだか分からないときは by句を付けません。by someone は情報を何も加えないので、省略するのが自然です。',
          choiceNotes: ['文法的には作れますが、by someone は情報ゼロなので付けないのが自然です。', null, '「盗まれた」のは someone ではなく自転車です。受動態の主語は「される側」に置きます。', '能動態 stole だと「自転車が(何かを)盗んだ」ことになってしまいます。'],
          audioEn: 'My bike was stolen last night.',
        },
        {
          id: 'u13-l2-q2',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The Mona Lisa ___ Leonardo da Vinci.',
          sentenceJa: 'モナリザはレオナルド・ダ・ヴィンチによって描かれました。',
          choices: ['was painted by', 'was painted', 'painted by', 'was painted from'],
          correctIndex: 0,
          explanation: '「誰が描いたか」がこの文の伝えたい情報なので、by句で作者を示します。',
          choiceNotes: [null, 'was painted だけでは、そのあとの Leonardo da Vinci が文とつながりません。', 'be動詞がないと受動態になりません。', 'する側を表す前置詞は from ではなく by です。'],
          audioEn: 'The Mona Lisa was painted by Leonardo da Vinci.',
        },
        {
          id: 'u13-l2-q3',
          prompt: '次の文に by句が付いていない理由として最も適切なものを選んでください。',
          sentence: 'The thief was arrested near the station.',
          sentenceJa: '泥棒は駅の近くで逮捕されました。',
          choices: ['逮捕するのは警察だと明らかで、言う必要がないから。', '逮捕した人が誰か、話し手が隠したがっているから。', '受動態には by句を付けてはいけないルールがあるから。', '過去の出来事には by句を使えないから。'],
          correctIndex: 0,
          explanation: '逮捕するのは警察に決まっているので、by the police はわざわざ言いません。「明らかな行為者」は省略するのが自然です。',
          choiceNotes: [null, '隠しているのではなく、言わなくても分かるから省略しています。', 'by句を付けるか省くかは自由で、禁止のルールはありません。', '過去の受動態でも by句は使えます(was painted by Picasso など)。'],
          audioEn: 'The thief was arrested near the station.',
        },
        {
          id: 'u13-l2-q4',
          prompt: '最も自然な文を選んでください。',
          sentenceJa: '「この地域では米が栽培されています」と言いたいとき。',
          choices: ['Rice is grown in this area.', 'Rice is grown in this area by people.', 'This area is grown rice.', 'Rice grows by farmers in this area.'],
          correctIndex: 0,
          explanation: '育てるのは「人々一般」なので by句は付けず、Rice is grown in this area. とするのが自然です。',
          choiceNotes: [null, 'by people は情報を何も加えないので、付けないのが自然です。', '「育てられる」のは米であって地域ではありません。受動態の主語は動詞の目的語だったものに限られます。', '能動態の grows(育つ)に「する側」の by句は付けられません。「農家が育てる」なら Farmers grow rice と能動態で言います。'],
          audioEn: 'Rice is grown in this area.',
        },
      ],
      summary: [
        '実際の受動態は by句なしが多数派。「する側」を言えない・言う必要がない場面で受動態を選ぶことが多い。',
        '省略する3つの場合: 誰がしたか不明/明らか・重要でない/「人々一般」。',
        '「誰がしたか」が伝えたいポイントのときだけ by句を残す。',
        '迷ったら「by 以下を消して意味が変わるか」で判断する。by someone / by people は付けない。',
      ],
    },
    {
      id: 'u13-l3',
      unitId: 'u13',
      level: 'B1',
      title: '助動詞・未来・完了の受動態',
      objective: 'will / can / must などの助動詞や現在完了と受動態を組み合わせて、will be done / has been done の形を作れるようになります。',
      minutes: 12,
      prereqs: ['u13-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '変わるのは be の部分だけ',
          body:
            '受動態の心臓部は **be + 過去分詞** です。助動詞や完了形と組み合わせても、この心臓部は変わりません。**変化するのは be の部分だけ**で、過去分詞はそのままです。\n\n- 助動詞のあとの動詞は原形 → be はそのまま **be**: must **be signed**\n- will のあとも原形 → **will be** announced\n- 完了形 have のあとは過去分詞 → be の過去分詞 **been**: has **been closed**\n\n「be を文法に合わせて着せ替える」と考えると、新しい形を暗記する必要はありません。',
        },
        {
          type: 'table',
          title: '組み合わせの一覧',
          headers: ['組み合わせ', '形', '例'],
          rows: [
            ['助動詞', 'can / must / should + be + 過去分詞', 'This form must be signed.'],
            ['未来(will)', 'will be + 過去分詞', 'The results will be announced tomorrow.'],
            ['未来(be going to)', 'be going to be + 過去分詞', 'The old library is going to be torn down.'],
            ['現在完了', 'have / has been + 過去分詞', 'The road has been closed since Monday.'],
          ],
        },
        {
          type: 'structure',
          title: 'will be + 過去分詞の語順',
          parts: [
            { label: '主語(される側)', text: 'The results' },
            { label: '助動詞', text: 'will' },
            { label: 'be(原形)', text: 'be' },
            { label: '過去分詞', text: 'announced' },
            { label: 'その他', text: 'tomorrow' },
          ],
          caption: '助動詞のあとの動詞は原形なので be は原形のまま。過去分詞 announced は変わりません。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The results will be announced tomorrow morning.', ja: '結果は明日の朝に発表されます。', highlight: 'will be announced' },
            { en: 'This medicine must be kept in the refrigerator.', ja: 'この薬は冷蔵庫で保管しなければなりません。', highlight: 'must be kept' },
            { en: "Smartphones can't be used during the exam.", ja: '試験中はスマートフォンを使用できません。', highlight: "can't be used" },
            { en: 'The meeting has been moved to Friday.', ja: '会議は金曜日に変更されました(今もその予定です)。', highlight: 'has been moved', note: '現在完了 + 受動態。「変更された結果が今も有効」という意味です。' },
            { en: 'A new bridge is going to be built here.', ja: 'ここに新しい橋が建設される予定です。', highlight: 'is going to be built' },
            { en: 'My order has just been shipped.', ja: '注文した商品はちょうど発送されたところです。', highlight: 'has just been shipped', note: 'just は has と been の間に置きます。' },
          ],
        },
        {
          type: 'explanation',
          title: '現在完了の受動態は「されて、今もそうだ」',
          body:
            'has / have **been** + 過去分詞は、U11 で学んだ現在完了の「今とつながる」感覚と、受動態の「される」が合体した形です。\n\n- The road **has been closed**.(閉鎖されて、**今も通れない**)\n- The problem **has been solved**.(解決されて、**今はもう問題ない**)\n\n否定文・疑問文の作り方も、これまでのルールの組み合わせです。\n\n- 否定: The road **hasn\'t been reopened** yet.\n- 疑問: **Will** the results **be announced** today? / **Has** the email **been sent**?',
        },
      ],
      quiz: [
        {
          id: 'u13-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The winner ___ next week.',
          sentenceJa: '優勝者は来週発表されます。',
          choices: ['will announce', 'will be announced', 'will is announced', 'will be announce'],
          correctIndex: 1,
          explanation: '優勝者は「発表される」側なので受動態です。will のあとは原形の be、そのあとに過去分詞 announced を続けます。',
          choiceNotes: ['能動態だと「優勝者が(何かを)発表する」ことになってしまいます。', null, '助動詞のあとの動詞は原形です。is ではなく be を使います。', 'be のあとは過去分詞 announced が必要です。'],
          audioEn: 'The winner will be announced next week.',
        },
        {
          id: 'u13-l3-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'The concert ___ because of the typhoon.',
          sentenceJa: '台風のため、コンサートは中止になっています。',
          choices: ['has been canceled', 'has canceled', 'has been cancel', 'was been canceled'],
          correctIndex: 0,
          explanation: '「中止が決まって、今もその状態だ」という現在完了の受動態です。have / has + been + 過去分詞の形にします。',
          choiceNotes: [null, '能動態だと「コンサートが(何かを)中止した」ことになってしまいます。', 'been のあとは過去分詞 canceled が必要です。', '完了形を作るのは have / has です。was と been は並べられません。'],
          audioEn: 'The concert has been canceled because of the typhoon.',
        },
        {
          id: 'u13-l3-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: ['This form must be signed by a parent.', 'The package will be delivered tomorrow.', 'This button must not be press.', 'The schedule has been changed.'],
          correctIndex: 2,
          explanation: '助動詞が付いても過去分詞は変わりません。must not be pressed が正しい形です。',
          choiceNotes: ['正しい文です。must + be + 過去分詞の形です。', '正しい文です。will + be + 過去分詞の形です。', null, '正しい文です。has + been + 過去分詞の形です。'],
          audioEn: 'This button must not be pressed.',
        },
        {
          id: 'u13-l3-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「その問題はもう解決されましたか」と尋ねたいとき。',
          choices: ['Has the problem been solved yet?', 'Has the problem solved yet?', 'Is the problem been solved yet?', 'Did the problem been solved yet?'],
          correctIndex: 0,
          explanation: '現在完了の受動態の疑問文は Has / Have を主語の前に出し、been + 過去分詞を続けます。',
          choiceNotes: [null, 'been が抜けると「問題が(何かを)解決した」という能動の意味になってしまいます。', '完了形を作るのは be動詞ではなく have / has です。', 'did と been は組み合わせられません。完了形の疑問文は Has / Have で作ります。'],
          audioEn: 'Has the problem been solved yet?',
        },
      ],
      summary: [
        '助動詞・未来・完了と組み合わせても、受動態の心臓部 be + 過去分詞は変わらない。変わるのは be の形だけ。',
        '助動詞 + be + 過去分詞(must be signed)、will be + 過去分詞(will be announced)。',
        '現在完了の受動態は have / has been + 過去分詞。「されて、今もそうだ」という意味。',
        '過去分詞はどの組み合わせでも形が変わらない。',
      ],
    },
    {
      id: 'u13-l4',
      unitId: 'u13',
      level: 'B1',
      title: '受動態を使う場面',
      objective: '「話題の中心は何か」「客観的に述べたいか」を基準に、能動態と受動態を場面に応じて選べるようになります。',
      minutes: 10,
      prereqs: ['u13-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '受動態は「選ぶ」もの',
          body:
            '受動態は書き換え練習の答えではなく、**話し手が理由があって選ぶ形**です。最大の基準は「**この文は何の話をしているか**」。\n\n英語は、すでに話題になっているものを主語にして文を続けるのが自然です。\n\n- お寺を見ながらの会話なら → **It** was built around 1600.(お寺が話題の中心)\n- 「誰が建てたの?」という流れなら → **A famous carpenter** built it.(建てた人が話題の中心)\n\n話題の中心が「される側」なら受動態、「する側」なら能動態——これが選択の第一基準です。',
        },
        {
          type: 'contrast',
          title: '能動態を選ぶ vs 受動態を選ぶ',
          left: {
            label: '能動態を選ぶとき',
            items: [
              { en: 'Kenta broke the window.', ja: 'ケンタが窓を割りました。', highlight: 'Kenta broke' },
              { en: 'I made this cake myself.', ja: 'このケーキは自分で作ったんです。', highlight: 'I made' },
            ],
            pointJa: '「誰がしたか」が伝えたいこと。日常会話の基本形',
          },
          right: {
            label: '受動態を選ぶとき',
            items: [
              { en: 'The window was broken during the night.', ja: '窓は夜の間に割られました。', highlight: 'was broken' },
              { en: 'This cake is sold only in Kyoto.', ja: 'このケーキは京都でしか売られていません。', highlight: 'is sold' },
            ],
            pointJa: '「されたもの」が話題の中心。する側は不明・重要でない',
          },
          note: '同じ出来事でも、主語に置いたものが「その文の話題」になります。',
        },
        {
          type: 'explanation',
          title: '客観的に述べたいときの受動態',
          body:
            'ニュース・科学レポート・ビジネスのお知らせでは、受動態がよく使われます。「誰が」という個人を出さず、**事実そのものを前に出せる**からです。\n\n- The suspect **was arrested** on Tuesday.(ニュース: 事実を客観的に)\n- The data **was collected** over six months.(レポート: 手順を客観的に)\n- Your order **has been shipped**.(お知らせ: 客の関心事を主語に)\n\n最後の例に注目してください。客が知りたいのは「自分の注文がどうなったか」であって、倉庫で誰が箱詰めしたかではありません。**読み手の関心事を主語にする**——これがビジネス英語で受動態が好まれる理由です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The new stadium will be completed in 2027.', ja: '新しいスタジアムは2027年に完成する予定です。', highlight: 'will be completed', note: 'お知らせ・ニュースの定番の形です。' },
            { en: 'The suspect was arrested on Tuesday morning.', ja: '容疑者は火曜日の朝に逮捕されました。', highlight: 'was arrested', note: 'ニュースは「された側」を主語に事実を客観的に伝えます。' },
            { en: 'Your order has been shipped.', ja: 'ご注文の商品は発送されました。', highlight: 'has been shipped', note: '客の関心事「注文品」を主語にしています。' },
            { en: 'The data was collected over six months.', ja: 'データは6か月かけて収集されました。', highlight: 'was collected', note: 'レポートや論文では「誰が」より事実を前に出します。' },
          ],
        },
        {
          type: 'explanation',
          title: '使いすぎに注意',
          body:
            '受動態は便利ですが、**日常会話の基本は能動態**です。理由なく受動態を使うと、硬く回りくどい英語になります。\n\n- ○ I made lunch.\n- × Lunch was made by me.(文法的には正しくても不自然)\n\n「する側」が分かっていて、隠す理由もないなら能動態。受動態を選ぶのは、**話題の中心が「される側」のとき**か、**客観的に述べたいとき**——この2つの理由があるときだけ、と覚えておきましょう。',
        },
      ],
      quiz: [
        {
          id: 'u13-l4-q1',
          prompt: '会話の流れに合う文を選んでください。',
          sentence: 'This is a beautiful temple! — Yes. ___',
          sentenceJa: '「美しいお寺ですね!」—「ええ。1600年ごろに建てられたんですよ。」',
          choices: ['It was built around 1600.', 'People built it around 1600.', 'Someone was built it around 1600.', 'It built around 1600.'],
          correctIndex: 0,
          explanation: '話題の中心はお寺なので、it を主語にした受動態で続けるのが自然です。建てた人の情報は不要です。',
          choiceNotes: [null, '文法的には正しいですが、話題の中心(お寺)を主語にした受動態のほうが会話の流れとして自然です。people は情報も加えません。', '「建てられた」のは someone ではなくお寺です。主語とされる側がずれています。', '能動態 built だと「お寺が(何かを)建てた」ことになってしまいます。'],
          audioEn: 'It was built around 1600.',
        },
        {
          id: 'u13-l4-q2',
          prompt: '客観的な報告書の文として最も適切なものを選んでください。',
          sentenceJa: '「データは3つの病院で収集された」と述べたいとき。',
          choices: ['The data was collected at three hospitals.', 'We was collected the data at three hospitals.', 'The data collected three hospitals.', 'Three hospitals were collected the data.'],
          correctIndex: 0,
          explanation: '報告書では「誰が」を出さず、データを主語にした受動態で事実を客観的に述べるのが定番です。',
          choiceNotes: [null, '主語 we は「集める」側なので、受動態ではなく能動態 We collected を使います。', '能動態だと「データが病院を collect した」という意味不明な文になります。', '「収集された」のはデータであって病院ではありません。'],
          audioEn: 'The data was collected at three hospitals.',
        },
        {
          id: 'u13-l4-q3',
          prompt: '最も自然な文を選んでください。',
          sentenceJa: '友達に「昨日ケーキを作ったよ」と話すとき。',
          choices: ['I made a cake yesterday.', 'A cake was made by me yesterday.', 'A cake made me yesterday.', 'I was made a cake yesterday.'],
          correctIndex: 0,
          explanation: 'する側(自分)が分かっていて隠す理由もない日常会話では、能動態が自然です。',
          choiceNotes: [null, '文法的には作れますが、by me をわざわざ言う受動態はとても不自然です。', '「ケーキが私を作った」という意味になってしまいます。', '「私が作られた」ことになり、する側とされる側が逆です。'],
          audioEn: 'I made a cake yesterday.',
        },
        {
          id: 'u13-l4-q4',
          prompt: '次の文で受動態が選ばれている理由として最も適切なものを選んでください。',
          sentence: 'Your order has been shipped and will be delivered on Friday.',
          sentenceJa: '(ネットショップからの通知)ご注文の商品は発送済みで、金曜日にお届け予定です。',
          choices: ['読み手の関心事である「注文品」を主語にするため。', '発送した担当者の名前を強調するため。', '過去の出来事だと示すため。', '命令の意味を和らげるため。'],
          correctIndex: 0,
          explanation: '客が知りたいのは「自分の注文がどうなったか」です。誰が発送作業をしたかは重要でないので、注文品を主語にした受動態が選ばれています。',
          choiceNotes: [null, 'この文に担当者の情報はなく、むしろ「誰が」を出さないための受動態です。', '時制を示すのは has been や will の部分で、受動態を選ぶ理由ではありません。', 'これは命令ではなく、状況を知らせる文です。'],
          audioEn: 'Your order has been shipped and will be delivered on Friday.',
        },
      ],
      summary: [
        '受動態は理由があって選ぶ形。第一基準は「話題の中心が主語になっているか」。',
        '話題の中心が「される側」なら受動態、「する側」なら能動態で続けるのが自然。',
        'ニュース・レポート・お知らせでは、事実や読み手の関心事を主語にするため受動態がよく使われる。',
        '日常会話の基本は能動態。理由なく受動態を使うと硬く不自然になる。',
      ],
    },
  ],
}
