import type { GrammarUnit } from '../../types'

// U14 関係詞 — 「2文を1文にする」イメージを軸に、主格・目的格・whose/where/when・
// 制限/非制限用法を段階的に学ぶ。structure ブロックで2文→1文の結合を視覚化する。

export const u14: GrammarUnit = {
  id: 'u14',
  level: 'B1',
  title: '関係詞',
  lessons: [
    {
      id: 'u14-l1',
      unitId: 'u14',
      level: 'B1',
      title: '主格の関係代名詞 who/which/that',
      objective: '人や物のあとに who / which / that で説明を続けて、「〜する人」「〜する物」を1文で表せるようになります。',
      minutes: 10,
      prereqs: ['u01-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '英語は名詞のあとから説明する',
          body:
            '日本語では「**カナダに住んでいる**友達」のように、説明を名詞の**前**に置きます。英語は逆で、名詞を先に言ってから **who / which / that** で説明を**後ろに**続けます。\n\n- a friend **who lives in Canada**(カナダに住んでいる友達)\n\nこの who / which / that を関係代名詞と呼びます。働きは「ここから後ろは、直前の名詞の説明ですよ」という合図です。長い説明も1文にまとめられるので、表現の幅が一気に広がります。',
        },
        {
          type: 'structure',
          title: '2文が1文になる仕組み',
          parts: [
            { label: '文1', text: 'I have a friend.' },
            { label: '文2', text: 'He lives in Canada.' },
            { label: '1文に', text: 'I have a friend who lives in Canada.' },
          ],
          caption: '文2の主語 He が who に変わり、説明したい名詞(a friend)の直後に続きます。He はもう言いません。',
        },
        {
          type: 'table',
          title: 'who / which / that の使い分け',
          headers: ['先行詞(説明したい名詞)', '使える関係代名詞', '例'],
          rows: [
            ['人', 'who / that', 'a friend who lives in Canada'],
            ['物・動物', 'which / that', 'a bag which has many pockets'],
            ['everything / all など', 'that が好まれる', 'everything that happened'],
          ],
        },
        {
          type: 'explanation',
          title: '「主格」= 関係代名詞が主語の働き',
          body:
            '文2 He lives in Canada. の主語 He が who に変わったので、この who は節の中で**主語の働き**をしています。これを主格の関係代名詞と呼びます。\n\n主格のポイントは2つです。\n\n- who / which / that の**すぐあとに動詞が続く**\n- 動詞の形は**先行詞に合わせる**: a friend who lives... / friends who live...\n\nまた、who がすでに主語なので、× a friend who he lives in Canada のように he を重ねてはいけません。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have a friend who lives in Canada.', ja: 'カナダに住んでいる友達がいます。', highlight: 'who lives' },
            { en: 'The bus that goes to the airport leaves every twenty minutes.', ja: '空港行きのバスは20分おきに出ています。', highlight: 'that goes to the airport', note: '主語が長くなっても、動詞 leaves の形は先行詞 the bus に合わせます。' },
            { en: 'Do you know anyone who can speak Chinese?', ja: '誰か中国語を話せる人を知っていますか。', highlight: 'who can speak' },
            { en: 'I want a phone which has a better camera.', ja: 'もっとカメラの性能がいい電話が欲しいです。', highlight: 'which has' },
            { en: 'The people who live next door are very friendly.', ja: '隣に住んでいる人たちはとても感じがいいです。', highlight: 'who live', note: '先行詞 the people が複数なので、動詞は live です。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u14-l1-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The woman ___ lives upstairs is a pianist.',
          sentenceJa: '上の階に住んでいる女性はピアニストです。',
          choices: ['who', 'which', 'whose', 'when'],
          correctIndex: 0,
          explanation: '先行詞 the woman は人で、空所のすぐあとに動詞 lives が続くので、主格の who を使います。',
          choiceNotes: [null, 'which は物・動物の先行詞に使います。人には使えません。', 'whose は「〜の」を表し、あとには名詞が必要です。動詞 lives を直接続けることはできません。', 'when は時を表す関係詞で、人の説明には使えません。'],
          audioEn: 'The woman who lives upstairs is a pianist.',
        },
        {
          id: 'u14-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「空港へ行くバスはもう出ました」と言いたいとき。',
          choices: [
            'The bus which go to the airport has already left.',
            'The bus which goes to the airport has already left.',
            'The bus who goes to the airport has already left.',
            'The bus goes to the airport which has already left.',
          ],
          correctIndex: 1,
          explanation: '物の先行詞 the bus には which(または that)を使い、動詞は単数の先行詞に合わせて goes にします。',
          choiceNotes: ['先行詞 the bus は単数なので、動詞は goes にします。', null, '先行詞 the bus は物なので who は使えません。', '説明の which 節は説明したい名詞 the bus の直後に置きます。この語順では「もう出発した空港」という意味になってしまいます。'],
          audioEn: 'The bus which goes to the airport has already left.',
        },
        {
          id: 'u14-l1-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I know a girl who plays the violin.',
            'He works for a company which makes car parts.',
            'She has a brother who live in Fukuoka.',
            'The dog that barks all night belongs to our neighbor.',
          ],
          correctIndex: 2,
          explanation: '先行詞 a brother は単数なので、動詞は lives にする必要があります。主格の関係代名詞のあとの動詞は先行詞に合わせます。',
          choiceNotes: ['先行詞 a girl(単数)に動詞 plays が正しく一致しています。', '物の先行詞 a company に which を使い、動詞 makes も一致した正しい文です。', null, 'that は動物の先行詞にも使え、単数に合わせた barks も正しい文です。'],
          audioEn: 'She has a brother who lives in Fukuoka.',
        },
        {
          id: 'u14-l1-q4',
          prompt: '次の2文を1文にした正しい文を選んでください。',
          sentence: 'I met a woman. She teaches yoga.',
          sentenceJa: '「私はヨガを教えている女性に会いました」という1文にしたいとき。',
          choices: [
            'I met a woman she teaches yoga.',
            'I met a woman who teaches yoga.',
            'I met a woman who she teaches yoga.',
            'I met a woman which teaches yoga.',
          ],
          correctIndex: 1,
          explanation: '文2の主語 She が who に変わって2文がつながります。who がすでに主語の働きをするので、she は残しません。',
          choiceNotes: ['関係代名詞なしで2つの文をそのまま並べることはできません。', null, 'who がすでに主語の働きをしているので、she を重ねることはできません。', '先行詞 a woman は人なので which は使えません。'],
          audioEn: 'I met a woman who teaches yoga.',
        },
      ],
      summary: [
        '英語は名詞のあとに who / which / that で説明を続ける(日本語と逆の語順)。',
        '先行詞が人なら who、物・動物なら which。that はどちらにも使える。',
        '主格の関係代名詞のあとには動詞が続き、動詞の形は先行詞に合わせる。',
        '関係代名詞は文2の主語の代わり。who のあとに he / she などを重ねない。',
      ],
    },
    {
      id: 'u14-l2',
      unitId: 'u14',
      level: 'B1',
      title: '目的格の関係代名詞と省略',
      objective: '「私が読んだ本」のように目的語だった名詞を説明する文を作り、関係代名詞を自然に省略できるようになります。',
      minutes: 10,
      prereqs: ['u14-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '「私が読んだ本」— 目的語を前に出す',
          body:
            '「私が先週読んだ本」を英語にしてみます。\n\n- This is the book.(これはその本です)\n- I read **it** last week.(私はそれを先週読んだ)\n\n説明したい the book は、文2では**目的語(it)**です。このときは it を **that / which** に変えて節の先頭へ移動させ、名詞のあとに続けます。\n\n- This is the book **that I read** last week.\n\n関係代名詞が節の中で目的語の働きをするので、これを**目的格**と呼びます。',
        },
        {
          type: 'structure',
          title: '2文が1文になる仕組み(目的格)',
          parts: [
            { label: '文1', text: 'This is the book.' },
            { label: '文2', text: 'I read it last week.' },
            { label: '1文に', text: 'This is the book that I read last week.' },
          ],
          caption: '文2の目的語 it が that に変わって節の先頭へ移動します。it をそのまま残さないのが最大のポイントです。',
        },
        {
          type: 'explanation',
          title: '目的格を省略できる条件',
          body:
            '**カンマを付けずに名詞を絞り込む関係節では、目的格の関係代名詞を省略できます**。\n\n- This is the book that I read last week.\n- This is the book I read last week.\n\nどちらも「これは私が先週読んだ本です」です。元の I read the book. では、the book が read の目的語になっています。\n\n省略できるかは、**関係節の中でどの役割が欠けているか**で確認します。主語の代わりなら省略できません。なお、カンマ付きの補足説明や、前置詞 + which / whom の形では、目的格でも省略しません。',
        },
        {
          type: 'contrast',
          title: '主格と目的格 — 省略できるのはどちら?',
          left: {
            label: '主格(省略できない)',
            items: [
              { en: 'The man who called you is my boss.', ja: 'あなたに電話した男性は私の上司です。', highlight: 'who called' },
              { en: 'I like songs that make me happy.', ja: '気分が明るくなる歌が好きです。', highlight: 'that make' },
            ],
            pointJa: '関係代名詞のすぐあとに動詞 → 消すと文が壊れる',
          },
          right: {
            label: '目的格(省略できる)',
            items: [
              { en: 'The man you met yesterday is my boss.', ja: 'あなたが昨日会った男性は私の上司です。', highlight: 'you met' },
              { en: 'This is the best pizza I have ever eaten.', ja: 'これは今まで食べた中で一番おいしいピザです。', highlight: 'I have ever eaten' },
            ],
            pointJa: '関係代名詞のあとに主語 + 動詞 → 省略が自然',
          },
          note: '名詞のすぐあとに「主語 + 動詞」が続いていたら、目的格の関係代名詞が省略された形です。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'The movie that we watched last night was really good.', ja: '昨夜見た映画は本当に良かったです。', highlight: 'that we watched' },
            { en: 'The cake she made was delicious.', ja: '彼女が作ったケーキはおいしかったです。', highlight: 'she made', note: '関係代名詞(that)が省略された形です。' },
            { en: 'Is this the umbrella you were looking for?', ja: 'これはあなたが探していた傘ですか。', highlight: 'you were looking for' },
            { en: 'He is a person everyone trusts.', ja: '彼はみんなが信頼する人です。', highlight: 'everyone trusts' },
            { en: 'The shoes which I ordered online were too small.', ja: 'ネットで注文した靴は小さすぎました。', highlight: 'which I ordered' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u14-l2-q1',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「これは私が先週買ったカメラです」と言いたいとき。',
          choices: [
            'This is the camera that I bought it last week.',
            'This is the camera that I bought last week.',
            'This is the camera that bought last week.',
            'This is the camera whose I bought last week.',
          ],
          correctIndex: 1,
          explanation: 'that が文2の目的語 it の代わりなので、it は残しません。that のあとに「主語 + 動詞」(I bought)が続く目的格の形です。',
          choiceNotes: ['that がすでに bought の目的語の働きをしているので、it を残すことはできません。', null, 'bought の主語がありません。「私が買った」なら that のあとに主語 I が必要です。', 'whose は「〜の」を表し、あとには名詞が必要です。ここでは使えません。'],
          audioEn: 'This is the camera that I bought last week.',
        },
        {
          id: 'u14-l2-q2',
          prompt: '関係代名詞を省略できる文を選んでください。',
          choices: [
            'The train that leaves at nine is usually crowded.',
            'The woman who lives across the street has two dogs.',
            'The pictures that you took in Okinawa are beautiful.',
            'People who exercise every day tend to sleep well.',
          ],
          correctIndex: 2,
          explanation: 'that のあとに「主語(you)+ 動詞(took)」が続いているので目的格です。目的格だけが省略でき、The pictures you took in Okinawa are beautiful. と言えます。',
          choiceNotes: ['that のすぐあとに動詞 leaves が続く主格なので省略できません。', 'who のすぐあとに動詞 lives が続く主格なので省略できません。', null, 'who のすぐあとに動詞 exercise が続く主格なので省略できません。'],
          audioEn: 'The pictures that you took in Okinawa are beautiful.',
        },
        {
          id: 'u14-l2-q3',
          prompt: '次の2文を1文にした正しい文を選んでください。',
          sentence: 'I lost the scarf. My grandmother made it for me.',
          sentenceJa: '「祖母が作ってくれたマフラーをなくしてしまいました」という1文にしたいとき。',
          choices: [
            'I lost the scarf my grandmother made for me.',
            'I lost the scarf my grandmother made it for me.',
            'I lost the scarf made my grandmother for me.',
            'I lost my grandmother made the scarf for me.',
          ],
          correctIndex: 0,
          explanation: '文2の目的語 it を消して、the scarf のあとに「主語 + 動詞」を続けます。目的格の関係代名詞は省略できるので、この形が最も自然です。',
          choiceNotes: [null, '目的語 it の働きは(省略された)関係代名詞が引き受けているので、it は残せません。', '名詞のあとは「主語 + 動詞」(my grandmother made)の順で続けます。', '説明したい名詞 the scarf を先に置き、そのあとに説明を続けます。'],
          audioEn: 'I lost the scarf my grandmother made for me.',
        },
        {
          id: 'u14-l2-q4',
          prompt: '空所に入る表現を選んでください。',
          sentence: 'The man ___ is over there.',
          sentenceJa: '「私を手伝ってくれた男性はあそこにいます」と言いたいとき。',
          choices: ['who helped me', 'I helped', 'who I helped', 'helped me'],
          correctIndex: 0,
          explanation: '手伝ったのは男性の方なので、男性が主語になる主格 who + 動詞(who helped me)を使います。',
          choiceNotes: [null, '「私が手伝った男性」という逆の意味になります(目的格の省略形)。', 'これも「私が手伝った男性」という意味です。手伝った側は男性なので主格 who + 動詞にします。', '主格の関係代名詞は省略できないので、関係代名詞なしで動詞を直接続けることはできません。'],
          audioEn: 'The man who helped me is over there.',
        },
      ],
      summary: [
        '文2の目的語を説明したいときは目的格の関係代名詞(that / which / who)。元の it や him は残さない。',
        '目的格の関係代名詞は省略できる。会話では省略する方が自然。',
        '関係代名詞のあとに動詞がすぐ続けば主格(省略不可)、主語 + 動詞が続けば目的格(省略可)。',
        '名詞の直後に「主語 + 動詞」が来ていたら、関係代名詞が省略されたサイン。',
      ],
    },
    {
      id: 'u14-l3',
      unitId: 'u14',
      level: 'B1',
      title: 'whose / where / when',
      objective: '所有の whose、場所の where、時の when を使って、「〜の」「そこで」「そのとき」という説明を名詞に続けられるようになります。',
      minutes: 12,
      prereqs: ['u14-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'whose は「〜の」をつなぐ',
          body:
            '「お父さんがシェフをしている友達」のように、**持ち物や家族(〜の)**で名詞を説明したいときは whose を使います。\n\n- I have a friend.(友達がいる)\n- **Her** father is a chef.(彼女のお父さんはシェフだ)\n\n文2の her(彼女の)が **whose** に変わり、father とセットで先行詞の直後に移動します。\n\n- I have a friend **whose father** is a chef.\n\nwhose は人にも物にも使え、必ず「whose + 名詞」のセットで動きます。',
        },
        {
          type: 'structure',
          title: '2文が1文になる仕組み(whose)',
          parts: [
            { label: '文1', text: 'I have a friend.' },
            { label: '文2', text: 'Her father is a chef.' },
            { label: '1文に', text: 'I have a friend whose father is a chef.' },
          ],
          caption: '文2の Her が whose に変わり、father とセットで先行詞 a friend の直後に移動します。',
        },
        {
          type: 'explanation',
          title: 'where は場所、when は時',
          body:
            '「そこで〜する」と場所を説明するなら **where**、「そのとき〜する」と時を説明するなら **when** を使えます。\n\n- This is the town where I was born. → 私が生まれた町です。\n- Do you remember the day when we first met? → 初めて会った日を覚えていますか。\n\nただし、名詞が場所だから必ず where になるわけではありません。**後ろの説明の中で何の役割をするか**を確認します。\n\n- the town **which I visited** → I visited the town. の目的語\n- the town **where I stayed** → I stayed in the town. の場所の情報\n\nwhere が「そこで」を表すので、the town where I stayed there のように場所を重ねません。',
        },
        {
          type: 'table',
          title: 'whose / where / when の整理',
          headers: ['関係詞', '先行詞', '働き', '例'],
          rows: [
            ['whose + 名詞', '人・物', '所有(〜の)', 'a friend whose father is a chef'],
            ['where', '場所', '「そこで〜する」', 'the town where I was born'],
            ['when', '時', '「そのとき〜する」', 'the day when we first met'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I have a friend whose father is a chef.', ja: 'お父さんがシェフをしている友達がいます。', highlight: 'whose father' },
            { en: 'She is the writer whose books sell millions of copies.', ja: '彼女は著書が何百万部も売れている作家です。', highlight: 'whose books' },
            { en: 'This is the town where I grew up.', ja: 'ここが私の育った町です。', highlight: 'where I grew up' },
            { en: 'We stayed at a hotel where you can see the ocean from every room.', ja: 'どの部屋からも海が見えるホテルに泊まりました。', highlight: 'where' },
            { en: 'Do you remember the day when we first met?', ja: '私たちが初めて会った日を覚えていますか。', highlight: 'when we first met' },
            { en: 'Winter is the season when this town is at its best.', ja: '冬はこの町が一番美しい季節です。', highlight: 'when' },
          ],
        },
        {
          type: 'contrast',
          title: '先行詞が場所でも where とは限らない',
          left: {
            label: 'which / that(節の中に穴がある)',
            items: [
              { en: 'This is a restaurant which serves great sushi.', ja: 'ここはおいしい寿司を出すレストランです。', highlight: 'which serves', note: 'which が serves の主語の働きをしています。' },
            ],
            pointJa: 'あとの文に主語や目的語の穴 → which / that',
          },
          right: {
            label: 'where(完全な文が続く)',
            items: [
              { en: 'This is the restaurant where we had our wedding party.', ja: 'ここは私たちが結婚パーティーをしたレストランです。', highlight: 'where we had our wedding party', note: 'we had our wedding party は主語も目的語もそろった完全な文です。' },
            ],
            pointJa: 'あとに完全な文 → where(「そこで」の意味)',
          },
          note: '先行詞が場所でも自動的に where になるわけではありません。あとに続く文の形で選びます。',
        },
      ],
      quiz: [
        {
          id: 'u14-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'She is the author ___ new novel became a bestseller.',
          sentenceJa: '彼女は新しい小説がベストセラーになった作家です。',
          choices: ['who', 'whose', 'which', 'where'],
          correctIndex: 1,
          explanation: '「作家の(彼女の)新しい小説」という所有の関係なので、whose + 名詞(whose new novel)の形にします。',
          choiceNotes: ['who のあとには動詞または主語 + 動詞が続きます。「〜の」という所有の関係は作れません。', null, '先行詞が人なので which は使えません。所有を表すのは whose です。', 'where は場所を表す関係詞で、ここでは使えません。'],
          audioEn: 'She is the author whose new novel became a bestseller.',
        },
        {
          id: 'u14-l3-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: 'The hotel ___ we stayed last summer has closed.',
          sentenceJa: '去年の夏に私たちが泊まったホテルは閉業しました。',
          choices: ['which', 'where', 'when', 'whose'],
          correctIndex: 1,
          explanation: '空所のあとの we stayed は主語も目的語もそろった完全な文なので、「そこで」を表す where を使います。',
          choiceNotes: ['we stayed は完全な文なので which の入る場所がありません。which を使うなら stayed at のように前置詞が必要です。', null, '先行詞 the hotel は時ではなく場所です。', 'whose のあとには名詞が必要です。'],
          audioEn: 'The hotel where we stayed last summer has closed.',
        },
        {
          id: 'u14-l3-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「6月は日本で雨がたくさん降る月です」と言いたいとき。',
          choices: [
            'June is the month when it rains a lot in Japan.',
            'June is the month where it rains a lot in Japan.',
            'June is the month who it rains a lot in Japan.',
            'June is when the month it rains a lot in Japan.',
          ],
          correctIndex: 0,
          explanation: '先行詞 the month は時を表す名詞なので、when でつなぎます。when のあとには完全な文が続きます。',
          choiceNotes: [null, 'where は場所の先行詞に使います。the month は時なので when です。', 'who は人を説明する関係詞です。', '関係詞 when は先行詞 the month の直後に置きます。'],
          audioEn: 'June is the month when it rains a lot in Japan.',
        },
        {
          id: 'u14-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'I met a woman whose son goes to my school.',
            'This is the park where we used to play.',
            'He works in a factory where makes car parts.',
            'Do you know a shop where I can buy fresh herbs?',
          ],
          correctIndex: 2,
          explanation: 'where のあとには完全な文が続きます。makes の主語が欠けているので、主語の働きをする which / that を使って a factory which makes car parts とします。',
          choiceNotes: ['whose + 名詞(whose son)で所有を表す正しい文です。', 'where のあとに完全な文 we used to play が続く正しい文です。', null, 'where のあとに完全な文 I can buy fresh herbs が続く正しい文です。'],
          audioEn: 'He works in a factory which makes car parts.',
        },
      ],
      summary: [
        'whose は所有(〜の)。必ず「whose + 名詞」のセットで先行詞の直後に置く。',
        'where は場所、when は時の先行詞に使い、あとには完全な文が続く。前置詞は付け足さない。',
        '先行詞が場所でも、あとの文に主語や目的語の穴があれば which / that を使う。',
      ],
    },
    {
      id: 'u14-l4',
      unitId: 'u14',
      level: 'B1',
      title: '制限用法と非制限用法',
      objective: 'カンマの有無で意味がどう変わるかを理解し、「絞り込む」用法と「付け加える」用法を使い分けられるようになります。',
      minutes: 12,
      prereqs: ['u14-l3'],
      blocks: [
        {
          type: 'explanation',
          title: 'カンマひとつで役割が変わる',
          body:
            '関係詞節には2つの使い方があります。\n\n- **制限用法(カンマなし)**: どの人・どれのことかを**絞り込む**。この説明がないと誰の話か決まらない\n- **非制限用法(カンマあり)**: すでに特定できている名詞に、情報を**付け加える**。「ちなみに〜なんですが」という感覚\n\n書くときはカンマで区切り、話すときはそこで軽くポーズを置きます。形はほぼ同じでも、聞き手が受け取る意味は大きく変わります。',
        },
        {
          type: 'contrast',
          title: 'カンマなし vs カンマあり',
          left: {
            label: 'カンマなし(制限用法): 絞り込む',
            items: [
              { en: 'My brother who lives in Osaka is a doctor.', ja: '大阪に住んでいる方の兄は医者です。', highlight: 'who lives in Osaka', note: '兄が複数いて、そのうちの一人に絞り込んでいます。' },
            ],
            pointJa: 'この説明がないと、どの人・どれのことか決まらない',
          },
          right: {
            label: 'カンマあり(非制限用法): 付け加える',
            items: [
              { en: 'My brother, who lives in Osaka, is a doctor.', ja: '兄は(ちなみに大阪に住んでいますが)医者です。', highlight: 'who lives in Osaka', note: '兄は一人。住んでいる場所は追加情報です。' },
            ],
            pointJa: '誰のことかは特定済み。「ちなみに」と情報を足す',
          },
          note: '同じ単語の並びでも、カンマの有無で「兄が何人いるか」の解釈まで変わります。',
        },
        {
          type: 'explanation',
          title: '非制限用法の3つのルール',
          body:
            'カンマ付きの非制限用法には、制限用法にはない制約があります。\n\n- **that は使えない**。who / which を使う(× My mother, that is seventy, ...)\n- **省略できない**。目的格でも関係代名詞を残す\n- 先行詞が Kyoto や my mother のように**一つに決まるもの**なら、絞り込みは不要なので非制限用法を使う\n\nもうひとつ便利な用法があります。**カンマ + which** は直前の名詞ではなく、**前の文全体の内容**を受けることができます。\n\n- The train was delayed again, **which** made everyone angry.(また電車が遅れた。**そのこと**がみんなを怒らせた)',
        },
        {
          type: 'table',
          title: '2つの用法の整理',
          headers: ['', '制限用法(カンマなし)', '非制限用法(カンマあり)'],
          rows: [
            ['働き', 'どれ・誰なのかを絞り込む', '補足情報を付け加える'],
            ['that', '使える', '使えない(who / which のみ)'],
            ['目的格の省略', 'できる', 'できない'],
            ['典型的な先行詞', '絞り込みが必要な名詞', '固有名詞など、一つに決まる名詞'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Kyoto, which was the capital of Japan for over a thousand years, attracts millions of tourists.', ja: '京都は、千年以上日本の都だった町ですが、何百万人もの観光客を集めています。', highlight: 'which was the capital of Japan for over a thousand years' },
            { en: 'My mother, who is seventy, still works in her garden.', ja: '母は70歳ですが、今も庭仕事をしています。', highlight: 'who is seventy' },
            { en: 'The students who handed in their homework late lost points.', ja: '宿題を遅れて出した学生は減点されました。', highlight: 'who handed in their homework late', note: 'カンマなし: 遅れて出した学生だけに絞り込んでいます。' },
            { en: 'Mr. Ito, who teaches us math, is retiring next month.', ja: '数学を教えてくれている伊藤先生が、来月退職します。', highlight: 'who teaches us math' },
            { en: 'The train was delayed again, which made everyone angry.', ja: 'また電車が遅れて、そのことにみんな腹を立てました。', highlight: 'which', note: 'この which は前の文全体の内容を受けています。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u14-l4-q1',
          prompt: '次の文から分かることを選んでください。',
          sentence: 'My sister, who lives in Nagoya, is a nurse.',
          choices: [
            '姉妹は一人で、その人が名古屋に住む看護師だ。',
            '姉妹が複数いて、そのうち名古屋に住む人が看護師だ。',
            '姉妹は看護師をもう辞めている。',
            '姉妹はこれから名古屋に引っ越す予定だ。',
          ],
          correctIndex: 0,
          explanation: 'カンマ付きの非制限用法は「誰のことか特定済みの名詞に情報を付け加える」言い方です。姉妹は一人で、住んでいる場所は補足情報です。',
          choiceNotes: [null, '複数の姉妹から絞り込むなら、カンマなしの制限用法 My sister who lives in Nagoya... を使います。', '文にそのような情報はありません。is a nurse は現在の事実です。', 'lives は現在の事実を表し、引っ越しの予定は表しません。'],
          audioEn: 'My sister, who lives in Nagoya, is a nurse.',
        },
        {
          id: 'u14-l4-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「富士山は、日本で一番高い山ですが、静岡と山梨の間にあります」と言いたいとき。',
          choices: [
            'Mt. Fuji, that is the highest mountain in Japan, stands between Shizuoka and Yamanashi.',
            'Mt. Fuji, which is the highest mountain in Japan, stands between Shizuoka and Yamanashi.',
            'Mt. Fuji which is the highest mountain in Japan stands between Shizuoka and Yamanashi.',
            'Mt. Fuji, is the highest mountain in Japan, which stands between Shizuoka and Yamanashi.',
          ],
          correctIndex: 1,
          explanation: 'Mt. Fuji は一つに決まる固有名詞なので、カンマ付きの非制限用法で情報を付け加えます。非制限用法では which を使います。',
          choiceNotes: ['カンマ付きの非制限用法では that は使えません。', null, '固有名詞 Mt. Fuji に絞り込みは不要なので、カンマなしの制限用法は使いません。', '主語と動詞の間をカンマで切ったこの形は文として成り立ちません。'],
          audioEn: 'Mt. Fuji, which is the highest mountain in Japan, stands between Shizuoka and Yamanashi.',
        },
        {
          id: 'u14-l4-q3',
          prompt: '次の文の意味として正しいものを選んでください。',
          sentence: 'The players who were tired left the field early.',
          choices: [
            '疲れていた選手だけが早めにフィールドを去った。',
            '選手は全員疲れていて、全員が早めに去った。',
            '選手は誰も疲れていなかった。',
            '疲れていた選手はフィールドに残った。',
          ],
          correctIndex: 0,
          explanation: 'カンマなしの制限用法なので、「疲れていた選手」に絞り込んでいます。全員なら The players, who were tired, left the field early. とカンマを付けます。',
          choiceNotes: [null, '「全員が疲れていた」という補足なら、カンマ付きの非制限用法にします。', 'who were tired とあるので、疲れていた選手はいます。', 'left the field early(早めに去った)とあるので、残ってはいません。'],
          audioEn: 'The players who were tired left the field early.',
        },
        {
          id: 'u14-l4-q4',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Our flight was canceled, ___ meant we had to stay another night.',
          sentenceJa: '私たちの便は欠航になり、そのためもう一泊しなければなりませんでした。',
          choices: ['which', 'that', 'what', 'who'],
          correctIndex: 0,
          explanation: 'カンマ + which は「便が欠航になったこと」という前の文全体の内容を受けることができます。',
          choiceNotes: [null, 'カンマのあとの非制限用法では that は使えません。', 'what は先行詞を含む語で、カンマのあとで前の文を受ける用法はありません。', 'who は人を受ける語で、文の内容は受けられません。'],
          audioEn: 'Our flight was canceled, which meant we had to stay another night.',
        },
      ],
      summary: [
        'カンマなし(制限用法)は「どれ・誰か」を絞り込む。カンマあり(非制限用法)は補足情報を付け加える。',
        '非制限用法では that は使えず、関係代名詞の省略もできない。',
        '固有名詞や my mother のように一つに決まる名詞には非制限用法を使う。',
        'カンマ + which は前の文全体の内容を受けることができる。',
      ],
    },
    {
      id: 'u14-l5',
      unitId: 'u14',
      level: 'B1',
      title: '関係詞 総合練習',
      objective: '主格・目的格・whose・where・when・カンマの有無を文脈から判断し、適切な関係詞を選べるようになります。',
      minutes: 12,
      prereqs: ['u14-l4'],
      blocks: [
        {
          type: 'explanation',
          title: '関係詞を選ぶ3ステップ',
          body:
            'どの関係詞を使うかは、次の3つを順に確認すれば決められます。\n\n- **ステップ1: 先行詞は何か** — 人 → who、物 → which(どちらも that 可)、「〜の」 → whose、場所 → where、時 → when\n- **ステップ2: あとに続く文の形は** — 主語や目的語が欠けた文なら who / which / that。完全な文なら where / when\n- **ステップ3: カンマは必要か** — 絞り込むならカンマなし、特定済みの名詞への補足ならカンマあり\n\n特にステップ2が実戦での決め手です。先行詞が場所でも、続く文に主語が欠けていれば which / that を選びます。',
        },
        {
          type: 'table',
          title: '関係詞の総整理',
          headers: ['関係詞', '先行詞', '節の中の働き', '省略'],
          rows: [
            ['who / that', '人', '主語または目的語', '目的格のみ可'],
            ['which / that', '物・動物', '主語または目的語', '目的格のみ可'],
            ['whose + 名詞', '人・物', '所有(〜の)', '不可'],
            ['where', '場所', '「そこで」(完全な文が続く)', '不可'],
            ['when', '時', '「そのとき」(完全な文が続く)', '省略されることも多い'],
          ],
        },
        {
          type: 'explanation',
          title: 'よくある間違いトップ3',
          body:
            '関係詞で特に多い間違いを確認しておきましょう。\n\n- **代名詞の残留**: × the bag which I bought **it** — which がすでに bought の目的語なので it は不要\n- **where と which の混同**: × a factory **where makes** car parts — makes の主語が欠けているので which / that\n- **非制限用法の that**: × Kyoto**, that** is my hometown — カンマのあとは who / which\n\nどれも「元の2文に戻して考える」ことで防げます。迷ったら2文に分解してみましょう。',
        },
        {
          type: 'contrast',
          title: '先行詞が同じでも、あとの文の形で決まる',
          left: {
            label: '穴がある文 → that / which',
            items: [
              { en: 'This is the factory that makes car parts.', ja: 'ここが自動車部品を作っている工場です。', highlight: 'that makes' },
              { en: 'The restaurant that we chose was very quiet.', ja: '私たちが選んだレストランはとても静かでした。', highlight: 'that we chose' },
            ],
            pointJa: 'makes の主語、chose の目的語が欠けています。先行詞が場所でも where は使いません。',
          },
          right: {
            label: '完全な文 → where',
            items: [
              { en: 'This is the factory where my father works.', ja: 'ここが父の働いている工場です。', highlight: 'where my father works' },
              { en: 'The restaurant where we had lunch was very quiet.', ja: '私たちが昼食をとったレストランはとても静かでした。', highlight: 'where we had lunch' },
            ],
            pointJa: 'my father works も we had lunch も要素がそろっています。足りないのは「そこで」という場所の情報です。',
          },
          note: '先行詞の種類だけで決めず、あとに続く文に穴があるかを必ず確認しましょう。',
        },
        {
          type: 'examples',
          title: '例文(種類を意識しながら)',
          items: [
            { en: 'The woman who designed this building won an international prize.', ja: 'このビルを設計した女性は国際的な賞を受賞しました。', highlight: 'who designed', note: '主格: who のすぐあとに動詞。' },
            { en: 'Is there anything I can do to help?', ja: '何か私に手伝えることはありますか。', highlight: 'I can do', note: '目的格の関係代名詞(that)が省略されています。' },
            { en: 'We visited the village where my grandfather was born.', ja: '祖父が生まれた村を訪ねました。', highlight: 'where', note: 'where のあとは完全な文です。' },
            { en: 'I have a coworker whose desk is always perfectly clean.', ja: '机がいつも完璧に片付いている同僚がいます。', highlight: 'whose desk' },
            { en: 'The cafe, which opened only last month, is already popular.', ja: 'そのカフェは先月オープンしたばかりですが、もう人気です。', highlight: 'which opened only last month', note: 'カンマあり: 補足情報を付け加えています。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u14-l5-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Is this the office ___ you used to work?',
          sentenceJa: 'ここがあなたが以前働いていたオフィスですか。',
          choices: ['which', 'where', 'who', 'whose'],
          correctIndex: 1,
          explanation: '空所のあとの you used to work は完全な文なので、「そこで」を表す where を使います。',
          choiceNotes: ['you used to work は完全な文なので which の入る場所がありません。which を使うなら文末に in や at が必要です。', null, '先行詞 the office は人ではありません。', 'whose のあとには名詞が必要です。'],
          audioEn: 'Is this the office where you used to work?',
        },
        {
          id: 'u14-l5-q2',
          prompt: '関係代名詞を省略できない文を選んでください。',
          choices: [
            'The movie that we saw last night was boring.',
            'The letter that arrived this morning is for you.',
            'The man that you asked about has moved away.',
            'The soup that I made yesterday tastes better today.',
          ],
          correctIndex: 1,
          explanation: 'that のすぐあとに動詞 arrived が続く主格なので省略できません。他の3つは that のあとに「主語 + 動詞」が続く目的格なので省略できます。',
          choiceNotes: ['that のあとに主語 we + 動詞 saw が続く目的格なので省略できます。', null, 'that のあとに主語 you + 動詞 asked が続く目的格なので省略できます。', 'that のあとに主語 I + 動詞 made が続く目的格なので省略できます。'],
          audioEn: 'The letter that arrived this morning is for you.',
        },
        {
          id: 'u14-l5-q3',
          prompt: '誤りを含む文を選んでください。',
          choices: [
            'She is the singer whose voice everyone loves.',
            'This is the town where I spent my childhood.',
            'The bag which I bought it last week is already broken.',
            'People who read a lot tend to write well.',
          ],
          correctIndex: 2,
          explanation: '目的格の関係代名詞 which がすでに bought の目的語の働きをしているので、it を重ねて残すことはできません。',
          choiceNotes: ['whose + 名詞(whose voice)で所有を表す正しい文です。', 'where のあとに完全な文が続く正しい文です。', null, '主格 who のあとに動詞 read が続く正しい文です。'],
          audioEn: 'The bag which I bought last week is already broken.',
        },
        {
          id: 'u14-l5-q4',
          prompt: '状況に合う文を選んでください。',
          sentenceJa: '息子は一人だけ。「東京の大学に通っている息子が、今週末帰ってきます」と言いたいとき。',
          choices: [
            'My son who goes to a university in Tokyo is coming home this weekend.',
            'My son, who goes to a university in Tokyo, is coming home this weekend.',
            'My son, that goes to a university in Tokyo, is coming home this weekend.',
            'My son whose goes to a university in Tokyo is coming home this weekend.',
          ],
          correctIndex: 1,
          explanation: '息子は一人で特定済みなので、カンマ付きの非制限用法で情報を付け加えます。',
          choiceNotes: ['カンマなしだと「複数いる息子のうち、東京の大学に通っている息子」という絞り込みに聞こえます。', null, 'カンマ付きの非制限用法に that は使えません。', 'whose のあとには名詞が必要です。動詞を直接続けることはできません。'],
          audioEn: 'My son, who goes to a university in Tokyo, is coming home this weekend.',
        },
      ],
      summary: [
        '関係詞は「先行詞の種類」と「あとの文の形(穴があるか、完全か)」で選ぶ。',
        '省略できるのは目的格だけ。名詞の直後の「主語 + 動詞」は省略のサイン。',
        '元の文の代名詞(it / him / there など)は残さない。迷ったら2文に分解して考える。',
        'カンマの有無で「絞り込み」か「補足」かが変わる。非制限用法に that は使えない。',
      ],
    },
  ],
}
