import type { GrammarUnit } from '../../types'

// U02 時制の基礎 — u01.ts をゴールドスタンダードとして執筆。

export const u02: GrammarUnit = {
  id: 'u02',
  level: 'A2',
  title: '時制の基礎',
  lessons: [
    {
      id: 'u02-l1',
      unitId: 'u02',
      level: 'A2',
      title: '現在進行形',
      objective: '今まさに起きていることを be動詞 + 動詞の-ing形で表し、現在形との役割の違いを理解できるようになります。',
      minutes: 10,
      prereqs: ['u01-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '「今まさに」を切り取る形',
          body:
            '現在進行形は、**今している最中の動作や、今の時期に取り組んでいる活動**を表します。形は **be動詞(am / is / are) + 動詞の -ing 形** です。\n\n- I am cooking dinner. → 今、夕食を作っている最中です。\n- I am reading a long book this week. → 今週、長い本を読んでいるところです。\n\n2つ目は、話している瞬間に本を開いていなくても使えます。「いつもの習慣」を述べる現在形と比べ、現在進行形は**現在を含む期間の途中の様子**に注目します。',
        },
        {
          type: 'table',
          title: '-ing形の作り方',
          headers: ['ルール', '例'],
          rows: [
            ['そのまま -ing を付ける', 'play → playing, read → reading'],
            ['e で終わる語は e を取って -ing', 'make → making, write → writing'],
            ['短母音 + 子音で終わる語は子音を重ねる', 'run → running, sit → sitting'],
            ['ie で終わる語は ie を y に変えて -ing', 'lie → lying, die → dying'],
          ],
        },
        {
          type: 'timeline',
          title: '現在進行形の時間イメージ',
          timelines: [
            {
              title: 'I am cooking dinner.',
              range: [85, 100],
              rangeLabel: '料理の最中',
              arrowToNow: true,
              caption: '少し前に始まった動作が、「今」もまだ続いています。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I am cooking dinner now.', ja: '私は今、夕食を作っています。', highlight: 'am cooking' },
            { en: 'She is talking on the phone.', ja: '彼女は電話で話しているところです。', highlight: 'is talking' },
            { en: 'The kids are playing in the yard.', ja: '子どもたちは庭で遊んでいます。', highlight: 'are playing' },
            { en: "He isn't watching TV right now.", ja: '彼は今、テレビを見ていません。', highlight: "isn't watching", note: '否定文は be動詞のあとに not を置くだけです。' },
            { en: 'Are you waiting for the bus?', ja: 'バスを待っているのですか。', highlight: 'Are', note: '疑問文は be動詞を主語の前に出します。' },
          ],
        },
        {
          type: 'explanation',
          title: '否定文・疑問文は be動詞のルールで',
          body:
            '現在進行形の文の主役は be動詞です。だから否定文・疑問文の作り方は、U01で学んだ be動詞のルールがそのまま使えます。\n\n- 否定文: be動詞のあとに not(He is not sleeping.)\n- 疑問文: be動詞を主語の前へ(Is he sleeping?)\n\ndo / does は使いません。× Does he sleeping?',
        },
      ],
      quiz: [
        {
          id: 'u02-l1-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Listen. Someone ___ the piano.',
          sentenceJa: '聞いて。誰かがピアノを弾いています。',
          choices: ['plays', 'is playing', 'playing', 'play'],
          correctIndex: 1,
          explanation: 'Listen.(聞いて)と言っているので、今この瞬間に起きていることです。現在進行形 is playing を使います。',
          choiceNotes: ['plays は「いつも弾く」という習慣の意味になり、今この瞬間には合いません。', null, '-ing形だけでは動詞になりません。be動詞が必要です。', '主語 someone は単数で、今の動作には現在進行形が必要です。'],
          audioEn: 'Listen. Someone is playing the piano.',
        },
        {
          id: 'u02-l1-q2',
          prompt: 'つづりも含めて正しい文を選んでください。',
          sentenceJa: '「彼は公園で走っています」と言いたいとき。',
          choices: ['He is runing in the park.', 'He is running in the park.', 'He is run in the park.', 'He is runs in the park.'],
          correctIndex: 1,
          explanation: 'run は「短母音 + 子音」で終わるので、n を重ねて running にします。',
          choiceNotes: ['n を重ねずに -ing を付けることはできません。', null, 'be動詞のあとに動詞の原形は続けられません。', 'be動詞のあとに三単現の -s形は続けられません。'],
          audioEn: 'He is running in the park.',
        },
        {
          id: 'u02-l1-q3',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「彼女は宿題をしているところですか」と尋ねたいとき。',
          choices: ['Does she doing her homework?', 'Is she doing her homework?', 'Is she does her homework?', 'She is doing her homework?'],
          correctIndex: 1,
          explanation: '現在進行形の疑問文は、be動詞を主語の前に出して作ります。do / does は使いません。',
          choiceNotes: ['進行形の疑問文に does は使えません。be動詞で作ります。', null, 'Is のあとには -ing形を続けます。', '語順を変えずに「?」を付けるだけでは正しい疑問文になりません。'],
          audioEn: 'Is she doing her homework?',
        },
        {
          id: 'u02-l1-q4',
          prompt: '「今この瞬間の動作」を表している文を選んでください。',
          choices: ['My father works at a bank.', 'My father is washing his car.', 'My father usually washes his car on Sundays.', 'My father likes his car.'],
          correctIndex: 1,
          explanation: 'be動詞 + -ing形の現在進行形だけが「今まさに進行中の動作」を表します。',
          choiceNotes: ['現在形なので「いつものこと(勤務先)」を表しています。', null, 'usually があり、習慣を表す現在形の文です。', '好みを表す現在形の文で、動作ではありません。'],
          audioEn: 'My father is washing his car.',
        },
      ],
      summary: [
        '現在進行形(be動詞 + 動詞の-ing形)は「今まさに進行中の動作」を表す。',
        '-ing形のつづりに注意: make → making、run → running、lie → lying。',
        '否定文は be動詞 + not、疑問文は be動詞を主語の前に。do / does は使わない。',
      ],
    },
    {
      id: 'u02-l2',
      unitId: 'u02',
      level: 'A2',
      title: '現在形 vs 現在進行形',
      objective: '「いつものこと」は現在形、「今だけのこと」は現在進行形という使い分けを判断でき、進行形にしない状態動詞にも対応できるようになります。',
      minutes: 12,
      prereqs: ['u02-l1'],
      blocks: [
        {
          type: 'explanation',
          title: '判断基準は「いつもの? 今だけ?」',
          body:
            '2つの形の使い分けは、**その動作が「いつものこと」か「今だけのこと」か**で決まります。\n\n- I take the bus to work.(毎日の習慣 → 現在形)\n- I am taking a taxi today.(今日だけの特別 → 現在進行形)\n\nヒントになる言葉もあります。\n\n- 現在形と相性がよい: every day, usually, always, on Sundays\n- 現在進行形と相性がよい: now, right now, at the moment, today, this week',
        },
        {
          type: 'timeline',
          title: '時間の広がりを比べる',
          timelines: [
            {
              title: '現在形 I take the bus.',
              range: [0, 130],
              rangeLabel: '普段くり返す習慣',
              caption: '「今この瞬間バスに乗っている」とは限りません。',
            },
            {
              title: '現在進行形 I am taking a taxi today.',
              range: [90, 100],
              rangeLabel: '今だけの一時的な動作',
              arrowToNow: true,
              caption: '「今」の周りだけで起きていることです。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'My mother teaches math at a high school.', ja: '母は高校で数学を教えています。', highlight: 'teaches', note: '職業は「いつものこと」なので現在形です。' },
            { en: 'She is teaching a class right now, so she cannot answer the phone.', ja: '彼女は今ちょうど授業中なので、電話に出られません。', highlight: 'is teaching' },
            { en: 'It rains a lot in June.', ja: '6月は雨がたくさん降ります。', highlight: 'rains', note: '毎年成り立つ事実です。' },
            { en: 'Take an umbrella. It is raining outside.', ja: '傘を持って行って。外は雨が降っています。', highlight: 'is raining' },
            { en: "I am staying at my aunt's house this week.", ja: '今週はおばの家に泊まっています。', highlight: 'am staying', note: '「今週だけ」のような一時的な状況にも現在進行形を使います。' },
          ],
        },
        {
          type: 'contrast',
          title: '現在形 vs 現在進行形',
          left: {
            label: '現在形(いつものこと)',
            items: [
              { en: 'He works in Nagoya.', ja: '彼は名古屋で働いています。', highlight: 'works' },
              { en: 'We usually eat dinner at seven.', ja: '私たちはたいてい7時に夕食を食べます。', highlight: 'eat' },
            ],
            pointJa: '習慣・事実・変わらない状況',
          },
          right: {
            label: '現在進行形(今だけのこと)',
            items: [
              { en: 'He is working from home today.', ja: '彼は今日は在宅で働いています。', highlight: 'is working' },
              { en: 'We are eating dinner now. Can I call you back?', ja: '今、夕食中です。かけ直してもいいですか。', highlight: 'are eating' },
            ],
            pointJa: '今この瞬間・一時的な状況',
          },
          note: '日本語ではどちらも「〜しています」と訳せることが多いので、訳ではなく「いつもの? 今だけ?」で判断するのがコツです。',
        },
        {
          type: 'explanation',
          title: '進行形にしない動詞(状態動詞)',
          body:
            'like / love / want / need / know / believe / understand / have(持っている)など、**動作ではなく「状態」を表す動詞は、原則として進行形にしません**。\n\n- ○ I know his name. / × I am knowing his name.\n- ○ She wants a new bike. / × She is wanting a new bike.\n\n注意: have は「持っている」の意味では進行形にできませんが、「食べる・(時間を)過ごす」という動作の意味なら進行形にできます。\n\n- ○ We are having lunch now.(今、昼食を食べている)',
        },
      ],
      quiz: [
        {
          id: 'u02-l2-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'My brother ___ the guitar every evening.',
          sentenceJa: '兄は毎晩ギターを弾きます。',
          choices: ['is playing', 'plays', 'play', 'is play'],
          correctIndex: 1,
          explanation: 'every evening(毎晩)は習慣のサインなので現在形を使います。主語が3人称単数なので plays です。',
          choiceNotes: ['every evening は習慣を表すので、現在進行形は合いません。', null, '主語 My brother は3人称単数なので -s が必要です。', 'be動詞と動詞の原形は並べられません。'],
          audioEn: 'My brother plays the guitar every evening.',
        },
        {
          id: 'u02-l2-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Be quiet, please. The students ___ a test now.',
          sentenceJa: '静かにしてください。生徒たちは今テストを受けています。',
          choices: ['take', 'takes', 'are taking', 'took'],
          correctIndex: 2,
          explanation: 'now とあるので今この瞬間に進行中の動作です。主語が複数なので are taking を使います。',
          choiceNotes: ['現在形の take は習慣の意味になり、「今受けている最中」を表せません。', '主語が複数なので takes は使えません。今の動作には進行形が必要です。', null, '過去形では「今」の状況を表せません。'],
          audioEn: 'Be quiet, please. The students are taking a test now.',
        },
        {
          id: 'u02-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「私は今、新しいかばんが欲しいです」と言いたいとき。',
          choices: ['I am wanting a new bag now.', 'I want a new bag now.', 'I wanting a new bag now.', 'I am want a new bag now.'],
          correctIndex: 1,
          explanation: 'want は状態動詞なので、now が付いていても進行形にはしません。現在形のままで「今欲しい」を表せます。',
          choiceNotes: ['want は状態動詞なので進行形にできません。', null, '-ing形だけでは動詞になりません。', 'be動詞と動詞の原形は並べられません。'],
          audioEn: 'I want a new bag now.',
        },
        {
          id: 'u02-l2-q4',
          prompt: '文法的に誤っている文を選んでください。',
          choices: ['I am looking for my keys.', 'She is knowing the answer.', 'They are staying at a hotel this weekend.', 'He is thinking about the problem.'],
          correctIndex: 1,
          explanation: 'know は状態動詞なので進行形にできません。She knows the answer. が正しい形です。',
          choiceNotes: ['「探す」は動作なので進行形にできます。', null, '一時的な滞在は進行形で自然に表せます。', 'think は「頭を働かせて考える」という動作の意味では進行形にできます。'],
          audioEn: 'She knows the answer.',
        },
      ],
      summary: [
        '「いつものこと」は現在形、「今だけのこと・一時的なこと」は現在進行形。',
        'every day / usually は現在形のサイン、now / at the moment / this week は現在進行形のサイン。',
        'like / want / know などの状態動詞は原則進行形にしない。',
        'have は「持っている」なら進行形にできず、「食べる」の意味なら進行形にできる。',
      ],
    },
    {
      id: 'u02-l3',
      unitId: 'u02',
      level: 'A2',
      title: '過去形(規則・不規則)',
      objective: '終わった出来事を過去形で表し、主要な不規則動詞と、did を使った否定文・疑問文を使えるようになります。',
      minutes: 12,
      prereqs: ['u02-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '過去の出来事・状態を伝える',
          body:
            '過去形は、**過去のある時点・期間に起きた出来事や状態**を伝えます。\n\n- I visited Kyoto last month. → 先月、京都を訪れました。\n- She was tired yesterday. → 昨日、彼女は疲れていました。\n\nyesterday / last week / two years ago などとよく使います。過去形だけでは、今どうなっているかまでは決まりません。昨日疲れていた人が、今日も疲れている可能性はあります。\n\n規則動詞は -ed を付けます(play → played、visit → visited)。一般動詞の過去形は、主語が I でも she でも同じ形です。be動詞は主語に合わせて was / were を選びます。',
        },
        {
          type: 'timeline',
          title: '過去形の時間イメージ',
          timelines: [
            {
              title: 'I visited Kyoto last month.',
              point: 40,
              pointLabel: 'visited(先月)',
              caption: '先月の訪問に注目しています。今の状況については、この文だけでは分かりません。',
            },
          ],
        },
        {
          type: 'table',
          title: '主要な不規則動詞',
          headers: ['原形', '過去形', '意味'],
          rows: [
            ['go', 'went', '行く'],
            ['come', 'came', '来る'],
            ['see', 'saw', '見る・会う'],
            ['eat', 'ate', '食べる'],
            ['take', 'took', '取る・(乗り物に)乗る'],
            ['get', 'got', '手に入れる'],
            ['make', 'made', '作る'],
            ['buy', 'bought', '買う'],
            ['have', 'had', '持っている・食べる'],
            ['do', 'did', 'する'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I visited my grandparents last weekend.', ja: '先週末、祖父母を訪ねました。', highlight: 'visited' },
            { en: 'We went to a new ramen shop yesterday.', ja: '昨日、新しいラーメン店に行きました。', highlight: 'went' },
            { en: 'She bought a nice jacket at the mall.', ja: '彼女はモールで素敵なジャケットを買いました。', highlight: 'bought' },
            { en: "I didn't watch the game last night.", ja: '昨夜は試合を見ませんでした。', highlight: "didn't watch", note: "didn't のあとは動詞を原形に戻します。" },
            { en: 'Did you finish your homework?', ja: '宿題は終わりましたか。', highlight: 'Did', note: '疑問文は Did + 主語 + 原形です。' },
            { en: 'The movie was really good.', ja: 'その映画は本当に良かったです。', highlight: 'was', note: 'be動詞の過去形は was / were です。' },
          ],
        },
        {
          type: 'explanation',
          title: '否定文・疑問文は did にお任せ',
          body:
            '一般動詞の過去の否定文・疑問文は、do / does の過去形 **did** を使います。\n\n- 否定文: didn\'t + 動詞の原形(I didn\'t go.)\n- 疑問文: Did + 主語 + 動詞の原形(Did you go?)\n\n**did が「過去」を引き受ける**ので、あとの動詞は原形に戻ります。× I didn\'t went. は最もよくある間違いです。\n\nbe動詞(was / were)の文は、これまでどおり be動詞が自分で否定・疑問を作ります(She wasn\'t tired. / Were you busy?)。',
        },
      ],
      quiz: [
        {
          id: 'u02-l3-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'We ___ dinner at an Italian restaurant last night.',
          sentenceJa: '私たちは昨夜、イタリアンレストランで夕食を食べました。',
          choices: ['eat', 'ate', 'eated', 'have eat'],
          correctIndex: 1,
          explanation: 'last night(昨夜)とあるので過去形が必要です。eat は不規則動詞で、過去形は ate です。',
          choiceNotes: ['last night とあるので現在形は使えません。', null, 'eat は不規則動詞で、eated という形はありません。', 'have eat という形はありません。'],
          audioEn: 'We ate dinner at an Italian restaurant last night.',
        },
        {
          id: 'u02-l3-q2',
          prompt: '正しい否定文を選んでください。',
          sentenceJa: '「私は昨日、彼に会いませんでした」と言いたいとき。',
          choices: ["I didn't see him yesterday.", "I didn't saw him yesterday.", "I don't saw him yesterday.", 'I not saw him yesterday.'],
          correctIndex: 0,
          explanation: "didn't が「過去」を引き受けるので、あとの動詞は原形 see に戻します。",
          choiceNotes: [null, "didn't のあとは原形 see に戻します。saw は使えません。", "過去の話なので don't ではなく didn't を使います。", 'not だけでは否定文を作れません。'],
          audioEn: "I didn't see him yesterday.",
        },
        {
          id: 'u02-l3-q3',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「あなたは先週末、テニスをしましたか」と尋ねたいとき。',
          choices: ['Did you played tennis last weekend?', 'Did you play tennis last weekend?', 'Do you played tennis last weekend?', 'You did play tennis last weekend?'],
          correctIndex: 1,
          explanation: 'Did が過去を引き受けるので、動詞は原形 play を使います。',
          choiceNotes: ['Did と played で過去が二重になっています。', null, '過去の疑問文には Do ではなく Did を使います。', '疑問文は Did を文頭に出します。'],
          audioEn: 'Did you play tennis last weekend?',
        },
        {
          id: 'u02-l3-q4',
          prompt: '空所に入る語を選んでください。',
          sentence: 'My keys ___ on the table this morning, but now I cannot find them.',
          sentenceJa: '今朝、鍵はテーブルの上にあったのに、今は見つかりません。',
          choices: ['was', 'were', 'did', 'are'],
          correctIndex: 1,
          explanation: '「今朝あった」という過去の話で、主語 My keys は複数なので were を使います。',
          choiceNotes: ['主語 My keys は複数なので was は使えません。', null, 'did は一般動詞の否定・疑問を作るヘルパーで、ここでは動詞になりません。', '「今朝あった」という過去の話なので現在形 are は合いません。'],
          audioEn: 'My keys were on the table this morning, but now I cannot find them.',
        },
      ],
      summary: [
        '過去形は「終わって今とは切り離された出来事」。yesterday / last week / ago と相性がよい。',
        '規則動詞は -ed。go → went、buy → bought などの不規則動詞は形ごと覚える。',
        "否定文は didn't + 原形、疑問文は Did + 主語 + 原形。動詞は必ず原形に戻す。",
        'be動詞の過去は was / were。否定・疑問は be動詞が自分で作る。',
      ],
    },
    {
      id: 'u02-l4',
      unitId: 'u02',
      level: 'A2',
      title: '過去進行形',
      objective: '過去のある時点で進行中だった動作を was / were + -ing形で表し、when / while を使って2つの出来事を組み合わせられるようになります。',
      minutes: 10,
      prereqs: ['u02-l3'],
      blocks: [
        {
          type: 'explanation',
          title: '「そのとき〜している最中だった」',
          body:
            '過去進行形(**was / were + 動詞の-ing形**)は、**過去のある時点で進行中だった動作**を表します。\n\n- At eight last night, I was taking a bath.(昨夜8時の時点で、入浴の最中だった)\n\n「何時に何をした」ではなく、「その時刻をまたいで動作が続いていた」ことを伝える形です。現在進行形の be動詞を was / were に変えるだけなので、作り方はもう知っているはずです。',
        },
        {
          type: 'timeline',
          title: '長い動作と短い出来事',
          timelines: [
            {
              title: 'I was taking a shower when the phone rang.',
              range: [30, 50],
              rangeLabel: 'was taking a shower(長い動作)',
              point: 42,
              pointLabel: 'the phone rang(短い出来事)',
              caption: '長く続いていた動作の途中に、短い出来事が割り込みました。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I was watching TV at nine last night.', ja: '昨夜9時にはテレビを見ていました。', highlight: 'was watching' },
            { en: 'They were playing soccer when it started to rain.', ja: '雨が降り出したとき、彼らはサッカーをしていました。', highlight: 'were playing' },
            { en: 'She was cooking dinner while I was doing my homework.', ja: '私が宿題をしている間、彼女は夕食を作っていました。', highlight: 'was cooking', note: 'while で2つの進行中の動作を並べられます。' },
            { en: 'What were you doing at noon yesterday?', ja: '昨日の正午には何をしていましたか。', highlight: 'were you doing' },
            { en: "I wasn't sleeping when you called me.", ja: 'あなたが電話をくれたとき、私は眠っていませんでした。', highlight: "wasn't sleeping" },
          ],
        },
        {
          type: 'contrast',
          title: '過去形 vs 過去進行形',
          left: {
            label: '過去形(完結した出来事)',
            items: [
              { en: 'I read a book last night.', ja: '昨夜、本を読みました。', highlight: 'read' },
              { en: 'The phone rang.', ja: '電話が鳴りました。', highlight: 'rang' },
            ],
            pointJa: '出来事を「ひとかたまり」として伝える',
          },
          right: {
            label: '過去進行形(途中だった動作)',
            items: [
              { en: 'I was reading a book at ten last night.', ja: '昨夜10時には本を読んでいる最中でした。', highlight: 'was reading' },
              { en: 'The phone was ringing when I got home.', ja: '帰宅したとき、電話が鳴っている最中でした。', highlight: 'was ringing' },
            ],
            pointJa: '「その時点で途中だった」ことを伝える',
          },
          note: 'when の文では「短い出来事 = 過去形」「背景の長い動作 = 過去進行形」の組み合わせが定番です。',
        },
        {
          type: 'explanation',
          title: 'when と while の使い分け',
          body:
            '**when は「〜したとき・〜するとき」、while は「〜している間」**です。動作の長さだけで時制が決まるわけではありません。\n\n- When the phone rang, I was taking a shower. → 電話が鳴ったとき、シャワーを浴びていました。\n- While I was taking a shower, the phone rang. → シャワーを浴びている間に、電話が鳴りました。\n\nどちらもシャワーの途中で電話が鳴った場面です。**途中だった動作は過去進行形、起きた出来事は過去形**で表しています。when + 過去進行形も使えるので、「when なら必ず過去形」とは覚えないようにしましょう。',
        },
      ],
      quiz: [
        {
          id: 'u02-l4-q1',
          prompt: '空所に入る形を選んでください。',
          sentence: 'When you called me, I ___ a shower.',
          sentenceJa: 'あなたが電話をくれたとき、私はシャワーを浴びている最中でした。',
          choices: ['took', 'was taking', 'am taking', 'were taking'],
          correctIndex: 1,
          explanation: '「電話が来た時点で浴びている最中だった」ので過去進行形です。主語が I なので was taking です。',
          choiceNotes: ['took だと完結した出来事になり、「最中だった」という意味が出ません。', null, '過去の話なので am は使えません。', '主語が I なので were ではなく was です。'],
          audioEn: 'When you called me, I was taking a shower.',
        },
        {
          id: 'u02-l4-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「雨が降り出したとき、私たちは公園を歩いていました」と言いたいとき。',
          choices: [
            'We walked in the park when it started to rain.',
            'We were walking in the park when it started to rain.',
            'We were walk in the park when it started to rain.',
            'We walking in the park when it started to rain.',
          ],
          correctIndex: 1,
          explanation: '「歩いている最中」という背景の動作は過去進行形 were walking で表します。',
          choiceNotes: ['walked だと「雨が降り出したあとに歩いた」ようにも聞こえ、「歩いている最中だった」という意味になりません。', null, 'were のあとは -ing形を続けます。', 'be動詞が抜けています。'],
          audioEn: 'We were walking in the park when it started to rain.',
        },
        {
          id: 'u02-l4-q3',
          prompt: '空所に入る語を選んでください。',
          sentence: '___ I was studying, my brother was playing video games.',
          sentenceJa: '私が勉強している間、弟はテレビゲームをしていました。',
          choices: ['While', 'During', 'Did', 'Was'],
          correctIndex: 0,
          explanation: 'あとに「主語 + 動詞」の文が続くので接続詞 While を使います。長く続く動作どうしを並べる形です。',
          choiceNotes: [null, 'during のあとには名詞(during the class など)を続けます。文は続けられません。', 'Did は疑問文を作る語で、ここでは意味が通りません。', 'Was を文頭に置くと疑問文になってしまいます。'],
          audioEn: 'While I was studying, my brother was playing video games.',
        },
        {
          id: 'u02-l4-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「昨日の午後3時、あなたは何をしていましたか」と尋ねたいとき。',
          choices: [
            'What did you doing at three yesterday afternoon?',
            'What were you doing at three yesterday afternoon?',
            'What you were doing at three yesterday afternoon?',
            'What were you do at three yesterday afternoon?',
          ],
          correctIndex: 1,
          explanation: '過去進行形の疑問文は were を主語の前に出し、動詞は -ing形のままにします。',
          choiceNotes: ['did と -ing形は組み合わせられません。', null, '疑問文では were を主語の前に出します。', 'were のあとは -ing形を続けます。'],
          audioEn: 'What were you doing at three yesterday afternoon?',
        },
      ],
      summary: [
        '過去進行形(was / were + -ing形)は「過去のある時点で進行中だった動作」を表す。',
        '短い出来事は過去形、背景の長い動作は過去進行形、という組み合わせが定番。',
        'when + 過去形(短い出来事)、while + 過去進行形(長い動作)。',
      ],
    },
    {
      id: 'u02-l5',
      unitId: 'u02',
      level: 'A2',
      title: 'willによる未来',
      objective: 'will を使って未来の予測・その場での決定・申し出や約束を表せるようになります。',
      minutes: 10,
      prereqs: ['u02-l4'],
      blocks: [
        {
          type: 'explanation',
          title: 'will の3つの顔',
          body:
            'will は「未来」と訳されますが、実際の会話では大きく3つの場面で使います。\n\n- **予測**: It will rain tomorrow.(たぶんこうなる、という見通し)\n- **その場の決定**: The phone is ringing. I\'ll get it.(今この瞬間に決めたこと)\n- **申し出・約束**: I\'ll help you with your bags.(〜しますよ / 〜しますね)\n\n特に「その場の決定」は日本人学習者が見落としがちな使い方です。前から決めていた計画には、次のレッスンで学ぶ be going to のほうが自然です。\n\n形は **will + 動詞の原形**。主語が何でも will の形は変わりません。会話では I\'ll / she\'ll のように短縮するのがふつうです。',
        },
        {
          type: 'timeline',
          title: 'will の時間イメージ',
          timelines: [
            {
              title: 'It will rain tomorrow.',
              point: 115,
              pointLabel: 'rain(明日)',
              caption: '「今」から先の出来事を、話し手の見通しとして述べています。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I think our team will win the game.', ja: '私たちのチームが試合に勝つと思います。', highlight: 'will win', note: 'I think とセットで予測によく使います。' },
            { en: "It's cold in here. I'll close the window.", ja: 'ここは寒いですね。窓を閉めますね。', highlight: "I'll close", note: '今この場で決めた行動です。' },
            { en: "Don't worry. I'll call you tonight.", ja: '心配しないで。今夜電話するよ。', highlight: "I'll call", note: '約束の will です。' },
            { en: 'She will be twenty next month.', ja: '彼女は来月20歳になります。', highlight: 'will be' },
            { en: "I won't be at home tomorrow morning.", ja: '明日の朝は家にいません。', highlight: "won't be", note: "won't は will not の短縮形です。" },
            { en: 'Will you be free this weekend?', ja: '今週末は空いていますか。', highlight: 'Will' },
          ],
        },
        {
          type: 'explanation',
          title: '否定文・疑問文',
          body:
            'will は助動詞なので、否定文・疑問文の作り方はシンプルです。\n\n- 否定文: will not(短縮形 **won\'t**)+ 原形。I won\'t be late.\n- 疑問文: **Will** + 主語 + 原形。Will she come to the party?\n\ndo / does / did は使いません。また、will のあとの動詞はいつでも原形です。主語が3人称単数でも -s は付けません。× She will comes.',
        },
      ],
      quiz: [
        {
          id: 'u02-l5-q1',
          prompt: '状況に合う応答を選んでください。',
          sentence: 'The doorbell is ringing. — ___',
          sentenceJa: '玄関のベルが鳴っています。—「わかった、私が出るよ」(今この場で決めた)',
          choices: ["OK, I'll get it.", 'OK, I get it.', 'OK, I am get it.', 'OK, I will getting it.'],
          correctIndex: 0,
          explanation: 'ベルの音を聞いて今この場で決めた行動なので、will(短縮形 I\'ll)を使います。',
          choiceNotes: [null, '現在形は習慣を表すので、今この場で決めた行動には合いません。', 'be動詞と動詞の原形は並べられません。', 'will のあとは動詞の原形を使います。'],
          audioEn: "OK, I'll get it.",
        },
        {
          id: 'u02-l5-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I think it ___ sunny tomorrow.',
          sentenceJa: '明日は晴れると思います。',
          choices: ['will be', 'will is', 'is', 'wills be'],
          correctIndex: 0,
          explanation: '明日についての予測なので will を使い、あとには原形 be を続けます。',
          choiceNotes: [null, 'will のあとは原形 be です。is は続けられません。', 'tomorrow の予測は現在形では表せません。', 'will は主語が何でも形が変わりません。'],
          audioEn: 'I think it will be sunny tomorrow.',
        },
        {
          id: 'u02-l5-q3',
          prompt: '正しい否定文を選んでください。',
          sentenceJa: '「明日は忙しくないでしょう」と言いたいとき。',
          choices: ["I won't be busy tomorrow.", "I don't will be busy tomorrow.", "I won't busy tomorrow.", "I will don't be busy tomorrow."],
          correctIndex: 0,
          explanation: "will の否定は will not(won't)で、あとに原形 be を続けます。busy は形容詞なので be が必要です。",
          choiceNotes: [null, "will の否定に don't は使いません。won't を使います。", 'busy は形容詞なので be が必要です。', "will と don't は並べられません。"],
          audioEn: "I won't be busy tomorrow.",
        },
        {
          id: 'u02-l5-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「彼女はパーティーに来るでしょうか」と尋ねたいとき。',
          choices: ['Does she will come to the party?', 'Will she come to the party?', 'Will she comes to the party?', 'She will come to the party?'],
          correctIndex: 1,
          explanation: 'will の疑問文は Will を主語の前に出し、動詞は原形のままにします。',
          choiceNotes: ['does と will は同じ文で使えません。', null, 'will のあとの動詞は主語が3人称単数でも原形です。', '語順を変えずに「?」を付けるだけでは正しい疑問文になりません。'],
          audioEn: 'Will she come to the party?',
        },
      ],
      summary: [
        'will は「予測」「その場の決定」「申し出・約束」の3つの場面で使う。',
        'will + 動詞の原形。主語が3人称単数でも -s は付けない。',
        "否定は won't(will not)、疑問は Will を主語の前に。do / does は使わない。",
        '前から決めていた計画には will より be going to が自然(次のレッスンで学習)。',
      ],
    },
    {
      id: 'u02-l6',
      unitId: 'u02',
      level: 'A2',
      title: 'be going to',
      objective: 'すでに決めている予定や、目の前の根拠がある予測を be going to で表し、will との使い分けを判断できるようになります。',
      minutes: 10,
      prereqs: ['u02-l5'],
      blocks: [
        {
          type: 'explanation',
          title: '「もう決めてある」の be going to',
          body:
            'be going to は、**話す前からすでに決めていた意図・計画**を表します。\n\n- I am going to visit my grandmother this weekend.(前から決めている予定)\n\n形は **be動詞 + going to + 動詞の原形** です。be動詞を使うので、否定文・疑問文の作り方はいつもの be動詞のルールどおりです。\n\n- She isn\'t going to buy that car.\n- Are you going to study abroad?',
        },
        {
          type: 'timeline',
          title: 'be going to の時間イメージ',
          timelines: [
            {
              title: 'I am going to visit my grandmother this weekend.',
              range: [70, 100],
              rangeLabel: 'すでに決めている',
              arrowToNow: true,
              point: 115,
              pointLabel: 'visit(今週末)',
              caption: '実行するのは未来ですが、決めたのは「今」より前です。',
            },
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'We are going to move to Sapporo next spring.', ja: '私たちは来春、札幌に引っ越す予定です。', highlight: 'are going to move' },
            { en: 'I am going to start jogging next week.', ja: '来週からジョギングを始めるつもりです。', highlight: 'am going to start' },
            { en: "He isn't going to take the job.", ja: '彼はその仕事を引き受けないつもりです。', highlight: "isn't going to take" },
            { en: 'What are you going to do during the holidays?', ja: '休みの間は何をする予定ですか。', highlight: 'are you going to do' },
            { en: 'Look at those clouds. It is going to rain.', ja: 'あの雲を見て。雨が降りそうです。', highlight: 'is going to rain', note: '目の前の根拠(雲)にもとづく予測です。' },
          ],
        },
        {
          type: 'explanation',
          title: '根拠のある予測',
          body:
            'be going to には「予測」の使い方もあります。will の予測との違いは、**目の前に根拠(証拠)が見えている**ことです。\n\n- Look at those clouds. It **is going to** rain.(黒い雲という証拠がある)\n- Watch out! You **are going to** drop the plates.(今にも落としそうな様子が見えている)\n\n「このままいけば確実にこうなる」と見えているときは be going to が自然です。',
        },
        {
          type: 'contrast',
          title: 'will vs be going to',
          left: {
            label: 'will(その場の決定・見通し)',
            items: [
              { en: "I'll have the pasta, please.", ja: 'パスタをお願いします(メニューを見て今決めた)。', highlight: "I'll have" },
              { en: 'I think he will pass the exam.', ja: '彼は試験に受かると思います(自分の考えとしての予測)。', highlight: 'will pass' },
            ],
            pointJa: '今この場で決めたこと・話し手の考えにもとづく予測',
          },
          right: {
            label: 'be going to(事前の計画・根拠のある予測)',
            items: [
              { en: 'I am going to make curry tonight. I bought the ingredients yesterday.', ja: '今夜はカレーを作る予定です。昨日材料を買いました。', highlight: 'am going to make' },
              { en: 'She is going to have a baby in June.', ja: '彼女は6月に出産予定です。', highlight: 'is going to have' },
            ],
            pointJa: '前から決めている計画・目に見える根拠のある予測',
          },
          note: '迷ったら「話す前から決めていた?」と自問してください。決めていたなら be going to、今決めたなら will です。',
        },
      ],
      quiz: [
        {
          id: 'u02-l6-q1',
          prompt: '状況に合う文を選んでください。',
          sentenceJa: '来月の旅行のために、もう航空券を買ってあります。友達に予定を伝えるとき。',
          choices: ["I'll visit Okinawa next month.", 'I am going to visit Okinawa next month.', 'I visit Okinawa next month.', 'I visited Okinawa next month.'],
          correctIndex: 1,
          explanation: '航空券を買ってあるということは、話す前から決めている計画なので be going to が自然です。',
          choiceNotes: ['will はその場で決めたときに使うので、すでに決まっている計画には be going to のほうが自然です。', null, '現在形は習慣を表し、1回限りの予定には使えません。', '過去形では未来の予定を表せません。'],
          audioEn: 'I am going to visit Okinawa next month.',
        },
        {
          id: 'u02-l6-q2',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Look out! That box ___ fall.',
          sentenceJa: '危ない!あの箱、落ちそうだよ。',
          choices: ['is going to', 'will going to', 'goes to', 'is go to'],
          correctIndex: 0,
          explanation: '今にも落ちそうな様子が目に見えているので、根拠のある予測の be going to を使います。',
          choiceNotes: [null, 'will と be going to は同時に使えません。', 'goes to では「落ちそうだ」という予測を表せません。', 'be動詞のあとは going to の形にします。'],
          audioEn: 'Look out! That box is going to fall.',
        },
        {
          id: 'u02-l6-q3',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「今週末、何をする予定ですか」と尋ねたいとき。',
          choices: [
            'What are you going to do this weekend?',
            'What do you going to do this weekend?',
            'What are you going to doing this weekend?',
            'What you are going to do this weekend?',
          ],
          correctIndex: 0,
          explanation: 'be going to の疑問文は be動詞を主語の前に出します。going to のあとは原形 do です。',
          choiceNotes: [null, 'be going to の疑問文は be動詞で作ります。do は使いません。', 'going to のあとは動詞の原形を続けます。', '疑問文では be動詞を主語の前に出します。'],
          audioEn: 'What are you going to do this weekend?',
        },
        {
          id: 'u02-l6-q4',
          prompt: '状況に合う応答を選んでください。',
          sentence: "We don't have any milk. — ___",
          sentenceJa: '牛乳が切れているよ。—「そうなの? じゃあ帰りに買ってくるよ」(今この場で決めた)',
          choices: [
            "Really? I'm going to buy some on my way home.",
            "Really? I'll buy some on my way home.",
            'Really? I buy some on my way home.',
            'Really? I bought some on my way home.',
          ],
          correctIndex: 1,
          explanation: '牛乳がないと聞いて今この場で決めたことなので will が自然です。be going to は前から決めていた場合に使います。',
          choiceNotes: ['be going to は前から決めていた計画に使うので、今この場の決定には will が自然です。', null, '現在形では「これからする」という決定を表せません。', '過去形ではこれからの行動を表せません。'],
          audioEn: "Really? I'll buy some on my way home.",
        },
      ],
      summary: [
        'be going to(be動詞 + going to + 原形)は「前から決めている意図・計画」を表す。',
        '目の前に根拠が見えている予測にも be going to を使う。',
        '今この場で決めたことは will、話す前から決めていたことは be going to。',
        "否定・疑問は be動詞のルールで作る(isn't going to / Are you going to ...?)。",
      ],
    },
  ],
}
