import type { GrammarUnit } from '../../types'

// U03 名詞と冠詞の基礎 — カリキュラム docs/grammar-curriculum.md の U03 に対応。

export const u03: GrammarUnit = {
  id: 'u03',
  level: 'A2',
  title: '名詞と冠詞の基礎',
  lessons: [
    {
      id: 'u03-l1',
      unitId: 'u03',
      level: 'A2',
      title: '可算名詞と不可算名詞',
      objective: '英語の名詞を「数えられる名詞」と「数えられない名詞」に区別し、複数形や数え方の表現を正しく使えるようになります。',
      minutes: 10,
      blocks: [
        {
          type: 'explanation',
          title: '「1つ、2つ」と数えられるか?',
          body:
            '英語の名詞は、**数えられる名詞(可算名詞)**と**数えられない名詞(不可算名詞)**の2種類に分かれます。\n\n- 可算名詞: 1つずつの形がはっきりしているもの。a / an が付き、複数形(-s)がある。an apple, two chairs\n- 不可算名詞: 液体・素材・まとまりなど、区切りのないもの。a / an も複数形も付かず、**単数扱い**。water, bread, money\n\n日本語には「りんご**たち**」のような複数形の習慣がないので、この区別は意識して身につける必要があります。',
        },
        {
          type: 'explanation',
          title: '日本人が間違えやすい不可算名詞',
          body:
            '「数えられそうなのに数えられない」名詞が要注意です。代表的なグループを覚えておきましょう。\n\n- 情報・助言のなかま: **information, advice, news**(× informations, × advices)\n- まとまりを指す語: **furniture(家具), luggage(荷物), money(お金)**\n- 素材・食べ物: **bread, rice, paper, water**\n\n「家具」は日本語では1つ2つと数えたくなりますが、英語の furniture は「家具類ぜんぶ」というまとまりを指すので数えられません。1つの物を指したいときは a chair, a table のように具体的な語を使います。',
        },
        {
          type: 'table',
          title: '不可算名詞を数えたいときの表現',
          headers: ['不可算名詞', '数える言い方', '意味'],
          rows: [
            ['water', 'a glass of water', 'コップ1杯の水'],
            ['coffee', 'two cups of coffee', 'コーヒー2杯'],
            ['bread', 'a slice of bread', 'パン1枚'],
            ['paper', 'a piece of paper', '紙1枚'],
            ['advice', 'a piece of advice', 'アドバイス1つ'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'There are three apples on the table.', ja: 'テーブルの上にりんごが3つあります。', highlight: 'three apples', note: '可算名詞は数詞 + 複数形で数えます。' },
            { en: 'I need some information about the hotel.', ja: 'そのホテルについての情報が必要です。', highlight: 'information', note: '× informations とは言いません。' },
            { en: 'She gave me two pieces of advice.', ja: '彼女は私にアドバイスを2つくれました。', highlight: 'two pieces of advice' },
            { en: 'We bought some furniture for the new house.', ja: '新しい家のために家具をいくつか買いました。', highlight: 'furniture' },
            { en: 'Money is important, but it is not everything.', ja: 'お金は大切ですが、すべてではありません。', highlight: 'Money is', note: '不可算名詞は単数扱いなので is を使います。' },
          ],
        },
        {
          type: 'contrast',
          title: '可算 vs 不可算',
          left: {
            label: '可算名詞(数えられる)',
            items: [
              { en: 'I ate two eggs this morning.', ja: '今朝、卵を2つ食べました。', highlight: 'two eggs' },
              { en: 'There is a chair in the corner.', ja: '隅に椅子が1脚あります。', highlight: 'a chair' },
            ],
            pointJa: 'a / an が付き、複数形 -s がある',
          },
          right: {
            label: '不可算名詞(数えられない)',
            items: [
              { en: 'I ate some rice this morning.', ja: '今朝、ごはんを食べました。', highlight: 'some rice' },
              { en: 'There is some furniture in the corner.', ja: '隅に家具がいくつかあります。', highlight: 'some furniture' },
            ],
            pointJa: 'a / an も複数形 -s も付かない',
          },
          note: '同じ「家具」でも、chair(1つの物)は可算、furniture(まとまり全体)は不可算です。',
        },
      ],
      quiz: [
        {
          id: 'u03-l1-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'Could you give me some ___?',
          sentenceJa: 'アドバイスをもらえますか。',
          choices: ['advice', 'advices', 'an advice', 'advise'],
          correctIndex: 0,
          explanation: 'advice は不可算名詞なので、複数形にも a / an を付ける形にもできません。some advice が正しい形です。',
          choiceNotes: [null, 'advice は不可算名詞なので複数形 advices はありません。', '不可算名詞に an は付けられません。', 'advise は「助言する」という動詞で、綴りも意味も別の語です。'],
          audioEn: 'Could you give me some advice?',
        },
        {
          id: 'u03-l1-q2',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「その旅行についての情報を持っています」と言いたいとき。',
          choices: ['I have some informations about the trip.', 'I have an information about the trip.', 'I have some information about the trip.', 'I have a information about the trip.'],
          correctIndex: 2,
          explanation: 'information は不可算名詞なので、複数形にせず、a / an も付けずに使います。量を表したいときは some を添えます。',
          choiceNotes: ['information に複数形はありません。', '不可算名詞に an は付けられません。', null, '不可算名詞に a は付けられません。'],
          audioEn: 'I have some information about the trip.',
        },
        {
          id: 'u03-l1-q3',
          prompt: '空所に入る語を選んでください。',
          sentence: 'There ___ some milk in the fridge.',
          sentenceJa: '冷蔵庫に牛乳があります。',
          choices: ['is', 'are', 'be', 'do'],
          correctIndex: 0,
          explanation: 'milk は不可算名詞で単数扱いなので、There is を使います。',
          choiceNotes: [null, 'are は複数の名詞に使います。milk は不可算で単数扱いです。', '原形の be はそのまま現在の文には使えません。', 'There 構文の「ある・いる」は be動詞で表します。do は使えません。'],
          audioEn: 'There is some milk in the fridge.',
        },
        {
          id: 'u03-l1-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['I drink a lot of water every day.', 'She has long hair.', 'He gave me many good advices.', 'We need more time.'],
          correctIndex: 2,
          explanation: 'advice は不可算名詞なので、複数形 advices にはできず、many とも組み合わせられません。a lot of good advice などとします。',
          choiceNotes: ['water は不可算名詞で、a lot of と組み合わせられる正しい文です。', '「髪全体」を指す hair は不可算で、この文は正しいです。', null, 'time(時間)は不可算で、more と組み合わせられる正しい文です。'],
          audioEn: 'He gave me a lot of good advice.',
        },
      ],
      summary: [
        '英語の名詞は可算(a / an と複数形あり)と不可算(どちらもなし・単数扱い)に分かれる。',
        'information, advice, furniture, luggage, money などは日本語の感覚に反して不可算。',
        '不可算名詞を数えたいときは a glass of / a piece of / a slice of などの単位を使う。',
        '不可算名詞は単数扱いなので、動詞は is / was など単数形に合わせる。',
      ],
    },
    {
      id: 'u03-l2',
      unitId: 'u03',
      level: 'A2',
      title: 'a / an の使い方',
      objective: '「たくさんある中の1つ」を表す a / an を正しく使い、次の語の発音によって a と an を使い分けられるようになります。',
      minutes: 8,
      prereqs: ['u03-l1'],
      blocks: [
        {
          type: 'explanation',
          title: 'a / an は「まだ特定していない1つ」',
          body:
            '**a / an は、聞き手がまだ「どれか」を特定できない1人・1つ**を、数えられる名詞の単数形で伝えるときに使います。\n\n- I saw a dog. → 犬を1匹見ました。話し手はどの犬か知っていますが、聞き手にはまだ紹介していません。\n- She is a nurse. → 彼女は看護師です。「看護師という職業の人」と説明しています。\n\na / an は「どれでもよい」という意味に限りません。大事なのは**聞き手と対象を共有できているか**です。共有できている対象には the を使います。',
        },
        {
          type: 'explanation',
          title: 'a と an の使い分けは「音」で決まる',
          body:
            '次に来る語が**母音の「音」**で始まるなら an、**子音の「音」**で始まるなら a を使います。大事なのは綴りではなく**発音**です。\n\n- an apple, an egg(母音の音で始まる)\n- **an hour**(hour の h は発音せず「アワー」と母音の音で始まる)\n- **a university**(綴りは u でも、発音は「ユ」という子音の音で始まる)\n\n綴りだけを見て判断すると間違えるので、声に出して確かめるのがコツです。',
        },
        {
          type: 'table',
          title: '音で決まる a / an',
          headers: ['語', '最初の音', '正しい形'],
          rows: [
            ['apple', '母音(ア)', 'an apple'],
            ['hour', '母音(ア)— h は発音しない', 'an hour'],
            ['honest', '母音(オ)— h は発音しない', 'an honest person'],
            ['university', '子音(ユ)', 'a university'],
            ['one-day trip', '子音(ワ)', 'a one-day trip'],
          ],
        },
        {
          type: 'contrast',
          title: '決めるのはつづりではなく最初の「音」',
          left: {
            label: 'an — 母音の音で始まる',
            items: [
              { en: 'She will arrive in an hour.', ja: '彼女は1時間後に到着します。', highlight: 'an hour', note: 'hour の h は発音しないので「アワー」と母音の音で始まります。' },
              { en: 'He gave me an honest answer.', ja: '彼は私に正直な答えをくれました。', highlight: 'an honest' },
            ],
            pointJa: 'つづりが h で始まっても、聞こえる最初の音が母音なら an。',
          },
          right: {
            label: 'a — 子音の音で始まる',
            items: [
              { en: 'My cousin works at a university.', ja: 'いとこは大学で働いています。', highlight: 'a university', note: 'university は「ユ」という子音の音で始まります。' },
              { en: 'They are planning a one-day trip.', ja: '彼らは日帰り旅行を計画しています。', highlight: 'a one-day trip' },
            ],
            pointJa: 'つづりが母音字で始まっても、聞こえる最初の音が子音なら a。',
          },
          note: '迷ったら声に出して、最初の音を確かめましょう。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'I saw a dog in the park.', ja: '公園で犬を見ました。', highlight: 'a dog', note: '聞き手はまだどの犬か知りません。初登場の1つには a。' },
            { en: 'She is an engineer.', ja: '彼女はエンジニアです。', highlight: 'an engineer', note: '職業を言うときも a / an が必要です。' },
            { en: 'The meeting starts in an hour.', ja: '会議は1時間後に始まります。', highlight: 'an hour', note: 'hour の h は発音しないので an。' },
            { en: 'He goes to a university in Nagoya.', ja: '彼は名古屋の大学に通っています。', highlight: 'a university', note: 'university は「ユ」という子音の音で始まるので a。' },
            { en: 'Do you have an umbrella?', ja: '傘を持っていますか。', highlight: 'an umbrella' },
          ],
        },
        {
          type: 'explanation',
          title: '単数の可算名詞は「裸」で使えない',
          body:
            '日本人学習者が最も落としやすいのがこのルールです。**単数の可算名詞は、a / an・the・my などの目印なしでは文に置けません**。\n\n- × I have pen.\n- ○ I have **a** pen. / I have **the** pen. / I have **my** pen.\n\n日本語では「ペンを持っています」と裸で言えるため抜けやすいポイントです。「単数の可算名詞には必ず目印」と覚えましょう。',
        },
      ],
      quiz: [
        {
          id: 'u03-l2-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'My father is ___ English teacher.',
          sentenceJa: '父は英語の教師です。',
          choices: ['a', 'an', 'the', 'some'],
          correctIndex: 1,
          explanation: 'English は母音の音(イ)で始まるので an を使います。職業や身分を言うときは a / an が必要です。',
          choiceNotes: ['English は母音の音で始まるので a ではなく an です。', null, '「たくさんいる教師の1人」なので、特定を表す the は合いません。', '単数名詞1つに some は使えません。'],
          audioEn: 'My father is an English teacher.',
        },
        {
          id: 'u03-l2-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: 'She goes to ___ university in Tokyo.',
          sentenceJa: '彼女は東京の大学に通っています。',
          choices: ['a', 'an', 'the', 'any'],
          correctIndex: 0,
          explanation: 'university は綴りこそ u で始まりますが、発音は「ユ」という子音の音なので a を使います。',
          choiceNotes: [null, 'an は次の語が母音の音で始まるときに使います。university は子音の音(ユ)で始まります。', 'どの大学かをまだ特定していない初登場の話なので the は合いません。', '肯定文の単数可算名詞に any は使えません。'],
          audioEn: 'She goes to a university in Tokyo.',
        },
        {
          id: 'u03-l2-q3',
          prompt: '正しい文を選んでください。',
          sentenceJa: '「彼は正直な人です」と言いたいとき。',
          choices: ['He is a honest man.', 'He is an honest man.', 'He is honest man.', 'He is the honest man.'],
          correctIndex: 1,
          explanation: 'honest の h は発音せず、「オ」という母音の音で始まるので an を使います。',
          choiceNotes: ['honest は母音の音で始まるので a は使えません。', null, '単数の可算名詞 man を目印なしで使うことはできません。', 'the は「どの人か特定できる」ときの形で、人柄の紹介には合いません。'],
          audioEn: 'He is an honest man.',
        },
        {
          id: 'u03-l2-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['I have a question.', 'She bought a new car.', 'He is doctor.', 'We watched a movie last night.'],
          correctIndex: 2,
          explanation: '職業を表す単数名詞にも a / an が必要です。He is a doctor. が正しい形です。',
          choiceNotes: ['question は可算名詞で、a question は正しい形です。', 'a new car は「1台の新しい車」で正しい形です。', null, 'a movie は「(ある)1本の映画」で正しい形です。'],
          audioEn: 'He is a doctor.',
        },
      ],
      summary: [
        'a / an は「たくさんある中の、どれでもいい1つ」。初登場のものや職業に使う。',
        'a と an の使い分けは綴りではなく音。母音の音なら an(an hour)、子音の音なら a(a university)。',
        '単数の可算名詞は a / an・the・my などの目印なしでは使えない。',
      ],
    },
    {
      id: 'u03-l3',
      unitId: 'u03',
      level: 'A2',
      title: 'the の使い方',
      objective: '「どれのことか、お互いにわかるもの」を指す the を使い、一般論や定型表現で冠詞を付けない場合と区別できるようになります。',
      minutes: 12,
      prereqs: ['u03-l2'],
      blocks: [
        {
          type: 'explanation',
          title: 'the は「どれのことか、お互いわかるよね」',
          body:
            'the の中心的な意味は、**話し手も聞き手も「どれのことか」わかっている**ということです。わかる理由は主に3つあります。\n\n- **前に話題に出たから**: I bought a shirt. The shirt was cheap.\n- **その場に1つしかないから**: Could you open the door?(この部屋のドア)\n- **世界に1つしかないから**: the sun, the moon, the internet\n\n逆に言うと、聞き手が「どれ?」と思うものには the は使えません。a / an(聞き手がまだ特定できない1つ)との違いはここにあります。',
        },
        {
          type: 'examples',
          title: 'a → the の流れ',
          items: [
            { en: 'I bought a shirt and a jacket. The shirt was on sale.', ja: 'シャツとジャケットを買いました。そのシャツはセール品でした。', highlight: 'The shirt', note: '2文目では「どのシャツか」が特定できるので the。' },
            { en: 'Could you open the window?', ja: '窓を開けてもらえますか。', highlight: 'the window', note: 'その場にある窓は、お互いにどれかわかるので the。' },
            { en: 'The sun rises in the east.', ja: '太陽は東から昇ります。', highlight: 'The sun', note: '世界に1つしかないものには the。' },
            { en: 'Is this the key to the front door?', ja: 'これが玄関の鍵ですか。', highlight: 'the key', note: 'to the front door という説明で「どの鍵か」が特定されています。' },
          ],
        },
        {
          type: 'explanation',
          title: '冠詞を付けない(無冠詞の)場合',
          body:
            '特定のものではなく**種類全体についての一般論**を言うときは、複数形や不可算名詞をそのまま(無冠詞で)使います。\n\n- I like dogs.(犬というものが好き)\n- Milk is good for you.(牛乳というものは体に良い)\n\nまた、**決まった言い回し**でも冠詞を付けません。\n\n- 食事: have breakfast / lunch / dinner\n- 交通手段: by train / by bus / by car\n- 活動としての場所: go to bed(寝る), go to work(仕事に行く)',
        },
        {
          type: 'contrast',
          title: 'the vs 無冠詞',
          left: {
            label: 'the(特定のもの)',
            items: [
              { en: 'The coffee at that cafe is great.', ja: 'あのカフェのコーヒーはおいしいです。', highlight: 'The coffee' },
              { en: 'The children are playing outside.', ja: 'うちの子どもたちは外で遊んでいます。', highlight: 'The children' },
            ],
            pointJa: 'どのことを指しているか、お互いにわかる',
          },
          right: {
            label: '無冠詞(一般論)',
            items: [
              { en: 'Coffee keeps me awake.', ja: 'コーヒーというものは目を覚まさせてくれます。', highlight: 'Coffee' },
              { en: 'Children learn languages quickly.', ja: '子どもというものは言語を早く覚えます。', highlight: 'Children' },
            ],
            pointJa: '種類全体についての一般論',
          },
          note: '「〜というものは」と一般論を言うときは、複数形や不可算名詞を無冠詞のまま使います。',
        },
        {
          type: 'table',
          title: '無冠詞の定型パターン',
          headers: ['パターン', '例', '意味'],
          rows: [
            ['食事', 'have breakfast', '朝食をとる'],
            ['交通手段', 'by train', '電車で'],
            ['活動としての場所', 'go to bed', '寝る'],
            ['スポーツ', 'play soccer', 'サッカーをする'],
            ['科目・言語', 'study math', '数学を勉強する'],
          ],
        },
      ],
      quiz: [
        {
          id: 'u03-l3-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: 'I bought a watch yesterday, but ___ watch has already stopped.',
          sentenceJa: '昨日腕時計を買いましたが、その時計はもう止まってしまいました。',
          choices: ['a', 'an', 'the', 'some'],
          correctIndex: 2,
          explanation: '1文目で話題に出た腕時計を指しているので、2回目は「どれのことかわかる」the を使います。',
          choiceNotes: ['a では「別のどれでもいい1つの時計」に聞こえてしまいます。', 'watch は子音の音で始まるうえ、ここでは特定の時計を指すので an は使えません。', null, '特定の1つの時計を指すので some は合いません。'],
          audioEn: 'I bought a watch yesterday, but the watch has already stopped.',
        },
        {
          id: 'u03-l3-q2',
          prompt: '「犬というものが好きだ」という一般論として正しい文を選んでください。',
          choices: ['I like the dogs.', 'I like dogs.', 'I like a dog.', 'I like dog.'],
          correctIndex: 1,
          explanation: '種類全体についての一般論は、複数形を無冠詞のまま使います。I like dogs. が正しい形です。',
          choiceNotes: ['the dogs は「(あの)特定の犬たち」の意味になり、一般論になりません。', null, 'a dog は「1匹の犬」で、犬全般の話にはなりません。', '単数の可算名詞 dog を目印なしで使うことはできません。'],
          audioEn: 'I like dogs.',
        },
        {
          id: 'u03-l3-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: 'I usually go to ___ by train.',
          sentenceJa: '私は普段、電車で仕事に行きます。',
          choices: ['work', 'the work', 'a work', 'works'],
          correctIndex: 0,
          explanation: '「仕事に行く」という活動を表す go to work は無冠詞で使う定型表現です。by train も無冠詞です。',
          choiceNotes: [null, 'go to work という定型表現には the を付けません。', 'work(仕事)は不可算名詞なので a は付けられません。', '不可算名詞 work に複数形はありません。'],
          audioEn: 'I usually go to work by train.',
        },
        {
          id: 'u03-l3-q4',
          prompt: '誤りを含む文を選んでください。',
          choices: ['We had dinner at seven.', 'She plays the piano very well.', 'He plays the soccer on weekends.', 'The moon was beautiful last night.'],
          correctIndex: 2,
          explanation: 'スポーツ名は無冠詞で使います。plays soccer が正しい形です。一方、楽器には the を付ける(play the piano)ので、混同に注意しましょう。',
          choiceNotes: ['食事名は無冠詞で使うので正しい文です。', '楽器には the を付けるので正しい文です。', null, '世界に1つしかない moon には the を付けるので正しい文です。'],
          audioEn: 'He plays soccer on weekends.',
        },
      ],
      summary: [
        'the は「どれのことか、お互いにわかる」とき。前に出た・その場に1つ・世界に1つが主な理由。',
        '種類全体の一般論は、複数形・不可算名詞を無冠詞のまま使う(I like dogs.)。',
        '食事(have breakfast)・交通手段(by train)・go to bed / work などの定型表現は無冠詞。',
        'スポーツは無冠詞(play soccer)、楽器は the 付き(play the piano)。',
      ],
    },
    {
      id: 'u03-l4',
      unitId: 'u03',
      level: 'A2',
      title: 'some / any / much / many',
      objective: '「いくつかの」を表す some / any と「たくさんの」を表す much / many / a lot of を、文の種類と名詞の種類に合わせて使い分けられるようになります。',
      minutes: 10,
      prereqs: ['u03-l3'],
      blocks: [
        {
          type: 'explanation',
          title: 'some と any は「いくつかの・いくらかの」',
          body:
            'some と any はどちらも「いくつかの・いくらかの」という意味で、**可算名詞の複数形にも不可算名詞にも**使えます。使い分けは文の種類で決まります。\n\n- **some**: 肯定文で使う(I bought some oranges.)\n- **any**: 否定文・疑問文で使う(We don\'t have any milk. / Do you have any questions?)\n\nただし例外があります。**相手に物をすすめたり、依頼したりする疑問文では some** を使います(Would you like some tea?)。「Yes の答えを期待している」質問だからです。',
        },
        {
          type: 'contrast',
          title: 'some vs any',
          left: {
            label: 'some(肯定文・すすめる疑問文)',
            items: [
              { en: 'I bought some oranges at the market.', ja: '市場でオレンジをいくつか買いました。', highlight: 'some' },
              { en: 'Would you like some tea?', ja: 'お茶はいかがですか。', highlight: 'some' },
            ],
            pointJa: '肯定文と、すすめ・依頼の疑問文で使う',
          },
          right: {
            label: 'any(否定文・疑問文)',
            items: [
              { en: "We don't have any milk.", ja: '牛乳が全然ありません。', highlight: 'any' },
              { en: 'Do you have any questions?', ja: '何か質問はありますか。', highlight: 'any' },
            ],
            pointJa: '否定文と、あるかどうかわからない疑問文で使う',
          },
          note: 'not any は「1つもない・全然ない」という意味になります。',
        },
        {
          type: 'explanation',
          title: 'much / many / a lot of は「たくさんの」',
          body:
            '「たくさんの」は、名詞の種類によって語を選びます。\n\n- **many + 可算名詞の複数形**: many books, How many students...?\n- **much + 不可算名詞**: much time, How much money...?\n- **a lot of + どちらでも**: a lot of books, a lot of time\n\n日常会話の肯定文では **a lot of が最も自然**です。much と many は、主に否定文・疑問文(特に How much / How many)で活躍します。',
        },
        {
          type: 'table',
          title: '数量表現の使い分け',
          headers: ['表現', '可算名詞(複数)', '不可算名詞', '主な使いどころ'],
          rows: [
            ['some', 'some apples', 'some water', '肯定文・すすめる疑問文'],
            ['any', 'any apples', 'any water', '否定文・疑問文'],
            ['many', 'many apples', '使えない', '疑問文・否定文、How many'],
            ['much', '使えない', 'much water', '疑問文・否定文、How much'],
            ['a lot of', 'a lot of apples', 'a lot of water', '肯定文で「たくさん」'],
          ],
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'How many students are in your class?', ja: 'あなたのクラスには生徒が何人いますか。', highlight: 'How many students', note: '数をたずねるときは How many + 複数形。' },
            { en: "I don't have much time today.", ja: '今日はあまり時間がありません。', highlight: 'much time', note: '否定文の much は「あまり〜ない」。' },
            { en: 'There are a lot of restaurants near here.', ja: 'この近くにはレストランがたくさんあります。', highlight: 'a lot of', note: '肯定文の「たくさん」は a lot of が自然です。' },
            { en: 'Can I have some water?', ja: 'お水をいただけますか。', highlight: 'some', note: '依頼の疑問文では some を使います。' },
            { en: 'Is there any coffee left?', ja: 'コーヒーはまだ残っていますか。', highlight: 'any', note: 'あるかどうかわからない疑問文では any。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u03-l4-q1',
          prompt: '空所に入る語を選んでください。',
          sentence: "I'm sorry, we don't have ___ bread today.",
          sentenceJa: 'すみません、今日はパンが全然ないんです。',
          choices: ['some', 'any', 'many', 'a'],
          correctIndex: 1,
          explanation: '否定文では any を使います。not any で「1つもない・全然ない」という意味になります。',
          choiceNotes: ['some は肯定文と、すすめ・依頼の疑問文で使います。', null, 'bread は不可算名詞なので many とは組み合わせられません。', '不可算名詞 bread に a は付けられません。'],
          audioEn: "I'm sorry, we don't have any bread today.",
        },
        {
          id: 'u03-l4-q2',
          prompt: '空所に入る語を選んでください。',
          sentence: 'How ___ money do you need?',
          sentenceJa: 'いくらお金が必要ですか。',
          choices: ['many', 'much', 'some', 'a lot of'],
          correctIndex: 1,
          explanation: 'money は不可算名詞なので、量をたずねるときは How much を使います。',
          choiceNotes: ['many は可算名詞の複数形に使います。money は不可算です。', null, 'How some という形はありません。', 'How a lot of という形はありません。量をたずねる疑問文では much を使います。'],
          audioEn: 'How much money do you need?',
        },
        {
          id: 'u03-l4-q3',
          prompt: '自然な文を選んでください。',
          sentenceJa: '「コーヒーはいかがですか」とすすめたいとき。',
          choices: ['Would you like any coffee?', 'Would you like some coffee?', 'Would you like many coffee?', 'Do you like some coffee?'],
          correctIndex: 1,
          explanation: '相手にすすめる疑問文では、Yes の答えを期待しているので some を使います。Would you like some coffee? が自然です。',
          choiceNotes: ['すすめるときは any ではなく some が自然です。', null, 'coffee は不可算名詞なので many とは組み合わせられません。', 'Do you like は「好きかどうか」をたずねる文で、その場ですすめる表現にはなりません。'],
          audioEn: 'Would you like some coffee?',
        },
        {
          id: 'u03-l4-q4',
          prompt: '不自然な文を選んでください。',
          choices: ['She has many friends in Canada.', "We didn't take many photos.", 'He drinks much coffee every day.', 'Do you have any plans for the weekend?'],
          correctIndex: 2,
          explanation: '日常的な肯定文の「たくさん」は much より a lot of が自然です。He drinks a lot of coffee every day. とします。',
          choiceNotes: ['many + 可算名詞の複数形(friends)で正しい文です。', '否定文の many は自然な使い方です。', null, '疑問文の any は正しい使い方です。'],
          audioEn: 'He drinks a lot of coffee every day.',
        },
      ],
      summary: [
        'some は肯定文と「すすめ・依頼」の疑問文、any は否定文・疑問文で使う。',
        'not any は「1つもない・全然ない」という意味。',
        'many は可算名詞の複数形、much は不可算名詞に使う。数・量をたずねるのは How many / How much。',
        '肯定文の「たくさん」は a lot of が最も自然。much / many は主に否定文・疑問文で使う。',
      ],
    },
  ],
}
