import type { GrammarUnit } from '../../types'

// U06 疑問文をつくる

export const u06: GrammarUnit = {
  id: 'u06',
  level: 'A2',
  title: '疑問文をつくる',
  lessons: [
    {
      id: 'u06-l1',
      unitId: 'u06',
      level: 'A2',
      title: 'Wh疑問文',
      objective: 'what / where / when / why / who / how を使って、「何・どこ・いつ・なぜ・誰・どのように」を尋ねる疑問文を作れるようになります。',
      minutes: 10,
      blocks: [
        {
          type: 'explanation',
          title: 'Yes/No疑問文の先頭にWh語を置くだけ',
          body:
            'U01で学んだ Do you...? / Is he...? という疑問文は、Yes / No でしか答えられません。「どこ?」「何?」と**具体的な情報**を聞きたいときは、知りたい内容を表す**Wh語を疑問文の先頭に置きます**。\n\n- Do you live in Tokyo?(東京に住んでいますか)\n- → **Where** do you live?(どこに住んでいますか)\n\n土台になる疑問文の語順(do / does や be動詞を主語の前に出す)はそのままで、頭にWh語が1つ乗るだけです。',
        },
        {
          type: 'table',
          title: 'Wh語の意味',
          headers: ['Wh語', '尋ねること', '例'],
          rows: [
            ['what', '何', 'What do you want?'],
            ['where', 'どこ', 'Where do you live?'],
            ['when', 'いつ', 'When does the movie start?'],
            ['why', 'なぜ', 'Why are you tired?'],
            ['who', '誰', 'Who is that woman?'],
            ['how', 'どのように・どんな様子', 'How do you go to school?'],
          ],
        },
        {
          type: 'structure',
          title: 'Wh疑問文の語順(一般動詞の文)',
          parts: [
            { label: 'Wh語', text: 'Where' },
            { label: 'do / does', text: 'does' },
            { label: '主語', text: 'she' },
            { label: '動詞の原形', text: 'work' },
          ],
          caption: 'be動詞の文では do を使わず「Wh語 + be動詞 + 主語」: Where is she?',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'What time do you usually get up?', ja: '普段何時に起きますか。', highlight: 'What time', note: 'what は time や color と組み合わせて「何時・何色」のようにも使えます。' },
            { en: 'Where did you buy that jacket?', ja: 'そのジャケットはどこで買ったのですか。', highlight: 'Where', note: '過去のことを尋ねるときは did を使います。' },
            { en: 'When does the next bus leave?', ja: '次のバスはいつ出発しますか。', highlight: 'When' },
            { en: 'Why is he angry?', ja: 'なぜ彼は怒っているのですか。', highlight: 'Why is', note: 'be動詞の文なので、Wh語のすぐあとに be動詞が来ます。' },
            { en: 'Who is your favorite singer?', ja: 'あなたの一番好きな歌手は誰ですか。', highlight: 'Who' },
            { en: 'How do I get to the station?', ja: '駅へはどう行けばいいですか。', highlight: 'How', note: '道の尋ね方の定番フレーズです。' },
          ],
        },
        {
          type: 'explanation',
          title: '答えるときは Yes / No を使わない',
          body:
            'Wh疑問文には、Yes / No ではなく**具体的な情報**で答えます。\n\n- Where do you live? — In Yokohama.(完全な文にしなくても自然です)\n- Why are you tired? — **Because** I got up at five.(why には because で理由を答えるのが定番)\n\n「Wh疑問文 → 情報で答える」「Yes/No疑問文 → Yes / No で答える」という対応を意識すると、会話のキャッチボールがスムーズになります。',
        },
      ],
      quiz: [
        {
          id: 'u06-l1-q1',
          prompt: '空所に入るWh語を選んでください。',
          sentence: '___ does your sister work? — At a hotel.',
          sentenceJa: 'お姉さんはどこで働いていますか。— ホテルです。',
          choices: ['What', 'Where', 'When', 'Who'],
          correctIndex: 1,
          explanation: '答えが At a hotel(場所)なので、場所を尋ねる where を使います。',
          choiceNotes: ['what への答えは「何」にあたる内容になるはずです。', null, 'when への答えは時を表す内容になるはずです。', 'who への答えは人になるはずです。'],
          audioEn: 'Where does your sister work?',
        },
        {
          id: 'u06-l1-q2',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「彼は何が欲しいのですか」と尋ねたいとき。',
          choices: ['What does he want?', 'What he wants?', 'What does he wants?', 'Does he want what?'],
          correctIndex: 0,
          explanation: 'Wh語のあとは疑問文の語順(does + 主語 + 動詞の原形)です。does が三単現を引き受けるので動詞は原形 want に戻します。',
          choiceNotes: [null, '一般動詞の疑問文には does が必要です。', 'does のあとの動詞は原形に戻します。wants は使えません。', 'Wh語は文頭に置きます。'],
          audioEn: 'What does he want?',
        },
        {
          id: 'u06-l1-q3',
          prompt: '空所に入るWh語を選んでください。',
          sentence: '___ are you late? — Because I missed the bus.',
          sentenceJa: 'なぜ遅れたのですか。— バスに乗り遅れたからです。',
          choices: ['What', 'Why', 'When', 'How'],
          correctIndex: 1,
          explanation: 'Because(〜だから)で理由を答えているので、理由を尋ねる why が入ります。',
          choiceNotes: ['what は「何」を尋ねる語で、because の答えとかみ合いません。', null, 'when は「いつ」を尋ねる語です。', 'how は「どのように」を尋ねる語で、理由の答えとは合いません。'],
          audioEn: 'Why are you late?',
        },
        {
          id: 'u06-l1-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「あなたの誕生日はいつですか」と尋ねたいとき。',
          choices: ['When is your birthday?', 'When does your birthday?', 'When your birthday is?', 'Does your birthday when?'],
          correctIndex: 0,
          explanation: 'birthday は名詞で動作を表す動詞がないので、be動詞の文です。「When + be動詞 + 主語」の語順にします。',
          choiceNotes: [null, 'does を使うなら一般動詞が必要ですが、この文に動詞がありません。be動詞の文には do / does を使いません。', 'Wh語のあとは be動詞を主語の前に出します。', 'Wh語は文頭に置き、be動詞の文に does は使いません。'],
          audioEn: 'When is your birthday?',
        },
      ],
      summary: [
        'Wh疑問文は「Wh語 + 疑問文の語順」。一般動詞なら do / does / did、be動詞なら be動詞を主語の前に。',
        'what(何)/ where(どこ)/ when(いつ)/ why(なぜ)/ who(誰)/ how(どのように)。',
        'Wh疑問文には Yes / No ではなく具体的な情報で答える。why には because で答えるのが定番。',
      ],
    },
    {
      id: 'u06-l2',
      unitId: 'u06',
      level: 'A2',
      title: 'How + 形容詞/副詞',
      objective: 'How long / How often / How far / How much などを使って、「どのくらい〜か」と程度や量を具体的に尋ねられるようになります。',
      minutes: 10,
      prereqs: ['u06-l1'],
      blocks: [
        {
          type: 'explanation',
          title: 'How は「どのくらい」をはかる物差し',
          body:
            'how は単独では「どのように」ですが、**how + 形容詞・副詞** の形にすると「どのくらい〜か」と程度を尋ねる表現になります。\n\n- long(長い)→ **How long** ...?(どのくらいの長さ・期間?)\n- old(古い・年をとった)→ **How old** ...?(何歳? どのくらい古い?)\n\n後ろに付ける形容詞・副詞を変えるだけで、時間・距離・頻度・値段など、さまざまな「どのくらい」を尋ねられる便利な仕組みです。',
        },
        {
          type: 'table',
          title: 'よく使う How + 形容詞/副詞',
          headers: ['表現', '尋ねること', '例'],
          rows: [
            ['How long', '時間・期間の長さ', 'How long is the movie?'],
            ['How often', '頻度', 'How often do you exercise?'],
            ['How far', '距離', 'How far is the station?'],
            ['How old', '年齢・古さ', 'How old is this building?'],
            ['How much', '値段・量(数えられない)', 'How much is this shirt?'],
            ['How many', '数(数えられる)', 'How many brothers do you have?'],
          ],
        },
        {
          type: 'contrast',
          title: 'How much vs How many',
          left: {
            label: 'How much: 数えられないもの・値段',
            items: [
              { en: 'How much water do you drink every day?', ja: '毎日どのくらい水を飲みますか。', highlight: 'How much water' },
              { en: 'How much is this bag?', ja: 'このかばんはいくらですか。', highlight: 'How much', note: '値段を聞く How much is ...? は買い物の決まり文句です。' },
            ],
            pointJa: '不可算名詞と値段に使う',
          },
          right: {
            label: 'How many: 数えられるもの',
            items: [
              { en: 'How many eggs do we need?', ja: '卵はいくつ必要ですか。', highlight: 'How many eggs' },
              { en: 'How many people did you invite?', ja: '何人招待したのですか。', highlight: 'How many people' },
            ],
            pointJa: '可算名詞の複数形と使う',
          },
          note: 'much / many の使い分け(U03)がそのまま How much / How many に引き継がれます。many のあとの名詞は複数形にします。',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'How long does it take to get to the airport?', ja: '空港までどのくらい時間がかかりますか。', highlight: 'How long', note: '所要時間は How long does it take ...? で尋ねます。' },
            { en: 'How often do you eat out?', ja: 'どのくらいの頻度で外食しますか。', highlight: 'How often', note: '答え方は Once a week. / Twice a month. など(U05の頻度の副詞も使えます)。' },
            { en: 'How far is it from here to the beach?', ja: 'ここからビーチまでどのくらいの距離ですか。', highlight: 'How far', note: '距離を尋ねる文の主語には it を使います。' },
            { en: 'How old is your dog?', ja: 'あなたの犬は何歳ですか。', highlight: 'How old' },
            { en: 'How many languages does he speak?', ja: '彼は何か国語を話しますか。', highlight: 'How many' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u06-l2-q1',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___ do you go to the gym? — Three times a week.',
          sentenceJa: 'どのくらいの頻度でジムに行きますか。— 週に3回です。',
          choices: ['How long', 'How often', 'How far', 'How many'],
          correctIndex: 1,
          explanation: '答えが Three times a week(週3回)という頻度なので、頻度を尋ねる How often を使います。',
          choiceNotes: ['How long は時間の長さを尋ねます。答えは For an hour. のようになるはずです。', null, 'How far は距離を尋ねます。', 'How many は後ろに数えられる名詞が必要です。'],
          audioEn: 'How often do you go to the gym?',
        },
        {
          id: 'u06-l2-q2',
          prompt: '空所に入る表現を選んでください。',
          sentence: '___ is it from your house to the office?',
          sentenceJa: '家からオフィスまでどのくらいの距離ですか。',
          choices: ['How far', 'How long', 'How much', 'How old'],
          correctIndex: 0,
          explanation: '「どのくらいの距離か」を尋ねるのは How far です。from A to B(AからBまで)と相性の良い表現です。',
          choiceNotes: [null, 'How long は時間・期間の長さに使います。距離には How far です。', 'How much は量や値段に使います。', 'How old は年齢や古さに使います。'],
          audioEn: 'How far is it from your house to the office?',
        },
        {
          id: 'u06-l2-q3',
          prompt: '空所に入る語を選んでください。',
          sentence: 'How ___ chairs do we need for the meeting?',
          sentenceJa: '会議には椅子がいくつ必要ですか。',
          choices: ['much', 'many', 'often', 'long'],
          correctIndex: 1,
          explanation: 'chairs は数えられる名詞の複数形なので、数を尋ねる How many を使います。',
          choiceNotes: ['much は数えられない名詞に使います。chairs は数えられます。', null, 'often は頻度を尋ねる語で、名詞の前には置けません。', 'long は長さを尋ねる語で、名詞の前には置けません。'],
          audioEn: 'How many chairs do we need for the meeting?',
        },
        {
          id: 'u06-l2-q4',
          prompt: '正しい文を選んでください。',
          sentenceJa: '店で「この腕時計はいくらですか」と尋ねたいとき。',
          choices: ['How much is this watch?', 'How many is this watch?', 'How much this watch is?', 'How much does this watch?'],
          correctIndex: 0,
          explanation: '値段を尋ねるときは How much is ...? という形を使います。',
          choiceNotes: [null, '値段は「量」の仲間なので many ではなく much を使います。', 'How much のあとは疑問文の語順(is + 主語)にします。', 'does のあとに動詞がなく、文が成り立っていません。'],
          audioEn: 'How much is this watch?',
        },
      ],
      summary: [
        'How + 形容詞/副詞 で「どのくらい〜か」と程度を尋ねられる。',
        'How long(期間)/ How often(頻度)/ How far(距離)/ How old(年齢)を使い分ける。',
        '数えられないもの・値段は How much、数えられるものは How many + 複数形。',
        '所要時間は How long does it take ...?、値段は How much is ...? が定番の形。',
      ],
    },
    {
      id: 'u06-l3',
      unitId: 'u06',
      level: 'A2',
      title: '主語を尋ねる疑問文',
      objective: '「誰が〜したの?」のように主語を尋ねる疑問文を、do / does / did を使わずに正しく作れるようになります。',
      minutes: 10,
      prereqs: ['u06-l2'],
      blocks: [
        {
          type: 'explanation',
          title: '知りたいのが主語なら、主語をそのまま置き換える',
          body:
            'これまでのWh疑問文は、目的語や場所など「主語以外」を尋ねるもので、do / does / did が必要でした。しかし**主語そのものを知りたいとき**は作り方がまったく違います。\n\n- Ken called you.(ケンがあなたに電話した)\n- → **Who** called you?(誰があなたに電話したの?)\n\n主語 Ken の位置に Who を置くだけ。**語順はそのまま、do / does / did も使いません**。「?」の部分に答えをはめ込むだけで返事になる、シンプルな形です。',
        },
        {
          type: 'structure',
          title: '主語を尋ねる疑問文の語順',
          parts: [
            { label: '疑問詞(=主語)', text: 'Who' },
            { label: '動詞', text: 'called' },
            { label: '目的語', text: 'you' },
          ],
          caption: 'もとの文と同じ語順のまま、主語だけを Who に置き換えます。did は使いません。',
        },
        {
          type: 'contrast',
          title: '主語を尋ねる vs 目的語を尋ねる',
          left: {
            label: '主語を尋ねる(do 不要)',
            items: [
              { en: 'Who called you?', ja: '誰があなたに電話したのですか。', highlight: 'Who called' },
              { en: 'What happened last night?', ja: '昨夜、何が起きたのですか。', highlight: 'What happened' },
            ],
            pointJa: '疑問詞が主語。もとの文と同じ語順のまま',
          },
          right: {
            label: '目的語を尋ねる(do が必要)',
            items: [
              { en: 'Who did you call?', ja: 'あなたは誰に電話したのですか。', highlight: 'did you call' },
              { en: 'What did you do last night?', ja: '昨夜、何をしたのですか。', highlight: 'did you do' },
            ],
            pointJa: '疑問詞は目的語。did + 主語 + 動詞の原形',
          },
          note: '日本語で見分けられます。「誰**が**した?」なら主語を尋ねる形(do 不要)、「誰**に・を**した?」なら目的語を尋ねる形(do が必要)です。',
        },
        {
          type: 'explanation',
          title: '疑問詞の主語は3人称単数扱い',
          body:
            'Who / What が主語のときは、答えが複数かもしれなくても、**he / she / it と同じ3人称単数扱い**にします。現在形なら動詞に -s が付きます。\n\n- Who **lives** in this house?(答えが複数人でも lives)\n- What **makes** you happy?\n\n答えるときは、do / does / did で短く受けられます。\n\n- Who made this cake? — Ken **did**.\n- Who wants coffee? — I **do**.',
        },
        {
          type: 'examples',
          title: '例文',
          items: [
            { en: 'Who made this cake?', ja: '誰がこのケーキを作ったのですか。', highlight: 'Who made' },
            { en: 'Who wants some ice cream?', ja: 'アイスクリームが欲しい人は誰ですか。', highlight: 'wants', note: '現在形なので動詞に -s が付きます。' },
            { en: 'What happened to your leg?', ja: '脚をどうしたのですか(脚に何が起きたのですか)。', highlight: 'happened' },
            { en: 'Who teaches you English?', ja: '誰があなたに英語を教えているのですか。', highlight: 'Who teaches', note: '答えは Ms. Green does. のように does で受けます。' },
            { en: 'Which bus goes to the airport?', ja: 'どのバスが空港へ行きますか。', highlight: 'goes', note: 'which + 名詞 が主語になることもあります。' },
          ],
        },
      ],
      quiz: [
        {
          id: 'u06-l3-q1',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「誰がこの窓を割ったのですか」と尋ねたいとき。',
          choices: ['Who did break this window?', 'Who broke this window?', 'Who did this window break?', 'Did who break this window?'],
          correctIndex: 1,
          explanation: '「誰が」と主語を尋ねているので、主語の位置に Who を置き、語順はそのまま。did は使いません。',
          choiceNotes: ['主語を尋ねる疑問文に did は使いません。動詞を過去形のまま使います。', null, 'この語順では「この窓が何かを割った」ことを尋ねる形になってしまい、意味が通りません。', '疑問詞は文頭に置きます。'],
          audioEn: 'Who broke this window?',
        },
        {
          id: 'u06-l3-q2',
          prompt: '英文の意味として正しいものを選んでください。',
          sentence: 'Who did Emi invite?',
          choices: ['誰がエミを招待したのですか。', 'エミは誰を招待したのですか。', 'エミと誰が招待されたのですか。', '誰かがエミを招待したのですか。'],
          correctIndex: 1,
          explanation: 'did があるので、これは目的語を尋ねる形です。主語は Emi で、Who は「招待された相手」。「誰がエミを招待したか」を尋ねるなら Who invited Emi? になります。',
          choiceNotes: ['「誰が招待した?」なら did を使わず Who invited Emi? となります。', null, '「誰と誰が」という意味はこの文にはありません。', '「誰かが〜したのか」と尋ねるなら Did someone invite Emi? となります。'],
          audioEn: 'Who did Emi invite?',
        },
        {
          id: 'u06-l3-q3',
          prompt: '空所に入る形を選んでください。',
          sentence: 'Who ___ in that big house?',
          sentenceJa: 'あの大きな家には誰が住んでいるのですか。',
          choices: ['live', 'lives', 'living', 'does live'],
          correctIndex: 1,
          explanation: '疑問詞が主語のときは3人称単数扱いなので、現在形の動詞に -s を付けて lives にします。',
          choiceNotes: ['疑問詞の主語は3人称単数扱いなので、原形の live は使えません。', null, 'living だけでは動詞になりません。', '主語を尋ねる疑問文に does は使いません。'],
          audioEn: 'Who lives in that big house?',
        },
        {
          id: 'u06-l3-q4',
          prompt: '正しい疑問文を選んでください。',
          sentenceJa: '「何が起きたのですか」と尋ねたいとき。',
          choices: ['What did happen?', 'What happened?', 'What did it happen?', 'What was happen?'],
          correctIndex: 1,
          explanation: 'What が主語なので、did を使わず動詞を過去形にして What happened? とします。',
          choiceNotes: ['主語を尋ねる疑問文に did は使いません。', null, 'What が主語なので、別の主語 it を入れることはできません。', 'be動詞と動詞の原形は並べられません。'],
          audioEn: 'What happened?',
        },
      ],
      summary: [
        '主語を尋ねるときは、主語の位置に Who / What を置くだけ。もとの文と同じ語順で、do / does / did は使わない。',
        '「誰が した?」なら主語を尋ねる形、「誰に・何を した?」なら do / does / did を使う形。',
        '疑問詞の主語は3人称単数扱い。現在形では動詞に -s(Who lives ...?)。',
        '答えは Ken did. / I do. のように do / does / did で短く受けられる。',
      ],
    },
  ],
}
